- src/app/modules/main/module.nim
- src/app/modules/main/profile_section/contacts/controller.nim
- src/app/modules/main/profile_section/contacts/io_interface.nim
- src/app/modules/main/profile_section/contacts/module.nim
- src/app/modules/main/profile_section/contacts/view.nim
- src/app/modules/shared_models/user_model.nim
- src/app_service/service/contacts/dto/contacts.nim
- src/app_service/service/contacts/service.nim
- storybook/pages/ProfileDialogViewPage.qml
- ui/app/AppLayouts/Chat/views/ChatColumnView.qml
- ui/app/AppLayouts/Chat/views/ChatContentView.qml
- ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
- ui/app/AppLayouts/Profile/stores/ContactsStore.qml
- ui/app/mainui/activitycenter/stores/ActivityCenterStore.qml
- ui/app/mainui/activitycenter/views/ActivityNotificationContactRequest.qml
- ui/imports/shared/views/ProfileDialogView.qml
- ui/imports/utils/Constants.qml
Close #10268
Close #9935
Waits https://github.com/status-im/status-desktop/pull/9871
Contacts, Profile, Chat
https://user-images.githubusercontent.com/2522130/233578352-7e8b0070-a758-4dd5-9c54-466381393bd3.mov
> Feat(Contacts): Fixes contact removal side effects

- src/app/modules/main/chat_section/controller.nim
- src/app/modules/main/chat_section/module.nim
- src/app/modules/main/controller.nim
- src/app/modules/main/module.nim
- src/app/modules/shared_models/section_item.nim
- src/app_service/service/chat/async_tasks.nim
- src/app_service/service/chat/service.nim
- src/app_service/service/community/service.nim
- src/backend/chat.nim
Fixes https://github.com/status-im/status-desktop/issues/10076
Reverts the refactor that makes getChannelGroups (ie getChats) not return chats (now it does return all chats too).
That way, we actually have the right mentions and unread count when receiving new messages
Also fixes an issue where mentions and unread count would get reset to 0 when getting a community update, because the signal doesn't have enough info
status-go PR https://github.com/status-im/status-go/pull/3439
> Fix Badge reseting

- ui/app/AppLayouts/Wallet/views/AssetsDetailView.qml
zero (0) is a valid change value here, it's a "stable" coin
Fixes displaying invalid "Dummy" values
AssetDetailView
Before:
After fix:
> fix(AssetsDetailView): don't display "Dummy" for zero values

- storybook/pages/DerivationPathInputPage.qml
- ui/app/AppLayouts/Wallet/addaccount/panels/DerivationPathInput.qml
- ui/app/AppLayouts/Wallet/addaccount/panels/DerivationPathInput/Controller.qml
Updates #10479
The warning for not being supported account index bigger than `99` make sense only for standard derivation paths we support. Therefore, remove the warning in case of derivation path
The change adds a test case to story book for investigating issue #10479. However, the control seems to work well with reflected values.
> fix(wallet) don't show too big account index for custom path

- ui/imports/shared/views/HistoryView.qml
Closes #10432
Updated section delegate to new height and added divider line according to design
Wallet activity list section delegate.
**Design:**
**App:**
> feat(@desktop/activity): Updated section delegate

- src/app_service/service/settings/dto/settings.nim
- src/app_service/service/settings/service.nim
There are a bunch of notification related settings that cause RPC calls when read from the UI in QML/Qt.
This is bad because whenever the view tries to read a notification setting it causes an RPC call and then rerenders the view. This happens pretty much every time a new signal arrives in the client.
To account for that we now fetch all notification settings once and mark the service as initialized so it know when to simply return cached values. The cache is updated when the notification settings change.
Fixes #10493
> fix: ensure notification settings are cached from RPC

- src/app/modules/main/chat_section/module.nim
- src/app_service/service/community/service.nim
was deleted
This is needed because there's cases where the deletion of a permission might cause the current user to no longer be eligible to join a community.
Community has the follwoing permissions:
- own 2 ETH and 1 FOO_NFT or
- own 1 FOO_NFT
User owns: 1 FOO_NFT
^ The above would make the user eligible to request access to join.
Now if the community removes the second permission, the user now no longer fulfills the requirements so we need to ensure the UI permits the user to request access.
Rebuilding the permissions model (including its token criteria) sets the necessary flags in the UI automatically.
> fix(permissions): ensure permissions model is rebuilt when permission

- ui/app/AppLayouts/Profile/ProfileLayout.qml
- ui/app/AppLayouts/Profile/views/AdvancedView.qml
- ui/app/AppLayouts/Profile/views/MessagingView.qml
Closes #9687
Settings moved Waku nodes to advanced settings menu
Settings
https://user-images.githubusercontent.com/31625338/234631169-260931ec-b6bc-4eaf-b047-d75a788b1158.mov
> (settings): moved waku nodes option to advanced

- ci/Dockerfile
- ci/Jenkinsfile.linux
- ci/Jenkinsfile.macos
- scripts/macos_build_setup.sh
- scripts/ubuntu_build_setup.sh
- scripts/windows_build_setup.ps1
Release notes: https://go.dev/doc/devel/release#go1.20
This is supposed to fix crashes on M1 Macs:
- https://github.com/status-im/status-desktop/issues/10548
- https://github.com/status-im/status-desktop/pull/10442
Specifically this commit:
- https://github.com/golang/go/commit/c00e9285eae4599f6a123d0a355633379be998e8 - runtime: save frame pointer to the stack in signal handlers for arm64
> ci: upgrade from Go 1.19.5 to 1.20.4

- ui/app/AppLayouts/Chat/ChatLayout.qml
- ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
Fixes: #9913
Remove legacy community popup call from settings.
PS: Don't know the popup should be removed as well cos it used in another place.  
Community Settings
> chore(CommunitySettings): Remove old legacy community popup

- ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
I missed an `id` when old legacy popup was removed [there](https://github.com/status-im/status-desktop/pull/9964)
Fix community settings view
CommunitySsettingsView
> fix(CommunitySettingsView): Fix community settings after removing old legacy popup ref

- src/app/modules/main/chat_section/module.nim
- ui/StatusQ/src/StatusQ/Components/StatusMessage.qml
- ui/app/AppLayouts/Chat/stores/RootStore.qml
- ui/app/AppLayouts/Chat/views/ChatContentView.qml
- ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
- ui/app/AppLayouts/Profile/views/EnsListView.qml
- ui/imports/shared/views/chat/MessageView.qml
Closing #10183 
1. Disable the group chat when the user is kicked
Here we need to detect the kick happens and update the UI accordingly. To do this I've used the same `amIMember` boolean from `chatCommunitySectionModule` that it is used for communities. This boolean is updated from 2 additional flows: When the chat becomes active; When the chat is added or updated.
2. Move 1to1 chat disabling logic to RootStore and extend it with the group chat logic
Message history
Group chat
1to1 chat
Group chats:
https://user-images.githubusercontent.com/47811206/236434822-1665afb6-b4f8-4543-87c5-7e9d3b5ef881.mov
1to1 chats:
https://user-images.githubusercontent.com/47811206/236434876-5994bf3f-49bd-4dda-b65a-427a069aa400.mov
> fix(blockChat): Disable chat input when minimal conditions are not met

- src/app/modules/main/communities/controller.nim
- src/app/modules/main/communities/io_interface.nim
- src/app/modules/main/communities/module.nim
- src/app/modules/main/communities/view.nim
- src/app_service/service/community/service.nim
- src/backend/communities.nim
- ui/app/AppLayouts/Chat/controls/community/CommunityOptions.qml
- ui/app/AppLayouts/Chat/panels/communities/CommunityOverviewSettingsPanel.qml
- ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
- ui/app/AppLayouts/CommunitiesPortal/popups/CreateCommunityPopup.qml
- ui/app/AppLayouts/CommunitiesPortal/stores/CommunitiesStore.qml
Create/edit encrypted community option removed
The community will be encrypted automatically if the community will be closed and decrypted if it became open
Fixed bug, when edition community description changed encryption
Closes: #9942
Status-go PR: https://github.com/status-im/status-go/pull/3455
Community encryption
Status-go PR https://github.com/status-im/status-go/pull/3455
> feat(@desktop/communities): automatically encrypt closed communities

- ui/app/AppLayouts/Chat/panels/communities/TokenHoldersPanel.qml
Closes #10258
TokenHoldersPanel: increased token holders combo width
TokenHoldersPanel
> [communities]: increased token holders combo width

- ui/imports/shared/views/ProfileDialogView.qml
Closes #10499
ProfileDialogView: updated remove contact popup
> [contacts]: updated remove contact popup

- ui/imports/shared/views/HistoryView.qml
fixes #10472
I found out glitch visible after my implementation of new activity section delegate.
How to reproduce:
* Have wallet with activity across multiple days (there must be few sections)
* Go to different wallet activity list (must be long enough to scroll whole screen), scroll down and scroll up
* Now at the top 2 sections can be visible
Activity list
> fix(@desktop/activity): Fixed section glitch

- ui/app/AppLayouts/Chat/popups/community/CreateChannelPopup.qml
Closes #9839
Communities: fixed add/edit channels community right emoji button should open emoji popup
communities
https://user-images.githubusercontent.com/31625338/236861839-f395008d-359b-4f39-87df-bbcef26c0b4b.mov
> (community): fixed add/edit channels community right emoji button

- ui/imports/shared/controls/AmountInput.qml
Fixes #10413
Components using `AmountInput`(currently only `TokenPanel`) did not allow entering decimal numbers if the system had a locale configured which used comma as decimal separator. This apparently only affected macOS.
It seems to be related to some bug in the base QML `DoubleValidator` component which takes some locale parameters from the system config instead of the one passed through the corresponding property. Anyway, passing only the locale part (`en`) instead of the full locale_country string ( `en_US`) seems to do the trick.
https://user-images.githubusercontent.com/11161531/236901665-e1122b16-00c0-4d3e-afb6-ac3f1c4e2e42.mov
IMO a "definitive" solution to this locale thing would be using the same locale for displaying and for user input, and give the user a setting where …
> fix(@desktop): Fix decimal input for components using AmountInput

- ui/app/AppLayouts/Chat/panels/communities/CommunityMintTokensSettingsPanel.qml
- ui/app/AppLayouts/Chat/panels/communities/MintTokensFooterPanel.qml
Closes #10579
Added property binded with model info and with needed footer visible property option.
https://user-images.githubusercontent.com/97019400/237017076-57ffea66-204b-4cd3-b210-cc3a5d8720c9.mov
> feat(MintToken):  Remote self-destruct footer option hidden if the minted collectible doesn't have self-destruct property set

- storybook/PagesModel.qml
- storybook/pages/CommunityMintTokensSettingsPanelPage.qml
- storybook/pages/StatusImageCropPanelPage.qml
- ui/app/AppLayouts/Chat/controls/community/CommunityBannerPicker.qml
- ui/app/AppLayouts/Chat/panels/communities/CommunityMintTokensSettingsPanel.qml
- ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityCollectibleView.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityNewCollectibleView.qml
- ui/imports/shared/panels/EditCroppedImagePanel.qml
- ui/imports/shared/panels/NoImageUploadedPanel.qml
- ui/imports/shared/stores/CommunityTokensStore.qml
UI part of [#10317](https://github.com/status-im/status-desktop/issues/10317)
- Added `StatusImageCropPanel` into `storybook`.
- Added **cropping tool** into the mint token workflow.
- Extended `EditCroppedImagePanel` to be able to drag/drop images.
**NOTE:** Only UI part done. 
- _UI --> backend_: UI will pass a `json` file with the crop image details and backend will be in charge of cropping it and store it accordingly. 
- _Backend --> UI_: Expected artwork image read from backend: Image already cropped.
- Mint token workflow with cropping tool:
https://user-images.githubusercontent.com/97019400/236849439-df3d94ae-3a58-4012-8b8c-9554321f7e84.mov
- Storybook new page (exported from `sandbox`):
https://user-images.githubusercontent.com/97019400/236847109-016f9c04-5d9b-4978-b683-932553e6a6b …
> feat(MintTokens): Artwork image field missing cropping tool

- src/app_service/service/community/async_tasks.nim
- src/app_service/service/community/service.nim
Fixes #10500
* Catch `RequestCommunityInfo` exceptions
* Avoid request duplications
* Remove redundant try/except in `requestCommunityInfo`
* Fix getting `communityId` in  `getFilteredJoinedCommunities`
> fix(communties): Catch `RequestCommunityInfo`exceptions. Avoid request duplications.

- src/app/modules/main/profile_section/advanced/controller.nim
- src/app/modules/main/profile_section/advanced/io_interface.nim
- src/app/modules/main/profile_section/advanced/module.nim
- src/app/modules/main/profile_section/advanced/view.nim
- src/app_service/common/network_constants.nim
- src/app_service/service/node_configuration/service.nim
- ui/app/AppLayouts/Profile/stores/AdvancedStore.qml
- ui/app/AppLayouts/Profile/views/AdvancedView.qml
Fixes #3610
status-go PR: https://github.com/status-im/status-go/pull/3465
Commit 1 fixes status-go to not accept a MaxBackups of 0, because the lib we use is dumb and when it's set to 0, it actually keeps them ALL
Commit 2 adds a setting in Advanced Settings to modify the number of archived logs to keep. Between 1 and 100
Edit: I just realized that we also have the Nim logs being saved in `Status/logs`. We probably want to fix that too, but they are way lighter. However, chronicles, the lib we use for logging,  is not as smart as lumberjack, the one in go. So it doesn't have a rotation mechanism.
Do we want to make it so we just keep one file. That would be easy. We just need to rename the file path to a set one, so we just always overwrite it with each new run.
If we want the setting …
> Stop archiving all log files + add setting to change how may to keep

- src/app/boot/app_controller.nim
- src/app/modules/main/profile_section/privacy/controller.nim
- src/app/modules/main/profile_section/privacy/module.nim
- src/app/modules/shared_modules/keycard_popup/controller.nim
- src/app/modules/startup/controller.nim
- src/constants.nim
Fixes: #10424
All case from issue isn't reproduced. This PR change usage of `DisplayName` to `KeyUid` as a key for `keychain`
Biometrics
> fix(biometrics): Change keychain keys from DisplayName to KeyUid

- storybook/PagesModel.qml
- storybook/pages/PopupSizingPage.qml
- ui/StatusQ/src/StatusQ/Controls/StatusDropdown.qml
- ui/app/AppLayouts/Chat/controls/community/MembersDropdown.qml
- Adds `PopupSizing` page to storybook clarifying issues related to popup's height calculation and positioning
- Added workaround for https://bugreports.qt.io/browse/QTBUG-87804 to `StatusDropdown`
- `MembersDropdown` implementation simplified, no "manual" height calculation
Closes: https://github.com/status-im/status-desktop/issues/10661
`StatusDropdown`, `MembersDropdown`
> chore: `MembersDropdown` simplified, workaround for QTBUG-87804 added to `StatusDropdown`

- ui/StatusQ/src/StatusQ/Controls/StatusDropdown.qml
Follow up to https://github.com/status-im/status-desktop/pull/10664 because of https://github.com/status-im/status-desktop/pull/10664#issuecomment-1545890322
`StatusDropdown`
> fix(StatusDropdown):  added to Binding to avoid warning (QTBUG-81787)

- ui/imports/shared/views/chat/MessageView.qml
Fixes https://github.com/status-im/status-desktop/issues/10669
> fix(MessageView): Show correct name of who pinned the message

- ui/imports/shared/views/chat/MessageView.qml
Fixes https://github.com/status-im/status-desktop/issues/10689
> fix(MessageView): Show header when prev message is system PinnedMessage

- src/app/modules/main/chat_section/module.nim
Fixes: #10382
When user crates new channel it returns without `members` from status-go. But community admin can remove channel anyway so I add the check if user is community admin.
Community
> fix(Community): Fix community channel admin flag

- ui/app/AppLayouts/Wallet/addaccount/panels/DerivationPathInput/Controller.qml
on Linux does not support named groups
Fixed regex for derivation path
wallet->add new address -> custom derivation path
> fix(desktop/wallet): fixed regex for derivation path as Qt 5.15 regex

- ui/imports/shared/views/chat/MessageView.qml
Fixes: #10614
Blocks `jumpToMessage` for deleted and unknown messages
Reply messages
> fix(replies): Blocks `jumpToMessage` for deleted and unknown messages

- src/app_service/service/message/service.nim
Close #10522
Why do we need to remove this check here:
- There should be spam protection in status-go
- We need to receive CR messages in chat for non contacts
Chat
> fix(Chat): Allow receiving messages from non-contacts in 1-to-1

- ui/StatusQ/src/StatusQ/Components/private/statusMessage/StatusMessageReply.qml
Fixes https://github.com/status-im/status-desktop/issues/10716
1. Move main `MouseArea` behind sender's `MouseArea`
2. Implemented clicking on sender's name
https://github.com/status-im/status-desktop/assets/25482501/4e5939b2-016e-414d-a35e-8a9c272d3784
> fix(StatusMessageReply): Fix clicking on sender

- ui/imports/shared/stores/TransactionStore.qml
- ui/imports/shared/views/RecipientView.qml
fix(@desktop/wallet): Clicking "Send" button on saved address does not add it into recipient input on SendModal Fix/issue 10685
#10685 
Assigning the address from saved address was not handled properly fixed that.
Ens and Stickers also need to have token preselected, that was not working either so fixed that too
SendModal (From SavedAddreses, ENS and Stickers)
https://github.com/status-im/status-desktop/assets/60327365/5747c754-ae5a-416c-a04d-5d205264f075
> fix(@desktop/wallet): Clicking "Send" button on saved address does not add it into recipient input on SendModal Fix/issue 10685

- ui/StatusQ/sandbox/controls/Icons.qml
- ui/StatusQ/sandbox/controls/ListItems.qml
- ui/StatusQ/sandbox/demoapp/data/Models.qml
- ui/StatusQ/sandbox/main.qml
- ui/StatusQ/sandbox/pages/StatusScrollViewPage.qml
- ui/StatusQ/sandbox/pages/StatusTextAreaPage.qml
- ui/StatusQ/src/StatusQ/Components/StatusListItem.qml
- ui/StatusQ/src/StatusQ/Controls/StatusScrollBar.qml
- ui/StatusQ/src/StatusQ/Controls/StatusTextArea.qml
- ui/StatusQ/src/StatusQ/Core/StatusScrollView.qml
- ui/app/AppLayouts/Chat/panels/InlineSelectorPanel.qml
First step for https://github.com/status-im/status-desktop/issues/9864
This is a draft PR with main required changes.
If this one is ok, I will proceed further and fix all places where `StatusScrollView` is used.
- Inherit `StatusScrollView` from `ScrollView`.
- Much easier to set correct sizes `StatusScrollView`. And in a `Popup` too.
- `implicitWidth` and `implicitHeight` out of the box. 
- No binding loops
- No need to attach manually `TextArea` to a `Flickable`. Just wrap it around.
- No glitches.
- Use standard `padding` and `available` sizes.
- Vertical and horizontal `ScrollBar` don't overlap each other in bottom-right corner.
- Added `StatusScrollViewPage` showing the difference in using `ScrollView` and `Flickable` with various options.
cons:
- `StatusScrollView` can't be dragged …
> fix(StatusScrollView): Changed implementation to inherit `ScrollView`

- storybook/PagesModel.qml
- storybook/pages/StatusBlockProgressBarPage.qml
- storybook/pages/StatusTxProgressBarPage.qml
- ui/StatusQ/src/StatusQ/Controls/StatusBlockProgressBar.qml
- ui/StatusQ/src/StatusQ/Controls/StatusProgressBar.qml
- ui/StatusQ/src/StatusQ/Controls/qmldir
- ui/StatusQ/src/StatusQ/Core/Theme/StatusDarkTheme.qml
- ui/StatusQ/src/StatusQ/Core/Theme/StatusLightTheme.qml
- ui/StatusQ/src/StatusQ/Core/Theme/ThemePalette.qml
- ui/StatusQ/src/statusq.qrc
- ui/app/AppLayouts/Wallet/controls/StatusTxProgressBar.qml
- ui/app/AppLayouts/Wallet/controls/qmldir
- ui/app/AppLayouts/Wallet/panels/WalletTxProgressBlock.qml
- ui/app/AppLayouts/Wallet/panels/qmldir
- ui/app/AppLayouts/Wallet/views/TransactionDetailView.qml
- ui/imports/shared/controls/TransactionDelegate.qml
fixes #10639
Implements the new progress bar in transaction details view as per new design https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=12304-277076&t=pVuSeVdn0HAEilDp-4
1. StatusQ component StatusBlockProgressBar.qml
2. Wrote a StatusTxProgressBar.qml that handles progress on both mainnet and other chains
3. WalletTxProgressBlock.qml which handles the text along with the progress bar (this will need further work when multiTx data is ready)
TransactionDetailsView
**StatusBlockProgressBar:**
https://github.com/status-im/status-desktop/assets/60327365/cfc840a6-f6d0-4220-b35c-cad13ed3d33 …
> feat(@desktop/wallet): Activity Details Progress bar

- storybook/pages/CommunityCollectibleViewPage.qml
- storybook/src/Models/MintedCollectiblesModel.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityCollectibleView.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityMintedTokensView.qml
- ui/app/AppLayouts/Wallet/views/collectibles/CollectibleView.qml
Closes #10620
- It updates `CommunityCollectibleView` to display minting failure state.
- It updates `CommunityMintedTokensView` to display minting failure state.
- It exposes subtitle color property in `CollectibleView`.
- It updates `storybook` with more options to display minting failure state.
https://github.com/status-im/status-desktop/assets/97019400/c4cfe216-67b5-4733-b923-58586e053f6f
> feat(MintTokens): Add mint failure flow

- src/app/modules/main/wallet_section/accounts/model.nim
- src/app/modules/main/wallet_section/saved_addresses/model.nim
- storybook/PagesModel.qml
- storybook/main.cpp
- storybook/pages/TransactionAddressPage.qml
- storybook/pages/TransactionAddressTilePage.qml
- ui/StatusQ/src/StatusQ/Components/StatusListItem.qml
- ui/imports/shared/controls/TransactionAddress.qml
- ui/imports/shared/controls/TransactionAddressTile.qml
- ui/imports/shared/controls/TransactionDelegate.qml
- ui/imports/shared/controls/qmldir
closes #10583
Changes introduce new components to
* Format address in specific way - `TransactionAddress`
* Base Tile component in Transaction Activity Details view - `TransactionActivityTile`
* Tile displaying  list of transaction addresses  - `TransactionAddressTile`
Currently only `TransactionAddress` component was added to storybook.
Wallet - Transaction Activity Details
Design: 
https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=12689-341126&t=zqIHTe3GG0EC5YOp-4
**NOTE**  - data on example image is mocked
> feat(@desktop/wallet): Added transaction address component

- nim.cfg
- src/app/modules/main/wallet_section/activity/controller.nim
- src/app/modules/main/wallet_section/activity/entry.nim
- src/app/modules/main/wallet_section/activity/model.nim
- src/app/modules/main/wallet_section/controller.nim
- src/app/modules/main/wallet_section/module.nim
- src/app/modules/main/wallet_section/transactions/controller.nim
- src/app/modules/main/wallet_section/transactions/io_interface.nim
- src/app/modules/main/wallet_section/transactions/item.nim
- src/app/modules/main/wallet_section/transactions/module.nim
- src/app/modules/main/wallet_section/transactions/multi_transaction_item.nim
- src/app/modules/main/wallet_section/transactions/utils.nim
- src/app/modules/main/wallet_section/transactions/view.nim
- src/app/modules/main/wallet_section/view.nim
- src/app_service/service/transaction/dto.nim
- src/app_service/service/transaction/service.nim
- src/backend/activity.nim
- src/backend/backend.nim
- src/backend/transactions.nim
- ui/app/AppLayouts/Wallet/stores/RootStore.qml
- ui/app/AppLayouts/Wallet/views/RightTabView.qml
- ui/imports/shared/views/ActivityView.qml
- ui/imports/shared/views/qmldir
status-go corresponding PR [#3419](https://github.com/status-im/status-go/pull/3419)
Add the possibility of retrieving the data of wallet activity based on the given filter criteria.
Major changes:
- Bump status-go with the new equivalent API
- Add temporary developer tools
- Debugging ActivityView QML component to test filter and display the activity
- Add activity Nim package and synchronous controller and model
Considerations
- Have the model synchronous for the first iteration and then move to async while implementing the fetching mechanism
- Use QtObject instances in the model instead of roles over items as agreed with the team
- Simplify the implementation by having a simple presentation layer using backend (service also in the future)
- Small required fixes and improvements
Closes: …
> feat(Wallet): add activity API prototype

- src/app/modules/main/chat_section/controller.nim
- src/app/modules/main/communities/controller.nim
- src/app_service/service/community/async_tasks.nim
- src/app_service/service/community/service.nim
- ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
Fixes: #10719
- Makes request to join async
- Add `Loading...` everywhere when `Pending` state was used
Request to join community 
> feat(communities): Makes `requestToJoinCommunity` async

- src/app/modules/main/module.nim
- src/app_service/service/community/service.nim
Fixes: #10736
The problem was in the `Args()` sending when expected `CommunityMemberArgs` and wrong implementation interface of method. This PR fix the crash, but I still see an error from status-go `message: no opensea client` which means that membership request was not accepted.
Community permissions 
> fix(community-permissions): Fixed failed event sending and fix method declaration

- ui/app/AppLayouts/Wallet/popups/ReceiveModal.qml
- ui/app/AppLayouts/Wallet/popups/TransactionAddressMenu.qml
- ui/app/AppLayouts/Wallet/stores/RootStore.qml
- ui/app/AppLayouts/Wallet/views/TransactionDetailView.qml
closes #10619 
Added activity details address interactions.
Address menu handles contact address, contract address, tx hashes.
Current implementation isn't called anywhere yet. It will be handled in #10751
Also I fixed memory leak with ReceiveModal that was not detroyed.
* ReceiveModel - added readonly mode
Design:
https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=12468-289341&t=LCTiWwXIfaNqJ0H7-4
> feat(@desktop/wallet): Activity address interactions

- src/app/modules/main/activity_center/controller.nim
- src/app/modules/main/chat_section/controller.nim
- src/app_service/service/activity_center/service.nim
- src/app_service/service/chat/service.nim
While trying to find out why the badge resets, I ran into this error that was thrown from the AC because it didn't have the chats yet.
I fixed it by waiting for channels to be loaded before fetching the AC notifications.
The other commit is just some random clean up
> AC order fix and small cleanup

- storybook/PagesModel.qml
- storybook/figma.json
- storybook/pages/BurnTokensPopupPage.qml
- storybook/pages/SignTokenTransactionsPopupPage.qml
- ui/app/AppLayouts/Chat/panels/communities/CommunityMintTokensSettingsPanel.qml
- ui/app/AppLayouts/Chat/panels/communities/MintTokensFooterPanel.qml
- ui/app/AppLayouts/Chat/popups/community/BurnTokensPopup.qml
- ui/app/AppLayouts/Chat/popups/community/SignTokenTransactionsPopup.qml
- ui/app/AppLayouts/Chat/popups/community/qmldir
- ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
- ui/imports/shared/stores/CommunityTokensStore.qml
- ui/imports/utils/Constants.qml
Closes [#10050](https://github.com/status-im/status-desktop/issues/10050)
- It creates new `BurnTokensPopup` and adds it to `storybook`.
- It enables `burn` footer option and integrates `BurnTokensPopup` in mint tokens flow. It also integrates `SignTokenTransaction` in burn flow (added needed signals to interact with backend).
**NOTE**: Only UI. Backend need.
**APP:**
https://github.com/status-im/status-desktop/assets/97019400/75408a8d-cf7c-44b9-a502-57e97e867ba2
**STORYBOOK:**
https://github.com/status-im/status-desktop/assets/97019400/459e8d58-39ee-41a3-8a40-4b40dbbcd682
> feat(MintToken): Implement UI burn footer option

- src/app/modules/main/wallet_section/overview/item.nim
- src/app/modules/main/wallet_section/overview/module.nim
- src/app/modules/main/wallet_section/overview/view.nim
- ui/app/AppLayouts/Wallet/panels/WalletFooter.qml
fix(@desktop/wallet): Wallet Footer for watch only accounts should show only "Receive" as an option
fixes #10786
For watch only account only let Receive button on footer be visible as sending with watch only account is not possible
WalletFooter
https://github.com/status-im/status-desktop/assets/60327365/fbaf83b6-bbfe-4702-93c6-556c6c71d2c5
> fix(@desktop/wallet): Wallet Footer for watch only accounts should show only "Receive" as an option

- src/app/modules/main/communities/controller.nim
- src/app/modules/main/communities/io_interface.nim
- src/app/modules/main/communities/module.nim
- src/app/modules/main/communities/view.nim
- src/app_service/service/community/service.nim
- ui/app/AppLayouts/Chat/stores/RootStore.qml
- ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
- ui/imports/shared/views/chat/InvitationBubbleView.qml
- ui/imports/shared/views/chat/LinksMessageView.qml
Fixes: #10422
Displays loading state for invitation bubble and show notification about loading in progress
Invitation bubble
> fix(invitation-bubble): Adds loading state for unfurling links

- src/app/modules/main/chat_section/controller.nim
- src/app/modules/main/chat_section/io_interface.nim
- src/app/modules/main/chat_section/model.nim
- src/app/modules/main/chat_section/module.nim
- src/app/modules/main/chat_section/view.nim
- src/app_service/service/community/service.nim
- ui/StatusQ/src/StatusQ/Components/StatusChatList.qml
Fixes #10733
The category Drag and Drop code was already pretty much all there. It just needed to be hooked appropriately and to change the model code to adapt to the new sorted model. 
[cat-dnd.webm](https://github.com/status-im/status-desktop/assets/11926403/5026c8d6-0507-472a-bc4e-3c3b34f102b7)
edit: I added a new commit that improves the code for the chat reorder too by passing the new position and category directly
> feat(category): hook category Drag and Drop to backend correctly

- src/app_service/service/collectible/async_tasks.nim
- src/app_service/service/community_tokens/async_tasks.nim
- src/app_service/service/transaction/async_tasks.nim
Fixes #10771
For collectibles API calls from status-go, exceptions were properly handled but errors were not, causing a crash when OpenSea is not reachable for some reason. This was fixed in this PR in all places where that part of the backend is used..
> fix(@desktop/wallet): properly handle collectibles api call errors

- ui/app/AppLayouts/Onboarding/views/LoginView.qml
Adjust to the new error messages when opening the database with the DB pool
Fixes #10830
Onboarding/Password login
> fix: wrong error message on incorrect password

- test/ui-test/testSuites/suite_settings/tst_userIdentity/test.feature
App bug to be solved: #10827
Skips `suite_settings/tst_userIdentity/The user can change own display name in profile popup`
`e2e tests`
> test(tst_userIdentity): Skipped scenario `The user can change own display name in profile popup`

- src/app_service/common/network_constants.nim
Replace POKT URLs with archival ones. Should not see "connected to non-archival node" banner anymore when POKT is up.
wallet
> fix(desktop/wallet): use archival URLs for POKT

- test/ui-test/src/screens/StatusCommunityScreen.py
- test/ui-test/testSuites/suite_communities/tst_communityFlows/test.feature
- test/ui-test/testSuites/suite_communities/tst_communityManageCommunity/test.feature
1. moved community edition test to a feature file that covers actions that are allowed from Overview page of the community settings
2. added a todo to fix scrolling issue (perhaps Mac only but it is reproducible to me in 100% cases) https://github.com/status-im/desktop-qa-automation/issues/57
UI tests
> test(suite_communities): move a test to different feature file

- ui/StatusQ/src/StatusQ/Components/StatusImage.qml
- ui/StatusQ/src/StatusQ/Components/StatusRoundIcon.qml
- ui/app/AppLayouts/Wallet/controls/NetworkFilter.qml
Do not load a lowres image, breaks on hires displays. Also make sure we treat any SVG image the same way we do with icons, that is set the `sourceSize` to the required displayed size.
Fixes #9853
NetworkFilter combobox
> fix: blurry icons in Network Filter combobox

- src/app/modules/main/chat_section/chat_content/controller.nim
- src/app/modules/main/chat_section/chat_content/io_interface.nim
- src/app/modules/main/chat_section/chat_content/module.nim
- src/app/modules/main/chat_section/chat_content/view.nim
- src/app/modules/main/chat_section/controller.nim
- src/app/modules/main/chat_section/io_interface.nim
- src/app/modules/main/chat_section/module.nim
- src/app/modules/main/chat_section/view.nim
- src/app_service/service/chat/service.nim
- src/backend/chat.nim
- ui/StatusQ/src/StatusQ/Popups/StatusMenuItem.qml
- ui/app/AppLayouts/Chat/views/ChatContextMenuView.qml
- ui/app/AppLayouts/Chat/views/ChatHeaderContentView.qml
- ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
- ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
- ui/imports/shared/controls/chat/menuItems/MuteChatMenuItem.qml
- ui/imports/utils/Constants.qml
Part of: #9369
Adds mute type usage to chats and channels:
PS: I make decision to split this tasks cos it requires some changes in status-go for `Community` and `Category` parts.l
Muting chats and channels
> feat(mute): Adds intervals for muting channels and chats

- src/app/core/signals/remote_signals/pairing.nim
- src/app/modules/main/profile_section/devices/model.nim
- src/app_service/service/devices/service.nim
Fixes https://github.com/status-im/status-desktop/issues/10096
- Fixed `dataChanged` roles list, which can't be empty to simply update everything
- Fixed that `SetupSyncingPopup` wasn't showing the progress correctly when pairing twice in a row
- Added some logging
https://github.com/status-im/status-desktop/assets/25482501/38da24f6-6163-4ce1-b6d2-b7f80d18d74e
> fix: Fix pairing same devices

- src/app/modules/main/controller.nim
- src/app/modules/main/profile_section/module.nim
- src/app/modules/main/profile_section/privacy/controller.nim
- src/app/modules/main/profile_section/privacy/io_interface.nim
- src/app/modules/main/profile_section/privacy/module.nim
- src/app/modules/main/profile_section/profile/controller.nim
- src/app/modules/main/profile_section/profile/io_interface.nim
- src/app/modules/main/profile_section/profile/module.nim
- src/app/modules/main/profile_section/profile/view.nim
- src/app/modules/main/wallet_section/accounts/module.nim
- src/app/modules/main/wallet_section/io_interface.nim
- src/app/modules/main/wallet_section/module.nim
- src/app/modules/main/wallet_section/send/module.nim
- src/app/modules/main/wallet_section/view.nim
- src/app_service/service/privacy/service.nim
- src/app_service/service/profile/service.nim
- src/app_service/service/settings/service.nim
- src/app_service/service/wallet_account/service.nim
- src/backend/settings.nim
This PR handles items from the `settings` table on the desktop app side and this way aligns mobile and desktop app.
There are items which are marked as inactive on the status-go side and because of that they are excluded from syncing and backing up.
There is a table in the description of #10389 describing the state of handling synced&backed up settings' items.
The work is splitted in several commits that can be easier for review. Single commit handles single setting.
Fixes: #10389
> Support for synchronized & backed up settings

- src/app/core/custom_urls/urls_manager.nim
- src/app_service/service/community/service.nim
- src/app_service/service/message/async_tasks.nim
- src/constants.nim
- status.iss
- ui/StatusQ/sandbox/demoapp/DemoCommunityDetailModal.qml
- ui/StatusQ/src/StatusQ/Core/Utils/Utils.qml
- ui/app/AppLayouts/Chat/stores/RootStore.qml
- ui/app/mainui/AppMain.qml
- ui/imports/utils/Constants.qml
- ui/imports/utils/Utils.qml
Fixes https://github.com/status-im/status-desktop/issues/9549
Fixes https://github.com/status-im/status-desktop/issues/10777
Fixes https://github.com/status-im/status-desktop/issues/10748
Update the Windows installer to use status-app instead of status-im
Also updates the code that references the old deep link
Also updates the external links to use `https/status.app` instead of `join.status.com`
Also fixes an issue that would make the app crash if a profile url was pasted in chat
> Update deep link and external links to use the new format

- src/app/modules/main/chat_section/model.nim
- ui/StatusQ/src/StatusQ/Components/StatusChatList.qml
- ui/StatusQ/src/StatusQ/Components/StatusChatListAndCategories.qml
Reverts the work done to do the chat model sorting in Nim and instead goes back to an unordered list in Nim and using SortFilterProxy to do the ordering.
The reason is that doing the model resets was a big CPU hog.
Also, the reason why I did the sort in the Nim model is no longer there.
It used to be that I needed the model sorted to get the closest category, but I just pass the destination category from the QML instead (duh) (that was done in a previous PR when I added the category drag and drop).
**Possible drawback:**
We might get again the issue of the duplicated categories. We're not sure why or when that issue happens, but the possible suspect was SortFilterProxy.
I think that small bug is less important than the performance improvement that we gain from going back to using …
> Revert Chat model sorting in Nim and go back to SortFilterProxy because of performance issue

- ui/app/AppLayouts/Chat/views/MembersSelectorView.qml
- ui/app/mainui/Popups.qml
- ui/imports/utils/Global.qml
Fixes #9736
When pasting the chat key of a user to whom you already sent a request to, but for which they haven't answered yet, we open the popup instead of doing nothing. If you paste the chat key of a user you are not a contact at all and sent no request, it opens the contact request popup as before. Also, same as before, if you paste the key of a mutual contact, their name will show in the suggestion list.
[new-chat.webm](https://github.com/status-im/status-desktop/assets/11926403/f88cb998-f9b3-4deb-b4d8-6c3f81e595ff)
> feat(NewChat): open contact popup when pasting key of user in request

- ui/StatusQ/src/StatusQ/Controls/StatusPasswordInput.qml
- ui/imports/shared/controls/StyledTextField.qml
We have a beautiful cursor. Let's use it! 🙂
> fix: Use `StatusCursorDelegate` for password inputs

- src/app_service/service/contacts/service.nim
- ui/app/AppLayouts/Chat/stores/RootStore.qml
- ui/app/AppLayouts/Chat/views/ChatContentView.qml
- ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
Fixes #10501
status-go PR https://github.com/status-im/status-go/pull/3558
The problem was that didn't have access to the updated contact from status-go after banning or unbanning, so we just changed the banned property, but there is more that gets changed in the backend, like `removed` being set to `true` as well. With this fix, when you unban someone, you go back to a fresh start, as **non** contact, so you need to send a request again. That was the state you got if you restarted the app, so "re-sync" the state with status-go.
Another issue was on the frontend (QML). When banned,  and after restarting to get the right state, the unban button would be disabled and the Add contact request button would show, which is not good. We only want to send requests when unbanned. …
> fix(contacts): fix inconsistency when banning or unbanning contact

- ui/app/AppLayouts/Wallet/panels/WalletNftPreview.qml
- ui/app/AppLayouts/Wallet/panels/qmldir
- ui/app/AppLayouts/Wallet/views/TransactionDetailView.qml
closes #10822 
Added token preview in activity details view.
I didn't add it to storybook as it will be possible to test it through whole TransactionDetailsView page introduced in separate PR.
Activity details view
Design: 
https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=12381-274293&t=1CBx3T8BWjF9u2Lh-4
https://github.com/status-im/status-desktop/assets/11396062/25c38f83-cac9-4d63-8535-6fe67b310eb5
> feat(@desktop/wallet): Added NFT preview

- storybook/PagesModel.qml
- storybook/pages/AlertPopupPage.qml
- storybook/pages/CommunityMintTokensSettingsPanelPage.qml
- storybook/pages/CommunityMintedTokensViewPage.qml
- storybook/pages/CommunityNewTokenViewPage.qml
- storybook/pages/CommunityTokenViewPage.qml
- storybook/src/Models/MintedTokensModel.qml
- storybook/src/Models/qmldir
- test/ui-test/testSuites/suite_communities/shared/scripts/community_names.py
- ui/app/AppLayouts/Chat/layouts/SettingsPageLayout.qml
- ui/app/AppLayouts/Chat/panels/communities/CommunityAirdropsSettingsPanel.qml
- ui/app/AppLayouts/Chat/panels/communities/CommunityMintTokensSettingsPanel.qml
- ui/app/AppLayouts/Chat/panels/communities/CommunityPermissionsSettingsPanel.qml
- ui/app/AppLayouts/Chat/popups/community/AlertPopup.qml
- ui/app/AppLayouts/Chat/popups/community/qmldir
- ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityMintedTokensView.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityWelcomeSettingsView.qml
- ui/imports/shared/stores/CommunityTokensStore.qml
- ui/imports/utils/Constants.qml
Closes #10625 and #10765
- It adds assets list UI in minted tokens view.
- It adds flow to open token view depending on type (asset or collectible).
- It updates minting flow to use `contractUniqueKey` instead of `index`.
- It refactors `SettingsPageLayout`.
- It adds `retry mint` and `delete` options when deploy process fails.
- It renames `RemotelyDestructAlertPopup` to generic name `AlertPopup`.
- It updates `storybook` accordingly.
**NOTE:** Only UI. Assets backend management is not ready, neither delete or retry minting.
https://github.com/status-im/status-desktop/assets/97019400/a6409554-6517-46d1-8062-eb1a948a6595
https://github.com/status-im/status-desktop/assets/97019400/696a671a-3a69-4012-a06d-4f75e550dc49
> feat(Mint Assets): Update minted tokens view with assets

- Makefile
For some reason the an infra change has triggered the behavior of `make` where the `if` clauses that compares `QT5_PKGCONFIG_INSTALL_PREFIX` with `QT5_INSTALL_PREFIX` would be true, which would cause `QT5_LIBDIR` to not be exported, and some `NIM_PARAMS` to not be set at all.
Resolves:
* https://github.com/status-im/status-desktop/issues/10876
> makefile: fix MacOS builds, restore missing env vars

- Makefile
Enable -O3 when compiling status-go for Release builds.
Testing the external c libs we're using in status-go with the following code revealed that the code is not optimised when compiling Release builds:
```
#ifdef __OPTIMIZE__
#pragma message "!!!!!!!Optimizing!!!!!!!"
#endif
#ifdef __OPTIMIZE_SIZE__
#pragma message "!!!!!!!Optimizing for size!!!!!!!"
#endif
#ifdef __NO_INLINE__
#pragma message "!!!!!!!Disabling inlining!!!!!!!"
#endif
//Expected output: !!!!!!!Optimizing!!!!!!!
//Actual output: !!!!!!!Disabling inlining!!!!!!!
```
The login time and overall app experience seems better with -O3
status-go, status-keycard-go build configuration on Release
> chore(enableStatusGoOptimizations): Optimise Release build with O3 CFLAG

- ui/app/AppLayouts/Wallet/views/LeftTabView.qml
A small regression from porting StatusModal to StatusDialog
Fixes #10913
Fixes Add/Remove wallet account modals
Add:
Remove:
> fix: add/remove account modal positioning is wrong

- ui/imports/shared/popups/keycard/KeycardPopup.qml
- ui/imports/shared/popups/keycard/states/EnterPassword.qml
- do no let text/input overflow our overall width
- set the scrollview horizontal padding to 0, the content item has its own margins already
Fixes #10915
Fixes #10906
KeycardPopup
> fix: Wallet: Authentication popup is broken

- ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
We no longer want to show pending membership requests in the left column of the layout. Instead, community owners need to go to the community settings -> members -> Pending requests
This however does not remove the legacy membership popup yet because it's still used when users click the OS notification of incoming community requests to join.
We don't yet have a mechanism to make the app navigate specifically to that section of the community settings.
> refactor(communities): remove legacy pending membership indicator

- src/app/modules/main/controller.nim
- src/app/modules/main/io_interface.nim
- src/app/modules/main/module.nim
- src/app/modules/main/view.nim
- src/app_service/service/community/service.nim
- src/backend/communities.nim
- ui/app/AppLayouts/stores/RootStore.qml
- ui/app/mainui/AppMain.qml
closes: #10815 
- speedups/slowdowns archives import based on window state
status-go PR: https://github.com/status-im/status-go/pull/3568
- importing archives
https://github.com/status-im/status-desktop/assets/33099791/9ed94887-306b-4ef7-81af-d108193d69b2
> feat: speedup/slowdown archives import based on window state

- ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
Closes #10952
Resolves popup warning "Warning: qrc:/app/AppLayouts/Chat/views/CommunityColumnView.qml:79: TypeError: Cannot read property 'open' of null "
> fix(Communities): resolved popup warning

- src/app/modules/main/chat_section/controller.nim
- src/app/modules/main/chat_section/io_interface.nim
- src/app/modules/main/chat_section/module.nim
- src/app/modules/main/chat_section/view.nim
- src/app_service/service/community/service.nim
- src/backend/communities.nim
- ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
Part of: #9369
[STATUSGO PR](https://github.com/status-im/status-go/pull/3534)
Adds mute interval for categories
Muting category
> feat(communities): Adds mute category interval

- src/app/modules/main/profile_section/contacts/controller.nim
- src/app_service/common/types.nim
- src/app_service/service/activity_center/dto/notification.nim
- src/app_service/service/chat/service.nim
- src/app_service/service/contacts/service.nim
- ui/StatusQ/src/StatusQ/Components/StatusMessage.qml
- ui/app/mainui/activitycenter/popups/ActivityCenterPopup.qml
- ui/app/mainui/activitycenter/stores/ActivityCenterStore.qml
- ui/app/mainui/activitycenter/views/ActivityNotificationContactRemoved.qml
- ui/app/mainui/activitycenter/views/ActivityNotificationMessage.qml
- ui/app/mainui/activitycenter/views/qmldir
- ui/imports/shared/views/chat/MessageView.qml
- ui/imports/utils/Constants.qml
Close #10395
Waits  https://github.com/status-im/status-go/pull/3519
Chat, Contacts
> feat(Chat): display MutualStateUpdate system messages in 1-to-1 chats

- ci/Jenkinsfile.tests-e2e
- src/app/global/utils.nim
- src/app_service/service/chat/service.nim
- ui/StatusQ/include/StatusQ/QClipboardProxy.h
- ui/StatusQ/src/QClipboardProxy.cpp
- ui/imports/shared/status/StatusChatInput.qml
- ui/imports/utils/Utils.qml
- vendor/DOtherSide/lib/include/DOtherSide/DOtherSide.h
- vendor/DOtherSide/lib/src/DOtherSide.cpp
Fixes several issues/deficiencies we had with handling image data (paste, drag'n'drop, resizing); pls see the individual commits for explanation; namely: 
- fix crash when dropping a remote URL (non-Chrome browsers)
- fix DND checks for URLs containing a query
- missing support for dropping URLs
- fixup support for dropping URLs from Chrome (uses a non standard MIME type)
- fix missing support for dropping a bunch of files (e.g. from a file manager)
- more efficient `image_resizer` C++ code, more robust file size/extension checks
StatusChatInput, `sendImages`
TODO: video
> fix: extend/fix DND and clipboard image operations

- ui/app/AppLayouts/Chat/views/communities/CommunityNewTokenView.qml
Closes #10991
Accounts `color` role was changed to `colorId` so, `CommunityNewTokenView` has been updated accordingly.
https://github.com/status-im/status-desktop/assets/97019400/a284896e-bc27-49c6-84d7-e7a1295208fc
> fix(MintToken): App crash when trying to create new token

- ui/StatusQ/src/StatusQ/Components/private/statusMessage/StatusMessageReply.qml
wrap the reply contents area (excluding the profile header) in a ColumnLayout and move the MouseArea that handles the `messageClicked()` signal there, thus avoiding the collisions between the two
Fixes #10950
Fixes being unable to click the reply contents (to jump back to the original message)
StatusMessage(Reply)
[Záznam obrazovky z 2023-06-08 02-10-31.webm](https://github.com/status-im/status-desktop/assets/5377645/4ef7a948-69ed-45c5-8a65-1a38af96e18e)
> fix(Chat): Quoted message in a reply is not clickable

- ci/Jenkinsfile.tests-e2e
- src/app_service/service/chat/service.nim
- vendor/DOtherSide/lib/CMakeLists.txt
- vendor/DOtherSide/lib/src/DOtherSide.cpp
this should resolve the CI issues in `e2e` target by moving away the httpclient NIM impl to DOS (C++). Potentially this should be even faster as we don't save to a temporary file anymore and just load the recieved data directly into the QImage
DOS, sendImages
Still good, can DND remote URLs and send them:
> fix: download remote image URLs in DOS/C++

- ui/app/AppLayouts/Chat/views/ChatColumnView.qml
- ui/imports/shared/status/StatusChatInput.qml
fixup undefined references which caused the users model to become empty
Fixes #11005
Fixes broken @mention suggestions
ChatColumnView, StatusChatInput
> fix: [chat] @mentions no longer working

- Info.dev.plist
- Info.plist
- status.iss
Fixes: #8102
Updates url scheme for deep links from `status-im` to `status-app` on macOS and inno-setup file
deeplinks
> fix(deeplinks): Update plist files and into-setup file to new url scheme

- src/app/modules/main/chat_section/controller.nim
- src/app_service/service/community/service.nim
Prior to this change, the control node would try to fetch the community token data from its database entries.
However, when a community has been recovered from importing an account via seedphrase, the database for community tokens will be empty.
So it's better to retrieve the contract addresses from the community description's metadata (which should always be there).
This change determines the community token from the community metadata.
> Retrieve community token contract addresses from token metadata

- ui/app/AppLayouts/Wallet/views/RightTabView.qml
- ui/imports/shared/controls/TransactionAddress.qml
Fixes color for wallet accounts showed in Activity Details View. After wallet account color changes it was showing as a black.
Wallet Activity UI
> fix(@desktop/wallet): Update wallet account color correctly

- src/app/modules/main/chat_section/controller.nim
- src/app/modules/main/chat_section/io_interface.nim
- src/app/modules/main/chat_section/module.nim
- src/app/modules/shared_models/token_permissions_model.nim
- src/app_service/service/community/async_tasks.nim
- src/app_service/service/community/dto/community.nim
- src/app_service/service/community/service.nim
- src/backend/communities.nim
This is an improved version to check wether a user has permission to join a community and updating the join community view accordingly.
We now asynchronously do all the checks in status-go and process a single result upon token permission updates, additions and deletions.
Depends on: https://github.com/status-im/status-go/pull/3494
Closes #10481 #4939
> feat: introduce and handle `checkPermissionsToJoinCommunity()`

- src/app/global/utils.nim
- ui/app/mainui/Popups.qml
- ui/imports/shared/views/chat/ImageContextMenu.qml
- vendor/DOtherSide/lib/src/DOtherSide.cpp
Detect the MIME type using `QMimeDatabase` from the actual content and save it in that same format using `QSaveFile`, as `QImage` does NOT support saving a GIF
Fixes #10747
Fixes saving images from chat
[Záznam obrazovky z 2023-06-12 10-38-22.webm](https://github.com/status-im/status-desktop/assets/5377645/da8447c4-7374-46c7-bb90-1bf6e5c81adb)
> fix(Chat): Context menu for gif downloads a PNG file

- src/app/modules/main/wallet_section/activity/controller.nim
- src/app/modules/main/wallet_section/activity/model.nim
- src/app/modules/main/wallet_section/module.nim
- src/backend/activity.nim
- ui/imports/shared/views/ActivityView.qml
Bump status-go with [#3593](https://github.com/status-im/status-go/pull/3593) to include the async API changes
Handle the wallet-activity-filtering-done event
Propagate has more flag
Extend the debugging UX
> feat(wallet): make filter API async

- storybook/main.qml
- storybook/src/Storybook/PageToolBar.qml
- ui/app/AppLayouts/Chat/controls/community/EnsPanel.qml
- ui/app/AppLayouts/Chat/controls/community/ExtendedDropdownContent.qml
Set the `KeyNavigation.backtab` to itself to avoid accidentally pressing
`Shift+Tab` and tab away from the focused `StatusInput` (which makes it
look like it's disabled)
(a second commit fixes storybook inspection for Popup-like components)
Fixes #10561
> fix: Holdings dropdown searcher locked

- src/app_service/service/transaction/service.nim
- src/backend/transactions.nim
Part of #10791
status-go side: https://github.com/status-im/status-go/pull/3603
Split `MultiTransactionCommand` from main `MultiTransaction` struct to decouple them, since the latter will face several changes in the near future.
> chore(wallet): split multitransaction command from full struct

- storybook/pages/CommunityMintTokensSettingsPanelPage.qml
- storybook/pages/CommunityMintedTokensViewPage.qml
- storybook/pages/CommunityTokenViewPage.qml
- storybook/src/Models/MintedTokensModel.qml
- storybook/src/Models/WalletAccountsModel.qml
- ui/app/AppLayouts/Chat/helpers/AssetObject.qml
- ui/app/AppLayouts/Chat/helpers/CollectibleObject.qml
- ui/app/AppLayouts/Chat/helpers/TokenObject.qml
- ui/app/AppLayouts/Chat/helpers/qmldir
- ui/app/AppLayouts/Chat/panels/communities/CommunityAirdropsSettingsPanel.qml
- ui/app/AppLayouts/Chat/panels/communities/CommunityMintTokensSettingsPanel.qml
- ui/app/AppLayouts/Chat/panels/communities/MintTokensFooterPanel.qml
- ui/app/AppLayouts/Chat/popups/community/RemotelyDestructPopup.qml
- ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityMintedTokensView.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityNewAirdropView.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityNewTokenView.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityTokenView.qml
- ui/app/AppLayouts/Wallet/controls/NetworkFilter.qml
- ui/imports/shared/panels/DropAndEditImagePanel.qml
- ui/imports/shared/stores/CommunityTokensStore.qml
- ui/imports/utils/Utils.qml
Closes [#10878](https://github.com/status-im/status-desktop/issues/10878)
Fixes [#10860](https://github.com/status-im/status-desktop/issues/10860)
1. Mint Token views refactor:
- Created `TokenObject` files and use them inside `CommunityNewTokenView` instead of plain properties.
- Updated `CommunityTokenView` to use `TokenObject` properties instead of plain properties.
- Updated store calls to use `TokenObject` properties instead of plain properties.
- Remote destruct properties renames.
- Airdrop navigation extended passing token type (asset or collectible).
- Updated `storybook` according to new changes.
2. Adds navigation from retry to filled token form.
3. Fixes new tokens form validation rules.
Community Settings / Mint token
- Retry enabled: …
> MintToken: Mint token views refactor / enable retry / validation bugs / qml warnings

- storybook/pages/StatusChatListAndCategoriesPage.qml
- ui/StatusQ/src/StatusQ/Components/StatusChatList.qml
- ui/StatusQ/src/StatusQ/Components/StatusChatListAndCategories.qml
- simplify StatusChatListAndCategories, and propagate the width
- set the correct width in StatusChatList's actions (using `Layout.fillWidth: true`)
- add a width slider to the storybook page to be able experiment with the whole component width
Fixes #11047
Fixes the chat list items being cut at the right side
StatusChatList[AndCategories]
Correct width, badge displayed:
Storybook demo:
[Záznam obrazovky z 2023-06-13 13-53-15.webm](https://github.com/status-im/status-desktop/assets/5377645/9403c14f-101c-42cf-a7c6-dbb57f61e7d9)
> fix: invalid width for items chat list

- src/app/modules/main/wallet_section/activity/controller.nim
- src/app/modules/main/wallet_section/activity/entry.nim
- src/app/modules/main/wallet_section/activity/model.nim
- src/backend/activity.nim
- ui/imports/shared/views/ActivityView.qml
Bump status-go with [#3598](https://github.com/status-im/status-go/pull/3598) the refactoring of `hasMore` and addition of the required `offset`
Add support for continuously loading activity in the wallet API.
Extend the debugging demo with continuous loading.
> feat(wallet): extend API to continue loading activity

- ui/StatusQ/src/StatusQ/Components/StatusQrCodeScanner.qml
- ui/app/AppLayouts/Onboarding/views/sync/SyncDeviceFromMobile.qml
Fixes #10101
The problem was quite weird. The camera worked, but only when not **directly** in a Loader.
So I fixed by moving the Loader outside of StatusQrCodeScanner and into its parent SyncDeviceFromMobile.
The bahaviour is the same. We get a button asking to enable the camera, then we load the Scanner component. Before the Loader contained only the Camera component.
This PR needs to be tested in Mac and Windows too, but mostly Mac, because Igor told me the Loader was for Mac first of all.
I also need to test if this works in the AppImage. I only tested in dev (before it didn't even for in dev).
[camera.webm](https://github.com/status-im/status-desktop/assets/11926403/4da455ed-8746-43fb-ba2a-7600665ecd8f)
> fix(CodeScanner): fix QrCode Scanner not working on Linux

- storybook/pages/NetworkFilterPage.qml
- storybook/src/Models/NetworksModel.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityNewTokenView.qml
- ui/app/AppLayouts/Wallet/controls/NetworkFilter.qml
Fixes #11030 
- It updates `NetworkFilter.qml` to allow setting a specific `chainId` when single selection mode is on.
- It adds `storybook` use case for setting specific `chainId` in single selection mode.
- It integrates new network initialization process in mint new token view form to initialize network combobox properly.
- App integration:
https://github.com/status-im/status-desktop/assets/97019400/a97052c0-ba51-4fd8-bdd4-9895e853e5cc
- Storybook usecase:
https://github.com/status-im/status-desktop/assets/97019400/421ebb6d-59dd-4280-b4e2-7d9ab9636c44
> fix(MintTokens): Network is not correctly initialized when the new token form is prefilled

- ci/Dockerfile
- ci/Jenkinsfile.linux
- ci/Jenkinsfile.tests-nim
Possible fix for weird Linux crashes:
* https://github.com/status-im/infra-ci/issues/88
> ci: upgrade to GCC 11 to match build outside Docker

- storybook/PagesModel.qml
- storybook/pages/SignMultiTokenTransactionsPopupPage.qml
- ui/StatusQ/src/StatusQ/Core/Utils/ModelUtils.qml
- ui/app/AppLayouts/Chat/panels/communities/CommunityAirdropsSettingsPanel.qml
- ui/app/AppLayouts/Chat/popups/community/SignMultiTokenTransactionsPopup.qml
- ui/app/AppLayouts/Chat/popups/community/qmldir
- ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityNewAirdropView.qml
- ui/imports/shared/stores/CommunityTokensStore.qml
Introduces `SignMultiTokenTransactionsPopup` for displaying fees broken down into individual tokens and integrates it into the Airdrop flow.
Closes: #10484
`CommunityNewAirdropView`
[Screencast from 14.06.2023 11:45:00.webm](https://github.com/status-im/status-desktop/assets/20650004/946e175d-cb23-4dd7-8102-8edff3fc1897)
> feat(CommunityAirdrops): Summary popup with multiple fees listed

- ci/Jenkinsfile.linux
- ci/Jenkinsfile.macos
- ci/Jenkinsfile.tests-e2e
- ci/Jenkinsfile.tests-nim
- ci/Jenkinsfile.windows
Possible fix for random build crashes on Linux:
* https://github.com/status-im/infra-ci/issues/88
> ci: disable QML cache to avoid stale cache

- src/app/modules/main/chat_section/chat_content/module.nim
- src/app/modules/main/chat_section/chat_content/view.nim
- storybook/pages/StatusChatInputPage.qml
- ui/app/AppLayouts/Chat/views/ChatColumnView.qml
- ui/imports/shared/status/StatusChatInput.qml
* Fix `blocked` state wasn't loading on app start 
* Move `Unblock` button to `ChatColumnView`, because:
* It's only used there
* This simplifies the logic with `enabled`/`blocked` properties
* Fixed `Unblock` button size to fit the input 
* Added `enabled` property for corresponding storybook page
> fix(ChatColumnView): fix `StatusChatInput` blocked state

- src/app/modules/main/profile_section/devices/model.nim
- ui/StatusQ/src/StatusQ/Components/StatusSyncDeviceDelegate.qml
- ui/app/AppLayouts/Profile/ProfileLayout.qml
- ui/app/AppLayouts/Profile/panels/MenuPanel.qml
- ui/app/AppLayouts/Profile/views/LeftTabView.qml
- ui/app/AppLayouts/Profile/views/SyncingView.qml
Fixes https://github.com/status-im/status-desktop/issues/11082
* Show `Setup Syncing` button only for non-paired devices
* Clicking on non-paired device will start pairing process
* Show non-paired devices badge for `Settings/Syncing`
> fix(SyncingView): only suggest to sync non-synced devices

- src/app/modules/main/chat_search_item.nim
- src/app/modules/main/chat_search_model.nim
- src/app/modules/main/chat_section/item.nim
- src/app/modules/main/chat_section/module.nim
- src/app/modules/main/module.nim
- ui/StatusQ/src/StatusQ/Controls/StatusItemDelegate.qml
- ui/app/AppLayouts/Profile/controls/CommunityShowcaseDelegate.qml
- ui/app/AppLayouts/Profile/panels/ProfileShowcaseCommunitiesPanel.qml
- ui/app/AppLayouts/Profile/stores/WalletStore.qml
- ui/app/mainui/AppMain.qml
- ui/imports/shared/status/StatusSearchListPopup.qml
- ui/imports/shared/views/profile/ProfileShowcaseView.qml
- expose `colorId` and `colorHash`, the latter only for non-ENS verified users
- use them in the results :)
Fixes #11086
Fixes missing chat colors and identicon rings in the channel picker (Ctrl+K) jump list
AppMain/StatusSearchListPopup
> fix: Channel picker doesn't render 1-1 chats correctly

- test/ui-test/src/screens/components/saved_address_popup.py
- test/ui-test/testSuites/global_shared/scripts/wallet_names.py
- test/ui-test/testSuites/suite_wallet/tst_wallet_savedAddresses/test.feature
- ui/app/AppLayouts/Wallet/controls/NetworkSelectItemDelegate.qml
- ui/app/AppLayouts/Wallet/controls/StatusNetworkListItemTag.qml
- ui/app/AppLayouts/Wallet/controls/StatusNetworkSelector.qml
- ui/app/AppLayouts/Wallet/popups/AddEditSavedAddressPopup.qml
Fixes https://github.com/status-im/desktop-qa-automation/issues/62
The whole test was refactored:
- removed unnecessary steps
- added networks selection
- added verification for network selector enabled
- added validation for network tag presence when selected
- commented out adding saved address with ens option because of https://github.com/status-im/status-desktop/issues/11090
Saved addresses tests
> chore(e2e_tests): extend saved address creation with network options

- ui/app/AppLayouts/Chat/ChatLayout.qml
- ui/app/AppLayouts/Chat/panels/communities/CommunityProfilePopupOverviewPanel.qml
- ui/app/AppLayouts/Chat/popups/community/CommunityProfilePopup.qml
- ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
- ui/app/AppLayouts/CommunitiesPortal/stores/CommunitiesStore.qml
- ui/app/AppLayouts/Profile/panels/CommunitiesListPanel.qml
- ui/app/AppLayouts/Profile/views/CommunitiesView.qml
- ui/app/mainui/AppMain.qml
- ui/app/mainui/Popups.qml
- ui/imports/utils/Global.qml
- differentiate between "Close" and "Leave" a community where the former applies to spectated communities
- move the "leave community" confirmation popup to a shared place (Popups.qml), extend it with the outro message and reuse it everywhere
- don't let admins leave a community
- some minor cleanups and dead code removals
Fixes #10963
No "leave" items when admin:
Regular "leave" item:
"Close" spectated community
Confirmation when leaving from context menu (with outro message):
Confirmation when leaving from settings (with outro message):
> fix: community context menu should not say "Leave community" if not joined

- Status.entitlements
- vendor/DOtherSide/lib/include/DOtherSide/Status/AppDelegate.h
- vendor/DOtherSide/lib/src/DOtherSide.cpp
- vendor/DOtherSide/lib/src/Status/AppDelegate.mm
Fixes: #7957
Adds `entitlements` with `status.app` domain and introduce `ApplicationDelegate` for macOS
Next step [here](https://github.com/status-im/status-desktop/issues/11087). THIS PR NOT WORKING without correct sign.
App for macOS
> feat(universal-links): Adds universal links support for macOS

- storybook/pages/CommunityAirdropsSettingsPanelPage.qml
- storybook/pages/CommunityNewAirdropViewPage.qml
- storybook/pages/HoldingsDropdownPage.qml
- storybook/src/Models/AssetsModel.qml
- ui/app/AppLayouts/Chat/controls/community/ExtendedDropdownContent.qml
- ui/app/AppLayouts/Chat/controls/community/HoldingsDropdown.qml
- ui/app/AppLayouts/Chat/controls/community/ListDropdownContent.qml
- ui/app/AppLayouts/Chat/panels/communities/CommunityAirdropsSettingsPanel.qml
- ui/app/AppLayouts/Chat/panels/communities/CommunityMintTokensSettingsPanel.qml
- ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityNewAirdropView.qml
Closes #11056
- It adds assets model.
- It adds no data text for assets tab.
- It adds navigation from airdrop to mint specific tab.
- It updates `HoldingsDropdown` component to allow network information for assets.
- It removes `isCollectiblesOnly` option in `HoldingsDropdown`. No longer needed.
- It udates `storybook` to support airdrop assets testing.
**NOTE**: Pending assets backend so the functionality has been tested only using `storybook`.
Community Settings / Airdrop tokens
- Storybook - Assets model:
https://github.com/status-im/status-desktop/assets/97019400/9a487f56-5f87-4bd8-8a8b-bbcaad51d89b
- App navigation between airdrop and mint settings:
https://github.com/status-im/status-desktop/assets/97019400/35c5e216-02b1-4cea-a8fc-1fbf5195068b
> feat(AirdropAssets): Enable assets tab in airdrop dropdown

- ui/app/mainui/activitycenter/controls/ReplyBadge.qml
- ui/app/mainui/activitycenter/views/ActivityNotificationReply.qml
Close #8758
ActivityCenter
https://github.com/status-im/status-desktop/assets/2522130/61f8affc-3e84-4763-a564-391a462ab6ff
> feat(ActivityCenter): Make reply badge more interactive

- ui/app/AppLayouts/Profile/controls/BloomSelectorButton.qml
- ui/app/AppLayouts/Profile/views/AdvancedView.qml
Fixes #10957
Requires https://github.com/status-im/status-go/pull/3606
Re-enable waku2 `Light mode` on status.prod.
messaging, settings
> fix: Re-enable light mode for status.prod

- storybook/pages/ActivityFilterMenuPage.qml
- storybook/src/Models/CollectiblesModel.qml
- ui/app/AppLayouts/Wallet/controls/ActivityTypeCheckBox.qml
- ui/app/AppLayouts/Wallet/panels/ActivityFilterPanel.qml
- ui/app/AppLayouts/Wallet/popups/ActivityFilterMenu.qml
- ui/app/AppLayouts/Wallet/popups/filterSubMenus/ActivityCounterpartyFilterSubMenu.qml
- ui/app/AppLayouts/Wallet/popups/filterSubMenus/ActivityStatusFilterSubMenu.qml
- ui/app/AppLayouts/Wallet/popups/filterSubMenus/ActivityTokensFilterSubMenu.qml
- ui/app/AppLayouts/Wallet/popups/filterSubMenus/ActivityTypeFilterSubMenu.qml
- ui/app/AppLayouts/Wallet/stores/ActivityFiltersStore.qml
- ui/app/AppLayouts/Wallet/stores/qmldir
- ui/imports/shared/views/HistoryView.qml
Activity filter functionality
Things that don't work are
1. The from timestamp is not correctly set when we launch the custom date picker
2. The Type (Send , Receive ) doesnt work correctly, will check it in a different issue
3. The recents list of contacts is still WIP under https://github.com/status-im/status-go/pull/3623#issuecomment-1593443407
4. Filtering by collectibles not yet implemented
all of these will be handled under https://github.com/status-im/status-desktop/issues/11117
Activity view
https://github.com/status-im/status-desktop/assets/60327365/7caa5418-5959-4862-bbb2-a677c2164cb2 …
> feat(@desktop/wallet): Glue between activity UI filters and backend

- ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
Close #10853
Waits https://github.com/status-im/status-go/pull/3609
Communities
https://github.com/status-im/status-desktop/assets/2522130/ed6a8487-7537-460f-97e0-c0d2eb62ee06
> feat(Communities): Request to join should ask for a wallet password

- src/app/modules/main/wallet_section/activity/controller.nim
- src/app/modules/main/wallet_section/activity/recipients_model.nim
- src/backend/activity.nim
- ui/imports/shared/views/ActivityView.qml
Bumps [status-go](https://github.com/status-im/status-go/pull/3623) to include the new API.
Add a new RecipientsModel to the activity Controller.
Extends the activity Controller with API to access and manage data in the RecipientsModel.
Resolving addresses to names remains to be implemented.
> feat(wallet) add recipients API and integrate with filter

- src/app/modules/main/wallet_section/activity/controller.nim
- src/app/modules/main/wallet_section/activity/entry.nim
- src/app/modules/main/wallet_section/module.nim
- src/app_service/service/currency/service.nim
- src/backend/activity.nim
- storybook/pages/TransactionDetailViewPage.qml
- ui/app/AppLayouts/Wallet/views/TransactionDetailView.qml
- ui/imports/shared/views/ActivityView.qml
- ui/imports/shared/views/HistoryView.qml
Part of #11080
status-go: https://github.com/status-im/status-go/pull/3620
Make use of the new in/out amount values added to the backend entry.
Compatibility with the old model was maintained. The old interface should be removed when support for multitransactions gets added.
A workaround for a bug in status-go was introduced, since the activity for simple transactions is not properly detected (they're all detected as Receive type). This should be removed when that gets fixed.
> feat(@dekstop/wallet): use amounts from activity backend

- src/app/modules/main/chat_section/module.nim
- src/app_service/service/chat/service.nim
- ui/StatusQ/src/StatusQ/Components/StatusChatListItem.qml
Fixes #11041
status-go PR https://github.com/status-im/status-go/pull/3619
Fixes the bug where going to a muted channel with a mention doesn't mark it as read. This was because the QML doesn't call mark as read when a channel doesn't have unviewed messages. That was because our Nim code put 0 as unviewedMessageCount when a channel is muted.
I changed it so that channels always have the value from status-go. No more conditions on the Nim side. Now the condition is on the QML side. So we hide the badge in QML instead. That also means that showing the number of unviewed message, even in a muted channel works.
I also fixed a bug where we counted muted messages on app restart for the normal badge. Usually it didn't cause issues, because it's rare that you had messages in a muted channel and …
> fix(badges): fix muted chat not being marked as read

- src/app/modules/main/chat_section/module.nim
- src/app/modules/main/communities/controller.nim
- src/app/modules/main/communities/io_interface.nim
- src/app/modules/main/communities/models/curated_community_item.nim
- src/app/modules/main/communities/models/curated_community_model.nim
- src/app/modules/main/communities/module.nim
- src/app/modules/main/communities/view.nim
- src/app/modules/main/module.nim
- src/app/modules/shared_models/token_permission_item.nim
- src/app/modules/shared_models/token_permissions_model.nim
- ui/app/AppLayouts/Chat/controls/community/CommunityPermissionsRow.qml
- ui/app/AppLayouts/CommunitiesPortal/CommunitiesPortalLayout.qml
- ui/app/AppLayouts/CommunitiesPortal/views/CommunitiesGridView.qml
- ui/app/mainui/AppMain.qml
Fixes https://github.com/status-im/status-desktop/issues/10410
Adds the permission model to the curated communities model.
Also fixes the assetsModel and collectiblesModel used by the community portal, because it was using the basic Chat Store created in AppMain, but that store doesn't have the assets model.
---
I had to do a lot of duplication of code, because the assets model lives in each chat section. IMO, we should just use the one that I created/duplicated in the communities, that way we have less to save in memory, but it would also remove the duplication of code.
The only downside is that if there is a token that is created in a community, it would also appear in the dropdowns of other communities. I think I can live with that. We can also easily filter it if we add the community …
> Add permissions model to curated communities

- storybook/main.qml
Heuristic for finding for the subject of inspection fixed.
Closes: #11110
`Storybook`
> fix(Storybook): reenable inspection tool for popup pages

- src/app/modules/main/wallet_section/transactions/controller.nim
- src/app/modules/main/wallet_section/transactions/io_interface.nim
- src/app/modules/main/wallet_section/transactions/module.nim
- src/app/modules/main/wallet_section/transactions/view.nim
- src/app_service/service/transaction/async_tasks.nim
- src/app_service/service/transaction/service.nim
- src/backend/backend.nim
- storybook/pages/TransactionDetailViewPage.qml
- storybook/stubs/shared/stores/RootStore.qml
- ui/app/AppLayouts/Wallet/views/TransactionDetailView.qml
Fixes: #10793
Status go PR: https://github.com/status-im/status-go/pull/3527
Backend changes done by @alaibe 
Display decoded transaction input data in activity tab
It uses additional effect if there is too many lines to display. 
To display it as whole user can use context menu to copy it to the clipboard.
In case `input` data fails to be decoded it displays input data hex instead.
Activity UI
Design:
https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=13066-397009&t=VWxQuu3KjW4OKcOi-4
> Feat Parse transaction input

- storybook/PagesModel.qml
- storybook/figma.json
- storybook/pages/StatusButtonPage.qml
- storybook/pages/TransactionDelegatePage.qml
- storybook/pages/WalletHeaderPage.qml
- test/ui-test/testSuites/global_shared/scripts/wallet_names.py
- ui/StatusQ/src/StatusQ/Controls/StatusBaseButton.qml
- ui/StatusQ/src/StatusQ/Controls/StatusIconTextButton.qml
- ui/StatusQ/src/StatusQ/Core/Theme/ThemePalette.qml
- ui/app/AppLayouts/Chat/controls/community/MembersDropdown.qml
- ui/app/AppLayouts/Wallet/panels/WalletHeader.qml
- ui/app/AppLayouts/Wallet/views/LeftTabView.qml
- ui/imports/shared/controls/TransactionDelegate.qml
- ui/imports/shared/popups/CommunityIntroDialog.qml
- ui/imports/shared/views/ProfileDialogView.qml
- ui/imports/utils/Utils.qml
- introduce StatusButton storybook page with controls to play around with the its options and variants
- StatusBaseButton: make the content item horizontally centered by default
- StatusBaseButton: remove `textAlignment` and fix `textFillWidth` for the intended usage
- fixup usage of the 2 above options which were introduced merely as a workaround, mostly in wallet + corresponding storybook pages
Fixes #10903
Fixes alignment issues in Status[Base,Flat]Button
Status[Base,Flat]Button
Storybook button overview with controls:
Transaction Copy details button:
Wallet header & Saved addresses button:
Transaction delegate:
Members dropdown:
> chore: Update StatusBaseButton content item layout

- scripts/common/PasswordFunctions.py
- scripts/open_database.py
- scripts/password-hash.py
Made this for easier testing https://github.com/status-im/status-desktop/issues/11132.
Implemented according to [Notion | How-to-browse-sqlcipher-database](https://www.notion.so/How-to-browse-sqlcipher-database-3300824d1d3242ec837bf8f99adeea33?pvs=4#f8e68616f9754a9cb0ef7762e34d9ec3)
Also fixed `password-hash.py`, as it wasn't working after os/python update.
* list all accounts in given directory
* select an account from the list 
* connect to database using auto-detected `kdfIterations` and `pageSize`
* print tables count
* loop sql commands
https://github.com/status-im/status-desktop/assets/25482501/d746dfd2-74c8-40ae-8678-f39004b6d64d
CLI arguments shortcut is also available:
> feat(scripts): simple python script to interact with database

- ui/app/AppLayouts/Chat/controls/community/InDropdown.qml
Closing: #11142 
Use contentHeight to determine the scrollable height when it's smaller than max height.
Also fixing a bug where `No channels found` was overlapping `+ Add channel` button by including the `+ Add channel` button in the column layout.
Channels selection dropdown in permissions settings.
https://github.com/status-im/status-desktop/assets/47811206/da539429-1f6d-4ed6-b014-ac82ceb03025
https://github.com/status-im/status-desktop/assets/47811206/b66b341c-ce59-4662-bf9a-7fdf3539802a
> fix: InDropdown scrollable height

- ui/StatusQ/src/StatusQ/Popups/StatusMenu.qml
- ui/StatusQ/src/StatusQ/Popups/StatusMenuItem.qml
- ui/imports/shared/controls/chat/ProfileHeader.qml
- ui/imports/shared/panels/EditCroppedImagePanel.qml
- ui/imports/shared/popups/UserStatusContextMenu.qml
- ui/imports/shared/views/ProfileDialogView.qml
- ui/imports/shared/views/chat/ProfileContextMenu.qml
Closing: #11028 
Calculating the `StatusMenu` implicitWidth based on content width.
`StatusMenu`
Checking for regressions:
> fix(StatusQ): Dynamic width calculation for StatusMenu

- scripts/windows_build_setup.ps1
If we don't installe Go separately this is what happens:
```
PS C:\Users\jenkins> scoop install --global 7zip git dos2unix findutils wget rcedit inno-setup make cmake gcc go@1.20.4
Couldn't find manifest for 'C:\Users\admin\scoop\buckets\main\bucket\go.json7zip git dos2unix findutils wget rcedit inno-setup make cmake gc
```
Seems like some kind of parsing issue with providing a version.
> ci: fix installation of windows build dependencies

- src/app/modules/main/wallet_section/activity/entry.nim
Part of #11080
status-go part: https://github.com/status-im/status-go/pull/3642
Now that activity type is properly detected in status-go, use it in status-desktop.
This lets us remove an ugly workaround.
> fix(@wallet): use fixed activity type from backend

- storybook/pages/CommunityNewPermissionViewPage.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityNewPermissionView.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityNewTokenView.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityTokenView.qml
Closing: #11123 
Setting `contentWidth` and `contentHeight` to match the layout size.
+ fixing [CommunityNewPermissionViewPage.qml](https://github.com/status-im/status-desktop/compare/11123-token-minting-mint-form-is-needlessly-scrollable-horizontally?expand=1#diff-a4b90148169dc21a14ff1e5ce2af8e89693786b801b229dde0f43f30c71e388d)
[CommunityNewPermissionView.qml](https://github.com/status-im/status-desktop/compare/11123-token-minting-mint-form-is-needlessly-scrollable-horizontally?expand=1#diff-b2ca4384028f15ee26d1e29080a31641d2e67f62e1de1275ed4a2a8d0743f069)
[CommunityNewTokenView.qml](https://github.com/status-im/status-desktop/compare/11123-token-minting-mint-form-is-needlessly-scrollable-horizontally?expand=1#diff-eaa091d8f7020da4397179dd6c593694c9b7503e8f927e277f5fbb6e0b4a598e) …
> fix: Community permissions and tokens view horizontal scrolling

- storybook/src/Models/WalletAccountsModel.qml
- ui/app/AppLayouts/Chat/panels/communities/CommunityMintTokensSettingsPanel.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityNewTokenView.qml
Closing: #11162 
Exclude watch accounts from mint token-accounts dropdown by adding filter for watch accounts in the accounts model.
Mint tokens - account selection
https://github.com/status-im/status-desktop/assets/47811206/d6d79cd0-f095-4e2a-9dcd-ee65c29e675e
> fix: Mint tokens view - exclude watch accounts from accounts dropdown

- storybook/src/Models/MintedTokensModel.qml
- ui/app/AppLayouts/Chat/panels/communities/CommunityAirdropsSettingsPanel.qml
- ui/app/AppLayouts/Chat/panels/communities/CommunityMintTokensSettingsPanel.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityMintedTokensView.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityNewAirdropView.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityTokenView.qml
There are 5 fixes here solved in different commits:
https://github.com/status-im/status-desktop/issues/11149
https://github.com/status-im/status-desktop/issues/11147
https://github.com/status-im/status-desktop/issues/11199
https://github.com/status-im/status-desktop/issues/11198
https://github.com/status-im/status-desktop/issues/11208
The fixes are mainly issues created after a rebase so, just some property names or signal params changed incorrectly.
- Remotely destruct tokens flow should work correctly (I cannot test it in the app bc of the frozen app with accounts that have some minted and airdroped tokens)
- Airdrop item inserted correctly when there is navigation between minting view and airdrop.
- Minting footer options disabled logic.
- A label changed in a minting view box as per …
> Fix some mint token UI issues

- ui/app/AppLayouts/Chat/views/ChatColumnView.qml
This has slipped through during rebase.
We don't want to show the list of permissions to be fullfilled if they are already satisfied
> fix: ensure view-and-post permissions are hidden when satisfied

- ui/app/AppLayouts/Chat/views/ChatColumnView.qml
- ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
- ui/imports/shared/status/StatusChatInput.qml
Fixes https://github.com/status-im/status-desktop/issues/11167
* Clear input `replyMessageId` on message sending
* Delay `enabled` input property binding to fix switching to a chat with Blocked contact
chat input area
https://github.com/status-im/status-desktop/assets/25482501/e8c20a77-a63f-4367-ac5e-b5be2ab53629
> fix: chat input preserved properties bugs

- src/app/modules/main/chat_section/controller.nim
- src/app/modules/main/chat_section/io_interface.nim
- src/app/modules/main/chat_section/module.nim
- src/app/modules/main/chat_section/view.nim
- src/app/modules/main/communities/controller.nim
- src/app/modules/main/profile_section/communities/controller.nim
- src/app/modules/main/profile_section/communities/io_interface.nim
- src/app/modules/main/profile_section/communities/module.nim
- src/app/modules/main/profile_section/communities/view.nim
- src/app_service/service/community/dto/community.nim
- src/app_service/service/community/service.nim
- src/backend/communities.nim
- ui/app/AppLayouts/Profile/panels/CommunitiesListPanel.qml
- ui/app/AppLayouts/Profile/views/CommunitiesView.qml
- ui/app/mainui/AppMain.qml
- ui/imports/utils/Constants.qml
Fixes: #9369
Now community can be muted for some intervals
Communities
> feat(communities): Adds mute community intervals

- ui/app/AppLayouts/Chat/views/communities/CommunityNewTokenView.qml
Different placeholders for Asset and Collectibles view per figma
> chore(@CommunityNewTokenView): placeholder should differ depends on view

- ui/app/AppLayouts/Chat/views/communities/CommunityNewTokenView.qml
Add validation to allow 1-10 for decimal points input on NewTokenView for Asset
**Before:**
https://github.com/status-im/status-desktop/assets/82375995/dac4dd3e-e471-4f2c-bd33-9afed760daf3
**After**:
> chore(@CommunityNewTokenView.qml): add validation for decimal points input

- storybook/PagesModel.qml
- storybook/figma.json
- storybook/pages/CommunitiesViewPage.qml
- ui/StatusQ/src/StatusQ/Components/StatusMemberListItem.qml
- ui/app/AppLayouts/Chat/ChatLayout.qml
- ui/app/AppLayouts/Chat/panels/communities/CommunityMembersSettingsPanel.qml
- ui/app/AppLayouts/Chat/panels/communities/CommunityMembersTabPanel.qml
- ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
- ui/app/AppLayouts/Profile/ProfileLayout.qml
- ui/app/AppLayouts/Profile/panels/CommunitiesListPanel.qml
- ui/app/AppLayouts/Profile/views/CommunitiesView.qml
- ui/app/AppLayouts/stores/RootStore.qml
- ui/app/mainui/AppMain.qml
- ui/app/mainui/Popups.qml
- ui/imports/shared/controls/chat/menuItems/MuteChatMenuItem.qml
- ui/imports/utils/Global.qml
Implements the new Settings/Communities view according to the Figma design: https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=16089-387522&mode=design&t=mt6XicISfqBzHVqx-0
- adds the corresponding storybook page to play around with various types of communities
- exchanges the mute/unmute menu icons according to the new design
- TokenMaster category TODO
Closes #11145
Settings/Communities
Admin:
Member:
Pending:
Storybook:
Storybook, empty communities:
> feat(Settings/Communities): implement new communities list

- storybook/src/Models/WalletAccountsModel.qml
- ui/app/AppLayouts/Chat/panels/communities/CommunityMintTokensSettingsPanel.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityNewTokenView.qml
Backport `Mint tokens view - exclude watch accounts from accounts dropdown` to 0.13:
https://github.com/status-im/status-desktop/pull/11168
> chore(0.13.x): Backport Mint tokens view - exclude watch accounts from accounts dropdown

- ci/Jenkinsfile.linux
- ci/Jenkinsfile.tests-e2e
This is a temporary stop-gap fix for a known linux build issue: https://github.com/status-im/infra-ci/issues/88
Since currently this issue is very hard to reproduce and there is no good solution in sight this should minimize the pain caused by it.
Thanks for good suggestion from @yakimant .
> ci: retry nim_status_client build 3 times

- src/app/modules/main/view.nim
- src/app_service/service/community_tokens/service.nim
- src/app_service/service/transaction/service.nim
- vendor/DOtherSide/lib/src/DOtherSide.cpp
Fixes #11176
This fixes the crash experienced after minting. It doesn't fix the root cause. It seems like the event didn't have any data, but I couldn't reproduce the bug.
I'm still positive that this should resolve the crash though. I also added better logging if it happens again, so we'll be able to find the origin.
> fix(community_tokens/service): fix crash when receiving bad event

- ui/app/AppLayouts/Chat/panels/communities/CommunityMembersTabPanel.qml
This hides the action items to kick or ban users if they happen to be admins. There's also a change in status-go that prevents admins to kick or ban other admins that has to land first here:
https://github.com/status-im/status-go/pull/3666
Closes #10936
> fix: don't allow admins to kick or ban admins

- test/ui-test/testSuites/suite_wallet/tst_wallet_accountsManagement/test.feature
Hide/show w/o accounts button should not hide/show accounts but should reflect the total balance. This will be implemented in the app soon and the test has to be re-written to handle that
Wallet tests
> chore(@e2e_tests): disable test for hiding w/o accounts

- ui/app/AppLayouts/Chat/views/communities/CommunityNewTokenView.qml
allow uppercase ASCII only input, up to 6 characters
Fixes #11201
Fixes input of asset/collectible symbol name
CommunityNewTokenView
Non-letters entered:
> [Mint Token] Automatically switch the typed text to uppercase in symbol input

- src/app/modules/main/wallet_section/add_account/module.nim
- src/app_service/service/wallet_account/async_tasks.nim
1. Fixing a crash caused by missing `derivedAddresses` property on the response of fetchDerivedAddresses task
2. Unblock the add account modal on error.
Might be related to: https://github.com/status-im/status-desktop/issues/11010
Wallet
> fix(accountDerivation): App is crashing when the account derivation fails in status-go

- src/app/modules/main/chat_section/controller.nim
- src/app/modules/main/chat_section/io_interface.nim
- src/app/modules/main/chat_section/module.nim
- src/app/modules/main/chat_section/view.nim
- src/app/modules/main/communities/controller.nim
- src/app/modules/main/communities/io_interface.nim
- src/app/modules/main/communities/module.nim
- src/app/modules/shared_models/token_list_item.nim
- src/app/modules/shared_models/token_list_model.nim
- ui/app/AppLayouts/Chat/controls/community/ExtendedDropdownContent.qml
- ui/app/AppLayouts/Chat/controls/community/HoldingsDropdown.qml
- ui/app/AppLayouts/Chat/panels/communities/CommunityAirdropsSettingsPanel.qml
- ui/app/AppLayouts/Chat/panels/communities/CommunityPermissionsSettingsPanel.qml
- ui/app/AppLayouts/Chat/stores/RootStore.qml
- ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityNewAirdropView.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityNewPermissionView.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityPermissionsView.qml
Fixes #11125
Updates the communities asset and collectibles lists when a new token is deployed. 
Also refactors the section module to remove all that code and use the communities token list instead.
Adds community ID to the token list model so that we can show only the global tokens and the tokens from the community are shown in the community
> feat(communities): update communities token list on token deploy

- ui/imports/utils/Utils.qml
Closes #8480
Primary Navbar tooltip
> fix: Rename "Communities Portal" button tooltip to "Discover Communities"

- storybook/pages/CommunityNewTokenViewPage.qml
- ui/StatusQ/include/StatusQ/modelutilsinternal.h
- ui/StatusQ/src/StatusQ/Core/Utils/ModelUtils.qml
- ui/StatusQ/src/modelutilsinternal.cpp
- ui/app/AppLayouts/Chat/views/communities/CommunityNewTokenView.qml
Fixes checking for duplicate token name in a case insensitive manner
Redo the `ModelUtils.contains(model, roleName, value, mode = Qt.CaseSensitive)` in C++; more speed and add ability to search case in/ sensitive
Some more smaller fixes/speedups
Fixes #11204
Fixes checking for duplicate token name in a case insensitive manner
CommunityNewTokenView
> [Mint Token] Update validation rule for name property

- src/app/modules/main/profile_section/wallet/accounts/controller.nim
- src/app/modules/main/profile_section/wallet/accounts/io_interface.nim
- src/app/modules/main/profile_section/wallet/accounts/module.nim
- src/app/modules/main/profile_section/wallet/accounts/view.nim
- src/app/modules/main/wallet_section/accounts/io_interface.nim
- src/app/modules/main/wallet_section/accounts/module.nim
- src/app/modules/main/wallet_section/controller.nim
- src/app/modules/main/wallet_section/filter.nim
- src/app/modules/main/wallet_section/module.nim
- src/app/modules/main/wallet_section/overview/io_interface.nim
- src/app/modules/main/wallet_section/overview/item.nim
- src/app/modules/main/wallet_section/overview/module.nim
- src/app/modules/main/wallet_section/overview/view.nim
- src/app/modules/main/wallet_section/view.nim
- src/app_service/service/settings/dto/settings.nim
- src/app_service/service/settings/service.nim
- src/app_service/service/wallet_account/service.nim
- storybook/pages/ActivityFilterMenuPage.qml
- storybook/pages/WalletHeaderPage.qml
- ui/app/AppLayouts/Profile/controls/WalletKeyPairDelegate.qml
- ui/app/AppLayouts/Profile/stores/WalletStore.qml
- ui/app/AppLayouts/Profile/views/wallet/MainView.qml
- ui/app/AppLayouts/Wallet/panels/WalletHeader.qml
- ui/app/AppLayouts/Wallet/views/LeftTabView.qml
fixes #11221
statusgo PR : https://github.com/status-im/status-go/pull/3676
Note to QA: Please also test if this setting is synced correctly 
Implements and sync watch only account settings in all c overview and wallet settings
Wallet Account overview + Wallet Settings
https://github.com/status-im/status-desktop/assets/60327365/44fe625f-5a56-4aef-a20d-e7bc923303b2
> feat(@desktop/wallet): Watch only account toggle + persisted

- ui/app/AppLayouts/Communities/controls/BannerPicker.qml
- ui/app/AppLayouts/Communities/controls/LogoPicker.qml
- ui/app/AppLayouts/Communities/popups/CreateCommunityPopup.qml
- ui/app/mainui/AppMain.qml
- ui/app/mainui/Popups.qml
- ui/imports/utils/Constants.qml
Fixes #11234
Makes the logo and banner mandatory when creating a new community in production builds
CreateCommunityPopup
Logo and banner not filled -> `Next` disabled:
> Community -> New community: make community banner and logo required

- src/app/modules/main/chat_section/controller.nim
- src/app/modules/main/chat_section/io_interface.nim
- src/app/modules/main/chat_section/module.nim
- src/app/modules/main/chat_section/view.nim
- src/app/modules/main/communities/controller.nim
- src/app/modules/main/communities/io_interface.nim
- src/app/modules/main/communities/module.nim
- src/app/modules/main/communities/view.nim
- src/app_service/service/community/async_tasks.nim
- src/app_service/service/community/service.nim
- src/backend/communities.nim
- ui/app/AppLayouts/Chat/ChatLayout.qml
- ui/app/AppLayouts/Chat/stores/RootStore.qml
- ui/app/AppLayouts/Communities/views/CommunityColumnView.qml
- ui/app/AppLayouts/Profile/views/CommunitiesView.qml
Fixes #11154
Adds the Nim code and status-go code to enable passing the user's wanted addresses, instead of using all addresses.
Status-go PR https://github.com/status-im/status-go/pull/3656
The new view function is  
```nim
requestToJoinCommunityWithAuthenticationWithSharedAddresses*
(self: View, ensName: string, addressesToShare: string) {.slot.}
```
When `addressesToShare` is a stringified array of string addresses.
> feat(requestToJoin): add addressesToShare to requestToJoin call

- ui/app/AppLayouts/Profile/panels/CommunitiesListPanel.qml
- ui/app/AppLayouts/Profile/views/CommunitiesView.qml
in case a community is both `spectated` and `joined`
Fixes #11301
Fixes potential dupes in Settings/Communities
Settings/Communities
Before:
After ("Contributors' test community" gone from `Pending`)
> Settings/Communities: fix duplicate entries

- storybook/PagesModel.qml
- storybook/pages/PasswordViewPage.qml
- ui/imports/shared/views/PasswordView.qml
Closing: #8385 
Update new password input validators to allow any character input and show error message if the character is invalid.
Add PasswordView to storybook
PasswordView
https://github.com/status-im/status-desktop/assets/47811206/b0f3d5ee-e903-4327-8e46-15f27f88ad21
> fix(PasswordView): Space is not allowed in password

- ui/app/AppLayouts/Profile/views/KeycardView.qml
- ui/app/mainui/AppMain.qml
This one also fixes the issue if user runs `"Import or restore via a seed phrase"` and after successful import click on `"View imported accounts in Wallet"` button.
Fixes: #11346
> fix(@desktop/keycard): crash by just running "Setup a new Keycard with an existing account" flow and closing it

- storybook/pages/EditAirdropViewPage.qml
- storybook/pages/EditPermissionViewPage.qml
- storybook/pages/MintTokensSettingsPanelPage.qml
- storybook/pages/PermissionsViewPage.qml
- storybook/pages/SortableTokenHoldersPanelPage.qml
- storybook/pages/StatusTxProgressBarPage.qml
- storybook/src/Models/AssetsModel.qml
- storybook/src/Models/CollectiblesModel.qml
- storybook/src/Models/MintedTokensModel.qml
- storybook/src/Models/ModelsData.qml
- ui/app/AppLayouts/Communities/controls/AddressesInputList.qml
- ui/app/AppLayouts/Communities/controls/MembersSelectorPanel.qml
- ui/app/AppLayouts/Communities/panels/NoHoldersPanel.qml
- ui/app/AppLayouts/Communities/views/EditAirdropView.qml
- ui/imports/shared/panels/SequenceColumnLayout.qml
- fix some colors to look correct in dark mode too
- update/unbreak the corresponding storybook pages
Fixes #11289
EditAirdropView
Airdrop view:
Empty holders panel:
> fix: Airdrop section of deployed NFT doesn't seem to apply darkmode

- src/app_service/service/transaction/service.nim
This is a quick fix until the work is completed with the following tasks
- https://github.com/status-im/status-go/pull/3699
- https://github.com/status-im/status-desktop/issues/11233
Fixes starting unnecessary legacy background services on every transaction update. On a new account added with a lot of activity, the legacy code was generating performance issues
Wallet, performance
> fix(wallet) remove legacy transaction history event

- src/app/modules/main/wallet_section/activity/controller.nim
- src/app_service/service/transaction/service.nim
- src/backend/activity.nim
- ui/app/AppLayouts/Wallet/panels/ActivityFilterPanel.qml
- ui/app/AppLayouts/Wallet/popups/ActivityFilterMenu.qml
- ui/app/AppLayouts/Wallet/popups/filterSubMenus/ActivityCounterpartyFilterSubMenu.qml
- ui/app/AppLayouts/Wallet/stores/ActivityFiltersStore.qml
Bump status-go HEAD to [#3699](https://github.com/status-im/status-go/pull/3699) which includes required changes
Refactor the API usage to use the new async APIs.
Support multiple events in the same block
Report the loading state for all the APIs
Also
- reset the model to empty when the filter is invalidated due to address and chain IDs change
> feat(wallet) make filer apis async

- build-linux.sh
- ci/Dockerfile
- ci/Jenkinsfile.linux
- ci/README.md
Ubuntu 18.04 LTS support has ended on the 31st of May 2023. It's about time we upgraded to 20.04, which uses Glibc `2.31` instead of `2.27`.
> ci: upgrade docker image to Ubuntu 20.04

- ui/app/AppLayouts/Communities/views/EditPermissionView.qml
It solves problem with detecting dirty state in "Edit permission" form when changing channels in `In` section. The issue was caused by changed role name in the model of channels.
Closes: #11063
https://github.com/status-im/status-desktop/assets/20650004/83c6530d-17b6-4630-a02b-28cc281935e2
> fix(EditPermissionView): Dirty state validation fixed

- storybook/pages/CommunityTokenViewPage.qml
- ui/app/AppLayouts/Communities/helpers/TokenObject.qml
- ui/app/AppLayouts/Communities/panels/MintTokensSettingsPanel.qml
- ui/app/AppLayouts/Communities/views/CommunityTokenView.qml
- ui/app/AppLayouts/Communities/views/EditCommunityTokenView.qml
- ui/imports/utils/Constants.qml
- Improved binding from token model to `CommunityTokenView` instance (instantiating whole view as a Repeater delegate)
- `Constants.TokenType` used consistently, `TokenObject.Type` enum removed
- `CommunityTokenView` - holdings list hidden when token not deployed
Closes: https://github.com/status-im/status-desktop/issues/11387
Closes: https://github.com/status-im/status-desktop/issues/11384
Closes: https://github.com/status-im/status-desktop/issues/11386
`TokenObject`, `MintTokensSettingsPanel`, `CommunityTokenView`, `EditCommunityTokenView`
https://github.com/status-im/status-desktop/assets/20650004/491c443d-9ef6-4a3a-afac-16b50ea0863e
> Minting: Improved binding from token model to CommunityTokenView and other fixes

- src/app/modules/main/chat_section/controller.nim
- src/app/modules/main/chat_section/module.nim
- src/app/modules/main/chat_section/view.nim
- ui/app/AppLayouts/Communities/views/CommunityColumnView.qml
Fixes #11272
The problem was that we didn't handle the cancellation (checking with password was empty). 
Now we do and we send the signal to cancel when it's the case.
[cancel.webm](https://github.com/status-im/status-desktop/assets/11926403/6deb0da3-843b-4f83-a9cd-ec9ee8c7f54d)
> fix(community): fix cancel of authentication still requests to join

- ui/app/AppLayouts/Chat/stores/RootStore.qml
Closes: #11297
Fixes collectible icons in community permissions.
`AppLayouts/Chat/stores/RootStore.qml`
https://github.com/status-im/status-desktop/assets/20650004/42090deb-4cfb-463b-b9e7-be783f70cc37
> fix(Community Permissions): handling collectible icons fixed

- Makefile
- ci/Jenkinsfile.linux
- ci/Jenkinsfile.tests-e2e
After a LOT of work from @jrainville bisecting the release branch he identified the issue to be this commit:
- https://github.com/status-im/status-desktop/commit/dad8e453 - ci: bump client build retries to 20
Which actually was poorly squashed by @iurimatias and contains the commit that also adds the retries in the first place:
- https://github.com/status-im/status-desktop/commit/a5ba2537 - ci: retry nim_status_client build 3 times
The reason why that's an issue is because normally it was caled by `make tgz-linux` target which included this setting:
https://github.com/status-im/status-desktop/blob/a10e83bcba262845c5b350c6897bb773c98095b8/Makefile#L532-L533
Which caused `NIM_PARAMS` to use `-d:development` instead of `-d:production`. The result was the app trying to write config file …
> ci: fix read-only FS errors in AppImage

- Makefile
- ci/Jenkinsfile.linux
- ci/Jenkinsfile.tests-e2e
Cherry-pick of https://github.com/status-im/status-desktop/pull/11427
After a LOT of work from @jrainville bisecting the release branch he identified the issue to be this commit:
https://github.com/status-im/status-desktop/commit/dad8e453 ci: bump client build retries to 20
Which actually was poorly squashed by @iurimatias and contains the commit that also adds the retries in the first place: https://github.com/status-im/status-desktop/commit/a5ba2537 ci: retry nim_status_client build 3 times
The reason why that's an issue is because normally it was caled by `make tgz-linux` target which included this setting:
```
override RESOURCES_LAYOUT := $(PRODUCTION_PARAMETERS)
```
Which caused `NIM_PARAMS` to use `-d:development` instead of `-d:production`. The result was the app trying to write …
> [CHERRY-PICK] ci: fix read-only FS errors in AppImage

- test/ui-test/testSuites/suite_settings/tst_languageSettings/test.feature
I need more time to fix it, so let's skip them, to have green pipeline
> Tests on Language settings skipped

- ui/app/AppLayouts/Communities/controls/EditCommunitySettingsForm.qml
Related to #11323
Fixing Edit Community Form width
Edit community panel
Create community popup
> fix(Edit community settings): Fixing width after merge error

- ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml
The same components are used to display data from rootStore.assetsModel, rootStore.collectiblesModel (permissions) and
root.community.communityTokens (airdrops). The models have different roles and need adjustments before passing to ui components.
Closes: #11309
https://github.com/status-im/status-desktop/assets/20650004/0992262a-2ac9-43f2-a6fa-e6c2e9b3da4f
> fix(CommunitySettingsView): Add expected roles to assets/collectibles models

- ui/app/AppLayouts/Communities/views/EditCommunityTokenView.qml
Closing #11359 
Check `errors` object for values before invalidating the supply amount.
Mint tokens
> fix: Supply amount in mint tokens preview

- ui/imports/shared/popups/keycard/KeycardPopup.qml
Closing #11335 
Increase the keycard popup with to predefined value.
Keycard popup
> fix: Increase keycard popup width

- storybook/PagesModel.qml
- storybook/figma.json
- storybook/pages/OverviewSettingsPanelPage.qml
- test/ui-test/src/screens/StatusCommunityScreen.py
- test/ui-test/testSuites/suite_communities/shared/scripts/community_names.py
- test/ui-test/testSuites/suite_communities/tst_communityFlows/test.feature
- test/ui-test/testSuites/suite_communities/tst_communityManageOverview/test.feature
- ui/app/AppLayouts/Communities/panels/OverviewSettingsPanel.qml
Closing: #11320 
Update Community Overview header based on the new design
[Design](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba⎜Desktop?type=design&node-id=31229-627216&mode=design&t=KoQOW7vmoNc7f41m-0)
1. Update header layout and size
2. Add OverviewSettingsPanel in storybook
3. Update squish tests - Fix random failure when clicking the `Edit Community` button + Remove tests related to the community identicon as it's removed from Overview.
Community overview
Storybook
> feat: Update Community Overview header based on the new design

- ui/app/AppLayouts/Chat/stores/RootStore.qml
Fixes: #11443
Trim emoji for community channels on create step. Its hard to test result because both sides (mobile and desktop) trim it in UI.
Community channels
> fix(community): Trim emojis in channels

- src/app/modules/main/wallet_section/activity/controller.nim
- src/app/modules/main/wallet_section/activity/events_handler.nim
- src/backend/activity.nim
- src/backend/transactions.nim
Bump status-go to include events: https://github.com/status-im/status-go/pull/3721
Process pending updates events and trigger button show
Also: improve parsing of the activity entry
- Root cause found here: https://github.com/status-im/status-desktop/issues/11404#issuecomment-1623849498
- renamed new-pending notification in pending updates and triggered it also on delete
> Refresh filter on pending 11233

- src/app/modules/main/wallet_section/activity/controller.nim
- src/app/modules/main/wallet_section/activity/events_handler.nim
- src/backend/transactions.nim
- ui/imports/shared/views/HistoryView.qml
Bumps status-go https://github.com/status-im/status-go/pull/3731
Handle ChainIDs also (don't show new data if not from the enabled chains)
Throttle down new data in filter events to show the activity at a maximum every two seconds.
> feat(wallet) handle multi-transaction update events for activity filter

- src/app/modules/main/profile_section/contacts/controller.nim
- src/app_service/common/types.nim
- src/app_service/service/contacts/service.nim
- src/app_service/service/message/service.nim
- ui/StatusQ/src/StatusQ/Components/StatusMessage.qml
- ui/imports/shared/views/chat/MessageView.qml
- ui/imports/utils/Constants.qml
Close #11121
Requires https://github.com/status-im/status-go/pull/3640
See the desired flow in the status-go PR
Chat, Contacts, ActivityCenter
> Fix mutual state update messages

- src/app/modules/startup/module.nim
- src/app/modules/startup/view.nim
- crash was happening because of some issue on the status-go side, rebasing to the latest master resolved that
- app was in loading state forever because of `db.reEncryption.started` and `db.reEncryption.finished` signals emitted for db re-encryption process while conversion from keycard to a regular account is ongoing
Fixes: #11507
> fix(@desktop/onboarding): the app crashes when converting a keycard to a regular account, or just being in loading state forever

- storybook/pages/AirdropsSettingsPanelPage.qml
- storybook/pages/MintTokensSettingsPanelPage.qml
- ui/StatusQ/src/StatusQ/Components/StatusInfoBoxPanel.qml
- ui/app/AppLayouts/Communities/panels/AirdropsSettingsPanel.qml
- ui/app/AppLayouts/Communities/panels/MintTokensSettingsPanel.qml
- ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml
- ui/app/AppLayouts/Communities/views/MintedTokensView.qml
- ui/app/AppLayouts/Communities/views/WelcomeSettingsView.qml
Closes #11472
- New `Get started` panel for admins in `Tokens` and `Airdrops` section added.
- Added support in `storybook`.
Community Settings / Tokens and Airdops
- Tokens:
https://github.com/status-im/status-desktop/assets/97019400/39954171-3d4c-4998-84dc-6fb6c7f66fc3
- Airdrops:
https://github.com/status-im/status-desktop/assets/97019400/6d969ce3-d268-4747-8bbd-53f6df83ac7c
> feat/issue-11472: Admin view of Tokens and Airdrops home - pre-Owner token minting

- src/app/modules/main/chat_section/controller.nim
- src/app/modules/main/chat_section/io_interface.nim
- src/app/modules/main/chat_section/module.nim
- src/app/modules/main/chat_section/view.nim
- src/app_service/service/community/async_tasks.nim
- src/app_service/service/community/service.nim
- src/backend/communities.nim
Fixes #11479
status-go PR https://github.com/status-im/status-go/pull/3756
To use it on the front-end, just call this function:
```nim
proc requestToJoinCommunityWithAuthenticationWithSharedAddresses*(self: View, ensName: string,
addressesToShare: string, airdropAddress: string) {.slot.} =
```
Where `addressesToShare` is a stringified array of strings and `airdropAddress` is a one of the addresses from `addressesToShare`.
QML example:
```qml
const exampleAddresses = [
"0xB69aca9A59566b8fBC0AA63A5e4c0F1DEf209f46",
"0x0d5795eB5F333b67569428Ae5374BEf010Cb7fea"
]
chatCommunitySectionModule.requestToJoinCommunityWithAuthenticationWithSharedAddresses(
ensName,
JSON.stringify(exampleAddresses),
"0x0d5795eB5F333b67569428Ae5374BEf010Cb7fea"
)
```
> feat(community): add airdropAddress param to request to join functions

- src/app/modules/main/communities/controller.nim
- src/app/modules/main/communities/io_interface.nim
- src/app/modules/main/communities/module.nim
- src/app/modules/main/communities/view.nim
- src/app_service/service/community/service.nim
- ui/app/AppLayouts/Communities/views/CommunityColumnView.qml
Fixes #11514
The problem was that we were not handling the error from request to join correctly.
Then I added an event that sends a signal to the QML to show a toast about an error. I don't show the actual error to the user because usually it's not super helpful. It will be in the logs.
The status-go change makes it so that we don't save the request to join if the permission check failed.
status-go PR: https://github.com/status-im/status-go/pull/3748
> fix: crash when request to join fails + add error toast when it fails

- ui/app/AppLayouts/Profile/views/WalletView.qml
- ui/app/AppLayouts/Profile/views/wallet/AccountView.qml
fixes #11526
The elements should be the size of its children and scroll only if they area to scroll is larger than available space
https://github.com/status-im/status-desktop/assets/60327365/628442cd-51c2-4526-a207-d63fda3e0339
> fix(@desktop/wallet): fixes weird scrolling behaviour in Wallet settings

- ui/StatusQ/src/StatusQ/Components/StatusChatList.qml
disable the highlight also when not exiting the DropArea
Fixes #11459
Fixes chat items staying highlighted even after a slight move
StatusChatList
> fix: Channels stay highlighted when they are not selected

- storybook/PagesModel.qml
- storybook/figma.json
- storybook/pages/OverviewSettingsChartPage.qml
- ui/StatusQ/src/StatusQ/Components/StatusChartPanel.qml
- ui/StatusQ/src/StatusQ/Components/private/chart/Chart.js
- ui/StatusQ/src/StatusQ/Core/LocaleUtils.qml
- ui/app/AppLayouts/Communities/panels/OverviewSettingsChart.qml
- ui/app/AppLayouts/Communities/panels/OverviewSettingsPanel.qml
- ui/app/AppLayouts/Communities/panels/qmldir
Closing. #11440
1. Implementing community messages over time chart. The chart qml item will receive a flat array as model containing timestamps of the individual messages.
2. Adding `OverviewSettingsChart.qml` to storybook
Overview Settings
https://github.com/status-im/status-desktop/assets/47811206/58ecd3d3-fd4e-4064-a214-1112232d83aa
> feat(communityChart): Add messages over time chart - mocked data

- test/ui-test/testSuites/suite_wallet/tst_wallet_accountsManagement/test.feature
Disable some tests for account management, should be refactored due to changes introduced in https://github.com/status-im/status-desktop/pull/11368. The expected behavior is to use `+`button to add accounts instead of context menu.
> chore(@e2e_tests): temp disable several wallet tests because of changing feature

- storybook/PagesModel.qml
- storybook/figma.json
- storybook/pages/EditOwnerTokenViewPage.qml
- ui/app/AppLayouts/Communities/helpers/PermissionsHelpers.qml
- ui/app/AppLayouts/Communities/helpers/TokenObject.qml
- ui/app/AppLayouts/Communities/panels/MintTokensSettingsPanel.qml
- ui/app/AppLayouts/Communities/panels/PrivilegedTokenArtworkPanel.qml
- ui/app/AppLayouts/Communities/panels/TokenInfoPanel.qml
- ui/app/AppLayouts/Communities/panels/qmldir
- ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml
- ui/app/AppLayouts/Communities/views/CommunityTokenView.qml
- ui/app/AppLayouts/Communities/views/EditOwnerTokenView.qml
- ui/app/AppLayouts/Communities/views/OwnerTokenWelcomeView.qml
- ui/app/AppLayouts/Communities/views/qmldir
- ui/imports/shared/stores/CommunityTokensStore.qml
Closes #11296
- It creates a generic `TokenInfoPanel` that will be reused in different mint token views.
- It creates new `EditOwnerTokenView` and storybook page support.
- It adds new `EditOwnerTokenView` into the minting flow, linking sign transaction flow and adding needed method to the store to do the deployment.
**NOTE:** Backend integration needed!
- App:
https://github.com/status-im/status-desktop/assets/97019400/c354671c-9021-4c11-9729-5aec15eb20ef
- Storybook:
https://github.com/status-im/status-desktop/assets/97019400/47e2567d-7ff1-4e5e-9bdf-c53e95cd9ddf
> feat(OwnerToken): Create `EditTokenView.qml` for mint owner token flow

- src/app/modules/main/chat_section/controller.nim
- src/app/modules/main/chat_section/io_interface.nim
- src/app/modules/main/chat_section/module.nim
- src/app/modules/main/chat_section/view.nim
- src/app/modules/main/communities/controller.nim
- src/app/modules/main/communities/io_interface.nim
- src/app/modules/main/communities/module.nim
- src/app/modules/main/communities/view.nim
- src/app_service/service/community/async_tasks.nim
- src/app_service/service/community/service.nim
- src/backend/communities.nim
Fixes #11153
Adds `editSharedAddressesWithAuthentication` in the chat_section view to be called from QML.
Also adds the `communityEditSharedAddressesSucceeded` and `communityEditSharedAddressesFailed` signals in the communities module to be used by QML to know if it worked.
> feat(communities): add API to edit shared addresses

- src/app/modules/main/chat_section/controller.nim
- src/app/modules/main/chat_section/io_interface.nim
- src/app/modules/main/chat_section/module.nim
- src/app/modules/main/chat_section/view.nim
- storybook/PagesModel.qml
- storybook/figma.json
- storybook/pages/ExportControlNodePopupPage.qml
- storybook/src/Storybook/FilteredPagesList.qml
- ui/app/AppLayouts/Chat/stores/RootStore.qml
- ui/app/AppLayouts/Communities/panels/OverviewSettingsFooter.qml
- ui/app/AppLayouts/Communities/panels/OverviewSettingsPanel.qml
- ui/app/AppLayouts/Communities/popups/ExportControlNodePopup.qml
- ui/app/AppLayouts/Communities/popups/qmldir
- ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml
- ui/app/mainui/Popups.qml
- ui/imports/utils/Global.qml
Closing #11547 
Adding the export control node popup. The popup is behind an authentication wall.
1. Create ExportControlNodePopup qml
2. Add the popup in storybook
3. Create authentication flow with qml callback to open the popup after authentication
4. Add the popup open action in Global.qml
Overview settings
https://github.com/status-im/status-desktop/assets/47811206/f744343e-3be7-4bdf-9be5-a996ed4dc62a
Design:
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba⎜Desktop?type=design&node-id=31171-627949&mode=design&t=2oTvQ8uKSyfpldMX-0
> feat: Export control node (except backend for primary action)

- storybook/pages/CommunitiesViewPage.qml
- storybook/stubs/AppLayouts/Chat/stores/RootStore.qml
- ui/app/AppLayouts/Profile/panels/CommunitiesListPanel.qml
- ui/app/AppLayouts/Profile/views/CommunitiesView.qml
- ui/imports/utils/Constants.qml
Add a `memberRole` value and section for the TokenMaster category in Settings/Communities
Fixes #11308
Settings/Communities
> feat(Token master): create category in Settings/Communities

- storybook/src/Models/PermissionsModel.qml
- ui/StatusQ/include/StatusQ/permissionutilsinternal.h
- ui/StatusQ/src/permissionutilsinternal.cpp
- ui/app/AppLayouts/Communities/panels/SharedAddressesPermissionsPanel.qml
Modify the PermissionUtils a bit to return an array of `[key, channelName]` instead of just the keys and use it to display the channel names in the permissions overview panel
(I could have used `QVariantMap` or `QJSonObject` here but those are always sorted by `key`, so had to resort to using a plain vector/array)
Fixes #11584
Fixes displaying proper channel names in the permissions panel
SharedAddressesPermissionsPanel
> feat(token-permissions): display channel names in SharedAddressesPanel

- ui/app/AppLayouts/Communities/panels/MintTokensSettingsPanel.qml
- close the first popup before opening another
- fix `SignTokenTransactionsPopup` title (it would display "Burn undefined tokens")
- remove duplicate close() calls
- `destroyOnClose: false` is the default
Fixes #11498
MintTokensSettingsPanel
[Záznam obrazovky z 2023-07-21 14-12-15.webm](https://github.com/status-im/status-desktop/assets/5377645/4bbb199b-acaf-4f57-8170-d651ffe9a0d2)
> fix: Burn and self destruct pop-ups are not closed after signing

- storybook/pages/AirdropsSettingsPanelPage.qml
- storybook/pages/MintTokensSettingsPanelPage.qml
- storybook/pages/MintedTokensViewPage.qml
- storybook/src/Models/MintedTokensModel.qml
- ui/app/AppLayouts/Communities/helpers/PermissionsHelpers.qml
- ui/app/AppLayouts/Communities/panels/AirdropsSettingsPanel.qml
- ui/app/AppLayouts/Communities/panels/MintTokensSettingsPanel.qml
- ui/app/AppLayouts/Communities/panels/PrivilegedTokenArtworkPanel.qml
- ui/app/AppLayouts/Communities/panels/TokenInfoPanel.qml
- ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml
- ui/app/AppLayouts/Communities/views/EditOwnerTokenView.qml
- ui/app/AppLayouts/Communities/views/MintedTokensView.qml
- ui/app/AppLayouts/Communities/views/OwnerTokenWelcomeView.qml
- ui/app/AppLayouts/Wallet/views/collectibles/CollectibleView.qml
- ui/imports/shared/stores/CommunityTokensStore.qml
Closes #11299
- Added `storybook` support to change minted tokens model with Owner and TMaster tokens.
- Added new properties into the `tokenModel` model.
- Extended `CollectiblesView` to allow Owner and TMaster tokens representation.
- Updated `MintedTokensView` in order to display Owner and TMaster tokens.
- Added logic to `enable/disable` MINT and AIRDROP token depending on the owner /  tmaster tokens deploy state.
- Added temp buttons in MINT and AIRDROP pages that keeps enabled the flows although owner and tmaster backend is not ready. **They will be removed by this [task](https://github.com/status-im/status-desktop/issues/11612)**
- Extended navigation from outsite to minting section, depending on user profile and owner and tmaster states.
- Hide footer options in case of owner or …
> feat(OwnerToken): Add all mint states views design details

- ui/app/mainui/activitycenter/stores/ActivityCenterStore.qml
Fixes https://github.com/status-im/status-desktop/issues/11616
Notification ID was passed as a message ID. Fixed that.
This was causing the chat to open but never find a message (cause the ID was invalid).
> fix(ActivityCenterStore): Fix `switchTo` messageId argument

- storybook/PagesModel.qml
- storybook/pages/FeeRowPage.qml
- storybook/pages/FeesBoxPage.qml
- storybook/pages/FeesPanelPage.qml
- storybook/pages/SignMultiTokenTransactionsPopupPage.qml
- storybook/src/Models/FeesModel.qml
- storybook/src/Models/qmldir
- storybook/src/Storybook/LimitProxyModel.qml
- storybook/src/Storybook/qmldir
- ui/StatusQ/src/StatusQ/Components/StatusEmojiAndColorComboBox.qml
- ui/StatusQ/src/modelutilsinternal.cpp
- ui/app/AppLayouts/Communities/controls/AccountSelector.qml
- ui/app/AppLayouts/Communities/controls/FeeRow.qml
- ui/app/AppLayouts/Communities/controls/FeesBoxFooter.qml
- ui/app/AppLayouts/Communities/controls/FeesSummaryFooter.qml
- ui/app/AppLayouts/Communities/controls/qmldir
- ui/app/AppLayouts/Communities/panels/FeesBox.qml
- ui/app/AppLayouts/Communities/panels/FeesPanel.qml
- ui/app/AppLayouts/Communities/panels/qmldir
- ui/app/AppLayouts/Communities/popups/SignMultiTokenTransactionsPopup.qml
- ui/app/AppLayouts/Communities/views/EditAirdropView.qml
- implements "fees box" and sign tx popup according to the new design, covering all variants
- add small utility to the Storybook
- fixes bug in `ModelUtils.get` potentially causing UB or crash
Closes: https://github.com/status-im/status-desktop/issues/11600
> feat(Communities): Redesigned fees box and sign tx popup components

- storybook/pages/OverviewSettingsPanelPage.qml
- storybook/pages/StatusInfoBoxPanelPage.qml
- ui/StatusQ/src/StatusQ/Components/StatusInfoBoxPanel.qml
- ui/StatusQ/src/StatusQ/Components/StatusListItem.qml
- ui/StatusQ/src/StatusQ/Controls/StatusBanner.qml
- ui/app/AppLayouts/Chat/ChatLayout.qml
- ui/app/AppLayouts/Communities/panels/OverviewSettingsPanel.qml
- ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml
- ui/app/mainui/AppMain.qml
- ui/imports/shared/panels/ModuleWarning.qml
- display an info box when in wallet testnet mode with a CTA to disable
it (functionality enabled for production builds only)
- the CTA can be tested/seen via OverviewSettingsPanelPage storybook page
- plus separate commits to add support for icon in `StatusInfoBox` and fix consistent usage of its `warning` color
Closes #11468
CommunitySettingsView, OverviewSettingsPanel, StatusInfoBox
[Záznam obrazovky z 2023-07-24 13-27-35.webm](https://github.com/status-im/status-desktop/assets/5377645/b06e708e-bdba-438b-a809-a4a0efeade73)
Testnet info banner (with Community editable off):
> feat: disable community settings while in Testnet mode

- test/ui-test/testSuites/suite_wallet/shared/steps/walletSteps.py
- test/ui-test/testSuites/suite_wallet/tst_wallet_accountsManagement/test.feature
Fixes https://github.com/status-im/desktop-qa-automation/issues/82
1. enabled back the tests which were disabled because of context menu changes
2. renamed several to make them look alike
3. disabled 2 tests because they need to be changed a little (additional verifications needed), for now they are duplicating existing stuff
Wallet tests
> chore(@e2e_tests): enable back disabled tests

- ui/app/AppLayouts/Communities/panels/OverviewSettingsPanel.qml
- ui/imports/utils/Constants.qml
Closing: #11451 
Updating the help page URL opened by `Learn more` button from Community Overview.
note: the page is currently behind authentication wall.
Community overview
https://github.com/status-im/status-desktop/assets/47811206/838dcdfc-9e3a-41cf-9f71-2d656b432e69
> feat(CommunityOverview): Update Control Node help page URL opened by Learn more button

- storybook/PagesModel.qml
- storybook/figma.json
- storybook/pages/ColumnHeaderPanelPage.qml
- storybook/pages/ImportControlNodePopupPage.qml
- ui/app/AppLayouts/Chat/stores/RootStore.qml
- ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
- ui/app/AppLayouts/Communities/panels/OverviewSettingsPanel.qml
- ui/app/AppLayouts/Communities/popups/ImportControlNodePopup.qml
- ui/app/AppLayouts/Communities/popups/qmldir
- ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml
- ui/app/mainui/Popups.qml
- ui/imports/utils/Global.qml
Closing: #11548
1. Create a new popup as per Design: ImportControlNodePopup
2. Add the popup in storybook
3. Integrate ImportControlNodePopup in the app
Community Settings overview
https://github.com/status-im/status-desktop/assets/47811206/5e796de8-693c-48e8-ae28-16ea0ca2f230
https://github.com/status-im/status-desktop/assets/47811206/89bde4a1-b18a-4e0d-8c85-841d9dce6eff
> feat(Import Control Node): Adding ImportControlNode flow

- ui/app/AppLayouts/Chat/stores/RootStore.qml
- ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml
Depends on: #11640
Related to: #11547
Enabling remove private key action from Export control node popup by connecting the action to backend.
Community Overview
https://github.com/status-im/status-desktop/assets/47811206/f3c1dbc4-6492-4a03-9efb-3b7b7d794d2e
> Connect Export control node popup to backend - Delete private key

- storybook/pages/ProfileDialogViewPage.qml
- ui/imports/shared/panels/ProfileBioSocialsPanel.qml
- ui/imports/shared/views/ProfileDialogView.qml
put a little label below the emoji hash with the elided compressed chat
key plus a copy button with a tooltip
(some minor spacing and storybook fixes in a separate commit)
Fixes https://github.com/status-im/status-desktop/issues/11665
Own profile, dark:
Jo's profile, light:
> fix(ProfileDialogView): impossible to copy one's chat key 

- src/app/modules/main/wallet_section/activity/entry.nim
- src/backend/activity.nim
- ui/app/AppLayouts/Wallet/stores/RootStore.qml
Remove usage of fetched details about transactions and multi-transactions and use metadata instead.
Transaction details fetching will be removed in a follow-up PR because the headers (summary) use the activity entry. This will require some more extensive refactoring.
Bump status-go to [#3775](https://github.com/status-im/status-go/pull/3775) for the required API changes
> chore(wallet) optimize fetching request by using metadata

- src/app_service/service/community_tokens/service.nim
- src/backend/community_tokens.nim
As discussed in https://github.com/status-im/status-go/pull/3798, there was a need to separate the logic in `AddCommunityToken()` into two API.
This commit adjust the client to these changes such that:
1. After community token deployment tx was sent, we create a `CommunityToken` and add it to the database for tracking purposes
2. Once the tx is mined or dropped, we add the community token to the community description and publish it, or we update the deployment state in the database
Needs: https://github.com/status-im/status-go/pull/3798
> refactor: make use of newly introduce `SaveCommunityToken()` API

- ui/StatusQ/src/StatusQ/Components/StatusMessage.qml
- ui/app/AppLayouts/Chat/popups/PinnedMessagesPopup.qml
- ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
- ui/imports/shared/views/chat/MessageView.qml
Missed some property bindings in my original PR, as @caybro noticed 🙂 
Also removed `linkUrls` property, which is not used anymore for now.
> fix: Bind `linkPreviewModel` property

- src/app/modules/main/communities/tokens/controller.nim
- src/app/modules/main/controller.nim
- src/app/modules/main/io_interface.nim
- src/app/modules/main/module.nim
- src/app_service/service/community_tokens/service.nim
We've been using this signal whenever a user has sent a transaction that attemps to deploy a smart contract onchain.
However, at this point it's not yet known if the transaction will actually go through. So to reflect what's actually happening, this commits renames a few things:
- `SIGNAL_COMMUNITY_TOKEN_DEPLOYED` becomes `SIGNAL_COMMUNITY_TOKEN_DEPLOYMENT_STARTED`
- `CommunityTokenDeployedArgs` becomes `CommunityTokenDeploymentArgs`
- `onCommunityTokenDeployed` becomes `onCommunityTokenDeploymentStarted`
This should remove any confusion around whether or not deployment is indeed finished.
> refactor: rename SIGNAL_COMMUNITY_TOKEN_DEPLOYED

- storybook/pages/EditAirdropViewPage.qml
- storybook/pages/FeesBoxPage.qml
- ui/StatusQ/src/StatusQ/Controls/StatusComboBox.qml
- ui/app/AppLayouts/Communities/controls/FeeRow.qml
- ui/app/AppLayouts/Communities/controls/FeesBoxFooter.qml
- ui/app/AppLayouts/Communities/panels/AirdropsSettingsPanel.qml
- ui/app/AppLayouts/Communities/panels/FeesBox.qml
- ui/app/AppLayouts/Communities/panels/FeesPanel.qml
- ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml
- ui/app/AppLayouts/Communities/views/EditAirdropView.qml
- ui/imports/shared/stores/CommunityTokensStore.qml
Update airdrop flow to use account selector in fees box. Also amends some inconsistencies with the design after recent updates.
Closes: https://github.com/status-im/status-desktop/issues/11605
`EditAirdropView`, `FeesBox`, `FeesBoxFooter`, `StatusComboBox`
> chore(Communities): Fee handling updated in the airdrop flow

- src/app/modules/main/communities/tokens/controller.nim
- src/app/modules/main/communities/tokens/io_interface.nim
- src/app/modules/main/communities/tokens/models/token_model.nim
- src/app/modules/main/communities/tokens/module.nim
- src/app/modules/main/communities/tokens/view.nim
- src/app/modules/main/controller.nim
- src/app/modules/main/io_interface.nim
- src/app/modules/main/module.nim
- src/app/modules/shared_models/section_item.nim
- src/app_service/service/community_tokens/service.nim
- src/backend/community_tokens.nim
- ui/imports/shared/stores/CommunityTokensStore.qml
This partially addresses #11186 as it implements the delete functionality for community tokens.
If a deployment failed, users have the ability to delete the added community token from the list.
The retry functionality will be implemented in a follow up commit.
> feat: implement delelete community token functionality

- src/app_service/service/community_tokens/service.nim
- ui/app/AppLayouts/Communities/panels/MintTokensSettingsPanel.qml
- ui/imports/shared/stores/CommunityTokensStore.qml
Ultimately, this means deleting/removing the entry of the previously failed deployment, then performing a new transaction.
Closes #11186
> feat: implement retrying deploying community contracts

- test/ui-test/src/screens/SettingsScreen.py
- test/ui-test/testSuites/global_shared/scripts/settings_names.py
- test/ui-test/testSuites/global_shared/steps/settingsSteps.py
- test/ui-test/testSuites/suite_wallet/tst_wallet_settingsManagement/test.feature
- ui/app/AppLayouts/Profile/views/WalletView.qml
Fixes https://github.com/status-im/desktop-qa-automation/issues/84
Add interaction with Add new account button in wallet settings
wallet tests
> test(@tst_wallet_settingsManagement): add test to add new account from settings

- Entitlements.plist
- Info.plist
- Makefile
Fixes https://github.com/status-im/status-desktop/issues/11643
- Added [Camera Entitlement](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_device_camera?language=objc)
- Fixed codesign calling to include entitlements
- Updated camera access message
- It seems that earlier it wasn't possible to sign anything with `QtWebEngine` without such entitlement, but now it seems fine.
Here's a thread about this: [QtWebEngine signing issues](https://forum.qt.io/topic/102212/qtwebengine-signing-issues/12)
- It was initially added here: https://github.com/status-im/status-desktop/pull/375.
- Apple docs says that it is "an extreme entitlement that removes a fundamental security protection from your app".
- It seems to be not included in our app for awhile …
> fix: Add camera entitlement on MacOS

- src/app/modules/main/communities/module.nim
- src/app/modules/main/communities/view.nim
- src/app/modules/shared_models/section_model.nim
- ui/StatusQ/sandbox/pages/StatusToastMessagePage.qml
- ui/StatusQ/src/StatusQ/Components/StatusToastMessage.qml
- ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
- ui/app/AppLayouts/Communities/stores/CommunitiesStore.qml
- ui/app/mainui/AppMain.qml
Closing #11652 
There are two commits:
eeb70d4e27ca2063e8911324ff331ef25b9736b7 - Display two lines of text in StatusToastMessage
4d10ea61dc4c21c861137bcf373db0dd2bb1886f - Adding the toast messages:
1. Fix an issue where importing a community using private key triggers the import finished event without updating the community data if the community is already imported with public key
2. Show toast messages on importCommunity and privateKeyRemoved events
3. Group community import toast messages handlers and move them from ContactsColumnView to AppMain. IMO these toast messages handlers should not be dependent on ContactsColumnView.
StatusQ
Import Community flow
ContactsColumnView
https://github.com/status-im/status-desktop/assets/47811206/141b0099-1eab-41ab-ab8d-7eaf4a2119f8
<!-- optional …
> [Control Node] Add toast messages when the control node is removed/added

- test/ui-test/src/drivers/aut.py
Fixes ([Skip closing AUT process at the end of the test](https://github.com/status-im/desktop-qa-automation/issues/85))
> test(AUT) Skip closing AUT process at the end of the test

- storybook/pages/HoldingsDropdownPage.qml
- ui/StatusQ/src/StatusQ/Controls/StatusDropdown.qml
- ui/app/AppLayouts/Communities/controls/ExtendedDropdownContent.qml
- ui/app/AppLayouts/Communities/controls/ListDropdownContent.qml
- ui/app/AppLayouts/Communities/controls/TokenItem.qml
- ui/app/AppLayouts/Communities/popups/HoldingsDropdown.qml
- remove padding and use margins so that the listview can span the whole width while having the scrollbar neatly next to it
- make the section header both inline and floatable (which makes it always visible, even when scrolled away)
- fix the special search results "section" to behave the same way
- sort the results by category and name
- expose the `allTokensMode` for easy testing with storybook
Closes #10201
holdings dropdown
[Záznam obrazovky z 2023-07-27 15-46-45.webm](https://github.com/status-im/status-desktop/assets/5377645/6c10ab5f-840d-407b-bb81-1747ae692491)
Plain list, all tokens:
Plain list, all tokens + search, scrolled down:
Collectibles, no results search:
> fix: Review scrolling behavior for holdings dropdown

- ui/app/AppLayouts/Wallet/controls/NetworkFilter.qml
- ui/app/AppLayouts/Wallet/controls/NetworkSelectItemDelegate.qml
Closes #11467 
There are two changes in this PR:
- Make the L2 chain as the default one - implicitly making Optimism as the default network 903fcf7b659abcda238e9385af18c5323b604ff6
- Fix a bug in the network selector for single selection configuration. Whenever a network is selected, the bindings are broken making it impossible to be selected again. 903fcf7b659abcda238e9385af18c5323b604ff6
NetworkFilter
https://github.com/status-im/status-desktop/assets/47811206/c0b72510-32ef-433e-a329-92a4876ef211
> 11467 Replace MainNet with Optimism as default network selection

- ui/app/AppLayouts/Communities/panels/AirdropsSettingsPanel.qml
- ui/app/AppLayouts/Communities/popups/MembersDropdown.qml
- ui/app/AppLayouts/Communities/views/EditAirdropView.qml
Fixes #11532
Hooks the Airdrop views to the new airdropAddress model property so that the fee calculation and the airdrop transaction can use a valid address.
To test this, I had to "hack" the view so that it let me through, since it requires the Owner Token to be minted, but we can't do that yet. Anyway, that restriction is UI only. I included the "hack" in the PR so that QAs can test.
[airdrop.webm](https://github.com/status-im/status-desktop/assets/11926403/15bf98a7-6b47-4a5e-ab0c-119f9e027e2f)
Successful transaction: https://goerli.etherscan.io/tx/0x70f81b3209f97d2306236883e229ca8a6f6d443dfd84b309fc94ba3ded62cf96
> feat(airdrop): make the airdrop member selector use the airdropAddress

- storybook/pages/SortableTokenHoldersPanelPage.qml
- storybook/pages/StatusInfoBoxPanelPage.qml
- ui/StatusQ/src/StatusQ/Components/StatusInfoBoxPanel.qml
- ui/app/AppLayouts/Communities/panels/MintTokensSettingsPanel.qml
- ui/app/AppLayouts/Communities/panels/SortableTokenHoldersPanel.qml
- ui/app/AppLayouts/Communities/views/CommunityTokenView.qml
Fixes #11496
- Added `buttonEnabled` property to `StatusInfoBoxPanel` so it can be set from outside.
- Fixed airdrop button enable condition in minting flow. It is enabled when minting state is **completed** and if the token properties are **infinite supply or** there are still **remaining tokens** to be airdropped.
- Updated storybook accordingly.
Community Settings / Tokens
https://github.com/status-im/status-desktop/assets/97019400/115419dd-5b8e-4b8c-827d-e4714b27d4ad
https://github.com/status-im/status-desktop/assets/97019400/d170e790-387f-4e5a-8975-cac960b92320
> fix(Minting): After minting completed 1 airdrop button is enabled and the other disabled

- ui/StatusQ/src/StatusQ/Core/StatusBaseText.qml
- ui/app/AppLayouts/Profile/panels/ContactsListPanel.qml
- ui/app/AppLayouts/Profile/popups/SendContactRequestModal.qml
- ui/app/AppLayouts/Profile/views/ContactsView.qml
- ui/app/mainui/Popups.qml
- ui/imports/shared/popups/SendContactRequestModal.qml
- fix missing profile image
- fix displaying wrong name when a nickname or ENS name is present
- fix ID verification flow ignoring nickname
- fix empty results when a contact has only an alias name
- fix needlessly requesting contact details several times (and
overwriting it); we get this info already from Popups.qml
- switch the popup to `StatusDialog` and fix hardcoded height
2 other smaller commits related to contact display
Fixes https://github.com/status-im/status-desktop/issues/11726
SendContactRequestModal, Popups
1. Sending a contact request (CR) has a correct profile image:
2. Correct display name and image for a user with an ENS name:
3. Correct nickname displayed when sending an ID verification request:
4. Alias name not discarded, even when the user is unknown:
5. Nickname + …
> fix(SendContactRequestModal): Display name / image problems with CR dialog

- ui/app/AppLayouts/Communities/popups/CreateCategoryPopup.qml
- ui/app/AppLayouts/Communities/popups/CreateChannelPopup.qml
- ui/imports/shared/popups/RenameGroupPopup.qml
- ui/imports/utils/Constants.qml
Restrict the character set to basically 7-bit ASCII plus some punctuation in community/chat/profile related popups in order to:
- reduce the risk of impersonation (UTF-8 characters might look the same despite being a different codepoint)
- narrow down the set of characters in order to keep the new share URL format short
Closes #11307
Create chat category:
Create channel:
Edit group chat:
Profile display name:
Community name/description:
> fix: Revisit character set usage in description fields

- storybook/pages/MintTokensSettingsPanelPage.qml
- ui/app/AppLayouts/Communities/panels/MintTokensSettingsPanel.qml
- ui/app/AppLayouts/Communities/panels/PrivilegedTokenArtworkPanel.qml
- ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml
- ui/app/AppLayouts/Communities/views/MintedTokensView.qml
Closes #11613
- In case of `Owner` and `TMaster` token deployment failed, a `Retry` button must be shown in minted tokens pages and it will navigate to the `Edit page` the same way it's done by using `Retry` button inside the item selected.
- Updated storybook accordingly.
**NOTE**: Only UI. Tested with `storybook`.
Community Settings / Tokens - Owner and TMaster tokens
https://github.com/status-im/status-desktop/assets/97019400/3e9288fd-06cd-4463-86d9-fbf6c41b36ed
> feat(OwnerToken): Add `Retry` button

- Makefile
Now `DOtherSide` built library is automatically updated with `make run`, if there're any changes 🎉 
During working on https://github.com/status-im/status-desktop/pull/11748, I needed to rebuild DOtherSide regularly. 
Old Makefile instructions didn't run cmake each time, so I had to clean and rebuild the whole library instead of rebuilding single changed file.
I used the same set of instructions as I previously used for `StatusQ`. 
build system
> chore(makefile): improve dotherside build

- src/app/modules/main/profile_section/wallet/accounts/module.nim
- src/app/modules/main/profile_section/wallet/accounts/view.nim
- src/app/modules/main/wallet_section/send/module.nim
- src/app/modules/shared_models/keypair_account_model.nim
- src/app/modules/shared_models/keypair_item.nim
- src/app/modules/shared_models/keypair_model.nim
- src/app_service/service/wallet_account/service.nim
- ui/app/AppLayouts/Wallet/popups/ReceiveModal.qml
- ui/imports/shared/views/RecipientView.qml
#11743 
Fixes :
1. Send modal on choosing an account as recipient , the preferred networks should be chosen
2. The receive modal resets after updating sharing networks which is incorrect 
3. 
Send and Receive Modal
https://github.com/status-im/status-desktop/assets/60327365/bb061e80-c152-4a3d-b26e-87bbfbc2caac
> Wallet: Send doesn't load preferred chains on account selection as recipient Fix/issue 11743

- ci/Jenkinsfile.combined
- ci/Jenkinsfile.linux
- ci/Jenkinsfile.macos
- ci/Jenkinsfile.tests-e2e
- ci/Jenkinsfile.tests-imports
- ci/Jenkinsfile.tests-nim
- ci/Jenkinsfile.windows
- ci/cpp/Jenkinsfile.linux
- ci/cpp/Jenkinsfile.macos
- ci/cpp/Jenkinsfile.windows
This is a possible fix for issues with `x86_64` app failures:
- https://github.com/status-im/status-desktop/issues/11762
Most probably caused by some jobs remembering `RELEASE` parameter, manifesting partially in the filename:
> ci: pass RELEASE parameter to child jobs from parent

- src/app/modules/main/communities/tokens/models/token_item.nim
- src/app/modules/main/communities/tokens/models/token_model.nim
- src/app/modules/main/communities/tokens/models/token_owners_item.nim
- src/app/modules/main/communities/tokens/models/token_owners_model.nim
- src/app/modules/main/controller.nim
- src/app/modules/main/io_interface.nim
- src/app/modules/main/module.nim
- src/app/modules/shared_models/section_item.nim
- src/app_service/service/community_tokens/service.nim
- src/backend/community_tokens.nim
- ui/app/AppLayouts/Communities/panels/MintTokensSettingsPanel.qml
Expose remote destruct state via tokens model and token holders model.
_Technical details:_
There are 2 new properties in the model: destructedAmount and remoteDestructedAddresses.
1. destructedAmount is used to show the correct Total value. During remote destruction we do not change supply, but we need to show the decreased supply for the user. We show total(UI) = supply - destructed_tokens. Example:
Total = 10, Airdropped= 5, Remaining=5 , Destructed = 0
Then we destruct 1 airdropped token and we have:
Total = 9, Airdropped=4, Remaining=5, Destructed = 1
2. remoteDestructedAddresses is used to show the remote destruct state (by checking len()) and also to set destruct state for concrete holders.
@noeliaSD @micieslak we need a new UI task to show burn icon in holders view. The name of …
> 11182 remote destruct state

- storybook/pages/PopupSizingPage.qml
- ui/StatusQ/src/StatusQ/Controls/StatusDropdown.qml
- ui/StatusQ/src/StatusQ/Popups/Dialog/StatusDialog.qml
- ui/imports/shared/popups/SendModal.qml
It improves workaround for QTBUG-87804 in `StatusDropdown`, to work nicely whenever content is set via contentItem or not. The same solution is added to `StatusDialog`.
Closes: #11768
`StatusDropdown`, `StatusDialog`
> fix(StatusDropdown, StatusDialog): height calculation improved

- storybook/pages/MintTokensSettingsPanelPage.qml
- storybook/pages/TokenMasterActionPopupPage.qml
- storybook/src/Models/MintedTokensModel.qml
- ui/app/AppLayouts/Communities/panels/MintTokensSettingsPanel.qml
- ui/app/AppLayouts/Communities/panels/SortableTokenHoldersPanel.qml
- ui/app/AppLayouts/Communities/popups/TokenMasterActionPopup.qml
- ui/app/AppLayouts/Communities/popups/qmldir
- ui/app/AppLayouts/Communities/views/CommunityTokenView.qml
Adds popups for handling `Remote destruct`, `Kick` and `Ban` actions for `TokenMaster`
Closes: #11622
`MintTokensSettingsPanel`
> feat(Communities): Remote destruct, Ban and Kick actions for TokenMaster

- src/app/modules/main/wallet_section/collectible_details/controller.nim
- src/app/modules/main/wallet_section/collectible_details/events_handler.nim
- src/app/modules/shared_models/collectible_details_entry.nim
- src/app/modules/shared_models/collectibles_utils.nim
- src/backend/collectibles.nim
- src/backend/collectibles_types.nim
Closes https://github.com/status-im/status-desktop/issues/10728
Status-go part: https://github.com/status-im/status-go/pull/3840
Bumps status-go
Adapt client to new Collectibles API
We should now be able to fetch collectibles from all chains we own:
- Infura (Used for Arb NFTs) doesn't provide Collection metadata we need (missing Collection Name + CollectionImageURL). Implementation of separate collection metadata fetching is left for another PR.
- We now have more than one provider for some chains, main+fallback providers mechanism for Collectibles ownership is left for another PR.
> chore: adapt to new collectibles api

- storybook/figma.json
- storybook/pages/SortableTokenHoldersListPage.qml
- storybook/src/Models/TokenHoldersModel.qml
- ui/app/AppLayouts/Communities/panels/SortableTokenHoldersList.qml
Presents state of remotely destruct in progress within token holders list.
Closes: #11775
`SortableTokenHoldersList`
Note: The token was minted long time ago and for some reason total and remaining is presented as zero here. It's ok for new tokens.
[Kazam_screencast_00001.webm](https://github.com/status-im/status-desktop/assets/20650004/61f10430-6e9d-4022-a62e-72fd677a115c)
> feat(Communities): Present remotely destruct in progress in token holders list

- ui/app/AppLayouts/Chat/views/MembersSelectorView.qml
Fixes https://github.com/status-im/status-desktop/issues/11778
1. Fix opening the CR popup for ENS name
- pass `contactData` object to `processContact`
https://github.com/status-im/status-desktop/blob/e97f77621457be3b42dcb7297140cda3bac14575/ui/app/AppLayouts/Chat/views/MembersSelectorView.qml#L177
- change check `contactData.displayName !== ""` to `contactData.displayName`, which also checks for `undefined`.
https://github.com/status-im/status-desktop/blob/e97f77621457be3b42dcb7297140cda3bac14575/ui/app/AppLayouts/Chat/views/MembersSelectorView.qml#L120
2. Fix the logic of opening the popup.
Popup opening should only happen after all other cases failed (is contact, pending contact request, blocked, ...)
`MembersSelectorView`
https://github.com/status-im/status-desktop/assets/25482501/5edf …
> fix(MembersdSelectorView): fix the logic of opening CR popup

- Entitlements.plist
Fixes https://github.com/status-im/status-desktop/issues/11762
In https://github.com/status-im/status-desktop/pull/11748 I added the `com.apple.developer.associated-domains` entitlement. But it was too early for that, as there are no provisioning profiles yet.
Working build from this branch: https://ci.infra.status.im/job/status-desktop/job/systems/job/macos/job/aarch64/job/package/774/
> fix(Entitlements.plist): not yet support apple associated domains

- src/app/modules/main/controller.nim
- src/app/modules/main/module.nim
Fixes #10770
There were two issues, the first one was that categories were included in the search model because the categories are now part of the chat_model.
Also, since it used the chat_model, some chats were not part of the search model at start, because they weren't loaded yet.
I fixed by using the chats from the service directly instead.
[chats-serahc.webm](https://github.com/status-im/status-desktop/assets/11926403/ef423c16-80ca-4d53-a6b3-d15cd8f636a9)
> fix(chatSearch): fix chat search to include all and only chats

- src/app/modules/main/chat_section/controller.nim
- src/app/modules/main/chat_section/io_interface.nim
- src/app/modules/main/chat_section/module.nim
- src/app/modules/main/chat_section/view.nim
- src/app_service/service/community/dto/community.nim
- src/app_service/service/community/service.nim
- storybook/pages/OverviewSettingsChartPage.qml
- ui/StatusQ/src/StatusQ/Components/private/chart/Chart.qml
- ui/app/AppLayouts/Chat/stores/RootStore.qml
- ui/app/AppLayouts/Communities/panels/OverviewSettingsChart.qml
- ui/app/AppLayouts/Communities/panels/OverviewSettingsPanel.qml
- ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml
Closing #11758 
This PR includes the following changes:
1. Request from backend the messages count in a specific time interval as opposed to all messages timestamps in that interval.
2. Update the chart end date before refreshing the data - this is fixing an issue where the chart was not updated after initialisation.
3. Fix metrics type parsing in community service
4. Fix a bug where the new incoming data was not processed by ChartJs without a hover event on the chart. The fix here is to manually request paint() on model changes.
Issues found and not handled here:
1. On large communities the backend request can take 3 minutes to complete
2. CPU usage can easily go to 100% when switching chart tabs on large communities.
Community Overview
Community metrics …
> feat(Community Overview): Trigger chart data updates on specific actions + reduce the backend call frequency

- src/app/modules/main/wallet_section/collectibles/controller.nim
- src/app/modules/main/wallet_section/collectibles/events_handler.nim
- src/app/modules/shared_models/collectibles_model.nim
- ui/app/AppLayouts/Wallet/views/CollectiblesView.qml
Fixes https://github.com/status-im/status-desktop/issues/11785
The model was not properly updated when the loading items were present and new collectibles were fetched. Clicking one of these corrupted items caused the app to crash.
This PR changes how loading items are managed. Also added a workaround for when the user quickly scrolls to the bottom of the list while items are being loaded, for some reason `fetchMore` is not called in this case.
The loading items mechanism should be simplified, added a task for working on that: https://github.com/status-im/status-desktop/issues/11802
> fix(@desktop/wallet): fix wrong model update when items are fetched

- src/app/modules/main/chat_section/chat_content/controller.nim
- src/app/modules/main/chat_section/chat_content/messages/controller.nim
- src/app/modules/main/chat_section/chat_content/messages/io_interface.nim
- src/app/modules/main/chat_section/chat_content/messages/module.nim
- src/app/modules/main/chat_section/chat_content/module.nim
- src/app_service/service/message/async_tasks.nim
- src/app_service/service/message/dto/call_reason.nim
- src/app_service/service/message/service.nim
- src/backend/messages.nim
- ui/StatusQ/src/StatusQ/Components/StatusMessage.qml
- ui/StatusQ/src/StatusQ/Components/StatusMessageDetails.qml
- ui/StatusQ/src/StatusQ/Components/private/statusMessage/StatusMessageReply.qml
- ui/app/AppLayouts/Chat/views/MembersSelectorView.qml
- ui/imports/shared/views/chat/MessageView.qml
Fixes #11759
1. `scrollToMessage` will not scroll if the message doesn't exist in the database
2. Now it's impossible to click on a deleted/unavailable message (even pointing hand cursor will not appear)
3. Moved reply clicking logic to `StatusMessageReply`
4. Made "message found" animation faster 
5. Renamed `fetchMessageByMessageId` to `getMessageByMessageId`, 
because by "fetch" we usually mean "fetch from waku", which doens't happen here. And the status-go method is "get" anyway.
I should say that I wasn't able to reproduce the bug actually.
But this should fix any potential problems.
https://github.com/status-im/status-desktop/assets/25482501/a69c7bd9-07dd-4830-90be-ec49630ca1a9
> fix: Only `scrollToMessage` when it's available in the database

- ui/app/AppLayouts/Profile/views/profile/MyProfileSettingsView.qml
- ui/imports/shared/panels/ProfileBioSocialsPanel.qml
Fixes #7924
1. Profile bio text is now trimmed when the user updates his profile.
2. Profile bio text is trimmed when displaying a user profile (own or other). This is to amend bio text that has already been saved with leading or tailing whitespace via the app or other means.
I've also considered the need to implement this safeguard in the `StatusInput` control, however, I couldn't justify it. Looking for feedback on this.
~~add video showcasing the trim in action?~~
> Trim white space before and after profile bio text

- storybook/pages/CommunityPermissionsSettingsPanelEditor.qml
- storybook/pages/PermissionsSettingsPanelPage.qml
- storybook/src/Models/PermissionsModel.qml
- ui/app/AppLayouts/Communities/controls/PermissionItem.qml
- ui/app/AppLayouts/Communities/controls/PermissionTypes.qml
- ui/app/AppLayouts/Communities/views/EditPermissionView.qml
- ui/app/AppLayouts/Communities/views/PermissionsView.qml
Closes #11769
- It adds info panel when control node is offline.
- It modifies UI texts when control node is offline.
- It updates `storybook` updating permissions model and allowing permission state changes.
**NOTE:** Only UI (can be tested on `storybook`), no backend. TODO: There is 1 expected integration point: permissions model item `permissionState` role.
Community Settings / Permissions
https://github.com/status-im/status-desktop/assets/97019400/aaf8dd4b-2f49-43cd-8e6a-0caffc86759d
> feat(Permissions): Adding, duplicating, editing and deleting permissions when control node is offline

- src/app/modules/main/communities/module.nim
- src/app/modules/main/module.nim
- src/app/modules/shared_models/member_item.nim
- src/app/modules/shared_models/member_model.nim
- src/app_service/common/types.nim
- src/app_service/service/activity_center/dto/notification.nim
- storybook/figma.json
- storybook/pages/ActivityNotificationCommunityMembershipRequestPage.qml
- storybook/pages/MembersTabPanelPage.qml
- ui/app/AppLayouts/Communities/panels/MembersTabPanel.qml
- ui/app/AppLayouts/Communities/panels/qmldir
- ui/app/mainui/activitycenter/panels/MembershipCta.qml
- ui/app/mainui/activitycenter/stores/ActivityCenterStore.qml
- ui/app/mainui/activitycenter/views/ActivityNotificationCommunityMembershipRequest.qml
- ui/app/mainui/activitycenter/views/qmldir
- ui/imports/shared/controls/DisabledTooltipButton.qml
- ui/imports/utils/Constants.qml
Closing #11770 
Changes:
1. Adding Accepted/Rejected Pending in activity notification and community members settings
2. Adding storybook pages for `ActivityNotificationCommunityMembershipRequest` and `MembersTabPanel`
3. Update the `MembershipCta` design for Accept/Reject buttons 
4. Adding the new states in nim
Can be tested only in Storybook.
Not handled in this PR:
1. Link the backend implementation for the new states
2. Accepted/Rejected Pending states can be changed only by the admin that initiated the request. In this case the other options needs to be hidden in the UI
Community members settings
Membership request notification
https://github.com/status-im/status-desktop/assets/47811206/b71fba82-5bb6-4052-abbe-1e3b8681b10b
> [Community] Accepting/Rejecting membership requests when control node is offline

- src/app/modules/main/chat_section/chat_content/users/module.nim
- src/app/modules/main/controller.nim
- src/app/modules/main/io_interface.nim
- src/app/modules/main/module.nim
- src/app/modules/shared_models/member_model.nim
- src/app/modules/shared_models/section_model.nim
- src/app_service/service/chat/dto/chat.nim
- src/app_service/service/community/async_tasks.nim
- src/app_service/service/community/dto/community.nim
- src/app_service/service/community/service.nim
- src/backend/communities.nim
- ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml
Fixes #11817
Instead of getting revealed accounts from the community description (it's no longer available), uses the new `getRevealedAccountsForAllMembers` API. Uses it async so that we do not slow the start process. The model is updated correctly when we finish loading them.
status-go PR: https://github.com/status-im/status-go/pull/3864
Screenshot shows a "hacked" version of the member downdown that shows that we indeed have the airdrop address
> feat(airdrop): get revealed accounts using new API instead of desc

- storybook/src/Models/WalletAccountsModel.qml
- ui/app/AppLayouts/Chat/ChatLayout.qml
- ui/app/AppLayouts/Communities/panels/MintTokensSettingsPanel.qml
- ui/app/AppLayouts/Communities/panels/SharedAddressesAccountSelector.qml
- ui/app/AppLayouts/Communities/panels/SharedAddressesPanel.qml
- ui/app/AppLayouts/Communities/popups/BurnTokensPopup.qml
- ui/app/AppLayouts/Communities/views/CommunityColumnView.qml
- ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml
- ui/app/AppLayouts/Communities/views/CommunityTokenView.qml
- ui/app/AppLayouts/Communities/views/EditCommunityTokenView.qml
- ui/app/AppLayouts/Communities/views/EditOwnerTokenView.qml
- ui/app/AppLayouts/Profile/views/CommunitiesView.qml
- ui/app/AppLayouts/Wallet/stores/RootStore.qml
- ui/app/AppLayouts/stores/RootStore.qml
- ui/imports/shared/popups/CommunityIntroDialog.qml
Closes #11829
It adds proxy of wallet accounts only in a single place (CommunitySettingsView.qml) and pass the tuned model through the rest of views.
Community Settings
> refactor(CommunitySettings): Add SFPM for wallet accounts model in a single place

- storybook/pages/SharedAddressesPopupPage.qml
- storybook/src/Models/PermissionsModel.qml
- ui/StatusQ/include/StatusQ/modelutilsinternal.h
- ui/StatusQ/include/StatusQ/permissionutilsinternal.h
- ui/StatusQ/src/modelutilsinternal.cpp
- ui/app/AppLayouts/Chat/ChatLayout.qml
- ui/app/AppLayouts/Chat/stores/RootStore.qml
- ui/app/AppLayouts/Communities/helpers/PermissionsHelpers.qml
- ui/app/AppLayouts/Communities/panels/SharedAddressesAccountSelector.qml
- ui/app/AppLayouts/Communities/panels/SharedAddressesPanel.qml
- ui/app/AppLayouts/Communities/panels/SharedAddressesPermissionsPanel.qml
- ui/app/AppLayouts/Communities/popups/SharedAddressesPopup.qml
- ui/app/AppLayouts/Profile/panels/CommunitiesListPanel.qml
- ui/app/mainui/AppMain.qml
- ui/app/mainui/Popups.qml
- makes `selectedSharedAddresses` and `selectedAirdropAddress` properties writable so that it's possible to pass these addresses to the popup upon opening
- makes the "Save" button change its icon and warning state based on the changes made
- `SharedAddressesPermissionsPanel` recalculates the overall and individual permission states based on modifications in the permissions model
- adds the possibility to start the whole "edit" flow from AppMain/Navbar context menu and Settings/Communities
- added some additional storybook models variations to simulate the loss of either channel or community level permissions (happens on unselecting all but last wallet address)
- added a C++ helper method `ModelUtilsInternal::isSameArray(a,b)` to compare JS 2D arrays for same elements
Actual …
> token-permissions: implement the UI "edit" flow for shared addresses

- storybook/pages/HoldingsDropdownPage.qml
- ui/app/AppLayouts/Communities/controls/ExtendedDropdownContent.qml
- ui/app/AppLayouts/Communities/controls/ListDropdownContent.qml
- ui/app/AppLayouts/Communities/popups/HoldingsDropdown.qml
- ui/app/AppLayouts/Communities/views/EditPermissionView.qml
Closes: #10546 
Changes in the Permissions design:
1. If the collectible is unique the amount input is disabled. 1 is auto-selected
2. Show `Max. 1` for unique tokens and empty string for other tokens
Changes in the Airdrop design:
1. Show `Max. 1` for unique tokens
Permissions
Airdrop
https://github.com/status-im/status-desktop/assets/47811206/cf3848f6-e1f9-45a5-9374-4b88850fc5e7
> fix(Permissions): Disable amount input for unique tokens + update amount indicator

- scripts/notarize-macos-pkg.sh
- scripts/sign-macos-pkg.sh
This now fails when the app is signed with a new certificate create from our new Apple organization but is not notarized:
```
tmp/macos/dist/Status.app: rejected
source=Unnotarized Developer ID
```
I actually have absolutely no idea why this verification worked with the old certificate, but it did.
For that reason I'm moving it to after notarization.
> sign-macos-pkg.sh: move gatekeeper verification

- storybook/pages/MembersTabPanelPage.qml
- test/ui-test/testSuites/suite_communities/shared/scripts/community_names.py
- ui/app/AppLayouts/Communities/panels/MembersTabPanel.qml
Closes: #11771 
This PR depends on https://github.com/status-im/status-desktop/pull/11820
Adding Ban pending and Kick pending states in the Community members settings - All members page.
Specifications: The `pending` state will be set by the backend if the control node is not online. If the state is pending no other option should be available for that specific member.
Members settings
https://github.com/status-im/status-desktop/assets/47811206/49767c55-f7aa-408d-b72d-58675d3b1a30
> Community kicking and banning members when control node is offline

- src/app/core/tasks/threadpool.nim
Same as https://github.com/status-im/status-desktop/pull/11911 but for master
> fix(threadpool): stop logging task args because they may contain pwd

- storybook/pages/AirdropsSettingsPanelPage.qml
- storybook/pages/MembersDropdownPage.qml
- storybook/src/Models/NetworksModel.qml
- ui/app/AppLayouts/Wallet/controls/NetworkFilter.qml
- ui/app/AppLayouts/Wallet/stores/NetworkSelectPopup/SingleSelectionInfo.qml
Fixes 2 problems, mainly visible when switching between test and non-test
networks:
- do not display network icons in single selection mode
- make really sure the default chain is Optimism
Separate commit to fix some other storybook run failures/issues
Fixes #11846
[Záznam obrazovky z 2023-08-15 14-07-23.webm](https://github.com/status-im/status-desktop/assets/5377645/5d9528a1-e35f-4c80-8eb2-73df40818a4b)
> fix(Mint token): Network selector not shown properly 

- src/app/modules/main/communities/tokens/io_interface.nim
- src/app/modules/main/communities/tokens/models/token_model.nim
- src/app/modules/main/communities/tokens/module.nim
- src/app/modules/main/communities/tokens/view.nim
- src/app_service/common/conversion.nim
- src/app_service/service/community_tokens/dto/community_token.nim
- storybook/pages/AirdropsSettingsPanelPage.qml
- storybook/pages/HoldingsDropdownPage.qml
- storybook/pages/InlineNetworksComboBoxPage.qml
- storybook/pages/TokenPanelPage.qml
- ui/StatusQ/src/StatusQ/Core/Utils/AmountsArithmetic.qml
- ui/app/AppLayouts/Communities/controls/InlineNetworksComboBox.qml
- ui/app/AppLayouts/Communities/controls/ListDropdownContent.qml
- ui/app/AppLayouts/Communities/controls/TokenPanel.qml
- ui/app/AppLayouts/Communities/helpers/PermissionsHelpers.qml
- ui/app/AppLayouts/Communities/helpers/TokenObject.qml
- ui/app/AppLayouts/Communities/panels/AirdropsSettingsPanel.qml
- ui/app/AppLayouts/Communities/panels/MintTokensSettingsPanel.qml
- ui/app/AppLayouts/Communities/panels/TokenInfoPanel.qml
- ui/app/AppLayouts/Communities/popups/BurnTokensPopup.qml
- ui/app/AppLayouts/Communities/popups/HoldingsDropdown.qml
- ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml
- ui/app/AppLayouts/Communities/views/EditAirdropView.qml
- ui/app/AppLayouts/Communities/views/EditCommunityTokenView.qml
- ui/app/AppLayouts/Communities/views/EditOwnerTokenView.qml
- ui/app/AppLayouts/Communities/views/EditPermissionView.qml
- ui/app/AppLayouts/Communities/views/MintedTokensView.qml
- ui/imports/shared/controls/AmountInput.qml
- ui/imports/shared/stores/CommunityTokensStore.qml
This PR refactors functionality of minting, airdrop and burn regarding handling fees. Provided earlier utilities `AmountsArithmetic` are used to handle amounts as big integers instead of floats. It prevents from problems described in https://github.com/status-im/status-desktop/issues/11376. Permissions functionality will be covered in a separate task.
Closes: #11491
Permissions part is going to be covered in a separate task: https://github.com/status-im/status-desktop/issues/11863
Multiple components for community settings, `AmountsArithmetic`
> chore(Communities): Refactor amounts handling for displaying, minting, airdropping and burning

- storybook/pages/RemotelyDestructPopupPage.qml
- ui/StatusQ/src/StatusQ/Core/Utils/ModelUtils.qml
- ui/app/AppLayouts/Communities/panels/MintTokensSettingsPanel.qml
- ui/app/AppLayouts/Communities/panels/TokenHoldersPanel.qml
- ui/app/AppLayouts/Communities/popups/RemotelyDestructPopup.qml
- ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml
- ui/imports/shared/stores/CommunityTokensStore.qml
Properly integrates `RemotelyDestructPopup` with the backend api. Fixes crash on selecting address for Remotely destruct action.
Closes: #11924
`RemotelyDestructPopup`, `MintTokensSettingsPanel`, `CommunitySettingsView`, `CommunityTokensStore`
[Kazam_screencast_00014.webm](https://github.com/status-im/status-desktop/assets/20650004/8849b859-d3f6-474c-b462-1ccda1050199)
> fix(Communities): Remotely destruct popup for regular collectibles integrated

- ui/app/AppLayouts/Communities/panels/MembersTabPanel.qml
- ui/app/mainui/activitycenter/panels/MembershipCta.qml
- ui/app/mainui/activitycenter/views/ActivityNotificationCommunityMembershipRequest.qml
Closing #11902 
When the control node is offline, the membership request cannot be processed. The admin can still accept/reject/kick/ban users, but the final action will be handled by the control node. This means we have new states for the membership request:
Accept pending; Reject pending; Kick pending; Ban pending; These states are set until the control node is online and the request is processed.
The admin that initiated the pending state can change his mind and change the pending state. Eg. When the request is in Accept pending, the admin that initiated the pending state can click on Reject and change the state to Reject pending.
This part is missing from backend.
The purpose of this PR it to hide the opposite action for all admins once the request is in pending state so that no admin …
> feat: Hide community membership request actions when the request is in action pending state

- src/nim_status_client.nim
Closing #10743
The root cause of this issue is still unknown to me. It can be reproduced while using the keycard to login. On most calls to status-keycard-go signal 16 will be triggered. Most of the times the signal handling works fine, but sometimes the signal handler is called outside of gsignal stack, goroutine scheduling stack, or sigaltstack. On some environments it happens quite often, on my environment it happens once every 10-50k calls to status-keycard-go.
Go is reporting the following error:
```
signal 16 received but handler not on signal stack
fatal error: non-Go code set up signal handler without SA_ONSTACK flag
```
Looking through go reported issues, I found 3 main reasons for this error:
1. Missing SA_ONSTACK on the sigaction - not in our case. When main is called there is …
> fix: Fixing MacOs arm64 crash on SIGURG signal

- ui/app/AppLayouts/Communities/controls/ListDropdownContent.qml
- ui/app/AppLayouts/Communities/helpers/PermissionsHelpers.qml
- ui/app/AppLayouts/Communities/popups/HoldingsDropdown.qml
- ui/app/AppLayouts/Communities/views/EditAirdropView.qml
- Remaining supply is used instead of supply for validating amount used for airdrop
- Remaining supply is displayed properly in TokenPanel (it was presented for collectibles but missing for assets)
- Presented amounts are properly localized
Now, validation should behave correctly in situation like the one described in https://github.com/status-im/status-desktop/pull/11862#issuecomment-1677585550
Closes: #11917
`HoldingsDropdown` and related subcomponents
[Kazam_screencast_00016.webm](https://github.com/status-im/status-desktop/assets/20650004/a4beb8ff-fd8c-46a6-b1cc-84eaa650408a)
> fix(Airdrop): Use remaining supply to display and validate amounts

- src/app_service/service/community/dto/community.nim
- src/app_service/service/community/service.nim
- src/backend/communities.nim
- ui/app/AppLayouts/Communities/panels/MembersSettingsPanel.qml
- ui/app/AppLayouts/Communities/panels/MembersTabPanel.qml
- ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml
- ui/imports/utils/Constants.qml
Fixes #11851
status-go PR: https://github.com/status-im/status-go/pull/3902
Hooks the new pending states for the requests to join to the UI. This starts by getting those requests on app start and adding them in the community cache.
Then, I also fixed a lot of mess with handling of community requests in the service.
Finally, I fixed a bug where an owner couldn't kick an admin.
> Hook pending join request backend to new UI

- src/app/modules/shared_models/link_preview_model.nim
- src/app_service/service/message/dto/link_preview.nim
- ui/imports/shared/views/chat/LinksMessageView.qml
- ui/imports/utils/Constants.qml
Closes https://github.com/status-im/status-desktop/issues/11634
Requires https://github.com/status-im/status-go/pull/3901
This PR adds support for new `type` property of link preview.
Image URLs are now unfurled again 🪄 
1. Unfortunately, this doesn't yet support GIF unfurling. I've opened a separate issue to track this:
- https://github.com/status-im/status-desktop/issues/11939
2. I was planning to update the image context menu to add `Copy/Open Link` instead of `Copy/Download Image`. 
But currently `StatusImageModal` is taking a whole `Image` component as an argument, so there's no "good" way of passing the link as well. This might require some refactoring. For now the URL in the text itself can still be clicked.
- https://github.com/status-im/status-desktop/issues/11941
Chat URL …
> feat: Support unfurl images

- src/app/modules/main/chat_section/chat_content/input_area/controller.nim
Fixes https://github.com/status-im/status-desktop/issues/11975
Only attach unfurled link previews (`hostname` not empty). 
Blindly sending all previews doesn't work, eventually no previews will be attached.
> Only send unfurled link previews

- src/app_service/service/transaction/service.nim
- src/backend/backend.nim
The multi-transaction ID was not propagated. The status-go change fixes this.
Bumps status-go [#3839](https://github.com/status-im/status-go/pull/3839)
> fix(wallet) duplicate entries in activity

- src/app/modules/main/chat_section/chat_content/messages/module.nim
We should at least keep the Chat Identifier _bogus message_ pinned up, as first message in the model.
Fixes #10889
> fix: clear chat history leaves user/channel page blank

- src/app/modules/main/communities/tokens/controller.nim
- src/app/modules/main/communities/tokens/io_interface.nim
- src/app/modules/main/communities/tokens/module.nim
- src/app/modules/main/communities/tokens/view.nim
- src/app_service/service/community_tokens/async_tasks.nim
- src/app_service/service/community_tokens/service.nim
- ui/app/AppLayouts/Communities/panels/MintTokensSettingsPanel.qml
- ui/imports/shared/stores/CommunityTokensStore.qml
Use address set in UI instead of deployer.
Fix #11827
The aim of this ticket is that the wallet address chosen in fees dialog will be used to pay for the operation.
From owner perspective it should not change anything. All operations should be doable.
More thorough testing will be done soon with @mprakhov when we check also master token holders.
Also there is an issue: https://github.com/status-im/status-desktop/issues/11929 which blocked good testing of the ticket because we do not see fees.
> fix(@desktop/communities): Pass addressFrom from UI to contract calls.

- ui/StatusQ/src/StatusQ/Core/LocaleUtils.qml
Use locale-neutral `getDayMonth()` plus the time part as there's no way to programatically check for date parts separator.
Fixes #10615
LocaleUtils
> fix(i18n): timestamp stripping year part

- src/app/modules/main/chat_section/chat_content/messages/module.nim
- src/app/modules/main/chat_section/module.nim
- src/app_service/service/community/dto/community.nim
- ui/app/AppLayouts/Chat/ChatLayout.qml
Fixes #11996
I was able to fix this by having a repro state on my release DB. I think in release mode, there was a race condition about permissions being checked too fast and creating the crash.
With these changes, I no longer experience the crash, though some of the crashes seemed very random, so further testing will be needed with a real build.
The changes I did here include:
- Stop checking for permissions as much
- We had verification-itis. We would call the function to check permissions in like 4 different places, so we'd check way too often
- The one i removed was that when creating the chat section, we'd call it on creation, then also on setting the chat active
- I kept only the one on set active
- I made sure that we only check permissions for members. Privileged users always …
> fix(crash): fix crash about community permissions

- storybook/src/Models/WalletAccountsModel.qml
- ui/app/AppLayouts/Chat/ChatLayout.qml
- ui/app/AppLayouts/Communities/views/CommunityColumnView.qml
- ui/app/AppLayouts/Communities/views/HoldingsSelectionModel.qml
- ui/app/AppLayouts/Profile/stores/WalletStore.qml
- ui/app/AppLayouts/Profile/views/CommunitiesView.qml
- ui/app/AppLayouts/Wallet/stores/RootStore.qml
- ui/app/AppLayouts/Wallet/views/TransactionDetailView.qml
- ui/app/AppLayouts/stores/RootStore.qml
- ui/app/mainui/Popups.qml
- rename `watchOnlyAccounts` to `nonWatchAccounts` to reflect what the property returns
- some warning fixes
Fixes #12023
Fixes wrong account colors and type
SharedAddressesAccountSelector
Accounts have the correct color and watch-only accounts are not displayed:
> fix(shared-addresses): wrong account color and type

- storybook/figma.json
- storybook/pages/BurnTokensPopupPage.qml
- ui/StatusQ/src/StatusQ/Controls/StatusRadioButton.qml
- ui/app/AppLayouts/Communities/popups/BurnTokensPopup.qml
- ui/imports/shared/controls/AmountInput.qml
- Support for non-integer values in `BurnTokensPopup`
- validation fixed
- Setting wrap to StatusRadioButton
- `AmountInput` - added possibility to customize err msg for exceeding max and label  and flag for zero as valid input
`BurnTokensPopup`, `StatusRadioButton`, `AmountInput`
[Kazam_screencast_00018.webm](https://github.com/status-im/status-desktop/assets/20650004/491422b2-ae86-4063-bfb6-5694979cc058)
> fix(BurnTokensPopup): Handle non-integer values for assets 

- ui/imports/shared/views/chat/ChatContextMenuView.qml
This was omitted in PR #11891, besides a LOG warning, it should have resulted in a failure to show a section line separator in the context menu when clearHistory is the sole option available, but it doesn't anyhow:
https://github.com/status-im/status-desktop/blob/17965d01952a303b2a6c3ea510d54f16cabdd109/ui/imports/shared/views/chat/ChatContextMenuView.qml#L199-L201
> Add missing object id for QML object

- ui/imports/utils/Constants.qml
Aligns UI constants with backend counterpart.
Closes: #12042 
`Constants.qml`
> fix(Communities): Align Constants.CommunityMembershipRequestState with backend

- storybook/pages/KickBanPopupPage.qml
- ui/app/AppLayouts/Communities/panels/MembersSettingsPanel.qml
- ui/app/AppLayouts/Communities/panels/MintTokensSettingsPanel.qml
- ui/app/AppLayouts/Communities/panels/SortableTokenHoldersPanel.qml
- ui/app/AppLayouts/Communities/popups/KickBanPopup.qml
- ui/app/AppLayouts/Communities/popups/qmldir
- ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml
- ui/app/AppLayouts/Communities/views/CommunityTokenView.qml
Closes: #11033
Integrates kick/ban actions with token holders list
Moreover:
- kick/ban popup refactored and moved to a separate file
- position of the popup fixed
- storybook page added
`MembersSettingsPanel`, `MintTokensSettingsPanel`
[Kazam_screencast_00022.webm](https://github.com/status-im/status-desktop/assets/20650004/0be2f96c-7359-426a-aaf0-6d31b420db89)
> feat(Communities): Integrate kick/ban actions with token holders list

- src/app/modules/main/profile_section/wallet/networks/controller.nim
- src/app/modules/main/profile_section/wallet/networks/io_interface.nim
- src/app/modules/main/profile_section/wallet/networks/module.nim
- src/app/modules/main/profile_section/wallet/networks/view.nim
- src/app_service/service/wallet_account/async_tasks.nim
- src/app_service/service/wallet_account/service_account.nim
- src/app_service/service/wallet_account/signals_and_payloads.nim
- storybook/pages/EditNetworkViewPage.qml
- ui/app/AppLayouts/Profile/stores/WalletStore.qml
- ui/app/AppLayouts/Profile/views/WalletView.qml
- ui/app/AppLayouts/Profile/views/wallet/EditNetworkForm.qml
- ui/app/AppLayouts/Profile/views/wallet/EditNetworkView.qml
…in rpc are the same
closes #11551
Implements https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=18442-531470&mode=dev when Main and Failover RPCS are the same
Profiel Wallet Networks Settings
https://github.com/status-im/status-desktop/assets/60327365/395bec13-76a3-46fc-bd2e-178354b79cc0
> fix(@desktop/wallet): Edit Networks: Add warning when failover and main rpc are the same

- src/app/modules/main/activity_center/model.nim
- src/app/modules/main/app_search/result_model.nim
- src/app/modules/main/chat_section/model.nim
- src/app/modules/main/communities/models/curated_community_model.nim
- src/app/modules/main/communities/models/discord_categories_model.nim
- src/app/modules/main/communities/models/discord_channels_model.nim
- src/app/modules/main/communities/models/discord_file_list_model.nim
- src/app/modules/main/communities/models/discord_import_tasks_model.nim
- src/app/modules/main/profile_section/ens_usernames/model.nim
- src/app/modules/main/profile_section/notifications/model.nim
- src/app/modules/main/profile_section/wallet/accounts/model.nim
- src/app/modules/main/stickers/models/sticker_list.nim
- src/app/modules/main/stickers/models/sticker_pack_list.nim
- src/app/modules/shared_models/member_model.nim
- src/app/modules/shared_models/message_model.nim
- src/app/modules/shared_models/message_reaction_model.nim
- src/app/modules/shared_models/section_model.nim
- src/app/modules/shared_models/token_permission_chat_list_model.nim
- src/app/modules/shared_models/token_permissions_model.nim
- src/app/modules/shared_models/user_model.nim
- src/app/modules/shared_modules/keycard_popup/models/keycard_model.nim
- src/app/modules/startup/models/fetching_data_model.nim
Closes #11996
I've found at lease 3 flows where the app is crashing, each one involving a SortFilterProxyModel on top of a nim model:
1. Reordering community channels
2. Reordering chats in chat column by receiving a new message or sending a message from/to a contact that is not the first one in the list.
The app is always crashing in `QQmlDelegateModel::_q_dataChanged(QModelIndex const&, QModelIndex const&, QVector<int> const&)` with different call stacks, in different flows. It appears that the model indexes used here are deleted too early.
The crash is generated by nim models using `dataChanged` event with a newly created QModelIndex. It seems the GC will collect this index too early.
The fix that appears to be working in these cases is to defer the QModelIndex.delete. I've added the …
> Fix: Crash when reordering community channels

- src/app/modules/main/communities/models/discord_categories_model.nim
- src/app/modules/main/communities/models/discord_channels_model.nim
- src/app/modules/main/communities/view.nim
- src/app_service/service/community/service.nim
- storybook/pages/CreateChannelPopupPage.qml
- ui/StatusQ/src/StatusQ/Controls/StatusButton.qml
- ui/StatusQ/src/StatusQ/Core/Theme/StatusDarkTheme.qml
- ui/StatusQ/src/StatusQ/Core/Theme/StatusLightTheme.qml
- ui/StatusQ/src/StatusQ/Core/Theme/ThemePalette.qml
- ui/app/AppLayouts/Chat/ChatLayout.qml
- ui/app/AppLayouts/Chat/views/ChatView.qml
- ui/app/AppLayouts/Communities/popups/CreateChannelPopup.qml
- ui/app/AppLayouts/Communities/popups/CreateCommunityPopup.qml
- ui/app/AppLayouts/Communities/popups/DiscordImportProgressContents.qml
- ui/app/AppLayouts/Communities/popups/DiscordImportProgressDialog.qml
- ui/app/AppLayouts/Communities/stores/CommunitiesStore.qml
- ui/app/AppLayouts/Communities/views/CommunityColumnView.qml
- ui/app/mainui/AppMain.qml
- ui/app/mainui/Popups.qml
Closes #12039
Implements the UI changes in CreateChannelPopup needed to be able to import a single Discord channel
CreateChannelPopup
[Záznam obrazovky z 2023-09-04 11-23-13.webm](https://github.com/status-im/status-desktop/assets/5377645/9c5ed0b2-34e5-4aa8-88d0-011f11b8968e)
> feat: Single discord channel import UI flow

- ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml
Fixes #12089
Added filter in collectibles airdrop's list:
- TMaster token will be shown ONLY if user is the community owner.
- Owner token is always hidden.
Community settings / Airdrop
- Member owning TMaster token:
- Community owner:
> fix(Airdrop): Update owner and tmaster tokens visualization in airdrop's list

- src/app/modules/main/browser_section/bookmark/model.nim
- src/app/modules/main/communities/models/curated_community_model.nim
- src/app/modules/main/profile_section/wallet/accounts/model.nim
- src/app/modules/main/wallet_section/send/network_model.nim
- src/app/modules/shared_models/link_preview_model.nim
- src/app/modules/shared_models/message_model.nim
- src/app/modules/shared_models/message_reaction_model.nim
- src/app/modules/shared_models/section_model.nim
- src/app/modules/shared_models/token_permissions_model.nim
- vendor/DOtherSide/lib/src/DOtherSide.cpp
When calling `QAIM.dataChanged(index, index, [roles])`, passing nothing (ie omitting the parameter altogether), an empty array `[]`, or an empty sequence `@[]` means "all roles", just like the C++ counterpart in https://doc.qt.io/qt-5/qabstractitemmodel.html#dataChanged
Depends on https://github.com/status-im/nimqml/pull/54
Fixes #11830
> feat: Passing an empty seq to dataChanged doesn't apply all roles

- ui/app/AppLayouts/Chat/panels/SuggestionFilterPanel.qml
- ui/app/AppLayouts/Chat/views/ChatColumnView.qml
Closes #11029
Enables "everyone" suggestion in group chat mentions box
group chat mentions box
https://github.com/status-im/status-desktop/assets/31625338/03903100-ac8e-4c92-95df-1c9de8c05e11
> fix(chat): enabled "everyone" in group chat mentions

- ui/app/AppLayouts/Chat/stores/CreateChatPropertiesStore.qml
- ui/app/AppLayouts/Chat/stores/RootStore.qml
- ui/app/AppLayouts/Chat/views/ChatColumnView.qml
- ui/app/AppLayouts/Chat/views/CreateChatView.qml
- ui/imports/shared/status/StatusChatInput.qml
The functionality for sending/receiving funds directly from chat is currently not supported, both code and designs are outdated. This commit removes integration part but leaves `ChatCommandsPopup` component for potential future use.
Related figma design:  https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?type=design&node-id=1335-145&mode=design&t=2k8OmchnCFOe6IRQ-0
Closes: #12118
`StatusChatInput`
> StatusChatInput: remove unmaintained integration with ChatCommandsPopup

- src/app/modules/main/profile_section/wallet/accounts/module.nim
- src/app_service/service/settings/service.nim
> fix(@desktop/wallet): the app crashes when receives "show/hide watch only" value from paired device

- ui/app/AppLayouts/Chat/stores/RootStore.qml
- ui/app/AppLayouts/Communities/panels/ProfilePopupInviteFriendsPanel.qml
- ui/app/AppLayouts/Communities/popups/CommunityProfilePopup.qml
- ui/app/AppLayouts/Communities/popups/TransferOwnershipPopup.qml
- ui/app/mainui/Popups.qml
- ui/imports/shared/status/StatusImageModal.qml
- ui/imports/shared/views/chat/ImageContextMenu.qml
- ui/imports/shared/views/chat/LinksMessageView.qml
- ui/imports/shared/views/chat/MessageView.qml
- ui/imports/utils/Global.qml
- ui/imports/utils/Utils.qml
Also moved copyToClipboard function in Utils
and updated Chat section to use it from there
Closes #11941
Updated image context menu to only show Copy link and Open link options
ImageContextMenu
https://github.com/status-im/status-desktop/assets/31625338/426e5e2b-c347-4f97-b942-e3ef86f24788
> fix(URLUnfurling): Updated image context menu

- storybook/pages/TokenListViewPage.qml
- ui/app/AppLayouts/Wallet/WalletLayout.qml
- ui/app/AppLayouts/Wallet/stores/RootStore.qml
- ui/app/AppLayouts/Wallet/views/RightTabView.qml
- ui/app/mainui/AppMain.qml
- ui/imports/shared/controls/CollectibleBackButtonWithInfo.qml
- ui/imports/shared/controls/SearchBoxWithRightIcon.qml
- ui/imports/shared/panels/HoldingItemSelector.qml
- ui/imports/shared/panels/HoldingSelector.qml
- ui/imports/shared/popups/SendModal.qml
- ui/imports/shared/stores/TransactionStore.qml
- ui/imports/shared/views/TokenListView.qml
fixes #12095
Implements https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=13540-381042&mode=design
To allow user to preselect a collectible from sendModal
SendModal
https://github.com/status-im/status-desktop/assets/60327365/464b84fa-09eb-462c-8721-ae0098b14f5d
> feat(@desktop/wallet): Enable Collectibles tab before token is selected

- src/app/modules/main/activity_center/model.nim
- src/app/modules/main/app_search/result_model.nim
- src/app/modules/main/chat_section/model.nim
- src/app/modules/main/communities/models/discord_categories_model.nim
- src/app/modules/main/communities/models/discord_channels_model.nim
- src/app/modules/main/communities/models/discord_file_list_model.nim
- src/app/modules/main/communities/models/discord_import_tasks_model.nim
- src/app/modules/main/profile_section/ens_usernames/model.nim
- src/app/modules/main/profile_section/notifications/model.nim
- src/app/modules/main/stickers/models/sticker_list.nim
- src/app/modules/main/stickers/models/sticker_pack_list.nim
- src/app/modules/main/wallet_section/send/network_model.nim
- src/app/modules/shared_models/member_model.nim
- src/app/modules/shared_models/message_model.nim
- src/app/modules/shared_models/section_model.nim
- src/app/modules/shared_models/token_permission_chat_list_model.nim
- src/app/modules/shared_models/user_model.nim
- src/app/modules/shared_modules/keycard_popup/models/keycard_model.nim
- src/app/modules/startup/models/fetching_data_model.nim
Cherrypick the fix for https://github.com/status-im/status-desktop/issues/11996 - Deferring the delete for nim QModelIndex
> Cherrypick: Fixing crash when reordering chats

- src/app/modules/main/communities/view.nim
- src/app/modules/main/controller.nim
- src/app/modules/main/io_interface.nim
- src/app/modules/main/module.nim
- src/app/modules/main/view.nim
- src/app/modules/shared_models/section_details.nim
- src/app/modules/shared_models/section_item.nim
While searching for what might be causing the crashes, I ran into the section_details item.
It is only used for the `activeSection` QVariant in the main module. Also, `activeSection` is only used for its `id`, `section_type` and `joined` properties, which makes sense, because sections that need more details than that already get it from the actual module it is in (eg the chat section or chat content).
Therefore, the section_details item contained a LOT of useless properties that were never used, but still kept in memory and edited on multiple events.
The biggest offenders where the member properties, because each contact event modified it.
Anyway, I don't think this will fix the crashes; that's why I didn't put it on top of the release branch. However, I do think it simplifies the code a …
> refactor(section_details): simplify section_details to only contain needed props

- ui/imports/shared/views/chat/ChatContextMenuView.qml
Since leaving a private group chat is not easily reversible, confirm the user's intent, just as we do with deleting chat history or a 1-to-1 chat.
Closes #11998
> feat(ChatContextMenu): Add confirmation dialog when the user tries to leave a group chat

- ui/StatusQ/src/StatusQ/Popups/StatusModal.qml
- ui/app/AppLayouts/Communities/controls/ColorPicker.qml
- ui/app/AppLayouts/Communities/panels/ColorPanel.qml
- ui/app/AppLayouts/Communities/popups/CreateChannelPopup.qml
Closes #9696
Permissions related stuff will be added in a separate PR (https://github.com/status-im/status-desktop/issues/12142)
Communities: updated channel color picker dialog as per design
Communities create/edit chat
[Záznam obrazovky z 2023-09-14 15-36-46.webm](https://github.com/status-im/status-desktop/assets/5377645/da2f02a1-88a3-4404-835f-91f3e8af1202)
> fix(Communities): fixed channel color picker dialog

- src/app/modules/main/communities/controller.nim
- src/app/modules/main/communities/io_interface.nim
- src/app/modules/main/communities/module.nim
- src/app/modules/main/communities/view.nim
- src/app/modules/main/controller.nim
- src/app/modules/main/profile_section/notifications/controller.nim
- src/app_service/service/community/service.nim
- src/backend/communities.nim
- storybook/figma.json
- storybook/pages/CommunityIntroDialogPage.qml
- storybook/pages/ExportControlNodePopupPage.qml
- storybook/pages/ImportControlNodePopupPage.qml
- storybook/pages/OverviewSettingsFooterPage.qml
- storybook/stubs/AppLayouts/Chat/stores/RootStore.qml
- ui/StatusQ/src/StatusQ/Controls/StatusTextWithLoadingState.qml
- ui/StatusQ/src/StatusQ/Core/StatusListView.qml
- ui/app/AppLayouts/Chat/stores/RootStore.qml
- ui/app/AppLayouts/Communities/panels/OverviewSettingsFooter.qml
- ui/app/AppLayouts/Communities/panels/OverviewSettingsPanel.qml
- ui/app/AppLayouts/Communities/popups/ExportControlNodePopup.qml
- ui/app/AppLayouts/Communities/popups/ImportControlNodePopup.qml
- ui/app/AppLayouts/Communities/stores/CommunitiesStore.qml
- ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml
- ui/app/mainui/AppMain.qml
- ui/app/mainui/Popups.qml
- ui/imports/utils/Global.qml
Implement the UI part of the new flow for moving community control nodes w/o involving private keys
Clean up the now redundant removal of private keys
~~The final notification will be handled separately in issue: https://github.com/status-im/status-desktop/issues/12147~~
Closes #12088
CommunitySettingsView, ExportControlNodePopup, ImportControlNodePopup, OverviewSettingsFooter
Not control node:
Control node:
Export:
Export 2:
Export with some synced devices:
Import:
> feat(community ownership): Move community control node flow UI

- storybook/pages/SharedAddressesPopupPage.qml
- ui/app/AppLayouts/Communities/panels/SharedAddressesAccountSelector.qml
compare the addresses to share in a case insensitive manner
Fixes #12152
Fixes shared addresses handling
SharedAddressesPopup
[Záznam obrazovky z 2023-09-18 12-25-36.webm](https://github.com/status-im/status-desktop/assets/5377645/54a7ba0d-65c2-493b-bc72-fb2dc57d6278)
> fix(shared addresses) wallet address selection broken

- src/app_service/service/message/service.nim
Fixes #12195
It fixes the crash when pinning a message, but should also affect other calls that use `getMessageByMessageId`
> fix(message/service): fix crash on missing assignment of MessageResult

- storybook/pages/FeeRowPage.qml
- storybook/pages/StatusMessagePage.qml
- ui/StatusQ/src/StatusQ/Components/private/statusMessage/StatusMessageReply.qml
- ui/StatusQ/src/StatusQ/Components/private/statusMessage/StatusTextMessage.qml
- ui/StatusQ/src/StatusQ/Core/StatusIdenticonRingSettings.qml
- fixes the missing/broken gradient mask behind the original message in a reply
- improve the respective storybook page
- some minor cleanups/fixes
Fixes #11385
StatusMessageReply
Before:
After:
Storybook:
> fix: Gradient mask of replied message doesn't work

- storybook/pages/TransferOwnershipPopupPage.qml
- ui/app/AppLayouts/Chat/ChatLayout.qml
- ui/app/AppLayouts/Communities/panels/MintTokensFooterPanel.qml
- ui/app/AppLayouts/Communities/panels/MintTokensSettingsPanel.qml
- ui/app/AppLayouts/Communities/panels/OverviewSettingsPanel.qml
- ui/app/AppLayouts/Communities/panels/ProfilePopupOverviewPanel.qml
- ui/app/AppLayouts/Communities/popups/CommunityProfilePopup.qml
- ui/app/AppLayouts/Communities/popups/TransferOwnershipPopup.qml
- ui/app/AppLayouts/Communities/views/CommunityColumnView.qml
- ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml
- ui/app/mainui/AppMain.qml
- ui/app/mainui/Popups.qml
- ui/imports/utils/Global.qml
Closes [#12171](https://github.com/status-im/status-desktop/issues/12171)
- Removed old transfer ownership flows.
- Applied new design to transfer ownership popup.
- Added support in storybook.
- Added navigation to transfer ownership popup from community settings / owner token footer.
- Added navigation to transfer ownership popup from community settings / overview.
- Linked wallet send modal to the transactions popup with the needed pre-populated data.
Community Settings / Overview & Tokens
https://github.com/status-im/status-desktop/assets/97019400/1d60d864-27a6-4c36-9491-c9002479a9a7
https://github.com/status-im/status-desktop/assets/97019400/4f5e8cdc-21c2-4b73-9861-20b8ae28e63c
> feat(TransferOwnershipPopup): Updated transfer ownership popup according to new design

- src/app_service/service/message/async_tasks.nim
- storybook/figma.json
- storybook/pages/UserProfileCardPage.qml
- ui/imports/shared/controls/chat/UserProfileCard.qml
- ui/imports/shared/controls/chat/qmldir
- ui/imports/shared/views/chat/LinksMessageView.qml
- ui/imports/shared/views/chat/MessageView.qml
Closing #10585 
Adding the new user profile cards and temporarily enable the user profile preview using the old unfurling mechanism.
Link previews
> feat: Adding new user profile cards for link previews

- src/app/modules/main/wallet_section/activity/controller.nim
The optimization was breaking testnet enabled use case by showing the cached activity for all chains ignoring the testnet on/off flag
> fix(wallet) remove optimization for all chains selected

- src/app/modules/main/wallet_section/send/io_interface.nim
- src/app/modules/main/wallet_section/send/module.nim
- src/app/modules/main/wallet_section/send/network_model.nim
- src/app/modules/main/wallet_section/send/view.nim
- ui/imports/shared/popups/send/SendModal.qml
- ui/imports/shared/popups/send/views/RecipientView.qml
- ui/imports/shared/popups/send/views/TabAddressSelectorView.qml
- ui/imports/shared/stores/send/TransactionStore.qml
fix(@desktop/wallet): SendModal: Move logic to nim Part 2, parsing recipient address string to separate the chain prefixes
fixes #12149
Move logic for parsing recipient text to nim side
SendModal
> fix(@desktop/wallet): SendModal: Move logic to nim Part 2, parsing recipient address string to separate the chain prefixes

- ui/StatusQ/src/StatusQ/Core/Utils/Utils.qml
- ui/app/AppLayouts/Communities/controls/TokenHolderListItem.qml
- ui/app/AppLayouts/Communities/panels/MintTokensSettingsPanel.qml
- ui/app/AppLayouts/Communities/panels/SortableTokenHoldersPanel.qml
- ui/app/AppLayouts/Communities/popups/TokenMasterActionPopup.qml
- ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml
- ui/app/AppLayouts/Communities/views/CommunityTokenView.qml
- ui/imports/shared/stores/CommunityTokensStore.qml
- Integrates `TokenMasterActionPopup` and sign popup for:
- remotely destruct - the same API as for regular tokens, currently fully working
- kick - the action not implemented on the backend (remotelyDestructAndKick)
- ban - the action not implemented on the backend (remotelyDestructAndBan)
- Displays elided wallet address when contact name is not available in case of remotely destruct
Closes: https://github.com/status-im/status-desktop/issues/12066
`MintTokensSettingsPanel`
[Kazam_screencast_00032.webm](https://github.com/status-im/status-desktop/assets/20650004/b86951a0-b9dc-4967-a6ae-90960ebd59d3)
> feat(CommunitySettingsView): Integrate Kick/Ban/Destruct popups for TokenMaster

- storybook/figma.json
- storybook/pages/TransferOwnershipAlertPopupPage.qml
- ui/app/AppLayouts/Communities/panels/OverviewSettingsPanel.qml
- ui/app/AppLayouts/Communities/popups/TransferOwnershipAlertPopup.qml
- ui/app/AppLayouts/Communities/popups/qmldir
- ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml
Closes #12173
It opens information popups when community owner token is still not created:
- From Overview / Transfer ownership button
- From Overview / How to move control node button
Community Settings / Overview + Tokens
https://github.com/status-im/status-desktop/assets/97019400/cf5b0503-0faf-4837-a9c6-47da7bcffc7c
> feat(TransferOwnershipAlertPopup): Add information popups when owner token is not created yet

- ui/imports/shared/status/StatusChatInput.qml
Currently, large text clipboard paste's are silently cut off if beyond 2000 (Waku?) character count limit.
Change the way we handle large messages in the StatusChatInput by:
1. Introducing three text limits:
https://github.com/status-im/status-desktop/blob/7b0c45a14a122e67e5721e86e4ae05d5596a1b33/ui/imports/shared/status/StatusChatInput.qml#L49-L51
2. Disable sending the message via `Return ↵` key if current text in the input control is beyond the `2000` character limit. A popup is displayed from the message character counter to inform the user of that.
3. When the user reaches the `1800` character limit, via typing or pasting text, the char counter is displayed. The counter is orange for the last `200` characters, then red when negative (beyond `2000` limit). The char counter label goes …
> fix(StatusChatInput): New handler method for large messages in StatusChatInput

- src/app/core/signals/remote_signals/community.nim
- src/app/core/signals/remote_signals/signal_type.nim
- src/app/core/signals/signals_manager.nim
- src/app/modules/main/communities/controller.nim
- src/app_service/service/community/service.nim
Fixes #12207
Adds support for the "unknown signal". This removes the spam, as we just do something with it now.
I also upped the timer for unknown communities to 1 minute instead of 3 seconds. https://github.com/status-im/status-go/pull/4046#pullrequestreview-1633952634
> fix(curated_communities): support curated.communities.update signal

- ui/imports/utils/Tracer.qml
Slightly simplifies implementation of Tracer component by using Timer instead of Animation. Needed for publishing Tweet about that utility :)
`Tracer`
> chore(Tracer): Simplify by using Timer instead of Animation

- ui/imports/shared/status/StatusChatInput.qml
The issue looks related to the recent conversion of `StatusChatInput` to a *resident* like control, where text, reply and image attachment data is persistent across the two types of chat modules, regular and community chats, and is restored when switching between the two types of chat.
After some investigation, the simplest fix, is to allow image drops only in the currently visible `StatusChatInput` control.
https://github.com/status-im/status-desktop/assets/544446/5f149c43-0b48-426c-812c-77e0d080f92b
Fixes #10885
> fix(StatusChatInput): Sent message image attachment persists when changing chat types

- test/ui-test/testSuites/global_shared/scripts/settings_names.py
- ui/StatusQ/include/StatusQ/stringutilsinternal.h
- ui/StatusQ/src/StatusQ/Components/StatusNavigationListItem.qml
- ui/StatusQ/src/StatusQ/Components/StatusToolBar.qml
- ui/StatusQ/src/StatusQ/Core/Utils/StringUtils.qml
- ui/StatusQ/src/plugin.cpp
- ui/StatusQ/src/stringutilsinternal.cpp
- ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml
- ui/app/AppLayouts/Profile/ProfileLayout.qml
- ui/app/AppLayouts/Profile/panels/MenuPanel.qml
- ui/app/AppLayouts/Profile/views/AboutView.qml
- ui/app/AppLayouts/Profile/views/AppearanceView.qml
- ui/app/AppLayouts/Profile/views/LanguageView.qml
- ui/app/AppLayouts/Profile/views/LeftTabView.qml
- ui/app/AppLayouts/Profile/views/MyProfileView.qml
- ui/app/AppLayouts/Profile/views/SettingsContentBase.qml
- ui/app/AppLayouts/Profile/views/wallet/EditNetworkView.qml
- ui/generate-rcc.go
- ui/imports/assets/docs/privacy.mdwn
- ui/imports/assets/docs/terms-of-use.mdwn
- ui/imports/shared/panels/StyledText.qml
- ui/imports/utils/Constants.qml
- bundle Privacy Statement and Terms of Use documents as Markdown
- some UI fixes according to latest Figma
- separate 2 commits for providing a C++ helper to read contents of a text file and additional UI fixes for the overall Settings layout (most notable left margin and icon size)
Fixes #12192
Settings/About
Terms of use MD:
Privacy statement MD:
> feat(settings): add Privacy Statement and Terms of Use 

- ui/app/AppLayouts/Communities/popups/TransferOwnershipPopup.qml
- ui/app/AppLayouts/Wallet/WalletLayout.qml
- ui/app/AppLayouts/Wallet/panels/WalletFooter.qml
- ui/app/AppLayouts/Wallet/stores/RootStore.qml
- ui/app/AppLayouts/Wallet/views/CollectiblesView.qml
- ui/app/AppLayouts/Wallet/views/collectibles/CollectibleDetailView.qml
- ui/app/mainui/AppMain.qml
- ui/imports/shared/popups/send/SendModal.qml
Closes #12172
It needes https://github.com/status-im/status-desktop/pull/12219
- It updates `CollectibleDetailsView` to show **owner** and **tMaster** token collectible types with the correct design.
- It updates `CollectiblesView` to show **owner** and **tMaster** token collectible types with the correct design.
- It modifies send footer option if collectible selected is an owner token.
- It adds needed logic in wallet rootstore to handle selected collectible object data.
Wallet / Collectibles
https://github.com/status-im/status-desktop/assets/97019400/d0908596-d8ec-4459-9b5b-f5fb12c7b84e
> feat(CommunityOwnership): Add transfer ownership popup flow from wallet collectible view

- src/app/modules/main/network_connection/view.nim
- src/app_service/service/network_connection/service.nim
- src/backend/collectibles.nim
- src/backend/connection_status.nim
- ui/app/mainui/AppMain.qml
- ui/imports/shared/panels/ConnectionWarnings.qml
- ui/imports/shared/stores/NetworkConnectionStore.qml
Fixes #11636
status-go part: https://github.com/status-im/status-go/pull/4066
Implements the connection error banner for Collectibles, as per https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=18105-123946&mode=design&t=ImrRpdHoBnXhPhFf-0
https://github.com/status-im/status-desktop/assets/11161531/6e324a26-7c1b-40ba-a37b-fe53ac2b6019
> feat(@desktop/wallet): implement collectibles error states and retry

- src/app/modules/shared_models/collectible_details_entry.nim
- src/app/modules/shared_models/collectibles_utils.nim
- ui/app/AppLayouts/Wallet/WalletLayout.qml
- ui/app/AppLayouts/Wallet/views/CollectiblesView.qml
- ui/app/AppLayouts/Wallet/views/collectibles/CollectibleDetailView.qml
- ui/app/AppLayouts/Wallet/views/collectibles/CollectibleView.qml
Fixes https://github.com/status-im/status-desktop/issues/12286
- Updated default value for `communityPrivilegesLevel` to `2 = Community`.
- Added `communityId` checker in `CollectiblesView`, `CollectibleDetailView` and `WalletLayout`.
Wallet / Collectibles
> fix(Wallet/Collectibles): Applied special collectible format only to community special collectibles

- src/backend/community_tokens.nim
Fix wrong status-go calls.
Rename from "collectibles_" to "communitytokens_".
Fix #12270 
All names are ok in master. Probably some mismatch when merging to 0.14.
> fix(@desktop/communities): Fix communitytokens status-go calls

- src/app/modules/startup/internal/user_profile_confirm_password_state.nim
The import process never worked correctly. It seemed like it was never fetching anything from store nodes.
Well it was a simple boolean that was missing. Without it, we ignore the backup messages when we receive messages from mailserver.
> fix(backup): fix import not setting recoverAccount so backup wasn't used

- ui/app/AppLayouts/Profile/controls/WalletNetworkDelegate.qml
Adding object name for easier reference by automation
`WalletNetworkDelegate.qml`
> chore(@WalletNetworkDelegate.qml): add objectname for text label

- Makefile
Accept `true` and `1` as values for TEST_ENVIRONMENT variable for keycard mock lib
Keycard mock lib
> chore(@keycard makefile): extend condition to accept env variable as true and 1 values

- src/app/modules/main/wallet_section/activity/controller.nim
- ui/app/AppLayouts/Wallet/panels/ActivityFilterPanel.qml
- ui/app/AppLayouts/Wallet/stores/ActivityFiltersStore.qml
- ui/app/AppLayouts/Wallet/stores/RootStore.qml
- ui/app/AppLayouts/Wallet/views/RightTabView.qml
- ui/app/AppLayouts/Wallet/views/TransactionDetailView.qml
- ui/app/mainui/AppMain.qml
- ui/imports/shared/popups/send/Helpers.qml
- ui/imports/shared/popups/send/SendModal.qml
- ui/imports/shared/popups/send/qmldir
- ui/imports/shared/popups/send/views/RecipientView.qml
- ui/imports/shared/views/HistoryView.qml
Enable user action to repeat a Send transaction from the activity view (HistoryView) and details view (TransactionDetailView).
Extend AppMain send modal entry and SendModal API to allow for selecting all the required parameters for repeating a transaction.
Optimize the update of the start timestamp for the activity filter only when a user attempts to open the filter panel.
> feat(wallet) user can repeat a Send transaction from activity view

- src/app/modules/main/module.nim
- src/app/modules/main/view.nim
- src/app/modules/main/wallet_section/send/network_model.nim
- ui/app/AppLayouts/stores/RootStore.qml
- ui/app/mainui/AppMain.qml
- ui/imports/shared/popups/send/SendModal.qml
fix(@desktop/wallet): Wallet: Send a multi tx, the notification for the 2nd transfer is not visible
fixes #12242
in case 2 transactions were made to complete a send, the 2nd tx would not show up as an ephemeral toast because the sendModal was closed after the first notification was shown.
Hence iv moved the logic of showing the toast via the AppMain.qml instead
SendModal
https://github.com/status-im/status-desktop/assets/60327365/54025ad2-5163-414f-a35c-a8635f6d59f0
> fix(@desktop/wallet): Wallet: Send a multi tx, the notification for the 2nd transfer is not visible

- src/app/modules/main/controller.nim
- src/app/modules/main/io_interface.nim
- src/app/modules/main/module.nim
- src/app/modules/shared_models/section_model.nim
- src/app_service/service/community_tokens/async_tasks.nim
- src/app_service/service/community_tokens/dto/community_token.nim
- src/app_service/service/community_tokens/service.nim
Fixes #11808
The problem was that when creating and editing communities, we get the community tokens and all the details about it. The thing is, those fetches were all done sync, and half of them needed to go to status-go for it.
I fixed it by making those operations async.
> fix: community freezes when editing because of sync operations

- ui/imports/shared/popups/send/controls/TokenBalancePerChainDelegate.qml
- ui/imports/shared/popups/send/panels/HoldingItemSelector.qml
1. A dropdown arrow should not be visible in the context of selecting token
2. Unnecessary padding added when expanding balances in the send modal popup
fixes #12254,#12256
Read above.
SendModal
https://github.com/status-im/status-desktop/assets/60327365/aa98d9f9-955c-4a67-85c5-2e72813075ad
> fix(@deaktop/wallet): fixes below issues in sendModal:

- ci/Jenkinsfile.combined
- ci/Jenkinsfile.linux
- ci/Jenkinsfile.macos
- ci/Jenkinsfile.tests-e2e
- ci/Jenkinsfile.tests-imports
- ci/Jenkinsfile.tests-nim
- ci/Jenkinsfile.tests-statusq
- ci/Jenkinsfile.windows
- ci/cpp/Jenkinsfile.linux
- ci/cpp/Jenkinsfile.macos
- ci/cpp/Jenkinsfile.windows
They are split by both platform and build type.
Depends on:
* https://github.com/status-im/status-jenkins-lib/pull/74
> ci: use new OpenSea API keys

- storybook/main.cpp
- storybook/main.qml
- storybook/pagesmodel.cpp
- storybook/pagesmodel.h
- storybook/sectionsdecoratormodel.cpp
- storybook/sectionsdecoratormodel.h
- storybook/tests/tst_SectionsDecoratorModel.cpp
- watch pages directory for changes, notify add/remove and metadata change (read from the file)
- handle changes from pages model in a proxy model providing sections decoration
- add convenience button for opening pages directory
Closes: #12216
Closes: #12271
`PagesModel`, `SectionsDecoratorModel`, storybook's `main.cpp`/``main.qml`
[Kazam_screencast_00035.webm](https://github.com/status-im/status-desktop/assets/20650004/5f0051f6-e577-4d8f-b69b-cee82a0ae203)
> Storybook: track pages directory on the fly

- src/app/global/local_app_settings.nim
- storybook/figma.json
- storybook/pages/CommunityInfoEditor.qml
- storybook/pages/EditSettingsPanelPage.qml
- storybook/pages/EnableShardingPopupPage.qml
- storybook/pages/ManageShardingPopupPage.qml
- storybook/pages/OverviewSettingsPanelPage.qml
- storybook/stubs/shared/stores/RootStore.qml
- ui/StatusQ/src/StatusQ/Controls/StatusBaseInput.qml
- ui/StatusQ/src/StatusQ/Controls/StatusCheckBox.qml
- ui/StatusQ/src/StatusQ/Controls/StatusTextArea.qml
- ui/StatusQ/src/StatusQ/Core/StatusAnimatedStack.qml
- ui/StatusQ/src/StatusQ/Popups/StatusStackModal.qml
- ui/app/AppLayouts/Communities/panels/EditSettingsPanel.qml
- ui/app/AppLayouts/Communities/panels/OverviewSettingsPanel.qml
- ui/app/AppLayouts/Communities/popups/EnableShardingPopup.qml
- ui/app/AppLayouts/Communities/popups/ManageShardingPopup.qml
- ui/app/AppLayouts/Communities/popups/qmldir
- ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml
- ui/app/AppLayouts/Profile/stores/AdvancedStore.qml
- ui/app/AppLayouts/Profile/views/AdvancedView.qml
- ui/imports/shared/popups/ImportCommunityPopup.qml
Implement the UI flow for enabling static sharding for owned communities and manage the respective community's shard index
Best review commit by commit, there are additional fixes to various components
Fixes https://github.com/status-im/status-desktop/issues/12197
changed: CommunitySettingsView, Community/OverviewSettingsPanel, Community/EditSettingsPanel
new: EnableShardingPopup, ManageShardingPopup
Master switch to enable creation and manage sharded communities:
Edit community settings with sharding disabled:
Enabling a dedicated sharding index:
[Enabling a dedicated sharding index](https://github.com/status-im/status-desktop/assets/5377645/227b15f8-749b-4be7-ba20-1a0cfe0f1a5b)
Manage the sharding index, disable:
[Manage the sharding index, …
> [Community sharding] UI to enable static sharding for a community

- src/app/modules/main/communities/controller.nim
- src/app/modules/main/communities/io_interface.nim
- src/app/modules/main/communities/module.nim
- src/app/modules/main/module.nim
- src/app/modules/shared_models/token_list_model.nim
- src/app_service/service/community_tokens/async_tasks.nim
- src/app_service/service/community_tokens/service.nim
Fixes [#12032](https://github.com/status-im/status-desktop/issues/12032)
- only call getCommunityTokens once per community: we used to call it each time the wallet updated
- use async getCommunityTokens for list creation
We still use `getCommunityTokens` sync in some places, but they happen more rarely and are harder to make async
> Reduce number of calls to `buildTokensAndCollectibles` and use an async function on init

- src/app_service/service/community_tokens/async_tasks.nim
- src/app_service/service/community_tokens/service.nim
Fix #12315
Crash was caught during application startup.
Some exceptions were of different type than RpcException and were not caught.
> fix(@desktop/communities): Catch all exceptions

- src/app/core/notifications/details.nim
- src/app/core/notifications/notifications_manager.nim
- src/app/global/global_events.nim
- src/app/modules/main/chat_section/module.nim
- src/app/modules/main/module.nim
- src/app_service/service/contacts/service.nim
Show a toast notification when a contact is removed by the user. This is in addition to the system message displayed in the message view.
Fixes #10497
> fix(messenger_contacts): Add toast notification when removing a contact

- storybook/figma.json
- storybook/pages/FinaliseOwnershipDeclinePopupPage.qml
- storybook/pages/FinaliseOwnershipPopupPage.qml
- storybook/pages/OverviewSettingsFooterPage.qml
- storybook/pages/OverviewSettingsPanelPage.qml
- ui/app/AppLayouts/Chat/ChatLayout.qml
- ui/app/AppLayouts/Chat/views/ChatView.qml
- ui/app/AppLayouts/Communities/controls/FeesBoxFooter.qml
- ui/app/AppLayouts/Communities/helpers/SingleFeeSubscriber.qml
- ui/app/AppLayouts/Communities/helpers/TransactionFeesBroker.qml
- ui/app/AppLayouts/Communities/panels/FeesBox.qml
- ui/app/AppLayouts/Communities/panels/OverviewSettingsFooter.qml
- ui/app/AppLayouts/Communities/panels/OverviewSettingsPanel.qml
- ui/app/AppLayouts/Communities/popups/FinaliseOwnershipDeclinePopup.qml
- ui/app/AppLayouts/Communities/popups/FinaliseOwnershipPopup.qml
- ui/app/AppLayouts/Communities/popups/qmldir
- ui/app/AppLayouts/Communities/views/CommunityColumnView.qml
- ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml
- ui/imports/shared/stores/CommunityTokensStore.qml
Closes #12174 
- Created finalise popup and added it into storybook.
- Decline popup created and added support in storybook.
- Itegration of the finalise flow in the app from: community column button and from community overview footer button.
- Updated storybook pages (settings overview related) according to new components requirements.
**NOTE: Only UI, backend not ready. Navigation from activity center not covered (missing backend).**
Community Column / Community Overview
- App:
https://github.com/status-im/status-desktop/assets/97019400/56053dec-3d61-4d67-afff-7558f8d7d94c
- Storybook:
https://github.com/status-im/status-desktop/assets/97019400/ab124bc0-2709-483a-ab1e-1fdae4b3c6cc
https://github.com/status-im/status-desktop/assets/97019400/ac1b397d-e3d2-4355-a09c-a513a8263bd3
> feat(CommunityOwnership): Finalise ownership UI flows

- src/app_service/common/network_constants.nim
- src/app_service/service/node_configuration/dto/node_config.nim
This PR enables Filter Full Node so desktop nodes can push messages to other nodes, and this way not depend only on the status fleet
Requires:
- https://github.com/status-im/status-go/pull/4071
> feat: enable filter full node by default

- ui/app/AppLayouts/Profile/views/wallet/EditNetworkForm.qml
I need to access main input object so i can grab the error messages later on
`ui/app/AppLayouts/Profile/views/wallet/EditNetworkForm.qml`
> chore(@EditNetworkForm.qml): add object names to main input objects

- ci/Jenkinsfile.linux
There is no need for this fix since this was resolved in:
* https://github.com/status-im/infra-ci/issues/88
* https://github.com/status-im/status-desktop/pull/11955
> chore(ci): drop temporary Nim client build fix

- src/app_service/service/wallet_account/dto/balance_dto.nim
Accept the balances to be "nil" in the BalanceDTO.
In some corner-cases, the balances are returned with rawBalance as `<nil>` which can't be parsed as a valid `Int256`;
This side-effect was introduced with this change: https://github.com/status-im/status-go/pull/4030
`<nil>` is not a valid JSON value, so this is still a workaround.
> fix(wallet) forever loading balances

- ui/app/AppLayouts/Onboarding/views/ProfileFetchingView.qml
- ui/app/AppLayouts/Profile/controls/WalletAccountDetailsKeypairItem.qml
- ui/app/AppLayouts/Wallet/panels/WalletHeader.qml
- ui/app/AppLayouts/Wallet/views/AccountContextMenu.qml
- ui/imports/utils/Utils.qml
fix(@desktop/wallet): Replaced watched-only with watched address/addresses text as per 2nd point in https://github.com/status-im/status-desktop/issues/11675
Walet Settings and Wallet view where we use watch-only keywords
> fix(@desktop/wallet): Replaced watched-only with watched address/addresses text

- src/app/modules/main/communities/controller.nim
- src/app_service/service/community/service.nim
- ui/app/mainui/AppMain.qml
Related to https://github.com/status-im/status-go/pull/4110
1. Fix error signalling in `asyncCommunityInfoLoaded`
This allows you to try again!
2. Add `communityId` argument to fails, because `community` is empty
3. In `onImportingCommunityStateChanged` only get community data in success case
> fix: process community info requests fails

- ui/imports/shared/controls/chat/LinkPreviewCard.qml
- ui/imports/shared/views/chat/ImageContextMenu.qml
- ui/imports/shared/views/chat/LinksMessageView.qml
- also fix the issue of not having the respective image context menu for the new unfurled links component
- open the resulting link using a centralized `Global.openLink(url)`
Fixes #12183
Fixes context menu for image-like elements
LinksMessageView,ImageContextMenu
New unfurled component:
Regular message context menu:
GIF context menu:
> fix: Add Copy/Open Link as context menu actions on GIF message previews

- ui/app/AppLayouts/Onboarding/views/ProfileFetchingView.qml
Fixes #10939
Following the design, it does not include a scroll bar as all rows and button can fit in the minimum window height, but the content was not centered correctly when the application is resized. So fixed that point in here.
Onboarding / Fetch data screen
https://github.com/status-im/status-desktop/assets/97019400/85ba91f9-b865-4e72-986c-cb889748bae4
> fix(Onboarding): Recover from seed - Fetching data screen layout

- ui/app/AppLayouts/Profile/stores/AdvancedStore.qml
- ui/app/AppLayouts/Profile/views/AdvancedView.qml
- ui/app/mainui/AppMain.qml
Fixes #12276
It adds a new switch in `Settings/Advanced` to **enable community management** on testnet.
**NOTE:** The state of the change is managed only in qml, so the state will not persist from one instance to another. It will always be initialized as `disabled`. We agreed with the **QA team** that this is a sufficient solution for the tests purpose.
Settings / Advanced
> feat(Advanced): Add toggle to enable managing community on testnet

- storybook/qmlTests/TestComponents/tst_DerivationPathInput.qml
- storybook/qmlTests/TestComponents/tst_StatusChatInput.qml
Part of #10842. This PR is just unblocking the task to add qml tests to the CI by either skipping or fixing tests. #10842 will be closed once the qml tests are properly fixed.
`test_successfulInitializationOfControllerBeforeItem` - Test is failing due to API change
`test_keyboard_mentions_input` - Test is unstable, failing randomly. The app seems to be fine
`test_mention_is_selected_by_keyboard` - Test is unstable, failing randomly. Sometimes there is no selection
`test_mention_cannot_be_invalidated` - App bug. Test is disabled until the app is fixed. New issue created #12394
`test_mention_is_deleted_with_large_selection` - Unstable test. App seems to be fine.
`test_text_mention_emoji_input ` - Unstable test. Failing randomly
`test_mention_is_skipped_by_cursor` - Unstable test. Failing …
> chore: Fix or skip Storybook qml tests

- src/app/modules/shared_modules/collectibles/controller.nim
- src/backend/collectibles.nim
Fixes #9823
status-go part: https://github.com/status-im/status-go/pull/4127
Implements collectibles re-fetch when an NFT transfer is detected
> feat: trigger collectibles refresh on transfer

- src/app_service/service/privacy/service.nim
- ui/StatusQ/include/StatusQ/stringutilsinternal.h
- ui/StatusQ/src/StatusQ/Controls/StatusCheckBox.qml
- ui/StatusQ/src/StatusQ/Core/Utils/StringUtils.qml
- ui/StatusQ/src/stringutilsinternal.cpp
- ui/app/mainui/AppMain.qml
- ui/app/mainui/Popups.qml
- ui/imports/shared/popups/ConfirmExternalLinkPopup.qml
- ui/imports/shared/popups/qmldir
- ui/imports/shared/views/chat/LinksMessageView.qml
- ui/imports/shared/views/chat/MessageView.qml
- ui/imports/utils/Global.qml
- add a popup asking the user before clicking on an unfurled link preview
- add a checkbox for the above popup to remember the trust for such domain
- use local Settings to persist the "trust domain" locally; for global persistence across devices, see https://github.com/status-im/status-go/issues/4132
Closes https://github.com/status-im/status-desktop/issues/12388
Implements "trust this domain" confirmation popup when opening an external link preview
AppMain
> feat: Add URL trust options when the user clicks on an unfurled link preview

- src/app_service/service/network/service.nim
fix(@desktop/wallet): Wallet -> Setting -> Edit network: toast message is not displayed when reverting to default
fixes #12419
Fixes error that no toast message is shown when revert to default is clicked
Wallet network settings
https://github.com/status-im/status-desktop/assets/60327365/4a4c94a7-0c52-4324-a787-bca1eaffdf30
> fix(@desktop/wallet): Wallet -> Setting -> Edit network: toast message is not displayed when reverting to default

- src/app/modules/main/chat_section/chat_content/input_area/controller.nim
- src/app/modules/main/chat_section/chat_content/input_area/io_interface.nim
- src/app/modules/main/chat_section/chat_content/input_area/module.nim
- src/app/modules/main/chat_section/chat_content/input_area/preserved_properties.nim
- src/app/modules/main/chat_section/chat_content/input_area/view.nim
- src/app/modules/shared_models/link_preview_model.nim
- storybook/pages/ChatInputLinksPreviewAreaPage.qml
- storybook/pages/LinkPreviewSettingsCardPage.qml
- storybook/pages/StatusChatInputPage.qml
- ui/app/AppLayouts/Chat/views/ChatColumnView.qml
- ui/imports/shared/controls/chat/ChatInputLinksPreviewArea.qml
- ui/imports/shared/controls/chat/LinkPreviewMiniCard.qml
- ui/imports/shared/controls/chat/LinkPreviewSettingsCard.qml
- ui/imports/shared/controls/chat/qmldir
- ui/imports/shared/status/StatusChatInput.qml
- ui/imports/shared/status/StatusChatInputImageArea.qml
- ui/imports/utils/UndoStackManager.qml
Closing: #12180
Depends on #12262 to be merged first.
This commit adds the link preview settings card in the chat input area and connects the settings to the controller.
Not included in this commit: Backend for the preserving the settings, syncing the settings and enforcing the settings on the backend side.
Whenever an url is detected in the chat input area, the link preview settings card is presented. This card enables the user to choose one of the following options:
1. `Show for this message` - All the link previews in the current message will be loaded without asking again. The current message can be defined as the message currently typed/pasted in the chat input. Deleting or sending the current content is resetting this setting and the link preview settings card will be presented …
> feat: Add settings card to control link previews settings in chat input

- ui/StatusQ/src/StatusQ/Components/StatusMessage.qml
- ui/StatusQ/src/StatusQ/Components/private/statusMessage/StatusTextMessage.qml
- ui/StatusQ/src/StatusQ/Core/Utils/Utils.qml
- ui/imports/shared/controls/chat/LinkPreviewCard.qml
- ui/imports/shared/views/chat/LinksMessageView.qml
- ui/imports/shared/views/chat/MessageView.qml
Closing: #12382 
Depends on #12181 for border updates on the `CalloutCard`
Changes:
1. Add hyperlink highlight in `StatusMessage`
2. Add link preview highlight in `LinksMessageView`
3. Connect the hover states between `StatusMessage` and `LinksMessageView`
Link previews in chat history
StatusMessage
https://github.com/status-im/status-desktop/assets/47811206/98b265fc-abd4-4e18-92fa-34ba67613e8e
> feat: highlight the hovered hyperlink and link preview

- ui/StatusQ/src/StatusQ/Popups/StatusModal.qml
- ui/imports/shared/popups/UserAgreementPopup.qml
- no logo
- tighter content, smaller vertical spacing
Fixes https://github.com/status-im/status-desktop/issues/12400
Fixes the beta dialog to fit minimum height better
UserAgreementPopup
> fix: Update the Beta dialog design to better fit the content

- Makefile
- ci/Jenkinsfile.linux
- ci/Jenkinsfile.macos
- ci/Jenkinsfile.tests-e2e
- ci/Jenkinsfile.windows
- src/app/global/local_account_settings.nim
- src/app/global/local_app_settings.nim
- src/constants.nim
Changes:
* Refactors the `status-keycard-go` to use `USE_MOCKED_KEYCARD_LIB` env variable.
- Use of `TEST_ENVIRONMENT` makes no sense since it's used at runtime.
* Renames `TEST_ENVIRONMENT` env variables to `STATUS_RUNTIME_TEST_MODE`.
- Because it needs to be clear this is runtime and what it actually does.
* Adds `USE_MOCKED_KEYCARD_LIB` parameter to Jenkins CI builds
- It will default to `true` for linux builds except release ones.
- This setting can always be overriden manually for any build.
Resolves:
* https://github.com/status-im/status-desktop/issues/12412
> feat(ci): add USE_MOCKED_KEYCARD_LIB parameter

- ui/imports/shared/popups/ImportCommunityPopup.qml
- track the import progress manually as `root.store.getCommunityDetails(key)` can optionally return `null` immediately if the community is not known and launch an async task
- as an additional measure, since the above async call sometimes never finishes, add a `Timer` that unsets the internal `loading` state
Fixes #12358
Fixes the ever spinning loading animation when trying to import a community
ImportCommunityPopup
Typing an invalid key:
Loading community info:
The happy error path, async call finishes with error:
The manual timeout error path:
> fix(ImportCommunityPopup): no UI information when requesting info failed

- src/app/global/utils.nim
- src/app/modules/main/chat_section/chat_content/input_area/controller.nim
- src/app/modules/main/chat_section/chat_content/input_area/io_interface.nim
- src/app/modules/main/chat_section/chat_content/input_area/link_preview_cache.nim
- src/app/modules/main/chat_section/chat_content/input_area/module.nim
- src/app/modules/main/chat_section/chat_content/input_area/view.nim
- src/app/modules/shared_models/link_preview_item.nim
- src/app/modules/shared_models/link_preview_model.nim
- src/app_service/service/message/dto/link_preview.nim
- src/app_service/service/message/dto/link_preview_thumbnail.nim
- src/app_service/service/message/dto/message.nim
- src/app_service/service/message/dto/standard_link_preview.nim
- src/app_service/service/message/dto/status_community_channel_link_preview.nim
- src/app_service/service/message/dto/status_community_link_preview.nim
- src/app_service/service/message/dto/status_contact_link_preview.nim
- src/app_service/service/message/dto/status_link_preview.nim
- src/app_service/service/message/service.nim
- src/backend/chat.nim
- storybook/pages/LinksMessageViewPage.qml
- ui/app/AppLayouts/Chat/views/ChatColumnView.qml
- ui/imports/shared/controls/LinkPreviewDebugView.qml
- ui/imports/shared/controls/chat/ChatInputLinksPreviewArea.qml
- ui/imports/shared/controls/chat/LinkPreviewMiniCard.qml
- ui/imports/shared/controls/qmldir
- ui/imports/shared/views/chat/LinksMessageView.qml
- ui/imports/shared/views/chat/MessageView.qml
- ui/imports/utils/Constants.qml
Fixes https://github.com/status-im/status-desktop/issues/11938
Requires https://github.com/status-im/status-go/pull/4033
This PR adds support updates status-go and for unfurled status links.
**NOTE:** Model roles and QML bindings went quite dirty in this PR.
I'd like this to be merged as is and then have a separate round of discussion on which model roles would be convenient to have. So please, don't judge the dirty QML here. It was hard to do clean after all the rebases and parallel work.
https://github.com/status-im/status-desktop/assets/25482501/c5274ed7-bd25-4372-a823-e53692ba50a2
https://github.com/status-im/status-desktop/assets/25482501/bebfd429-5810-464e-8f34-d430ddd5904a
https://github.com/status-im/status-desktop/assets/25482501/38fec033-f6f7-4fb3-b6b5-084ccd29d4af …
> feature: unfurl Status links (contact/community/channel)

- storybook/qmlTests/TestComponents/tst_StatusChatInput.qml
Updating the `Undo` test that compares the `Undo` done in StatusChatInput with a standard TextEdit component. 
Undo/Redo feature was changed by https://github.com/status-im/status-desktop/pull/12262. Now we're using a custom undo/redo logic and the undo is more granular as opposed to TextEdit.
StatusChatInput test
> chore: fix StatusChatInput tests

- src/app/modules/main/module.nim
make a few "fixups" for OneToOne and Group chats so that we set the correct `sectionId` and `sectionName`
Fixes #12264
Fix quick search (Ctrl+K) navigation to work in all cases
ChatSearchModel
[Záznam obrazovky z 2023-10-13 15-54-33.webm](https://github.com/status-im/status-desktop/assets/5377645/9b72d9dc-e13d-4a53-9162-2469f7c1ae93)
> fix: CTRL+K navigation doesn't work for 1-1 chats (only for communities)

- src/app/global/local_app_settings.nim
- src/constants.nim
Env vars were read correctly and evaluated during the runtime, but then assigned to a const evaluated during the compile time and that const was used in the code, leading to ignoring a real env value.
> fix(@desktop/general): env vars evaluation fixed

- ui/app/AppLayouts/Communities/views/CommunityColumnView.qml
when another import is already in progress
Fixes #12239
Disable (not hide) the respective menu items to import a single channel from discord when another discord import job is already in progress
CommunityColumnView
> fix: disable importing channel from discord

- Makefile
- storybook/CMakeLists.txt
Adds target to run a storybook itself (run-storybook) and also target to run all tests from storybook directory (run-storybook-tests):
- unit tests for storybook itself
- unit tests for the app using the same stubs mechanism (in offscreen mode)
- PagesValidator
Tests are run via `ctest`.
Closes: #12448
Note: crash for qml-tests is fixed in https://github.com/status-im/status-desktop/pull/12409
[Kazam_screencast_00050.webm](https://github.com/status-im/status-desktop/assets/20650004/271a6032-698b-4139-b8dd-945f3f474649)
> feat(Storybook): Add storybook targets to Makefile

- ui/app/AppLayouts/Profile/controls/WalletKeyPairDelegate.qml
add object name for keypair delegate item
`ui/app/AppLayouts/Profile/controls/WalletKeyPairDelegate.qml`
> chore(@WalletKeyPairDelegate.qml): add object name for keypair delegate item

- src/app/modules/main/ephemeral_notification_item.nim
- src/app/modules/main/module.nim
- ui/StatusQ/sandbox/CMakeLists.txt
- ui/StatusQ/sandbox/pages/StatusToastMessagePage.qml
- ui/StatusQ/sandbox/sandboxapp.cpp
- ui/StatusQ/sandbox/sandboxapp.h
- ui/StatusQ/src/StatusQ/Components/StatusToastMessage.qml
- ui/app/AppLayouts/Chat/views/ChatColumnView.qml
- ui/app/mainui/AppMain.qml
- ui/imports/utils/Constants.qml
Closing #12398 
Changes:
1. StatusToastMessage now supports dynamic content height
2. Add new StatusToastMessage type: Danger
3. Update StatusToastMessage to support RichText content
4. Fix StatusQ sanboxapp compilation
5. Add the new StatusToastMessage content to sandbox
6. Show toast messages when the link preview settings changes from StatusChatInput
StatusQ - StatusToastMessage.qml
Toast notifications
ChatColumnView
https://github.com/status-im/status-desktop/assets/47811206/a06032cb-a8c0-4024-8463-2b7d70e819c3
> [LinkPreviews] Show toast messages when link preview settings changes from StatusChatInput

- ui/imports/shared/controls/chat/CalloutCard.qml
- ui/imports/shared/controls/chat/LinkPreviewCard.qml
- ui/imports/shared/views/chat/LinksMessageView.qml
Closing #12444
Replace the 1px blue border with `DropShadow` and fix link preview highlighting when hovering the URL
LinkPreviewCard
> fix: Update link preview border to match the new design

- ci/Jenkinsfile.tests-e2e
Otherwise none of these credentials are present:
https://github.com/status-im/status-jenkins-lib/blob/master/vars/linux.groovy
> fix(ci): use linux.bundle() to add credentials

- ci/Jenkinsfile.combined
- ci/Jenkinsfile.linux
- ci/Jenkinsfile.macos
- ci/Jenkinsfile.tests-e2e
- ci/Jenkinsfile.tests-nim
- ci/Jenkinsfile.windows
- ci/cpp/Jenkinsfile.linux
- ci/cpp/Jenkinsfile.macos
- ci/cpp/Jenkinsfile.windows
- src/app/boot/app_controller.nim
- src/app_service/common/network_constants.nim
- src/app_service/service/accounts/service.nim
- src/constants.nim
- src/env_cli_vars.nim
- src/nim_status_client.nim
The first commit of this PR sorts a bit vars that should be evaluated during the runtime. Also supports setting them as CL arguments or env vars.
If variables are provided as CL arguments they will be used, if not provided, will be read from env variables if they are set, if not, the default values are used.
This also brings some new changes in env vars, all of env vars used by the Status are prefixed with `STATUS_`. Because of this we should check all of them and update them in CI if needed. @jakubgs 
There is a `-h` or `--help` command that prints out all arguments/variables that are known to the Status app.
**Usage**
- CL:
`./StatusDev.app/Contents/MacOS/nim_status_client --runtime-test-mode:true`
- env var:
`export STATUS_RUNTIME_TEST_MODE=true`
Closes: 
* …
> env vars sorted,  isolated node config when user is logging in

- ci/Jenkinsfile.linux
We run `prs` job for PRs and `nightly` for... nightly.
Result:
```
21:38:21  Scheduling project: [status-desktop » e2e » prs](https://ci.status.im/job/status-desktop/job/e2e/job/prs/)
```
https://ci.status.im/job/status-desktop/job/e2e/job/prs/51/
Depends on:
* https://github.com/status-im/desktop-qa-automation/pull/195
> feat(ci): trigger new E2E run after Linux build

- storybook/qmlTests/tests/tst_StatusChatInput.qml
- ui/imports/utils/UndoStackManager.qml
Closing #12446 
Changes: 
1. Preserve the cursor position on undo/redo
2. Add qml tests
3. Fix undo/redo corner case when the user text change is the same as the last undo action
E.g. Type `abcde`
Delete `b` -> `acde`
Undo -> `abcde`
Delete `b` -> `acde`
Unfo -> `abcd` (this was happening because the previous unformatted text was not set on Undo/Redo actions)
https://github.com/status-im/status-desktop/assets/47811206/a91ec8fe-7e98-4720-85fe-d37ed6df5dad
> fix: Preserve the previous cursor position on `undo/redo` in StatusChatInput

- src/app/modules/main/chat_section/chat_content/input_area/controller.nim
- src/app/modules/main/chat_section/chat_content/input_area/io_interface.nim
- src/app/modules/main/chat_section/chat_content/input_area/module.nim
- src/app/modules/main/chat_section/chat_content/input_area/view.nim
- src/app/modules/main/profile_section/privacy/controller.nim
- src/app/modules/main/profile_section/privacy/io_interface.nim
- src/app/modules/main/profile_section/privacy/module.nim
- src/app/modules/main/profile_section/privacy/view.nim
- src/app_service/service/settings/service.nim
- ui/app/AppLayouts/Chat/views/ChatColumnView.qml
Closing #12442
Changes:
1. Update privacy controller to react to external unfurling settings change
2. Add handler to input controller and react to external unfurling settings change
3. Small other fixes
Link preview settings
https://github.com/status-im/status-desktop/assets/47811206/c47a3b9a-9fd3-46c9-9d61-e588721e0ba2
https://github.com/status-im/status-desktop/assets/47811206/e647b9bd-c229-4b72-b5c9-a706b6a579af
> feat: Link preview settings to Status chat input unfurling mode

- ui/imports/shared/views/chat/ChatContextMenuView.qml
- ui/imports/utils/Utils.qml
Added a channel context menu option to copy link to channel.
I'm not sure why it wasn't added in the first place, but we need to test URL unfurling.
If this button shouldn't exist, or it should be of different design, let me know 🙂 
https://github.com/status-im/status-desktop/assets/25482501/b6644a79-1d12-4d1a-9ba1-971855030ad7
> feature: copy channel link menu action

- src/app/modules/main/chat_section/chat_content/input_area/controller.nim
- src/app/modules/main/chat_section/chat_content/input_area/io_interface.nim
- src/app/modules/main/chat_section/chat_content/input_area/module.nim
- src/app/modules/main/chat_section/chat_content/input_area/urls_model.nim
- src/app/modules/main/chat_section/chat_content/input_area/view.nim
- storybook/pages/StatusChatInputPage.qml
- ui/app/AppLayouts/Chat/views/ChatColumnView.qml
- ui/imports/shared/status/StatusChatInput.qml
The link preview model can be filtered, but the hyperlink detection needs an unfiltered model to properly highlight all URLs. This brought in the need to separate the urls model and the link previews model.
https://github.com/status-im/status-desktop/assets/47811206/6bb65043-5586-4ef3-b80e-abe5fa0aecbe
> fix(LinkPreviews): Fixing gif hyperlink detection in StatusChatInput

- src/app/modules/main/chat_section/chat_content/input_area/controller.nim
- src/app/modules/main/chat_section/chat_content/input_area/view.nim
Removing link preview settings leftovers after resolving conflicts.
The link preview settings change is event based. The previous logic needs to be removed.
> fix(LinkPreviews): Fix link preview settings

- ci/Jenkinsfile.combined
- ci/Jenkinsfile.linux
The method of triggering new E2E builds from the Linux build makes sense for PRs, but doesn't make as much sense for nightly or release builds.
By triggering it this way we will see the result as part of the whole build that includes all platforms and all tests.
> feat(ci): trigger E2E from meta build for releases

- src/app/modules/main/communities/controller.nim
- src/app/modules/main/communities/io_interface.nim
- src/app/modules/main/communities/module.nim
- src/app/modules/main/communities/view.nim
- storybook/main.qml
- storybook/pages/ImportCommunityPopupPage.qml
- ui/app/AppLayouts/Communities/stores/CommunitiesStore.qml
- ui/app/mainui/Popups.qml
- ui/imports/shared/popups/ImportCommunityPopup.qml
Fixes https://github.com/status-im/status-desktop/issues/12465
Fixes https://github.com/status-im/status-desktop/issues/12542
Drops the usage of `parseCommunitySharedUrl` (https://github.com/status-im/status-desktop/issues/12356)
1. Correctly show result of `requestCommunityInfo` call
2. Remove QML timeout, trust status-go timeout instead
3. Remove support for private key importing
4. Remove automatic call for `reuestCommunityInfo` from `getCommunityDetails`. 
Because the former returns nothing and requires binding to nim signals.
5. Update status-go to include https://github.com/status-im/status-go/pull/4194
6. storybook page for `ImportCommunityPopup`
ImportCommunityPopup
https://github.com/status-im/status-desktop/assets/25482501/acc37804-a043-4652-abfc-25ed68f2c286 …
> fix `ImportCommunityPopup` issues, remove private key importing

- storybook/pages/LeftJoinModelPage.qml
- storybook/pages/LeftJoinRenamingSfpmPage.qml
- storybook/pages/RolesRenamingModelPage.qml
- ui/StatusQ/CMakeLists.txt
- ui/StatusQ/include/StatusQ/leftjoinmodel.h
- ui/StatusQ/include/StatusQ/rolesrenamingmodel.h
- ui/StatusQ/src/leftjoinmodel.cpp
- ui/StatusQ/src/plugin.cpp
- ui/StatusQ/src/rolesrenamingmodel.cpp
- ui/StatusQ/tests/CMakeLists.txt
- ui/StatusQ/tests/tst_LeftJoinModel.cpp
- ui/StatusQ/tests/tst_RolesRenamingModel.cpp
It introduces two generic proxy models:
1. `RolesRenamingModel` - it allows to change role names of existing model.
2. `LeftJoinModel` - this proxy takes two source models as an input (`rightMode` and `leftModel`). The idea is to mimic SQL's left join but in a dynamic way.
When joining two models via `LeftJoinModel` it may be needed to change role names to avoid conflicts (same names in both models) and adjust role names to meet expectations of the view. Because of that need `RolesRenamingModel` has been introduces as a complementary proxy model for `LeftJoinModel`.
Closes: https://github.com/status-im/status-desktop/issues/12502
`StatusQ`
[Kazam_screencast_00051.webm](https://github.com/status-im/status-desktop/assets/20650004/2d5cdd36-6954-4433-a2a4-4633d9869001)
> StatusQ: Generic proxy models `RolesRenamingModel` and `LeftJoinModel`

- ui/app/AppLayouts/Profile/views/wallet/AccountView.qml
add object name for confirmation popup
`ui/app/AppLayouts/Profile/views/wallet/AccountView.qml`
> chore(@AccountView.qml): add object name for confirmation popup

- src/app_service/service/devices/dto/local_pairing_event.nim
- src/app_service/service/devices/dto/local_pairing_status.nim
- src/app_service/service/devices/service.nim
Fixes #12550
The problem was that we used the pairing event saying "Finished" to show the Login button, however, when that event is received, the Node hasn't started fully yet, so we might try to login when the accounts are still empty in the cache.
The solution is to use the return from the async task, since that one returns at the very end when the process is over and the node is ready. Obviously, if that returns an error, we still use the error instead.
> fix(pairing): fix pairing error on too fast login

- ui/StatusQ/src/leftjoinmodel.cpp
- ui/StatusQ/tests/tst_LeftJoinModel.cpp
A small follow-up to https://github.com/status-im/status-desktop/pull/12530
- `QModelIndexList::match` used instead of plain loop over right model entries to allow lookup optimizations
- warning printing when join model contains duplicated roles
- tests amended, `QAbstractItemModelTester` used
Closes: https://github.com/status-im/status-desktop/issues/12574
`LeftJoinModel` (`StatusQ`)
> chore(LeftJoinModel): Minor improvements and tests amendments

- Makefile
Changes:
1. `brew` was installed at a different dir, so I condition is changed a bit
2. `yarn install` instead of `npm i` solves error during `nan` installation
```
npm ERR! In file included from ../src/volume.cc:2:
npm ERR! In file included from ../../nan/nan.h:178:
npm ERR! ../../nan/nan_callbacks.h:55:23: error: no member named 'AccessorSignature' in namespace 'v8'
npm ERR! typedef v8::Local<v8::AccessorSignature> Sig;
npm ERR!                   ~~~~^
```
status: ready
> Makefile changes for macOS Sonoma

- src/app/modules/main/chat_section/controller.nim
- src/app/modules/main/chat_section/io_interface.nim
- src/app/modules/main/chat_section/module.nim
- src/app/modules/main/chat_section/view.nim
- src/app/modules/main/controller.nim
- src/app/modules/main/module.nim
- src/app_service/service/community/async_tasks.nim
- src/app_service/service/community/dto/community.nim
- src/app_service/service/community/service.nim
- src/backend/communities.nim
- ui/app/AppLayouts/Chat/ChatLayout.qml
- ui/app/AppLayouts/Communities/panels/ControlNodeOfflineCenterPanel.qml
- ui/app/AppLayouts/Communities/panels/qmldir
- ui/app/AppLayouts/Communities/views/ControlNodeOfflineCommunityView.qml
- ui/app/AppLayouts/Communities/views/qmldir
When the community ownership changes, the new owner will kick out all members and they must reveal their address in order to rejoin the community. As soon, as they will do it - they will automatically rejoin by the control node.
If the control node will not be online to accept them, the appropriate info msg will be displayed
Closes: https://github.com/status-im/status-desktop/issues/11969
status-go PR: https://github.com/status-im/status-go/pull/4187
Ownership change
https://github.com/status-im/status-desktop/assets/117639195/a64d28fd-4f68-4738-9e77-0876535972c5
> feat: info msg if owner is not awailable after community ownership change

- ui/app/AppLayouts/Wallet/views/AccountContextMenu.qml
Removed the predefined width in the context menu to allow the new option of including/excluding from total balance be fully visible
Fixes https://github.com/status-im/status-desktop/issues/12579
> chore(@AccountContexMenu.qml): make the context menu dynamic

- storybook/pages/LinksMessageViewPage.qml
- ui/StatusQ/src/StatusQ/Components/StatusMessage.qml
- ui/imports/shared/controls/delegates/LinkPreviewCardDelegate.qml
- ui/imports/shared/controls/delegates/LinkPreviewGifDelegate.qml
- ui/imports/shared/status/StatusChatImageLoader.qml
- ui/imports/shared/views/chat/LinksMessageView.qml
- ui/imports/shared/views/chat/MessageView.qml
Closing: #12599 
Set the link preview tight corner on the left side.
Link previews
https://github.com/status-im/status-desktop/assets/47811206/1cb5aeda-a27c-4017-bfa5-43197f38e6f2
> fix(LinkPreviews): Left align the message link preview tight corner

- src/app/modules/main/profile_section/wallet/accounts/module.nim
- src/app/modules/main/wallet_section/module.nim
- src/app/modules/main/wallet_section/send/module.nim
- src/app/modules/shared_modules/collectibles/controller.nim
- src/backend/collectibles.nim
Closes #12520
status-go part: https://github.com/status-im/status-go/pull/4245
Implement additional Collectibles filtering, using some communities-related criteria.
This allows us to, for example, get a list of all Owner Tokens owned by the user.
> feat: implement generalized collectibles filter

- test/ui-test/testSuites/suite_communities/tst_communityMessageFlows/test.feature
- ui/imports/shared/status/StatusChatInput.qml
Closing #12440 
The enabled property of the text input needs to have a binding to the StatusChatInput enabled property
+ re-enable the squish test
https://github.com/status-im/status-desktop/assets/47811206/ccf8ded7-1a5d-40c8-95e9-3e5051c6f09e
> fix: Fixing broken binding on text input enabled property

- ci/Jenkinsfile.combined
QA needs easier access to public URLs from DigitalOcean spaces, and when this meta-job fails the URLs are buried within child jobs and hard to access.
This not only sets the description if build fails, it sets it after every single child build finishes.
Result:
> feature(ci): set build description even if it fails

- storybook/pages/SubmodelProxyModelPage.qml
- ui/StatusQ/CMakeLists.txt
- ui/StatusQ/include/StatusQ/submodelproxymodel.h
- ui/StatusQ/src/leftjoinmodel.cpp
- ui/StatusQ/src/plugin.cpp
- ui/StatusQ/src/submodelproxymodel.cpp
- ui/StatusQ/tests/CMakeLists.txt
- ui/StatusQ/tests/tst_SubmodelProxyModel.cpp
It allows transforming model, including submodels outside of the view component consuming the model. Thanks to that now there is no need to create proxies for submodels in view's delegate. It can be done earlier, on the level of the main view.
This PR contains:
- New proxy model `SubmodelProxyModel`
- Storybook's page showcasing usage of the proxy with `SFPM` and `LeftJoinModel`
Basic usage - left join:
```
SubmodelProxyModel {
sourceModel: tokensModel
delegateModel: LeftJoinModel {
leftModel: submodel
rightModel: networksModel
joinRole: "chainId"
}
submodelRoleName: "balances"
}
```
Basic usage - sorting:
```
SubmodelProxyModel {
sourceModel: tokensModel
delegateModel: SortFilterProxyModel {
sourceModel: submodel
sorters: RoleSorter {
roleName: "name"
enabled: sortCheckBox.checked
}
} …
```
> feat(StatusQ): Generic proxy model allowing setting proxies like SFPM or LeftJoinModel for submodels

- src/app/modules/main/chat_section/chat_content/messages/controller.nim
- src/app/modules/main/chat_section/chat_content/messages/io_interface.nim
- src/app/modules/main/chat_section/chat_content/messages/module.nim
- src/app/modules/main/chat_section/chat_content/messages/view.nim
- src/app/modules/shared_models/link_preview_item.nim
- src/app/modules/shared_models/link_preview_model.nim
- src/app/modules/shared_models/message_item.nim
- src/app/modules/shared_models/message_model.nim
- src/app_service/service/chat/dto/chat.nim
- src/app_service/service/community/async_tasks.nim
- src/app_service/service/community/service.nim
- src/app_service/service/message/dto/link_preview.nim
- src/app_service/service/message/dto/link_preview_thumbnail.nim
- src/app_service/service/message/dto/status_community_channel_link_preview.nim
- src/app_service/service/message/dto/status_community_link_preview.nim
- src/app_service/service/message/dto/status_contact_link_preview.nim
- src/backend/communities.nim
- ui/StatusQ/src/assets.qrc
- ui/app/mainui/AppMain.qml
- ui/imports/shared/controls/chat/LinkPreviewCard.qml
- ui/imports/shared/controls/chat/private/CommunityData.qml
- ui/imports/shared/controls/delegates/LinkPreviewCardDelegate.qml
- ui/imports/shared/views/chat/MessageView.qml
Closes https://github.com/status-im/status-desktop/issues/12459
Requires https://github.com/status-im/status-go/pull/4238
Requires https://github.com/status-im/status-go/pull/4246
Requires https://github.com/status-im/status-go/pull/4260
This introduces a feature about updating status link previews with trusted data from waku.
1. I decided to do it fully on client (desktop) side, because we want to keep original LinkPreviews untouched and not modify `user_messages` table.
2. The real data is pushed to `LinkPreviewModel` (it's transparent for UI)
3. When a new message is loaded, we check if there's real data locally available already.
4. When a message comes into user viewport (i.e. `LinksMessageView.onCompleted:  ...`), we "force" the real data to be loaded into the link preview. At this …
> feature: live status link previews

- ci/Jenkinsfile.combined
This allows `jenkins.copyArts()` - which assumes existence of `pkg` folder - to work with meta-jobs.
Required for:
* https://github.com/status-im/desktop-qa-automation/pull/270
> fix(ci): archive artifacts in pkg folder

- ui/app/AppLayouts/Onboarding/stores/StartupStore.qml
- ui/app/AppLayouts/Onboarding/views/ConfirmPasswordView.qml
Fixes part of [#12605](https://github.com/status-im/status-desktop/issues/12605)
I put this on top of the release branch because the issue happened in the release mostly. 
It also only happens in release builds, so it was definitely a race condition.
In the end, the issue was that we were using the `privacyModule` during the account creation when the `privacyModule` doesn't exist and it ended up calling multiple modules that also weren't initialized and probably during all this, it created a race condition that crashed.
> fix(ConfirmPasswordView): only use privacyModule when in main app state

- src/app/modules/main/controller.nim
- src/app/modules/main/io_interface.nim
- src/app/modules/main/module.nim
- src/app_service/service/community/service.nim
- src/app_service/service/shared_urls/dto/url_data.nim
Fixes https://github.com/status-im/status-desktop/issues/12539
1. Improve the algorithm of switching to channel by using the known community id
2. Fix the used `chatID` for chat lookup, as it should be a concatenation of community id and channel id
3. Fix the order of processing channel/community in `activateStatusDeepLink`. Channel should be processed earlier, because communityId is also set
4. Fix json parsing of `channelUuid` field 
5. Refactor switching to community/channel to use `switchTo` function
6. Works for non-spectated/joined community too!
https://github.com/status-im/status-desktop/assets/25482501/7d5d887c-2664-4ae5-ad95-d042f8f457b8
> fix: activate community channel link

- storybook/CMakeLists.txt
- storybook/pages/ManageTokensPanelPage.qml
- storybook/src/Models/ManageTokensModel.qml
- storybook/src/Models/qmldir
- ui/StatusQ/CMakeLists.txt
- ui/StatusQ/src/StatusQ/Components/StatusDraggableListItem.qml
- ui/StatusQ/src/StatusQ/Controls/StatusCheckBox.qml
- ui/StatusQ/src/StatusQ/Controls/StatusItemDelegate.qml
- ui/StatusQ/src/StatusQ/Controls/StatusSwitch.qml
- ui/StatusQ/src/StatusQ/Popups/StatusAction.qml
- ui/StatusQ/src/StatusQ/Popups/StatusMenu.qml
- ui/StatusQ/src/StatusQ/Popups/StatusMenuItem.qml
- ui/StatusQ/src/StatusQ/Popups/StatusSearchPopupMenuItem.qml
- ui/StatusQ/src/assets/img/icons/arrow-bottom.svg
- ui/StatusQ/src/assets/img/icons/arrow-top.svg
- ui/StatusQ/src/plugin.cpp
- ui/StatusQ/src/wallet/managetokenscontroller.cpp
- ui/StatusQ/src/wallet/managetokenscontroller.h
- ui/StatusQ/src/wallet/managetokensmodel.cpp
- ui/StatusQ/src/wallet/managetokensmodel.h
- ui/app/AppLayouts/Profile/controls/CollectibleShowcaseDelegate.qml
- ui/app/AppLayouts/Profile/controls/ShowcaseDelegate.qml
- ui/app/AppLayouts/Wallet/controls/ManageTokenMenuButton.qml
- ui/app/AppLayouts/Wallet/controls/SortOrderComboBox.qml
- ui/app/AppLayouts/Wallet/controls/qmldir
- ui/app/AppLayouts/Wallet/panels/ManageTokensPanel.qml
- ui/app/AppLayouts/Wallet/panels/qmldir
- ui/imports/shared/controls/InformationTag.qml
- implements the UI component to manage regular & community tokens (drag'n'drop or context menu to reorder, show/hide, group by community)
- implements a custom C++ QAIM model which acts as a fake proxy model for the above QML panel (internally it does all the sorting/grouping/hiding and preserves the custom sort order)
- adds and corrects support for cascading submenus in `StatusAction`, and `StatusMenu[Item]`
- adds support for mirrored (horizontally flipped) `StatusSwitch`
- adds a new `SortOrderComboBox.qml` (this was being used in the first Figma version, can be ignored now, will be used by the main wallet view later)
- some minor fixes and cleanups in the used components
Note: this PR can still be considered a POC, given that it has some performance issues, especially for the …
> feat: Manage tokens panel UI component & model

- src/app/modules/main/ephemeral_notification_item.nim
- src/app/modules/main/ephemeral_notification_model.nim
- src/app/modules/main/io_interface.nim
- src/app/modules/main/module.nim
- src/app/modules/main/view.nim
- ui/StatusQ/src/StatusQ/Components/StatusToastMessage.qml
- ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml
- ui/app/mainui/AppMain.qml
- ui/app/mainui/Popups.qml
- ui/app/mainui/ToastsManager.qml
- ui/imports/shared/stores/CommunityTokensStore.qml
- ui/imports/utils/Global.qml
Part of #12175. 
NOTE: It needs some other backend works in order to fully close it (missing signal `communityTokensModuleInst.sendOwnerTokenStateChanged`)
This is a first step to globalize how toasts are treated in the qml layer:
- Created `ToastsManager.qml` class to deal with all app toasts generation.
- Started moving community transfer ownership related toasts to the new manager class.
- Some small cleanup in `AppMain.qml`
Nim backend:
- Created new api method to deal with extended / action toasts.
- Updated needed model / item with new needed roles.
**NOTE:** There will be a follow up task to work on the next toasts management unification refactor: https://github.com/status-im/status-desktop/issues/12661
AppMain / Toasts
CommunityTokensStore
- Dummy data example and forcing toasts …
> feat(CommunityOwnership): UI toasts part

- ci/Jenkinsfile.tests-e2e
For debugging possible delays caused by old and new e2e jobs running on the same CI host.
Related to:
* https://github.com/status-im/desktop-qa-automation/pull/298
> fix(ci): run old e2e on dediated hosts

- ci/Jenkinsfile.combined
#276
Each night, we run e2e tests. To have a report in TestRail, we need to fill in the TESTRAIL_RUN_NAME field.
In PR, I added generating the name of test runs in TestRail.
Tested here:
https://ci.status.im/job/status-desktop/job/e2e/job/manual/856/console
In the console output, you can find that the name was generated in the format: Nightly regression 10.11.2023
> chore(e2e): Generate name of Nightly run for TesRail

- src/app/modules/main/stickers/models/sticker_pack_list.nim
- src/app/modules/main/stickers/module.nim
- src/app_service/service/stickers/async_tasks.nim
- src/app_service/service/stickers/service.nim
Fixes #12664
1. The issue was that the async task was badly made. It could return `false` instead of a tuple, so it made the app crashed.
I fixed it by removing that condition, since I we don't actually care if the pack we are installing is in the cache. Worst case, status-go will return an error and we can handle it. In the better case, it was just a weird problem with the cache and since it exists in the model, it probably exists in the backend, so it would go through anyway. That issue was very random for me and I could trigger it only once.
2. Another issue I found was that when buying a pack, we set the `installed` property in the model, but not `bought`, so if you uninstall the pack, it looks like you didn't buy it. That's fixed.
3. Finally, I found that we called …
> fix(stickers): fix crash in async task + clean up  + set bought status

- ui/StatusQ/src/StatusQ/Controls/StatusSeedPhraseInput.qml
This PR fixes #10708
During the entering of Seed phrase, when pressing `Qt.Key_Up`, Qt would handle the event and keep the event cached. Similarly, when pressing `Qt.Key_Down`, that event will also be cached. When the user then pressed `Qt.Key_Return` the previous event would be replayed then changing the actual expected result. Here are some example from the bug :
In input we enter `z` to have the following : 
On this state, the first word is selected automatically and the cache of event is empty.
- If I press Key_Return, the expected result is `zebra` which is correct
Now if I do a Key_Down
- The event cache contains Key_Down, and the currently selected word is `zero`
- If I press Key_Return, the expected result should be `zero` but is `zone`
Now if I do a Key_Down, Key_Down again and …
> Fix incorrect suggestion input when entering seed phrase

- src/app/modules/main/communities/controller.nim
- src/app/modules/main/communities/io_interface.nim
- src/app/modules/main/communities/module.nim
- src/app/modules/main/communities/view.nim
- ui/app/AppLayouts/Communities/popups/DiscordImportProgressContents.qml
- ui/app/AppLayouts/Communities/stores/CommunitiesStore.qml
Fixes: #12684
Process `delete channel & restart import` button
Discord import single channel
> fix(discord): Process `delete channel & restart import` button

- ui/StatusQ/src/StatusQ/Components/StatusCard.qml
- ui/imports/shared/popups/send/views/NetworkSelector.qml
the most recent Qt upstream version introduced a regression that causes our app to crash right on startup when a grouped property is assigned to inside a `PropertyChanges` handler
upstream issue: https://bugreports.qt.io/browse/QTBUG-107795
Upstream fix will be released with Qt 5.15.12, code being at https://codereview.qt-project.org/c/qt/qtdeclarative/+/424702
Culprit found thanks to `PagesValidator` from `storybook`
Fixes a nasty crash with Qt 5.15.11
ALL (indirectly via SendModal)
Back in business ;)
> fix: workaround to crash on startup with Qt 5.15.11

- storybook/pages/LinkPreviewMiniCardPage.qml
- ui/imports/shared/controls/chat/LinkPreviewMiniCard.qml
- Fix the color of `LinkPreviewMiniCard` in dark theme.
> fix(LinkPreviewMiniCard): dark theme background color

- ui/imports/shared/panels/MockedKeycardLibControllerWindow.qml
Corresponding `status-keycard-go` PR:
- https://github.com/status-im/status-keycard-go/pull/7
> fix(mocked-keycard-lib): details for the default export public flow updated

- src/app/modules/main/activity_center/controller.nim
- src/app/modules/main/activity_center/model.nim
- src/app/modules/main/activity_center/module.nim
- src/app/modules/main/activity_center/view.nim
- ui/app/mainui/activitycenter/popups/ActivityCenterPopup.qml
- ui/app/mainui/activitycenter/stores/ActivityCenterStore.qml
- ui/app/mainui/activitycenter/views/ActivityNotificationCommunityMembershipRequest.qml
- ui/app/mainui/activitycenter/views/ActivityNotificationMessage.qml
Close #9637
Partially fixes #12646
https://github.com/status-im/status-desktop/assets/2522130/c10e657b-03fb-4b8b-a93d-6d1f575fbfdf
(on video limit of notifications is 7, default is 20)
> feat(ActivityCenter): Fetch notifications on scroll to bottom

- ui/app/AppLayouts/Onboarding/views/CreatePasswordView.qml
- ui/app/AppLayouts/Profile/popups/ChangePasswordModal.qml
- ui/imports/shared/popups/keycard/states/CreatePassword.qml
- ui/imports/shared/views/PasswordView.qml
This PR fixes #11965
During the password creation flow, the description underneath the Create password label didn't have any constraints on the number of lines to display the text. This caused the overall components below the description to move down, which is not expected. This pull request adds a 2 lines constraint on the mentioned description.
- Onboarding Create and Confirm screens.
- Also can affect Change Password view since they share qml component.
Here is the original text in English : 
The longest translation for the first sentence is in German, with 76 characters: `Erstellen Sie ein Passwort, um Status auf diesem Gerät zu entsperren und Transaktionen zu signieren.`
The longest translation for the second sentence is in French, with 61 characters: `Vous ne pourrez pas récupérer …
> fix(Onboarding): Apply 2 line constraint for create password description text

- ci/Jenkinsfile.combined
The current solution needs to be fixed.
We have nightly build #59: https://ci.status.im/job/status-desktop/job/nightly/
And e2e tests:
https://ci.status.im/job/status-desktop/job/systems/job/linux/job/x86_64/job/tests-e2e-new/66/parameters/
Looks like we didn't receive TESTRAIL_RUN_NAME parameter
In the PR I updated the creation of data time variable.
Tested here with echo:
https://ci.status.im/job/status-desktop/job/e2e/job/manual/934/console
> chore: Generate test run name for Test Rail

- storybook/pages/ManageCollectiblesPanelPage.qml
- storybook/qmlTests/main.cpp
- storybook/qmlTests/tests/tst_ManageCollectiblesPanel.qml
- storybook/src/Models/ManageCollectiblesModel.qml
- storybook/src/Models/ModelsData.qml
- storybook/src/Models/qmldir
- ui/StatusQ/src/StatusQ/Components/StatusDraggableListItem.qml
- ui/StatusQ/src/assets.qrc
- ui/StatusQ/src/wallet/managetokenscontroller.cpp
- ui/StatusQ/src/wallet/managetokensmodel.cpp
- ui/StatusQ/src/wallet/managetokensmodel.h
- ui/app/AppLayouts/Wallet/controls/ManageTokenMenuButton.qml
- ui/app/AppLayouts/Wallet/controls/ManageTokensCommunityTag.qml
- ui/app/AppLayouts/Wallet/controls/ManageTokensDelegate.qml
- ui/app/AppLayouts/Wallet/controls/ManageTokensGroupDelegate.qml
- ui/app/AppLayouts/Wallet/controls/qmldir
- ui/app/AppLayouts/Wallet/panels/ManageCollectiblesPanel.qml
- ui/app/AppLayouts/Wallet/panels/qmldir
- implements a QML panel to organize collectibles
- factors out the delegates to separate files to be reusable with the Assets tab
- adds QML tests to assess the UI functionality (move, show/hide, save/load)
- does NOT cover the problematic "Arrange by collection" switch (will be handled separately in https://github.com/status-im/status-desktop/issues/12703)
Fixes: https://github.com/status-im/status-desktop/issues/12379
Adds a Manage Collectibles UI panel component to storybook
storybook
> feat: Manage Collectibles panel UI component & model

- src/app/modules/main/chat_section/chat_content/input_area/controller.nim
- src/app/modules/main/chat_section/chat_content/input_area/link_preview_cache.nim
There was a bug, we were checking `linkPreviewsCache` for unknown URLs.  But it's possible that we start editing the message before the unfurling response is received.
Now we also save the list of requested URLs and check it before making a new request.
It's possible to see from the logs that after the second `setText` there're no new URLs found.
```go
DBG 2023-11-10 11:02:30.104+00:00 <<< setText                                tid=28511231 file=controller.nim:202
DBG 2023-11-10 11:02:30.105+00:00 NewBE_callPrivateRPC                       topics="rpc" tid=28511231 file=core.nim:27 rpc_method=wakuext_getTextURLs
DBG 2023-11-10 11:02:30.146+00:00 <<< newUrls                                tid=28511231 file=controller.nim:216 newUrls="@[\"https://github.com/status-im/status-go/pull/4280\", …
```
> fix: avoid duplicating UnfurlURLs requests

- src/app/modules/shared_models/collectible_details_entry.nim
- src/app/modules/shared_models/collectibles_utils.nim
- src/app/modules/shared_modules/collectible_details/controller.nim
- src/app/modules/shared_modules/collectibles/controller.nim
- src/app_service/service/community_tokens/service.nim
- src/backend/collectibles.nim
- src/backend/collectibles_types.nim
Part of https://github.com/status-im/status-desktop/issues/12578
Adjust client to the changes implemented in https://github.com/status-im/status-go/pull/4290
Models are all the same, we're just adapting to the new functions / structs used in the backend.
> feat(@wallet/desktop): implement generalized collectibles api

- ui/app/AppLayouts/Profile/views/wallet/AccountOrderView.qml
- ui/app/AppLayouts/Wallet/views/LeftTabView.qml
fixes #12777
Fixes issues in account ordering and wallet left header
WalletLayout, Wallet Settings -> account ordering
https://github.com/status-im/status-desktop/assets/60327365/a87ff0a6-71a5-4d06-8730-93be96eddd2d
> fix(@desktop/wallet): Wallet TEST_MODE: account ordering is buggy when in test mode

- ci/Jenkinsfile.combined
This way they are available earlier for E2E tests. Also bump general job timeout.
> fix(ci): archive copied artifacts right away

- ci/Jenkinsfile.linux
Set keycard mock lib to False. I made some investigation over here https://github.com/status-im/desktop-qa-automation/issues/328#issuecomment-1820981445 and as a conclusion I can say that KEYCARD_MOCK_LIB affects the application behaviour in unpredictable way. It also impacts the tests we try to implement. 
I need to have it disabled so I can monitor the progress, but i also need the possibility to enable it when i need it (manually)
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1057/allure/
> chore: keycard mocked lib is set to false by default

- src/app/global/utils.nim
- src/app/modules/main/wallet_section/wallet_connect/controller.nim
- src/app/modules/main/wallet_section/wallet_connect/helper.nim
- src/app/modules/main/wallet_section/wallet_connect/session_response_dto.nim
- src/backend/wallet_connect.nim
- ui/app/AppLayouts/Wallet/views/walletconnect/WalletConnect.qml
- https://github.com/status-im/status-go/pull/4345
Closes: #12730
> feat(@desktop/walletconnect): signing tx or personal sign via keycard

- ui/app/AppLayouts/Chat/ChatLayout.qml
Closes #12678
Fixed unable to join token gated community
CommunityIntroDialog
https://github.com/status-im/status-desktop/assets/31625338/9c73db03-175f-4e06-a8f0-874023f6fa7f
> fix(CommunityIntroDialog): Unable to join token gated community

- storybook/pages/EditCommunityTokenViewPage.qml
- storybook/pages/MintTokensSettingsPanelPage.qml
- ui/app/AppLayouts/Chat/ChatLayout.qml
- ui/app/AppLayouts/Communities/panels/MintTokensSettingsPanel.qml
- ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml
- ui/app/AppLayouts/Communities/views/EditCommunityTokenView.qml
- ui/app/AppLayouts/Wallet/stores/TokensStore.qml
- ui/app/AppLayouts/stores/RootStore.qml
- ui/app/mainui/AppMain.qml
Closes #12365
- It adds link to the corresponding tokens model in `EditCommunityTokenView`.
- It adds validation for `name` and `symbol`.
- It updates `storybook accordingly.`
**NOTE**: Real validation will be available into the app once the following [pr](https://github.com/status-im/status-desktop/pull/12489) is integrated 
https://github.com/status-im/status-desktop/assets/97019400/21c0da5f-f883-44ac-a4d8-f9bf89946c01
> feat(MintToken): Validation on name / symbol if exists in standard token list

- ui/StatusQ/src/wallet/managetokenscontroller.cpp
a feeble attempt to make M$ compiler grok otherwise valid C++17 code
Unbreaks Windows build
> fix(Windows): unbreak Windows build

- ui/app/AppLayouts/Chat/ChatLayout.qml
Cherry-pick of f011fcd5c311738e28ddf865675a7aa86ae1581a
if a privileged user lost his permission while being in the community settings - the community UI became blank
Closes:
- https://github.com/status-im/status-desktop/issues/12805
- https://github.com/status-im/status-desktop/issues/12468
> fix: quit from community settings in UI if member privileged role changed (cherry-pick)

- src/app_service/service/community_tokens/service.nim
The default structure was emitted, when there was computing fees error.
This default structure contained CurrencyAmount type fields which were nil (they are pointers).
Json conversion function caused crash.
> 12847 fix crash fees

- Makefile
- ui/StatusQ/CMakeLists.txt
- ui/StatusQ/tests/CMakeLists.txt
It fixes `make run-statusq-tests` to run all `StatusQ`'s test targets via `ctest`. Also applies required ctest-related fixes in `StatusQ`'s cmake files.
Closes: #12841
`StatusQ` cmake configs, `Makefile`
> fix(StatusQ): Run all unittests via make and on CI

- src/app/modules/shared_models/message_model.nim
Fixes #12785
Based on top of https://github.com/status-im/status-desktop/pull/12804 to make sure I didn't create conflicts
Status-go PR https://github.com/status-im/status-go/pull/4354
[delte-reply.webm](https://github.com/status-im/status-desktop/assets/11926403/344fceb8-38c9-4c2c-ba6c-a9140558247f)
> fix(message): fix deleting a quoted message loses the user info

- ui/StatusQ/src/StatusQ/Components/StatusToolBar.qml
align the left padding with the chat contents; reapply the needed extra margin for the back button
Fixes #12859
Fixes too big left margin in chat header
Chat, StatusToolbar
> fix: Misaligned profile image in chat header

- ui/StatusQ/src/QClipboardProxy.cpp
check for the (supported) extension in case insensitive manner. Fixes uploading/sending/DND files like "foo.JPG"
Fixes #12835
Fixes uploading supported images with uppercase extension
Chat
> fix: supported image formats are case sensitive

- ui/app/AppLayouts/Chat/ChatLayout.qml
Show info about the control node offline, during rejoining the community after the ownership change
This code was accidentally removed during the rebase
Closes: https://github.com/status-im/status-desktop/issues/12868
> fix: show info about the control node offline, during rejoining the community after the ownership change

- src/app/modules/main/activity_center/module.nim
Close #10311
Display Community and Chat badges in the Activity Center
ActivityCenter
> fix(ActivityCenter): Fix Community and Chat badges in the Activity Center

- ui/StatusQ/src/StatusQ/Components/private/statusMessage/StatusTextMessage.qml
Fixes emojis being shown as plain HTML markup in replies
- revert to previous behavior, we want RichText even though we really don't :)
Fixes #12786
StatusTextMessage
> fix(chat): Emoji is html-encoded in message reply

- src/app/boot/app_controller.nim
- src/app_service/common/activity_center.nim
- src/app_service/service/activity_center/service.nim
- src/app_service/service/community/service.nim
- src/app_service/service/community_tokens/service.nim
- src/app_service/service/contacts/service.nim
- src/app_service/service/message/async_tasks.nim
- src/app_service/service/message/service.nim
Close #9349
Waits https://github.com/status-im/status-go/pull/4337
Activity Center, Messages
https://github.com/status-im/status-desktop/assets/2522130/a6d4c7e1-6eaf-4a38-91b0-7687c1134ed3
> feat(ActivityCenter): Sync message & AC notification read state

- src/app/modules/main/chat_section/controller.nim
- src/app/modules/main/chat_section/io_interface.nim
- src/app/modules/main/chat_section/module.nim
Fixes #12719
The problem was that we had two event handlers that did the same thing and if the main module's event processed first, the second event would basically reset the active item, causing the UI to try to fetch an empty chat content.
If you comment out the main module event handler, it doesn't work correctly, because it's the one doing the actual section switching.
Removing the chat section event handling is ok, because the main module already calls its child's (chat section) same functions.
@igor-sirotin I'm guessing you couldn't reproduce because somehow for you, the chat section event processed first.
> fix(chat_section): remove duplicated event handling

- src/app/boot/app_controller.nim
- src/app/modules/main/wallet_section/send/account_item.nim
- src/app/modules/main/wallet_section/send/view.nim
- src/app/modules/startup/io_interface.nim
- src/app/modules/startup/module.nim
Fixes #12880
There were two problems:
1. We manually delete the startup module on login to free memory. Part of that clean up includes remove the QVariant (` singletonInstance.engine.setRootContextProperty("startupModule", newQVariant())`), but since that code was put in the `delete` function of the module, it meant it was also executed on quit, and you can't call `setRootContextProperty` on quit
2. The wallet module is created on app start. That's fine, it doesn't do anything. However, it has a sub module that later in its cycle creates account items, but most of the time, those account items are not initiated, so on `delete`, there was a crash.
> fix(delete): fix closing the app before login would make it crash

- src/app/modules/main/communities/view.nim
Cherry-pick
requestCommunityInfo signature was invalid, from QML side we sent 4 params, while here we accept only 2
It was working somehow, but importing was always true, which led to importing community instead of sharing it, when the community owner sent an invitation to the community with the minted owner
Closes: https://github.com/status-im/status-desktop/issues/12883
> fix: share community instead of import during inviting community member in the community with minted owner token (CHERRY_PICK))

- src/app/modules/main/communities/view.nim
`requestCommunityInfo` signature was invalid, from QML side we sent 4 params, while here we accept only 2
It was working somehow, but `importing` was always `true`, which led to importing community instead of sharing it, when the community owner sent an invitation to the community with the minted owner
Closes: https://github.com/status-im/status-desktop/issues/12883
> fix: share community instead of import during inviting community member in the community with minted owner token

- src/app_service/service/community/service.nim
- src/app_service/service/community_tokens/service.nim
- src/app_service/service/contacts/service.nim
- src/app_service/service/message/async_tasks.nim
Close #12889
Fixes the crash when accepting a CR and a few more random crashes
> Fix: Crash when handling response without AC notifications

- shell.nix
- src/app/modules/main/chat_section/chat_content/controller.nim
- src/app/modules/main/chat_section/chat_content/io_interface.nim
- src/app/modules/main/chat_section/chat_content/messages/io_interface.nim
- src/app/modules/main/chat_section/chat_content/module.nim
- src/app/modules/main/chat_section/chat_content/view.nim
- src/app/modules/main/chat_section/controller.nim
- src/app/modules/main/chat_section/io_interface.nim
- src/app/modules/main/chat_section/module.nim
- src/app/modules/main/chat_section/view.nim
- src/app_service/service/mailservers/service.nim
- src/backend/mailservers.nim
- ui/app/AppLayouts/Chat/views/ChatHeaderContentView.qml
- ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
- ui/app/AppLayouts/Communities/views/CommunityColumnView.qml
- ui/imports/shared/views/chat/ChatContextMenuView.qml
This PR adds support for fetching messages for a given channel.
It will perform a request fetching the last 30 days.
This is useful for dogfooding and debugging, and it will be enabled only on developer mode (have yet to do that). 
We discussed with John/Design and they are not going to want the feature on production builds.
I have added a working nix shell to build the project, taken from @jakubgs and slightly modified, it pulls too many dependencies, but it works.
I have literally no clue what I am doing, but it seems to be working (I can see the request is made correctly in status-go).
> Add fetch messages 

- src/app/boot/app_controller.nim
- src/app/modules/main/wallet_section/all_tokens/controller.nim
- src/app/modules/main/wallet_section/all_tokens/flat_tokens_model.nim
- src/app/modules/main/wallet_section/all_tokens/io_interface.nim
- src/app/modules/main/wallet_section/all_tokens/market_details_item.nim
- src/app/modules/main/wallet_section/all_tokens/module.nim
- src/app/modules/main/wallet_section/all_tokens/token_by_symbol_model.nim
- src/app/modules/main/wallet_section/all_tokens/view.nim
- src/app_service/service/network_connection/service.nim
- src/app_service/service/token/async_tasks.nim
- src/app_service/service/token/dto.nim
- src/app_service/service/token/service.nim
- src/app_service/service/token/service_items.nim
- src/backend/backend.nim
Loading market values and details for tokens in the token_service. 
THe same repeating part will be cleaning up from wallets_accounts assets when we work on that.
The idea is that all generic token related values are retrieved from tokens service and tokens model
Nothing yet. Just implements backend for getting wallet toke details under token details.
> Fix/12668: Add new go api to get token market values not bundled with token balances

- ui/imports/shared/views/AssetsView.qml
fix(@desktop/wallet): Adds STT for default tokens visible
removes condition for showing only tokens with non zero balance as that part is already done on status_go side
Read description
Wallet Assets View
https://github.com/status-im/status-desktop/assets/60327365/0ac353e2-74bf-4491-a8fa-3f9f3582ce8d
> fix(@desktop/wallet): Adds STT for default tokens visible

- src/app/modules/main/communities/controller.nim
- src/app/modules/main/profile_section/ens_usernames/controller.nim
- src/app/modules/main/stickers/controller.nim
- src/app/modules/main/wallet_section/send/controller.nim
- src/app/modules/shared_modules/add_account/controller.nim
- src/app/modules/shared_modules/keycard_popup/controller.nim
- src/app/modules/startup/controller.nim
I've checked some complex and critical flows after I removed os `sleep`, looks like the keycard flows work just fine.
Since that was introduced a long time ago, after that the code was copied wherever we wanted to cancel the current and run a new flow successively, we ended up with that code in several places across the app.
But during that period many things on the keycard lib side were improved as well as on the desktop app side, many things that were called directly initially are not async calls, seems that we got rid of the need for that line of code, that's why I'm removing it here.
Though I cannot recall exactly what was the case where we needed it at the beginning with keycard features implementation, I cannot find the reason now why should we keep it, I've checked and tested the …
> chore(@dekstop/keycard): os sleep used in the past is not needed any more

- ci/Jenkinsfile.tests-e2e
Update config to `squish-7.2.1-qt515x-linux64`
```
21:08:00  ---------------------------------------------
21:08:00  Squish plug-in version is: 8.6
21:08:00  ---------------------------------------------
21:08:00  Squish tests executed on "linux-03" agent
21:08:00  ---------------------------------------------
21:08:00  Squish tests executed with squishrunner:
21:08:00  /opt/squish-runner-7.2.1/buildinfo.txt
21:08:00  Package Name:  squish-7.2.1-qt515x-linux64
21:08:00  Internal Name: /home/autotest/public_html/binpackages/2023/11/04-1700/bin_package/7.2.1/qt/Dock10-Qt5.15.0binary-TkNone-iOSNone-def-08dc30a
21:08:00  Git Branch:    7.2.1
21:08:00  Git Revision:  966be14528b68781a196490efd4b6f21e7340b66
21:08:00  
21:08:00  Python Version: default
21:08:00  Patched:        False
21:08:00 …
```
> chore: update to new squish version

- src/app/modules/main/browser_section/current_account/controller.nim
- src/app/modules/main/browser_section/current_account/module.nim
- src/app/modules/main/profile_section/profile/controller.nim
- src/app/modules/main/profile_section/profile/models/profile_preferences_asset_item.nim
- src/app/modules/main/profile_section/wallet/accounts/module.nim
- src/app/modules/main/wallet_section/assets/controller.nim
- src/app/modules/main/wallet_section/assets/module.nim
- src/app/modules/main/wallet_section/overview/controller.nim
- src/app/modules/main/wallet_section/overview/module.nim
- src/app/modules/main/wallet_section/send/controller.nim
- src/app/modules/shared/wallet_utils.nim
- src/app/modules/shared_modules/keycard_popup/io_interface.nim
- src/app/modules/shared_modules/keycard_popup/module.nim
- src/app_service/service/ens/service.nim
- src/app_service/service/stickers/service.nim
- src/app_service/service/token/service.nim
- src/app_service/service/token/service_items.nim
- src/app_service/service/wallet_account/dto/account_dto.nim
- src/app_service/service/wallet_account/signals_and_payloads.nim
- src/backend/backend.nim
- src/backend/helpers/balance.nim
- src/backend/helpers/helpers.nim
- src/backend/helpers/token.nim
Replace it with the new API `GetWalletToken`
Move the backend-related JSON parsing to the `backend/helpers` folder close to the source so as not to create reverse dependencies.
Update some imports to absolute paths.
Remove related indirect imports.
> fix(wallet) remove unused API GetTokensBalances old api

- src/app_service/service/community/async_tasks.nim
- src/app_service/service/community/dto/community.nim
- src/app_service/service/community/service.nim
- src/backend/communities.nim
Receive all non-approved requests to join through the API `allNonApprovedCommunitiesRequestsToJoin`
Closes: https://github.com/status-im/status-go/issues/4419
Status-go PR: https://github.com/status-im/status-go/pull/4422
Requests to join
> chore: receive all non-approved requests to join through the API allNonApprovedCommunitiesRequestsToJoin

- storybook/pages/ConcatModelPage.qml
- ui/StatusQ/CMakeLists.txt
- ui/StatusQ/include/StatusQ/concatmodel.h
- ui/StatusQ/src/concatmodel.cpp
- ui/StatusQ/src/modelutilsinternal.cpp
- ui/StatusQ/src/plugin.cpp
- ui/StatusQ/tests/CMakeLists.txt
- ui/StatusQ/tests/tst_ConcatModel.cpp
This PR provides next generic utility proxy model. It allows concatenating multiple source models, with same roles, partially different roles or even totally different roles. The model performs necessary roles mapping internally.
The proxy is similar to https://doc.qt.io/qt-5/qconcatenatetablesproxymodel.html but QML-ready, performing all necessary role names remapping.
Roles are established when first item appears in one of the sources. Expected roles can be also declared up-front using `expectedRoles` property (because on first insertion some roles may be not yet available via `roleNames() `on other models).
Additionally the model introduces additional role with name configurable via `markerRoleName` property. Value of this role may be set separately for each source model in …
> feat(StatusQ): QML-oriented proxy model concatenating source models vertically

- Makefile
- src/app/boot/app_controller.nim
- src/app_service/service/accounts/service.nim
- src/app_service/service/node_configuration/service.nim
- src/constants.nim
Requires https://github.com/status-im/status-desktop/pull/12916
Requires https://github.com/status-im/status-desktop/pull/12934
1. Pass correct value to status-go log level when `TRACE` logs are used.
`TRACE` is not supported by status-go, so we replace it with `DEBUG`.
2. Fix places that were checking for `LOG_LEVEL` env variable.
- Use `STATUS_RUNTIME_LOG_LEVEL` instead
- Aldo check if `--log-level` CLI option is set
> Fix `TRACE` log level support

- src/app/modules/main/chat_section/chat_content/messages/controller.nim
- src/app/modules/main/chat_section/chat_content/messages/io_interface.nim
- src/app/modules/main/chat_section/chat_content/messages/module.nim
- src/app/modules/main/chat_section/chat_content/messages/view.nim
- src/app/modules/main/chat_section/controller.nim
- src/app/modules/main/chat_section/io_interface.nim
- src/app/modules/main/chat_section/module.nim
- src/app/modules/shared_models/message_model.nim
- src/app_service/service/chat/service.nim
- src/app_service/service/message/async_tasks.nim
- src/app_service/service/message/service.nim
- src/backend/messages.nim
- test/nim/message_model_test.nim
- ui/app/AppLayouts/Chat/stores/MessageStore.qml
- ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
- ui/imports/shared/views/chat/MessageContextMenuView.qml
- ui/imports/shared/views/chat/MessageView.qml
[Link to status-go changes](https://github.com/status-im/status-go/pull/4382)
Feature to enhance message context menu with mark as unread.
[Figma design](https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?type=design&node-id=14632-460085&mode=design&t=9iVc38RXY5QVm5uz-0)
fixes #10329
The PR does the following : 
- Adds capacity to mark a message as unread
- Adds capacity to mark a message with mention as unread
- Adds persistence to the marking of the message (change can be seen at after reboot)
- Adds marking in right click contextual menu
- Chat screen
- Contextual menu (Right click 
[Screencast from 2023-11-30 09:08:03 AM.webm](https://github.com/status-im/status-desktop/assets/2589171/9da6b145-603d-4999-9052-228195f34cce)
> feature(@desktop/chat) Enhance message context menu with mark as unread

- ui/imports/shared/popups/addaccount/states/Main.qml
Closes #12907
Wallet/AddAccountPopup: Removed emoji random selection
Wallet/AddAccountPopup
https://github.com/status-im/status-desktop/assets/31625338/f09e220b-41ab-4fb3-9d85-83d6d718df75
> fix(Wallet/AddAccountPopup): Removed emoji random selection

- ui/app/AppLayouts/Onboarding/views/LoginView.qml
Closing #11274 
The wrong password error message coming from status-go can be different depending on the app flow. The only constant is the sqlite error message used for wrong key: `SQLITE_NOTADB: "file is not a database"`.
The LoginView now checks if the sqlite `file is not a database` error is included in the message.
LoginView
https://github.com/status-im/status-desktop/assets/47811206/fc5c6003-d5fe-4253-8b79-70b3f1337a98
> fix: Show wrong password error on V4 migration as well

- storybook/pages/CommunitiesViewPage.qml
- storybook/pages/InviteFriendsToCommunityPopupPage.qml
- ui/app/AppLayouts/Communities/popups/InviteFriendsToCommunityPopup.qml
- ui/app/AppLayouts/Profile/stores/ProfileSectionStore.qml
turns out the model from the communitiesModule doesn't contain the members; use the sectionModel (as in all other places) instead which already has the correct info
additionally, fix the InviteFriendsToCommunityPopup display, it appeared empty all the time
(plus some relevant storybook fixes)
Fixes #12967
Fixes the member count and invite popup in Communities settings
CommunitiesView, InviteFriendsToCommunityPopup
Correct member count:
... in SB too:
Invite popup working again:
> fix(CommunitiesView): display proper member count

- ui/StatusQ/src/StatusQ/Components/StatusImage.qml
Fixes #12991
Fixes blurry rendering for non SVG images
StatusImage
> fix(StatusImage) blurry rendering due to wrong sourceSize

- ui/app/AppLayouts/Profile/views/MessagingView.qml
Added object names for Messaging settings page. I need them for tests
`ui/app/AppLayouts/Profile/views/MessagingView.qml`
> chore: add object names for Messaging settings page

- storybook/pages/AssetsViewPage.qml
- storybook/pages/CollectiblesViewPage.qml
- storybook/pages/ManageAssetsPanelPage.qml
- storybook/pages/ManageCollectiblesPanelPage.qml
- storybook/src/Models/ManageTokensModel.qml
- ui/StatusQ/src/rolesrenamingmodel.cpp
- ui/StatusQ/src/submodelproxymodel.cpp
- ui/StatusQ/src/wallet/managetokenscontroller.cpp
- ui/StatusQ/src/wallet/managetokenscontroller.h
- ui/app/AppLayouts/Profile/ProfileLayout.qml
- ui/app/AppLayouts/Profile/views/WalletView.qml
- ui/app/AppLayouts/Profile/views/wallet/ManageTokensView.qml
- ui/app/AppLayouts/Wallet/WalletLayout.qml
- ui/app/AppLayouts/Wallet/controls/SortOrderComboBox.qml
- ui/app/AppLayouts/Wallet/panels/ManageAssetsPanel.qml
- ui/app/AppLayouts/Wallet/panels/ManageCollectiblesPanel.qml
- ui/app/AppLayouts/Wallet/views/AssetsDetailView.qml
- ui/app/AppLayouts/Wallet/views/CollectiblesView.qml
- ui/app/AppLayouts/Wallet/views/RightTabView.qml
- ui/app/mainui/AppMain.qml
- ui/imports/shared/views/AssetsView.qml
- ui/imports/shared/views/HistoryView.qml
- ui/imports/utils/Constants.qml
- ui/imports/utils/Global.qml
- add the sort combobox to assets/collectibles main wallet view pages
- preserve the current view settings
- add the possibility to navigate/drill down into wallet settings (sub)subsection
- some other minor changes/fixes
Note: currently assets can't be sorted by "1W change" and collectibles by "Date added" due to missing backend for these
Fixes #12517
Fixes #12518
Adds asset/collectibles filtering to the wallet front page
Wallet
Assets sorted by balance value:
Custom order defined:
Custom order being displayed:
Collectibles sorted by collection or community name:
> (wallet) implement sorting for assets/collectibles views

- ui/StatusQ/CMakeLists.txt
- ui/StatusQ/include/StatusQ/fastexpressionrole.h
- ui/StatusQ/src/fastexpressionrole.cpp
- ui/StatusQ/src/plugin.cpp
- ui/StatusQ/tests/CMakeLists.txt
- ui/StatusQ/tests/TestCore/TestModels/tst_FastExpressionRole.qml
- ui/StatusQ/tests/main.cpp
- ui/StatusQ/tests/src/TestHelpers/modelaccessobserverproxy.cpp
- ui/StatusQ/tests/src/TestHelpers/modelaccessobserverproxy.h
- Provides `FastExpressionRole` component compatible with `SortFilterProxyModel`. In comparison to original `ExpressionRole` it allows to define which role values should be provided to the expression's context. This approach improves performance significantly in most cases.
- Simple test utility for tracking access to a model
Closes: #13047
`StatusQ`, `Qt Proxy Models Lib`
> feat(StatusQ): Faster version of SFPM's ExpressionRole

- ui/StatusQ/include/StatusQ/concatmodel.h
- ui/StatusQ/src/concatmodel.cpp
- ui/StatusQ/tests/tst_ConcatModel.cpp
The general rule should be to avoid any actions on destruction different than setting relevant pointers to null. Other actions like emiting signals are potentially dangerous when the whole objects hierarchy is under destruction.
Closes: #13065
`StatusQ`/`ConcatModel`
> fix(ConcatModel): Changed behavior on submodel destruction to not emit signals

- ui/StatusQ/include/StatusQ/leftjoinmodel.h
- ui/StatusQ/src/leftjoinmodel.cpp
- ui/StatusQ/tests/tst_ConcatModel.cpp
- ui/StatusQ/tests/tst_LeftJoinModel.cpp
- ability to change left/right models
- improved handling of model deletion
- base class changed to QAbstractListModel, dataChanged signal emision improved
Closes: #12912
`StatusQ`, `Qt Proxy Models Lib`
> feat(StatusQ): Ability to change sources in `LeftJoinModel`

- ui/imports/shared/popups/UserStatusContextMenu.qml
Added an object name for this header so i can better init this whole object of context menu better (improves test stability)
> chore: add object name for online identify header

- src/app/modules/main/stickers/controller.nim
- src/app/modules/main/stickers/io_interface.nim
- src/app/modules/main/stickers/models/sticker_list.nim
- src/app/modules/main/stickers/module.nim
- src/app/modules/main/stickers/view.nim
linked to https://github.com/status-im/status-go/pull/4474
Fix recent stickers displayed after sticker packs are deleted
- Sticker functionality
[Screencast from 2023-12-20 06:03:27 PM.webm](https://github.com/status-im/status-desktop/assets/2589171/fadda375-b400-426d-ab11-0e2d0c2f0bd6)
> Fix recent stickers displayed after sticker packs are deleted

- src/app/modules/main/communities/controller.nim
- src/app/modules/main/communities/io_interface.nim
- src/app/modules/main/communities/module.nim
- src/app/modules/main/communities/view.nim
- src/app_service/service/community/service.nim
- ui/app/AppLayouts/Chat/stores/RootStore.qml
- ui/app/AppLayouts/Communities/stores/CommunitiesStore.qml
Fixes https://github.com/status-im/status-desktop/issues/12537
status-go PR: https://github.com/status-im/status-go/pull/4446
This status-go update contains refactoring of fetching communities.
I made quick tests of where we fetch communities in status-desltop:
- Import community (with public key)
- Link previews
Would be nice to test other places if we have any. E.g. community directory, but I couldn't get any curated communities.
> chore: update for StoreNodeRequestManager

- ui/StatusQ/src/StatusQ/Controls/StatusImageSelector.qml
- ui/imports/shared/popups/ImageCropWorkflow.qml
- ui/imports/utils/Constants.qml
Fixes: #13077
Removes `.heif, .tif(f)` supporting from file dialogs
Edit profile
> fix(images-formats): Remove .heif and .tif(f) from supported formats

- src/app_service/service/activity_center/service.nim
- src/app_service/service/message/async_tasks.nim
- src/app_service/service/message/dto/seen_unseen_messages.nim
- src/app_service/service/message/service.nim
- src/backend/messages.nim
Close #12857
Waits https://github.com/status-im/status-go/pull/4461
When a user marks an activation center notification as read, the corresponding message in the chat is considered read and the chat and community counters are updated.
Chat, Communities, Activity Center
https://github.com/status-im/status-desktop/assets/2522130/9e158e8d-646c-439f-8114-228a11372d81
> feat: update chat unseen counters from the Activity Center

- test/ui-test/testSuites/suite_communities/shared/scripts/community_names.py
- ui/app/AppLayouts/Communities/controls/PermissionItem.qml
Object names for permission tags
`ui/app/AppLayouts/Communities/controls/PermissionItem.qml`
> chore: several object names for permissions tags

- storybook/pages/AssetsViewPage.qml
- storybook/pages/CollectiblesViewPage.qml
- storybook/qmlTests/tests/tst_ManageCollectiblesPanel.qml
- storybook/src/Models/ManageCollectiblesModel.qml
- storybook/stubs/shared/stores/CurrenciesStore.qml
- ui/StatusQ/src/StatusQ/Controls/StatusBaseInput.qml
- ui/StatusQ/src/StatusQ/Controls/StatusComboBox.qml
- ui/StatusQ/src/StatusQ/Core/StatusAssetSettings.qml
- ui/StatusQ/src/concatmodel.cpp
- ui/StatusQ/src/wallet/managetokenscontroller.cpp
- ui/StatusQ/src/wallet/managetokenscontroller.h
- ui/StatusQ/src/wallet/managetokensmodel.cpp
- ui/StatusQ/tests/tst_ConcatModel.cpp
- ui/app/AppLayouts/Wallet/controls/FilterComboBox.qml
- ui/app/AppLayouts/Wallet/controls/qmldir
- ui/app/AppLayouts/Wallet/panels/ActivityFilterPanel.qml
- ui/app/AppLayouts/Wallet/views/CollectiblesView.qml
- ui/app/AppLayouts/Wallet/views/RightTabView.qml
- ui/imports/shared/controls/TokenDelegate.qml
- ui/imports/shared/views/AssetsView.qml
- ui/imports/shared/views/HistoryView.qml
- ui/imports/shared/views/chat/ProfileContextMenu.qml
.. to filter by community or collection name
- make the HistoryView own filter button look like the other combos
- fix some cosmetic issues for StatusCombo in small/secondary mode
- fix StatusBaseInput bg color in dark mode (was invisible)
- update CollectiblesViewPage with options to include regular and/or
community collectibles
Fixes https://github.com/status-im/status-desktop/issues/12969
Fixes https://github.com/status-im/status-desktop/issues/12948
Adds a filtering combo to the collectibles view
Wallet/CollectiblesView
Storybook with optional collectibles' sources:
> feat(CollectiblesView): Add combobox/popup with custom filtering options

- ui/StatusQ/tests/CMakeLists.txt
- ui/StatusQ/tests/main.cpp
- ui/StatusQ/tests/src/TestHelpers/listmodelwrapper.cpp
- ui/StatusQ/tests/src/TestHelpers/listmodelwrapper.h
- ui/StatusQ/tests/src/TestHelpers/testmodel.cpp
- ui/StatusQ/tests/src/TestHelpers/testmodel.h
- ui/StatusQ/tests/tst_Aggregator.cpp
- ui/StatusQ/tests/tst_ConcatModel.cpp
- ui/StatusQ/tests/tst_LeftJoinModel.cpp
- ui/StatusQ/tests/tst_RolesRenamingModel.cpp
- ui/StatusQ/tests/tst_SingleRoleAggregator.cpp
- ui/StatusQ/tests/tst_SubmodelProxyModel.cpp
- ui/StatusQ/tests/tst_SumAggregator.cpp
Before creating common testing library (https://github.com/status-im/status-desktop/pull/13032) some utilities were duplicated across multiple test files. Now they are moved to the library reducing duplication.
- `ListModelWrapper` (testing utility exposing qml's `ListModel` to cpp) excluded to a separate file
- Generic `TestModel` excluded to a separate file
Closes: https://github.com/status-im/status-desktop/issues/12843
`StatusQ`'s tests related to proxy models
> chore(StatusQ): Models-related testing utilities moved to a testing lib

- src/app/modules/main/chat_section/chat_content/messages/module.nim
- src/app_service/service/message/dto/message.nim
linked to https://github.com/status-im/status-go/pull/4516
This PR fixes [#12821](https://github.com/status-im/status-desktop/issues/12821)
This Pull Request is a continuation on [10986](https://github.com/status-im/status-desktop/issues/10986)
In the earlier version of the Status App, we employed a map associating albums with images to establish a connection between the received images and the corresponding message album. While this approach represented an improvement over the initial state of the application, where no mechanism facilitated the retrieval of quoted images, it faced limitations due to the finite number of messages received. Consequently, a quoted image might not be displayed if the associated message is too old.
The resolution presented in this Pull Request involves adding …
> Fix thumbnail images for quoted message

- storybook/pages/WritableProxyModelPage.qml
- ui/StatusQ/CMakeLists.txt
- ui/StatusQ/include/StatusQ/writableproxymodel.h
- ui/StatusQ/src/plugin.cpp
- ui/StatusQ/src/writableproxymodel.cpp
- ui/StatusQ/tests/CMakeLists.txt
- ui/StatusQ/tests/tst_WritableProxyModel.cpp
Part of #12690
WritableProxyModel is a QAbstractProxyModel that allows you to modify the data without modifying the source model. It is useful for implementing a "dirty" state for a model, where you can modify the data and then commit the changes to the source model.
Supported features (reimplemented):
- setData
- setItemData
- removeRows
- insertRows
- moveRows (TODO. It supports move only source model move)
- toVariantMap
- revert
- to be continued...
Limitations:
Supports only list models. This means only 1 column and no parent for the items.
Usage example: https://github.com/status-im/status-desktop/pull/12898/files#diff-6f0f1b2d4d9522735e91ef5777baed02b1426d6b0eec56340783bb11b0fe18e6
Particularities:
1. Edited items won't be removed if the source model removes them. These items will …
> StatusQ: Adding WritableProxyModel

- ui/app/AppLayouts/Wallet/views/RightTabBaseView.qml
- ui/app/AppLayouts/Wallet/views/RightTabView.qml
Fixes #13157
Set and propagate the correct height for the scrolling to work again
Wallet/RightTabView
[Záznam obrazovky z 2024-01-10 10-31-22.webm](https://github.com/status-im/status-desktop/assets/5377645/6f341f86-65fe-4cc1-9da9-c9f5daf1144c)
> fix(wallet): unbreak scrolling of the wallet views

- ui/app/AppLayouts/Profile/views/wallet/MainView.qml
Added object names for new settings items in `ui/app/AppLayouts/Profile/views/wallet/MainView.qml`
`ui/app/AppLayouts/Profile/views/wallet/MainView.qml`
> chore: object names for new settings items in wallet settings

- src/app/modules/main/chat_section/module.nim
Show create/update/delete permissions toast notification for privileged members only when it is approved by the control node, and not when it is pending.
Closes: https://github.com/status-im/status-desktop/issues/12184
Community permissions toast notifications
> fix(descktop@community): show create/update/delete permissions toast notification for privileged members only when it is approved by the control node

- ui/app/AppLayouts/Profile/views/WalletView.qml
Object name for new button to add saved address from wallet settings
`ui/app/AppLayouts/Profile/views/WalletView.qml`
> chore: object name for adding saved address in settings

- ui/StatusQ/tests/TestCore/TestModels/tst_FastExpressionSorter.qml
Threshold for acceptable accesses has been increased but also additional check regarding roles has been introduced to ensure expected behavior.
Closes: #13181
StatusQ, Qt Models Library
> fix(StatusQ): FastExpressionSorter's test fixed for mac

- storybook/pages/CurrencyAmountInputPage.qml
- storybook/qmlTests/main.cpp
- storybook/qmlTests/tests/tst_CurrencyAmountInput.qml
- ui/StatusQ/CMakeLists.txt
- ui/StatusQ/include/StatusQ/formatteddoubleproperty.h
- ui/StatusQ/src/formatteddoubleproperty.cpp
- ui/StatusQ/src/plugin.cpp
- ui/app/AppLayouts/Profile/panels/SupportedTokenListsPanel.qml
- ui/app/AppLayouts/Profile/views/WalletView.qml
- ui/app/AppLayouts/Profile/views/wallet/ManageTokensView.qml
- ui/app/AppLayouts/Wallet/controls/FilterComboBox.qml
- ui/app/AppLayouts/Wallet/views/CollectiblesView.qml
- ui/imports/shared/controls/CurrencyAmountInput.qml
- ui/imports/shared/controls/qmldir
... under Settings/Wallet/Manage Tokens
- rename Tokens List tab to Advanced tab
- introduce a new `CurrencyAmountInput` component, backed by `FormattedDoubleProperty` C++ class (plus the respective SB page and a QML test case)
- use `FastExpressionFoo` for the collectibles views as well
Fixes #12611
Fixes #13040
NOTE: This needs integration with the backend (done separately)
SB for CurrencyAmountInput:
> feat: Add Advanced settings in new Advanced Tab

- src/app/modules/main/wallet_section/all_tokens/market_details_item.nim
fixes #13152
The response for market data may come before we have the token list
> fix(@wallet): wrong decimal place for market value in assets list

- src/app/modules/main/chat_section/chat_content/users/controller.nim
- src/app_service/service/community/service.nim
This fixes members list of the channels. The conficting signal, `SIGNAL_COMMUNITY_MEMBERS_CHANGED`, was causing it to always show all members.
As a consequence, it enables mentioning only members of a given channel.
closes: #12384
https://github.com/status-im/status-desktop/assets/33099791/c543e938-a373-4ce6-8ec5-5cf0541de7f3
> fix(communities): make users module always use channels members

- src/app/modules/main/wallet_section/saved_addresses/controller.nim
- src/app/modules/main/wallet_section/saved_addresses/io_interface.nim
- src/app/modules/main/wallet_section/saved_addresses/item.nim
- src/app/modules/main/wallet_section/saved_addresses/model.nim
- src/app/modules/main/wallet_section/saved_addresses/module.nim
- src/app/modules/main/wallet_section/saved_addresses/view.nim
- src/app_service/service/saved_address/async_tasks.nim
- src/app_service/service/saved_address/dto.nim
- src/app_service/service/saved_address/service.nim
- src/backend/backend.nim
- test/ui-test/src/drivers/elements/base_element.py
- test/ui-test/src/screens/components/saved_address_popup.py
- test/ui-test/testSuites/suite_wallet/tst_wallet_savedAddresses/test.feature
- ui/app/AppLayouts/Wallet/controls/SavedAddressesDelegate.qml
- ui/app/AppLayouts/Wallet/popups/AddEditSavedAddressPopup.qml
- ui/app/AppLayouts/Wallet/popups/RemoveSavedAddressPopup.qml
- ui/app/AppLayouts/Wallet/stores/RootStore.qml
- ui/app/AppLayouts/Wallet/views/SavedAddresses.qml
- ui/app/mainui/AppMain.qml
- https://github.com/status-im/status-go/pull/4537
What's changed:
- favourite property removed
- changes needed because of new constraints are applied (name is unique based on the testnet mode, search for name or for an item by address is done based on the testnet mode)
- fetching all addresses moved to async task
- checking for the latest ens name associated with the saved address is done on each fetching saved addresses, when adding or updating saved address
- validation of the entered ens name is done on the UI side and not only if the form is good, but resolving the address for it, if the address can not be resolved that results in an error
Closes: #13140
> Saved addresses improvements - favourite removed, primary key changed to (address, is_test)

- ui/imports/shared/stores/NetworkConnectionStore.qml
- ui/imports/shared/views/AssetsView.qml
fixes #13136
This PR is trying to achieving better performance when switching tabs in AssetsView. 
This lag is seen specifically on windows OS.
This change improves the peformance but we still a seconds delay which will be discussed further in the Token Management offsite.
AssetsView
Behvaior after changes as seen on Anthonys machine
https://github.com/status-im/status-desktop/assets/60327365/1421a729-eb4e-4b84-9d9e-5f176993c5c4
> fix(@deaktop/wallet): Slowness when switching accounts

- storybook/qmlTests/tests/tst_ManageCollectiblesPanel.qml
- ui/StatusQ/src/wallet/managetokenscontroller.cpp
- ui/StatusQ/src/wallet/managetokenscontroller.h
- ui/StatusQ/src/wallet/managetokensmodel.cpp
- ui/app/AppLayouts/Wallet/controls/ManageTokensDelegate.qml
- ui/app/AppLayouts/Wallet/controls/ManageTokensGroupDelegate.qml
- ui/app/AppLayouts/Wallet/panels/ManageAssetsPanel.qml
- ui/app/AppLayouts/Wallet/panels/ManageCollectiblesPanel.qml
- emit the signal from the backend
- trigger the toast notification in QML
- update the test(s)
Fixes #12704
Emit a toast notification when an asset/collectible is hidden in the Manage tokens settings
> feat: Emit notifications when an asset/collectible is hidden in the settings

- src/app/modules/main/profile_section/wallet/accounts/module.nim
- src/app/modules/main/wallet_section/module.nim
- src/app/modules/main/wallet_section/send/module.nim
- src/app/modules/shared_models/collectibles_entry.nim
- src/app/modules/shared_models/collectibles_model.nim
- src/app/modules/shared_modules/collectible_details/controller.nim
- src/app/modules/shared_modules/collectibles/controller.nim
Fixes #13169
The "Autofetch" setting for the Collectibles controller was replaced by the `loadType` setting.
`AutoLoadSingleUpdate`: Fetches all pages until the full list is retrieved, and performs a single model update with it.
`AutoLoadPaginated`: Fetches all pages until the full list is retrieved. The model is updated and the items are appended when each page arrives.
`OnDemand`: Fetches a new page only when `loadMoreItems` is called.
> feat(@desktop/wallet): Implement loadTypes in collectibles controller

- src/app/modules/shared_models/keypair_account_item.nim
- src/app/modules/shared_modules/keycard_popup/module.nim
- ui/imports/shared/popups/keycard/helpers/KeyPairUnknownItem.qml
- ui/imports/shared/popups/keycard/states/ManageAccounts.qml
The same issue was present in two places:
- check what's on a Keycard
- importing an account from a Keycard to the Status app
Fixes #11841
> fix(keycard): fetching balances for unknown accounts (those read from keycard) is fixed

- src/backend/collectibles.nim
Closes #13215
status-go part: https://github.com/status-im/status-go/pull/4584
Implement new Filter option to get only specific collectibles in the results
> feat(@desktop/wallet): add collectibles filter option collectibleIDs

- ui/app/AppLayouts/Communities/views/ChannelsSelectionModel.qml
- ui/app/AppLayouts/Communities/views/EditPermissionView.qml
- ui/app/AppLayouts/Communities/views/PermissionsView.qml
Motivation:
ChannelsSelectionModel.qml is freezing the app when used with a live channel that's being edited because on each channel change the selection model is re-created.
The fix for this is to use the LeftJoinModel to unify the channels selection (a light model containing only keys) and the full channels model containing the channels data. On top of this, the SortFilterProxyModel is added to decorate the model with the roles expected in the UI. Another improvement is by replacing the ExpressionRole with the FastExpressionRole.
PermissionsView
EditPermissionsView
https://github.com/status-im/status-desktop/assets/47811206/3e4bd8df-c23f-47a1-812f-e036d712579b
https://github.com/status-im/status-desktop/assets/47811206/fdf62f3e-6794-43c6-9135-fa590a7d8d33
> performance(ChannelsSelectionModel): Use LeftJoinModel for ChannelsSelectionModel.qml

- src/app/modules/shared_modules/keycard_popup/internal/state_factory_state_implementation.nim
- src/app/modules/startup/internal/state_factory_login_implementation.nim
- src/app/modules/startup/internal/state_factory_onboarding_implementation.nim
- ui/imports/shared/popups/keycard/KeycardPopupContent.qml
The issue re-running keycard flows on Windows is fixed in this commit, cause a different signal was emitted on Windows in case of missing Keycard.
> fix(keycard): unable to re-run keycard flow on windows

- storybook/pages/MovableModelPage.qml
- ui/StatusQ/CMakeLists.txt
- ui/StatusQ/include/StatusQ/movablemodel.h
- ui/StatusQ/src/movablemodel.cpp
- ui/StatusQ/src/plugin.cpp
- ui/StatusQ/tests/CMakeLists.txt
- ui/StatusQ/tests/src/TestHelpers/listmodelwrapper.cpp
- ui/StatusQ/tests/src/TestHelpers/listmodelwrapper.h
- ui/StatusQ/tests/src/TestHelpers/modelsignalsspy.cpp
- ui/StatusQ/tests/src/TestHelpers/modelsignalsspy.h
- ui/StatusQ/tests/src/TestHelpers/modeltestutils.cpp
- ui/StatusQ/tests/src/TestHelpers/modeltestutils.h
- ui/StatusQ/tests/src/TestHelpers/snapshotmodel.cpp
- ui/StatusQ/tests/src/TestHelpers/snapshotmodel.h
- ui/StatusQ/tests/src/TestHelpers/testmodel.h
- ui/StatusQ/tests/tst_MovableModel.cpp
- `MovableModel`
Proxy decorating source mode with additional method move(from, to, count) similar to that available in ListModel. The custom order is stored within a proxy, not altering the original model. May be useful whenever UI needs to allow user to set custom order. Temporary state can be held in the proxy, and send to the backend when changes are accepted.
- `SnapshotModel`
Testing utility allowing to grab state of the model and use for comparison later.
- `ModelSignalsSpy`
Testing utility aggregating `SignalsSpy`'s listening to `QAbstractItemModel`'s signals.
Closes: #12686
`StatusQ`, `Qt Proxy Models Library`
> feat(StatusQ): MovableModel for setting custom order over source model

- storybook/pages/DoubleFlickablePage.qml
- storybook/pages/DoubleFlickableWithFoldingPage.qml
- ui/StatusQ/src/StatusQ/Core/Utils/DoubleFlickable.qml
- ui/StatusQ/src/StatusQ/Core/Utils/DoubleFlickableWithFolding.qml
- ui/StatusQ/src/StatusQ/Core/Utils/qmldir
- ui/StatusQ/src/statusq.qrc
It adds two components:
- `DoubleFlickable` - Utility making two `Flickable`s operating as a single one. They are not "unrolled" and only needed delegates from both underlying `ListView`s/`GridView`s are instantiated.
- `DoubleFlickableWithFolding` - Built on top of `DoubleFlickable`, provides custom behavior of sticky headers and folding.
Closes: #13193
`StatusQ`
[Kazam_screencast_00082.webm](https://github.com/status-im/status-desktop/assets/20650004/b21f9eac-48ba-4add-9e81-2da71e535ccb)
[Kazam_screencast_00083.webm](https://github.com/status-im/status-desktop/assets/20650004/777258fd-0754-44b1-b38e-d67d91a4773c)
> feat(StatusQ): 2-sections `Flickable` component

- src/app/modules/main/profile_section/profile/models/profile_preferences_asset_item.nim
- src/app/modules/main/profile_section/profile/models/profile_preferences_assets_model.nim
- storybook/pages/ProfileShowcaseAssetsPanelPage.qml
- ui/app/AppLayouts/Profile/ProfileLayout.qml
- ui/app/AppLayouts/Profile/controls/AssetShowcaseDelegate.qml
- ui/app/AppLayouts/Profile/panels/ProfileShowcaseAssetsPanel.qml
- ui/app/AppLayouts/Profile/panels/ProfileShowcasePanel.qml
- ui/app/AppLayouts/Profile/stores/WalletStore.qml
- ui/app/AppLayouts/Profile/views/MyProfileView.qml
- ui/app/AppLayouts/Profile/views/profile/MyProfileSettingsView.qml
- ui/app/mainui/AppMain.qml
Uses the New assets model in the Profile showcase view.
There are issues with saving the data currently but thats an already exisiting issue
Profile Showcase view
https://github.com/status-im/status-desktop/assets/60327365/4ea0604d-739a-4b14-afa6-7caa6c896a3e
> Update new assets in profile

- src/app/modules/main/wallet_section/module.nim
- src/app/modules/shared_modules/add_account/controller.nim
- src/app/modules/shared_modules/add_account/io_interface.nim
- src/app/modules/shared_modules/add_account/module.nim
- src/app/modules/shared_modules/add_account/view.nim
- src/app_service/service/saved_address/service.nim
- ui/app/AppLayouts/Wallet/popups/AddEditSavedAddressPopup.qml
- ui/imports/shared/popups/addaccount/AddAccountPopup.qml
This commit prevents the user from adding an address to the saved addresses list, if it was already added to the Wallet section. Also when the user is about to add an address to the Wallet section, which is already added to the saved addresses list, the app will ask whether to proceed with that action by removing the related saved address or cancel the action.
Closes: #13109
https://github.com/status-im/status-desktop/assets/86303051/d39d83ae-7775-4896-9c5c-ccef7b3247d4
> fix(savedaddresses): preferred chains maintained in two places

- storybook/pages/CollectiblesViewPage.qml
- storybook/pages/DoubleFlickableWithFoldingPage.qml
- storybook/src/Models/ManageCollectiblesModel.qml
- ui/StatusQ/src/StatusQ/Core/Utils/DoubleFlickableWithFolding.qml
- ui/app/AppLayouts/Wallet/views/CollectiblesView.qml
- Wallet's main view, collectibles section is adjusted to the recent design
`DoubleFlickableWithFolding` provides foldable sections and controls
underlying grid views for both categories preventing from instantiating
too many delegates.
- `CollectiblesView`'s Storybook page fixed
- `DoubleFlickableWithFolding` - some minor fixes regarding bindings, flags for foldings
- `ManageCollectiblesModel` updated
`CollectiblesView`
[Kazam_screencast_00084.webm](https://github.com/status-im/status-desktop/assets/20650004/7aedd4e1-aad9-47ea-97b0-a4916069b38a)
> feat(Wallet): Collectibles view adjusted to design using `DoubleFlickableWithFolding`

- ui/app/AppLayouts/Profile/views/SettingsContentBase.qml
- ui/app/AppLayouts/Profile/views/WalletView.qml
- ui/app/AppLayouts/Profile/views/wallet/ManageTokensView.qml
- ui/app/AppLayouts/Wallet/WalletLayout.qml
- ui/app/AppLayouts/Wallet/views/CollectiblesView.qml
- ui/app/mainui/AppMain.qml
- ui/imports/shared/views/AssetsView.qml
- ui/imports/utils/Constants.qml
Fixes applying the Custom order settings in the main wallet view
Updates the Constants with the correct subsections and fix navigating into section/subsection
Fixes https://github.com/status-im/status-desktop/issues/13275
> fix: apply Custom order to main wallet view 

- ui/StatusQ/src/wallet/managetokenscontroller.cpp
- ui/StatusQ/src/wallet/managetokensmodel.cpp
- ui/StatusQ/src/wallet/managetokensmodel.h
- ui/app/AppLayouts/Wallet/controls/FilterComboBox.qml
- ui/app/AppLayouts/Wallet/controls/ManageTokenMenuButton.qml
- ui/app/AppLayouts/Wallet/controls/ManageTokensDelegate.qml
teach the model about the special cased self-collections containing just one single collectible item; we need that for the "Arrange by collection" token mgmt feature but in all other cases it shouldn't be treated as a collection/group
Fixes #13281
CollectiblesView
> fix: fake collections shouldn't be visible in a filtering combo

- src/app/modules/main/profile_section/module.nim
- src/app/modules/main/profile_section/profile/controller.nim
- src/app/modules/main/profile_section/profile/io_interface.nim
- src/app/modules/main/profile_section/profile/models/profile_preferences_asset_item.nim
- src/app/modules/main/profile_section/profile/models/profile_preferences_assets_model.nim
- src/app/modules/main/profile_section/profile/models/profile_preferences_collectible_item.nim
- src/app/modules/main/profile_section/profile/models/profile_preferences_collectibles_model.nim
- src/app/modules/main/profile_section/profile/module.nim
- src/app/modules/main/profile_section/profile/view.nim
- src/app/modules/shared_models/collectibles_model.nim
- src/app/modules/shared_modules/collectibles/controller.nim
- src/app_service/service/profile/dto/profile_showcase.nim
- src/app_service/service/profile/dto/profile_showcase_preferences.nim
- src/app_service/service/wallet_account/service_account.nim
- src/app_service/service/wallet_account/service_token.nim
- src/app_service/service/wallet_account/utils.nim
- ui/app/AppLayouts/Profile/panels/ProfileShowcaseAssetsPanel.qml
- ui/app/AppLayouts/Profile/panels/ProfileShowcaseCollectiblesPanel.qml
- ui/app/AppLayouts/Profile/stores/ProfileStore.qml
- ui/app/AppLayouts/Profile/views/profile/MyProfileSettingsView.qml
Close #13073
Waits https://github.com/status-im/status-go/pull/4511
https://github.com/status-im/status-desktop/assets/2522130/018fab85-bebf-4c62-b416-56bce02f0063
> feat(ProfileShowcase): Implement profile showcase collectibles

- src/app/global/utils.nim
- src/app/global/utils/time_utils.nim
- src/app/modules/main/chat_section/chat_content/messages/module.nim
- src/app/modules/main/chat_section/model.nim
- test/nim/utils_test.nim
- ui/app/AppLayouts/Chat/views/ChatHeaderContentView.qml
- ui/imports/shared/views/ProfileDialogView.qml
- ui/imports/utils/Utils.qml
This PR fixes [9947](https://github.com/status-im/status-desktop/issues/9947) and contains : 
- Commit to fix the changing of custom picture and having the change reflected on contact's side
- Commit to fix the deleting of picture and having the change reflected on contact's side
-------
Previously, the inconsistency in reflecting profile picture changes occurred due to a bug tied to the design choice for generating and serving images through URLs. Upon uploading an image, status-go generates an image and saves a URL link. The observed issue was that even after changing the profile image, the URL remained the same. Although the backend correctly associated the URL with the newly uploaded image, Qt/QML failed to update the value accordingly.
- **[Preferred - Implemented]** Using the same …
> (fix/desktop) removing custom picture is not reflected on contact's side

- src/app/modules/shared_modules/keycard_popup/internal/state_factory_state_implementation.nim
- src/app/modules/shared_modules/keycard_popup/internal/wrong_keycard_state.nim
- ui/app/AppLayouts/Profile/views/keycard/DetailsView.qml
Among this, two other things are fixed:
- a keycard details screen's title should follow the keypair's name, not the keycard's names
- copy keycard flow is blocked if the keycard user is copying to is locked and doesn't belong to any of the app's known keypairs
Fixes: #13289
> fix(keycard): unable to pass pin entry screen in certain flows

- src/app/modules/shared_modules/keycard_popup/controller.nim
A crash was happening cause the wallet account service was not available before the user logged in.
Fixes: #13286
> fix(keycard): app crashes when trying to generate new keys with an already used keycard

- src/app_service/service/contacts/service.nim
- src/app_service/service/message/service.nim
Close #11854
Remove the early activation of the chat which caused the animation to freeze. Previously this fix was needed because the chat was activated at the moment of sending a contact request, and now it is activated at the moment of receiving. 
Chat
https://github.com/status-im/status-desktop/assets/2522130/46e257eb-a378-4d46-9ac5-f7f752b36432
> fix(Chat): Remove early chat fetching when sending a CR

- ui/app/mainui/activitycenter/popups/ActivityCenterPopup.qml
- ui/app/mainui/activitycenter/stores/ActivityCenterStore.qml
- ui/app/mainui/activitycenter/views/ActivityNotificationCommunityTokenReceived.qml
Fixes #12515
- Added UI support for first community token received (asset or collectible).
- Added UI support for any community token received (asset or collectible).
- TODO: Storybook support --> https://github.com/status-im/status-desktop/issues/13362
**NOTE**: Only UI -- Backend missing
Notification Center
Hardcoded notifications in app to test them:
https://github.com/status-im/status-desktop/assets/97019400/e3179974-e682-469a-bf62-0a335d238cae
> feat(AC-CommunityTokenReceived): Added UI for community tokens received

- storybook/pages/SendModalPage.qml
- storybook/pages/TokenListViewPage.qml
- storybook/src/Models/TokensBySymbolModel.qml
- storybook/stubs/shared/stores/CurrenciesStore.qml
- storybook/stubs/shared/stores/send/TransactionStore.qml
- ui/StatusQ/src/StatusQ/Controls/StatusComboBox.qml
- ui/app/AppLayouts/Wallet/stores/TokensStore.qml
- ui/app/AppLayouts/Wallet/views/AssetsDetailView.qml
- ui/app/mainui/AppMain.qml
- ui/imports/shared/controls/AssetsSectionDelegate.qml
- ui/imports/shared/controls/qmldir
- ui/imports/shared/popups/CommunityAssetsInfoPopup.qml
- ui/imports/shared/popups/qmldir
- ui/imports/shared/popups/send/SendModal.qml
- ui/imports/shared/popups/send/controls/TokenBalancePerChainDelegate.qml
- ui/imports/shared/popups/send/panels/HoldingItemSelector.qml
- ui/imports/shared/popups/send/panels/HoldingSelector.qml
- ui/imports/shared/popups/send/views/TokenListView.qml
- ui/imports/shared/stores/send/TransactionStore.qml
- ui/imports/shared/views/AssetsView.qml
fixes #12378
Implements the community assets section in the SendModal ->  https://www.figma.com/file/eM26pyHZUeAwMLviaS1KJn/%E2%9A%99%EF%B8%8F-Wallet-Settings%3A-Manage-Tokens?type=design&node-id=1-16520&mode=design&t=hfXbuGCnv4mpaHcF-4
Please note bacjend integration with advanced settings will happen under https://github.com/status-im/status-desktop/issues/13178
SendModal, AssetsView
https://github.com/status-im/status-desktop/assets/60327365/c0f93959-6d9d-4fc7-9a34-1fb5acdbe3d2
> fix(@desktop/wallet):  Prepare send modal to display community assets

- ui/StatusQ/src/StatusQ/Components/StatusMessageHeader.qml
Fixes https://github.com/status-im/status-desktop/issues/13279
The bug appeared with this fix: https://github.com/status-im/status-desktop/pull/12957
I kept the fix working and fixed the part not to expand the header if not needed.
-----
And activity center is still ok:
> fix: invalid message header size

- src/app/modules/main/communities/controller.nim
- src/app/modules/main/communities/io_interface.nim
- src/app/modules/main/communities/module.nim
- src/app/modules/main/communities/tokens/controller.nim
- src/app_service/service/community/service.nim
- src/app_service/service/community_tokens/service.nim
Fix #12547
Keep community tokens in cache.
Community tokens are loaded from database only once at the beginning.
The cache should be updated anytime we update database:
- deploy new contracts,
- remove contracts from database,
- update supply (burn),
- update deploy state,
- update owner and master contracts addresses (deployment)
> fix(@desktop/communities): Keep community tokens in cache.

- ui/app/AppLayouts/Wallet/controls/ManageTokensGroupDelegate.qml
- set width for the text so that the elision works correctly
Fixes #13396
Cherry pick to: 2.27.0 Alpha RC
Token management
> fix: Incorrect margins when collection group name is long

- src/app_service/service/node_configuration/dto/node_config.nim
Fixes https://github.com/status-im/status-desktop/issues/13355
The clusterID was not being sent when a change related to the node config was executed.
This issue is related to https://github.com/status-im/status-desktop/issues/12918 and should be fixed once proper endpoints for status-go node configuration changes are created
> fix: missing clusterID in node config

- src/app/modules/main/profile_section/advanced/io_interface.nim
- src/app/modules/main/profile_section/advanced/module.nim
- src/app/modules/main/profile_section/advanced/view.nim
- src/app_service/service/accounts/service.nim
- src/app_service/service/node_configuration/service.nim
- ui/app/AppLayouts/Profile/stores/AdvancedStore.qml
- ui/app/AppLayouts/Profile/views/AdvancedView.qml
- ui/imports/shared/status/StatusSettingsLineButton.qml
Previously it was not possible to change the state of the Debug toggle in settings. This was because the code forced the setting the default value (DEBUG or INFO depending on the environment) at every login, ignoring the database setup, hence always setting the DEBUG or INFO as LogLevel.
Closes #13139
The PR removes forced initialization to avoid overwriting the updated config in the node_config table in database and recently set by the user. To achieve this, the PR uses a newly created entity called `runTimeLogLevel` that is `NOT` updated in Database, and that is used to set the logger in status-go. The PR still makes the Debug to be default in dev environments and disbales debug in prod environment
----------------
---------------
`./bin/nim_status_client`
The application displays the …
> fix(settings): It's not possible to switch the log level

- src/app/modules/main/profile_section/profile/models/profile_preferences_accounts_model.nim
- src/app/modules/main/profile_section/profile/models/profile_preferences_assets_model.nim
- src/app/modules/main/profile_section/profile/models/profile_preferences_collectibles_model.nim
- src/app/modules/main/profile_section/profile/models/profile_preferences_communities_model.nim
- ui/app/AppLayouts/Profile/panels/ProfileShowcasePanel.qml
- unify the signature of the method to `move(from, to, count)` so that both ListModel and NIM have it the same
- realize the move operation using the proper `begin/endMoveRows` instead of doing a full model reset
- simplify signaling `dataChanged()` for all model roles (nimqml now follows the C++ impl)
Fixes #13329
Fixes DND in profile showcase settings
Settings/Profile/showcase tabs
[Záznam obrazovky z 2024-02-06 09-19-17.webm](https://github.com/status-im/status-desktop/assets/5377645/0dc3b5b0-2eb1-418d-8a62-53fde7ca7777)
> fix(showcase): unbreak drag and drop reordering

- ui/app/AppLayouts/Wallet/panels/ManageHiddenPanel.qml
When removing the top-most item from the list, animation was ending with improper delegates' positioning. No workaround found, transition disabled.
Closes: #13392
`ManageHiddenPanel`
[Kazam_screencast_00088.webm](https://github.com/status-im/status-desktop/assets/20650004/dadce093-5a91-458f-9801-f8db00e2f838)
> fix(ManageHiddenPanel): Disable displace Transition to fix positioning on unhiding

- ci/Jenkinsfile.combined
The full suite is unstable and causes frequent timeouts currently.
> fix(ci): run only critical path of new e2e for releases

- src/app/modules/shared_models/collectibles_model.nim
- src/app/modules/shared_modules/collectibles/controller.nim
- storybook/pages/CollectiblesViewPage.qml
- ui/app/AppLayouts/Wallet/stores/CollectiblesStore.qml
- ui/app/AppLayouts/Wallet/views/CollectiblesView.qml
- ui/app/AppLayouts/Wallet/views/RightTabView.qml
Fixes #11802
Moves the "Loading Items" logic from the Collectibles model to the CollectiblesView, making use of the new ConcatModel util. 
Perhaps a smoother animation can be introduced in the future when a state change occurs.
https://github.com/status-im/status-desktop/assets/11161531/18ca5663-cccd-49dd-91f1-5beca8a59337
https://github.com/status-im/status-desktop/assets/11161531/655c2df1-6b59-484b-a167-d1143de1a549
> feat(wallet): simplify loading items mechanism for collectibles model

- ui/app/mainui/AppMain.qml
Displays a notification badge over the Settings cog when we have an incoming/pending Contact Request (CR)
Fixes #9779
AppMain
Incoming CR:
CR accepted:
> fix(AppMain): display a badge for Settings icon with incoming CR

- ui/StatusQ/src/StatusQ/Components/StatusMessageHeader.qml
[This PR](https://github.com/status-im/status-desktop/pull/13372/files) introduced a small bug.
Some user names ended up in text wrapping. Added a `+1px` hack to prevent this.
| Mark Cub | Mark Cuba | Mark Cuban |
|-|-|-|
| <img width="441" alt="Screenshot 2024-02-07 at 11 17 26" src="https://github.com/status-im/status-desktop/assets/25482501/cc9bb7d1-def3-42bf-b1f6-1dbb7b6baa11"> | <img width="441" alt="Screenshot 2024-02-07 at 11 17 38" src="https://github.com/status-im/status-desktop/assets/25482501/378186b1-d71f-4c73-ba68-98c9ab65892d"> | <img width="441" alt="Screenshot 2024-02-07 at 11 17 43" src="https://github.com/status-im/status-desktop/assets/25482501/cf5cd05b-f16f-4541-be13-f23843539a5e"> |
Fixed looks like this:
> fix: display name width calculation

- storybook/pages/StatusDialogFooterPage.qml
- storybook/pages/StatusModalFooterPage.qml
- ui/StatusQ/src/StatusQ/Popups/Dialog/StatusDialogFooter.qml
- ui/StatusQ/src/StatusQ/Popups/StatusStackModal.qml
- ui/StatusQ/src/StatusQ/Popups/statusModal/StatusModalFooter.qml
- ui/app/AppLayouts/Communities/popups/CommunityProfilePopup.qml
- ui/app/AppLayouts/Communities/popups/CreateChannelPopup.qml
- ui/app/AppLayouts/Communities/popups/FinaliseOwnershipPopup.qml
- ui/app/AppLayouts/Communities/popups/SharedAddressesPopup.qml
- ui/imports/shared/popups/addaccount/AddAccountPopup.qml
- ui/imports/shared/popups/keycard/KeycardPopupDetails.qml
- ui/imports/shared/popups/keypairimport/KeypairImportPopup.qml
When there is no room for footer buttons in their full width, they are shrank and elided instead of going outside the popup.
Closes: #11449
`StatusDialogFooter`, `StatusModalFooter`
[Kazam_screencast_00091.webm](https://github.com/status-im/status-desktop/assets/20650004/84e0df31-af9f-4daf-9770-2873eb7df10d)
> fix(StatusDialogFooter/StatusModalFooter): Prevent footer's buttons overflow

- storybook/pages/ProfileDialogViewPage.qml
- ui/StatusQ/src/StatusQ/Components/StatusMemberListItem.qml
- ui/StatusQ/src/StatusQ/Components/StatusMessageHeader.qml
- ui/StatusQ/src/StatusQ/Components/StatusSmartIdenticon.qml
- ui/imports/shared/controls/chat/ProfileHeader.qml
- ui/imports/shared/controls/chat/UserImage.qml
- ui/imports/shared/popups/SendContactRequestModal.qml
- ui/imports/shared/views/ProfileDialogView.qml
- ui/imports/shared/views/chat/ProfileContextMenu.qml
- ui/imports/shared/views/chat/SimplifiedMessageView.qml
- ui/imports/shared/views/profile/ShareProfileDialog.qml
- ui/imports/utils/Constants.qml
- adds the green/gray dot (aka online indicator) to Profile dialog and
context menu (via ProfileHeader and UserImage components)
- add the respective combobox to storybook too
- separate commit to fixup display of the elided compressed user key
Fixes https://github.com/status-im/status-desktop/issues/13480
Profile dialog and context menu
Profile dialog:
Context menu:
Storybook:
> fix(profile): add online status badge to profile picture

- storybook/pages/ProfileShowcaseAssetsPanelPage.qml
- ui/app/AppLayouts/Profile/panels/ProfileShowcaseAssetsPanel.qml
- ui/app/AppLayouts/Profile/panels/ProfileShowcasePanel.qml
- ui/app/AppLayouts/Profile/views/MyProfileView.qml
Closes #13337
- Added new button to navigate to accounts tab form assets tab.
- Added needed support in storybook to cover the new use case.
**NOTE:** Backend needed. It will provide `.hiddenCount` property for the profile showcase models. 
Profile Showcase Assets and Accounts tabs
https://github.com/status-im/status-desktop/assets/97019400/68615920-13de-4504-92b3-408cd2fa8fef
> feat(ProfileShowcase): Assets panel navigation button

- src/app/modules/main/profile_section/profile/models/profile_preferences_accounts_model.nim
- src/app/modules/main/profile_section/profile/models/profile_preferences_assets_model.nim
- src/app/modules/main/profile_section/profile/models/profile_preferences_collectibles_model.nim
- src/app/modules/main/profile_section/profile/models/profile_preferences_communities_model.nim
For https://github.com/status-im/status-desktop/pull/13489
- Add one more dirty state property. 
Temporary changes. These models are going to be wiped in a few weeks
> feat(Profile): Add `hiddenCount` property for profile showcase models

- ui/StatusQ/src/StatusQ/Components/StatusTimeStampLabel.qml
- ui/StatusQ/src/StatusQ/Core/StatusSharedUpdateTimer.qml
- ui/StatusQ/src/StatusQ/Core/qmldir
- ui/StatusQ/src/statusq.qrc
Fixes wrong message timestamp in a channel when the relative date changes (due to time going over midnight, HW clock skews or timezone/DST changes)
- introduce one global update timer, to be used in various components for date/time sensitive updates
- this timer runs only when the app is/becomes active
- use the timer's `triggered()` signal to update the timestamp label when needed; ie. if it's to display a relative timestamp and it's currently visible
Fixes #11460
StatusTimeStampLabel
Before midnight:
After midnight:
> fix: timestamp shows yesterday for a message received 3 days ago

- src/app/core/signals/remote_signals/community.nim
- src/app/core/signals/remote_signals/signal_type.nim
- src/app/core/signals/signals_manager.nim
- src/app/modules/main/communities/view.nim
- src/app/modules/main/module.nim
- src/app_service/service/community/service.nim
- ui/app/AppLayouts/Communities/popups/DiscordImportProgressContents.qml
- ui/app/AppLayouts/Communities/stores/CommunitiesStore.qml
Fixes #12724
The actual issue wasn't reproducible, even if I removed the guards against duplicate names. But I did find that the community wasn't cleaned up correctly, so I fixed it in this PR. It should limit the confusion and possible issues that could arise.
You can see the fixed behaviour in the video below.
Do note, I removed the duplicate name guards in status-go to create the video. Normally, the import would have worked.
[import.webm](https://github.com/status-im/status-desktop/assets/11926403/11510d74-bb58-437f-a226-de878e1ebbf2)
status-go PR https://github.com/status-im/status-go/pull/4693
> fix(discord_import): fix community not cleaned up when it fails

- ui/app/AppLayouts/Profile/views/MyProfileView.qml
- ui/imports/shared/popups/SettingsDirtyToastMessage.qml
Closes #13334
- Replaced current `StatusButton` type to `DisabledTootipButton` to allow the tooltip being displayed when button is disabled, in dirty toast message.
- Added needed conditions in `MyProfileView` where the tooltip, in save changes button, is shown in disable condition.
Settings / Save changes toast button
https://github.com/status-im/status-desktop/assets/97019400/96b6da44-163f-4217-8f32-463d56ae808d
> feat(ProfileShowcase): Save changes tooltip when disabled

- ci/Jenkinsfile.combined
fix leftover to allow tests running in nightly. Nightly job https://ci.status.im/job/status-desktop/job/nightly/186/ failed with
```
WorkflowScript: 58: Unknown stage section "stage". Starting with version 0.5, steps in a stage must be in a ‘steps’ block. @ line 58, column 5.
stage('Tests') {
^
WorkflowScript: 58: Expected one of "steps", "stages", or "parallel" for stage "Tests" @ line 58, column 5.
stage('Tests') {
^
```
`ci/Jenkinsfile.combined`
> ci: fix leftover to allow tests running in nightly

- ui/imports/shared/panels/EditCroppedImagePanel.qml
add object name for EditCroppedImage item
`ui/imports/shared/panels/EditCroppedImagePanel.qml`
> chore: add object name for EditCroppedImage item

- storybook/pages/ProfileDialogViewPage.qml
- ui/imports/shared/views/profile/ShareProfileDialog.qml
add a regular image context menu with:
- "Copy image" -> copy the image to clipboard
- "Download image" -> downloads the image in the user specified folder
Fixes #13479
ShareProfileDialog
> fix(profile/qr) add Copy/Download menu for QR code

- ui/imports/shared/popups/SettingsDirtyToastMessage.qml
It fixes issue with save changes button introduced in commit edf7e82.
Settings / Save changes bubble button
https://github.com/status-im/status-desktop/assets/97019400/7f26bf54-c96d-41e5-bb30-3190c8300825
> fix(SettingsDirtyToastMessage): Save changes always disabled

- storybook/pages/ProfileShowcaseAssetsPanelPage.qml
- storybook/pages/ProfileShowcaseCollectiblesPanelPage.qml
- ui/app/AppLayouts/Profile/controls/AddMoreAccountsLink.qml
- ui/app/AppLayouts/Profile/controls/qmldir
- ui/app/AppLayouts/Profile/panels/ProfileShowcaseAssetsPanel.qml
- ui/app/AppLayouts/Profile/panels/ProfileShowcaseCollectiblesPanel.qml
- ui/app/AppLayouts/Profile/views/MyProfileView.qml
Closes #13340
- Added new button to navigate to accounts tab form collectibles tab.
- Added needed support in `storybook` to cover the new use case.
Settings / Profile Showcase / Collectibles tab
- Storybook:
https://github.com/status-im/status-desktop/assets/97019400/cbc35e21-6707-4105-90c8-30bb2d7b31cb
- App:
https://github.com/status-im/status-desktop/assets/97019400/84eb81c3-5166-4892-ad4e-c48864a7981e
> feat(ProfileShowcase): Collectibles panel navigation button

- storybook/pages/ProfileDialogViewPage.qml
- ui/app/AppLayouts/Profile/stores/ProfileStore.qml
- ui/imports/shared/views/ProfileDialogView.qml
- ui/imports/shared/views/profile/ShareProfileDialog.qml
- fix the QR code to generate a URL with the link to the profile instead of just the user key
- reuse the `UserImage` component and place it on top of the existing QR code
- put a white rectangle behind the QR code image and white ring around
the user image
Fixes #13482
Adds a user image on top of the QR code
ShareProfileDialog
QR code displayed in the app:
QR code scanned on phone:
> feat(profile): Place user image/identicon onto the QR code

- src/app/modules/main/wallet_section/activity/controller.nim
- src/app/modules/main/wallet_section/activity/model.nim
- src/app/modules/main/wallet_section/module.nim
- src/app/modules/main/wallet_section/saved_addresses/controller.nim
- src/app/modules/main/wallet_section/saved_addresses/module.nim
- src/app_service/service/saved_address/service.nim
- ui/app/AppLayouts/Wallet/views/RightTabView.qml
- ui/app/AppLayouts/Wallet/views/TransactionDetailView.qml
- ui/imports/shared/controls/TransactionAddress.qml
- ui/imports/shared/views/HistoryView.qml
This commit handles saved addresses changes and reflects them to the history view and tx details view. In this context it handles the same way changes coming from sync devices.
It also fixes the issue when switching network mode.
Closes: #13095
https://github.com/status-im/status-desktop/assets/86303051/0410fa20-293a-4cd5-ae24-8a43450924b1
> feat(savedaddresses): add save receiver address to the context menu in tx details view

- src/app_service/service/transaction/service.nim
- src/backend/response_type.nim
Maintenance bumps of several dependencies - broadly address security issues, 1.6+ compatibility, bugfixes etc to catch up with Nimbus' development
The extra try/catch is due to increased exception safety requirements in `chronicles`, where `fmt` allows dynamic format strings and therefore may raise `ValueError` in theory.
> maintenance bumps

- ui/StatusQ/src/concatmodel.cpp
Closes #13585 
Check vector boundaries.
The app is crashing when mapFromSourceRoles is called with 0 m_rolesMappingFromSource length.
ConcatModel
> fix: App crash while switching wallet accounts

- src/app_service/service/community/service.nim
Closes #13369 
This behaviour is encountered only when updating the permissions in the channel edit popup because the community description is updated in 2 steps: 1 - Update the channel; 2 - update the permissions.
Flow:
1. Call channel update rpc
2. Call permission update rpc
3. Update the local permissions -> Emit permission created event
4. Receive the community description from step 1 (with older permissions) -> Emit permission deleted event + update the local permissions;
5. Receive the community description from step 2 (new permissions) -> Emit permission created event + update the local permission again
In this case the permissions updates are processed twice. Once when the permission update is called to the backend and the second time when the event for the new community …
> fix: Multiple permission update toasts are spawned

- ui/imports/utils/Constants.qml
Closing: #13335
Changes:
1. Update error messages in the display name validators
Profile settings
Display name validators
https://github.com/status-im/status-desktop/assets/47811206/0b926458-d884-40a5-b1e9-33bbf5a67b45
> 13335 profile showcase identity update display name error messages

- src/app/modules/shared_models/collectibles_model.nim
- src/app/modules/shared_models/collectibles_nested_model.nim
- src/app/modules/shared_modules/collectibles/controller.nim
- test/nim/collectibles_model_test.nim
Fixes #13254
Whenever a change in the list of owned collectibles is reported by status-go, we now update the model with the delta (added/removed items) instead of doing a full reset, which should help avoid doing unnecessary work in the SFPM.
This is a straightforward approach, and there's room for improvement still:
- Don't re-request the full list from status-go, only request new items and remove what's needed.
- - I considered this originally, but the complexity became quite high (similar to what Stefan's doing for the Session-Based Activity API). It was taking too long and I feared inconsistencies between the two lists, so I abandoned this idea for now.
- Separate models with collectibles metadata (most of what we currently have) and ownership (accounts + uids), which can be combined …
> feat(@wallet): update collectibles model only with changes

- src/app_service/service/transaction/dto.nim
- src/app_service/service/transaction/service.nim
Fixes a regression introduced in https://github.com/status-im/status-desktop/pull/13426/files#diff-bcb992e307c40bf1f94c84d7fed5ef8dacc1b572e84df79de01b118a72cb12f9R467
> fix(@desktop/Wallet): Fix ERC721 sending

- storybook/pages/TokenListViewPage.qml
- ui/imports/shared/popups/send/SendModal.qml
- ui/imports/shared/popups/send/views/FeesView.qml
- ui/imports/shared/popups/send/views/NetworkSelector.qml
- ui/imports/shared/popups/send/views/NetworksSimpleRoutingView.qml
- ui/imports/shared/popups/send/views/SendModalFooter.qml
- ui/imports/shared/popups/send/views/TabAddressSelectorView.qml
- ui/imports/shared/popups/send/views/TokenListView.qml
#13377 
Applies the new sizing rules for SendModal as per design https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=21233-57676&mode=design&t=2O68lxNGG9g1b1tx-4
Please note even though the code looks like its been touched a lot, its only been rearranged or the container has been changed
SendModal
https://github.com/status-im/status-desktop/assets/60327365/a180ee29-5cfe-4c5d-859f-a3d8e9572a51
> Send dialog: sizing and layout rules to limit dialog height jumping between states

- storybook/pages/StatusButtonPage.qml
- ui/StatusQ/src/StatusQ/Controls/StatusBaseButton.qml
- ui/StatusQ/src/StatusQ/Controls/StatusButton.qml
- ui/StatusQ/src/StatusQ/Controls/StatusFlatButton.qml
- ui/app/AppLayouts/Communities/panels/MembersTabPanel.qml
- implemented the missing `StatusBaseButton.Type.Success` state and colors for both `StatusButton` and `StatusFlatButton`
- use a `switch` instead of a waterfall of ternaries
- adjust storybook for the new case
Fixes #13622
Status[Base,Flat]Button
[Záznam obrazovky z 2024-02-19 14-36-28.webm](https://github.com/status-im/status-desktop/assets/5377645/684fabee-c79a-4604-bae9-e1e5fe155175)
> feat[StatusButton] missing green/success state

- storybook/pages/ProfileDialogViewPage.qml
- ui/app/mainui/Popups.qml
- ui/imports/shared/popups/RemoveContactPopup.qml
- ui/imports/shared/popups/qmldir
- ui/imports/shared/views/ProfileDialogView.qml
- ui/imports/shared/views/chat/ProfileContextMenu.qml
- ui/imports/utils/Global.qml
- implement the new remove contact confirmation popup
Fixes #13521
RemoveContactPopup
Coming from ProfileDialog:
Chat context menu:
> feat(Profile flow): Remove a contact

- storybook/pages/MovableModelPage.qml
- storybook/pages/MovableModelWithSfpmPage.qml
- storybook/pages/ProfileShowcaseDirtyStatePage.qml
- storybook/pages/ProfileShowcaseModelsPage.qml
- storybook/src/Storybook/GenericListView.qml
- storybook/src/Storybook/qmldir
- ui/StatusQ/CMakeLists.txt
- ui/StatusQ/include/StatusQ/movablemodel.h
- ui/StatusQ/include/StatusQ/undefinedfilter.h
- ui/StatusQ/src/StatusQ/Core/Utils/QObject.qml
- ui/StatusQ/src/StatusQ/Core/Utils/qmldir
- ui/StatusQ/src/movablemodel.cpp
- ui/StatusQ/src/plugin.cpp
- ui/StatusQ/src/undefinedfilter.cpp
- ui/StatusQ/tests/tst_MovableModel.cpp
- ui/app/AppLayouts/Profile/helpers/ProfileShowcaseDirtyState.qml
- ui/app/AppLayouts/Profile/helpers/ProfileShowcaseModels.qml
- ui/app/AppLayouts/Profile/helpers/VisibilityAndPositionDirtyStateModel.qml
- ui/app/AppLayouts/Profile/helpers/qmldir
This PR provides basic building blocks necessary to build ui-side dirty state management for Profile Showcase functionality (settings part):
- reusable `ProfileShowcaseDirtyState` for managing `visibility` and `position` in showcase tabs
- `ProfileShowcaseModel` providing all showcase-related models needed by the UI, managing dependencies between them internally (like accounts selection affecting collectibles). Those models are intended to be consumed by the UI according to specification described in #13498
- simple referencial UI showing the dirty state management in action, integrated in the same way as it will be done with the real UI accordign to #13498 The UI is integrated with models using workaround (calling `movableModel.syncOrder()` to avoid crash caused by …
> feat(ProfileShowcase): Dirty state management for communities/accounts/collectibles

- ui/app/AppLayouts/Communities/popups/SharedAddressesPopup.qml
Fixes #13618
[shared-airdrop.webm](https://github.com/status-im/status-desktop/assets/11926403/8453ca00-d46a-4276-9d1f-1930b33bfac9)
> fix(SharedAddresses): fix airdrop address not being reflected in popup

- ui/StatusQ/src/StatusQ/Controls/StatusWarningBox.qml
- ui/app/mainui/Popups.qml
- ui/imports/shared/popups/BlockContactConfirmationDialog.qml
- ui/imports/shared/popups/MarkAsUntrustedPopup.qml
- ui/imports/shared/popups/UnblockContactConfirmationDialog.qml
- ui/imports/shared/views/ProfileDialogView.qml
- ui/imports/shared/views/chat/ProfileContextMenu.qml
- ui/imports/utils/Global.qml
- implement block and unblock user popups with optional "Remove contact" and "Remove ID verification" check boxes
- emit (combined) toasts
- separate commit to expose text size from `StatusWarningBox`
Fixes #13522
[Un]BlockConfirmationDialog
Block:
> feat(Profile flow): Block/unblock user

- src/app/modules/main/wallet_section/saved_addresses/item.nim
- src/app/modules/main/wallet_section/saved_addresses/model.nim
- src/app/modules/main/wallet_section/saved_addresses/module.nim
- src/app_service/service/saved_address/dto.nim
- ui/app/AppLayouts/Wallet/views/SavedAddresses.qml
- https://github.com/status-im/status-go/pull/4791
Fixes #13665
> fix(savedaddresses): saved addresses should be displayed in mixed cases format

- ui/app/AppLayouts/Profile/popups/backupseed/Acknowledgements.qml
Closes #8402
Backup Seed Phrase Popup: Fixed warning message size based on text size
Backup Seed Phrase Popup
https://github.com/status-im/status-desktop/assets/31625338/eaec85bd-ec00-43e3-ad6c-bc8bafea4daf
> [BackupSeedPopup]: Fixed warning message size based on text size

- src/app/core/signals/remote_signals/messages.nim
- src/app/modules/main/chat_section/chat_content/controller.nim
- src/app/modules/main/chat_section/chat_content/input_area/controller.nim
- src/app/modules/main/chat_section/chat_content/messages/controller.nim
- src/app/modules/main/chat_section/chat_content/messages/io_interface.nim
- src/app/modules/main/chat_section/chat_content/messages/module.nim
- src/app/modules/main/chat_section/controller.nim
- src/app/modules/main/chat_section/io_interface.nim
- src/app/modules/main/chat_section/module.nim
- src/app/modules/main/chat_section/view.nim
- src/app/modules/shared_models/message_model.nim
- src/app_service/service/activity_center/dto/notification.nim
- src/app_service/service/chat/dto/chat.nim
- src/app_service/service/chat/service.nim
- src/app_service/service/community/async_tasks.nim
- src/app_service/service/community/service.nim
- src/app_service/service/message/service.nim
- src/backend/chat.nim
- src/backend/communities.nim
- ui/app/AppLayouts/Chat/stores/RootStore.qml
- ui/app/AppLayouts/Communities/panels/MembersSettingsPanel.qml
- ui/app/AppLayouts/Communities/popups/KickBanPopup.qml
- ui/app/AppLayouts/Communities/views/CommunityColumnView.qml
- ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml
- ui/app/mainui/activitycenter/popups/ActivityCenterPopup.qml
- ui/app/mainui/activitycenter/stores/ActivityCenterStore.qml
- ui/app/mainui/activitycenter/views/ActivityNotificationCommunityBanUnban.qml
- extend the Ban/Unban popup with the "Delete all messages" option
- delete all messages during the ban functionality
- AC notification for ban/unban
- refactor names for functionality to split messages remove and delete  
- fixed bug when kicking user results to "Pending request" state
status-go PR: https://github.com/status-im/status-go/pull/4743
Closes:
- https://github.com/status-im/status-desktop/issues/13610
- https://github.com/status-im/status-desktop/issues/13608
- https://github.com/status-im/status-desktop/issues/12063
- Messages deletion
- AC notifications
https://github.com/status-im/status-desktop/assets/117639195/35256183-8001-4927-8077-f029c4e1ae35
> feat(@desktop/community): allow owner delete all messages during the ban and ban/unban AC notifications

- ui/StatusQ/include/StatusQ/movablemodel.h
- ui/StatusQ/src/movablemodel.cpp
- ui/StatusQ/tests/CMakeLists.txt
- ui/StatusQ/tests/src/TestHelpers/modelsignalsspy.h
- ui/StatusQ/tests/src/TestHelpers/modeltestutils.cpp
- ui/StatusQ/tests/src/TestHelpers/modeltestutils.h
- ui/StatusQ/tests/src/TestHelpers/persistentindexestester.cpp
- ui/StatusQ/tests/src/TestHelpers/persistentindexestester.h
- ui/StatusQ/tests/tst_MovableModel.cpp
`MovableModel` wasn't updating own persistent indexes when layoutChanged was emitted from the source and within `syncOrder` method. I could lead to data corruption in models relying on this model by taking persistent indexes.
- persistent indexes handling fixed
- utility for persistent indexes validation added
- some other improvements in `ModelTestUtils` - `isNotSame(...)` method added
- `MovableModel`'s code structure improved
Closes: #13602
> StatusQ(MovableModel): layoutChanged handling fixed 

- src/app_service/service/chat/async_tasks.nim
- src/app_service/service/chat/service.nim
Kind of fixes #13640
The issue itself was no reproducible even after dozens of restarts and following of the repro steps. It seems like this was an unfortunate DB close event that caused the app to close.
Adding a try catch won't actually fix that, since the DB is closed and also the `communtiies`already had a try/catch, but it will help for later.
> fix(async_tasks): add try catch to getChannelGroups async task

- .gitignore
- src/app/modules/main/chat_section/controller.nim
- src/app/modules/main/chat_section/module.nim
- src/app/modules/main/controller.nim
- src/app/modules/main/io_interface.nim
- src/app/modules/main/module.nim
Use correct chains when creating permissions: testnet or mainnet.
Status-go https://github.com/status-im/status-go/pull/4771
Fixes https://github.com/status-im/status-mobile/issues/18896
> 18896 use correct chains when creating permissions master

- ui/app/AppLayouts/Profile/panels/ProfileShowcaseAssetsPanel.qml
- ui/app/AppLayouts/Profile/panels/ProfileShowcaseCollectiblesPanel.qml
- ui/app/AppLayouts/Profile/panels/ProfileShowcasePanel.qml
- ui/imports/shared/controls/EmptyShapeRectangleFooterListView.qml
Closes #13590
- Added new additional footer component in `EmptyShapeRectangleFooterListView`.
- Enabled more accounts component in profile **showcase assets** and **collectibles** panel.
Profile showcase assets and collectibles tabs
https://github.com/status-im/status-desktop/assets/97019400/256dfee4-d6a9-437e-b48b-5a9d8bd82705
> feat(ProfileShowcase): Enable add more accounts component

- scripts/open_database.py
- src/app/core/fleets/fleet_configuration.nim
- src/app/modules/main/profile_section/advanced/controller.nim
- src/app_service/service/node_configuration/service.nim
- src/app_service/service/settings/service.nim
Requires https://github.com/status-im/status-go/pull/4785
1. Update status-go to get https://github.com/status-im/status-go/pull/4785
2. Implement custom `fleetFromString` function to prevent panic for unknown enum values
3. Added `import readline` to `scripts/open_database.py`. This just improves the work of the script. Don't think it's worth a separate PR 😄 
Tested with 2 cases:
1. case 1
- setup a new account with 0.14.0
- migrate to 2.27
2. case 2
- setup a new account with 0.14.0
- switch to `waku.test` fleet
- switch back to `status.prod` fleet 
(this is required for `status.prod` to appear in settings)
⚠️ Then this fix actually starts to work. If the `settings.fleet` is empty, `1701961850_shards_test.up.sql` migration does the job.
In both cases I end up with no crash and …
> fix: fallback to default fleet when unknown value in settings

- src/app_service/service/community/dto/community.nim
- src/app_service/service/community/service.nim
This PR solves the missing crown problem after an ownership transfer
fixes #13218 https://github.com/status-im/status-desktop/issues/13218
The PR triggers the update of the memberRole property in the user model to be able to update the presence of a crown on a member.
- Chat
[solution-missing-crown.webm](https://github.com/status-im/status-desktop/assets/2589171/45da74b1-eb35-431f-8f93-fc8febb1dc90)
> (desktop/fix) Fix missing crown after ownership transfer

- ui/StatusQ/src/StatusQ/Components/StatusDraggableListItem.qml
- ui/app/AppLayouts/Profile/controls/ShowcaseDelegate.qml
- ui/app/AppLayouts/Profile/panels/ProfileShowcasePanel.qml
- ui/imports/shared/controls/EmptyShapeRectangleFooterListView.qml
- ui/imports/utils/ProfileUtils.qml
Closes #13509
- It updates `ProfileShowcasePanel` with new drop area design adding shadows, changing drop areas design and sizes.
- It adjusts `ShowcaseDelegate` according to design, ie: heigh and background colour on dragActive.
- SQ / `StatusDraggableListItem`: Added new property `colorOnDragActive ` that holds if background color will be changed on drag active or not.
Profile showcase tabs: Communities, Accounts, Collectibles and Assets
StatusQ / StatusDraggableListItem
https://github.com/status-im/status-desktop/assets/97019400/0169c764-fc95-4da1-abc7-8ec91b19a477
> feat(ProfileShowcase): Drop area behaviour / design when sections expanded

- scripts/open_database.py
- src/app/core/fleets/fleet_configuration.nim
- src/app/modules/main/profile_section/advanced/controller.nim
- src/app_service/service/node_configuration/service.nim
- src/app_service/service/settings/service.nim
cherry-pick https://github.com/status-im/status-desktop/pull/13670
> [CHERRY-PICK] fix: use `fleetFromString` function to prevent panic for unknown values

- src/app/modules/main/module.nim
- src/app/modules/main/wallet_section/all_tokens/controller.nim
- src/app/modules/main/wallet_section/all_tokens/flat_tokens_model.nim
- src/app/modules/main/wallet_section/all_tokens/io_interface.nim
- src/app/modules/main/wallet_section/all_tokens/module.nim
- src/app/modules/main/wallet_section/all_tokens/token_by_symbol_model.nim
- src/app/modules/main/wallet_section/module.nim
- src/app_service/service/community_tokens/service.nim
- storybook/pages/AssetsViewPage.qml
- storybook/src/Models/TokensBySymbolModel.qml
- ui/StatusQ/src/StatusQ/Components/StatusChartPanel.qml
- ui/StatusQ/src/StatusQ/Core/Utils/Utils.qml
- ui/app/AppLayouts/Communities/views/EditCommunityTokenView.qml
- ui/app/AppLayouts/Wallet/controls/ActivityFilterTagItem.qml
- ui/app/AppLayouts/Wallet/controls/CollectibleDetailsHeader.qml
- ui/app/AppLayouts/Wallet/controls/InformationTileAssetDetails.qml
- ui/app/AppLayouts/Wallet/controls/qmldir
- ui/app/AppLayouts/Wallet/panels/ActivityFilterPanel.qml
- ui/app/AppLayouts/Wallet/popups/ReceiveModal.qml
- ui/app/AppLayouts/Wallet/views/AssetsDetailView.qml
- ui/app/AppLayouts/Wallet/views/RightTabView.qml
- ui/imports/shared/controls/AssetsDetailsHeader.qml
- ui/imports/shared/controls/InformationTag.qml
closes #12373
Design implemented in this PR: https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=21330-199931&mode=design&t=CjaU66KwWS3bRgrp-4
AssetDetailsView
**Community Token:**
https://github.com/status-im/status-desktop/assets/60327365/f4480677-443a-466c-bdb3-c6351750293f
**ERC20**
https://github.com/status-im/status-desktop/assets/60327365/635c4599-3328-495f-8b02-837da8c9bba3
> feat(@desktop/wallet): Update token details view

- ui/app/AppLayouts/Profile/controls/ShowcaseDelegate.qml
- ui/app/AppLayouts/Profile/panels/ProfileShowcasePanel.qml
Closes #13594
- Added `FastBlur` component to `ShowcaseDelegate` and added property to change to blur state.
- Updated `ProfileShowcasePanel` to activate blur delegate state when dragging.
Profile Showcase --> Accounts, communities, assets and collectibles tabs
- **Storybook**:
https://github.com/status-im/status-desktop/assets/97019400/3d18efc9-cd27-44cd-9da8-db035770b939
- **App**:
https://github.com/status-im/status-desktop/assets/97019400/c49ec850-6c9c-4480-8989-904ab9b9f048
> feat(ProfileShowcase): Add blur delegate state while dragging

- src/app/global/local_account_settings.nim
- src/app/modules/main/profile_section/profile/io_interface.nim
- src/app/modules/main/profile_section/profile/module.nim
- src/app/modules/main/profile_section/profile/view.nim
- storybook/pages/ProfileShowcaseInfoPopupPage.qml
- ui/app/AppLayouts/Communities/panels/IntroPanel.qml
- ui/app/AppLayouts/Profile/popups/ProfileShowcaseInfoPopup.qml
- ui/app/AppLayouts/Profile/popups/qmldir
- ui/app/AppLayouts/Profile/stores/ProfileStore.qml
- ui/app/AppLayouts/Profile/views/MyProfileView.qml
Closes #13338
- Created `ProfileShowcaseInfoPopup` component.
- Added `storybook` support for the new popup component.
- Added new popup into the application flow. 
- Added new settings property in _local account settings_ file.
Profile Showcase settings page
- App integration:
https://github.com/status-im/status-desktop/assets/97019400/a3765851-60c6-48df-a645-c322bc0e79f1
- Storybook:
https://github.com/status-im/status-desktop/assets/97019400/8066d70e-94ed-4008-94ab-7d1b35e28056
> feat(ProfileShowcase): Created first info popup

- storybook/pages/ProfileDialogViewPage.qml
- ui/StatusQ/src/StatusQ/Controls/StatusBaseButton.qml
- ui/app/mainui/Popups.qml
- ui/imports/shared/popups/CommonContactDialog.qml
- ui/imports/shared/popups/MarkAsIDVerifiedDialog.qml
- ui/imports/shared/popups/RemoveIDVerificationDialog.qml
- ui/imports/shared/popups/qmldir
- ui/imports/shared/views/ProfileDialogView.qml
- ui/imports/shared/views/chat/ProfileContextMenu.qml
- ui/imports/utils/Global.qml
> [!NOTE]
> This won't work directly in the app as of now, needs the appropriate backend: https://github.com/status-im/status-desktop/issues/13716
- implement two new actions and popups to directly mark a contact as "ID verified" and remove the verification thereof respectively
- do not hardcode the secondary button inside ProfileDialogView and make it a Loader
- make the CommonContactDialog contents scrollable
Fixes #13711
ProfileDialogView, ProfileContextMenu
Optional secondary button for a contact ("Request ID verification):
Mark as ID verified popup:
ID verified + action to remove:
Popup to remove the ID verified status (+ optionally mark as untrusted or remove the contact):
> feat(Profile flow) Mark as ID verified / remove verification

- ui/app/AppLayouts/Profile/popups/ConfirmAppRestartModal.qml
- ui/app/AppLayouts/Profile/views/AppearanceView.qml
- ui/app/AppLayouts/Profile/views/LanguageView.qml
- ui/main.qml
- vendor/DOtherSide/lib/src/DOtherSide.cpp
The long story:
- since Qt treats the various scale factors in a multiplicative way (see https://www.qt.io/blog/2016/01/26/high-dpi-support-in-qt-5-6 for explanation) and there's no way to get the screen's baseline scale factor programatically, we also have to export `QT_SCREEN_SCALE_FACTORS` to something that's not equal to `0` or `1` to force the monitor scale factor to `100%` and then compensate for it when exporting our own scale
value using `QT_SCALE_FACTOR`
- make the UI slider values go in `25%` steps, allowing for more fine grained control; with `100%` we fallback to the Qt's native handling of highdpi 
- raised the maximum to `300%` since on highres displays, one wouldn't be able to go over the implicit maximum of `200%` (due to the internal scaling being 2x)
- scale our main …
> fix: 150% and 200% zoom levels prevent the user from logging in

- ui/app/AppLayouts/Profile/panels/ProfileShowcasePanel.qml
- ui/imports/shared/controls/FoldableHeader.qml
Closes #13595
- It adds an additional right component to `FoldableHeader.qml`.
- It adds hidden button component in `hidden` foldable header.
- It adds visibility buttons component in `in showcase` foldable header.
**NOTE /  Known issues**: App can behave wrongly until https://github.com/status-im/status-desktop/issues/13498 is integrated. Right now changing visibility of items trigger some unnecessary model resets that can cause UI misbehaviors (i.e: collapsing / uncollapsing section items). 
Profile showcase communities, accounts, assets and collectibles tabs.
https://github.com/status-im/status-desktop/assets/97019400/ee58e37f-82ef-429a-bb0d-ec37bd1051be
> feat(ProfileShowcase): Adds drop area in collapsed headers

- src/app_service/common/network_constants.nim
Make goerli only via infura and no fallback as a result of POKT removing support for goerli next week
> chore: remove pokt goerli

- src/app/modules/main/communities/models/curated_community_item.nim
- src/app/modules/main/communities/models/curated_community_model.nim
- src/app/modules/main/communities/module.nim
- src/app_service/service/community/service.nim
- ui/StatusQ/src/StatusQ/Controls/StatusNavBarTabButton.qml
- ui/app/AppLayouts/Chat/ChatLayout.qml
- ui/app/AppLayouts/Communities/CommunitiesPortalLayout.qml
- ui/app/AppLayouts/Communities/panels/CommunityBannedMemberCenterPanel.qml
- ui/app/AppLayouts/Communities/panels/qmldir
- ui/app/AppLayouts/Communities/views/BannedMemberCommunityView.qml
- ui/app/AppLayouts/Communities/views/qmldir
- ui/app/mainui/AppMain.qml
- ui/imports/Themes/Theme.qml
- when a user is banned or kicked, the community should disappear from the community nav bar and the next community down should be selected (unless there are no other communities in the nav bar in which case the Find community page is selected).
- if a user is banned from the community, they should not be able to see or search for the community in the Find Community page
- if the user navigates to the community while they are banned (e.g. via a share link), they will see a banned state for that community
Closes: https://github.com/status-im/status-desktop/issues/13454
status-go PR: https://github.com/status-im/status-go/pull/4806
- Ban/unban
- Curated communities list
https://github.com/status-im/status-desktop/assets/117639195/2dab83c6-4a4c-4279-801b-b1fe6e2c00f6
> feat(desktop@communities): change kicked/banned member behavior

- ui/app/AppLayouts/Profile/popups/ProfileShowcaseInfoPopup.qml
Object name for build showcase button added
ProfileShowcaseInfoPopup.qml
> chore: object name for build showcase button added

- ui/imports/shared/views/chat/MessageView.qml
> fix(@desktop/messages) Bridge messages will always have headers

- src/app/modules/main/chat_section/module.nim
- src/app/modules/main/communities/module.nim
- src/app/modules/shared_models/token_criteria_item.nim
- src/app/modules/shared_models/token_list_item.nim
- src/app/modules/shared_models/token_list_model.nim
- src/app/modules/shared_models/token_permission_item.nim
- src/app_service/service/community/dto/community.nim
- ui/app/AppLayouts/Communities/helpers/PermissionsHelpers.qml
- ui/app/AppLayouts/Communities/panels/JoinPermissionsOverlayPanel.qml
- ui/app/AppLayouts/Communities/views/EditPermissionView.qml
- ui/app/AppLayouts/Communities/views/HoldingsSelectionModel.qml
Handle correct values in permissions.
Add a new field AmountInWeis to token criteria dto.
Keep strings instead of floats in token_criteria_item.
HoldingSelectionModel keeps amount in wei-like units but they are displayed in permissions as floats (divided by decimals).
Add decimals to token_list_model.
status-go [pr](https://github.com/status-im/status-go/pull/4727)
Issue #11588
> 11588 fix permissions values

- src/app/modules/main/module.nim
Show pending ban/unban/kick state if the control node is offline
Closes: https://github.com/status-im/status-desktop/issues/13596
kick/ban/unban state in the member's list
> fix: show pending ban/unban/kick state if the control node is offline

- src/app/modules/main/profile_section/contacts/controller.nim
- src/app/modules/main/profile_section/contacts/io_interface.nim
- src/app/modules/main/profile_section/contacts/module.nim
- src/app/modules/main/profile_section/contacts/view.nim
- src/app_service/service/contacts/service.nim
- src/backend/contacts.nim
- ui/app/AppLayouts/Profile/stores/ContactsStore.qml
Close #13716
- Add `markAsTrusted` endpoint (already present in status-go)
Contacts
> Feat: add `markAsTrusted` endpoint

- ui/app/AppLayouts/Communities/panels/MintTokensSettingsPanel.qml
- ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml
- ui/app/AppLayouts/Communities/views/CommunityTokenView.qml
Fix #12065 token owner presentation in Token section by displaying the owner token holder as contact
Fetch the contactDetails for the token owner found in the tokenOwnerModel.
MintedTokenView page
Figma:
The following match the UI expectations
> (desktop/fix) Fix Owner token holder representation

- scripts/bump-status-go.sh
This allows now to bump status-go to latest develop. Usage: 
```bash
./scripts/bump-status-go.sh --latest
```
Also improved the PR link a bit 🙂
> chore: `bump-status-go.sh` latest option

- ui/app/AppLayouts/Profile/views/ChangePasswordView.qml
Closes #13302
ProfileSettings: Added biometrics in password change view
ProfileSettings password change view
https://github.com/status-im/status-desktop/assets/31625338/68a91a5e-5d58-4ac6-80ae-d4f63b07bae5
> [ProfileSettings]: Added biometrics in password change view

- src/app/modules/main/profile_section/contacts/controller.nim
- src/app/modules/main/profile_section/contacts/io_interface.nim
- src/app/modules/main/profile_section/contacts/module.nim
- src/app/modules/main/profile_section/contacts/view.nim
- src/app_service/service/contacts/service.nim
- src/backend/contacts.nim
- ui/app/AppLayouts/Profile/stores/ContactsStore.qml
Close #13604
Waits https://github.com/status-im/status-go/pull/4819
Add endpoint for getting latest pending CR for a contact including message
Contacts
```
{
"id":"0xb0ee14df8c433398fa017fd404fc535631889b2f73926d3973cafc3416ba0d5d",
"from":"0x04effb663a86fcc5f7df47b2c945731789e338c7556cb30d935947be4db8be9e3c2791f8f8b19cd46758a887a22af09db522c98508ae0a6d79a2df33cb6468cd15",
"parsedText":[
{
"type":"paragraph",
"literal":"",
"destination":"",
"children":[
{
"type":"",
"literal":"Hi Mishka,,, just testing :)",
"destination":"",
"children":[
]
}
]
}
],
"text":"Hi Mishka,,, just testing :)",
"contactRequestState":2,
"s
```
> feat: Add api for getting full pending CR object

- src/app/modules/shared_modules/keycard_popup/controller.nim
fixes #13051 User blocked in model when using biometrics to share address when joining a community. 
There was a missing connection of the connect signal coming from the Key chain after entering a password and correctly obtaining data from the Keychain service. So this PR just connects the signal to the already existing signal processor
NA
> (fix/biometrics) Fix biometric authentication

- ui/StatusQ/include/StatusQ/writableproxymodel.h
- ui/StatusQ/src/writableproxymodel.cpp
- ui/StatusQ/tests/tst_WritableProxyModel.cpp
1. Fixes improper intermediate state on move (`onRowsAboutToBeMoved` handler), added test covering this case
2. Added proper handling of layoutAboutToBeChanged/layoutChanged (also for move operation)
Closes: #13601
`WritableProxyModel`
> StatusQ(WritableProxyModel): Handling of layoutChanged/rowsMoved from source models fixed

- ui/StatusQ/src/StatusQ/Components/StatusFlowSelector.qml
Added object name for add item buttons
ui/StatusQ/src/StatusQ/Components/StatusFlowSelector.qml
> chore: object name for add item button added

- storybook/pages/ProfileDialogViewPage.qml
- ui/app/mainui/Popups.qml
- ui/imports/shared/popups/ContactVerificationRequestPopup.qml
- ui/imports/shared/popups/ReviewContactRequestPopup.qml
- ui/imports/shared/popups/qmldir
- ui/imports/shared/views/ProfileDialogView.qml
- ui/imports/shared/views/chat/ProfileContextMenu.qml
- ui/imports/utils/Global.qml
- implement the new "Review contact request" popup & flow
- adjust storybook
Fixes #13519
ProfileDialogView,ProfileContextMenu
> feat(Profile flow): Respond to/review an incoming CR

- ui/app/AppLayouts/Profile/ProfileLayout.qml
- ui/app/AppLayouts/Profile/views/MyProfileView.qml
- ui/app/AppLayouts/Profile/views/SettingsContentBase.qml
- ui/app/AppLayouts/Profile/views/WalletView.qml
Closes #13517
- Added `autoscrollWhenDirty` property to be able to configure the settings content base as autoscroll mode when dirty toast appears. Otherwise, the toast will be shown overlaid on top of the view content.
- Updated profile view to setup autoscroll on `Identity` tab. Rest of app cases are setup with the overlay mode.
Setting pages
https://github.com/status-im/status-desktop/assets/97019400/204f6d01-49df-43f0-b9bf-d4e4e470713f
> feat(SettingsContentBase): Save changes bubble overlapping by default

- src/app/modules/main/chat_section/chat_content/view.nim
- ui/StatusQ/src/StatusQ/Components/private/statusMessage/StatusMessageEmojiReactions.qml
- ui/app/AppLayouts/Chat/stores/RootStore.qml
- ui/app/AppLayouts/Chat/views/ChatColumnView.qml
- ui/app/AppLayouts/Chat/views/ChatView.qml
- ui/imports/shared/status/StatusChatInput.qml
- ui/imports/shared/views/chat/MessageView.qml
- extend `isUserAllowedToSendMessage` to also cover `Constants.chatType.communityChat`
- let `admin` always satisfy the permissions
- hide the add emoji/reaction button instead of disabling it when the permissions are not met
- adjust the error msg to better reflect the reality (tokens vs. permissions)
Fixes #13777
StatusChatInput,ChatColumnView
[Záznam obrazovky z 2024-03-04 11-17-37.webm](https://github.com/status-im/status-desktop/assets/5377645/0009cdbc-6538-4a5d-a085-ca83093b2674)
> fix(chat input): should be disabled if user is not able to post

- src/app_service/service/community_tokens/service.nim
Fixes #13407
We were processing all wallet events received as if they were from us, so I skip the ones from watch only accounts.
I assumed that `accounts` always contains one address (it seems it's assumed as such in the code later too). Let me know if that's now the case and I'll make it smarter if needed.
> fix(community_tokens): ignore wallet events from watch only accounts

- storybook/pages/CreateChannelPopupPage.qml
- ui/StatusQ/src/StatusQ/Popups/Dialog/StatusDialog.qml
- ui/StatusQ/src/StatusQ/Popups/StatusConfirmationDialog.qml
- ui/StatusQ/src/StatusQ/Popups/StatusModal.qml
- ui/StatusQ/src/StatusQ/Popups/StatusStackModal.qml
- ui/StatusQ/src/StatusQ/Popups/qmldir
- ui/StatusQ/src/statusq.qrc
- ui/app/AppLayouts/Communities/popups/CreateChannelPopup.qml
Closing #13463 
Changes:
1. Added StatusConfirmationDialog
2. Add NoAutoClose to the `CreateChannelPopup`
3. Updated the StatusStackModal tree to support custom close handler
4. Add the dirty state flag in the `CreateChannelPopup` to include all fields
Edit channel popup
https://github.com/status-im/status-desktop/assets/47811206/4f4c98f1-9145-41fb-8972-e04dd6c0b3a5
> feat(ChannelPermissions): Show confirmation dialog before closing the channel edit popup

- ui/app/mainui/Popups.qml
- ui/imports/shared/views/ProfileDialogView.qml
- ui/imports/shared/views/chat/ProfileContextMenu.qml
- ui/imports/utils/Global.qml
- trigger a reload of contact details when the secondary popup has been closed
Fixes #13870
ProfileDialog
[Záznam obrazovky z 2024-03-07 11-12-43.webm](https://github.com/status-im/status-desktop/assets/5377645/ba919f19-1c1d-472f-a67c-d95f5a932aec)
> fix: [Profile flow] Nickname not updated after it was added, edited or removed

- storybook/pages/ProfileShowcaseAccountsPanelPage.qml
- storybook/pages/ProfileShowcaseAssetsPanelPage.qml
- storybook/pages/ProfileShowcaseCollectiblesPanelPage.qml
- storybook/pages/ProfileShowcaseCommunitiesPanelPage.qml
- storybook/pages/ProfileShowcasePanelPage.qml
- ui/app/AppLayouts/Profile/controls/ShowcaseDelegate.qml
- ui/app/AppLayouts/Profile/panels/ProfileShowcasePanel.qml
- ui/imports/shared/controls/DisabledTooltipButton.qml
- ui/imports/utils/ProfileUtils.qml
Closes #13507 
- Added counter in showcase header.
- Added placeholder when limit reached and section expanded.
- Added placeholder when limit reached and section collapsed.
- Added green animation when section collapsed and element added.
- Disabled showcase delegate context menu when limit reached.
- Added model changes tracker to track the in showcase count.
Profile Showcase / Community, Assets, Accounts and Collectibles tabs
- App fixed limit to 2 for testing:
https://github.com/status-im/status-desktop/assets/97019400/fdea4cc0-adb6-4589-aaf0-b0447dd988c5
- Storybook:
https://github.com/status-im/status-desktop/assets/97019400/c53e148a-fe6f-424a-b9c2-6aaee4126f29
> feat(ProfileShowcase): Display counter in `In showcase` section header a… …nd elements limit

- ui/StatusQ/include/StatusQ/movablemodel.h
- ui/StatusQ/src/movablemodel.cpp
- ui/StatusQ/tests/tst_MovableModel.cpp
Don't emit `layoutChanged` when the source model changes.
+Update tests
MovableModel
> fix(StatusQ): Don't emit layoutChanged on source model reset in MovableModel

- ui/app/AppLayouts/Wallet/views/CollectiblesView.qml
- use the right icons for collapsed/expanded state (this should probably use the existing `FoldableHeader` component, with some modifications)
Fixes #13774
CollectiblesView
> fix: Collapse / expand section header icons in collectibles view

- storybook/pages/ProfileShowcasePanelPage.qml
- ui/app/AppLayouts/Profile/helpers/ProfileShowcaseDirtyState.qml
- ui/app/AppLayouts/Profile/helpers/ProfileShowcaseModels.qml
- ui/app/AppLayouts/Profile/panels/ProfileShowcaseAccountsPanel.qml
- ui/app/AppLayouts/Profile/panels/ProfileShowcaseAssetsPanel.qml
- ui/app/AppLayouts/Profile/panels/ProfileShowcaseCollectiblesPanel.qml
- ui/app/AppLayouts/Profile/panels/ProfileShowcaseCommunitiesPanel.qml
- ui/app/AppLayouts/Profile/panels/ProfileShowcasePanel.qml
- ui/app/AppLayouts/Profile/views/MyProfileView.qml
- ui/imports/utils/Constants.qml
- ui/imports/utils/ProfileUtils.qml
Closes #13508
- Added searcher input in header.
- Added 2 filter proxies for hidden and inshowcase models depending on search text.
- Added filter expression per showcase tab (accounts, collectibles and communities).
- Added specific placeholder when search empty.
- Added specific logic when search active.
- Added search validation.
Profile Showcase / Community, Assets, Accounts and Collectibles tabs
https://github.com/status-im/status-desktop/assets/97019400/69185b40-f5c7-465f-b27c-68fc41be9afc
> feat(ProfileShowcase): Add search input in all tabs

- src/constants.nim
- src/env_cli_vars.nim
- src/nim_status_client.nim
- ui/app/AppLayouts/Profile/ProfileLayout.qml
- ui/app/AppLayouts/Profile/views/AdvancedView.qml
- introduce `ENABLE_FLEET_SELECTION` desktop config entry to control the Fleet selection UI availability
- UI can be enabled with envvar `STATUS_RUNTIME_ENABLE_FLEET_SELECTION=1`
Fixes #13848
Settings/Advanced
Disabled by default:
With `ENABLE_FLEET_SELECTION=1`:
> fix: Hide fleet selection from settings

- ui/StatusQ/src/StatusQ/Components/StatusDraggableListItem.qml
#13681
Fixes blinking when hovering over an address
https://github.com/status-im/status-desktop/assets/1083341/c7f8650e-4271-4d00-91ea-6f03988264b1
and the same component is used here
https://github.com/status-im/status-desktop/assets/1083341/3182c88b-1e38-437d-8ec0-f8deeb4a2aad
> fix(ProfileShowcase): Fix blinking when hovering over an address

- ci/Jenkinsfile.windows
If we don't we regularly get weird Git failures on Windows like:
```
fatal: Unable to find current revision in submodule path 'vendor/qzxing/tests/resources'
fatal: Failed to recurse into submodule path 'vendor/qzxing'
```
Or
```
stderr: fatal: Unable to create '.../.git/index.lock': File exists.
```
Which are very annoying and require manual workspace purge by infra team.
Many of you will get annoyed with resulting slower checkouts on subsequent builds, but that's a price I'm willing to pay.
> chore(ci): do full Windows workspace cleanup

- ui/app/AppLayouts/Chat/views/ChatColumnView.qml
- ui/app/AppLayouts/Chat/views/ChatView.qml
Fixes #13779
The problem was that the permission update some times takes time to get propagated and get back, or even the control node is offline, so the TM would not be able to post, because the backend would detect that there is a permission and that we don't have the key for it.
The solution is to block the UI when a permission update is pending, since we can't post correctly while it is not processed by he control node.
See in this video how it looks like. Do note that there is still the bug that the input isn't disabled when there is this message. That's fixed somewhere else.
[TM-posting.webm](https://github.com/status-im/status-desktop/assets/11926403/76d2a002-a7c9-49ca-aa5a-44da2ff35402)
> fix: fix token master can't send a message on permissioned channel

- storybook/pages/ProfileShowcasePanelPage.qml
- storybook/qmlTests/tests/tst_ManageCollectiblesPanel.qml
- storybook/src/Models/ManageCollectiblesModel.qml
- ui/app/AppLayouts/Communities/panels/MintTokensSettingsPanel.qml
- ui/app/AppLayouts/Communities/views/MintedTokensView.qml
- ui/app/AppLayouts/Profile/panels/ProfileShowcaseCollectiblesPanel.qml
- ui/app/AppLayouts/Wallet/controls/ManageTokensCommunityTag.qml
- ui/app/AppLayouts/Wallet/controls/ManageTokensDelegate.qml
- ui/app/AppLayouts/Wallet/controls/ManageTokensGroupDelegate.qml
- ui/app/AppLayouts/Wallet/views/collectibles/CollectibleView.qml
- ui/imports/shared/controls/TokenDelegate.qml
> feat(@wallet): unknown token

- src/app/modules/main/wallet_section/activity/controller.nim
- src/app/modules/main/wallet_section/activity/entry.nim
- src/app/modules/main/wallet_section/activity/events_handler.nim
- src/app/modules/main/wallet_section/activity/model.nim
- src/app/modules/main/wallet_section/activity/status.nim
- src/app/modules/main/wallet_section/module.nim
- src/backend/activity.nim
- src/backend/backend.nim
- src/backend/transactions.nim
- storybook/pages/TransactionDelegatePage.qml
- test/nim/activity_tests.nim
- test/status-go/integration/helpers/helpers.go
- test/status-go/integration/wallet/activityfiltering_test.go
- ui/imports/shared/controls/TransactionDelegate.qml
- ui/imports/shared/stores/RootStore.qml
- ui/imports/shared/views/HistoryView.qml
Switch the activity filter to use the new session-based API, which provides incremental updates to the current filter. 
Replace the previous method of listening for individual change events with this unified API that delivers all the updates at filter entry level.
The new transactions now activate the "new transactions" button, causing a reset of the current filter and highlighting the top new transactions.
New entries (pulled by downloader) older than the latest visible entries are inserted in the view and highlithed
On all filter clear the updates made while the filter was active are highlighted
https://github.com/status-im/status-desktop/assets/47554641/1c997635-2500-4754-846b-dde93162e766
https://github.com/status-im/status-desktop/assets/47554641/f0f0c86e-0078-4817-aad2-ecdd5258bc8a …
> Activity dynamic updates integration

- storybook/pages/FinaliseOwnershipDeclinePopupPage.qml
- storybook/validator_main.cpp
- ui/app/AppLayouts/Profile/ProfileLayout.qml
- ui/app/AppLayouts/Profile/views/SettingsContentBase.qml
- use the full `QQmlEngine` to test loading of the component
- separate commits to fix the failures and simplify SettingsContentsBase
Fixes #13901
CI/StoryBook
Before:
After:
> fix[CI] PagesValidator UI test doesn't catch missing `required` properties

- src/app/modules/shared_models/collectible_ownership_model.nim
- storybook/src/Models/ManageCollectiblesModel.qml
- ui/StatusQ/src/StatusQ/Core/Utils/AmountsArithmetic.qml
- ui/app/AppLayouts/Wallet/controls/CollectibleBalanceTag.qml
- ui/app/AppLayouts/Wallet/controls/qmldir
- ui/app/AppLayouts/Wallet/views/CollectiblesView.qml
- ui/app/AppLayouts/Wallet/views/collectibles/CollectibleView.qml
Closes #12940
status-go part: https://github.com/status-im/status-go/pull/4870
Followups:
https://github.com/status-im/status-desktop/issues/13866
https://github.com/status-im/status-desktop/issues/13880
Show balances in the Collectibles view for ERC1155 collectibles with balance >1
> feat(@desktop/wallet): display balance in collectibles view

- src/app_service/service/profile/service.nim
- ui/StatusQ/include/StatusQ/writableproxymodel.h
- ui/StatusQ/src/writableproxymodel.cpp
- ui/StatusQ/tests/tst_WritableProxyModel.cpp
- ui/app/AppLayouts/Profile/helpers/ProfileShowcaseDirtyState.qml
- ui/app/AppLayouts/Profile/helpers/VisibilityAndPositionDirtyStateModel.qml
- ui/app/AppLayouts/Profile/views/MyProfileView.qml
Closing #13603 
Changes:
1. Adding `syncedRemovals` flag to the WritableProxyModel. This flag enables the source model to remove dirty rows
2. Fix the WritableProxyModel to allow full dirty state synchronisation with the model chains and properly remove the dirty state
3. Update the Profile Showcase qml components to use `syncedRemovals` and fix the dirty state after save
4. Removed the `reset` call after `save`
5. Added a call to fetch the newly saved showcase models from the backend to update the models
WritableProxyModel
https://github.com/status-im/status-desktop/assets/47811206/addadca2-891f-46a8-b954-a5197f5e5d4d
> 13603 statusqwritablemodel add option allowing to remove items always when removed in source

- storybook/pages/BeforeGetStartedModalPage.qml
- ui/StatusQ/src/stringutilsinternal.cpp
- ui/app/AppLayouts/Onboarding/popups/BeforeGetStartedModal.qml
- ui/app/AppLayouts/Onboarding/popups/qmldir
- display the locally bundled "privacy/terms of use" texts in a popup
- add support for reading text files with both relative and absolute files or URLs, useful for having the same file path in both storybook and the app
Fixes #13877
Onboarding
[Záznam obrazovky z 2024-03-11 15-24-36.webm](https://github.com/status-im/status-desktop/assets/5377645/30cad682-d305-4486-9b5d-328b18cef2bc)
> fix[onboarding] Broken links to "Terms" and "Privacy"

- ui/app/AppLayouts/Communities/popups/CreateChannelPopup.qml
Closing: #13648 
Fixing the permission view width in the create channel popup to remove the scroll.
ChannelPopup
https://github.com/status-im/status-desktop/assets/47811206/97848bb5-ba9c-42c9-802e-b5078877aa8e
> fix(ChannelPopup): Fix channel popup width

- storybook/pages/ProfileShowcaseModelsPage.qml
- storybook/pages/ProfileSocialLinksPanelPage.qml
- ui/StatusQ/src/StatusQ/Controls/StatusSeedPhraseInput.qml
- ui/app/AppLayouts/Profile/helpers/ProfileShowcaseDirtyState.qml
- ui/app/AppLayouts/Profile/helpers/ProfileShowcaseModelAdapter.qml
- ui/app/AppLayouts/Profile/helpers/ProfileShowcaseModels.qml
- ui/app/AppLayouts/Profile/helpers/VisibilityAndPositionDirtyStateModel.qml
- ui/app/AppLayouts/Profile/panels/ProfileSocialLinksPanel.qml
- ui/app/AppLayouts/Profile/popups/ModifySocialLinkModal.qml
- ui/app/AppLayouts/Profile/views/MyProfileView.qml
- ui/imports/utils/ProfileUtils.qml
Closing #13495
This will be merged after https://github.com/status-im/status-desktop/issues/13799 to align the save action as well.
Changes:
1. Create the dirty state component for the web tab
2. Update the ProfileSocialLinksPanel to support the new model
3. Integrate the ProfileSocialLinksPanel actions with the dirty state component
4. Update storybook
5. Quick fix here ui/StatusQ/src/StatusQ/Controls/StatusSeedPhraseInput.qml because the `Popups` component cannot be used in storybook with qt 5.15.8
https://github.com/status-im/status-desktop/assets/47811206/868e9a5e-dacb-4250-ab93-064d29d9be1f
> feat(ProfileShowcase): Create dirty state component for the web tab and integrate the UI

- src/app/modules/main/profile_section/profile/io_interface.nim
- src/app/modules/main/profile_section/profile/models/profile_save_data.nim
- src/app/modules/main/profile_section/profile/module.nim
- src/app/modules/main/profile_section/profile/view.nim
- ui/app/AppLayouts/Profile/stores/ProfileStore.qml
- ui/app/AppLayouts/Profile/views/MyProfileView.qml
Close #13767
Profile
https://github.com/status-im/status-desktop/assets/2522130/fda799a4-792c-4afa-95ef-31364ed09f6f
> feat: Save profile identity in one json

- storybook/src/Models/ManageCollectiblesModel.qml
- ui/app/AppLayouts/Wallet/controls/ManageTokensCommunityTag.qml
- ui/app/AppLayouts/Wallet/views/CollectiblesView.qml
- ui/app/AppLayouts/Wallet/views/collectibles/CollectibleView.qml
- ui/imports/shared/controls/FoldableHeader.qml
Closes #13315
It closes previous mentioned issue but also some other fixes:
-  Some strange layout behaviour in `CollectiblesView` caused by a wrong syntax.
- Storybook waring cleanup.
- Collectible community tag elided correctly.
- Visualize section header when only community collectibles present.
Main wallet collectibles layout
- Fix in layout due to some syntax error:
_Before:_
_After:_
- Community tag:
- Header visible/hidden depending on collectibles type:
https://github.com/status-im/status-desktop/assets/97019400/dd17faff-93ef-4939-b83b-c69b55857c22
> feat(CollectiblesLayout): Always visualize section header if community minted collectibles are present

- src/app/modules/main/profile_section/wallet/accounts/model.nim
- ui/app/AppLayouts/Profile/helpers/ProfileShowcaseModels.qml
- ui/app/AppLayouts/Profile/panels/ProfileShowcaseAccountsPanel.qml
- ui/app/AppLayouts/Profile/stores/WalletStore.qml
- ui/app/AppLayouts/Profile/views/MyProfileView.qml
Closes #13899
- Added network prefixes in profile showcase accounts delegate and included them in the searcher.
- Added filter to just display own accounts in profile showcase accounts tab.
Profile Showcase / accounts tab
https://github.com/status-im/status-desktop/assets/97019400/7eccb7f8-002a-4999-83b4-d510badde691
> feat(ProfileShowcase): Add network prefixes and filter watch only accounts

- ui/app/AppLayouts/Profile/controls/ShowcaseDelegate.qml
- ui/app/AppLayouts/Profile/panels/ProfileShowcaseCollectiblesPanel.qml
- ui/app/AppLayouts/Profile/panels/ProfileShowcasePanel.qml
Closing #13343 
Changes: 
1. Update drop area to show only the drop available items
2. Update the context menu to disable unavailable options
3. Add dynamic width to the context menu
https://github.com/status-im/status-desktop/assets/47811206/6659c5e4-0393-47c6-8e83-aa06af73092d
> feat(profileShowcase): Sync collectibles context menu with account visibility

- src/app/modules/main/chat_section/chat_content/chat_details.nim
- src/app/modules/main/chat_section/chat_content/module.nim
- src/app/modules/main/chat_section/chat_content/view.nim
- src/app/modules/main/chat_section/controller.nim
- src/app/modules/main/chat_section/io_interface.nim
- src/app/modules/main/chat_section/item.nim
- src/app/modules/main/chat_section/model.nim
- src/app/modules/main/chat_section/module.nim
- src/app/modules/main/chat_section/view.nim
- src/app_service/service/chat/dto/chat.nim
- src/app_service/service/chat/service.nim
- src/app_service/service/community/service.nim
- src/backend/communities.nim
- ui/app/AppLayouts/Chat/stores/RootStore.qml
- ui/app/AppLayouts/Communities/popups/CreateChannelPopup.qml
- ui/app/AppLayouts/Communities/views/CommunityColumnView.qml
- ui/app/AppLayouts/Communities/views/PermissionsView.qml
- ui/imports/shared/stores/PermissionsStore.qml
- ui/imports/shared/views/chat/ChatContextMenuView.qml
- ui/imports/shared/views/chat/MessageContextMenuView.qml
- ui/imports/shared/views/chat/MessageView.qml
Fixes #13523
Status-go PR: https://github.com/status-im/status-go/pull/4900
This hooks the feature that let's users react in a view only channel, but only if the setting is enabled by admins.
It also fixes a couple small issues, 2 of them in status-go.
Known issues:
- It's very small, but the context menu doesn't look very good. That's because I had to temper with the QMl myself and there is no design or component right now for just emojis. Let me know if I'm wrong. Otherwise, it can be fixed in another issue/PR
[reactions.webm](https://github.com/status-im/status-desktop/assets/11926403/6a7ea6cc-f063-4a1e-a171-3193bac9c5fd)
> feat: hook reactions in read only channel and fix issues

- ui/app/AppLayouts/Communities/stores/CommunitiesStore.qml
- ui/imports/utils/Constants.qml
- ui/imports/utils/Utils.qml
Closing: https://github.com/status-im/status-desktop/issues/13434
Validate the display name against the joined community members.
Profile identity - Display name validation
> fix(DisplayNameValidation): Integrate duplicate display name in joined communities

- storybook/pages/StatusMessagePage.qml
- ui/StatusQ/include/StatusQ/statussyntaxhighlighter.h
- ui/StatusQ/src/StatusQ/Components/private/statusMessage/StatusTextMessage.qml
- ui/StatusQ/src/statussyntaxhighlighter.cpp
Closes: #12266 
The root cause of this issue is that the `TextEdit.text` is replaced on hover to add specific styling for the hovered state. As a result the selection is dropped.
To fix this I've moved the highlighted hyperlink style to the StatusSyntaxHighlighter.
Changes:
1. Add feature flags to the StatusSyntaxHighlighter to allow picking specific highlighting features
2. Move the StatusTextMessage hovered hyperlink styling from rich text formatting to StatusSyntaxHighlighter
3. Fix StatusSyntaxHighlighter hyperlink regex to allow visible punctuation characters at the end of the link
4. Update storybook page
StatusSyntaxHighlighter
StatusTextMessage
https://github.com/status-im/status-desktop/assets/47811206/6900e67a-1ebc-4cdd-8166-f01e14328a9a
> fix(StatusTextMessage): Allow user to copy parts of a message containing URLs

- ui/app/AppLayouts/Chat/panels/UserListPanel.qml
Related to https://github.com/status-im/status-desktop/issues/13354
As @caybro proposed here: https://github.com/status-im/status-desktop/issues/12363#issuecomment-1873850368, I replaced `ExpressionRole` with `FastExpressionRole`, it helped.
As noted in comments, this doesn't fix the issue. But should be there anyway.
https://github.com/status-im/status-desktop/pull/13299#discussion_r1467794778
> fix(UserListPanel): use `FastExpressionRole`

- ui/StatusQ/src/StatusQ/Components/StatusChatList.qml
- ui/StatusQ/src/StatusQ/Components/StatusChatListCategoryItem.qml
Fixes https://github.com/status-im/status-desktop/issues/13959
Fixed the styling of community category. This now considers:
- `muted`
- `hadUnreadMessages`
- `highlighted`
Which follows the same logic as for channels.
https://github.com/status-im/status-desktop/assets/25482501/c7eb7c56-75d6-45f5-89b3-92f00d7f2c58
> fix: category item style

- ui/app/AppLayouts/Profile/views/MyProfileView.qml
- ui/imports/shared/popups/ProfileDialog.qml
- ui/imports/shared/views/ProfileDialogView.qml
- ui/imports/shared/views/profile/ProfileShowcaseView.qml
Closes: #13949 
Adding live preview support in the profile view.
Changes:
1. Propagate the dirty models from the profile showcase to the profile view
2. Adding live preview support in the ProfileShowcaseView. We're swapping the models when the live preview is active
3. Adapt the community model to support `membersCount` role needed in the `ProfileShowcaseView `
Profile view
https://github.com/status-im/status-desktop/assets/47811206/19906cde-fb2f-42b4-a777-f590638c48a6
https://github.com/status-im/status-desktop/assets/47811206/d08908be-361b-4a7f-b384-e5a2e5e21efb
> fix(ProfileShowcase): Add live preview support in the profile view

- storybook/pages/ChangePasswordViewPage.qml
- ui/app/AppLayouts/Profile/views/ChangePasswordView.qml
- ui/imports/shared/views/PasswordView.qml
Required changes:
- Fixed text colors
- Fixed text expressions
- Added dividers
- Added labels
| Design | Implementation |
| - | - |
| ![image](https://github.com/status-im/status-desktop/assets/47554641/50ab88cb-7623-4ab1-8b2c-a12f54ec4429) | ![image](https://github.com/status-im/status-desktop/assets/47554641/3b94b261-1e5f-4a19-b2e0-a0aa69f73b10) |
> fix(settings) align password screen with design

- ui/app/AppLayouts/Profile/popups/ConfirmChangePasswordModal.qml
The extra space was not needed given that modal has a padding of 16 already
| Design | Implementation |
|-|-|
| ![image](https://github.com/status-im/status-desktop/assets/47554641/b91e20b8-6d80-4f0c-83dc-99ea4d433ab3) | ![image](https://github.com/status-im/status-desktop/assets/47554641/c26d7725-8ed3-41ae-96cf-3880586cb21f) |
> fix(settings) fix popup spacing for change password modal

- src/app_service/service/community/service.nim
Unexpected exception (from findOwner() function) broke handleCommunityUpdates.
Exception was raised, because previous community did not have a member list (there was join permission).
Fix #13958
https://github.com/status-im/status-desktop/assets/61889657/78b92c63-d38d-43fb-ae51-46b62fead903
> fix(@desktop/communities): Fix joining community

- src/app/modules/main/communities/module.nim
- src/app/modules/shared_models/token_list_model.nim
Before adding a new token we check if it is already in the model.
Fix #13993
> fix(@desktop/permissions): Fix multiple tokens on tokens list

- src/app/modules/main/chat_section/chat_content/chat_details.nim
- src/app/modules/main/chat_section/chat_content/module.nim
- src/app/modules/main/chat_section/chat_content/view.nim
- src/app/modules/main/chat_section/controller.nim
- src/app/modules/main/chat_section/io_interface.nim
- src/app/modules/main/chat_section/item.nim
- src/app/modules/main/chat_section/model.nim
- src/app/modules/main/chat_section/module.nim
- src/app/modules/main/chat_section/view.nim
- src/app_service/service/chat/dto/chat.nim
- src/app_service/service/community/service.nim
- src/backend/communities.nim
- ui/StatusQ/src/StatusQ/Components/StatusChatListAndCategories.qml
- ui/app/AppLayouts/Chat/stores/RootStore.qml
- ui/app/AppLayouts/Chat/views/ChatHeaderContentView.qml
- ui/app/AppLayouts/Chat/views/ChatView.qml
- ui/app/AppLayouts/Communities/popups/CreateChannelPopup.qml
- ui/app/AppLayouts/Communities/views/CommunityColumnView.qml
- ui/imports/shared/views/chat/ChatContextMenuView.qml
Extend chats model with channel permissions info and hideIfPermissionsNotMet.
Visibility of chat item is based on: member roles, channel permissions, hideIfPermissionsNotMet.
If all channels from category are hidden, category item is also hidden.
If all channels in community are hidden, information label is displayed.
Related status-go [pr](https://github.com/status-im/status-go/pull/4884)
Issue #13291 
https://github.com/status-im/status-desktop/assets/61889657/6cc6ada3-f811-45a9-b252-13bf91171033
> 13291 hide channels

- src/app/modules/main/chat_section/module.nim
Fixes #9147
when handling SIGNAL_CHAT_LEFT and SIGNAL_COMMUNITY_CHANNEL_DELETED signals
the currently active chat will be kept as active if another chat has been deleted
chat_section
no UI changes
https://github.com/status-im/status-desktop/assets/1083341/0e300696-5b35-41df-9f93-3ef0df1f53c1
> fix(chat_section): fix changing active chat on leaving another group chat

- ui/app/AppLayouts/Profile/views/WalletView.qml
- we _always_ want to save the changes, it's the toasts that we don't want to see when looking at the Advanced tab
Fixes #14016
[Záznam obrazovky z 2024-03-18 19-01-24.webm](https://github.com/status-im/status-desktop/assets/5377645/e9d3086f-c714-4295-88c0-a8ee4603964f)
> fix(WalletView): `Apply to my wallet` doesn't save or apply the order

- ui/app/AppLayouts/Communities/panels/PermissionsSettingsPanel.qml
- ui/app/AppLayouts/Communities/views/EditPermissionView.qml
- distinguish between `permissionTypeLimitReached` and the new `permissionTypeLimitExceeded`
- the latter is used to enable/disable the "Save" button when editting the permissions as we're not going to add a new one (going over the limit), and to also hide the warning texts
Fixes #13989
PermissionsSettingsPanel
[Záznam obrazovky z 2024-03-18 18-32-49.webm](https://github.com/status-im/status-desktop/assets/5377645/3990511d-9e8e-4a04-9183-9a5509e630b8)
> fix(permissions): Unable to Confirm Changes to Existing Community Permission

- storybook/pages/ChangePasswordViewPage.qml
- ui/app/AppLayouts/Profile/views/ChangePasswordView.qml
Add notification to biometrics enable
Also fix biometrics toggle button and popup dismissal for change password screen
| | Design | Implementation |
|-|-|-|
| Disabled | ![image](https://github.com/status-im/status-desktop/assets/47554641/f0af6e9e-f819-4444-bf65-864648881e91) | ![image](https://github.com/status-im/status-desktop/assets/47554641/1630bfdf-8034-49f6-95c3-0e70af776a2a) |
| Enabled | ![image](https://github.com/status-im/status-desktop/assets/47554641/461b3400-7207-46cb-a82a-d6868939d2ec) | ![image](https://github.com/status-im/status-desktop/assets/47554641/daf95971-c38c-486e-bc30-0dd9f987dd70) |
> feat(wallet): add notification to biometrics enable

- ui/app/AppLayouts/Profile/panels/ProfileShowcasePanel.qml
Fixes #13693 
Add a rectangle wrapper to ShapeRectangle to fill the dash border area as well.
> fix(ProfileShowcase|): Change stroke position from the outside to inside of the drop area

- storybook/qmlTests/tests/tst_ManageCollectiblesPanel.qml
- storybook/src/Models/ManageCollectiblesModel.qml
- ui/StatusQ/CMakeLists.txt
- ui/StatusQ/src/wallet/managetokenscontroller.cpp
- ui/StatusQ/src/wallet/managetokenscontroller.h
- ui/StatusQ/src/wallet/managetokensmodel.cpp
- ui/StatusQ/src/wallet/managetokensmodel.h
- ui/app/AppLayouts/Profile/views/WalletView.qml
- ui/app/AppLayouts/Wallet/controls/ManageTokensGroupDelegate.qml
- ui/imports/shared/controls/FoldableHeader.qml
- ui/imports/shared/popups/CommunityAssetsInfoPopup.qml
- keep track of the grouped item kind (community vs. collection)
- when the "arrange by" mode is active, use it for sorting the tokens in the main wallet view
- change the behavior to always sort by the number of tokens inside the group when entering the grouped (arrange by...) mode + add tests
- remove unused code dealing with handling of community IDs
- separate commits to fix some smaller UI issues in the group delegate
Fixes #13276
ManageTokensController,ManageTokensGroupDelegate
> fix(TokenManagement): Fix sorting grouped positions

- Makefile
- src/app/modules/shared_modules/keycard_popup/controller.nim
As @arnetheduck recommended, I upgraded `nimbus-build-sytem` to the one that uses latest `Nim 1.6.18`.
This is to try to make `--warningAsError:UnusedImport:on` work.
> upgrade Nim-build-system

- storybook/pages/CommunitiesViewPage.qml
- ui/app/AppLayouts/Profile/ProfileLayout.qml
- ui/app/AppLayouts/Profile/stores/ProfileStore.qml
- ui/app/AppLayouts/Profile/views/CommunitiesView.qml
- ui/app/AppLayouts/Profile/views/MyProfileView.qml
- ui/app/mainui/AppMain.qml
- ui/app/mainui/ToastsManager.qml
- ui/imports/shared/popups/SettingsDirtyToastMessage.qml
- ui/imports/shared/stores/CurrenciesStore.qml
Closes #13950
- Added loading state in dirty toast message.
- Added store connections in `MyProfileView` and save loading logic.
- Added toasts notifications.
- `ProfileSectionStore` only instanciated once
- `SettingsDirtyToastMessage` extended with additional information in bottom needed for task [#13997](https://github.com/status-im/status-desktop/issues/13997)
- Added some needed properties for task [#13997](https://github.com/status-im/status-desktop/issues/13997)
**Profile Showcase** settings and `SettingsDirtyToastMessage`
- **Scenario 1**: Success changing both identity and preferences alone and / or together
https://github.com/status-im/status-desktop/assets/97019400/6d45a762-f08e-4d03-aeeb-dda517fd2587
- **Scenario 2**: Forcing backend failure by sending multiple times same …
> feat(ProfileShowcase): Align UI save flow according to backend response

- ui/app/AppLayouts/Wallet/stores/RootStore.qml
- ui/app/AppLayouts/Wallet/views/collectibles/CollectibleDetailView.qml
fix(@desktop/wallet): Fix link out to blockchain explorer from collectibles details view
Fixes the url to link out to a blockchain explorer from the collectible detailsview
CollectibleDetailsView
Mainnet linkout
https://github.com/status-im/status-desktop/assets/60327365/9e6925c3-1690-4e2d-8d4f-5a3facd181d9
Testnet linkout
https://github.com/status-im/status-desktop/assets/60327365/c070935e-d03e-473b-8e75-94b53b95d7ac
> fix(@desktop/wallet): Fix link out to blockchain explorer from collectibles details view

- Makefile
- config.nims
- src/app/modules/shared_modules/keycard_popup/controller.nim
1. Added a workaround to make `--warningAsError` work.
Context: https://github.com/nim-lang/Nim/issues/23429
2. Moved config parameters to `config.nims` 
3. Removed some unused imports.
> chore: force some warnings as errors

- src/app/modules/main/chat_section/chat_content/messages/controller.nim
- src/app/modules/main/chat_section/module.nim
- src/app/modules/main/controller.nim
- src/app/modules/main/io_interface.nim
- src/app/modules/main/module.nim
During clicking on AC mention message
- open section
- open chat
- scroll and highlight the message
Closes: https://github.com/status-im/status-desktop/issues/14063
- selecting the section
- storing the last visited section
- opening the necessary chat and scrolling to the message
> (CHERRY-PICK) fix: open activity center mentions messages (#14075)

- ui/app/AppLayouts/Wallet/views/RightTabView.qml
- ui/imports/shared/views/AssetsView.qml
Add object names for wallet right tab view
ui/app/AppLayouts/Wallet/views/RightTabView.qml
ui/imports/shared/views/AssetsView.qml
> chore: object names added for wallet right tab buttons and filter button

- src/app/modules/main/wallet_section/all_tokens/view.nim
- storybook/pages/AssetsViewPage.qml
- storybook/src/Models/GroupedAccountsAssetsModel.qml
- storybook/stubs/AppLayouts/Wallet/stores/TokensStore.qml
- ui/app/AppLayouts/Profile/views/wallet/ManageTokensView.qml
- ui/app/AppLayouts/Wallet/views/RightTabView.qml
- ui/imports/shared/stores/send/TransactionStore.qml
- ui/imports/shared/views/AssetsView.qml
- take the balance threshold value into account when presenting the assets in the main wallet view
- additional fix from Emil for storing the threshold value
- storybook fixes to display the correct `currentCurrencyBalance` values based on the address/wallet filters and mocking the threshold values using TransactionStore
Needs: https://github.com/status-im/status-go/pull/4960
Fixes: #14017
AssetsView
[Záznam obrazovky z 2024-03-20 17-14-58.webm](https://github.com/status-im/status-desktop/assets/5377645/802d016e-4981-421a-9c1e-4871889137a4)
> fix(TokenManagement): Asset balance threshold value not reflected in main wallet view

- storybook/stubs/nim/sectionmocks/WalletSectionAccounts.qml
- ui/app/AppLayouts/Wallet/panels/ActivityFilterPanel.qml
- ui/app/AppLayouts/Wallet/popups/filterSubMenus/ActivityCounterpartyFilterSubMenu.qml
- ui/app/AppLayouts/Wallet/stores/RootStore.qml
- ui/app/AppLayouts/Wallet/views/RightTabView.qml
- ui/app/AppLayouts/Wallet/views/TransactionDetailView.qml
Refresh recipients in menu for activity filter
Also
- fix namespace clash in wallet RootStore
- lazy load `TransactionDetailView`
- wrong properties referenced in `TransactionDetailView`
> Fix saved addresses in activity 13663

- ui/imports/utils/Constants.qml
- do not use the `alphanumericalExpanded: /^$|^[a-zA-Z0-9\-_\.\u0020]+$/` regex which contains the dot (`.`) character too; be explicit here and do what the error message says
- the space character at start/end is validated above with the `startsWithSpaceValidator`
CHERRY-PICK-TO: 2.28
Fixes #14127
Display name validation
[Záznam obrazovky z 2024-03-25 14-08-04.webm](https://github.com/status-im/status-desktop/assets/5377645/d103ba4d-4d69-4fa6-892f-4f8e8248732a)
> fix: Display name is not validated properly (UI part)

- ui/imports/utils/Constants.qml
Cherry-pick of https://github.com/status-im/status-desktop/pull/14142
- do not use the `alphanumericalExpanded: /^$|^[a-zA-Z0-9\-_\.\u0020]+$/` regex which contains the dot (`.`) character too; be explicit here and do what the error message says
- the space character at start/end is validated above with the `startsWithSpaceValidator`
Fixes #14127
> cherry-pick fix: Display name is not validated properly (UI part)

- src/app/modules/main/wallet_section/activity/controller.nim
- src/app/modules/main/wallet_section/activity/events_handler.nim
- src/app/modules/main/wallet_section/activity/status.nim
> fix(wallet): counterparty loading forever in activity history

- src/app/modules/main/module.nim
Fixes #14111
The problem was that the init code shows the loader when the last section was the profile, expecting that when sections load, the personal chat would be activated, but the code that displays the section didn't catch the ball.
> fix(main): set personnal chat as active if last active was profile

- src/app/modules/main/module.nim
Fixes #14111
Cherry-pick of https://github.com/status-im/status-desktop/pull/14155
> [CHERRY-PICK] fix(main): set personnal chat as active if last active was profile

- storybook/pages/JoinCommunityViewPage.qml
- storybook/pages/JoinPermissionsOverlayPanelPage.qml
- ui/app/AppLayouts/Chat/ChatLayout.qml
- ui/app/AppLayouts/Chat/views/ChatView.qml
- ui/app/AppLayouts/Communities/panels/JoinCommunityCenterPanel.qml
- ui/app/AppLayouts/Communities/panels/JoinPermissionsOverlayPanel.qml
- ui/app/AppLayouts/Communities/views/JoinCommunityView.qml
Closes #14098
- Change text and remove existing icon.
- Removed unnecessary property `loginType` on different files.
- Renamed signals to be more accurate with existing requirements.
Join Community flow
> fix(JoinCommunity): Join CTA labelling: Change text and remove existing icon

- ci/Jenkinsfile.combined
- ci/Jenkinsfile.linux
- ci/Jenkinsfile.macos
- ci/Jenkinsfile.tests-nim
- ci/Jenkinsfile.tests-ui
- ci/Jenkinsfile.windows
- ci/cpp/Jenkinsfile.linux
- ci/cpp/Jenkinsfile.macos
- ci/cpp/Jenkinsfile.windows
Had to be changed to `PLATFORM` due to conflict of `TARGET` with our Nix shell setup in `status-mobile` and `status-go`.
> chore(ci): bump jenkins lib and rename TARGET

- ui/app/AppLayouts/Wallet/views/TransactionDetailView.qml
Cherry picked from https://github.com/status-im/status-desktop/pull/14069
Fixes wrong properties referenced in `TransactionDetailView`
> fix(wallet): activity details missing - 2.28.x

- src/app/modules/main/wallet_section/all_collectibles/controller.nim
- src/app/modules/main/wallet_section/all_collectibles/view.nim
- src/app_service/service/collectible/service.nim
- src/backend/collectibles_types.nim
- storybook/pages/AssetsViewPage.qml
- storybook/pages/CollectiblesViewPage.qml
- storybook/pages/ManageAssetsPanelPage.qml
- storybook/pages/ManageCollectiblesPanelPage.qml
- storybook/pages/ManageHiddenPanelPage.qml
- storybook/qmlTests/tests/tst_ManageCollectiblesPanel.qml
- ui/StatusQ/CMakeLists.txt
- ui/StatusQ/src/wallet/managetokenscontroller.cpp
- ui/StatusQ/src/wallet/managetokenscontroller.h
- ui/StatusQ/src/wallet/managetokensmodel.cpp
- ui/StatusQ/src/wallet/managetokensmodel.h
- ui/StatusQ/src/wallet/tokendata.cpp
- ui/StatusQ/src/wallet/tokendata.h
- ui/app/AppLayouts/Wallet/panels/ManageAssetsPanel.qml
- ui/app/AppLayouts/Wallet/panels/ManageCollectiblesPanel.qml
- ui/app/AppLayouts/Wallet/panels/ManageHiddenPanel.qml
- ui/app/AppLayouts/Wallet/stores/CollectiblesStore.qml
- ui/app/AppLayouts/Wallet/stores/WalletAssetsStore.qml
Add a separation layer for save/load/clear to `ManageTokensModel` so that we can save/load from external sources.
The separate layer is composed of JSON as protocol, a set of signals and slots for interface. The implementation forwards data to current `QSettings` for storybook and nim controllers for the app.
Groups are not handled in this PR
Note: I auto formatted some C++ files by mistake using vscode, please use ignore spaces in diff for easier review :(
> feat(wallet) save/load collectibles user handled state in DB

- ui/app/AppLayouts/Chat/ChatLayout.qml
- ui/imports/shared/popups/CommunityMembershipSetupDialog.qml
Closes #14097
- Added dialog instead of calling directly to the cancel method.
- Updated `Cancel` button format according to figma in `CommunityMembershipSetupDialog`.
Join Community flow
https://github.com/status-im/status-desktop/assets/97019400/06bf8b22-434f-4b26-86aa-065adb871a25
> fix(CancelCommunityMembership): Added popup instead of directly cancelling request

- src/app/modules/shared_modules/keycard_popup/controller.nim
- src/app/modules/shared_modules/keycard_popup/module.nim
- ui/app/AppLayouts/Profile/ProfileLayout.qml
Don't know why that line was added, but seems it was a main culprit for this issue, the point is to have biometrics signals connected when needed only:
https://github.com/status-im/status-desktop/pull/13793/files
Closes #14173
> fix(general): when biometric is setup the authentication flow is not correct showing the password one instead

- ui/imports/shared/popups/CommunityMembershipSetupDialog.qml
It's a single line change since `values()` on the map returns an iterator, and since I changed that line based on review comments in my previous PR it got broken. Fixed now.
Closes #14175
> fix(communities): when only keycard accounts selected (and 1 keycard) authentication is not triggered

- src/app/modules/main/communities/io_interface.nim
- src/app/modules/main/communities/module.nim
- src/app/modules/main/communities/view.nim
- ui/StatusQ/src/StatusQ/Popups/Dialog/StatusDialog.qml
- ui/app/AppLayouts/Chat/ChatLayout.qml
- ui/app/AppLayouts/Chat/stores/RootStore.qml
- ui/app/AppLayouts/Communities/views/CommunityColumnView.qml
- ui/app/AppLayouts/Profile/views/CommunitiesView.qml
- ui/app/AppLayouts/stores/RootStore.qml
- ui/app/mainui/Popups.qml
- ui/imports/shared/popups/CommunityMembershipSetupDialog.qml
A fix for this issue was in the line `726` in `module.nim`, but I also made a change to make sure that all sensitive data kept in the memory while the popup is active gets cleared on the popup close.
Closes #14174
> fix(communities): keycard authentication marked automatically as authenticated

- ui/imports/shared/popups/CommunityMembershipSetupDialog.qml
> fix(communities): join community button text instead of share all addresses to join text in membership setup dialog

- src/app/modules/shared_modules/collectibles/controller.nim
Only use relevant (i.e. contained in the current filter) chains and addresses to determine the Collectible Model's state.
> fix(@wallet): prevent collectibles error due to irrelevant chain state

- src/app/modules/main/chat_section/module.nim
- storybook/pages/JoinCommunityPermissionsEditor.qml
- storybook/src/Models/PermissionsModel.qml
- ui/app/AppLayouts/Chat/stores/RootStore.qml
- ui/app/AppLayouts/Chat/views/ChatView.qml
- ui/app/AppLayouts/Communities/panels/JoinCommunityCenterPanel.qml
- ui/app/AppLayouts/Communities/panels/JoinPermissionsOverlayPanel.qml
- ui/imports/shared/stores/PermissionsStore.qml
Fixes
- crash fix
- set correct permission required UI during joining the closed community
- if community permission is closed and the user owns TM or admin token - show this token in the join community permission view
- if all channels are hidden, show the "You don't hold the necessary tokens" UI only if the community is not closed and we fit the permissions to join the community
- do not show join community permission view if it is open community
Closes: 
- https://github.com/status-im/status-desktop/issues/14091
- https://github.com/status-im/status-desktop/issues/14085
- https://github.com/status-im/status-desktop/issues/14104
IMPACT:
- join community permission view for a member, who wants to join
- showing community channels permission
> fix: set correct permision required UI during joining the community

- ui/app/AppLayouts/Profile/popups/ConfirmChangePasswordModal.qml
- ui/imports/shared/popups/keycard/states/CreatePassword.qml
- ui/imports/shared/views/PasswordView.qml
- hide the "Current password" label when creating a new password
- fix margins inside the keycard popup
- some minor UI fixups according to Figma
Fixes: #14214
Fixes: #14177
PasswordView
> fix[Onboarding] Password screen is not correct

- ui/app/AppLayouts/Profile/helpers/ProfileShowcaseModelAdapter.qml
- ui/imports/shared/views/profile/ProfileShowcaseView.qml
Profile showcase for a contact just got broken after conflict resolution. This is fixing showcase for a contact and removing unwanted log
> fix(PRofileShowcase): Fixing conflict merge error

- storybook/pages/CommunityMembershipSetupDialogPage.qml
- storybook/pages/SharedAddressesAccountSelectorPage.qml
- storybook/src/Models/GroupedAccountsAssetsModel.qml
- storybook/src/Storybook/GenericListView.qml
- ui/StatusQ/include/StatusQ/permissionutilsinternal.h
- ui/StatusQ/src/StatusQ/Components/StatusListItem.qml
- ui/StatusQ/src/permissionutilsinternal.cpp
- ui/app/AppLayouts/Communities/helpers/PermissionsHelpers.qml
- ui/app/AppLayouts/Communities/panels/SharedAddressesAccountSelector.qml
- ui/app/AppLayouts/Communities/panels/SharedAddressesPanel.qml
- ui/app/AppLayouts/Communities/panels/qmldir
- ui/app/mainui/Popups.qml
- ui/imports/shared/popups/CommunityMembershipSetupDialog.qml
Implements displaying collectibles within account delegate in sharing addresses flow.
- collectibles used in permissions are displayed in account delegate with proper balance (presented as integer, no decimal separator)
- assets and collectibles are sorted together alphabetically
- assets and collectibles with 0 balance in given account are filtered out
What's not covered in this PR:
- assets and collectibles used in hidden, but fulfilled permissions are not presented
This is fast, pre-refactor implementation, indended to be 
Fixes https://github.com/status-im/status-desktop/issues/14102
`SharedAddressesAccountSelector`
> feat(SharedAddressesAccountSelector): Support for collectibles in account's delegate tags

- src/app/modules/main/communities/module.nim
- src/app/modules/shared_models/token_list_item.nim
- src/app/modules/shared_models/token_list_model.nim
- ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml
fixes #13561
1. Add `privilegesLevel` role to token_list_model.nim
2. Communities/module.nim - moved duplicate code to buildCommunityTokenItemFallback
3. CommunitySettingsView.qml - filter out collectibles with TokenPrivilegesLevel.Owner
Community - Permissions - HoldingsDropdown
https://github.com/status-im/status-desktop/assets/1083341/82129351-d2f7-4052-8bce-4ee135cf5804
If we always show community-minted tokens, it may be sufficient to filter the `communityTokens` model (a similar approach is used for `AirdropsSettingsPanel)
```
Loader {
id: collectiblesModelLoader
active: airdropPanel.communityTokens
sourceComponent: SortFilterProxyModel {
sourceModel: airdropPanel.communityTokens
filters: [
ValueFilter {
roleName: "tokenType"
value: Constants.TokenType.ERC721
},
ExpressionFilter { …
```
> fix(Permissions): tokenOwner is present in the list of collectibles when adding a permission

- ui/app/AppLayouts/Profile/helpers/ProfileShowcaseSettingsModelAdapter.qml
Closes #14231 
Filter the communities the user hasn't joined.
https://github.com/status-im/status-desktop/assets/47811206/79d0397a-f111-463f-8d01-295d17c71614
> fix(ProfileShowcase): Filter out communities the user hasn't joined from

- ui/app/AppLayouts/Communities/panels/SharedAddressesAccountSelector.qml
- ui/app/AppLayouts/Communities/panels/SharedAddressesPanel.qml
- ui/app/AppLayouts/Communities/panels/SharedAddressesPermissionsPanel.qml
- ui/app/AppLayouts/stores/RootStore.qml
- ui/imports/shared/popups/CommunityMembershipSetupDialog.qml
- implement sorting of the wallet accounts by the number of tokens (aka tags) and then by alphabet
- due to the delegate complexity here and usage of nested models, keep track of the tags count separately and outside of the model
- this will be improved later on as part of the complete sort/order design described in https://github.com/status-im/status-desktop/issues/14192
Fixes https://github.com/status-im/status-desktop/issues/14101
SharedAddressesAccountSelector, SharedAddressesPanel
> feat(SharedAddressesAccountSelector): update wallet account sorting

- src/app/modules/main/wallet_section/send/module.nim
- src/app/modules/shared_models/collectible_ownership_model.nim
- src/app/modules/shared_models/collectibles_entry.nim
- src/app/modules/shared_models/collectibles_model.nim
- src/app/modules/shared_models/collectibles_nested_item.nim
- src/app/modules/shared_models/collectibles_nested_model.nim
- src/app/modules/shared_models/collectibles_nested_utils.nim
- ui/imports/shared/popups/send/SendModal.qml
- ui/imports/shared/popups/send/controls/CollectibleNestedDelegate.qml
- ui/imports/shared/popups/send/controls/TokenBalancePerChainDelegate.qml
- ui/imports/shared/popups/send/panels/HoldingSelector.qml
- ui/imports/shared/popups/send/views/TokenListView.qml
- ui/imports/shared/stores/send/TransactionStore.qml
- ui/imports/utils/Constants.qml
Fixes #14080
Community collectibles were not properly handled in the Send modal, showing a group of 0 elements instead and not allowing to select them for sending. This PR fixes that. 
There was a small rework in preparation for future tasks. Some other minor issues are also fixed and support for ERC1155 balance display is introduced.
https://github.com/status-im/status-desktop/assets/11161531/98ae94a4-8336-4bf0-8454-2756ddaeefd4
> fix(@desktop/wallet): properly handle collectible groups in send modal

- ui/imports/shared/popups/send/controls/TokenBalancePerChainDelegate.qml
- ui/imports/shared/popups/send/panels/HoldingSelector.qml
In case of assets the symbol doesn't have an icon representation in resources, hence we use the image of the asset itself. Same fix was applied for header and delegates
> fix(SendModal) missing icons for assets in Send Modal

- src/app_service/service/transaction/service.nim
The contract address is not resolved for the community tokens because of symbol usage which is not resolved by `getTokenBySymbolByTokensKey`.
This change switched to always using `tokensKey` to identify the token for all non-native transfers. Basically the `transferToken` always requires token which guarantees a valid token address.
Also remove token lookup redundant code.
> fix(wallet) sending community tokens doesn't work

- src/app/modules/main/profile_section/contacts/controller.nim
- src/app/modules/main/profile_section/contacts/module.nim
- src/app_service/common/utils.nim
Close #14243
Fix crash when a profile collectible had a chainId from disabled network e.g main net chain id when test net is enabled
Profile
> fix(Profile): Fix crashing when showcase collectible having disabled chainIds

- config.nims
- src/app/modules/shared_modules/keycard_popup/controller.nim
- src/app_service/service/chat/dto/chat.nim
Fixed this warning:
```bash
/src/app_service/service/chat/dto/chat.nim(302, 33) Warning: conversion to enum with holes is unsafe: ChatType(chatTypeInt) [HoleEnumConv]
```
The simplest fix here is to fill the hole in the `ChatType` enum. Value `5` corresponds to `Timeline` chat type, which is deprecated:
https://github.com/status-im/status-go/blob/8bf03609fc0f76eb8488869db1a7c22c68408c01/protocol/chat.go#L43-L45
1. Added `Timeline` with `{.deprecated.}` pragma
2. Marked `[Deprecated]` warning as error. You'll get this if you try to use it:
```bash
/src/app_service/service/chat/dto/chat.nim(310, 19) Error: Timeline is deprecated [Deprecated]
```
3. Marked `[HoleEnumConv]` warning as error.
Fixed this warning:
```bash
src/app/modules/shared_modules/keycard_popup/controller.nim(653, 21) …
```
> chore: fill holes in ChatType enum

- src/app_service/service/contacts/dto/contacts.nim
fixes #13772
There are several approaches to displaying the "verified" icon for a contact:
- ProfileContexatMenu.qml, ProfileDialogView.qml - it checks whether the outgoingVerificationStatus, incomingVerificationStatus, or trustedStatus is "trusted"
- StatusMemberListItem.qml - only used the usersModule.model.isVerified field (which is the same as outgoingVerificationStatus)
1. Adds `trustStatus` to `ChatContentModule.usersModule.model`
2. Fixes `isVerified` value passed to `StatusMemberListItem` 
usersModule.model
https://github.com/status-im/status-desktop/assets/1083341/dc80f85e-c7db-4409-bf55-aae6870e015f
Further improvements:
- I think it makes sense to move this logic to users/module.nim and leave only the `isVerified` field to be calculated with trustedStatus (and maybe …
> fix(Profile Flow): Marking as ID verified is not reflected in community member

- ui/app/AppLayouts/Communities/views/EditPermissionView.qml
Fixes https://github.com/status-im/status-desktop/issues/14006
As documented in big.js, `toString()` might return exponential form, which is not expected by our status-go backend.
The fix is to use `toFixed()`, which always returns normal form.
https://github.com/status-im/status-desktop/assets/25482501/3a86c8d9-6d67-41ca-910b-9aa808d40c2c
> fix: permissions with value>1000

- src/app_service/common/utils.nim
Fix https://github.com/status-im/status-desktop/pull/14252#pullrequestreview-1976999879
> Hotfix: fix compilation warning

- ui/imports/shared/popups/send/controls/TokenBalancePerChainDelegate.qml
- ui/imports/shared/popups/send/panels/HoldingSelector.qml
The previous attempt to control the order of delegate instantiation and avoid QML warnings didn't work for this case (Loader with injected properties). Therefore, I reverted to the last working version.
> fix(SendModal): fix not showing tokens in the holding selector

- src/app/modules/main/chat_section/module.nim
Fixes #14209
The fix is in status-go here https://github.com/status-im/status-go/pull/5000
The changes in this are just clean ups
> fix(permissions): fix view and post permission overwritten by view perm

- src/app/modules/main/profile_section/contacts/module.nim
- src/app/modules/main/profile_section/contacts/view.nim
- ui/app/AppLayouts/Profile/helpers/ProfileShowcaseModelAdapter.qml
- ui/app/AppLayouts/Profile/helpers/ProfileShowcaseSettingsModelAdapter.qml
- ui/app/AppLayouts/Profile/stores/ContactsStore.qml
- ui/app/AppLayouts/Profile/stores/ProfileSectionStore.qml
- ui/imports/shared/views/profile/ProfileShowcaseCommunitiesView.qml
Closes #14232
Adding loading state in community delegates when the showcase validation is in progress.
https://github.com/status-im/status-desktop/assets/47811206/59b36ad5-c5d3-45bf-8089-91e9e90443e0
> feat(ProfileShowcase): Add community showcase loading state

- src/app/modules/main/wallet_section/all_collectibles/view.nim
- src/app/modules/main/wallet_section/all_tokens/view.nim
- src/app_service/service/token/service.nim
- ui/StatusQ/src/StatusQ/Components/StatusRoundedImage.qml
- ui/StatusQ/src/wallet/managetokensmodel.cpp
- ui/StatusQ/src/wallet/tokendata.cpp
- ui/StatusQ/src/wallet/tokendata.h
- ui/app/AppLayouts/Profile/views/MyProfileView.qml
- ui/app/AppLayouts/Profile/views/WalletView.qml
- ui/app/AppLayouts/Wallet/stores/CollectiblesStore.qml
- ui/app/AppLayouts/Wallet/stores/TokensStore.qml
- ui/app/AppLayouts/Wallet/stores/WalletAssetsStore.qml
Use `updateTokenPreferences` and `getTokenPreferencesJson` to save assets instead of local `QSettings`
> feat(wallet) connect assets ordering with saving to DB backend

- ui/app/AppLayouts/Communities/views/CommunityColumnView.qml
- ui/app/AppLayouts/Profile/panels/CommunitiesListPanel.qml
- ui/app/mainui/AppMain.qml
- disallow changing the Shared addresses while our request to join community is still pending
Fixes https://github.com/status-im/status-desktop/issues/14292
AppMain, Settings/Communities
Main nav:
Settings/Communities:
> fix[Shared Addresses] Can't edit shared address while the join request is pending

- src/app/modules/main/chat_section/module.nim
Fixes https://github.com/status-im/status-desktop/issues/14369
> fix: proper content for bridged messages in OS notifications

- ci/Dockerfile
- ci/Jenkinsfile.combined
- ci/Jenkinsfile.linux
- ci/Jenkinsfile.macos
- ci/Jenkinsfile.tests-nim
- ci/Jenkinsfile.tests-ui
- ci/Jenkinsfile.windows
- ci/cpp/Jenkinsfile.linux
- ci/cpp/Jenkinsfile.macos
- ci/cpp/Jenkinsfile.windows
Otherwise it fails with:
```
performing a single-user installation of Nix...
directory /nix does not exist; creating it by running 'mkdir -m 0755 /nix && chown jenkins /nix' using sudo
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
/tmp/nix-binary-tarball-unpack.roliyEDk9X/unpack/nix-2.19.3-x86_64-linux/install: please manually run 'mkdir -m 0755 /nix && chown jenkins /nix' as root to create /nix
```
Related to:
* https://github.com/status-im/status-go/pull/4388
> feat(ci): add Nix 2.19.3 for status-go builds

- Makefile
Linux builds on desktop are stuck with:
```
/usr/bin/ld: .../libstatus.so: undefined reference to `pthread_mutexattr_init@GLIBC_2.34'
/usr/bin/ld: .../libstatus.so: undefined reference to `dlclose@GLIBC_2.34'
/usr/bin/ld: .../libstatus.so: undefined reference to `pthread_detach@GLIBC_2.34'
/usr/bin/ld: .../libstatus.so: undefined reference to `__isoc23_strtol@GLIBC_2.38'
```
Due to using old Glibc 2.34 from Ubuntu 22.04 while Nix uses 2.38.
> fix(status-go): skip Nix shell use to avoid Glibc errors

- ui/StatusQ/include/StatusQ/concatmodel.h
- ui/StatusQ/src/concatmodel.cpp
- ui/StatusQ/tests/CMakeLists.txt
- ui/StatusQ/tests/src/TestHelpers/testmodel.cpp
- ui/StatusQ/tests/src/TestHelpers/testmodel.h
- ui/StatusQ/tests/tst_ConcatModel.cpp
- ui/app/AppLayouts/Communities/panels/SharedAddressesAccountSelector.qml
- Add method to `TestModel` removing items an emiting `layoutChanged`
- Proper handling of source models layout change
Whenever source model emits `layoutAboutToBeChanged`/`layoutChanged`,
persisten model are updated appropriately, also scenario when items are
removed is covered.
- Extensive tests, including case with SFPM removing items in between `layoutAboutToBeChanged`/`layoutChanged` signals
- `SharedAddressesAccountSelector` - workaround removed, now source models are set directly to `ConcatModel`
- `SharedAddressesAccountSelector` - flow simplified by setting `type` role via `ConcatModel`
Closes: https://github.com/status-im/status-desktop/issues/14244
Closes: https://github.com/status-im/status-desktop/issues/14245
`TestModel`, `ConcatModel`, `SharedAddressesAccountSelector`
> StatusQ(ConcatModel): Proper handling of source models' layout changes

- storybook/pages/ManageAssetsPanelPage.qml
- storybook/pages/ManageCollectiblesPanelPage.qml
- storybook/qmlTests/tests/tst_ManageCollectiblesPanel.qml
- ui/app/AppLayouts/Profile/views/WalletView.qml
- ui/app/AppLayouts/Profile/views/wallet/ManageTokensView.qml
- ui/app/AppLayouts/Wallet/panels/ManageAssetsPanel.qml
- ui/app/AppLayouts/Wallet/panels/ManageCollectiblesPanel.qml
Add a specific state to the saveSettings action to update the model by reloading the data.
The previous implementation was using the same `saveChanges` API which doesn't refresh the model. There must have been a side effect that made it work.
> fix(wallet): update wallet assets and collectibles order on user action

- storybook/pages/AssetsViewPage.qml
- storybook/pages/CollectiblesViewPage.qml
- storybook/pages/ManageAssetsPanelPage.qml
- storybook/pages/ManageCollectiblesPanelPage.qml
- storybook/pages/ManageHiddenPanelPage.qml
- storybook/qmlTests/tests/tst_ManageCollectiblesPanel.qml
- ui/StatusQ/src/wallet/managetokenscontroller.cpp
- ui/StatusQ/src/wallet/managetokenscontroller.h
Removed loading hidden groups from local settings and instead reload them from the externally loaded settings.
Also move the local saving code from the controller to external, therefore now it is implemented in storybook
> fix(wallet): hidden groups are still loading from user local settings

- ui/StatusQ/src/StatusQ/Components/StatusSmartIdenticon.qml
- ui/StatusQ/src/wallet/managetokenscontroller.cpp
- ui/StatusQ/src/wallet/managetokenscontroller.h
- ui/app/AppLayouts/Wallet/controls/ManageTokensCommunityTag.qml
The "settings exist" done via `ManageTokensController::hasSettings()` was using the global store, hence not working user based. Therefore, after an onboarding the previous user's settings presence was taken into account.
The fix now uses the order data that is loaded externally per user.
`HEAD~1` also  fixes an annoying warning that was distracting from debugging
> fix(token-order): global has settings check that introduced side effects

- src/app/modules/main/chat_section/module.nim
Fixes #14025
[unread-badge.webm](https://github.com/status-im/status-desktop/assets/11926403/2cfbd367-492e-4ad1-8c36-24ce8cd639e5)
> fix(chat_section): fix parent badge not updating on chat close and open

- ui/app/AppLayouts/Communities/controls/CommunityEligibilityTag.qml
- ui/app/AppLayouts/Communities/controls/PermissionTypes.qml
- ui/app/AppLayouts/Communities/panels/SharedAddressesAccountSelector.qml
- ui/app/AppLayouts/Communities/panels/SharedAddressesPanel.qml
- ui/app/AppLayouts/Communities/panels/SharedAddressesPermissionsPanel.qml
- ui/imports/shared/popups/CommunityMembershipSetupDialog.qml
- previously, we'd display the bubble only when joining the community
- now we display it also when editing the shared addresses, with a slightly different wording (eg. "You're an admin" -> "You'll be a member"), hinting the user about the future change
- remove the usage of `ModuleWarning` as we don't want its delay or transitions here, replace it with a regular red `Rectangle` + text
Fixes #13397
Edit Shared Addresses
Initial state with default accounts:
The "crucial" account unchecked:
> feat(SharedAddresses): display the eligibility bubble in edit mode too

- src/app/modules/main/chat_section/controller.nim
- src/app/modules/main/chat_section/io_interface.nim
- src/app/modules/main/chat_section/module.nim
- src/app/modules/main/chat_section/view.nim
- src/app/modules/main/communities/io_interface.nim
- src/app_service/service/chat/dto/chat.nim
- src/app_service/service/community/async_tasks.nim
- src/app_service/service/community/dto/community.nim
- src/app_service/service/community/service.nim
- src/backend/communities.nim
- ui/StatusQ/src/StatusQ/Components/StatusChatList.qml
- ui/StatusQ/src/StatusQ/Components/StatusChatListAndCategories.qml
- ui/app/AppLayouts/Chat/stores/RootStore.qml
- ui/app/AppLayouts/Communities/views/CommunityColumnView.qml
This previous PR https://github.com/status-im/status-go/pull/3269 the status-go part was already implement for enabling the persisting of collapsed or expanded categories.
This PR implements the `nim` part for enabling having collapsed categories that persist into the database. This fixes #13944
- communities collapsed categories
[Screencast from 2024-03-24 03:41:58 AM.webm](https://github.com/status-im/status-desktop/assets/2589171/55deee29-e7e8-4c8e-af82-1a49ccab4166)
> (desktop) Implement collapsed categories

- storybook/pages/AmountToSendPage.qml
- storybook/pages/StatusAmountInputPage.qml
- ui/StatusQ/src/StatusQ/Controls/StatusAmountInput.qml
- ui/StatusQ/src/StatusQ/Controls/Validators/StatusFloatValidator.qml
- ui/StatusQ/src/StatusQ/Core/LocaleUtils.qml
- ui/app/AppLayouts/Communities/controls/TokenPanel.qml
- ui/imports/shared/controls/AmountInput.qml
- teach `userInputLocale` about `Locale.OmitGroupSeparator` option which discards the said thousands separator
- some more fixes to other inputs to do the same, and align what the validators do
- StatusAmountInput: discard illegal characters, and reuse the same locale for the validator
- StatusAmountInputPage: make it possible to select a different locale
Fixes #14165
(Status)AmountInput, LocaleUtils
> fix: do not display the thousands separator when editing

- src/app/modules/main/chat_section/module.nim
Fixes #14444 and #14447
The problem was that we accessed a categoryItem that might not have existed yet.
> fix: fix crashes on join and permission removed

- src/app/modules/main/chat_section/module.nim
- src/app/modules/main/communities/module.nim
The tokens criteria items were filtered out if the `criteriaMet` flag doesn't change after a model update.
This filtering was done due to perf reasons, but we need all the token criteria items in the model.
Community permissions
This shows that both token criteria items are shown in the UI even though one is met and one is not.
https://github.com/status-im/status-desktop/assets/47811206/67318258-bfc5-42b3-bb17-ad88cc751c6e
> fix(CommunityPermissions): Fix token criteria updates in the permissions model

- src/app/modules/main/chat_section/chat_content/users/module.nim
- src/app/modules/main/profile_section/contacts/controller.nim
- src/app/modules/main/profile_section/contacts/io_interface.nim
- src/app/modules/main/profile_section/contacts/module.nim
- src/app/modules/main/profile_section/contacts/view.nim
- src/app_service/service/contacts/service.nim
- src/backend/contacts.nim
- storybook/pages/ProfileDialogViewPage.qml
- ui/app/AppLayouts/Profile/stores/ContactsStore.qml
- ui/app/mainui/Popups.qml
fixes #13619 
status-go PR: https://github.com/status-im/status-go/pull/5058
also hides the "trust" icon in the members list for myself
1. When "Remove ID verification" is clicked both Trusted and Verified verificationStatus will be reset to Unverified as well as trustStatus
2. The own account will not be marked as "trusted" in the groupchat member list
contacts / members_list / verification
https://github.com/status-im/status-desktop/assets/1083341/671a0a7e-ad39-42aa-ac85-1aa04e76361c
Added some general ideas on how to improve consistency:
https://github.com/status-im/status-desktop/issues/13619#issuecomment-2039823408
> fix(Profile flow): ID verification cannot be removed

- src/app/modules/main/wallet_section/all_collectibles/controller.nim
- src/app/modules/main/wallet_section/all_collectibles/view.nim
- src/app_service/service/collectible/service.nim
- src/backend/collectibles_types.nim
- storybook/pages/AssetsViewPage.qml
- storybook/pages/CollectiblesViewPage.qml
- storybook/pages/ManageAssetsPanelPage.qml
- storybook/pages/ManageCollectiblesPanelPage.qml
- storybook/pages/ManageHiddenPanelPage.qml
- storybook/qmlTests/tests/tst_ManageCollectiblesPanel.qml
- ui/StatusQ/CMakeLists.txt
- ui/StatusQ/src/wallet/managetokenscontroller.cpp
- ui/StatusQ/src/wallet/managetokenscontroller.h
- ui/StatusQ/src/wallet/managetokensmodel.cpp
- ui/StatusQ/src/wallet/managetokensmodel.h
- ui/StatusQ/src/wallet/tokendata.cpp
- ui/StatusQ/src/wallet/tokendata.h
- ui/app/AppLayouts/Profile/views/WalletView.qml
- ui/app/AppLayouts/Profile/views/wallet/ManageTokensView.qml
- ui/app/AppLayouts/Wallet/panels/ManageAssetsPanel.qml
- ui/app/AppLayouts/Wallet/panels/ManageCollectiblesPanel.qml
- ui/app/AppLayouts/Wallet/panels/ManageHiddenPanel.qml
- ui/app/AppLayouts/Wallet/stores/CollectiblesStore.qml
- ui/app/AppLayouts/Wallet/stores/WalletAssetsStore.qml
cherry-pick: https://github.com/status-im/status-desktop/pull/14394
also cherry-pick the require dependency: https://github.com/status-im/status-desktop/pull/13903
> fix(wallet): cherry-pick assets and collectible order fixes

- src/app/modules/main/chat_section/module.nim
- src/app/modules/main/communities/module.nim
closes #14446
Re-create the token criteria and include all items whenever the model changes.
The previous perf optimisation fix filtered the items where the criteriaMet doesn't change.
(cherry picked from commit a9a83df301f2b2b6b20e255b699dd56dcb0c4a73)
> chore: Cherry pick - Fix token criteria updates in the permissons model

- src/app/modules/main/chat_section/chat_content/messages/module.nim
Cherry-pick of https://github.com/status-im/status-desktop/pull/14482
Fixes #14479
The problem is our code assumed that we'd have the original message first, but in the case where messages are sent and edited before we open our app, when we fetch, we can't guarantee the order, so we might get the fully edited message directly from status-go.
The solution is simply to treat those messages as new messages.
> [CHERRY-PICK] fix(edit): fix edits received before the message did not appear

- src/app/modules/main/communities/view.nim
There were 2 properties broken, but they weren't crashing the app because they weren't used. However it was a problem for Monitoring Tool reading all the exposed properties.
Closes: #14493
`src/app/modules/main/communities/view.nim`
> fix(CommunitiesModule): Qt props fixed to not crash MonitoringTool

- storybook/pages/ColorsPage.qml
- ui/StatusQ/include/StatusQ/QClipboardProxy.h
- ui/StatusQ/src/QClipboardProxy.cpp
- gives an overview of all the `Theme.palette.foo` colors
- the color name/code can be copied to clipboard
- light/dark variant supported via storybook's "Dark mode" switch
- integrated search (both the color name and value)
Storybook
Full page, scrollable:
Search in action:
> chore(StoryBook): add Colors page

- storybook/pages/ProfileDialogViewPage.qml
- ui/imports/shared/views/ProfileDialogView.qml
- also trim the leading/trailing whitespace
- fixes long bio (mainly due to linebreaks) pushing down everything below and also overflowing the preview
- adjust SB page to include such example bio and remove the obsolete socialLinks (they are now part of the showcase models)
Fixes #14463
Fixes #14465
[Záznam obrazovky z 2024-04-19 00-05-53.webm](https://github.com/status-im/status-desktop/assets/5377645/18bdb19b-07b6-4e08-accf-ec3ec1e5629d)
> fix(ProfileDialogView): wrap bio in a scroll view

- ui/imports/shared/controls/chat/ProfileHeader.qml
- ui/imports/shared/views/chat/ProfileContextMenu.qml
- calculate the text width correctly, taking into account all the contents (verification icons, edit button) and also the margins
- extra commit to fix the erroneous "Send CR" menu entry
Fixes #14462
ProfileContextMenu
No clipped icons:
Pending CR + context menu:
> fix(ProfileContextMenu): don't overflow the title

- storybook/pages/CommunityMembershipSetupDialogPage.qml
- ui/StatusQ/src/StatusQ/Controls/StatusToolTip.qml
- ui/StatusQ/src/StatusQ/Popups/Dialog/StatusDialog.qml
- ui/StatusQ/src/permissionutilsinternal.cpp
- ui/app/AppLayouts/Chat/stores/RootStore.qml
- ui/app/AppLayouts/Communities/panels/SharedAddressesPanel.qml
- ui/app/AppLayouts/Communities/panels/SharedAddressesPermissionsPanel.qml
- ui/app/AppLayouts/stores/RootStore.qml
- ui/app/mainui/Popups.qml
- ui/imports/shared/popups/CommunityMembershipSetupDialog.qml
- fix the corner case and allow the user to join a community without an explicitly stated "Member" permission
- enable/disable the Share/Join/Save buttons when the permission to join check is ongoing, or when the permission check failed
- display tooltips over the disabled buttons explaining why it's disabled
- always display the eligibility button floating on top of the (scrollable) contents
Fixes #14473
Fixes #14299
CommunityMembershipSetupDialog
Main join dialog:
Check over:
Editting addresses:
> fix: can't join an encrypted community

- ui/app/AppLayouts/Profile/views/WalletView.qml
- "Save for later" -> "Save"
- "Apply to my Wallet" -> "Save and apply"
Fixes #14519
> fix(Token Management): update wording for Save/Apply buttons

- ui/app/AppLayouts/Profile/controls/WalletKeyPairDelegate.qml
- ui/app/AppLayouts/Profile/views/wallet/AccountView.qml
- ui/app/AppLayouts/Wallet/views/AccountContextMenu.qml
- "Include in total balance" -> "Include in balances and activity"
Fixes #14517
(Settings/)Wallet
> fix: Inclusion of Watched addresses in Balances: Wording change

- ui/app/AppLayouts/Communities/panels/SharedAddressesPanel.qml
- ui/imports/shared/popups/CommunityMembershipSetupDialog.qml
- fix a binding loop warning for `implicitHeight` (can happen with no permissions at all)
- fix word wrap for long texts with no word breaks
Fixes #14536
CommunityMembershipSetupDialog
> fix(Community): community invitation is missing intro and logo

- monitoring/MonitorEntryPoint.qml
- whenever a cell in a list view displaying model represents submodel, it's clickable and opens windows with a listview for submodel
- names of injected properties are selectable (and therefore easy to copy)
- display number of items for submodels
For reviewers: Running `Monitoring Tool` app is described in this ticket: https://github.com/status-im/status-desktop/pull/8961
Closes: #14496
`MonitorEntryPoint.qml`
> feat(MonitoringTool): Ability to inspect submodels

- src/app/global/local_app_settings.nim
- src/nim_status_client.nim
- storybook/pages/LanguageViewPage.qml
- ui/StatusQ/src/StatusQ/Components/StatusListPicker.qml
- ui/StatusQ/src/StatusQ/Controls/StatusPickerButton.qml
- ui/StatusQ/src/StatusQ/Controls/StatusWarningBox.qml
- ui/app/AppLayouts/Profile/ProfileLayout.qml
- ui/app/AppLayouts/Profile/views/AdvancedView.qml
- ui/app/AppLayouts/Profile/views/LanguageView.qml
- make it conditionally available for testing via Settings/Advanced/Enable translations
- display a tooltip and infobox explaining the current and future situation
- upon app start, force the language to "en" if the translations are not enabled; and suggest app restart when they get disabled
Fixes #14527
Settings/[Language,Advanced]
Defaults:
Advanced toggle:
Translations enabled:
> feat: disable language/translations selection

- src/app/global/local_app_settings.nim
- src/nim_status_client.nim
- storybook/pages/LanguageViewPage.qml
- ui/StatusQ/src/StatusQ/Components/StatusListPicker.qml
- ui/StatusQ/src/StatusQ/Controls/StatusPickerButton.qml
- ui/StatusQ/src/StatusQ/Controls/StatusWarningBox.qml
- ui/app/AppLayouts/Profile/ProfileLayout.qml
- ui/app/AppLayouts/Profile/views/AdvancedView.qml
- ui/app/AppLayouts/Profile/views/LanguageView.qml
Cherry-pick of PR https://github.com/status-im/status-desktop/pull/14539
- make it conditionally available for testing via Settings/Advanced/Enable translations
- display a tooltip and infobox explaining the current and future situation
- upon app start, force the language to "en" if the translations are not enabled; and suggest app restart when they get disabled
Fixes #14527
Settings/[Language,Advanced]
> CHERRY-PICK-2.28.x: feat: disable language/translations selection

- src/app/global/local_app_settings.nim
- ui/app/AppLayouts/Communities/CommunitiesPortalLayout.qml
- ui/app/AppLayouts/Communities/stores/CommunitiesStore.qml
- ui/app/AppLayouts/Profile/stores/AdvancedStore.qml
- ui/app/AppLayouts/Profile/views/AdvancedView.qml
Fixes https://github.com/status-im/status-desktop/issues/14530
(includes a revert of the previous hide that wasn't exactly what we wanted)
[community-creation.webm](https://github.com/status-im/status-desktop/assets/11926403/58504057-3718-4146-9c2b-3b638a430308)
Known issue: if you disable the setting, the Loader doesn't lose its width. It,s not a huge deal, as it's not a common use case, but if the UI team has an easy fix, might as well.
> Hide Create Community button

- ui/imports/shared/views/chat/MessageView.qml
Fixes pinned messages preview.
Previously:
MessageByMessageId was returning a message from the persistence without preparation of its contents.
Now:
chat_content/module.nim `onPinMessage` calls `PreparedMessageById` to get a message with prepared links to images/stickers and passes it to `buildPinnedMessageItem`.
status-go PR: https://github.com/status-im/status-go/pull/5102
Fixes #13684
chat_content, status-go messenger api
https://github.com/status-im/status-desktop/assets/1083341/a4385f35-d449-411b-a038-ed733df016be
> fix(chat_section): fix preview for pinned messages with images/stickers (#13684)

- src/app/modules/main/profile_section/advanced/controller.nim
- src/app/modules/main/profile_section/advanced/io_interface.nim
- src/app/modules/main/profile_section/advanced/module.nim
- src/app/modules/main/profile_section/advanced/view.nim
- src/app_service/common/network_constants.nim
- src/app_service/service/node_configuration/service.nim
- src/backend/node_config.nim
- ui/app/AppLayouts/Communities/controls/Options.qml
- ui/app/AppLayouts/Profile/ProfileLayout.qml
- ui/app/AppLayouts/Profile/stores/AdvancedStore.qml
- ui/app/AppLayouts/Profile/views/AdvancedView.qml
- ui/app/AppLayouts/Profile/views/MessagingView.qml
> chore: disable history archive for new user and add advanced setting

- ui/app/AppLayouts/Communities/panels/SharedAddressesPanel.qml
Set contentItem explicitly, that's probably needed because root item is `Control`
Communities
Before:
After:
> fix: Fix content height for SharedAddressesPanel

- src/app/global/feature_flags.nim
- src/app/global/global_singleton.nim
- src/nim_status_client.nim
- ui/app/AppLayouts/Wallet/panels/WalletHeader.qml
- ui/imports/utils/Global.qml
Also add basic feature flag support that work with `QML` and `nim`
The feature is disabled by default. To enable the feature for development: `FLAG_DAPPS_ENABLED=1 make run`
> chore(global) add the DApps button under a feature flag

- src/app/global/local_app_settings.nim
- src/app/modules/main/profile_section/advanced/controller.nim
- src/app/modules/main/profile_section/advanced/io_interface.nim
- src/app/modules/main/profile_section/advanced/module.nim
- src/app/modules/main/profile_section/advanced/view.nim
- src/app_service/common/network_constants.nim
- src/app_service/service/accounts/service.nim
- src/app_service/service/node_configuration/service.nim
- src/backend/node_config.nim
- ui/app/AppLayouts/Communities/CommunitiesPortalLayout.qml
- ui/app/AppLayouts/Communities/controls/Options.qml
- ui/app/AppLayouts/Communities/stores/CommunitiesStore.qml
- ui/app/AppLayouts/Profile/ProfileLayout.qml
- ui/app/AppLayouts/Profile/stores/AdvancedStore.qml
- ui/app/AppLayouts/Profile/views/AdvancedView.qml
- ui/app/AppLayouts/Profile/views/MessagingView.qml
Cherry picks of https://github.com/status-im/status-desktop/pull/14545 and https://github.com/status-im/status-desktop/pull/14547
Fixes [#14534](https://github.com/status-im/status-desktop/issues/14534) and [#14530](https://github.com/status-im/status-desktop/issues/14530)
> Cherry-picks of hide create community button and disable archive

- storybook/pages/ChangePasswordViewPage.qml
- ui/app/AppLayouts/Profile/views/ChangePasswordView.qml
- use the proper `StatusFlatButton` as it was meant in the Figma design
Fixes #13763
Settings/Password
[Záznam obrazovky z 2024-05-02 12-46-41.webm](https://github.com/status-im/status-desktop/assets/5377645/6233b521-c295-43cf-a68b-7196f8c191a5)
> fix(ChangePasswordView): Clear and cancel button is not blue

- ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml
Fixes [#14271](https://github.com/status-im/status-desktop/issues/14271)
Set StatusChatInfoButton in CommunitySettingsView.qml to be hoverable. Clicking on StatusChatInfoButton will have the same behavior as "Back to community" link. 
Now StatusChatInfoButton in CommunitySettingsView behaves similarly to StatusChatInfoButton in StatusAppChatView:
Communities: CommunitySettingsView.qml
> fix(UX Improvement): Clicking on the community logo when in the admin panel should take back to the community (#14271)

- storybook/pages/CommunityInfoEditor.qml
- storybook/pages/StatusCommunityCardPage.qml
- ui/StatusQ/src/StatusQ/Components/StatusCommunityCard.qml
- ui/StatusQ/src/StatusQ/Components/StatusCommunityTags.qml
- ui/app/AppLayouts/Communities/views/CommunitiesGridView.qml
- ui/imports/shared/views/profile/ProfileShowcaseCommunitiesView.qml
- correct propagation of hover events, fixes card flicker
- improve the ugly thick border
- token icons are now correctly rounded
- fix text descent lines are cut of ("y" and "p" truncated at the bottom) due to excessive clipping, set correct max line count
- fix tag outline not being visible in dark mode
- add/update the corresponding SB page, with more controls to play around with the different params
Fixes #14555
StatusCommunityCard
[Záznam obrazovky z 2024-05-01 15-31-30.webm](https://github.com/status-im/status-desktop/assets/5377645/d50a586a-6c11-443d-9db0-6033eb21d2cb)
Correctly rounded token icons:
> fix(StatusCommunityCard): fix some visual glitches

- src/app/modules/main/communities/models/curated_community_item.nim
- src/app/modules/main/communities/models/curated_community_model.nim
- src/app/modules/main/communities/module.nim
- src/app_service/service/message/dto/status_community_link_preview.nim
- ui/StatusQ/src/StatusQ/Components/StatusCommunityCard.qml
- ui/app/AppLayouts/Communities/views/CommunitiesGridView.qml
- ui/imports/shared/controls/chat/LinkPreviewCard.qml
- ui/imports/shared/controls/chat/private/CommunityData.qml
- ui/imports/shared/controls/delegates/LinkPreviewCardDelegate.qml
Fixes #14567
This is mostly just a cherry-pick of https://github.com/status-im/status-desktop/pull/14538 to the release branch.
It also includes a status-go fix for fetching the curated communities: https://github.com/status-im/status-go/pull/5110
> Fix hide member count for encrypted communities + Fix fetching curated communities

- storybook/pages/CommunityInfoEditor.qml
- storybook/pages/StatusCommunityCardPage.qml
- ui/StatusQ/src/StatusQ/Components/StatusCommunityCard.qml
- ui/StatusQ/src/StatusQ/Components/StatusCommunityTags.qml
- ui/app/AppLayouts/Communities/views/CommunitiesGridView.qml
- ui/imports/shared/views/profile/ProfileShowcaseCommunitiesView.qml
Cherry pick of https://github.com/status-im/status-desktop/pull/14564 to `release/2.28.x` branch
- correct propagation of hover events, fixes card flicker
- improve the ugly thick border
- token icons are now correctly rounded
- fix text descent lines are cut of ("y" and "p" truncated at the bottom) due to excessive clipping, set correct max line count
- fix tag outline not being visible in dark mode
- add/update the corresponding SB page, with more controls to play around with the different params
Fixes #14555
StatusCommunityCard
See the original PR
> CHERRY-PICK: fix(StatusCommunityCard): fix some visual glitches

- src/app/modules/main/profile_section/profile/io_interface.nim
- src/app/modules/main/profile_section/profile/models/profile_save_data.nim
- src/app/modules/main/profile_section/profile/module.nim
- src/app/modules/main/profile_section/profile/view.nim
- ui/app/AppLayouts/Profile/stores/ProfileStore.qml
- ui/app/AppLayouts/Profile/views/MyProfileView.qml
fixes #14464 
Problem:
There were no difference between the fact that the avatar is not changed and the avatar is deleted. The same for bio and displayName. In NIM, this state was simply rewritten
(The problem was discovered due to the fact that if the picture does not change, then Nim receives a base64 encoded source - instead of the path to the new avatar. Which status-go could not parse as a file.)
Solution:
On the QML side, if we see that there have been changes, we add changes to changesMapJson, if there are no changes, then do not add.
On the view.nim Side - use Option when converting to IdentitySaveData
On the module.nim side - distinguish None from an empty string (bio, image.source)
Profile
https://github.com/status-im/status-desktop/assets/1083341/0ca65ae8-52f1-4df5-a6cf-9f78e013 …
> Fix(Profile): Fix saving of profile identity changes (#14464)

- ui/StatusQ/src/StatusQ/Components/StatusCard.qml
- ui/StatusQ/src/StatusQ/Components/StatusGroupBox.qml
- ui/StatusQ/src/StatusQ/Components/StatusLoadingIndicator.qml
- ui/StatusQ/src/StatusQ/Components/private/statusMessage/StatusSticker.qml
- ui/StatusQ/src/StatusQ/Core/StatusIcon.qml
- ui/app/AppLayouts/Communities/controls/InlineNetworksComboBox.qml
- ui/app/AppLayouts/Communities/models/ChannelPermissionsModelEditor.qml
- ui/app/AppLayouts/Communities/panels/SharedAddressesAccountSelector.qml
TLDR: the `StatusLoadingIndicator` will be able to continue the (rotating) animation eventhough the app might be stuck as `RotationAnimator` runs on the render thread
(separate commit to fix the failing ui-tests)
- make `StatusIcon` use internally `ColorImage` component which makes it possible to recolor `Image` on the fly w/o the need to use `QtGraphicalEffects` module and a separate color layer
- which in turn enables us to use `StatusIcon` with the `RotationAnimator`
- one minor drawback though, we can no longer use the versioned properties like `mipmap` with `StatusIcon`; not a big deal as we use this with SVGs only
Fixes #10014
StatusIcon, StatusLoadingIndicator
[Záznam obrazovky z 2024-05-02 20-56-49.webm](https://github.com/status-im/status-desktop/assets/5377645/a153a4fb-c7ff-40e3- …
> fix(StatusLoadingIndicator): make StatusLoadingIndicator use Animator

- ui/imports/shared/views/profile/ProfileShowcaseCommunitiesView.qml
- messing around with the DropShadow layer lead to a nasty crash somewhere deep inside Qt mouse event handlers
Fixes #14596
Profile/Profile Showcase/Communities
[Záznam obrazovky z 2024-05-03 17-20-44.webm](https://github.com/status-im/status-desktop/assets/5377645/55923de2-0b0f-4069-9e1c-a8908e6c49d5)
> fix: Hovering community in the profile showcase leads to crash

- Makefile
- package.json
The `fileicon` `v0.3.0` tool we used on MacOS to embed icons in our binary is failing. Upgrading to latest `v0.3.3` fixes this. It will require a `make update` though to fix local builds.
Also improved to update `yarn` packages all the time ensuring that a change in `package.json` will be reflected on `make update` without manual intervention.
The `make run` error
```bash
Building: StatusQ
Building: DOtherSide
Installing: StatusQ
Performing one-time user-level installation of required Python packages: pyobjc-core pyobjc-framework-Cocoa - this can take while...
error: externally-managed-environment
× This environment is externally managed
╰─> To install Python packages system-wide, try brew install
xyz, where xyz is the package you are trying to
install.
If you wish to install a Python …
```
> fix(build) fix python package error on make run with MacOS developer environments

- ui/app/AppLayouts/Communities/panels/PermissionsSettingsPanel.qml
- ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml
Fixes #14449
To move fast on this ticket, I have a one liner change that produces expected result, meaning the token name is correctly displayed on the permission for the token master. However, I am aware that the model from which the data is coming from is a `SortFilterProxyModel` between the `assetsMOdel` and the `collectiblesModel` and that the `text` FastExpressionRole should provide the necessary data but, it seems that this is not enough, hence producing the missing token name bug. I would love to deepen my understanding or any feedbacks if I am missing something.
- Permissions
> fix: Token Master permission missing token name

- storybook/pages/SubmodelProxyModelPage.qml
- ui/StatusQ/include/StatusQ/submodelproxymodel.h
- ui/StatusQ/src/movablemodel.cpp
- ui/StatusQ/src/submodelproxymodel.cpp
- ui/StatusQ/src/sumaggregator.cpp
- ui/StatusQ/tests/tst_MovableModel.cpp
- ui/StatusQ/tests/tst_SubmodelProxyModel.cpp
- adds possibility to expose values computed per submodel as a role to top-level model in a dynamic, declarative way
- extends the existing Storybook page to present added functionality, adds intro describing the flow
- adds test (marked with SKIP(...)) pointing the problem with creating multiple proxies over the same source (to be fixed in a separate task: https://github.com/status-im/status-desktop/issues/14550)
[Screencast from 29.04.2024 16:07:21.webm](https://github.com/status-im/status-desktop/assets/20650004/3e0e841a-a758-4525-82f2-16e7f6af1abd)
Closes: #14390
`SubmodelProxyModel`
> feat(StatusQ/SubmodelProxyModel): Exposing roles computed per submodel to the top-level model
