src/app/modules/main/communities/controller.nim, src/app/modules/main/communities/module.nim, src/app/modules/main/communities/tokens/models/token_item.nim, src/app/modules/main/communities/tokens/models/token_model.nim, src/app/modules/main/communities/tokens/models/token_owners_item.nim, src/app/modules/main/communities/tokens/models/token_owners_model.nim, src/app/modules/main/controller.nim, src/app/modules/main/io_interface.nim, src/app/modules/main/module.nim, src/app/modules/shared_models/section_item.nim, src/app_service/service/community_tokens/async_tasks.nim, src/app_service/service/community_tokens/dto/community_token_owner.nim, src/app_service/service/community_tokens/service.nim, src/backend/community_tokens.nim, storybook/src/Models/TokenHoldersModel.qml, ui/app/AppLayouts/Chat/panels/communities/CommunityMintTokensSettingsPanel.qml, ui/app/AppLayouts/Chat/panels/communities/TokenHoldersPanel.qml, ui/app/AppLayouts/Chat/popups/community/RemoteSelfDestructPopup.qml, ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml, ui/app/AppLayouts/Chat/views/communities/CommunityCollectibleView.qml, ui/imports/shared/stores/CommunityTokensStore.qml
- replace qml owners model with Nim one
- get token owners from wallet service
- keeping owners cache in community_tokens/service and refresh every 10 minutes
Requirements:
In order to display token owners correctly some wallet endpoints needs to be set up correctly (depend on the chain used):
- custom Infura account with Infura secret key
- Alchemy account for Optimism Goerli (or Arbitrum Goerli)
Details: https://www.notion.so/Getting-and-Configuring-API-Keys-67347f753e1444ae92c85aaee69faeb4#ae2f773d397c4a049ba39f02da39208f
=> 10254 token holders

ui/imports/shared/popups/ImportCommunityPopup.qml
Closes #10325
ImportCommunityPopup: added wrap mode in community key text area
ImportCommunityPopup 
https://user-images.githubusercontent.com/31625338/236808588-a122d722-1377-448e-ad19-148fc89d4181.mov
=> [createCommunity]: added wrap mode in community key

ui/app/AppLayouts/Chat/popups/PinnedMessagesPopup.qml, ui/app/AppLayouts/Chat/views/ChatColumnView.qml, ui/imports/shared/views/chat/MessageContextMenuView.qml, ui/imports/shared/views/chat/MessageView.qml
Close #10570
* Reuse chat root store connections
* Fix quick actions for blocked chat
Chat
=> fix(Chat): Reuse chat root store connections and fix chat quick actions when blocked

src/app/modules/main/wallet_section/assets/controller.nim, src/app/modules/main/wallet_section/assets/module.nim, src/app/modules/shared/wallet_utils.nim, src/app_service/service/wallet_account/dto.nim, src/app_service/service/wallet_account/service.nim
=> feat(@wallet): allows multiple addresses in assets module

src/app/core/signals/remote_signals/messages.nim, src/app/core/signals/remote_signals/waku_backed_up_keycards.nim, src/app/modules/main/profile_section/ens_usernames/module.nim, src/app/modules/main/profile_section/keycard/controller.nim, src/app/modules/main/profile_section/keycard/io_interface.nim, src/app/modules/main/profile_section/keycard/module.nim, src/app/modules/main/profile_section/wallet/accounts/controller.nim, src/app/modules/main/stickers/module.nim, src/app/modules/main/wallet_section/accounts/controller.nim, src/app/modules/main/wallet_section/add_account/controller.nim, src/app/modules/main/wallet_section/add_account/module.nim, src/app/modules/main/wallet_section/send/controller.nim, src/app/modules/main/wallet_section/send/module.nim, src/app/modules/shared/keypairs.nim, src/app/modules/shared_modules/keycard_popup/controller.nim, src/app/modules/shared_modules/keycard_popup/internal/copying_keycard_state.nim, src/app/modules/shared_modules/keycard_popup/internal/creating_account_new_seed_phrase_state.nim, src/app/modules/shared_modules/keycard_popup/internal/creating_account_old_seed_phrase_state.nim, src/app/modules/shared_modules/keycard_popup/internal/enter_seed_phrase_state.nim, src/app/modules/shared_modules/keycard_popup/internal/importing_from_keycard_state.nim, src/app/modules/shared_modules/keycard_popup/internal/migrating_key_pair_state.nim, src/app/modules/shared_modules/keycard_popup/internal/state_factory.nim, src/app/modules/shared_modules/keycard_popup/module.nim, src/app_service/service/wallet_account/async_tasks.nim, src/app_service/service/wallet_account/keycard_dto.nim, src/app_service/service/wallet_account/service.nim, src/backend/backend.nim
This change is needed for further changes which are part of issue #10592
- https://github.com/status-im/status-go/pull/3469
=> chore(@desktop/wallet): `KeyPairDto` which actually refers to keycard is renamed to `KeycardDto`

storybook/main.qml, storybook/src/Storybook/InspectionItem.qml, storybook/src/Storybook/InspectionItemsList.qml, storybook/src/Storybook/InspectionPanel.qml, storybook/src/Storybook/InspectionUtils.qml, storybook/src/Storybook/InspectionWindow.qml, storybook/src/Storybook/PageToolBar.qml, storybook/src/Storybook/qmldir
Interactive tool for visual inspection of components in Storybook.
Closes: https://github.com/status-im/status-desktop/issues/10574
Storybook
=> Storybook: Generic, figma-like inspection tool for checking structure/sizes/paddings

ui/app/mainui/Popups.qml, ui/imports/shared/views/ProfileDialogView.qml, ui/imports/shared/views/chat/MessageContextMenuView.qml, ui/imports/utils/Global.qml
Closes #10502
Contacts message context menu, added "remove contact" option in settings menu
Contacts
https://github.com/status-im/status-desktop/assets/31625338/33178155-e487-48ce-9efa-810aaefbf879
=> [contacts]: added "remove contact" option in settings menu

storybook/pages/InDropdownPage.qml, storybook/pages/InviteFriendsToCommunityPopupPage.qml, storybook/pages/MembersDropdownPage.qml, ui/app/AppLayouts/Chat/controls/community/InDropdown.qml, ui/app/AppLayouts/Chat/controls/community/MembersDropdown.qml, ui/app/AppLayouts/Chat/popups/community/InviteFriendsToCommunityPopup.qml, ui/app/AppLayouts/Chat/views/communities/CommunityNewAirdropView.qml, ui/imports/shared/views/ExistingContacts.qml
Adjusts search behavior in
* `MembersDropdown`
* `InDropdown`
* `InviteFriendsToCommunityPopup`
according to agreements from the ticket.
Closes: https://github.com/status-im/status-desktop/issues/8879
`MembersDropdown`, `InDropdown`, `InviteFriendsToCommunityPopup`
[Screencast from 11.05.2023 16:42:15.webm](https://github.com/status-im/status-desktop/assets/20650004/6d4a6758-1fc6-4298-9d4e-7b255ef64e18)
[Screencast from 11.05.2023 16:50:31.webm](https://github.com/status-im/status-desktop/assets/20650004/bcfca37e-c469-446b-8a56-d6536bf3a576)
[Screencast from 11.05.2023 17:15:17.webm](https://github.com/status-im/status-desktop/assets/20650004/f7626919-2958-4d43-ab50-a836142de73d)
=> chore(MembersDropdown, InDropdown, InviteFriendsToCommunityPopup): Adjust search behavior

ui/app/AppLayouts/Chat/panels/communities/CommunityMintTokensSettingsPanel.qml
=> fix(MintTokens): Update welcome page strings

src/app_service/service/contacts/dto/contacts.nim, src/app_service/service/contacts/service.nim, ui/imports/shared/views/chat/MessageView.qml
Close #10500
1. Fix displaying CR messages in the chat
2. Relay on actual status-go state for contacts flows 
Contacts, Chat, Activity Center
=> Fix(Contacts): fix weird behaviour in some contacts flows edge cases

ui/app/AppLayouts/Chat/panels/communities/CommunityMintTokensSettingsPanel.qml, ui/app/AppLayouts/Chat/views/communities/CommunityNewCollectibleView.qml
Closes #10597
Strings and focus updates.
https://github.com/status-im/status-desktop/assets/97019400/a5537b6e-8de4-48bb-8a6e-1ea9017eaa37
=> fix(MintTokens): Update Create new collectible page according to new design

ui/imports/shared/popups/ImportCommunityPopup.qml, ui/imports/utils/Utils.qml
Fixes https://github.com/status-im/status-desktop/issues/10686
Support non-compressed public keys in `Import Community` popup 
https://github.com/status-im/status-desktop/assets/25482501/bf1f90cf-1e51-4895-b95d-b94409570cbc
=> fix(ImportCommunityPopup): Support uncompressed public keys

src/app_service/service/chat/service.nim, src/app_service/service/community/service.nim
Cherry pick https://github.com/status-im/status-desktop/pull/10684
=> [cherry-pick] fix: Don't try to update unknown communities

ui/app/AppLayouts/Chat/views/MembersSelectorView.qml, ui/app/AppLayouts/Chat/views/private/MembersSelectorBase.qml
Fixes: #9881
Adds new filter for member selector 
MemberSelector
=> fix(member-selector): Adds filter suggestions by chat key pasted in input

src/app_service/service/community/service.nim
Fixes: #10582
I change the order of methods calls, cos it makes duplication on spectating communities.
Community
=> fix(community): Remove channels duplications

src/app_service/service/community/service.nim
Cherry-pick of [this](https://github.com/status-im/status-desktop/pull/10700)
=> cherry-pick: fix(community): Remove channels duplications

src/app/modules/main/chat_section/controller.nim, src/app/modules/main/chat_section/module.nim, src/app_service/service/community/service.nim
=> fix(chat_section): make chat hidden if category collapsed when creating

src/app/modules/main/wallet_section/module.nim, src/app/modules/main/wallet_section/view.nim, ui/app/AppLayouts/Wallet/WalletLayout.qml, ui/app/AppLayouts/Wallet/stores/RootStore.qml
=> feat(@wallet): add account toast

src/app_service/service/network/service.nim, src/app_service/service/wallet_account/async_tasks.nim, src/app_service/service/wallet_account/service.nim, src/backend/accounts.nim
fixes #10068
status-go pr: https://github.com/status-im/status-go/pull/3492
=> fix(@wallet): Address details per chain

ui/app/AppLayouts/Onboarding/views/KeycardInitView.qml, ui/app/AppLayouts/Onboarding/views/KeycardPinView.qml, ui/app/AppLayouts/Onboarding/views/KeycardPukView.qml, ui/app/AppLayouts/Onboarding/views/KeycardStateView.qml, ui/app/AppLayouts/Onboarding/views/KeysMainView.qml, ui/app/AppLayouts/Onboarding/views/LoginView.qml, ui/app/AppLayouts/Onboarding/views/ProfileFetchingView.qml, ui/app/AppLayouts/Onboarding/views/SeedPhraseView.qml, ui/app/AppLayouts/Onboarding/views/SeedPhraseWordsInputView.qml, ui/imports/utils/Constants.qml
Closes #8525
Login screen fixed overall positioning
Login screen
=> [onboarding]: fixed overall positioning

src/app/modules/startup/controller.nim, src/app/modules/startup/internal/login_keycard_enter_pin_state.nim, src/app/modules/startup/internal/login_keycard_wrong_keycard.nim, src/app/modules/startup/internal/state_factory_login_implementation.nim, src/app/modules/startup/module.nim, ui/app/AppLayouts/Onboarding/views/LoginView.qml
=> feat(@desktop/general): try again button added to wrong keycard screen

src/app/modules/main/chat_section/controller.nim, src/app/modules/main/wallet_section/collectibles/controller.nim, src/app/modules/main/wallet_section/collectibles/current_collectible/controller.nim, src/app/modules/main/wallet_section/collectibles/current_collectible/io_interface.nim, src/app/modules/main/wallet_section/collectibles/current_collectible/module.nim, src/app/modules/main/wallet_section/collectibles/io_interface.nim, src/app/modules/main/wallet_section/collectibles/module.nim, src/app_service/service/collectible/service.nim
=> feat(@wallet): collectible multi address

src/app_service/service/wallet_account/async_tasks.nim, src/backend/accounts.nim
- https://github.com/status-im/status-go/pull/3526
Fixes: #10800
=> fix(@desktop/wallet): let user add a new account even address' activity details are not fully fetched

ui/StatusQ/src/StatusQ/Components/StatusListItem.qml, ui/imports/shared/popups/keycard/helpers/KeyPairItem.qml
=> fix(@desktop/keycard): updated information for listed keypairs for migration to a keycard

src/app_service/service/wallet_account/service.nim
status-go PR: https://github.com/status-im/status-go/pull/3514
=> feat(@wallet): returns only enabled networks

ui/StatusQ/src/StatusQ/Controls/StatusNavBarTabButton.qml
check if there indeed is a popup menu
Fixes #10824
=> fix(NavBar) right clicking on Wallet, Community Portal and Settings highlight them

src/app/modules/main/communities/tokens/controller.nim, src/app/modules/main/communities/tokens/io_interface.nim, src/app/modules/main/communities/tokens/models/token_item.nim, src/app/modules/main/communities/tokens/models/token_model.nim, src/app/modules/main/communities/tokens/module.nim, src/app/modules/main/communities/tokens/view.nim, src/app/modules/main/controller.nim, src/app/modules/main/module.nim, src/app_service/common/utils.nim, src/app_service/service/community_tokens/async_tasks.nim, src/app_service/service/community_tokens/service.nim, src/app_service/service/transaction/dto.nim, src/backend/community_tokens.nim, ui/app/AppLayouts/Chat/panels/communities/CommunityMintTokensSettingsPanel.qml, ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml, ui/app/AppLayouts/Chat/views/communities/CommunityMintedTokensView.qml, ui/app/AppLayouts/Chat/views/communities/CommunityTokenView.qml, ui/imports/shared/stores/CommunityTokensStore.qml, ui/imports/utils/Constants.qml
Self-destruct collectibles tokens.
Additional fixes:
- showing account name in collectibles details
- adding to the model uniqueId for contract (technical detail needed in QML)
**Functionality will work correctly only for new deployed contracts**
Related status-go pr: https://github.com/status-im/status-go/pull/3483
https://github.com/status-im/status-desktop/assets/61889657/862a0291-afa5-4005-8cf2-b8c02349c365
=> 10052 remote destruct

storybook/PagesModel.qml, storybook/pages/StatusDateRangePickerPage.qml, ui/StatusQ/src/StatusQ/Components/StatusDateInput.qml, ui/StatusQ/src/StatusQ/Components/private/dateInput/StatusBaseDateInput.qml, ui/StatusQ/src/StatusQ/Components/private/qmldir, ui/StatusQ/src/StatusQ/Components/qmldir, ui/StatusQ/src/statusq.qrc, ui/app/AppLayouts/Wallet/controls/StatusDateRangePicker.qml, ui/app/AppLayouts/Wallet/controls/qmldir
fixes #10796
Implements the new date picker to filter transactions as per new designs https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=12635-313636&t=OzBdxthbwYnJmDFP-4
Hasnt be used on desktop yet, only sotry book will be added under https://github.com/status-im/status-desktop/issues/10787
https://github.com/status-im/status-desktop/assets/60327365/191762ec-7e4f-454b-bb49-d809ff7409ae
**US Format**
**UK format**
=> fix(@desktop/wallet): Simple Custom Date range date picker

src/app/modules/main/chat_section/chat_content/messages/module.nim
- show loading screen on message search
I thought it would be beneficial to provide a visual indicator of progress when searching for older messages. This was primarily motivated by the occasional jumpy behavior observed when the chat was automatically scrolling to the first unseen message.
- messages search
- scroll to first unseen message
https://github.com/status-im/status-desktop/assets/33099791/dbb34e2f-dfc8-446a-8398-b241e1da1139
=> chore: show loading screen on message search

src/nim_status_client.nim, vendor/DOtherSide/lib/src/DOtherSide.cpp
fixes #6930 
Fixes environment variables not being applied correctly on Windows during runtime.
Whole application during runtime.
=> desktop(DOtherSide): Set env var before creating gui app

ui/imports/shared/status/StatusChatInput.qml
=> chore(StatusChatInput): hide ChatCommands for now

storybook/pages/TransactionDetailViewPage.qml, storybook/stubs/shared/stores/RootStore.qml, ui/app/AppLayouts/Wallet/popups/TransactionAddressMenu.qml, ui/app/AppLayouts/Wallet/views/TransactionDetailView.qml, ui/imports/shared/controls/TransactionDataTile.qml
closes #10792 
* Updated values section to new design.
* Extended storybook TransactionDetailsView logic
* Fixed transaction menu tx hash link
* Wallet activity view
Design:
https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=12310-258079&t=KdYIzdn0ahxB48oq-4
Sent:
Bridge
=> feat(@desktop/wallet): Transactions values

ui/imports/shared/views/AssetsView.qml
=> fix(@wallet): no token balance

test/ui-test/src/screens/StatusCommunityScreen.py, test/ui-test/testSuites/suite_communities/shared/scripts/community_names.py, test/ui-test/testSuites/suite_communities/shared/steps/communitySteps.py, test/ui-test/testSuites/suite_communities/tst_communityManageOverview/test.feature, test/ui-test/testSuites/suite_wallet/tst_wallet/test.py
Fixes https://github.com/status-im/desktop-qa-automation/issues/59
UI tests
=> tst_communityManageOverview: add test for Airdrop page navigation from Overview screen

test/ui-test/testSuites/suite_wallet/shared/steps/walletSteps.py, test/ui-test/testSuites/suite_wallet/tst_wallet/test.feature, test/ui-test/testSuites/suite_wallet/tst_wallet/test.py
Fix background step and imports
e2e tests
=> chore(@e2e_tests): fix background for wallet suite

Makefile, ci/Jenkinsfile.linux, ci/Jenkinsfile.macos, ci/Jenkinsfile.tests-e2e, ci/Jenkinsfile.tests-imports, ci/Jenkinsfile.tests-nim, ci/Jenkinsfile.windows
Debugging:
* https://github.com/status-im/infra-ci/issues/88
Also minimal Makefile refactor as the conditional was needlessly overcomplicated.
=> ci: add NIMFLAGS parameter to jobs

ui/imports/shared/controls/TransactionDelegate.qml, ui/imports/shared/popups/keycard/states/KeycardConfirmation.qml
fixes #10918 
fixes #10924 
Fixes 2 small bugs
* Keycard popup
* Wallet activity UI
=> fix(@desktop/keycard/wallet): Small fixes

src/app/core/signals/remote_signals/messages.nim, src/app/modules/main/profile_section/profile/controller.nim, src/app/modules/main/profile_section/profile/io_interface.nim, src/app/modules/main/profile_section/profile/module.nim, src/app/modules/main/profile_section/profile/view.nim, src/app/modules/shared_models/social_links_model.nim, src/app/modules/startup/module.nim, src/app_service/common/social_links.nim, src/app_service/service/accounts/dto/accounts.nim, src/app_service/service/settings/service.nim, src/backend/settings.nim, test/ui-test/src/screens/SettingsScreen.py, ui/app/AppLayouts/Profile/panels/ProfileSocialLinksPanel.qml, ui/app/AppLayouts/Profile/popups/AddSocialLinkModal.qml, ui/app/AppLayouts/Profile/popups/ModifySocialLinkModal.qml, ui/app/AppLayouts/Profile/stores/ProfileStore.qml, ui/imports/utils/Constants.qml, ui/imports/utils/ProfileUtils.qml, ui/imports/utils/Utils.qml
Corresponding `stauts-go` PR:
- https://github.com/status-im/status-go/pull/3552
- https://github.com/status-im/status-go/pull/3577
Changes:
- added to sync mechanism
- added to backup mechanism
- UI updated according to the newest changes
Closes: #10390
https://github.com/status-im/status-desktop/assets/86303051/5e60260c-73c3-4171-8417-efd58a6660f7
=> fix(@desktop/profile): profile social links

test/ui-test/testSuites/suite_settings/tst_userIdentity/test.feature
disable test for links
settings tests
=> chore(@e2e_tests): disable flaky test

src/app/core/signals/remote_signals/status_updates.nim
=> chore(nim): Adds try/catch block to fromEvent

src/app/modules/main/wallet_section/accounts/io_interface.nim, src/app/modules/main/wallet_section/accounts/module.nim, src/app/modules/main/wallet_section/filter.nim, src/app/modules/main/wallet_section/module.nim, src/app/modules/main/wallet_section/overview/io_interface.nim, src/app/modules/main/wallet_section/overview/module.nim, ui/app/AppLayouts/Wallet/views/LeftTabView.qml
=> fix(@wallet): hide watch only account

src/app/modules/startup/models/fetching_data_model.nim, src/app/modules/startup/module.nim, src/app_service/service/general/service.nim, src/backend/mailservers.nim
- https://github.com/status-im/status-go/pull/3585
Fixes: #10969
=> fix(@desktop/onboarding): recovering an account from waku

src/app/modules/main/wallet_section/activity/controller.nim, src/app/modules/main/wallet_section/activity/entry.nim, src/backend/activity.nim, ui/app/AppLayouts/Wallet/views/RightTabView.qml, ui/imports/shared/views/ActivityView.qml
Bumps [status-go to include #3512](https://github.com/status-im/status-go/pull/3512) for the required changes and parse the status information from the status-go API.
=> feat(Wallet): add filter by status to the filter API

ui/app/AppLayouts/Wallet/popups/TransactionAddressMenu.qml, ui/app/AppLayouts/Wallet/views/TransactionDetailView.qml, ui/imports/utils/Constants.qml
Fixes #11013 
Added handling to testnet for transaction menu.
Wallet activity UI
=> fix(@desktop/wallet): Handle testnet explorer links

src/app/modules/main/wallet_section/module.nim, src/app/modules/main/wallet_section/view.nim, ui/app/AppLayouts/Wallet/views/LeftTabView.qml
=> fix(@wallet): left bar selection

storybook/PagesModel.qml, storybook/pages/ActivityFilterMenuPage.qml, ui/app/AppLayouts/Wallet/controls/ActivityFilterMenuItem.qml, ui/app/AppLayouts/Wallet/controls/ActivityTypeCheckBox.qml, ui/app/AppLayouts/Wallet/controls/MenuBackButton.qml, ui/app/AppLayouts/Wallet/controls/StatusWalletMenuRadioButton.qml, ui/app/AppLayouts/Wallet/popups/ActivityFilterMenu.qml, ui/app/AppLayouts/Wallet/popups/filterSubMenus/ActivityPeriodFilterSubMenu.qml, ui/app/AppLayouts/Wallet/popups/filterSubMenus/ActivityTypeFilterSubMenu.qml, ui/app/AppLayouts/Wallet/popups/qmldir, ui/imports/shared/views/HistoryView.qml
Implements the UI for filter by period for the activity list.
please note that this is not covering the whole feature but a part of , there work pending which will be done in subsequent PR's
Activity UI
https://github.com/status-im/status-desktop/assets/60327365/f2097ad9-ed6b-497f-a6db-7fa82ee9f07d
=> feat(@desktop/wallet): Part implementation of the filter activity UI

ui/app/AppLayouts/Profile/views/AboutView.qml, ui/app/mainui/AppMain.qml
Fixes #10990
Hides the button and comments out the line that makes the banner appear
=> chore(update): comment out check for updates for now

ui/imports/shared/popups/SendModal.qml
=> fix(@wallet): send modal max link

storybook/PagesModel.qml, storybook/pages/StatusInputPage.qml, ui/app/AppLayouts/Profile/ProfileLayout.qml, ui/app/AppLayouts/Profile/popups/SyncDeviceCustomizationPopup.qml, ui/app/AppLayouts/Profile/views/SyncingView.qml
Just added this for debugging purposes. The input field is read-only.
=> feat(SyncingView): show installation id in debug mode

ui/app/AppLayouts/Profile/panels/MenuPanel.qml
=> fix(Settings): fix left panel items width

src/app/core/signals/remote_signals/signal_type.nim, src/app/modules/startup/controller.nim, src/app/modules/startup/io_interface.nim, src/app/modules/startup/module.nim, src/app/modules/startup/view.nim, src/app_service/service/accounts/service.nim, ui/main.qml
1. Bump status go to include DB migration
2. Integrate the new DB re-encryption signals to show the re-encryption loading screen
Context: https://github.com/status-im/status-go/pull/3591#issuecomment-1584555668
Login
Password migration from upper case to lower case
=> Bump status-go: integrate DB re-encryption process to increase the page size

storybook/pages/ActivityFilterMenuPage.qml, storybook/src/Models/RecipientModel.qml, ui/app/AppLayouts/Wallet/controls/ActivityFilterTagItem.qml, ui/app/AppLayouts/Wallet/controls/StatusWalletMenuRadioButton.qml, ui/app/AppLayouts/Wallet/controls/qmldir, ui/app/AppLayouts/Wallet/panels/ActivityFilterPanel.qml, ui/app/AppLayouts/Wallet/panels/qmldir, ui/app/AppLayouts/Wallet/popups/ActivityFilterMenu.qml, ui/app/AppLayouts/Wallet/popups/filterSubMenus/ActivityCounterpartyFilterSubMenu.qml, ui/app/AppLayouts/Wallet/popups/filterSubMenus/ActivityPeriodFilterSubMenu.qml, ui/app/AppLayouts/Wallet/popups/filterSubMenus/ActivityTokensFilterSubMenu.qml, ui/imports/shared/controls/InformationTag.qml, ui/imports/shared/views/HistoryView.qml
fixes #10823
Implements the filters with the "X" sign as shown in design https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=12304-273877&t=YRkXdb4fj0KuWmLt-4
HistoryView
Uploading Screen Recording 2023-06-13 at 7.06.42 PM.mov…
=> feat(@desktop/wallet): Complete Filter Activity List

ui/imports/shared/views/chat/InvitationBubbleView.qml
make the button rounded only at the bottom
Fixes #9157
Fixes rounded corners in InvitationBubbleView (Go to Community...)
InvitationBubbleView
=> fix(InvitationBubbleView): inconsistency in message link previews buttons

ui/app/AppLayouts/Chat/views/ChatColumnView.qml, ui/imports/shared/status/StatusChatInput.qml
* Hide chat input when no active chat
* Hide warnings about not active chat
=> fix(ChatColumnView): hide input when no active chat

src/app/modules/main/communities/tokens/controller.nim, src/app/modules/main/communities/tokens/io_interface.nim, src/app/modules/main/communities/tokens/models/token_item.nim, src/app/modules/main/communities/tokens/models/token_model.nim, src/app/modules/main/communities/tokens/module.nim, src/app/modules/main/communities/tokens/view.nim, src/app/modules/main/controller.nim, src/app/modules/main/io_interface.nim, src/app/modules/main/module.nim, src/app/modules/shared_models/section_item.nim, src/app_service/service/community_tokens/async_tasks.nim, src/app_service/service/community_tokens/service.nim, src/app_service/service/transaction/dto.nim, src/backend/community_tokens.nim, ui/app/AppLayouts/Chat/panels/communities/CommunityMintTokensSettingsPanel.qml, ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml, ui/app/AppLayouts/Chat/views/communities/CommunityMintedTokensView.qml, ui/imports/shared/stores/CommunityTokensStore.qml
Issue #10816 
Burning collectibles.
Displaying burning fee.
Displaying remaining supply.
Related status-go pr: https://github.com/status-im/status-go/pull/3588
https://github.com/status-im/status-desktop/assets/61889657/9d522b76-2da3-42a3-b39e-3c4ffdcd668f
=> feat(@desktop/communities): Add burning collectibles functionality

test/ui-test/src/screens/components/saved_address_popup.py, test/ui-test/testSuites/global_shared/scripts/wallet_names.py, test/ui-test/testSuites/suite_wallet/shared/steps/walletSteps.py, test/ui-test/testSuites/suite_wallet/tst_wallet_savedAddresses/test.feature, ui/app/AppLayouts/Wallet/controls/StatusNetworkSelector.qml
Fixes https://github.com/status-im/desktop-qa-automation/issues/63
UI tests
=> chore(@e2e_tests): split scenario to create and edit, improved edit logic

ui/app/AppLayouts/Chat/panels/communities/CommunityMembersSettingsPanel.qml, ui/app/AppLayouts/Chat/panels/communities/CommunityMembersTabPanel.qml, ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
=> fix: Community settings member context menu

test/ui-test/src/drivers/elements/checkbox.py, test/ui-test/src/screens/StatusWalletScreen.py, test/ui-test/src/screens/components/saved_address_popup.py, test/ui-test/testSuites/suite_wallet/shared/steps/walletSteps.py, test/ui-test/testSuites/suite_wallet/tst_wallet_savedAddresses/test.feature
Interact with network selector only if saved address is in hex
e2e tests
=> chore(@e2e_tests): add logic to use networks selector only if address is hex

src/app_service/service/contacts/service.nim
Fixes https://github.com/status-im/status-desktop/issues/11160
https://github.com/status-im/status-desktop/assets/25482501/3ca30f18-e8cc-4671-bc28-2d4f9cf80b87
=> fix: synced nickname is only updated after restart 

storybook/src/Storybook/InspectionItem.qml, storybook/src/Storybook/InspectionItemsList.qml, storybook/src/Storybook/InspectionPanel.qml, storybook/src/Storybook/InspectionUtils.qml, storybook/src/Storybook/InspectionWindow.qml
It iterates the inspection tool towards more usable tool:
- more meaningful item names
- no clipping of auxiliary lines
- better selection of parent item to draw auxiliary lines
- finding item on the left list by clicking
- proper handling of SpriteSequence
Strybook's inspection tool
=> feat(Storybook): inspection tool improvements

ui/app/AppLayouts/Chat/views/communities/CommunityNewTokenView.qml
Three tiny commits covering:
- Fixes: https://github.com/status-im/status-desktop/issues/11122
- Fixes: https://github.com/status-im/status-desktop/issues/11190
- Fixes: https://github.com/status-im/status-desktop/issues/11187
CommunityNewTokenView
[Záznam obrazovky z 2023-06-22 10-41-23.webm](https://github.com/status-im/status-desktop/assets/5377645/c8e791cb-2eab-4a7f-bbfe-1c88674ac615)
=> Various token minting UI fixes

src/app/modules/main/wallet_section/activity/controller.nim, ui/app/AppLayouts/Wallet/panels/ActivityFilterPanel.qml, ui/app/AppLayouts/Wallet/popups/ActivityFilterMenu.qml, ui/app/AppLayouts/Wallet/popups/filterSubMenus/ActivityCounterpartyFilterSubMenu.qml, ui/app/AppLayouts/Wallet/popups/filterSubMenus/ActivityTokensFilterSubMenu.qml, ui/app/AppLayouts/Wallet/stores/ActivityFiltersStore.qml, ui/imports/shared/views/HistoryView.qml
1. Handling case where filters result in no results
2. Fixed period filter
3. Used recipient model from go side
https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=15679-490389&t=koVmCHszO5TMb76J-4
Activity View
https://github.com/status-im/status-desktop/assets/60327365/857e22ab-8397-4f79-82e8-d650ec18b7e8
=> fix(@desktop/wallet): Activity UI filtering improvements

storybook/src/Models/MintedTokensModel.qml, ui/app/AppLayouts/Chat/panels/communities/CommunityAirdropsSettingsPanel.qml, ui/app/AppLayouts/Chat/panels/communities/CommunityMintTokensSettingsPanel.qml, ui/app/AppLayouts/Chat/views/communities/CommunityMintedTokensView.qml, ui/app/AppLayouts/Chat/views/communities/CommunityNewAirdropView.qml, ui/app/AppLayouts/Chat/views/communities/CommunityTokenView.qml
Cherry pick: https://github.com/status-im/status-desktop/pull/11212
Mint Tokens
=> Fix some mint token UI issues

ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
=> fix: don't cause a wrong redirect when performing community admin

src/app/modules/main/profile_section/wallet/accounts/controller.nim, src/app/modules/main/profile_section/wallet/accounts/io_interface.nim, src/app/modules/main/profile_section/wallet/accounts/item.nim, src/app/modules/main/profile_section/wallet/accounts/model.nim, src/app/modules/main/profile_section/wallet/accounts/module.nim, src/app/modules/main/profile_section/wallet/accounts/view.nim, src/app/modules/main/wallet_section/accounts/item.nim, src/app/modules/main/wallet_section/accounts/model.nim, src/app/modules/main/wallet_section/module.nim, src/app/modules/shared/wallet_utils.nim, src/app_service/service/wallet_account/dto.nim, src/app_service/service/wallet_account/service.nim, src/backend/backend.nim, ui/app/AppLayouts/Profile/stores/WalletStore.qml, ui/app/AppLayouts/Profile/views/WalletView.qml, ui/app/AppLayouts/Profile/views/wallet/AccountOrderView.qml, ui/app/AppLayouts/Profile/views/wallet/MainView.qml, ui/app/AppLayouts/Wallet/views/LeftTabView.qml
#11133
status-go: https://github.com/status-im/status-go/pull/3645
=> feat(@wallet): Sort account by position

src/app/modules/main/view.nim, src/app_service/service/community_tokens/service.nim, src/app_service/service/transaction/service.nim, vendor/DOtherSide/lib/src/DOtherSide.cpp
Cherry-pick of https://github.com/status-im/status-desktop/pull/11196
=> [CHERRY-PICK] Fix crash when Filter Proxy is collected by nim GC

ui/app/AppLayouts/Onboarding/OnboardingLayout.qml
=> fix(@desktop/onboarding): Keycard -> Factory reset button is not calling any action

ui/app/AppLayouts/Chat/panels/communities/CommunityMintTokensSettingsPanel.qml
fix some refactoring error
Fixes #11287
Fixes being unable to mint a token
CommunityMintTokensSettingsPanel
=> fix: Can't deploy collectible via community's mint token section

src/app/modules/main/wallet_section/send/account_item.nim, src/app/modules/main/wallet_section/send/accounts_model.nim, ui/app/AppLayouts/Wallet/popups/ReceiveModal.qml, ui/imports/shared/popups/SendModal.qml
=> feat(@wallet): all accounts list are ordered by position

src/app/modules/main/controller.nim, src/app/modules/main/io_interface.nim, src/app/modules/main/module.nim, src/app/modules/main/profile_section/devices/controller.nim, src/app/modules/main/profile_section/devices/io_interface.nim, src/app/modules/main/profile_section/devices/module.nim, src/app/modules/main/profile_section/devices/view.nim, src/app/modules/shared_modules/keycard_popup/controller.nim, src/app/modules/shared_modules/keycard_popup/io_interface.nim, src/app/modules/shared_modules/keycard_popup/module.nim, src/app/modules/startup/controller.nim, src/app_service/service/accounts/service.nim, src/app_service/service/devices/dto/local_pairing_event.nim, src/app_service/service/devices/dto/local_pairing_status.nim, src/app_service/service/devices/service.nim, ui/app/AppLayouts/Profile/popups/SetupSyncingPopup.qml, ui/app/AppLayouts/Profile/stores/DevicesStore.qml, ui/app/AppLayouts/Profile/views/SyncingView.qml, ui/app/AppLayouts/Wallet/stores/RootStore.qml
- https://github.com/status-im/status-go/pull/3594
Closes: #10983
https://github.com/status-im/status-desktop/assets/86303051/b881a0f3-f992-427e-9932-9ee238622886
=> feat(@desktop/syncing): keypair syncing - recovering from another device with Keycard related profile

src/app/modules/main/communities/tokens/controller.nim, src/app/modules/main/communities/tokens/io_interface.nim, src/app/modules/main/communities/tokens/models/token_model.nim, src/app/modules/main/communities/tokens/module.nim, src/app/modules/main/communities/tokens/view.nim, src/app_service/service/community_tokens/async_tasks.nim, src/app_service/service/community_tokens/dto/community_token.nim, src/app_service/service/community_tokens/dto/deployment_parameters.nim, src/app_service/service/community_tokens/service.nim, src/backend/community_tokens.nim, ui/app/AppLayouts/Communities/panels/MintTokensSettingsPanel.qml, ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml, ui/imports/shared/stores/CommunityTokensStore.qml
Handling assets deployment (w/o burn and mint functionality)
Related status-go pr: https://github.com/status-im/status-go/pull/3636/files
https://github.com/status-im/status-desktop/assets/61889657/442fa0e3-a28e-4d91-8e38-14f8f2147967
=> 10987 assets deployment

ui/app/AppLayouts/Chat/views/ChatColumnView.qml, ui/app/AppLayouts/Chat/views/ChatMessagesView.qml, ui/imports/shared/status/StatusChatInput.qml
cherry pick https://github.com/status-im/status-desktop/pull/11195 from `release/0.13.x`
=> [CHERRY-PICK] fix: chat input preserved properties bugs

ui/app/AppLayouts/Profile/views/KeycardView.qml, ui/app/mainui/AppMain.qml, ui/imports/shared/popups/keycard/states/ManageAccounts.qml, ui/imports/utils/Utils.qml
=> fix(@desktop/keycard): create card with new seed phrase always fails

ui/app/AppLayouts/Profile/views/KeycardView.qml, ui/app/mainui/AppMain.qml, ui/imports/shared/popups/keycard/states/ManageAccounts.qml, ui/imports/utils/Utils.qml
Bringing fixes #11311 and #11346 to `release/0.13.x`
=> Bringing fixes #11311 and #11346 to `release/0.13.x`

ui/app/AppLayouts/Wallet/controls/SavedAddressesDelegate.qml, ui/app/AppLayouts/Wallet/stores/RootStore.qml, ui/app/AppLayouts/Wallet/views/SavedAddressesView.qml
=> fix(@wallet): test etherscan link

ui/app/AppLayouts/Communities/views/EditCommunityTokenView.qml
Closes #10783
EditCommunityToken: adjusted validation error messages for emojis
EditCommunityToken
https://github.com/status-im/status-desktop/assets/31625338/7da284c1-3100-4e15-83ca-1486813d1bb7
=> fix(EditCommunityToken): adjusted validation error messages for emojis

src/app/modules/main/communities/tokens/controller.nim, src/app/modules/main/communities/tokens/io_interface.nim, src/app/modules/main/communities/tokens/module.nim, src/app/modules/main/communities/tokens/view.nim, src/app_service/service/community_tokens/service.nim, src/backend/community_tokens.nim, ui/imports/shared/stores/CommunityTokensStore.qml
Needs: https://github.com/status-im/status-go/pull/3705
Closes: #10317
=> feat: add support for cropped asset data when deploying community NFTs

src/app/modules/main/wallet_section/activity/controller.nim, src/app/modules/main/wallet_section/activity/events_handler.nim, src/app/modules/main/wallet_section/activity/status.nim, src/app_service/service/transaction/service.nim, src/backend/transactions.nim, ui/StatusQ/src/StatusQ/Core/Theme/ThemePalette.qml, ui/app/AppLayouts/Wallet/stores/ActivityFiltersStore.qml, ui/imports/shared/stores/RootStore.qml, ui/imports/shared/views/HistoryView.qml
fixes #9995 
Show a reload hint button for the user to refresh the filter
https://github.com/status-im/status-desktop/assets/47554641/e37fd326-7938-4cf1-9952-2e59de7b1d90
Also, refactor `activity.Controller` by extacting events and status responsibilities, see first commit.
=> feat(wallet) reload on new transaction downloaded quick win

ui/app/AppLayouts/Communities/controls/ExtendedDropdownContent.qml, ui/app/AppLayouts/Communities/panels/PermissionsSettingsPanel.qml, ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml, ui/app/AppLayouts/Communities/views/EditPermissionView.qml
`CommunitySettingsView` refactored:
- sections cross referencing simplified
- stack components directly define content of the left list
- fixed navigation from Permissions section to minting
- various code style fixes
- not needed top level Loader removed
Closes: https://github.com/status-im/status-desktop/issues/11179
Closes: https://github.com/status-im/status-desktop/issues/11363
`CommunitySettingsView`
=> [Community Settings]: `CommunitySettingsView.qml` refactor

src/app/modules/main/wallet_section/accounts/item.nim, src/app/modules/main/wallet_section/accounts/model.nim, src/app/modules/shared/wallet_utils.nim, ui/app/AppLayouts/Wallet/views/AccountContextMenu.qml
fixes #11398
WalletType is never empty anymore!
=> fix(@wallet): prevent delete main account

src/app/modules/main/wallet_section/activity/controller.nim, src/app/modules/main/wallet_section/filter.nim, src/app/modules/main/wallet_section/module.nim, ui/app/AppLayouts/Wallet/panels/WalletHeader.qml
fixes #11397
Also correctly use the filter
=> fix(@wallet): overview balance with symbol

src/app/core/signals/remote_signals/base.nim, src/app/core/signals/remote_signals/node.nim, src/app/core/signals/signals_manager.nim, src/app/core/signals/types.nim, src/app/modules/startup/controller.nim
This PR handles changes made on the status-go side in `e08aad7d731817169d6c7140fabc7e02d277dd19` commit.
Fixes: #11454
=> fix(@desktop/onboarding): app loading screen displayed forever when creating a new Status account

ui/app/AppLayouts/Profile/views/SyncingView.qml
=> fix(@desktop/general): make "Backup data" button available only for the "development" build

storybook/PagesModel.qml, storybook/figma.json, storybook/pages/MintTokensSettingsPanelPage.qml, storybook/pages/OwnerTokenWelcomeViewPage.qml, ui/app/AppLayouts/Communities/panels/MintTokensSettingsPanel.qml, ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml, ui/app/AppLayouts/Communities/views/OwnerTokenWelcomeView.qml, ui/app/AppLayouts/Communities/views/qmldir, ui/imports/shared/controls/DisabledTooltipButton.qml
Closes #11292
- Created new `Owner Token` and `TokenMaster Token` welcome screen.
- Navigations added.
- Storybook support added.
Community Settings / Mint token
- App:
https://github.com/status-im/status-desktop/assets/97019400/2a307bfa-554e-4fe8-99e4-2d5ffb5d636b
- Storybook:
https://github.com/status-im/status-desktop/assets/97019400/b91a5dd1-6baa-4bc5-8e9d-772da0a7d389
=> feat(OwnerToken): Add Mint Owner token view

src/app/boot/app_controller.nim, src/app/modules/startup/controller.nim, src/app/modules/startup/internal/biometrics_state.nim, src/app/modules/startup/internal/keycard_pin_set_state.nim, src/app/modules/startup/io_interface.nim, src/app/modules/startup/module.nim, src/app_service/service/wallet_account/service.nim, src/backend/backend.nim
=> fix(@desktop/onboarding): cannot run any keycard flow after creating a Keycard replacement

src/app/modules/shared_modules/keycard_popup/internal/copying_keycard_state.nim, src/app/modules/shared_modules/keycard_popup/io_interface.nim, src/app/modules/shared_modules/keycard_popup/module.nim
=> fix(@desktop/onboarding): keycard is not shown in settings after first launch

ui/app/AppLayouts/Wallet/views/RightTabView.qml
=> fix(@wallet): reset tab view on filter change

src/app/modules/main/communities/controller.nim, src/app/modules/main/communities/io_interface.nim, src/app/modules/main/communities/module.nim, src/app/modules/main/communities/view.nim, src/app/modules/main/profile_section/contacts/controller.nim, src/app/modules/main/profile_section/contacts/io_interface.nim, src/app/modules/main/profile_section/contacts/module.nim, src/app/modules/main/profile_section/contacts/view.nim, src/app_service/service/community/service.nim, src/app_service/service/contacts/service.nim, src/backend/communities.nim, src/backend/contacts.nim, ui/app/AppLayouts/Profile/stores/ContactsStore.qml, ui/imports/shared/views/ProfileDialogView.qml, ui/imports/utils/Utils.qml
Part of: #11448
Adds usage of new links generators
Contacts, Communities 
=> feat(new-links-format): Adds new links to UI

src/app/modules/main/profile_section/wallet/networks/controller.nim, src/app/modules/main/profile_section/wallet/networks/io_interface.nim, src/app/modules/main/profile_section/wallet/networks/module.nim, src/app/modules/main/profile_section/wallet/networks/view.nim, src/app_service/service/wallet_account/async_tasks.nim, src/app_service/service/wallet_account/service.nim, src/backend/backend.nim, ui/app/AppLayouts/Profile/stores/WalletStore.qml, ui/app/AppLayouts/Profile/views/wallet/EditNetworkForm.qml, ui/app/AppLayouts/Profile/views/wallet/EditNetworkView.qml
status-go: https://github.com/status-im/status-go/pull/3740
=> feat(@wallet): verify json rpc URL

src/app_service/service/community_tokens/service.nim, src/app_service/service/transaction/dto.nim
Fixing transaction system for minting operations.
Upgrading pending transaction types for community token operations according to status-go types.
Issue #11565
=> 11565 fix tx system tokens

src/app_service/service/community_tokens/service.nim, ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml
=> fix: display notification when asset deployment fails

src/app/modules/main/module.nim
Fixes: #10892
Open user profile or chat if user is contact
Deeplinks
=> feat(deeplinks): Open user profile or chat if user is contact

src/app/modules/main/chat_section/chat_content/users/controller.nim, src/app/modules/main/chat_section/chat_content/users/module.nim, src/app/modules/main/chat_section/module.nim, src/app/modules/main/communities/module.nim, src/app/modules/main/module.nim, src/app/modules/shared_models/member_item.nim, src/app/modules/shared_models/member_model.nim, src/app_service/service/chat/dto/chat.nim
Fixes #11540
One thing to note, if we end up fixing this issue https://github.com/status-im/status-desktop/issues/11573, we'll have to get the member address from somewhere else then the community description most likely.
The model wouldn't change though, so you can use this in QML.
=> feat(member_model): add airdropAddress to members_model

src/app_service/service/chat/dto/chat.nim
=> fix(dto/chat): fix toChannelMember where `isAidropAddress` can be null

src/app/modules/main/communities/tokens/io_interface.nim, src/app/modules/main/communities/tokens/models/token_item.nim, src/app/modules/main/communities/tokens/models/token_model.nim, src/app/modules/main/communities/tokens/module.nim, src/app/modules/main/controller.nim, src/app/modules/main/io_interface.nim, src/app/modules/main/module.nim, src/app/modules/shared_models/section_item.nim, src/app_service/common/types.nim, src/app_service/service/community_tokens/service.nim, src/app_service/service/transaction/service.nim, ui/app/AppLayouts/Communities/panels/MintTokensSettingsPanel.qml
Expose burningState in the model.
Update burningState when burning operation changes its status.
Issue #11076
https://github.com/status-im/status-desktop/assets/61889657/fff2d108-f349-45ba-b509-fa050c6e82dc
=> feat(@desktop/communities): Add burning state logic

src/app/core/signals/remote_signals/messages.nim, src/app/modules/main/profile_section/keycard/controller.nim, src/app/modules/main/profile_section/keycard/io_interface.nim, src/app/modules/main/profile_section/keycard/module.nim, src/app/modules/main/profile_section/wallet/accounts/controller.nim, src/app/modules/main/profile_section/wallet/accounts/io_interface.nim, src/app/modules/main/profile_section/wallet/accounts/item.nim, src/app/modules/main/profile_section/wallet/accounts/model.nim, src/app/modules/main/profile_section/wallet/accounts/module.nim, src/app/modules/main/profile_section/wallet/accounts/view.nim, src/app/modules/main/wallet_section/accounts/item.nim, src/app/modules/main/wallet_section/accounts/model.nim, src/app/modules/main/wallet_section/send/account_item.nim, src/app/modules/main/wallet_section/send/accounts_model.nim, src/app/modules/shared_models/wallet_account_item.nim, src/app_service/service/wallet_account/service.nim, src/backend/backend.nim, ui/StatusQ/src/StatusQ/Components/StatusDraggableListItem.qml, ui/app/AppLayouts/Profile/stores/WalletStore.qml, ui/app/AppLayouts/Profile/views/wallet/AccountOrderView.qml
- https://github.com/status-im/status-go/pull/3763
This PR fixes:
#11508 
#11512 
#11513 
Functionallity:
https://github.com/status-im/status-desktop/assets/86303051/186b1168-30f8-4894-a65a-6877ff2b15fa
=> Account order - drag and drop accounts in account list is not smooth

src/app/modules/main/chat_section/controller.nim, src/app/modules/main/chat_section/module.nim, src/app/modules/main/communities/controller.nim, src/app/modules/main/communities/module.nim, src/app/modules/main/module.nim, src/app/modules/shared_models/token_permission_chat_list_item.nim, src/app/modules/shared_models/token_permission_chat_list_model.nim, src/app/modules/shared_models/token_permission_item.nim, src/app/modules/shared_models/token_permissions_model.nim, src/app_service/service/chat/service.nim
Fixes: #11481
Add channel name to token permission chat list model.
Community token permissions
=> feat(token-permissions): Add channel name to token permission chat list model

src/app/boot/app_controller.nim, src/app/modules/main/profile_section/keycard/module.nim, src/app/modules/main/profile_section/wallet/accounts/controller.nim, src/app/modules/main/profile_section/wallet/accounts/module.nim, src/app/modules/shared/keypairs.nim, src/app/modules/shared_models/keypair_account_item.nim, src/app/modules/shared_models/keypair_account_model.nim, src/app/modules/shared_models/keypair_item.nim, src/app/modules/shared_modules/keycard_popup/controller.nim, src/app/modules/shared_modules/keycard_popup/module.nim, src/app_service/service/wallet_account/service.nim, storybook/PagesModel.qml, storybook/pages/AccountViewPage.qml, storybook/pages/ProfileAccountsPage.qml, test/ui-test/src/screens/SettingsScreen.py, test/ui-test/testSuites/global_shared/scripts/settings_names.py, ui/app/AppLayouts/Profile/ProfileLayout.qml, ui/app/AppLayouts/Profile/controls/WalletAccountDetailsKeypairItem.qml, ui/app/AppLayouts/Profile/controls/WalletAccountDetailsListItem.qml, ui/app/AppLayouts/Profile/controls/WalletKeyPairDelegate.qml, ui/app/AppLayouts/Profile/stores/WalletStore.qml, ui/app/AppLayouts/Profile/views/SettingsContentBase.qml, ui/app/AppLayouts/Profile/views/WalletView.qml, ui/app/AppLayouts/Profile/views/wallet/AccountView.qml, ui/app/AppLayouts/Profile/views/wallet/MainView.qml, ui/app/AppLayouts/Profile/views/wallet/qmldir, ui/app/AppLayouts/Wallet/controls/AccountHeaderGradient.qml, ui/imports/utils/Utils.qml
fixes #11537
new accounts view for wallet settings https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=15479-316147&mode=dev
https://github.com/status-im/status-desktop/assets/60327365/bbcfd062-f26a-4638-b722-fb0c71ca6788
=> feat(@desktop/wallet): Account view - New Account view UI

src/app/modules/startup/controller.nim, src/app/modules/startup/internal/biometrics_state.nim, src/app_service/common/network_constants.nim, src/app_service/service/accounts/service.nim, src/app_service/service/devices/service.nim, src/backend/accounts.nim
- https://github.com/status-im/status-go/pull/3781
Corresponding `nim-status-go` PR:
- https://github.com/status-im/nim-status-go/pull/26
Fixes: #11582
=> fix(@desktop/syncing): discard messages coming from waku if user didn't follow recover account path

src/app/modules/main/communities/controller.nim, src/app/modules/main/communities/io_interface.nim, src/app/modules/main/communities/module.nim, src/app/modules/main/communities/view.nim, src/app/modules/main/controller.nim, src/app/modules/main/profile_section/notifications/controller.nim, src/app_service/service/community/service.nim, src/backend/communities.nim
Close #11475
Add endpoint to remove community private key (owner node)
Communities
=> feat: Add api to remove a community private key (nim part)

ui/app/AppLayouts/Wallet/WalletLayout.qml, ui/app/AppLayouts/Wallet/controls/NetworkFilter.qml, ui/app/AppLayouts/Wallet/panels/WalletFooter.qml, ui/app/AppLayouts/Wallet/views/LeftTabView.qml
* Left bar hover color fix
* Network filter darkmode border
* No footer in all addresses
fixes #11659
=> fix(@wallet): wallet color fixes

storybook/pages/CommunityTokenViewPage.qml, storybook/pages/EditOwnerTokenViewPage.qml, storybook/pages/MintTokensSettingsPanelPage.qml, ui/StatusQ/include/StatusQ/modelutilsinternal.h, ui/StatusQ/src/StatusQ/Components/StatusEmojiAndColorComboBox.qml, ui/StatusQ/src/StatusQ/Controls/StatusComboBox.qml, ui/StatusQ/src/StatusQ/Core/Utils/ModelUtils.qml, ui/StatusQ/src/modelutilsinternal.cpp, ui/app/AppLayouts/Communities/panels/FeesPanel.qml, ui/app/AppLayouts/Communities/panels/MintTokensSettingsPanel.qml, ui/app/AppLayouts/Communities/popups/SignMultiTokenTransactionsPopup.qml, ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml, ui/app/AppLayouts/Communities/views/CommunityTokenView.qml, ui/app/AppLayouts/Communities/views/EditCommunityTokenView.qml, ui/app/AppLayouts/Communities/views/EditOwnerTokenView.qml
- Fee box added to owner/token master tokens minting flow, updated sign popup
- Fee box added to standard tokens minting flow, updated sign popup
- `ModelUtils` - `modelToArray` method - `roles` param made optional, support for nested models
Closes: https://github.com/status-im/status-desktop/issues/11303
Standard minting flow, Owner/TokenMaster tokens minting flow
https://github.com/status-im/status-desktop/assets/20650004/17efcb1f-db81-4a17-b79f-f2e4941ed246
https://github.com/status-im/status-desktop/assets/20650004/107f6ad2-69e1-4efe-b2c3-1da2608a503e
=> feat(Communities): Add fees box and updated sign popup to minting flows

src/app/modules/main/chat_section/controller.nim, src/app/modules/main/chat_section/io_interface.nim, src/app/modules/main/chat_section/module.nim, src/app/modules/main/chat_section/view.nim, src/app/modules/main/communities/controller.nim, src/app/modules/main/communities/io_interface.nim, src/app/modules/main/communities/module.nim, src/app/modules/main/communities/view.nim, ui/StatusQ/src/assets.qrc, ui/app/AppLayouts/Chat/ChatLayout.qml, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Communities/CommunitiesPortalLayout.qml, ui/app/AppLayouts/Communities/stores/CommunitiesStore.qml, ui/app/AppLayouts/Communities/views/CommunityColumnView.qml, ui/app/AppLayouts/Profile/views/CommunitiesView.qml, ui/app/AppLayouts/stores/RootStore.qml, ui/app/mainui/Popups.qml, ui/imports/shared/popups/CommunityIntroDialog.qml, ui/imports/shared/popups/ImportCommunityPopup.qml, ui/imports/utils/Global.qml
Closes #11242
Import community popup: changes in import popup for public keys
Import community popup
https://github.com/status-im/status-desktop/assets/31625338/8fe2100f-a0ee-4ac2-bc1e-474c7146b7e1
=> feat(Communities): changes in import popup for public keys

src/app/modules/main/wallet_section/activity/controller.nim, src/backend/activity.nim, ui/app/AppLayouts/Wallet/panels/ActivityFilterPanel.qml, ui/app/AppLayouts/Wallet/stores/ActivityFiltersStore.qml
Also, optimize for no filter instead of giving a specific time range.
=> fix(wallet): fix activity time filter

ci/Jenkinsfile.combined, ci/Jenkinsfile.linux, ci/Jenkinsfile.macos, ci/Jenkinsfile.tests-e2e, ci/Jenkinsfile.tests-imports, ci/Jenkinsfile.tests-nim, ci/Jenkinsfile.windows, ci/cpp/Jenkinsfile.linux, ci/cpp/Jenkinsfile.macos, ci/cpp/Jenkinsfile.windows
Depends on:
* https://github.com/status-im/status-jenkins-lib/pull/71
=> ci: fix use of release Infura key for E2E runs

ui/app/AppLayouts/Communities/panels/MintTokensSettingsPanel.qml
Fixes #11731
- It updates `MintTokensSettingsPanel.qml` to properly behaves when reseting navigation.
Community Settings / Tokens
=> fix(Mint): No redirect to Tokens screen when minting a token

src/app/modules/main/communities/controller.nim, src/app/modules/main/communities/io_interface.nim, src/app/modules/main/communities/module.nim, src/app/modules/main/communities/view.nim, src/app_service/service/community/service.nim, src/backend/communities.nim
Needed for the Import popup work by @alexandraB99 
status-go PR https://github.com/status-im/status-go/pull/3828
=> feat(communities): add getCommunityPublicKeyFromPrivateKey function

src/app/modules/main/communities/controller.nim, src/app_service/service/community/async_tasks.nim, src/app_service/service/community/service.nim, ui/app/AppLayouts/Chat/stores/RootStore.qml
Fixes #11693
I couldn't actually reproduce the issue, but I can see that we were calling the status-go function in the same thread, so it makes sense that it could freeze for some.
@alexjba can you test this PR and see if it fixes the issue for you? I'm not sure if you have a loading indicator already, but at least it shouldn't be frozen.
=> Fix slow/frozen import

ui/app/AppLayouts/stores/RootStore.qml, ui/app/mainui/Popups.qml
Closes #11773
ImportCommunities: Add token models needed for CommunityIntroPopup
ImportCommunities: community intro popup
=> [ImportCommunities] Add token models needed for CommunityIntroPopup

src/app/modules/main/chat_section/chat_content/io_interface.nim, src/app/modules/main/chat_section/chat_content/module.nim, src/app/modules/main/chat_section/chat_content/view.nim, src/app/modules/main/chat_section/controller.nim, src/app/modules/main/chat_section/io_interface.nim, src/app/modules/main/chat_section/model.nim, src/app/modules/main/chat_section/module.nim, src/app/modules/main/chat_section/view.nim, storybook/pages/JoinCommunityPermissionsEditor.qml, storybook/pages/JoinPermissionsOverlayPanelPage.qml, ui/app/AppLayouts/Chat/ChatLayout.qml, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Chat/views/ChatView.qml, ui/app/AppLayouts/Communities/panels/JoinCommunityCenterPanel.qml, ui/app/AppLayouts/Communities/panels/JoinPermissionsOverlayPanel.qml, ui/app/AppLayouts/Communities/views/JoinCommunityView.qml
closes: #11157
Adds pending state to permissions check.
- join community view overlay
https://github.com/status-im/status-desktop/assets/33099791/b11201be-abd3-4f6d-be64-d5b69c1790b0
https://github.com/status-im/status-desktop/assets/33099791/dc48f251-966e-4c7d-bc03-2ba5ef32564f
=> feat(communities): add check permissions pending state

storybook/pages/BurnTokensPopupPage.qml, ui/app/AppLayouts/Communities/panels/MintTokensSettingsPanel.qml, ui/app/AppLayouts/Communities/popups/BurnTokensPopup.qml, ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml, ui/imports/shared/stores/CommunityTokensStore.qml
Closes #11609
- It adds fee box into the Burn popup component.
- It updates storybook accordingly.
Community Settings / Tokens / Burn
https://github.com/status-im/status-desktop/assets/97019400/e93ecc9c-a5bf-442b-932f-91b589f09f5d
=> feat(BurnToken): Add fee box with network selector to Burn popup

src/app/modules/shared_models/section_model.nim
Fixes #11091
[req-to-join.webm](https://github.com/status-im/status-desktop/assets/11926403/d5ee5f55-1109-417f-a920-6a29c1e35097)
=> fix(section_model): fix missing role to update the access (request)

storybook/pages/SortableTokenHoldersListPage.qml, storybook/pages/TokenHoldersPanelPage.qml, storybook/src/Models/TokenHoldersModel.qml, ui/app/AppLayouts/Communities/panels/SortableTokenHoldersList.qml, ui/app/AppLayouts/Communities/panels/SortableTokenHoldersPanel.qml, ui/app/AppLayouts/Communities/panels/TokenHoldersList.qml, ui/app/AppLayouts/Communities/panels/TokenHoldersPanel.qml, ui/app/AppLayouts/Communities/panels/TokenHoldersProxyModel.qml, ui/app/AppLayouts/Communities/popups/RemotelyDestructPopup.qml
Closes #11032
TokenHoldersPanel: Added sorting feature
TokenHoldersPanel
https://github.com/status-im/status-desktop/assets/31625338/54a50d92-2d9b-432e-8c71-5122356a6f77
https://github.com/status-im/status-desktop/assets/31625338/386cd482-3170-4678-a7bb-c08b0c42dde5
=> fix(TokenHoldersPanel): Added sorting feature

src/app/modules/main/module.nim, src/app/modules/main/profile_section/wallet/accounts/module.nim, src/app/modules/main/profile_section/wallet/networks/controller.nim, src/app/modules/main/profile_section/wallet/networks/view.nim, src/app/modules/main/view.nim, src/app_service/service/network/service.nim, src/app_service/service/settings/service.nim, ui/app/AppLayouts/Profile/stores/WalletStore.qml, ui/app/AppLayouts/Profile/views/WalletView.qml, ui/app/AppLayouts/Profile/views/wallet/EditNetworkView.qml, ui/app/AppLayouts/Profile/views/wallet/NetworksView.qml, ui/app/mainui/AppMain.qml
fixes #11719
Fixes some errors I found + notifications for updating network url + notification for include watch only address
https://github.com/status-im/status-desktop/assets/60327365/b544a8c6-6237-48d2-9137-db22f59652b0
=> feat(@desktop/wallet): Wallet settings - Notification after each action

ui/imports/shared/popups/addaccount/states/EnterPrivateKey.qml
=> feat(@wallet): private key multiline

Makefile, ci/Jenkinsfile.combined, ci/Jenkinsfile.linux, ci/Jenkinsfile.macos, ci/Jenkinsfile.tests-e2e, ci/Jenkinsfile.tests-imports, ci/Jenkinsfile.tests-nim, ci/Jenkinsfile.windows, ci/cpp/Jenkinsfile.linux, ci/cpp/Jenkinsfile.macos, ci/cpp/Jenkinsfile.windows, scripts/notarize-macos-pkg.sh
See the issue: https://github.com/status-im/status-desktop/issues/11067
Release CI
=> ci: switch altool to notarytool

ui/app/AppLayouts/Wallet/views/LeftTabView.qml
=> fix(@desktop/wallet): Wallet -> Main screen: + button is overlapped

src/app/modules/main/module.nim, src/app/modules/main/profile_section/wallet/accounts/controller.nim, src/app/modules/main/profile_section/wallet/accounts/module.nim, src/app/modules/main/profile_section/wallet/accounts/view.nim, src/app/modules/main/view.nim, src/app/modules/shared_models/keypair_model.nim, src/app_service/service/wallet_account/service_account.nim, src/app_service/service/wallet_account/signals_and_payloads.nim, storybook/pages/ProfileAccountsPage.qml, ui/app/AppLayouts/Profile/controls/WalletAccountDelegate.qml, ui/app/AppLayouts/Profile/popups/RemoveKeypairPopup.qml, ui/app/AppLayouts/Profile/popups/qmldir, ui/app/AppLayouts/Profile/views/WalletView.qml, ui/app/mainui/AppMain.qml, ui/imports/shared/controls/qmldir
fixes #11734
Implements the popup : https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?node-id=15814%3A385398&mode=dev
https://github.com/status-im/status-desktop/assets/60327365/37bff172-6eb0-4a8c-9746-93eb71c005ad
=> feat(@desktop/wallet): Update remove keypair popup to match the Figma

src/app/modules/shared_modules/keypair_import/controller.nim, src/app/modules/shared_modules/keypair_import/internal/scan_qr_state.nim, src/app/modules/shared_modules/keypair_import/internal/select_import_method_state.nim, src/app/modules/shared_modules/keypair_import/internal/select_keypair_state.nim, src/app/modules/shared_modules/keypair_import/internal/state.nim, src/app/modules/shared_modules/keypair_import/internal/state_factory.nim, src/app/modules/shared_modules/keypair_import/io_interface.nim, src/app/modules/shared_modules/keypair_import/module.nim, src/app/modules/shared_modules/keypair_import/view.nim, src/app_service/service/wallet_account/dto/keypair_dto.nim, src/app_service/service/wallet_account/service_account.nim, ui/app/AppLayouts/Profile/popups/WalletKeypairAccountMenu.qml, ui/app/AppLayouts/Profile/views/wallet/MainView.qml, ui/imports/shared/popups/keycard/helpers/KeyPairItem.qml, ui/imports/shared/popups/keycard/helpers/KeyPairList.qml, ui/imports/shared/popups/keycard/states/SelectKeyPair.qml, ui/imports/shared/popups/keypairimport/KeypairImportPopup.qml, ui/imports/shared/popups/keypairimport/states/SelectImportMethod.qml, ui/imports/shared/popups/keypairimport/states/SelectKeypair.qml, ui/imports/utils/Constants.qml, ui/imports/utils/Utils.qml
- https://github.com/status-im/status-go/pull/3868
Closes the second part of https://github.com/status-im/status-desktop/issues/11779
=> feat(@desktop/syncing): make a not operable account fully operable, part 2

storybook/pages/RemotelyDestructPopupPage.qml, ui/app/AppLayouts/Communities/panels/MintTokensSettingsPanel.qml, ui/app/AppLayouts/Communities/panels/TokenHoldersList.qml, ui/app/AppLayouts/Communities/popups/RemotelyDestructPopup.qml, ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml, ui/imports/shared/stores/CommunityTokensStore.qml
Closes #11624
Added FeesBox in RemotelyDestructPopup
RemotelyDestructPopup
https://github.com/status-im/status-desktop/assets/31625338/66bd0243-ef1c-45da-98ed-8edd902f6d87
=> feat(RemotelyDestructPopup): Added fee box

test/ui-pytest/configs/_local.py.ci, test/ui-pytest/configs/_local.py.default, test/ui-pytest/configs/testpath.py, test/ui-pytest/conftest.py, test/ui-pytest/constants/user.py, test/ui-pytest/driver/aut.py, test/ui-pytest/driver/server.py, test/ui-pytest/gui/objects_map/onboarding_names.py, test/ui-pytest/gui/screens/onboarding.py, test/ui-pytest/pytest.ini, test/ui-pytest/scripts/utils/local_system.py, test/ui-pytest/tests/fixtures/aut.py, test/ui-pytest/tests/test_onboarding.py
Test ([copied from squish framework](https://github.com/status-im/desktop-qa-automation/issues/86)]
Test case: https://ethstatus.testrail.net/index.php?/cases/view/703040&group_by=cases:section_id&group_id=51041&group_order=asc&display_deleted_cases=0
=> test(Onboarding) Test on Import: 12 word seed phrase added

src/app_service/service/wallet_account/service_account.nim
=> fix(@desktop/wallet): no notification after deleting keyapir

src/app/modules/main/communities/module.nim, src/app/modules/main/communities/tokens/controller.nim, src/app/modules/main/communities/tokens/io_interface.nim, src/app/modules/main/communities/tokens/models/token_model.nim, src/app/modules/main/communities/tokens/module.nim, src/app/modules/main/communities/tokens/view.nim, src/app/modules/main/controller.nim, src/app/modules/main/io_interface.nim, src/app/modules/main/module.nim, src/app/modules/shared_models/section_item.nim, src/app_service/service/community_tokens/async_tasks.nim, src/app_service/service/community_tokens/dto/community_token.nim, src/app_service/service/community_tokens/dto/deployment_parameters.nim, src/app_service/service/community_tokens/service.nim, src/app_service/service/transaction/dto.nim, src/backend/community_tokens.nim, storybook/pages/MintTokensSettingsPanelPage.qml, storybook/src/Models/MintedTokensModel.qml, ui/app/AppLayouts/Communities/helpers/TokenObject.qml, ui/app/AppLayouts/Communities/panels/AirdropsSettingsPanel.qml, ui/app/AppLayouts/Communities/panels/MintTokensSettingsPanel.qml, ui/app/AppLayouts/Communities/panels/TokenInfoPanel.qml, ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml, ui/app/AppLayouts/Communities/views/EditOwnerTokenView.qml, ui/app/AppLayouts/Communities/views/MintedTokensView.qml, ui/app/AppLayouts/Wallet/views/collectibles/CollectibleView.qml, ui/imports/shared/stores/CommunityTokensStore.qml, ui/imports/utils/Constants.qml
Deploy owner token and master token flow.
status-go pr: https://github.com/status-im/status-desktop/pull/11857
Issue #11250
=> 11250 deploy token master

ci/Jenkinsfile.combined, ci/Jenkinsfile.linux, ci/Jenkinsfile.macos, ci/Jenkinsfile.tests-e2e, ci/Jenkinsfile.tests-imports, ci/Jenkinsfile.tests-nim, ci/Jenkinsfile.windows, ci/cpp/Jenkinsfile.linux, ci/cpp/Jenkinsfile.macos, ci/cpp/Jenkinsfile.windows
=> ci: update jenkins lib

ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml, ui/imports/utils/Constants.qml
Set up isTokenMasterOwner flag correctly in UI.
This flag is used to block/unblock some operations.
We will test it when we connect Minting and Permissions.
=> 11276 token master operations

ui/StatusQ/CMakeLists.txt, ui/StatusQ/include/StatusQ/stringutilsinternal.h, ui/StatusQ/src/StatusQ/Core/Utils/StringUtils.qml, ui/StatusQ/src/StatusQ/Core/Utils/qmldir, ui/StatusQ/src/plugin.cpp, ui/StatusQ/src/statusq.qrc, ui/StatusQ/src/stringutilsinternal.cpp, ui/app/AppLayouts/Browser/panels/BrowserTabView.qml, ui/app/AppLayouts/Browser/panels/FavoritesBar.qml, ui/app/AppLayouts/Communities/controls/FeeRow.qml, ui/imports/shared/popups/ContactVerificationRequestPopup.qml, ui/imports/shared/status/StatusChatInput.qml, ui/imports/utils/Utils.qml
Fixes displaying fee amounts by sanitizing amount string.
Closes: #11929
`LocaleUtils`
=> fix(Utils): Sanitize string representing amount

src/app_service/service/accounts/service.nim
The status-go log level [is overwritten on login](https://github.com/status-im/status-go/blob/a42e2907b945095c7b3a24a68958a3afc3f36988/api/geth_backend.go#L1403) due to our default configuration including a default LogLevel. Hence later changing this doesn't have any effect at the next login.
Optionally override the log level using the same env variable we use for Nim logging.
=> fix(debug) don't overwrite the status-go log level

src/app/modules/main/chat_section/chat_content/io_interface.nim, src/app/modules/main/chat_section/chat_content/module.nim, src/app/modules/main/chat_section/controller.nim, src/app/modules/main/chat_section/io_interface.nim, src/app/modules/main/chat_section/module.nim, src/app/modules/main/communities/controller.nim, src/app/modules/main/communities/io_interface.nim, src/app/modules/main/communities/module.nim, src/app/modules/main/communities/view.nim, src/app_service/service/chat/async_tasks.nim, src/app_service/service/chat/service.nim, src/app_service/service/community/async_tasks.nim, src/app_service/service/community/dto/community.nim, src/app_service/service/community/service.nim, src/backend/communities.nim, ui/app/AppLayouts/Chat/ChatLayout.qml, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Communities/panels/SharedAddressesPanel.qml, ui/app/AppLayouts/Communities/popups/SharedAddressesPopup.qml, ui/app/AppLayouts/Communities/views/CommunityColumnView.qml, ui/app/AppLayouts/Profile/views/CommunitiesView.qml, ui/app/AppLayouts/stores/RootStore.qml, ui/app/mainui/Popups.qml, ui/imports/shared/popups/CommunityIntroDialog.qml
Fixes: #11480
Adds method to update spectated community token model by shared addresses
Communities
=> feat(communities): Update permissions list for spectated community tokens model

ui/app/AppLayouts/Profile/views/CommunitiesView.qml, ui/app/AppLayouts/stores/RootStore.qml, ui/app/mainui/Popups.qml
=> feat: hook edit shared addresses to backend

src/app/modules/main/communities/tokens/models/token_item.nim, src/app/modules/main/communities/tokens/models/token_model.nim, src/app/modules/main/communities/tokens/models/token_owners_item.nim, src/app/modules/main/communities/tokens/models/token_owners_model.nim, src/app/modules/main/io_interface.nim, src/app/modules/main/module.nim, src/app/modules/main/view.nim, storybook/src/Models/TokenHoldersModel.qml, ui/app/AppLayouts/Communities/controls/TokenHolderListItem.qml, ui/app/AppLayouts/Communities/controls/TokenHolderNumberCell.qml, ui/app/AppLayouts/Communities/panels/SortableTokenHoldersList.qml, ui/app/AppLayouts/Communities/panels/SortableTokenHoldersPanel.qml, ui/app/AppLayouts/Communities/panels/TokenHoldersList.qml, ui/app/AppLayouts/Communities/panels/TokenHoldersProxyModel.qml, ui/app/mainui/activitycenter/views/ActivityNotificationContactRequest.qml, ui/imports/utils/Utils.qml
Close #11858
Communities, Community tokens
=> feat(Communities): Improvements for token holders list 

src/app/modules/main/communities/module.nim
Close #11843
Communities, Community tokens
https://github.com/status-im/status-desktop/assets/2522130/1626cfaf-f3ad-41af-b094-ff9f74a66d07
=> fix(Communities): Fix assets dropdown in create permission view

ui/app/AppLayouts/Communities/panels/MembersTabPanel.qml
Closing: #11895 
- Adding the pending state indicator as a separate item in the members tab listView
- Removing the pending indicator from Buttons.
MembersTabPanel
1. CTA Allowed (The pending state was initiated by the current user)
https://github.com/status-im/status-desktop/assets/47811206/ea5af798-360b-4d32-aaa8-409e1e8f9583
3. CTA not allowed (The pending state was initiated by another admin)
https://github.com/status-im/status-desktop/assets/47811206/7c7e2104-0bc5-42a4-8404-d404e266c31f
=> feat(MembersTab): Update pending states based on new design

test/ui-test/src/drivers/aut.py, test/ui-test/testSuites/suite_messaging/tst_OneToOneChatFlow/test.feature
1. Fix the import module
2. Skip failed test tst_OneToOneChatFlow because of the issue with DB :
=> Test(Hotfix) Fix import module

src/app/modules/main/controller.nim, src/app_service/service/wallet_account/service.nim, src/app_service/service/wallet_account/service_account.nim, src/app_service/service/wallet_account/signals_and_payloads.nim, src/backend/accounts.nim, ui/app/AppLayouts/Profile/views/wallet/MainView.qml
- https://github.com/status-im/status-go/pull/3927
Closes: #11781
=> feat(@desktop/wallet): make a partially operable account fully operable on the first use

src/app/modules/main/activity_center/controller.nim, src/app/modules/main/app_search/controller.nim, src/app/modules/main/chat_section/chat_content/controller.nim, src/app/modules/main/chat_section/chat_content/messages/controller.nim, src/app/modules/main/chat_section/chat_content/messages/module.nim, src/app/modules/main/chat_section/chat_content/module.nim, src/app/modules/main/chat_section/controller.nim, src/app/modules/main/chat_section/module.nim, src/app/modules/main/communities/controller.nim, src/app/modules/main/communities/tokens/controller.nim, src/app/modules/main/controller.nim, src/app_service/service/community/service.nim
Iterating over https://github.com/status-im/status-desktop/issues/11996
This has a possible fix for the crashes. It also adds logs in case it still happens. I'll remove the logs before publishing the final build.
This also cleans up some files. And finally it ups status-go to the fix for pending transactions
=> Possible fix to the crash + logs + clean up + status-go up

src/backend/community_tokens.nim
=> 12011 change collectibles service to communitytokens

ui/app/AppLayouts/Chat/panels/EmptyChatPanel.qml, ui/imports/shared/popups/InviteFriendsPopup.qml, ui/imports/shared/views/NoFriendsRectangle.qml, ui/imports/utils/Constants.qml
- make the popup centered across the whole window
- fix (and extract) the get/download link to `Constants`
- fix some memleaks
Fixes #11926
InviteFriendsPopup
=> fix(chat): Download/invite popup small issues

src/app/core/eventemitter.nim, src/app/core/signals/signals_manager.nim, src/app/modules/main/activity_center/module.nim, src/app/modules/main/chat_section/chat_content/controller.nim, src/app/modules/main/chat_section/chat_content/messages/module.nim, src/app/modules/main/chat_section/controller.nim, src/app/modules/main/profile_section/notifications/controller.nim, src/app/modules/main/profile_section/notifications/module.nim
More iterating for https://github.com/status-im/status-desktop/issues/11996
I added more logs to understand what is going on when it crashes
=> More small fixes and logs

src/app/modules/main/chat_section/chat_content/controller.nim, src/app/modules/main/chat_section/chat_content/messages/controller.nim, src/app/modules/main/chat_section/chat_content/messages/module.nim, src/app/modules/main/chat_section/chat_content/module.nim, src/app/modules/main/chat_section/controller.nim, src/app/modules/main/chat_section/module.nim, src/app_service/service/community/dto/community.nim, ui/app/AppLayouts/Chat/ChatLayout.qml
Just cherry picks of https://github.com/status-im/status-desktop/pull/11999 and https://github.com/status-im/status-desktop/pull/12022
=> Cherry picks for small fixes to crashes

src/app/core/eventemitter.nim, src/app/core/signals/signals_manager.nim, src/app/modules/main/activity_center/controller.nim, src/app/modules/main/app_search/controller.nim, src/app/modules/main/chat_section/chat_content/controller.nim, src/app/modules/main/chat_section/chat_content/messages/controller.nim, src/app/modules/main/chat_section/controller.nim, src/app/modules/main/communities/controller.nim, src/app/modules/main/communities/models/curated_community_model.nim, src/app/modules/main/communities/tokens/controller.nim, src/app/modules/main/communities/view.nim, src/app/modules/main/controller.nim, src/app/modules/main/profile_section/notifications/controller.nim, src/app/modules/main/profile_section/notifications/module.nim, src/app_service/service/community/service.nim, ui/app/AppLayouts/Chat/ChatLayout.qml
=> Fix missing admin page + make the logs appear in the log files

src/app/modules/main/communities/controller.nim, src/app/modules/main/communities/io_interface.nim, src/app/modules/main/communities/module.nim, src/app/modules/main/communities/view.nim, ui/app/AppLayouts/Chat/ChatLayout.qml, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Communities/panels/JoinPermissionsOverlayPanel.qml, ui/app/AppLayouts/Communities/panels/RequirementsCheckPendingLoader.qml, ui/app/AppLayouts/Communities/panels/SharedAddressesPanel.qml, ui/app/AppLayouts/Communities/panels/qmldir, ui/app/AppLayouts/Communities/popups/SharedAddressesPopup.qml, ui/app/AppLayouts/Communities/stores/CommunitiesStore.qml, ui/app/AppLayouts/Communities/views/CommunityColumnView.qml, ui/app/AppLayouts/Profile/views/CommunitiesView.qml, ui/app/AppLayouts/stores/RootStore.qml, ui/app/mainui/Popups.qml, ui/imports/shared/popups/CommunityIntroDialog.qml
Fixes #11893
Joining:
[joining-loading.webm](https://github.com/status-im/status-desktop/assets/11926403/1720ac76-f449-4246-bddb-b27f081e1b2e)
Editing:
[edit-addr-loading.webm](https://github.com/status-im/status-desktop/assets/11926403/fb56da0d-a81f-4366-8f37-f14713417567)
=> feat(shared-addresses): add loading state for checking permissions

src/app/modules/main/profile_section/keycard/io_interface.nim, src/app/modules/main/profile_section/keycard/module.nim, src/app/modules/main/profile_section/keycard/view.nim, src/app/modules/shared_modules/keycard_popup/module.nim, src/app_service/service/wallet_account/service_account.nim, src/app_service/service/wallet_account/service_keycard.nim, ui/app/AppLayouts/Profile/ProfileLayout.qml, ui/app/AppLayouts/Profile/controls/WalletKeyPairDelegate.qml, ui/app/AppLayouts/Profile/popups/WalletKeypairAccountMenu.qml, ui/app/AppLayouts/Profile/stores/KeycardStore.qml, ui/app/AppLayouts/Profile/views/KeycardView.qml, ui/app/AppLayouts/Profile/views/WalletView.qml, ui/app/AppLayouts/Profile/views/keycard/MainView.qml, ui/app/AppLayouts/Profile/views/wallet/AccountView.qml, ui/app/AppLayouts/Profile/views/wallet/MainView.qml
- https://github.com/status-im/status-go/pull/3956
Closes part 1 of: #11737
=> Account Interaction - migrate to keycard

test/ui-test/src/screens/StatusCommunityScreen.py, test/ui-test/testSuites/suite_communities/shared/scripts/community_names.py, test/ui-test/testSuites/suite_communities/shared/steps/communitySteps.py, test/ui-test/testSuites/suite_communities/tst_communityManagePermissions/test.feature, ui/app/AppLayouts/Communities/popups/PermissionsDropdown.qml
Added new test for adding permissions in communities
https://github.com/status-im/desktop-qa-automation/issues/89
=> test(Communities) Adding permission test automated

test/ui-test/testSuites/suite_communities/tst_communityManagePermissions/test.feature
Small fix for adding permissions test (due to text changes in the app)
https://github.com/status-im/desktop-qa-automation/issues/94
=> test(Communities) Small fix for adding permissions test

test/ui-pytest/gui/components/context_menu.py, test/ui-pytest/gui/components/signing_phrase_popup.py, test/ui-pytest/gui/components/wallet/add_saved_address_popup.py, test/ui-pytest/gui/components/wallet/confirmation_popup.py, test/ui-pytest/gui/elements/qt/text_edit.py, test/ui-pytest/gui/main_window.py, test/ui-pytest/gui/objects_map/__init__.py, test/ui-pytest/gui/objects_map/component_names.py, test/ui-pytest/gui/objects_map/main_names.py, test/ui-pytest/gui/objects_map/wallet_names.py, test/ui-pytest/gui/screens/wallet.py, test/ui-pytest/scripts/utils/decorators.py, test/ui-pytest/tests/test_wallet.py
https://ethstatus.testrail.net/index.php?/cases/view/703021
https://github.com/status-im/desktop-qa-automation/issues/91
=> test(Wallet) Test Manage a saved address automated

src/app/modules/main/communities/controller.nim, src/app/modules/main/communities/io_interface.nim, src/app/modules/main/communities/module.nim, src/app/modules/main/communities/view.nim, src/app_service/service/community/async_tasks.nim, src/app_service/service/community/service.nim, ui/app/AppLayouts/Communities/panels/SharedAddressesAccountSelector.qml, ui/app/AppLayouts/Communities/panels/SharedAddressesPanel.qml, ui/app/AppLayouts/Communities/popups/SharedAddressesPopup.qml, ui/app/AppLayouts/stores/RootStore.qml, ui/app/mainui/Popups.qml
Fixes #11973
[edit-shared-addr.webm](https://github.com/status-im/status-desktop/assets/11926403/343ee7eb-c65b-42d9-b2c5-edc87a3dda16)
=> feat(shared_addresses): get old shared addresses for the edit popup

src/app/modules/main/wallet_section/activity/controller.nim, src/app/modules/main/wallet_section/activity/entry.nim, src/app/modules/main/wallet_section/activity/entry_details.nim, src/app/modules/main/wallet_section/activity/model.nim, src/backend/activity.nim, ui/app/AppLayouts/Wallet/views/RightTabView.qml, ui/app/AppLayouts/Wallet/views/TransactionDetailView.qml, ui/imports/shared/controls/TransactionDelegate.qml, ui/imports/shared/stores/RootStore.qml, ui/imports/shared/views/HistoryView.qml
=> chore(wallet) remove legacy code to fetch details for displaying headers

src/app/modules/main/wallet_section/activity/controller.nim, src/app/modules/main/wallet_section/filter.nim, src/app/modules/main/wallet_section/module.nim
Optimization and fixes no chain ID for multi-transaction issues.
=> fix(wallet) use the all chains enabled state in filter

src/app/boot/app_controller.nim, src/app/modules/main/controller.nim, src/app/modules/main/io_interface.nim, src/app/modules/main/module.nim, src/app/modules/main/view.nim, src/app/modules/main/wallet_section/module.nim, src/app/modules/shared_modules/keycard_popup/internal/create_password_state.nim, src/app/modules/shared_modules/keycard_popup/internal/enter_seed_phrase_state.nim, src/app/modules/shared_modules/keycard_popup/internal/migrating_keypair_to_app_state.nim, src/app/modules/shared_modules/keycard_popup/internal/wrong_seed_phrase_state.nim, src/app/modules/shared_modules/keycard_popup/io_interface.nim, src/app/modules/shared_modules/keycard_popup/module.nim, src/app/modules/shared_modules/keycard_popup/view.nim, src/app_service/service/settings/dto/settings.nim, src/app_service/service/settings/service.nim, src/app_service/service/wallet_account/service_account.nim, ui/app/mainui/AppMain.qml, ui/imports/shared/popups/keycard/KeycardPopup.qml, ui/imports/shared/popups/keycard/KeycardPopupDetails.qml, ui/imports/shared/popups/keycard/states/KeycardInit.qml
- https://github.com/status-im/status-go/pull/3841
Part 4 of: #11737
=> feat(@desktop/wallet): account interaction - stop using a keycard for profile keypair - handling on paired devices

ui/app/AppLayouts/Communities/controls/PermissionTypes.qml
Fixes #12004
Tweak to Owner and TokenMaster permissions wording
Community Settings / Permissions
=> fix(Permissions): Tweak to Owner and TokenMaster permissions wording

ui/app/AppLayouts/Communities/views/CommunityColumnView.qml, ui/app/AppLayouts/Profile/panels/CommunitiesListPanel.qml, ui/app/mainui/AppMain.qml, ui/imports/shared/views/chat/InvitationBubbleView.qml
=> Test(Community) Object names added

src/app/modules/main/wallet_section/send/controller.nim, src/app/modules/main/wallet_section/send/io_interface.nim, src/app/modules/main/wallet_section/send/module.nim, src/app/modules/main/wallet_section/send/network_model.nim, src/app/modules/main/wallet_section/send/view.nim, src/app_service/service/eth/dto/transaction.nim, src/app_service/service/transaction/async_tasks.nim, src/app_service/service/transaction/dto.nim, src/app_service/service/transaction/service.nim, ui/app/AppLayouts/Wallet/WalletLayout.qml, ui/app/AppLayouts/Wallet/panels/WalletFooter.qml, ui/app/mainui/AppMain.qml, ui/imports/shared/controls/GasSelector.qml, ui/imports/shared/popups/SendModal.qml, ui/imports/shared/stores/TransactionStore.qml, ui/imports/shared/views/NetworkSelector.qml, ui/imports/shared/views/NetworksSimpleRoutingView.qml, ui/imports/shared/views/RecipientView.qml, ui/imports/utils/Constants.qml
fixed #12128 
go PR : https://github.com/status-im/status-go/pull/3945
This PR is the glue needed in order to send NFT Erc721 from the wallet
SendModal
https://github.com/status-im/status-desktop/assets/60327365/3db492c1-5c90-4ef9-ac7b-c12c9d37d4f6
https://github.com/status-im/status-desktop/assets/60327365/f30e0a3a-f209-4c01-a77b-fdc7be1fee33
=> feat(@desktop/wallet): Glue for sending nft

ui/StatusQ/sandbox/DemoApp.qml, ui/StatusQ/sandbox/controls/Layout.qml, ui/StatusQ/sandbox/demoapp/StatusAppCommunityView.qml, ui/StatusQ/sandbox/pages/StatusChatInfoToolBarPage.qml
Object names for invite people menu item added
=> Test(Community) Object names for invite people menu item added

src/app_service/service/accounts/service.nim, src/app_service/service/devices/service.nim
- https://github.com/status-im/status-go/pull/4014
=> chore(@desktop/keycard): desktop side handling of status-go #4003 issue

src/app/modules/main/communities/view.nim, src/app/modules/main/controller.nim, src/app/modules/main/io_interface.nim, src/app/modules/main/module.nim, src/app/modules/main/view.nim, src/app/modules/shared_models/section_details.nim, src/app/modules/shared_models/section_item.nim
This reverts commit 9968495ef31248505e79ad6b660f2c0ee148042b.
I merged my PR by accident before QA
=> Revert "refactor(section_details): simplify section_details to only contain needed props"

ui/app/AppLayouts/Profile/views/wallet/EditNetworkForm.qml
https://github.com/status-im/status-go/pull/4032
=> feat(@wallet): empty fallback url

src/app/modules/main/wallet_section/activity/controller.nim, src/app/modules/main/wallet_section/module.nim, src/backend/activity.nim, ui/imports/shared/popups/send/views/TabAddressSelectorView.qml
Bumps status-go to [#4021](https://github.com/status-im/status-go/pull/4021) and pass all addresses selected to the API
=> chore(wallet) remove activity filter dependency on accounts

src/app/modules/main/wallet_section/send/network_model.nim, src/app/modules/main/wallet_section/send/view.nim, ui/app/AppLayouts/Wallet/WalletLayout.qml, ui/app/mainui/AppMain.qml, ui/imports/shared/popups/send/SendModal.qml, ui/imports/shared/popups/send/views/TokenListView.qml
Fixing bugs found during demo-
1. After sending a collectible a normal tx doesnt work because the chains are locked 
2. Locked in amounts are not getting reset on closing on menu
3. Hide collectibles when on bridge 
4. Resizing issue on send modal
5. Bridge routes not visible everytime
SendModal
=> fix(@desktop/wallet): Fixing bugs found during demo

src/app/modules/main/activity_center/module.nim, src/app/modules/shared_models/message_item_qobject.nim, src/app_service/service/activity_center/dto/notification.nim, ui/app/mainui/activitycenter/views/ActivityNotificationMessage.qml, ui/imports/shared/views/chat/SimplifiedMessageView.qml
Fixes: #9951
Display album of images in AC
AC
=> feat(activity-center): Display album of images

src/app/modules/main/wallet_section/send/controller.nim, src/app/modules/main/wallet_section/send/io_interface.nim, src/app/modules/main/wallet_section/send/module.nim, src/app/modules/main/wallet_section/send/view.nim, src/app_service/service/transaction/async_tasks.nim, src/app_service/service/transaction/service.nim, ui/app/AppLayouts/Browser/BrowserLayout.qml, ui/app/AppLayouts/Profile/views/EnsDetailsView.qml, ui/app/AppLayouts/Profile/views/EnsSearchView.qml, ui/app/AppLayouts/Profile/views/EnsTermsAndConditionsView.qml, ui/app/AppLayouts/Wallet/WalletLayout.qml, ui/app/mainui/AppMain.qml, ui/imports/shared/popups/send/SendModal.qml, ui/imports/shared/status/StatusStickerMarket.qml, ui/imports/shared/status/StatusStickerPackClickPopup.qml, ui/imports/shared/stores/send/TransactionStore.qml, ui/imports/utils/Constants.qml
[Move selected recipient and send type to nim#12206](https://github.com/status-im/status-desktop/issues/12206)
SendModal
=> Fix/issue #12206

ui/app/AppLayouts/Onboarding/views/TouchIDAuthView.qml
Added an object name for TouchID button for ui/app/AppLayouts/Onboarding/views/TouchIDAuthView.qml This is needed for automation purposes
UI tests in Pytest framework, so now - nothing is affected at all
=> chore(@TouchIDAuthView.qml): added object name for TouchID button

src/app/modules/shared_models/collectible_details_entry.nim, src/app/modules/shared_models/collectibles_item.nim, src/app/modules/shared_models/collectibles_model.nim, src/app/modules/shared_models/collectibles_utils.nim, src/backend/collectibles_types.nim, src/backend/community_tokens_types.nim
Fixes https://github.com/status-im/status-desktop/issues/12155
status-go part: https://github.com/status-im/status-go/pull/4048
Parses new Collectibles community info, makes it available in the model
To be used by https://github.com/status-im/status-desktop/issues/12172
=> feat(@desktop/wallet): add community info to collectibles

ui/app/AppLayouts/Profile/popups/SetupSyncingPopup.qml, ui/app/AppLayouts/Profile/views/SyncingView.qml, ui/imports/shared/views/SyncingDisplayCode.qml
add several object names
```
ui/app/AppLayouts/Profile/popups/SetupSyncingPopup.qml
ui/app/AppLayouts/Profile/views/SyncingView.qml
ui/imports/shared/views/SyncingDisplayCode.qml
```
=> chore(@sync_code_qml): added object names for testing purposes

src/app/modules/main/wallet_section/send/network_model.nim, src/app/modules/main/wallet_section/send/view.nim, storybook/pages/SendModalPage.qml, ui/StatusQ/src/StatusQ/Components/StatusCard.qml, ui/imports/shared/popups/send/SendModal.qml, ui/imports/shared/popups/send/controls/GasValidator.qml, ui/imports/shared/popups/send/views/FeesView.qml, ui/imports/shared/popups/send/views/NetworkCardsComponent.qml, ui/imports/shared/popups/send/views/SendModalFooter.qml
fixes #12243
Fixes:
1. Send request everytime there is a change in enabled/disabled change
2.  The sendModal doesnt resize for simple networks
3.  Fees rectangle is bigger than its contents
SendModal
Uploading Screen Recording 2023-09-26 at 12.18.08 PM.mov…
=> fix(@desktop/wallet): Send Modal Improvements & missing features

ui/app/AppLayouts/Profile/views/wallet/NetworksView.qml
added object name property for network items
`NetworksView.qml`
=> chore(@NetworksView.qml): added object name property for network items

test/ui-test/testSuites/suite_communities/tst_communityFlows/test.feature, test/ui-test/testSuites/suite_communities/tst_communityManageOverview/test.feature, test/ui-test/testSuites/suite_wallet/tst_wallet_settingsManagement/test.feature
Switching off tests failing here https://ci.status.im/job/status-desktop/job/branches/job/linux/job/x86_64/job/tests-e2e/job/PR-12182/26/squishResults_230927_111650.490/webreport_230927_111650.490_linux-02/index.html
We need to merge the keycard mock branch
Squish tests
=> chore(@tests): switch off some tests that are failing on linux

src/app/modules/startup/internal/user_profile_confirm_password_state.nim
Cherry-pick of https://github.com/status-im/status-desktop/pull/12280
=> [CHERRY-PICK] fix(backup): fix import not setting recoverAccount so backup wasn't used

storybook/CMakeLists.txt, storybook/main.cpp, storybook/validator_main.cpp
Adds additional target to `Storybook` for checking if pages are compilable.
Closes: #12282
`Storybook`
=> feat(Storybook): Validator app to check if all pages can be compiled

ui/app/AppLayouts/Chat/stores/RootStore.qml
Just something I ran into while working on something else
=> fix(RootStore): add missing copyToClipboard function

ui/imports/assets/docs/privacy.mdwn, ui/imports/assets/docs/terms-of-use.mdwn
to the latest official versions, as of 2023-09-22
Fixes #12279
Settings/About
=> fix: update Privacy and Terms of Use documents

ui/StatusQ/src/StatusQ/Components/StatusListItem.qml
Creates object names for sensor in mouse area of list item
StatusListItem.qml
=> chore(@StatusListItem.qml): object name for mouse area

src/app/modules/main/wallet_section/send/network_model.nim, src/app/modules/main/wallet_section/send/view.nim, storybook/pages/SendModalPage.qml, storybook/src/Models/NetworksModel.qml, storybook/src/Models/WalletAssetsModel.qml, storybook/src/Models/WalletSendAccountsModel.qml, storybook/src/Models/qmldir, storybook/stubs/shared/stores/CurrenciesStore.qml, storybook/stubs/shared/stores/send/TransactionStore.qml, ui/app/AppLayouts/Browser/BrowserLayout.qml, ui/app/AppLayouts/Communities/popups/TransferOwnershipPopup.qml, ui/app/AppLayouts/Profile/views/EnsDetailsView.qml, ui/app/AppLayouts/Profile/views/EnsSearchView.qml, ui/app/AppLayouts/Profile/views/EnsTermsAndConditionsView.qml, ui/app/mainui/AppMain.qml, ui/imports/shared/popups/send/SendModal.qml, ui/imports/shared/status/StatusStickerMarket.qml, ui/imports/shared/status/StatusStickerPackClickPopup.qml, ui/imports/shared/stores/send/TransactionStore.qml
closes #12244
Added pre loading SendModal with data
Adding flow for showing routes
SendModal 
https://github.com/status-im/status-desktop/assets/60327365/67b7d0df-1972-456d-b7b8-394ecc89e39b
=> chore(@desktop/wallet): SendModal: complete storybook flow

ui/app/AppLayouts/Profile/views/wallet/EditNetworkForm.qml, ui/app/AppLayouts/Profile/views/wallet/EditNetworkView.qml
Object names for Edit Network view / form
```
ui/app/AppLayouts/Profile/views/wallet/EditNetworkForm.qml
ui/app/AppLayouts/Profile/views/wallet/EditNetworkView.qml
```
=> chore(@EditNetwork): added object names

ui/app/AppLayouts/Profile/views/wallet/EditNetworkView.qml
Add more object names
`EditNetworkView.qml`
=> chore(@Update EditNetworkView.qml): missing object name

ui/app/AppLayouts/Profile/views/wallet/EditNetworkView.qml
adding object names
`EditNetworkView.qml`
=> chore(@EditNetworkView.qml): adding object name for loader

storybook/src/Storybook/InspectionItem.qml, storybook/src/Storybook/InspectionPanel.qml
=> feat: add objectName to Inspect window (if present)

src/app/modules/main/communities/tokens/controller.nim, src/app/modules/main/communities/tokens/io_interface.nim, src/app/modules/main/communities/tokens/module.nim, src/app/modules/main/communities/tokens/view.nim, src/app/modules/main/controller.nim, src/app/modules/main/io_interface.nim, src/app/modules/main/module.nim, src/app_service/service/community_tokens/async_tasks.nim, src/app_service/service/community_tokens/service.nim, src/backend/community_tokens.nim, storybook/pages/MintTokensSettingsPanelPage.qml, ui/app/AppLayouts/Communities/helpers/DeployFeesSubscriber.qml, ui/app/AppLayouts/Communities/helpers/TransactionFeesBroker.qml, ui/app/AppLayouts/Communities/panels/MintTokensSettingsPanel.qml, ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml, ui/imports/shared/stores/CommunityTokensStore.qml
Issue #11954 
Adjust owner and master tokens deployment flow to new API - deployment uses new contracts now.
Passing communityId during computing fee - deployment fee is calculated dynamically now and communityId is needed to prepare structures.
**Deployment contracts are deployed only on Optimism chain. Other chains will not work.**
Related status-go pr: https://github.com/status-im/status-go/pull/3970
https://github.com/status-im/status-desktop/assets/61889657/ecc2cd51-81ae-42e2-8578-99f54ee9ea10
=> 11954 deploy owner token

src/app/modules/main/chat_section/chat_content/chat_details.nim, src/app/modules/main/chat_section/chat_content/module.nim, src/app/modules/main/chat_section/chat_content/view.nim, ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
=> fix(chat): fix chat highlighted because it was never marked as read

src/app/modules/main/chat_section/chat_content/users/controller.nim, src/app/modules/main/chat_section/controller.nim, src/app/modules/main/communities/controller.nim, src/app/modules/main/communities/io_interface.nim, src/app/modules/main/communities/module.nim, src/app/modules/main/controller.nim, src/app/modules/main/io_interface.nim, src/app/modules/main/module.nim, src/app/modules/shared_models/member_item.nim, src/app/modules/shared_models/member_model.nim, src/app/modules/shared_models/section_item.nim, src/app_service/common/types.nim, src/app_service/service/community/async_tasks.nim, src/app_service/service/community/dto/community.nim, src/app_service/service/community/service.nim, storybook/pages/MembersTabPanelPage.qml, ui/app/AppLayouts/Communities/panels/MembersTabPanel.qml, ui/imports/utils/Constants.qml
Waits https://github.com/status-im/status-go/pull/3948
Close #11795
Add handling KickedPending and BannedPending states from status-go
Communities
https://github.com/status-im/status-desktop/assets/2522130/0ec3e46b-db4b-4d49-b9a0-5b34f8e17504
=> Feat/issue 11795 introduce KickedPending and BannedPending states

ui/app/AppLayouts/Onboarding/views/SyncCodeView.qml
Added object name for syncing enter code for automation purposes
=> chore(@SyncCodeView.qml): object name for syncing enter code object

src/app/modules/shared/wallet_utils.nim, src/app/modules/shared_models/token_item.nim, src/app/modules/shared_models/token_model.nim, src/app_service/service/wallet_account/dto/token_dto.nim, storybook/src/Models/WalletAssetsModel.qml, ui/imports/shared/popups/send/panels/HoldingSelector.qml, ui/imports/shared/popups/send/views/TokenListView.qml
fixes #12255
Uses updated property to show token list in sendModal
SendModal
https://github.com/status-im/status-desktop/assets/60327365/87975f1d-69a0-40d8-87ce-40c06d066152
=> fix(@desktop/wallet): Selecting other than the mainnet doesn't display DAI

storybook/pages/ActivityFilterMenuPage.qml, storybook/pages/DerivationPathInputPage.qml, storybook/pages/EditCommunityTokenViewPage.qml, storybook/pages/StatusTxProgressBarPage.qml, storybook/pages/TokenListViewPage.qml, storybook/pages/TransactionDelegatePage.qml, storybook/validator_main.cpp, ui/app/AppLayouts/Wallet/stores/ActivityFiltersStore.qml, ui/imports/shared/controls/TransactionDelegate.qml
It was mostly some missing or non-existing properties or the component got moved somewhere else
Fixes #12285
Fixes loading broken StoryBook pages
Storybook
ActivityFilterMenu:
DerivationPathInput:
EditCommunityTokenView:
StatusTxProgressBar:
TokenListView:
TransactionDelegate:
=> fix(storybook): fix broken pages

src/app/modules/main/profile_section/wallet/networks/controller.nim, src/app/modules/main/profile_section/wallet/networks/io_interface.nim, src/app/modules/main/profile_section/wallet/networks/module.nim, src/app/modules/main/profile_section/wallet/networks/view.nim, src/app_service/common/network_constants.nim, src/app_service/service/network/service.nim, src/app_service/service/network/types.nim, src/app_service/service/settings/dto/settings.nim, src/app_service/service/settings/service.nim, src/app_service/service/wallet_account/service_account.nim, ui/app/AppLayouts/Profile/popups/WalletAddressMenu.qml, ui/app/AppLayouts/Profile/stores/AdvancedStore.qml, ui/app/AppLayouts/Profile/stores/ProfileSectionStore.qml, ui/app/AppLayouts/Profile/stores/WalletStore.qml, ui/app/AppLayouts/Profile/views/AdvancedView.qml, ui/app/AppLayouts/Profile/views/wallet/AccountView.qml, ui/app/AppLayouts/Wallet/controls/SavedAddressesDelegate.qml, ui/app/AppLayouts/Wallet/panels/WalletNftPreview.qml, ui/app/AppLayouts/Wallet/popups/TransactionAddressMenu.qml, ui/app/AppLayouts/Wallet/views/SavedAddressesView.qml, ui/app/AppLayouts/Wallet/views/TransactionDetailView.qml, ui/imports/utils/Constants.qml
status-go: https://github.com/status-im/status-go/pull/4092
=> feat(@wallet): Enable sepolia network

ui/app/AppLayouts/Profile/controls/WalletKeyPairDelegate.qml, ui/app/AppLayouts/Profile/popups/RenameKeypairPopup.qml, ui/app/AppLayouts/Profile/views/wallet/AccountView.qml, ui/imports/shared/controls/ImportKeypairInfo.qml, ui/imports/shared/popups/keypairimport/states/SelectKeypair.qml, ui/imports/utils/Utils.qml
fix(@desktop/wallet): Wallet settings - various small enhancements identified via mobile wallet settings work
fixes #11675
Addresses the flows mentioned and updated values where required. please note that some parts mention in the issue is outdated and Ive followed the design eventually after discussion with Ben.
=> fix(@desktop/wallet): Wallet settings - various small enhancements identified via mobile wallet settings work

ui/app/AppLayouts/Communities/views/CommunityColumnView.qml
Fixes #12351
- Fixed wrong property access.
Community Column View
=> fix(JoinCommunity): Unable to join community

libs/Onboarding/src/Onboarding/Accounts/AccountsService.cpp, src/app_service/service/accounts/service.nim, src/app_service/service/node_configuration/service.nim
Enrtrees are updated, please test the DNS discovery.
=> update status/wakuv2 fleets DNS discovery enrtree

ui/imports/shared/views/chat/LinksMessageView.qml
Closing: #12179 
Changes:
1. Replace ColumnLayout with Flow
2. Move the image previews up to be presented before the link previews
NOTE: Currently the user cannot send both link previews and raw images
LinksMessageView
https://github.com/status-im/status-desktop/assets/47811206/06a2ad3c-f83d-48d9-bad5-4a90725f2c8d
=> feat: Arrange link previews in messages view in a flow layout

ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml
=> fix(@desktop/communities): Fix enabling/disabling mint button

ui/app/AppLayouts/Wallet/stores/RootStore.qml
=> fix(wallet) deconflict import of Utils in wallet.RootStore

src/app_service/service/wallet_account/service_token.nim, src/backend/backend.nim
fixes #12405
remove PR thats been deprecated 
Nim service
=> fix(@desktop/wallet): (tokens) unknown RPC method wallet_updateVisibleTokens

src/app_service/common/network_constants.nim
status-go: https://github.com/status-im/status-go/pull/4140
=> feat(@wallet): arbitrum sepolia

ui/app/AppLayouts/Profile/popups/RenameAccontModal.qml, ui/imports/shared/popups/addaccount/states/Main.qml, ui/imports/shared/popups/keycard/states/ManageAccounts.qml
=> feat(@desktop/wallet): align emoji with mobile

src/app_service/service/chat/service.nim
Fixes #10324 and https://github.com/status-im/status-go/issues/3547
status-go PRs:
- https://github.com/status-im/status-go/pull/4073
- https://github.com/status-im/status-go/pull/4102
[import-chats.webm](https://github.com/status-im/status-go/assets/11926403/0c241a66-6ee6-4f1a-8f9d-b699e20ba5d3)
[pairing-chats.webm](https://github.com/status-im/status-go/assets/11926403/a263bf2e-b7cc-4b17-9043-c51a565b4d9e)
=> feat(sync): sync and pair 1-1 chats and groups

src/app/core/signals/remote_signals/wallet.nim, src/app/modules/main/module.nim, src/app/modules/main/profile_section/keycard/module.nim, src/app/modules/main/wallet_section/module.nim, src/app/modules/main/wallet_section/send/controller.nim, src/app/modules/main/wallet_section/send/io_interface.nim, src/app/modules/main/wallet_section/send/module.nim, src/app/modules/main/wallet_section/send/view.nim, src/app/modules/shared/keypairs.nim, src/app/modules/shared_modules/keycard_popup/controller.nim, src/app_service/service/devices/service.nim, src/app_service/service/keycard/internal.nim, src/app_service/service/keycard/service.nim, src/app_service/service/transaction/service.nim, src/app_service/service/wallet_account/dto/keypair_dto.nim, src/backend/transactions.nim
- https://github.com/status-im/status-go/pull/4078
Corresponding `go-ethereum` PR:
- https://github.com/status-im/go-ethereum/pull/102
Closes #8566
=> feat(@desktop/wallet): support keycard authentication for transactions

src/app/modules/main/communities/tokens/module.nim
Pass owner & master tokens addresses when deploying assets.
=> 12364 pass addrs to assets

Makefile
Allows doing stuff like this:
```
make run ARGS=--datadir=./some_path
```
=> feat: allow passing args to `make run`

ui/app/AppLayouts/Profile/views/wallet/AccountView.qml
Add several object names to `AccountView.qml`
`ui/app/AppLayouts/Profile/views/wallet/AccountView.qml`
=> chore(@AccountView.qml): adding object names for testing purposes

src/app/modules/shared/wallet_utils.nim, src/app/modules/shared_models/token_item.nim, src/app/modules/shared_models/token_model.nim, src/app_service/service/wallet_account/dto/token_dto.nim, storybook/pages/ProfileDialogViewPage.qml, storybook/pages/ProfileShowcaseAssetsPanelPage.qml, storybook/src/Models/WalletAssetsModel.qml, ui/app/AppLayouts/Profile/panels/ProfileShowcaseAssetsPanel.qml, ui/imports/shared/controls/AssetDelegate.qml, ui/imports/shared/popups/send/panels/HoldingSelector.qml, ui/imports/shared/popups/send/views/TokenListView.qml, ui/imports/shared/views/AssetsView.qml, ui/imports/shared/views/profile/ProfileShowcaseView.qml
fixes #12508
The backend returns what is needed
=> fix(@wallet): token not always visible

ui/app/mainui/AppMain.qml, ui/i18n/qml_base.ts
Fix misspelling on toast message
Toast message text string
=> chore(@AppMain.qml): fix misspelling

ui/app/mainui/AppMain.qml
=> chore(@AppMain.qml): add object name for toast message

src/app/modules/main/wallet_section/filter.nim
=> fix(@wallet): all highlight

Makefile, ci/Jenkinsfile.macos, resources/Entitlements.plist, resources/Entitlements_squish.plist
And CI parameter to override the default entitlements.
=> chore(macos): add entitlements required for squish

ci/Jenkinsfile.combined, ci/Jenkinsfile.linux, ci/Jenkinsfile.macos, ci/Jenkinsfile.tests-e2e, ci/Jenkinsfile.tests-nim, ci/Jenkinsfile.tests-statusq, ci/Jenkinsfile.tests-ui, ci/Jenkinsfile.windows, ci/cpp/Jenkinsfile.linux, ci/cpp/Jenkinsfile.macos, ci/cpp/Jenkinsfile.windows
This version introduces a bunch of changes so I want to test them separately.
=> chore(ci): upgrade Jenkins library to 1.8.0

src/app_service/service/accounts/service.nim
=> fix(@desktop/general): error while generating account

test/ui-test/testSuites/suite_communities/tst_communityMessageFlows/test.feature
Reason: https://github.com/status-im/status-desktop/issues/12440
Disable failing test because of bug in the app
=> chore(@community_tests): disabling test with reply because of bug

storybook/pages/SupportedTokenListsPanelPage.qml, storybook/pages/TokenListPopupPage.qml, storybook/src/Models/FlatTokensModel.qml, storybook/src/Models/NetworksModel.qml, storybook/src/Models/SourceOfTokensModel.qml, storybook/src/Models/qmldir, ui/StatusQ/src/StatusQ/Controls/StatusBaseButton.qml, ui/app/AppLayouts/Profile/ProfileLayout.qml, ui/app/AppLayouts/Profile/panels/SupportedTokenListsPanel.qml, ui/app/AppLayouts/Profile/panels/qmldir, ui/app/AppLayouts/Profile/popups/TokenListPopup.qml, ui/app/AppLayouts/Profile/popups/qmldir, ui/app/AppLayouts/Profile/views/WalletView.qml, ui/app/AppLayouts/Profile/views/wallet/MainView.qml, ui/app/AppLayouts/Profile/views/wallet/ManageTokensView.qml, ui/app/AppLayouts/Profile/views/wallet/qmldir, ui/app/AppLayouts/Wallet/stores/RootStore.qml, ui/app/AppLayouts/Wallet/stores/TokensStore.qml, ui/app/AppLayouts/Wallet/stores/qmldir, ui/app/mainui/AppMain.qml, ui/imports/shared/controls/ShapeRectangle.qml, ui/imports/utils/Constants.qml
Closes #12374 and #12376
**1. New wallet settings option:**
- It adds `Manage tokens` entry in wallet settings (but hidden until backend ready).
**NOTE:** To enable it: `ui/app/AppLayout/Profile/views/wallet/MainView.qml` remove lines `145` and `159`
**2. Tokens list tab:**
- It creates new component `SupportedTokensListsPanel`.
- It updates tokens list tab content with the expected component.
- It creates new component `TokenListPopup`.
- It adds support to new created components in `storybook`.
**3. New `TokensStore`:**
- It creates new `TokensStore` that will provide all needed token models for all app sections:
- `sourcesOfTokensModel`
- `flatTokensModel`
- `tokensBySymbolModel`
**NOTE:** There will be other steps to improve this store. I.e: …
=> feat(Wallet_TokenManagement): Display token list as well as popup to see each token in it

scripts/macos_build_setup.sh
addresses this comment https://github.com/status-im/status-desktop/pull/12592#issuecomment-1788975224
=> Add yarn installation to macOS setup script

app/qml/Status/Application/System/StatusTrayIcon.qml
object names in StatusTrayIcon.qml
`StatusTrayIcon.qml`
=> chore(@StatusITrayIcon.qml): object names

ui/app/AppLayouts/Profile/views/wallet/AccountView.qml
=> fix(@wallet): hide store section for watch only accounts

src/app/modules/main/wallet_section/send/controller.nim, src/app/modules/main/wallet_section/send/io_interface.nim, src/app/modules/main/wallet_section/send/module.nim, src/app/modules/main/wallet_section/send/view.nim, src/app_service/service/keycard/internal.nim, src/app_service/service/transaction/async_tasks.nim, src/app_service/service/transaction/service.nim, src/backend/eth.nim, ui/imports/shared/popups/send/SendModal.qml, ui/imports/utils/Constants.qml
- https://github.com/status-im/status-go/pull/4253
Fixes: #12420
=> fix: send modal not working with bridge hop (mainnet to optimism)

src/app_service/service/accounts/service.nim
This PR closes the issue that is logged on the status-go side, cause initially it looked like a status-go issue.
https://github.com/status-im/status-go/issues/4265
=> fix(@desktop/general): LoadAllTransfers flag is set to true when a user is logging in

src/app_service/service/wallet_account/dto/balance_dto.nim, src/app_service/service/wallet_account/dto/token_dto.nim
fixes #12581
Building the DTO cause random nil values.
This "seems" to prevent it
=> fix(@wallet): random failure with building dto

ui/imports/shared/popups/send/SendModal.qml
Buying ens and stickers didn't work because of the wrongly sent tx type.
Fixes: #12665
=> fix(@desktop/general): buying ens usernames/stickers fixed

src/app_service/service/wallet_account/dto/balance_dto.nim, src/app_service/service/wallet_account/dto/token_dto.nim
This reverts commit 8abd9c56a1c42af5603210d42fd2290a800bae2f.
=> Revert "fix(@wallet): random failure with building dto"

ui/app/AppLayouts/Profile/views/wallet/AccountView.qml
Add object name for new ListItem in AccountView.qml
=> chore(@AccountView.qml): object name to interact with toggle

ui/app/mainui/AppMain.qml, ui/imports/shared/panels/ModuleWarning.qml
Closes #10607
WarningBanners should show only if after 3 seconds are still active ([as per design change](https://github.com/status-im/status-desktop/issues/10607#issuecomment-1715317966))
WarningBanners
=> fix(WarningBanners): updated show/hide as per design

ui/imports/shared/popups/send/SendModal.qml
=> feat(@wallet): Add buffer to max input

fleets.json, src/app/core/fleets/fleet_configuration.nim, src/app_service/service/accounts/service.nim, src/app_service/service/node_configuration/dto/node_config.nim, src/app_service/service/node_configuration/service.nim, src/app_service/service/settings/dto/settings.nim, src/app_service/service/settings/service.nim, ui/app/AppLayouts/Profile/popups/FleetsModal.qml, ui/app/AppLayouts/Profile/stores/AdvancedStore.qml, ui/imports/utils/Constants.qml
Requires:
- https://github.com/status-im/status-go/pull/4094
- https://github.com/status-im/status-go/pull/4161
- https://github.com/status-im/status-go/pull/4289
=> feat: shards.test fleet

ui/imports/shared/panels/DidYouKnowSplashScreen.qml, ui/main.qml
`DidYouKnowSplashScreen.qml` has now object name
=> chore(@SplashScreen): add object name

ui/imports/shared/popups/UserAgreementPopup.qml
add object names to UserAgreementPopup.qml
UserAgreementPopup.qml
=> chore: add object names to UserAgreementPopup.qml

ui/app/AppLayouts/Profile/ProfileLayout.qml
object name in ProfileLayout.qml
ProfileLayout.qml
=> chore: object name in ProfileLayout.qml

fleets.json, src/app/core/fleets/fleet_configuration.nim, src/app_service/service/accounts/service.nim, src/app_service/service/node_configuration/dto/node_config.nim, src/app_service/service/node_configuration/service.nim, src/app_service/service/settings/dto/settings.nim, src/app_service/service/settings/service.nim, ui/app/AppLayouts/Profile/popups/FleetsModal.qml, ui/app/AppLayouts/Profile/stores/AdvancedStore.qml, ui/imports/utils/Constants.qml
It caused issues with the filter/light-push mode.
=> reverts the shard fleet commits on desktop and status-go

ui/app/AppLayouts/Communities/panels/MintTokensSettingsPanel.qml
Closes #12648
CommunitySettings/Tokens: Updated page title as per design
CommunitySettings/Tokens
=> fix(CommunitySettings/Tokens): Updated page title

ui/app/AppLayouts/Wallet/views/walletconnect/WalletConnect.qml, ui/app/AppLayouts/Wallet/views/walletconnect/WalletConnectSDK.qml, ui/app/AppLayouts/Wallet/views/walletconnect/sdk/README.md, vendor/DOtherSide/lib/src/Status/AppDelegate.mm
Validated that WebEngineView runs SDK in the background and can be hidden from view.
Some more cleanup
Follow up task https://github.com/status-im/status-desktop/issues/12791
=> feat(wallet): WalletConnect web engine view runs SDK in background

ui/StatusQ/src/StatusQ/Components/StatusImage.qml
Closes #10139
Improved sourcesize width/height
StatusImage
=> fix(StatusImage): Improved sourcesize width/height

ui/app/AppLayouts/Chat/ChatLayout.qml
Cherry-pick of https://github.com/status-im/status-desktop/pull/12824
=> Cherry-pick + up status-go

src/app/core/notifications/notifications_manager.nim, src/app/global/app_signals.nim, src/app/modules/main/io_interface.nim, src/app/modules/main/module.nim, src/app/modules/main/view.nim, ui/main.qml
=> fix(notifs): only process notifs once the loading screen is done

ci/Jenkinsfile.combined, ci/Jenkinsfile.linux, ci/Jenkinsfile.macos, ci/Jenkinsfile.tests-e2e, ci/Jenkinsfile.tests-nim, ci/Jenkinsfile.tests-ui, ci/Jenkinsfile.windows
Requires:
* https://github.com/status-im/status-jenkins-lib/pull/81
=> chore(ci): add Sepolia API keys as on credential

src/app_service/service/community_tokens/service.nim
Fix #12847
Corresponding release pr: https://github.com/status-im/status-desktop/pull/12874
=> fix(@desktop/communities): Fix fees estimation crash

src/app/modules/main/profile_section/ens_usernames/controller.nim, src/app/modules/main/profile_section/ens_usernames/io_interface.nim, src/app/modules/main/profile_section/ens_usernames/module.nim, src/app/modules/main/profile_section/module.nim, src/app_service/service/ens/service.nim, src/backend/ens.nim
Corresponding `stauts-go` PR:
- https://github.com/status-im/status-go/pull/4397
Closes the second part of #12556
=> Signing buying/releasing ens usernames using keycard

ui/imports/utils/Utils.qml
Fixes: #12848
Fix new links to profile validation in qml
Processing new links format
=> fix(new-links): Fix processing links to profile without encoded data

ui/app/AppLayouts/Profile/popups/SendContactRequestModal.qml
Fixes: #12829
Updates validation process for new links formats in `Settings->Messaging->Send Contact Request`
Send contact request dialog
=> fix(contacts): Fix new url format validation in contact request dialog from settings

src/app/modules/shared_modules/keycard_popup/controller.nim, src/app/modules/shared_modules/keycard_popup/io_interface.nim, src/app/modules/shared_modules/keycard_popup/module.nim, src/app_service/common/async_tasks.nim, src/app_service/service/keycard/service.nim
=> chore(@desktop/keycard): improvement in terms of avoiding overlapping keycard library flows

src/app/modules/main/wallet_section/wallet_connect/controller.nim, src/app/modules/main/wallet_section/wallet_connect/tx_response_dto.nim, src/app_service/service/community_tokens/service.nim, src/app_service/service/transaction/dto.nim, src/backend/wallet.nim, src/backend/wallet_connect.nim
- https://github.com/status-im/status-go/pull/4414
=> chore(walletconnect): adapting to improvements done on the statusgo side

src/app/modules/main/profile_section/privacy/controller.nim, src/app/modules/main/profile_section/privacy/io_interface.nim, src/app/modules/main/profile_section/privacy/module.nim, src/app/modules/main/profile_section/privacy/view.nim, src/app_service/service/privacy/service.nim, src/app_service/service/settings/service.nim, src/backend/settings.nim, ui/app/AppLayouts/Profile/popups/BackupSeedModal.qml, ui/app/AppLayouts/Profile/popups/backupseed/ConfirmSeedPhrasePanel.qml, ui/app/AppLayouts/Profile/stores/PrivacyStore.qml
needed for https://github.com/status-im/status-go/issues/4200
status: ready
=> Mark mnemonic as shown on revealing it to the user

ui/imports/shared/popups/send/SendModal.qml
=> fix(@wallet): prevent max amount to be ellipsed

ui/imports/shared/status/StatusImageModal.qml
Closes #10080
StatusImageModal: fixed Image view is not scaled with window size changes
StatusImageModal
https://github.com/status-im/status-desktop/assets/31625338/0e22ea0a-3431-4981-868b-753db6d1da23
=> fix(StatusImageModal): Image view is not scaled with window size changes

ui/app/AppLayouts/Wallet/stores/ActivityFiltersStore.qml
=> fix(@wallet): period filter for this week/this month

ui/app/AppLayouts/Profile/views/wallet/AccountView.qml
=> fix(@wallet): Rename edit watch address

ui/StatusQ/src/concatmodel.cpp, ui/StatusQ/tests/tst_ConcatModel.cpp
- changes the way of handling model reset of source submodels. Now it's notified from ConcatModel as removal/insertion
- fixes crash when source model is reset but ConcatModel is not initialized
- new tests added
- some other minor fixes
Closes: #12974
`StatusQ/ConcatModel`
=> fix(StatusQ/ConcatModel): Handle source submodel reset properly, tests amended

test/ui-test/testSuites/suite_wallet/tst_wallet_accountsManagement/test.feature
=> chore: fix test with new design

test/ui-test/testSuites/suite_wallet/tst_wallet_accountsManagement/test.feature, ui/app/AppLayouts/Profile/views/wallet/AccountView.qml, ui/app/AppLayouts/Wallet/views/LeftTabView.qml, ui/imports/shared/popups/RemoveAccountConfirmationPopup.qml
=> feat(@wallet): delete account new design

src/app/modules/main/communities/tokens/controller.nim, src/app/modules/main/communities/tokens/io_interface.nim, src/app/modules/main/communities/tokens/module.nim, src/app/modules/main/communities/tokens/view.nim, src/app/modules/main/wallet_section/send/controller.nim, src/app/modules/main/wallet_section/send/io_interface.nim, src/app/modules/main/wallet_section/send/module.nim, src/app/modules/main/wallet_section/send/view.nim, src/app_service/service/transaction/service.nim, ui/app/AppLayouts/Communities/helpers/TokenObject.qml, ui/app/AppLayouts/Communities/panels/MintTokensSettingsPanel.qml, ui/app/AppLayouts/Communities/panels/OverviewSettingsPanel.qml, ui/app/AppLayouts/Communities/popups/TransferOwnershipPopup.qml, ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml, ui/app/AppLayouts/Wallet/WalletLayout.qml, ui/app/mainui/Popups.qml, ui/imports/shared/popups/send/SendModal.qml, ui/imports/shared/stores/CommunityTokensStore.qml, ui/imports/shared/stores/send/TransactionStore.qml, ui/imports/utils/Global.qml
Add toasts to send owner token process.
Also a few additional issues fixed:
- fixed transfer ownership button from Overview screen
- set correct data in SendModal - token is autoselected
Issue #12656
https://github.com/status-im/status-desktop/assets/61889657/5ceb39b2-55a4-4566-a881-2f519c8b885f
=> fix(@desktop/communities): Add toasts to send owner token process

src/app/boot/app_controller.nim, src/app/global/app_signals.nim, src/app/modules/main/wallet_section/wallet_connect/controller.nim, ui/app/AppLayouts/Wallet/views/walletconnect/WalletConnectModal.qml, ui/app/AppLayouts/Wallet/views/walletconnect/WalletConnectSDK.qml
Continuation of changes made here https://github.com/status-im/status-desktop/pull/13014
Closes: #12993
=> Check for potential WalletConnect pairings after the user logs in

src/app/global/local_account_settings.nim, src/app_service/service/accounts/service.nim
=> fix(@desktop/general): biometrics prompt is shown after restarting the app even it was not enabled

ui/app/AppLayouts/Onboarding/views/InsertDetailsView.qml
Add an object name for emoji hash so i can access this object easier and get is properties
=> chore: add object name for emoji hash

src/app_service/service/community/service.nim
Fixes all found issues, where accepted members could stay on the pending list:
- member auto-accepted by the control node
- member accepted by the privileged member
- member leaves the community and requests to join the community again, privileged member approves request to join
Closes: https://github.com/status-im/status-desktop/issues/12904
status-go PR: https://github.com/status-im/status-go/pull/4487
- Members pending list
https://github.com/status-im/status-desktop/assets/117639195/27ccd55c-8af1-4ee3-b799-d538fd8d8046
=> fix(@desktop/requestsToJoin): do not display approved people in the pending list

src/app/modules/startup/models/fetching_data_model.nim, ui/app/AppLayouts/Onboarding/views/ProfileFetchingView.qml
=> fix(@desktop/onboarding): when recovering user sometimes needs to wait for the end of the countdown even if all backup data are fetched

ui/app/AppLayouts/Communities/controls/PermissionItem.qml
Object name for PermissionItem
`ui/app/AppLayouts/Communities/controls/PermissionItem.qml`
=> chore: object name for permission item

ui/app/AppLayouts/Wallet/WalletLayout.qml, ui/app/mainui/AppMain.qml
=> fix(@wallet): open sign modal only when ready

ui/app/AppLayouts/Profile/panels/SupportedTokenListsPanel.qml, ui/app/AppLayouts/Profile/popups/TokenListPopup.qml
=> fix(@wallet): prevent black image in token list

ui/StatusQ/sandbox/controls/Others.qml, ui/StatusQ/src/StatusQ/Components/StatusDraggableListItem.qml, ui/StatusQ/src/StatusQ/Components/StatusLetterIdenticon.qml, ui/StatusQ/src/StatusQ/Components/StatusListItemBadge.qml, ui/StatusQ/src/StatusQ/Components/StatusSmartIdenticon.qml, ui/StatusQ/src/StatusQ/Core/StatusAssetSettings.qml, ui/StatusQ/src/StatusQ/Popups/statusModal/StatusImageWithTitle.qml, ui/app/AppLayouts/Browser/controls/BookmarkButton.qml, ui/app/AppLayouts/Wallet/controls/SavedAddressesDelegate.qml, ui/app/AppLayouts/Wallet/popups/AddEditSavedAddressPopup.qml, ui/app/AppLayouts/Wallet/views/SavedAddresses.qml
=> feat(savedaddresses): make save addresses list as per design (without search logic)

src/app/modules/main/wallet_section/saved_addresses/module.nim, src/app/modules/main/wallet_section/saved_addresses/view.nim, test/ui-test/src/screens/StatusWalletScreen.py, test/ui-test/src/screens/components/confirmation_popup.py, test/ui-test/testSuites/global_shared/scripts/settings_names.py, test/ui-test/testSuites/global_shared/scripts/wallet_names.py, ui/app/AppLayouts/Wallet/controls/SavedAddressesDelegate.qml, ui/app/AppLayouts/Wallet/popups/RemoveSavedAddressPopup.qml, ui/app/AppLayouts/Wallet/popups/qmldir, ui/app/mainui/AppMain.qml
=> feat(savedaddresses): context menu - remove saved address

src/app/modules/main/wallet_section/saved_addresses/item.nim, src/app/modules/main/wallet_section/saved_addresses/model.nim, src/app/modules/main/wallet_section/saved_addresses/module.nim, src/app/modules/main/wallet_section/saved_addresses/view.nim, test/ui-test/src/screens/StatusWalletScreen.py, test/ui-test/src/screens/components/confirmation_popup.py, test/ui-test/testSuites/global_shared/scripts/settings_names.py, test/ui-test/testSuites/global_shared/scripts/wallet_names.py, ui/app/AppLayouts/Wallet/controls/SavedAddressesDelegate.qml, ui/app/AppLayouts/Wallet/popups/RemoveSavedAddressPopup.qml, ui/app/AppLayouts/Wallet/popups/qmldir, ui/app/mainui/AppMain.qml
=> feat(savedaddresses): context menu - edit saved address

src/app/modules/main/wallet_section/assets/view.nim, ui/imports/shared/views/AssetsView.qml
=> fix(@desktop/wallet): Improving performance when switching accounts

src/app/modules/main/chat_section/chat_content/input_area/controller.nim, src/app/modules/main/chat_section/chat_content/input_area/io_interface.nim, src/app/modules/main/chat_section/chat_content/input_area/module.nim, src/app/modules/main/chat_section/chat_content/input_area/view.nim, src/app/modules/main/chat_section/chat_content/module.nim
Fixes https://github.com/status-im/status-desktop/issues/12624
=> fix: use local nickname in chat input link previews

Makefile, config.nims, scripts/fetch-brew-bottle.sh, vendor/DOtherSide/lib/CMakeLists.txt
- https://github.com/status-im/status-go/pull/4549
=> Broken release build for mac x86 fixed

test/ui-test/src/screens/StatusWalletScreen.py, ui/app/AppLayouts/Wallet/controls/SavedAddressesDelegate.qml
=> bug(savedaddresses): the send modal should be run clicking on the send button of a saved address item

src/app/modules/main/wallet_section/assets/grouped_account_assets_model.nim, src/app/modules/main/wallet_section/assets/module.nim, src/app/modules/main/wallet_section/assets/view.nim, src/app/modules/main/wallet_section/module.nim, src/app/modules/main/wallet_section/view.nim, src/app_service/service/token/service.nim, src/app_service/service/wallet_account/dto/account_token_item.nim, src/app_service/service/wallet_account/service.nim, src/app_service/service/wallet_account/service_account.nim, src/app_service/service/wallet_account/service_token.nim, src/app_service/service/wallet_account/service_token_new.nim, ui/app/AppLayouts/Wallet/stores/RootStore.qml, ui/app/AppLayouts/Wallet/views/RightTabView.qml, ui/imports/shared/views/AssetsView.qml
fixes #13137, fixes https://github.com/status-im/status-desktop/issues/13144
Calls newBuildWalletTokens on test networks toggled , please note the old buildWalletTokens will be replaced with the newBuildWallet tokens under https://github.com/status-im/status-desktop/issues/13142
Solves below issues on AssetsView.qml -
1. Refresh after 10 mins doesnt work
2. Add new account doesnt work
3. switching test networks doesnt work
4. swtching currency doesnt work
AssetsView
https://github.com/status-im/status-desktop/assets/60327365/a8b5f4c3-a814-4855-9677-db0c633e3c94 …
=> fix(@desktop/wallet): Switching networks doesn't change assets

ui/app/AppLayouts/Wallet/views/SavedAddressesView.qml
Added object name for saved addresses area
SavedAddressesView.qml
=> Object name for saved addresses area added

ui/app/AppLayouts/Communities/views/MintedTokensView.qml
Fix #12905
- Just a text change depending on user profile.
Community Settings / Mint Tokens / Owner token
https://github.com/status-im/status-desktop/assets/97019400/49244654-ef69-4974-81d0-6f51031c1fe4
=> fix(OwnerToken): Change owner token subtitle depending on user profile

src/app/modules/main/wallet_section/networks/model.nim, src/app/modules/main/wallet_section/networks/view.nim, src/app/modules/main/wallet_section/saved_addresses/io_interface.nim, src/app/modules/main/wallet_section/saved_addresses/module.nim, src/app/modules/main/wallet_section/saved_addresses/view.nim, ui/StatusQ/src/StatusQ/Controls/StatusRoundButton.qml, ui/app/AppLayouts/Profile/popups/WalletAddressMenu.qml, ui/app/AppLayouts/Profile/views/wallet/AccountView.qml, ui/app/AppLayouts/Wallet/WalletLayout.qml, ui/app/AppLayouts/Wallet/controls/SavedAddressesDelegate.qml, ui/app/AppLayouts/Wallet/popups/AddEditSavedAddressPopup.qml, ui/app/AppLayouts/Wallet/popups/ReceiveModal.qml, ui/app/AppLayouts/Wallet/popups/TransactionAddressMenu.qml, ui/app/AppLayouts/Wallet/stores/RootStore.qml, ui/app/mainui/AppMain.qml, ui/imports/shared/popups/send/controls/AccountsModalHeader.qml, ui/imports/utils/Constants.qml, ui/imports/utils/Global.qml, ui/imports/utils/Utils.qml
This pr introduces actions for the saved address item's context menu.
Apart from that, it makes adding/editing popup's content scrollable, reactors QR popup to be reusable and introduces a new UI design for it.
Changes are split into several commits for easier review.
=> Saved addresses - context menu

ui/StatusQ/src/writableproxymodel.cpp
Nim models are crashing when calling `itemData`. A workaround for this is to re-implement the `itemData` calls in the writableModel.
Moreover, the default `itemData` implementation in the QAbstractItemModel seems to process only the static roles.
WritableProxyModel
=> fix(StatusQ): Fixing a crash when the source model is a nim model

src/app/modules/main/communities/tokens/models/token_owners_item.nim, src/app/modules/main/communities/tokens/models/token_owners_model.nim, src/app_service/service/community_tokens/async_tasks.nim, src/app_service/service/community_tokens/community_collectible_owner.nim, src/app_service/service/community_tokens/service.nim, src/backend/backend.nim, src/backend/collectibles_types.nim, test/nim/collectibles_types_conversions_test.nim, ui/app/AppLayouts/Communities/controls/TokenHolderListItem.qml, ui/app/AppLayouts/Communities/panels/SortableTokenHoldersList.qml, ui/app/AppLayouts/Communities/panels/SortableTokenHoldersPanel.qml, ui/app/AppLayouts/Communities/views/CommunityTokenView.qml
Add displaying holders for ERC20 - only community members.
Add json conversions test for some holders structs.
Displaying ERC721 holders worked every time for me. Could not reproduce the problem described in task.
Fix #12062
=> 12062 fix token holders

src/app/modules/main/wallet_section/all_collectibles/controller.nim, src/app/modules/main/wallet_section/all_collectibles/io_interface.nim, src/app/modules/main/wallet_section/all_collectibles/module.nim, src/app/modules/main/wallet_section/all_collectibles/view.nim, src/app/modules/main/wallet_section/module.nim, src/app/modules/main/wallet_section/view.nim, src/app/modules/shared_models/collectible_ownership_model.nim, src/app/modules/shared_models/collectibles_entry.nim, src/app/modules/shared_models/collectibles_model.nim, src/app/modules/shared_modules/collectibles/controller.nim, src/backend/collectibles.nim, storybook/pages/CollectiblesViewPage.qml, storybook/src/Models/ManageCollectiblesModel.qml, ui/app/AppLayouts/Profile/views/WalletView.qml, ui/app/AppLayouts/Wallet/stores/CollectiblesStore.qml, ui/app/AppLayouts/Wallet/views/CollectiblesView.qml, ui/app/AppLayouts/Wallet/views/RightTabView.qml
Fixes #13235
Replace the plain Collectibles Controller for a new AllCollectibles model which contains a full list of collectibles, to be filtered with the SFPM.
https://github.com/status-im/status-desktop/assets/11161531/213d46a8-6f55-4c3d-9272-5bbfc8745001
=> feat(@desktop/wallet): implement allCollectibles module

src/app/core/fleets/fleet_configuration.nim, src/app/modules/main/node_section/controller.nim, src/app/modules/main/node_section/io_interface.nim, src/app/modules/main/node_section/module.nim, src/app/modules/main/node_section/view.nim, src/app/modules/main/profile_section/advanced/controller.nim, src/app/modules/main/profile_section/advanced/io_interface.nim, src/app/modules/main/profile_section/advanced/module.nim, src/app/modules/main/profile_section/advanced/view.nim, src/app_service/common/network_constants.nim, src/app_service/service/accounts/service.nim, src/app_service/service/mailservers/service.nim, src/app_service/service/node/service.nim, src/app_service/service/node_configuration/service.nim, src/app_service/service/settings/service.nim, src/backend/communities.nim, src/backend/node.nim, src/constants.nim, ui/app/AppLayouts/Profile/popups/AddWakuStoreModal.qml, ui/app/AppLayouts/Profile/popups/FleetsModal.qml, ui/app/AppLayouts/Profile/stores/AdvancedStore.qml, ui/app/AppLayouts/Profile/views/AdvancedView.qml, ui/imports/utils/Constants.qml
Adds missing commits from https://github.com/status-im/status-desktop/pull/12963
Fixes https://github.com/status-im/status-desktop/issues/13246
=> fix: add missing commits to set shards.test as default and remove status.prod mentions

src/app/boot/app_controller.nim, src/app/modules/startup/controller.nim, src/app_service/service/accounts/service.nim
=> feat(onboarding): remove mnemonic as early as possible

storybook/pages/ManageAssetsPanelPage.qml, storybook/pages/ManageCollectiblesPanelPage.qml, storybook/pages/ManageHiddenPanelPage.qml, storybook/qmlTests/tests/tst_ManageCollectiblesPanel.qml, storybook/src/Models/ManageCollectiblesModel.qml, storybook/src/Models/ManageTokensModel.qml, ui/StatusQ/src/StatusQ/Controls/StatusRadioButton.qml, ui/StatusQ/src/StatusQ/Controls/StatusSwitch.qml, ui/StatusQ/src/wallet/managetokenscontroller.cpp, ui/StatusQ/src/wallet/managetokenscontroller.h, ui/StatusQ/src/wallet/managetokensmodel.cpp, ui/StatusQ/src/wallet/managetokensmodel.h, ui/app/AppLayouts/Wallet/controls/FilterComboBox.qml, ui/app/AppLayouts/Wallet/controls/ManageTokenMenuButton.qml, ui/app/AppLayouts/Wallet/controls/ManageTokensDelegate.qml, ui/app/AppLayouts/Wallet/controls/ManageTokensGroupDelegate.qml, ui/app/AppLayouts/Wallet/panels/ManageAssetsPanel.qml, ui/app/AppLayouts/Wallet/panels/ManageCollectiblesPanel.qml, ui/app/AppLayouts/Wallet/panels/ManageHiddenPanel.qml, ui/app/AppLayouts/Wallet/views/CollectiblesView.qml, ui/imports/shared/views/AssetsView.qml
- simplify the delegates (no more nested inner models/ListViews)
- persist the "Arrange by" toggles state (when needed)
- adjust the tests
Fixes #13232
Wallet/Settings/Manage tokens/Collectibles
=> feat(Manage Tokens): implement "Arrange by collection"

storybook/pages/AssetsViewPage.qml, storybook/pages/SendModalPage.qml, storybook/src/Models/WalletSendAccountsModel.qml, storybook/stubs/AppLayouts/Wallet/stores/ActivityFiltersStore.qml, storybook/stubs/AppLayouts/Wallet/stores/TokensStore.qml, storybook/stubs/AppLayouts/Wallet/stores/WalletAssetsStore.qml, storybook/stubs/AppLayouts/Wallet/stores/qmldir, storybook/stubs/shared/stores/send/TransactionStore.qml, ui/app/AppLayouts/Browser/BrowserLayout.qml, ui/app/AppLayouts/Chat/ChatLayout.qml, ui/app/AppLayouts/Chat/views/ChatView.qml, ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml, ui/app/AppLayouts/Profile/ProfileLayout.qml, ui/app/AppLayouts/Profile/views/EnsDetailsView.qml, ui/app/AppLayouts/Profile/views/EnsSearchView.qml, ui/app/AppLayouts/Profile/views/EnsTermsAndConditionsView.qml, ui/app/AppLayouts/Profile/views/EnsView.qml, ui/app/mainui/AppMain.qml, ui/imports/shared/popups/send/SendModal.qml, ui/imports/shared/popups/send/controls/TokenBalancePerChainDelegate.qml, ui/imports/shared/popups/send/panels/HoldingSelector.qml, ui/imports/shared/popups/send/views/TokenListView.qml, ui/imports/shared/status/StatusStickerMarket.qml, ui/imports/shared/status/StatusStickerPackClickPopup.qml, ui/imports/shared/status/StatusStickersPopup.qml, ui/imports/shared/stores/send/TransactionStore.qml
Adapt tot he new assets model in the SendModal
SendModal
Uploading Screen Recording 2024-01-16 at 8.38.25 PM.mov…
=> Flat account assets in send

ui/app/AppLayouts/Profile/panels/SupportedTokenListsPanel.qml, ui/app/AppLayouts/Profile/views/wallet/ManageTokensView.qml
Closes #13253
ManageTokensView: Restructured contents in column
ManageTokensView
=> [ManageTokensView]: Restructured contents in column

storybook/pages/ManageAssetsPanelPage.qml, storybook/pages/ManageCollectiblesPanelPage.qml, storybook/pages/ManageHiddenPanelPage.qml, storybook/qmlTests/tests/tst_ManageCollectiblesPanel.qml, storybook/src/Models/ManageCollectiblesModel.qml, ui/StatusQ/src/StatusQ/Components/StatusDraggableListItem.qml, ui/StatusQ/src/StatusQ/Controls/StatusRadioButton.qml, ui/StatusQ/src/StatusQ/Controls/StatusSwitch.qml, ui/StatusQ/src/wallet/managetokenscontroller.cpp, ui/StatusQ/src/wallet/managetokenscontroller.h, ui/StatusQ/src/wallet/managetokensmodel.cpp, ui/StatusQ/src/wallet/managetokensmodel.h, ui/app/AppLayouts/Profile/views/SettingsContentBase.qml, ui/app/AppLayouts/Profile/views/WalletView.qml, ui/app/AppLayouts/Profile/views/wallet/ManageTokensView.qml, ui/app/AppLayouts/Wallet/WalletLayout.qml, ui/app/AppLayouts/Wallet/controls/FilterComboBox.qml, ui/app/AppLayouts/Wallet/controls/ManageTokenMenuButton.qml, ui/app/AppLayouts/Wallet/controls/ManageTokensCommunityTag.qml, ui/app/AppLayouts/Wallet/controls/ManageTokensDelegate.qml, ui/app/AppLayouts/Wallet/controls/ManageTokensGroupDelegate.qml, ui/app/AppLayouts/Wallet/panels/ManageAssetsPanel.qml, ui/app/AppLayouts/Wallet/panels/ManageCollectiblesPanel.qml, ui/app/AppLayouts/Wallet/panels/ManageHiddenPanel.qml, ui/app/AppLayouts/Wallet/panels/qmldir, ui/app/AppLayouts/Wallet/views/CollectiblesView.qml, ui/app/mainui/AppMain.qml, ui/imports/shared/views/AssetsView.qml, ui/imports/utils/Constants.qml
(all of the partial PRs have been reviewed and tested before in the feature branch; see the individual commits )
Implements these new token management features:
- [feat: Create the hidden tab (to host both assets and collectibles)](https://github.com/status-im/status-desktop/commit/32553eeb7df9e788bd40367df90d2db5a4a3a9d3)
- [feat(Manage Tokens): implement "Arrange by collection"](https://github.com/status-im/status-desktop/commit/f70452faebcd8b20c550be2a7bb9c91cddfac9c2)
- [fix: apply Custom order to main wallet view](https://github.com/status-im/status-desktop/commit/47657d35a674ff41a51ccd152c2e9f44fd21dc52)
- [fix: fake collections shouldn't be visible in a filtering combo](https://github.com/status-im/status-desktop/commit/3a79b6a7cbdc6972de42d69b2f860f52e406f339)
- [fix: cleanup and …
=> feat: Wallet mgmt 2nd iteration

storybook/pages/FirstTokenReceivedPopupPage.qml, ui/app/AppLayouts/Communities/popups/FirstTokenReceivedPopup.qml, ui/app/AppLayouts/Communities/popups/qmldir, ui/app/mainui/Popups.qml, ui/app/mainui/ToastsManager.qml, ui/imports/shared/stores/CommunityTokensStore.qml, ui/imports/utils/Global.qml
Closes #12366
- Created new popup component.
- Created related `storybook` page.
- Integration of the popup into the app.
**NOTE:** Out of scope --> Hide token button -->  #13293
First token received toast
- Storybook:
https://github.com/status-im/status-desktop/assets/97019400/b617de33-7d25-4fb2-bf4d-e3e1b9695552
- App integration (hardcoded code to force the toast is being displayed):
https://github.com/status-im/status-desktop/assets/97019400/e50acd15-1367-4014-8531-81c1a729b9b4
=> feat(FirstTokenReceivedPopup): Created new popup `FirstTokenReceived`

src/app/modules/main/io_interface.nim, src/app/modules/main/module.nim, src/app/modules/main/profile_section/profile/controller.nim, src/app/modules/main/profile_section/profile/io_interface.nim, src/app/modules/main/profile_section/profile/module.nim, src/app/modules/main/profile_section/profile/view.nim, src/app/modules/main/view.nim, src/app/modules/main/wallet_section/accounts/io_interface.nim, src/app/modules/main/wallet_section/accounts/module.nim, src/app/modules/main/wallet_section/accounts/view.nim, src/app_service/service/profile/async_tasks.nim, src/app_service/service/profile/dto/profile_showcase.nim, src/app_service/service/profile/service.nim, src/app_service/service/wallet_account/dto/account_dto.nim, src/backend/accounts.nim, ui/app/AppLayouts/Chat/views/ChatColumnView.qml, ui/app/AppLayouts/Communities/controls/TokenHolderListItem.qml, ui/app/AppLayouts/Wallet/popups/AddEditSavedAddressPopup.qml, ui/app/AppLayouts/Wallet/stores/RootStore.qml, ui/app/mainui/activitycenter/views/ActivityNotificationCommunityMembershipRequest.qml, ui/app/mainui/activitycenter/views/ActivityNotificationContactRemoved.qml, ui/app/mainui/activitycenter/views/ActivityNotificationMessage.qml, ui/imports/shared/controls/ContactSelector.qml, ui/imports/shared/controls/TransactionAddress.qml, ui/imports/shared/views/SearchResults.qml, ui/imports/utils/Utils.qml
- https://github.com/status-im/status-go/pull/4632
Closes: #13280
https://github.com/status-im/status-desktop/assets/86303051/17f473d7-7c0a-4b95-9117-62fd19ce7aa1
=> feat(savedaddresses): display various cards if an address user is trying to save is known

src/app_service/service/wallet_account/service_keycard.nim
=> chore(@wallet): cache get keycards with same key uid

src/app/modules/main/wallet_section/activity/events_handler.nim, test/status-go/integration/README.md, test/status-go/integration/go.mod, test/status-go/integration/go.sum, test/status-go/integration/helpers/helpers.go, test/status-go/integration/wallet/activityfiltering_test.go, test/status-go/integration/wallet/common.go, test/status-go/integration/wallet/pendingtransactions_test.go
Requires status-go [#4480](https://github.com/status-im/status-go/pull/4480)
The test is used to investigate the deadlock caused by sending a message while in a message handler. It will be used later for debugging the other incremental events.
=> test(wallet) add dev integration tests for incremental activity updates

src/app/modules/main/wallet_section/all_tokens/controller.nim, src/app/modules/main/wallet_section/all_tokens/module.nim, src/app/modules/main/wallet_section/all_tokens/view.nim, src/app_service/service/token/dto.nim, src/app_service/service/token/service.nim, storybook/pages/TokenListPopupPage.qml, storybook/src/Models/SourceOfTokensModel.qml, ui/app/AppLayouts/Profile/panels/SupportedTokenListsPanel.qml, ui/app/AppLayouts/Profile/popups/TokenListPopup.qml, ui/app/AppLayouts/Profile/views/WalletView.qml, ui/app/AppLayouts/Profile/views/wallet/ManageTokensView.qml, ui/app/AppLayouts/Wallet/stores/TokensStore.qml
fixes #13269
https://github.com/status-im/status-go/pull/4664
=> feat(@wallet): token list global updated at

fleets.json, libs/Onboarding/src/Onboarding/Common/Constants.h, resources/fleets_cpp.json, src/app/core/fleets/fleet_configuration.nim, src/app_service/service/settings/dto/settings.nim, src/app_service/service/settings/service.nim
See https://github.com/status-im/infra-go-waku/issues/18 for more details
=> chore: go-waku fleets cleanup

storybook/pages/MovableModelPage.qml, storybook/pages/MovableModelWithSfpmPage.qml, ui/StatusQ/src/movablemodel.cpp
Presents flow allowing to maintain ordering using `MovableModel` proxy with combination with SFPM.
This approach is intended to be used in `Profle Showcase` functionality (settings part).
Additionally, the PR fixes small issue in `MovableModel` (improper index was passed to source model in data(...) method)
[Kazam_screencast_00087.webm](https://github.com/status-im/status-desktop/assets/20650004/dbe12f7f-8919-4447-bf95-b3c8254dfa7b)
`MovableModel`, `Storybook`
=> Storybook: PoC flow with SFPM, MovableModel and drag&drop

src/app_service/service/wallet_account/async_tasks.nim, src/backend/backend.nim
needed for https://github.com/status-im/status-go/issues/4630
=> Replace getWalletTokenBalances with fetchOrGetCachedWalletBalances

ui/app/AppLayouts/Communities/popups/TransferOwnershipPopup.qml
Closes #13288
TransferOwnershipPopup: Added getUidForData function
TransferOwnershipPopup
=> [TransferOwnershipPopup]: Added getUidForData function

ui/imports/shared/popups/ImportCommunityPopup.qml
Closes #12620
Communities: Fixed community key text area scrolling
Communities
=> [Communities]: Fixed community key text area scrolling

ui/imports/utils/Constants.qml
Closes #13456
Profile: Aligned display name max length with mobile
Profile
=> [Profile] Aligned display name max length with mobile

ui/app/AppLayouts/Communities/CommunitiesPortalLayout.qml
Closes #8481
Communities: renamed create community button
Communities
=> [Communities]: remaned create community button

ui/app/AppLayouts/Profile/views/MyProfileView.qml
Added object names for tabs in profile tab bar
MyProfileView.qml
=> chore: object names for profile tab buttons added

storybook/pages/ProfileShowcaseCollectiblesPanelPage.qml, ui/app/AppLayouts/Profile/controls/ShowcaseDelegate.qml
Closes #13336
- Added community badge in `ShowcaseDelegate`.
- Added `storybook` support.
`ShowcaseDelegate`
https://github.com/status-im/status-desktop/assets/97019400/6d8f422e-065c-455f-aa6d-b19db43955c8
=> feat(ShowcaseDelegate): Added community badge

ui/app/AppLayouts/Profile/stores/WalletStore.qml, ui/app/AppLayouts/Profile/views/WalletView.qml, ui/app/AppLayouts/Profile/views/wallet/EditNetworkForm.qml, ui/app/AppLayouts/Profile/views/wallet/EditNetworkView.qml
=> feat(@wallet): add restart required for changes

src/app/modules/main/chat_section/controller.nim, src/app/modules/main/chat_section/module.nim
fix(@desktop/wallet): Fix issues in adding minted collectible as permission in a community
Reverts issues introduced under https://github.com/status-im/status-desktop/pull/13426/files
Add new permission
=> fix(@desktop/wallet): Fix issues in adding minted collectible as permission in a community

test/status-go/integration/helpers/helpers.go, test/status-go/integration/wallet/activityfiltering_test.go, test/status-go/integration/wallet/common.go, test/status-go/integration/wallet/pendingtransactions_test.go
Refactor tests to follow changes in session-based activity API here [#4654](https://github.com/status-im/status-go/pull/4654)
Updates #12120
=> test(wallet) sql integration tests for activity incremental update

ui/app/AppLayouts/Onboarding/views/InsertDetailsView.qml
object name for image cropper
`ui/app/AppLayouts/Onboarding/views/InsertDetailsView.qml`
=> chore: object name for image cropper

src/app/modules/main/wallet_section/saved_addresses/controller.nim, src/app/modules/main/wallet_section/saved_addresses/io_interface.nim, src/app/modules/main/wallet_section/saved_addresses/module.nim, src/app_service/service/saved_address/async_tasks.nim, src/app_service/service/saved_address/dto.nim, src/app_service/service/saved_address/service.nim, src/app_service/service/settings/service.nim, ui/app/AppLayouts/Wallet/popups/AddEditSavedAddressPopup.qml, ui/app/AppLayouts/Wallet/views/SavedAddresses.qml
- https://github.com/status-im/status-go/pull/4716
Closes: #9567
https://github.com/status-im/status-desktop/assets/86303051/7122c6c5-6c90-4541-8271-00ae8c60f419
=> fix(savedaddresses): saved addresses are not in sync between devices

src/app_service/service/profile/dto/profile_showcase.nim, src/app_service/service/profile/dto/profile_showcase_preferences.nim, src/app_service/service/profile/service.nim
Close #13548
Fix saving and requesting empty profile showcase
https://github.com/status-im/status-desktop/assets/2522130/b9924581-bbc6-40a0-8b93-38c161ed64b8
=> fix(Profile): Fix requesting empty profile showcase

src/app_service/service/transaction/service.nim, src/backend/response_type.nim
Cherry-pick of https://github.com/status-im/status-desktop/pull/13117
Needed for security patches
Maintenance bumps of several dependencies - broadly address security issues, 1.6+ compatibility, bugfixes etc to catch up with Nimbus' development
The extra try/catch is due to increased exception safety requirements in `chronicles`, where `fmt` allows dynamic format strings and therefore may raise `ValueError` in theory.
=> [CHERRY-PICK] maintenance bumps

src/app/modules/shared_models/collectibles_entry.nim, src/app/modules/shared_models/collectibles_model.nim, storybook/src/Models/ManageCollectiblesModel.qml, ui/app/AppLayouts/Wallet/views/CollectiblesView.qml
Cherrypick https://github.com/status-im/status-desktop/pull/13569
The status-go commit is already included in the release branch: https://github.com/status-im/status-desktop/commit/16f482cf5193f6f22da5bc0cb69ca94397c29cc6
=> fix(wallet): implement sort collectibles by date

src/app/modules/main/profile_section/advanced/controller.nim, src/app/modules/main/profile_section/advanced/io_interface.nim, src/app/modules/main/profile_section/advanced/module.nim, src/app/modules/main/profile_section/advanced/view.nim, src/app_service/service/node_configuration/dto/node_config.nim, src/app_service/service/node_configuration/service.nim, ui/app/AppLayouts/Profile/stores/AdvancedStore.qml, ui/app/AppLayouts/Profile/views/AdvancedView.qml
This PR adds the Advanced setting toggle for Nimbus enabling.
It fixes [13204](https://github.com/status-im/status-desktop/issues/13204)
This PR is linked to : https://github.com/status-im/status-go/pull/4254
- Settings/Advanced pannel
[Screencast from 2024-01-18 01:06:00 PM.webm](https://github.com/status-im/status-desktop/assets/2589171/1f62b7bf-908f-457d-8fe7-9856a96156f8)
=> Nimbus desktop toggle setting

src/app/modules/main/chat_section/controller.nim, src/app/modules/main/chat_section/module.nim, src/app/modules/main/controller.nim, src/app/modules/main/io_interface.nim, src/app/modules/main/module.nim
Use correct chains when creating permissions: testnet or mainnet.
Status-go [pr](https://github.com/status-im/status-go/pull/4771)
Fixes [#18896](https://github.com/status-im/status-mobile/issues/18896)
=> use correct chains when creating permissions

ui/app/AppLayouts/Communities/controls/Options.qml
As per new designs
Closes #12809
Create new community popup: Adjusted request to join checkbox
Create new community popup
https://github.com/status-im/status-desktop/assets/31625338/7be5019f-f596-41ef-b475-05aab49f9ffa
=> [Create new community popup]: Adjusted request to join

src/app/modules/main/chat_section/module.nim
=> fix(permissions): TMs can also bypass permission to join

src/app/modules/main/communities/controller.nim, src/app/modules/main/communities/io_interface.nim, src/app/modules/main/communities/module.nim, src/app/modules/main/communities/view.nim, src/app_service/service/community/service.nim, src/app_service/service/community_tokens/service.nim, src/backend/communities.nim, src/backend/community_tokens.nim, ui/app/AppLayouts/stores/RootStore.qml, ui/app/mainui/Popups.qml
Fixes https://github.com/status-im/status-desktop/issues/13560
=> feat(communities): hook promoteSelfToControlNode to UI

src/app_service/service/currency/service.nim
fix(@desktop/wallet): Syncing: Difference in decimal places in wallet between synced devices
fixes #13574
Fixes the issue of currency formats not updated on async task fetchAllCurrencyFormatsTaskArg as it is not correctly parsed.
Currency formats
https://github.com/status-im/status-desktop/assets/60327365/5f80bbbe-9bcb-498c-97c8-37e08069870f
=> fix(@desktop/wallet): Syncing: Difference in decimal places in wallet between synced devices

src/app/modules/main/communities/controller.nim, src/app/modules/main/communities/io_interface.nim, src/app/modules/main/communities/module.nim, src/app/modules/main/communities/view.nim, src/app_service/service/community/service.nim, src/backend/communities.nim, ui/app/AppLayouts/Communities/stores/CommunitiesStore.qml
Close #13434
Waits https://github.com/status-im/status-go/pull/4839
Validate the display name against all members of joined communities
Communities
=> feat: Add `IsDisplayNameDupeOfCommunityMember ` endpoint

ui/app/AppLayouts/Profile/views/wallet/MainView.qml
=> fix(wallet): warning that key pair requires import disappears after adding new acc on paired device

ui/app/AppLayouts/Profile/views/LeftTabView.qml
Added object name for settings left panel item so I can locate this item better with my tests
`ui/app/AppLayouts/Profile/views/LeftTabView.qml`
=> chore: add object name for settings left panel

src/app/modules/shared_models/collectibles_entry.nim, src/app/modules/shared_models/collectibles_model.nim, src/app/modules/shared_models/collectibles_nested_item.nim, src/app/modules/shared_models/collectibles_nested_model.nim, src/app/modules/shared_models/collectibles_nested_utils.nim, src/app_service/service/eth/dto/transaction.nim, src/app_service/service/transaction/dto.nim, src/app_service/service/transaction/service.nim, src/backend/collectibles_types.nim, ui/app/AppLayouts/Wallet/views/CollectiblesView.qml, ui/app/AppLayouts/Wallet/views/RightTabView.qml, ui/imports/shared/popups/send/SendModal.qml, ui/imports/shared/popups/send/panels/HoldingSelector.qml, ui/imports/shared/popups/send/views/NetworkSelector.qml, ui/imports/shared/popups/send/views/NetworksSimpleRoutingView.qml, ui/imports/shared/popups/send/views/RecipientView.qml, ui/imports/shared/popups/send/views/TokenListView.qml, ui/imports/shared/stores/send/TransactionStore.qml, ui/imports/utils/Constants.qml
fixes #13797
status-go PR: https://github.com/status-im/status-go/pull/4865
Implement route for sending a ERC1155 token type
SendModal
https://github.com/status-im/status-desktop/assets/60327365/1aa23242-9979-48a6-9d78-57be1380eb34
=> fest(@desktop/wallet): Update Desktop UI to correctly call the router and send

src/app/modules/main/wallet_section/send/controller.nim, src/app/modules/main/wallet_section/send/io_interface.nim, src/app/modules/main/wallet_section/send/module.nim, src/app/modules/main/wallet_section/send/view.nim, src/app_service/service/transaction/service.nim, ui/imports/shared/popups/send/SendModal.qml, ui/imports/shared/stores/send/TransactionStore.qml
=> fix(wallet): erc20 transfer with multiple path

ui/StatusQ/src/StatusQ/Controls/StatusIconSwitch.qml
Added object name for status switch item
ui/StatusQ/src/StatusQ/Controls/StatusIconSwitch.qml
=> chore: object name added for status switch

storybook/pages/StatusChartPanelPage.qml
As part of  #13838
StoryBook: Added Chart Panel page
StoryBook
https://github.com/status-im/status-desktop/assets/31625338/2305b01e-6f9d-4598-83bc-c20ea295bf60
=> [StoryBook] Added Chart Panel in story book

src/app/modules/main/chat_section/chat_content/messages/module.nim
=> fix(@desktop/chat): Fix referencing message nil pointer

src/app/core/notifications/details.nim, src/app/core/notifications/notifications_manager.nim, src/app/global/global_events.nim, src/app/modules/main/ephemeral_notification_item.nim, src/app/modules/main/ephemeral_notification_model.nim, src/app/modules/main/module.nim, src/app/modules/main/view.nim, src/app_service/common/types.nim, src/app_service/service/community/dto/community.nim, src/app_service/service/community/service.nim, ui/app/mainui/AppMain.qml, ui/imports/utils/Constants.qml
Show ban/unban/kick system and ephemeral notifications
Closes: https://github.com/status-im/status-desktop/issues/13597
- system and ephemeral notifications
- setting active chat section
Note: in the video below I force the APP to be active to show ephemeral notifications
https://github.com/status-im/status-desktop/assets/117639195/c4610619-a3f7-46d3-8def-bd7344246224
=> feat: ban/unban/kick system and ephemeral notifications

ui/app/AppLayouts/Profile/helpers/ProfileShowcaseDirtyState.qml, ui/app/AppLayouts/Profile/helpers/ProfileShowcaseModels.qml, ui/app/AppLayouts/Profile/panels/ProfileShowcasePanel.qml, ui/app/AppLayouts/Profile/panels/ProfileSocialLinksPanel.qml, ui/app/AppLayouts/Profile/stores/ProfileStore.qml, ui/app/AppLayouts/Profile/views/MyProfileView.qml, ui/imports/utils/Constants.qml, ui/imports/utils/ProfileUtils.qml
Closes [#13799](https://github.com/status-im/status-desktop/issues/13799)
- Created JSON file according to new backend structure when saving.
- Updated `dirty state` to sync writable and movable models when position is changed to have a better internal models sync.
- Reenabled identity fields save.
**NOTE: Only UI. It needs backend integration task #13688**
https://github.com/status-im/status-desktop/assets/97019400/93967f0e-f0d5-4523-89f1-ee177bf754dc
=> feat(ProfileShowase): Save action with the new backend and integration with backend

src/app_service/service/token/service.nim
status go pr: https://github.com/status-im/status-go/pull/4886
=> fix(@wallet): buy ens from sepolia

src/app/modules/main/communities/module.nim
The model with tokens should be updated also when we import community data.
Fix #13773
https://github.com/status-im/status-desktop/assets/61889657/18346d58-1e7c-41fc-81ea-fb7ca9324d30
=> fix(@desktop/permissions): Fix displaying tokens in permissions

ui/imports/shared/views/PasswordView.qml
Closes #13549
- Backgroun color fix
Password View
- App:
https://github.com/status-im/status-desktop/assets/97019400/8d815a39-ca12-4dfc-a60d-ce77c69f1da2
- Storybook:
https://github.com/status-im/status-desktop/assets/97019400/290e939f-f709-4908-ae5d-692301bf72b0
=> fix(PasswordView): Dark mode background fix

src/app_service/service/community_tokens/async_tasks.nim, src/backend/community_tokens.nim
Issue #13646
Cherry-picked from https://github.com/status-im/status-desktop/pull/13666
=> [CHERRY-PICK] Compute deployment fees dynamically

src/app/modules/main/chat_section/chat_content/view.nim, ui/StatusQ/src/StatusQ/Components/private/statusMessage/StatusMessageEmojiReactions.qml, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Chat/views/ChatColumnView.qml, ui/app/AppLayouts/Chat/views/ChatView.qml, ui/imports/shared/status/StatusChatInput.qml, ui/imports/shared/views/chat/MessageView.qml
Cherry-pick of https://github.com/status-im/status-desktop/pull/13825
=> [CHERRY-PICK] block input in read-only channel

src/app/modules/main/chat_section/chat_content/messages/module.nim, src/app/modules/main/wallet_section/activity/controller.nim, src/app/modules/main/wallet_section/activity/events_handler.nim
=> chore: remove unused imports

src/app/modules/main/profile_section/profile/controller.nim, src/app/modules/main/profile_section/profile/io_interface.nim, src/app/modules/main/profile_section/profile/module.nim, src/app/modules/main/profile_section/profile/view.nim, src/app/modules/startup/controller.nim, src/app_service/service/profile/service.nim, ui/app/AppLayouts/Profile/stores/ProfileStore.qml, ui/app/AppLayouts/Profile/views/MyProfileView.qml
=> Feat: emit signals on profile showcase preferences and save actions

storybook/main.qml, ui/app/AppLayouts/Profile/popups/ConfirmChangePasswordModal.qml
| Design | Implementation |
| - | - |
| ![image](https://github.com/status-im/status-desktop/assets/47554641/e2dd691e-8924-4234-8192-7fa6fe696566) | ![image](https://github.com/status-im/status-desktop/assets/47554641/99d1bd13-2abd-4b39-8f07-1a5f45c2da15) |
=> feat(settings) blur background when re-encrypting due to password change

storybook/pages/TransactionDetailViewPage.qml, storybook/stubs/nim/sectionmocks/WalletSectionAccounts.qml, ui/app/AppLayouts/Profile/popups/WalletAddressMenu.qml, ui/app/AppLayouts/Wallet/controls/SavedAddressesDelegate.qml, ui/app/AppLayouts/Wallet/panels/WalletNftPreview.qml, ui/app/AppLayouts/Wallet/popups/TransactionAddressMenu.qml, ui/app/AppLayouts/Wallet/stores/RootStore.qml, ui/app/AppLayouts/Wallet/views/TransactionDetailView.qml, ui/imports/utils/Constants.qml, ui/imports/utils/Utils.qml
Also
- refactor code for reusability and readability.
- fix storybook to test the links in transaction details view
=> fix(qml): fix etherscan links for all networks

src/app/modules/main/chat_section/chat_content/messages/module.nim
Fixes https://github.com/status-im/status-desktop/issues/14011
My fault. I thought that we don't display the ContactRequest message, but we actually do.
Thanks for catching, @anastasiyaig!
=> fix: allow scrolling to ContactRequest message

ui/StatusQ/src/StatusQ/Core/Utils/Emoji.qml, ui/StatusQ/tests/TestCore/TestUtils/tst_Emoji.qml, ui/imports/shared/popups/addaccount/states/Main.qml
Also add a test to validate the knowledge of the emoji picker function about flags position
=> fix(wallet): pick a random emoji in the wallet new account modal

src/app/modules/main/chat_section/module.nim, src/app/modules/main/controller.nim, src/app/modules/main/module.nim, src/app_service/service/community/service.nim, ui/app/AppLayouts/Chat/ChatLayout.qml, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Chat/views/ChatColumnView.qml, ui/imports/shared/views/chat/InvitationBubbleView.qml
Kinda fixes #13957
Turns out the crash was only in my own account and even though I kept pushing the crash back, it still happened sometimes and finally, it crashed on the weirdest place, ie a `return`.
@kounkou tried to reproduce to help me, and he couldn't. I then tried with a new account and lo and behold, the crash doesn't happen anymore.
So long story short, I was fighting a windmill.
I did at least improve the windmill a little, so there's that. This PR is the result of that. 
So we should see less warnings at least.
=> fix: fix warning and inconsistencies with spectating

src/app_service/service/chat/service.nim
Fixes #14079
[category-muted.webm](https://github.com/status-im/status-desktop/assets/11926403/8e9d3ea6-a4a5-4b45-bda5-78d154aeea12)
=> fix(category): fix muted category and received messages

src/app_service/service/chat/service.nim
Fixes #14079
Cherry-pick of https://github.com/status-im/status-desktop/pull/14082
=> [CHERRY-PICK] fix(category): fix muted category and received messages (#14082)

src/app_service/service/community_tokens/service.nim
This PR fixes #13650
- Reduces the timer for fetching the token hodlers to refresh cashe
- Check for temporary contract address before making requests
During my testing, I noticed that sometimes the contract address provided to status-go is temporary (It ends with `-owner` or `-master` and caused  the error :
```bash
ERR 2024-03-19 09:32:33.670-07:00 Can't fetch community token owners         topics="community-tokens-
service" tid=271622 file=service.nim:1407 chainId=421613
contractAddress="\"0x24b23b3f095f33909b23cff69fc67f6c67242d026a1b93b16a02a4f308cfcf4b-master\""
errorMsg="\nstatus-go error [methodName:wallet_getCollectibleOwnersByContractAddress, code:-32602,
message:invalid argument 1: json: cannot unmarshal hex string of odd length into Go value of type
common.Address ]\n"
```
- …
=> (fix/desktop) fix sporadic empty community token hodler list

src/app/modules/main/chat_section/model.nim
Fixes https://github.com/status-im/status-desktop/issues/14059
=> fix(category): fix missing category when empty

src/app/modules/main/controller.nim, src/app/modules/main/module.nim
Fix community selection bubble display in sections panel after creating the community
=> fix: community selection bubble display in sections panel after creating the community

src/app/modules/shared_modules/add_account/controller.nim, src/app/modules/shared_modules/add_account/module.nim, src/app_service/service/wallet_account/service_account.nim, src/backend/accounts.nim
Corresponding `status-go` issue:
- https://github.com/status-im/status-go/pull/4996
Closes #14188
=> chore: move logic for resolving suggested derivation path to status-go

src/app/modules/main/wallet_section/activity/controller.nim
There is still an issue with layouts that I could not find a fix quickly but the activity list works:
https://github.com/status-im/status-desktop/assets/47554641/102286c6-6802-46b2-bfb2-f26248ad8628
=> fix(wallet) start a session in case of tmp activity models

ui/imports/shared/popups/send/controls/TokenBalancePerChainDelegate.qml
add object name for `TokenBalancePerChainDelegate`
`TokenBalancePerChainDelegate.qml`
=> chore: add object name for TokenBalancePerChainDelegate

test/status-go/integration/go.mod, test/status-go/integration/go.sum, test/status-go/integration/helpers/helpers.go, test/status-go/integration/wallet/activityfiltering_test.go, test/status-go/integration/wallet/common.go, test/status-go/integration/wallet/pendingtransactions_test.go, test/status-go/integration/wallet/sendtransactions_test.go
Bumps status-go to [#5017](https://github.com/status-im/status-go/pull/5017)
Also added a test to debug the issue
=> fix(wallet): activity duplicate in case of non-native transfer 

src/app_service/service/transaction/dto.nim
Fix suggested fees conversion from json.
Related status-go [pr](https://github.com/status-im/status-go/pull/5019)
=> 14307 fix minting fees

src/app/modules/main/chat_section/chat_content/messages/module.nim
[Cherry-picked](https://github.com/status-im/status-desktop/pull/14151)
Issue #14044
=> [CHERRY-PICK] 14044 handle edit messages in bridge master

src/app/modules/main/wallet_section/send/controller.nim, src/app/modules/main/wallet_section/send/io_interface.nim, src/app/modules/main/wallet_section/send/module.nim, src/app/modules/main/wallet_section/send/view.nim, src/app_service/service/eth/dto/transaction.nim, src/app_service/service/transaction/async_tasks.nim, src/app_service/service/transaction/dto.nim, src/app_service/service/transaction/service.nim, src/backend/eth.nim
This PR brings swap via paraswap backend logic, without any UI changes.
- https://github.com/status-im/status-go/pull/5002
UI changes made for the testing purpose are done in this PR: https://github.com/status-im/status-desktop/pull/14286
We're waiting for the final UI which is not ready yet.
Closes #14241
=> feat: swap via paraswap backend implementation

ui/app/AppLayouts/Communities/popups/InDropdown.qml
add object name
`ui/app/AppLayouts/Communities/popups/InDropdown.qml`
=> chore(@ui/app/AppLayouts/Communities/popups/InDropdown): add object name

ui/StatusQ/src/StatusQ/Components/StatusDraggableListItem.qml, ui/app/AppLayouts/Profile/views/wallet/AccountOrderView.qml
Fixed an issue with dropping a draggable item outside the bounds of the DropArea.
Fixes #13836
=> fix(wallet): changes in account order in settings are not applied in wallet

ui/app/AppLayouts/Wallet/views/TransactionDetailView.qml
fixes #14357
This parameter is not part of send modal property
=> fix: repeat tx open the send modal

src/app/modules/shared_modules/keycard_popup/module.nim
This is not an issue actually, instead a request was if the Keycard is present to display an appropriate state based on the Keycard content, which requires the following steps when a user clicks any flow to run:
- run appropriate keycard flow
- wait for a response from the keycard
- resolving state that needs to be displayed based on the response
- display appropriate state
This commit changes that to the following:
- display keycard reading state immediately after the user clicks any flow to run and then the rest as it was
- run appropriate keycard flow
- wait for a response from the keycard
- resolving state that needs to be displayed based on the response
- display appropriate state
With this change on OS' where communication between the app and keycard is slow it wouldn't look like a …
=> feat(keycard): noticeable delay in starting flows

storybook/pages/AssetsViewPage.qml, storybook/pages/NetworkFilterPage.qml, storybook/pages/NetworkSelectPopupPage.qml, ui/StatusQ/src/StatusQ/Components/private/StatusComboboxBackground.qml, ui/StatusQ/src/StatusQ/Components/private/StatusComboboxIndicator.qml, ui/StatusQ/src/StatusQ/Components/private/qmldir, ui/StatusQ/src/StatusQ/Controls/StatusComboBox.qml, ui/StatusQ/src/modelutilsinternal.cpp, ui/StatusQ/src/statusq.qrc, ui/app/AppLayouts/Communities/controls/InlineNetworksComboBox.qml, ui/app/AppLayouts/Wallet/controls/FilterComboBox.qml, ui/app/AppLayouts/Wallet/controls/NetworkFilter.qml, ui/app/AppLayouts/Wallet/controls/SortOrderComboBox.qml, ui/app/AppLayouts/Wallet/views/CollectiblesView.qml, ui/app/AppLayouts/Wallet/views/RightTabView.qml, ui/imports/shared/views/AssetsView.qml
various combobox related fixes and harmonizations; see the respective commits
Fixes #14121
NetworkFilter, StatusComboBox, SortOrderComboBox
Sort/filter combo box:
Network filter:
No activity history:
=> fix(Wallet Filtering): various UI fixes

storybook/pages/StatusAmountInputPage.qml, storybook/qmlTests/tests/tst_StatusAmountInput.qml, ui/StatusQ/src/StatusQ/Components/StatusCard.qml, ui/StatusQ/src/StatusQ/Controls/StatusAmountInput.qml, ui/StatusQ/src/StatusQ/Controls/StatusBaseInput.qml, ui/StatusQ/src/StatusQ/Controls/qmldir, ui/StatusQ/src/StatusQ/Core/LocaleUtils.qml, ui/StatusQ/src/statusq.qrc, ui/app/AppLayouts/Communities/controls/TokenPanel.qml, ui/app/AppLayouts/Profile/views/AdvancedView.qml, ui/imports/shared/popups/send/controls/AmountInputWithCursor.qml, ui/imports/shared/popups/send/views/AmountToSend.qml
Cherrypick of https://github.com/status-im/status-desktop/pull/14399
Task #14163
Screenshot from 0.28.0
=> fix(wallet): Update amount to send decimal handling

src/app/modules/shared_models/currency_amount.nim, src/app_service/service/community_tokens/service.nim
Cherry-picked [1fd013026bc69daabd48b5a122a617791a6fff59](https://github.com/status-im/status-desktop/pull/14406)
=> fix(wallet): fixed precision loss for balance amount in nimqml

ui/StatusQ/src/submodelproxymodel.cpp, ui/StatusQ/tests/tst_SubmodelProxyModel.cpp
So far submodel's proxies were created on the fly, on every data(...) call. Now, once created the proxy is persistent and reused whenever needed. It improves performance in majority of cases and allows to hold state in a submodel proxy.
Closes: #14389
`SubmodelProxyModel`
=> feat(StatusQ/SubmodelProxyModel): persistent submodels proxies

src/app/modules/main/wallet_section/send/module.nim, src/app/modules/shared_models/collectible_ownership_model.nim, src/app/modules/shared_models/collectibles_entry.nim, src/app/modules/shared_models/collectibles_model.nim, src/app/modules/shared_models/collectibles_nested_item.nim, src/app/modules/shared_models/collectibles_nested_model.nim, src/app/modules/shared_models/collectibles_nested_utils.nim, ui/imports/shared/popups/send/SendModal.qml, ui/imports/shared/popups/send/controls/CollectibleNestedDelegate.qml, ui/imports/shared/popups/send/controls/TokenBalancePerChainDelegate.qml, ui/imports/shared/popups/send/panels/HoldingSelector.qml, ui/imports/shared/popups/send/views/TokenListView.qml, ui/imports/shared/stores/send/TransactionStore.qml, ui/imports/utils/Constants.qml
Cherry-picks https://github.com/status-im/status-desktop/pull/14197
Fixes https://github.com/status-im/status-desktop/issues/14080
=> fix(@desktop/wallet): properly handle collectible groups in send modal

src/app/modules/main/communities/module.nim, src/app/modules/main/communities/view.nim
Close #14313
Add two signals about failed permissions check
Communities
=> Feat: add check permissions failed signals

ui/imports/shared/controls/StatusSyncCodeInput.qml
Add object names for buttons in `StatusSyncCodeInput.qml`
`StatusSyncCodeInput.qml`
=> chore@StatusSyncCodeInput.qml: add object names for buttons

ui/imports/shared/controls/StatusSyncCodeInput.qml
Add new object names, commit b8fec4636e2bc8a20ec68068b853c5ab360d1468
We need it for one of autotests
=> chore@StatusSyncCodeInput: add object names for buttons

src/app/modules/main/wallet_section/send/gas_fees_item.nim, src/app/modules/main/wallet_section/send/module.nim, src/app_service/service/transaction/async_tasks.nim, src/app_service/service/transaction/dto.nim, ui/imports/shared/popups/send/controls/GasSelector.qml, ui/imports/shared/popups/send/views/FeesView.qml, ui/imports/shared/popups/send/views/NetworkSelector.qml
cherry-pick https://github.com/status-im/status-desktop/pull/14149
[status-go #5075](https://github.com/status-im/status-go/pull/5075)
=> fix(wallet): displaying L1 gas cost in UI  - 2.8.1 - cherry-pick

src/app_service/service/community_tokens/service.nim
Get owners only for privileged users.
Fix initial call - both communities and tokens should be loaded.
Issue #14282
=> fix(@desktop/communitytokens): Fix too many getOwner calls.

src/app/modules/main/wallet_section/activity/details_controller.nim, ui/imports/shared/controls/TransactionDelegate.qml
* Fix details fetching
* Hide retry button. Retry logic is not implemented
Wallet activity details
=> fix(wallet): Fetch details

ui/app/AppLayouts/Communities/CommunitiesPortalLayout.qml
[noCreate.webm](https://github.com/status-im/status-desktop/assets/11926403/c4fa50e2-f74d-4a7b-86bf-b049299f12fc)
=> chore(CommunitiesPortal): change CreateCommunity to Import from Discord

ui/app/AppLayouts/Communities/panels/TagsPanel.qml, ui/app/AppLayouts/Profile/views/AdvancedView.qml
What does the PR do
Add object names for enable create community button and confirm community tags button
Affected areas
ui/app/AppLayouts/Communities/panels/TagsPanel.qml
ui/app/AppLayouts/Profile/views/AdvancedView.qml
=> Add object names for confirm tags button and enable create community button to release branch

ui/app/AppLayouts/Communities/panels/TagsPanel.qml, ui/app/AppLayouts/Profile/views/AdvancedView.qml
Add object names for enable create community button and confirm community tags button
ui/app/AppLayouts/Communities/panels/TagsPanel.qml
ui/app/AppLayouts/Profile/views/AdvancedView.qml
=> Add object names for confirm tags button and enable create community button to master

src/app_service/common/network_constants.nim
Closes #14501
For Opt Sepolia and Arb Sepolia, add Grove as main provider and move Infura to fallback provider
=> feat(wallet): add grove support for opt sepolia and arb sepolia

src/app_service/service/transaction/dto.nim
=> fix(wallet): Fix fees missing on community owner token minting

ui/imports/shared/views/profile/ProfileShowcaseCommunitiesView.qml
Cherry pick for https://github.com/status-im/status-desktop/pull/14600
=> fix: Hovering community in the profile showcase leads to crash

ui/imports/shared/panels/private/DidYouKnowMessages.qml
=> chore(status-go): up status-go for the fix to hidden channels being unread

src/app/modules/main/profile_section/profile/controller.nim, src/app_service/service/profile/service.nim, src/backend/accounts.nim
fixes #[12617](https://github.com/status-im/status-desktop/issues/12617)
When the user updates their bio, call `publishContactCode`
https://github.com/status-im/status-desktop/assets/1083341/537e03cc-556e-4bf6-915a-45bfb83e0b66
=> Fix(ProfileShowcase): send contact update when bio changes (#12617)

src/app_service/service/message/dto/link_preview.nim
fixes: #14731
https://github.com/status-im/status-desktop/assets/33099791/d363e969-a9e2-4f5d-973e-57786308a99c
=> fix: `LinkPreview` to json conversion

storybook/pages/StatusDialogPage.qml, ui/StatusQ/src/StatusQ/Controls/StatusBackButton.qml, ui/StatusQ/src/StatusQ/Popups/Dialog/StatusDialogFooter.qml, ui/StatusQ/src/StatusQ/Popups/Dialog/StatusDialogHeader.qml, ui/StatusQ/src/StatusQ/Popups/Dialog/StatusTitleSubtitle.qml
- fix rounded corners in header/footer background
- add support for footer drop shadow
- add a page/demo with the various features to StoryBook
Fixes #14499
StatusDialog
=> chore(StatusDialog): Support custom elements in the footer

ui/app/AppLayouts/Onboarding/views/KeysMainView.qml
Add object name for i dont have other device button
ui/app/AppLayouts/Onboarding/views/KeysMainView.qml
=> chore: add object name for i dont have other device button

src/app/modules/main/chat_section/module.nim, src/app_service/service/chat/dto/chat.nim, src/app_service/service/chat/service.nim, src/app_service/service/community/dto/community.nim, src/app_service/service/community/service.nim, ui/StatusQ/src/StatusQ/Components/StatusChatList.qml
Cherry-pick of https://github.com/status-im/status-desktop/pull/14895
Fixes https://github.com/status-im/status-desktop/issues/14886
=> [CHERRY PICK] category fixes 

ui/app/AppLayouts/Onboarding/views/KeysMainView.qml
cherry pick https://github.com/status-im/status-desktop/pull/14921/commits
UI e2e tests
=> [CHERRY-PICK]: object name for seed phrase test

src/app/global/local_app_settings.nim, src/app/modules/main/communities/tokens/controller.nim, src/app/modules/main/communities/tokens/io_interface.nim, src/app/modules/main/communities/tokens/module.nim, src/app/modules/main/communities/tokens/view.nim, src/app_service/service/community_tokens/service.nim, src/backend/community_tokens.nim, ui/app/AppLayouts/Communities/panels/MintTokensSettingsPanel.qml, ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml, ui/app/AppLayouts/Profile/stores/AdvancedStore.qml, ui/app/AppLayouts/Profile/views/AdvancedView.qml, ui/imports/shared/stores/CommunityTokensStore.qml
Cherry-picked https://github.com/status-im/status-desktop/pull/14884
=> [CHERRY-PICK] 14699 stucked miniting recovery release

ui/app/AppLayouts/Chat/ChatLayout.qml
Add object name for ChatView component so my tests can find this object easily
`ui/app/AppLayouts/Chat/ChatLayout.qml`
=> chore: add object name for ChatView component

monitoring/ModelInspectionPane.qml, monitoring/MonitorEntryPoint.qml, ui/include/StatusDesktop/Monitoring/Monitor.h, ui/src/StatusDesktop/Monitoring/Monitor.cpp
This utility may be helpful for debugging complex data flows in the application.
Once a model has `objectName` assigned, it can be inspected in runtime via `Monitoring Tool`. Object name and root object should be provided.
For models not created in singletons good root object is `applicationWindow`.
For models created in singletons, singleton handler must be provided, as explained in the tool's UI.
Closes: #14971
`MonitoringTool`
[Screencast from 29.05.2024 12:01:50.webm](https://github.com/status-im/status-desktop/assets/20650004/0e1e3a16-5146-4db9-ae9e-8f664fce1e12)
=> feat(MonitoringTool): Inspect of arbitrary model found by objectName

ui/app/AppLayouts/Wallet/popups/swap/SwapModalAdaptor.qml
fixes #14926
Uses the SubModelProxyModel after fix from @micieslak https://github.com/status-im/status-desktop/pull/14900#pullrequestreview-2080552879
SwapModal
=> feat(@desktop/wallet): Use SubModelProxyModel in SwapAdaptor.qml

ui/StatusQ/src/StatusQ/Components/private/statusMessage/StatusMessageEmojiReactions.qml
Added object name for emoji reaction
ui/StatusQ/src/StatusQ/Components/private/statusMessage/StatusMessageEmojiReactions.qml
=> Add object name for emoji reaction

src/app/modules/main/chat_section/chat_content/chat_details.nim, src/app/modules/main/chat_section/chat_content/controller.nim, src/app/modules/main/chat_section/chat_content/io_interface.nim, src/app/modules/main/chat_section/chat_content/module.nim, src/app/modules/main/chat_section/chat_content/view.nim, src/app/modules/main/chat_section/item.nim, src/app/modules/main/chat_section/module.nim, src/app_service/service/chat/dto/chat.nim, src/app_service/service/chat/service.nim, src/app_service/service/community/service.nim, ui/imports/shared/views/chat/MessageView.qml
Cherry-pick of https://github.com/status-im/status-desktop/pull/14933
Fixes #14089
=> [CHERRY-PICK] Fix missing reaction and edit buttons on permissioned channels  (#14933)

ui/app/AppLayouts/Profile/panels/ProfileDescriptionPanel.qml
=> [CHERRY-PICK] fix: Error message is misleading when pasting bio longer than 240 chars

ui/imports/shared/views/ProfileDialogView.qml
cherry picking https://github.com/status-im/status-desktop/pull/15001
=> [CHERRY-PICK] fix(ProfileDialogView): Share your own profile button is missing

src/app/modules/main/chat_section/module.nim, src/app_service/service/community/dto/community.nim, src/app_service/service/community/service.nim, ui/app/AppLayouts/Communities/views/CommunityColumnView.qml
Cherry pick of https://github.com/status-im/status-desktop/pull/14977/ to release 2.29
=> fix(communities): Correct handling 'hide channel from certain members (cherry pick)

ui/imports/shared/views/ProfileDialogView.qml
Add object name for share profile button
=> chore: object name for share profile button

test/e2e/configs/_local.default.py
- update slightly the template config file for tests
- test that new flows work
End-to-end tests
=> chore: update default local config

test/e2e/configs/_local.default.py
I made a typo yesterday removing wrong variable
End to end tests
=> chore: use correct variable in default config template

storybook/pages/SwapModalPage.qml, storybook/qmlTests/tests/tst_SwapModal.qml, storybook/src/Models/GroupedAccountsAssetsModel.qml, ui/app/AppLayouts/Wallet/WalletLayout.qml, ui/app/AppLayouts/Wallet/controls/NetworkFilter.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapModal.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapModalAdaptor.qml, ui/imports/shared/popups/send/SendModal.qml, ui/imports/shared/popups/send/controls/HeaderTitleText.qml, ui/imports/shared/popups/send/controls/qmldir
fixes #14750
Uses the existing Network filter in its current state in the Swap Modal.
Added Unit tests for the interactions with the network selector in context to the SwapModal
Unit testing the new Network filter should be done under https://github.com/status-im/status-desktop/issues/14780
SwapModal
Design does match for network filter as of now, will be done under https://github.com/status-im/status-desktop/issues/14780
https://github.com/status-im/status-desktop/assets/60327365/c6f82acf-e5b1-4d55-a5a3-07965da33c83
=> feat(@desktop/wallet): Implement Network selection in SwapModal

ui/imports/shared/popups/send/SendModal.qml
Cherry-pick for: https://github.com/status-im/status-desktop/pull/15056 - unblocking send modal flow for collectibles
=> CHERRY-PICK: fix(SendModal): Unblock sending collectibles flow

src/app/modules/main/app_search/module.nim, src/app_service/service/chat/dto/chat.nim
Fixes #14961
[hidden-channels-search.webm](https://github.com/status-im/status-desktop/assets/11926403/5d037219-2a4e-4afe-b42d-0b108c95129e)
=> fix(search): fix searching for hidden chats

ui/app/AppLayouts/Wallet/views/RightTabView.qml
reset the back button on stack reset
fixing: #14320 
https://github.com/status-im/status-desktop/assets/16547115/aab27247-bcfa-4a0c-a8d8-fdc761dfb84f
=> fix(wallet): fixing back button shows unnecessarily

ci/Jenkinsfile.macos, test/e2e/constants/wallet.py
Renamed keypair to key pair 
https://github.com/status-im/status-desktop/pull/15051 - tests for this PR are failing, so we need to rename it already
=> Fixes for tests due to renaming in the app

ci/Jenkinsfile.linux
This way fixes to tests can be applied in the same PR.
=> feat(ci): use same commit as PR for e2e tests

test/e2e/constants/wallet.py, ui/app/AppLayouts/Communities/panels/SharedAddressesSigningPanel.qml, ui/app/AppLayouts/Onboarding/views/ProfileFetchingView.qml, ui/app/AppLayouts/Onboarding/views/SeedPhraseInputView.qml, ui/app/AppLayouts/Profile/popups/RemoveKeypairPopup.qml, ui/app/AppLayouts/Profile/popups/RenameKeypairPopup.qml, ui/app/AppLayouts/Profile/popups/WalletKeypairAccountMenu.qml, ui/app/AppLayouts/Profile/views/keycard/DetailsView.qml, ui/app/AppLayouts/Profile/views/wallet/AccountView.qml, ui/app/AppLayouts/Profile/views/wallet/MainView.qml, ui/app/mainui/AppMain.qml, ui/app/mainui/activitycenter/views/ActivityNotificationNewKeypairFromPairedDevice.qml, ui/imports/shared/controls/GetSyncCodeDesktopInstructions.qml, ui/imports/shared/controls/GetSyncCodeMobileInstructions.qml, ui/imports/shared/controls/ImportKeypairInfo.qml, ui/imports/shared/panels/private/DidYouKnowMessages.qml, ui/imports/shared/popups/addaccount/states/EnterKeypairName.qml, ui/imports/shared/popups/common/EnterPrivateKey.qml, ui/imports/shared/popups/common/EnterSeedPhrase.qml, ui/imports/shared/popups/keycard/KeycardPopup.qml, ui/imports/shared/popups/keycard/states/EnterSeedPhrase.qml, ui/imports/shared/popups/keycard/states/KeycardInit.qml, ui/imports/shared/popups/keypairimport/KeypairImportPopup.qml, ui/imports/shared/popups/keypairimport/states/ExportKeypair.qml, ui/imports/shared/popups/keypairimport/states/ScanOrEnterQrCode.qml, ui/imports/shared/popups/keypairimport/states/SelectKeypair.qml, ui/imports/utils/Constants.qml, ui/imports/utils/Utils.qml
replaced the keypair occurances with key pair in the entire qml ui files
closes: #13612 
=> fix(wallet): Renamed KeyPair to key pair throughout the entire app

src/app/modules/main/chat_section/module.nim
Fix permissions lock icon visibility on channel permissions, fixes #14746
As far as I could see, the `addOrUpdateChat` was the only function doing the `updateChatRequiredPermissions`, however, it makes sense to have the `onCommunityTokenPermissionDeleted` and the `onCommunityTokenPermissionCreated` to have a way to trigger the update of permissions since they control directly the `requiresPermissions` which is used to update the `chatsModel`. The only problem I could see is how we have to linearly go through the list of chats to perform the update, but this list is restricted by the permission and we need to do the update of those chats one way or another. 
- Channel lock display
[Screencast from 2024-06-04 21-54-33.webm](https://github.com/status-im/status-desktop/assets/2589171/884e4073- …
=> fix(@desktop/permission): fix permissions lock icon visibility

src/app/modules/startup/internal/user_profile_confirm_password_state.nim, src/app/modules/startup/internal/user_profile_create_state.nim
- no emojihash and identicon ring displayed in for keycard onboarding flow
- can't restore account (windows and linux), issue #15101
- can't create new account with keycard (linux, windows), issue #15055
- illegal storage access issue when hitting Start using status button (which actually was a crash after pressing the button), issue #15035
=> fix: onboarding keycard issues fixed

src/app_service/service/message/service.nim
fixes #15002 
Unify response error parsing for task responses in message/service using `{}` and get-family `getStr`.
> By using the {} operator instead of [], it will return nil when the field is not found. The get-family of procedures will return a type's default value when called on nil.
works for all our needs
```
proc getErrorString(jsonObject: JsonNode): string =
return jsonObject{"error"}.getStr
suite "getErrorString tests":
test "error field with non-empty string":
let jsonObj = %*{
"error": "error message"
}
check getErrorString(jsonObj) == "error message"
test "error field with empty string":
let jsonObj = %*{
"error": ""
}
check getErrorString(jsonObj) == ""
test "error field with null":
let jsonObj = %*{}
jsonObj.add("error", nil)
check getErrorString(jsonObj) == ""
test "no …
```
=> fix(message/service): unify error parsing

src/app/modules/main/wallet_section/all_collectibles/controller.nim
=> fix(wallet): display collectibles even if account is not in total

test/e2e/constants/wallet.py, test/e2e/gui/components/emoji_popup.py, test/e2e/gui/components/settings/rename_keypair_popup.py, test/e2e/gui/components/wallet/wallet_account_popups.py, test/e2e/gui/objects_map/names.py, test/e2e/tests/settings/settings_wallet/test_wallet_rename_keypair.py, test/e2e/tests/settings/settings_wallet/test_wallet_settings_add_account.py, test/e2e/tests/wallet_main_screen/wallet - plus button/test_plus_button_manage_account_added_for_new_generated_seed.py, test/e2e/tests/wallet_main_screen/wallet - plus button/test_plus_button_manage_account_from_private_key.py, test/e2e/tests/wallet_main_screen/wallet - plus button/test_plus_button_manage_account_from_seed_phrase.py
- Added test for verifying min length of 5 characters for account name and key pair name
- Added some fixes for stability of wallet tests
CI run:
https://ci.status.im/job/status-desktop/job/e2e/job/manual/2049/
=> 5 chars min account keypair name

src/app_service/service/community_tokens/async_tasks.nim
=> fix(communities): fetching owners of erc20

src/app/boot/app_controller.nim, src/app/modules/main/wallet_section/module.nim, src/app/modules/shared_modules/wallet_connect/controller.nim, src/app_service/service/wallet_connect/service.nim, storybook/pages/DAppsWorkflowPage.qml, storybook/qmlTests/tests/tst_DAppsWorkflow.qml, ui/app/AppLayouts/Wallet/panels/DAppsWorkflow.qml, ui/app/AppLayouts/Wallet/services/dapps/DAppsRequestHandler.qml, ui/app/AppLayouts/Wallet/services/dapps/WalletConnectSDK.qml, ui/app/AppLayouts/Wallet/services/dapps/WalletConnectSDKBase.qml, ui/app/AppLayouts/Wallet/services/dapps/WalletConnectService.qml, ui/app/AppLayouts/Wallet/services/dapps/types/SessionRequestsModel.qml, ui/app/mainui/AppMain.qml, ui/imports/shared/popups/walletconnect/DAppRequestModal.qml, ui/imports/shared/stores/DAppsStore.qml
Trigger authentication with identity of the request
Track the authentication using the identity and allow only once
Add tests for the new functionality
Minor improvements around the code
=> feat(dapps) authenticated user for session request

ui/app/AppLayouts/Communities/controls/ExtendedDropdownContent.qml
Fix missing assets on permissions lists.
Fix #14905
https://github.com/status-im/status-desktop/assets/61889657/4c4dd7b5-d595-428c-8e33-61500baa40a0
=> fix(@desktop/permissions): Fix missing assets on permissions lists

ui/app/AppLayouts/Chat/views/ChatColumnView.qml, ui/app/AppLayouts/Chat/views/ChatView.qml
Fixes #15143
This is basically a revert of https://github.com/status-im/status-desktop/pull/13831 as it's no longer needed
[revert.webm](https://github.com/status-im/status-desktop/assets/11926403/0f45a94b-a14b-4e5f-8fd1-65098f37a592)
=> chore(chat): no need to block the input when a permission is pending

ui/imports/shared/views/chat/MessageContextMenuView.qml
Status-go PR: https://github.com/status-im/status-go/pull/5330
=> feat(messages): enable removing bridge messages as admin

ui/app/AppLayouts/Wallet/popups/swap/SwapModalAdaptor.qml
Solve crash when launching swap Modal
SwapModal
=> fix(@desktop/wallet): Swap: Fix crash on launching SwapModal

test/e2e/gui/components/community/create_community_popups.py, test/e2e/gui/screens/community_settings.py, test/e2e/gui/screens/messages.py, test/e2e/gui/screens/onboarding.py
Remove hardcoded uri path to use it properly so windows is not complaining
UI tests
=> chore: do not hardcode file uri so it becomes OS agnostic

test/e2e/tests/messages/test_messaging_1x1_chat.py
- Added verification that message status changed to edited
- Reworked verification of text in messages - now it's easier to read test and also it decrease a bit duration of test
- Some other small changes
I ran test several times, all good (some runs fail but it's not related)
https://ci.status.im/job/status-desktop/job/e2e/job/manual/2098/
https://ci.status.im/job/status-desktop/job/e2e/job/manual/2099/
=> Reworked 1-1 chat test

src/app/modules/main/chat_section/chat_content/input_area/controller.nim
Closes https://github.com/status-im/status-desktop/issues/12930
Chat
https://github.com/status-im/status-desktop/assets/25482501/f8b2c8e7-ca83-4c0b-9ee9-4e2992db6ad3
=> feat: limit message link previews count

src/app_service/service/contacts/service.nim
Fixes https://github.com/status-im/status-desktop/issues/14863
contacts
https://github.com/status-im/status-desktop/assets/25482501/3a9a3a98-b453-4f31-a4f4-388170e97ec7
=> fix: removeTrustStatus response processing

test/e2e/configs/__init__.py, test/e2e/configs/system.py, test/e2e/conftest.py, test/e2e/constants/commands.py, test/e2e/driver/aut.py, test/e2e/fixtures/aut.py, test/e2e/gui/main_window.py, test/e2e/gui/screens/onboarding.py, test/e2e/scripts/tools/image.py, test/e2e/scripts/utils/local_system.py, test/e2e/tests/communities/test_communities_mint_owner_token.py, test/e2e/tests/onboarding/test_onboarding_generate_new_keys.py, test/e2e/tests/onboarding/test_onboarding_import_seed.py, test/e2e/tests/onboarding/test_onboarding_negative_scenarios.py, test/e2e/tests/onboarding/test_onboarding_syncing.py, test/e2e/tests/settings/test_ens_name_purchase.py, test/e2e/tests/wallet_main_screen/wallet - footer actions/test_footer_actions_send.py, test/e2e/tests/wallet_main_screen/wallet - footer actions/test_footer_actions_send_nft.py
Kill process on Windows 
UI tests
=> chore: terminate app process on windows

src/app_service/service/accounts/dto/login_request.nim, src/app_service/service/accounts/service.nim
Requries https://github.com/status-im/status-go/pull/5369
Fixes https://github.com/status-im/status-desktop/issues/15155
Get back the bandwidth usage
login, node management
=> fix: bandwidth usage

test/e2e/tests/communities/test_communities_permissions.py
Marked permissions tests as skipped because of bug https://github.com/status-im/status-desktop/issues/15246
=> Disable permissions tests because of bug

src/app/modules/main/wallet_section/send/controller.nim, src/app/modules/main/wallet_section/send/io_interface.nim, src/app/modules/main/wallet_section/send/module.nim, src/app/modules/main/wallet_section/send/view.nim, src/app_service/service/eth/dto/transaction.nim, src/app_service/service/transaction/service.nim, ui/app/AppLayouts/Wallet/popups/swap/SwapModalAdaptor.qml, ui/app/AppLayouts/Wallet/stores/SwapStore.qml
Closes #15096
status-go: https://github.com/status-im/status-go/pull/5363
Integrate the Max Slippage parameter present in the UI with the backend.
Manually tested by adding printlns in the backend, since this value is not present on-chain after the tx is done
=> feat(wallet): integrate swap slippage percentage parameter

storybook/pages/ErrorTagPage.qml, storybook/pages/SwapInputPanelPage.qml, storybook/qmlTests/tests/tst_ErrorTag.qml, storybook/qmlTests/tests/tst_SwapInputPanel.qml, storybook/qmlTests/tests/tst_SwapModal.qml, ui/app/AppLayouts/Wallet/panels/SwapInputPanel.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapModal.qml, ui/imports/shared/controls/ErrorTag.qml, ui/imports/shared/popups/send/views/AmountToSend.qml
fixes  #15162
Solves all the bugs mentioned under https://github.com/status-im/status-desktop/issues/15162
SwapInputPanel.qml, SwapModal.qml
https://github.com/status-im/status-desktop/assets/60327365/12a06ab0-87f4-4c44-b07e-71c6279c167e
https://github.com/status-im/status-desktop/assets/60327365/2e4e87c0-a154-4818-b36a-6fe4924f1bcd
=> fix(@desktop/wallet): solving the issues with SwapInputPanel list in the issue

test/e2e/gui/objects_map/names.py, test/e2e/gui/screens/community.py, test/e2e/tests/communities/test_communities.py, test/e2e/tests/communities/test_communities_add_a_contact_from_member_list.py, test/e2e/tests/communities/test_communities_pin_and_unpin_messages.py, test/e2e/tests/online_identifier/test_online_identifier.py
Reworked inviting to community steps
Closes https://github.com/status-im/status-desktop/issues/15222
CI runs:
https://ci.status.im/job/status-desktop/job/e2e/job/manual/2104/
https://ci.status.im/job/status-desktop/job/e2e/job/manual/2105/
=> Replaced inviting people to community by clicking add members button

src/app/modules/main/chat_section/chat_content/input_area/controller.nim, src/app/modules/main/chat_section/chat_content/input_area/io_interface.nim, src/app/modules/main/chat_section/chat_content/input_area/module.nim, src/app/modules/main/chat_section/chat_content/input_area/view.nim, src/app/modules/main/chat_section/chat_content/messages/controller.nim, src/app/modules/main/chat_section/chat_content/messages/io_interface.nim, src/app/modules/main/chat_section/chat_content/messages/module.nim, src/app/modules/main/chat_section/chat_content/messages/view.nim, src/app/modules/main/stickers/controller.nim, src/app_service/service/chat/async_tasks.nim, src/app_service/service/chat/service.nim, src/app_service/service/stickers/async_tasks.nim, src/app_service/service/stickers/service.nim, src/backend/chat.nim, ui/app/AppLayouts/Chat/views/ChatColumnView.qml, ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
Fixes #12411
Makes message sending async and adds a placeholder "Sending.." message
[async-send.webm](https://github.com/status-im/status-desktop/assets/11926403/782865d3-7b56-4060-b943-7430ca7e261b)
=> refactor(messages): make message sending async

ui/imports/utils/Utils.qml
Removing network calls on main thread.
This is a potential fix for https://github.com/status-im/status-desktop/issues/15273
The URL validator needs to be refactored to use an async connection.
=> perf: Remove network calls to validate the URLs on main thread

ui/app/AppLayouts/Wallet/stores/RootStore.qml
=> chore(Wallet.RootStore): Fixed qml runtime error.

test/e2e/constants/community_settings.py, test/e2e/gui/objects_map/communities_names.py, test/e2e/gui/screens/community_settings.py, test/e2e/tests/communities/test_communities_permissions.py, ui/app/AppLayouts/Communities/views/EditPermissionView.qml
Added steps to verify duplication of permission
CI run:
https://ci.status.im/job/status-desktop/job/e2e/job/manual/2170/
=> Duplicate permission step added to permission test

src/app_service/service/chat/async_tasks.nim, src/app_service/service/chat/service.nim, src/backend/chat.nim
=> fix(links): fix sending links plus images

test/e2e/tests/wallet_main_screen/wallet - assets tab/test_wallet_assets_sorting.py
I replaced address in assets sorting tests to the one which don't have Produced blocks (as was advised)
CI run:
https://ci.status.im/job/status-desktop/job/e2e/job/manual/2199/
=> Use different watched address

test/e2e/tests/online_identifier/test_online_identifier.py
I also replaced for 2 more tests, but will open PR for this after bug with contact requests and messages is fixed
For now I open only for online identifier test
CI run:
https://ci.status.im/job/status-desktop/job/e2e/job/manual/2196/
=> Replaced steps with user data for online identifier test

ui/imports/shared/popups/send/views/RecipientView.qml
- validate input also when pasting via the button (extract to a common function)
- show the Paste button only when the input is empty and we have sth to paste actually and prevent it from stealing focus
- upon clicking the Paste button, put focus on the input field
- after pasting, set the cursor past the end of the text
Fixes #14576
SendModal -> RecipientView -> address input
[Záznam obrazovky z 2024-06-27 12-50-37.webm](https://github.com/status-im/status-desktop/assets/5377645/a632bc20-2336-4498-9a58-b0b74c840066)
=> [SendModal] fix pasting an address

storybook/qmlTests/tests/tst_SwapInputPanel.qml, storybook/qmlTests/tests/tst_SwapModal.qml, storybook/src/Models/WalletAccountsModel.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapModalAdaptor.qml
fixes #15272
Fixes flaky tests
tst_SwapModal.qml
=> fix(@desktop/wallet): [SwapModal] Fix for flaky tests and remove the skip flag

src/app/core/signals/remote_signals/wallet.nim, src/app/modules/main/wallet_section/send/module.nim, src/app_service/service/eth/dto/transaction.nim, src/app_service/service/transaction/async_tasks.nim, src/app_service/service/transaction/dto.nim, src/app_service/service/transaction/dtoV2.nim, src/app_service/service/transaction/dto_conversion.nim, src/app_service/service/transaction/service.nim
Closes [#15095](https://github.com/status-im/status-desktop/issues/15095)
status-go part: https://github.com/status-im/status-go/pull/5447
Getting suggested routes was broken for Swap in https://github.com/status-im/status-desktop/pull/15344.
Moreover, sending Swap transactions was broken due to changes in https://github.com/status-im/status-go/pull/5362.
We fix both issues in this PR.
- Added back rawPaths parameter in SuggestedRoutesDto, adapted to the V2 changes
- Added From/To tokens to TransactionData for Swap.
=> fix(@desktop/wallet): fix swap in routerV2 integration

src/app/modules/shared_modules/wallet_connect/controller.nim, src/app_service/service/wallet_connect/service.nim, storybook/pages/DAppRequestModalPage.qml, storybook/pages/DAppsWorkflowPage.qml, ui/app/AppLayouts/Wallet/panels/DAppsWorkflow.qml, ui/app/AppLayouts/Wallet/services/dapps/DAppsRequestHandler.qml, ui/app/AppLayouts/Wallet/services/dapps/types/SessionRequest.qml, ui/app/AppLayouts/Wallet/services/dapps/types/SessionRequestResolved.qml, ui/imports/shared/popups/walletconnect/DAppRequestModal.qml, ui/imports/shared/stores/DAppsStore.qml
Also added Fees section
https://github.com/status-im/status-desktop/assets/47554641/abd8fedf-58b9-486e-b8ce-36ed17de3dc7
=> feat(dapps) implement send transaction support for wallet connect

.github/pull_request_template.md
Define a process for status-go PRs as more of those are expected to be
opened by the Waku team.
=> Add instructions for status-go PRs

ui/imports/shared/views/chat/MessageView.qml
=> fix(edit): fix message contentType when editing (emoji or message)

test/e2e/constants/links.py, test/e2e/gui/screens/messages.py, test/e2e/tests/messages/test_messaging_link_previews.py
Reworked link preview test, added more verifications (link unfurls + images in sent message)
CI run:
https://ci.status.im/job/status-desktop/job/e2e/job/manual/2223/
=> chore: fix link preview and add more verifications

ui/app/AppLayouts/Communities/panels/AirdropsSettingsPanel.qml, ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml
Fixes #15383
[airdrop-info.webm](https://github.com/status-im/status-desktop/assets/11926403/27d9cb37-8ee8-426e-a9a4-57357418d520)
=> fix(airdrop): fix lost info when closing password in airdrop flow

src/app/modules/main/chat_section/chat_content/chat_details.nim, src/app/modules/main/chat_section/chat_content/module.nim, src/app/modules/main/chat_section/item.nim, src/app/modules/main/chat_section/model.nim, src/app/modules/main/chat_section/module.nim, src/app_service/service/chat/dto/chat.nim, src/app_service/service/community/service.nim, ui/app/AppLayouts/Chat/views/ChatView.qml, ui/app/AppLayouts/Communities/panels/BlinkingText.qml, ui/app/AppLayouts/Communities/panels/JoinCommunityCenterPanel.qml, ui/app/AppLayouts/Communities/panels/JoinPermissionsOverlayPanel.qml, ui/app/AppLayouts/Communities/panels/qmldir
closes: https://github.com/status-im/status-desktop/issues/15064
status-go PR: https://github.com/status-im/status-go/pull/5438
https://github.com/status-im/status-desktop/assets/33099791/e1dc84b4-14b6-4a78-b34b-af501016411c
**NOTE**
I simulated missing encryption key by modifying control node client to send encryption keys with 30s delay.
=> Inform about missing encryption key

src/app_service/service/community_tokens/async_tasks.nim, src/app_service/service/community_tokens/service.nim
1. Upgrading status-go from [here](https://github.com/status-im/status-go/pull/5465/files)
2. Fix a bug that burn icon did not show after restart application (when the app was closed in the middle of transaction).
Issue https://github.com/status-im/status-go/issues/4947
=> 4947 upgrade community contracts

storybook/pages/SwapModalPage.qml, storybook/qmlTests/tests/tst_SwapInputPanel.qml, storybook/qmlTests/tests/tst_SwapModal.qml, storybook/qmlTests/tests/tst_TokenSelector.qml, storybook/qmlTests/tests/tst_TokenSelectorView.qml, storybook/qmlTests/tests/tst_TokenSelectorViewAdaptor.qml, storybook/src/Models/GroupedAccountsAssetsModel.qml, storybook/src/Models/TokensBySymbolModel.qml, ui/app/AppLayouts/Wallet/adaptors/TokenSelectorViewAdaptor.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapInputParamsForm.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapModal.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapSignApproveInputForm.qml
fixes #15274
Implements -> https://www.figma.com/design/TS0eQX9dAZXqZtELiwKIoK/Swap---Milestone-1?node-id=3410-271335&m=dev
https://www.notion.so/Setup-Swap-59212ae7e94248b7aa26cafdd133e858?pvs=4#a22e797b879a4274ac7b45df9f0e7181
SwapModal.qml
https://github.com/status-im/status-desktop/assets/60327365/cec410e5-c07f-4897-8f44-362aa81aa15e
Behaviour on switching networks on sap modal after values are filled in
Described potential risks and worst case …
=> feat(@desktop/wallet): Implements Network selection behaviour

storybook/pages/SwapApproveCapModalPage.qml, storybook/qmlTests/tests/tst_SwapApproveCapModal.qml, ui/StatusQ/src/StatusQ/Core/LocaleUtils.qml, ui/app/AppLayouts/Wallet/panels/ContractInfoButtonWithMenu.qml, ui/app/AppLayouts/Wallet/panels/SignInfoBox.qml, ui/app/AppLayouts/Wallet/popups/SignTransactionModalBase.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapApproveCapModal.qml, ui/app/AppLayouts/Wallet/popups/swap/qmldir, ui/imports/shared/controls/InformationTag.qml
- create a new UI component
- add it to StoryBook
- add QML tests
- integration will be done as part of https://github.com/status-im/status-desktop/issues/15443
Fixes #15442
SwapApproveCapModal
=> feat:[UI - Swap] Create swap approve dialog

storybook/qmlTests/tests/tst_SwapModal.qml, ui/StatusQ/src/StatusQ/Core/Utils/AmountsArithmetic.qml, ui/app/AppLayouts/Wallet/panels/SwapInputPanel.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapInputParamsForm.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapModal.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapModalAdaptor.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapOutputData.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapSignApprovePopup.qml
fixes #14952
Implements https://www.figma.com/design/TS0eQX9dAZXqZtELiwKIoK/Swap---Milestone-1?node-id=4151-71714&m=dev
Know limitation https://github.com/status-im/status-desktop/issues/15454
SwapModal.qml
Error:
https://github.com/status-im/status-desktop/assets/60327365/621bb529-78ad-4cc3-83de-acdc2188b826
Swap:
https://github.com/status-im/status-desktop/assets/60327365/6816b0d9-828c-4edc-a279-dde8428a8d9b
Approve:
https://github.com/status-im/status-desktop/assets/60327365/aa316191-fea2-470b-9319-b39fe1429b10
- How should one proceed …
=> feat(@desktop/wallet): Implements auto refresh

storybook/pages/DAppsWorkflowPage.qml, ui/app/AppLayouts/Wallet/panels/DAppsWorkflow.qml, ui/app/AppLayouts/Wallet/services/dapps/WalletConnectService.qml, ui/app/AppLayouts/Wallet/services/dapps/helpers.js, ui/app/AppLayouts/Wallet/services/dapps/types/Pairing.qml, ui/app/AppLayouts/Wallet/services/dapps/types/SessionRequest.qml, ui/app/AppLayouts/Wallet/services/dapps/types/qmldir, ui/imports/shared/popups/walletconnect/PairWCModal.qml, ui/imports/shared/popups/walletconnect/PairWCModal/WCUriInput.qml
https://github.com/status-im/status-desktop/assets/47554641/0e6ac19e-b292-454c-b3c1-d6696fd259d2
=> feat(dapps) check Wallet Connect pair uri for already used and expired

test/e2e/tests/wallet_main_screen/wallet - right click out of account area/test_right_click_manage_watched_address.py
Added step to remove and verify it was removed for watched account
CI run:
https://ci.status.im/job/status-desktop/job/e2e/job/manual/2287/
=> chore: added removing of watched account

test/e2e/gui/components/profile_popup.py, test/e2e/gui/components/share_profile_popup.py, test/e2e/gui/objects_map/names.py, test/e2e/tests/onboarding/test_onboarding_generate_new_keys.py, ui/imports/shared/views/profile/ShareProfileDialog.qml
Added verifications for share profile popup
CI run:
https://ci.status.im/job/status-desktop/job/e2e/job/manual/2295/
=> test: verifications for share profile popup added

fleets.json, src/app/core/fleets/fleet_configuration.nim, src/app_service/service/node_configuration/service.nim, src/app_service/service/settings/dto/settings.nim, src/app_service/service/settings/service.nim, ui/app/AppLayouts/Profile/popups/FleetsModal.qml, ui/imports/utils/Constants.qml
Requires: https://github.com/status-im/status-go/pull/5500
See https://github.com/status-im/infra-shards/issues/33 for requirement details
=> chore: rename shards.staging to status.staging

src/app/modules/main/communities/controller.nim
No idea if this affected anything. But the code just seem wrong, looks like an indentation typo.
community permissions smth?
=> fix: events subscription indentation

test/e2e/configs/system.py, test/e2e/gui/components/wallet/wallet_account_popups.py, test/e2e/gui/main_window.py, test/e2e/gui/objects_map/settings_names.py, test/e2e/gui/objects_map/wallet_names.py, test/e2e/gui/screens/settings.py, test/e2e/gui/screens/settings_wallet.py, test/e2e/gui/screens/wallet.py, test/e2e/tests/onboarding/test_onboarding_generate_new_keys.py, test/e2e/tests/settings/test_settings_back_up_seed.py, test/e2e/tests/wallet_main_screen/wallet - assets tab/test_wallet_assets_sorting.py
Polish some repetitive code
UI end-to-end tests
=> tests: some cosmetic code improvements

ui/app/AppLayouts/Wallet/panels/WalletHeader.qml
in case not interactive, we should not change the color on hover
=> fix(@wallet): disable state for refresh

src/app/boot/app_controller.nim, src/app_service/service/accounts/service.nim, src/app_service/service/metrics/dto.nim, src/app_service/service/metrics/service.nim, src/backend/accounts.nim, ui/app/AppLayouts/Onboarding/stores/StartupStore.qml, ui/app/AppLayouts/Onboarding/views/KeysMainView.qml
Integrating centralized metrics system in desktop application.
Add a check box on Onboarding screen which enables/disables metric system (will be replaced with a popup in the next task).
Credentials for metric system are passed via env variables for now.
=> feat(@desktop/metrics): Initialize centralized metrics

ci/Jenkinsfile.tests-e2e
Change the project ID for test rail mapping
Autotests
=> chore: change the test rail project id

test/e2e/gui/components/wallet/RPCChangeRestartPopup.py, test/e2e/gui/objects_map/names.py, test/e2e/gui/screens/settings_wallet.py, test/e2e/tests/settings/settings_wallet/test_wallet_settings_networks_edit_network.py, ui/app/AppLayouts/Profile/views/wallet/EditNetworkForm.qml
- Removed duplicated method (for some reason we had 2 same methods even with the same name)
- Fixed test according to changes for revert to default 
- Also removed comment from test, it works fine now
CI run:
https://ci.status.im/job/status-desktop/job/e2e/job/manual/2347/
=> Fixed revert to defaults test

test/e2e/tests/settings/settings_wallet/test_wallet_settings_add_account.py
Closes https://github.com/status-im/status-desktop/issues/15286
Tests
=> tests: enable back test for account creation in settings

test/e2e/gui/components/onboarding/share_usage_data_popup.py, test/e2e/gui/objects_map/names.py, test/e2e/gui/objects_map/settings_names.py, test/e2e/gui/screens/onboarding.py, test/e2e/gui/screens/settings.py, test/e2e/tests/settings/test_settings_back_up_seed.py
Fixes for tests according to new flow (metrics popup)
CI run:
https://ci.status.im/job/status-desktop/job/e2e/job/manual/2352/allure/ (fails - one fix is in master, another one - UI issue, not related to these changes)
=> Fixes according to new metrics popup

test/e2e/constants/colors.py, test/e2e/gui/main_window.py, test/e2e/tests/onboarding/test_onboarding_generate_new_keys.py
=> chore: add background color verification for avatar

storybook/qmlTests/tests/tst_DAppsWorkflow.qml, ui/app/AppLayouts/Wallet/panels/DAppsWorkflow.qml, ui/imports/shared/popups/walletconnect/ConnectDAppModal.qml
=> feat(dapps) reject request on closing of modal

test/e2e/tests/communities/test_communities_channels.py
Added test for viewing and posting in non-restricted channel
CI run:
https://ci.status.im/job/status-desktop/job/e2e/job/manual/2250
=> Owner and member can view and post in non-restricted channel test

ci/Jenkinsfile.combined
=> feat(ci): add Nix Linux build to nightly and release builds

src/app/global/local_account_sensitive_settings.nim, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Communities/panels/PermissionsSettingsPanel.qml, ui/app/AppLayouts/Communities/popups/CreateChannelPopup.qml, ui/app/AppLayouts/Communities/popups/HoldingsDropdown.qml, ui/app/AppLayouts/Communities/views/CommunityColumnView.qml, ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml, ui/app/AppLayouts/Communities/views/EditPermissionView.qml, ui/app/AppLayouts/Profile/stores/AdvancedStore.qml, ui/app/AppLayouts/Profile/views/AdvancedView.qml
Fixes #15663
[ens-hide.webm](https://github.com/user-attachments/assets/e7334c1b-29ca-4608-af02-d552870e6914)
=> chore(beta): hide ENS community permission creation

storybook/pages/DAppsWorkflowPage.qml, storybook/qmlTests/tests/helpers/wallet_connect.js, storybook/qmlTests/tests/tst_DAppsWorkflow.qml, ui/app/AppLayouts/Wallet/services/dapps/DAppsRequestHandler.qml, ui/app/AppLayouts/Wallet/services/dapps/WalletConnectService.qml
Also differentiate between l1 and l2 fees and check them against the specific chain balance
and
- Included tests for the new functionality
- Fixed some inconsistencies in handling types
=> feat(dapps) check max fees against balance for transactions

storybook/pages/SwapSignModalPage.qml, storybook/qmlTests/tests/tst_SwapSignModal.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapModal.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapSignModal.qml, ui/imports/utils/Constants.qml
Update the link to point to terms and condition of paraswap page.
SwapSignModal
https://github.com/user-attachments/assets/70ef9196-81bd-4d1f-b035-f2d30d216308
=> fix(@desktop/wallet): Update the link to point to terms and condition of paraswap page.

src/app/modules/main/module.nim, src/app/modules/main/view.nim, src/app/modules/main/wallet_section/send/controller.nim, src/app/modules/main/wallet_section/send/module.nim, src/app_service/service/transaction/async_tasks.nim, src/app_service/service/transaction/service.nim, ui/app/mainui/AppMain.qml
fixes #14834
Implements:
**User Story:** https://www.notion.so/Notifications-66e71ffbe08749498e43c02e97f5a207
**Design:** https://www.figma.com/design/TS0eQX9dAZXqZtELiwKIoK/Swap---Milestone-1?node-id=3542-496691&m=dev
https://www.figma.com/design/TS0eQX9dAZXqZtELiwKIoK/Swap---Milestone-1?node-id=3531-446153&m=dev
SwapModal , AppMain
**Approval Flow:**
https://github.com/status-im/status-desktop/assets/60327365/740ad2fb-6a60-4f2e-b854-88f757620bc6
**Swap Flow:**
https://github.com/status-im/status-desktop/assets/60327365/e6ec0544-36b0-4e23-9b72-d88f42487551
What is the impact of these changes on the end user …
=> feat(@desktop/wallet): Implementation of Notifications

src/app_service/service/wallet_connect/service.nim, storybook/qmlTests/tests/tst_DAppsWorkflow.qml, ui/StatusQ/src/StatusQ/Core/Utils/AmountsArithmetic.qml, ui/app/AppLayouts/Wallet/panels/DAppsWorkflow.qml, ui/app/AppLayouts/Wallet/services/dapps/DAppsRequestHandler.qml, ui/app/AppLayouts/Wallet/services/dapps/types/SessionRequestResolved.qml, ui/imports/shared/stores/DAppsStore.qml
Notify user if he doesn't hold enough funds to make the transaction
Also check fees funds including the amount to be sent
=> feat(dapps) make wallet connect request data human readable

test/e2e/tests/settings/settings_keycard/test_check_whats_on_keycard.py, test/e2e/tests/settings/settings_keycard/test_create_keycard_account_with_new_seed_phrase.py, test/e2e/tests/settings/settings_keycard/test_factory_reset_keycard.py, test/e2e/tests/settings/settings_keycard/test_import_restore_keycard_via_seed_phrase.py, test/e2e/tests/settings/settings_keycard/test_setup_existing_account.py, test/e2e/tests/settings/settings_keycard/test_unlock_keycard.py
Logged a ticket here https://github.com/status-im/status-desktop/issues/15741
=> Tests: temp disable keycard tests as keycard mock is broken

src/app/global/feature_flags.nim
Removes feature flag for Swap so that its enabled by default
Swap
=> feat(@desktop/wallet): Swap:: Remove feature flag

storybook/qmlTests/tests/tst_SwapModal.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapModal.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapModalAdaptor.qml
=> fix(@desktop/wallet): Enabled unit tests previously marked as flaky and skipped

src/app_service/service/eth/dto/transaction.nim, src/app_service/service/transaction/dto.nim, src/app_service/service/transaction/dto_conversion.nim, src/app_service/service/transaction/service.nim
- https://github.com/status-im/status-go/pull/5574
- includes changes done in this PR as well https://github.com/status-im/status-go/pull/5569
Fixes: #15722
=> fix: bridging from send modal results in bounder fee error

src/app/modules/main/wallet_section/send/view.nim, src/app_service/service/eth/dto/transaction.nim, src/app_service/service/transaction/dto.nim, src/app_service/service/transaction/dto_conversion.nim, src/app_service/service/transaction/service.nim, ui/imports/shared/popups/send/SendModal.qml, ui/imports/shared/status/StatusStickerMarket.qml, ui/imports/utils/Constants.qml
Closes: #15764
With these 2 transactions:
- https://sepolia.etherscan.io/tx/0x545369867cba897e90389d1430c05c967f6ad257019362b57b31d8233bb53267
- https://sepolia.etherscan.io/tx/0x395aa569444b4e9150e10a1724890d119ef3aff66040267c4d28909a10838cfd
I successfully bought two stickers from the app.
=> fix: buying stickers doesn't work and popup may be misleading for the user

test/e2e/gui/objects_map/settings_names.py, test/e2e/gui/screens/settings_wallet.py
Cherry-pick f2952836b3708ae85987e9fcd71c13f321abd97e (fix for tests)
=> [cherry-pick]: Chore network test fix

ui/StatusQ/src/StatusQ/Controls/StatusSwitchTabButton.qml, ui/imports/shared/popups/send/views/NetworkSelector.qml, ui/imports/shared/popups/send/views/NetworksSimpleRoutingView.qml
Closes #15833
https://github.com/user-attachments/assets/09a9f3ca-2365-404b-ba1b-b9bdc778cb38
=> chore: send modal adjustments

test/e2e/constants/links.py, test/e2e/tests/messages/test_messaging_link_previews.py
Fix for link preview test, old link doesn't work again
CI run:
https://ci.status.im/job/status-desktop/job/e2e/job/manual/2438/
=> Fix link preview

storybook/qmlTests/tests/tst_DAppsWorkflow.qml, ui/app/AppLayouts/Wallet/services/dapps/DAppsListProvider.qml, ui/app/AppLayouts/Wallet/services/dapps/DAppsRequestHandler.qml, ui/app/AppLayouts/Wallet/services/dapps/DappsConnectorSDK.qml, ui/app/AppLayouts/Wallet/services/dapps/WalletConnectService.qml, ui/app/AppLayouts/Wallet/services/dapps/qmldir
=> CHERRY-PICK: fix(dApps): Improved logic for disconnecting of dApps in the app.

storybook/qmlTests/tests/tst_ConnectDAppModal.qml, ui/imports/shared/popups/walletconnect/ConnectDAppModal.qml
CHERRY-PICK of PR https://github.com/status-im/status-desktop/pull/15847
- wrap the contents into a scroll view and don't hardcode the height
Fixes #15592
ConnectDAppModal
=> CHERRY-PICK: fix(ConnectDAppModal): add scrolling

ui/app/AppLayouts/Profile/popups/WakuNodesModal.qml, ui/app/AppLayouts/Profile/popups/WakuStoreModal.qml
cherry-pick of #15836
fixes https://github.com/status-im/status-desktop/issues/14929
=> [Cherry-Pick] temporary hide add waku node button

storybook/qmlTests/tests/tst_SwapModal.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapModal.qml
fixes #15784
master branch PR merged https://github.com/status-im/status-desktop/pull/15807
=> fix(@desktop/wallet): Swap "Approve" button becomes enabled before Approve Tx succeeds/fails

storybook/pages/DAppSignRequestModalPage.qml, ui/imports/shared/popups/walletconnect/DAppSignRequestModal.qml, ui/imports/shared/popups/walletconnect/panels/ContentPanel.qml
CHERRY-PICK of PR https://github.com/status-im/status-desktop/pull/15856
=> fix(DAppSignRequestModal): correctly compute text painted height

ui/StatusQ/src/StatusQ/Controls/StatusSwitchTabButton.qml, ui/app/AppLayouts/Wallet/WalletUtils.qml, ui/imports/shared/popups/send/SendModal.qml, ui/imports/shared/popups/send/views/NetworkSelector.qml, ui/imports/shared/popups/send/views/NetworksSimpleRoutingView.qml, ui/imports/utils/Constants.qml
Cherry-picked `status-go` changes:
- https://github.com/status-im/status-go/pull/5620
=> Cherry pick/needed router changes

fleets.json, src/app/core/fleets/fleet_configuration.nim, src/app_service/service/accounts/service.nim, src/app_service/service/node_configuration/service.nim, src/app_service/service/settings/dto/settings.nim, src/app_service/service/settings/service.nim, ui/app/AppLayouts/Profile/popups/FleetsModal.qml, ui/imports/utils/Constants.qml
Requires:
- https://github.com/status-im/status-go/pull/5571
=> chore: rename shards.test to status.prod

test/e2e/constants/community_settings.py, test/e2e/gui/components/community/ban_member_popup.py, test/e2e/gui/objects_map/communities_names.py, test/e2e/gui/objects_map/messaging_names.py, test/e2e/gui/objects_map/names.py, test/e2e/gui/screens/community.py, test/e2e/gui/screens/community_settings.py, test/e2e/gui/screens/messages.py, test/e2e/tests/communities/test_communities.py, ui/app/AppLayouts/Communities/panels/MembersSettingsPanel.qml, ui/app/AppLayouts/Communities/panels/MembersTabPanel.qml
Added steps to ban member to the existing test, finally it passes on CI!
CI run:
https://ci.status.im/job/status-desktop/job/e2e/job/manual/2442/
=> Ban community member test

ui/app/AppLayouts/Wallet/services/dapps/types/SessionRequest.qml
=> chore(dapps) disable eth_signTransaction for Wallet Connect

ui/StatusQ/src/StatusQ/Components/StatusDraggableListItem.qml, ui/app/AppLayouts/Profile/stores/ProfileStore.qml, ui/app/AppLayouts/Profile/views/MyProfileView.qml
Fixes #15904
Cherry-pick of https://github.com/status-im/status-desktop/pull/15905
=> [CHERRY-PICK] fix(profile): fix canceling modifications in the profile (#15905)

src/app_service/service/transaction/service.nim, ui/app/AppLayouts/Wallet/WalletUtils.qml, ui/imports/shared/popups/send/SendModal.qml, ui/imports/utils/Constants.qml
- https://github.com/status-im/status-go/pull/5636
Closes #15922
=> fix: tx fails if the bonder fee is higher than the amount being sent

ui/app/AppLayouts/Wallet/stores/WalletAssetsStore.qml, ui/imports/shared/popups/send/SendModal.qml
Cherry pick of https://github.com/status-im/status-desktop/pull/15908
=> [CHERRY-PICK] fix(wallet)_: Filter non-bridgeable assets in Bridge Modal

ui/app/AppLayouts/Wallet/controls/TokenSelectorNew.qml, ui/imports/shared/popups/send/SendModal.qml
Cherrypick of https://github.com/status-im/status-desktop/pull/15859 for release
=> [CHERRY-PICK] fix(wallet): Constrain token name size to send modal width (#15859)

ui/StatusQ/include/StatusQ/concatmodel.h, ui/StatusQ/src/concatmodel.cpp, ui/StatusQ/tests/tst_ConcatModel.cpp
Cherry pick of `d0962a3795129142052858a9986897707eac19fa` from `release/2.30.x`
Closes: #15891
=> [CHERRY-PICK]: StatusQ/ConcatModel: flag added changing behavior on source model's reset

test/e2e/tests/communities/test_communities_send_accept_decline_request_from_profile.py
As was discussed I replaced using user data in case we add contact in test. 
I reviewed also all other tests where we use user data and only in this one we add contact after start.
CI run:
https://ci.status.im/job/status-desktop/job/e2e/job/manual/2417/allure/
=> Replaced using user data with steps

storybook/pages/SendModalPage.qml, storybook/src/Models/NetworksModel.qml, ui/imports/shared/popups/send/SendModal.qml, ui/imports/shared/popups/send/views/NetworksSimpleRoutingView.qml
Backport of PR https://github.com/status-im/status-desktop/pull/15969
- remove the nested unneeded ScrollView
- cleanups and fixes in mocked models and stores to unbreak showing the networks/routing in storybook
Fixes #15902
=> [CHERRY-PICK] fix(SendModal): Bridge modal Simple mode's scroll is very clunky

ui/imports/shared/popups/addaccount/states/Main.qml
cherry-pick: https://github.com/status-im/status-desktop/pull/15944
=> fix(wallet): Disable adding new watch-only accounts

ui/imports/shared/popups/send/SendModal.qml, ui/imports/shared/popups/send/views/NetworkCardsComponent.qml
cherry-pick https://github.com/status-im/status-desktop/pull/15867
=> [cherry-pick]: Disable send button on router errors & visually indicate gas issues

ui/app/AppLayouts/Wallet/services/dapps/DAppsRequestHandler.qml
closes [#15947](https://github.com/status-im/status-desktop/issues/15947)
Transform the fees from Wei to ETH when the fees are provided by the dApp.
Wallet Connect
Connect to Rarible and try to purchase a collectible
Tick **one**:
-->
=> fix(WalletConnect): Fixing fees parsing when provided by the dApp

test/e2e/tests/settings/settings_wallet/test_wallet_settings_account_order.py, test/e2e/tests/wallet_main_screen/wallet - plus button/test_plus_button_add_watched_address.py
cherry-pick [tests: rework e2e tests according to product changes](https://github.com/status-im/status-desktop/pull/15990)
=> [CHERRY-PICK] tests: e2e tests fixes

ci/Jenkinsfile.tests-e2e
[CHERRY-PICK] test: set screen 2560x1440x24
=> [CHERRY-PICK] test: set screen 2560x1440x24

src/app_service/service/accounts/dto/api_config.nim
Cherry-pick:
- https://github.com/status-im/status-desktop/pull/16003
=> fix: [cherry-pick] change rpc host to localhost (#16003)

ui/app/AppLayouts/Wallet/stores/WalletAssetsStore.qml
=> fix(@wallet): enable eth bridging

ui/app/AppLayouts/Profile/views/wallet/ManageTokensView.qml, ui/app/AppLayouts/Wallet/WalletLayout.qml, ui/app/AppLayouts/Wallet/controls/TokenSelectorNew.qml, ui/app/AppLayouts/Wallet/panels/TokenSelectorPanel.qml, ui/app/AppLayouts/Wallet/stores/TokensStore.qml, ui/app/AppLayouts/Wallet/views/RightTabView.qml
Cherry-pick of `39d533acd45a428623a94589ce39986a519a92e4` from `release/2.30.x` branch, related PR: https://github.com/status-im/status-desktop/pull/15956
Closes: #15766
=> fix(Wallet/SendModal): Using community assets in SendModal unblocked

test/e2e/gui/components/wallet/wallet_account_popups.py, test/e2e/tests/settings/settings_wallet/test_wallet_settings_account_order.py
Fix for color codes mismatch on different OSes
e.g. https://ci.status.im/job/status-desktop/job/systems/job/linux/job/x86_64/job/tests-e2e-new/491/allure/#suites/e6bb673289fea3c08585040382884efe/77be4b32f045edeb/
=> tests: set random color and return it so it works on any OS

test/e2e/configs/system.py, test/e2e/conftest.py, test/e2e/gui/main_window.py, test/e2e/gui/screens/settings.py, test/e2e/scripts/utils/decorators.py, test/e2e/tests/communities/test_communities.py, test/e2e/tests/communities/test_communities_categories.py, test/e2e/tests/communities/test_communities_mint_owner_token.py, test/e2e/tests/communities/test_communities_permissions.py, test/e2e/tests/messages/test_messaging_1x1_chat.py, test/e2e/tests/onboarding/test_onboarding_generate_new_keys.py, test/e2e/tests/onboarding/test_onboarding_import_seed.py, test/e2e/tests/onboarding/test_onboarding_negative_scenarios.py, test/e2e/tests/onboarding/test_onboarding_syncing.py, test/e2e/tests/settings/settings_wallet/test_wallet_settings_networks_testnet_mode.py, test/e2e/tests/settings/test_ens_name_purchase.py, test/e2e/tests/settings/test_settings_back_up_seed.py, test/e2e/tests/wallet_main_screen/wallet - footer actions/test_footer_actions_send.py, test/e2e/tests/wallet_main_screen/wallet - footer actions/test_footer_actions_send_nft.py, test/e2e/tests/wallet_main_screen/wallet - right click out of account area/test_right_click_manage_watched_address.py
Cherry-pick 95addf9fcee74cbab18d9d41a56e8ea7ee522d7f
Tests
=> [cherry-pick] chore: make tests running for dev build and update marks

storybook/pages/SwapSignModalPage.qml, storybook/qmlTests/tests/tst_SwapApproveCapModal.qml, storybook/qmlTests/tests/tst_SwapSignModal.qml, ui/app/AppLayouts/Wallet/controls/SwapProvidersTermsAndConditionsText.qml, ui/app/AppLayouts/Wallet/controls/qmldir, ui/app/AppLayouts/Wallet/popups/swap/SwapApproveCapModal.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapModal.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapSignModal.qml, ui/app/AppLayouts/Wallet/stores/RootStore.qml, ui/app/mainui/AppMain.qml, ui/imports/utils/Constants.qml
master PR https://github.com/status-im/status-desktop/pull/16035
Implements new design https://www.figma.com/design/TS0eQX9dAZXqZtELiwKIoK/Swap---Milestone-1?node-id=6187-84605&m=dev
Swap, SwapSign, SwapApprove Modals
=> [Cherry-Pick] Feat/add paraswap terms and conditions url text

src/app/boot/app_controller.nim, src/app/global/global_events.nim, src/app_service/service/metrics/async_tasks.nim, src/app_service/service/metrics/service.nim, storybook/pages/MetricsEnablePopupPage.qml, ui/app/AppLayouts/Onboarding/views/WelcomeView.qml, ui/app/AppLayouts/Profile/views/PrivacyAndSecurityView.qml, ui/imports/shared/popups/MetricsEnablePopup.qml, ui/imports/shared/stores/MetricsStore.qml, ui/imports/utils/Constants.qml, ui/imports/utils/Global.qml, ui/main.qml
Issue #15737
Cherry-pick of https://github.com/status-im/status-desktop/pull/15803
=> [CHERRY-PICK] feat(@desktop/metrics): send basic metrics (#15803)

src/app_service/service/transaction/service.nim, ui/app/AppLayouts/Wallet/WalletUtils.qml, ui/imports/shared/popups/send/SendModal.qml, ui/imports/utils/Constants.qml
Depends on `status-go` PR:
- https://github.com/status-im/status-go/pull/5637
- https://github.com/status-im/status-desktop/pull/15926
=> [CHERRY-PICK] fix: tx fails if the bonder fee is higher than the amount being sent

storybook/pages/SwapModalPage.qml, ui/app/AppLayouts/Wallet/WalletUtils.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapModalAdaptor.qml, ui/imports/utils/Constants.qml
Cherrypick https://github.com/status-im/status-desktop/pull/15875
bump status-go
=> (CHERRYPICK) feat(@desktop/wallet): handle Paraswap price impact error 

ui/app/AppLayouts/Wallet/views/RightTabView.qml
Cherry-pick of https://github.com/status-im/status-desktop/pull/15997
=> [CHERRY-PICK] Fix/wallet lose view 15857

ci/Jenkinsfile.combined
This PR makes the E2E stage run as soon as the linux stage is complete.
=> ci: run E2E as soon as linux stage is complete

ui/app/AppLayouts/Wallet/WalletUtils.qml, ui/imports/shared/popups/send/views/NetworkSelector.qml, ui/imports/utils/Constants.qml
This PR doesn't depend on statusgo, but adds nonce improvements for sending tx (we could merge it without statusgo changes as well):
- https://github.com/status-im/status-go/pull/5658
=> chore: display generic error returned from the router

ci/Jenkinsfile.combined
This PR makes the E2E stage run as soon as the linux stage is complete.
=> [cherry-pick] ci: run E2E as soon as linux stage is complete

src/app/modules/main/wallet_section/module.nim, src/app/modules/shared_modules/wallet_connect/controller.nim, src/app_service/service/wallet_connect/service.nim, src/backend/wallet.nim, src/backend/wallet_connect.nim, storybook/qmlTests/tests/tst_DAppsWorkflow.qml, ui/app/AppLayouts/Wallet/services/dapps/DAppsRequestHandler.qml, ui/app/AppLayouts/Wallet/services/dapps/DappsConnectorSDK.qml, ui/app/AppLayouts/Wallet/services/dapps/WalletConnectService.qml, ui/imports/shared/stores/DAppsStore.qml
Corresponding `nim-status-go` PR:
- https://github.com/status-im/nim-status-go/pull/32 
Fixes: #15957
These changes integrate keycard signing into each of so far the developed wallet connect flows.
In the video below you can see signing all of those flows using keycard:
https://github.com/user-attachments/assets/f74b08bd-6163-469d-affe-f7dbfe890c32
=> fix: keycard signing integration into wallet connect flows

ui/app/AppLayouts/Wallet/WalletUtils.qml, ui/imports/shared/popups/send/views/NetworkSelector.qml, ui/imports/utils/Constants.qml
- https://github.com/status-im/status-desktop/pull/16001
=> [CHERRY-PICK] display generic error returned from the router

src/app/modules/main/wallet_section/controller.nim, src/app/modules/main/wallet_section/io_interface.nim, src/app/modules/main/wallet_section/module.nim, src/app/modules/main/wallet_section/view.nim, src/app/modules/shared_modules/add_account/controller.nim, src/app/modules/shared_modules/add_account/io_interface.nim, src/app/modules/shared_modules/add_account/module.nim, src/app/modules/shared_modules/add_account/view.nim, src/app_service/service/wallet_account/service.nim, src/backend/backend.nim, ui/StatusQ/src/StatusQ/Core/StatusIconWithTooltip.qml, ui/StatusQ/src/StatusQ/Core/qmldir, ui/StatusQ/src/statusq.qrc, ui/app/AppLayouts/Wallet/popups/AddEditSavedAddressPopup.qml, ui/app/AppLayouts/Wallet/stores/RootStore.qml, ui/imports/shared/popups/addaccount/panels/WatchOnlyAddressSection.qml, ui/imports/shared/popups/addaccount/stores/AddAccountStore.qml
Depends on `status-go` PR:
- https://github.com/status-im/status-go/pull/5632
- https://github.com/status-im/status-desktop/pull/15893
=> [CHERRY-PICK] checksum validation

src/app/modules/main/wallet_section/module.nim, src/app/modules/shared_modules/wallet_connect/controller.nim, src/app_service/service/wallet_connect/service.nim, src/backend/wallet.nim, src/backend/wallet_connect.nim, storybook/qmlTests/tests/tst_DAppsWorkflow.qml, ui/app/AppLayouts/Wallet/services/dapps/DAppsRequestHandler.qml, ui/app/AppLayouts/Wallet/services/dapps/DappsConnectorSDK.qml, ui/app/AppLayouts/Wallet/services/dapps/WalletConnectService.qml, ui/imports/shared/stores/DAppsStore.qml
Cherry picked PR:
- https://github.com/status-im/status-desktop/pull/16064
These changes rely on `nim-status-go` PR:
- https://github.com/status-im/nim-status-go/pull/32 
I guess we can update `nim-status-go` without having `release` branch specifically there.
=> [CHERRY-PICK] wallet connect keycard integration

src/app_service/service/wallet_account/async_tasks.nim, src/app_service/service/wallet_account/service.nim, src/app_service/service/wallet_account/service_account.nim
Fixes #16086
Work by me and @saledjenic
=> Make the getENSName calls async

ui/app/AppLayouts/Profile/views/EnsDetailsView.qml, ui/app/AppLayouts/Profile/views/EnsSearchView.qml, ui/app/AppLayouts/Profile/views/EnsTermsAndConditionsView.qml, ui/app/AppLayouts/Wallet/WalletUtils.qml, ui/imports/shared/popups/send/SendModal.qml
Fixes the register Ens flow
Register Ens, SendModal
https://github.com/user-attachments/assets/33597402-ea8b-49b4-b442-1c50c7fcdab9
https://github.com/user-attachments/assets/db37671b-219c-48f8-a979-4d376f98780c
=> fix(@desktop/wallet): Fix register ENS flow which is currently broken

ui/imports/assets/docs/terms-of-use.mdwn
- update to the latest version, as of 2024-08-14
=> chore: update Terms of Use document

ci/Jenkinsfile.tests-e2e, src/app_service/service/accounts/dto/api_config.nim, src/constants.nim, src/env_cli_vars.nim, test/e2e/tests/settings/settings_wallet/test_wallet_settings_saved_addresses_add.py, test/e2e/tests/wallet_main_screen/wallet - saved addresses/test_saved_addresses.py
cherry-pick:
- https://github.com/status-im/status-desktop/pull/16118
=> chore: cherry-pick #16118: enable disabling http/ws api from cli

ui/imports/assets/docs/terms-of-use.mdwn
Backport of PR https://github.com/status-im/status-desktop/pull/16122
- update to the latest version, as of 2024-08-14
=> [CHERRY-PICK] chore: update Terms of Use document

ui/app/AppLayouts/Profile/views/EnsDetailsView.qml, ui/app/AppLayouts/Profile/views/EnsSearchView.qml, ui/app/AppLayouts/Profile/views/EnsTermsAndConditionsView.qml, ui/imports/shared/popups/send/SendModal.qml
CherryPick https://github.com/status-im/status-desktop/pull/16105 into master
=> [CherryPick]: fix(@desktop/wallet): Fix register ENS flow which is currently broken

src/app/global/feature_flags.nim, src/env_cli_vars.nim
=> chore(connector): disable connector flag and WS server by  default

ui/app/AppLayouts/Profile/ProfileLayout.qml, ui/app/AppLayouts/Profile/views/AboutView.qml, ui/app/mainui/AppMain.qml, ui/imports/assets/docs/privacy.mdwn, ui/imports/assets/docs/terms-of-use.mdwn
- change the section names and titles accordingly too
- open embedded links with an external browser
- do not require confirmation for `mailto:` protocol
Settings/About
Privacy Policy:
About:
=> chore(Settings/About): update Privacy Policy document

ui/app/AppLayouts/Profile/ProfileLayout.qml, ui/app/AppLayouts/Profile/views/AboutView.qml, ui/app/mainui/AppMain.qml, ui/imports/assets/docs/privacy.mdwn, ui/imports/assets/docs/terms-of-use.mdwn
Backport of PR https://github.com/status-im/status-desktop/pull/16151
- change the section names and titles accordingly too
- open embedded links with an external browser
- do not require confirmation for mailto: protocol
Settings/About
=> [CHERRY-PICK] chore(Settings/About): update Privacy Policy document

ui/imports/shared/popups/addaccount/panels/WatchOnlyAddressSection.qml, ui/imports/shared/popups/addaccount/stores/AddAccountStore.qml
=> fix: can't add ens name as watched address

src/app_service/service/transaction/dto_conversion.nim
the fromToken decimals was 0 and hence throwing the errors
Send
https://github.com/user-attachments/assets/66483a07-f879-4679-bbae-99e0b84d95b9
=> fix(@desktop/wallet): fix sending erc1155

Makefile
- do not depend on NIM for building/running StatusQ and Storybook stuff
Makefile/build
=> chore(Makefile): reduce ui-tests build and runtime

src/app_service/service/transaction/dto_conversion.nim
cherry pick PR from release https://github.com/status-im/status-desktop/pull/16172
SendModal
=> [Cherry-Pick] fix(@desktop/wallet): fix sending erc1155

ui/app/AppLayouts/Communities/panels/MintTokensSettingsPanel.qml
- https://github.com/status-im/status-desktop/pull/16175
=> [CHERRY-PICK] fixed issue with no fees when minting community token

test/e2e/constants/user.py, test/e2e/constants/wallet.py, test/e2e/gui/components/context_menu.py, test/e2e/gui/objects_map/names.py, test/e2e/gui/screens/wallet.py, test/e2e/requirements.txt, test/e2e/scripts/utils/generators.py, test/e2e/tests/wallet_main_screen/wallet - plus button/test_plus_button_manage_account_from_seed_phrase.py, test/e2e/tests/wallet_main_screen/wallet - plus button/test_plus_button_manage_generated_account_custom_derivation_path.py, ui/app/AppLayouts/Wallet/views/AccountContextMenu.qml
Reduce the number of iterations for the same test in a single run. Instead, each run random selection from enum will be picked up. It will save us time for total run
Updated object name for account action items
Tests
=> tests: reduce number of iterations of the same test per run by adding randomisation

src/app_service/service/wallet_account/async_tasks.nim, src/app_service/service/wallet_account/service_account.nim, src/backend/accounts.nim
- https://github.com/status-im/status-go/pull/5748
Fixes #15299
=> fix: can't add account when being offline

ui/app/AppLayouts/Wallet/WalletUtils.qml, ui/imports/utils/Constants.qml
- https://github.com/status-im/status-go/pull/5761
=> chore: new router error `no positive balance` added

test/e2e/constants/wallet.py, test/e2e/gui/components/wallet/wallet_account_popups.py, test/e2e/scripts/utils/generators.py, test/e2e/tests/crtitical_tests_prs/test_wallet_settings_acct_interactions_delete_account.py, test/e2e/tests/settings/settings_wallet/test_wallet_settings_account_order.py, test/e2e/tests/settings/settings_wallet/test_wallet_settings_acct_interactions_edit_status_account.py, test/e2e/tests/wallet_main_screen/wallet - plus button/test_plus_button_manage_generated_account_custom_derivation_path.py
Reduce number of test iterations for adding account with specifying derivation path. Now test will select randomly a path to use each time
Only tests
=> tests: add account with derivation path test randomised

test/e2e/gui/screens/onboarding.py, test/e2e/scripts/utils/generators.py, test/e2e/tests/crtitical_tests_prs/test_onboarding_import_seed.py
Use another generator for random seed, seem to be more convenient. Also fixed a method for completing seed from suggestions
=> chore: update random seed generator

test/e2e/tests/crtitical_tests_prs/test_add_edit_delete_generated_account.py
Exclude test from running in PRs
Reference: https://github.com/status-im/status-desktop/issues/16236
=> tests: temp exclude test from critical path

storybook/pages/BuyCryptoModalPage.qml, storybook/qmlTests/tests/tst_BuyCryptoModal.qml, ui/app/AppLayouts/Wallet/controls/BuyCryptoProvidersDelegate.qml, ui/app/AppLayouts/Wallet/panels/SelectParamsForBuyCryptoPanel.qml, ui/app/AppLayouts/Wallet/popups/buy/BuyCryptoModal.qml, ui/app/AppLayouts/Wallet/popups/buy/BuyCryptoModalAdaptor.qml, ui/app/mainui/AppMain.qml, ui/app/mainui/Popups.qml
fixes #16041
1. Write missing Qml Unit tests for Buy crypto flow
Also following new UI architecture proposed and the comment here https://github.com/status-im/status-desktop/pull/16002#discussion_r1710281670
BuyCryptoModal
https://github.com/user-attachments/assets/b107a7f4-273c-426f-94c6-99a54846f231
=> feat(@desktop/wallet): Buy Mercuryo flow - Improvements

src/app/modules/main/wallet_section/send/controller.nim, src/app/modules/main/wallet_section/send/io_interface.nim, src/app/modules/main/wallet_section/send/module.nim, src/app/modules/main/wallet_section/send/view.nim, src/app_service/service/transaction/service.nim, ui/imports/shared/popups/send/SendModal.qml, ui/imports/shared/stores/send/TransactionStore.qml
Corresponding `status-go` changes:
- https://github.com/status-im/status-go/pull/5783
Closes #14571
=> feat: fees update integration after calculating the initial route

src/app/modules/main/wallet_section/accounts/model.nim
This fixes the issues where the accounts model gets reset on every minor model change triggering full UI refresh. This is not fixing the root cause, but the symptoms in the upper-most level I could find in order to keep the regression risk to a low level.
Next steps:
Adding a new task to refactor the signals and events handling here
https://github.com/status-im/status-desktop/blob/9d9fb69e3be1bcd39ead3e94bf7b903ab301d382/src/app/modules/main/wallet_section/module.nim#L222-L229
Wallet accounts
https://github.com/user-attachments/assets/786f52bd-91bd-4a17-8a18-f82b44b33e86
=> fix(Accounts): Avoid model reset on every account change

test/e2e/tests/transactions_tests/test_buy_ens_name_in_settings.py
Fix method reference that has been changed recently
Tests
=> chore: fix method reference

test/e2e/tests/crtitical_tests_prs/test_onboarding_import_seed.py, ui/app/AppLayouts/Wallet/views/TokenSelectorCollectibleDelegate.qml
object name for collectibles in wallet
=> chore: add object name for collectibles delegates

ui/app/AppLayouts/Wallet/panels/SearchableCollectiblesPanel.qml
object name for search box in searchable collectibles panel
=> chore: object name for search box in searchable collectibles panel

test/e2e/gui/components/community/invite_contacts.py, test/e2e/gui/screens/community.py, test/e2e/gui/screens/community_settings.py, test/e2e/tests/wallet_main_screen/wallet - plus button/test_plus_button_manage_account_from_seed_phrase.py
Fix fails in nightly from today: https://ci.status.im/job/status-desktop/job/systems/job/linux/job/x86_64/job/tests-e2e-new/543/allure/#suites/bce9c379aef0429c737b315127e9480e/c4bb839256d070ee/
- test_create_community
- test_join_community_and_pin_unpin_message
- test_communities_send_accept_decline_request_remove_contact_from_profile
- test_plus_button_manage_account_from_seed_phrase
Group chat test was fixed in previous PR
Transaction test is failing because send/bridge buttons are not accessible, addressed in chat
CI runs: 
https://ci.status.im/job/status-desktop/job/e2e/job/manual/2516/allure/#suites/b84b99d2c699f7ea120c5dcc06c723f8
https://ci.status.im/job/status-desktop/job/e2e/job/manual/2515/allure/
=> chore: fix nightly failures

storybook/pages/SendModalPage.qml, storybook/pages/SendRecipientInputPage.qml, storybook/qmlTests/tests/tst_SendRecipientInput.qml, storybook/stubs/shared/stores/send/TransactionStore.qml, ui/imports/shared/popups/send/SendModal.qml, ui/imports/shared/popups/send/controls/SendRecipientInput.qml, ui/imports/shared/popups/send/views/RecipientView.qml
- update the SB page with the toggle too
Fixes #16355
SendRecipientInput -> RecipientView -> SendModal
https://github.com/user-attachments/assets/dc319497-8c9f-4eb4-a353-ea5c66a4dc59
=> feat(SendModal): add a spinner when resolving an ENS name

src/nim_status_client.nim, storybook/pages/DAppsWorkflowPage.qml, storybook/qmlTests/tests/tst_DAppsWorkflow.qml, ui/app/AppLayouts/Wallet/panels/DAppsWorkflow.qml, ui/app/AppLayouts/Wallet/services/dapps/DAppsRequestHandler.qml, ui/app/AppLayouts/Wallet/services/dapps/DappsConnectorSDK.qml, ui/app/AppLayouts/Wallet/services/dapps/types/SessionRequestResolved.qml
Fixing several transactions/sign failures
1. Fixing Storybook
2. Removing the usage of js objects representing model items. The alternative to this is to pass around the object ids and the data can be extracted when needed from the model.
Wallet Connect
Browser Connect
Before: The user could not do transactions or sign messages in some situations
After: The user can do transactions
1. Run connect, sign and transaction flows on Storybook
2. Run connect, sign and transaction flows in the app
Signing messages
Sending transactions. The crash happened while sending transactions on L2 and the account doesn't have …
=> WC: Fixing transactions failures

test/e2e/tests/crtitical_tests_prs/test_onboarding_sync_with_code.py
- update status-go in master
- fix sync devices test to reflect recent changes in https://github.com/status-im/status-go/pull/5794
=> Update status go and fix sync devices test

test/e2e/tests/crtitical_tests_prs/test_messaging_group_chat.py, test/e2e/tests/crtitical_tests_prs/test_onboarding_import_seed.py, test/e2e/tests/messages/test_messaging_link_previews.py, test/e2e/tests/settings/settings_wallet/test_wallet_rename_keypair.py, test/e2e/tests/transactions_tests/test_mint_owner_and_tokenmaster_tokens.py, test/e2e/tests/transactions_tests/test_wallet_send_eth.py, test/e2e/tests/transactions_tests/test_wallet_send_nft.py, test/e2e/tests/wallet_main_screen/wallet - plus button/test_plus_button_manage_account_from_seed_phrase.py
Merge 2 existing tests into single one 
e2e
=> chore: merge tests into a single flow

test/e2e/gui/components/wallet/send_popup.py, test/e2e/gui/components/wallet/token_selector_popup.py, test/e2e/gui/objects_map/names.py, ui/app/AppLayouts/Wallet/views/TokenSelectorAssetDelegate.qml
NOTE: i spoke to Michal C and we discussed as next step to change the way of accessing delegates:
> Instead of relying on object names for delegates we should rely on indexes
> it mean that we should check the position of given item in the model
> and then what you need is handler to ListView
> on list view you can call positionViewAtIndex to make sure that delegate is rendered
> and then access it via itemAtIndex 
that would be a next step to implement as now i am just trying to make the test work again
Fix test for sending transaction which failed in nightly today https://ci.status.im/job/status-desktop/job/systems/job/linux/job/x86_64/job/tests-e2e-new/553/allure/#suites/a1c3ee7c9d32765015c6799e7b8f7727/ab0c5ff2318eb10d/
CI run: …
=> chore: fix test for sending transaction

test/e2e/gui/components/wallet/send_popup.py, test/e2e/gui/components/wallet/token_selector_popup.py, test/e2e/gui/elements/object.py, test/e2e/gui/elements/scroll.py, test/e2e/gui/objects_map/names.py, test/e2e/tests/transactions_tests/test_wallet_send_eth.py, test/e2e/tests/transactions_tests/test_wallet_send_nft.py
Test to send NFT in wallet
Depends on https://github.com/status-im/status-desktop/issues/16328
CI run:  https://ci.status.im/job/status-desktop/job/e2e/job/manual/2522/allure/#suites/70fdb27d8baec44f061998da79f5a084/317a3b1addc4ddf/
=> tests: send random NFT

test/e2e/constants/messaging.py, test/e2e/tests/settings/settings_messaging/test_messaging_settings_reject_request.py, test/e2e/tests/transactions_tests/test_mint_owner_and_tokenmaster_tokens.py
=> chore: tiny fixes for several failures in nightly

ui/StatusQ/CMakeLists.txt, ui/StatusQ/include/StatusQ/constantrole.h, ui/StatusQ/src/constantrole.cpp, ui/StatusQ/src/plugin.cpp, ui/StatusQ/tests/TestCore/TestModels/tst_ConstantRole.qml
Adds custom proxy role for `SFPM` serving fixed value.
Closes: #16401
=> StatusQ: ConstantRole - custom SFPM proxy role added

test/e2e/gui/objects_map/communities_names.py, test/e2e/gui/screens/community.py, test/e2e/gui/screens/messages.py, test/e2e/scripts/utils/parsers.py, test/e2e/tests/communities/test_communities_categories.py, test/e2e/tests/communities/test_communities_channels.py
Improve channels and categories locators in tests
Only tests
=> chore: fix community channels and categories locators

storybook/qmlTests/tests/tst_LazyStackLayout.qml, ui/StatusQ/src/StatusQ/Core/Utils/LazyStackLayout.qml, ui/StatusQ/src/StatusQ/Core/Utils/qmldir, ui/StatusQ/src/statusq.qrc
This PR introduces component encapsulating logic of stack view with deferred instantiation. Provided components are wrapped with loaders and instantiated when first time accessed.
Closes: #16416
[Screencast from 26.09.2024 13:52:37.webm](https://github.com/user-attachments/assets/b494bed4-48f6-48d8-b405-26dab8673c0c)
=> StatusQ: Introduce LazyStackLayout - stack layout with deferred instantiation

storybook/pages/AddEditSavedAddressPopupPage.qml, ui/app/AppLayouts/Wallet/panels/DAppsWorkflow.qml, ui/app/AppLayouts/Wallet/panels/WalletHeader.qml, ui/app/AppLayouts/Wallet/popups/AddEditSavedAddressPopup.qml, ui/app/AppLayouts/Wallet/stores/RootStore.qml, ui/app/AppLayouts/Wallet/views/LeftTabView.qml, ui/app/AppLayouts/Wallet/views/RightTabBaseView.qml, ui/app/mainui/AppMain.qml, ui/imports/shared/controls/TransactionDelegate.qml
(best review commit by commit, also see my inline code comments below):
- TransactionDelegate: fix `transactionType` function
- AddEditSavedAddressPopup: fix validating account
- DappSignRequestModal: fix passing `loginType` from the correct RootStore + an evil typo fix
Fixes #16089
Wallet(Connect)
AddEditSavedAddressPopup: 
DappSignRequestModal:
=> fix(wallet): several regressions due to recent store refactorings

src/app/modules/main/communities/tokens/module.nim
Fixes #16326
Passes the image through the image formatting function before sending
=> fix(minting): fix minting tokens on Windows

.github/pull_request_template.md
Updates the broken link in the PR template.
=> Fixed link to CONTRIBUTING.md in the PR template

test/e2e/driver/aut.py, test/e2e/driver/context.py, test/e2e/gui/components/onboarding/beta_consent_popup.py, test/e2e/gui/components/wallet/wallet_account_popups.py, test/e2e/gui/objects_map/names.py, test/e2e/tests/wallet_main_screen/wallet - plus button/test_plus_button_manage_account_from_seed_phrase.py
- fix potential typos
- cover https://github.com/status-im/status-desktop/issues/16380 in autotest
CI run: https://ci.status.im/job/status-desktop/job/e2e/job/manual/2534/
=> tests: add verification when re-adding same seed again

test/e2e/gui/components/authenticate_popup.py, test/e2e/gui/components/community/community_channel_popups.py, test/e2e/gui/components/onboarding/before_started_popup.py, test/e2e/gui/components/onboarding/beta_consent_popup.py, test/e2e/gui/components/settings/block_user_popup.py, test/e2e/gui/components/settings/confirm_switch_waku_mode_popup.py, test/e2e/gui/components/settings/sign_out_popup.py, test/e2e/gui/components/signing_phrase_popup.py, test/e2e/gui/components/wallet/remove_wallet_account_popup.py, test/e2e/gui/components/wallet/wallet_account_popups.py, test/e2e/gui/main_window.py, test/e2e/gui/screens/community_settings.py, test/e2e/gui/screens/onboarding.py, test/e2e/scripts/utils/local_system.py, test/e2e/tests/settings/settings_wallet/test_wallet_rename_keypair.py, test/e2e/tests/settings/settings_wallet/test_wallet_settings_account_order.py, test/e2e/tests/settings/settings_wallet/test_wallet_settings_add_account.py
- increase timeouts
- simplify rename keypair test
=> tests: simplify renaming of keypair test and increase timeouts

Makefile, ci/Dockerfile, ci/Jenkinsfile.linux, ci/Jenkinsfile.linux-nix, ci/Jenkinsfile.macos, ci/Jenkinsfile.windows, nix/overlay.nix, nix/pkgs/go-module/default.nix, nix/pkgs/go/binary.nix, nix/pkgs/mockgen/default.nix, nix/pkgs/protobuf/default.nix, nix/pkgs/protobuf/generic-v3.nix, nix/pkgs/protoc-gen-go/default.nix, scripts/macos_build_setup.sh, scripts/ubuntu_build_setup.sh, scripts/windows_build_setup.ps1, shell.nix
Requires things like: `go-bindata`, `mockgen`, `protobuf`
Fixes:
- https://github.com/status-im/status-desktop/issues/16477
For more details see:
- https://github.com/status-im/status-go/pull/5878
=> fix(status-go)_: add missing status-go dependencies

ui/imports/utils/Utils.qml
Initial separation of backend-independ and stateless content from backend-dependent method/properties which are a subject of further refactors.
This PR only moves code within one file, to make initial investigation and make further PRs shorter and cleaner.
The categorization is added as a description to https://github.com/status-im/status-desktop/issues/16251
Closes: #16481
`imports/utils/Utils.qml`
=> chore: Utils.qml content divided into two categories

ui/imports/shared/popups/UserAgreementPopup.qml
Remove warning discouraging usage
Hello popup
=> chore(@wallet): Desktop is in beta

test/e2e/constants/community.py, test/e2e/gui/components/community/create_community_popups.py, test/e2e/gui/components/community/leave_community_confirmation.py, test/e2e/gui/components/context_menu.py, test/e2e/gui/objects_map/communities_names.py, test/e2e/gui/screens/community_settings_tokens.py, test/e2e/tests/communities/test_communities_kick_ban.py, test/e2e/tests/communities/test_communities_limit_to_5_permissions.py, test/e2e/tests/communities/test_communities_screens_overview.py, test/e2e/tests/crtitical_tests_prs/test_community_create_edit.py, test/e2e/tests/crtitical_tests_prs/test_community_permissions_add_edit_delete_duplicate.py, test/e2e/tests/settings/settings_messaging/test_block_unblock_user.py, test/e2e/tests/transactions_tests/test_mint_owner_and_tokenmaster_tokens.py, ui/app/mainui/AppMain.qml
Continuation of https://github.com/status-im/status-desktop/pull/16535
=> Tests: edit community test improved

test/e2e/gui/screens/wallet.py, test/e2e/tests/crtitical_tests_prs/test_add_account_after_restart.py, test/e2e/tests/crtitical_tests_prs/test_add_delete_account_from_settings.py, test/e2e/tests/crtitical_tests_prs/test_add_edit_delete_generated_account.py, test/e2e/tests/settings/settings_wallet/test_wallet_settings_account_order.py, test/e2e/tests/settings/settings_wallet/test_wallet_settings_add_account.py, test/e2e/tests/settings/settings_wallet/test_wallet_settings_watched_addr_include_in_total_balance.py, test/e2e/tests/wallet_main_screen/wallet - footer actions/test_footer_actions_default_account_values.py
Cherry pick 009357e9ea171d59568556f8f24668950ced6c4b
=> [Cherry-pick]: Tests/wallet account simplified

test/e2e/tests/crtitical_tests_prs/test_messaging_1x1_chat.py, test/e2e/tests/wallet_main_screen/wallet - plus button/test_plus_button_manage_generated_account_custom_derivation_path.py
Remove xfail mark for test with custom derivation path as the related issue was fixed
=> chore(@e2e): remove xfail mark for test, bug is fixed

src/app/modules/main/profile_section/ens_usernames/module.nim, src/app/modules/main/profile_section/ens_usernames/view.nim, src/app/modules/main/wallet_section/networks/model.nim, src/app/modules/main/wallet_section/networks/view.nim, src/app_service/service/network/service.nim, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Profile/stores/EnsUsernamesStore.qml, ui/app/AppLayouts/Profile/views/EnsTermsAndConditionsView.qml, ui/app/AppLayouts/Profile/views/EnsView.qml, ui/app/AppLayouts/stores/RootStore.qml, ui/app/mainui/AppMain.qml, ui/imports/shared/stores/send/TransactionStore.qml
Cherry-picked:
- https://github.com/status-im/status-desktop/pull/16660
=> [CHERRY-PICK] fix: links do not work in the terms of name registration popup

ci/Jenkinsfile.tests-e2e
Cherry pick changes from https://github.com/status-im/status-desktop/pull/16659/
=> [Cherry-pick]: Tests/cherry pick timeout

ui/app/AppLayouts/Profile/views/EnsDetailsView.qml, ui/app/AppLayouts/Profile/views/EnsView.qml, ui/imports/shared/popups/send/SendModal.qml, ui/imports/shared/popups/send/views/NetworkSelector.qml
- https://github.com/status-im/status-desktop/pull/16644
=> [CHERRY-PICK] fix: cant fetch fees when releasing ens name, token is not set, as well as value

test/e2e/tests/crtitical_tests_prs/test_messaging_1x1_chat.py
Fix the condition for emoji path
=> chore(@e2e): fix condition for emoji path

test/e2e/gui/objects_map/settings_names.py, test/e2e/gui/screens/settings.py
change tests according to new settings list
=> chore(@e2e): change tests according to new settings list

test/e2e/helpers/SettingsHelper.py, test/e2e/tests/communities/test_communities_categories.py, test/e2e/tests/communities/test_communities_channels.py, test/e2e/tests/communities/test_communities_kick_ban.py, test/e2e/tests/communities/test_communities_limit_to_5_permissions.py, test/e2e/tests/communities/test_communities_pin_and_unpin_messages.py, test/e2e/tests/communities/test_communities_screens_overview.py, test/e2e/tests/communities/test_communities_send_accept_decline_request_from_profile.py, test/e2e/tests/communities/test_communities_share_link.py, test/e2e/tests/crtitical_tests_prs/test_community_category_add_edit_delete.py, test/e2e/tests/crtitical_tests_prs/test_community_create_edit.py, test/e2e/tests/crtitical_tests_prs/test_community_permissions_add_edit_delete_duplicate.py, test/e2e/tests/onboarding/test_onboarding_syncing.py, test/e2e/tests/onboarding/test_password_strength.py, test/e2e/tests/transactions_tests/test_mint_owner_and_tokenmaster_tokens.py, test/e2e/tests/wallet_main_screen/wallet - assets tab/test_wallet_assets_sorting.py, test/e2e/tests/wallet_main_screen/wallet - footer actions/test_footer_actions_default_account_values.py
Fix the parsing of community link and validation
=> chore(@e2e): fix community link parsing

storybook/pages/ErrorTagPage.qml, storybook/qmlTests/tests/tst_BuyCryptoModal.qml, storybook/qmlTests/tests/tst_ErrorTag.qml, storybook/qmlTests/tests/tst_SwapModal.qml, ui/app/AppLayouts/Wallet/WalletLayout.qml, ui/app/AppLayouts/Wallet/popups/buy/BuyCryptoModal.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapModal.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapModalAdaptor.qml
Fix https://github.com/status-im/status-desktop/issues/16469
Address feedback from legal https://discord.com/channels/1210237582470807632/1217171454940938341/1291353246874734622
Buy crypto modal
=> feat: buy flow wording adjusted

test/e2e/constants/wallet.py, test/e2e/tests/crtitical_tests_prs/test_messaging_group_chat.py, test/e2e/tests/transactions_tests/test_buy_ens_name_in_settings.py
- fix group chat verification
- fix toast verification for ens name
=> chore(@e2e): fix group chat test and leftover for registering ens name toast

storybook/pages/StatusMessagePage.qml, ui/StatusQ/src/StatusQ/Components/StatusContactVerificationIcons.qml, ui/StatusQ/src/StatusQ/Components/StatusMemberListItem.qml, ui/StatusQ/src/StatusQ/Components/StatusMessage.qml, ui/StatusQ/src/StatusQ/Components/StatusMessageHeader.qml, ui/StatusQ/src/StatusQ/Components/StatusMessageSenderDetails.qml, ui/StatusQ/src/StatusQ/Components/private/statusMessage/StatusMessageReply.qml, ui/app/AppLayouts/Communities/panels/MembersSettingsPanel.qml, ui/app/AppLayouts/Communities/panels/MembersTabPanel.qml, ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml, ui/imports/shared/views/chat/MessageView.qml
- add ability to copy display name of a message author
- add possibility to search for a member by a un/compressed chat key
- adjust the search field placeholder text to "Search by member name or chat key"
- update SB with some more variations
- cleanup some the signal handling
Fixes #16790
StatusMessage(Header), MembersSettingsPanel
https://github.com/user-attachments/assets/b39fd83e-e50a-4218-80ec-7c6e13ba3803
=> feat: Improvements for community admins

ui/StatusQ/src/StatusQ/Components/StatusMessage.qml, ui/app/AppLayouts/Chat/popups/PaymentRequestModal.qml
Cherry-pick 674359ff1dbb4af70c564c8dc653b23a8e954e35
=> [cherry-pick] fix(chat): Fix disappearing payment request after message edit

src/app/modules/main/communities/tokens/models/token_model.nim
Cherry pick: https://github.com/status-im/status-desktop/pull/16880
closes: #16875 #16860 #16859
(cherry picked from commit 5fcb425b47a7a73aef41e5b06107afac78b72154)
=> fix(CommunityTokens): Fixing crash on token update

storybook/pages/SendModalFooterPage.qml, storybook/pages/SimpleSendModalPage.qml, storybook/pages/SimpleTransactionsFeesPage.qml, ui/app/AppLayouts/Wallet/panels/RecipientSelectorPanel.qml, ui/app/AppLayouts/Wallet/panels/SendModalHeader.qml, ui/app/AppLayouts/Wallet/panels/SimpleTransactionsFees.qml, ui/app/AppLayouts/Wallet/panels/StickySendModalHeader.qml, ui/app/AppLayouts/Wallet/panels/qmldir, ui/app/AppLayouts/Wallet/popups/simpleSend/SimpleSendModal.qml, ui/app/AppLayouts/Wallet/views/RecipientView.qml, ui/app/AppLayouts/Wallet/views/SendModalFooter.qml, ui/app/AppLayouts/Wallet/views/qmldir, ui/app/mainui/AppMain.qml, ui/app/mainui/SendModalHandler.qml, ui/imports/shared/popups/send/views/AmountToSend.qml
… current state
fixes #16903, #16913,  #16706, #16918
SimpleSendModal
- [ x I am familiar with the application architecture and agreed good practices.
https://github.com/user-attachments/assets/9c31b414-98b6-495f-9247-a25fa52fc604
=> feat(@desktop/wallet): Entering asset value + using max button in its current state

ui/imports/assets/docs/terms-of-use.mdwn
=> chore(tou): update Terms of Use document to version 9

ui/imports/assets/docs/terms-of-use.mdwn
=> chore(tou): update terms of use to version 9.1

src/app/modules/main/profile_section/wallet/module.nim, src/app/modules/main/profile_section/wallet/view.nim, src/app/modules/main/wallet_section/module.nim, src/app/modules/main/wallet_section/view.nim
Cherry-pick from https://github.com/status-im/status-desktop/pull/16938
=> [CHERRY-PICK] Wallet: add missing notification on keypairImportModule change

ui/app/AppLayouts/Onboarding/views/KeysMainView.qml, ui/app/AppLayouts/Onboarding/views/SyncDeviceResult.qml
Updates some wording in on-boarding according to the design.
Closes: #16929
`KeysMainView`, `SyncDeviceResult`
=> Onboarding: minor wording adjustments

ui/imports/assets/docs/terms-of-use.mdwn
Fixes #16930
Cherry-pick of https://github.com/status-im/status-desktop/pull/16931
=> [CHERRY-PICK] chore(tou): update Terms of Use document to version 9

src/app/modules/main/module.nim, src/app/modules/main/profile_section/ens_usernames/module.nim, src/app/modules/main/profile_section/ens_usernames/view.nim, ui/app/AppLayouts/Profile/views/EnsListView.qml
Corresponding `statusgo` PR:
- https://github.com/status-im/status-go/pull/6208
This PR should be a replacement for this one https://github.com/status-im/status-desktop/pull/16934 that means it fixes https://github.com/status-im/status-desktop/issues/16921 and https://github.com/status-im/status-desktop/issues/16922.
It also fixes https://github.com/status-im/status-desktop/issues/16942
=> fix(wallet): adding ens name to the model and improving ephemeral notification with saved address if exists

src/app/modules/main/module.nim, src/app/modules/main/profile_section/ens_usernames/module.nim, src/app/modules/main/profile_section/ens_usernames/view.nim, ui/app/AppLayouts/Profile/views/EnsListView.qml
Cherry-picked:
- https://github.com/status-im/status-desktop/pull/16953
Corresponding `stauts-go` PR:
- https://github.com/status-im/status-go/pull/6213
=> [cherry-pick]: fix(wallet): adding ens name to the model and improving ephemeral notification with saved address if exists

test/e2e/constants/messaging.py
Slightly update the text on No Friends screen
=> chore(@e2e): update no friends text on messaging screen

Makefile
=> ci: don't update brew

storybook/pages/SimpleTransactionsFeesPage.qml, storybook/qmlTests/tests/tst_SendModalFooter.qml, storybook/qmlTests/tests/tst_SimpleTransactionsFees.qml, ui/app/AppLayouts/Wallet/controls/RouterErrorTag.qml, ui/app/AppLayouts/Wallet/panels/RecipientSelectorPanel.qml, ui/app/AppLayouts/Wallet/panels/SimpleTransactionsFees.qml, ui/app/AppLayouts/Wallet/popups/simpleSend/SimpleSendModal.qml, ui/app/AppLayouts/Wallet/views/SendModalFooter.qml
fixes #17141
Implements new error state defined here https://www.figma.com/design/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=27987-285409&m=dev
SimpleSend
=> feat(@desktop/wallet): Add new error state for simple send

storybook/pages/OnboardingLayoutPage.qml, ui/app/AppLayouts/Onboarding2/LoginWithKeycardFlow.qml, ui/app/AppLayouts/Onboarding2/OnboardingFlow.qml, ui/app/AppLayouts/Onboarding2/UnblockWithSeedphraseFlow.qml, ui/app/AppLayouts/Onboarding2/qmldir
1. Excludes unblock with seedphrase flow to separate flow component (`UnblockWithSeedphraseFlow`)
2. Use the flow for to cases (existing local user login and new login)
Closes: #17142
`OnboardingFlow`
=> Onboarding: Unblock with seedphrase flow for login

src/app/modules/onboarding/module.nim, ui/StatusQ/src/onboarding/enums.h, ui/app/AppLayouts/Onboarding2/KeycardCreateReplacementFlow.qml, ui/app/AppLayouts/Onboarding2/OnboardingFlow.qml, ui/app/AppLayouts/Onboarding2/OnboardingLayout.qml
Part of
- https://github.com/status-im/status-desktop/issues/17238
1. Connect proper signals for the Create Keycard Replacement flow
2. Update enums list in Nim
=> fix: unblock create replacement flow

ci/Jenkinsfile.combined, ci/Jenkinsfile.linux, ci/Jenkinsfile.linux-nix, ci/Jenkinsfile.macos, ci/Jenkinsfile.windows
Refs:
- https://github.com/status-im/infra-ci/issues/168
- https://github.com/status-im/status-jenkins-lib/pull/107
=> chore(ci): bump status-jenkins-lib to include alchemy base api keys

src/app/global/app_sections_config.nim, src/app/modules/main/module.nim, src/app/modules/shared_models/section_item.nim, storybook/pages/SwapInputPanelPage.qml, storybook/pages/SwapModalPage.qml, storybook/qmlTests/tests/tst_SwapModal.qml, ui/app/AppLayouts/Wallet/WalletLayout.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapInputParamsForm.qml, ui/app/mainui/AppMain.qml, ui/imports/utils/Constants.qml
fixes #17197
Added swap button to Left Application list
App sections and swap
https://github.com/user-attachments/assets/8d7fe7de-9fcc-47f7-9f71-faa23dbb86c0
=> Feat/17197: Add swap button in left sidebar

src/app/boot/app_controller.nim
Iterates:
- https://github.com/status-im/status-desktop/issues/17238
_Probably_ fixes:
- https://github.com/status-im/status-desktop/issues/17168 (I didn't test it)
- https://github.com/status-im/status-desktop/issues/17222
When the onboarding finishes, we need to create the `startupModule`, because there are some post-onboarding tasks that require it.
=> feat: create `startupModule` when onboarding is finished

ui/StatusQ/src/StatusQ/Components/StatusSmartIdenticon.qml
fixes: #17131 by reverting the regression introduced in 3705249e40cabda3c45bf919143f57724740d361.
https://github.com/user-attachments/assets/1d72795f-c327-47ee-b5ef-e6a4aabf52b0
=> fix(chat): revert `StatusSmartIdenticon` changes

test/e2e/gui/objects_map/onboarding_names.py, test/e2e/gui/screens/onboarding.py, test/e2e/tests/communities/test_communities_kick_ban.py
Fix a couple of failed tests for nightly run as of 17--02-2025
Only e2e tests
=> chore(@e2e): small fixes for tests

src/app/modules/onboarding/module.nim, src/app/modules/onboarding/states.nim, src/app_service/service/keycardV2/async_tasks.nim, src/app_service/service/keycardV2/rpc.nim, src/app_service/service/keycardV2/service.nim
Just moved the types around a bit, no real code change here.
=> chore: separate rpc and states files

src/app/modules/onboarding/controller.nim, src/app/modules/onboarding/io_interface.nim, src/app/modules/onboarding/module.nim, src/app/modules/onboarding/view.nim, src/app_service/service/keycardV2/async_tasks.nim, src/app_service/service/keycardV2/service.nim
Closes https://github.com/status-im/status-desktop/issues/17223
Just bind the `FactoryReset` UI to backend. Works.
https://github.com/user-attachments/assets/cbfa33fc-dfd9-4898-887e-f502063f605a
=> feat: bind FactoryReset flow

test/e2e/driver/squish_api.py, test/e2e/gui/components/splash_screen.py, test/e2e/gui/main_window.py, test/e2e/helpers/OnboardingHelper.py, test/e2e/tests/crtitical_tests_prs/test_add_edit_delete_generated_account.py, test/e2e/tests/crtitical_tests_prs/test_messaging_1x1_chat.py, test/e2e/tests/crtitical_tests_prs/test_messaging_group_chat.py, test/e2e/tests/crtitical_tests_prs/test_onboarding_generate_account_back_up_seed.py, test/e2e/tests/crtitical_tests_prs/test_onboarding_sync_with_code.py, test/e2e/tests/onboarding/test_onboarding_negative_scenarios.py
temp increase timeout for splash screen
=> chore(@e2e): temp increase timeout for splash screen

ui/app/AppLayouts/Wallet/panels/SendModalHeader.qml, ui/app/AppLayouts/Wallet/panels/StickySendModalHeader.qml, ui/app/AppLayouts/Wallet/panels/TokenSelectorPanel.qml, ui/app/AppLayouts/Wallet/popups/simpleSend/SimpleSendModal.qml, ui/app/mainui/SendModalHandler.qml, ui/imports/shared/popups/send/views/AmountToSend.qml
fixes #17280 #17290
fix(@desktop/wallet): Fixing some bugs in simple send:
1. Collectible details lost when entering review send modal
2. Size of simeple send for Collectible
3. Preset amount set for stickers and ens names
4. Swtching between Fiat and Crypto in amount to send
5. Keeping last user tab selection in Send
SimpleSend
https://github.com/user-attachments/assets/2ab0e505-8cf0-4a5e-827a-0cf5fdeaac30
https://github.com/user-attachments/assets/8173942f-2107-4ef1-ab8d-ae940c06575e
https://github.com/user-attachments/assets/994a736e-359c-46eb-a21e-5cc8fa168ebd
https://github.com/user-attachments/assets/8b025d07-861c-4c15-9cb9-0afcd480c218
=> fix/simple send bugs: Solve remaining bugs and last tab selected setting

ci/Jenkinsfile.combined, ci/Jenkinsfile.linux, ci/Jenkinsfile.linux-nix, ci/Jenkinsfile.macos, ci/Jenkinsfile.windows, src/app_service/service/accounts/dto/wallet_secretes_config.nim, src/app_service/service/accounts/service.nim, src/backend/network_types.nim, src/constants.nim, src/env_cli_vars.nim, ui/imports/utils/Constants.qml
_TODO: update description_
closes #17229  (see description)
=> feat(wallet): integrate eth rpc proxy

src/app/modules/main/wallet_section/send_new/controller.nim, src/app/modules/main/wallet_section/send_new/io_interface.nim, src/app/modules/main/wallet_section/send_new/module.nim, src/app/modules/main/wallet_section/send_new/path_item.nim, src/app/modules/main/wallet_section/send_new/path_model.nim, src/app/modules/main/wallet_section/send_new/view.nim, src/app_service/service/transaction/dtoV2.nim, src/app_service/service/transaction/service.nim, src/backend/backend.nim, ui/app/AppLayouts/Wallet/WalletUtils.qml, ui/app/AppLayouts/Wallet/popups/simpleSend/SendSignModal.qml, ui/app/AppLayouts/Wallet/stores/TransactionStoreNew.qml, ui/app/AppLayouts/Wallet/views/TransactionSettings.qml, ui/app/mainui/SendModalHandler.qml
- https://github.com/status-im/status-go/pull/6346
=> feat(wallet): estimated time added to transaction settings

storybook/CMakeLists.txt, storybook/src/Storybook/FigmaPreviewWindow.qml, storybook/src/Storybook/ImagesNavigationLayout.qml, ui/StatusQ/CMakeLists.txt, ui/StatusQ/include/StatusQ/clipboardutils.h, ui/StatusQ/include/StatusQ/objectproxymodel.h, ui/StatusQ/include/StatusQ/statussyntaxhighlighter.h, ui/StatusQ/sandbox/CMakeLists.txt, ui/StatusQ/sanity_checker/CMakeLists.txt, ui/StatusQ/src/genericvalidator.cpp, ui/StatusQ/src/keychain_other.cpp, ui/StatusQ/src/objectproxymodel.cpp, ui/StatusQ/tests/CMakeLists.txt, ui/StatusQ/tests/main.cpp
- Updates `CMakeLists.txt` files for `StatusQ`
- Fixes compilation issues
Closes: https://github.com/status-im/status-desktop/issues/17342
Depends on: https://github.com/status-im/status-desktop/pull/17374, https://github.com/status-im/status-desktop/pull/17373
`StatusQ`
=> CMake configs for StatusQ supporting both Qt 5 & 6

src/app/boot/app_controller.nim, src/app/modules/main/profile_section/privacy/module.nim, src/app/modules/main/profile_section/privacy/view.nim, src/app/modules/onboarding/io_interface.nim, src/app/modules/onboarding/module.nim, src/app/modules/onboarding/view.nim, src/app/modules/shared_modules/keycard_popup/controller.nim, src/app/modules/shared_modules/keycard_popup/internal/state_factory_state_implementation.nim, src/app/modules/shared_modules/keycard_popup/io_interface.nim, src/app/modules/shared_modules/keycard_popup/module.nim, src/app/modules/shared_modules/keycard_popup/view.nim, storybook/pages/ChangePasswordViewPage.qml, storybook/pages/LoginScreenPage.qml, storybook/pages/OnboardingLayoutPage.qml, storybook/qmlTests/tests/tst_OnboardingLayout.qml, ui/StatusQ/include/StatusQ/keychain.h, ui/StatusQ/src/keychain_osx.mm, ui/StatusQ/src/keychain_other.cpp, ui/app/AppLayouts/Onboarding2/OnboardingFlow.qml, ui/app/AppLayouts/Onboarding2/OnboardingLayout.qml, ui/app/AppLayouts/Onboarding2/pages/LoginScreen.qml, ui/app/AppLayouts/Onboarding2/stores/OnboardingStore.qml, ui/app/AppLayouts/Profile/ProfileLayout.qml, ui/app/AppLayouts/Profile/stores/PrivacyStore.qml, ui/app/AppLayouts/Profile/views/ChangePasswordView.qml, ui/app/mainui/AppMain.qml, ui/main.qml
Closes:
- https://github.com/status-im/status-desktop/issues/17085
- https://github.com/status-im/status-desktop/issues/17368
- https://github.com/status-im/status-desktop/issues/17338
- https://github.com/status-im/status-desktop/issues/17103
- https://github.com/status-im/status-desktop/issues/15167
- https://github.com/status-im/status-desktop/issues/16167
Provides final integration of `Keychain` component with new Onboarding.
- Onboarding
- Saving credentials when the fresh account is created
- Login
- Query `Keychain` when the account is selected on the login screen to determine if biometrics can be used
- Support biometrics authentication in both OLD and NEW login screens
- Settings
- Integrate the `Keychain` component into "Change password" page
- Common
- Hide the any biometrics …
=> Onboarding: Integration of biometrics for onboarding flows and login screen

ci/Jenkinsfile.tests-e2e, test/e2e/tests/communities/test_communities_categories.py
- disable 1 test because of a bug
- remove reference to old qa repo in jenkins file
=> Tests: mark test as xfail

config.nims, ui/StatusQ/CMakeLists.txt, vendor/DOtherSide/lib/CMakeLists.txt
=> chore: Use a more granular build configuration to enable cross-compilation

src/app/modules/main/module.nim, src/app/modules/main/wallet_section/send_new/module.nim, src/app/modules/main/wallet_section/send_new/view.nim, src/app_service/service/transaction/router_transactions_dto.nim, ui/app/AppLayouts/Wallet/popups/simpleSend/SimpleSendModal.qml, ui/app/AppLayouts/Wallet/stores/TransactionStoreNew.qml, ui/app/mainui/AppMain.qml, ui/app/mainui/SendModalHandler.qml
=> fix(wallet): send modal - error message logic improved

ui/StatusQ/src/typesregistration.cpp
Closes #17463
- Added needed import condition 
- Only functional issues will be resolved, visual issues will be handled in separate [tasks](https://github.com/status-im/status-desktop/issues/17490)
`SQ/StatusDatePicker`
=> feat(Qt5->6): Refactor usages of `Qt.labs.calendar`

storybook/pages/PaymentRequestModalPage.qml, ui/app/AppLayouts/Chat/popups/PaymentRequestModal.qml, ui/app/AppLayouts/Wallet/adaptors/PaymentRequestAdaptor.qml, ui/app/AppLayouts/Wallet/adaptors/qmldir, ui/app/AppLayouts/Wallet/popups/simpleSend/SimpleSendModal.qml, ui/app/mainui/Popups.qml, ui/imports/shared/popups/send/views/AmountToSend.qml
Cherrypick of https://github.com/status-im/status-desktop/pull/17462 for release
Please note that unit tests are not added here. They will be merged to master.
Payment request
- [X} I am familiar with the application architecture and agreed good practices.
See linked PR
=> fix: Add payment request adaptor

ui/app/AppLayouts/Communities/popups/TransferOwnershipPopup.qml, ui/app/AppLayouts/Wallet/popups/simpleSend/SimpleSendModal.qml, ui/app/mainui/SendModalHandler.qml
Cherry-pick of https://github.com/status-im/status-desktop/pull/17482/commits
=> [CHERRY-PICK] fix(@desktop/wallet): Fix broken Transfer ownership flow

ui/app/AppLayouts/Wallet/panels/RecipientSelectorPanel.qml, ui/app/AppLayouts/Wallet/popups/simpleSend/SimpleSendModal.qml, ui/app/AppLayouts/Wallet/views/RecipientView.qml, ui/app/mainui/SendModalHandler.qml
Task #17408
* Resolve ens when selected from 1:1 chat
send modal
https://github.com/user-attachments/assets/039244fd-f629-486e-8223-84dd2d155acc
=> fix: Resolve ens from 1:1 chat

ui/StatusQ/CMakeLists.txt, ui/StatusQ/src/typesregistration.cpp
Closes #17476 
Adding an option to build StatusQ as static lib
=> chore: Add static lib option to statusQ

storybook/pages/IntroduceYourselfPopupPage.qml, test/e2e/gui/components/community/create_community_popups.py, test/e2e/gui/components/introduce_yourself_popup.py, test/e2e/gui/main_window.py, test/e2e/gui/objects_map/names.py, test/e2e/gui/screens/community_portal.py, ui/imports/shared/popups/IntroduceYourselfPopup.qml, ui/main.qml
Backport of https://github.com/status-im/status-desktop/pull/17499 to 2.33
Iterates: #17498 
Onboarding/main
=> BACKPORT: fix(Post Onboarding): unbreak showing of `IntroduceYourselfPopup`

src/app/modules/onboarding/module.nim, src/app/modules/onboarding/view.nim, src/app_service/service/keycardV2/dto.nim, storybook/pages/LoginScreenPage.qml, storybook/pages/OnboardingLayoutPage.qml, storybook/pages/UnblockWithPukFlowPage.qml, storybook/qmlTests/tests/tst_OnboardingLayout.qml, ui/StatusQ/src/onboarding/enums.h, ui/app/AppLayouts/Onboarding2/KeycardCreateProfileFlow.qml, ui/app/AppLayouts/Onboarding2/KeycardCreateReplacementFlow.qml, ui/app/AppLayouts/Onboarding2/KeycardFactoryResetFlow.qml, ui/app/AppLayouts/Onboarding2/OnboardingFlow.qml, ui/app/AppLayouts/Onboarding2/OnboardingLayout.qml, ui/app/AppLayouts/Onboarding2/UnblockWithPukFlow.qml, ui/app/AppLayouts/Onboarding2/UnblockWithSeedphraseFlow.qml, ui/app/AppLayouts/Onboarding2/UseRecoveryPhraseFlow.qml, ui/app/AppLayouts/Onboarding2/components/LoginKeycardBox.qml, ui/app/AppLayouts/Onboarding2/pages/ConvertKeycardAccountAcksPage.qml, ui/app/AppLayouts/Onboarding2/pages/KeycardCreatePinDelayedPage.qml, ui/app/AppLayouts/Onboarding2/pages/KeycardIntroPage.qml, ui/app/AppLayouts/Onboarding2/pages/KeycardLostPage.qml, ui/app/AppLayouts/Onboarding2/pages/LoginScreen.qml, ui/app/AppLayouts/Onboarding2/pages/qmldir, ui/app/AppLayouts/Onboarding2/stores/OnboardingStore.qml
Backport of 3 keycard related fixes to the 2.33 release; see the respective PRs for details:
- https://github.com/status-im/status-desktop/pull/17423
- https://github.com/status-im/status-desktop/pull/17435
- https://github.com/status-im/status-desktop/pull/17507
Onboarding/keycard
=> BACKPORT: Fix keycard related flows issues

ui/app/AppLayouts/Communities/popups/TransferOwnershipPopup.qml, ui/app/AppLayouts/Wallet/WalletUtils.qml, ui/app/AppLayouts/Wallet/popups/simpleSend/SimpleSendModal.qml, ui/app/mainui/SendModalHandler.qml
fixes #17456  
There was an issues in which the token data was passed from Ownership popup and Ive fixed that here
Transfer ownership
https://github.com/user-attachments/assets/caf68755-ae67-4ce7-bca4-584a6332a48a
=> fix(@desktop/wallet): Fix broken Transfer ownership flow

ui/app/AppLayouts/Chat/popups/PaymentRequestModal.qml, ui/imports/shared/popups/send/views/AmountToSend.qml
Also fixes switching fiat<->crypto symbol in Payment request modal
Cheery-pick of https://github.com/status-im/status-desktop/pull/17565/
fixes #17497
=> [CHERRY-PICK] fix(@desktop/wallet): Send Modal - Switcher icon's position is incorrect

ui/app/AppLayouts/Wallet/popups/buy/BuyCryptoModal.qml, ui/app/AppLayouts/Wallet/popups/buy/BuyCryptoParamsForm.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapModal.qml
Cherrypick https://github.com/status-im/status-desktop/pull/1743, https://github.com/status-im/status-desktop/pull/17504
and https://github.com/status-im/status-desktop/pull/17505
Fixes https://github.com/status-im/status-desktop/issues/17347, https://github.com/status-im/status-desktop/issues/17471, https://github.com/status-im/status-desktop/issues/17466 and https://github.com/status-im/status-desktop/issues/17474
=> fix: cherrypick release 2.33.x fixes

src/app_service/service/token/service.nim
Presumably closes #17398 
Wallet tokens
=> fix(Wallet): Try extending the string lifetime until `Json.decode` finishes

ci/Jenkinsfile.tests-e2e, test/e2e/configs/__init__.py, test/e2e/gui/objects_map/onboarding_names.py, test/e2e/gui/screens/onboarding.py, test/e2e/tests/communities/test_communities_categories.py, test/e2e/tests/onboarding/test_onboarding_negative_scenarios.py
=> chore(@e2e): some fixes for nightly run

ui/app/AppLayouts/Wallet/popups/simpleSend/SimpleSendModal.qml, ui/app/mainui/SendModalHandler.qml
Cherry-picked commits from PR:
- https://github.com/status-im/status-desktop/pull/17577
=> [Cherry-picked] fix(wallet): reevaluation of a max safe crypto on chain even when it's 0

src/app/modules/main/view.nim
fixes: #17131
https://github.com/user-attachments/assets/c816a3ca-f30b-4a59-b798-394be00b8326
=> fix: ensure signal is emitted on section change

test/e2e/helpers/SettingsHelper.py, test/e2e/requirements.txt, test/e2e/tests/transactions_tests/test_mint_owner_and_tokenmaster_tokens.py, test/e2e/tests/wallet_main_screen/wallet - plus button/test_plus_button_manage_account_added_for_new_generated_seed.py, test/e2e/tests/wallet_main_screen/wallet - plus button/test_plus_button_manage_account_from_private_key.py, test/e2e/tests/wallet_main_screen/wallet - plus button/test_plus_button_manage_account_from_seed_phrase.py, test/e2e/tests/wallet_main_screen/wallet - plus button/test_plus_button_manage_generated_account_custom_derivation_path.py, test/e2e/tests/wallet_main_screen/wallet - right click out of account area/test_right_click_manage_watched_address.py
Minor fixes to failed tests in nightly
=> chore(@e2e): cosmetic fixes for tests

storybook/pages/TradingCenterLayoutPage.qml, storybook/qmlTests/tests/tst_TradingCenterLayout.qml, ui/app/AppLayouts/TradingCenter/TradingCenterLayout.qml, ui/app/AppLayouts/TradingCenter/controls/TradingCenterLoadingTokenDelegate.qml, ui/app/AppLayouts/TradingCenter/controls/TradingCenterTokenDelegate.qml, ui/app/AppLayouts/TradingCenter/controls/TradingCenterTokenHeader.qml, ui/app/AppLayouts/TradingCenter/controls/qmldir, ui/app/AppLayouts/Wallet/WalletUtils.qml, ui/app/mainui/AppMain.qml, ui/imports/shared/controls/TokenDelegate.qml
fixes #17443
Implementing token delegate and dummy list in Trading Center
TradingCenterLayout
https://github.com/user-attachments/assets/ed2ddbb3-41fb-4e74-9929-92c633277685
https://github.com/user-attachments/assets/a63cc816-f3b7-4a75-bd06-98f94359c8fa
Tick **one**:
-->
=> feat(@desktop/wallet): Tokens Table in Trading Center

Makefile, storybook/pages/ChangePasswordViewPage.qml, storybook/pages/NetworkSelectPopupPage.qml, storybook/pages/ProfileDialogViewPage.qml, storybook/pages/StatusFolderDialogPage.qml, storybook/pages/StatusImageCropPanelPage.qml, storybook/qmlTests/main.cpp, storybook/src/Models/CommunitiesModel.qml, storybook/validator_main.cpp
- see the individual commits
Storybook, QmlTests, PagesValidator, Makefile
PagesValidator run:
```
17:22:25: Starting /home/ltinkl/git/status/status-desktop/storybook/build/Desktop_Qt_6_8_3-Debug/bin/PagesValidator...
QML debugging is enabled. Only use this in a safe environment.
>>> StoryBook page verification started; Qt runtime version: 6.8.3 ; built against version: "6.8.3"
>>> StoryBook page verification completed successfully.
17:22:57: /home/ltinkl/git/status/status-desktop/storybook/build/Desktop_Qt_6_8_3-Debug/bin/PagesValidator exited with code 0
```
QmlTests run:
```
❯ ./QmlTests …
```
=> fix(Qt6): fix some SB pages, and running the QmlTest and PagesValidator

ci/Jenkinsfile.macos
Bump status-go to get https://github.com/status-im/status-go/pull/6527
=> chore: bump status-go

storybook/pages/CollectibleDetailViewPage.qml, storybook/pages/ProfileSocialLinksPanelPage.qml, ui/app/AppLayouts/Profile/panels/SupportedTokenListsPanel.qml, ui/app/AppLayouts/Wallet/panels/ManageHiddenPanel.qml, ui/app/AppLayouts/Wallet/views/CollectiblesView.qml, ui/app/AppLayouts/Wallet/views/SavedAddresses.qml, ui/imports/shared/controls/ShapeRectangle.qml, ui/imports/shared/popups/walletconnect/DAppsListPopup.qml, ui/imports/shared/stores/NetworkConnectionStore.qml
- give it an explicit size
Fixes #17783
ShapeRectangle
=> fix(ShapeRectangle): do not freeze the app under Qt6

storybook/pages/ContactsViewPage.qml, storybook/pages/LanguageViewPage.qml, storybook/pages/ProfileSocialLinksPanelPage.qml, storybook/pages/StatusChatListAndCategoriesPage.qml, storybook/pages/StatusChatListItemPage.qml, storybook/pages/SwapSignModalPage.qml, storybook/src/Storybook/FigmaUtils.qml, ui/StatusQ/src/StatusQ/Components/StatusChatList.qml, ui/StatusQ/src/StatusQ/Components/StatusChatListCategoryItem.qml, ui/StatusQ/src/StatusQ/Components/StatusChatListItem.qml, ui/StatusQ/src/StatusQ/Components/StatusDraggableListItem.qml, ui/StatusQ/src/StatusQ/Components/StatusMemberListItem.qml, ui/StatusQ/src/StatusQ/Controls/StatusLinkText.qml, ui/app/AppLayouts/Chat/panels/UserListPanel.qml, ui/app/AppLayouts/Profile/panels/ProfileSocialLinksPanel.qml, ui/app/AppLayouts/Wallet/controls/ManageTokensGroupDelegate.qml, ui/app/AppLayouts/Wallet/panels/ManageHiddenPanel.qml, ui/app/AppLayouts/Wallet/views/CollectiblesView.qml, ui/app/AppLayouts/Wallet/views/LeftTabView.qml, ui/app/AppLayouts/Wallet/views/collectibles/CollectibleView.qml, ui/app/mainui/Popups.qml, ui/imports/utils/Utils.qml
Fixes mouse handling and DND under Qt6 and some other smaller Qt6 related issues; see the respective commits for more details
Fixes #17785
Fixes https://github.com/status-im/status-desktop/issues/17807
Fixes https://github.com/status-im/status-desktop/issues/17810
Fixes https://github.com/status-im/status-desktop/issues/17814
App
https://github.com/user-attachments/assets/95ce2049-14d3-4ca8-b947-dfaac73de778
Chat list:
=> fix(Qt6): Drag'n'drop and some mouse clicks are not working

ui/app/AppLayouts/Wallet/views/AssetsDetailView.qml
Closes #17812 
https://github.com/user-attachments/assets/6d648dc0-dc08-4181-bfc0-f960775faf39
=> fix(wallet): user should be able to click the token contract and copy it

ui/app/AppLayouts/Wallet/popups/swap/SwapModal.qml, ui/imports/shared/popups/send/SendModal.qml, ui/imports/shared/popups/send/views/NetworkSelector.qml
Fixes the spacing in modals
Swap Modal, Bridge Modal
=> Fix/17445: Fix spacing in Swap and Bridge Modal

ui/app/AppLayouts/Communities/controls/CommunityInfoPanel.qml, ui/app/AppLayouts/Communities/controls/qmldir, ui/app/AppLayouts/Communities/views/OwnerTokenWelcomeView.qml
Move inline component to controls lib so it is reusable
=> chore(@qml): make inline component a control

test/e2e/gui/components/wallet/send_popup.py, test/e2e/gui/objects_map/names.py, test/e2e/gui/screens/wallet.py, test/e2e/helpers/wallet_helper.py, test/e2e/tests/transactions_tests/test_mint_owner_and_tokenmaster_tokens.py, test/e2e/tests/transactions_tests/test_wallet_send_eth.py
test to send ETH now can send across L2 networks. I do avoid sending on L1 because of high transaction fee. In addition to that, test for community tokens will be able to use Base Sepolia
=> chore(@e2e): enhance the variety of coverage by selecting random L2 network

ui/app/AppLayouts/Profile/views/PrivacyAndSecurityView.qml
Closes #17848
Just a text update
Privacy and Security screen
=> feat(Privacy&Security): Update text

ui/app/mainui/activitycenter/popups/ActivityCenterPopup.qml
=> feat(news): empty states when there are no News

ui/imports/shared/popups/NewsMessagePopup.qml
=> chore(news): hide the footer in the NewsPopup when there is no link

ui/app/AppLayouts/Wallet/popups/swap/SwapModal.qml
fixes #16806
I think we should stop using this component all over but that's higher risk and better be done in next cycle https://github.com/status-im/status-desktop/issues/17900
SwapModal
https://github.com/user-attachments/assets/7c2d16f5-e1a1-46c0-890d-259828ac64b4
=> fix(@desktop/wallet): Stopped using StatusTextWithLoadingState in SwapModal as it has some issues

storybook/pages/AssetsDetailsHeaderPage.qml, ui/app/AppLayouts/Wallet/views/TokenSelectorAssetDelegate.qml, ui/imports/shared/controls/AssetsDetailsHeader.qml, ui/imports/shared/popups/send/SendModal.qml, ui/imports/shared/popups/send/views/NetworkSelector.qml
fixes #17055, #17909
1. Buy Button launched when interacting with Bridge Modal. This has been fixed generically as I saw it happen with any Modal using the TokenSelector when it aligns with the Buy Button on the Assets Page. 
2. Fixed the broken layout for AssetsDetailsView when the token balances in long
3. Fixed Error box visibility in Bridge Modal, sometimes it wouldnt expand
4. FIxed BridgeModal is minimum window height the header would get hidden previously
Bridge Modal
https://github.com/user-attachments/assets/2e330b48-dd85-4165-881b-7c16a6ee0223
https://github.com/user-attachments/assets/97d5cdaf-4b23-4f7b-87fc-fc3defdca5eb …
=> fix(@desktop/wallet): Small bug fixes for Bridge modal

test/e2e/gui/components/toast_message.py, test/e2e/gui/main_window.py, test/e2e/gui/objects_map/communities_names.py, test/e2e/gui/screens/community_settings.py, test/e2e/tests/communities/test_communities_kick_ban.py, test/e2e/tests/crtitical_tests_prs/test_community_create_edit_share_link.py
get_notifications method is now having try / except wrapper , when outer method wait_for notification handles retries. That allows to wait (retry getting notifications) within specified timeout
only e2e
=> chore(@e2e): improve wait for notification method

test/e2e/gui/screens/messages.py, test/e2e/tests/crtitical_tests_prs/test_messaging_group_chat.py, test/e2e/tests/transactions_tests/test_mint_owner_and_tokenmaster_tokens.py
- extend the list of chains used to mint tokens at
=> chore(@e2e): update minting tokens test to use Status Network chain

src/app/modules/main/wallet_section/send/controller.nim, src/app/modules/main/wallet_section/send/io_interface.nim, src/app/modules/main/wallet_section/send/module.nim, src/app/modules/main/wallet_section/send/view.nim, src/app_service/service/network/service.nim, storybook/pages/SendModalPage.qml, ui/imports/shared/popups/send/SendModal.qml
fixes #17959
Fix the overflow issue in BridgeModal
Bridge Modal
https://github.com/user-attachments/assets/a7851da3-985d-4ce2-a1e9-eb99df966ab2
https://github.com/user-attachments/assets/c22f9fc2-9079-4d8f-8c2d-46d8b7322fa0
=> fix(@desktop/wallet): Bridge - Text overflows the Bridge modal when choosing USDC (EVM) token

src/app/modules/main/wallet_section/networks/controller.nim, src/app/modules/main/wallet_section/networks/io_interface.nim, src/app/modules/main/wallet_section/networks/module.nim, src/app/modules/main/wallet_section/networks/view.nim, src/app_service/service/network/service.nim, ui/app/AppLayouts/Profile/views/WalletView.qml, ui/imports/shared/stores/NetworksStore.qml
Fixes https://github.com/status-im/status-desktop/issues/17760
Fixes setting custom RPC providers for the different chains.
Settings/Wallet/Networks
https://github.com/user-attachments/assets/65417ce2-da7f-47a8-a592-771f68f7f98a
Tick **one**:
-->
=> fix(wallet): fix setting custom rpc providers

storybook/qmlTests/tests/tst_OwnerTokenWelcomeView.qml, ui/StatusQ/src/StatusQ/Components/StatusInfoBoxPanel.qml, ui/app/AppLayouts/Communities/controls/CommunityInfoPanel.qml, ui/app/AppLayouts/Communities/panels/MintTokensSettingsPanel.qml, ui/app/AppLayouts/Communities/views/MintedTokensView.qml, ui/app/AppLayouts/Communities/views/OwnerTokenWelcomeView.qml
add tests for OwnerTokenWelcomeView page
=> tests(@qml): add tests for OwnerTokenWelcomeView page

ui/app/AppLayouts/Wallet/adaptors/TokenSelectorViewAdaptor.qml, ui/app/AppLayouts/Wallet/controls/TokenSelector.qml, ui/app/AppLayouts/Wallet/panels/StickySendModalHeader.qml, ui/app/AppLayouts/Wallet/popups/simpleSend/SimpleSendModal.qml, ui/app/mainui/AppMain.qml
fixes #17920
Fixes and error and default state for SimpleSendModal
SimpleSendModal
https://github.com/user-attachments/assets/e46c35fd-b470-459d-a02b-b79cdef5a351
=> fix(@desktop/wallet): Wallet: Send Modal errors and misbehaviour with  Qt6

src/app_service/common/utils.nim, ui/app/AppLayouts/Communities/helpers/AirdropFeesSubscriber.qml, ui/app/AppLayouts/Communities/views/EditAirdropView.qml
Fixes the issue discovered in https://github.com/status-im/status-desktop/pull/17974#issuecomment-2892375224
Now community tokens can be airdropped again.
https://bscscan.com/tx/0xb3978f6e8251761705e296dca8f337494a9198d0cae6a84f5f5d2087a7972324
=> fix(community): fix token airdrops

storybook/pages/TransactionSettingsPanelPage.qml, ui/app/AppLayouts/Wallet/popups/simpleSend/SendSignModal.qml, ui/app/AppLayouts/Wallet/views/TransactionSettings.qml, ui/app/mainui/SendModalHandler.qml, ui/imports/utils/Constants.qml, ui/imports/utils/Utils.qml
The discussion has run in comment of this PR
https://github.com/status-im/status-desktop/pull/17960
And here are the changes that solve the localization for the transactions settings part.
=> fix(wallet): localization within custom transaction fees panel solved

src/app_service/service/node_configuration/service.nim
Part of #16895
I forgot about this branch I had. I was waiting on some reproduction of the original issue so that I could solve it at the root.
I think we might as well merge this for now, to prevent possible crashes.
@anastasiyaig feel free to test if you can reproduce the original issue on master and this branch.
=> fix(node_config): fix bad error management in the node_config service

ui/app/AppLayouts/Wallet/popups/simpleSend/SimpleSendModal.qml
This fix forces re-evaluation of max amount on assets model count changed
SendModal
https://github.com/user-attachments/assets/4bcf8851-ef3c-40d4-bf03-401b34c99805
=> fix(@desktop/wallet): Fix for max amount not showing updated balance as per account selected.

test/e2e/tests/crtitical_tests_prs/test_community_permissions_add_edit_delete_duplicate.py
=> chore(@e2e): fix typo

ui/app/AppLayouts/Profile/panels/ContactsListPanel.qml
Fixes #18008
[blocked-contact.webm](https://github.com/user-attachments/assets/0189d186-b71e-41c7-943e-c224f86c8dce)
=> fix(contacts): fix remove rejection button showing on blocked users

src/app_service/service/token/service.nim, ui/app/AppLayouts/Wallet/stores/TokensStore.qml, ui/imports/utils/Constants.qml
- https://github.com/status-im/status-desktop/pull/18007
This PR relies on stauts-go release PR:
- https://github.com/status-im/status-go/pull/6611
=> [cherry-pick] chore(wallet): properly update the list of tokens lists after fetching them from remote

ui/app/AppLayouts/Profile/panels/ContactsListPanel.qml
Fixes #18008
Cherry-pick of https://github.com/status-im/status-desktop/pull/18010
=> [CHERRY-PICK] fix(contacts): fix remove rejection button showing on blocked users

CONTRIBUTING.md
1. made several small changes and fixes across the copy
2. re "Please, remember to put your app into Debug mode: Settings >>> Advanced >>> Debug (toggle it on) so the App starts generating logs (in case you need to attach them when reporting bugs)." - I'm not sure if this is correct to add where I added it - if not, please delate this part.
=> Small fixes for CONTRIBUTING.md

ci/Jenkinsfile.tests-e2e
Referenced issue:
* https://github.com/status-im/status-desktop/issues/17640
Points Squish dir to a new 9.0.1 installation.
E2E tests
- [x ] I am familiar with the application architecture and agreed good practices.
=> ci: point squish dir to new 9.0.1 version installation

src/app/modules/shared_modules/collectible_details/events_handler.nim, src/app_service/service/community_tokens/service.nim
Fixes: https://github.com/status-im/status-desktop/issues/18018
status-go PR: https://github.com/status-im/status-go/pull/6627
Fixes a couple collectibles-related bugs:
- Fix crash when community collectible is processed for an address not available in the accounts service.
- Fix collectible metadata updates processing for collectible details module.
=> fix: misc collectibles fixes

storybook/src/Storybook/TestRunnerController.qml
=> fix(@desktop/wallet): [Qt 5->6]: Storybook Pages reports Seg Crash when running Tests for the page

mobile/README.md
Update based on comment https://github.com/status-im/status-desktop/pull/18042#discussion_r2137231126
README
=> chore: Fix mobile build instruction

src/app_service/common/utils.nim, src/app_service/service/eth/utils.nim, src/backend/general.nim
Removes waku service usage leftovers.
None
=> chore: remove waku service usage leftovers

scripts/clean-git.sh, scripts/version.sh
Cherry pick of
https://github.com/status-im/status-desktop/pull/18133
https://github.com/status-im/status-desktop/pull/18132
=> Cherry picks of the dirty flag fix

ui/app/AppLayouts/Profile/views/AdvancedView.qml
Fixes #18176
Settings/Advanced
=> fix: Hide Archive protocol switch (Advanced settings) on mobile

mobile/android/qt5/AndroidManifest.xml, mobile/android/qt6/AndroidManifest.xml
Allow portrait mode on android.
=> fix: Allow portrait mode on android

ui/StatusQ/src/StatusQ/Controls/StatusSeedPhraseInput.qml
=> fix(@desktop/wallet): Fixes only allowing lower case letters in Seed phrase input

Makefile
Updating Makefile in order to allow running status-go with nwaku as a backend.
To do so, the `USE_NWAKU` env variable must be set to true in the following way:  
```
USE_NWAKU=true make
make run
```
Issue:
https://github.com/waku-org/nwaku/issues/3076
=> feat_: support nwaku compilation

storybook/pages/DerivationPathInputPage.qml, ui/imports/shared/popups/addaccount/panels/DerivationPathDisplay.qml, ui/imports/shared/popups/addaccount/stores/AddAccountStore.qml, ui/imports/utils/Constants.qml
=> chore(@desktop/wallet): Remove Ropsten from derivation path when adding a new account

test/e2e/tests/wallet_main_screen/wallet - plus button/test_plus_button_add_watched_address.py, test/e2e/tests/wallet_main_screen/wallet - plus button/test_plus_button_manage_account_added_for_new_generated_seed.py, test/e2e/tests/wallet_main_screen/wallet - plus button/test_plus_button_manage_account_from_private_key.py, test/e2e/tests/wallet_main_screen/wallet - plus button/test_plus_button_manage_generated_account_custom_derivation_path.py
Change the verification for toasts so its not counting the exact number when not needed
=> chore(@e2e): do not check for exact number of toasts when not needed

ui/app/AppLayouts/Profile/popups/RenameKeypairPopup.qml, ui/app/AppLayouts/Profile/views/WalletView.qml
fixes #18316
Rename keypair modal
https://github.com/user-attachments/assets/886fafd0-98a9-496d-b581-39cf82574d96
- 
-
=> fix(@desktop/wallet): Animation for rename keypair modal is abnormally slow

test/e2e/gui/components/wallet/wallet_account_popups.py, test/e2e/gui/main_window.py, test/e2e/gui/screens/settings_wallet.py, test/e2e/tests/crtitical_tests_prs/test_add_delete_account_from_settings.py, test/e2e/tests/settings/settings_wallet/test_wallet_settings_acct_interactions_edit_status_account.py
Closes https://github.com/status-im/status-desktop/issues/18397
=> chore(@e2e): fix editing status account test

test/e2e/gui/components/authenticate_popup.py, test/e2e/gui/components/settings/rename_keypair_popup.py, test/e2e/gui/components/wallet/testnet_mode_popup.py, test/e2e/gui/main_window.py, test/e2e/gui/objects_map/settings_names.py, test/e2e/gui/screens/community_settings_tokens.py, test/e2e/gui/screens/settings_advanced.py, test/e2e/gui/screens/settings_ens_usernames.py, test/e2e/gui/screens/settings_syncing.py, test/e2e/gui/screens/settings_wallet.py, test/e2e/helpers/settings_helper.py, test/e2e/scripts/utils/decorators.py, test/e2e/tests/crtitical_tests_prs/test_onboarding_sync_with_code.py, test/e2e/tests/onboarding/test_onboarding_syncing.py, test/e2e/tests/settings/settings_messaging/test_block_unblock_user.py, ui/app/AppLayouts/Profile/ProfileLayout.qml, ui/imports/shared/views/NoFriendsRectangle.qml
Fix https://github.com/status-im/status-desktop/issues/18426
Fix https://github.com/status-im/status-desktop/issues/18417
Additionally wrapped up a method of checking terms and conditions for ens purchase in attempts (the UI jumps are annoying)
Additionally added decorator for repetitive code in main_window.py
=> chore(@e2e): fix navigation for advanced section

ci/Jenkinsfile.combined, ci/Jenkinsfile.linux, ci/Jenkinsfile.linux-nix, ci/Jenkinsfile.macos, ci/Jenkinsfile.tests-e2e, ci/Jenkinsfile.tests-nim, ci/Jenkinsfile.tests-ui, ci/Jenkinsfile.windows
related issue: https://github.com/status-im/infra-ci/issues/202
=> ci: disable restart from stage in jenkins

src/app/modules/main/module.nim
Used by nimbus/nwaku/etc
Bump nim version
Nim code
Better performance
- 
- 
Low - ie this Nim release has been vetted by other teams already
=> Nim v2.2.4

test/e2e/tests/settings/settings_profile/__init__.py, test/e2e/tests/settings/settings_profile/test_settings_profile_edit.py
Temp disable because of https://github.com/status-im/status-desktop/issues/18462
=> chore(@e2e): temp disable test to edit profile links

storybook/pages/MarketLayoutPage.qml, storybook/qmlTests/tests/tst_MarketFooter.qml, ui/app/AppLayouts/Market/MarketLayout.qml, ui/app/AppLayouts/Market/controls/MarketFooter.qml, ui/app/AppLayouts/Market/controls/MarketTokenDelegate.qml, ui/app/AppLayouts/Market/controls/MarketTokenHeader.qml, ui/app/AppLayouts/Market/controls/Paginator.qml, ui/app/mainui/AppMain.qml, ui/main.qml
fixes #18278
Adapt the Market Layout so that it easily fits into changing app widths
MarketLayout
Storybook:
https://github.com/user-attachments/assets/cea73bfd-bbb7-4777-a558-e1912a017e34
Desktop:
https://github.com/user-attachments/assets/d5a1d3ba-cdf7-467e-a065-68c05f20f485
Android:
iOS:
- 
-
=> fix(@desktop/wallet): Fix broken Market Tab in portrait mode

src/app/modules/main/profile_section/ens_usernames/controller.nim, src/app/modules/main/profile_section/ens_usernames/io_interface.nim, src/app/modules/main/profile_section/ens_usernames/module.nim, src/app/modules/main/profile_section/ens_usernames/view.nim, src/app_service/service/ens/async_tasks.nim, src/app_service/service/ens/service.nim, src/app_service/service/ens/utils.nim, src/app_service/service/transaction/service.nim, src/backend/ens.nim, ui/app/AppLayouts/Profile/ProfileLayout.qml, ui/app/AppLayouts/Profile/stores/EnsUsernamesStore.qml, ui/app/AppLayouts/Profile/views/EnsSearchView.qml, ui/app/AppLayouts/Profile/views/EnsView.qml, ui/app/mainui/AppMain.qml, ui/app/mainui/Handlers/HandlersManager.qml, ui/app/mainui/Handlers/SendModalHandler.qml
fixes #18482
statusgo PR - https://github.com/status-im/status-go/pull/6803
.eth ensName
https://github.com/user-attachments/assets/e1ef3c34-f812-494a-ac14-94931a48f4fe
.stateofus.eth
https://github.com/user-attachments/assets/84eda2ad-664a-4a3e-a1d5-cdbd3324338a
- 
-
=> fix(@desktop/wallet): ENS name ownership not detected

src/app/modules/main/profile_section/ens_usernames/controller.nim, src/app/modules/main/profile_section/ens_usernames/io_interface.nim, src/app/modules/main/profile_section/ens_usernames/module.nim, src/app/modules/main/profile_section/ens_usernames/view.nim, src/app_service/service/ens/async_tasks.nim, src/app_service/service/ens/service.nim, src/app_service/service/ens/utils.nim, src/app_service/service/transaction/service.nim, src/backend/ens.nim, ui/app/AppLayouts/Profile/ProfileLayout.qml, ui/app/AppLayouts/Profile/stores/EnsUsernamesStore.qml, ui/app/AppLayouts/Profile/views/EnsSearchView.qml, ui/app/AppLayouts/Profile/views/EnsView.qml, ui/app/mainui/AppMain.qml, ui/app/mainui/Handlers/HandlersManager.qml, ui/app/mainui/Handlers/SendModalHandler.qml
fixes #18482
cherry-pick of https://github.com/status-im/status-desktop/pull/18506/commits
- 
-
=> [CHERRY-PICK] Fix/connect ens issues

src/app_service/service/accounts/dto/accounts.nim
Fixes #18533
Cherry-pick of https://github.com/status-im/status-desktop/pull/18541
=> fix(backup): fix contact and account images not showing after backup

ci/Jenkinsfile.tests-e2e
Fixes:
```
groovy.lang.MissingPropertyException: No such property:
TEST_SCOPE_FLAG for class: groovy.lang.Binding
```
=> fix(ci): no such property TEST_SCOPE_FLAG

ci/Jenkinsfile.linux, ci/Jenkinsfile.linux-nix, ci/Jenkinsfile.macos, ci/Jenkinsfile.tests-e2e, ci/Jenkinsfile.tests-nim, ci/Jenkinsfile.tests-ui, ci/Jenkinsfile.windows
Should make Mac builds pass reliably instead of being flaky
=> Cherry-pick Mac build fixes

storybook/qmlTests/tests/tst_SwapInputPanel.qml, ui/app/AppLayouts/Wallet/adaptors/TokenSelectorViewAdaptor.qml, ui/app/AppLayouts/Wallet/controls/AssetSelector.qml
and unscrollable issue
fixes #18648
Cherrypick of https://github.com/status-im/status-desktop/pull/18666
- 
-
=> [CHERRY_PICK] fix(@desktop/wallet): Fix the Swap asset selector issue being very slow

src/app/modules/main/module.nim, test/e2e/gui/main_window.py, test/e2e/helpers/settings_helper.py, test/e2e/tests/communities/test_communities_categories.py, test/e2e/tests/communities/test_communities_channels.py, test/e2e/tests/crtitical_tests_prs/test_add_edit_restart_add_delete_generated_account.py, test/e2e/tests/crtitical_tests_prs/test_onboarding_import_seed.py, test/e2e/tests/crtitical_tests_prs/test_onboarding_sync_with_code.py, test/e2e/tests/crtitical_tests_prs/test_settings_password_change_password.py
Cherry-pick of https://github.com/status-im/status-desktop/pull/18672
=> [CHERRY-PICK] Stop showing Home page by default when logging in

src/app/modules/main/profile_section/privacy/controller.nim, src/app/modules/main/profile_section/privacy/io_interface.nim, src/app/modules/main/profile_section/privacy/module.nim, src/app/modules/main/profile_section/privacy/view.nim, src/app_service/common/utils.nim, src/app_service/service/accounts/service.nim, src/app_service/service/privacy/service.nim, src/backend/accounts.nim, src/backend/eth.nim, src/backend/privacy.nim
Requires: 
- https://github.com/status-im/status-go/pull/6870
- https://github.com/status-im/nim-status-go/pull/35
Required for:
- https://github.com/status-im/status-desktop/pull/18716
- https://github.com/status-im/status-go/pull/6846
1. For the `change password` procedure, moved password verification to `status-go`
2. Removed lower-case password hash database migration
3. Removed unused `VerifyAccountPassword` and `VerifyDatabasePassword`
UI-wise the password verification works as before:
=> fix: move password verification to status-go

src/app_service/service/wallet_account/service.nim, src/app_service/service/wallet_account/service_token.nim
cherry-pick https://github.com/status-im/status-desktop/pull/18741
=> fix(collectibles): sync button forces refetchOwnedCollectibles

ui/app/AppLayouts/Profile/views/SyncingView.qml
cherry-pick of https://github.com/status-im/status-desktop/pull/18757
=> [CHERRY-PICK] fix(backup): open import file dialog to current setting

test/e2e/README.md
Slightly update readme in tests
=> chore(@e2e): update readme

test/e2e/gui/components/social_links_popup.py, test/e2e/tests/settings/settings_profile/test_settings_profile_edit.py
Fixes https://github.com/status-im/status-desktop/issues/18462
Tested it here https://ci.status.im/job/status-desktop/job/e2e/job/manual/2788/
=> Tests: fix TextEdit

Makefile, ci/Jenkinsfile.android
Android app will now get all the keys from CI that the linux build gets.
=> ci: build mobile app with secrets

ci/Jenkinsfile.android, ci/Jenkinsfile.combined, ci/Jenkinsfile.linux, ci/Jenkinsfile.tests-e2e, ci/Jenkinsfile.tests-nim, ci/Jenkinsfile.tests-ui, ci/e2e.Dockerfile
Moves all the builds to the container.
CI.
- [x ] I am familiar with the [application architecture](/docs/architecture.md) and agreed good practices.
None
Run the CI
CI fails.
=> feat(ci): Move Linux builds/tests to run in a container

ci/Jenkinsfile.android, ci/Jenkinsfile.combined, ci/Jenkinsfile.linux
Referenced issue:
* https://github.com/status-im/infra-ci/issues/188
=> ci: fix linux and android build pipeline
