status-im/status-desktop

ui/app/AppLayouts/Communities/views/MintedTokensView.qml
PR hide the ManageTokensCommunityTag item in "Community"->Tokens page. Previous changes introduced ManageTokensCommunityTag [12519](https://github.com/status-im/status-desktop/issues/12519) ManageTokensCommunityTag for displaying community icon and name when showing Collectibles in User's Wallet->Collectibles page. However when going to particular Community and checking its "Tokens" there is no need to display that tag, according to the [MintedTokensSettingsPanel](https://github.com/status-im/status-desktop/commit/8a83aba05a6aafa94822ee5225f878fabc5b8fbb#diff-0488295b2d9e9eb20093f3f473b5d483c1f9d33499a47c6e72637f05e06a6db1R182) PR: [11347](https://github.com/status-im/status-desktop/pull/11347)
Wallet
Communities
- [x ] test changes in both light and dark theme?
In Wallet -> Collectibles, …
=> fix(TokenUI): Hide explicitly ManageTokensCommunityTag in community settings page

src/app/global/feature_flags.nim, ui/app/AppLayouts/Wallet/panels/WalletFooter.qml
fixes #14627
Added a feature flag behind which we will hide all swap related code on desktop client
simply export FLAG_SWAP_ENABLED=1 in order to see the swap functionality on desktop
NA
=> feat(@desktop/wallet): Add Swap Feature Flag

src/app/core/signals/remote_signals/community.nim, src/app/core/signals/remote_signals/signal_type.nim, src/app/core/signals/signals_manager.nim, src/app/modules/main/chat_section/controller.nim, src/app/modules/main/chat_section/io_interface.nim, src/app/modules/main/chat_section/module.nim, src/app/modules/main/chat_section/view.nim, src/app_service/service/community/service.nim, ui/app/AppLayouts/Chat/panels/UserListPanel.qml, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Chat/views/ChatView.qml, ui/imports/utils/Constants.qml
Fixes #14378
This is only for the control node. We can improve the UI later
status-go PR: https://github.com/status-im/status-go/pull/5120
[reevaluation-message.webm](https://github.com/status-im/status-desktop/assets/11926403/c6d2d88e-56b2-42cc-8f8c-c35eff4e8832)
=> feat(community): show a message when the member reevaluation is ongoing

storybook/pages/CreateChannelPopupPage.qml, ui/app/AppLayouts/Communities/controls/ColorPicker.qml, ui/app/AppLayouts/Communities/models/ChannelPermissionsModelEditor.qml, ui/app/AppLayouts/Communities/popups/CreateChannelPopup.qml
- if there's a valid community info and the color is non-empty, inherit it when creating a new channel
- also fix the color picker button height
- adjust the SB page with separate "create" and "edit" options
Fixes #14570
CreateChannelPopup
[Záznam obrazovky z 2024-05-03 17-54-29.webm](https://github.com/status-im/status-desktop/assets/5377645/c60ae215-b725-4864-ab65-f83032e69ae3)
=> feat(CreateChannelPopup): inherit the channel color from community color

Makefile
This would allow us to create non-prod builds in CI.
=> chore(ci): allow overriding PRODUCTION_PARAMETERS

ui/app/AppLayouts/Communities/panels/OverviewSettingsFooter.qml, ui/app/AppLayouts/Communities/panels/OverviewSettingsPanel.qml
This PR mitigates permission stuck in pending state upon making device a control node. It fixes
[#14023](https://github.com/status-im/status-desktop/issues/14023) by applying events and publishing community events once the device is promoted to control node.
Related to https://github.com/status-im/status-go/pull/5070
- NA
Performing tests to gather evidence for resolution.
=> fix: Permission created before making device a control node is not getting active

ui/StatusQ/include/StatusQ/submodelproxymodel.h, ui/StatusQ/src/submodelproxymodel.cpp, ui/StatusQ/tests/tst_SubmodelProxyModel.cpp
- fixes the problem observed in `SharedAddressesAccountSelector`
- add many new tests to cover fixed problem and other corner cases
Closes: #14650
`SubmodelProxyModel`
=> fix(SubmodelProxyModel): model reset emitted properly when roles change

ui/imports/shared/controls/chat/LinkPreviewCard.qml
Fixes: [13379](https://github.com/status-im/status-desktop/issues/13379)
According to the descripbtion in [13379](https://github.com/status-im/status-desktop/issues/13379) and [Figma: Exploring the application of OG aspect ratio image crops for unfurls ](https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?type=design&mode=design&t=43aRj8DnMnKLb37q-0) aspect ratios of unfurled images should be 1.91:1 (324px x 170px)
Chat: LinkPreviewCard.qml
Using GammaRay to check the actual size of the Image control containing unfurled image indeed shows that the new width is 324px:
figma design:
=> fix: Messages: Change unfurl image crop aspect ratio to align with Open Graph

src/app/modules/main/profile_section/devices/module.nim
Closes #11908
When user cancels or closes KeycardPopup.qml, it will be 'Rejected'. Appropriate state will be signaled up to the interested objects.
ProfileLayout.qml reacts to the 'Rejected' / 'Accepted' state by discarding any error messages from the nim layer.
ProfileLayout.qml, KeycardPopup.qml, SyncingView.qml
- [x ] I've checked the design and this PR matches it (No designs for cancel/discard/X of Sync Device flow)
=> fix(Syncing): cancelling syncing flow should not result in error dialog

ui/StatusQ/include/StatusQ/aggregator.h, ui/StatusQ/src/aggregator.cpp, ui/StatusQ/tests/src/TestHelpers/testmodel.cpp, ui/StatusQ/tests/src/TestHelpers/testmodel.h, ui/StatusQ/tests/tst_Aggregator.cpp
- adds handling for special case where there are rows removed between `layoutAboutToBeChanged`/`layoutChanged` signals
- proper unit test added, existing unit tests extended
- minor code style alignments
Similar special handling had to be applied to `ConcatModel`: https://github.com/status-im/status-desktop/pull/14368
Closes: #14554
`StatusQ/Aggregator`
[Screencast from 06.05.2024 12:53:51.webm](https://github.com/status-im/status-desktop/assets/20650004/4e9c2d6c-640a-4ab2-acac-f145052bf5b5)
=> fix(StatusQ/Aggregator): Proper recalculation on layout change removing rows

storybook/pages/FunctionAggregatorPage.qml, storybook/src/Storybook/GenericListView.qml, ui/StatusQ/CMakeLists.txt, ui/StatusQ/include/StatusQ/functionaggregator.h, ui/StatusQ/src/functionaggregator.cpp, ui/StatusQ/src/plugin.cpp, ui/StatusQ/tests/CMakeLists.txt, ui/StatusQ/tests/tst_FunctionAggregator.cpp
- provides `FunctionAggregator` component for easy aggregation of single model's role according to provided function and initial value
- unit tests
- Storybook page presenting several possible usages, also using `AmountsAritmetic`
Closes: #14617
`StatusQ`
[Screencast from 07.05.2024 16:25:53.webm](https://github.com/status-im/status-desktop/assets/20650004/78d11a4a-161c-4f8a-9864-cdd17c28d0d4)
=> feat(StatusQ): General purpose js function-based aggregator

storybook/pages/LoginViewPage.qml, storybook/pages/ProfileDialogViewPage.qml, storybook/src/Models/UsersModel.qml, ui/StatusQ/src/StatusQ/Components/StatusMemberListItem.qml, ui/StatusQ/src/StatusQ/Components/StatusMessageHeader.qml, ui/StatusQ/src/StatusQ/Core/Utils/Emoji.qml, ui/app/AppLayouts/Chat/panels/UserListPanel.qml, ui/app/AppLayouts/Onboarding/panels/AccountMenuItemPanel.qml, ui/app/AppLayouts/Onboarding/views/LoginView.qml, ui/imports/shared/popups/CommonContactDialog.qml, ui/imports/shared/views/ProfileDialogView.qml, ui/imports/shared/views/chat/ProfileContextMenu.qml
- run the user's display name (ENS name) thru the `Emoji.parse()` function as that will convert the potentially UTF-16 encoded name containing emojis into an image
Fixes #12290
Profile Dialog, User List, Profile context menu
Profile dialog (with user list on the right):
Secondary profile dialog:
Context menu and chat header:
Login view:
=> fix: ENS keycap display issues

storybook/pages/CommunitiesPortalDummyModel.qml, storybook/pages/CommunitiesPortalLayoutPage.qml, storybook/src/Models/PermissionsModel.qml, ui/StatusQ/include/StatusQ/permissionutilsinternal.h, ui/StatusQ/src/permissionutilsinternal.cpp, ui/app/AppLayouts/Communities/CommunitiesPortalLayout.qml, ui/app/AppLayouts/Communities/helpers/PermissionsHelpers.qml, ui/app/AppLayouts/Communities/views/CommunitiesGridView.qml
- hide the permissions row and tokens when the community is free to join
- fix evaluating the `requirementsMet` property which affects the lock icon state (that role was never part of the model) -> the lock icon is now correctly opened/closed based on whether we are eligible to join or not
- add a helper C++ method `isTokenGatedCommunity`
- adjust the SB models, adding different variations of the permissionsModel for the CommunitiesPortalLayoutPage
Fixes #14671
Community Portal
Community Portal with Status CC (free to join):
CommunitiesPortalLayout in SB with different permissions models:
=> fix(CommunityPortal): don't show PermissionsRow for free communities

ui/app/AppLayouts/Profile/views/AppearanceView.qml, ui/main.qml, vendor/DOtherSide/lib/src/DOtherSide.cpp
- as discussed with Design, do not allow the user to select the UI scale option from Settings as it causes many problems; instead rely on the OS/Qt HighDPI support to handle the scaling for us
- note however, for advanced users, it's still possible to specify the UI scale manually by exporting the standard `QT_SCALE_FACTOR` prior to starting the app
- in the longterm, we will come with our own scaling solution at the QML level, independent from the OS
Fixes #14137
Settings/Appearance
=> feat(Settings): remove UI scaling option panel

src/app/modules/startup/internal/biometrics_state.nim, src/app/modules/startup/internal/keycard_enter_pin_state.nim, src/app/modules/startup/internal/keycard_pin_set_state.nim, src/app/modules/startup/internal/keycard_wrong_puk_state.nim
Handling for recovering Status profile for Linux updated since we don't use biometrics for Linux and that requires slightly different flow.
Closes: #14673
=> fix(keycard): unable to import account from keycard

storybook/pages/ProfileShowcaseAccountsPanelPage.qml, storybook/pages/ProfileShowcaseCollectiblesPanelPage.qml, ui/app/AppLayouts/Profile/helpers/ProfileShowcaseDirtyState.qml, ui/app/AppLayouts/Profile/helpers/ProfileShowcaseModels.qml, ui/app/AppLayouts/Profile/helpers/VisibilityAndPositionDirtyStateModel.qml, ui/app/AppLayouts/Profile/panels/ProfileShowcaseAccountsPanel.qml, ui/app/AppLayouts/Profile/panels/ProfileShowcaseCollectiblesPanel.qml, ui/app/AppLayouts/Profile/panels/ProfileShowcaseCommunitiesPanel.qml, ui/app/AppLayouts/Profile/panels/ProfileShowcasePanel.qml, ui/app/AppLayouts/Profile/views/MyProfileView.qml
closes #13682
closes #14040
Changes:
1. Move the searcher SFPM in the ProfileShowcasePanel along with the MovableModel
2. Compute the indexes involved in the position change for all proxy layers
3. Fully implement changePosition in `VisibilityAndPositionDirtyStateModel.qml`
4. Fix storybook pages
https://github.com/status-im/status-desktop/assets/47811206/364bb73e-3267-4f2d-aac5-7016c12d312d
=> feat(ProfileShowcase): Implement custom showcase position when searcher text is filtering items

src/app/core/signals/remote_signals/community.nim, src/app/core/signals/remote_signals/signal_type.nim, src/app/core/signals/signals_manager.nim, src/app/modules/main/communities/tokens/controller.nim, src/app/modules/main/communities/tokens/module.nim, src/app_service/service/community_tokens/async_tasks.nim, src/app_service/service/community_tokens/dto/community_token.nim, src/app_service/service/community_tokens/dto/deployment_parameters.nim, src/app_service/service/community_tokens/service.nim, src/backend/community_tokens.nim
Move community tokens logic to status-go.
Nim part is only responsible for catching the signal about handled transaction and update UI.
Added CommunityTokenTransactionStatusChangedSignal.
Issue https://github.com/status-im/status-go/issues/4351
status-go [pr](https://github.com/status-im/status-go/pull/4953)
=> 4351 community token refactoring

src/app_service/service/node_configuration/service.nim, src/backend/node_config.nim
fixes #14643
(see more details in the ticket)
using a separate method to change log level
settings, community archive protocol
https://github.com/status-im/status-desktop/assets/1083341/864abc05-3b00-42c7-905e-fc1a5329fcaf
* The `saveConfiguration` method overwrites NodeConfig fields it doesn't know about. It will lead to a crash if archive protocol is enabled. Replace all usages of this method and make the corresponding methods rewrite only updated fields (see `SetLogLevel, enableCommunityHistoryArchiveSupport`):
* saveNewWakuNode
* setV2LightMode
* setNimbusProxyConfig
* setMaxLogBackups
https://github.com/status-im/status-desktop/issues/12918
* Validate NodeConfig before writing to the database. Fix validation issues when APIModules and KeycardPairingDataFile are missing. Add …
=> Fix(settings): crash when enabling history archive and disabling logs

src/app_service/common/conversion.nim, src/app_service/service/community_tokens/async_tasks.nim, src/app_service/service/community_tokens/service.nim, src/app_service/service/ens/utils.nim
All fees (suggested fees, l1 fee, gas units) are computed in 1 status-go call. 
Suggested fees contains correct l1 fee.
We display the cost with included l1 fee.
Related status-go [pr](https://github.com/status-im/status-go/pull/5071)
=> 14166 add l1 fees

ui/app/AppLayouts/Chat/ChatLayout.qml, ui/app/AppLayouts/Chat/views/ChatView.qml
When channel has view-only permission not requiring any holdings, the channel is not encrypted and should be presented to non-members in read-only mode.
There is additional flag introduced `hasUnrestrictedViewOnlyPermission` reflecting described condition. If `true`, the channel overlay is not presented.
Closes: #14439
`ChatLayout`
[Screencast from 17.05.2024 11:53:34.webm](https://github.com/status-im/status-desktop/assets/20650004/cd60375f-c947-413f-9501-8e8193f72a92)
=> fix(Communities): Show channel for non-members when read-only, tokenless permission is set

ui/imports/shared/status/StatusEmojiPopup.qml
Issue #14744
fix the emoji color selector animation is out of bounds
StatusEmojiPopup
[Mdias 2024-05-17.16-20.webm](https://github.com/status-im/status-desktop/assets/8908607/208be58b-6188-4f09-876a-01a21b4fb13b)
=> fix: The emoji color selector animation is out of bounds

src/app/modules/main/chat_section/controller.nim, src/app/modules/main/chat_section/io_interface.nim, src/app/modules/main/chat_section/module.nim, src/app/modules/main/controller.nim, src/app/modules/main/module.nim, src/app_service/service/chat/service.nim, src/app_service/service/community/service.nim
Fixes #14816
The muted property on the community was never checked anywhere. I don't know how it ever worked, but oh well.
I also made it so that when the mute property on the community changes, the badge gets re-evaluated.
[muted-community.webm](https://github.com/status-im/status-desktop/assets/11926403/c9231d98-f2f1-472a-ad2a-29cf2695cd9a)
=> fix(mute): fix muted community still sending notifs and having a badge

ui/StatusQ/src/StatusQ/Components/StatusLetterIdenticon.qml, ui/StatusQ/src/StatusQ/Components/StatusSmartIdenticon.qml, ui/StatusQ/src/StatusQ/Controls/StatusIconTabButton.qml, ui/StatusQ/src/StatusQ/Controls/StatusNavBarTabButton.qml, ui/StatusQ/src/StatusQ/Core/StatusAssetSettings.qml, ui/app/AppLayouts/Onboarding/views/ProfileChatKeyView.qml, ui/app/AppLayouts/Wallet/controls/SavedAddressesDelegate.qml, ui/app/AppLayouts/Wallet/popups/AddEditSavedAddressPopup.qml, ui/app/AppLayouts/Wallet/popups/ReceiveModal.qml, ui/app/AppLayouts/Wallet/popups/RemoveSavedAddressPopup.qml, ui/app/mainui/AppMain.qml, ui/imports/shared/controls/chat/UserImage.qml
Changes in `StatusLetterIdenticon`:
- in `useAcronymForLetterIdenticon` the following letters generation rules are used, `charactersLength` property is ignored:
```
John -> J
John Smith -> JS
John Smith Junior -> JS
```
- `useAcronymForLetterIdenticon` is no longer causing background semi-transparent. Semi-transparent background can be enabled by setting `backgroundWithAlpha` to `true` (`false` by default)
- `useAcronymForLetterIdenticon` is `true` by default
- adjust usages of `StatusSmartIdenticon`
`StatusLetterIdenticon`, `StatusSmartIdenticon` and some components using `StatusSmartIdenticon`
=> StatusLetterIdenticon: Aligning avatar initials display with mobile

ui/app/AppLayouts/Profile/popups/AddSocialLinkModal.qml, ui/imports/shared/controls/chat/LinkPreviewSettingsCard.qml
Add object names for links preview popup elements and add button (social links popup)
ui/app/AppLayouts/Profile/popups/AddSocialLinkModal.qml
ui/imports/shared/controls/chat/LinkPreviewSettingsCard.qml
=> chore: add object names for links preview and add button

src/app/modules/main/chat_section/controller.nim, src/app/modules/main/communities/controller.nim, src/app/modules/main/communities/module.nim, src/app_service/service/chat/async_tasks.nim, src/app_service/service/chat/service.nim, src/app_service/service/community/async_tasks.nim, src/app_service/service/community/service.nim, src/backend/communities.nim
Light functions are used first in order to reduce the number of calls to blockchain.
If the permission is not met (user is not a member of community/channel member list), then normal permissions-check function is used.
status-go [pr](https://github.com/status-im/status-go/pull/5168)
Issue #14220
https://github.com/status-im/status-desktop/assets/61889657/c5d6e409-d331-4aba-9d9c-b4e44f896089
=> 14220 check permissions light mode

fleets.json, src/app/core/fleets/fleet_configuration.nim, src/app_service/service/node_configuration/service.nim, src/app_service/service/settings/dto/settings.nim, src/app_service/service/settings/service.nim, ui/app/AppLayouts/Profile/popups/FleetsModal.qml, ui/imports/utils/Constants.qml
Adds the shards.test fleet
Requires
- https://github.com/status-im/status-go/pull/5160
=> feat: shards.staging fleet

ui/app/AppLayouts/Wallet/services/dapps/WalletConnectService.qml
Updates: #14754
Note that this PR just adds the simple toast notifications. I'm postponing the notification center implementation for later due to low priority.
=> feat(dapps) add toast notifications for Wallet Connect paring

ui/app/AppLayouts/Communities/panels/SharedAddressesPanel.qml
closes #14195
The `hasPermissions` flag has an impact in how the popup height is calculated. When the permissionsModel has only hidden permissions, the `hasPermissions` flag is true, but UI wise there's no permission to display.
Fix: Account for hidden permissions when computing `hasPermissions` flag
Join community flow
https://github.com/status-im/status-desktop/assets/47811206/1490ab8c-248f-4c40-a56b-ab10b6eaa677
=> fix: Fixing the share addresses popup height when only owner and TM permissions are available

src/app/modules/main/browser_section/bookmark/model.nim, src/app/modules/main/browser_section/dapps/dapps.nim, src/app/modules/main/stickers/models/sticker_pack_list.nim, src/app/modules/main/wallet_section/activity/collectibles_model.nim, src/app/modules/main/wallet_section/networks/model.nim, src/app/modules/main/wallet_section/saved_addresses/model.nim, src/app/modules/shared_models/collectibles_model.nim, src/app/modules/shared_models/collectibles_nested_model.nim, storybook/pages/NetworkSelectPopupPage.qml, storybook/src/Models/NetworksModel.qml, ui/StatusQ/src/StatusQ/Controls/StatusAccountSelector.qml, ui/StatusQ/src/StatusQ/Core/Utils/Utils.qml, ui/app/AppLayouts/Browser/BrowserLayout.qml, ui/app/AppLayouts/Browser/popups/BrowserWalletMenu.qml, ui/app/AppLayouts/Browser/stores/BookmarksStore.qml, ui/app/AppLayouts/Wallet/stores/RootStore.qml, ui/app/AppLayouts/stores/CloneModel.qml, ui/app/mainui/AppMain.qml, ui/imports/shared/status/StatusStickerPackClickPopup.qml, ui/imports/shared/views/AssetsView.qml, ui/imports/utils/Utils.qml
- Some NIM's models define additional (not part of the QAbstractModelItem API) method rowData to allow access to model's data on UI side
- The same job can be done relying fully on public QAbstractModelItem API using ModelUtils utility. It gives full transparency if we need nim's model or other like ListModel replacement in tests/storybook
Fixes #14805
Models
=> chore: Remove custom `rowData()` method from NIM's models

ui/app/AppLayouts/Onboarding/views/LoginView.qml
Closes #13046 
Moving to regular login whenever the biometric login fails
Onboarding login flow
https://github.com/status-im/status-desktop/assets/47811206/ffb4827e-3381-48ae-a140-b4a54688c610
=> fix(BiometricLogin): Move to regular login page when biometric login fails with error

src/app/modules/main/module.nim, src/app/modules/shared_models/link_preview_model.nim, src/app_service/service/shared_urls/dto/url_data.nim, src/app_service/service/shared_urls/service.nim, ui/imports/shared/views/chat/MessageView.qml
Fixes #14844
The problem was that links to status.app that are not shared links were still considered shared urls, because our util function can only check if it contains `status.app`.
The solution is two fold:
1. If there are Link Previews, I ask the link preview for the type of Link. If it's a normal link, I just open it.
2. If there are no Link Preview for that link, we call `parseSharedUrl` as before, but now we handle the failure by opening in the browser because we can assume that it's a normal link.
=> fix(links): open status links in the browser when not shared urls

ui/imports/shared/controls/chat/LinkPreviewCard.qml, ui/imports/shared/controls/chat/LinkPreviewMiniCard.qml, ui/imports/shared/controls/chat/LinkPreviewSettingsCard.qml
Add object names for titles, subtitles of link preview bubbles, link preview area (also emojihash)
ui/imports/shared/controls/chat/LinkPreviewCard.qml
ui/imports/shared/controls/chat/LinkPreviewMiniCard.qml
ui/imports/shared/controls/chat/LinkPreviewSettingsCard.qml
=> More object names added for link previews elements

src/app/modules/main/chat_section/chat_content/users/controller.nim
Close #14442
Waits https://github.com/status-im/status-go/pull/5190
Temporary workaround for showing members for a new channels (and in a few more rare cases)
Should be refactored in https://github.com/status-im/status-desktop/issues/14219
Chats, Communities
https://github.com/status-im/status-desktop/assets/2522130/dfac425a-afed-49ca-b5a5-bbe2ceff12bb
=> fix: correct member list for new community channels

storybook/pages/ErrorTagPage.qml, storybook/qmlTests/tests/tst_ErrorTag.qml, ui/StatusQ/src/StatusQ/Components/LoadingComponent.qml, ui/StatusQ/src/StatusQ/Components/StatusSmartIdenticon.qml, ui/imports/shared/controls/ErrorTag.qml, ui/imports/shared/controls/InformationTag.qml, ui/imports/shared/controls/qmldir
- created a new component (`ErrorTag`) based on the existing `InformationTag`, suitable for displaying a row of icon (optional), text and (optional) button in red/danger color
- add ErrorTagPage.qml to StoryBook
- add some basic QML tests
- InformationTag: make more properties customizable, use the same `bgRadius` consistently
- StatusSmartIdenticon: some fixes for the MouseArea hover/click behavior
Fixes #14792
ErrorTag
=> feat: [UI - Swap] Create tag error component

storybook/pages/AirdropsSettingsPanelPage.qml, storybook/pages/HoldingsDropdownPage.qml, storybook/pages/TokenPanelPage.qml, ui/app/AppLayouts/Communities/controls/InlineNetworksComboBox.qml, ui/app/AppLayouts/Communities/controls/TokenPanel.qml, ui/app/AppLayouts/Communities/popups/HoldingsDropdown.qml, ui/imports/shared/controls/AmountInput.qml, ui/imports/shared/controls/Input.qml
Fixes #11918
1) HoldingsDropdown.qml - add "decimal" to assetPanel ListModel
2) InlineNetworksComboBox.qml - propogate "decimal" from the model  
3) TokenPanel.qml - propogate "decimal" from to AmountInput
4) AmountInput.qml - validate number of digits in franctional part of entered amount
Community/Airdrop
<kbd>
=> fix(airdrop): fix decimals validation

config.nims
In more recent versions of ubuntu, the version of ssl used is 3.0
Trying to compile desktop with -lcrypto and -lssl by default will end up causing the build process to fail with:
```
/usr/bin/ld: nimcache/release/nim_status_client/@m..@svendor@snimbus-build-system@svendor@sNim@slib@spure@snet.nim.c.o: in function `checkCertName__pureZnet_1309':
/home/richard/status/status-desktop/vendor/nimbus-build-system/vendor/Nim/lib/pure/net.nim:831: undefined reference to `SSL_get_peer_certificate'
collect2: error: ld returned 1 exit status
```
With this PR at least we are being explicit that we're using a version of libssl that has reached its end of life since 11th September 2023
https://www.openssl.org/blog/blog/2023/03/28/1.1.1-EOL/index.html
*le sigh*
newer versions should use the openssl v3, …
=> fix?: use libssl 1.1

ui/app/AppLayouts/Wallet/views/AssetsDetailView.qml
Add object names for market data fields
ui/app/AppLayouts/Wallet/views/AssetsDetailView.qml
=> chore: add object names market data fields

ui/app/AppLayouts/Wallet/panels/WalletHeader.qml
"All Accounts" -> "All accounts" in main wallet view
Fixes #14669
Wallet
=> fix(Wallet): "All accounts" title casing typo

fleets.json, libs/Onboarding/src/Onboarding/Common/Constants.h, resources/fleets_cpp.json, src/app/core/fleets/fleet_configuration.nim, src/app_service/service/node_configuration/service.nim, src/app_service/service/settings/dto/settings.nim, src/app_service/service/settings/service.nim, ui/app/AppLayouts/Profile/popups/FleetsModal.qml, ui/imports/utils/Constants.qml
See status-im/infra-nim-waku#91 for details
Mostly done automatically. Some parts manually.
=> chore: switch wakuv2 fleet to waku

ui/app/AppLayouts/Communities/panels/SortableTokenHoldersPanel.qml, ui/app/AppLayouts/Communities/panels/TokenHoldersPanel.qml, ui/i18n/qml_base.ts
Rename a string to match the general pattern across the application
=> chore: rename holders string to match the general in app approach

ui/app/AppLayouts/Communities/popups/HoldingsDropdown.qml
When creating or editing a community permission, if you add a holding token that has already been added, the amount value displayed is in basic units (long value) of that token instead of primary units.
This PR fixes that
Fixes [#14919](https://github.com/status-im/status-desktop/issues/14919)
Community | Permissions | Assets Holding
https://github.com/status-im/status-desktop/assets/8908607/c6276c45-b5cd-49eb-a022-af8c63391166
=> Fix asset value in HoldingsDropdown when adding an asset to permissions

ui/app/AppLayouts/Profile/panels/ProfileDescriptionPanel.qml
In ProfileDescriptionPanel.qml in bioInput component separated charLimit and input.maximumLength, so StatusInput was left intact. This made bio input to behave on desktop similarly to mobile clients
ProfileDescriptionPanel.qml 
https://github.com/status-im/status-desktop/assets/5157464/8d7b8939-0955-4a73-8620-d13cd060737e
=> 14879 error message is misleading when pasting bio longer than 240 chars

storybook/pages/ProfileDialogViewPage.qml, ui/imports/shared/views/ProfileDialogView.qml, ui/imports/shared/views/chat/ProfileContextMenu.qml
Cherry-pick of https://github.com/status-im/status-desktop/pull/14968 to master
- temporarily disable all ID verification flows by default for 2.29
- enabled it in StoryBook for testing purposes
Fixes #14954
ProfileDialogView, ProfileContextMenu
=> CHERRY-PICK-MASTER: fix: Hide ID verification buttons

ci/Dockerfile, ci/Jenkinsfile.linux, ci/Jenkinsfile.macos, ci/Jenkinsfile.windows, scripts/windows_build_setup.ps1, shell.nix
- updates status-go reference to build from the branch where we bump go to 1.21 
- https://github.com/status-im/status-go/pull/5216
Could be many areas since go upgrades impact every feature that communicates with status-go
=> Upgrade go to 1.21

ui/app/AppLayouts/Communities/views/PermissionsView.qml
Unfork of https://github.com/status-im/status-desktop/pull/14917 to run the CI on the changes
PR by @marcioatdias 
Fixed an issue where communityDetails were not being updated in PermissionsView. This issue was causing the name, color, and image not to update correctly.
=> fix: ensure communityDetails are updated in PermissionsView

src/app/modules/main/chat_section/module.nim, src/app_service/service/community/dto/community.nim, src/app_service/service/community/service.nim, ui/app/AppLayouts/Communities/views/CommunityColumnView.qml
Close #14915
Communities
(with disabled send)
https://github.com/status-im/status-desktop/assets/2522130/bb3ab022-dbf1-4b24-a03d-d1fbfcc71d9d
https://github.com/status-im/status-desktop/assets/2522130/5e599036-c9e1-4324-9f52-65657a928ca2
P.S: expected result - https://github.com/status-im/status-desktop/issues/14978
=> fix(communities): Correct handling 'hide channel from certain members'

ui/app/AppLayouts/Communities/controls/TokenItem.qml, ui/app/AppLayouts/Communities/controls/TokenPanel.qml, ui/app/AppLayouts/Communities/helpers/PermissionsHelpers.qml, ui/app/AppLayouts/Communities/popups/HoldingsDropdown.qml
(Edit Permissions)
If `asset.chainName` is empty, HoldingsDropdown doesn't initialize "decimals" for AmountInput
Fixes #14942
Use `assetsModel.decimals` when `TokenPanel.networksModel` is not intialized
Communities
(!) testing in progress
```mermaid
%% Flowchart
graph LR
subgraph AmountInput 
AmountTokenDecimals[tokenDecimals]
end
subgraph TokenPanel
TokentokenDecimals[tokenDecimals]
TokenDecimals[decimals]
TokenNetworksModel[networksModel]
TokenItem[item]
networksComboBoxLoader
TokentokenDecimals --> TokenItem
networksComboBoxLoader --> TokenNetworksModel
end
subgraph HoldingsDropdown
assetsModel[(assetsModel)]
AssetsTokenPanel[TokenPanel]
end 
AmountTokenDecimals -->|init| networksComboBoxLoader
AmountTokenDecimals --> TokentokenDecimals
TokenNetworksModel -->|chainName?| assetsModel …
```
=> fix(permissions): Communities: HoldingsDropdown doesn't allow decimal input

ui/imports/shared/views/ProfileDialogView.qml
- do not fully deactivate the secondary button slot/loader as it's also used by the Share button
Fixes #14995
=> fix(ProfileDialogView): Share your own profile button is missing

src/app/modules/main/chat_section/module.nim
Leftover after https://github.com/status-im/status-desktop/pull/14977
Fresh created channel will have valid canView and canPost before handling the community description
Communities
=> hotfix: use canPost and canView from chat in case of a new channel

src/app/core/signals/remote_signals/community.nim, src/app/core/signals/remote_signals/signal_type.nim, src/app/core/signals/signals_manager.nim, src/app/modules/main/controller.nim, src/app_service/common/conversion.nim, src/app_service/service/community_tokens/service.nim
Handle signal with information about token actions made by other owner/tokenmaster and update UI accordingly.
status-go [pr](https://github.com/status-im/status-go/pull/5243)
Issue #13371 
All 3 operations were tested: airdrop, burn and remote destruct.
Airdrop/remote destruct - the list of holders is refreshed.
Burn - token supply is changed.
=> 13371 propagate token actions

src/app/modules/main/chat_section/chat_content/io_interface.nim, src/app/modules/main/chat_section/chat_content/module.nim, src/app/modules/main/chat_section/chat_content/view.nim, src/app/modules/main/chat_section/controller.nim, src/app/modules/main/chat_section/item.nim, src/app/modules/main/chat_section/model.nim, src/app/modules/main/chat_section/module.nim, src/app/modules/main/communities/controller.nim, src/app/modules/main/communities/module.nim, src/app_service/service/chat/async_tasks.nim, src/app_service/service/chat/service.nim, src/app_service/service/community/async_tasks.nim, src/app_service/service/community/service.nim, src/backend/communities.nim, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Chat/views/ChatColumnView.qml, ui/app/AppLayouts/Chat/views/ChatView.qml
Fixes #14983
status-go PR: https://github.com/status-im/status-go/pull/5267
We had the issue of checking actual permissions for a lot of things. That is a problem because it can be untrue information if the control node hadn't run the re-evaluation yet, plus it was slower.
The solution here is to rely on communityChat's `canPost` and `canView` as well as Community's `joined`. Those properties are computed by the control node itself, so they will always be accurate to the real state.
[refactor-perms.webm](https://github.com/status-im/status-desktop/assets/11926403/eb8f1d78-15a3-465b-9d76-aed86779928e)
**Known issue:** As seen in the video, when the owner adds a permission that would grant us access to a channel, the UI will still show that we do not meet the requirements, with the token we …
=> refactor: rely on canPost and canView instead of checking permissions

src/app/modules/main/wallet_section/buy_sell_crypto/item.nim, src/app/modules/main/wallet_section/buy_sell_crypto/model.nim, src/app/modules/main/wallet_section/buy_sell_crypto/module.nim, src/app_service/service/transaction/cryptoRampDto.nim, storybook/qmlTests/tests/tst_BuyCryptoModal.qml, storybook/src/Models/OnRampProvidersModel.qml, ui/app/AppLayouts/Wallet/popups/BuyCryptoModal.qml
fixes #14820
adds reccurentSiteUrl on the nim side and valid filter on qml model
Adding test cases for recurrent tab
BuyCryptoModal
https://github.com/status-im/status-desktop/assets/60327365/467d47fa-ac57-4e82-a408-a8f0af5a704b
https://github.com/status-im/status-desktop/assets/60327365/952ddd01-e218-4c8c-a54a-67653c9e49ec
=> feat(@desktop/wallet): Integrate recurring onramp providers in Recurrent tab

src/app_service/service/message/service.nim
fixes #14928
fixes error handling when error is null
MarkAllRead
I think the same change should be applied to onAsyncSearchMessages, onAsyncLoadMoreMessagesForChat, onAsyncLoadPinnedMessagesForChat. But we need to check the status-go first
Optional: I would also put all this error parsing into a separate method, because it looks the same
=> fix(chat): Display mention tag even if there is no mention

src/app/modules/main/module.nim, src/app_service/service/chat/dto/chat.nim, src/app_service/service/community/dto/community.nim
Fixes #14994
If you are part of the community member list, it means you are joined. It made no sense to add conditions to it.
The original bug was caused by my own code. I removed `result.joined = joined` in my refactor. TBH, I don't remmeber why I did it.
However, just re-adding that line felt wrong. That old code made no sense. First of all the line in `dto/community.nim` 
```nim
let joined = result.isMember or result.tokenPermissions.len == 0
```
made no sense, because `isMember` is for ourselves. So if we were part of the community, everyone else was also joined. Which in the end still worked, because indeed we want everyone to have `joined: true` from the member list, but it used a bad way to do it.
=> fix: set joined to all members of the comm since they are in the list

src/app/modules/main/module.nim, src/app_service/service/chat/dto/chat.nim, src/app_service/service/community/dto/community.nim
Cherry-pick of https://github.com/status-im/status-desktop/pull/15016
Fixes #14994
If you are part of the community member list, it means you are joined. It made no sense to add conditions to it.
=> [CHERRY-PICK] fix: set joined to all members of the comm since they are in the list

src/app/core/signals/remote_signals/mailserver.nim, src/app/modules/main/profile_section/sync/controller.nim, src/app/modules/main/profile_section/sync/io_interface.nim, src/app/modules/main/profile_section/sync/module.nim, src/app/modules/main/profile_section/sync/view.nim, src/app_service/service/mailservers/service.nim, src/app_service/service/settings/dto/settings.nim, src/app_service/service/settings/service.nim, src/backend/mailservers.nim, ui/app/AppLayouts/Profile/popups/WakuStoreModal.qml, ui/app/AppLayouts/Profile/stores/MessagingStore.qml, ui/app/AppLayouts/Profile/views/AdvancedView.qml
Fixes #14982
1. Fix the distinction between pinned and active servers
2. Use id instead of address. Previously mailserver could store id or address. Change method names to be more explicit.
3. Fix typo in fleet name "shard.test"
4. Prefer go API methods to set/get mail servers that fire a "mailserver.changed" signal. Instead of SaveSettings API
1. toggleUseMailservers
2. setPinnedMailservers
5. The sync module doesn't store pinned/active mail servers to avoid inconsistencies. This is done in my settings/mail server services
mailservers, settings
https://github.com/status-im/status-desktop/assets/1083341/f7652680-25fd-4c11-a2e6-185d78fd6104
#15030 
#15032
=> fix(HistoryNodes): Fix mailserver management UI controllers

test/e2e/gui/components/emoji_popup.py, test/e2e/gui/components/wallet/wallet_account_popups.py, test/e2e/gui/objects_map/communities_names.py, test/e2e/tests/communities/test_communities_channels.py, test/e2e/tests/communities/test_communities_pin_and_unpin_messages.py, test/e2e/tests/wallet_main_screen/wallet - assets tab/test_wallet_assets_sorting.py, test/e2e/tests/wallet_main_screen/wallet - plus button/test_plus_button_manage_account_from_seed_phrase.py
- Changes for wallet tests stabilisation - added waiting, attempts
- Skipped assets ordering tests (forgot to do this before - it fails because of known issue)
- Edited name of method save to save_changes in one test because of recent changes
- Increased timeout in pin unpin test
- Added waitFor channel name after editing
CI run:
https://ci.status.im/job/status-desktop/job/e2e/job/manual/2019/allure/
=> Fixes and changes for tests stability

storybook/pages/ObjectProxyModelExample1.qml, storybook/pages/ObjectProxyModelExample2.qml, storybook/pages/ObjectProxyModelPage.qml, storybook/pages/SubmodelProxyModelPage.qml, ui/StatusQ/CMakeLists.txt, ui/StatusQ/include/StatusQ/modelsyncedcontainer.h, ui/StatusQ/include/StatusQ/objectproxymodel.h, ui/StatusQ/include/StatusQ/submodelproxymodel.h, ui/StatusQ/src/objectproxymodel.cpp, ui/StatusQ/src/plugin.cpp, ui/StatusQ/tests/CMakeLists.txt, ui/StatusQ/tests/tst_ModelSyncedContainer.cpp, ui/StatusQ/tests/tst_ObjectProxyModel.cpp
This PR provides generalized version of `SubmodelProxyModel`. It can be used to create proxies over submodels but works in the same way also with other properties. May be used to override properties what is not possible with SFPM. Added proxy roles can be writable what's also not possible with SFPM.
Example:
```
ListModel {
id: srcModel
ListElement {
uid: 1
name: "ETH"
balances: [
ListElement {
value: 0.1
chainId: 1
},
ListElement {
value: 0.3
chainId: 2
}
]
}
ListElement {
uid: 2
name: "SNT"
balances: [
ListElement {
value: 0.8
chainId: 2
},
ListElement {
value: 0.32
chainId: 3
}
]
}
ListElement {
uid: 3
name: "DAI"
balances: [
ListElement {
value: 0.12
chainId: 1
},
ListElement {
value: 0.3
chainId: 3
}
]
}
}
ObjectProxyModel {
id: objectProxy
delegate: QtObject {
id: delegateRoot …
```
=> feat(StatusQ): `ObjectProxyModel` added - generalized `SubmodelProxyModel`

ui/app/AppLayouts/Profile/panels/ProfileDescriptionPanel.qml
Set bio's validationMode to StatusInput.ValidationMode.Always, as the default value (StatusInput.ValidationMode.OnlyWhenDirty) was preventing calculating up-to-date 'valid' state when the end-user does not change bio, but changes other data (e.g. Communities in Profile Showcase)
fixes #15015
https://github.com/status-im/status-desktop/assets/5157464/5570a49a-1540-4491-9a11-a8d95ef1d47c
=> fix(15015): cant save changes to the profile showcase

ui/imports/shared/popups/send/SendModal.qml
This PR unblocks send modal flow related to collectibles. Because of invalid state of hidden amount input the flow was broken (routes/fees part was never visible).
Closes: #15039
`SendModal`
[Screencast from 05.06.2024 14:47:47.webm](https://github.com/status-im/status-desktop/assets/20650004/3c4379c5-5c67-48be-8d6f-ffe56d1ad70d)
=> fix(SendModal): Unblock sending collectibles flow

src/app/modules/main/communities/tokens/controller.nim, src/app/modules/main/communities/tokens/io_interface.nim, src/app/modules/main/communities/tokens/module.nim, src/app/modules/main/communities/tokens/view.nim, src/app_service/service/community_tokens/service.nim, ui/app/AppLayouts/Communities/panels/MintTokensSettingsPanel.qml, ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml, ui/app/AppLayouts/Communities/views/CommunityTokenView.qml, ui/imports/shared/stores/CommunityTokensStore.qml
Token holders are not fetched when application starts. 
Tokens holders are fetched only for a concrete token for which CommunityTokenView is opened.
The time of last fetch operation for every token is kept in cache. 
Possible cases:
1. Open token screen and there are no holders yet - fetch holders instantly and run timer to refresh in 5 minutes
2. Open token screen and holders were fetched <5minutes ago - run timer to fetch holders
3. Open token screen and holders were fetched >5minutes ago - do the same as 1.
4. Close token screen - stop timer and do nothing
Fix #14974
=> fix(@desktop/communities): Lazy loading token holders

ci/Jenkinsfile.macos
Otherwise we end up with weird errors like:
```
status-go/go.mod:5: unknown directive: toolchain
```
=> fix(ci): prefix PATH with correct Go compiler path

storybook/pages/EditAirdropViewPage.qml, storybook/pages/NetworkFilterPage.qml, storybook/qmlTests/tests/tst_SwapModal.qml, ui/app/AppLayouts/Wallet/controls/NetworkFilter.qml, ui/app/AppLayouts/Wallet/controls/NetworkSelectItemDelegate.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapModal.qml, ui/app/AppLayouts/Wallet/views/NetworkSelectionView.qml
- add new `showRadioButtons` and `showTitle` UI customization points
- adjust SB and expose all the existing modes, fix it to make it work with multi selection
- integrate these new modes into SwapModal to align it with the Figma design
Fixes #14780
NetworkFilter,SwapModal
All the modes in action in SB:
[Záznam obrazovky z 2024-06-06 11-52-59.webm](https://github.com/status-im/status-desktop/assets/5377645/cad6387b-73f1-45c1-8ed8-58f32029d2ab)
The new modes in action in SwapModal:
[Záznam obrazovky z 2024-06-06 11-46-55.webm](https://github.com/status-im/status-desktop/assets/5377645/4fa7d6e2-d821-4fd8-8282-49df7c9cea12)
=> [UI - Swap] Update / improve NetworkFilter component to cover swap design specs

storybook/pages/SwapModalPage.qml, storybook/qmlTests/tests/tst_SwapModal.qml, ui/StatusQ/src/StatusQ/Popups/StatusModalDivider.qml, ui/app/AppLayouts/Wallet/controls/EditSlippagePanel.qml, ui/app/AppLayouts/Wallet/controls/qmldir, ui/app/AppLayouts/Wallet/popups/swap/SwapInputParamsForm.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapModal.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapModalAdaptor.qml, ui/imports/shared/controls/SlippageSelector.qml
fixes #14829
Implements the Edit Slippage panel and button behaviour in swapModal as defined in design https://www.figma.com/design/TS0eQX9dAZXqZtELiwKIoK/Swap---Milestone-1?node-id=3410-270310&m=dev
and User Story https://www.notion.so/Edit-max-slippage-4e590f28389d4ffebf2a50c7ed51143e?pvs=4 but Ive raised a bug for Slippage as it is not covering all the uses cases needed for the swap - https://github.com/status-im/status-desktop/issues/15017
1. Edit Slippage Panel
2. Edit Slippage footer button
3. Footer for swap modal
SwapModal
https://github.com/status-im/status-desktop/assets/60327365/3dd6107e-f8f6-4180-bd7f-6d67e …
=> feat(@desktop/wallet): Implements Edit slippage

src/app/modules/main/node_section/controller.nim, src/app/modules/main/node_section/io_interface.nim, src/app/modules/main/node_section/module.nim, src/app/modules/main/node_section/view.nim, src/app/modules/main/profile_section/advanced/controller.nim, src/app/modules/main/profile_section/waku/controller.nim, src/app/modules/main/profile_section/waku/module.nim, src/app_service/service/node_configuration/service.nim, src/app_service/service/settings/service.nim, src/backend/node_config.nim
status-go PR https://github.com/status-im/status-go/pull/5237
fixes #12918 #14889
1. The main goal - remove all uses of `saveNodeConfiguration`. Because it can overwrite the values it doesn't know about. 
(for example https://github.com/status-im/status-desktop/pull/14812)
2. Use instead: setLightClient, saveNewWakuNode, setMaxLogBackups (https://github.com/status-im/status-desktop/issues/14889)
Settings, NodeConfig
https://github.com/status-im/status-desktop/assets/1083341/3c87fddf-e356-4ffe-9005-fe67adc17c62
`setNimbusProxyConfigEnabled` currently is not used anywhere. Should be fixed after merging https://github.com/status-im/status-go/pull/4254
https://github.com/status-im/status-desktop/issues/14929
=> Save only the settings that are changed

src/backend/transactions.nim
Part of #15098
Implement custom marshaller for `MultiTransactionCommandDto`, properly handling the `MultiTransactionType` field so it gets serialized as a number instead of the enum label.
```
MultiTransactionCommandDto* = ref object of RootObj
fromAddress* {.serializedFieldName("fromAddress").}: string
toAddress* {.serializedFieldName("toAddress").}: string
fromAsset* {.serializedFieldName("fromAsset").}: string
toAsset* {.serializedFieldName("toAsset").}: string
fromAmount* {.serializedFieldName("fromAmount").}: string
multiTxType* {.serializedFieldName("type").}: MultiTransactionType
```
=> fix(wallet): properly marshall multiTxCommand type

test/e2e/scripts/utils/local_system.py
Closes https://github.com/status-im/status-desktop/issues/15131
I realised it is not enough to comment the steps in 1 test. The problem was also at the place when we stop the test, so i just changed the signal type we use
I ran this in the pr where tests are stuck and it passes now https://ci.status.im/job/status-desktop/job/e2e/job/manual/2054/console
NOTE: the code is a point to simplify, i will review it later, we need to unblock PRs now
tests
=> chore: use sigkill to kill the process

test/e2e/constants/wallet.py, test/e2e/driver/aut.py, test/e2e/driver/server.py, test/e2e/scripts/utils/local_system.py, test/e2e/tests/onboarding/test_onboarding_generate_new_keys.py, test/e2e/tests/onboarding/test_onboarding_import_seed.py, test/e2e/tests/settings/settings_password/test_settings_password_change_password.py
- removed unnecessary steps to check the process is closed from tests as it was never working, because even i log out from the app by a button (the very last step of the test), i am killing the app process as next thing immediately by a fixture
https://github.com/status-im/status-desktop/blob/75d755ea0f54c6ac514e0063fcb4627bc37854c7/test/e2e/fixtures/aut.py#L63
- brought back the steps i commented earlier (with app restart). It should work normally now
- decided to go with 1 method of `kill process` instead of multiple ones
Full tests run is here https://ci.status.im/job/status-desktop/job/systems/job/linux/job/x86_64/job/tests-e2e-new/386/console,  same as nightly of the other day
Autotests
=> Use one kill_process method in autotests instead of multiple

storybook/pages/DAppRequestModalPage.qml, storybook/pages/DAppsWorkflowPage.qml, storybook/qmlTests/tests/helpers/wallet_connect.js, storybook/qmlTests/tests/tst_DAppsWorkflow.qml, storybook/stubs/AppLayouts/Profile/stores/WalletStore.qml, ui/app/AppLayouts/Wallet/panels/DAppsWorkflow.qml, ui/app/AppLayouts/Wallet/panels/WalletHeader.qml, ui/app/AppLayouts/Wallet/services/dapps/DAppsListProvider.qml, ui/app/AppLayouts/Wallet/services/dapps/DAppsRequestHandler.qml, ui/app/AppLayouts/Wallet/services/dapps/WalletConnectSDK.qml, ui/app/AppLayouts/Wallet/services/dapps/WalletConnectSDKBase.qml, ui/app/AppLayouts/Wallet/services/dapps/WalletConnectService.qml, ui/app/AppLayouts/Wallet/services/dapps/helpers.js, ui/app/AppLayouts/Wallet/services/dapps/qmldir, ui/app/AppLayouts/Wallet/services/dapps/types/SessionRequestResolved.qml, ui/app/AppLayouts/Wallet/services/dapps/types/SessionRequestsModel.qml, ui/app/AppLayouts/Wallet/services/dapps/types/qmldir, ui/imports/shared/popups/walletconnect/DAppRequestModal.qml, ui/imports/shared/popups/walletconnect/DAppsListPopup.qml, ui/imports/shared/popups/walletconnect/PairWCModal.qml, ui/imports/shared/stores/DAppsStore.qml
Support showing sign message only, rejects other requests
Support user rejecting the request
Other changes
Minor general improvements
Add tests for the main logic and sanity UI tests
Storybook integration
`HEAD~1`: chore(dapps) abstract WalletConnectSDK to make it testable
Beware that `FLAG_DAPPS_ENABLED` with the value of 1 must be defined to enable the feature and make it testable
https://github.com/status-im/status-desktop/assets/47554641/0101797e-6eec-4ca0-868d-9bea01ec3a26
=> feat(dapps) implements responding to wallet connect requests

storybook/pages/SwapInputPanelPage.qml, storybook/qmlTests/tests/tst_SwapInputPanel.qml, storybook/stubs/shared/stores/send/TransactionStore.qml, ui/app/AppLayouts/Wallet/WalletUtils.qml, ui/app/AppLayouts/Wallet/controls/MaxSendButton.qml, ui/app/AppLayouts/Wallet/controls/qmldir, ui/app/AppLayouts/Wallet/panels/SwapInputPanel.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapModalAdaptor.qml, ui/imports/shared/popups/send/SendModal.qml, ui/imports/shared/popups/send/views/AmountToSend.qml
- create a reusable "Max" send button component
- use it in SwapModal and SendModal
- add some more tests in tst_SwapInputPanel.qml
Fixes #15066
SwapModal, SendModal
[Záznam obrazovky z 2024-06-10 12-41-32.webm](https://github.com/status-im/status-desktop/assets/5377645/57ab53af-acae-4289-bb21-2e18c3126a3d)
=> feat: [UI - Wallet Stability] Create Max button component

ui/app/AppLayouts/Communities/panels/MembersTabPanel.qml
Fixes: https://github.com/status-im/status-desktop/issues/13890
Sorting community members list by concatenated name: `localNickname + ensName + displayName + alias`
MembersTabPanel, for admin of a community
=> fix(MembersTabPanel): Sorted Community members list alphabetically

ui/app/AppLayouts/Node/NodeLayout.qml
Changes the order of the fields in the node management tab, so the text field to enter the RPC call is always available, because otherwise, once you use a method that returns a large amount of data, the field will no longer be visible.
=> chore: change order of rpc text input

test/e2e/tests/settings/settings_password/test_settings_password_change_password.py
Disable change password test because of https://github.com/status-im/status-desktop/issues/15178
ui tests
=> test: disable change password test because it creates ghost instances

src/app/modules/main/profile_section/contacts/controller.nim, src/app/modules/main/profile_section/contacts/io_interface.nim, src/app/modules/main/profile_section/contacts/module.nim, src/app/modules/main/profile_section/contacts/view.nim, src/app/modules/shared_models/user_item.nim, src/app/modules/shared_models/user_model.nim, storybook/pages/ContactDetailsPage.qml, storybook/qmlTests/tests/tst_ContactDetails.qml, storybook/src/Storybook/StorybookUtils.qml, storybook/stubs/AppLayouts/Profile/stores/ContactsStore.qml, storybook/stubs/AppLayouts/Profile/stores/ProfileStore.qml, storybook/stubs/AppLayouts/Profile/stores/qmldir, ui/StatusQ/include/StatusQ/concatmodel.h, ui/StatusQ/src/concatmodel.cpp, ui/StatusQ/src/modelentry.cpp, ui/app/AppLayouts/Profile/helpers/ContactDetails.qml, ui/app/AppLayouts/Profile/helpers/qmldir, ui/app/AppLayouts/Profile/stores/ContactsStore.qml, ui/app/AppLayouts/Profile/stores/ProfileStore.qml, ui/app/AppLayouts/Profile/stores/qmldir, ui/imports/shared/views/ProfileDialogView.qml
Closes #14963 
Depends on #14891
This PR creates the `ContactDetails` helper component to provide live data to the UI and implements all the logistics to have a functional implementation in the profile view.
1. Expose a new model from nim `contactsModel`. This model holds all the available contacts. It's reusing the `user_model` that was extended to support all the extra data needed by the `ContactDetails`. https://github.com/status-im/status-desktop/commit/d9cc76a01757841af8d52ce4e8fe589790182775
2. Extend the `ProfileStore` to provide the extra info needed for own profile.
3. Create the `ContactDetails` component and add support for requesting new contact details through `contactsStore.requestContactInfo`
4. Adding the storybook page and qml tests
5. Adapt the profile view to the new …
=> Refactor(getContactDetailsAsJson): Create the `ContactDetails` component

test/e2e/configs/testpath.py, test/e2e/conftest.py, test/e2e/gui/components/onboarding/before_started_popup.py, test/e2e/gui/elements/check_box.py, test/e2e/gui/elements/object.py, test/e2e/gui/main_window.py, test/e2e/gui/objects_map/names.py, test/e2e/tests/communities/test_communities_mint_owner_token.py, ui/StatusQ/src/StatusQ/Controls/StatusCheckBox.qml
- click checkboxes' indicators on `Before get started` modal instead of checkbox item (which has text as well)
- click other elements in the middle by default
- remove `:` to make windows happy
ui tests
=> chore: use checkbox indicator to locate checkboxes on login, click objects in the middle

src/app/modules/shared_modules/wallet_connect/controller.nim, src/app_service/service/wallet_connect/service.nim, src/backend/wallet_connect.nim, storybook/pages/DAppRequestModalPage.qml, storybook/pages/DAppsWorkflowPage.qml, storybook/qmlTests/tests/tst_DAppsWorkflow.qml, ui/app/AppLayouts/Wallet/panels/DAppsWorkflow.qml, ui/app/AppLayouts/Wallet/services/dapps/DAppsRequestHandler.qml, ui/app/AppLayouts/Wallet/services/dapps/WalletConnectSDK.qml, ui/app/AppLayouts/Wallet/services/dapps/WalletConnectService.qml, ui/app/AppLayouts/Wallet/services/dapps/helpers.js, ui/imports/shared/popups/walletconnect/DAppRequestModal.qml, ui/imports/shared/stores/DAppsStore.qml
Implement infrastructure and integration with status-go to support general session requests
Supported methods:
- `personal_sign`
- `eth_signTypedData_v4`
Also
- support hex or utf8 encoding for personal_sign
- format the typed data for display in the modal
=> feat(dapps) implement signing of wallet connect messages

storybook/pages/SwapInputPanelPage.qml, storybook/pages/SwapModalPage.qml, storybook/pages/TokenSelectorAssetDelegatePage.qml, storybook/pages/TokenSelectorViewPage.qml, storybook/qmlTests/tests/tst_TokenSelectorView.qml, storybook/qmlTests/tests/tst_TokenSelectorViewAdaptor.qml, storybook/src/Models/GroupedAccountsAssetsModel.qml, storybook/src/Models/NetworksModel.qml, storybook/src/Models/TokensBySymbolModel.qml, storybook/stubs/shared/stores/CurrenciesStore.qml, storybook/stubs/shared/stores/send/TransactionStore.qml, ui/StatusQ/include/StatusQ/modelsyncedcontainer.h, ui/StatusQ/include/StatusQ/objectproxymodel.h, ui/StatusQ/src/StatusQ/Core/LocaleUtils.qml, ui/StatusQ/src/leftjoinmodel.cpp, ui/StatusQ/src/objectproxymodel.cpp, ui/StatusQ/tests/tst_ObjectProxyModel.cpp, ui/app/AppLayouts/Wallet/adaptors/TokenSelectorViewAdaptor.qml, ui/app/AppLayouts/Wallet/adaptors/qmldir, ui/app/AppLayouts/Wallet/panels/SwapInputPanel.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapModalAdaptor.qml, ui/app/AppLayouts/Wallet/stores/TokensStore.qml, ui/app/AppLayouts/Wallet/views/TokenSelectorAssetDelegate.qml, ui/app/AppLayouts/Wallet/views/TokenSelectorView.qml, ui/app/AppLayouts/Wallet/views/qmldir, ui/imports/shared/popups/send/SendModal.qml, ui/imports/shared/stores/CurrenciesStore.qml, ui/imports/shared/stores/send/TransactionStore.qml
TLDR: later this should form a basic building block for a new TokenSelector picker component, potentially replacing the current HoldingSelector* and TokenListView components (support for collectibles TBD as part of https://github.com/status-im/status-desktop/issues/15121)
- create reusable `TokenSelectorAssetDelegate` and `TokenSelectorView`
- add corresponding SB page, showcasing the flow/integration and the separation of concerns between the view, adaptor and delegate layers
- add QML testcase for TokenSelectorView
- don't display crypto symbol for token balances per chain tags
- update the stores and SB pages
- add some missing formatter functions to LocaleUtils and CurrenciesStore
Fixes #14716
TokenSelectorView, TokenSelectorAssetDelegate
=> feat[UI - Wallet Stability] Create generic/reusable assets listview component

storybook/pages/SwapInputPanelPage.qml, storybook/pages/SwapModalPage.qml, storybook/qmlTests/tests/tst_SwapInputPanel.qml, storybook/qmlTests/tests/tst_SwapModal.qml, ui/app/AppLayouts/Wallet/WalletLayout.qml, ui/app/AppLayouts/Wallet/WalletUtils.qml, ui/app/AppLayouts/Wallet/panels/SwapInputPanel.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapInputParamsForm.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapModal.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapModalAdaptor.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapOutputData.qml, ui/imports/shared/popups/send/panels/HoldingItemSelector.qml, ui/imports/shared/popups/send/views/AmountToSend.qml
fixes #14826, #14825
This PR uses the SwapInputPanel and connects it to the backend. it tried to cover all the flows of Swap M1 designs related to input and output fields that can be supported and added TODO is places there are bugs such as the ones listed here https://github.com/status-im/status-desktop/issues/15162
Have written UTS for all possible scenarios but may need more as we find more corner cases. some tests are comented because of the issue mentioned above. 
US's covered
https://www.notion.so/Select-input-parameters-56c5f81573d145f6b079678cdaaa362c?pvs=4 and 
https://www.notion.so/Select-output-parameters-ce74bb4ee5fe43f9923476a26e8ff130?pvs=4
SwapModal, SwapInputPanel
- in case of new features, add variation to existing …
=> feat(@desktop/wallet): Add Select Input and  output params to swap modal

monitoring/MonitorEntryPoint.qml, src/app/modules/main/chat_section/model.nim
fixes #14719
Trigger role updates when dependency roles are updated
```mermaid
graph TD
A[itemShouldBeHiddenBecauseNotPermitted]
B[memberRole]
C[isCategory]
D[categoryId]
E[hideBecausePermissionsAreNotMet\n*of all items in category]
F[hideIfPermissionsNotMet]
G[canPost]
H[canView]
A --> B
A --> C
A --> D
A --> E
E --> F
E --> G
E --> H
```
Communities, show hidden channels to admin when joining a community
https://github.com/status-im/status-desktop/assets/1083341/ed654334-5f2b-464c-a3b8-d32d6ab2ce09
There should be another potential problem: when I change the visibility of a channel in the category, the `ShouldBeHiddenBecausePermissionsAreNotMet` for the category item should not be updated with the current code. But for some reason this doesn't happen, and the category gets hidden when …
=> fix(community): update hidden channels visibility when joining the community

test/e2e/gui/objects_map/communities_names.py, test/e2e/gui/screens/community_settings_tokens.py, test/e2e/tests/communities/test_communities_mint_owner_token.py, ui/app/AppLayouts/Communities/views/EditOwnerTokenView.qml
Fixed mint owner test, so now it should always scroll to the objects, added object names
CI run: https://ci.status.im/job/status-desktop/job/e2e/job/manual/2148/
test/e2e/tests/communities/test_communities_mint_owner_token.py
ui/app/AppLayouts/Communities/views/EditOwnerTokenView.qml
=> Fixes for mint owner token test

ci/Jenkinsfile.tests-e2e
In this PR we specify `QT_QPA_PLATFORM` to  `linuxfb`
reference -> https://doc.qt.io/qt-5/embedded-linux.html#linuxfb
This ensures we do not rely on `xcb` for e2e tests on linux hosts. 
Helps us fix the following error : 
```
"Could not load the Qt platform plugin "xcb" in "" even though it was found."
```
fixes: #13811
=> e2e: specify linux plugin platform for QT

storybook/pages/AccountViewPage.qml, storybook/pages/NetworkFilterPage.qml, storybook/pages/NetworkSelectItemDelegatePage.qml, storybook/pages/NetworkSelectPopupPage.qml, storybook/qmlTests/tests/tst_NetworkSelectItemDelegate.qml, test/e2e/gui/objects_map/names.py, ui/StatusQ/src/StatusQ/Components/StatusSmartIdenticon.qml, ui/app/AppLayouts/Wallet/controls/NetworkFilter.qml, ui/app/AppLayouts/Wallet/controls/NetworkSelectItemDelegate.qml, ui/app/AppLayouts/Wallet/popups/NetworkSelectPopup.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapModal.qml, ui/app/AppLayouts/Wallet/views/NetworkSelectionView.qml, ui/app/AppLayouts/Wallet/views/qmldir
Iterates #14692 
This is the first step in refactoring the NetworkFilter, by cleaning the base component that handles the check states. This component supports multiple configurations:
1. Single selection with or without radio button
2. Multiple selection with or without checkbox
3. Automatic handling of the check state. The component will change the check state based on user clicks
4. Manual handling of the check state. The component will not change the check state, but offers a toggled signal and expects the user to change the check state based on external flows
+ Fix minor bugs
NEXT STEPS: Repeat this process on `NetworkSelectionView` and `NetworkFilter`
1. Cleaning the NetworkSelectItemDelegate. The extra logic has been moved in the upper layer. The next phase is to clean the upper …
=> refactoring(NetworkSelectItemDelegate): Remove backend dependency and clean the API

storybook/pages/NetworkSelectorViewPage.qml, storybook/qmlTests/tests/tst_NetworkSelectorView.qml, ui/app/AppLayouts/Wallet/views/NetworkSelectorView.qml, ui/app/AppLayouts/Wallet/views/qmldir
Iterates #14692 
Built on top of https://github.com/status-im/status-desktop/pull/15147
This commit creates a new component NetworkSelectorView and it's implementation will replace the NetworkSelectionView
+ Adding the storybook page
+ Adding tests
Features:
1. Single selection
2. Multi selection
3. Interactive - on/off
Nest steps: Transplant this component in the app
https://github.com/status-im/status-desktop/assets/47811206/f22207e9-88cf-4dfd-b7f9-7ae6df113ca5
=> refactoring(NetworkSelectionView): Update NetworkSelectionView and remove the backend dependency

ui/app/AppLayouts/Wallet/popups/swap/SwapModal.qml
Closes #15275 
Fixing the modal height.
SwapModal
=> fix(SwapModal): Fixing the modal height

test/e2e/tests/settings/settings_wallet/test_wallet_settings_add_account.py
Disable add account test because the app segfaults with the following error
```
Critical: Error parsing my revealed addresses SyntaxError: JSON.parse: Parse error (qrc:/app/AppLayouts/stores/RootStore.qml:54, expression for myRevealedAddressesForCurrentCommunity)
```
I logged https://github.com/status-im/status-desktop/issues/15286 to investigate
end-to-end tests
=> tests: test for adding account from settings is disabled

ci/Jenkinsfile.tests-e2e
CI run:
here I checked that it works and test is timing out on permissions tests which was broken and stuck forever (used old build)
https://ci.status.im/job/status-desktop/job/e2e/job/manual/2164/allure/#suites/ea35bd66d78deeec4a096260dd1d8144/991d57c78fc381bd
here I ran all tests to make sure all works good for all tests (actual master build)
https://ci.status.im/job/status-desktop/job/e2e/job/manual/2168/
After investigating I came to the conclusion that the best option to cover any issues (not only when the app crashes and stuck forever, but other possible cases which causes hanging tests too) is to set global timeout using pytest-timeout. 
So when it's set globally, test would fail in case test execution takes more than 3 minutes, but test run will continue. It also works for hanging …
=> Timeout for tests added so hanging test fail after timeout rather then stuck forever

storybook/pages/SwapInputPanelPage.qml, storybook/pages/SwapModalPage.qml, storybook/pages/TokenSelectorPage.qml, storybook/qmlTests/tests/tst_SwapInputPanel.qml, storybook/qmlTests/tests/tst_SwapModal.qml, storybook/qmlTests/tests/tst_TokenSelector.qml, storybook/src/Models/GroupedAccountsAssetsModel.qml, ui/StatusQ/src/StatusQ/Controls/StatusComboBox.qml, ui/app/AppLayouts/Wallet/adaptors/TokenSelectorViewAdaptor.qml, ui/app/AppLayouts/Wallet/controls/EditSlippagePanel.qml, ui/app/AppLayouts/Wallet/controls/MaxSendButton.qml, ui/app/AppLayouts/Wallet/controls/NetworkFilter.qml, ui/app/AppLayouts/Wallet/controls/TokenSelector.qml, ui/app/AppLayouts/Wallet/controls/qmldir, ui/app/AppLayouts/Wallet/panels/SwapInputPanel.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapModal.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapModalAdaptor.qml, ui/imports/shared/controls/SlippageSelector.qml
- create new dedicated (asset) token selector component
- integrate it into `SwapInputPanel`, `SwapModalAdaptor` and `SwapModal`
- add respective SB page and QML tests suite
Fixes #14783
TokenSelector, SwapInputPanel, SwapModal
SwapModal:
SwapInputPanel:
TokenSelector:
=> feat:[UI - Swap] Create new TokenSelector component

test/e2e/tests/communities/test_communities_categories.py, test/e2e/tests/communities/test_communities_channels.py
Fixed community name to one from user data
CI run:
https://ci.status.im/job/status-desktop/job/e2e/job/manual/2185/allure/#suites/804b25da7c0d1c4c7f8a050c6a89e043/7185f754fe8983f1/
(1 fail - mint owner token, fixed in another PR, 1 - slow contact requests)
=> Fix for community name

src/app/modules/main/wallet_section/activity/controller.nim, src/app/modules/shared_modules/wallet_connect/controller.nim, src/app_service/service/wallet_connect/service.nim, storybook/pages/DAppRequestModalPage.qml, storybook/pages/DAppsWorkflowPage.qml, storybook/qmlTests/tests/helpers/wallet_connect.js, storybook/qmlTests/tests/tst_DAppsWorkflow.qml, ui/StatusQ/src/StatusQ/Core/Utils/ModelUtils.qml, ui/app/AppLayouts/Wallet/panels/DAppsWorkflow.qml, ui/app/AppLayouts/Wallet/panels/WalletHeader.qml, ui/app/AppLayouts/Wallet/services/dapps/DAppsListProvider.qml, ui/app/AppLayouts/Wallet/services/dapps/DAppsRequestHandler.qml, ui/app/AppLayouts/Wallet/services/dapps/WalletConnectService.qml, ui/app/AppLayouts/Wallet/services/dapps/types/SessionRequest.qml, ui/app/AppLayouts/Wallet/services/dapps/types/qmldir, ui/app/mainui/AppMain.qml, ui/imports/shared/popups/walletconnect/DAppRequestModal.qml, ui/imports/shared/stores/DAppsStore.qml
`HEAD~2` Uses status-go's endpoints:
- `wallet_buildTransactions` to format the transaction
- `wallet_signMessage` to sign the transaction
- `wallet_buildRawTransaction` to format the final signed transaction
Also
- `HEAD` fix(dapps): failure if case sensitivity mismatch in account address
- `HEAD~1` feat(dapps) fix missing list of dapps in wallet connect
- `HEAD~3` chore(dApps) support multiple actions in DAppRequestModal
- Also fix minor issue and add improvements
https://github.com/status-im/status-desktop/assets/47554641/80bdd75a-c149-4779-8c11-7f5142467af7
=> feat(dApps) implement sign transaction for wallet connect

src/app/modules/main/module.nim
fixes #15076
When a new token is minted and `SIGNAL_COMMUNITIES_UPDATE` is emitted, we recreate the `SectionItem` with the updated `CommunityDto`.
After this, `SectionItem.communityTokens` is empty and will be retrieved asynchronously via `getCommunityTokensDetailsAsync`.
In this PR, old `communityTokens` are kept until `onCommunityTokensDetailsLoaded` updates the tokens.
Communities
https://github.com/status-im/status-desktop/assets/1083341/11d44e03-849e-4adf-9819-f5c8bec52e7a
https://github.com/status-im/status-desktop/assets/1083341/739bd549-d703-4869-b971-63e8d45986ca
=> fix(community): community tokens disappear when minting of a new token is finished

ui/imports/shared/controls/AmountInput.qml
(regression after https://github.com/status-im/status-desktop/commit/a12a6a4894c087a3c3ffac23b97cc457570656c1)
fixes #15264 
Restores the old approach:
When calling `LocaleUtils.numberToLocaleString`, calculates number precision for amount text based on `fractionalPartLength`
As far as I can see, `multiplierIndex` for collectibles is always 0. Previously the default `precision` was -1, which made the effective precision value for collectibles 0. 
```
function numberToLocaleString(num, precision = -1, locale = null) {
locale = locale || Qt.locale()
if (precision === -1)
precision = fractionalPartLength(num)
return num.toLocaleString(locale, 'f', precision)
}
```
After changing it to -128, the resulting string became 1000000.
```
function numberToLocaleString(num, precision = -128 /* …
```
=> fix(airdrop): Incorrect default amount when airdropping a community token or setting token permission

test/e2e/driver/squish_api.py, test/e2e/gui/components/authenticate_popup.py, test/e2e/gui/components/wallet/wallet_account_popups.py, test/e2e/gui/elements/object.py, test/e2e/gui/screens/onboarding.py
Fixes https://github.com/status-im/status-desktop/issues/15335
Opens https://github.com/status-im/status-desktop/issues/15345
- Implement usage of https://doc.qt.io/squish/squish-api.html#applicationcontext-isfrozen-function after click
- Add timeout param to click function and set it default to 1 second
- Pass non-default timeout (10 seconds) to the clicks, where application freezes (we will fix them later in the ticket above)
end-to-end UI tests
We aim to UI respond within 0.2 seconds in future
=> chore: add ApplicationContext.isFrozen() function call after click

src/app_service/service/chat/dto/chat.nim, src/app_service/service/community/dto/community.nim, src/app_service/service/community/service.nim
Fixes #15149
In [this status go PR](https://github.com/status-im/status-go/pull/5335), we are removing the members from channels that are not-permissioned to increase performance (we don't need to pass such a big JSON).
It doesn't change anything in the UI
[members.webm](https://github.com/status-im/status-desktop/assets/11926403/317ca55a-1596-433b-b604-7da586b68788)
=> perf: use community members for unpermissioned channels

monitoring/ModelInspectionPane.qml, monitoring/MonitorEntryPoint.qml, ui/include/StatusDesktop/Monitoring/Monitor.h, ui/src/StatusDesktop/Monitoring/Monitor.cpp
Closes: #15181
Now the search traverses freely over all objects, including those created by `ListView`, `Repeater` and similar. Parents are predefined in code, no longer needed to provide them manually. All of them are test until the given object name is found.
[Screencast from 26.06.2024 20:32:41.webm](https://github.com/status-im/status-desktop/assets/20650004/7a97396a-ea4b-47fc-ac58-df45d3d35923)
=> feat(MonitoringTool): Search improved

test/e2e/driver/aut.py, test/e2e/driver/server.py, test/e2e/fixtures/aut.py
attach geth.log to allure report when running autotests
Fixes https://github.com/status-im/status-desktop/issues/15339
e2e tests
=> chore: attach geth.log to allure report when running autotests

storybook/pages/GroupingModelPage.qml, ui/StatusQ/CMakeLists.txt, ui/StatusQ/include/StatusQ/groupingmodel.h, ui/StatusQ/src/groupingmodel.cpp, ui/StatusQ/src/plugin.cpp, ui/StatusQ/tests/CMakeLists.txt, ui/StatusQ/tests/src/TestHelpers/listmodelwrapper.cpp, ui/StatusQ/tests/tst_GroupingModel.cpp
Provides reusable, generic proxy model for grouping model's entries into submodels.
Assuming that we have a source model of the following structure and content:
```
[
{ "name": "A", "subname": "a1" },
{ "name": "A", "subname": "a2" },
{ "name": "B", "subname": "b1" },
{ "name": "C", "subname": "c1" },
{ "name": "C", "subname": "c2" },
{ "name": "C", "subname": "c3" },
{ "name": "C", "subname": "c4" },
{ "name": "D", "subname": "d1" },
{ "name": "D", "subname": "d2" },
{ "name": "D", "subname": "d3" },
{ "name": "E", "subname": "e1" },
{ "name": "E", "subname": "e2" }
]
```
using `GroupingModel`:
```
GroupingModel {
sourceModel: src
groupingRoleName: "name"
submodelRoleName: "subnames"
}
```
We will receive model of the following structure:
```
[
{
"name": "A", "subname": "a1",
"subnames": …
```
=> feat(StatusQ): GroupingModel

src/backend/communities.nim
fixes #15340
The twin of mobile PR: https://github.com/status-im/status-mobile/pull/20481
Use `wakuext_serialisedCommunities` instead of `wakuext_communities` API which returns image media server URLs instead of base64 blobs.
works seamlessly
Any place in the app showing community images (banner, logo, thumbnail)
Here I've logged incoming json with communities and show that the community logo is present as the media server URL.
https://github.com/status-im/status-desktop/assets/1083341/0f571c9b-edf6-4afb-8546-197d0ecdde7b
=> chore: Use optimized endpoint to get communities with images

test/e2e/tests/communities/test_communities_pin_and_unpin_messages.py, test/e2e/tests/messages/test_messaging_1x1_chat.py, test/e2e/tests/messages/test_messaging_link_previews.py
Replace account seed usage with new account creation in community test
Tests
=> tests: replace seed recovery with new user creation instead

test/e2e/tests/communities/test_communities.py, test/e2e/tests/messages/test_messaging_1x1_chat.py, test/e2e/tests/wallet_main_screen/wallet - assets tab/test_wallet_assets_sorting.py
- Added waitFor in a couple of steps - it's good for stability and may temporarily help with fails in nightly (even after bug is fixed is good to have it)
- Skipped assets sorting as it fails on CI again due to rate limits issues
CI runs:
https://ci.status.im/job/status-desktop/job/e2e/job/manual/2209/
https://ci.status.im/job/status-desktop/job/e2e/job/manual/2210/
=> Some changes to stabilise tests

ui/StatusQ/CMakeLists.txt, ui/StatusQ/include/StatusQ/modelcount.h, ui/StatusQ/src/modelcount.cpp, ui/StatusQ/src/plugin.cpp, ui/StatusQ/tests/CMakeLists.txt, ui/StatusQ/tests/src/TestHelpers/testmodel.cpp, ui/StatusQ/tests/src/TestHelpers/testmodel.h, ui/StatusQ/tests/tst_ModelCount.cpp
Introduces attached type `ModelCount` providing model count for arbitrary `QAbstractItemModel`. Works with both UI models like `ListModel`, all proxy models, and NIM models. Doesn't rely on `count` property in source model. It gives a possibility to skip implementation of `count` in nim models, which is boilerplate code repeated in many models.
Closes: #15374
Example:
Whenever in existing code we have:
```
channelsListModel: model.channelsListModel.rowCount()
? channelsSelectionModel : communityItemModel
```
such binding is unreliable because won't be reevaluated appropriately on count change.
Now it can be fixed easily with `ModelCount`:
```
channelsListModel: model.channelsListModel.ModelCount.count
? channelsSelectionModel : communityItemModel
```
which is fully responsive to count …
=> feat(StatusQ): Generic attachd type for providing model count

src/app/core/signals/remote_signals/signal_type.nim, src/app/core/signals/remote_signals/wallet.nim, src/app/core/signals/signals_manager.nim, src/app/modules/main/wallet_section/send/controller.nim, src/app/modules/main/wallet_section/send/io_interface.nim, src/app/modules/main/wallet_section/send/module.nim, src/app/modules/main/wallet_section/send/network_model.nim, src/app/modules/main/wallet_section/send/view.nim, src/app_service/common/utils.nim, src/app_service/service/eth/dto/transaction.nim, src/app_service/service/transaction/async_tasks.nim, src/app_service/service/transaction/dto.nim, src/app_service/service/transaction/dtoV2.nim, src/app_service/service/transaction/dto_conversion.nim, src/app_service/service/transaction/service.nim, src/backend/eth.nim, ui/app/AppLayouts/Wallet/popups/swap/SwapModalAdaptor.qml, ui/app/AppLayouts/Wallet/stores/SwapStore.qml, ui/imports/shared/popups/send/controls/GasSelector.qml, ui/imports/shared/stores/send/TransactionStore.qml
An asynchronous which was before on the Nim side, is not achieved on the status-go side and the result is handled by handling `"wallet.suggested.routes"` signal sent from the status-go side.
- https://github.com/status-im/status-go/pull/5426
Apart from that change nothing should be changed in terms of UI, and nothing is refactored (even the SendModal popup deserves a big refactor to get it back to the good and maintainable path), what's really done is just a simple router v2 integration, by mapping new to the old path params.
Closes: #15204
=> chore: router v2 integration

storybook/pages/SwapInputPanelPage.qml, storybook/pages/SwapModalPage.qml, storybook/pages/TokenSelectorAssetDelegatePage.qml, storybook/pages/TokenSelectorPage.qml, storybook/pages/TokenSelectorViewPage.qml, storybook/pages/WalletAccountListItemPage.qml, storybook/qmlTests/tests/tst_SwapInputPanel.qml, storybook/qmlTests/tests/tst_SwapModal.qml, storybook/qmlTests/tests/tst_TokenSelector.qml, storybook/qmlTests/tests/tst_TokenSelectorView.qml, storybook/qmlTests/tests/tst_TokenSelectorViewAdaptor.qml, storybook/src/Models/WalletAccountsModel.qml, ui/StatusQ/src/StatusQ/Components/StatusListItem.qml, ui/StatusQ/src/StatusQ/Core/Utils/Utils.qml, ui/app/AppLayouts/Wallet/adaptors/TokenSelectorViewAdaptor.qml, ui/app/AppLayouts/Wallet/controls/EditSlippagePanel.qml, ui/app/AppLayouts/Wallet/controls/TokenSelector.qml, ui/app/AppLayouts/Wallet/panels/SwapInputPanel.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapModal.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapModalAdaptor.qml, ui/app/AppLayouts/Wallet/views/TokenSelectorAssetDelegate.qml, ui/app/AppLayouts/Wallet/views/TokenSelectorView.qml, ui/imports/shared/controls/AccountSelector.qml, ui/imports/shared/controls/AccountSelectorHeader.qml, ui/imports/shared/controls/WalletAccountListItem.qml, ui/imports/utils/Utils.qml
- AccountsSelector: update / improve  component to cover swap design specs (Fixes #14779)
- SwapModal: add scrolling support (Fixes #15276)
- TokenSelector: support showing all known (plain) tokens (Fixes #15278)
See the respective commits for further details
SwapModal
Dialog expanded and scrolled down:
Account selector (correct subbalances, font and sorting):
Token selector with sections + plain tokens:
=> feat: SwapModal UI fixes

src/app_service/common/net_utils.nim, src/app_service/common/network_constants.nim, src/app_service/service/accounts/dto/api_config.nim, src/app_service/service/accounts/dto/create_account_request.nim, src/app_service/service/accounts/dto/login_request.nim, src/app_service/service/accounts/service.nim
For https://github.com/status-im/status-desktop/issues/14795
Waits https://github.com/status-im/status-go/pull/5346
This PR enables rpc server over HTTP on port 8545 and over Websocket on port 8586.
1. Start status desktop, create or login into account
2. After login rpc server should be available, test it with curl:
```
curl -X POST http://127.0.0.1:8545      -H 'Content-type: application/json'      -d '{
"jsonrpc": "2.0",
"id": 37,
"method": "connector_callRPC",
"params": ["{\"method\": \"eth_accounts\", \"params\": []}"]
}' | jq
```
3. Websocket can be enabled in config, test with
```
wscat -c "ws://0.0.0.0:8586"
```
=> feat: Enable WS and HTTP RPC servers for status desktop through config

storybook/qmlTests/tests/tst_SwapInputPanel.qml, storybook/qmlTests/tests/tst_SwapModal.qml
Closes: #15272
Changes: 
1. Move the mouse to hover the account selector after opening. IDK why but sometimes the cursor is hovering the first row and triggers a hover state making the subtitle to change
2. Adding `waitForRendering` after setting the amount to swap. For some reason the Backpressure starts much later (if ever). Seems to fix it. Now I hope it's really fixing the issue and not making it less detectable..
Maybe the real fix would be to refactor the tests and rely on signals instead of `wait`. Synchronising the tests with the implementation is quite difficult because we have both timers and delayed bindings
=> fix(swapModal): Fixing flaky tests (hopefully)

storybook/pages/TokenSelectorPage.qml, storybook/qmlTests/tests/tst_TokenSelectorViewAdaptor.qml, ui/app/AppLayouts/Wallet/adaptors/TokenSelectorViewAdaptor.qml, ui/app/AppLayouts/Wallet/controls/TokenSelector.qml, ui/app/AppLayouts/Wallet/views/TokenSelectorAssetDelegate.qml
- filter out plain tokens from the adaptor if already present in the output model
- add a corresponding regression test
- hardcode the TokenSelector's popup height and increase margins
- fix sections in search mode
- add a placeholder for no search results
Fixes https://github.com/status-im/status-desktop/issues/15412
TokenSelector[ViewAdaptor]
=> fix(TokenSelector): Duplicate plain token entries

storybook/qmlTests/tests/tst_ContactDetails.qml, ui/app/AppLayouts/Profile/helpers/ContactDetails.qml
Fixes #15314
The problem is that we used the `name` property to know if we have an ENS name, but we actually set it to whatever is available, so we need to validate that it's an ENS name
As seen here:
https://github.com/status-im/status-desktop/blob/7a7dbb631c11edf7e63594eddbc7beffa42ab646/src/app/global/user_profile.nim#L98-L103
=> fix(profile): fix missing ring in own profile

src/app/modules/main/chat_section/controller.nim, src/app/modules/main/chat_section/module.nim, src/app_service/service/chat/service.nim
Fixes #11093
When unmuting a channel, reevaluate the section badge so that it appears if there were unread messages in that channel
Also fixes an issue where the chat muted property was not set correctly in the cache after muting or unmuting
[unmute.webm](https://github.com/status-im/status-desktop/assets/11926403/1de2d94f-250f-4b7d-a683-95de6336d5d6)
=> fix(muted): reevaluate section badge when unmuting

src/app/modules/main/wallet_section/controller.nim, src/app/modules/main/wallet_section/io_interface.nim, src/app/modules/main/wallet_section/module.nim, src/app/modules/main/wallet_section/view.nim, src/app_service/service/wallet_account/service_token.nim, src/app_service/service/wallet_account/signals_and_payloads.nim, src/backend/backend.nim, ui/StatusQ/src/StatusQ/Controls/StatusBaseButton.qml, ui/StatusQ/src/StatusQ/Core/StatusAssetSettings.qml, ui/app/AppLayouts/Wallet/panels/WalletHeader.qml, ui/app/AppLayouts/Wallet/stores/RootStore.qml
This PR implements the manual wallet reload functionality. It introduces the following key changes:
* Adds a manual reload button to the wallet header.
* Integrates a throttle mechanism to prevent frequent reloads.
* Updates the backend to support wallet reload functionality via RPC.
* Enhances UI components to reflect the loading state and display the last reload timestamp.
resolves: #13652
blocked by: https://github.com/status-im/status-go/pull/5461
* Wallet: Added manual reload functionality and UI enhancements.
* Backend: Added support for wallet reload via RPC.
* StatusQ: Enhanced button and loader components to support new functionality.
- nice to have: add it to …
=> feat(wallet)_: Implement Manual Wallet Reload Functionality

ui/app/AppLayouts/Wallet/controls/TokenSelector.qml
- fix crash deep in ListView section handling; turns out ListView doesn't like `section.property` being empty
Fixes #15445
TokenSelector, SwapModal
[Záznam obrazovky z 2024-07-04 00-51-14.webm](https://github.com/status-im/status-desktop/assets/5377645/b60e1413-2d04-4c8c-a37a-15d042cee3ad)
- new code, no risk
- Try a search and delete characters
Tick **one**:
=> fix(TokenSelector): Crash when try to search token in SwapModal

storybook/pages/DAppsWorkflowPage.qml, storybook/pages/WCUriInputPage.qml, ui/imports/shared/popups/walletconnect/PairWCModal/WCUriInput.qml, ui/imports/shared/popups/walletconnect/PairWCModal/qmldir
Closes #14675.
Implemented loading state for uri processing .
WCUriInput
=> feat(dapps): Implemented Loading state while processing URL

ui/StatusQ/src/StatusQ/Components/StatusListItem.qml, ui/imports/shared/popups/send/views/TokenListView.qml
- Adjusted StatusListItem height to account for scrollbar visibility by adding 16 pixels to contentHeight when tags are visible.
- Set tagsScrollBarVisible to true in TokenListView to ensure the scrollbar is displayed as needed.
fixes: #13620 
- Wallet
- UI components related to StatusListItem and TokenListView
The user will have a proper scrollbar that doesn't overlap with tags underneath when tags are visible.
1. navigate to wallet -> chose any account
2. at the bottom click send
3. if you have account with balances too big you will start to see scrollbar
Tick …
=> fix(wallet)_: SendModel scrollbar overlaps with tokens

src/nim_status_client.nim, vendor/DOtherSide/lib/include/DOtherSide/DOtherSide.h, vendor/DOtherSide/lib/src/DOtherSide.cpp
Requires: https://github.com/status-im/nimqml/pull/58
Advantages:
1. QML/Qt logs will appear in file logs, not just terminal
2. Add timestamps to each message
3. Display with colour in terminal
Disadvantages:
1. The text has to be a `static[string]`. It means I have to put it to the
```nim
let qtMessage = "binding loop" # coming from C++/QML as variable
warn "qt message", qtMessage
warn qtMessage
```
2. There's a file already in the log properties. Adding another one is a bit of a mess:
```
file=nim_status_client.nim:93 text="qrc:/imports/shared/stores/PermissionsStore.qml:98:9: Unable to assign [undefined] to QAbstractItemModel*" file=qrc:/imports/shared/stores/PermissionsStore.qml line=98
```
logs
=> Redirect qt logs to nim-chronicles

src/app/modules/shared_modules/wallet_connect/controller.nim, src/app_service/service/wallet_connect/service.nim, src/backend/wallet_connect.nim, storybook/pages/DAppsWorkflowPage.qml, storybook/qmlTests/tests/tst_DAppsWorkflow.qml, ui/app/AppLayouts/Wallet/controls/DappsComboBox.qml, ui/app/AppLayouts/Wallet/panels/DAppsWorkflow.qml, ui/app/AppLayouts/Wallet/services/dapps/DAppsListProvider.qml, ui/app/AppLayouts/Wallet/services/dapps/WalletConnectSDK.qml, ui/app/AppLayouts/Wallet/services/dapps/WalletConnectService.qml, ui/imports/shared/popups/walletconnect/controls/DAppDelegate.qml, ui/imports/shared/stores/DAppsStore.qml
Changes
- `HEAD` fix(dapps) fail to process a transaction if missing the usual fields
- `HEAD~1` feat(dapps) update persistence from the SDK on sessions refresh
- `HEAD~2` feat(dapp) disconnect wallet connect dapps
=> feat(dapp) disconnect wallet connect dApps

storybook/pages/DappsComboBoxPage.qml, ui/imports/shared/popups/walletconnect/DAppsListPopup.qml
Changes:
1. Updating alignments
2. Adding scrolling effects
3. Updating storybook page
DApps
https://github.com/status-im/status-desktop/assets/47811206/70d18353-c83e-412f-9f81-2b35906abac9
UX improvements
Storybook:
Open `DAppsComboBoxPage`
App:
Enable `FLAG_DAPPS_ENABLED=1`
Open dApps combo box from wallet header
Tick **one**:
=> feat(dApps): Fine-tune dAppsListPopup

src/app/modules/main/browser_section/current_account/module.nim, src/app/modules/main/wallet_section/accounts/module.nim, src/app/modules/main/wallet_section/all_collectibles/module.nim, src/app/modules/main/wallet_section/all_tokens/module.nim, src/app/modules/main/wallet_section/assets/module.nim, src/app/modules/main/wallet_section/buy_sell_crypto/module.nim, src/app/modules/main/wallet_section/module.nim, src/app/modules/main/wallet_section/overview/module.nim, src/app/modules/main/wallet_section/saved_addresses/module.nim, src/app/modules/main/wallet_section/send/module.nim
Closes: #15035 
The app is crashing when the QVariant set as module context property gets collected. Not sure why it happens more often in the onboarding flow and on windows.
1. Integrate `nim-libbacktrace` to help debugging nim crashes where there is no call stack provided by nim and analyse if we can use it on release builds or only for debugging purposes.
Once we release the app there will be no way to debug such crashes unless we reproduce. And even then it's very difficult to do and time consuming.
Wallet
=> fix: Fixing windows crash after onboarding

src/app/modules/shared_models/message_model.nim, storybook/pages/StatusMessagePage.qml, ui/StatusQ/src/StatusQ/Components/StatusMessage.qml, ui/StatusQ/src/StatusQ/Components/StatusMessageHeader.qml, ui/imports/shared/views/chat/MessageView.qml, ui/imports/utils/Constants.qml
Closes https://github.com/status-im/status-desktop/issues/15293
1. Show corresponding icon and text for message outgoing state: sending/sent/delivered/error
2. Improve UI of the sending error and `Resend` button
3. Make the expire time calculation "live" using `StatusSharedUpdateTimer`
4. Lock `Delivered` state. 
There's a bug that `Delivered` state change to `Sent` at some point. 
The reasons for this should be fixed on status-go side anyway:
- https://github.com/status-im/status-go/issues/5464
chat
https://github.com/status-im/status-desktop/assets/25482501/345dc8f8-7db3-408b-b809-5a6880e5f79e
https://github.com/status-im/status-desktop/assets/25482501/67969c64-cbcf-45ea-bab4-c13623f0474d
With no internet connection and expire time set to 10 seconds (normal time 3 minutes): …
=> feat: display message outgoing state

test/e2e/conftest.py
I started executing autotests on Windows and tests were failing because of screenshot name on failure was exceeding the 256 chars limit on Windows platform, so the PR is just enhancing the way we name the screenshot on failure for tests
UI end-to-end tests
=> chore: use uuid in screenshot name instead of timestamp to make the filename smaller

storybook/pages/SendModalPage.qml, storybook/pages/SendRecipientInputPage.qml, storybook/qmlTests/tests/tst_SendRecipientInput.qml, storybook/src/Models/WalletSendAccountsModel.qml, storybook/stubs/AppLayouts/Wallet/stores/TokensStore.qml, storybook/stubs/AppLayouts/Wallet/stores/WalletAssetsStore.qml, storybook/stubs/shared/stores/send/TransactionStore.qml, ui/StatusQ/include/StatusQ/QClipboardProxy.h, ui/StatusQ/include/StatusQ/stringutilsinternal.h, ui/StatusQ/src/QClipboardProxy.cpp, ui/StatusQ/src/StatusQ/Controls/StatusClearButton.qml, ui/StatusQ/src/StatusQ/Controls/StatusInput.qml, ui/StatusQ/src/StatusQ/Core/Utils/StringUtils.qml, ui/StatusQ/src/stringutilsinternal.cpp, ui/imports/shared/popups/send/SendModal.qml, ui/imports/shared/popups/send/controls/SendRecipientInput.qml, ui/imports/shared/popups/send/controls/qmldir, ui/imports/shared/popups/send/models/SendModalAssetsAdaptor.qml, ui/imports/shared/popups/send/views/RecipientView.qml, ui/imports/shared/popups/send/views/TabAddressSelectorView.qml
(Separate commits to unbreak SendModal in StoryBook)
- some minor visual fixes (padding & clear button color)
- make it always paste plain text, eventhough the base component has to stay RichText
- use it in SendModal->RecipientView
- add a storybook page
- added QML tests
Fixes https://github.com/status-im/status-desktop/issues/15252
SendModal->RecipientView->SendRecipientInput
SendRecipientInput component:
Used in SendModal:
=> chore(SendModal): factor out and create new `SendRecipientInput` component 

src/app_service/service/keycard/service.nim
I've tested this and was able to reproduce it, but it was nothing wrong in the code implementation itself, it's up to the keycard lib low-level things. What we're doing, when the user clicks to run any flow, we ensure that it can be run successfully by calling the cancel flow immediately before it, but in some cases even the cancel flow is called it doesn't invalidate all the things on the lib side if at the moment when we run next flow, because of that we may see `"already running"` response, so in this PR we just delay the next flow call for 200ms after calling the cancel flow. Tested the app a lot after it and couldn't reproduce the issue.
Fixes: #15113
=> fix: can't proceed further when clicking back button on any of keycards screens

ui/imports/shared/popups/send/controls/GasSelector.qml
feat(@desktop/wallet): Display for L1 fees on a transaction as per design
fixes #14208
show l1  and l2 fees for optimism as per new design https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=22652-265707&mode=design&t=FzBHjGy3ckdRF9mn-4
SendModal
https://github.com/status-im/status-desktop/assets/60327365/db109729-3f8d-434d-b45e-9fee5c57b105
User will be able to see the L1 and L2 fee distinction more clearly as shown in the attached video
Try to launch SendModal and …
=> feat(@desktop/wallet): Display for L1 fees on a transaction as per design

storybook/pages/DAppsWorkflowPage.qml, ui/app/AppLayouts/Wallet/panels/DAppsWorkflow.qml, ui/app/AppLayouts/Wallet/services/dapps/WalletConnectService.qml, ui/app/AppLayouts/Wallet/services/dapps/types/Pairing.qml, ui/imports/shared/popups/walletconnect/PairWCModal.qml, ui/imports/shared/popups/walletconnect/PairWCModal/WCUriInput.qml
Found out while testing that in some corner cases there will be no response of error in case of pairing. This is handled now by showing a generic error message. The implementation is using a timer to handle this case.
Extend the logic to report errors in the pairing process.
https://github.com/status-im/status-desktop/assets/47554641/7ca91b1c-0db0-475e-994a-1809d0743ddb
=> feat(dapp) handle pairing errors or timeout if no response

test/e2e/gui/components/back_up_your_seed_phrase_popup.py, test/e2e/gui/components/community/create_community_popups.py, test/e2e/gui/components/wallet/back_up_your_seed_phrase_popup.py, test/e2e/gui/components/wallet/wallet_account_popups.py, test/e2e/gui/elements/scroll.py, test/e2e/gui/mocked_keycard_controller.py, test/e2e/gui/objects_map/names.py, test/e2e/gui/screens/community_settings.py, test/e2e/gui/screens/community_settings_tokens.py, test/e2e/gui/screens/messages.py, test/e2e/gui/screens/settings.py, test/e2e/gui/screens/settings_advanced.py, test/e2e/gui/screens/settings_keycard.py, test/e2e/gui/screens/settings_password.py, test/e2e/gui/screens/settings_profile.py, test/e2e/gui/screens/settings_wallet.py
- Reworked scroll method, created 2 new methods - one for scrolling up and one for scrolling down
- Replaced all verticall_scroll_to to verticall_scroll_down (because we always scroll down in our tests for now)
The advantages of these methods:
- they never scroll infinitely, always till the end (or till the beginning) of scroll view object
- the object is always 100% visible, before it happened that only top of the object was visible
I also left old methods, if all will be good, we will just delete them later
CI runs:
https://ci.status.im/job/status-desktop/job/e2e/job/manual/2281/
https://ci.status.im/job/status-desktop/job/e2e/job/manual/2283/
=> chore: reworked scroll method

test/e2e/gui/components/profile_popup.py, test/e2e/gui/screens/community.py, test/e2e/gui/screens/onboarding.py, test/e2e/gui/screens/settings_wallet.py, test/e2e/tests/messages/test_messaging_group_chat.py, test/e2e/tests/online_identifier/test_online_identifier.py
- Reworked some methods to make tests more stable on CI
- Also reworked edit_network test to make it fail on correct step (but didn't fix it yet, need to investigate further)
- Increased timeout in a couple of buttons when click
CI run:
https://ci.status.im/job/status-desktop/job/e2e/job/manual/2273/ (fails are known - waku issues, edit network, which will be fixed later, need to investigate)
=> chore: changes for tests stability

ui/StatusQ/src/StatusQ/Components/private/statusMessage/StatusTextMessage.qml
Issue #15291
I moved replacing newline to bridge [pr](https://github.com/status-im/matterbridge/pull/13)
Here, I fixed wrong displaying of "edited" keyword. I found this during testing.
It is a different problem, but let's kill 2 birds with 1 stone.
=> fix(@desktop/chat): fix edited keyword for bridged messages

storybook/src/Models/WalletAccountsModel.qml, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapModalAdaptor.qml, ui/app/AppLayouts/Wallet/stores/RootStore.qml
Fixes #15471
We only filtered out watch only accounts, but we also need to make sure it was a fully imported account, ie an account that is usable, hence why using `canSend`. It is the same property they use in the SendTransaction modal
All wallet accounts (seedAccount is the one that wasn't fully imported back):
Available shared addresses:
=> fix(sharedAddress): hide non fully imported accounts from shared address

storybook/qmlTests/tests/tst_SwapModal.qml, storybook/stubs/shared/stores/CurrenciesStore.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapModal.qml
fixes #15505
show total fees on the swap modal on swap modal when approval is needed
SwaoModal
https://github.com/status-im/status-desktop/assets/60327365/144802e2-4539-4ecd-8185-fbbd403f4704
The fees for actual swap in this recording was very low and hence the total fees with approval gets approx rounded off!
<!-- Uncomment this section for status-go upgrade/dogfooding pull requests
Tick **one**:
=> feat(@desktop/wallet): Show total fees instead of approval fees if aproval is needed on the swapmodal

storybook/qmlTests/tests/tst_SwapModal.qml, ui/app/AppLayouts/Wallet/panels/SwapInputPanel.qml
fixes #15418
Entering numbers such as 0.00001 and deleting last character leads to text being set to 0
Also for a number like 100.01, deleting last character leads to text being set to 0
also when deleting a single digit number like 1, it sets to 0 instead of empty text.
This PR fixes above mentioned issues and also adds qml tests so that the issue doesnt come back
SwapModal
https://github.com/status-im/status-desktop/assets/60327365/aeba0e78-c065-45ef-b8a8-36d03aa2ef27
<!-- Uncomment this section for status-go upgrade/dogfooding pull requests
What is the impact of these changes on the end user (before/after …
=> fix(@desktop/wallet): Fixing issue in deleting characters from Input area

src/app/global/feature_flags.nim
Add feature flag for dapps connector
fixes #15550
Add feature flag for dapps connector. This is common practice for adding a feature flag. The feature flag will be able to be used in QML
- NA
By using a feature flag, the end user will not see any impact on new under development feature
- NA
Tick **one**:
=> feat(@desktop/wallet): Add connector Feature Flag

test/e2e/configs/_local.ci.py, test/e2e/configs/_local.default.py, test/e2e/conftest.py, test/e2e/fixtures/aut.py, test/e2e/gui/main_window.py
So now environment variable for keycard controller set only for keycard tests. For the rest it's turned off and no need to handle keycard controller.
For now I enabled only 1 keycard test, will work on the rest as a separate task
CI runs:
keycard test - https://ci.status.im/job/status-desktop/job/e2e/job/manual/2298/
critical tests - https://ci.status.im/job/status-desktop/job/e2e/job/manual/2299/
=> Separate environment for keycard tests

Makefile
adds `run-linux-gdb` task to the makefile.
When executed, this tasks runs the app binary in gdb to enable capturing the backtrace and doing other debugging actions.
No user impact
=> chore: add gdb run task for linux

ui/imports/shared/popups/send/SendModal.qml
This PR updates the SendModal.qml to filter out non-transferable (soulbound) collectibles from the send model, ensuring only transferable collectibles are displayed when sending.
* wallet
https://github.com/user-attachments/assets/eab29664-3b93-407d-9bba-f13c3b5e0bc3
The changes will ensure users only see transferable collectibles in the send model, improving user experience by preventing attempts to send non-transferable items.
1. Open the send modal in the wallet.
2. Ensure that only transferable (non-soulbound) collectibles are displayed.
3. Verify that non-transferable (soulbound) collectibles are filtered out. …
=> fix(wallet)_: filter out non-transferable collectibles in send modal

src/app/core/signals/remote_signals/wallet.nim, ui/app/AppLayouts/Wallet/popups/swap/SwapModal.qml
fixes #15509
status-go part: https://github.com/status-im/status-go/pull/5506
QA note: Please check for side impacts cause here -> Check that getting routes / route error didn't break for the other types of txs (Send, Bridge). No need to perform the Tx, just the getting routes part.
Lets user fetch swap proposals even when they dont have sufficient balance. 
SwapModal
https://github.com/user-attachments/assets/f7f55248-d0a0-4daa-a8f7-cdd60129005a
<!-- Uncomment this section for status-go upgrade/dogfooding pull requests
- How should one …
=> fix(@desktop/wallet): Swap:: calculate proposal even if amount entered is more than balance

test/e2e/fixtures/testrail.py, test/e2e/tests/communities/test_communities_channels.py
Close #15564 
Remove reference to the test case which was not present in project directory , therefore nightly test runs were always failing on pre setup
**TODO**: refactor Testrail fixture: add error handling and do not fail the pre setup if test run was not created. This will be done separately as it requires re-writing the whole test rail integration logic
Test run with the fix https://ethstatus.testrail.net/index.php?/runs/view/17279
Jenkins job https://ci.status.im/job/status-desktop/job/e2e/job/manual/2317/
End to end tests
=> chore: temp remove the wrong test case reference

test/e2e/constants/links.py, test/e2e/tests/messages/test_messaging_link_previews.py
Replace old references in test of links preview
Tests
https://ci.status.im/job/status-desktop/job/e2e/job/manual/2319/
=> tests: fix broken reference in links preview test

src/app/modules/main/chat_section/module.nim, ui/app/mainui/Popups.qml
Fixes #15526
Fixes the import popup showing the wrong state. That was because a param was removed from the function, but not from the call to that function, so `true` was passed in `invitationPending` when it shouldn't have.
I also added a call to `spectateCommunity` before the community intro popup so that the community spectated beforee sending the request
[importPopupFix.webm](https://github.com/user-attachments/assets/18c6f99d-b2ad-4cf9-b80c-90426ff5b6f6)
=> fix(import): fix import community popup

storybook/pages/GenericValidatorPage.qml, ui/StatusQ/CMakeLists.txt, ui/StatusQ/include/StatusQ/genericvalidator.h, ui/StatusQ/src/genericvalidator.cpp, ui/StatusQ/src/plugin.cpp
It exposes `QValidator` to QML world in a fully generic way. The custom validator can be created easily on UI side by providing expression for `validate` property.
- provides new `GenericValidator` component with basic docs
- registers `Validator` type - it gives possibility of strong typing of validators taken as a dependency
- Storybook page with a few examples
Closes: #15581
`StatusQ`
[Screencast from 15.07.2024 15:31:16.webm](https://github.com/user-attachments/assets/09ab5a52-164e-4b42-8b4b-9a6f5a94d513)
=> StatusQ: QValidator fully exposed to QML

ui/app/AppLayouts/Wallet/WalletLayout.qml, ui/imports/shared/popups/send/SendModal.qml, ui/imports/shared/popups/send/views/NetworkSelector.qml, ui/imports/shared/popups/send/views/NetworksAdvancedCustomRoutingView.qml, ui/imports/shared/popups/send/views/NetworksSimpleRoutingView.qml
Fixes #15629
- Fixes issue when opening `BridgeModal`. Preselected recipient object assignement was wrong.
- Fixes issue showing available networks in `Simple` tab.
- Small UI fixes to be more accurate with new design and solve some UX issues like the one commented [here](https://github.com/status-im/status-desktop/issues/15216#issuecomment-2202911932)
Opening Bridge Modal
https://github.com/user-attachments/assets/79f41041-c57b-438c-8724-8f221390800a
- What kind of user flows should be checked? Opening `BridgeModal` from the flows it can be open and be able to see the networks in `Simple` tab
=> fix(Wallet/BridgeModal): Incorrect preselected recipient value

test/e2e/gui/screens/settings_wallet.py
Fixed the issue with raising error
CI run:
https://ci.status.im/job/status-desktop/job/e2e/job/manual/2361/
All tests are green after this change, but we need to see how tests will behave in nightly and investigate if the issue will appear again.
=> Raise Assertion error correctly

ci/Jenkinsfile.linux, ci/Jenkinsfile.linux-nix
Just enable keycard mock lib as we have tests now for it. I want it only in nightly builds. 
@siddarthkay pls help me to confirm it will happen only in nightly builds for now
=> ci: enable keycard mock lib as there are now tests running for it

storybook/pages/SwapSignModalPage.qml, storybook/qmlTests/tests/tst_SwapSignModal.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapModal.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapSignModal.qml
#15553 , #15605 
reset output params when any of the values in the form changes and 
wrong value when amount entered with more that 4 decimal places in SwapSignModal
SwapModal.qml, SwapSignModal.qml
https://github.com/user-attachments/assets/cb27ce1f-126f-4daa-b450-d29a8d492738
https://github.com/user-attachments/assets/2c8868cf-7cb5-4d17-9933-64318e2adfa6
=> [SwapModal]: Fix for can approve Swap with no amount entered Fix/15553

storybook/pages/TokenListPopupPage.qml, ui/app/AppLayouts/Profile/panels/SupportedTokenListsPanel.qml, ui/app/AppLayouts/Profile/popups/TokenListPopup.qml, ui/app/AppLayouts/Wallet/stores/TokensStore.qml, ui/imports/utils/Constants.qml
fixes #14366
Modified TokenListPopup to use Constants.supportedTokenSources to match to known Token sources for the popup title similarly to the logic for Token Source Image (SNT/UNI/Default)
TokenListPopup
=> fix: Removed duplicated text in Token Popup by reusing existing supportedTokenSources mapping

ui/StatusQ/src/StatusQ/Controls/StatusSeedPhraseInput.qml
Fixes: #15478
For the Popup component inside StatusSeedPhraseInput `contentHeight` was calculated incorrectly (it contained top and bottom margins of the popup). Previous logic was calculating `height`, therefore margins had to be included.
StatusQ.Controls.StatusSeedPhraseInput
https://github.com/user-attachments/assets/8b7f3ab7-26d5-4892-b314-314c8210fd4a
=> fix(SeedPhrasePopup): fixed popup size when there is 1 item in the list.

storybook/pages/ModelEntryPage.qml, ui/StatusQ/include/StatusQ/modelentry.h, ui/StatusQ/src/modelentry.cpp, ui/StatusQ/tests/tst_ModelEntry.cpp, ui/app/AppLayouts/Wallet/WalletLayout.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapModal.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapModalAdaptor.qml, ui/app/AppLayouts/Wallet/stores/RootStore.qml, ui/app/AppLayouts/Wallet/views/RightTabView.qml, ui/imports/shared/views/AssetsViewAdaptor.qml
Closes #15554 
Changes:
1. [chore(ModelEntry): Emit itemChanged event when the ModelEntry points …](https://github.com/status-im/status-desktop/commit/3d135d9a730c925d3b9f6bcbc5625a0088071660)
Adding `itemChanged` signal when ModelEntry points to another row in the model
2. [fix(Swap): Fixing the account balance in the swap modal](https://github.com/status-im/status-desktop/commit/39e72f071c61ba11ba17663fb8987fc7ccdb5eb3)
The root cause of this issue is the improper computation of the  `accountBalance`  expression role in the accounts model. Its value depends on another model (`filteredBalancesModel`) and by the time the expression role gets computed the proper `balance ` is not ready in the `filteredBalancesModel`.
This is a quick fix, but maybe the real fix should be restructuring the …
=> [Wallet] Review and fix potential failures of AccountSelector, NetworkFilter and ModelEntry

src/app/modules/shared_modules/collectibles/controller.nim, storybook/pages/CollectiblesViewPage.qml, storybook/pages/SendModalPage.qml, ui/app/AppLayouts/Browser/BrowserLayout.qml, ui/app/AppLayouts/Communities/panels/MintTokensSettingsPanel.qml, ui/app/AppLayouts/Communities/panels/OverviewSettingsPanel.qml, ui/app/AppLayouts/Communities/popups/TransferOwnershipPopup.qml, ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml, ui/app/AppLayouts/Wallet/WalletLayout.qml, ui/app/AppLayouts/Wallet/panels/WalletFooter.qml, ui/app/AppLayouts/Wallet/stores/RootStore.qml, ui/app/AppLayouts/Wallet/views/CollectiblesView.qml, ui/app/AppLayouts/Wallet/views/RightTabView.qml, ui/app/AppLayouts/Wallet/views/TransactionDetailView.qml, ui/app/mainui/AppMain.qml, ui/app/mainui/Popups.qml, ui/imports/shared/controls/AccountSelector.qml, ui/imports/shared/popups/send/SendModal.qml, ui/imports/shared/stores/send/TransactionStore.qml, ui/imports/shared/views/HistoryView.qml, ui/imports/utils/Global.qml
closes #15217
This PR goes through all places where Send modal can be invoked from and fixes the identified issues.
General rules used when pre-filling the Send modal:
1. If the Send modal is launched in the context of an account, the account is pre-selected
2. If the Send modal is not launched in the context of an account, the first account in the list is pre-selected
3. If the Send modal is launched in the context of an asset, the asset is pre-selected
4. If the Send modal is launched in the context of a collectible, the collectible and owning account is pre-selected.
5. If the Send modal is launched in the context of a transaction, the account, receiver, token and about is pre-selected.
"Repeat transaction" when an airdrop is selected. Will be handled in …
=> 15217 UI   wallet stability ensure  review all the entry points for send

src/app/core/signals/remote_signals/connector.nim, src/app/core/signals/remote_signals/signal_type.nim, src/app/core/signals/signals_manager.nim, src/app/core/signals/types.nim, src/app/modules/main/wallet_section/module.nim, src/app/modules/main/wallet_section/view.nim, src/app/modules/shared_modules/connector/controller.nim, src/app_service/service/connector/service.nim, src/backend/connector.nim, ui/app/AppLayouts/Wallet/services/dapps/DappsConnectorSDK.qml, ui/app/AppLayouts/Wallet/services/dapps/qmldir, ui/app/AppLayouts/Wallet/stores/RootStore.qml, ui/app/AppLayouts/Wallet/views/NetworkSelectorView.qml, ui/app/mainui/AppMain.qml, ui/imports/shared/popups/walletconnect/ConnectDAppModal.qml, ui/imports/shared/popups/walletconnect/private/ContextCard.qml
Create connection between connector service and status-desktop and handle request account, as well as `reject`, `connect` flows and post connect flows.
fixes https://github.com/status-im/status-desktop/issues/15179
- A popup for DappsConnector is added for the account request flow
[Screencast from 2024-07-19 11-52-05.webm](https://github.com/user-attachments/assets/c1660ac3-dc82-40d8-8002-a98a3b6e7062)
- The user will be able to validate connection requests on the Status-desktop upon sending a `eth_requestAccounts` from a client
- The user will be able to reject connection requests on the Status-desktop upon sending a `eth_requestAccounts` from a client
[🔉 This PR requires status-go to work, I didn't associate the status-go PR since the status-go contains more than the request accounts …
=> feat(connector)_: create connection between connector service and status-desktop + request account workflow

src/app/modules/main/wallet_section/send/controller.nim, src/app/modules/main/wallet_section/send/io_interface.nim, src/app/modules/main/wallet_section/send/module.nim, src/app/modules/main/wallet_section/send/view.nim, src/app_service/service/transaction/service.nim, storybook/pages/SendModalPage.qml, storybook/pages/SwapModalPage.qml, storybook/qmlTests/tests/tst_SwapModal.qml, storybook/stubs/shared/stores/send/TransactionStore.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapModal.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapModalAdaptor.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapOutputData.qml, ui/app/AppLayouts/Wallet/stores/SwapStore.qml, ui/imports/shared/popups/send/SendModal.qml, ui/imports/utils/Constants.qml
Closes #14956
status-go part: https://github.com/status-im/status-go/pull/5540
Add different error messages in Swap modal when error codes are returned by the router.
Swap modal
https://github.com/user-attachments/assets/3d203189-e837-44d5-b2ce-b88276cafba7
There's an issue with the buy button not resizing properly when the text is longer. 
To be fixes separately here: https://github.com/status-im/status-desktop/issues/15687
=> feat(swap): added more explicit error messages

src/app/modules/main/wallet_section/networks/view.nim, ui/app/AppLayouts/Chat/ChatLayout.qml, ui/app/AppLayouts/Communities/panels/AirdropsSettingsPanel.qml, ui/app/AppLayouts/Communities/panels/MintTokensSettingsPanel.qml, ui/app/AppLayouts/Communities/panels/NetworkWarningPanel.qml, ui/app/AppLayouts/Communities/panels/qmldir, ui/app/AppLayouts/Communities/popups/BurnTokensPopup.qml, ui/app/AppLayouts/Communities/popups/RemotelyDestructPopup.qml, ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml, ui/app/AppLayouts/Communities/views/EditAirdropView.qml, ui/app/AppLayouts/Communities/views/EditCommunityTokenView.qml, ui/app/AppLayouts/Wallet/stores/RootStore.qml
Fixes #15507
Makes sure to enable the network where the owner token was minted before minting or airdroping a token. This makes sure that the account selector shows the right balance and there is no ETH error before doing the transation
[activate-network.webm](https://github.com/user-attachments/assets/49c60a4b-3f7d-4ae3-a431-8c74d438c434)
=> fix(networks): enable network before mint or airdrop

src/app_service/service/keycard/service.nim, src/backend/accounts.nim, src/constants.nim
With the help of build flags this PR sleep for 0.7 seconds before we make calls to the following status-go functions that crash on intel MacOS.
- `keycard_go.keycardInitFlow`
- `keycard_go.keycardCancelFlow`
- `status_go.initializeApplication`
As per my investigations this crash happens due to a race condition and was not consistently reproducible. Sometimes it would happen and other times it would not.
I know for sure it used to happen in these places and adding a tiny sleep before calling them made sure that the crashes weren't reproducible for me.
I think a 2.1 second delay during onboarding would be acceptable vs the existing condition of the desktop app straight up crashing.
fixes: #15134
=> chore: sleep a little to avoid race conditions on intel

ui/app/mainui/AppMain.qml
Reverts changes introduced by #15565 the connector integration that were loading the SDK asynchronously. Not sure why it isn't working though.
Wallet Connect, Dapps Connector
Connect a wallet connect dApp or check the existing connections
Tick **one**:
=> fix(dapps) restore loading of Wallet Connect SDK

ui/imports/shared/views/SyncingCodeInstructions.qml, ui/imports/shared/views/SyncingDeviceView.qml
Iterates: #14668
Settings/Sync
Device list:
Instructions:
Sync code:
SB:
=> fix(Sync): unbreak sync instructions page layout

ui/imports/shared/popups/send/SendModal.qml
It was about `cryptoValueToSendFloat` property which doesn't exist in the new `AmountToSendNew` component.
Fixes: #15699
=> fix: recalculation is not happening when changing amounts in custom bridge flow

src/app/global/local_app_settings.nim, src/app_service/service/metrics/service.nim, storybook/pages/MetricsEnablePopupPage.qml, test/e2e/gui/components/onboarding/share_usage_data_popup.py, test/e2e/gui/main_window.py, test/e2e/gui/objects_map/names.py, test/e2e/gui/objects_map/settings_names.py, test/e2e/gui/screens/onboarding.py, test/e2e/gui/screens/settings.py, test/e2e/tests/settings/test_settings_back_up_seed.py, ui/app/AppLayouts/Communities/popups/CreateCategoryPopup.qml, ui/app/AppLayouts/Onboarding/OnboardingLayout.qml, ui/app/AppLayouts/Onboarding/stores/StartupStore.qml, ui/app/AppLayouts/Onboarding/views/KeysMainView.qml, ui/app/AppLayouts/Onboarding/views/WelcomeView.qml, ui/app/AppLayouts/Profile/ProfileLayout.qml, ui/app/AppLayouts/Profile/stores/ProfileSectionStore.qml, ui/app/AppLayouts/Profile/views/PrivacyAndSecurityView.qml, ui/app/AppLayouts/Profile/views/qmldir, ui/app/mainui/AppMain.qml, ui/imports/shared/popups/MetricsEnablePopup.qml, ui/imports/shared/popups/qmldir, ui/imports/shared/stores/MetricsStore.qml, ui/imports/shared/stores/qmldir, ui/imports/utils/Constants.qml, ui/imports/utils/Global.qml, ui/main.qml
Add new settings page for metrics management - Privacy and security
Showing metrics popup: 1. on welcome screen, 2. on Settings/Privacy page and 3. after login when the popup has not been shown yet
Remember whether metrics popup was shown: metrics_popup_seen added to local settings.
Issue #15628
https://github.com/user-attachments/assets/769e5871-ba73-44aa-9a40-80db99482700
https://github.com/user-attachments/assets/64adda39-6e6e-472b-a946-658378a5a54c
=> 15628 metrics after update

ui/StatusQ/include/StatusQ/objectproxymodel.h, ui/StatusQ/src/objectproxymodel.cpp
Investigating https://github.com/status-im/status-desktop/issues/15324 it was noticed that there is unnecessary `const_cast` used, which can be easily removed.
Closes: #15744
=> StatusQ(ObjectProxyModel): const_cast removed from proxyObject method

src/app/modules/main/module.nim, src/app_service/service/transaction/service.nim
When swapping the notification showed from to token symbo and amount.
This PR fixes that
SwapModal notifications
**`Swap ERC20`**
https://github.com/user-attachments/assets/5d2a0e12-bf1a-432a-870a-43bf71d7b59e
**`Swap ETH`**
https://github.com/user-attachments/assets/f8df0046-7cd4-47f7-a108-ad808c29cb15
**`Approve ERC20`**
https://github.com/user-attachments/assets/09aa01f9-0924-4e27-b0fb-fda1ec6f7bee
=> fix(@desktop/wallet): Fix for notification showing from to token symbol and to token amount

src/app/global/feature_flags.nim
This PR turns on the feature flag for Connector
- Any screen will be able to see popup  when triggered for `request account` or `sign transacation` from a DApp or equivalent
Refer to : 
- [Create connection](https://github.com/status-im/status-desktop/pull/15565)
- [Sign transaction](https://github.com/status-im/status-desktop/pull/15662)
User will now be able to request connection with account and/oor sign transactions
Please refer to above PR's for testing
No specific risks.
Tick **one**:
=> feat(connector)_: turn feature flag on

ui/app/mainui/AppMain.qml
Closes #15545 
Postponing walletconnect service loader until main app becomes visible, similarly to the walletLoader's logic. This is needed to prevent "sign popup" from showing up during app loading when there is an active request from one of the connected dApps 
Wallet Connect
https://github.com/user-attachments/assets/6b67e48a-1c33-4aec-bcde-c73e317aad4d
End users will observe the Sign Request if there is one, only after the app fully starts, and the splash screen finishes.
Please check the videos at https://github.com/status-im/status-desktop/issues/15545 , but instead of crashing the app just after connecting to the Rarible dApp, just quit the Status app, and start it again.
Tick **one**:
=> fix(dApps): sign popup appears during splash screen

ui/imports/shared/popups/send/SendModal.qml
This PR unblocks sending `0` in `SendModal`.
Note: When providing `0` routes are not found, it requires further investigation probably on status-go side.
Closes: #15720
[Screencast from 23.07.2024 11:00:12.webm](https://github.com/user-attachments/assets/f6496c63-c59b-4e8d-8ca3-e44218cb406c)
`SendModal`
=> fix(SendModal): Allow to send 0

src/backend/wallet_connect.nim, storybook/qmlTests/tests/tst_DAppsWorkflow.qml, ui/app/AppLayouts/Wallet/services/dapps/DAppsListProvider.qml, ui/app/AppLayouts/Wallet/services/dapps/DAppsRequestHandler.qml, ui/app/AppLayouts/Wallet/services/dapps/WalletConnectService.qml, ui/app/AppLayouts/Wallet/services/dapps/helpers.js
`HEAD` fix(dapps): filter out dApps connected on other profiles
- Add helper function to filter out dApps with sessions that don't have any supported account in the available accounts list.
- Use helper function to filter out dApps connected on other profiles when listing dApps in the dApps list.
- When disconnecting an app only disconnect sessions for the current profile.
`HEAD~1` fix(dapps) don't show Wallet Connect state from other profiles
- Ignore session requests events that include accounts in other profiles
`HEAD~2` fix(dapps) minor wallet connect fixes and improvements
- don't report error in case of status-go returning nil instead
of an empty array.
- fix misleading alias to AmountsArithmetic
- minor improvements requested in previous discussions
`dApps`
maybe connector …
=> fix(dapps): isolate wallet connect functionality for profile

ui/app/AppLayouts/Wallet/popups/swap/SwapModal.qml, ui/imports/shared/controls/ErrorTag.qml
- also limit the max width in order for the ErrorTag not to overflow the modal width
Fixes #15687
SwapModal, ErrorTag
=> fix(SwapModal): Buy button not resizing with text

ui/app/AppLayouts/Wallet/services/dapps/DappsConnectorSDK.qml
Wallet team updated the SessionRequestResolved.qml component adding a required param : `prepareData` which caused the Connector service sign request popup to render incorrectly.
Wallet PR that added required parameter : https://github.com/status-im/status-desktop/pull/15645
- Connector popup screen
- Screenshot before the fix
- Screenshot after the fix
No impact
- Launch an instance of status-desktop
- Use postman or equivalent to send a `eth_sendTransaction` request
```bash
{
"jsonrpc": "2.0",
"id": 37,
"method": "connector_callRPC",
"params": [
"{\"method\": \"eth_sendTransaction\", \"params\":[{\"from\":\"0x013233bcfdc038f1c73f1ab0643ed5a676c3dd6a\",\"to\":\"0x6f29cea3011904b143dea3a09f736f8cbf83c0c9\",\"gas\":\"0x41c0\",\"gasPrice\":\"0x4a0\",\"value\":\"0x8ac7230489e80000\",\"nonce\": …
```
=> fix missing required param to fix sign request popup display

ci/Jenkinsfile.linux, ci/Jenkinsfile.linux-nix, test/e2e/conftest.py, test/e2e/fixtures/aut.py, test/e2e/gui/components/community/community_channel_popups.py, test/e2e/gui/components/settings/block_user_popup.py, test/e2e/scripts/utils/local_system.py
- Disabled keycard mock in nightly until bug is fixed
- Added fixture to close all running apps before session if there are any
- Increased timeout for clicking some buttons
- There are still a couple of fails, will continue investigation
CI run:
https://ci.status.im/job/status-desktop/job/e2e/job/manual/2398/allure/
=> Fix some nightly fails and disabled keycard mock in nightly

storybook/qmlTests/tests/tst_ConnectDAppModal.qml, storybook/qmlTests/tests/tst_DAppsWorkflow.qml, ui/app/AppLayouts/Wallet/panels/DAppsWorkflow.qml, ui/app/AppLayouts/Wallet/services/dapps/WalletConnectService.qml, ui/app/AppLayouts/Wallet/services/dapps/helpers.js, ui/app/AppLayouts/Wallet/services/dapps/types/Pairing.qml, ui/imports/shared/popups/walletconnect/PairWCModal.qml, ui/imports/shared/popups/walletconnect/private/ContextCard.qml
fixes: #15591
fixes: #15638
fixes: #15594
fixes: #15673
`HEAD` fix(dapps) emoji in wallet connect uri error
`HEAD~1` feat(dapps) don't allow user selection of networks while connecting
`HEAD~2` fix(dapps) Wallet Connect url validation
- When the pairing response is received the UX is validated and after half second UX is moved to the approval process (`ConnectedDAppModal`)    
- The static url validation state `Pairing.errors.ok` was directly responsible for the validation action in UX. With current change the validation is now based on the pairing response.
`HEAD~3`  fix(dapps) unsupported protocol Wallet Connect corner case
- We have no easy way to check the protocol and provide a customized error message. Therefore we generalizes the error message to network not supported.
=> fix(dapps) various UX fixes for Wallet Connect

storybook/pages/DappsComboBoxPage.qml, ui/imports/shared/popups/walletconnect/controls/DAppDelegate.qml
Closes #15593
1. If there is no name provided via WC API, name would be extracted from the dApp url
2. If there is no url for dApp icon provided, it will be constructed based on dApp name, similarly to  Wallet User avatar component [15593](https://github.com/status-im/status-desktop/issues/15593#issuecomment-2236471549) . 
dApp DAppDelegate
-For now (according to [15593](https://github.com/status-im/status-desktop/issues/15593) yearn.fi does not provide neither name nor icon, so its a good candidate to test the fallback logic.
Fallback dApp icon changed from "dapp" to avatar-like icon constructed based on dApp name.
Fallback dApp name will now depend on dApp url
=> fix(dApps): Added default dApp icon according to the new spec. Extracting dApp name from its url, if no name is provided through walletconnect API.

storybook/qmlTests/tests/tst_SwapInputPanel.qml, storybook/qmlTests/tests/tst_SwapModal.qml, ui/app/AppLayouts/Wallet/panels/SwapInputPanel.qml, ui/imports/shared/popups/send/SendModal.qml
- This commit temporarily disable the MaxAmount button in the `SwapInputPanel` and `SendModal` components.
- The MaxAmount button will be reintroduced with the correct behavior in issue #15709 for the 2.31 release.
- closes: #15710
* sendModal
* swapModal
Tick **one**:
=> fix(wallet)_: Temporarily disable Max Amount button pending #15709

src/app/modules/main/wallet_section/send/controller.nim, src/app/modules/main/wallet_section/send/module.nim, src/app/modules/main/wallet_section/send/view.nim, src/app_service/service/wallet_account/service_token.nim
This PR fixes the issue where the SendModal incorrectly displays "No gas" for multi-chain transactions, despite having sufficient gas.
closes: #15681 
blocked by: https://github.com/status-im/status-go/pull/5581
* Wallet
* SendModal
Users will no longer see incorrect "No gas" messages in the SendModal when performing multi-chain transactions. The UI will now accuratel
Tick **one**:
=> feat(Wallet)_: Support Multi-Chain Gas Fee Calculation in SendModal to Resolve No Gas Display Issue

test/e2e/gui/objects_map/settings_names.py, test/e2e/gui/screens/settings_wallet.py
Removed condition for scroll, because for some reason test always considered button edit network as visible. So now tests always scroll to this button and all good.
CI run:
https://ci.status.im/job/status-desktop/job/e2e/job/manual/2428/allure/#suites/c6abfc71b8927eeb22d04f5e7f84bb0e/a28d19583c11aa60/
=> Fix scroll to edit network button

ui/app/AppLayouts/Profile/popups/WakuNodesModal.qml, ui/app/AppLayouts/Profile/popups/WakuStoreModal.qml
Fixes #14929
Correct fix should be done as part of https://github.com/status-im/status-go/issues/5597 after dependency tasks are done
Hides "add waku node" buttons until https://github.com/status-im/status-go/issues/5597 is completed 
https://github.com/user-attachments/assets/cd590a82-2932-4511-b5b2-f738bbc205f8
=> fix(wakunodes): temporarily hide "add waku nodes" in advanced settings

ui/StatusQ/src/StatusQ/Controls/StatusSwitchTabButton.qml, ui/app/AppLayouts/Wallet/WalletUtils.qml, ui/imports/shared/popups/send/SendModal.qml, ui/imports/shared/popups/send/views/NetworkSelector.qml, ui/imports/shared/popups/send/views/NetworksSimpleRoutingView.qml, ui/imports/utils/Constants.qml
This PR brings `status-go` changes which close #15693
- https://github.com/status-im/status-go/pull/5615
and also introduces displaying routing errors in the UI, which closes #15396 
Closes #15396 #15693
How it was
Now
=> chore: build the error reporting mechanism

storybook/qmlTests/tests/tst_ConnectDAppModal.qml, ui/imports/shared/popups/walletconnect/ConnectDAppModal.qml
- wrap the contents into a scroll view and don't hardcode the height
Fixes #15592
ConnectDAppModal
[Záznam obrazovky z 2024-07-29 10-43-51.webm](https://github.com/user-attachments/assets/1acb2cf7-8012-4597-9ff3-beac285da702)
=> fix(ConnectDAppModal): add scrolling

storybook/qmlTests/tests/tst_SwapModal.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapModal.qml
fixes #15784
The auto refresh occurred even though approval was pending
SwapModal
https://github.com/user-attachments/assets/bdfd1b55-4f5a-4ebb-b173-ad32a7aea98e
=> fix(@desktop/wallet): Swap "Approve" button becomes enabled before Approve Tx succeeds/fails

src/app_service/service/accounts/dto/create_account_request.nim, src/app_service/service/accounts/service.nim
This only affects new accounts. Existing accounts have already these flags set via migrations
Requires: https://github.com/status-im/status-go/pull/5570
=> chore: set missing message verification and confirmation for message sent enabled by default

storybook/pages/DAppSignRequestModalPage.qml, ui/imports/shared/popups/walletconnect/DAppSignRequestModal.qml, ui/imports/shared/popups/walletconnect/panels/ContentPanel.qml
- fixes text overflowing the box height
Fixes #15650
DAppSignRequestModal
[Záznam obrazovky z 2024-07-29 14-32-39.webm](https://github.com/user-attachments/assets/e454d3ab-8088-4e0f-a86c-1f584c63b9cd)
=> fix(DAppSignRequestModal): correctly compute text painted height

storybook/qmlTests/tests/tst_DAppsWorkflow.qml, ui/app/AppLayouts/Wallet/services/dapps/DAppsListProvider.qml, ui/app/AppLayouts/Wallet/services/dapps/DAppsRequestHandler.qml, ui/app/AppLayouts/Wallet/services/dapps/DappsConnectorSDK.qml, ui/app/AppLayouts/Wallet/services/dapps/WalletConnectService.qml, ui/app/AppLayouts/Wallet/services/dapps/qmldir
Closes: #15814
Adjusted the logic of disconnect function as it takes not an array of session item, but an object with keys as session ids:
```
{
"c7d3ddc6ff973a4f3f22084f5f728d9f47d75c4f213b108ec9af9673e970d724": {
"acknowledged": true,
"controller": "1d2847b79ce6a08638bc4be0b1e872686c2f8ce153896f16972331725d776d63",
"expiry": 1722426933,
...
},
"deb300dd977a07d1ef56f7080051d6833f47eb6f1d58380280598ff72aa4180a": {
"acknowledged": true,
....
}
}
```
Also renamed Helpers to DAppsHelpers in order to avoid QtQuick runtime name clashes with other Helpers (e.g from send)
dApps
https://github.com/user-attachments/assets/a6292806-a2ae-43d9-a65b-31ecf8c55911
Now it is possible to disconnect from dApps directly from the …
=> fix(dApps): Improved logic for disconnecting of dApps in the app.

test/e2e/constants/links.py, test/e2e/tests/messages/test_messaging_link_previews.py
Cherry-pick 7a2584dde45a870706431bed22a49e9139fcd118
Tests
=> [cherry-pick]: Fix link preview

ui/imports/shared/popups/walletconnect/DAppsListPopup.qml
Fixes(partially): #15595.
Allowed connected dApps list to grow in height as much as possible (max height will be the height of the app window). That will allow the end user to see and disconnect with more dApps without the need to scroll. The scroll of ListView using some mouse wheels and some touchpad devices is working incorrectly. It looks like there were several attempts of Qt company to fix that problem, but issue still occurs at least on macOS and Qt5.15.13
dApps
=> fix(dApps): improved logic for the connected dApps list to always display as many dApps as possible.

ui/imports/shared/popups/send/SendModal.qml, ui/imports/shared/popups/send/views/NetworkCardsComponent.qml
This PR fixes a bug in the wallet's transaction flow where the send button was not disabled when the router encountered router errors, leading to failed transactions. It also adds a visual indicator (red arrow) for networks that lack sufficient gas for a transaction, providing more helpful feedback to users.
Closes #15700 #15701
* SendModal.qml
* NetworkCardsComponent.qml
- Users will no longer be able to initiate a transaction when the router detects errors, preventing failed transactions and potential loss of funds.
- Users will receive clearer feedback about why a network is unsuitable for a transaction (e.g., …
=> fix(wallet)_: Disable send button on router errors & visually indicate gas issues

ui/app/AppLayouts/Onboarding/views/KeysMainView.qml, ui/app/AppLayouts/Profile/stores/ProfileSectionStore.qml, ui/app/AppLayouts/Profile/views/SyncingView.qml, ui/imports/shared/views/SyncingEnterCode.qml
Fixes #15871
Adds a beta tag to the pairing screens on onboarding and settings
=> chore(beta): add beta tag to pairing screens

src/app/modules/main/wallet_section/controller.nim, src/app/modules/main/wallet_section/io_interface.nim, src/app/modules/main/wallet_section/module.nim, src/app/modules/main/wallet_section/view.nim, src/app/modules/shared_modules/add_account/controller.nim, src/app/modules/shared_modules/add_account/io_interface.nim, src/app/modules/shared_modules/add_account/module.nim, src/app/modules/shared_modules/add_account/view.nim, src/app_service/service/wallet_account/service.nim, src/backend/backend.nim, ui/StatusQ/src/StatusQ/Core/StatusIconWithTooltip.qml, ui/StatusQ/src/StatusQ/Core/qmldir, ui/StatusQ/src/statusq.qrc, ui/app/AppLayouts/Wallet/popups/AddEditSavedAddressPopup.qml, ui/app/AppLayouts/Wallet/stores/RootStore.qml, ui/imports/shared/popups/addaccount/panels/WatchOnlyAddressSection.qml, ui/imports/shared/popups/addaccount/stores/AddAccountStore.qml
Related `status-go` PR:
- https://github.com/status-im/status-go/pull/5629
Closes #15772 
Closes #15779 
https://github.com/user-attachments/assets/2387a5a9-feb7-400b-b3fd-4d44b1a7b75b
=> feat: checksum validation added when adding saved address and watch only address

ui/app/AppLayouts/Onboarding/views/KeysMainView.qml, ui/app/AppLayouts/Profile/stores/ProfileSectionStore.qml, ui/app/AppLayouts/Profile/views/SyncingView.qml, ui/imports/shared/views/SyncingEnterCode.qml
Fixes #15871
Cherry-pick of https://github.com/status-im/status-desktop/pull/15873
Adds a beta tag to the pairing screens on onboarding and settings
=> [CHERRY-PICK] chore(beta): add beta tag to pairing screens (#15873)

src/app_service/service/accounts/dto/create_account_request.nim, src/app_service/service/accounts/service.nim
cherry-pick of https://github.com/status-im/status-desktop/pull/15774
Status-go PR: https://github.com/status-im/status-go/pull/5631
=> [CHERRY-PICK] chore: set missing message verification and confirmation for message sent enabled by default

ui/StatusQ/src/StatusQ/Components/StatusDraggableListItem.qml, ui/app/AppLayouts/Profile/stores/ProfileStore.qml, ui/app/AppLayouts/Profile/views/MyProfileView.qml
Fixes #15904
[cancel.webm](https://github.com/user-attachments/assets/d2f067a1-80bc-4b45-90b0-c74840d43685)
=> fix(profile): fix canceling modifications in the profile

storybook/qmlTests/tests/tst_ConnectDAppModal.qml, ui/app/AppLayouts/Wallet/controls/NetworkFilter.qml, ui/imports/shared/popups/walletconnect/ConnectDAppModal.qml, ui/imports/shared/popups/walletconnect/private/ContextCard.qml, ui/imports/shared/popups/walletconnect/private/DAppCard.qml, ui/imports/shared/popups/walletconnect/private/PermissionsCard.qml
- set the correct widths and elide mode
- fixup the visuals of the NetworkFilter combo box (to disable it w/o making it look disabled)
- fix passing the connection status down to DAppCard
ConnectDAppModal
=> fix(ConnectDAppModal): don't overflow texts

ui/app/AppLayouts/Wallet/stores/WalletAssetsStore.qml, ui/imports/shared/popups/send/SendModal.qml
- Implemented a bridgeableGroupedAccountAssetsModel in WalletAssetsStore.qml to dynamically filter assets based on their bridgeability.
closes: #15697
- WalletAssetsStore.qml
- SendModal.qml
Before:
- Non-bridgeable assets were displayed in the Bridge Modal, potentially causing confusion.
- Users could select non-bridgeable assets, leading to errors or failed transactions.
After:
- Only bridgeable assets are displayed in the Bridge Modal, ensuring a streamlined and error-free selection process.
- Users will not be able to choose assets that are incompatible with the Bridge, preventing unnecessary confusion and errors. …
=> fix(wallet)_: Filter non-bridgeable assets in Bridge Modal

storybook/qmlTests/tests/tst_SwapModal.qml, ui/app/AppLayouts/Wallet/panels/SwapInputPanel.qml
fixes #15818
The issue was only visible when formatting was with , separator such as DE etc, not visible when locale is EN
Ive adapted the logic so that its locale agnostic and also added tests so that the issue is not reintroduced in the future. 
SwapModal.qml
https://github.com/user-attachments/assets/6ad41e30-9050-4d83-84f2-927000dec3f4
=> fix(@desktop/wallet): Swap modal - Pay input amount - deleting 1 decimal deletes the entire number

src/app/modules/main/module.nim
Fixes #15835
Evaluate if we have notification on app start (when chats are loaded) so that the notification icon can be shown if we open the app **not** in the chat (eg in the wallet)
[notif.webm](https://github.com/user-attachments/assets/deb59d00-30ab-4a8e-bdd8-14650d57ab21)
=> fix(notif-indicator): evaluate the notifications on app start

ui/StatusQ/include/StatusQ/concatmodel.h, ui/StatusQ/src/concatmodel.cpp, ui/StatusQ/tests/tst_ConcatModel.cpp
- adds flag `propagateResets` with default value `false` to have ability to change behavior of the proxy whenever one of concatenated source models emit `modelAboutToBeReset`/`modelReset` signals. So far those events were translated into removals/insertions on the concat model. Now, by setting `propagateReset` to `true` it's possible to change it and propagate source's resets as reset from the proxy model itself.
- amends tests
Closes: #15891
`ConcatModel`
=> StatusQ/ConcatModel:  flag added changing behavior on source model's reset

storybook/qmlTests/tests/tst_ConnectDAppModal.qml, ui/app/AppLayouts/Wallet/controls/NetworkFilter.qml, ui/imports/shared/popups/walletconnect/ConnectDAppModal.qml, ui/imports/shared/popups/walletconnect/private/ContextCard.qml, ui/imports/shared/popups/walletconnect/private/DAppCard.qml, ui/imports/shared/popups/walletconnect/private/PermissionsCard.qml
BACKPORT of PR https://github.com/status-im/status-desktop/pull/15889
- set the correct widths and elide mode
- fixup the visuals of the NetworkFilter combo box (to disable it w/o making it look disabled)
- fix passing the connection status down to DAppCard
ConnectDAppModal
=> [CHERRY-PICK]fix(ConnectDAppModal): don't overflow texts

src/app/modules/shared_models/keypair_account_model.nim, src/app_service/service/wallet_account/service_account.nim
Cherrypick of https://github.com/status-im/status-desktop/pull/15841 for release
=> [CHERRY-PICK] fix(wallet): Update preferred networks even when empty (#15841)

src/app/modules/main/module.nim
Fixes #15835
Cherry-pick of https://github.com/status-im/status-desktop/pull/15872
Evaluate if we have notification on app start (when chats are loaded) so that the notification icon can be shown if we open the app **not** in the chat (eg in the wallet)
=> [CHERRY-PICK] fix(notif-indicator): evaluate the notifications on app start (#15872)

storybook/pages/AssetsViewPage.qml, ui/StatusQ/src/wallet/managetokenscontroller.cpp, ui/StatusQ/src/wallet/managetokensmodel.h, ui/app/AppLayouts/Wallet/controls/ManageTokenMenuButton.qml, ui/app/AppLayouts/Wallet/controls/ManageTokensDelegate.qml, ui/app/AppLayouts/Wallet/views/RightTabView.qml, ui/app/mainui/Popups.qml, ui/imports/shared/views/AssetsView.qml, ui/imports/utils/Global.qml
- partially reuse the already available Global/Popups methods to hide assets (which also emit proper notifications); those are needed as another shared modal from Popups uses it too (may come from outside of Wallet)
- some warnings cleanup in the controller
Fixes #15777
Wallet
[Záznam obrazovky z 2024-07-25 12-47-15.webm](https://github.com/user-attachments/assets/c4fb2926-1da7-4356-9ef1-2e89093953f9)
=> fix(Wallet): Hiding assets from wallet's main view doesn't work

storybook/pages/DAppSignRequestModalPage.qml, storybook/pages/SwapApproveCapModalPage.qml, storybook/pages/SwapSignModalPage.qml, storybook/qmlTests/tests/tst_DAppsWorkflow.qml, storybook/qmlTests/tests/tst_SwapApproveCapModal.qml, storybook/qmlTests/tests/tst_SwapSignModal.qml, storybook/stubs/shared/stores/CurrenciesStore.qml, ui/StatusQ/src/StatusQ/Validators/AmountValidator.qml, ui/app/AppLayouts/Wallet/panels/DAppsWorkflow.qml, ui/app/AppLayouts/Wallet/popups/SignTransactionModalBase.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapApproveCapModal.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapModal.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapSignModal.qml, ui/app/AppLayouts/Wallet/services/dapps/DAppsRequestHandler.qml, ui/app/AppLayouts/Wallet/services/dapps/DappsConnectorSDK.qml, ui/imports/shared/popups/send/SendModal.qml, ui/imports/shared/popups/send/views/AmountToSendNew.qml, ui/imports/shared/popups/walletconnect/DAppSignRequestModal.qml, ui/imports/shared/popups/walletconnect/DAppsListPopup.qml, ui/imports/shared/stores/CurrenciesStore.qml
- format Big decimal numbers correctly according to the current locale; some precision loss is tolerated here for the display purposes
- fixes wrong decimal separators in some places and aligns with the standard in terms of number of decimals, as everywhere else in the app
Fixes #15612
Fixes #15790
SwapApproveCapModal, SwapSignModal, DAppSignRequestModal
=> fix: inconsistent/incorrect decimal value formatting

ui/imports/shared/popups/addaccount/states/Main.qml
closes: #15933 
- Wallet -> addAccount
User will not be able to add new watch only accounts
Tick **one**:
=> fix(wallet): Disable adding new watch-only accounts

storybook/pages/SendModalPage.qml, storybook/src/Models/NetworksModel.qml, ui/imports/shared/popups/send/SendModal.qml, ui/imports/shared/popups/send/views/NetworksSimpleRoutingView.qml
- use a plain StatusListView instead of a nested ScrollView -> Repeater -> Column
- cleanups and fixes in mocked models and stores to unbreak showing the networks/routing in storybook
Fixes #15902
SendModal, NetworksSimpleRoutingView
[Záznam obrazovky z 2024-08-02 11-03-33.webm](https://github.com/user-attachments/assets/a602a54e-374d-45ca-a203-9838799beffc)
=> fix(SendModal): Bridge modal Simple mode's scroll is very clunky

storybook/pages/DAppSignRequestModalPage.qml, storybook/pages/SwapApproveCapModalPage.qml, storybook/pages/SwapSignModalPage.qml, storybook/qmlTests/tests/tst_DAppsWorkflow.qml, storybook/qmlTests/tests/tst_SwapApproveCapModal.qml, storybook/qmlTests/tests/tst_SwapSignModal.qml, storybook/stubs/shared/stores/CurrenciesStore.qml, ui/StatusQ/src/StatusQ/Validators/AmountValidator.qml, ui/app/AppLayouts/Wallet/panels/DAppsWorkflow.qml, ui/app/AppLayouts/Wallet/popups/SignTransactionModalBase.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapApproveCapModal.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapModal.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapSignModal.qml, ui/app/AppLayouts/Wallet/services/dapps/DAppsRequestHandler.qml, ui/app/AppLayouts/Wallet/services/dapps/DappsConnectorSDK.qml, ui/imports/shared/popups/send/SendModal.qml, ui/imports/shared/popups/send/views/AmountToSendNew.qml, ui/imports/shared/popups/walletconnect/DAppSignRequestModal.qml, ui/imports/shared/popups/walletconnect/DAppsListPopup.qml, ui/imports/shared/stores/CurrenciesStore.qml
Backport of PR https://github.com/status-im/status-desktop/pull/15920
- format Big decimal numbers correctly according to the current locale; some precisions loss is tolerated here for the display purposes
- fixes wrong decimal separators in some places and aligns with the standard in terms of number of decimals, as everywhere else in the app
Fixes #15612
Fixes #15790
=> [CHERRY-PICK] fix: inconsistent/incorrect decimal value formatting

storybook/pages/AssetsViewPage.qml, ui/StatusQ/src/wallet/managetokenscontroller.cpp, ui/StatusQ/src/wallet/managetokensmodel.h, ui/app/AppLayouts/Wallet/controls/ManageTokenMenuButton.qml, ui/app/AppLayouts/Wallet/controls/ManageTokensDelegate.qml, ui/app/AppLayouts/Wallet/views/RightTabView.qml, ui/app/mainui/Popups.qml, ui/imports/shared/views/AssetsView.qml, ui/imports/utils/Global.qml
Backport of PR https://github.com/status-im/status-desktop/pull/15811
- partially reuse the already available Global/Popups methods to hide assets (which also emit proper notifications); those are needed as anotehr shared modal from Popups uses it too (may come from outside of Wallet)
- some warnings cleanup in the controller
Fixes #15777
=> [CHERRY-PICK] fix(Wallet): Hiding assets from wallet's main view doesn't work

storybook/qmlTests/tests/tst_SwapInputPanel.qml, storybook/qmlTests/tests/tst_SwapModal.qml, ui/app/AppLayouts/Wallet/adaptors/TokenSelectorViewAdaptor.qml, ui/app/AppLayouts/Wallet/panels/SwapInputPanel.qml
fixes #15785
cherry-pick of https://github.com/status-im/status-desktop/pull/15927
=> [CherryPick]:: fix(@desktop/wallet): fix for Swap Input parameters reset when balances are reloaded

storybook/pages/StatusBetaTagPage.qml, ui/StatusQ/src/StatusQ/Components/StatusBetaTag.qml, ui/StatusQ/src/StatusQ/Components/StatusNavigationListItem.qml, ui/StatusQ/src/StatusQ/Components/StatusSmartIdenticon.qml, ui/StatusQ/src/StatusQ/Controls/StatusToolTip.qml, ui/app/AppLayouts/Profile/panels/MenuPanel.qml, ui/app/AppLayouts/Profile/stores/ProfileSectionStore.qml, ui/app/AppLayouts/Profile/views/SyncingView.qml, ui/app/AppLayouts/Profile/views/WalletView.qml, ui/app/AppLayouts/Profile/views/wallet/MainView.qml, ui/app/AppLayouts/Wallet/WalletLayout.qml, ui/app/AppLayouts/Wallet/controls/TokenSelectorNew.qml, ui/app/AppLayouts/Wallet/panels/WalletFooter.qml, ui/app/mainui/activitycenter/panels/ActivityCenterPopupTopBarPanel.qml, ui/imports/shared/views/HistoryView.qml, ui/imports/utils/Utils.qml
- display additional beta information as a tooltip
- don't overlap the Beta badge with the unread msg indicator
- some minor cleanups & fixes
Fixes #15795
Fixes #15929
Badge and beta tag together:
Activity beta banner:
Settings/ENS:
Setting/Wallet/Account order:
Settings/Wallet/Manage tokens:
Activity center:
Settings/Syncing:
=> fix: Add additional information to the Beta tags

storybook/pages/DAppsWorkflowPage.qml, storybook/pages/DappsComboBoxPage.qml, storybook/qmlTests/tests/tst_DAppsWorkflow.qml, ui/app/AppLayouts/Wallet/panels/WalletHeader.qml, ui/app/AppLayouts/Wallet/services/dapps/DAppsListProvider.qml, ui/app/AppLayouts/Wallet/services/dapps/WalletConnectService.qml, ui/app/AppLayouts/Wallet/services/dapps/helpers.js, ui/imports/shared/popups/walletconnect/DAppsListPopup.qml
Backport of https://github.com/status-im/status-desktop/pull/15877
1. Hiding DApps button on not supported wallet account selection
2. Filtering DApps in connected dApps list based on account selection
closes: #15589
closes: #15647
=> [CHERRY-PICK] fix(dApps): Improved handling of connected dApps.

storybook/pages/StatusBetaTagPage.qml, ui/StatusQ/src/StatusQ/Components/StatusBetaTag.qml, ui/StatusQ/src/StatusQ/Components/StatusNavigationListItem.qml, ui/StatusQ/src/StatusQ/Components/StatusSmartIdenticon.qml, ui/StatusQ/src/StatusQ/Controls/StatusToolTip.qml, ui/app/AppLayouts/Profile/panels/MenuPanel.qml, ui/app/AppLayouts/Profile/stores/ProfileSectionStore.qml, ui/app/AppLayouts/Profile/views/SyncingView.qml, ui/app/AppLayouts/Profile/views/WalletView.qml, ui/app/AppLayouts/Profile/views/wallet/MainView.qml, ui/app/AppLayouts/Wallet/WalletLayout.qml, ui/app/AppLayouts/Wallet/controls/TokenSelectorNew.qml, ui/app/AppLayouts/Wallet/panels/WalletFooter.qml, ui/app/mainui/activitycenter/panels/ActivityCenterPopupTopBarPanel.qml, ui/imports/shared/views/HistoryView.qml, ui/imports/utils/Utils.qml
Backport of PR https://github.com/status-im/status-desktop/pull/15977
- display additional beta information as a tooltip
- don't overlap the Beta badge with the unread msg indicator
- some minor cleanups & fixes
Fixes #15795
Fixes #15929
=> [CHERRY-PICK] fix: Add additional information to the Beta tags

storybook/pages/DAppsWorkflowPage.qml, storybook/pages/DappsComboBoxPage.qml, storybook/qmlTests/tests/tst_DAppsWorkflow.qml, ui/app/AppLayouts/Wallet/panels/WalletHeader.qml, ui/app/AppLayouts/Wallet/services/dapps/DAppsListProvider.qml, ui/app/AppLayouts/Wallet/services/dapps/WalletConnectService.qml, ui/app/AppLayouts/Wallet/services/dapps/helpers.js, ui/imports/shared/popups/walletconnect/DAppsListPopup.qml
fix(dApps): Improved handling of connected dApps.
closes: https://github.com/status-im/status-desktop/issues/15589
closes: https://github.com/status-im/status-desktop/issues/15647
1. Hiding DApps button on not supported wallet account selection
2. Filtering DApps in connected dApps list based on account selection
dApps
https://github.com/user-attachments/assets/e8d21d57-3af4-4b27-b4fa-5e94eff17f97
End users can see DApps button only when either all accounts are selected, or supported wallet address is selected (non watched, not keycard accounts).
In addition to that, the dApps list will show only dApps connected to the selected wallet address
Please create several wallet accounts, at least 1 watched address and 1 keycard address
🚀
=> 15647 dapps watched accounts and keycard accounts shouldnt be considered for wallet connect interactions

ci/Jenkinsfile.tests-e2e
aligned CI resolution with development environments
fix for resolution mismatch related issues, e.g. 
[test_settings_networks_edit_restore_defaults](https://ci.status.im/job/status-desktop/job/systems/job/linux/job/x86_64/job/tests-e2e-new/488/allure/#suites/c6abfc71b8927eeb22d04f5e7f84bb0e/d8a027187b077a1b/)
CI run with fixed tests https://ci.status.im/job/status-desktop/job/e2e/job/manual/2449/
=> test: set screen 2560x1440x24

test/e2e/gui/elements/object.py, test/e2e/tests/settings/settings_wallet/test_wallet_settings_account_order.py, test/e2e/tests/wallet_main_screen/wallet - plus button/test_plus_button_add_watched_address.py
reworks e2e tests according to product changes
- added more wait time in case if app is frozen
- https://github.com/status-im/status-desktop/issues/15933 removed "watch only accounts" as result:
- `test_change_account_order_by_drag_and_drop` reworked to include only generated accounts
- `test_plus_button_add_watched_address` skipped
=> tests: rework e2e tests according to product changes

src/app/modules/shared_modules/wallet_connect/controller.nim, src/app_service/service/wallet_connect/service.nim, src/backend/wallet_connect.nim, ui/app/AppLayouts/Wallet/services/dapps/WalletConnectService.qml, ui/imports/shared/stores/DAppsStore.qml
Fixing #15898
The disconnect notifications were operating on `WalletConnectService.currentSessionProposal`. This object stores the current session object on connect, but it's not necessarily the same session the user wants to disconnect.
To fix this I'm getting the active sessions from status-go when the disconnect request is received (from Status or dapp). If the topic matches to any connection topic owned by the users accounts we'll show a notification.
Wallet connect
https://github.com/user-attachments/assets/dc554095-02a9-4b90-9ae2-a790a82436db
Presenting to the user the correct dapp that has been disconnected.
- Wrong dapp name in the notification
1. Connect 2 dapps. ReactApp and then Rariable
2. Disconnect the first connected dapp (ReactApp)
3. Notification would say the Rariable …
=> fix(WalletConnect): Fixing disconnect notifications

ui/app/AppLayouts/Profile/views/wallet/ManageTokensView.qml, ui/app/AppLayouts/Wallet/WalletLayout.qml, ui/app/AppLayouts/Wallet/controls/TokenSelectorNew.qml, ui/app/AppLayouts/Wallet/panels/TokenSelectorPanel.qml, ui/app/AppLayouts/Wallet/stores/TokensStore.qml, ui/app/AppLayouts/Wallet/views/RightTabView.qml
- Fixes send modal to open correctly with pre-selected community-minted assets
- Fixes `TokenSelectorNew` to display icons of community minted assets properly
- Temporarily hides switch `Show community assets when sending tokens` in token management, advanced tab
- Temporarily sets fixed `true` value to `TokensStore.showCommunityAssetsInSend`
Closes: #15766 
Follow-up task: https://github.com/status-im/status-desktop/issues/15955
[Screencast from 01.08.2024 12:20:02.webm](https://github.com/user-attachments/assets/9bfb9d58-fbfa-44ce-8a7d-a3540dc737b8)
`SendModal`, `ManageTokensView`, `TokensStore`
=> fix(Wallet/SendModal): Using community assets in SendModal unblocked

src/app_service/service/accounts/dto/api_config.nim
`0.0.0.0` is dangerous. `127.0.0.1` is more than enough.
=> fix: change rpc host to localhost

src/app/core/signals/remote_signals/connector.nim, src/app/core/signals/remote_signals/signal_type.nim, src/app/core/signals/signals_manager.nim, src/app/modules/shared_modules/connector/controller.nim, src/app_service/service/connector/service.nim, src/backend/connector.nim, ui/app/AppLayouts/Wallet/services/dapps/ConnectorDAppsListProvider.qml, ui/app/AppLayouts/Wallet/services/dapps/DappsConnectorSDK.qml, ui/app/AppLayouts/Wallet/services/dapps/WalletConnectService.qml, ui/app/AppLayouts/Wallet/services/dapps/qmldir
fixes https://github.com/status-im/status-desktop/issues/15885
Waits for https://github.com/status-im/status-go/pull/5646
This PR contains the changes to be able to see the list of connected DApps on the Status desktop for Connector service. It also contains changes to managed `DAppPermissionGranted` and `DAppPermissionRevoked`
- Connected DApps list
[Screencast from 2024-08-02 01-51-36.webm](https://github.com/user-attachments/assets/4e3f9149-1c5a-459e-a75b-d8f6d07201b7)
Similar to other PR's this PR reuses some Wallet connect functionalities. I performed test to make sure Wallet Connect still works as expected
Please refer to the video to test. Please be aware that this PR requires setting the `FLAG_DAPPS_ENABLED` flag to `enabled` since it enables seeing the list of DApps.
Or use : …
=> feature(connector)_: Add model join to handle connected dApps

test/e2e/tests/wallet_main_screen/wallet - right click out of account area/test_right_click_manage_watched_address.py, ui/app/AppLayouts/Wallet/views/AccountContextMenu.qml, ui/imports/shared/popups/addaccount/states/Main.qml
Cherrypick 566a954935159caf17b1c89317f9534e84835015 and 5ac1f129e58d39dccf8e9e369402f5367bc7be4e
Closes https://github.com/status-im/status-desktop/issues/15979
Remove the possibility to add new watch accounts for production builds.
I've opted to allow watch accounts for dev purposes. We're actively using watch accounts to reproduce bugs and develop/test features on collectibles/assets we don't own.
=> [Cherry-pick] Fix/watch accounts removal master

src/app/core/signals/remote_signals/connector.nim, src/app/core/signals/remote_signals/signal_type.nim, src/app/core/signals/signals_manager.nim, src/app/modules/shared_modules/connector/controller.nim, src/app_service/service/connector/service.nim, src/backend/connector.nim, ui/app/AppLayouts/Wallet/services/dapps/ConnectorDAppsListProvider.qml, ui/app/AppLayouts/Wallet/services/dapps/DappsConnectorSDK.qml, ui/app/AppLayouts/Wallet/services/dapps/WalletConnectService.qml, ui/app/AppLayouts/Wallet/services/dapps/qmldir
cherry-pick
- https://github.com/status-im/status-desktop/pull/15954
=> feature(connector)_: Add model join to handle connected dApps (#15954)

storybook/pages/SwapModalPage.qml, ui/app/AppLayouts/Wallet/WalletUtils.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapModalAdaptor.qml, ui/imports/utils/Constants.qml
Fixes #15542
Handle "Price Impact Too High" error. Swap platforms return this when the requested swap will make the price of the token change more than X% (that means the swap is large compared to the available liquidity. https://help.crypto.com/en/articles/7891394-what-is-price-impact)
https://www.figma.com/design/TS0eQX9dAZXqZtELiwKIoK/Swap---Milestone-1?node-id=6012-83789&t=X4WCo5OrN3M9B2Se-0
=> feat(@desktop/wallet): handle Paraswap price impact error

src/app/modules/shared_modules/wallet_connect/controller.nim, src/app_service/service/wallet_connect/service.nim, src/backend/wallet_connect.nim, ui/app/AppLayouts/Wallet/services/dapps/WalletConnectService.qml, ui/imports/shared/stores/DAppsStore.qml
closes #15898
The disconnect notifications were operating on `WalletConnectService.currentSessionProposal`. This object stores the current session object on connect, but it's not necessarily the same session the user wants to disconnect. To fix this I'm getting the active sessions from status-go when the disconnect request is received (from Status or dapp). If the topic matches to any connection topic owned by the users accounts we'll show a notification.
(cherry picked from commit fea4e8ed7695acbbabf3c39da955bf4bab1962c3)
=> [Cherry-pick] fix(WalletConnect): Fixing disconnect notifications

ui/app/AppLayouts/Wallet/panels/WalletFooter.qml
- display the "Buy" button in every context in the wallet footer except when viewing a collectible's details
Fixes #15813
Wallet/Footer
=> feat(Wallet): Display the "Buy" button everywhere

ui/app/AppLayouts/Wallet/services/dapps/DAppsRequestHandler.qml
Closes https://github.com/status-im/status-desktop/issues/15898
The disconnect notifications were operating on WalletConnectService.currentSessionProposal. This object stores the current session object on connect, but it's not necessarily the same session the user wants to disconnect.
To fix this I'm getting the active sessions from status-go when the disconnect request is received (from Status or dapp). If the topic matches to any connection topic owned by the users accounts we'll show a notification.
(cherry picked from commit f73356e2e8f2c6569ea58b8ead5bb469b24c7cf0)
=> [Cherry-pick ]fix(WalletConnect): Fixing fees parsing when provided by the dApp

test/e2e/configs/system.py, test/e2e/conftest.py, test/e2e/gui/main_window.py, test/e2e/gui/screens/settings.py, test/e2e/scripts/utils/decorators.py, test/e2e/tests/communities/test_communities.py, test/e2e/tests/communities/test_communities_categories.py, test/e2e/tests/communities/test_communities_mint_owner_token.py, test/e2e/tests/communities/test_communities_permissions.py, test/e2e/tests/messages/test_messaging_1x1_chat.py, test/e2e/tests/onboarding/test_onboarding_generate_new_keys.py, test/e2e/tests/onboarding/test_onboarding_import_seed.py, test/e2e/tests/onboarding/test_onboarding_negative_scenarios.py, test/e2e/tests/onboarding/test_onboarding_syncing.py, test/e2e/tests/settings/settings_wallet/test_wallet_settings_networks_testnet_mode.py, test/e2e/tests/settings/test_ens_name_purchase.py, test/e2e/tests/settings/test_settings_back_up_seed.py, test/e2e/tests/wallet_main_screen/wallet - footer actions/test_footer_actions_send.py, test/e2e/tests/wallet_main_screen/wallet - footer actions/test_footer_actions_send_nft.py, test/e2e/tests/wallet_main_screen/wallet - right click out of account area/test_right_click_manage_watched_address.py
- fix condition to allow tests running for local build, perhaps devs could use that, since attaching to packaged build with squish is somewhat pain
- reviewed some marks for critical path, so the subset is slightly changed now, total run took 11 min. I will review other tests and perhaps add more test cases to this subset later on
=> chore: make tests running for dev build and update marks

storybook/pages/AssetsViewPage.qml, ui/app/AppLayouts/Wallet/panels/WalletFooter.qml, ui/app/AppLayouts/Wallet/stores/RootStore.qml, ui/app/AppLayouts/Wallet/views/CollectiblesView.qml, ui/app/AppLayouts/Wallet/views/RightTabView.qml, ui/imports/shared/views/AssetsView.qml
- make `swap` and `bridge` buttons not visible in collectible details view
- make `swap` and `bridge` buttons not visible in community assets details view
- make `swap` action to available in context menu when right-clicking on community minted asset in wallet main view, assets tab
> [!NOTE]
> This pr is not fixing existing problems in the code related to storing UI's temporary state in stores. It's intended to be refactored as a separate ticket.
Closes: #15952
Closes: #15931
[Screencast from 02.08.2024 11:49:55.webm](https://github.com/user-attachments/assets/b158fc1e-b888-4688-b7d5-3e920f0c2545)
=> Wallet: swap/bridge buttons visibility adjusted

ui/StatusQ/src/wallet/managetokenscontroller.cpp, ui/app/AppLayouts/Wallet/views/CollectiblesView.qml
Cherry-pick of https://github.com/status-im/status-desktop/pull/16011 from `release/2.30.x` to `master` (`f57864c46bcdaaa1f54bbe6b1b1e1039ff3d1cc4`, `28de8375eb69d56f71ecd50834f5702aee8d01fe`).
Closes: https://github.com/status-im/status-desktop/issues/15775
=> [CHERRY-PICK]: CollectiblesView: fixed crash when hiding collectibles from wallet's main view

storybook/pages/AssetsViewPage.qml, ui/app/AppLayouts/Wallet/panels/WalletFooter.qml, ui/app/AppLayouts/Wallet/stores/RootStore.qml, ui/app/AppLayouts/Wallet/views/CollectiblesView.qml, ui/app/AppLayouts/Wallet/views/RightTabView.qml, ui/imports/shared/views/AssetsView.qml
Cherry-pick of https://github.com/status-im/status-desktop/pull/15971 from `release/2.30.x` to `master` (`98cacb2d4aaa2fe2c57d761b29325df68968a139`).
Closes: #15952
Closes: #15931
=> [CHERRY-PICK]: Wallet: swap/bridge buttons visibility adjusted

ui/imports/shared/views/chat/MessageView.qml
- update the `unparsedText` after having edited the message; it is used for copying the msg text to clipboard
- some cleanups
Fixes #15129
MessageView
[Záznam obrazovky z 2024-08-08 10-39-01.webm](https://github.com/user-attachments/assets/71f8ed18-e29b-48ef-9219-752f9abefd81)
=> fix(MessageView): Clipboard after editing a message

test/e2e/tests/wallet_main_screen/wallet - footer actions/test_footer_actions_default_account_values.py
- Test for share wallet address popup verifications (user guide section) - ci run https://ci.status.im/job/status-desktop/job/e2e/job/manual/2443/allure/#suites/f59b4938eea2b74826b801325557e3dc/7375ba37ff634a5c/
- Test for verifications for default account values in send/receive/bridge popups (skipped for now, we need to think how to create a mark for such tests which pass only locally for now, but to not include them to ci runs at the same time - will be done in a separate task)
=> Share wallet address and default account values in send/receive/bridge tests

ci/Jenkinsfile.combined
In this PR we get rid of `E2E_GIT_REF` parameter which would default to `master` or whatever value is set in Jenkins.
We instead just rely on `env.BRANCH_NAME` (thanks @apentori) to run E2E tests on the same branch the build on CI is generated from.
=> ci: use current branch as git ref for E2E tests

ci/Jenkinsfile.combined
In this PR we get rid of `E2E_GIT_REF` parameter which would default to master or whatever value is set in CI. We instead just rely on `env.BRANCH_NAME` to run E2E tests on the same branch the build on CI is generated from.
=> [cherry-pick] ci: use current branch as git ref for E2E tests

test/e2e/constants/user.py, test/e2e/tests/messages/test_messaging_group_chat.py
Group chat test was using predefined user data (when all 3 users are already in contacts of each other to speed up things). However, it might be issue for waku so i decided to change the test using newly created accounts each time to be on the safe side. If the test fails (no contact requests received, etc) then we could be more confident that it is somewhat real issue in waku / messaging rather than in test itself
https://ci.status.im/job/status-desktop/job/e2e/job/manual/2454/allure/#suites/dd016288b8f9f39d70dd9d9176bfc098
UI tests
=> chore: group chat test is using newly created users to avoid potential waku issues

storybook/pages/SendModalPage.qml, ui/StatusQ/src/StatusQ/Components/StatusBetaTag.qml, ui/StatusQ/src/StatusQ/Controls/StatusSwitchTabBar.qml, ui/StatusQ/src/StatusQ/Controls/StatusSwitchTabButton.qml, ui/app/AppLayouts/Communities/popups/HoldingsDropdown.qml, ui/app/mainui/AppMain.qml, ui/imports/shared/popups/send/SendModal.qml, ui/imports/shared/popups/send/views/NetworkSelector.qml
In SendModal, hides the Custom network mode button in `production`
- manage the lifetime of the Custom tab button dynamically; setting the tab button to `visible: false` doesn't unfortunately remove it from the tab bar
- add the option to StoryBook too
2 separate commits to customize StatusBetaTag and StatusSwitchTab*
SendModal (StatusBetaTag, StatusSwitchTab*)
[Záznam obrazovky z 2024-08-10 14-47-40.webm](https://github.com/user-attachments/assets/a6ad3bcd-e32e-4f9a-a438-46afbb17a026)
=> fix(SendModal): hide the Custom network mode in `production`

ui/StatusQ/src/StatusQ/Core/Theme/ThemePalette.qml, ui/app/AppLayouts/Chat/panels/ChatAnchorButtonsPanel.qml
- unify bg color, use white as fg color, add drop shadow according to Figma
- fixup the hover color intensity
Fixes #13771
Chat
App light theme:
App dark theme:
SB light mode:
SB dark mode:
=> fix(chat): Button to go to the latest message is barely visible on dark theme

storybook/pages/SendModalPage.qml, ui/StatusQ/src/StatusQ/Components/StatusBetaTag.qml, ui/StatusQ/src/StatusQ/Controls/StatusSwitchTabBar.qml, ui/StatusQ/src/StatusQ/Controls/StatusSwitchTabButton.qml, ui/app/AppLayouts/Communities/popups/HoldingsDropdown.qml, ui/app/mainui/AppMain.qml, ui/imports/shared/popups/send/SendModal.qml, ui/imports/shared/popups/send/views/NetworkSelector.qml
Backport of PR https://github.com/status-im/status-desktop/pull/16070
In SendModal, hides the Custom network mode button in production
- manage the lifetime of the Custom tab button dynamically; setting the tab button to visible: false doesn't unfortunately remove it from the tab bar
- add the option to StoryBook too
2 separate commits to customize StatusBetaTag and StatusSwitchTab*
=> [CHERRY-PICK]fix(SendModal): hide the Custom network mode in production

ui/StatusQ/src/StatusQ/Core/Theme/ThemePalette.qml, ui/app/AppLayouts/Chat/panels/ChatAnchorButtonsPanel.qml
Backport of PR https://github.com/status-im/status-desktop/pull/16051
- unify bg color, use white as fg color, add drop shadow according to Figma
- fixup the hover color intensity
Fixes #13771
=> [CHERRY-PICK] fix(chat): Button to go to the latest message is barely visible on dark theme

ui/app/AppLayouts/Wallet/services/dapps/DAppsListProvider.qml, ui/app/AppLayouts/Wallet/services/dapps/DAppsRequestHandler.qml, ui/app/AppLayouts/Wallet/services/dapps/DappsConnectorSDK.qml, ui/app/AppLayouts/Wallet/services/dapps/WalletConnectService.qml
closes #16032
Cherry-pick #16050
There are two issues fixed by this PR:
1. Crashing on authentication while signing dapp messages. In this case the root cause was the usage of model data items stored in js. When the modal changes, the underlying data changes as well and the app would crash in the JS execution.
- The quick fix is to create deep copies for the model data to be stored in JS.
2. Fixing the desynchronisation of the dapp connection status. This issue had lots of apparently random symptoms that could have been wrongly attributed to the shared cookies!
-    The DAppsListProvider needs to receive all the user accounts so that it can process all dapps the user is connected to (the dapps filtering based on selected account is an internal impl. detail)
- Call `revokeSession` on …
=> [CHERRY-PICK] Fix WC crash and dApp connected status

src/app/modules/main/activity_center/io_interface.nim, src/app/modules/main/activity_center/module.nim, src/app/modules/main/module.nim
Fixes #16021
The problem was that the view doesn't update in a sync way, so getting the count from the view might be wrong.
This fix makes it so we have to get the count from status-go twice, which is not ideal, but to fix it, we'd need a refactor of the AC view count mechanism
I opened a refactor issue to address it at some point: https://github.com/status-im/status-desktop/issues/16023
[red-dot-ac.webm](https://github.com/user-attachments/assets/4fb00501-fb24-426a-babc-be284f213239)
=> fix(red-dot): fix getting the real state of the AC notification count

ui/StatusQ/src/StatusQ/Components/WebEngineLoader.qml, ui/app/AppLayouts/Wallet/services/dapps/DAppsRequestHandler.qml, ui/app/AppLayouts/Wallet/services/dapps/WalletConnectSDK.qml, ui/app/mainui/AppMain.qml
closes #16088
+Fixing the shared cookies issues on WalletConnect
WalletConnect
The dApp flow is completed even when the authentication fails.
Each user profile will use its own cookies for WC
1. Start a sign flow and reach the password input stage in Status
2. Hit cancel or X button.
3. The sign request should be explicitly rejected and the dApp is informed
Tick **one**:
=> Fix: Reject the sign request when cancelling the authentication method + fix cookies issue

ci/Jenkinsfile.combined, ci/Jenkinsfile.linux, ci/Jenkinsfile.linux-nix, ci/Jenkinsfile.macos, ci/Jenkinsfile.tests-e2e, ci/Jenkinsfile.tests-nim, ci/Jenkinsfile.tests-ui, ci/Jenkinsfile.windows, ci/cpp/Jenkinsfile.linux, ci/cpp/Jenkinsfile.macos, ci/cpp/Jenkinsfile.windows
This PR points to `status-jenkins-lib` version where we provide api-proxy credentials to Jenkins in CI and the desktop build would then get these env vars 
- `STATUS_BUILD_PROXY_USER`
- `STATUS_BUILD_PROXY_PASSWORD`
=> ci: build with api-proxy credentials

src/app_service/service/wallet_account/async_tasks.nim, src/app_service/service/wallet_account/service.nim, src/app_service/service/wallet_account/service_account.nim
Cherry-pick of https://github.com/status-im/status-desktop/pull/16099
* wip: make the getENSName calls async
* fix: login to the app takes forever
Resolving ens name sometimes, most likely due to network congestion can be really slow, that results in slow app loading, especially if user has more accounts, cause the app checks ens name existence for each account.
This PR does that check in an async way.
Fixes #16086
* chore: async check for ens name existence when adding new accounts
---------
=> [CHERRY-PICK] Make the getENSName calls async

ci/Jenkinsfile.tests-e2e, test/e2e/tests/settings/settings_wallet/test_wallet_settings_saved_addresses_add.py, test/e2e/tests/wallet_main_screen/wallet - saved addresses/test_saved_addresses.py
Adding env vars to prevent tests hitting 8454
=> ci: add env vars to prevent autotests hitting 8545

ci/Jenkinsfile.tests-e2e, src/app_service/service/accounts/dto/api_config.nim, src/constants.nim, src/env_cli_vars.nim, test/e2e/tests/settings/settings_wallet/test_wallet_settings_saved_addresses_add.py, test/e2e/tests/wallet_main_screen/wallet - saved addresses/test_saved_addresses.py
First step to fix https://github.com/status-im/status-desktop/issues/15846
Added 2 new CLI options: `--http-api` and `--ws-api`.
The main use case is e2e tests, which for some reason frequently fail acuirng port 8545.
=> chore_: allow disabling http/ws api from cli

src/app/global/global_events.nim, src/app/modules/main/module.nim, src/app/modules/startup/view.nim, src/app_service/service/metrics/async_tasks.nim, src/app_service/service/metrics/service.nim, ui/app/AppLayouts/Onboarding/OnboardingLayout.qml, ui/imports/shared/stores/MetricsStore.qml, ui/imports/utils/Constants.qml, ui/imports/utils/Global.qml, ui/main.qml
Fixes #16100
Adds metrics for navigating to the different screens of the onboarding and when navigating to a new section while logged in; only when enabled of course.
I refactored the code a little to make it simpler. I moved the check to see if the metrics collection is enabled in the async task itself, so we don't have to check it each time we add a new metric
=> feat(metrics): add onboarding screen metrics and section navigation

src/app/global/feature_flags.nim, src/env_cli_vars.nim
Cherry-pick of https://github.com/status-im/status-desktop/pull/16139
Also includes the fix from [the comment](https://github.com/status-im/status-desktop/pull/16139#discussion_r1720716474) by @caybro 
Fixes #16101
=> [CHERRY-PICK] chore(connector): disable connector flag and WS server by  default

src/app/global/global_events.nim, src/app/modules/main/module.nim, src/app/modules/startup/view.nim, src/app_service/service/metrics/async_tasks.nim, src/app_service/service/metrics/service.nim, ui/imports/shared/stores/MetricsStore.qml, ui/imports/utils/Constants.qml, ui/imports/utils/Global.qml, ui/main.qml
Cherry-pick of https://github.com/status-im/status-desktop/pull/16112
* feat(metrics): add onboarding screen metrics and section navigation
Fixes #16100
Adds metrics for navigating to the different screens of the onboarding and when navigating to a new section while logged in; only when enabled of course.
I refactored the code a little to make it simpler. I moved the check to see if the metrics collection is enabled in the async task itself, so we don't have to check it each time we add a new metric
=> [CHERRY-PICK] feat(metrics): add onboarding screen metrics and section navigation 

ci/Jenkinsfile.tests-e2e
Adding more output during tests execution so it is more readable real time
Only tests
=> ci: adding more output for pytest when running tests

storybook/pages/StatusButtonPage.qml, storybook/qmlTests/tests/tst_StatusButton.qml, storybook/qmlTests/tests/tst_SwapModal.qml, ui/StatusQ/src/StatusQ/Controls/StatusBaseButton.qml, ui/app/AppLayouts/Wallet/panels/WalletHeader.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapModal.qml
- add a secondary "loading" state (`loadingWithText`), that is show the loading indicator next to the text
- simplify the StatusBaseButton layout (esp. handling the overall opacity/visibility)
- add a QML test suite; the code was becoming too complex and adding a simple boolean prop was getting "dangerous"
- port the SwapModal to use the new `loadingWithText` property
Fixes #15313
Status(Base)Button
SwapModal approval pending:
Loading with text:
Loading:
=> feat(StatusButton): Add support to show text when button is loading

src/app/modules/main/module.nim, src/app/modules/main/profile_section/contacts/module.nim
Fixes #16147
Since ID verification is disabled for now, we can remove the calls to getLatestVerificationRequestFrom.
If we want to have ID verification back, we can re-add those calls, but in my opinion, it should be done better from status-go directly, or only asking for the ID verif when looking at the contact's profile
I tested with a timer and it doesn't save much on app start, but it's something. Also, it's a function that accesses the database, so it's better to not do it, and especially not that many times.
=> chore: remove calls to getLatestVerificationRequestFrom

Makefile, nix/nix.conf
Because re-building QT that we already have in cache locally is dumb.
=> fix(nix): add missing nix.conf with our binary cache

storybook/pages/StatusButtonPage.qml, ui/StatusQ/src/StatusQ/Controls/StatusBackButton.qml, ui/StatusQ/src/StatusQ/Controls/StatusBaseButton.qml, ui/app/AppLayouts/Wallet/controls/SwapExchangeButton.qml
- this fixes 2 small regressions, namely in how we calculate the background corner radius and icon size when in the mode of `isRoundIcon`
- the "Saved addresses" button in wallet's left view is very special on its own; overall we have only 3 instances of this "round" icon buttons in the whole app (only the first was affected)
Fixes #16156
StatusBaseButton
Wallet left view (Saved addresses):
Swap exchange button:
Sticker back button:
=> fix(StatusBaseButton): correct radius and icon size for `isRoundIcon` mode

storybook/pages/MetricsEnablePopupPage.qml, test/e2e/gui/objects_map/names.py, ui/app/AppLayouts/Profile/views/PrivacyAndSecurityView.qml, ui/app/mainui/Popups.qml, ui/imports/shared/popups/MetricsEnablePopup.qml, ui/imports/utils/Global.qml, ui/main.qml
- mention the "Privacy Policy" document in the text explaining "Help us improve Status", make a link to it and display it in a separate popup
- add a standalone header button to the settings page, doing the same
- extend storybook page with the "placement" param
Fixes #16157
Settings/Privacy and security
Settings:
https://github.com/user-attachments/assets/7a39fdb5-7229-40a8-98a5-0a3deb7b3b74
SB:
=> feat(Settings/Privacy and security): add Privacy Policy popup

storybook/pages/MetricsEnablePopupPage.qml, test/e2e/gui/objects_map/names.py, ui/app/AppLayouts/Profile/views/PrivacyAndSecurityView.qml, ui/app/mainui/Popups.qml, ui/imports/shared/popups/MetricsEnablePopup.qml, ui/imports/utils/Global.qml, ui/main.qml
Backport of PR https://github.com/status-im/status-desktop/pull/16164
- mention the "Privacy Policy" document in the text explaining "Help us improve Status", make a link to it and display it in a separate popup
- add a standalone header button to the settings page, doing the same
- extend storybook page with the "placement" param
Fixes #16157
=> [CHERRY-PICK] feat(Settings/Privacy and security): add Privacy Policy popup

src/app/modules/main/profile_section/notifications/controller.nim, src/app/modules/main/profile_section/notifications/view.nim, ui/app/AppLayouts/Profile/stores/NotificationsStore.qml, ui/app/AppLayouts/Profile/views/NotificationsView.qml
Fixes #16165
All the logs about `settings_notificationsGetExPersonalMentions` are only to populate the model in the Notifications settings view, so it was pointless to load them on app start. Now we lazy load them on loading that page.
An additional improvement that could be done later is to make it async and/or create a new API that gets all the DB info in one shot, because calling 4 APIs for each chat and community is a bit useless.
(the calls to all those APIs is about 0.02 seconds on my machine)
=> fix(notifs): only fetch notification exemptions when going to the page

src/app/modules/main/activity_center/controller.nim, src/app/modules/main/activity_center/io_interface.nim, src/app/modules/main/activity_center/module.nim, src/app/modules/main/activity_center/view.nim, src/app/modules/main/module.nim, src/app_service/service/activity_center/service.nim
Fixes #16023
Caches the values of the number of notifications and hasUnseen in the view so that we access status-go only when there is an update or on app start. Also, uses the response value from user actions in the AC to retrieve the hasUnseen value directly instead of re-fetching. Finally, fixes an issue where marking notifs as read/unread wouldn't update the count
[ac-count.webm](https://github.com/user-attachments/assets/b6d14b4a-5b61-4890-b800-a476112a970a)
=> fix(ac): cache ac unread count and hasUnread in the view

ui/imports/shared/stores/CommunityTokensStore.qml, ui/imports/utils/Utils.qml
(!) suboptimal solution
This issue is a regression after refactoring and sending images as localhost URLs instead of base64 (which is good)
We try to create a token and pass URL as base64 image, SaveCommunityToken(protocol/communities/manager.go) fails to read it.
To keep the old format, I'm fetching image dataUrl (base64) and passing it to the API in the expected format
owner/master token
I admit the solution is not perfect. Ideally we should update the approach and just pass the community ID and get the image from the database. Not sure how to crop it properly though. And also update status-go (DeploymentParameters and DeployOwnerToken API endpoint) …
=> fix(community): Missing community owner token image

storybook/qmlTests/tests/tst_DAppsWorkflow.qml, ui/app/AppLayouts/Wallet/services/dapps/helpers.js
There are two fixes needed here.
1. Status-go fix for unknown primitive when signing the message
2. Fix for Paraswap pairing failure due to required namespaces mismatch
Needs for: https://github.com/status-im/status-go/pull/5755
Wallet Connect
Message signing
Before:
The user could not use Paraswap services
The user could not sign messages using uint160 type
After:
The user can use Paraswap services
The user can sign messages using all types
Case 1:
Connect to Paraswap (make sure the events in requiredNamespaces.eip155.events is not empty in the pairing message)
Case 2:
Try to swap more than USDC to DAI using Uniswap. Not sure of the repro steps. Probably can be reproduced when connecting new …
=> fix(WalletConnect): Fixing sign for uniswap and paraswap

ci/Jenkinsfile.linux-nix
Nightly build have one build overriding another:
https://ci.status.im/job/status-desktop/job/nightly/
This is a easy way to fix the names.
=> ci: change Nix build filename to differentiate with regular build

src/app/core/signals/remote_signals/mailserver.nim, src/app/core/signals/signals_manager.nim
Adds back the `can not connect to store node. Retrying automatically` banner.
=> fix_: mailserver.not.working signal

test/e2e/gui/components/online_identifier.py, test/e2e/gui/objects_map/names.py, test/e2e/gui/screens/onboarding.py, test/e2e/tests/crtitical_tests_prs/test_onboarding_generate_new_keys.py, test/e2e/tests/messages/test_messaging_link_previews.py, ui/imports/shared/popups/UserStatusContextMenu.qml
Test logic is changed , instead of using pre-defined link to user profile, test now uses profile link of created account for the test. I am removing hardcoded values and improving test stability, because profile link is not unfurling (not showing display name and emoji hash) if user for this profile has not been online for 30 days (current threshold for storing info in waku)
So in short, test wont fail from now on at this screen being unable to get data from not resolved link 
CI run:
=> tests: use own profile link in messages so the information is not gone after 30 days

ci/Jenkinsfile.windows, scripts/sign-windows-bin.sh
https://learn.microsoft.com/en-us/windows/msix/package/signing-known-issues
Related to:
- https://github.com/status-im/status-desktop/issues/16199
=> chore(ci): add debug logs for windows signing

ci/Jenkinsfile.combined, ci/Jenkinsfile.linux, ci/Jenkinsfile.linux-nix, ci/Jenkinsfile.macos, ci/Jenkinsfile.tests-e2e, ci/Jenkinsfile.tests-nim, ci/Jenkinsfile.tests-ui, ci/Jenkinsfile.windows, ci/cpp/Jenkinsfile.linux, ci/cpp/Jenkinsfile.macos, ci/cpp/Jenkinsfile.windows
Related jenkins lib commit:
- [`status-jenkins-lib#9571602f`](https://github.com/status-im/status-jenkins-lib/commit/9571602f) - desktop,mobile: add proxy stage env variable
Update:
- [`status-jenkins-lib#242b8554`](https://github.com/status-im/status-jenkins-lib/commit/242b8554) - mobile: remove proxy stage env variable setup
- [`status-jenkins-lib#32dda2a7`](https://github.com/status-im/status-jenkins-lib/commit/32dda2a7) - desktop: refactor proxy stage setup
=> ci: move stage env variable setup to jenkins-lib

src/app/modules/main/chat_section/controller.nim, src/app/modules/main/chat_section/io_interface.nim, src/app/modules/main/chat_section/item.nim, src/app/modules/main/chat_section/model.nim, src/app/modules/main/chat_section/module.nim, src/app/modules/main/module.nim, src/app/modules/shared_models/section_model.nim, src/app_service/service/community/service.nim
Fixes #16181
This commit improves the time taken by onChatsLoaded that is called on login. The culprit is `buildChatSectionUI` in the chat_section module. There is no silver bullet here. It's slow because the community is big and has a lot of channels to load and generate.
This commit helps by removing some old code that was inefficient (calculating if a channel has a permission instead of just using the `tokenGated` property for example). It also adds all the section items in one go instead of one another.
There are some other small improvements, but again, no way to make it way faster. Thankfully, that time is spent with the loading spinner at the same time.
Some other improvements can be made for the login, but in other parts of the app.
=> perf(chat_section): improve onChatsLoaded performance

src/app/modules/main/wallet_section/activity/entry.nim, src/app_service/common/wallet_constants.nim, ui/app/AppLayouts/Wallet/popups/swap/SwapApproveCapModal.qml, ui/app/AppLayouts/Wallet/stores/RootStore.qml, ui/imports/utils/Constants.qml
Closes #15755
bumps status-go to get https://github.com/status-im/status-go/pull/5572
Adapt contract addresses to the ones used by Paraswap V6.2
Swap
Made Swaps on the 3 chains. 
https://etherscan.io/tx/0xcb356077e3e7c9a19bcd9a2784de8f548a4d8ce35e093d8df97ca4a0cba03e96
https://optimistic.etherscan.io/tx/0x9f4508b65109a5341f72e04d8be36b23cb0399e16be2f549610ab25d13bebc4d
https://arbiscan.io/tx/0xe8f8b3747067c139f2ca23c1ccab78b6fa953bb990aa27b85add98b5ef64517e
Approve dialog looks correct, showing the new contract address.
Swap dialog looks correct.
Fees transferred to the new Fee Vault contract on all of them
Found a UI bug while testing this, reported here: https://github.com/status-im/status-desktop/issues/16200
=> feat(wallet): upgrade paraswap api to v6.2

test/e2e/gui/components/context_menu.py, test/e2e/gui/screens/wallet.py, test/e2e/tests/communities/test_communities_channels.py, test/e2e/tests/wallet_main_screen/wallet - plus button/test_add_edit_delete_generated_account.py, test/e2e/tests/wallet_main_screen/wallet - plus button/test_plus_button_manage_account_added_for_new_generated_seed.py, test/e2e/tests/wallet_main_screen/wallet - right click on account/test_context_menu_edit_default_account.py, test/e2e/tests/wallet_main_screen/wallet - right click out of account area/test_right_click_manage_watched_address.py
1. now editing account in wallet with right click won't be flaky (as on the video below). It was clicking too fast, and accidentally closing context menu and ending up opening saved addresses instead 
https://github.com/user-attachments/assets/7a48cd31-847c-4b01-936d-41e782467e78
2. removed unnecessary encapsulation. Frankly speaking, having a separate method that will locate and click item is overhead. I simplified that (for now only for context menu class, but will do more later on, it is just less code which is great i think)
CI run, seem to be no retries https://ci.status.im/job/status-desktop/job/e2e/job/manual/2477/allure/#suites/1daca0bc81a20f2b3833d58fe035f048/a33e374caad4a93c/
Tests
=> tests: editing account with right click stabilised

ui/imports/shared/status/StatusChatImageExtensionValidator.qml, ui/imports/shared/status/StatusChatImageQtyValidator.qml, ui/imports/shared/status/StatusChatImageSizeValidator.qml, ui/imports/shared/status/StatusChatInput.qml, ui/imports/utils/Constants.qml
- re-evaluate the validators to be able to hide the warning after 3 seconds (the validators won't let the user select/paste an invalid image; it's just the warning bubble that persisted)
- some small cleanups
Fixes #16210
https://github.com/user-attachments/assets/f09bc5b0-d65f-4409-9b8d-b3df3fc63bd7
=> fix(StatusChatInput): set max number of images to 6 to align with mobile

storybook/pages/SlippageSelectorPage.qml, storybook/qmlTests/tests/tst_SlippageSelector.qml, ui/StatusQ/src/StatusQ/Controls/StatusButtonRow.qml, ui/imports/shared/controls/CurrencyAmountInput.qml, ui/imports/shared/controls/SlippageSelector.qml
- add various error/warning messages according to Figma (where it makes sense)
- letters or more than 2 decimals are caught by the internal validator so those combinations are impossible to enter
- fix marking the custom value as (in)valid
- fix selecting "Use default" after typing a custom value
- fix resetting to predefined value after typing a custom value that matches one of the predefined ones
- add regression QML tests for the above fixes
Fixes #15017
SlippageSelector, SwapModal
https://github.com/user-attachments/assets/dd09cf52-aef5-4246-ac32-56bc5e96ffc5
=> fix: Slippage Selector Issues

Makefile, config.nims, scripts/fetch-brew-bottle.sh, storybook/CMakeLists.txt
The openssl bigsur bottle has be dropped, this PR updates the Makefile so the minimum version is now Monterey
=> fix for issue breaking `make` on mac: Update macOS deployment target to 12.0 and bottle version to Monterey

ci/Jenkinsfile.windows
Otherwise signing fails with:
```
Error: SignerSign() failed." (-2146869243/0x80096005)
```
See:
- https://stackoverflow.com/questions/62161135/signersign-failed-2146869243-0x80096005
- https://github.com/electron-userland/electron-builder/issues/5166#issuecomment-663568037
=> fix(ci): add hash algoritm for Sectigo TS server

test/e2e/tests/crtitical_tests_prs/test_add_edit_delete_generated_account.py
enable test back as the corresponding issue was fixed. Enabled for both nightly and PRs
=> chore: enable back test with context menu interactions

test/e2e/gui/components/wallet/send_popup.py, test/e2e/gui/components/wallet/token_selector_popup.py, test/e2e/gui/objects_map/names.py, test/e2e/gui/screens/wallet.py, test/e2e/tests/transactions_tests/test_buy_ens_name_in_settings.py, test/e2e/tests/transactions_tests/test_wallet_send_eth.py, test/e2e/tests/transactions_tests/test_wallet_send_nft.py, ui/StatusQ/src/StatusQ/Controls/StatusInput.qml, ui/app/AppLayouts/Wallet/controls/TokenSelectorNew.qml, ui/app/AppLayouts/Wallet/panels/TokenSelectorPanel.qml
Bring back to life test for sending 0 eth. For nightly only.
CI run https://ci.status.im/job/status-desktop/job/e2e/job/manual/2486/allure/#suites/a1c3ee7c9d32765015c6799e7b8f7727/e06e69a5e6f1532d/
=> tests: test to send 0 eth

ui/StatusQ/src/StatusQ/Components/StatusNavigationListItem.qml
- fixes regression when hover wouldn't work if the menu item contained a beta tag
Fixes #16263
Settings
https://github.com/user-attachments/assets/fcd76ecd-c522-4c1f-9d2e-aa4272c0e05f
=> fix(StatusNavigationListItem): unbreak hovering over settings menu items

test/e2e/configs/__init__.py, test/e2e/constants/user.py, test/e2e/constants/wallet.py, test/e2e/tests/transactions_tests/test_buy_ens_name_in_settings.py, test/e2e/tests/transactions_tests/test_mint_owner_and_tokenmaster_tokens.py, test/e2e/tests/transactions_tests/test_wallet_send_eth.py, test/e2e/tests/transactions_tests/test_wallet_send_nft.py
- moved the funds to another account and hid it under env var
- temp disabled test to mint tokens for community as it is hardcoded to use mainnet and it is quite expensive. I will redo it to use L2 networks
=> tests: use seed phrase for account with funds under env var

ui/app/AppLayouts/Wallet/panels/DAppsWorkflow.qml, ui/app/AppLayouts/Wallet/services/dapps/DappsConnectorSDK.qml
- we are getting a colorId, so convert it
Fixes #16094
DAppSignRequestModal
=> fix(DAppSignRequestModal): correct wallet account color

test/e2e/constants/community_settings.py, test/e2e/gui/objects_map/communities_names.py, test/e2e/gui/screens/community_settings_tokens.py, test/e2e/gui/screens/settings.py, test/e2e/tests/transactions_tests/test_buy_ens_name_in_settings.py, test/e2e/tests/transactions_tests/test_mint_owner_and_tokenmaster_tokens.py, test/e2e/tests/transactions_tests/test_wallet_send_eth.py, test/e2e/tests/transactions_tests/test_wallet_send_nft.py
- test to mint community tokens is now using L2
- remove seed phrase from pytest params so it is not exposed in allure report
- removed flaky verifications of strings, i will bring them back later
CI run https://ci.status.im/job/status-desktop/job/e2e/job/manual/2495/
=> Tests: make mint token test smarter using L2 networks to mint tokens (cheaper)

ui/StatusQ/src/StatusQ/Popups/StatusAction.qml, ui/imports/shared/controls/chat/menuItems/MuteChatMenuItem.qml, ui/imports/shared/views/chat/ChatContextMenuView.qml, ui/imports/utils/Constants.qml
The "Delete my messages for viola.stateofus.eth" option is not yet supported, TBD [here](https://github.com/status-im/status-desktop/issues/14169).
Fetching messages for specific timeframes TBD [here](https://github.com/status-im/status-desktop/issues/14312)
Leaving and deleting group when being the owner TBD [here](https://github.com/status-im/status-desktop/issues/14311)
Closes #13393 
Depends on https://github.com/status-im/status-go/pull/5813
StatusChatMenu: updated menu options as per designs
StatusChatMenu
1-1 chat:
Group chat:
Community chat, admin:
Community chat, non-admin:
=> fix[StatusChatMenu]: updated menu options as per designs

storybook/qmlTests/tests/tst_EnterSeedPhrase.qml, storybook/stubs/shared/stores/BIP39_en.qml, ui/StatusQ/src/StatusQ/Controls/StatusSeedPhraseInput.qml, ui/imports/shared/panels/EnterSeedPhrase.qml
- fix for a corner case prob when there was a valid seedphrase word (e.g. cat) that is at the same time a prefix for other valid suggestions (e.g. category, catalog, ...); it was imposible to select it using Enter key or mouse click from the suggestions popup at the last field
- add a QML regression test for this issue
- use standard subcomponents (StatusDropdown, StatusListView) reducing code duplication and unifying UI/UX
Fixes #16291
StatusSeedPhraseInput
https://github.com/user-attachments/assets/2e0f8888-aba2-4cf6-832e-7a01146c7de6
=> fix(StatusSeedPhraseInput): accept a common prefix suggestion

src/app/global/utils.nim, storybook/pages/StatusChatInputPage.qml, storybook/pages/TransactionDetailViewPage.qml, storybook/qmlTests/tests/tst_StatusChatInput.qml, storybook/stubs/shared/stores/GifStore.qml, storybook/stubs/shared/stores/RootStore.qml, storybook/stubs/shared/stores/qmldir, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Chat/views/ChatColumnView.qml, ui/app/AppLayouts/Chat/views/CreateChatView.qml, ui/app/AppLayouts/stores/RootStore.qml, ui/imports/shared/status/StatusChatInput.qml, ui/imports/shared/status/StatusGifPopup.qml, ui/imports/shared/status/StatusGifPopup/ConfirmationPopup.qml, ui/imports/shared/status/StatusGifPopup/StatusGifColumn.qml, ui/imports/shared/stores/GifStore.qml, ui/imports/shared/stores/RootStore.qml, ui/imports/shared/stores/qmldir, ui/imports/shared/views/chat/MessageView.qml
This PR is very first step of bigger effort defined in https://github.com/status-im/status-desktop/issues/16246
It does initial cleanup in `shared/stores/RootStore` in order to make it non-singleton later.
- removes not used methods `hex2Dec`, `hex2Eth` and `hex2Gwei` from `nim` code and several stores where they were exposed
- moves `getSelectedTextWithFormationChars` from store to `Utils` because this method is stateless and fully backend-independent. It allowed the clean-up in `StatusChatInput`'s test and storybook page where this method was duplicated. It also reduced dependency of `StatusChatInput` on a singleton root store.
- dedicated `GifStore` excluded from shared `RootStore`
- direct usages of singleton `RootStore` removed from `StatusChatInput`, tests and sb page slightly …
=> Exclude gifs handling to separate store, make shared/RootStore singleton smaller

storybook/pages/StatusChatInputPage.qml, storybook/qmlTests/tests/tst_BuyCryptoModal.qml, storybook/qmlTests/tests/tst_StatusChatInput.qml, storybook/src/Models/UsersModel.qml, ui/StatusQ/sandbox/examples/FilteringSorting.qml, ui/StatusQ/src/StatusQ/Components/StatusMemberListItem.qml, ui/StatusQ/src/StatusQ/Components/StatusTagSelector.qml, ui/StatusQ/src/StatusQ/Core/StatusAssetSettings.qml, ui/app/AppLayouts/Chat/panels/SuggestionFilterPanel.qml, ui/app/AppLayouts/Chat/panels/UserListPanel.qml, ui/app/AppLayouts/Chat/stores/UsersStore.qml, ui/app/AppLayouts/Chat/views/ChatColumnView.qml, ui/app/AppLayouts/Chat/views/CreateChatView.qml, ui/app/AppLayouts/Communities/controls/MembersSelectorPanel.qml, ui/app/AppLayouts/Communities/controls/TokenHolderListItem.qml, ui/app/AppLayouts/Communities/panels/MembersTabPanel.qml, ui/app/AppLayouts/Communities/popups/MembersDropdown.qml, ui/app/AppLayouts/Communities/views/CommunityTokenView.qml, ui/imports/shared/controls/delegates/ContactListItemDelegate.qml, ui/imports/shared/status/StatusChatInput.qml, ui/imports/shared/views/ExistingContacts.qml, ui/imports/shared/views/PickedContacts.qml, ui/imports/shared/views/chat/MessageView.qml
- simpler, standard property based API
- much lighter than deriving from the heavy StatusListItem
- should reduce RAM usage significantly, esp. with large communities
Iterates #11059
StatusMemberListItem (and derived classes)
Community channel member list:
Group chat:
Contacts:
Create chat:
Invite contacts to community:
=> chore(StatusMemberListItem): refactor to use ItemDelegate

ui/imports/shared/stores/NetworkConnectionStore.qml
A bug was introduced in https://github.com/status-im/status-desktop/pull/16230
A variable name was changed at the definition but not where it is used in `ui/imports/shared/stores/NetworkConnectionStore.qml`. This PR fixes that.
Wallet
Before:
After:
Users can use wallet bottom bar actions again. 
- Open app
- Go to wallet
- If online, Send and other bottom bar buttons should be enabled
Tick **one**:
-->
=> fix: use proper networks model for detection of offline chain providers

src/app/modules/shared_modules/wallet_connect/helpers.nim, src/app_service/common/json_utils.nim, test/nim/wallet_connect_tests.nim, ui/app/AppLayouts/Wallet/services/dapps/DAppsRequestHandler.qml
Placed tx:
- https://etherscan.io/tx/0xa60423657d8d27a1754ce857282a5d22a5ba3bc53ea829acdccbf89ffabe6bc7
Fixes #16096
=> fix: wallet connect - sake.lido.fi dApp - staking transaction gets stuck

src/app/modules/main/communities/tokens/controller.nim, src/app/modules/main/communities/tokens/io_interface.nim, src/app/modules/main/communities/tokens/models/token_item.nim, src/app/modules/main/communities/tokens/models/token_model.nim, src/app/modules/main/communities/tokens/module.nim, src/app/modules/main/communities/tokens/view.nim, src/app/modules/main/controller.nim, src/app/modules/main/io_interface.nim, src/app/modules/main/module.nim, src/app/modules/main/view.nim, src/app/modules/shared_models/section_item.nim, src/app_service/service/community_tokens/service.nim, storybook/pages/CommunityTokenViewPage.qml, ui/app/AppLayouts/Communities/helpers/TokenObject.qml, ui/app/AppLayouts/Communities/panels/MintTokensSettingsPanel.qml, ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml, ui/app/AppLayouts/Communities/views/CommunityTokenView.qml, ui/imports/shared/stores/CommunityTokensStore.qml
Fixes #16307
Instead of fetching community token holders each time members change, we fetch when the page for the token is opened. It shows a small loading text then the resulting holders. If the list is already available (fetched previously, we show it directly). There is still the timer to refresh the list if you stay on the page.
The community admin page where we show the list of holders for a token. That list is also shown in the remote destruct screen,
[token-holders.webm](https://github.com/user-attachments/assets/9db839f2-aae2-4388-a0d9-5b6cad79e325)
There should be less background calls and less data loaded in the background, hopefully improving the performance and also reducing the RAM …
=> refactor(community_tokens): only fetch holders when going to the page

storybook/pages/CountdownPillPage.qml, storybook/pages/DAppSignRequestModalPage.qml, storybook/pages/IssuePillPage.qml, storybook/pages/SwapSignModalPage.qml, ui/StatusQ/src/StatusQ/Controls/StatusCircularProgressBar.qml, ui/StatusQ/src/StatusQ/Controls/qmldir, ui/StatusQ/src/statusq.qrc, ui/app/AppLayouts/Communities/controls/IssuePill.qml, ui/app/AppLayouts/Wallet/popups/SignTransactionModalBase.qml, ui/imports/shared/controls/CountdownPill.qml, ui/imports/shared/controls/qmldir, ui/imports/shared/popups/walletconnect/DAppSignRequestModal.qml
- show countdown until which the sign (WalletConnect and Swap) dialogs expire
- after expiration, hide the Reject/Sign buttons and display a plain Close button
- make the dialogs non-closable by clicking outside or pressing Esc; the user has to explicitely click some of the footer buttons
See separate commits for the individual components buildup
Fixes https://github.com/status-im/status-desktop/issues/16327
Fixes https://github.com/status-im/status-desktop/issues/16314
TODO:
SwapSignModal, DAppSignRequestModal
Swap sign with initial 120s timeout:
After expiration:
DAppSignRequestModal in dark mode (and tooltip):
DAppSignRequestModal expired:
=> feat: add countdown pill to sign dialogs and make them unclosable

ui/imports/shared/views/chat/MessageView.qml
- need to refer to the RootStore singleton under an alias now
Fixes #16368
Chat (MessageView)
=> fix(MessageView): unbreak GIF unfurling

test/e2e/tests/crtitical_tests_prs/test_onboarding_sync_with_code.py
Sync test is excluded from PRs temporarily
=> chore: disable sync test temp from critical path

config.nims
Closes https://github.com/status-im/status-desktop/issues/15198
- Updated nim-chronicles to the latest version including https://github.com/status-im/nim-chronicles/pull/152
- Defined `chronicles_timestamps=RfcUtcTime`
Less identity disclusure.
Start app
Check logs are in UTC time and not in local time
Tick **one**:
=> fix: logs in utc time

ui/app/AppLayouts/Wallet/services/dapps/DappsConnectorSDK.qml
- https://github.com/status-im/status-go/pull/5855
Fixes #16063 
**Important** 
- while working on this I've noticed many holes in the browser connect implementation that @alexjba and I will work on
- with changes here and on the statusgo side I wanted just to make the sending flow working anyhow, but the real work is yet to come
Executed swap tx:
- https://arbiscan.io/tx/0x1c98c0e57341a99f6041a401d3f8639629e81512ea0b6df9e1298dc72016c9df
Screenshot from the app, where you can see the displayed content in a readable form instead of weird symbols that we had before:
=> fix: browser connect - send transaction command

CONTRIBUTING.md
Extends `contributing.md` with Unit Tests section.
Closes: https://github.com/status-im/status-desktop/issues/16370
=> `CONTRIBUTING.md` extended with section regarding unit tests

storybook/pages/LoginViewPage.qml, test/e2e/gui/objects_map/names.py, test/e2e/gui/objects_map/onboarding_names.py, test/e2e/gui/screens/onboarding.py, ui/StatusQ/src/StatusQ/Popups/StatusMenu.qml, ui/StatusQ/src/StatusQ/Popups/StatusMenuItem.qml, ui/StatusQ/src/StatusQ/Popups/StatusSuccessAction.qml, ui/app/AppLayouts/Onboarding/panels/AccountMenuItemPanel.qml, ui/app/AppLayouts/Onboarding/views/LoginView.qml, ui/imports/shared/controls/chat/UserImage.qml
- StatusSuccessAction, despite its name, is a visual item (`MenuItem` -> `AbstractButton`) which is not part of the `contentModel` but just added to the menu container
- therefore we don't use a ListView but a ScrollView/Repeater instead and set the width/maxWidth manually after the menu items have been added to the layout
Fixes #14037
Context Menus
=> fix(StatusMenu): StatusSuccessAction is not taken into account for Menu width

ui/app/AppLayouts/Communities/panels/MembersTabPanel.qml
- restore backwards compatibility; a lot of the actions in the component relies on the old StatusListItem's `title` property to work correctly
- fixes the missing image and name in the profile context menu, among others
Fixes #16367
Community/Settings/Members
=> fix(MembersTabPanel): unbreak context menu

ui/imports/shared/popups/send/SendModal.qml
When 0 value was entered checking for the best route was not done cause the amount change signal was not emitted.
=> fix: check for the route if 0 value is entered

src/app/core/notifications/notifications_manager.nim
We should **never** log messages, even in debug
=> chore(notiifcations): stop logging messages in debug logs for notifs

ui/app/AppLayouts/Wallet/popups/swap/SwapModal.qml
- if the slippage value is invalid, display a "N/A" text in the footer instead of a partial value
Fixes #16395
SwapModal
=> fix(SwapModal): Max slippage value remains as set even the custom field is erased

storybook/qmlTests/tests/tst_SlippageSelector.qml, ui/imports/shared/controls/SlippageSelector.qml
- set the max custom limit to < 100%
- add a regression test
Fixes #16394
SlippageSelector, SwapModal
=> fix(SlippageSelector): cant do Swap with 100% slippage

storybook/pages/ProfileContextMenuPage.qml, ui/app/AppLayouts/Chat/panels/UserListPanel.qml, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/imports/shared/views/chat/MessageView.qml, ui/imports/shared/views/chat/ProfileContextMenu.qml
closes #16130
requires https://github.com/status-im/status-desktop/pull/16334
Adds "Remove from group" to context menu in group chats
Should only affect group chats
1. create or use an existing group chat
2. right click on the user list and click 'remove from group'
OR
2. right on a message from that user and click "remove from group'
expected: user is removed from the group and the message "user has left the group" is displayed for everyone
> - What kind of user flows should be checked?
- this option should NOT be available for self (i.e a user cannot remove himself from the group)
- this option should NOT be available if the user is not the group admin
- this option should only be available in group chats, e.g going to the community member list and right clicking should not have this …
=> Add remove user groups option to group chat context menu

src/app/modules/main/chat_section/chat_content/chat_details.nim, src/app/modules/main/chat_section/chat_content/module.nim, src/app/modules/main/chat_section/chat_content/users/module.nim, src/app/modules/shared_models/member_model.nim, ui/app/AppLayouts/Chat/panels/UserListPanel.qml, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Chat/views/ChatView.qml, ui/app/AppLayouts/stores/RootStore.qml
Redo of https://github.com/status-im/status-desktop/pull/16178
Fixes https://github.com/status-im/status-desktop/issues/16132
In the previous PR, I was improving the slow chat switching by delaying the loading of the member list and the nkeeping it in memory.
After discussing with @micieslak , we agreed that it was making the code harder to understand and also didn't fix the root cause.
Turns out, the root cause is the SortFilterProxyModel and the `preferredDisplayName` property. 
@caybro already has [a PR](https://github.com/status-im/status-desktop/pull/16277) improving it, but I pushed it one step further (sorry)
In my PR, I moved the `preferredDisplayName` property to the Nim side (this is the biggest speed up).
I also made it so that we populate the models in one go instead of one …
=> Fix slow chat switching 2: Electric Boogaloo

storybook/pages/MessageContextMenuPage.qml, test/e2e/tests/crtitical_tests_prs/test_messaging_1x1_chat.py, ui/imports/shared/views/chat/MessageContextMenuView.qml, ui/imports/shared/views/chat/MessageView.qml
Removes logic and global calls from MessageContextMenu and simplifies some of it
Anything with messages
Functionality should remain the same
Right click on a message and test menu options, such as emoji reactions, copy message, reply to message
message context menu items not working as expected in some particular context
=> refactor: make MessageContextMenu a functional component

ui/app/mainui/AppMain.qml, ui/imports/shared/status/StatusSearchListPopup.qml
Speeds up the CTRL+K search popup search by using a SPFM instead of making objects invisible.
The CTRL+K popup only
- [C] I am familiar with the application architecture and agreed good practices.
[speed-ctrl-k.webm](https://github.com/user-attachments/assets/7f8e8931-5b16-4579-b531-3fce88aaee5d)
Makes using the ctrl-K menu way more snappy
- Open tke ctrl-k popup and search channels
Tick **one**:
Worsct case scenario is the ctrl-K search doesn't work anymore
=> fix(searchList): speed up ctrl-k search by using SPFM

test/e2e/gui/objects_map/messaging_names.py, test/e2e/gui/screens/messages.py, test/e2e/tests/crtitical_tests_prs/test_messaging_1x1_chat.py
Update existing test for 1x1 chat to cover sending transaction in chat. The test opens the link and verifies that send modal appears and has correct recipient address.
NOTE: i did not cover ENS here as it is covered in QML tests. 
https://github.com/status-im/status-desktop/blob/730fcef6dee30f5c502c23d401238a87a9a15b88/storybook/qmlTests/tests/tst_StatusMessage.qml#L46
NOTE: I also did not cover full sending flow here as there is a separate test for it.
=> tests: update existing test to open send modal from chat message

test/e2e/gui/components/settings/sign_out_popup.py, test/e2e/gui/components/signing_phrase_popup.py, test/e2e/gui/screens/community_settings.py
We did not yet figure out https://github.com/status-im/status-desktop/issues/15345
However, this issue impacts autotests.
Main problem: when the application is stuck because of https://github.com/status-im/status-desktop/issues/15345, and then test is terminated (i kill the app process), then on a test retry (we have 1 retry for failed test) squish cant connect to the application for some reason, which is looking like this:
It just stares at the app window and then fails.
I am not entirely sure, where the problem lies, in `pytest-rerunfailures` plugin i use to retry failed test, or in Squish version, or there is some bug in the app (that makes app completely froxzen), or all three or none
=> chore: add timeout for clicks

storybook/pages/StatusChatInputPage.qml, storybook/qmlTests/tests/tst_StatusChatInput.qml, ui/app/AppLayouts/Wallet/panels/WalletHeader.qml, ui/app/AppLayouts/Wallet/popups/SavedAddressActivityPopup.qml, ui/app/AppLayouts/Wallet/stores/RootStore.qml, ui/app/AppLayouts/Wallet/stores/TokensStore.qml, ui/app/AppLayouts/Wallet/views/AssetsDetailView.qml, ui/app/AppLayouts/Wallet/views/RightTabView.qml, ui/app/AppLayouts/Wallet/views/TransactionDetailView.qml, ui/app/mainui/AppMain.qml, ui/imports/shared/status/StatusStickerMarket.qml, ui/imports/shared/status/StatusStickersPopup.qml, ui/imports/shared/stores/RootStore.qml, ui/imports/shared/views/HistoryView.qml
Makes the `shared/RootStore` singleton smaller by moving content to appropriate places. It's the next step towards making that store non-singleton.
- moves wallet-related content to `wallet/RootStore` and `wallet/TokensStore`
- changes dependency on stores from implicit (via singleton) to explicit (taken as a property) in various components (e.g. `HistoryView`)
Closes: https://github.com/status-im/status-desktop/issues/16254
`shared/RootStore`, `wallet/RootStore`, several related ui components
=> stores: move wallet-related methods/properties from shared/stores/RootStore to dedicated stores

src/app/modules/main/profile_section/ens_usernames/controller.nim, src/app/modules/main/profile_section/ens_usernames/io_interface.nim, src/app/modules/main/profile_section/ens_usernames/module.nim, src/app/modules/main/profile_section/ens_usernames/view.nim, src/app/modules/main/profile_section/module.nim, src/app_service/service/ens/dto/ens_username_dto.nim, src/app_service/service/ens/service.nim, src/app_service/service/stickers/service.nim, src/backend/ens.nim, ui/app/AppLayouts/Profile/stores/EnsUsernamesStore.qml, ui/app/AppLayouts/Profile/views/EnsDetailsView.qml, ui/app/AppLayouts/Profile/views/EnsSearchView.qml, ui/app/AppLayouts/Profile/views/EnsTermsAndConditionsView.qml
Based on changes done in this PR https://github.com/status-im/status-go/pull/5807 we can simplify our client logic a lot.
This results in the removal of many lines of code that are no longer needed
Closes 2nd part of #16336
=> chore: align buying/releasing/setting ens usernames with the new sending flow

storybook/pages/MembersTabPanelPage.qml, ui/StatusQ/src/StatusQ/Components/StatusMemberListItem.qml, ui/app/AppLayouts/Chat/panels/UserListPanel.qml, ui/app/AppLayouts/Communities/panels/MembersTabPanel.qml, ui/app/AppLayouts/Profile/views/ContactsView.qml, ui/imports/shared/views/chat/MessageView.qml
- move the MouseArea into `background` so that it doesn't obscure the potential action buttons
- fixup SB page
- separate commit to fix ProfileContextMenu memory leaks
Fixes https://github.com/status-im/status-desktop/issues/16426
MembersTabPanel
https://github.com/user-attachments/assets/d51302ad-8c17-496c-85b2-94c420eba57e
=> fix(MembersTabPanel): Buttons in the Member tab do not work

storybook/pages/CommunitiesPortalDummyModel.qml, storybook/pages/CommunitiesPortalLayoutPage.qml, storybook/pages/PermissionsRowPage.qml, storybook/src/Models/CommunitiesModel.qml, storybook/src/Models/PermissionsModel.qml, ui/StatusQ/src/StatusQ/Components/StatusCommunityCard.qml, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Communities/CommunitiesPortalLayout.qml, ui/app/AppLayouts/Communities/controls/PermissionsRow.qml, ui/app/AppLayouts/Wallet/stores/RootStore.qml, ui/app/AppLayouts/Wallet/views/RightTabView.qml, ui/app/mainui/AppMain.qml, ui/imports/shared/stores/RootStore.qml, ui/imports/shared/views/HistoryView.qml, ui/imports/shared/views/profile/ProfileShowcaseCommunitiesView.qml
- hide the permission from the `PermissionsRow` when it's set to private and the conditions are not met
- display a tooltip "(Not) eligible to join" over the lock icon
- show the same info in both community portal and profile dialog's community showcase tab
- speedup searching/filtering in the community portal
- fixup and extend the SB pages to demonstrate the new behavior
- separate commit to fixup `StatusCommunityCard` layout
Fixes https://github.com/status-im/status-desktop/issues/14747
Community Portal, Profile Dialog/Showcase/Communities
CommunitiesPortalLayout (Status community not showing the tokens due to restrictions): …
=> fix(community): Token gating info when permission not met and set to private

.github/CODEOWNERS
closes #16473
Setting-up the initial code owners in GH. The code owners will be automatically added to PR reviews.
See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
Any CC can change the `CODEOWNERS` file to add/remove himself as a default reviewer. `CODEOWNERS` file can work with specific files or folders (E.g. When developing a new feature, the dev can add himself as a default reviewer for the files involved in the feature)
I've took the freedom to add specific CCs to some domain that are clearly defined (CI, e2e, qml). Please feel free to propose changes if you'd like me to extend the ownership or remove your username completely.
CC. @jakubgs @yakimant @micieslak @caybro
@status-im/desktop is the …
=> chore: Set-up the initial codeowners

ui/imports/shared/popups/UserAgreementPopup.qml
- reword the sentence, remove ref to 1.0 release
Fixes #16447
UserAgreementPopup
=> fix: Update "Welcome to Status Beta" startup dialog

storybook/pages/DAppsWorkflowPage.qml, storybook/qmlTests/tests/helpers/wallet_connect.js, storybook/qmlTests/tests/tst_DAppsWorkflow.qml, ui/StatusQ/src/StatusQ/Core/Utils/ModelUtils.qml, ui/app/AppLayouts/Wallet/panels/DAppsWorkflow.qml, ui/app/AppLayouts/Wallet/panels/WalletHeader.qml, ui/app/AppLayouts/Wallet/services/dapps/ConnectorDAppsListProvider.qml, ui/app/AppLayouts/Wallet/services/dapps/DAppsListProvider.qml, ui/app/AppLayouts/Wallet/services/dapps/DAppsRequestHandler.qml, ui/app/AppLayouts/Wallet/services/dapps/DappsConnectorSDK.qml, ui/app/AppLayouts/Wallet/services/dapps/WalletConnectSDK.qml, ui/app/AppLayouts/Wallet/services/dapps/WalletConnectSDKBase.qml, ui/app/AppLayouts/Wallet/services/dapps/WalletConnectService.qml, ui/app/AppLayouts/Wallet/services/dapps/types/SessionRequestResolved.qml, ui/app/AppLayouts/Wallet/services/dapps/types/SessionRequestsModel.qml, ui/app/AppLayouts/Wallet/services/dapps/types/qmldir, ui/imports/shared/popups/walletconnect/ConnectDAppModal.qml, ui/imports/shared/popups/walletconnect/DAppSignRequestModal.qml, ui/imports/shared/popups/walletconnect/PairWCModal/WCUriInput.qml, ui/imports/utils/Constants.qml
closes https://github.com/status-im/status-desktop/issues/16463
**Separation of concerns**
1. **Issue**: The UI components depend on the `WalletConnectService` and also on its dependencies like `DAppsRequestHAndler`. As a result the UI components have a hard dependency on the WalletConnect specifics and are incompatible with BC. This results in duplication of logic.
2. **Issue**: The UI components operate on WalletConnect specific JSON object. E.g. session objects, session proposal etc. As a result the UI is built around the WalletConnect message format.
3. **Issue**: The UI components operate on ListModel items received through functions and stored internally. Any change in the model would result in a crash.
- **Solution**: Remove the WalletConnectService dependency from `DAppsWorkflow`. …
=> refactor: Remove the business logic from UI components

src/app/modules/main/profile_section/ens_usernames/module.nim, src/app/modules/main/profile_section/ens_usernames/view.nim, src/app_service/service/transaction/service.nim, ui/app/AppLayouts/Chat/ChatLayout.qml, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Chat/views/ChatView.qml, ui/app/AppLayouts/Profile/ProfileLayout.qml, ui/app/AppLayouts/Profile/views/EnsDetailsView.qml, ui/app/AppLayouts/Profile/views/EnsSearchView.qml, ui/app/AppLayouts/Profile/views/EnsTermsAndConditionsView.qml, ui/app/AppLayouts/Profile/views/EnsView.qml, ui/app/AppLayouts/Wallet/WalletUtils.qml, ui/app/mainui/AppMain.qml, ui/imports/shared/status/StatusStickerMarket.qml, ui/imports/shared/status/StatusStickerPackClickPopup.qml, ui/imports/shared/status/StatusStickersPopup.qml, ui/imports/utils/Constants.qml
Corresponding `statusgo` PR:
- https://github.com/status-im/status-go/pull/5910
Fixes #16452
This PR brings back "Remove username" and "Release username" options via the first commit.
The second commit improves all ens-related flows.
The third commit improves all buying stickers flows.
Affected flows:
- buying ens name
- connecting an existing ens name
- releasing ens name
- removing ens name
- buying stickers from the all stickers popup (bottom right corner of the chat view)
- buying stickers from the single stickers popup (bottom right corner of the chat view, click on the desired pack, then click buy for that popup)
- buying stickers from chat (click on the sticker in messages and buy it if you don't have it bought)
Old implementation had 6 usages of SendModal component:
Now there is a …
=> fix: there are no options for remove and release ens username

AppRun, Makefile, src/nim_status_client.nim, storybook/main.cpp, ui/StatusQ/tests/TestComponents/tst_WebEngineLoader.qml
closes #16391
Remove the forced openGL context sharing. This will be done in the QtWebView::initialise by Qt if possible, depending on platform.
WebEngineView
WalletConnect
- [ x I am familiar with the application architecture and agreed good practices.
=> fix: Remove forced OpenGl context sharing

storybook/pages/StatusChatInputPage.qml, storybook/qmlTests/tests/tst_StatusChatInput.qml, test/e2e/configs/__init__.py, test/e2e/gui/components/back_up_your_seed_phrase_popup.py, test/e2e/gui/components/base_popup.py, test/e2e/gui/components/community/community_category_popup.py, test/e2e/gui/components/community/create_community_popups.py, test/e2e/gui/components/messaging/edit_group_name_and_image_popup.py, test/e2e/gui/components/messaging/leave_group_popup.py, test/e2e/gui/components/settings/send_contact_request_popup.py, test/e2e/gui/components/settings/sync_new_device_popup.py, test/e2e/gui/components/wallet/add_saved_address_popup.py, test/e2e/gui/elements/object.py, test/e2e/gui/main_window.py, test/e2e/tests/crtitical_tests_prs/test_add_account_after_restart.py, test/e2e/tests/crtitical_tests_prs/test_add_delete_account_from_settings.py, test/e2e/tests/crtitical_tests_prs/test_add_edit_delete_generated_account.py, ui/app/mainui/AppMain.qml, ui/app/mainui/panels/DropAreaPanel.qml, ui/app/mainui/qmldir, ui/imports/shared/status/StatusChatImageLoader.qml, ui/imports/shared/status/StatusChatInput.qml, ui/imports/utils/Global.qml
- do not allow DND when the StatusChatInput is disabled
- remove `Global.dragArea` variable from the Global singleton
Fixes #16451
Chat/Input
https://github.com/user-attachments/assets/dbf0c944-d92f-4251-b89d-cb83fd9fda2f
=> fix(chat): chat input accepts DnD for blocked users

src/app/modules/main/controller.nim, src/app/modules/main/io_interface.nim, src/app/modules/main/module.nim, src/app/modules/shared_models/member_model.nim, src/app/modules/shared_models/section_model.nim, src/app_service/service/community/dto/community.nim, src/app_service/service/community/service.nim, ui/app/AppLayouts/Communities/popups/InDropdown.qml, ui/app/AppLayouts/Communities/popups/MembersDropdown.qml, ui/app/AppLayouts/Communities/views/EditAirdropView.qml
Iterates https://github.com/status-im/status-desktop/issues/16043
When the community gets updated by any means, we reconstruct the section item, which is already bad, but we also re-fetch all tokens and all shared addresses, which in turn re-updates models for no reason.
Instead, I make sure to only fetch those on first section build, then, I get the new shared addresses when members join using the request to join response that comes from status-go
Status-go PR to fix the correct return of the shared addresses: https://github.com/status-im/status-go/pull/5867
A further improvement IMO would be to stop redoing the section when the community updates, but we'll need to be careful, because it might break a lot of places that would normally update automatically.
Also includes a commit that …
=> Fix some of the freezes experienced by the admins when the community updates

ui/StatusQ/src/StatusQ/Controls/StatusChatInfoButton.qml, ui/app/AppLayouts/Chat/views/ChatHeaderContentView.qml, ui/app/AppLayouts/Communities/popups/CommunityMemberMessagesPopup.qml, ui/app/mainui/Popups.qml, ui/imports/shared/views/chat/MessageView.qml
- propagate and set `requiresPermissions` + `locked` from the `chatContentModule.chatDetails`
- set the icon accordingly for community chats
- separate commit to fix a store refactoring regression
Fixes #16502
StatusChatInfoButton / ChatHeaderContentView
=> fix(StatusChatInfoButton): missing lock icon

test/e2e/driver/mouse.py, test/e2e/gui/elements/scroll.py, test/e2e/gui/mocked_keycard_controller.py
Closes #16325 
This makes the scrolling work for any qml type where the child supports scrolling. By default the cursor is positioned in the middle of the scrollable item and scroll in steps of 30px.
This can be adjusted later on to better fit most of our use cases. It's a configuration we can tweak in an empirical way.
=> chore(E2E): Use `mouseWheel` method to scroll

ci/Jenkinsfile.linux, ci/Jenkinsfile.linux-nix, ci/Jenkinsfile.macos, ci/Jenkinsfile.windows
An error has shown that Nim compilation uses cache folder in `jenkins` home:
```
clang: error: no such file or directory:
'/Users/jenkins/.cache/nim/nimsuggest_r/@m..@slib@swrappers@slinenoise@slinenoise.c.o'
```
This is a bad idea as parallel CI builds can result in very bizzarre bugs.
=> fix(ci)_: move nim cache to workspace tmp folder

src/app/modules/main/chat_section/chat_content/chat_details.nim, src/app/modules/main/chat_section/chat_content/module.nim, src/app/modules/main/chat_section/chat_content/users/controller.nim, src/app/modules/main/chat_section/chat_content/users/io_interface.nim, src/app/modules/main/chat_section/chat_content/users/module.nim, src/app/modules/main/chat_section/chat_content/users/view.nim, src/app/modules/main/chat_section/controller.nim, src/app/modules/main/chat_section/io_interface.nim, src/app/modules/main/chat_section/module.nim, src/app/modules/main/chat_section/view.nim, src/app_service/service/community/service.nim, src/app_service/service/contacts/dto/contacts.nim, src/app_service/service/ens/dto/ens_username_dto.nim, ui/app/AppLayouts/Chat/views/ChatView.qml
Fixes https://github.com/status-im/status-desktop/issues/16288
Follow up of https://github.com/status-im/status-desktop/pull/16279
In the base PR, I introduced the idea of reusing the same user model when we have the same full model.
However, as @alexjba pointed out, this was dangerous, since if a channel is deleted, the model should be deleted too and then we could have a crash.
This is remedied in this PR, by introducing a new instance of the users module, but managed by the section module.
This user module is managing the "public" community members list. Meaning that everytime we have a public channel in a community, we use that module instead.
The channel's user module is empty for public channels to reduce the amount of processing and memory used.
If the channel becomes private, we …
=> Use a single member list for community public channels

storybook/qmlTests/tests/tst_DAppsWorkflow.qml, ui/app/AppLayouts/Wallet/panels/DAppsWorkflow.qml
Fixing flaky qml test. The `Sign` and `Reject` buttons would sometimes overlap at the moment of mouseClick. This results in the wrong button to be clicked.
To fix this I'm waiting for the buttons to be aligned before doing any action.
=> fix: DAppsWorkflow flaky test

src/app/modules/main/wallet_section/send/io_interface.nim, src/app/modules/main/wallet_section/send/module.nim, src/app/modules/main/wallet_section/send/view.nim, src/app_service/service/ens/service.nim, storybook/qmlTests/tests/tst_SwapModal.qml, storybook/qmlTests/tests/tst_SwapSignModal.qml, ui/app/AppLayouts/Wallet/popups/SignTransactionModalBase.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapModal.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapModalAdaptor.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapSignModal.qml
The Swap flow now:
1. if approval not needed (swapping ETH)
- run swap flow
- click "Swap" button
- review "Sign Swap" popup
- click "Sign"
- authenticate
2. if approval needed (swapping any ERC20 token)
- run swap flow
- click "Approve TOKEN" button
- review "Approve spending cap" popup
- click "Sign"
- authenticate
- button is in the "Approving TOKEN" state
- when approval is executed, and "Swap" button becomes available, click it
- review "Swap" popup
- click "Swap" button **(no need to sign again here)**
Updated the following User Stories:
- SD-28
- SD-36
- SD-89
Closes #16337
=> chore: sign the flow only once if approval and transaction need to be placed once after another (swap flow)

storybook/pages/PasswordViewPage.qml, test/e2e/constants/onboarding.py, test/e2e/scripts/utils/generators.py, test/e2e/tests/crtitical_tests_prs/test_settings_password_change_password.py, test/e2e/tests/onboarding/test_onboarding_negative_scenarios.py, test/e2e/tests/settings/settings_password/__init__.py, ui/StatusQ/src/StatusQ/Controls/StatusPasswordStrengthIndicator.qml, ui/imports/shared/views/PasswordConfirmationView.qml, ui/imports/shared/views/PasswordView.qml, ui/imports/utils/Constants.qml
- set the pass max length to 100 (via `Constants`, not with a hardcoded regexp)
- delay the validation until the user hits the limit
- clear the categories (lower/upper/num/sym) info if the password is cleared too
- update the error messages according to latest Figma designs
Fixes #16239
PasswordView
Max length check (101 chars entered):
Unsupported chars check:
Min length check:
=> fix(PasswordView): Password instructions missing max length requirement

ui/StatusQ/include/StatusQ/modelcount.h, ui/StatusQ/src/modelcount.cpp, ui/StatusQ/tests/tst_ModelCount.cpp, ui/imports/shared/views/AssetsViewAdaptor.qml
It adds `empty` property for convenience and simplifies the internal implementation of `ModelCount` attached property.
Closes: #15740
`ModelCount`
=> StatusQ: ModelCount simplified and  property added

Makefile, ci/Jenkinsfile.tests-nim, src/app/modules/shared_models/collectibles_entry.nim, test/nim/message_model_test.nim, ui/app/AppLayouts/Wallet/views/RightTabView.qml
Otherwise combining separate `nim` calls with `;` results in only the last one informing `make` call what exit code the whole target had.
Resolves:
- https://github.com/status-im/status-desktop/issues/16545
=> fix(nim-tests): split tests into individual targets

ui/app/AppLayouts/Profile/ProfileLayout.qml, ui/app/AppLayouts/Profile/panels/MenuPanel.qml, ui/app/AppLayouts/Profile/views/LeftTabView.qml, ui/app/AppLayouts/Profile/views/WalletView.qml, ui/app/mainui/AppMain.qml, ui/imports/utils/Global.qml
This PR is a next step towards making `Global` and other singletons stateless.
Closes: #16457
`Global`, `ProfileLayout` and related subcomponents
=> chore: remove `settingsSubsection`/`settingsSubSubsection` props (state in singleton) from `Global`

test/e2e/gui/screens/wallet.py, test/e2e/tests/crtitical_tests_prs/test_add_account_after_restart.py, test/e2e/tests/crtitical_tests_prs/test_add_delete_account_from_settings.py, test/e2e/tests/crtitical_tests_prs/test_add_edit_delete_generated_account.py, test/e2e/tests/settings/settings_wallet/test_wallet_settings_account_order.py, test/e2e/tests/settings/settings_wallet/test_wallet_settings_add_account.py, test/e2e/tests/settings/settings_wallet/test_wallet_settings_watched_addr_include_in_total_balance.py, test/e2e/tests/wallet_main_screen/wallet - footer actions/test_footer_actions_default_account_values.py
Temp disable setting color and emoji for accounts in wallet. It looks to be the root cause of application silently close in the middle of the test and then we face with `AssertionError: Acknowledge checkbox is not checked` 
When the root cause of the app closing itself is most likely found (i will fix it properly later, along with some refactoring for wallet account tests), it does not fix the problem of tests being unable to recover after this situation. 
Similar thing could potentially happen when application crashes. There could be a possibility to cover that with CrashEventHandler but it is not yet implemented (in to do)
Overall, this change should stabilise tests
=> chore(@e2e): temp disable adding color and emoji for account creation

ui/StatusQ/src/StatusQ/Controls/StatusTagItem.qml, ui/app/AppLayouts/Chat/panels/InlineSelectorPanel.qml, ui/app/AppLayouts/Chat/panels/SuggestionBoxPanel.qml, ui/app/AppLayouts/Chat/panels/qmldir, ui/app/AppLayouts/Chat/views/ChatColumnView.qml, ui/app/AppLayouts/Chat/views/CreateChatView.qml, ui/app/AppLayouts/Chat/views/MembersEditSelectorView.qml, ui/app/AppLayouts/Chat/views/MembersSelectorView.qml, ui/app/AppLayouts/Chat/views/private/MembersSelectorBase.qml, ui/imports/shared/popups/RenameGroupPopup.qml, ui/imports/shared/status/StatusChatInput.qml, ui/imports/shared/views/chat/ChatContextMenuView.qml, ui/imports/shared/views/chat/MessageView.qml, ui/imports/utils/Constants.qml
- increase the length limit to 30 and allow `&`, as per the spec
- wrap the popup in a scroll view
- plus some minor cleanups
Fixes #16523
RenameGroupPopup
Group created:
Editting group properties:
https://github.com/user-attachments/assets/214aa374-4c37-45a7-9bfa-3d368fb62204
=> fix(RenameGroupPopup): fix name validation and scrolling

storybook/CMakeLists.txt
Adds a switch in Storybook's `CMakeLists.txt` determining how stores are resolved in QtCreator.
Closes: #16582
Storybook's `CMakeLists.txt`
[Screencast from 23.10.2024 16:55:06.webm](https://github.com/user-attachments/assets/a622ce8f-a62f-4548-ac23-12d2ef4de4e9)
=> Storybook: switch to determine how to resolve stores' paths in QtCreator

ui/app/AppLayouts/Wallet/popups/SignTransactionModalBase.qml
Closes #16529
Fixing the scroll contentHeight whenever the content changes height.
Sign popup - Wallet connect and Swap, Swap cap approval
https://github.com/user-attachments/assets/ce5956df-b05f-49cd-a410-0d622049110a
=> fix: Sign transaction popup scroll when content changes height

src/app/modules/main/chat_section/controller.nim, src/app/modules/main/controller.nim, src/app/modules/main/io_interface.nim, src/app/modules/main/module.nim, src/app/modules/shared_models/section_model.nim, src/app_service/service/community/service.nim
Fixes #16600
There was no update to the model when we get a signal that a membership request is received. We also didn't send an event when one is canceled.
These changes were part of the [Improve performance by only updating the properties that changed in the model instead of reseting](https://github.com/status-im/status-desktop/pull/16436) PR I did, but that only landed in master because it's a bit too big or risky to put in the release so late.
I only selected the needed changes from that big PR.
Once this is merged, it shouldn't be necessary to cherry-pick it.
[requests-pending.webm](https://github.com/user-attachments/assets/0fa84e3f-1d1c-4cc1-a16f-70545813213f)
=> fix(requests): fix member requests not showing in list

ui/imports/shared/status/StatusGifPopup.qml, ui/imports/shared/stores/GifStore.qml, ui/imports/shared/stores/RootStore.qml
Fixes #16598
The gif popup was using the global RootStore, but it didn't work and it's also not a good practice.
I move the function to enable to the GifStore which is accessible as a reference instead.
[gif-enabling.webm](https://github.com/user-attachments/assets/0db23d3d-c4ca-4e19-8fec-79418b825827)
=> fix(gifs): fix call to setGifUnfurlingEnabled using a bad store

ui/imports/shared/status/StatusGifPopup.qml, ui/imports/shared/stores/GifStore.qml, ui/imports/shared/stores/RootStore.qml
Fixes #16598
Cherry-pick of https://github.com/status-im/status-desktop/pull/16603
The gif popup was using the global RootStore, but it didn't work and it's also not a good practice.
I moved the function to enable to the GifStore which is accessible as a reference instead.
=> [CHERRY-PICK] fix(gifs): fix call to setGifUnfurlingEnabled using a bad store (#16603)

ui/StatusQ/src/StatusQ/Popups/StatusMenu.qml, ui/StatusQ/src/StatusQ/Popups/StatusMenuSeparator.qml, ui/app/AppLayouts/Profile/controls/ShowcaseDelegate.qml, ui/imports/shared/controls/chat/ProfileHeader.qml, ui/imports/shared/views/chat/MessageContextMenuView.qml, ui/imports/shared/views/chat/ProfileContextMenu.qml
- hide the separators when showing a bridged profile
- fix calculating the menu item widths
Fixes #16593
ProfileContextMenu
Bridged profile:
Regular profile:
=> fix(ProfileContextMenu): excessive separators for a bridged profile

ui/app/AppLayouts/Chat/views/qmldir, ui/app/AppLayouts/Profile/panels/CommunitiesListPanel.qml
Fixes #16627
I had missed that the community settings also used the members. Fixed by using the model adaptor and using the right property name
Community settings (members only)
Goes back to expected behavior of seeing the members count in the settings
- Be part of a community
- Check the community settings
Tick **one**:
=> fix(communities): fix missing members in community settings

ui/app/AppLayouts/Communities/panels/MembersSettingsPanel.qml, ui/app/AppLayouts/Communities/panels/OverviewSettingsPanel.qml, ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml
- this adds direct access to sending invitations to new ppl (aka adding members), instead of going thru the secondary nav context menu
- the new community context menu will be tackled in a separate task/issue
Fixes #16597
Community/Settings/Members
https://github.com/user-attachments/assets/1d66b2e3-72e5-4255-97be-884ba0ba849f
=> feat(CommunitySettingsView): add "Invite people" button

ui/app/AppLayouts/Communities/panels/PermissionsSettingsPanel.qml
- fixup the initial item width
Fixes #16617
PermissionsSettingsPanel
App:
SB:
=> fix(PermissionsSettingsPanel): fix initial view being too wide

ui/app/AppLayouts/Communities/popups/InviteFriendsToCommunityPopup.qml
- pass the correct community ID
Fixes #16637
InviteFriendsToCommunityPopup
=> fix: Share community link is gone

ui/app/AppLayouts/Wallet/popups/swap/SwapModal.qml
fixes #16568
Fixes the tooltip text in SwapModal, doesnt show any tooltip when Swap button is shown
SwapModal
https://github.com/user-attachments/assets/706ba2d1-d40a-478b-87f9-b5fc23b47619
=> (CHERRYPICK)fix(@desktop/wallet): Swap transaction - Wrong copy on the tooltip of the 'Swap' button

ui/app/AppLayouts/Wallet/popups/swap/SwapModal.qml
fixes #16568
Fixes the tooltip text in SwapModal, doesnt show any tooltip when Swap button is shown
SwapModal
https://github.com/user-attachments/assets/a94417d8-fd65-4ac9-abb0-97facdf2e414
=> Fix/16568: Swap transaction - Wrong copy on the tooltip of the 'Swap' button

ui/app/AppLayouts/Chat/stores/UsersStore.qml, ui/app/AppLayouts/Chat/views/ChatColumnView.qml, ui/app/AppLayouts/Chat/views/ChatContentView.qml, ui/app/AppLayouts/Chat/views/ChatView.qml
Fixes #16602
This was broken when we refactored the members to use a single model for public channels. Those public channels then didn't have any members in their model they used for suggestions. This is fixed by putting the logic in the UsersStore and reusing that store whenever we need a list of the members.
ChatColumnView and ChatView
[mentions.webm](https://github.com/user-attachments/assets/45df2f1a-f768-47cc-bca1-282fce04da39)
I forgot to show in the video, but they work in the Edit message input too.
Fixes the mentions
Test the mentions in different types of chats and scenarios (1-1, group, community channel (public or not), edit …
=> fix(mentions): fix wrong user list given to mentions model

ui/app/AppLayouts/Profile/views/EnsDetailsView.qml, ui/app/AppLayouts/Profile/views/EnsView.qml, ui/imports/shared/popups/send/SendModal.qml, ui/imports/shared/popups/send/views/NetworkSelector.qml
There are a few things improved in this commit:
- the account the username was bought with is selected for releasing
- if the account was removed in meantime, we warn user displaying a popup message
- ETH token is selected
- 0 value is set
Fixes #16611
@benjthayer if you have a better suggestion for the message in the video below, in case when the address the username was bought with was removed, let me know to update it.
https://github.com/user-attachments/assets/a1a5a037-5f75-48a2-accb-615d95b554e9
=> fix: cant fetch fees when releasing ens name, token is not set, as well as value

storybook/pages/DerivationPathInputPage.qml, ui/imports/shared/popups/addaccount/panels/DerivationPathInput.qml, ui/imports/shared/popups/addaccount/panels/DerivationPathSelection.qml, ui/imports/shared/popups/addaccount/panels/qmldir, ui/imports/shared/popups/common/BasePopupStore.qml
- use `StatusListView` for the popup/menu contentItem
- add the menu to SB too
Fixes #16635
DerivationInput
https://github.com/user-attachments/assets/3151eca5-513d-475e-8035-4a72d48131ac
=> fix(AddAccount): Derivation path drop down is empty

src/app/modules/main/profile_section/ens_usernames/module.nim, src/app/modules/main/profile_section/ens_usernames/view.nim, src/app/modules/main/wallet_section/networks/model.nim, src/app/modules/main/wallet_section/networks/view.nim, src/app_service/service/network/service.nim, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Profile/stores/EnsUsernamesStore.qml, ui/app/AppLayouts/Profile/views/EnsTermsAndConditionsView.qml, ui/app/AppLayouts/Profile/views/EnsView.qml, ui/app/AppLayouts/stores/RootStore.qml, ui/app/mainui/AppMain.qml, ui/imports/shared/stores/send/TransactionStore.qml
Old `getEtherscanLink` is now `getEtherscanTxLink` and the new `getEtherscanAddressLink` method added.
Fixes #16658
=> fix: links do not work in the terms of name registration popup

ui/app/AppLayouts/Communities/helpers/AirdropFeesSubscriber.qml
Fixes #16562
Just a small rewording
=> fix(airdrop): fix wording of the error when selecting the wrong account

ui/app/AppLayouts/Chat/stores/UsersStore.qml, ui/app/AppLayouts/Chat/views/ChatColumnView.qml, ui/app/AppLayouts/Chat/views/ChatContentView.qml, ui/app/AppLayouts/Chat/views/ChatView.qml
Cherry-pick of https://github.com/status-im/status-desktop/pull/16615
Fixes #16602
This was broken when we refactored the members to use a single model for public channels. Those public channels then didn't have any members in their model they used for suggestions. This is fixed by putting the logic in the UsersStore and reusing that store whenever we need a list of the members.
=> [CHERRY-PICK] fix(mentions): fix wrong user list given to mentions model

test/e2e/tests/communities/test_communities_pin_and_unpin_messages.py
Test for pinning messages is failing of wrong memebrs count
https://github.com/status-im/status-desktop/issues/16672
=> chore(@e2e): mark pin messages test with xfail

src/app/modules/main/communities/module.nim
Found while debugging https://github.com/status-im/status-desktop/issues/16645
While this doesn't fix the issue, it removes useless calls to status-go.
Curated communities
None. We only need to load once, so if they are already loaded, we don't need to call `load` each time we go there.
Check the curated communities with an old and new account
Tick **one**:
I doubt anything can happen, but if the fetch fails, it won't retry
=> fix(curated): only load curated communities once

test/e2e/tests/wallet_main_screen/wallet - plus button/test_plus_button_manage_generated_account_custom_derivation_path.py
Mark test for adding account with custom derivation path as expected to fail: https://github.com/status-im/status-desktop/issues/16683
=> chore(@e2e): mark test as xfail because of issue

src/app/modules/main/module.nim, src/app_service/service/community/service.nim, test/e2e/tests/communities/test_communities_pin_and_unpin_messages.py
Fixes #16672
The issue was that the requests to join were not handled in time for when the community update came in, so when we udpated the section, we got both the normal member and the pending member still and they clashed and the pending one came on top, meaning that the joined member was not counted. On a restart it would fix itself.
To fix it, I reordered the parsing of communities and requests, so that the request is updated first, ie deleted because it is now accepted. I also fixed the function that handles request to that the state gets updated at all times. Before, it would only get updated if it was not accepted, pending or waiting for address. Finally, there was a weird scenario where as a TM, I saw myself as pending even if I was joined, so I fixed it by removing duplicates. …
=> fix(members): fix member count not updating correctly on join

monitoring/ModelInspectionPane.qml, monitoring/MonitorEntryPoint.qml, monitoring/MonitorUtils.qml
Adds possibility to inspect nested objects. It's especially useful when modules are nested, like `profileSectionModule` -> `contactsModule`.
[Screencast from 31.10.2024 23:55:30.webm](https://github.com/user-attachments/assets/3485f212-dc93-4998-8c61-67a8d2f30b8b)
=> Monitoring Tool: possibility of nested objects inspection

ui/StatusQ/include/StatusQ/urlutils.h, ui/StatusQ/src/typesregistration.cpp, ui/StatusQ/src/urlutils.cpp, ui/app/AppLayouts/Communities/stores/CommunitiesStore.qml, ui/app/AppLayouts/Profile/views/CommunitiesView.qml, ui/imports/shared/popups/ImageCropWorkflow.qml, ui/imports/shared/status/StatusChatImageExtensionValidator.qml, ui/imports/shared/status/StatusChatInput.qml, ui/imports/utils/Constants.qml, ui/imports/utils/Utils.qml
- use the same approach as status-go to detect the image type, relying on "magic" type matching instead of looking at the file extension (now using C++ and QMime*)
- add a little error popup when the user tries to upload an unsupported image type while creating/editing a community
- expose all the image related properties from the C++ backend instead of constructing and duplicating them in QML
- cleanup some unused/dead code
Fixes #16668
Community settings, StatusChatInput, Image DND
Trying to change the community logo, using an AVIF (unsupported) image:
https://github.com/user-attachments/assets/8978a02a-fce5-4ca0-8a32-ea7ba9424373
Trying to …
=> fix: improve image type detection

src/app/modules/shared_modules/wallet_connect/helpers.nim, ui/app/AppLayouts/Wallet/panels/DAppsWorkflow.qml, ui/app/AppLayouts/Wallet/panels/WalletHeader.qml, ui/app/AppLayouts/Wallet/services/dapps/DAppsRequestHandler.qml, ui/app/AppLayouts/Wallet/services/dapps/WalletConnectService.qml, ui/imports/shared/popups/walletconnect/DAppSignRequestModal.qml, ui/imports/shared/popups/walletconnect/panels/ContentPanel.qml, ui/imports/utils/Constants.qml
- the following params were removed from the tx preview (cause they are dynamic and recalculate with base fee change):
- `maxFeePerGas`
- `maxPriorityFeePerGas`
- `gasPrice`
- fees and estimated time are recalculated periodically
Fixes #16528
https://github.com/user-attachments/assets/9282d927-320b-4d84-9704-542faa5cc235
=> fix: fill missing fees in tx object received from dApp

test/e2e/tests/wallet_main_screen/wallet - plus button/test_plus_button_manage_generated_account_custom_derivation_path.py, ui/StatusQ/src/StatusQ/Components/StatusPageIndicator.qml, ui/imports/shared/popups/addaccount/panels/AccountAddressSelection.qml, ui/imports/shared/popups/addaccount/panels/DerivationPath.qml
- use a similar approach as in the DerivationPath popup; ListView instead of a Repeater
- some smaller fixes & speedups in the SFPM
- reenable the test
- separate commit to fix a small issue in StatusPageIndicator
Fixes https://github.com/status-im/status-desktop/issues/16683
AddAccountPopup, StatusPageIndicator
https://github.com/user-attachments/assets/0ae1589f-cc7d-4cbc-ad5a-6668ef218579
=> fix(AddAccountPopup): account list for address selection is empty

status.iss
It fixes problem with unwanted qmldir in 2.31 which is in `bin/StatusQ` when overriding 2.30.1 or older installation.
Closes: #16693
Window's installer script (`status.iss`)
=> Windows installer: remove bin dir as a first step of installation

status.iss
Cherry-pick of https://github.com/status-im/status-desktop/pull/16698
It fixes problem with unwanted qmldir in 2.31 which is in `bin/StatusQ` when overriding 2.30.1 or older installation.
Closes: #16693
Windows installer's script (`status.iss`)
- install Status Desktop on windows using 2.30 or earlier
- install Status Desktop 2.31 on top
Check if the app is running normally.
Tick **one**:
=> [CHERRYPICK]: Windows installer: remove bin dir as a first step of installation

test/e2e/gui/components/wallet/wallet_account_popups.py, test/e2e/gui/objects_map/names.py
Allow the list of addresses to load before trying to click them
https://ci.status.im/job/status-desktop/job/e2e/job/manual/2577/
=> chore(@e2e): allow account list to load before selecting

src/app/modules/main/chat_search_item.nim, src/app/modules/main/chat_search_model.nim, src/app/modules/main/module.nim, src/app_service/service/contacts/dto/contacts.nim, ui/imports/shared/status/StatusSearchListPopup.qml
- add `emoji` to the channel list model
- add sorting by channel name
- fix hiding unavailable channels due to permissions, or the chat not being active
Fixes #16623
StatusSearchListPopup (Ctrl+K search)
=> fix[Chat] Jump to popup missing channel emojis

storybook/qmlTests/tests/tst_ModelEntryChangeTracker.qml, storybook/stubs/shared/stores/ProfileStore.qml, storybook/stubs/shared/stores/qmldir, ui/StatusQ/include/StatusQ/modelutilsinternal.h, ui/StatusQ/src/StatusQ/Core/Utils/ModelEntryChangeTracker.qml, ui/StatusQ/src/StatusQ/Core/Utils/ModelUtils.qml, ui/StatusQ/src/StatusQ/Core/Utils/qmldir, ui/StatusQ/src/modelutilsinternal.cpp, ui/StatusQ/src/statusq.qrc, ui/StatusQ/tests/CMakeLists.txt, ui/StatusQ/tests/tst_ModelUtilsInternal.cpp, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Chat/views/ChatColumnView.qml, ui/app/AppLayouts/Profile/stores/ProfileStore.qml, ui/app/mainui/activitycenter/views/ActivityNotificationContactRemoved.qml, ui/app/mainui/activitycenter/views/ActivityNotificationContactRequest.qml, ui/app/mainui/activitycenter/views/ActivityNotificationMessage.qml
- `ModelUtils`: optimize `indexOf` by moving implementation to C++
- `ModelUtils`: expose method `persistentIndex` giving possibility to obtain persistent index in QML
- Removes dependency on contact model's `onItemChanged`, unblocking https://github.com/status-im/status-desktop/pull/16667
- Fixes problems with updating activity view delegates after updating contact details (e.g. setting nickname)
Closes: #16754 
`ModelUtils`, `ActivityNotificationMessage` with subclasses
=> `ModelEntryChangeTracker` introduced, removed dependency on contact model's `onItemChanged`

storybook/pages/LoginViewPage.qml, ui/imports/shared/controls/Input.qml
Fixing the login error wrapping issue on login view. Was missing the width.
LoginView
=> fix: Wrap login error message in login view

storybook/pages/ProfileContextMenuPage.qml, ui/app/AppLayouts/Chat/panels/UserListPanel.qml, ui/app/AppLayouts/Chat/views/ChatView.qml, ui/app/AppLayouts/Communities/panels/MembersTabPanel.qml, ui/app/AppLayouts/Profile/views/ContactsView.qml, ui/app/AppLayouts/Profile/views/MyProfileView.qml, ui/app/mainui/Popups.qml, ui/imports/shared/popups/RemoveIDVerificationDialog.qml, ui/imports/shared/views/chat/MessageView.qml, ui/imports/shared/views/chat/ProfileContextMenu.qml
- enhance and fix the SB page to be able to show all the permutations, including profile image, emoji hash and ring
Fixes #16586
ProfileContextMenu
Mark as trusted:
User marked as trusted:
Removing the trusted mark:
Storybook:
=> feat(ProfileContextMenu): Add "Mark as Trusted" and "Remove trusted mark"

ui/app/AppLayouts/Profile/helpers/SettingsEntriesModel.qml, ui/imports/shared/popups/SendContactRequestModal.qml
- fixes contact info loading in `SendContactRequestModal`
- fixes qml warnings from `SettingsEntriesModel`
Closes: #16774
`SendContactRequestModal`, `SettingsEntriesModel`
[Screencast from 14.11.2024 13:47:56.webm](https://github.com/user-attachments/assets/375b4b13-a138-480a-a7d2-cb8126a5dd7b)
=> SendContactRequestModal: fetching contact info fixed 

.github/ISSUE_TEMPLATE/feature-issue.md
Update the feature template to remind about metrics
We might need something similar to https://www.notion.so/Event-Tracking-Specification-Mobile-11a8f96fb65c8032a05efcebea3a1ce6
We started tracking it on our side in https://www.notion.so/Metrics-to-be-collected-7d8139a5a048476b8e6cc9ea51773f0c , i will discuss what is the best place to keep the metrics from now on and then i we will need to place the link in the template of the PR as well
GH PR template
=> chore: add a reminder in feature template to cover metrics

src/app/core/signals/remote_signals/connector.nim, src/app/core/signals/remote_signals/signal_type.nim, src/app/core/signals/signals_manager.nim, src/app/modules/shared_modules/connector/controller.nim, src/app_service/service/connector/service.nim, src/backend/connector.nim, ui/app/AppLayouts/Wallet/services/dapps/DappsConnectorSDK.qml, ui/app/AppLayouts/Wallet/services/dapps/plugins/SignRequestPlugin.qml, ui/imports/shared/stores/BrowserConnectStore.qml
Closes: #16015
Introducing personal_sign to Browser Connect.
https://docs.metamask.io/wallet/reference/json-rpc-methods/personal_sign/
Adding the event handler for personal sign, accept/reject QML slots and accept/reject result signals.
+ Fixed the send transaction parsing. The parsing has been adding unnecessary arguments to the event even if the arguments had no value.
Browser Connect
https://github.com/user-attachments/assets/c8e531e4-20f1-49d5-9b45-336a405039b3
=> fix(BC): Implementing the personal_sign

src/app/modules/shared_modules/connector/controller.nim
Iterates https://github.com/status-im/status-desktop/pull/16767
The send transaction was successful, but the transaction hash is not recognized by the dApp because it was being hashed again.
Browser connect
https://github.com/user-attachments/assets/474fa2f4-0cbe-4d08-bbb4-9584b4b3d30f
=> [BC] Fixing the transaction hash forwarded to the dApp

ui/imports/shared/popups/keycard/states/SelectKeyPair.qml
=> fix(wallet): set up an new keycard with an existing account screen does not show key pairs

storybook/pages/AssetsViewPage.qml, storybook/pages/CollectiblesViewPage.qml, storybook/qmlTests/tests/tst_BannerCard.qml, storybook/qmlTests/tests/tst_BuyReceiveBanner.qml, ui/StatusQ/src/assets.qrc, ui/app/AppLayouts/Wallet/WalletLayout.qml, ui/app/AppLayouts/Wallet/controls/BannerCard.qml, ui/app/AppLayouts/Wallet/panels/BuyReceiveBanner.qml, ui/app/AppLayouts/Wallet/views/CollectiblesView.qml, ui/app/AppLayouts/Wallet/views/RightTabView.qml, ui/imports/shared/views/AssetsView.qml, ui/imports/shared/views/HistoryView.qml
Iterates: #16780 
+ store the card state in user settings
+ amend the BannerCard close button state. It needs to change color on hover and to become visible only when the card is hovered.
+ amend unit tests with the new behavior 
https://github.com/user-attachments/assets/176ff826-6dbc-4a5a-ab10-5649a8f0c482
=> feat(WalletFirst): Integrate the BuyReceiveBanner in the app

storybook/pages/AmountToSendPage.qml, storybook/pages/AmountValidatorPage.qml, storybook/qmlTests/tests/tst_AmountValidator.qml, storybook/qmlTests/tests/tst_SwapInputPanel.qml, ui/StatusQ/src/StatusQ/Validators/AmountValidator.qml, ui/imports/shared/popups/send/views/AmountToSend.qml
fixes #16703
Adapts the send Amount to send as per new simple send modal design https://www.figma.com/design/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=25233-292013&t=lyrihnGzlWTKcnI8-4
AmountToSend.qml
SendModal.qml
SwapModal.qml
https://github.com/user-attachments/assets/1d23dffd-65f2-4b7f-bb9e-36e35569ac4b
=> feat(@desktop/wallet): Adapt AmountToSend for Simple Send

storybook/pages/CurrencyAmountToLocaleStringPage.qml, storybook/qmlTests/tests/tst_SwapModal.qml, ui/StatusQ/src/StatusQ/Core/LocaleUtils.qml, ui/app/AppLayouts/Wallet/panels/SwapInputPanel.qml, ui/imports/shared/popups/send/SendModal.qml
Closes #16828
Add RoundingMode option to `currencyAmountToLocaleString` util.
Max amount shown in SendModal and SwapModal is now always rounded down. That way, if the user enters the amount shown, it will always be <= the real (full-precision) balance.
Wallet: SendModal, SwapModal.
https://github.com/user-attachments/assets/379709cd-054e-493a-b08b-f8058ab66d8f
=> feat(@desktop/wallet): Round down max value in Send and Swap modals

src/app/modules/main/module.nim, src/app/modules/main/wallet_section/send/controller.nim
When some tx send error occurred, no `sentTransaction` field is sent with the event. Some parts of the code reacting to that event were not performing the necessary nil checks, causing a crash. This PR fixes that.
We also bump status-go to bring https://github.com/status-im/status-go/pull/6132/files
=> Properly handle tx send errors

src/app_service/service/accounts/service.nim, src/backend/accounts.nim, src/constants.nim, src/env_cli_vars.nim
Closes https://github.com/status-im/status-desktop/issues/16414
Requires:
- https://github.com/status-im/status-go/pull/6117
1. Added ability to enable `status-go` API logging. Run with `--api-logging` or env var `STATUS_RUNTIME_API_LOGGING=1`.
The log will appear in `<account>/data/api.log` file.
2. Also added proper initialization of logging in status-go. 
Before this PR logs would appear in `geth.log` file only after logging into account, and before logging it it was in in console.
Now all logs go into the file right from the start.
Logging, initialize application
Tick **one**:
=> feat: status-go API logging option

ci/Jenkinsfile.combined, ci/Jenkinsfile.linux, ci/Jenkinsfile.linux-nix, ci/Jenkinsfile.macos, ci/Jenkinsfile.windows
Referenced issue: https://github.com/status-im/status-desktop/issues/16842
Adds Sentry related secrets to env vars for release builds.
Desktop release build.
=> ci: enable sentry in the release builds

src/app/modules/shared_modules/connector/controller.nim, ui/app/AppLayouts/Wallet/services/dapps/DappsConnectorSDK.qml, ui/app/AppLayouts/Wallet/services/dapps/plugins/DAppConnectionsPlugin.qml
closes #16830 
The plugin connection was hardcoded on chainId 1. As a result it was impossible to establish a connection on testnet.
Fixing connection flows to include all supported chains.
Browser connect
https://github.com/user-attachments/assets/f4143439-2bc9-4068-8382-e99ca37cda04
@virginiabalducci @benjthayer This PR proposes an update to the chains selection proposed to the user. In the [BC designs](https://www.figma.com/design/1OYKMzU6KTQHQAqDhojk0r/Status-connector?node-id=2009-321&node-type=frame&m=dev) we're asking the user to approve the dApp session on Mainnet. But this is not accurate (at least until we implement the chains management views). We don't know in advance on what chain the dApp wants to operate on. As a result, the best way forward I see for now is to propose to …
=> fix(BC): Fixing the testnet dApp connection

src/app/global/feature_flags.nim, storybook/pages/SimpleSendModalPage.qml, ui/app/AppLayouts/Wallet/popups/simpleSend/SimpleSendModal.qml, ui/app/AppLayouts/Wallet/popups/simpleSend/qmldir, ui/app/AppLayouts/stores/FeatureFlagsStore.qml, ui/app/mainui/AppMain.qml, ui/app/mainui/SendModalHandler.qml
fixes #16710
Adds new feature flag for Simple Send
Create a mechanism to launch Simple Send in case the flag `FLAG_SIMPLE_SEND_ENABLED` is set to true
Else it will launch normal send as usual.
Simple Send 
=> feat(@desktop/wallet): Adding feature flag for Simple Send until it is ready for release

storybook/pages/DAppsWorkflowPage.qml, storybook/qmlTests/tests/tst_DAppsWorkflow.qml, storybook/qmlTests/tests/tst_DappsComboBox.qml, ui/app/AppLayouts/Wallet/WalletLayout.qml, ui/app/AppLayouts/Wallet/panels/WalletHeader.qml, ui/app/AppLayouts/Wallet/panels/qmldir, ui/app/AppLayouts/Wallet/popups/dapps/DAppsWorkflow.qml, ui/app/AppLayouts/Wallet/popups/dapps/qmldir, ui/app/AppLayouts/Wallet/views/RightTabBaseView.qml, ui/app/mainui/AppMain.qml, ui/imports/utils/Global.qml
closes #16831
Moving the dapp popups to the global scope in order for them to be triggered on any view. There are a few changes required for this:
1. DAppsWorkflow has been split. Previously all popups were declared in the `DappsComboBox`. Now the DAppsWorkflow inherits the QObject instead and the `DappsComboBox` is used as is in the wallet header.
2. The DAppsWorkflow has been moved to AppMain. The DAppsWorkflow will be constructed in the scope of DAppsService and connected directly to the service signals
3. Updated tests and storybook with the new structure
4. Removed the `dAppsService` from `Global`. There's no reason to keep the `dAppsService` instance in the `Global` singleton.
Extra: Reduce the test execution time by configuring a 200ms timeout.
WalletConnect
BrowserConnect …
=> refactoring(dapps): Move WC and BC popups in the global scope

ui/imports/shared/popups/walletconnect/ConnectDAppModal.qml
closes: #16829
Adding NoAutoClose option to the popup.
Removing the close button in the popup header.
This will align the connect modal to the sign modal close policy.
WalletConnect
BrowserConnect
https://github.com/user-attachments/assets/4aa833cf-52d7-49b9-b5cb-d7840a976ce9
=> fix(dapps): Update the connect modal close policy

ui/app/AppLayouts/Chat/views/ChatMessagesView.qml, ui/app/mainui/AppMain.qml
Fixes https://github.com/status-im/status-desktop/issues/16098
The first problem was just a misplaces parenthesis. It prevented the Chat section badge to appear.
The second problem was that we were marking messages as read even if the app is in the background,  because the chat kept scrolling, even if the app was not active.
I fixed that by only marking as read if the app is active. I added a Connections to the active property of the Applicaiton too to mark as read when the app comes back active.
I also removed a condition that prevented the Unread messages line appearing in that condition.
Now, when a message is sent to the active chat, but the app is not in focus, the red dot appears, as well as the badges. Then when the app comes active, it is marked as read, but the unread messages …
=> Fix unread badge on the chat section button + fix unread count not being counted when the  chat is active and the app is not in focus

ui/app/AppLayouts/Chat/views/ChatHeaderContentView.qml
Fixes #16688
Fixes the issue by adding a version to the URL on the status-go side. No extra code needed on our side. The only change is that we no longer need the `addTimestampToURL` hack for the community now.
Status-go PR: https://github.com/status-im/status-go/pull/6118
Community image url
[edit-img.webm](https://github.com/user-attachments/assets/391934b7-6757-4118-96e7-96d6e67a263f)
Note that the app on the right is on master, hence why it still has the issue
Updated image will show straight away
- Update the image of your community
- Update the image of a community you joined or spectated
Tick **one**:
Worst case: the bug still happens
=> fix(community): fix community image not updating

src/app/modules/main/chat_section/chat_content/messages/controller.nim, src/app/modules/main/chat_section/chat_content/messages/io_interface.nim, src/app/modules/main/chat_section/chat_content/messages/module.nim, src/app/modules/main/chat_section/chat_content/messages/view.nim, src/app_service/service/message/service.nim, src/backend/messages.nim, ui/app/AppLayouts/Chat/stores/MessageStore.qml, ui/imports/shared/views/chat/MessageView.qml
Fixes #16741
status-go PR: https://github.com/status-im/status-go/pull/6133
The problem was that we replaced the ContentType from Image to Text, so on restart, it doesn't understand it had images anymore.
Fixed in status-go by reusing the ContentType of the original message.
This makes it so that we don't need to pass the ContentType from Nim anymore, so I removed that param from the code.
Message edits
[edit-images.webm](https://github.com/user-attachments/assets/53ce366b-91d3-4a21-87e9-ab60c6dc76e0)
Fixes editing messages with Images
1. Send an image or images
2. Edit the message on it
3. restart the app
Tick **one**:
Worst case: the issue still happens
=> fix(edit): fix message edits loses the album of images

ui/StatusQ/src/StatusQ/Components/StatusMessage.qml, ui/app/AppLayouts/Chat/popups/PaymentRequestModal.qml
Fixes #16870
Fixes #16869
* Fixed popup height, so that network selector isn't clipped
* Fixed import. That caused the payment request list to disappear. This also affected gifs and link previews.
Chat view
https://github.com/user-attachments/assets/15607a1f-8f58-4289-8d0b-bd3bec4211f1
See decription at beginning
Height: Open payment request
Edit: Edit message with payment request in it.
Payment Request
Tick **one**:
=> fix(chat): Fix disappearing payment request after message edit

src/app/modules/main/communities/tokens/models/token_model.nim
closes: #16875 #16860 #16859
NOTE: These bugs are reproducible when the minting fails on status-go side.
Fixing the out-of-bounds exception that's crashing the app.
Community tokens
=> fix(CommunityTokens): Fixing crash on token update

ui/imports/shared/views/SyncingDeviceView.qml
- re-add forgotten `Layout.alignment: Qt.AlignHCenter`
Fixes #16879
Settings/Syncing
=> fix(SyncingDeviceView): fix user image misalignment

src/app/modules/main/wallet_section/send/module.nim
The code followed the `signOnKeycard` param, but the key pair itself should not be signed on the keycard, which is true. However, for the local signing, in case when the profile is migrated to a keycard we should not hash the password, just use the enc pub key as the password and that check was missed. It has been added now.
fixes: #16901
=> fix(wallet): cannot sing tx sent from imported key pair if the profile is migrated to keycard

storybook/pages/DappsComboBoxPage.qml, ui/app/AppLayouts/Wallet/WalletLayout.qml, ui/app/AppLayouts/Wallet/controls/DappsComboBox.qml, ui/app/AppLayouts/Wallet/panels/WalletHeader.qml, ui/app/AppLayouts/Wallet/views/RightTabBaseView.qml, ui/app/mainui/AppMain.qml, ui/imports/shared/popups/walletconnect/ConnectDAppModal.qml
closes #16883 #16882
1. connect the dapps service online state to the enabled state for the dapps button
2. Fix the connect modal primary action button
3. Align DappsComboBox disabled color with the refresh button disabled color
dapps
https://github.com/user-attachments/assets/c62f4787-0ca8-452b-a3b6-a621fc253217
=> fix(dapps): Fixing the dApps disabled state if the dapps service is not online

ui/app/AppLayouts/Wallet/popups/dapps/DAppsWorkflow.qml, ui/app/AppLayouts/Wallet/services/dapps/DAppsService.qml, ui/imports/shared/popups/walletconnect/PairWCModal.qml
closes #16887
The pairing popup can be destroyed while the pair instructions popup is active. As a result the pair instructions popup will misbehave. To fix this, the pair instructions component is moved outside of the pair popup scope
dapps
https://github.com/user-attachments/assets/110ffc5f-fdaa-4ff3-aad2-b4f1f374b6b9
=> fix(dapps): Detach the pair instructions popup from the pairing popup

src/app/modules/main/wallet_section/send/module.nim
Cleaning parameters was done earlier than when needed for the swap.
fixes: #16867
=> fix(swap): after approving spending cap with a keycard the swap transaction fails

src/app_service/service/wallet_account/async_tasks.nim, src/backend/backend.nim
Corresponding `statusgo` PR: 
- https://github.com/status-im/status-go/pull/6160/files
This PR aligns with the updated `fetchOrGetCachedWalletBalances ` call. A new param was added to the call.
=> chore(wallet): added param to fetchOrGetCachedWalletBalances call to align with statusgo change

ci/Jenkinsfile.combined, ci/Jenkinsfile.linux, ci/Jenkinsfile.linux-nix, ci/Jenkinsfile.macos, ci/Jenkinsfile.tests-e2e, ci/Jenkinsfile.tests-nim, ci/Jenkinsfile.tests-ui, ci/Jenkinsfile.windows, ci/cpp/Jenkinsfile.linux, ci/cpp/Jenkinsfile.macos, ci/cpp/Jenkinsfile.windows
This PR updates `status-jenkins-lib` which contains the fixes for `getVersion` function throwing an exception when `VERSION` file was not found.
Also reverts @igor-sirotin 's recent change since thats not needed anymore.
relevant changes in `status-jenkins-lib`: https://github.com/status-im/status-jenkins-lib/pull/106
none, this just fixes the build issues which happen in nightly
- Run nightly job from this branch
=> Fix e2e version not found

src/app/modules/shared_modules/keycard_popup/module.nim
=> fix(wallet): cannot recover Status profile if there is no metadata on a keycard

storybook/pages/CollectiblesSelectionAdaptorPage.qml, storybook/pages/SendModalFooterPage.qml, storybook/pages/SimpleSendModalPage.qml, storybook/pages/SimpleTransactionsFeesPage.qml, ui/app/AppLayouts/Wallet/adaptors/CollectiblesSelectionAdaptor.qml, ui/app/AppLayouts/Wallet/controls/TokenSelector.qml, ui/app/AppLayouts/Wallet/panels/RecipientSelectorPanel.qml, ui/app/AppLayouts/Wallet/panels/SendModalHeader.qml, ui/app/AppLayouts/Wallet/panels/SimpleTransactionsFees.qml, ui/app/AppLayouts/Wallet/panels/StickySendModalHeader.qml, ui/app/AppLayouts/Wallet/panels/qmldir, ui/app/AppLayouts/Wallet/popups/simpleSend/SimpleSendModal.qml, ui/app/AppLayouts/Wallet/views/RecipientView.qml, ui/app/AppLayouts/Wallet/views/SendModalFooter.qml, ui/app/AppLayouts/Wallet/views/qmldir, ui/app/mainui/AppMain.qml, ui/app/mainui/SendModalHandler.qml, ui/imports/shared/popups/send/views/AmountToSend.qml
fixes #16820, #16835, #16878
Adds logic to set and expose selected network, token and account. 
Also add synchronisation for the 2 header instances (sticky + scrollable)
SimpleSend.qml
https://github.com/user-attachments/assets/f36124a9-3836-4c4f-afbe-c4c4103b9498
https://github.com/user-attachments/assets/8b6fe65e-f569-4ceb-9224-9c61bae7af16
=> feat(@desktop/wallet): Adding features of Account, Network and Token Selection to the popup

src/app/modules/main/profile_section/wallet/module.nim, src/app/modules/main/profile_section/wallet/view.nim, src/app/modules/main/wallet_section/module.nim, src/app/modules/main/wallet_section/view.nim
Adds missing notification on `keypairImportModule` change.
Without the notification it was possible to use `keypairImportModule` only directly, e.g.:
```qml
sourceComponent: KeypairImportPopup {
store.keypairImportModule: walletSection.keypairImportModule
}
```
Assigning the module to some property and using it via that property wasn't working because the lack of change propagation.
With the change introduced, changes are notified and `keypairImportModule` can be used indirectly as any other object.
Closes: #16773
`profile_section/wallet/module.nim`
`profile_section/wallet/view.nim`
`wallet_section/module.nim`
`wallet_section/view.nim` …
=> Wallet: add missing notification on keypairImportModule change

src/app/modules/main/controller.nim
Fixes #16957
We didn't listen to the event in the main module.
[nickname-update.webm](https://github.com/user-attachments/assets/7665d609-e790-48b4-8e89-9bd3cbd75f27)
=> fix(admin): fix nicknames not showing in the admin tab immediately

ui/StatusQ/src/StatusQ/Components/StatusMessageHeader.qml, ui/imports/shared/views/chat/LinksMessageView.qml
- when clicking the underlined profile name; the prob was that `TapHandler` (unlike a `MouseArea`) is not a visual `Item` and hence can't be a parent for the context menu
- small (unrelated) typo fix to unbreak GIF link previews...
Fixes #16950
StatusMessageHeader
=> [CHERRY-PICK] fix(StatusMessageHeader): unbreak context menu

ui/app/AppLayouts/Chat/views/ChatContentView.qml
Fixes #16951
The property `isContactBlocked` was not passed to the component.
=> fix(chat): fix blocked contact being able to be sent a CR

src/app/modules/main/controller.nim
Cherry-pick of https://github.com/status-im/status-desktop/pull/16959
Fixes #16957
We didn't listen to the event in the main module.
=> [CHERRY-PICK] fix(admin): fix nicknames not showing in the admin tab immediately

ui/app/AppLayouts/Chat/views/ChatContentView.qml
Cherry-pick of https://github.com/status-im/status-desktop/pull/16954
Fixes #16951
The property `isContactBlocked` was not passed to the component.
=> [CHERRY-PICK] fix(chat): fix blocked contact being able to be sent a CR (#16954)

src/app/modules/main/communities/controller.nim, src/app_service/service/community/service.nim
Fixes #16967
I cannot confirm for sure if the crash is fixed.
However, using the trace from the crash, I removed the function that caused the crash, since it's not useful, and since then, I couldn't reproduce the issue. The problem is that the issue was not that easily reproducible.
@anastasiyaig if you could give it a run and tell me if you can reproduce in the same conditions, it would be great. Thanks
=> fix(curated): fix crash when loading curated communities

src/app/modules/main/chat_section/module.nim, src/app_service/service/chat/service.nim, src/app_service/service/contacts/service.nim, src/backend/contacts.nim
Fixes #16640
This makes it so that when you block a contact, it now also removes the chat and the messages as expected by the requirements and as Mobile does.
To do so, I use the same API as mobile instead of the forked desktop one. I removed the desktop one as it is no longer needed [(see status-go PR)](https://github.com/status-im/status-go/pull/6172)
I also fixed an issue when unblocking where it would send a double toast messages with one saying you "removed the contact", but it was already removed.
Chat and contacts
[block-user.webm](https://github.com/user-attachments/assets/15eceac5-819f-4f1c-960f-65ec5f25003c)
Removes the chat and …
=> fix(block): remove chat and messages when blocking a contact

src/app/modules/main/profile_section/contacts/controller.nim, src/app/modules/main/profile_section/contacts/io_interface.nim, src/app/modules/main/profile_section/contacts/module.nim, src/app/modules/main/profile_section/contacts/view.nim, ui/app/AppLayouts/Chat/panels/UserListPanel.qml, ui/app/AppLayouts/Profile/stores/ContactsStore.qml, ui/app/mainui/Popups.qml, ui/app/mainui/ToastsManager.qml
- listen to the NIM's signal `SIGNAL_REMOVED_TRUST_STATUS`
- emit a signal for QML signal accordingly
- emit a toast/notification as a result
Fixes #16949
Profile
Marked as untrusted:
Removed the untrusted mark:
=> fix: No toast on removal of untrusted mark

src/app/boot/app_controller.nim, src/app/global/feature_flags.nim, src/app/modules/onboarding/controller.nim, src/app/modules/onboarding/io_interface.nim, src/app/modules/onboarding/module.nim, src/app/modules/onboarding/view.nim
Part of #16832
Adds the basic files needed for the new onboarding, aka onboarding V2. It does not do anything yet, but it's ready to be implemented.
It is locked behind a feature flag.
To enable it,  run the app with `export FLAG_ONBOARDING_V2_ENABLED=1`
Creating a small PR straightaway, that way subsequent PRs will be easier to review, since it won't contain all the file creation.
=> chore(onboarding): add scaffolding for the new onboarding

ci/Jenkinsfile.tests-e2e, test/e2e/conftest.py, test/e2e/fixtures/aut.py, test/e2e/gui/screens/settings.py, test/e2e/pytest.ini, test/e2e/tests/settings/settings_keycard/__init__.py, test/e2e/tests/settings/settings_keycard/test_check_whats_on_keycard.py, test/e2e/tests/settings/settings_keycard/test_create_keycard_account_with_new_seed_phrase.py, test/e2e/tests/settings/settings_keycard/test_factory_reset_keycard.py, test/e2e/tests/settings/settings_keycard/test_import_restore_keycard_via_seed_phrase.py, test/e2e/tests/settings/settings_keycard/test_setup_existing_account.py, test/e2e/tests/settings/settings_keycard/test_unlock_keycard.py, test/e2e/tests/wallet_main_screen/wallet - plus button/test_plus_button_use_keycard.py
Fixes https://github.com/status-im/status-desktop/issues/15741
- rename mark to `keycard`
- change fixture to rely on mark instead of tests path
- uncomment and fix all the keycard tests
- change the selection of tests for nightly run to exclude keycard tests instead of skipping them. These tests can't be run in nightly because we require a special build (with mocked keycard lib). However, there will be then a possibility to run these tests on Jenkins via manual launch
=> chore(@e2e): update mark for keycard tests

test/e2e/constants/community.py, test/e2e/gui/elements/object.py, test/e2e/gui/objects_map/communities_names.py, test/e2e/gui/screens/community.py, test/e2e/gui/screens/community_settings.py, test/e2e/gui/screens/messages.py, test/e2e/tests/communities/test_communities_kick_ban.py, test/e2e/tests/communities/test_communities_pin_and_unpin_messages.py, test/e2e/tests/communities/test_communities_send_accept_decline_request_from_profile.py, ui/app/AppLayouts/Communities/panels/CommunityBannedMemberCenterPanel.qml
reimplement test for banning and kicking community member. What the test does now:
- creates 2 separate users, adds them to mutual contacts
- creates community, invites a user to community
- as community owner (control node) - ban community member -> check notification about this action + check that user is listed on the Banned members tab
- as banned member, check that community disappeared from the left pane. open the community by clicking direct link from chat and verify that messages about being banned appears
- as community owner, unban user, check notification about this action
- as banned member -> open community by direct link and wait for a notification that you are unbanned. Note: the notification is not coming when you are not opening the community link it seems, i have to …
=> tests: reimplement test for banning and kicking community member

storybook/pages/OnboardingLayoutPage.qml, storybook/qmlTests/tests/tst_OnboardingLayout.qml, storybook/src/Storybook/StorybookUtils.qml, ui/StatusQ/src/statusq.qrc, ui/app/AppLayouts/Onboarding2/CreateNewProfileFlow.qml, ui/app/AppLayouts/Onboarding2/KeycardCreateProfileFlow.qml, ui/app/AppLayouts/Onboarding2/LoginBySyncingFlow.qml, ui/app/AppLayouts/Onboarding2/LoginWithKeycardFlow.qml, ui/app/AppLayouts/Onboarding2/OnboardingFlow.qml, ui/app/AppLayouts/Onboarding2/OnboardingLayout.qml, ui/app/AppLayouts/Onboarding2/OnboardingStackView.qml, ui/app/AppLayouts/Onboarding2/RecoveryPhraseCreateProfileFlow.qml, ui/app/AppLayouts/Onboarding2/UseRecoveryPhraseFlow.qml, ui/app/AppLayouts/Onboarding2/pages/KeycardEnterPinPage.qml, ui/app/AppLayouts/Onboarding2/qmldir
Decomposes `OnboardingLayout` into following elements:
- `OnboardingFlow` orchestrating all on-boarding flows on the stack
- `OnboardingStackView` which is specifically configured `StackView` for handling all on-boarding flows
- `OnboardingLayout` itself integrating `OboardingFlow` with stores and `OnboardingStackView`
Moreover `OnboardingFlow` consists of sub-flows:
- `CreateNewProfileFlow`
- `KeycardCreateProfileFlow`
- `RecoveryPhraseCreateProfileFlow`
- `LoginBySyncingFlow`
- `LoginWithKeycardFlow`
- `UseRecoveryPhraseFlow`
Flows don't operate on own `StackView`, which must be provided from outside. This allows to compose complex flows from smaller ones within one `StackView`.
Other:
- little change in syncing flow, retry causes instantaneous retry with the previously provided …
=> feat(OnboardingLayout): Decompose into smaller, pure ui sub-flows

src/app/modules/main/chat_section/chat_content/controller.nim, src/app/modules/main/chat_section/chat_content/io_interface.nim, src/app/modules/main/chat_section/chat_content/module.nim, src/app_service/service/message/service.nim
Fixes https://github.com/status-im/status-desktop/issues/16639
- Fixes edits not showing up in pins until a restart
- Fixes deleted messages reappearing in the pinned messages after a restart (status-go PR: https://github.com/status-im/status-go/pull/6173)
Pins
[pin-fixes.webm](https://github.com/user-attachments/assets/e3a46b46-ca7a-4366-b534-2f870c787f94)
Fixes some scenarios of using pinned messages
- Follow the repro steps in the og issue
- Delete the message that is pinned and restart
Tick **one**:
Worst case is issue still happens
=> Fixes to pinned messages

src/app/modules/main/chat_section/chat_content/users/module.nim, src/app/modules/main/controller.nim, src/app/modules/main/module.nim, src/app/modules/shared_models/member_model.nim, src/app/modules/shared_models/section_item.nim, src/app/modules/shared_models/section_model.nim, test/nim/member_model_test.nim, ui/app/AppLayouts/Chat/panels/UserListPanel.qml
Fixes #16948 and #16952
The problem was that we just didn't pass `isBlocked` to the `Item`. So either it never worked or we broke it during the refactors.
We also didn't have updates when the events were called in the main module.
Same thing for the `contactRequest`
Member list in the admin panel and on the right bar of a community.
Block/unblock:
[block-unblock.webm](https://github.com/user-attachments/assets/51aafa9f-d786-47a3-a937-de3eac29983d)
CR:
[contact-request-context-menu.webm](https://github.com/user-attachments/assets/77595a82-debf-4e28-be5e-0089148cf8b8)
Fixes the issue of missing updates
- Block and unblock a user and check the different member lists
- Send a contact request to the user and check the member lists
Tick **one**:
Worst case, the issue still happens
=> Fix context menus not updating when blocking/unblocking or when getting a CR

src/app/modules/main/app_search/location_menu_sub_item.nim, src/app/modules/main/app_search/location_menu_sub_model.nim, src/app/modules/main/app_search/module.nim, src/app/modules/main/chat_section/module.nim, src/app_service/service/chat/dto/chat.nim, ui/StatusQ/src/StatusQ/Popups/StatusSearchLocationMenu.qml
Fixes #10184
- Fixes the order of channels in the location menu
- Makes sure that only channels that can be read are shown in the location menu
Missing part: the emoji size wasn't fixed as I need help
Location menu in the search popup
Fixed order: 
Spectated community not appearing:
Encrypted channels don't show:
Fixes the location menu
1. Be part of a community with lots of channels with categories
2. Press CTRL+F
3. Check the location menu for the channels of that community
4. Have an encrypted channel (a channel the user can't view)
5. As a member of the channel (not owner), check the menu again
6. The encrypted channel doesn't show
Tick …
=> Fix some search issues

ui/app/mainui/activitycenter/views/ActivityNotificationContactRequest.qml
Fixes #16601
The original issue of seeing `&nbsp;`  was already fixed, but the popup, when opening from the activity center didn't have any spaces. However, when displayed from the profile, everything showed fine. So the fix was simply to remove the old way of opening from the AC and use the same call that is used in the profile popup.
Review contact request popup (when opened from the AC)
Fixes the issue with spaces not working in the popup
0. Receive a CR that contains spaces
1. Go in the AC and click the three dots on the right
2. Click "Details"
Everything should look ok
Tick **one**:
Worst case the spaces look weird still
=> fix(ac): fix review CR popup not showing correct data from the AC

src/app/modules/main/chat_section/controller.nim, src/app/modules/main/chat_section/io_interface.nim, src/app/modules/main/chat_section/module.nim, src/app/modules/main/chat_section/view.nim, src/app_service/service/chat/service.nim, src/app_service/service/community/service.nim, src/backend/communities.nim, ui/app/mainui/AppMain.qml
Fixes #16573
Adds the "Mark as read" to the community context menu that marks all channels in the community as read
Community context menu
[mark-as-read.webm](https://github.com/user-attachments/assets/f476c4ed-7256-40ec-bf8f-c52dff349c5a)
New feature
- Mark some messages as unread or receive new messages
- Click the new option in the context menu
Tick **one**:
Worst case, the feature doesn't work lol
=> feat(community): add mark as read to community button

ui/StatusQ/src/StatusQ/Popups/Dialog/StatusDialog.qml, ui/app/AppLayouts/Profile/views/MyProfileView.qml
- we are inside Settings, and `isCurrentUser` needs to be true for the profile perspective selector (aka the "Preview as..." combo) to be shown
- also fix the (unrelated) warning about `Window` being null
Fixes #17041
Settings/Profile
=> fix(MyProfileView): unbreak showing the "Preview as..." combo

src/app/core/tasks/threadpool.nim
Don't log the data shared between threads to reduce the risk of sensitive data leaks.
=> fix: Remove threadpool data from logs on production builds

storybook/pages/OnboardingLayoutPage.qml, storybook/qmlTests/tests/tst_OnboardingLayout.qml, ui/app/AppLayouts/Onboarding2/KeycardCreateProfileFlow.qml, ui/app/AppLayouts/Onboarding2/LoginBySyncingFlow.qml, ui/app/AppLayouts/Onboarding2/LoginWithKeycardFlow.qml, ui/app/AppLayouts/Onboarding2/OnboardingFlow.qml, ui/app/AppLayouts/Onboarding2/OnboardingLayout.qml, ui/app/AppLayouts/Onboarding2/pages/KeycardAddKeyPairPage.qml, ui/app/AppLayouts/Onboarding2/pages/KeycardCreatePinPage.qml, ui/app/AppLayouts/Onboarding2/pages/KeycardEnterPinPage.qml, ui/app/AppLayouts/Onboarding2/pages/SyncProgressPage.qml, ui/imports/shared/panels/EnterSeedPhrase.qml
- exposes states controlling the flow to the Storybook page
- makes the Storybook page easier to use by adding contextual actions depending on the current page
- fixes some missing interactions with the store
- removes some timeouts that should not be handled directly on the ui level
- makes unit test for OnboardingLayout very fast
Closes: #17030
Closes: #17031
Closes: #17032
Onboarding flows
=> Onboarding flows: SB page improvements, timeouts removal and other minor fixes

ci/Jenkinsfile.windows
Possibly cause of signature verifiction checks.
=> fix(ci): revert to using DigiCert timeserver by default

storybook/pages/ContactsViewPage.qml, ui/app/AppLayouts/Profile/ProfileLayout.qml, ui/app/AppLayouts/Profile/panels/ContactPanel.qml, ui/app/AppLayouts/Profile/panels/ContactsListPanel.qml, ui/app/AppLayouts/Profile/views/ContactsView.qml, ui/app/mainui/AppMain.qml, ui/app/mainui/adaptors/ContactsModelAdaptor.qml, ui/imports/utils/Constants.qml
Fixes https://github.com/status-im/status-desktop/issues/16844
Adds a tab in the Messaging>Contacts page that shows the dismissed contact requests.
it has a button to undo the rejection. That is simply a call to accept the old contact request, which then makes the two users mutual contacts
The first commit just adds tooltips to the buttons for the panel as the button without tooltip was very confusing.
Contacts settings in Messaging
[dismissed-tab.webm](https://github.com/user-attachments/assets/118b597b-26e8-4ec7-b482-508f5b251346)
Makes it clearer that you can undo a dismissed contact request.
0. Receive a contact request
1. Dismiss it
2. …
=> Add a "Dismissed contact requests" tab in the Contacts panel

ui/app/AppLayouts/Communities/popups/CommunityRulesPopup.qml, ui/app/AppLayouts/Communities/popups/qmldir, ui/app/mainui/AppMain.qml, ui/app/mainui/Popups.qml
Fixes #16826
Adds the option to see the community rules in the community context menu on the left.
Also adapts a few things according to designs.
Community context menu
Design: 
App:
It's now possible to see the community rules after joining
- Right click a community a click "View community rules"
Tick **one**:
Worst case: :shrug:
=> feat(community): add option to see community rules

ci/Jenkinsfile.combined, ci/Jenkinsfile.macos, test/e2e/configs/squish.py
- fixes https://github.com/status-im/status-desktop/issues/17077. The issue was that we were relying on BUILD_NUMBER env var, which was wrong (we started exceeding the max port range)
- rename linux nix stage in order to avoid confusion
=> chore(@e2e): don't rely on build number env var when generating port number

src/app/modules/main/wallet_section/assets/view.nim, src/app/modules/main/wallet_section/view.nim, src/app_service/service/token/service.nim
Closes #16994
Check if something has actually change in prices before reseting the wallet.
This would be the first line of defense for token prices updates. It seems to be enough for the send modal performance improvements.
The full solution to this issue (and maybe to a lot of wallet related UI perf issues) would be to send granular QML updates only for values that have actually changed. But this implies extensive nim+qml refactoring.
SendModal
SwapModal
=> fix(perf): Optimize token prices propagation

test/e2e/tests/wallet_main_screen/wallet - right click out of account area/test_right_click_manage_watched_address.py, ui/app/AppLayouts/Wallet/views/AccountContextMenu.qml, ui/app/AppLayouts/Wallet/views/LeftTabView.qml, ui/imports/shared/popups/addaccount/AddAccountPopup.qml, ui/imports/shared/popups/addaccount/states/Main.qml, ui/imports/shared/popups/addaccount/stores/AddAccountStore.qml, ui/imports/utils/Constants.qml
closes #15995
Revert the changes done by https://github.com/status-im/status-desktop/issues/15979 to enable the watch accounts on release.
=> Re-enable watch only accounts on release

test/e2e/constants/user.py, test/e2e/gui/screens/wallet.py, test/e2e/tests/crtitical_tests_prs/test_add_edit_delete_generated_account.py, test/e2e/tests/settings/settings_wallet/test_wallet_settings_add_account.py, test/e2e/tests/wallet_main_screen/wallet - plus button/test_plus_button_add_watched_address.py, test/e2e/tests/wallet_main_screen/wallet - plus button/test_plus_button_manage_account_added_for_new_generated_seed.py, test/e2e/tests/wallet_main_screen/wallet - plus button/test_plus_button_manage_account_from_private_key.py, test/e2e/tests/wallet_main_screen/wallet - plus button/test_plus_button_manage_account_from_seed_phrase.py, test/e2e/tests/wallet_main_screen/wallet - plus button/test_plus_button_manage_generated_account_custom_derivation_path.py, test/e2e/tests/wallet_main_screen/wallet - right click on account/test_context_menu_edit_default_account.py, test/e2e/tests/wallet_main_screen/wallet - right click out of account area/test_right_click_manage_watched_address.py, test/e2e/tests/wallet_main_screen/wallet - saved addresses/test_saved_addresses.py
refer to random wallet account data where possible instead of hardcoded values
=> chore(@e2e): switch to wallet account data class instance

src/app/boot/app_controller.nim, src/app/modules/onboarding/controller.nim, src/app/modules/onboarding/io_interface.nim, src/app/modules/onboarding/module.nim, src/app/modules/onboarding/view.nim, ui/StatusQ/src/onboarding/enums.h, ui/app/AppLayouts/Onboarding2/OnboardingLayout.qml, ui/app/AppLayouts/Onboarding2/stores/OnboardingStore.qml, ui/app/AppLayouts/stores/FeatureFlagsStore.qml, ui/app/mainui/AppMain.qml, ui/main.qml
Fixes [#17044 ](https://github.com/status-im/status-desktop/issues/17004)
(I'll create a new issue for unhappy paths)
Branched on top of https://github.com/status-im/status-desktop/pull/16722
Integrates all the non-keycard flows for the new onboarding. All happy paths for those should work, including the pairing fallback.
Do note that the new onboarding only applies for **new** users. If you have a profile already, it will show the old startup/login/onboarding.
This is because the new screens for the Login are not implemented yet and the LoginView is super tied with the old startup module, so it's not worth it to extract it.
To use the new onboarding, you need to delete or rename your data folder.
Then, run the app with `export FLAG_ONBOARDING_V2_ENABLED=1`.
None by default, because all …
=> New onboarding integration (happy paths)

storybook/pages/DAppsMetricsPage.qml, storybook/pages/DAppsWorkflowPage.qml, storybook/pages/DappsComboBoxPage.qml, storybook/qmlTests/tests/tst_ChainsSupervisorPlugin.qml, storybook/qmlTests/tests/tst_DAppsWorkflow.qml, storybook/qmlTests/tests/tst_DappsComboBox.qml, storybook/stubs/shared/stores/qmldir, ui/app/AppLayouts/Wallet/WalletLayout.qml, ui/app/AppLayouts/Wallet/controls/DappsComboBox.qml, ui/app/AppLayouts/Wallet/helpers/ChainsAvailabilityWatchdog.qml, ui/app/AppLayouts/Wallet/panels/WalletHeader.qml, ui/app/AppLayouts/Wallet/popups/dapps/DAppsWorkflow.qml, ui/app/AppLayouts/Wallet/services/dapps/DAppsMetrics.qml, ui/app/AppLayouts/Wallet/services/dapps/DAppsModule.qml, ui/app/AppLayouts/Wallet/services/dapps/WalletConnectSDK.qml, ui/app/AppLayouts/Wallet/services/dapps/WalletConnectSDKBase.qml, ui/app/AppLayouts/Wallet/services/dapps/helpers.js, ui/app/AppLayouts/Wallet/services/dapps/plugins/ChainsSupervisorPlugin.qml, ui/app/AppLayouts/Wallet/services/dapps/plugins/DAppConnectionsPlugin.qml, ui/app/AppLayouts/Wallet/services/dapps/plugins/SiweRequestPlugin.qml, ui/app/AppLayouts/Wallet/services/dapps/qmldir, ui/app/AppLayouts/Wallet/services/dapps/types/SessionRequestsModel.qml, ui/app/AppLayouts/Wallet/views/RightTabBaseView.qml, ui/app/mainui/AppMain.qml, ui/imports/shared/popups/walletconnect/controls/DAppDelegate.qml
closes #16912
Sending the dapps events to mixpanel
Events structure: https://www.notion.so/Event-Tracking-Specification-Desktop-1518f96fb65c8026a3a5c8a0459f7f21?pvs=4#63de5b7c3b6c4a7cab492cff6aa95957
Events description: https://www.notion.so/Metrics-for-Wallet-Connect-d3d1e60e7ea24479bd35cbb11219540c?pvs=4#375a52965a98458eb45b2e2eea6a4bd5
New board created here: https://eu.mixpanel.com/s/3kYRpk
+ Moved the `Connect dialog` from dapps comboBox to the dappsWorkflow where the other modals are placed
+ Extend component with necessary signals/functions of collect metrics data
+ Update tests and storybook
+ Implement fully functional storybook metrics page to test the events with Mixpanel
dapps …
=> feat(dapps): Adding dapp metrics

ui/StatusQ/src/StatusQ/Components/StatusChatList.qml
Fixes #17016
Sets the channel as visible when it has unread messages, but not muted, or has a notification (reply or mention) or it's active, even when collapsed.
Channel list (only for communities)
Unread messages (shows even if it's collapsed):
Active channel (shows even if read and collapsed):
Muted channel (doesn't show):
Muted but it's a notification (shows even if muted and collapsed):
Makes it easier to manage a community with a lot of channels. Currently, it's not useful to collapse unmuted categories, because then when you have messages in a collapsed channel, you have to manually open the category to see which channel it is.
With …
=> feat(channel): show channels with unread messages  even if collapsed

storybook/pages/SimpleSendModalPage.qml, ui/app/AppLayouts/Wallet/adaptors/CollectiblesSelectionAdaptor.qml, ui/app/mainui/SendModalHandler.qml
Filters out community owner and master tokens from the tokens list in the new single network send modal
SimpleSendModal
=> feat(@desktop/wallet): Filter out community owner and master tokens rom single network send modal

storybook/qmlTests/tests/tst_SwapInputPanel.qml, storybook/qmlTests/tests/tst_SwapModal.qml, storybook/qmlTests/tests/tst_TokenSelectorViewAdaptor.qml, ui/app/AppLayouts/Wallet/WalletLayout.qml, ui/app/AppLayouts/Wallet/WalletUtils.qml, ui/app/AppLayouts/Wallet/adaptors/TokenSelectorViewAdaptor.qml, ui/app/AppLayouts/Wallet/panels/SearchableAssetsPanel.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapModal.qml, ui/app/mainui/Popups.qml, ui/imports/utils/Global.qml
Closes #16981
Fixing the performance issues related to the data transformations done in `TokenSelectorViewAdaptor.qml` by reducing the complexity.
There are two inputs in the adaptor. The assets with balances submodels and a plain model of all tokens.
The output consists in a single model holding the assets with transformed balances as plain properties.
There are two options for the adaptor: To show all tokens,  or only the tokens with positive balance. When the output model provides all tokens, the ones with positive balance will be the first ones in the list, with a specific `sectionName` property.
The main culprit for the bad performance was that we've been transforming the two input models, concatenating the items in a single model and then process the model again to remove the …
=> perf(SwapModal): improve the performance on tokenSelectorAdaptor

src/app_service/service/accounts/dto/login_request.nim, src/app_service/service/accounts/service.nim, storybook/qmlTests/tests/tst_BuyCryptoModal.qml, ui/app/AppLayouts/Wallet/panels/BuyCryptoProvidersListPanel.qml, ui/app/AppLayouts/Wallet/popups/buy/BuyCryptoModalAdaptor.qml
Closes #17069
Needs https://github.com/status-im/status-go/pull/6253/
Revert "feat: hide mercuryo"
This reverts commit https://github.com/status-im/status-desktop/commit/22c4bb2846c2a88f79ccb326fbbb885ead077d41.
This reverts commit https://github.com/status-im/status-go/commit/43056094932b9b15cce5827a19dafc27cf8160a6.
+ Adapt changes
=> 17069 wallet bring back mercuryo

src/app/modules/onboarding/module.nim, ui/app/AppLayouts/Onboarding2/OnboardingLayout.qml, ui/app/AppLayouts/Onboarding2/stores/OnboardingStore.qml, ui/imports/utils/Utils.qml, ui/main.qml
Fixes #17047
Hooks the same old metrics we had previously to the new onboarding.
The only difference is we cannot easily track the flow during page navigation because the flow is often jsut sent at the end. Anyway, I think mobile also doesn't give it and it's easy to infer the flow from the page name.
I added a required property to the OnboardinPages so that we cna get the page name and send it. If it's not set on some page, we just don't send a metric.
Onboarding metrics
None, it works as before
- Either enable the metrics in the onbaording and then check the metrics on mixpanel or just check the logs. You'll see …
=> feat(onboarding): hook metrics to the new onboarding

storybook/pages/StatusButtonPage.qml, storybook/qmlTests/tests/tst_StatusButton.qml, ui/StatusQ/src/StatusQ/Controls/StatusBaseButton.qml, ui/StatusQ/src/StatusQ/Controls/StatusButton.qml
- only for `StatusButton` as for the `StatusFlatButton` it's not desired
- add support for showing the new variant to SB
- also use defined metrics for padding/spacing
- add a QML test
Fixes #17124
StatusButton
Light:
Dark:
=> feat(StatusButton): add an "outline" variant

ui/app/AppLayouts/Onboarding2/controls/OnboardingInfoButton.qml, ui/app/AppLayouts/Onboarding2/controls/qmldir, ui/app/AppLayouts/Onboarding2/pages/CreatePasswordPage.qml, ui/app/AppLayouts/Onboarding2/pages/HelpUsImproveStatusPage.qml
- create a reusable component
- fix the bg and hover colors as specified in Figma
Fixes #17102
Onboarding/Info button(s)
Normal:
Hover:
=> fix(Onboarding): fixup and extract info button to `OnboardingInfoButton`

storybook/pages/KeycardAddKeyPairPagePage.qml, storybook/pages/KeycardIntroPagePage.qml, storybook/pages/LoginScreenPage.qml, storybook/pages/OnboardingLayoutPage.qml, storybook/pages/SyncProgressPagePage.qml, ui/StatusQ/src/onboarding/enums.h, ui/StatusQ/src/typesregistration.cpp, ui/app/AppLayouts/Onboarding2/LoginBySyncingFlow.qml, ui/app/AppLayouts/Onboarding2/pages/HelpUsImproveStatusPage.qml, ui/app/AppLayouts/Onboarding2/pages/KeycardAddKeyPairPage.qml, ui/app/AppLayouts/Onboarding2/pages/SyncProgressPage.qml, ui/app/AppLayouts/Onboarding2/pages/WelcomePage.qml
- SyncProgressPagePage: enable the back button only in the failed state
- SyncProgressPagePage: fix the "Try again" and "Back" button to go to the Scan QR step; the connection code is disposable and can't be used again anyway
- adjust the respective SB pages to reflect the correct enum values
- seperate small commit to simplify the code and use the new `isOutline` variants of `StatusButton`
Fixes #17108
Onboarding/progress pages
https://github.com/user-attachments/assets/20e5424e-eb15-434a-a2f3-6c8efab96b4e
=> fix(Onboarding/SyncProgressPagePage): fixup back buttons 

src/app/modules/main/wallet_section/send_new/module.nim, src/app/modules/main/wallet_section/send_new/path_model.nim, src/app/modules/main/wallet_section/send_new/view.nim, ui/app/mainui/SendModalHandler.qml, ui/imports/utils/Constants.qml
Updated Sign Send popup (that is going to be a review popup soon) to operate over a single tx path instead like it's now. It needs to display a path-specific time, fees, later priority fees ranges, nonce and so.
These changes are necessary to ensure the correctness of the displayed data, align with step-by-step tx review while sending/bridging and prepare the code for introducing custom tx settings.
=> chore(wallet): new send modal improvements

storybook/pages/KeycardEnterPinPagePage.qml, storybook/pages/KeycardEnterPukPagePage.qml, storybook/pages/KeycardIntroPagePage.qml, storybook/pages/LoginScreenPage.qml, storybook/pages/OnboardingLayoutPage.qml, storybook/pages/UnblockWithPukFlowPage.qml, storybook/qmlTests/tests/tst_OnboardingLayout.qml, storybook/src/Storybook/BiometricsPopup.qml, ui/StatusQ/src/StatusQ/Popups/StatusSimpleTextPopup.qml, ui/StatusQ/src/onboarding/enums.h, ui/app/AppLayouts/Onboarding2/KeycardCreateProfileFlow.qml, ui/app/AppLayouts/Onboarding2/LoginWithKeycardFlow.qml, ui/app/AppLayouts/Onboarding2/OnboardingFlow.qml, ui/app/AppLayouts/Onboarding2/OnboardingLayout.qml, ui/app/AppLayouts/Onboarding2/OnboardingStackView.qml, ui/app/AppLayouts/Onboarding2/UnblockWithPukFlow.qml, ui/app/AppLayouts/Onboarding2/UseRecoveryPhraseFlow.qml, ui/app/AppLayouts/Onboarding2/components/LoginKeycardBox.qml, ui/app/AppLayouts/Onboarding2/controls/MaybeOutlineButton.qml, ui/app/AppLayouts/Onboarding2/pages/KeycardEnterPinPage.qml, ui/app/AppLayouts/Onboarding2/pages/KeycardEnterPukPage.qml, ui/app/AppLayouts/Onboarding2/pages/KeycardIntroPage.qml, ui/app/AppLayouts/Onboarding2/pages/LoginScreen.qml, ui/app/AppLayouts/Onboarding2/pages/qmldir, ui/app/AppLayouts/Onboarding2/qmldir, ui/app/AppLayouts/Onboarding2/stores/OnboardingStore.qml
- integrate the PUK unblock flow into the Onboarding and Login screen
- added a dedicated SB page for it
- remove the `Locked` keycard state everywhere in favor of `BlockedPIN` and `BlockedPUK`
- fix the various "(B)locked" buttons, based on the context and the state of the keycard
Fixes: https://github.com/status-im/status-desktop/issues/17092
Fixes: #17109
Iterates: #17098
Onboarding
Unblocking with PUK from both Onboarding and Login screens:
https://github.com/user-attachments/assets/0cfb1aaf-ee79-4abc-81f6-266b0862f6c3
=> feat(Onboarding): implement the new `UnblockWithPukFlow` 

ui/imports/shared/popups/keycard/states/CreatePassword.qml, ui/imports/shared/stores/RootStore.qml
- the view was missing the import for `Theme`
- the `getPasswordStrengthScore` was not being called with the correct signature (like in every other store)
Fixes #17050
Settings/Keycard
=> fix(PasswordView): unbreak strength score and padding/margins

storybook/pages/LoginScreenPage.qml, storybook/pages/OnboardingLayoutPage.qml, storybook/qmlTests/tests/tst_OnboardingLayout.qml, ui/app/AppLayouts/Onboarding2/OnboardingFlow.qml, ui/app/AppLayouts/Onboarding2/OnboardingLayout.qml, ui/app/AppLayouts/Onboarding2/pages/LoginScreen.qml, ui/imports/utils/Utils.qml
- `LoginScreen` and related SB page simplified
- OnboardingLayoutPage - settings introduced for handier testing
- LoginScreen moved from OnboardingLayout to OnboardingFlow, making first flow's page bound to model content (instead of relying on check during initialization)
- UnblockWithPukFlow removed from OnboardingLayout (now it's used only in OnboardingFlow)
- Login error/success processing extracted from LoginScreen to OnboardingLayout
- small bug fixed in Utils::objectTypeName
Closes: #17160
`OnboardingLayout` and related components
=> Onboarding: LoginScreen location adjusted

ui/app/AppLayouts/Wallet/adaptors/TokenSelectorViewAdaptor.qml, ui/app/AppLayouts/Wallet/controls/TokenSelector.qml, ui/app/AppLayouts/Wallet/panels/SearchableAssetsPanel.qml, ui/app/AppLayouts/Wallet/panels/SendModalHeader.qml, ui/app/AppLayouts/Wallet/panels/TokenSelectorPanel.qml, ui/app/mainui/SendModalHandler.qml
fixes #17148
Implements the logic to show default token (ETH, DAI and SNT) with 0 balance in SendModal
SimpleSend
https://github.com/user-attachments/assets/7cd5b357-5887-4028-98ff-e2bed4c4f31a
=> feat(@desktop/wallet): Add option to not show Popular section in TokenSelectorViewAdaptor.qml

storybook/qmlTests/tests/tst_SendModalFooter.qml, storybook/qmlTests/tests/tst_SimpleSendModal.qml, storybook/qmlTests/tests/tst_SimpleTransactionsFees.qml, ui/app/AppLayouts/Wallet/controls/TokenSelector.qml, ui/app/AppLayouts/Wallet/panels/SendModalHeader.qml, ui/app/AppLayouts/Wallet/panels/SimpleTransactionsFees.qml, ui/app/AppLayouts/Wallet/popups/simpleSend/SimpleSendModal.qml, ui/app/AppLayouts/Wallet/views/SendModalFooter.qml
fixes #17123y
Writing Unit Tests for -
1. SimpleSendModal
2. SimpleTransactionFees
3. SendModalFooter
SimpleSendModal
=> feat(@desktop/wallet): Write Unit tests for SimpleSendModal, SimpleTransactionFees and SendModalFooter

ci/Dockerfile, ci/Jenkinsfile.linux, ci/Jenkinsfile.tests-nim
Without `python3-dev` and `build-essential` build of `pyzstd` fails with:
```
error: command 'x86_64-linux-gnu-gcc' failed: No such file or directory
```
=> fix(ci): add missing deps for building Python deps

storybook/pages/LoginScreenPage.qml, storybook/pages/OnboardingLayoutPage.qml, ui/app/AppLayouts/Onboarding2/KeycardFactoryResetFlow.qml, ui/app/AppLayouts/Onboarding2/LoginWithKeycardFlow.qml, ui/app/AppLayouts/Onboarding2/OnboardingFlow.qml, ui/app/AppLayouts/Onboarding2/OnboardingLayout.qml, ui/app/AppLayouts/Onboarding2/UnblockWithPukFlow.qml, ui/app/AppLayouts/Onboarding2/components/LoginKeycardBox.qml, ui/app/AppLayouts/Onboarding2/pages/KeycardEnterPinPage.qml, ui/app/AppLayouts/Onboarding2/pages/LoginScreen.qml, ui/app/AppLayouts/Onboarding2/qmldir, ui/app/AppLayouts/Onboarding2/stores/OnboardingStore.qml
- integrate it into the UI and StoryBook
- a new keycardState is introduced: `FactoryResetting` (matching the backend)
- a new store method introduced: `startKeycardFactoryReset()`
Fixes: #17094
Onboarding
https://github.com/user-attachments/assets/19fa9a76-2913-4d67-ae0b-bee1f6e25c43
=> feat(Onboarding): implement the KeycardFactoryReset flow

storybook/pages/ChangePasswordViewPage.qml, storybook/pages/PasswordViewPage.qml, ui/StatusQ/src/StatusQ/Controls/StatusPasswordStrengthIndicator.qml, ui/app/AppLayouts/Profile/popups/ConfirmChangePasswordModal.qml, ui/app/AppLayouts/Profile/views/ChangePasswordView.qml, ui/imports/shared/views/PasswordView.qml
- display validation messages closer to the input fields
- warn about pass too long, info for "passwords match"
- fix an actual bug when two too long passwords would be considered as "valid" by the UI
- various fixes and UX improvements for the respective SB pages
Iterates: #17101
To fully fix the above issue, we need a more complete Figma design, depicting the various error scenarios
Password input component(s) and panels
Matching correct passwords:
Min. length not met:
Max length exceeded:
=> fix(PasswordView): UI fixes and alignments with latest Figma

src/app/modules/main/activity_center/controller.nim, src/app/modules/main/activity_center/io_interface.nim, src/app/modules/main/activity_center/module.nim, src/app/modules/main/activity_center/view.nim, src/app/modules/main/module.nim, src/app/modules/onboarding/io_interface.nim, src/app/modules/onboarding/module.nim, src/app/modules/startup/controller.nim, src/app/modules/startup/internal/profile_fetching_announcement_state.nim, src/app_service/service/activity_center/dto/notification.nim, src/app_service/service/general/async_tasks.nim, src/app_service/service/general/service.nim, ui/app/mainui/activitycenter/popups/ActivityCenterPopup.qml, ui/app/mainui/activitycenter/stores/ActivityCenterStore.qml, ui/app/mainui/activitycenter/views/ActivityNotificationProfileFetching.qml
Fixes #17028
When an old user imports an account, we now fetch the backups in the background and show an AC notification.
When the fetch is successful, the AC notif switches to a success message.
If after a timeout we detect that we didn't fetch anything or just part, we show an error and the possibility to try again.
Based on top of https://github.com/status-im/status-desktop/pull/17058
Status-go PR: https://github.com/status-im/status-go/pull/6255
Onboarding and AC. In the status-go side, backup handling
[backup-fetching.webm](https://github.com/user-attachments/assets/e8efc850-9c44-4455-b4e0-6fe1c2a3ce0b)
@micieslak @caybro if I could …
=> feat(onboarding): add AC notif for importing old accounts

ci/Dockerfile, ci/Jenkinsfile.combined, ci/Jenkinsfile.linux, ci/Jenkinsfile.linux-nix, ci/Jenkinsfile.macos, ci/Jenkinsfile.windows, ci/cpp/Jenkinsfile.macos, ci/cpp/Jenkinsfile.windows
This PR fixes issues like :
```
11:16:59  + s3cmd --stats --acl-public --no-preserve --host=ams3.digitaloceanspaces.com 
'--host-bucket=%(bucket)s.ams3.digitaloceanspaces.com' put 
pkg/StatusIm-Desktop-250205-101034-e6dfac-pr17210-aarch64.dmg 
s3://status-im-desktop-prs/ 11:16:59  
/opt/homebrew/Cellar/s3cmd/2.4.0_1/libexec/lib/python3.13/site-packages/S3/S3Uri.py:122: 
SyntaxWarning: invalid escape sequence '\.'
11:16:59    m = re.match("(.*\.)?s3(?:\-[^\.]*)?(?:\.dualstack)?(?:\.[^\.]*)?\.amazonaws\.com(?:\.cn)?$",
11:16:59  /opt/homebrew/Cellar/s3cmd/2.4.0_1/libexec/lib/python3.13/site-packages/S3/S3Uri.py:170: 
SyntaxWarning: invalid escape sequence '\w'
11:16:59    _re = re.compile("^(\w+://)?(.*)", re.UNICODE)
11:16:59  /opt/homebrew/Cellar/s3cmd/2.4.0_1/libexec/lib/python3.13/site-p …
```
=> ci: use sc5cmd for uploads

storybook/pages/EnterSeedPhrasePage.qml, storybook/qmlTests/tests/tst_EnterSeedPhrase.qml, ui/StatusQ/src/StatusQ/Controls/StatusBaseInput.qml, ui/StatusQ/src/StatusQ/Controls/StatusInput.qml, ui/StatusQ/src/StatusQ/Controls/StatusSeedPhraseInput.qml, ui/app/AppLayouts/Onboarding2/components/SeedphraseVerifyInput.qml, ui/app/AppLayouts/Onboarding2/pages/BackupSeedphraseVerify.qml, ui/app/AppLayouts/Onboarding2/qmldir, ui/imports/shared/controls/Timer.qml, ui/imports/shared/panels/EnterSeedPhrase.qml
Fixes a couple of UX issues in the `EnterSeedPhrase` component (cf respective commits):
- focus last input field after paste
- fix backspace, delete or overwrite with selected text
- add regression QML tests
- improve the corresponding SB page
Separate commit to fix the Seed verification UX issue
Fixes #17105
Fixes #17219
Onboarding/Seedphrase
https://github.com/user-attachments/assets/a01b1cfb-5e20-4c7c-af76-d8fe2f1f3c42
=> fix(Onboarding): Seed Phrase Entry UX Issues

storybook/pages/KeychainMock.qml, storybook/pages/KeychainPage.qml, storybook/pages/LoginScreenPage.qml, storybook/pages/OnboardingLayoutPage.qml, storybook/qmlTests/tests/tst_OnboardingLayout.qml, storybook/src/Storybook/BiometricsPopup.qml, ui/StatusQ/include/StatusQ/keychain.h, ui/StatusQ/src/keychain.cpp, ui/StatusQ/src/keychain_osx.mm, ui/StatusQ/src/keychain_other.cpp, ui/app/AppLayouts/Onboarding2/OnboardingFlow.qml, ui/app/AppLayouts/Onboarding2/OnboardingLayout.qml, ui/app/AppLayouts/Onboarding2/pages/LoginScreen.qml, ui/app/AppLayouts/Onboarding2/stores/OnboardingStore.qml, ui/main.qml
- changes the `Keychain` to take `reason` as a function argument
- removes biometrics-related signals from `OnboardingStore`
- slightly simplifies SB's mock popup for biometrics (`BiometricsPopup`)
- introduces ability to dismiss biometrics request from the flows
- allows `LoginScreen` to call for credentials in generic way (can be used with `Keychain`, mock or any other potential implementation)
- changes behavior of `LoginScreen`:
-  pin is requested via biometrics only if keycard is in a proper state
- adds `Keychain` to `main.qml` and combines with `OnboardingLayout`
`LoginScreen`, `OnboardingFlow`, `OnboardingLayout`, `Keychain` and others
My PR is consistent with this document: [Status Desktop Architecture Guide](https://github.com/status-im/status-desktop/blob/master/CONTRIBUTING.md …
=> [Oboarding]: Biometrics integration for login screen

storybook/pages/KeycardAddKeyPairPagePage.qml, storybook/pages/KeycardEnterPinPagePage.qml, storybook/pages/KeycardIntroPagePage.qml, storybook/pages/OnboardingLayoutPage.qml, storybook/pages/UnblockWithPukFlowPage.qml, ui/app/AppLayouts/Onboarding2/KeycardCreateProfileFlow.qml, ui/app/AppLayouts/Onboarding2/KeycardCreateReplacementFlow.qml, ui/app/AppLayouts/Onboarding2/LoginWithKeycardFlow.qml, ui/app/AppLayouts/Onboarding2/OnboardingFlow.qml, ui/app/AppLayouts/Onboarding2/OnboardingLayout.qml, ui/app/AppLayouts/Onboarding2/UnblockWithPukFlow.qml, ui/app/AppLayouts/Onboarding2/pages/KeycardAddKeyPairPage.qml, ui/app/AppLayouts/Onboarding2/pages/KeycardEmptyPage.qml, ui/app/AppLayouts/Onboarding2/pages/KeycardEnterPinPage.qml, ui/app/AppLayouts/Onboarding2/pages/KeycardIntroPage.qml, ui/app/AppLayouts/Onboarding2/pages/KeycardNotEmptyPage.qml
- the manual "I've inserted a keycard" reload buttons are no longer needed; we can rely solely on the HW keycard state
- when doing a "Restart", also reset the internal mock/store states
Fixes #17234
Onboarding
Onboarding flow with no Reload button:
Login screen with no Reload button:
=> chore(Onboarding): Remove all "Reload keycard state" buttons

storybook/pages/KeycardEnterPinPagePage.qml, storybook/pages/KeycardExtractingKeysPagePage.qml, storybook/pages/OnboardingLayoutPage.qml, storybook/pages/ProgressSelector.qml, storybook/qmlTests/tests/tst_OnboardingLayout.qml, ui/app/AppLayouts/Onboarding2/LoginWithKeycardFlow.qml, ui/app/AppLayouts/Onboarding2/OnboardingFlow.qml, ui/app/AppLayouts/Onboarding2/pages/KeycardEnterPinPage.qml, ui/app/AppLayouts/Onboarding2/pages/KeycardExtractingKeysPage.qml, ui/app/AppLayouts/Onboarding2/pages/qmldir
- separates pin entering and presenting keys extraction progress by using separate pages
- simplifies `KeycardEnterPinPage`, removing states from top level component (https://github.com/Furkanzmc/QML-Coding-Guide?tab=readme-ov-file#st-1-dont-define-top-level-states)
- rework `KeycardEnterPinPage`'s SB page to cover whole API
- fixes StackView inspection in OnboardingFlow
- adds reusable `ProgressSelector` to Storybook
- OnboardingLayout test: introduces inspection if given store method was called
Closes: #17205
Onboarding
`KeycardExtractingKeysPage` needs further alignment to the design (missing design)
[Screencast from 07.02.2025 …
=> feat(Onboarding): KeycardExtractingKeysPage excluded from KeycardEnterPinPage

storybook/qmlTests/tests/tst_OnboardingLayout.qml, ui/app/AppLayouts/Onboarding2/KeycardCreateProfileFlow.qml, ui/app/AppLayouts/Onboarding2/KeycardCreateReplacementFlow.qml, ui/app/AppLayouts/Onboarding2/components/SeedphraseVerifyInput.qml, ui/app/AppLayouts/Onboarding2/pages/KeycardAddKeyPairPage.qml
- changes the order of the "Create profile on empty Keycard" flow to match Figma (seedphrase -> create pin -> add key pair)
- fixup tests to match the order
Fixes #17216
Onboarding -> Create Profile -> Empty Keycard -> Existing seedphrase
=> fix(Onboarding): Incorrect Navigation Flow for 'Use existing phrase' subflow

src/app_service/service/keycardV2/async_tasks.nim, src/app_service/service/keycardV2/service.nim
No need to pass it around, just create a single global variable.
=> chore: simplify keycard rpc counter

storybook/pages/KeycardAddKeyPairPagePage.qml, storybook/pages/OnboardingLayoutPage.qml, storybook/qmlTests/tests/tst_OnboardingLayout.qml, ui/app/AppLayouts/Onboarding2/KeycardCreateProfileFlow.qml, ui/app/AppLayouts/Onboarding2/KeycardCreateReplacementFlow.qml, ui/app/AppLayouts/Onboarding2/OnboardingFlow.qml, ui/app/AppLayouts/Onboarding2/pages/KeycardAddKeyPairDelayedPage.qml, ui/app/AppLayouts/Onboarding2/pages/KeycardAddKeyPairPage.qml, ui/app/AppLayouts/Onboarding2/pages/KeycardEnterPinPage.qml, ui/app/AppLayouts/Onboarding2/pages/KeycardExtractingKeysPage.qml, ui/app/AppLayouts/Onboarding2/pages/qmldir, ui/app/AppLayouts/Onboarding2/stores/OnboardingStore.qml
- Adjusts `KeycardAddKeyPairPage` to have 2 states with minimal times of displaying them to the user
- restores mnemonic auto-fill button in OnboardingLayout's SB pge
- adds post-review amendments mistakenly skipped in https://github.com/status-im/status-desktop/issues/17205
Closes: #17233
Onboarding
[Screencast from 10.02.2025 21:11:51.webm](https://github.com/user-attachments/assets/5a4c9c6b-c4a8-42b0-9d07-6c39b278615b)
[Screencast from 10.02.2025 21:10:29.webm](https://github.com/user-attachments/assets/7af060c2-aadc-4bd3-a72b-23a410d2d6de)
[Screencast from 10.02.2025 21:12:33.webm](https://github.com/user-attachments/assets/c2ec613d-ae37-4 …
=> Onboarding: Adding new keypair page adjusted

src/app/boot/app_controller.nim, src/app_service/service/keycard/service.nim, src/app_service/service/keycardV2/service.nim, src/nim_status_client.nim
Requires:
- https://github.com/keycard-tech/status-keycard-go/pull/19
- https://github.com/keycard-tech/status-keycard-go/pull/19
Iterates:
- https://github.com/status-im/status-desktop/issues/17238
- https://github.com/status-im/status-desktop/issues/17168 (will open a PR with fix after this one)
Closes:
- https://github.com/status-im/status-desktop/issues/17226
Switches back to the old `KeycardService` and Flow API of `status-keycard-go` after login.
=> fix: reset keycard api after login

storybook/pages/KeycardCreatePinPagePage.qml, storybook/pages/UnblockWithPukFlowPage.qml, storybook/qmlTests/tests/tst_OnboardingLayout.qml, ui/app/AppLayouts/Onboarding2/KeycardCreateProfileFlow.qml, ui/app/AppLayouts/Onboarding2/KeycardCreateReplacementFlow.qml, ui/app/AppLayouts/Onboarding2/OnboardingFlow.qml, ui/app/AppLayouts/Onboarding2/OnboardingLayout.qml, ui/app/AppLayouts/Onboarding2/UnblockWithPukFlow.qml, ui/app/AppLayouts/Onboarding2/UnblockWithSeedphraseFlow.qml, ui/app/AppLayouts/Onboarding2/UseRecoveryPhraseFlow.qml, ui/app/AppLayouts/Onboarding2/pages/KeycardAddKeyPairDelayedPage.qml, ui/app/AppLayouts/Onboarding2/pages/KeycardCreatePinDelayedPage.qml, ui/app/AppLayouts/Onboarding2/pages/KeycardCreatePinPage.qml, ui/app/AppLayouts/Onboarding2/pages/SeedphrasePage.qml, ui/app/AppLayouts/Onboarding2/pages/qmldir
- Restores the initial design of the onboarding, removing hacks used for fast initial integration (at least in the touched area)
- `KeycardCreatePinPage` and `SeedphrasePage` components made not aware of any logic in the upper layer, making the flows more structured and easier to follow.
- fixes the unlock with seedphrase flow (page was not loading because required property not set)
Required for: #17232
`Onboarding`
=> Onboarding: `KeycardCreatePinPage` and `SeedphrasePage` refactored to be pure UI components

src/app/boot/app_controller.nim, src/app/modules/onboarding/module.nim, storybook/pages/LoginScreenPage.qml, storybook/pages/OnboardingLayoutPage.qml, storybook/pages/ProgressSelector.qml, storybook/qmlTests/tests/tst_OnboardingLayout.qml, ui/StatusQ/include/StatusQ/keychain.h, ui/StatusQ/include/StatusQ/modelutilsinternal.h, ui/StatusQ/src/keychain_other.cpp, ui/StatusQ/src/modelutilsinternal.cpp, ui/app/AppLayouts/Onboarding2/OnboardingFlow.qml, ui/app/AppLayouts/Onboarding2/OnboardingLayout.qml, ui/app/AppLayouts/Onboarding2/components/LoginKeycardBox.qml, ui/app/AppLayouts/Onboarding2/components/LoginPasswordBox.qml, ui/app/AppLayouts/Onboarding2/controls/LoginUserSelector.qml, ui/app/AppLayouts/Onboarding2/pages/LoginScreen.qml
- remove `tryToSetPinFunction` and correct `setPin` functions; those were not used in LoginScreen
- consistently report login errors to the LoginScreen, including details for the keycard profiles
- display error details in a popup (extracted from `LoginKeycardBox` to `LoginScreen`) for both password and keycard profiles
- add login error simulation buttons to SB pages
Fixes #17258
Separate commit to fix an issue with empty entries in `LoginUserSelector` and extend the QML tests
Fixes #17271
Onboarding/LoginScreen
https://github.com/user-attachments/assets/7e57bef0-a030-4d51-8d84-47095853d600
=> fix(Onboarding): Better handling of login errors

src/app/boot/app_controller.nim, src/app/modules/onboarding/io_interface.nim, src/app/modules/onboarding/module.nim, src/app/modules/onboarding/post_onboarding/keycard_replacement_task.nim, src/app/modules/onboarding/post_onboarding/task.nim
Iterates:
-  https://github.com/status-im/status-desktop/issues/17238
1. Added a concept of post-onboarding task. These can be added during `onboarding` and will be executed after login.
For now it's only 1 task, but I have defined 2 more that we will need to migrate from old `startup` as well.
2. Added `doKeycardReplacement` to the new onboarding
=> feat:  post-onboarding keycard replacement task

storybook/pages/LoginScreenPage.qml, storybook/qmlTests/tests/tst_OnboardingLayout.qml, ui/app/AppLayouts/Onboarding2/OnboardingFlow.qml, ui/app/AppLayouts/Onboarding2/OnboardingLayout.qml, ui/app/AppLayouts/Onboarding2/pages/LoginScreen.qml
Required for https://github.com/status-im/status-desktop/pull/17273
When going to `Lost keycard` flow, we need to collect the selected profile `KeyUID`. This is further needed for:
1. To call backend with proper `KeyUID` (done in https://github.com/status-im/status-desktop/pull/17273)
2. Enable to check is seed phrase matches the profile and show [this screen](https://www.figma.com/design/Lw4nPYQcZOPOwTgETiiIYo/Desktop-Onboarding-Redesign?node-id=999-46476&m=dev)
=> feat: collect `KeyUID` during `LoginWithLostKeycardSeedphrase`

storybook/pages/StatusButtonPage.qml, storybook/qmlTests/tests/tst_SwapModal.qml, ui/StatusQ/src/StatusQ/Controls/StatusBaseButton.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapModal.qml
Closes #17199 
Show the exchange rate approximation in swap. The exchange rate shows when the swap input is valid. It has 3 states:
1. invisibile - when the pay/receive input is empty
2. visible and loading - while fetching the routes. Happens whenever the swap input changes AND the input is valid
3. visible, with data - once the routes have been fetched
Swap
https://github.com/user-attachments/assets/310e6614-df7e-47fe-a33a-5130681e37ce
https://www.notion.so/b68de7395a0245909ad3b8755c460015?v=9d95d86c162944b68c8d55c7499f1140&p=1928f96fb65c80348476d907c236d704&pm=s
=> feat(Swap): display the exchange rate approximation in swap

ui/app/AppLayouts/Profile/views/MyProfileView.qml
fixes: #17195 by displaying real display name rather than alias fallback.
Profile settings.
https://github.com/user-attachments/assets/37e567ea-bbc3-414a-86d3-6c54ea888bf6
=> fix(settings): don't fallback to alias if display name is empty

storybook/pages/BackupSeedphraseFlowPage.qml, storybook/pages/KeycardEnterPinPagePage.qml, storybook/pages/KeycardEnterPukPagePage.qml, storybook/pages/LoginScreenPage.qml, storybook/pages/OnboardingLayoutPage.qml, storybook/pages/UnblockWithPukFlowPage.qml, storybook/qmlTests/tests/tst_OnboardingLayout.qml, ui/app/AppLayouts/Onboarding2/KeycardCreateProfileFlow.qml, ui/app/AppLayouts/Onboarding2/KeycardCreateReplacementFlow.qml, ui/app/AppLayouts/Onboarding2/OnboardingLayout.qml, ui/app/AppLayouts/Onboarding2/components/LoginKeycardBox.qml, ui/app/AppLayouts/Onboarding2/pages/KeycardCreatePinPage.qml, ui/imports/utils/Constants.qml
For the PIN pages:
- add a `pinSettingInProgress` bool hint to `KeycardCreatePinPage` when setting/authorizing the PIN is in progress to be able to correctly display the Back button
- don't display the "success" image yet when in progress
- use the hint in related flows
For the backup seed phrase sequence:
- the mnemonic is a string and gets submitted when exiting the BackupSeedphraseReveal, not right after its (re)creation
- when starting the flow (going from `KeycardCreatePinDelayedPage`), replace instead of push, so that Back skips the PIN page
- fixup the related SB pages
Fixes https://github.com/status-im/status-desktop/issues/17218
Onboarding/Create profile on empty Keycard …
=> fix(onboarding): Incorrect Back Navigation and Button Visibility on PIN Screens

storybook/pages/KeycardEnterPinPagePage.qml, ui/app/AppLayouts/Onboarding2/LoginWithKeycardFlow.qml, ui/app/AppLayouts/Onboarding2/OnboardingFlow.qml, ui/app/AppLayouts/Onboarding2/pages/KeycardEnterPinPage.qml
- removes unused internal components from `KeycardEnterPinPage`
- removes dependency on `authorizationState`, exposes `state` property taking own self-defined enum
- mapping authorization failed state to wrong pin state until #17289 is solved
`KeycardEnterPinPage`
=> Onboarding: `KeycardEnterPinPage` cleanup

ui/app/AppLayouts/Wallet/WalletLayout.qml
Closes #17321
Show SignPhraseModal only when the appMain is visible
https://github.com/user-attachments/assets/dd817ce8-e374-4847-935c-c898a8802bf7
=> fix: Show SignPhraseModal only when the appMain is visible

src/app/modules/onboarding/controller.nim, src/app/modules/onboarding/io_interface.nim, src/app/modules/onboarding/module.nim, src/app/modules/onboarding/states.nim, src/app/modules/onboarding/view.nim, src/app_service/service/keycardV2/service.nim, storybook/pages/OnboardingLayoutPage.qml, storybook/qmlTests/tests/tst_OnboardingLayout.qml, ui/StatusQ/src/onboarding/enums.h, ui/app/AppLayouts/Onboarding2/LoginWithKeycardFlow.qml, ui/app/AppLayouts/Onboarding2/OnboardingFlow.qml, ui/app/AppLayouts/Onboarding2/UnblockWithPukFlow.qml, ui/app/AppLayouts/Onboarding2/UnblockWithSeedphraseFlow.qml, ui/app/AppLayouts/Onboarding2/stores/OnboardingStore.qml
Closes #17289
Requires:
- https://github.com/keycard-tech/status-keycard-go/pull/21
1. Added separate `AuthorizationState`:
https://github.com/status-im/status-desktop/blob/f25e2540520ef3117279c4f0bd68998f6be0f2c7/ui/StatusQ/src/onboarding/enums.h#L85-L91
2. Update `status-keycard-go` to include https://github.com/keycard-tech/status-keycard-go/pull/21
3. 
Onboarding, Login
Login:
https://github.com/user-attachments/assets/a861feef-289c-42bb-9796-81b6520614f5
Login with keycard:
https://github.com/user-attachments/assets/6a14130c-699f-4115-bc89-ca59839dedaa
=> feat: `AuthorizationState`

ui/app/AppLayouts/Wallet/popups/simpleSend/SimpleSendModal.qml, ui/app/mainui/SendModalHandler.qml
This PR fixes below issues-
1. Sending 0 eth or any ERC20 is now working
2. Sending after rejecting review send is now enabled 
Simple Send
=> fix/17291: Fix sending 0 eth & review send after reject enabled

storybook/pages/OnboardingLayoutPage.qml, storybook/pages/UnblockWithPukFlowPage.qml, storybook/qmlTests/tests/tst_OnboardingLayout.qml, ui/StatusQ/src/StatusQ/Core/Utils/RecursiveStackView.qml, ui/StatusQ/src/StatusQ/Core/Utils/qmldir, ui/StatusQ/src/statusq.qrc, ui/app/AppLayouts/Onboarding2/CreateNewProfileFlow.qml, ui/app/AppLayouts/Onboarding2/KeycardCreateProfileFlow.qml, ui/app/AppLayouts/Onboarding2/KeycardCreateReplacementFlow.qml, ui/app/AppLayouts/Onboarding2/KeycardFactoryResetFlow.qml, ui/app/AppLayouts/Onboarding2/LoginBySyncingFlow.qml, ui/app/AppLayouts/Onboarding2/LoginWithKeycardFlow.qml, ui/app/AppLayouts/Onboarding2/OnboardingFlow.qml, ui/app/AppLayouts/Onboarding2/OnboardingLayout.qml, ui/app/AppLayouts/Onboarding2/OnboardingStackView.qml, ui/app/AppLayouts/Onboarding2/UnblockWithPukFlow.qml, ui/app/AppLayouts/Onboarding2/UnblockWithSeedphraseFlow.qml, ui/app/AppLayouts/Onboarding2/UseRecoveryPhraseFlow.qml
- introduces utility component to StatusQ - `RecursiveStackView` for easy nesting multiple `StackView`s
- alters the structure of onboarding from single shared `StackView` to multiple `StackView`s, one per flow. This approach simplifies the flow management because every flow handles freely it's own stack.
- consistent handling of single pages and flows by pushing/replacing/popping on the stack
- no need for custom `init` function to start the flow
- flows instantiated on demand and disposed whenever not needed
- flows are self-contained, no need to provide external stack view to run on
- handier inspection into the flow in Storybook (both pages and flows are listed)
Closes: #17304
`Onboarding` …
=> Onboarding: Flows based on own StackView

src/app/modules/main/wallet_section/accounts/item.nim, src/app/modules/main/wallet_section/accounts/model.nim, src/app/modules/shared/wallet_utils.nim, src/app/modules/shared_models/wallet_account_item.nim, ui/app/AppLayouts/Wallet/popups/ReceiveModal.qml, ui/app/AppLayouts/Wallet/views/LeftTabView.qml
Closes #17301
Adding the `MixedcaseAddress` role to accounts model. This role can be used when sharing the address.
Receive model (QR code, display address, and copy address )
Walet account context menu -> the copy action use the mixcase address
=> fix: Use mixcase address when sharing the address

ui/app/mainui/AppMain.qml
Fixes https://github.com/status-im/status-desktop/issues/17346
We were using the old stores for getting the areTestNetworksEnabled property
=> fix: restore missing testnet mode banner, community settings disable

src/app/modules/onboarding/controller.nim, src/app/modules/onboarding/io_interface.nim, src/app/modules/onboarding/module.nim, src/app/modules/onboarding/view.nim, storybook/pages/OnboardingLayoutPage.qml, storybook/qmlTests/tests/tst_OnboardingLayout.qml, ui/app/AppLayouts/Onboarding2/OnboardingFlow.qml, ui/app/AppLayouts/Onboarding2/OnboardingLayout.qml, ui/app/AppLayouts/Onboarding2/UseRecoveryPhraseFlow.qml, ui/app/AppLayouts/Onboarding2/pages/SeedphrasePage.qml, ui/app/AppLayouts/Onboarding2/stores/OnboardingStore.qml
- adds a new NIM method `isMnemonicDuplicate` which checks for duplicate mnemonics
- use it in the "seedphrase recovery flows"
- in case of a duplicate seedphrase, present the user with a more suitable error message (other than a plan "Invalid seedphrase")
- fixes re-importing the same seed leading to an infinite splash screen loop due to an "account already exists" error
Fixes #17248
Onboarding/seed flows
Storybook:
Wrong seed:
Duplicate seed:
=> fix(Onboarding): prevent importing the same seedphrase twice

src/app/modules/onboarding/module.nim, src/app/modules/onboarding/view.nim, storybook/pages/OnboardingLayoutPage.qml, ui/StatusQ/src/onboarding/enums.h, ui/app/AppLayouts/Onboarding2/pages/SyncProgressPage.qml
Fixes https://github.com/status-im/status-desktop/issues/17283
`ProgressState` was used instead of the `LocalPairingState`. Fixed that.
https://github.com/user-attachments/assets/00928a3d-1c62-46fc-b717-3146f9d9e2ac
=> fix: use proper LocalPairingState

src/app/boot/app_controller.nim, src/app/modules/onboarding/controller.nim, src/app/modules/onboarding/module.nim, src/app_service/service/keycardV2/async_tasks.nim, src/app_service/service/keycardV2/dto.nim, src/app_service/service/keycardV2/queued_async_calls.nim, src/app_service/service/keycardV2/rpc.nim, src/app_service/service/keycardV2/service.nim, src/app_service/service/keycardV2/utils.nim, src/app_service/service/wallet_account/service_account.nim
Changes done in this PR:
- Due to inability (because of the hardware limitations/speed) to call one keycard flow immediately after another a queued mechanism of calls is added
- All functions from the keycard service that do the async keycard calls follow the pattern "asyncFunctionName"
- New functions added to keycard service:
- getMetadata
- asyncStoreMetadata
- Keycard's metadata updated and synced with the app state
- The app updated appropriately that keycard accounts are marked with the keycard icon and keycard is now visible in the settings' keycards section
- By default if there is no name for the profile key pair "Status Keycard" is used for the keycard name
Closes: https://github.com/status-im/status-desktop/issues/17128 …
=> fix(onboarding/keycard): keycard being used through the onboarding flows is recognized in the app and synced with the app state

src/app/modules/onboarding/module.nim, storybook/pages/LoginScreenPage.qml, storybook/pages/OnboardingLayoutPage.qml, ui/app/AppLayouts/Onboarding2/OnboardingFlow.qml, ui/app/AppLayouts/Onboarding2/OnboardingLayout.qml, ui/main.qml
- don't clear the stack, we might need it to show errors during login (while displaying splash screen)
- use the `backAvailableHint` instead on the splash screen itself to hide the back button
- when a login error happens, unwind (or recreate) the stack to show the LoginScreen page again, together with the error message
- add a simulation of these 2 scenarios to StoryBook, together with showing the splash screen after a login
Fixes https://github.com/status-im/status-desktop/issues/17352
Onboarding/Splash screen
https://github.com/user-attachments/assets/c78882e2-adda-465c-9579-d4720d4d9c6e
=> fix(Onboarding): Back button appears on loading screen

src/app_service/service/keycardV2/service.nim, src/constants.nim
Fixes https://github.com/status-im/status-desktop/issues/17364
Requires https://github.com/status-im/status-desktop/pull/17355
Based on top of https://github.com/status-im/status-desktop/pull/17337
1. Update dependency to get https://github.com/keycard-tech/status-keycard-go/pull/22
2. Only write keycard logs in development builds. 
3. Write keycard logs to `Status/data/keycard/keycardl.log` file, instead of console (because the format doesn't match and logs are not synced)
Onboarding, Logs
1. Run development build, ensure:
- no keycard logs in console
- `Status/data/keycard/keycardl.log` file,
2. Run production build, ensure:
- no keycard logs in both console and files
Tick **one**:
=> feat: keycard log to file and only in development

ui/app/AppLayouts/Onboarding2/OnboardingFlow.qml
... when creating a new keycard profile from login screen
- reject requests for the biometrics prompt when not looking at the LoginScreen
Fixes #17370
Onboarding
https://github.com/user-attachments/assets/a017ea76-4710-4636-978e-83868d54f1de
=> fix(Onboarding): unexpected biometrics popup

ui/app/AppLayouts/Communities/views/CommunityColumnView.qml
- fix height calculation for an inactive Loader
Fixes #17365
CommunityColumnView
https://github.com/user-attachments/assets/572915b2-d50f-45b7-a479-e86845611acb
=> fix(CommunityColumnView): 'Add Channels' buttons overlap 'Add members'

storybook/pages/StatusImageCropPanelPage.qml, ui/StatusQ/sandbox/pages/StatusImageCropPanelPage.qml, ui/StatusQ/src/StatusQ/Components/StatusCard.qml, ui/StatusQ/src/StatusQ/Components/StatusChatInfoToolBar.qml, ui/StatusQ/src/StatusQ/Components/StatusColorSpace.qml, ui/StatusQ/src/StatusQ/Components/StatusListItem.qml, ui/StatusQ/src/StatusQ/Components/StatusListPicker.qml, ui/StatusQ/src/StatusQ/Components/StatusQrCodeScanner.qml, ui/StatusQ/src/StatusQ/Components/StatusRoundedComponent.qml, ui/StatusQ/src/StatusQ/Components/StatusTagSelector.qml, ui/StatusQ/src/StatusQ/Components/StatusToastMessage.qml, ui/StatusQ/src/StatusQ/Components/private/statusMessage/StatusImageMessage.qml, ui/StatusQ/src/StatusQ/Components/private/statusMessage/StatusMessageQuickActions.qml, ui/StatusQ/src/StatusQ/Components/private/statusMessage/StatusPinMessageDetails.qml, ui/StatusQ/src/StatusQ/Components/private/statusMessage/StatusTextMessage.qml, ui/StatusQ/src/StatusQ/Controls/StatusImageCrop.qml, ui/StatusQ/src/StatusQ/Controls/StatusSelect.qml, ui/StatusQ/src/StatusQ/Controls/StatusSlider.qml, ui/StatusQ/src/StatusQ/Platform/StatusMacNotification.qml, ui/StatusQ/src/typesregistration.cpp, ui/app/AppLayouts/Communities/controls/BannerPicker.qml, ui/app/AppLayouts/Communities/controls/LogoPicker.qml, ui/app/AppLayouts/Communities/panels/ControlNodeOfflineCenterPanel.qml, ui/app/AppLayouts/Communities/panels/JoinCommunityCenterPanel.qml, ui/app/AppLayouts/Communities/panels/JoinCommunityHeaderPanel.qml, ui/app/AppLayouts/Communities/panels/PrivilegedTokenArtworkPanel.qml, ui/app/AppLayouts/Communities/panels/TokenInfoPanel.qml, ui/app/AppLayouts/Wallet/controls/AccountHeaderGradient.qml, ui/app/mainui/activitycenter/controls/CommunityBadge.qml, ui/imports/shared/panels/SeedPhrase.qml
- Creates import alias for Qt 6 by
- registering dummy `QtGraphicalEffects 1.15`
- registering module import `Qt5Compat.GraphicalEffects` for the dummy module to load the actual module
- Replaces all occurences of `import QtGraphicalEffects 1.* ` to
```
import QtGraphicalEffects 1.15
```
Closes: #17388
Script used for replacement:
```bash
#!/bin/bash
directory=$1
count=0
while IFS= read -r -d '' file; do
occurrences=$(grep -E 'import QtGraphicalEffects 1\..*' "$file" | grep -v 'import QtGraphicalEffects 1.15' | wc -l)
if [ "$occurrences" -gt 0 ]; then
sed -i -E 's/import QtGraphicalEffects 1\..*/import QtGraphicalEffects 1.15/' "$file"
count=$((count + occurrences))
fi
done < <(find "$directory" -type f -name "*.qml" -print0)
echo "Replaced $count occurrences."
```
The whole qml codebase …
=> Qt 5->6: Adjust `GraphicalEffects` imports to work on both qt 5/6

src/app/boot/app_controller.nim, src/app/modules/onboarding/controller.nim, src/app/modules/onboarding/io_interface.nim, src/app/modules/onboarding/module.nim, src/app/modules/onboarding/post_onboarding/keycard_convert_account.nim, src/app/modules/onboarding/post_onboarding/keycard_replacement_task.nim, src/app/modules/onboarding/post_onboarding/save_biometrics_task.nim, src/app/modules/onboarding/post_onboarding/task.nim, src/app/modules/onboarding/states.nim, src/app/modules/onboarding/view.nim, storybook/pages/ConvertKeycardAccountPagePage.qml, storybook/pages/OnboardingLayoutPage.qml, ui/StatusQ/src/keychain_osx.mm, ui/StatusQ/src/onboarding/enums.h, ui/app/AppLayouts/Onboarding2/OnboardingFlow.qml, ui/app/AppLayouts/Onboarding2/OnboardingLayout.qml, ui/app/AppLayouts/Onboarding2/pages/ConvertKeycardAccountPage.qml, ui/app/AppLayouts/Onboarding2/pages/qmldir, ui/app/AppLayouts/Onboarding2/stores/OnboardingStore.qml, ui/app/mainui/SplashScreen.qml, ui/main.qml
Fixes https://github.com/status-im/status-desktop/issues/17284
Nim-side:
1. Implemented `LoginWithLostKeycardSeedphrase`
2. Implemented `KeycardConvertAccountTask`
3. Added handling of keycard account conversion result 
4. Added handling of re-encryption signals
5. Introduce `moment` for post-onboarding tasks
To distinguish, should one be executed after login or when main module loaded.
6. Implemented login using mnemonic
7. Re-implement save biometrics as a post-onboarding task
QML:
1. Implemented `ConvertKeycardAccountPage` (with an according storybook page)
- This requires conversation with design team.
2. Added re-ecnryption splash screen
- This requires conversation with design team. I reused the standard `SplashScreen` for this. 
- I'm not sure if the way I used `StackView` is …
=> feat: lost keycard flow - convert keycard account to regular

src/app_service/service/keycardV2/service.nim
Copy https://github.com/status-im/status-desktop/pull/15194 hotfix to `KeycardServiceV2`
=> chore: Add sleep to prevent crash on Intel MacOS during init

src/app/modules/onboarding/module.nim
Fixes https://github.com/status-im/status-desktop/issues/17350
But I couldn't confirm that it works. I can see that the metrics are enabled:
```
2025-02-26T18:52:39.383Z	DEBUG	RequestLogger	call	{"method": "centralizedMetricsInfo", "duration": "77.875µs", "request": null, "response": {"enabled":true,"userConfirmed":true}}
```
But I don't see `Add metric flow` log in the logs, which should be done here:
https://github.com/status-im/status-desktop/blob/42a95304520b41b3333432f54e4b9b64903d07d6/src/app_service/service/metrics/async_tasks.nim#L21
But... maybe I'm doing something wrong 🤷
=> fix: send metrics event with proper login flow

ui/app/AppLayouts/Onboarding2/OnboardingLayout.qml, ui/main.qml
Fixes https://github.com/status-im/status-desktop/issues/17351
I wasn't able to fully reproduce the issue. I got an empty `viewId`, but only as the last navigation event, not in the middle of some flow.
Anyway, from code there seem to be only one possible reason for this. - when there's no page visible. Perhaps there's sometimes a quick glitch when switching pages.
Basically, I just added a condition to skip such events, when the page name is empty 😄
=> fix: only publish onboarding navigation event on non-null page

src/env_cli_vars.nim
Closes #17380
Don't try to load the commandLineParams if the app is built as lib or staticLib
=> fix: Don't load the command line arguments for lib or staticLib

ui/StatusQ/src/StatusQ/Controls/StatusFeeOption.qml, ui/app/AppLayouts/Wallet/views/TransactionSettings.qml
- use the correct icon size
- fix some forgotten `qsTr()`
- silence some warnings; a plain `return` returns `undefined` whereas a `bool` is expected
TransactionSettings
https://github.com/user-attachments/assets/ca3dc68d-b2b2-4b0b-9498-875508359014
=> fix(TransactionSettings): fix component height jumping around

storybook/pages/OnboardingLayoutPage.qml, storybook/qmlTests/tests/tst_OnboardingLayout.qml, ui/app/AppLayouts/Onboarding2/UseRecoveryPhraseFlow.qml, ui/app/AppLayouts/Onboarding2/pages/ConvertKeycardAccountAcksPage.qml, ui/app/AppLayouts/Onboarding2/pages/KeycardLostPage.qml, ui/app/AppLayouts/Onboarding2/pages/qmldir
- `Lost keycard -> Start using this profile without Keycard` has a new screen (`KeycardRecovery` type in `UseRecoveryPhraseFlow`)
- adjust the QML tests to take the extra page into account
- 2 small extra commits for a better simulation in SB
Fixes https://github.com/status-im/status-desktop/issues/17415
Onboarding/LoginScreen/LostKeycard
https://github.com/user-attachments/assets/f9f7758c-fa8c-4e49-a216-cebb83729ab3
=> feat(Onboarding): Implement re-enryption warning screen 

ui/StatusQ/src/keychain_osx.mm, ui/app/AppLayouts/Profile/views/ChangePasswordView.qml
Iterates #17450
1. Remove reference to undefined `errorDescription`, which blocks closing the popup
2. Add some logs for Keychain access operation failures
=> fix: undefined reference `errorDescription`

storybook/main.cpp, storybook/pages/StatusQrCodeScannerPage.qml, ui/StatusQ/sandbox/DemoApp.qml, ui/StatusQ/sandbox/QrCodeScannerPage.qml, ui/StatusQ/sandbox/sandboxapp.cpp, ui/StatusQ/sanity_checker/main.cpp, ui/StatusQ/src/StatusQ/Components/+qt6/StatusQrCodeCapture.qml, ui/StatusQ/src/StatusQ/Components/StatusQrCodeCapture.qml, ui/StatusQ/src/StatusQ/Components/StatusQrCodeScanner.qml, ui/StatusQ/src/StatusQ/Components/qmldir, ui/StatusQ/src/StatusQ/Core/StatusIcon.qml, ui/StatusQ/src/statusq.qrc, ui/app/AppLayouts/Onboarding2/pages/LoginScreen.qml, ui/imports/shared/controls/DecoratedListItem.qml, ui/imports/shared/controls/StatusSyncCodeScan.qml
- Excludes `StatusQrCodeCapture` which is responsible exclusively for qr codes detection from the video input, with no other UI elements. It's the only component related to qr codes depending directly on QZXing and
QtMultimedia. That depenency is removed StatusQrCodeScanner. It gives ability of providing alternative version on the StatusQrCodeCapture for qt 6 via file selector.
- Register file selector for qt6 in `Storybook` and `Sandbox` apps
- Add Qt6 variant of StatusQrCodeCapture. It makes `StatusQrCodeScanner` working on both qt 5 and 6
- Fixes url resolution in `StatusIcon` In Qt6 URLs are no longer automatically resolved on assignment, therefore it's necessary to resolve them explicitely where necessary. It doesn't change the behavior on Qt5.
- Solves some small inconsistencies to …
=> [Qt5->6]: Refactor `StatusQrCodeScanner` to work on both Qt 5/6, OnboardingLayout SB page working on Qt 6

ci/Jenkinsfile.linux, ci/Jenkinsfile.linux-nix, ci/Jenkinsfile.macos, ci/Jenkinsfile.windows, ci/cpp/Jenkinsfile.windows
- observed that nightly was timing out on linux job, bumped linux, linux-nix and windows timeout to 30 minutes.
- trim VERSION to prevent newline from sneaking in as observed in release/2.33.x branch.
status: ready
=> ci: increase timeout and trim VERSION

ui/imports/shared/popups/send/SendModal.qml, ui/imports/shared/popups/send/views/FeesView.qml, ui/imports/shared/popups/send/views/NetworkCardsComponent.qml, ui/imports/shared/popups/send/views/NetworkSelector.qml
I inspected this issue a lot, and it was very hard to reproduce. It could be that some dependencies are triggered now since I've added the `isLoading` property to trigger some recalculations. As you can see in the attached video, a bridge was successfully found for any input parameters I set.
Fixes: #17439
https://github.com/user-attachments/assets/9d5e825a-6fc8-49b2-b7cc-f2cd635ef74b
=> fix(wallet): bridge mainnet L1 to Base L2 - No route found

ui/StatusQ/src/systemutilsinternal.cpp, vendor/DOtherSide/lib/src/DOtherSide.cpp
Closes #17477 
Guarding QProcess so that it's used only when the Qt build supports this feature.
=> chore: Use QProcess only when Qt is configured to support the feature

src/app/core/tasks/threadpool.nim, src/app/global/feature_flags.nim, src/app/global/global_singleton.nim, src/app_service/service/keycard/service.nim, src/app_service/service/keycardV2/rpc.nim, src/app_service/service/keycardV2/service.nim, src/env_cli_vars.nim, src/nim_status_client.nim, storybook/pages/OnboardingLayoutPage.qml, storybook/pages/SettingsLeftTabViewPage.qml, ui/app/AppLayouts/Onboarding/OnboardingLayout.qml, ui/app/AppLayouts/Onboarding/views/KeysMainView.qml, ui/app/AppLayouts/Onboarding2/OnboardingFlow.qml, ui/app/AppLayouts/Onboarding2/OnboardingLayout.qml, ui/app/AppLayouts/Onboarding2/controls/ListItemButton.qml, ui/app/AppLayouts/Onboarding2/pages/CreateProfilePage.qml, ui/app/AppLayouts/Onboarding2/pages/LoginScreen.qml, ui/app/AppLayouts/Onboarding2/pages/NewAccountLoginPage.qml, ui/app/AppLayouts/Profile/ProfileLayout.qml, ui/app/AppLayouts/Profile/helpers/SettingsEntriesModel.qml, ui/app/AppLayouts/Profile/views/WalletView.qml, ui/app/AppLayouts/Profile/views/wallet/MainView.qml, ui/app/AppLayouts/Wallet/WalletLayout.qml, ui/app/AppLayouts/Wallet/views/LeftTabView.qml, ui/app/AppLayouts/stores/FeatureFlagsStore.qml, ui/app/mainui/AppMain.qml, ui/imports/shared/popups/addaccount/AddAccountPopup.qml, ui/imports/shared/popups/addaccount/states/SelectMasterKey.qml, ui/main.qml
Closes #17430 
Needs https://github.com/status-im/nimqml/pull/60
Adding a new compile time flag to disable the Keycard support on platforms where PCSC-lite is not available.
This should be a temporary solution, but in a state where it could be released.
Changes:
- Adding a new `featureFlag` macro to create public feature flags. This macro can read the feature flag at compile time or at run time, based on configuration.
Usage:
```
featureFlag("KEYCARD_ENABLED", DEFAULT_FLAG_KEYCARD_ENABLED, true)
```
- Adding a `featureGuard` macro to guard the code based on a feature flag. There are two main usages for this featureGuard: To guard a statement list (in this case it just drops the statement list), to guard a `proc` (in this case the proc just returns `discard`). I've kept the proc symbols …
=> 17430 platform abstraction guard keycard dependency with compilation flag

storybook/pages/SendSignModalPage.qml, storybook/pages/StatusFeeOptionPage.qml, storybook/pages/TransactionSettingsPanelPage.qml, storybook/qmlTests/tests/tst_SendSignModal.qml, ui/StatusQ/src/StatusQ/Controls/StatusFeeOption.qml, ui/app/AppLayouts/Wallet/WalletUtils.qml, ui/app/AppLayouts/Wallet/popups/SignTransactionModalBase.qml, ui/app/AppLayouts/Wallet/popups/simpleSend/SendSignModal.qml, ui/app/AppLayouts/Wallet/views/TransactionSettings.qml, ui/app/mainui/SendModalHandler.qml, ui/imports/utils/Constants.qml
fixes #17446 
Cherry-pick of https://github.com/status-im/status-desktop/pull/17331.
SimpleSend
https://github.com/user-attachments/assets/b0f693dd-d2e5-4c1b-b893-7478fd47304b
=> feat(@desktop/wallet): Adapt changes for estimated time and fee mode in the single network SendModal

src/app/modules/onboarding/module.nim, src/app/modules/onboarding/view.nim, src/app_service/service/keycardV2/dto.nim, storybook/pages/LoginScreenPage.qml, storybook/pages/OnboardingLayoutPage.qml, storybook/qmlTests/tests/tst_OnboardingLayout.qml, ui/StatusQ/src/onboarding/enums.h, ui/app/AppLayouts/Onboarding2/OnboardingFlow.qml, ui/app/AppLayouts/Onboarding2/OnboardingLayout.qml, ui/app/AppLayouts/Onboarding2/components/LoginKeycardBox.qml, ui/app/AppLayouts/Onboarding2/pages/KeycardIntroPage.qml, ui/app/AppLayouts/Onboarding2/pages/LoginScreen.qml, ui/app/AppLayouts/Onboarding2/stores/OnboardingStore.qml
- expose `keycardUID` from keycard info
- compare it with the `selectedProfileKeyId` to determine whether it's the matching (or wrong) keycard for the selected profile
- use native `ProgressState` types internally in onboarding/view.nim instead of a generic `int`
- removed unused "WrongKeycard" dto state
Fixes #17391
Onboarding/Login
=> fix(Onboarding/Login): missing state for incorrect keycard during login

src/app/modules/main/module.nim, src/app/modules/main/view.nim, ui/app/AppLayouts/stores/RootStore.qml, ui/app/mainui/AppMain.qml, ui/app/mainui/SendModalHandler.qml
Closes #17410 
Replace nim `browsers` module with QML API.
Motivation: The browsers module is using `c_system` calls to start the browser. This call has been deprecated on some platforms.
=> chore: Remove `browsers` module dependency and replace it with QT API

ui/app/AppLayouts/Wallet/popups/simpleSend/SimpleSendModal.qml, ui/app/mainui/SendModalHandler.qml
Closes #17472 
* Cache the selected asset so it is still showed even if another account doesn't have it
Send modal
=> fix: Remain pre-selected asset even if not owned

storybook/pages/OnboardingLayoutPage.qml, storybook/pages/UnblockWithPukFlowPage.qml, ui/app/AppLayouts/Onboarding2/KeycardCreateProfileFlow.qml, ui/app/AppLayouts/Onboarding2/KeycardCreateReplacementFlow.qml, ui/app/AppLayouts/Onboarding2/KeycardFactoryResetFlow.qml, ui/app/AppLayouts/Onboarding2/OnboardingFlow.qml, ui/app/AppLayouts/Onboarding2/OnboardingLayout.qml, ui/app/AppLayouts/Onboarding2/UnblockWithPukFlow.qml, ui/app/AppLayouts/Onboarding2/UnblockWithSeedphraseFlow.qml, ui/app/AppLayouts/Onboarding2/pages/KeycardCreatePinDelayedPage.qml
- when creating a keycard profile, we can't set the PIN twice w/o finishing the flow
- skip the PIN creation screen a second time when going back and forth
- correctly propagate and consistently use the delay interval to display the final success state to the user
Plus two smaller fixes for other flows
Fixes https://github.com/status-im/status-desktop/issues/17494
Onboarding/Create profile with empty keycard
https://github.com/user-attachments/assets/c3a9dae4-a595-4f56-91d1-62a2fa30d827
=> fix(Onboarding): skip PIN creation a second time

src/backend/accounts.nim, src/constants.nim, src/env_cli_vars.nim
Add parameters to `InitializeApplication` request for enabling prometheus and specifying port.
Corresponding status-go PR: https://github.com/status-im/status-go/pull/6256
This change is necessary to enable viewing metrics locally by running Prometheus/Grafana as specified here: https://github.com/waku-org/status-metrics
Application startup. Default behavior introduced by this change does not change anything.
(I glanced at the document but this is a relatively minor change that doesn't involve complex logic and only touches a small part of the application)
=> feat(metrics)_: update initializeapplication params with metrics flag and port

ui/app/AppLayouts/Wallet/popups/buy/BuyCryptoModal.qml, ui/app/AppLayouts/Wallet/popups/buy/BuyCryptoParamsForm.qml
Fixes https://github.com/status-im/status-desktop/issues/17466
The default token was set in `selectedTokenEntry`, while we expect to have the current value in `buyCryptoInputParamsForm.selectedTokenKey`. This PR fixes that
Wallet/Buy
=> fix(wallet): set default selected token in buy modal form

storybook/pages/IntroduceYourselfPopupPage.qml, test/e2e/gui/components/community/create_community_popups.py, test/e2e/gui/components/introduce_yourself_popup.py, test/e2e/gui/main_window.py, test/e2e/gui/objects_map/names.py, test/e2e/gui/screens/community_portal.py, ui/imports/shared/popups/IntroduceYourselfPopup.qml, ui/main.qml
- the problem was that the feature flag (`onboardingV2Enabled`) was incorrect due to a nasty side effect of mixing it with the check for `onboardingModule`
- this was true only inside main.qml; once propagated down to AppMain, where the popup resides, it became `false` because the `onboardingModule` gets unloaded
Fixes #17498
NEEDS_BACKPORT
Onboarding/main
=> fix(Post Onboarding): unbreak showing of `IntroduceYourselfPopup`

ui/app/AppLayouts/Wallet/popups/swap/SwapModal.qml
Fixes https://github.com/status-im/status-desktop/issues/17347 and https://github.com/status-im/status-desktop/issues/17471
`amount`, used in the `fromTokenAmount` calculation, is calculated using a bunch of properties that might be updated before or after `rawValue` changes. In unlucky conditions, `value` would be 0 even though the user had entered a valid amount, causing the value in `swapInputParamsForm` to not be properly updated.
This PR avoids using `amount` in that calculation, using `rawAmount` instead.
Swap
=> fix: solve race condition in swap payPanel

ui/app/AppLayouts/Profile/views/wallet/AccountView.qml, ui/app/AppLayouts/Wallet/views/RightTabView.qml
Related Figma:
- https://www.figma.com/design/idUoxN7OIW2Jpp3PMJ1Rl8/Settings-%7C-Desktop?node-id=18442-539034&m=dev
Closes #17394
=> fix(wallet): import missing keypair button is missing when recovering data from waku

ui/app/AppLayouts/Wallet/services/dapps/+noWebEngine/WalletConnectSDK.qml, ui/app/AppLayouts/Wallet/services/dapps/DappsConnectorSDK.qml
Adding a `noWebEngine` qml variant for `WalletConnectSDK`.
It can be configured by using the `QT_FILE_SELECTORS` env variable when needed.
E.g. qputenv("QT_FILE_SELECTORS", "noWebEngine");
=> chore: Allow targets without qt webengine to run the app

ui/app/AppLayouts/Profile/views/wallet/AccountView.qml, ui/app/AppLayouts/Wallet/views/RightTabView.qml
Cherry picked:
- https://github.com/status-im/status-desktop/pull/17549
=> [cherry-pick] fix(wallet): import missing keypair button is missing when recovering data from waku

ui/main.qml
- call the `mainModule.fakeLoadingScreenFinished()` when moving to AppMain
- avoids calling it in the splash screen progress handler, since it can get stuck, or completely skipped in dev envs
Fixes #17558
OS notifications
=> [cherry-pick] fix: unbreak OS notifications

ui/app/mainui/AppMain.qml
fixes #17530 
Corrects the chain name being set  when sending notifications
Swap, Send Notifications
https://github.com/user-attachments/assets/fdcb9472-5494-402e-ba10-d298276ea349
https://github.com/user-attachments/assets/0026a922-1fee-4dc6-bc30-2a398d87b16a
https://github.com/user-attachments/assets/03b5c021-8bc3-4304-a4b7-e95eeb112bd6
=> Swap and Send - notifications - Unknown displays on the notification instead of the corresponding chain explorer

src/app/core/signals/remote_signals/signal_type.nim, src/app/core/signals/signals_manager.nim, src/app/modules/main/wallet_section/all_tokens/controller.nim, src/app/modules/main/wallet_section/all_tokens/io_interface.nim, src/app/modules/main/wallet_section/all_tokens/module.nim, src/app/modules/main/wallet_section/all_tokens/view.nim, src/app_service/service/settings/dto/settings.nim, src/app_service/service/settings/service.nim, src/app_service/service/token/service.nim, src/backend/settings.nim, ui/app/AppLayouts/Profile/panels/SupportedTokenListsPanel.qml, ui/app/AppLayouts/Profile/views/wallet/ManageTokensView.qml, ui/app/AppLayouts/Wallet/stores/TokensStore.qml, ui/imports/utils/Constants.qml
Corresponding `statusgo` PRs:
- https://github.com/status-im/status-go/pull/6399
- https://github.com/status-im/status-go/pull/6398
Changes:
- added toggle for enabling disabling tokens auto-refresh
- tokens lists updated at regular intervals
By default, new lists are fetched every 30 minutes. Once new tokens are fetched, the token lists and available tokens in the app will be updated with any newly published tokens from those lists. The auto-refresh setting is being synced across paired devices.
Closes #17377
@benjthayer, please look at the screenshot here and let me know if the wording (and design) is acceptable or how to name the "Auto-refresh tokens lists" option? If this is ok, then we will just need to update the related Figma accordingly.
=> feat(wallet): auto-refresh tokens lists

ui/app/mainui/AppMain.qml
- extend the check for showing the Introduce yourself popup with the empty display name condition
Fixes #17596
AppMain/IntroduceYourselfPopup
=> fix(IntroduceYourselfPopup): only show when the display name is empty

storybook/pages/StatusMessageDialogPage.qml, ui/StatusQ/src/StatusQ/Popups/Dialog/StatusDialog.qml, ui/StatusQ/src/StatusQ/Popups/Dialog/StatusDialogBackground.qml, ui/StatusQ/src/StatusQ/Popups/Dialog/StatusDialogHeader.qml, ui/StatusQ/src/StatusQ/Popups/Dialog/StatusMessageDialog.qml, ui/StatusQ/src/StatusQ/Popups/Dialog/StatusTitleSubtitle.qml, ui/StatusQ/src/StatusQ/Popups/Dialog/qmldir, ui/StatusQ/src/statusq.qrc, ui/app/AppLayouts/Chat/views/ChatMessagesView.qml, ui/app/AppLayouts/Communities/popups/CreateCategoryPopup.qml, ui/app/AppLayouts/Communities/popups/CreateChannelPopup.qml, ui/app/AppLayouts/Communities/popups/CreateCommunityPopup.qml, ui/app/AppLayouts/Communities/views/CommunityColumnView.qml, ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml, ui/app/AppLayouts/Profile/popups/RenameAccontModal.qml
- (almost) a dropin replacement for the QtQuick.1 `MessageDialog`, preserving the same API
- based on `StatusDialog` to get the default look'n'feel
- works on both Qt5/Qt6 using native Status components
- some smaller fixes/alignments to the underlying StatusDialog
- add a dedicated StoryBook page
Fixes #17562
StatusMessageDialog
=> feat(StatusQ): create a standard `StatusMessageDialog` component

scripts/macos_build_setup.sh
This PR updates the build script to install QT directly with the homebrew formulae on MacOS.
We also move away from the python method because of : 
https://peps.python.org/pep-0668/
This mitigates a risk with newer python version that mandate installing global python packages under a virtual environment.
```
STDERR:
Warning: python@3.10 3.10.16 is already installed and up-to-date.
To reinstall 3.10.16, run:
brew reinstall python@3.10
error: externally-managed-environment
```
We can now pin QT version to 5.15.16_1 on MacOS with brew.
=> ci: install QT 5.15.16_1 on MacOS with homebrew formula

src/app/modules/onboarding/view.nim, storybook/pages/LoginScreenPage.qml, storybook/pages/OnboardingLayoutPage.qml, storybook/qmlTests/tests/tst_OnboardingLayout.qml, ui/app/AppLayouts/Onboarding2/controls/LoginUserSelector.qml, ui/app/AppLayouts/Onboarding2/pages/LoginScreen.qml
- set the current item in CTOR only iff the model is not empty
- and then again anytime the model contents/count changes
- remove the separator with just 1 model entry
Fixes #17597
Onboarding/Login
=> fix(LoginScreen): set account selector initial selection

test/e2e/gui/main_window.py, test/e2e/gui/objects_map/names.py, test/e2e/gui/screens/onboarding.py, test/e2e/tests/communities/test_communities_channels.py, test/e2e/tests/crtitical_tests_prs/test_settings_password_change_password.py, ui/main.qml
- Temp disable tests that are using custom user data, it has to be reworked first
- Change the splash screen reference to use SplashScreenV2 in tests
=> chore(@e2e): use new splash screen in tests

ui/app/mainui/AppMain.qml
Backport of PR https://github.com/status-im/status-desktop/pull/17604 to fix issue https://github.com/status-im/status-desktop/issues/17596
- extend the check for showing the Introduce yourself popup with the empty display name condition
Fixes #17596
AppMain/IntroduceYourselfPopup
=> [CHERRY-PICK] fix(IntroduceYourselfPopup): only show when the display name is empty

storybook/pages/StatusFolderDialogPage.qml, ui/StatusQ/src/StatusQ/Popups/Dialog/+qt6/StatusFolderDialog.qml, ui/StatusQ/src/StatusQ/Popups/Dialog/StatusFolderDialog.qml, ui/StatusQ/src/StatusQ/Popups/Dialog/qmldir, ui/StatusQ/src/statusq.qrc, ui/app/mainui/Popups.qml
Closes #17544
- It creates a basic `StatusFolderDialog` wrapper for both qt versions. In case of qt5 it uses `FileDialog` as a source, in case of qt6, it uses `FolderDialog`.
- It creates a `storybook` page to test the new component.
- It replaces existing `FileDialog` by new `StatusFolderDialog` component, compatible with qt5 and qt6.
Popups / downloadImageDialogComponent
**- qt5 version:**
https://github.com/user-attachments/assets/ff076092-fca1-4017-a326-ac44c39e3816
**- qt6 version:**
https://github.com/user-attachments/assets/cdd2ddd9-725c-4299-8b60-8d6702324f3b
No impact
- Go through the flow where you can right click a gif and download …
=> feat(qt5->6): Create a `StatusFolderDialog` wrapper component for both qt5 and qt6 versions and refactor the existing code

storybook/pages/StatusFileDialogPage.qml, ui/StatusQ/src/StatusQ/Controls/StatusImageSelector.qml, ui/StatusQ/src/StatusQ/Popups/Dialog/+qt6/StatusFileDialog.qml, ui/StatusQ/src/StatusQ/Popups/Dialog/StatusFileDialog.qml, ui/StatusQ/src/StatusQ/Popups/Dialog/qmldir, ui/StatusQ/src/statusq.qrc, ui/app/AppLayouts/Communities/controls/BannerPicker.qml, ui/app/AppLayouts/Communities/controls/LogoPicker.qml, ui/app/AppLayouts/Communities/popups/CreateChannelPopup.qml, ui/app/AppLayouts/Communities/popups/CreateCommunityPopup.qml, ui/app/AppLayouts/Onboarding/OnboardingLayout.qml, ui/app/AppLayouts/Onboarding/views/LoginView.qml, ui/imports/shared/popups/ImageCropWorkflow.qml, ui/imports/shared/status/StatusChatInput.qml, ui/imports/shared/status/StatusInputListPopup.qml
- It closes the main wrapper component creation: [#17561](https://github.com/status-im/status-desktop/issues/17561)
- It also includes commits for the migration of the needed components: 
[#17547](https://github.com/status-im/status-desktop/issues/17547), [#17534](https://github.com/status-im/status-desktop/issues/17534), [#17535](https://github.com/status-im/status-desktop/issues/17535), [#17541](https://github.com/status-im/status-desktop/issues/17541), [#17542](https://github.com/status-im/status-desktop/issues/17542), [#17538](https://github.com/status-im/status-desktop/issues/17538), [#17537](https://github.com/status-im/status-desktop/issues/17537), [#17546](https://github.com/status-im/status-desktop/issues/17546), [#17532](https://github.com/status-im/status-desktop/issues/17532), …
=> feat(qt5->6): Create a `StatusFileDialog` wrapper component for both qt5 and qt6 versions and refactor the existing code

src/app_service/service/accounts/dto/create_account_request.nim, src/app_service/service/accounts/dto/login_request.nim, src/app_service/service/accounts/service.nim
We don't use `statusProxyEnabled` anywhere on the statusgo side, thus not needed on the client side anymore.
Corresponding `statusgo` PR that removes it:
- https://github.com/status-im/status-go/pull/6434
=> chore(wallet): statusProxyEnabled flag removed since it's not in use anymore

storybook/main.cpp, ui/StatusQ/sandbox/sandboxapp.cpp, ui/StatusQ/src/typesregistration.cpp
- sets file selector for StatusQ
- removes per-app selectors from storybook/sanbox
Closes: #17650
`StatusQ` types registration
=> StatusQ: Set file selector for qt6 along with types registration

ui/imports/shared/views/PasswordConfirmationView.qml
- Replaces `RegExpValidator` with `RegularExpressionValidator` as the former is deprecated in qt 5 and removed from qt 6.
Closes: #17644
=> chore: replace deprecated `RegExpValidator` with `RegularExpressionValidator` for qt 6 compat

src/app/modules/main/chat_section/chat_content/input_area/controller.nim, src/app/modules/main/chat_section/chat_content/input_area/module.nim, src/app/modules/main/chat_section/chat_content/input_area/view.nim, src/app_service/service/chat/async_tasks.nim, src/app_service/service/chat/service.nim, ui/StatusQ/CMakeLists.txt, ui/StatusQ/include/StatusQ/urlutils.h, ui/StatusQ/src/typesregistration.cpp, ui/StatusQ/src/urlutils.cpp, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Communities/popups/CreateCommunityPopup.qml, vendor/DOtherSide/lib/include/DOtherSide/DOtherSide.h, vendor/DOtherSide/lib/src/DOtherSide.cpp
- just use the intrinsic resizing done by status-go, only convert the image paths from local URLs to local file paths
Needs https://github.com/status-im/nimqml/pull/63
Fixes #17580
DOtherSide
Chat/Send image(s)
=> chore(DOtherSide): remove image resizing (`dos_image_resizer`)

ui/app/mainui/AppMain.qml, ui/imports/shared/popups/UserStatusContextMenu.qml
In Qt 6 Menu component has final `icon` properly what was conflicting with `icon` property alias defined in UserStatusContextMenu.
Closes: #17647
No impact
=> UserStatusContextMenu: icon property renamed to avoid conflict on Qt 6

ui/app/AppLayouts/Onboarding2/OnboardingLayout.qml, ui/app/AppLayouts/Onboarding2/pages/LoginScreen.qml, ui/app/AppLayouts/Wallet/views/RightTabView.qml
Workaround for qt bug affecting Qt 6 build (https://bugreports.qt.io/browse/QTBUG-135039).
Closes: #17645
`OnboardingLayout`, `LoginScreen`, `RightTabView` (no visual changes)
No impact
=> chore: workaround for QTBUG-135039

storybook/pages/StatusSaveFileDialogPage.qml, ui/StatusQ/src/StatusQ/Popups/Dialog/+qt6/StatusSaveFileDialog.qml, ui/StatusQ/src/StatusQ/Popups/Dialog/StatusSaveFileDialog.qml, ui/StatusQ/src/StatusQ/Popups/Dialog/qmldir, ui/StatusQ/src/statusq.qrc, ui/imports/shared/views/chat/ChatContextMenuView.qml
Closes #17633
Although this is not an issue for migrating to qt6, it's been done for consistency with https://github.com/status-im/status-desktop/issues/17561.
- Created `StatusSaveFileDialog` component with basic interface working in both Qt5 and Qt6.
- Created `storybook` page to test the new component.
`ChatContextMenuView`
No impact
- There is a `storybook` page
- In the app: Go to a 1:1 chat, right click the user / `Download` option in the context menu
=> feat(qt5 -> 6 - SQ/StatusFileDialog): Created new `StatusSaveFileDialog` component

storybook/figmaio.cpp, storybook/pagesmodel.cpp, storybook/validator_main.cpp, ui/StatusQ/include/StatusQ/leftjoinmodel.h, ui/StatusQ/src/concatmodel.cpp, ui/StatusQ/src/leftjoinmodel.cpp, ui/StatusQ/src/modelentry.cpp, ui/StatusQ/src/objectproxymodel.cpp, ui/StatusQ/src/rolesrenamingmodel.cpp, ui/StatusQ/src/statussyntaxhighlighter.cpp, ui/StatusQ/tests/src/TestHelpers/modelsignalsspy.cpp, ui/StatusQ/tests/src/TestHelpers/modelsignalsspy.h, ui/StatusQ/tests/tst_LeftJoinModel.cpp, ui/StatusQ/tests/tst_ObjectProxyModel.cpp, ui/StatusQ/tests/tst_RolesRenamingModel.cpp
- fixes various compilation warnings in cpp components
- adds missing `Q_INTERFACE` declaration to `LeftJoinModel`
- fixes tests of `ObjectProxyModel` caused by additional `headerDataChanged` signal emitted only in qt 6.
- fixes tests of `LeftJoinModel` and `RolesRenamingModel` related to changed format of `QList`'s `toString`
- added `printDebugSummary()` method to `ModelSignalsSpy` for debug purpose
Closes: #17665 
Closes: #17664
`Qt Proxy Models` and other Cpp components.
No impact
=> [Qt 5->6]: Compilation warnings fixes, `Qt Proxy Models` tests aligned to qt 6

storybook/qmlTests/tests/tst_OnboardingLayout.qml, test/e2e/gui/screens/onboarding.py, ui/app/AppLayouts/Onboarding2/OnboardingFlow.qml
- show the HelpUsImprovePage too, when creating a new profile from the login screen's context menu
- adjust the tests for the new expected page in the flow
Fixes #17658
Onboarding/Login
https://github.com/user-attachments/assets/5348c59b-e34d-4a60-bd2d-aee503243979
=> feat(Onboarding): enable analytics screen from login screen too

ui/main.qml
It's not necessary to clear the stack (via unload()) as the whole stack is unloaded in the next line. It's especially important that clearing the stack in this situation was leading to crash on Qt 6 because https://bugreports.qt.io/browse/QTBUG-135295.
Closes: #17679
`main.qml`
[Screencast from 28.03.2025 13:38:45.webm](https://github.com/user-attachments/assets/b379de4c-9e61-401d-9922-6ce323015953)
No impact
Tick **one**:
=> [Qt 5->6]: Onboarding: stack clearing before onboarding deactivation removed

src/app/global/app_signals.nim, src/app/modules/main/module.nim, src/app/modules/onboarding/controller.nim, src/app/modules/onboarding/io_interface.nim, src/app/modules/onboarding/module.nim, src/app/modules/onboarding/view.nim, ui/app/AppLayouts/Onboarding2/stores/OnboardingStore.qml, ui/main.qml
Fixes #17629
Only moves to the main screen when the chats are loaded to avoid showing the "loading sections" message. Also removes the loadingSection as it will never have a chance to be shown again. Removes the 3 second debounce when switching to main as the loading should be all finished by that point anyway
Login and onboarding too technically, but there is nothing to load
This just shows that everything works as expected. It's slow because it's not on top of my speed up branch
[move-to-app-main.webm](https://github.com/user-attachments/assets/76a6484d-b3bc-4d85-be10-0140c579bdca)
Makes sure to never sow the !loading sections" section. …
=> fix(login): move to main only when the chat is loaded

storybook/src/Storybook/HotReloader.qml
Starting from Qt 6.8.3 the behavior of `QQmlEngine::clearComponentCache` has changed, affecting Storybook's hot reloading. 
Related Qt bug report: https://bugreports.qt.io/browse/QTBUG-135448
The provided solution is the simplest one. It delays cache cleaning by `Qt.callLater`. The minor drawback is visible blinking when the component is reloaded. Various other paths has been checked (e.g. using `QQmlComponent`) but in all cases the changed behavior regarding `QQmlEngine::clearComponentCache` turns to be a problem.
Closes: #17716
`HotReloader`
Tick **one**:
-->
=> [Qt 5->6]: Storybook: hot reloading fixed for Qt 6.8.3 and newer

storybook/pages/AccountSelectorPage.qml, storybook/pages/SwapModalPage.qml, ui/app/AppLayouts/Wallet/popups/simpleSend/SimpleSendModal.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapModal.qml, ui/imports/shared/controls/AccountSelector.qml, ui/imports/shared/popups/send/SendModal.qml
- unbreak the binding loops, use absolute `y` position in the header style
- some SB page fixes
AccountSelector
https://github.com/user-attachments/assets/b621190d-b93a-4a65-b370-1541dc30438f
SwapModal under Qt6:
SwapModal under Qt5:
=> fix(AccountSelector): incorrectly rendering header on Qt 6

ci/Jenkinsfile.combined, ci/Jenkinsfile.linux, ci/Jenkinsfile.linux-nix, ci/Jenkinsfile.macos, ci/Jenkinsfile.tests-e2e, ci/Jenkinsfile.tests-nim, ci/Jenkinsfile.tests-ui, ci/Jenkinsfile.windows
Sometimes when CI fails in checkout stage, the post cleanup phase does not get executed which could leave Jenkins workspace in a dirty state.
This PR adds another cleanup phase at the beginning of all jobs, to take care of such scenarios.
=> ci: add cleanup stage before build

ui/StatusQ/include/StatusQ/modelentry.h, ui/StatusQ/src/modelentry.cpp, ui/StatusQ/tests/tst_ModelEntry.cpp
- fixed crash on Qt 6 caused by https://bugreports.qt.io/browse/QTBUG-135619
- fixed `dataChange` from source model handling (fixing broken behavior of `AccountSelector`)
Closes: #17666
Closes: #17682 
`ModelEntry`
=> fix(ModelEntry): Alignments to work on both Qt 5/6

test/e2e/tests/crtitical_tests_prs/test_messaging_1x1_chat.py, test/e2e/tests/crtitical_tests_prs/test_messaging_group_chat.py
bring back messaging tests (1x1 and group chat tests)
=> chore(@e2e): enable messaging tests in PRs

src/app/global/local_app_settings.nim, test/e2e/gui/screens/settings_advanced.py, test/e2e/helpers/SettingsHelper.py, test/e2e/tests/communities/test_communities_categories.py, test/e2e/tests/communities/test_communities_channels.py, test/e2e/tests/communities/test_communities_kick_ban.py, test/e2e/tests/communities/test_communities_limit_to_5_permissions.py, test/e2e/tests/communities/test_communities_pin_and_unpin_messages.py, test/e2e/tests/communities/test_communities_screens_overview.py, test/e2e/tests/communities/test_communities_send_accept_decline_request_from_profile.py, test/e2e/tests/crtitical_tests_prs/test_community_category_add_edit_delete.py, test/e2e/tests/crtitical_tests_prs/test_community_create_edit_share_link.py, test/e2e/tests/crtitical_tests_prs/test_community_permissions_add_edit_delete_duplicate.py, test/e2e/tests/transactions_tests/test_mint_owner_and_tokenmaster_tokens.py, ui/app/AppLayouts/Communities/CommunitiesPortalLayout.qml, ui/app/AppLayouts/Communities/stores/CommunitiesStore.qml, ui/app/AppLayouts/Profile/stores/AdvancedStore.qml, ui/app/AppLayouts/Profile/views/AdvancedView.qml
Fixes #17671
Makes the Create Community button visible and available to everyone regardless of the setting. The setting switch and Nim code for it has been removed.
Community portal and settings
Everyone has access to the create community buttons now
- Open the portal and the settings
Tick **one**:
Not much risk here
=> chore(community): show Create Community button for everyone

Makefile, ui/main.qml
TLDR: make it possible to build against multiple Qt versions at will; Windows use a dll so should be fine
- add separate build dirs, based on Qt version being used
- do not hardcode/repeat the `DOTHERSIDE_LIBFILE`
- use the respective `CMAKE_PREFIX_PATH` when building the Qt parts
- output Qt runtime version on app start to ease debugging/verifying the correct Qt version is used at runtime for QML
- store `QMAKE` variable to a file in order to compare current and previous invocation and therefore detect need of re-linking
Fixes #17738
Needs: https://github.com/status-im/dotherside/pull/92
Makefile
Qt 6 build:
Qt 5 build:
=> feat(Qt5 -> 6): support parallel builds

test/e2e/tests/crtitical_tests_prs/test_messaging_1x1_chat.py, test/e2e/tests/crtitical_tests_prs/test_messaging_group_chat.py
- bring back step of sending community link in chat
- disable step of checking wallet address to link functionality
=> chore(@e2e): temp disable step with resolving wallet address in chat

ui/app/AppLayouts/Communities/controls/OutroMessageInput.qml, ui/app/AppLayouts/Communities/popups/CreateCommunityPopup.qml
Close #17753
Added clarification text to the community intro and outro labels.
Community Creation popup
No impact, just a clarification message to the user
- Create community flow
=> feat(communities): Add clarification text to the community intro an outro labels

storybook/pages/EnableFullMessageHistoryPopupPage.qml, ui/app/AppLayouts/Communities/controls/EditCommunitySettingsForm.qml, ui/app/AppLayouts/Communities/controls/Options.qml, ui/app/AppLayouts/Communities/popups/CreateCommunityPopup.qml, ui/app/AppLayouts/Communities/popups/EnableFullMessageHistoryPopup.qml, ui/app/AppLayouts/Communities/popups/qmldir, ui/app/AppLayouts/Profile/stores/AdvancedStore.qml, ui/app/mainui/AppMain.qml, ui/app/mainui/Popups.qml
Closes #17751
- `Options` component reordering.
- Archive protocol related checkbox renamed.
- Created new information popup `EnableFullMessageHistoryPopup` and its corresponding `storybook` page.
Create New Community Popup
**App running on Qt5:**
https://github.com/user-attachments/assets/7ec583bc-6850-4b66-8e3d-da3cbaec5082
**Storybook running on Qt6:**
https://github.com/user-attachments/assets/a02e59fe-00c3-4e7d-8161-a2284eb7b24b
No impact, just more information about the archive protocol checkbox.
- Opening the `Create New Community` popup.
- Using `storybook`.
=> feat(Communities): Updated community creation archive protocol flow with new design

ui/app/AppLayouts/Profile/popups/ExemptionNotificationsModal.qml, ui/app/AppLayouts/Profile/views/NotificationsView.qml
- wrap the modal in a `Component`, and pass the proper parent when creating it
Fixes #17733
Settings/Notifications
=> fix(NotificationsView): Exemption dialog populates off-centre

ui/StatusQ/src/StatusQ/Controls/StatusSelectableText.qml, ui/StatusQ/src/StatusQ/Controls/StatusWarningBox.qml, ui/app/AppLayouts/Communities/controls/Options.qml
Closes #17752
- Add info banner to ensure users know token gating and mint tokens flows can be reached after community is created.
- `SQ/StatusSelectableText`: Added `defaultLinkColor` property.
- `SQ/StatusWarningBox`: Added new property to setup the `extraContent` layout as column or row format.
- Create community popup flow
- `StatusSelectableText` component
- `StatusWarningBox` component
https://github.com/user-attachments/assets/720581a9-6439-4a1f-aeea-b542ea2a3477
During `Create Community Flow` there's a new info box to add more clarification to the user about the gated communities. 
- Open create community flow and scroll to the …
=> feat(Communities): Add info banner in Community Creation Flow

test/e2e/tests/communities/test_communities_limit_to_5_permissions.py
Test for permission creation is marked as expected to fail because of https://github.com/status-im/status-desktop/issues/17786
=> chore(@e2e): mark permission creation test xfail

ci/Jenkinsfile.macos
I've upgraded all CI hosts to Xcode 16.
After this PR is merged we can finally switch the labels in Jenkins.
=> ci: use xcode 16.2

storybook/pages/PromotionalCommunityCardPage.qml, ui/app/AppLayouts/Communities/controls/PromotionalCommunityCard.qml, ui/app/AppLayouts/Communities/controls/qmldir, ui/app/AppLayouts/Communities/views/CommunitiesGridView.qml
Closes #17754
- It creates`PromotionalCommunityCard` component and added corresponding `storybook` page.
- It adds a promotional card into the third position of the current `Communities Portal` layout as per design.
Communities Portal
- `Storybook` page
https://github.com/user-attachments/assets/f14f229e-6036-429d-86e7-50787b12239f
- `App`
It promotes the Community Directory Curation to encourage community owners and members to have their community featured on the Communities Portal page.
- Test the component at `storybook`
- Test the promotional card at `Communities Portal` page
=> feat(Communities): Add promotional card into community portal

storybook/pages/ActivityNotificationNewsMessagePage.qml, storybook/pages/NewsMessagePopupPage.qml, ui/StatusQ/src/StatusQ/Components/StatusRoundedImage.qml, ui/app/mainui/Popups.qml, ui/app/mainui/activitycenter/popups/ActivityCenterPopup.qml, ui/app/mainui/activitycenter/views/ActivityNotificationNewsMessage.qml, ui/imports/shared/popups/NewsMessagePopup.qml, ui/imports/shared/popups/qmldir
Fixes https://github.com/status-im/status-desktop/issues/17691
Based on top of https://github.com/status-im/status-desktop/pull/17719
Status-go PR: https://github.com/status-im/status-go/pull/6487
The first commit is the component alone and storybook elements
The second one is the hooking to the rest + metrics
AC
Again, it doesn't follow the Design exactly, because I use the current component and I also used Hacker news so there is no image and the text is not truncated yet (it will be done in another issue/PR)
[news-popup.webm](https://github.com/user-attachments/assets/161c5879-2a04-4398-897f-1bfc59ebe162)
Storybook: 
Let's users see the …
=> Implement News Feed popup

ui/StatusQ/src/StatusQ/Components/StatusContactVerificationIcons.qml, ui/StatusQ/src/StatusQ/Components/StatusEmoji.qml, ui/StatusQ/src/StatusQ/Components/StatusListPickerProxies.qml, ui/StatusQ/src/StatusQ/Controls/StatusTokenInlineSelector.qml, ui/StatusQ/src/StatusQ/Platform/StatusMacNotification.qml, ui/StatusQ/src/StatusQ/Platform/StatusMacTrafficLights.qml
Closes #17451
In Qt 5, relative urls were directly resolved, especially when assigned to an url property. In Qt 6 this is no longer the case. In order to continue with the old behavior, `Qt.resolvedUrl` is used.
SQ components: `StatusContactVerificationIcons`, `StatusEmoji`, `StatusListPickerProxies` (`CurrenciesModel`), `StatusTokenInlineSelector`, `StatusMacNotification` and `StatusMacTrafficLights`.
No impact
=> fix(Qt5->6): Fix relative url resolution

src/app/core/notifications/details.nim, src/app/core/notifications/notifications_manager.nim, src/app/global/global_events.nim, src/app/modules/main/activity_center/item.nim, src/app/modules/main/activity_center/model.nim, src/app/modules/main/activity_center/module.nim, src/app/modules/main/ephemeral_notification_item.nim, src/app/modules/main/io_interface.nim, src/app/modules/main/module.nim, src/app/modules/main/view.nim, src/app_service/service/activity_center/dto/notification.nim, storybook/pages/NewsMessagePopupPage.qml, ui/app/mainui/AppMain.qml, ui/app/mainui/Popups.qml, ui/app/mainui/ToastsManager.qml, ui/app/mainui/activitycenter/helpers/ActivityNotification.qml, ui/app/mainui/activitycenter/helpers/NotificationModelEntry.qml, ui/app/mainui/activitycenter/helpers/qmldir, ui/app/mainui/activitycenter/popups/ActivityCenterPopup.qml, ui/app/mainui/activitycenter/views/ActivityNotificationNewsMessage.qml, ui/imports/shared/popups/NewsMessagePopup.qml, ui/imports/utils/Global.qml
Fixes https://github.com/status-im/status-desktop/issues/17690
Status-go PR: https://github.com/status-im/status-go/pull/6487
When receiving a new News, shows an Ephemeral or OS notification depending on the active state of the app
Contains 3 commits:
1. Basic implementation of the ephemeral notification without action
2. Clean up of old duplicated code
3. Adding the action of opening the News popup when clicking the toast and also move the opening logic to QML to have `qsTr`.
Notification manager, AC code, main module code
[toast-message.webm](https://github.com/user-attachments/assets/401dd75b-68d9-4b06-868d-2b4dd1587671)
There are a lot of …
=> Implement News Feed Ephemeral notifications

scripts/macos_build_setup.sh
Pin `cmake` formulae from `homebrew`: https://github.com/Homebrew/homebrew-core/commit/b4e46db74e74a8c1650b38b1da222284ce1ec5ce
`homebrew` will still complain like this but we don't care
```
Warning: cmake 4.0.1 is available and more recent than version 3.31.6.
```
I tested this locally on my Mac and it works : 
```
==> Downloading https://ghcr.io/v2/homebrew/core/cmake/manifests/3.31.6
############################################################################ 100.0%
==> Fetching cmake
==> Downloading https://ghcr.io/v2/homebrew/core/cmake/blobs/sha256:755552ccd83c734
############################################################################ 100.0%
==> Upgrading cmake
3.30.4 -> 3.31.6 
Warning: cmake 4.0.1 is available and more recent than version 3.31.6.
==> Pouring …
```
=> macos: pin cmake to 3.31.6

test/e2e/gui/elements/object.py, test/e2e/gui/screens/community.py, test/e2e/gui/screens/messages.py, test/e2e/tests/communities/test_communities_kick_ban.py, test/e2e/tests/communities/test_communities_pin_and_unpin_messages.py
- replace the waitFor with explicit condition, no need to wait there
- replace the Lookup class with general exception in order not to re-define built-in Squish Lookup error
- removed a bit of unused code
=> chore(@e2e): remove useless waitFor that was leading tests to stuck forever

ui/StatusQ/src/StatusQ/Components/private/StatusComboboxBackground.qml, ui/StatusQ/src/StatusQ/Controls/StatusComboBox.qml, ui/StatusQ/src/StatusQ/Popups/StatusMenuSeparator.qml, ui/app/AppLayouts/Wallet/controls/SortOrderComboBox.qml
- also fix the separator height/bg color
- use the common StatusDropdown for the popup impl
- fix a similar generic prob in StatusComboBox
Fixes #17815
SortOrderComboBox (in Assets/CollectiblesView)
Qt5 / light mode:
Qt6 / dark mode:
=> fix: SortOrderComboBox doesn't render any text under Qt6

ui/app/AppLayouts/Wallet/controls/NetworkFilter.qml, ui/app/AppLayouts/Wallet/popups/NetworkSelectPopup.qml
fixes #17775
Removed Binding errors and now it works as excpected
NetworkFilter -> Swap, Send and Buy modal
https://github.com/user-attachments/assets/02739fea-0e9a-4d7f-b5ec-5f9870dbfe18
=> fix(@desktop/wallet): Send modal - Network selector does not show Mainnet as default chain

ui/app/AppLayouts/Onboarding2/OnboardingFlow.qml
- avoid binding component nested in Loader and StackView which causes a crash under Qt6 (https://bugreports.qt.io/browse/QTBUG-135295)
Fixes #17827
Onboarding/Login
https://github.com/user-attachments/assets/d8580743-6d4e-423b-bc2b-8d4baf60f49c
=> fix(Onboarding): don't crash with wrong password on Qt6

storybook/pages/StatusMessagePage.qml, ui/StatusQ/src/StatusQ/Components/StatusMessage.qml, ui/StatusQ/src/StatusQ/Components/private/statusMessage/StatusTextMessage.qml, ui/StatusQ/src/StatusQ/Core/Utils/Utils.qml, ui/app/AppLayouts/Chat/ChatLayout.qml, ui/app/AppLayouts/Chat/views/ChatColumnView.qml, ui/app/AppLayouts/Chat/views/ChatContentView.qml, ui/app/AppLayouts/Chat/views/ChatMessagesView.qml, ui/app/AppLayouts/Chat/views/ChatView.qml, ui/app/mainui/AppMain.qml, ui/imports/shared/views/chat/MessageView.qml
fixes #17757
Adds disabled tooltip over address/end name link in chat so that the user can know that the send in chat is unavailable because send functionality is not working currently. 
Send 1-1 chat
https://github.com/user-attachments/assets/0756b4fd-0b48-48f7-8d24-5bb54d4b05c3
=> fix(@desktop/wallet): Wallet address is not being resolved into a link in chat

src/app/core/signals/remote_signals/wallet.nim, src/app/modules/main/wallet_section/send/controller.nim, src/app/modules/main/wallet_section/send/io_interface.nim, src/app/modules/main/wallet_section/send/module.nim, src/app/modules/main/wallet_section/send/suggested_route_item.nim, src/app/modules/main/wallet_section/send/view.nim, src/app/modules/main/wallet_section/send_new/controller.nim, src/app/modules/main/wallet_section/send_new/io_interface.nim, src/app/modules/main/wallet_section/send_new/module.nim, src/app/modules/main/wallet_section/send_new/view.nim, src/app_service/service/community_tokens/service.nim, src/app_service/service/transaction/dto.nim, src/app_service/service/transaction/service.nim, src/backend/transactions.nim, src/backend/wallet.nim, ui/app/AppLayouts/Wallet/popups/swap/SwapInputParamsForm.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapModalAdaptor.qml, ui/app/AppLayouts/Wallet/stores/SwapStore.qml, ui/app/AppLayouts/Wallet/stores/TransactionStoreNew.qml, ui/app/mainui/SendModalHandler.qml, ui/imports/shared/popups/send/SendModal.qml, ui/imports/shared/stores/send/TransactionStore.qml
After improvements on the fees calculation the build transaction 1001 error started to occur. It was because of missed slippage param when doing the build tx call. Fixed on the statusgo side.
These changes also bring some improvements on setting custom slippage.
Corresponding `status-go` changes:
- https://github.com/status-im/status-go/pull/6548
=> fix(swap): build paraswap tx error

ui/StatusQ/src/systemutilsinternal.cpp, ui/app/AppLayouts/Profile/views/SettingsLeftTabView.qml, ui/app/AppLayouts/Profile/views/wallet/EditNetworkForm.qml, ui/app/mainui/StatusTrayIcon.qml, ui/main.qml
- workaround the `closing` signal differences between Qt5 and Qt6, and call `Qt::exit()` directly when we want to explicitly quit the app
- removed some unused stuff
Fixes https://github.com/status-im/status-desktop/issues/17855
App
TBD
=> fix(Qt6): impossible to quit the app

src/app_service/service/accounts/dto/create_account_request.nim, src/app_service/service/accounts/service.nim
Setting the auto-refresh option by default to true was already implemented on the statusgo side and that way old Status profiles were affected, but for newly created Status profile that setting has to be sent from the client. That's now fixed in this PR.
Closes #17868
=> fix(wallet): ensure the token list auto-refresh option is enabled by default

src/app/modules/main/wallet_section/send/io_interface.nim, src/app/modules/main/wallet_section/send/module.nim, src/app/modules/main/wallet_section/send/view.nim, src/app/modules/main/wallet_section/send_new/io_interface.nim, src/app/modules/main/wallet_section/send_new/module.nim, src/app/modules/main/wallet_section/send_new/view.nim, storybook/pages/SendModalPage.qml, storybook/qmlTests/tests/tst_SwapModal.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapModal.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapModalAdaptor.qml, ui/app/AppLayouts/Wallet/stores/SwapStore.qml, ui/app/AppLayouts/Wallet/stores/TransactionStoreNew.qml, ui/app/mainui/SendModalHandler.qml, ui/imports/shared/popups/send/SendModal.qml, ui/imports/shared/stores/send/TransactionStore.qml
The password was permanently stored between different swap flow runs if the flow was closed after approval but before swap tx. The flow didn't ask for password if higher amount was entered after successfully completed approval tx.
How it works now:
- if the user runs Swap and provides pass for the approval the app doesn't ask for pass when placing a swap tx
- if the user closes the Swap popup after providing correct password the app will ask for it next time the user runs Swap popup and try to place approval/swap tx
- if the user runs Swap popup and tries to increase amount after an already approved amount during the same Swap flow, the app will ask for pass
Closes #17875
=> fix(wallet): swap - approve spending cap doesn't ask for password

src/app/core/notifications/notifications_manager.nim, src/app_service/service/settings/dto/settings.nim, src/app_service/service/settings/service.nim, src/backend/settings.nim, ui/app/AppLayouts/Profile/ProfileLayout.qml, ui/app/AppLayouts/Profile/stores/NotificationsStore.qml, ui/app/AppLayouts/Profile/stores/PrivacyStore.qml, ui/app/AppLayouts/Profile/views/NotificationsView.qml, ui/app/AppLayouts/Profile/views/PrivacyAndSecurityView.qml, ui/app/mainui/activitycenter/popups/ActivityCenterPopup.qml, ui/imports/shared/popups/NewsMessagePopup.qml
Fixes #17811
Based on top of https://github.com/status-im/status-desktop/pull/17809
Status-go PR: https://github.com/status-im/status-go/pull/6540
Hooks the NewsFeedNotification setting and the RSS setting to the backend.
The Notification setting has a bit of complexity on the service side, because while the UI setting is a select of 3 options, the status-go settings are actually 2 bool settings. So the service does some logic to set the right setting from those two.
The settings are used to disable the polling if one of the settings is disabled. If the setting is on DeliverQuietly, the AC notif is shown, but no OS or toast notification
Hooks the UI settings to the backend settings. Makes the UX for the News Feed complete, once the feature flag on the status-go side is enabled and once …
=> feat(news): hook settings to the backend

ui/app/mainui/Popups.qml
Fixes #17883
[cta-fix.webm](https://github.com/user-attachments/assets/b464baa8-d13e-4259-8e4f-80482108d893)
=> fix(news): fix News popup CTA not opening the website

ui/app/AppLayouts/Communities/controls/DescriptionInput.qml, ui/imports/utils/Constants.qml
Adds comma to the set of allowed character for community description.
Closes: #17896
Note: created task for improving constants handling: https://github.com/status-im/status-desktop/issues/17898
`DescriptionInput`
=> chore(Communities): Allow commas in the community description

test/e2e/gui/objects_map/settings_names.py, test/e2e/gui/screens/settings_advanced.py
allow test to scroll to the very bottom of the advanced screen so test can access the "manage communities on testnet" toggle easily
=> chore(@e2e): scroll to the very last element on the advanced screen

storybook/main.cpp, storybook/main.qml, storybook/pages/ProfileContextMenuPage.qml, storybook/pages/StatusNavBarTabButtonPage.qml, ui/StatusQ/src/StatusQ/Controls/StatusBaseButton.qml, ui/StatusQ/src/StatusQ/Controls/StatusIconTabButton.qml, ui/StatusQ/src/StatusQ/Controls/StatusTabButton.qml, ui/StatusQ/src/StatusQ/Controls/StatusTextArea.qml, ui/StatusQ/src/StatusQ/Core/Theme/Theme.qml, ui/StatusQ/src/StatusQ/Popups/StatusMenu.qml, ui/StatusQ/src/StatusQ/Popups/StatusMenuItem.qml, ui/app/AppLayouts/Communities/panels/SharedAddressesPermissionsPanel.qml, ui/app/AppLayouts/Profile/views/AppearanceView.qml, ui/app/AppLayouts/Wallet/views/RightTabView.qml, ui/imports/shared/status/StatusChatInput.qml, ui/main.qml
- fix Qt6 styling for Status(Base)Button and StatusChatInput
- remove `Universal` style imports
- bring Qt6 hover effects/events in line with the old behavior of Qt 5, that is when the control is disabled, we get no hover events (changed bg, different cursor shape, etc)
- fix some spurious startup issue (more visible on mac), related to nested `Rectangle` aliased properties
(see the commits for a more detailed description) 
Fixes #17763
Fixes https://github.com/status-im/status-desktop/issues/17693
Fixes https://github.com/status-im/status-desktop/issues/17905
StatusButton, StatusChatInput
=> fix(Qt6): Broken styling on some platforms 

src/app/modules/onboarding/module.nim
Fixes #17907
The problem was that we were calling appReady when the app wasn't fully loaded, so the main module wasn't loaded to listen to the event being emited by the url_manager.
Order of events during login
[deep-link-fix.webm](https://github.com/user-attachments/assets/27850e3e-0866-4131-a45f-1db1b9f31b07)
Fixes the use case where a user clicks on a deep link and the app is not opened yet
1. Close the app
2. Click a deep link
3. App opens
4. Login
5. See that the link resolves
No risk as `appReady` only does the call to the urls_manager
=> fix(deep-links): fix the order of calling appReady to fix deep links

ui/imports/shared/popups/ImportCommunityPopup.qml, ui/imports/utils/Utils.qml
Fixes #17904
Enables the use of short community urls, channel links and data+ID in the import community popup
Import Community Popup and Utils function (but it's only used in the popup)
[import-keys.webm](https://github.com/user-attachments/assets/515d4f23-50f1-4011-bf37-d97909ce7f48)
Enables the user to import their community from more types of links
- Paste links in the Join Community popup (formerly known as Import Community)
No risk
=> fix(import): fix importing communities using the c#key format

scripts/sign-windows-bin.sh
Possibly a fix for signing errors while using default DigiCert timeserver.
- Windows signatures failing with error:
```groovy
Error information: "Error: SignerSign() failed." (-2146869243/0x80096005)
SignTool Error: An unexpected internal error has occurred.
```
Ref.: 
- https://github.com/status-im/status-desktop/issues/16199
- https://github.com/status-im/status-desktop/pull/17063
=> fix(ci): fix for signing using DigiCert timeserver

src/app/modules/main/wallet_section/send/controller.nim, src/app/modules/main/wallet_section/send/io_interface.nim, src/app/modules/main/wallet_section/send/module.nim, src/app/modules/main/wallet_section/send/suggested_route_item.nim, src/app/modules/main/wallet_section/send/view.nim, src/app_service/service/transaction/dto.nim, src/app_service/service/transaction/service.nim, src/backend/wallet.nim, ui/app/AppLayouts/Wallet/popups/swap/SwapModal.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapModalAdaptor.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapOutputData.qml, ui/app/AppLayouts/Wallet/stores/SwapStore.qml
- https://github.com/status-im/status-go/pull/6568
In the video below you can spot the different fees for an already approved amount of 0.5 USDC and a higher value which was not approved yet. In the second part higher value of 0.59 USDC was approved and sent.
Related tx:
- approval tx: https://etherscan.io/tx/0x1cb64c2007f7b44fced952fbf327fce9f60f9a3b6186b900bb5918f64b69bc09
- swap tx: https://etherscan.io/tx/0xc5f6bcb913b4f0a636de1528ed5658a05d8737767d660fb5020d6d20c04310fa
https://github.com/user-attachments/assets/01410ce8-a1a2-4615-9e52-98ecf913da42
=> fix(wallet): reevaluating fees for swap after approval tx gets confirmed

ui/StatusQ/src/StatusQ/Components/StatusMemberListItem.qml, ui/app/AppLayouts/Communities/panels/MembersTabPanel.qml
- handle the RMB using a MouseArea in order to not collide with the builtin left click
- in the members settings panel, differentiate correctly between left and right mouse clicks
Fixes #17917
Community/Admin/Members
https://github.com/user-attachments/assets/cd1a7f58-f936-4449-803d-5c66bcb34015
=> fix(MembersTabPanel): fix left/right mouse click

storybook/pages/NewsMessagePopupPage.qml, ui/StatusQ/src/StatusQ/Core/Utils/Utils.qml, ui/imports/shared/popups/NewsMessagePopup.qml
Fixes the layout of the News popup when it has an image.
Before, it would always make the "image" 300px high and if the image was smaller than that, it would have a lot of empty space.
Now it adapts and has a **max** of 300.
NewsMessagePopup
Implementation:
Design:
None
- Check the storybook
- Check a News with an image
None
=> Fix News Popup layout when it has an image

src/app/core/notifications/notifications_manager.nim, src/app/modules/main/activity_center/controller.nim, src/app/modules/main/activity_center/io_interface.nim, src/app/modules/main/activity_center/module.nim, src/app_service/service/activity_center/service.nim, src/app_service/service/general/service.nim
Fixes https://github.com/status-im/status-desktop/issues/17895
The issue was that I was too permissive when I wrote the code to show the toasts and it triggered any time a notification was added or loaded, so on app start, it could trigger too.
However, I got lucky because most of the time the load happened before the NotificationManager was ready, so this race condition hid the issue.
I fixed it by using different event names for when an AC notif is received vs loaded
I also added a second commit that cleans some dead code. This event was never listened to, so it can be safely removed.
AC service and module
Fixes the random issue of toasts …
=> fix(news): fix toast notifs sometimes showing when they should not

ui/StatusQ/src/StatusQ/Core/Utils/Utils.qml, ui/imports/shared/popups/NewsMessagePopup.qml
Removes the Utils stripHtmlPreserveBreaks function that was used as a workaround since the RSS contained HTML tags still.
Also fixes a little layout issue where if the Content was too long, it didn't elide.
=> chore(news): remove stripHtml workaround for the news content

ui/app/AppLayouts/Wallet/popups/simpleSend/SendSignModal.qml
This PR solves the following two issues:
Closes #17932
Closes #17934
Corresponding statusgo PR:
- https://github.com/status-im/status-go/pull/6575
Swap made from the Stauts app:
- approval: https://optimistic.etherscan.io/tx/0x79f4c93ea35e9e8129cba00cf14fd54ba5536f9f77d470df94e1d60619bce9d9
- swap: https://optimistic.etherscan.io/tx/0x7570e654150862ac4e3517271d5c15db7f0ff8fa33141328fe8f692c05ae2841
**Note:**
If you have a gap in nonces for your account, make sure it's fixed before testing the swap. That's a good opportunity to test the custom settings part. If you need help on this, feel free to ping me.
=> fix(swap): Swap BNB chain tokens - Swap tx gets stuck in Pending

ui/StatusQ/src/StatusQ/Components/StatusMemberListItem.qml
- got caught by e2e tests; we still need the HoverHandler to handle the hover & cursorShape for the whole item in a way that doesn't obscur the extra buttons placed on top
- the MouseArea handles the right mouse click, and nothing else
Fixes #17944
StatusMemberListItem
https://github.com/user-attachments/assets/4b950b79-340e-44d0-bd2c-1adb367a1766
=> fix(StatusMemberListItem): fixup hover over extra buttons

ci/Jenkinsfile.combined, ci/Jenkinsfile.windows, scripts/sign-windows-bin.sh
This PR implements DigiCert Keylocker, a cloud-based HSM solution, for signing release binaries. Development builds continue to use self-signed certificates for code signing.
Configure environment variables for DigiCert credentials
Update signing script to conditionally use either DigiCert (for releases) or development certificates
Tested on Windows with this PR:
- https://github.com/status-im/status-desktop/pull/17862
Verifying development builds sign correctly with self-signed certificate
Confirming release builds successfully sign with DigiCert Keylocker
Closes [#183](https://github.com/status-im/infra-ci/issues/183)
=> chore(ci): renew DigiCert Certificate for signing release builds

ui/app/AppLayouts/Communities/popups/CreateChannelPopup.qml, ui/imports/utils/Constants.qml
While testing other bugs, I found that channel descriptions didn't support commas, like the community description.
So I changed it to use the same regex.
I also added `&` in the list of accepted characters. I don't think it can cause issues, as it's just a description.
Finally, I added comments to the regexes, because reading regexes is a pain.
=> fix(channel): enable the use of commas and ampersands in channel desc

ui/StatusQ/src/StatusQ/Controls/StatusBaseInput.qml, ui/app/AppLayouts/Profile/panels/ProfileDescriptionPanel.qml, ui/imports/shared/views/profile/ShareProfileDialog.qml
Fixes #14467
The issue was that the TextEdit was bound to the size of the flickable, so when it got scrolled, mouse clicked we only on the ScrollView and no longer on the TextEdit, ie the mouse click was only good to scroll (drag) but not to select text.
Removing the height property and letting the TextEdit follow its content fixes it.
All `StatusBaseInput`s, ie all `StatusInput`s :see_no_evil: 
As far as I could see, only the ShareProfileDialog was affected, where the placeholder text for the share link was stuck to the top of the input. I fixed it in this PR too.
Other Inputs seem fine.
In this video, I show the long bio issue being fixed …
=> fix(StatusBaseInput): clicking in bottom text of the input not working

storybook/pages/SendModalPage.qml, ui/imports/shared/popups/send/SendModal.qml, ui/imports/shared/popups/send/views/NetworkCardsComponent.qml, ui/imports/shared/popups/send/views/NetworksAdvancedCustomRoutingView.qml, ui/imports/shared/popups/send/views/TransactionModalFooter.qml
fixes #17949
Fixes broken layout in Bridge modal advanced mode
https://github.com/user-attachments/assets/30a71472-de20-44d1-abf5-b1624569e5a1
=> fix(@desktop/wallet): [Qt6] BridgeModal layout broken

src/app/core/signals/remote_signals/messages.nim, src/app_service/service/accounts/service.nim, src/app_service/service/profile/service.nim, ui/app/mainui/Popups.qml, ui/imports/shared/controls/chat/ProfileHeader.qml
Fixes #17731
We just didn't listen to the property change from the signal.
Signal listening
[profile-change.webm](https://github.com/user-attachments/assets/7ace2798-b14b-4643-a6a5-8f47e59937aa)
Fixes the issue (no longer need to restart the app)
1. Pair your desktop app with a mobile one (though another desktop would do the same)
2. Update the profile pic on the new one
3. it updates now
Worst case the bug isn't fixed
Tick **one**:
=> fix(pairing): profile img not updating when the paired device changes it

src/app/modules/main/wallet_section/send_new/controller.nim, src/app/modules/main/wallet_section/send_new/io_interface.nim, src/app/modules/main/wallet_section/send_new/module.nim, src/app/modules/main/wallet_section/send_new/path_item.nim, src/app/modules/main/wallet_section/send_new/path_model.nim, src/app/modules/main/wallet_section/send_new/view.nim, src/app_service/service/network/network_item.nim, src/app_service/service/transaction/dtoV2.nim, src/app_service/service/transaction/service.nim, src/backend/backend.nim, src/backend/network_types.nim, src/backend/wallet.nim, storybook/pages/SendSignModalPage.qml, storybook/pages/TransactionSettingsPanelPage.qml, storybook/qmlTests/tests/tst_SendSignModal.qml, ui/app/AppLayouts/Wallet/popups/simpleSend/SendSignModal.qml, ui/app/AppLayouts/Wallet/stores/TransactionStoreNew.qml, ui/app/AppLayouts/Wallet/views/TransactionSettings.qml, ui/app/mainui/SendModalHandler.qml
Corresponding `stautsgo` PR:
- https://github.com/status-im/status-go/pull/6582
Apart from adding custom fee settings for BSC chain-based transactions, this PR solves some bugs that are in the master branch:
- missing bottom left message for the `Max base fee` input field from the custom transaction settings form
- incorrectly calculated fees on the bottom right side for the `Max base fee` and `Priority fee` inputs 
- issue with empty input fields if the user opens the custom transaction settings view, then goes to any other then comes back to the custom view again
- missing explanation message when hovering over fee options
=> feat(wallet): fees/custom settings for non eip1559 chains

ci/Jenkinsfile.combined, ci/Jenkinsfile.linux, ci/Jenkinsfile.linux-nix, ci/Jenkinsfile.macos, ci/Jenkinsfile.windows
Updating jenkins lib to v1.9.24 to  inject Market data Proxy credentials to the desktop builds.
CI
- [ x] I am familiar with the application architecture and agreed good practices.
=> ci: update jenkins lib to v1.9.24

storybook/qmlTests/tests/tst_SwapInputPanel.qml, storybook/qmlTests/tests/tst_SwapModal.qml, storybook/src/Models/GroupedAccountsAssetsModel.qml, storybook/src/Models/TokensBySymbolModel.qml, ui/app/AppLayouts/Wallet/panels/SwapInputPanel.qml, ui/app/AppLayouts/Wallet/popups/swap/SwapModal.qml, ui/imports/utils/Constants.qml
Fixes https://github.com/status-im/status-desktop/issues/17778
Slightly change the logic for token re-evaluation when changing chains. If the token is not available on the new chain, we try to set the default one. If the default one collides with what's selected on the opposite side, we just leave it blank.
Token existence on a give chain is now done with `plainTokensBySymbolModel`, and the model set to the selector (which only contains tokens on a subset of chains) is only used to properly set the button state but doesn't impact the reevaluation. This prevents wrongly resetting to default when a chain change occurs.
https://github.com/user-attachments/assets/abbac167-384f-431c-8256-cee8af5d9523
Swap …
=> fix: proper workaround for swap default tokens

ui/app/AppLayouts/Wallet/popups/simpleSend/SimpleSendModal.qml
#17983
cherry pic of as per account selected.
This fix forces re-evaluation of max amount on assets model count changed
=> [CHERRY-PICK]: Release/fix max amount on account changed as per account selected

src/app/modules/main/communities/tokens/models/token_model.nim, src/app/modules/main/module.nim, src/app/modules/shared_models/section_item.nim, storybook/pages/SortableTokenHoldersListPage.qml, storybook/pages/SortableTokenHoldersPanelPage.qml, storybook/src/Models/TokenHoldersJoinModel.qml, storybook/src/Models/TokenHoldersModel.qml, storybook/src/Models/UsersModel.qml, storybook/src/Models/qmldir, ui/StatusQ/src/StatusQ/Components/StatusMemberListItem.qml, ui/app/AppLayouts/Chat/panels/UserListPanel.qml, ui/app/AppLayouts/Communities/controls/TokenHolderListItem.qml, ui/app/AppLayouts/Communities/panels/MintTokensSettingsPanel.qml, ui/app/AppLayouts/Communities/panels/SortableTokenHoldersList.qml, ui/app/AppLayouts/Communities/panels/SortableTokenHoldersPanel.qml, ui/app/AppLayouts/Communities/panels/TokenHoldersProxyModel.qml, ui/app/AppLayouts/Communities/views/CommunityTokenView.qml, ui/app/mainui/activitycenter/views/ActivityNotificationMessage.qml, ui/imports/shared/views/chat/MessageView.qml, ui/imports/utils/Utils.qml
Fixes #17146
The issue was that we didn't use the LeftJoinModel correctly. The TokenHolderModel should have been on the left.
Then, we often do not have access to the shared address of the members as a TokenMaster, so it would show an empty member. I fixed that by doing a clean up so that we use the normal token list component, which has a mode where it shows the address only if we don't have access to the member's info.
This differs from the design a little but makes the code way cleaner, as we don't need two different components and also I removed the use of `getContactbyIDJson`
Finally, if the Owner is yourself, we also never got the full info, because we do not save our own revealed addresses as an owner.
I implemented a workaround fix to the problem.
The fix here is to simply …
=> fix(tokens): fix token holder list not showing the right member

src/app_service/service/token/service.nim, ui/app/AppLayouts/Wallet/stores/TokensStore.qml, ui/imports/utils/Constants.qml
This commit contains changes that align with adding kleros and superchain remote lists on the statusgo side.
- https://github.com/status-im/status-go/pull/6606
For the recording, I've set the refresh interval to 30 seconds.
https://github.com/user-attachments/assets/2e61990e-7b8c-41eb-8c1a-2ded5dea32c5
=> chore(wallet): properly update the list of tokens lists after fetching them from remote

ui/app/AppLayouts/Wallet/popups/simpleSend/SimpleSendModal.qml
Fixes #18015
That property is only used to bind the  balances, however, for collectible sends, those balances don't exist. This condition fixes the issue and also keeps the binding for asset sends
[fix-send.webm](https://github.com/user-attachments/assets/4fa3e9ee-a0c3-4d5c-a798-a5a11aa44362)
=> fix(collectibles): fix sending of collectibles in the SimpleSendModal

CONTRIBUTING.md, README.md, guidelines/QML_ARCHITECTURE_GUIDE.md
Moves the current content of the CONTRIBUTING guide to `guidelines/QML_ARCHITECTURE_GUIDE.md`
Adds a basic Developing section to CONTRIBUTING (needs more love in another PR) and adds the testing docs.
=> docs(contributing): update CONTRIBUTING guide to add the Testing section

BUILDING.md
This moves the content of the building guide from Notion to Github. While the guide was public, it was on a "sketchy" url and also was not editable by external contributors.
I'll update the README once this is merged and the README PR is also merged https://github.com/status-im/status-desktop/pull/17938
=> docs(building): add BUILDING guide

ui/app/AppLayouts/Chat/ChatLayout.qml, ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml, ui/app/mainui/AppMain.qml
Cherry-pick of https://github.com/status-im/status-desktop/pull/18009
Fixes #18004
Apply same procedure as https://github.com/status-im/status-desktop/pull/17767 but for edit.
I tried to see if I could use a common store function for that, but there is no easy way since it's two different function (create vs edit).
=> [CHERRY-PICK] fix(community): enable archive protocol when CHS is enabled during edit

storybook/pages/AboutViewPage.qml, ui/app/AppLayouts/Profile/views/AboutView.qml
- the link opens https://status.app/help in browser
- also fix the SB page (SystemUtils import conflict)
Fixes https://github.com/status-im/status-desktop/issues/17136
Settings/About
=> feat(About): add a link to Status Help site

src/app/modules/main/chat_section/active_item.nim, src/app/modules/main/chat_section/chat_content/io_interface.nim, src/app/modules/main/chat_section/chat_content/module.nim, src/app/modules/main/chat_section/io_interface.nim, src/app/modules/main/chat_section/item.nim, src/app/modules/main/chat_section/model.nim, src/app/modules/main/chat_section/module.nim, src/app/modules/main/chat_section/view.nim, src/app/modules/main/communities/module.nim, src/app/modules/main/module.nim, src/app/modules/shared_models/section_item.nim, src/app_service/service/chat/dto/chat.nim, test/nim/chat_section_model_test.nim, ui/app/AppLayouts/Shell/ShellAdaptor.qml, ui/app/mainui/AppMain.qml
> Note: review per commit
Fixes https://github.com/status-im/status-desktop/issues/18030
I moved the initialization of the chats to the Nim side. The personal section's chats get loaded on app start now. It will impact the login a little, but not much, since it only loads the model of chats, not messages.
For the image issue, the problem was that the ShellAdaptor didn't have the `chatType` as an `expectedRole`. Same for `onlineStatus`. I guess there is a bug in the SFPM where without the expectedRole, it's undefined at first, but then when you reload the page it works, the bug being that it somehow works on reload.
---
I also did a clean up of the chat Item and Model because I was annoyed that we always use Item.
Changes Item to ChatItem. initItem to initChatItem.
Plus some clean ups to …
=> Fix shell's chats not being loaded at start and missing image

storybook/pages/SwapInputPanelPage.qml, storybook/qmlTests/tests/tst_BuyReceiveBanner.qml, storybook/qmlTests/tests/tst_DappsComboBox.qml, storybook/qmlTests/tests/tst_LazyStackLayout.qml, storybook/qmlTests/tests/tst_OnboardingLayout.qml, storybook/qmlTests/tests/tst_SendRecipientInput.qml, storybook/qmlTests/tests/tst_SimpleSendRecipientInput.qml, storybook/qmlTests/tests/tst_SwapInputPanel.qml, ui/app/AppLayouts/Wallet/controls/AssetSelector.qml, ui/app/AppLayouts/Wallet/panels/SwapInputPanel.qml, ui/imports/shared/popups/send/controls/SendRecipientInput.qml
Fix Qml Tests on qt6.9.0 for
1. BuyReceiveBanner
2. DappsComboBox
3. SendRecipientInput
4. SimpleSendRecipientInput 5.SwapInputPanel
fixes #17705, #17707
=> fix(@desktop/wallet): Fix Qml Tests on qt6.9.0

ci/Jenkinsfile.combined
In the light of upcoming QT6 upgrade we've decided to stop building nix package in CI.
We will re think the nix builds after QT6 upgrade.
=> ci: remove nix job

storybook/cachecleaner.cpp, storybook/main.cpp, storybook/main.qml, storybook/src/Storybook/HotReloader.qml
- it's been a bit flimsy under Qt 6.9, and completely stopped working in 6.9.1
- simplify the QML logic for reloading the page: guard the reloading process with a simple boolean flag, instead of working directly on the view loader 
- improve the C++ cache cleaner with first manually running the GC, send a delayed event to all objects to do a cleanup/delete, and then finally clear the component cache (suggested by Pepe in
https://bugreports.qt.io/browse/QTBUG-135448?focusedCommentId=882898&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-882898)
Quoting:
> clearComponentCache() indeed does another GC run. However, both GC
runs are required here. The first one drops the component's JavaScript wrapper, calling deleteLater() on the component. Then the event …
=> fix(Storybook): unbreak (hot) reloading the pages

src/app/modules/main/chat_section/chat_content/users/view.nim, storybook/pages/MembersSelectorPage.qml, ui/app/AppLayouts/Chat/ChatLayout.qml, ui/app/AppLayouts/Chat/panels/InlineSelectorPanel.qml, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Chat/stores/UsersStore.qml, ui/app/AppLayouts/Chat/views/ChatColumnView.qml, ui/app/AppLayouts/Chat/views/ChatContentView.qml, ui/app/AppLayouts/Chat/views/ChatHeaderContentView.qml, ui/app/AppLayouts/Chat/views/ChatMessagesView.qml, ui/app/AppLayouts/Chat/views/ChatView.qml, ui/app/AppLayouts/Chat/views/CreateChatView.qml, ui/app/AppLayouts/Chat/views/MembersEditSelectorView.qml, ui/app/AppLayouts/Chat/views/private/MembersSelectorBase.qml, ui/app/mainui/AppMain.qml, ui/imports/shared/views/chat/MessageView.qml
Closes #18000
This refactor separates the `UsersStore` usage from low-level UI components by lifting its instantiation up to the `Chat.RootStore`. All components now use this single centralized instance, eliminating unnecessary store instantiations and improving state consistency and maintainability across the app.
No functional changes to user flows.
Updated all affected components and flows:
- User mentions list in the status chat input (for both standard and edit chat input modes)
- Right-side members/users column
- Group chat members management
Chat / Channels User Flows:
- Mentions list (chat input + edit chat input)
- Members list (right column)
- Group chat flow (list, create, add, remove..)  …
=> refactor(UsersStore): Decouple users store from UI components and centralize instantiation in `Chat.RootStore`

scripts/clean-git.sh
This is causing package version to include `-dirty` flag.
=> fix: do not remove vendor folder from submodules when cleaning

storybook/main.qml, ui/StatusQ/src/StatusQ/Core/StatusScrollView.qml, ui/StatusQ/src/objectproxymodel.cpp, ui/app/AppLayouts/Shell/ShellAdaptor.qml, ui/app/AppLayouts/Shell/ShellContainer.qml, ui/app/AppLayouts/Shell/ShellGrid.qml, ui/app/AppLayouts/Shell/delegates/ShellGridItem.qml, ui/app/mainui/AppMain.qml
- make the grid a ScrollView + Flow (instead of a GridView) so that we can stretch it horizontally from edge to edge, and also properly center it
- scale down the grid delegates and font sizes a bit when in narrow/portrait mode
- fix the "Reload" action in Shell's SB page
Fixes https://github.com/status-im/status-desktop/issues/18090
Shell
https://github.com/user-attachments/assets/fdba0d82-273c-45ee-a444-2658d6b5e194
=> fix(Shell): the shell doesn't fit on a mobile device

scripts/clean-git.sh
To fix errors like this in CI 
```
[2025-06-13T15:41:23.856Z] + make update
[2025-06-13T15:41:26.301Z] error: cannot rebase: You have unstaged changes.
[2025-06-13T15:41:26.301Z] error: Please commit or stash them.
[2025-06-13T15:41:26.301Z] fatal: Unable to rebase 'ede3886cc5507c2ba000ab9b057f198da03e8766' in 
submodule path 'mobile/vendors/openssl/gost-engine'
[2025-06-13T15:41:26.301Z] fatal: Failed to recurse into submodule path 'mobile/vendors/openssl'
[2025-06-13T15:41:26.301Z] error: cannot rebase: You have unstaged changes.
[2025-06-13T15:41:26.301Z] error: Please commit or stash them.
[2025-06-13T15:41:26.301Z] fatal: Unable to rebase 'ede3886cc5507c2ba000ab9b057f198da03e8766' in 
submodule path 'mobile/vendors/openssl/gost-engine'
[2025-06-13T15:41:26.301Z] fatal: Failed to …
```
=> fix: clean mobile vendor

storybook/pages/StatusChatInfoButtonPage.qml, ui/StatusQ/src/StatusQ/Controls/StatusChatInfoButton.qml
- the HoverHandler doesn't work as expected when it's placed inside `background` since it's now really behind the actual `contentItem`
- added a dedicated Storybook page
- some minor cleanups
Fixes #18136
StatusChatInfoButton
https://github.com/user-attachments/assets/cf13424b-c358-4a24-89e3-e807cca425ff
=> fix(StatusChatInfoButton): Wrong hover/cursor on Qt6

storybook/pages/ShellContainerPage.qml, storybook/src/Models/ChatsModel.qml, ui/app/AppLayouts/Shell/ShellContainer.qml, ui/app/AppLayouts/Shell/ShellDock.qml, ui/app/AppLayouts/Shell/ShellDockButton.qml, ui/app/AppLayouts/Shell/ShellGrid.qml, ui/app/AppLayouts/Shell/ShellSearchField.qml, ui/app/AppLayouts/Shell/ShellToolButton.qml, ui/app/AppLayouts/Shell/delegates/ShellGridChatItem.qml, ui/app/AppLayouts/Shell/delegates/ShellGridCommunityItem.qml, ui/app/AppLayouts/Shell/delegates/ShellGridDAppItem.qml, ui/app/AppLayouts/Shell/delegates/ShellGridItem.qml, ui/app/AppLayouts/Shell/delegates/ShellGridSettingsItem.qml, ui/app/AppLayouts/Shell/delegates/ShellGridWalletItem.qml, ui/app/mainui/AppMain.qml
- fix the colors/icons to use the system Theme
- add some dropshadows around the grid items and dock to distinguish it more from the background
- provides proper light/dark theme support
Fixes #18167
Shell
Light theme:
Dark theme:
=> fix(Shell): use system Theme colors and default icons

storybook/pages/StatusSectionLayoutPage.qml, ui/StatusQ/src/StatusQ/Layout/+qt6/StatusSectionLayoutLandscape.qml, ui/StatusQ/src/StatusQ/Layout/+qt6/StatusSectionLayoutPortrait.qml, ui/app/AppLayouts/Chat/views/CreateChatView.qml, ui/app/AppLayouts/Chat/views/MembersSelectorView.qml, ui/app/AppLayouts/Wallet/controls/AccountHeaderGradient.qml
closes #18171
Bring back the section toolbar in qt6. It needs to be proxied as well because we have only one instance of the toolbar actions defined by the section user.
+ fix the header background in wallet. It seems the LayoutItemProxy cannot work well with a Loader. Not sure if it's a bug in Qt or not.
+ enable the back button navigation for the right side panel
+ fix a bug where the ens name wasn't resolved in the create chat view
chat toolbar
community toolbar
https://github.com/user-attachments/assets/7d90bc21-e691-437c-bcd0-037b4fee82a7
=> Fix(StatusSectionLayout) Bring back the section toolbar in qt6

ui/imports/shared/popups/addaccount/panels/DerivationPathSection.qml
fixes #18156
Adds width to loader instead of sourceComponent
Edit Account flow
=> fix(@desktop/wallet): Derivation path is broken for imported from seed account

src/app/modules/main/chat_search_item.nim, src/app/modules/main/chat_search_model.nim, src/app/modules/main/module.nim, storybook/pages/ShellContainerPage.qml, storybook/src/Models/ChatsSearchModel.qml, storybook/src/Models/qmldir, ui/StatusQ/src/StatusQ/Core/Theme/Theme.qml, ui/app/AppLayouts/Shell/ShellAdaptor.qml, ui/app/AppLayouts/Shell/ShellDock.qml, ui/app/AppLayouts/Shell/ShellDockButton.qml, ui/app/AppLayouts/Shell/ShellGrid.qml, ui/app/AppLayouts/Shell/delegates/ShellGridChatItem.qml, ui/app/mainui/AppMain.qml
- the community channels are displayed by default only when searching (in order not to pollute the grid with too many items)
- extend the chat_search_model with `chatType` field to be able to filter out the otherwise duplicate chat items (which we already have in the grid with much more detailed info)
- reuse the same grid chat delegate and use the `lastMessageText` to identify the community name
- extend/adjust the Storybook page with the respective option
Fixes #18137
Shell
https://github.com/user-attachments/assets/4733329b-ec63-4bf8-abc4-283756120bb6
=> feat(Shell): Add support for community channels

.github/pull_request_template.md
The links to the architecture guideline still pointed to CONTRIBUTING. Also I added a link to the architecture.
I removed the part about matching designs because no one does it. I replaced by  a stronger emphasis on having a video, because that's the best.
Finally, I removed the checkboxes about QA testing as every dev should test their work thoroughly themselves.
=> docs(pr): update PR template to fix links and adapt to new flows

storybook/pages/OverviewSettingsChartPage.qml, storybook/pages/OverviewSettingsFooterPage.qml, storybook/pages/OverviewSettingsPanelPage.qml, ui/app/AppLayouts/Communities/panels/OverviewSettingsFooter.qml, ui/app/AppLayouts/Communities/panels/OverviewSettingsPanel.qml, ui/app/AppLayouts/Communities/views/CommunitySettingsView.qml, ui/imports/utils/Constants.qml
separate commits fixing:
- Hide Control node transfer (Admin screen) on mobile (Fixes #18175)
- Hide Community History Service switch on mobile (Fixes #18177)
- improve the respective SB pages
Community Admin
https://github.com/user-attachments/assets/e7c7ba13-ecad-4e44-98ba-bddaa162d6f1
=> fix(CommunityAdmin): hide Community History and Node transfer on mobile

src/app/global/utils.nim, src/app_service/service/chat/async_tasks.nim, src/app_service/service/chat/service.nim, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/imports/utils/Utils.qml
Cherry-pick of https://github.com/status-im/status-desktop/pull/18182
Fixes #18181
There were two problems
First, we added a path formatting function in the QML that just deleted the image data. Making it so that we sent nothing. I fixed that and also improved the error management so that when we send nothing, we show an error to the user instead of leaving them stuck.
Second, we removed the resize function that also put the image data in a temp file. So now the status-go code couldn't handle the data images. I fixed that by re-adding part of the resize function that puts the data inside a team file.
=> [CHERRY-PICK] fix(images): fix sending pasted images

storybook/pages/ProfileShowcasePanelPage.qml, ui/StatusQ/src/StatusQ/Controls/StatusComboBox.qml, ui/StatusQ/src/StatusQ/Core/Theme/Theme.qml, ui/StatusQ/src/StatusQ/Popups/StatusMenuHeadline.qml, ui/StatusQ/src/StatusQ/Popups/StatusMenuItem.qml, ui/app/AppLayouts/Wallet/controls/FilterComboBox.qml, ui/app/AppLayouts/Wallet/controls/ManageTokensCommunityTag.qml, ui/app/AppLayouts/Wallet/controls/MaxSendButton.qml, ui/app/AppLayouts/Wallet/controls/SortOrderComboBox.qml, ui/imports/shared/controls/chat/LinkPreviewSettingsCard.qml, ui/imports/shared/controls/chat/LinkPreviewSettingsCardMenu.qml
Bunch of small fixes for various UI issues in popup menus when running under Qt6; see the individual commits for details
Fixes #18216
StatusMenuItem
Menuitem checkmark:
Destructive/danger menuitem:
Group icon:
Max send button:
=> fix: various small UI fixes for popup menus under Qt6

ui/StatusQ/src/StatusQ/Layout/+qt6/StatusSectionLayoutLandscape.qml, ui/StatusQ/src/StatusQ/Layout/+qt6/StatusSectionLayoutPortrait.qml, ui/app/AppLayouts/Profile/ProfileLayout.qml
- the section layout under Qt6 has a slightly different API (Item vs. Component), so use a Loader for the `rightPanel`
- fix the docu
Fixes #18250
Settings/Profile
=> fix(ProfileLayout): fix side-by-side profile preview on Qt6

ui/StatusQ/src/StatusQ/Core/Theme/Theme.qml, ui/StatusQ/src/StatusQ/Layout/+qt6/StatusSectionLayout.qml, ui/app/AppLayouts/Onboarding2/pages/+qt6/WelcomePage.qml, ui/main.qml
Also fixes some small issues on welcome page, have tested on macOS desktop, android tablet and mobile
fixes #18236
Overall screen size
Welcome Page
**Desktop macOS:**
**Android Tablet:**
**Android Mobile:**
- 
-
=> fix(@desktop/wallet): Adding Bindings to set min width & height only for desktop

ui/app/mainui/Handlers/SendModalHandler.qml
Corresponding `status-go` changes:
- https://github.com/status-im/status-go/pull/6705
This PR integrates a fully gasless Status chain.
0 ETH tx from 0 balance account:
- https://sepoliascan.status.network/tx/0x2c651a91301094acea596b581d1c901f40c63c45044d6b091f1198889b1c5278
Token minted and transferred tx:
- https://sepoliascan.status.network/tx/0xf9af84ad53d89bf9293140e8d82285ebb80fdafec119b0a32267a74fafcc3b1d
=> fix(wallet): enhance route fetching and fee estimation logic for gasless Status chain

src/app/global/local_app_settings.nim, src/nim_status_client.nim, storybook/main.qml, ui/StatusQ/src/StatusQ/Core/Theme/Theme.qml, ui/app/AppLayouts/Profile/ProfileLayout.qml, ui/app/AppLayouts/Profile/views/AppearanceView.qml, ui/app/mainui/AppMain.qml, ui/main.qml
- under Qt6, we can now listen to the styleHints color scheme property changes and react accordingly
- remove the hack of detecting the current dark theme by checking the hsl lightness of the window; also removes propagating the systemPalette object thru the hierarchy
- as a result, we can get rid of the dedicated C++ OSThemeEvent
Fixes #17764
Fixes #14856
Needs https://github.com/status-im/dotherside/pull/95
Needs https://github.com/status-im/nimqml/pull/67
App/Settings
https://github.com/user-attachments/assets/98803fca-6389-4c08-8982-f0e49cd59eca
Storybook:
Settings/Appearance/System should follow system light/dark theme changes
=> fix: properly handle light/dark theme switch

ui/StatusQ/src/StatusQ/Popups/Dialog/StatusDialog.qml, ui/app/AppLayouts/Wallet/WalletLayout.qml, ui/app/AppLayouts/Wallet/popups/buy/BuyCryptoModal.qml, ui/app/AppLayouts/Wallet/popups/simpleSend/SimpleSendModal.qml, ui/imports/shared/popups/send/views/AmountToSend.qml
fix(@desktop/wallet): Fix Modal heights on mobile portrait, doesn't effect anything on desktop or landscape.
Add number only keyboard where amounts are to be entered
AddAcountModal
SimpleSend
Add saved address
SwapModal
- 
-
=> fix(@desktop/wallet): Fix Modal heights on mobile portrait

test/e2e/gui/components/change_password_popup.py, test/e2e/gui/main_window.py, test/e2e/gui/objects_map/home_names.py, test/e2e/gui/objects_map/names.py, test/e2e/gui/screens/home.py, test/e2e/tests/crtitical_tests_prs/test_settings_password_change_password.py
Fixes https://github.com/status-im/status-desktop/issues/18352
- fixed change password test and enabled it for nightly (for now)
- open profile from home screen too to cover it more
- deleted not needed step to open wallet from profile creation logic
=> chore(@e2e): bring back change password test

BUILDING.md, ci/Dockerfile, ci/Jenkinsfile.linux, ci/Jenkinsfile.macos, ci/Jenkinsfile.tests-nim, ci/Jenkinsfile.windows, scripts/macos_build_setup.sh, scripts/ubuntu_build_setup.sh, scripts/windows_build_setup.ps1
- update status-go to point to changes in https://github.com/status-im/status-go/pull/6678
- update build scripts for windows,linux and desktop for go 1.23
- use docker image with go 1.23
=> ci: upgrade go to 1.23

ui/app/mainui/AppMain.qml
- fixes the StatusEmojiPopup searching for emojis with a skin color variant
- has to be a string (as before), otherwise it gets prepended with the `#` character and twemoji won't find the SVG file
Fixes #18362
StatusEmojiPopup
Low
- search e.g. for "man_white_haired" in the emoji popup
Low
=> fix(StatusEmojiPopup): fix the `skinColor` emoji setting

storybook/pages/ProfileShowcaseInfoPopupPage.qml, storybook/pages/StatusDialogPage.qml, storybook/qmlTests/tests/tst_StatusDialog.qml, ui/StatusQ/src/StatusQ/Core/Theme/Theme.qml, ui/StatusQ/src/StatusQ/Popups/Dialog/StatusDialog.qml
- need to delay constructing the windowWidth/Height bindings for after the `contentItem` becomes non-null
- add a QML testcase for the centered on desktop and bottomSheet on mobile behavior
- fixes some popups having wrong position and size
Fixes #18356
Popups
https://github.com/user-attachments/assets/08d2e34c-7263-4adc-895a-dfbf2f0eae7e
https://github.com/user-attachments/assets/083ac759-71c7-4989-8d6e-2719ba54fb3d
SB with correct behavior and passing tests:
low
Open some popups, should be either centered, or appear as a bottom edge sheet in size constrained scenarios
Low
=> fix(StatusDialog): fix evaluating the window width/height

ci/Jenkinsfile.tests-e2e
Fixes https://github.com/status-im/status-desktop/issues/18378
It should be easier now to get to the allure report link, it is now visible in the `Jenkins Builds` table:
The link in the last column takes you to the Allure report.
=> ci: add tests/e2e to GitHub jenkins jobs table

BUILDING.md, Makefile, package-lock.json, package.json
1. Update building instructions for Qt 6
2. Use `fileicon` from `homebrew` instead of `npm`. 
Ideally we should also use [shell version create-dmg](https://github.com/create-dmg/create-dmg) instead of [nodejs version create-dmg](https://github.com/status-im/create-dmg), then we can remove NPM and Yarn dependencies. 
3. Added instruction to run `make status-go-deps`
4. Added tips to skip some steps only required for DMG building
=> chore: simplify macos building && update building docs to Qt 6

src/app/modules/main/chat_section/controller.nim, src/app/modules/main/chat_section/io_interface.nim, src/app/modules/main/chat_section/model.nim, src/app/modules/main/chat_section/module.nim, src/app/modules/main/module.nim, src/app_service/service/community/service.nim, ui/app/mainui/AppMain.qml
Fixes #18361 and #14431
Lazy loads the chat section's children modules so that only when a chat is activated are the modules loaded (content, users, messages and chat input). This improves performance and memory a little bit.
Also fixes other performance issues in the chat_section for communities, like useless calls to the service, useless calls to update the model (for categories) and also useless calls to update the badge. All of those slowed down the load. Most of those were fixed by simply accessing the `community` object already available.
I added those additional fixes because just lazy loading didn't give much of an improvement.
chat_section module (mostly communities)
OLD …
=> perf(chat_section): lazy load chat modules and improve performance

ui/app/AppLayouts/Wallet/panels/BuyReceiveBanner.qml
fixes #18197
Thus simple PR simply uses the same text as defined in the Mobile designs which makes it look good even on mobile devices.
Wallet CTA
Desktop:
iOS:
- 
-
=> fix(@desktop/wallet): [Mobile] CTA for “Ways to Buy / Receive Assets” Is Clipped on Mobile

src/app/modules/main/profile_section/devices/controller.nim, src/app/modules/main/profile_section/devices/io_interface.nim, src/app/modules/main/profile_section/devices/model.nim, src/app/modules/main/profile_section/devices/module.nim, src/app/modules/main/profile_section/devices/view.nim, src/app_service/service/devices/service.nim, src/backend/installations.nim, ui/StatusQ/src/StatusQ/Components/StatusSyncDeviceDelegate.qml, ui/app/AppLayouts/Profile/stores/DevicesStore.qml, ui/app/AppLayouts/Profile/views/SyncingView.qml
Fixes #18399
The backend functionality already existed, we just needed to hook it. When Unpair is clicked, we no longer send messages to that installation. when Pair is clicked, we send them again
Syncing View and Devices module/service
[pairing-and-unpairing.webm](https://github.com/user-attachments/assets/d1346ad3-fab4-4358-bc85-132da832a783)
Enables the user to pair and unpair a device form the Syncing menu (if the device was already paired before)
- Pair two devices using the normal onboarding method
- Go to settings > Syncing
- Click Unpair and confirm
- See that 1-1 messages no longer show for yourself
None. It's a new feature that doesn't touch other modules
=> feat(syncing): enable pairing and unpairing already paired devices

test/e2e/gui/main_window.py, test/e2e/gui/objects_map/settings_names.py, test/e2e/gui/screens/settings.py, test/e2e/scripts/utils/decorators.py, test/e2e/scripts/utils/generators.py, test/e2e/tests/crtitical_tests_prs/test_create_edit_join_community_pin_unpin_message.py, test/e2e/tests/transactions_tests/test_mint_owner_and_tokenmaster_tokens.py, test/e2e/tests/transactions_tests/test_wallet_send_eth.py, ui/app/AppLayouts/Profile/ProfileLayout.qml
- improve the logic of retry decorator. Fixes https://github.com/status-im/status-desktop/issues/18413
- move the network selection to params of the tests, so it is more clear which network is selected for certain test
=> chore(@e2e): retry decorator logic

ci/Jenkinsfile.tests-e2e
Was added and not removed during work on parallel Qt5 and Qt6 support.
=> chore(ci): remove unnecessary label for e2e tests

package-lock.json, package.json, scripts/macos_build_setup.sh
End-of-Life for Node.js 18 was on 30th of April, and the recommended version to ugprade to is 22 according to this article: https://nodejs.org/en/blog/announcements/node-18-eol-support
This upgrade should have no impact on usage of `create-dmg` tool.
=> chore(ci): upgrade Node.js from 18 to 22

mobile/ios/Info.plist, mobile/scripts/buildApp.sh, mobile/scripts/buildStatusGo.sh, mobile/scripts/ios/run.sh, mobile/wrapperApp/Status-tablet.pro, ui/StatusQ/CMakeLists.txt, ui/StatusQ/src/StatusQ/Components/StatusImageCropPanel.qml, ui/StatusQ/src/StatusQ/Core/Utils/Utils.qml, ui/StatusQ/src/StatusQ/Popups/Dialog/StatusFileDialog.qml, ui/StatusQ/src/ios_utils.h, ui/StatusQ/src/ios_utils.mm, ui/StatusQ/src/systemutilsinternal.cpp, ui/StatusQ/src/urlutils.cpp, ui/app/mainui/Popups.qml
closes: #18077 
Adding StatusQ platform specific flows for saving images to photo album and for resolving iOS images.
This flow is supported by `ios_utils.mm`
- Fixing the IOS build. Apparently we can't register a signature for im.status.status-tablet more than once. I've updated the bundleId to append the username in the bundleId for dev purposes.
- Fixing status-go build script. It wasn't stopping on failure. The `go run` had errors ignored by the build system
Send image
Download image
Changing profile picture
=> feat(IOSFileAccess): Enable IOS file access for images

src/app_service/service/accounts/service.nim
fixes #18154
set wake node to light client by default
- 
-
=> fix(@desktop/wallet): Make sure the mobile builds are running in light mode

ui/StatusQ/src/StatusQ/Components/StatusMessage.qml, ui/StatusQ/src/StatusQ/Components/StatusUserImage.qml
Fixing profile image click in messenger following the Qt6 migration.
https://github.com/user-attachments/assets/cbf8cc7a-4b8b-447d-8fc0-69af23cc7d4b
=> fix: Clicking profile image in the chat list won't trigger any action

src/app/global/utils.nim, src/app/modules/main/communities/tokens/module.nim, src/app/modules/main/profile_section/profile/module.nim, src/app/modules/main/profile_section/sync/module.nim, src/app_service/common/utils.nim, src/app_service/service/chat/service.nim, src/app_service/service/community/service.nim, src/app_service/service/settings/dto/settings.nim, src/app_service/service/settings/service.nim, src/backend/settings.nim, src/constants.nim, storybook/pages/SyncingViewPage.qml, ui/app/AppLayouts/Profile/ProfileLayout.qml, ui/app/AppLayouts/Profile/stores/DevicesStore.qml, ui/app/AppLayouts/Profile/views/SyncingView.qml
Fixes #18128
Adds a SettingsLine above the "Backup Data" and "Import Backup" buttons that shows what is the current path for the backup and let's the user change that path.
Status-go PR: https://github.com/status-im/status-go/pull/6699
- settings service
- SyncingView
- Renamed `formatImagePath` to `fromPathUri` because it's not just useful for images
[change-setting-path.webm](https://github.com/user-attachments/assets/d826c2dc-f4a9-4fb6-b892-cbf111c30c75)
Let's the user know what the path is and change it if needed
- Have the feature flags enabled (in status-go remove the commented option in `service.ext` and in Desktop `export …
=> feat(backup): add SettingsLine in SyncingView to change backup path

src/app/modules/main/communities/module.nim, src/app/modules/main/communities/view.nim, src/app/modules/main/module.nim, src/app/modules/shared_models/member_model.nim, src/app/modules/shared_models/model_utils.nim, src/app/modules/shared_models/section_item.nim, src/app/modules/shared_models/section_model.nim, storybook/pages/InviteFriendsToCommunityPopupPage.qml, storybook/pages/ProfilePopupInviteFriendsPanelPage.qml, ui/app/AppLayouts/Communities/panels/ProfilePopupInviteFriendsPanel.qml, ui/app/AppLayouts/Communities/popups/InviteFriendsToCommunityPopup.qml, ui/app/AppLayouts/stores/RootStore.qml, ui/app/mainui/Popups.qml, ui/imports/shared/views/ExistingContacts.qml
Two fixes in one.
Fixes https://github.com/status-im/status-desktop/issues/18412
The problem was introduced when I implemented the lazy loading for the members in the section model. Turns out even if that member list is never shown to members, we do use it for some checks, like the banned one.
I fixed by passing the banned value to the sectionItem directly. Relying on the members model was a crutch.
Then also fixes a bug with the Invite friend to community popup that no longer hid contacts that are already member of the community.
We relied on the main section's members model to see if a contact was member of the community, but instead we can use the chat section members model
Mostly Main section's Model and Items
My PR is consistent with this document: [QML Architecture …
=> Fix banner member screen and invite friends popup filtering

src/app/modules/main/wallet_section/activity/collectibles_model.nim, src/app/modules/main/wallet_section/activity/entry.nim, src/app/modules/main/wallet_section/activity/utils.nim, src/app_service/common/conversion.nim, src/app_service/common/json_utils.nim, src/app_service/common/utils.nim, src/app_service/service/activity_center/service.nim, src/app_service/service/ens/service.nim, src/app_service/service/ens/utils.nim, src/app_service/service/eth/dto/coder.nim, src/app_service/service/eth/dto/method_dto.nim, src/app_service/service/eth/dto/transaction.nim, src/app_service/service/eth/utils.nim, src/app_service/service/stickers/service.nim, src/app_service/service/token/service.nim, src/app_service/service/transaction/dto.nim, src/app_service/service/transaction/dtoV2.nim, src/app_service/service/wallet_account/service.nim, src/backend/activity.nim, src/backend/community_tokens_types.nim
nim-eth and nim-web3 underwent a significant refactor a few years ago while status desktop is still stuck on the really really old approach where working with these types in nim clunky and inconvenient.
In the new version, the same primitive types are used across eth/web3 and
[json_serialization](https://status-im.github.io/nim-json-serialization/getting_started.html) is consistently used to encode/decode json.
Eventually, it makes sense that status-desktop also uses this common infrastructure instead of rolling its own, but here's a baby step that upgrades the relevant libraries to more recent versions.
The changes are introduced _without_ refactoring the code to take advantage of the new types, ie this is the minimal changeset for making things work - there are many ways in which the …
=> web3: bump

storybook/CMakeLists.txt
Fixing regression introduced in https://github.com/status-im/status-desktop/pull/18431, affecting Storybook on mac. 
Storybook's cmake config
=> Storybook: cmake config for mac fixed

ui/imports/shared/panels/EnterSeedPhrase.qml
fixes #18140
Check if word already entered and ignoring adding new word and moving focus to next text input
EnterSeedPhrase screen
https://github.com/user-attachments/assets/f5615ce1-5823-4fbc-a3a6-e7459d641bf9
- 
-
=> fix(@desktop/wallet):iOS:: Cannot edit seed phrase words after typing

src/app_service/service/accounts/service.nim, src/backend/accounts.nim, src/backend/core.nim, src/backend/general.nim, test/e2e/gui/objects_map/names.py, test/e2e/gui/screens/settings_wallet.py
- https://github.com/status-im/status-go/pull/6732
Corresponding `nim-status-go` PR:
- https://github.com/status-im/nim-status-go/pull/33
Changes:
- Removed keyStoreDir property and its associated methods from the accounts service.
- Updated `verifyAccountPassword` method, no longer require keyStoreDir.
- Cleaned up login and account restoration processes by removing unnecessary keystore migration logic.
=> refactor(accounts): remove keystore dir handling

ui/StatusQ/include/StatusQ/systemutilsinternal.h, ui/StatusQ/src/StatusQ/Layout/StatusSectionLayoutPortrait.qml, ui/StatusQ/src/systemutilsinternal.cpp, ui/main.qml
fixes #18168
Adds back behaviour for android
Back button handling for android
https://github.com/user-attachments/assets/22196b0b-b31c-4d82-ba60-e945849ce18b
https://github.com/user-attachments/assets/74838f3e-9373-4951-ad19-8fed0f3b5c36
- 
-
=> fix(@desktop/wallet): Back button on Android will kill the app

src/app/modules/main/profile_section/sync/module.nim, src/app/modules/main/profile_section/sync/view.nim, src/app/modules/onboarding/controller.nim, src/app/modules/onboarding/io_interface.nim, src/app/modules/onboarding/module.nim, src/app/modules/onboarding/post_onboarding/local_backup_task.nim, src/app/modules/onboarding/post_onboarding/task.nim, src/app_service/service/general/service.nim, ui/app/AppLayouts/Profile/stores/DevicesStore.qml, ui/app/mainui/AppMain.qml, ui/app/mainui/ToastsManager.qml
Based on top of https://github.com/status-im/status-desktop/pull/18434
Fixes https://github.com/status-im/status-desktop/issues/18359
When the user provides a file path to the backup, we call the async function to perform the backup after the signup.
Also adds a toast message when it completes.
Onboarding and backup
In this video, I disabled the Waku backup to make sure the local one worked
[local-backup-onboarding.webm](https://github.com/user-attachments/assets/f2906d1f-b6a5-4b6f-982f-a737b909805d)
Makes the local backup from the onboarding work
- Enable the feature flag `export FLAG_LOCAL_BACKUP_ENABLED=1`
- Have an other account and get the mnemonic and do a local backup on it …
=> Hook backup file form onboarding to backup functions

src/app/boot/app_controller.nim, src/app/core/signals/remote_signals/messages.nim, src/app/modules/main/profile_section/profile/controller.nim, src/app/modules/onboarding/module.nim, src/app_service/service/accounts/dto/accounts.nim, src/app_service/service/accounts/service.nim, src/app_service/service/contacts/dto/contacts.nim, src/app_service/service/general/service.nim, src/app_service/service/profile/service.nim, src/backend/general.nim
Fixes https://github.com/status-im/status-desktop/issues/18428
status-go PR: https://github.com/status-im/status-go/pull/6776
Changes the use of the base 64 images for Accounts to the local URL one.
I also cleaned up the code a lot. We used two different types of `Image` dtos, but they were the same one on the status-go side, so I re-aligned them.
Account images
[account-image.webm](https://github.com/user-attachments/assets/aa7955ce-c22c-496c-9f1a-bd797cab24ed)
No UX impact
Better memory usage and performance
- Have accounts with profile images
Mid risk. If something is not set correctly, it's possible that the user's own image doesn't show
=> perf: stop using data images for accounts

Makefile, mobile/scripts/buildNimStatusClient.sh
Iterates: [#18454](https://github.com/status-im/status-desktop/issues/18454)
The goal is to reduce the app size to less than 100mb.
Starting with nim_status_client.so at 14.8MB
--opt:size -> 14.3
-d:danger -> 12.9
-flto -> 2.1MB
Mobile builds
=> Chore(android): reduce app size - nim_status_client lib

src/app/modules/main/app_search/controller.nim, src/app/modules/main/app_search/io_interface.nim, src/app/modules/main/app_search/models/chat_search_item.nim, src/app/modules/main/app_search/models/chat_search_model.nim, src/app/modules/main/app_search/models/location_menu_item.nim, src/app/modules/main/app_search/module.nim, src/app/modules/main/chat_section/controller.nim, src/app/modules/main/chat_section/module.nim, src/app_service/service/message/service.nim, ui/app/AppLayouts/HomePage/HomePageAdaptor.qml, ui/app/AppLayouts/HomePage/HomePageGrid.qml, ui/app/AppLayouts/HomePage/delegates/HomePageGridChatItem.qml
Fixes #18298
ChatSearchModel
HomePage
[lastMessage.webm](https://github.com/user-attachments/assets/e37f433e-4834-4b9f-a09b-eda0e44bf3f6)
Adds the last message to community chats in the Home page
- Be in a community
- Send messages in the chats
- check the Home page
Low
=> feat(home): add lastMessage to chatSearchModel to show in the HomePage

test/e2e/gui/components/settings/unpair_confirmation_popup.py, test/e2e/gui/objects_map/names.py, test/e2e/gui/objects_map/onboarding_names.py, test/e2e/gui/objects_map/settings_names.py, test/e2e/gui/screens/home.py, test/e2e/gui/screens/onboarding.py, test/e2e/gui/screens/settings_messaging.py, test/e2e/gui/screens/settings_syncing.py, test/e2e/tests/crtitical_tests_prs/test_messaging_group_chat.py, test/e2e/tests/crtitical_tests_prs/test_onboarding_sync_with_code.py, test/e2e/tests/onboarding/test_onboarding_syncing.py, ui/StatusQ/src/StatusQ/Components/StatusSyncDeviceDelegate.qml
Fixes #18415 
First approach to use display name changes to test it was not successful because of some issues potentially caused by rapid display name changes. 
Now the test is syncing 2 desktop apps via onboarding, then on first app, changes value of `Allow contact requests` toggle -> on second instance checks that the toggle becomes off to (devices) are paired. After that, test unpairs devices and enables the toggle again -> on second instance the toggle should remain the same.
The timeframe for the changes to be synced is 15 seconds (or earlier). If that would not be enough (test starts failing because of this thing), i will change that to different value, however the expectation of the changes to be synced within 5 seconds.
=> Tests: add unpair to sync devices test

ci/Dockerfile, ci/Jenkinsfile.linux, ci/Jenkinsfile.tests-nim, scripts/ubuntu_build_setup.sh, storybook/CMakeLists.txt, storybook/README.md, storybook/main.cpp, storybook/main.qml, storybook/qmlTests/main.cpp, storybook/resources.qrc, storybook/validator_main.cpp
This PR introduces new approach regarding loading pages and related source code. Instead of loading files from file system directly, Storybook runs HTTP server hosting qml files. It gives ability of hot-reloading on potentially any device with network access.
The approach used so far (direct file system reading) stays in place and remains the default mode for desktop. The new mode is default on Android.
Related PR in `QmlStorybook` repository: https://github.com/status-im/QmlStorybook/pull/1
To run Storybook in `remote` mode, use `--mode remote` argument.
> [!WARNING]  
> ~~Do not merge until the `QmlStorybook` pr is merged and commit sha updated in the cmake config~~
- connect device
- run `adb reverse tcp:8080 tcp:8080` in order to set up reverse proxy
- run desktop instance in remote …
=> Server-based storybook

storybook/pages/ImportCommunityPopupPage.qml, ui/StatusQ/src/StatusQ/Controls/StatusTextArea.qml, ui/imports/shared/popups/ImportCommunityPopup.qml
- no need to set width or anchors to the StatusTextArea when wrapped in a scroll view
- fix the scroll views sizing
- adjust the info text a bit to cover to possible types of input
- some minor fixes to the SB page and the text area component itself
Fixes #18502
ImportCommunityPopup
https://github.com/user-attachments/assets/245fb247-6b6d-4876-808e-318ad911b3ac
- user can enter key longer than a few characters (w/o wrapping)
- try to input some key/link into the text area
- low
=> fix(ImportCommunityPopup): The input is just 5 characters wide

ci/Dockerfile, ci/Jenkinsfile.linux, ci/Jenkinsfile.macos, scripts/init_app_dir.sh, scripts/version.sh
- Adds 2 CI jobs that build `status-desktop` with `nwaku` enabled status-go.
- These jobs will be optional.
=> ci: generate experimental nwaku builds

src/app/modules/main/app_search/controller.nim, src/app/modules/main/app_search/module.nim, src/app/modules/main/chat_section/chat_content/users/controller.nim, src/app/modules/main/chat_section/chat_content/users/module.nim, src/app/modules/main/controller.nim, src/app/modules/main/module.nim, src/app_service/service/contacts/service.nim
Fixes #18548
The problem was that we introduced a mechanism to speed up login by skipping backend calls on contacts on app start. This was fine before because we also relied on the service to get the contact details. However, we now use the contacts model instead, which is faster. So that was empty. Plus, we were storing an empty alias in the contacts table, so the contact never populated.
Now, the fix is simple, we stop using `skipBackendCalls`, because we already stopped loading any member lists on app start, so we no longer need that. Also, we update the contacts model when we save a new contact, making sure there is an alias for them.
Contacts service …
=> fix(contacts): fix unknown contacts not having an alias

ui/StatusQ/src/StatusQ/Core/Utils/Emoji.qml
- fixes the wrong path in `Emoji.svgImage()` by removing the extra `svg/` in the path
Fixes #18575
StatusInputListPopup,Emoji
Emojis work in the suggestions popup in chat
Type a message, start typing an emoji short code, ie. `:hea...`
low
=> fix(Emoji): unbreak the StatusInputListPopup emoji images

ui/StatusQ/src/StatusQ/Core/Utils/Emoji.qml
- fixes the wrong path in `Emoji.svgImage` by removing the extra `svg/` in the path
Fixes #18575
cherry-pick of https://github.com/status-im/status-desktop/pull/18576
=> [CHERRY-PICK] fix(Emoji): unbreak the StatusInputListPopup emoji images

src/app/modules/main/app_search/controller.nim, src/app/modules/main/app_search/module.nim, src/app/modules/main/chat_section/chat_content/users/controller.nim, src/app/modules/main/chat_section/chat_content/users/module.nim, src/app/modules/main/controller.nim, src/app/modules/main/module.nim, src/app_service/service/contacts/service.nim
Cherry-pick of https://github.com/status-im/status-desktop/pull/18560
Fixes #18548
The problem was that we introduced a mechanism to speed up login by skipping backend calls on contacts on app start. This was fine before because we also relied on the service to get the contact details. However, we now use the contacts model instead, which is faster. So that was empty. Plus, we were storing an empty alias in the contacts table, so the contact never populated.
Now, the fix is simple, we stop using `skipBackendCalls`, because we already stopped loading any member lists on app start, so we no longer need that. Also, we update the contacts model when we save a new contact, making sure there is an alias for them.
=> [CHERRY_PICK] fix(contacts): fix unknown contacts not having an alias

scripts/clean-git.sh, ui/app/mainui/AppMain.qml, ui/imports/shared/panels/ModuleWarning.qml, ui/main.qml
This PR fixes two issues regarding banners on mac:
- action buttons are not clickable
- icon / text overlapping with os window buttons (min/max/close)
Closes: #18555 
`main`, `AppMain`, `ModuleWarning`
=> Fix banners on Mac

ui/imports/shared/views/HistoryView.qml
Fixes https://github.com/status-im/status-desktop/issues/18658
Fixes context menu for activity entries in Activity tab
The console indicated
```
WRN 2025-08-21 13:42:03.955Z qt warning                                 topics="qt" tid=333491990 text="qrc:/imports/shared/views/HistoryView.qml:359:17 Parameter \"mouse\" is not declared. Injection of parameters into signal handlers is deprecated. Use JavaScript functions with formal parameters instead." category=qt.qml.context file=:0
WRN 2025-08-21 13:42:03.961Z qt warning                                 topics="qt" tid=333491990 text="\"Could not convert argument 0 from QQuickMouseEvent(0x3eb59d968) to QQuickItem*\"" category=default file=:0
WRN 2025-08-21 13:42:03.961Z qt warning                                 topics="qt" tid=333491990 …
```
=> fix(@desktop/wallet): properly set up activity entry context menu

src/app/global/utils.nim
Fixes #18624
The URI given for base64 images changed when we upgraded to QT6. Hopefully this new Regex is more permissive and shouldn't break on new changes
Utils function
[sendng-screenshots.webm](https://github.com/user-attachments/assets/6c76a73d-70f1-4064-a796-f83c8a9c4a50)
Fixes the issue
- Send screenshots or copied images (CTRL+V)
- 
Low
=> fix(images): sending screenshots by changing the regex to detect base64

src/app/global/utils.nim
Cherry-pick of https://github.com/status-im/status-desktop/pull/18671
Fixes #18624
The URI given for base64 images changed when we upgraded to QT6. Hopefully this new Regex is more permissive and shouldn't break on new changes
=> [CHERR-PICK] fix(images): sending screenshots by changing the regex to detect base64

src/app/modules/main/module.nim, test/e2e/gui/main_window.py, test/e2e/helpers/settings_helper.py, test/e2e/tests/communities/test_communities_categories.py, test/e2e/tests/communities/test_communities_channels.py, test/e2e/tests/crtitical_tests_prs/test_add_edit_restart_add_delete_generated_account.py, test/e2e/tests/crtitical_tests_prs/test_onboarding_import_seed.py, test/e2e/tests/crtitical_tests_prs/test_onboarding_sync_with_code.py, test/e2e/tests/crtitical_tests_prs/test_settings_password_change_password.py, test/e2e/tests/wallet_main_screen/wallet_load_time/test_wallet_loading_time.py
- treat the HomePage as any other section
Fixes #18664
AppMain
https://github.com/user-attachments/assets/bda4de84-49b6-49e3-9e71-d1cb878fa1d5
No more special treatment of the HomePage, last active section will always be the one we start with the next time
- navigate to some section
- quit & restart the app
- the app should start with the last active section
- low
=> chore: don't enforce the HomePage as the start section

src/app/modules/onboarding/module.nim, storybook/qmlTests/tests/tst_OnboardingLayout.qml, ui/app/AppLayouts/Onboarding2/pages/SyncProgressPage.qml
Fixes https://github.com/status-im/status-desktop/issues/18633
We weren't checking to see if the pairing failed, only that a paring happened.
I think the regression happened during the refactor. That code was probably in a code path that could only be reached by restoring using a mnemonic and now we only have one "ending" path (simpler).
Also removes "Log in anyway" button as it's not part of the design and it doesn't work. What would "logging in anyway" do if the pairing failed? We do not have a private key at that point.
Onboarding module and Syncing Page
No AC notif when it's a success:
[no-qac-notif-when-success.webm](https://github.com/user-attachments/assets/c0c05048-2e6d-44ed …
=> Fix Syncing AC notification showing even when pairing worked + remove useless button

storybook/pages/CreateCommunityPopupPage.qml, ui/StatusQ/src/StatusQ/Components/StatusImageCropPanel.qml, ui/StatusQ/src/StatusQ/Controls/StatusImageCrop.qml, ui/StatusQ/src/StatusQ/Controls/StatusRoundButton.qml, ui/StatusQ/src/StatusQ/Controls/StatusSlider.qml, ui/StatusQ/src/StatusQ/Controls/StatusWarningBox.qml, ui/StatusQ/src/StatusQ/Core/Theme/StatusDarkTheme.qml, ui/StatusQ/src/StatusQ/Core/Theme/StatusLightTheme.qml, ui/StatusQ/src/StatusQ/Core/Theme/ThemePalette.qml, ui/StatusQ/src/StatusQ/Popups/Dialog/StatusDialogFooter.qml, ui/StatusQ/src/StatusQ/Popups/StatusStackModal.qml, ui/StatusQ/src/StatusQ/Popups/statusModal/StatusModalFooter.qml, ui/app/AppLayouts/Communities/controls/BannerPicker.qml, ui/app/AppLayouts/Communities/controls/EditCommunitySettingsForm.qml, ui/app/AppLayouts/Communities/controls/LogoPicker.qml, ui/app/AppLayouts/Communities/controls/Options.qml, ui/app/AppLayouts/Communities/panels/TagsPanel.qml, ui/app/AppLayouts/Communities/popups/CreateCommunityPopup.qml, ui/app/AppLayouts/Communities/popups/EnableFullMessageHistoryPopup.qml, ui/imports/shared/panels/EditCroppedImagePanel.qml
- when checking the "Request to join required" option; make the warning text part of the control
Fixes https://github.com/status-im/status-desktop/issues/18448
- another commit to fix the barely visible handle in StatusSlider
Fixes #18598
(See the individual commits for more details)
CreateCommunityPopup
https://github.com/user-attachments/assets/e2dec488-86ac-4585-8264-38576c37894e
StatusSlider fixed:
- easier to create the community
- invoke the CreateCommunityPopup
- click the "Request to join required" option
- should not autoscroll to the very top
- low
=> fix(CreateCommunityPopup): fix the erratic autoscroll

ci/Dockerfile, ci/Jenkinsfile.linux
fixes path to ipcdir for pcscd, to solve errors like these: 
```
$ ./StatusIm-Desktop-2.35.0-rc.4-e8083a-x86_64.AppImage 
starting pcscd with /tmp/.mount_StatusMlBcBD/usr/bin/pcscd -f &
00000000 [138400321718208] ../src/pcscdaemon.c:629:main() cannot create /pcscd/run: No such file or directory
qt.core.qobject.connect: QObject::connect(QObject, Unknown): invalid nullptr parameter
```
fixes: https://github.com/status-im/status-desktop/issues/18635
=> ci: fix pcsc run dir

test/e2e/tests/transactions_tests/test_wallet_send_nft.py
temp disable test so its not failing nightly job until i fix it
=> chore(@e2e): temp disable nft test, it fails because collectibles are loading more than a minute

ui/app/mainui/AppMain.qml
Fixes banner text to present timestamp only when balances are cached and therefore valid timestamp is available.
Closes: #18654
`AppMain`
=> Network down banner: show timestamp only if cached

storybook/pages/ActivityNotificationCommunityRequestPage.qml, ui/app/AppLayouts/ActivityCenter/ActivityCenterLayout.qml, ui/app/AppLayouts/ActivityCenter/views/ActivityNotificationCommunityRequest.qml
Fixes #18119
AC
[mark-as-read.webm](https://github.com/user-attachments/assets/109accf0-0f7b-4202-9a53-af290f4cefb4)
Fixes the issue. Better UX
- Request to join a community
- Get aaccepted
- Click the community link
Low
=> fix(ac): notification not being marked as read when going to community

ui/app/mainui/AppMain.qml
- e.g. on mobile, where the browser is not enabled -> open links in an external browser instead
Fixes #18778
AppMain,Browser
https://github.com/user-attachments/assets/4c07f26e-446e-40b3-bb66-906c143ff497
Links can be always opened, e.g. on mobile
- click on a link
- the links opens in the internal, or external browser
- low
=> fix(Browser): do not offer opening links in browser when disabled

src/app/global/feature_flags.nim, src/app/modules/onboarding/controller.nim, src/app/modules/onboarding/module.nim, src/app_service/service/accounts/dto/create_account_request.nim, src/app_service/service/accounts/service.nim, src/app_service/service/settings/dto/settings.nim, src/app_service/service/settings/service.nim, src/backend/settings.nim, storybook/pages/OnboardingLayoutPage.qml, storybook/pages/PrivacyAndSecurityViewPage.qml, storybook/pages/ThirdpartyServicesPopupPage.qml, storybook/qmlTests/tests/tst_OnboardingLayout.qml, ui/StatusQ/src/StatusQ/Popups/StatusModal.qml, ui/app/AppLayouts/Onboarding2/OnboardingFlow.qml, ui/app/AppLayouts/Onboarding2/OnboardingLayout.qml, ui/app/AppLayouts/Onboarding2/pages/WelcomePage.qml, ui/app/AppLayouts/Profile/ProfileLayout.qml, ui/app/AppLayouts/Profile/stores/PrivacyStore.qml, ui/app/AppLayouts/Profile/views/PrivacyAndSecurityView.qml, ui/app/AppLayouts/stores/FeatureFlagsStore.qml, ui/app/mainui/AppMain.qml, ui/app/mainui/Handlers/HandlersManager.qml, ui/app/mainui/Handlers/ThirdpartyServicesPopupHandler.qml, ui/imports/shared/popups/ThirdpartyServicesPopup.qml, ui/imports/shared/popups/qmldir, ui/imports/utils/Constants.qml, ui/main.qml
party services
fixes #18510
status-go PR : https://github.com/status-im/status-go/pull/6865
**_Summary_**
This PR introduces the Third-Party Services feature with full UI integration, feature-flag control, and persistence in the settings database.
**_Key Changes_**
- UI Flows
- Added Third-Party Services section on the Welcome Page.
- Added Third-Party Services option in the Privacy & Settings view.
- Feature Flag
- Introduced privacyModeFeatureEnabled flag to toggle the feature on/off.
- Settings Database
- Added a new setting in the Go settings DB to persist user preference.
- Integrated with UI switch to enable/disable the feature.
- Onboarding Integration
- Integrated Third-Party Services setting into the account creation/login flows.
**_Covered Flows_**
- CreateProfileWithPassword
- …
=> feat(@desktop/wallet): Adding UI flows for Enabling/Disabling Third

ci/Jenkinsfile.combined, ci/Jenkinsfile.linux, ci/Jenkinsfile.linux-nix, ci/Jenkinsfile.macos, ci/Jenkinsfile.tests-e2e, ci/Jenkinsfile.tests-nim, ci/Jenkinsfile.tests-ui, ci/Jenkinsfile.windows
Fixes workspace checkout issues by disabling submodule checkout in Jenkins job and adding git submodule checkout after cleanup stage. 
CI hosts would occasionally end up in a dirty state and each PR job would checkout git submodules during checkout phase. Ideally cleanup phase should run before checkout because most of the PR issues happen during checkout phase.
Some errors looked like this : 
```
> git submodule update --init --recursive vendor/nim-taskpools # timeout=10
ERROR: Checkout failed
hudson.plugins.git.GitException: Command "git submodule update --init --recursive mobile/vendors/openssl" returned status code 1:
stdout: Current branch master is up to date.
Submodule path 'mobile/vendors/openssl/gost-engine': rebased into 'ede3886cc5507c2ba000ab9b057f198da03e8766'
stderr: error: …
```
=> ci: add submodule fetch stage

ui/imports/shared/views/chat/MessageContextMenuView.qml
Fixes #18786
If a message has text, show the button even if it's an image
MessageContextMenu
[copy-msg.webm](https://github.com/user-attachments/assets/b9f9581b-9179-472f-93cf-94af1594c9c1)
fixes the issue
- right click messages 
low
=> fix(message): show Copy message option when image has text too

scripts/windows_build_setup.ps1
Otherwise installation using `scoop` fails with:
```
Test-Path : Cannot bind argument to parameter 'Path' because it is an empty string.
At C:\Users\admin\scoop\apps\scoop\current\lib\manifest.ps1:95 char:31
+                 if (Test-Path $app) {
+                               ~~~~
+ CategoryInfo          : InvalidData: (:) [Test-Path], ParameterBindingValidationException   
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.Po  
werShell.Commands.TestPathCommand
Couldn't find manifest for ''.
```
=> fix(ci): bump protobuf from 3.20.0 to 3.20.1

ci/Jenkinsfile.linux, ci/Jenkinsfile.macos, scripts/version.sh
Fixes this bug where App's version shows "-nwaku-experimental" even when `USE_NWAKU` is not set to `true`
This can confuse users if they're not even using the nwaku version.
Screenshot After the fix for non nwaku builds
We also add "experimental" in filename of package.
=> ci: fix nwaku version in settings and filename

storybook/pages/CommunityInfoEditor.qml, storybook/pages/EditSettingsPanelPage.qml, ui/StatusQ/src/StatusQ/Controls/StatusBaseInput.qml, ui/app/AppLayouts/Communities/controls/DescriptionInput.qml, ui/imports/utils/Constants.qml
- extend the regexp (validator) with a newline character
- adjust the SB pages a bit and silence some related warnings
Fixes #17571
Community description
SB:
User can enter a newline when creating or editing a community description
low
=> fix(Community): being unable to use newline in description

.github/workflows/pr.yml
The new github action will verify that `status-go` submodule is pointing to an appropriate commit:
1. Targeting desktop's `master` branch, status-go `develop` is required
2. Targeting desktop's `release/*` branch, status-go `release/*` is required
3. Commit must be newer that the current in the target branch.
So https://github.com/status-im/status-desktop/labels/waiting-for-status-go-merge label is not needed anymore.
1. Update to newer `develop` commit on 
4. Revert to an older `develop` commit
5. Point to `status-go` feature branch, based on desktop's `master` branch
1. Point to `status-go` _feature_ branch, based on desktop's `release/` branch
2. Point to `status-go` _release_ branch, based on desktop's `release/` branch
The whole workflow can be 10x faster (like ~2s total) if we use …
=> ci: pr check status go commit

test/e2e/tests/crtitical_tests_prs/test_onboarding_sync_with_code.py
Replace the usage of method because Squish is behaving wrong with minimize on windows, it is not working there
=> chore(@e2e): remove minimize method as its not working on windows

ui/imports/shared/popups/addaccount/panels/SelectOrigin.qml
Fixes #18199
The tag height was previously tied to `Theme.bigPadding`, which caused it to resize dynamically with screen size and appear cut off on smaller devices. It is now set to a fixed value to maintain consistent visual appearance.
Wallet / Create New Account
Account tag has now better appearance.
Go to create new account and look at the already created account tags.
None
=> fix(Wallet): Ensure `StatusListItemTag` height is stable across screen sizes

ci/Jenkinsfile.tests-e2e, ci/Jenkinsfile.tests-ui, ci/tests.Dockerfile
With this we avoid maintaining separately and tagging the test docker image.
Referenced issue:
* https://github.com/status-im/infra-ci/issues/188
Fixes tests-ui pipeline and makes both tests-ui and e2e build an image for the build itself out of the dockerfile in the repo.
Linux e2e tests pipeline.
- [ x] I am familiar with the [application architecture](/docs/architecture.md) and agreed good practices.
=> feat(ci): set e2e and tests-ui pipeline to use dockerfile for build steps

ui/app/AppLayouts/Chat/views/ChatColumnView.qml
Disabling text area when message sending was in progress was causing losing focus for a moment. It was triggering closing and re-opening (in wrong position) on-screen keyboard on mobile.
Closes: #18839
`ChatColumnView`
https://github.com/user-attachments/assets/1d979d11-1e58-4fe8-822e-c0b99d3ef151
Low
Use chat on mobile
-
=> StatusChatInput: prevent losing focus when msg is sent

storybook/pages/EditPermissionViewPage.qml, ui/StatusQ/src/StatusQ/Components/StatusItemSelector.qml, ui/app/AppLayouts/Communities/controls/ExtendedDropdownContent.qml, ui/app/AppLayouts/Communities/controls/TokenPanel.qml, ui/app/AppLayouts/Communities/popups/HoldingsDropdown.qml, ui/app/AppLayouts/Communities/views/EditPermissionView.qml, ui/imports/shared/controls/Input.qml
- extract the `getCategoryLabelForType()` function outside of the `categoryLabel` expression; fixes the endless warnings spam
- use `FastExpressionRole` instead for the above
- use `SearchFilter` for the search function
- unbreak the InDropdown (channel selector) in the EditPermissionView SB page
- cleanup and silence some warnings
Fixes #18921
EditPermissionView,HoldingsDropdown
https://github.com/user-attachments/assets/dc391dfa-e949-4651-b86e-07b11803ab19
Adding/editing permissions (namely adding a collectible) should be much faster
=> fix(HoldingsDropdown): speed up and unfreeze the Collectibles Tab

mobile/scripts/ios/run.sh
Sometimes the bundleId is not identified and the app isn't starting. `mdls` returns null. `plutil` seems to be a much better option
=> fix: Use a more robust bundle identifier detection in ios run script
