status-im/status-desktop

src/assets.nim, src/nim_status_client.nim, ui/app/AppLayouts/Wallet/LeftTab.qml
The assets shown in the wallet are now coming from the Nim model.
They are currently relatively bogus since it's the ETH of the 0x0 account, but that's now easily changeable once we have an account.
=> Hook wallet to nim model to show "real" values

ui/app/AppLayouts/ChatLayout.qml
The messages you send will now be aligned right.
Also fixes the issue of the chats being visible under the chat input
The final style is not super pretty IMO, but it shows that we can do different stuff if it's the current user, so I'll wait for a real design to make it pretty
=> feat: show your messages right aligned

Makefile
`.so` for Linux, `.dylib` for macOS
=> chore: DOtherSide shared lib extension differs by platform

README.md, src/nim_status_client.nim
Please note that I've removed Nim from the list of pre-requisites because it will be installed automatically by nimbus-build-system.
=> Clarify the required use of globals

src/app/chat/core.nim, src/app/chat/view.nim, src/status/chat.nim, src/status/utils.nim, ui/app/AppLayouts/ChatLayout.qml
Fixes https://github.com/status-im/nim-status-client/issues/50
Right now it doesn't do anything since we still have the `test` channel hardcoded, but it enables adding a private chat and then sending messages to it.
I also fixed the chat middle section to have ellipsis.
=> Change chat functions to be able to send private messages

src/app/chat/view.nim, ui/app/AppLayouts/ChatLayout.qml
Fixes #59 
At first, I thought to do a loop on the list values and append them back to the view if they matched when the search bar changed. But then I found a better way to do it which is just to hide the items that don't match the string using an alias.
I added the `get` function for the first idea, but then T didn't need it. IMO, it's still a good to have since the ` data` function sucks,
=> Add filter for channels

.gitmodules, src/app/node/core.nim, src/nim_status_client.nim
See https://github.com/status-im/nim-chronicles for usage
```nimrod
import chronicles
logScope:
topics = "Some topic"
debug "Some message", variableName = someValue
info "Some other message", otherVariableName = otherValue
```
=> feat: add nim-chronicles

src/app/chat/core.nim, src/app/chat/view.nim, src/app/signals/messages.nim, ui/app/AppLayouts/Chat/ChatLayout.qml
=> feat: support multiple channels on the UI

src/app/chat/core.nim, src/app/chat/view.nim, src/models/chat.nim, src/nim_status_client.nim, ui/app/AppLayouts/Chat/ChatLayout.qml
Refactor to use MVC model proposed by @iurimatias 
Wait until his PR to merge
=> refactor: join public chats

src/app/onboarding/core.nim, src/app/profile/core.nim, src/models/accounts.nim, src/nim_status_client.nim, src/status/accounts.nim, src/status/types.nim, ui/onboarding/GenKey.qml
The "accountsReady" event now passes the account information for the account that was logged in, which helps pass the correct account info to Profile and is available for other modules that may need it.
This will become particularly useful once the login functionality is implemented.
=> feat: Pass login account data in account event

src/app/wallet/walletView.nim
this was causing the wallet to not display assets
=> revert change to rowCount and Data methods

src/app/chat/view.nim, src/app/chat/views/channels_list.nim, src/models/chat/chat_item.nim, ui/app/AppLayouts/Chat/ChatColumn.qml
Adds the top bar for the chat including hooks to the channel name and new colors for the icon
Disclaimer: the tree dots in the top right do nothing for now but have the MouseArea
=> Add top bar for the chat

src/nim_status_client.nim, ui/app/AppLayouts/Chat/ChatColumn.qml, ui/app/AppLayouts/Chat/ChatLayout.qml, ui/app/AppLayouts/Chat/ContactsColumn.qml, ui/app/AppLayouts/Chat/components/SuggestedChannel.qml, ui/app/AppLayouts/Chat/components/qmldir, ui/nim-status-client.pro
=>  default views for when there is no chat opened + chat links

ui/app/AppLayouts/Browser/BrowserLayout.qml, ui/app/AppLayouts/Chat/ChatColumn.qml, ui/app/AppLayouts/Chat/ChatLayout.qml, ui/app/AppLayouts/Chat/ContactsColumn.qml, ui/app/AppLayouts/Node/NodeLayout.qml, ui/app/AppLayouts/Profile/ProfileLayout.qml, ui/app/AppLayouts/Wallet/LeftTab.qml, ui/app/AppLayouts/Wallet/WalletLayout.qml, ui/app/AppMain.qml, ui/onboarding/GenKey.qml
This started as the new wallet design, but I found how to fix the anchor warnings, so I jumped on it.
=> Fix all anchor warnings and a couple clean ups

src/app/chat/views/message_list.nim, src/models/chat/chat_message.nim, ui/app/AppLayouts/Chat/ChatColumn/Message.qml
=> ui(chat): don't repeat user info for the same user

ui/app/AppLayouts/Chat/ChatColumn.qml, ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml, ui/app/AppLayouts/Chat/ChatColumn/Message.qml, ui/app/AppLayouts/Chat/ChatColumn/samples/MessagesData.qml, ui/app/AppLayouts/Chat/ChatColumn/samples/qmldir, ui/nim-status-client.pro
adds some default properties for the message component, and for the messages list. now that we know how it works we can apply the same to other components
=> Qml components default properties

ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml, ui/app/AppLayouts/Chat/ChatColumn/Message.qml
=> feat: new design for the chat bubble

ui/app/AppLayouts/Chat/components/PrivateChatPopup.qml, ui/app/AppLayouts/Chat/components/PublicChatPopup.qml, ui/app/AppLayouts/Wallet/Components/SendModalContent.qml, ui/app/AppLayouts/Wallet/Components/qmldir, ui/app/AppLayouts/Wallet/SendModal.qml, ui/app/AppLayouts/Wallet/WalletHeader.qml, ui/nim-status-client.pro, ui/shared/Input.qml, ui/shared/Separator.qml, ui/shared/StyledButton.qml, ui/shared/qmldir
Adds back the send form but in the form of a popup modal.
Adds an Input reusable component and pimps the Button one.
Disclaimer: The form doesn't work, but I tried in past master and it already didn't work, so we'll need to fix it in another PR
=> Add send modal and Input and Button reusable components

ui/nim-status-client.pro, ui/onboarding/GenKey.qml, ui/onboarding/Login.qml, ui/shared/Input.qml, ui/shared/StyledButton.qml
- Adds the StyledButton to all buttons
- Adds the Input tot the Login screen,
- A couple of improvements to the login screen:
- List is now full screen and button positioned correctly
- Pressing Enter in th password field now submits!
- Improve the Input component to now accept "otherProps"
- Since QML doesn't work like React where you can just pass `{...otherProps}` to a component, I created a bogus `otherProps` var on the Input where you can put a function into which you can manually add props to the textField that has been aliased. Example:
```
Input: {
otherProps: {
this.textField.focus: true
// Any other weird props that TextField accepts
}
}
```
=> Change all buttons to StyledButton + improve Login screen

src/app/chat/views/channels_list.nim, src/app/wallet/core.nim, src/app/wallet/view.nim, src/app/wallet/views/account_list.nim, src/app/wallet/views/asset_list.nim, src/nim_status_client.nim, src/status/wallet.nim, ui/app/AppLayouts/Chat/ContactsColumn/ChannelList.qml, ui/app/AppLayouts/Wallet/AssetsTab.qml, ui/app/AppLayouts/Wallet/Components/SendModalContent.qml, ui/app/AppLayouts/Wallet/LeftTab.qml, ui/app/AppLayouts/Wallet/SendModal.qml, ui/shared/Input.qml
Adds AccountList which contains the accounts.
The Account is now what contains the AssetList (which has been renamed AssetList from AssetsList), since each account has its own asset list
Rename assetModel to walletModel because it's no longer only assets
The screen shot doesn't show much different, except that all numbers are 0 now. It's juts that it's no longer hardcoded. We show the real value of the account, which is 0.
I'll fix the top values/balances in another PR.
=> feat: show accounts in wallet and put assetList in Account

src/app/login/core.nim, src/app/login/view.nim, src/app/onboarding/core.nim, src/app/onboarding/view.nim, src/app/onboarding/views/account_info.nim, src/nim_status_client.nim, src/signals/types.nim, src/status/accounts.nim, src/status/libstatus/accounts.nim, src/status/libstatus/libstatus.nim, src/status/libstatus/types.nim, ui/onboarding/ExistingKey.qml, ui/onboarding/GenKey.qml, ui/onboarding/Login.qml, ui/onboarding/OnboardingMain.qml
Allow user to import an existing mnemonic.
TODO: add mnemonic validation with the `validateMnemonic` status-go function.
=> feat: Add import account functionality

src/app/wallet/core.nim, src/app/wallet/view.nim, src/app/wallet/views/account_item.nim, src/app/wallet/views/account_list.nim, ui/app/AppLayouts/Wallet/LeftTab.qml, ui/app/AppLayouts/Wallet/WalletHeader.qml
I tried using only QML to achieve this, but sadly it was not possible. Getting a single `accounts` from `accounts` does not seem possible unless you have a QObject for it, so after digging around, I just defaulted back to having a new `currentAccount` object in the View and using that to pass it to QML.
=> feat: show the real value of the current account in the wallet

src/app/chat/view.nim, src/app/chat/views/channels_list.nim, src/status/chat.nim, src/status/libstatus/chat.nim
=> feat(chat): clear unread messages count when changing channels

src/app/wallet/view.nim, ui/app/AppLayouts/Chat/components/PrivateChatPopup.qml, ui/app/AppLayouts/Chat/components/PublicChatPopup.qml, ui/app/AppLayouts/Wallet/Components/AddAccount.qml, ui/app/AppLayouts/Wallet/Components/GenerateAccountModal.qml, ui/app/AppLayouts/Wallet/Components/SendModalContent.qml, ui/app/AppLayouts/Wallet/Components/qmldir, ui/imports/Constants.qml, ui/nim-status-client.pro, ui/onboarding/Login.qml, ui/shared/Input.qml, ui/shared/ModalPopup.qml, ui/shared/PopupMenu.qml
Adds a modal to generate an account
It works, but only on the front-end. The Nim part if very WIP and hardcoded, but it was to not conflict with Iuri who is working on the wallet on the Nim side as well.
=> Add modal to generate a new account (front side only)

src/status/libstatus/accounts.nim, src/status/libstatus/wallet.nim, src/status/wallet.nim, ui/app/AppLayouts/Wallet/LeftTab.qml
Adds the functions to save a newly generated account
Changes the wallet get accounts function to get the wallet accounts correctly instead of just the main account which is just a string.
=> feat: generate new accounts and get wallet account correctly

src/app/wallet/core.nim, src/app/wallet/view.nim, src/status/libstatus/core.nim, src/status/libstatus/tokens.nim, src/status/wallet.nim, ui/app/AppLayouts/Wallet/Components/TokenSettingsModalContent.qml, ui/app/AppLayouts/Wallet/data/Tokens.qml
=> add/remove & update configured tokens on the fly

src/app/wallet/view.nim, src/status/libstatus/accounts.nim, src/status/libstatus/accounts/constants.nim, src/status/wallet.nim, ui/app/AppLayouts/Wallet/Components/AddAccount.qml, ui/app/AppLayouts/Wallet/Components/AddAccountWithSeed.qml, ui/app/AppLayouts/Wallet/Components/GenerateAccountModal.qml, ui/app/AppLayouts/Wallet/Components/qmldir, ui/nim-status-client.pro, ui/shared/Input.qml, ui/shared/ModalPopup.qml
Also makes the Input be a TextArea with `isTextArea`
=> Add accounts with a seed phrase

src/status/libstatus/core.nim, src/status/profile.nim
Needs https://github.com/status-im/status-go/pull/1987 to land first.
=> feat(libstatus): introduce API to get contact by ID

src/app/chat/core.nim, src/app/chat/views/channels_list.nim, src/status/chat.nim, src/status/chat/chat_item.nim, ui/app/AppLayouts/Chat/ChatColumn/Message.qml, ui/app/AppLayouts/Chat/ChatColumn/TopBar.qml, ui/app/AppLayouts/Chat/ContactsColumn/Channel.qml
- Make the topbar channel identifier color match the channel list color
- Display private groups on the channel list
- Reduce chat identifier height
=> Various fixes

src/app/wallet/core.nim, src/app/wallet/view.nim, src/app/wallet/views/account_item.nim, src/app/wallet/views/account_list.nim, src/status/libstatus/accounts.nim, src/status/libstatus/wallet.nim, src/status/wallet.nim, src/status/wallet/account.nim, src/status/wallet/balance_manager.nim, ui/app/AppLayouts/Wallet/AccountSettingsModal.qml, ui/app/AppLayouts/Wallet/Components/AddAccountWithPrivateKey.qml, ui/app/AppLayouts/Wallet/LeftTab.qml, ui/app/AppLayouts/Wallet/WalletHeader.qml, ui/imports/Constants.qml, ui/imports/Theme.qml, ui/nim-status-client.pro, ui/shared/TextWithLabel.qml, ui/shared/qmldir
Enables changing account name and color + the error handling if it fails
=> Enable changing wallet account settings

src/app/wallet/view.nim, src/app/wallet/views/account_list.nim, src/status/libstatus/accounts.nim, src/status/libstatus/utils.nim, src/status/wallet.nim, ui/app/AppLayouts/Wallet/AccountSettingsModal.qml, ui/app/AppLayouts/Wallet/LeftTab.qml, ui/app/AppLayouts/Wallet/WalletHeader.qml, ui/app/AppLayouts/Wallet/WalletLayout.qml
branched off of https://github.com/status-im/nim-status-client/pull/304
Enables removing accounts in the wallet. Includes better error handling and a confirmation popup
=> Enable removing wallet accounts

src/app/chat/view.nim, src/status/chat.nim, src/status/libstatus/chat.nim, src/status/profile.nim, ui/app/AppLayouts/Chat/components/ProfilePopup.qml, ui/shared/ModalPopup.qml, ui/shared/StyledButton.qml
=> feat: introduce button to block users

ui/imports/Theme.qml, ui/main.qml, ui/nim-status-client.pro, ui/onboarding/CreatePasswordModal.qml, ui/onboarding/EnterSeedPhraseModal.qml, ui/onboarding/ExistingKey.qml, ui/onboarding/Login.qml, ui/onboarding/Login/ConfirmAddExistingKeyModal.qml, ui/onboarding/Login/qmldir, ui/onboarding/qmldir
=> feat: add design to enter a seed key

src/app/chat/views/channels_list.nim, src/signals/messages.nim, src/status/chat.nim, src/status/chat/chat.nim, src/status/libstatus/chat.nim
I also renamed `.active` to `.isActive` because it's easier to seach :)
=> fix: allow receiving 1:1 messages after deleting chats

src/app/onboarding/view.nim, ui/main.qml, ui/nim-status-client.pro, ui/onboarding/GenKey.qml, ui/onboarding/GenKeyModal.qml, ui/onboarding/Login/AccountList.qml, ui/onboarding/Login/AddressView.qml, ui/onboarding/Login/SelectAnotherAccountModal.qml, ui/onboarding/qmldir
=> feat: design gen new key modal

src/app/wallet/view.nim, src/app/wallet/views/transaction_list.nim, src/status/libstatus/core.nim, src/status/libstatus/types.nim, src/status/libstatus/wallet.nim, src/status/wallet.nim, ui/app/AppLayouts/Wallet/HistoryTab.qml, ui/app/AppLayouts/Wallet/WalletLayout.qml
There's still some things that needs to be done (possibly in future commits):
[ ] Asset icons need to be determined so they can be displayed along the transaction
[ ] Transaction values need to be converted to decimal values
[ ] Date-time formatting
[ ] Grouping of transactions by days
=> feat(wallet): Introduce simple account transaction list

src/app/chat/core.nim, src/app/chat/view.nim, src/app/chat/views/message_list.nim, src/app/profile/core.nim, src/app/profile/view.nim, src/app/profile/views/contact_list.nim, src/app/profile/views/mailservers_list.nim, src/app/profile/views/profile_info.nim, src/nim_status_client.nim, src/signals/messages.nim, src/signals/types.nim, src/status/chat.nim, src/status/chat/chat.nim, src/status/contacts.nim, src/status/ens.nim, src/status/libstatus/contacts.nim, src/status/profile.nim, src/status/profile/mailserver.nim, src/status/profile/profile.nim, ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml, ui/app/AppLayouts/Chat/ChatColumn/Message.qml
In a separate PR I'll handle the contacts as a table instead of a sequence to simplify some parts of the code
=> feat: Support ENS usernames in messages

src/status/libstatus/wallet.nim, ui/app/AppLayouts/Wallet/Components/TransactionModal.qml, ui/app/AppLayouts/Wallet/Components/qmldir, ui/app/AppLayouts/Wallet/HistoryTab.qml
=> feat: implement transaction detail modal

ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml, ui/app/AppLayouts/Chat/ChatColumn/Message.qml, ui/app/AppLayouts/Chat/components/ProfilePopup.qml, ui/app/AppLayouts/Profile/Sections/Contacts/Contact.qml, ui/app/AppLayouts/Profile/Sections/Contacts/ContactList.qml
also improves memory usage since the popup is initialized once instead of for each message
=> make profile popup reusable

ui/app/AppLayouts/Profile/LeftTab/Menu.qml, ui/app/AppLayouts/Profile/Sections/AdvancedContainer.qml, ui/app/AppMain.qml
=> support enabling/disabling tabs in the advanced settings

ui/app/AppLayouts/Wallet/Components/AddAccountWithPrivateKey.qml, ui/app/AppLayouts/Wallet/Components/TokenSettingsModalContent.qml, ui/app/AppLayouts/Wallet/TokenSettingsModal.qml, ui/app/AppLayouts/Wallet/WalletHeader.qml
I fixed the weird spaces that appeared by removing the spacing from the ListView. 
Since we don't really remove the items from the list, even in the items are now at 0 height, there is still the spacing between the items, hence creating the illusion that the items where not really at 0 height.
To still have a space between the items, I made the Item's height + 10, so that way it handles the spacing itself.
=> Refactor token filter to use Modal Popup + Fix token filter's weird spaces 

src/app/profile/core.nim, src/app/profile/view.nim, src/app/profile/views/contact_list.nim, src/status/contacts.nim, src/status/libstatus/contacts.nim, src/status/profile/profile.nim
* updates to latest status-go (that has getContactById API)
* fixes add contact
* displays & updates contacts correctly in the UI
=> get contacts fully working

src/app/wallet/view.nim, src/app/wallet/views/collectibles_list.nim, src/status/wallet.nim, src/status/wallet/account.nim, src/status/wallet/collectibles.nim, ui/app/AppLayouts/Wallet/CollectiblesTab.qml
It's not super pretty, but it's because there was no design yet
=> Display collectibles in the wallet

ui/app/AppLayouts/Chat/ChatColumn/Message.qml, ui/app/AppLayouts/Chat/ContactsColumn.qml, ui/app/AppLayouts/Chat/ContactsColumn/Channel.qml, ui/app/AppLayouts/Chat/ContactsColumn/ChannelList.qml
=> Fix channel text and chat text with weird text breaks

.gitmodules, config.nims, src/app/chat/views/chat_members.nim, src/app/profile/views/contact_list.nim, src/app/profile/views/mailservers_list.nim, src/status/libstatus/contracts.nim, src/status/libstatus/types.nim
=> remove vendor/nim-nat-traversal

src/app/profile/core.nim, src/app/profile/view.nim, ui/app/AppLayouts/Profile/LeftTab/Menu.qml, ui/app/AppLayouts/Profile/Sections/BackupSeedModal.qml, ui/app/AppLayouts/Profile/Sections/PrivacyContainer.qml, ui/app/AppLayouts/Profile/Sections/qmldir
=> feat(settings): introduce moodal to back up seed phrase

src/nim_status_client.nim
=> feat: app icon on Linux

ui/app/AppLayouts/Chat/ContactsColumn/Channel.qml
=> fix: fix timestamp formatting in chat list

src/app/wallet/views/transaction_list.nim, src/status/libstatus/types.nim, src/status/libstatus/wallet.nim, ui/app/AppLayouts/Wallet/HistoryTab.qml
=> ui(Wallet): render asset icons in transaction list items

src/app/chat/views/message_format.nim, src/app/chat/views/message_list.nim, src/signals/messages.nim, src/status/chat/message.nim, ui/app/AppLayouts/Chat/ChatColumn/Message.qml
=> feat: support message formatting

src/nim_status_client.nim
=> fix: application title on task bar

src/app/onboarding/view.nim, src/status/libstatus/libstatus.nim, src/status/libstatus/wallet.nim, src/status/wallet.nim, ui/onboarding/EnterSeedPhraseModal.qml, ui/onboarding/ExistingKey.qml, ui/onboarding/InvalidSeedPhraseModal.qml, ui/onboarding/qmldir
=> feat(Onboarding): validate mnemonic when importing seed phrase

ui/app/AppLayouts/Chat/ChatColumn.qml, ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml
The message scrollbar stopped working a while ago. This fixes the issue
=> fix: message scrollbar

src/app/wallet/view.nim, src/status/libstatus/accounts.nim, src/status/libstatus/libstatus.nim, src/status/wallet.nim, ui/app/AppLayouts/Wallet/components/AddAccountWithPrivateKey.qml, ui/app/AppLayouts/Wallet/components/AddAccountWithSeed.qml, ui/app/AppLayouts/Wallet/components/AddWatchOnlyAccount.qml, ui/app/AppLayouts/Wallet/components/GenerateAccountModal.qml, ui/onboarding/Login.qml
Also shows the error if there is one when adding.
Should show a loading state too, but it doesn't work because the Nim function freezes the QML
=> feat: check password before saving a new account

src/app/wallet/views/account_list.nim, ui/app/AppLayouts/Wallet/SendModal.qml, ui/app/AppLayouts/Wallet/components/SendModalContent.qml, ui/shared/Input.qml, ui/shared/Select.qml
Also improves the Select component a lot
Missing points:
- Error handling
- Actually testing if the send method still works
- Enable using tokens
Those will be done in another PR
=> Show wallet account in the send modal and add validation

src/app/login/core.nim, src/app/login/view.nim, src/app/onboarding/core.nim, src/app/onboarding/view.nim, ui/onboarding/CreatePasswordModal.qml, ui/onboarding/Login.qml
=> fix: double "login" event being emitted by login / onboarding

.gitignore, src/app/chat/views/message_format.nim, ui/app/AppLayouts/Chat/ChatColumn/Message.qml, ui/app/AppLayouts/Profile/Sections/HelpContainer.qml, ui/shared/xss.js
=> feat(Chat): display clickable links, sanitize them and XSS protect

src/app/chat/views/message_format.nim, ui/app/AppLayouts/Chat/ChatColumn/Message.qml
=> feat: Support status-tag to join a public channel if mentioned in the message list

ui/main.qml, ui/onboarding/GenKey.qml, ui/onboarding/Login.qml
=> Fix login and onboarding issues

src/app/chat/core.nim, src/app/chat/event_handling.nim, src/app/chat/signal_handling.nim, src/app/chat/view.nim, src/app/chat/views/message_list.nim, src/nim_status_client.nim, src/signals/core.nim, src/signals/envelopes.nim, src/signals/messages.nim, src/signals/types.nim, src/status/chat.nim, src/status/chat/message.nim, src/status/libstatus/chat.nim, src/status/messages.nim, src/status/status.nim, ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml, ui/app/AppLayouts/Chat/ChatColumn/Message.qml
=> feat: Determine if a message was sent

src/app/chat/view.nim, src/app/chat/views/message_format.nim, src/status/accounts.nim, ui/app/AppLayouts/Chat/ChatColumn/Message.qml
=> feat(chat): open user profile from mentions

src/app/chat/views/channels_list.nim, src/app/chat/views/chat_item.nim, src/signals/messages.nim, src/status/chat/chat.nim, ui/app/AppLayouts/Chat/ContactsColumn/Channel.qml, ui/app/AppLayouts/Chat/ContactsColumn/ChannelList.qml
=> feat(chat): show "@" when logged in user has been mentioned in channel

src/app/chat/views/message_list.nim, ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml, ui/app/AppLayouts/Chat/ChatColumn/Message.qml
=> fix: fix message width by using the plainText

src/app/chat/views/message_list.nim, src/signals/messages.nim, src/status/chat/message.nim, ui/app/AppLayouts/Chat/ChatColumn.qml, ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml, ui/app/AppLayouts/Chat/ChatColumn/Message.qml, ui/app/AppLayouts/Chat/ChatLayout.qml, ui/app/AppLayouts/Profile/ProfileLayout.qml, ui/app/AppLayouts/Profile/Sections/AdvancedContainer.qml, ui/main.qml
This commit adds support for rendering images by detecting
image URLs inside of a message and attaching them to their
corresponding message bubble.
=> Image support in chat messages

ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml, ui/app/AppLayouts/Chat/ChatColumn/Message.qml, ui/app/AppLayouts/Chat/ChatColumn/TopBar.qml, ui/app/AppLayouts/Chat/ContactsColumn/Channel.qml, ui/app/AppLayouts/Chat/components/ChannelIcon.qml
Branched on top of https://github.com/status-im/nim-status-client/pull/567
=> feat: make channel list compact in compact mode

src/app/chat/core.nim, src/app/chat/signal_handling.nim, src/app/chat/view.nim, src/app/chat/views/message_list.nim, src/nim_status_client.nim, src/signals/core.nim, src/signals/expired.nim, src/signals/types.nim, src/status/chat.nim, src/status/libstatus/chat.nim, src/status/messages.nim, ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml, ui/app/AppLayouts/Chat/ChatColumn/Message.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/CompactMessage.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/NormalMessage.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/Retry.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/SentMessage.qml
To see it in action, temporarily modify the proc `getMailServers` to return an empty array
=> feat: retry sending messages

.gitmodules, src/app/chat/view.nim, ui/app/AppLayouts/Chat/ContactsColumn/Channel.qml
The pictures are saved in /tmp and there's no limit on filesize
=> feat: resize images and remove EXIF data - UNSAFE

ui/app/AppLayouts/Chat/ChatColumn/Message.qml
=> fix: group status messages were not being displayed

src/app/chat/event_handling.nim, src/app/chat/view.nim, ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatImage.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ImageMessage.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/SentMessage.qml
=> fix: load messages on scroll up, scroll down when sending messages and hide sending status for expired messages

src/app/chat/event_handling.nim, src/app/chat/view.nim, ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatImage.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/CompactMessage.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ImageLoader.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ImageMessage.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/SentMessage.qml, ui/nim-status-client.pro
Fix autoscroll on load and on image load
Also hide the sent message on compact mode once the message is sent
=> Fix autoscroll

src/app/profile/core.nim, src/app/profile/views/profile_info.nim, ui/app/AppLayouts/Chat/ChatColumn/ChatButtons.qml, ui/app/AppLayouts/Chat/ChatColumn/ChatInput.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChannelIdentifier.qml, ui/app/AppLayouts/Chat/components/ChannelIcon.qml, ui/app/AppLayouts/Chat/components/EmojiPopup.qml, ui/app/AppLayouts/Chat/components/StickersPopup.qml, ui/app/AppLayouts/Profile/ProfileLayout.qml, ui/app/AppLayouts/Profile/Sections/BackupSeedModal.qml, ui/app/AppLayouts/Profile/Sections/LanguageContainer.qml, ui/app/AppLayouts/Profile/Sections/MyProfileContainer.qml, ui/app/AppLayouts/Profile/Sections/SyncContainer.qml, ui/app/AppLayouts/Wallet/AccountSettingsModal.qml, ui/app/AppLayouts/Wallet/AssetsTab.qml, ui/app/AppLayouts/Wallet/SetCurrencyModal.qml, ui/app/AppLayouts/Wallet/components/SendModalContent.qml, ui/app/AppLayouts/Wallet/components/SetCurrencyModalContent.qml, ui/app/AppLayouts/Wallet/components/TokenSettingsModalContent.qml, ui/imports/Themes/DarkTheme.qml, ui/imports/Themes/LightTheme.qml, ui/nim-status-client.pro, ui/shared/CopyToClipBoardButton.qml, ui/shared/Identicon.qml, ui/shared/Input.qml, ui/shared/Select.qml, ui/shared/StyledTArea.qml, ui/shared/StyledTextArea.qml, ui/shared/StyledTextField.qml
Fixes the chat, wallet and profile.
Also fixes all the remaining QML warnings
Remaining ugly stuff:
- links (`<a>`). They are ugly even in Light mode
- Checkboxes and radio buttons
- QML sucks for those. It doesn't let you customize the color of the boxes or even the text
=> Fix dark theme issues

src/app/chat/view.nim, ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml
Fixes #285 
Branched off of https://github.com/status-im/nim-status-client/pull/643
=> feat: add New messages box in chat when scrolling up

src/app/chat/view.nim, src/status/chat.nim, src/status/libstatus/chat.nim, ui/app/AppLayouts/Chat/ChatColumn/ChatButtons.qml, ui/app/AppLayouts/Chat/ChatColumn/ChatInput.qml, ui/imports/Utils.qml
=> fix: send emoji content type

src/app/onboarding/view.nim, src/app/wallet/view.nim, ui/imports/Utils.qml, ui/onboarding/ExistingKey.qml
=> fix: validate mnemonic format when importing a existing key

src/app/chat/view.nim, src/status/chat.nim, src/status/libstatus/chat.nim, ui/app/AppLayouts/Chat/ChatColumn/ChatButtons.qml, ui/app/AppLayouts/Chat/ChatColumn/ChatInput.qml, ui/imports/Utils.qml
=> fix: hide replybox after sending a message

ui/app/AppLayouts/Chat/components/EmojiPopup.qml, ui/app/AppLayouts/Chat/components/EmojiSection.qml
Branched off of https://github.com/status-im/nim-status-client/pull/685
=> feat: add emoji search

ui/app/AppLayouts/Chat/components/EmojiPopup.qml, ui/app/AppLayouts/Chat/components/EmojiSection.qml, ui/main.qml
Branched off of https://github.com/status-im/nim-status-client/pull/686
=> feat: add support for recent emojis

src/app/chat/view.nim, ui/app/AppLayouts/Chat/ChatColumn.qml, ui/app/AppLayouts/Chat/ChatColumn/ChatButtons.qml, ui/app/AppLayouts/Chat/ChatColumn/ChatInput.qml, ui/app/AppLayouts/Chat/ChatColumn/SuggestionFilter.qml, ui/app/AppLayouts/Chat/components/EmojiPopup.qml, ui/imports/Emoji.qml
=> fix: render emojis in ChatInput

ui/app/AppLayouts/Chat/ChatColumn.qml, ui/app/AppLayouts/Chat/ChatColumn/Message.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/UserImage.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/UsernameLabel.qml, ui/app/AppLayouts/Chat/components/MessageContextMenu.qml, ui/nim-status-client.pro
=> feat: add profile section to the context menu

ui/app/AppLayouts/Profile/Sections/LanguageContainer.qml, ui/app/AppLayouts/Wallet/SendModal.qml, ui/app/AppLayouts/Wallet/components/SendModalContent.qml, ui/shared/AccountSelector.qml, ui/shared/AssetSelector.qml, ui/shared/Select.qml
Fixes #672.
Selects an asset to be used in the send transaction dialog.
=> feat: Send transaction componets -- Asset selector

src/app/profile/core.nim, src/app/profile/view.nim, src/app/profile/views/ens_manager.nim, src/status/libstatus/types.nim, ui/app/AppLayouts/Profile/ProfileLayout.qml, ui/app/AppLayouts/Profile/Sections/Ens/Added.qml, ui/app/AppLayouts/Profile/Sections/Ens/List.qml, ui/app/AppLayouts/Profile/Sections/Ens/Search.qml, ui/app/AppLayouts/Profile/Sections/Ens/TermsAndConditions.qml, ui/app/AppLayouts/Profile/Sections/EnsContainer.qml
- Show welcome page only when there are no ens names registered
- If you already have an ens username for the current account, connect and mark it as preferred name
- State machine navigation
=> feat: connect existing status ens username

ui/app/AppLayouts/Chat/ChatColumn/TopBar.qml, ui/app/AppLayouts/Chat/components/GroupInfoPopup.qml
=> feat(GroupInfo): allow user to visit group member profile page

src/app/profile/views/contact_list.nim, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChannelIdentifier.qml, ui/app/AppLayouts/Chat/components/GroupChatPopup.qml, ui/app/AppLayouts/Chat/components/GroupInfoPopup.qml, ui/app/AppLayouts/Chat/components/PrivateChatPopup.qml
=> fix: additional text on channel identifier

src/app/chat/view.nim, src/app/chat/views/chat_item.nim, src/app/chat/views/message_format.nim, src/app/profile/views/contact_list.nim, src/status/ens.nim, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChannelIdentifier.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/NormalMessage.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/UsernameLabel.qml, ui/app/AppLayouts/Chat/ChatColumn/TopBar.qml, ui/app/AppLayouts/Chat/ContactsColumn/Channel.qml, ui/app/AppLayouts/Chat/components/GroupChatPopup.qml, ui/app/AppLayouts/Chat/components/GroupInfoPopup.qml, ui/app/AppLayouts/Chat/components/MessageContextMenu.qml, ui/app/AppLayouts/Chat/components/PrivateChatPopup.qml, ui/app/AppLayouts/Chat/components/ProfilePopup.qml, ui/app/AppLayouts/Profile/Sections/Contacts/ContactList.qml, ui/app/AppLayouts/Profile/Sections/Ens/List.qml, ui/imports/Utils.qml
=> fix: ens format

ui/app/AppLayouts/Wallet/components/SendModalContent.qml, ui/shared/AccountSelector.qml
As per comment: https://github.com/status-im/nim-status-client/pull/703#discussion_r467879840
=> refactor(AccountSelector): use built-in onSelectedAccountChanged event

Makefile, src/nim_status_client.nim
Fixes #650 
Fix translations for packaged build.
I only was able to test with Windows, as I couldn't install linux-deploy-qt and I don't have a Mac.
Marking do not merge until someone tests Linux and Mac (cc @michaelsbradleyjr )
=> fix: make packaged translations work

src/app/profile/views/contact_list.nim, ui/app/AppLayouts/Wallet/components/SendModalContent.qml, ui/imports/Themes/DarkTheme.qml, ui/imports/Themes/LightTheme.qml, ui/shared/AccountSelector.qml, ui/shared/AddressInput.qml, ui/shared/AddressSourceSelector.qml, ui/shared/ContactSelector.qml, ui/shared/Identicon.qml, ui/shared/Input.qml, ui/shared/PopupMenu.qml, ui/shared/RecipientSelector.qml, ui/shared/Select.qml, ui/shared/TertiaryButton.qml
Fixes #671.
Based on the spec in https://www.notion.so/emizzle/Wallet-transaction-components-2003b78a8d0d41c4ab3d21eb2496fb20, this component handles user input for a recipient address, which can be sourced from manual address input, ENS name, contact selection, or another of the user's wallet accounts.
=> feat/tx-comps: Add RecipientSelector component

ui/shared/StatusSlider.qml, ui/shared/qmldir
This is a slider component with Status look and feel. Will be used in components like GasSelector
=> feat(StatusSlider): introduce StatusSlider component

ui/imports/Utils.qml, ui/shared/AddressInput.qml, ui/shared/ContactSelector.qml, ui/shared/RecipientSelector.qml
This work must have gotten lost in a rebase along the way.
=> fix/tx-comps: Recipient selector -- ability to have readonly value shown

src/app/wallet/view.nim, src/status/libstatus/types.nim, src/status/wallet.nim, ui/app/AppLayouts/Wallet/WalletHeader.qml, ui/app/AppLayouts/Wallet/components/SendModalContent.qml, ui/shared/GasSelector.qml, ui/shared/StatusSlider.qml
=> feat(GasSelector): Introduce GasSelector component

src/app/chat/view.nim, src/app/chat/views/channels_list.nim, src/signals/messages.nim, src/status/chat.nim, src/status/chat/chat.nim, src/status/libstatus/chat.nim, ui/app/AppLayouts/Chat/ContactsColumn/Channel.qml, ui/app/AppLayouts/Chat/ContactsColumn/ChannelList.qml
=> feat: allow users to mute and unmute channels

src/app/wallet/core.nim, src/app/wallet/view.nim, src/status/libstatus/types.nim, ui/app/AppLayouts/Wallet/SendModal.qml, ui/app/AppLayouts/Wallet/components/SendModalContent.qml, ui/shared/TransactionSigner.qml, ui/shared/qmldir
=> feat: introduce TransactionSigner UI component

src/app/wallet/view.nim, src/app/wallet/views/collectibles_list.nim, src/status/wallet/collectibles.nim, ui/app/AppLayouts/Wallet/CollectiblesTab.qml, ui/app/AppLayouts/Wallet/components/collectiblesComponents/CollectiblesContainer.qml, ui/app/AppLayouts/Wallet/components/collectiblesComponents/CollectiblesContent.qml, ui/app/AppLayouts/Wallet/components/collectiblesComponents/CollectiblesHeader.qml
plus reload button
Branched off of https://github.com/status-im/nim-status-client/pull/753
=> feat: add error management to the collectibles

src/app/wallet/view.nim, src/app/wallet/views/collectibles_list.nim, src/status/wallet/collectibles.nim, ui/app/AppLayouts/Wallet/CollectiblesTab.qml, ui/app/AppLayouts/Wallet/components/collectiblesComponents/CollectiblesContainer.qml, ui/app/AppLayouts/Wallet/components/collectiblesComponents/CollectiblesContent.qml, ui/app/AppLayouts/Wallet/components/collectiblesComponents/CollectiblesHeader.qml
Reverts status-im/nim-status-client#759
=> Revert "feat: add error management to the collectibles"

src/app/chat/views/message_format.nim, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatText.qml, ui/app/AppLayouts/Chat/ContactsColumn/AddChat.qml, ui/nim-status-client.pro
- link color in compact mode
- channel links did not have a #
- clicking on a mention should show that profile
- The AddChat button image didn't reposition when closing
=> fix: fix chat links in a  couple of ways

ui/app/AppLayouts/Chat/components/ProfilePopup.qml, ui/app/AppLayouts/Profile/Sections/AdvancedContainer.qml, ui/app/AppLayouts/Profile/Sections/MyProfileContainer.qml, ui/app/AppLayouts/UIComponents/UIComponents.qml, ui/app/AppLayouts/Wallet/WalletHeader.qml, ui/app/AppLayouts/Wallet/components/TransactionModal.qml, ui/nim-status-client.pro, ui/onboarding/Login.qml, ui/shared/Address.qml
It's juts like you imagine. By default the address is cropped in the middle. Once you click on it, it unfurls.
I also added `maxWidth` to it in the case where the container is too small to unfurl completely.
Also works on Hashes, but Address is a better name
=> Add Address component and use it where needed

src/app/chat/event_handling.nim, src/status/chat.nim, src/status/libstatus/mailservers.nim, src/status/mailservers.nim
Prior to this commit, the app would request messages from the last
24 hours for all joined channels.
The changes made here ensure that messages since the *last* request
are requested. The last request for each topic/chat is stored in the
nodes mailserver topics.
When no channels are joined, the default is still 24 hours, however,
as soon as a channel is joined, the last request time will be updated
and honored in the next request.
=> chore(chat): request mailserver messages since last request

src/status/libstatus/default_tokens.nim, src/status/libstatus/tokens.nim, src/status/libstatus/wallet.nim, src/status/wallet/balance_manager.nim, src/status/wallet/collectibles.nim
=> fix: token decimals and returning no collectibles when there's no contract for a collectible on the current network

ui/app/AppLayouts/Profile/Sections/Contacts/Contact.qml
=> fix(Contacts): "Unblock User" i18n ID doesn't have a translation

ui/app/AppLayouts/Chat/components/PrivateChatPopup.qml
=> fix(Chat): use qsTr() over qsTrId() due to non-existent i18n id

ui/app/AppLayouts/Chat/components/Contact.qml
=> uiux(Chat): make entire contact item clickable when starting new chat

ui/app/AppLayouts/Wallet/components/AddAccount.qml
=> fix(Wallet): restore add account button default state

src/app/wallet/view.nim, ui/app/AppLayouts/Wallet/SendModal.qml, ui/imports/Utils.qml, ui/shared/AddressInput.qml, ui/shared/FormGroup.qml
This commit extends the AddressInput to perform ENS lookups when valid
ENS values are entered. The lookup happens asynchronously, so we show a loading
indicator as the request is happening.
Closes #790
=> feat(TransactionModal): introduce async validation for ENS names

src/app/chat/core.nim, src/app/chat/view.nim, src/app/wallet/view.nim, src/status/chat.nim, src/status/ens.nim, src/status/libstatus/coder.nim, src/status/libstatus/eth/contracts.nim, src/status/libstatus/eth/eth.nim, src/status/libstatus/eth/methods.nim, src/status/libstatus/eth/transactions.nim, src/status/libstatus/stickers.nim, src/status/libstatus/tokens.nim, src/status/libstatus/utils.nim, src/status/libstatus/wallet.nim, src/status/status.nim, src/status/stickers.nim, src/status/transactions.nim, src/status/wallet.nim, src/status/wallet/collectibles.nim, ui/app/AppLayouts/Chat/components/StickerPackPurchaseModal.qml, ui/app/AppLayouts/Wallet/SendModal.qml, ui/shared/AccountSelector.qml, ui/shared/GasValidator.qml
Remove from ChatModel and add StickerModel
=> refactor: move stickers to own model

src/app/chat/core.nim, src/app/chat/event_handling.nim, src/app/chat/view.nim, src/app/wallet/core.nim, src/status/chat.nim, src/status/libstatus/wallet.nim, src/status/stickers.nim, src/status/wallet.nim
The stickerpack still needs to be marked as pending. Also, what should happen in case the transaction for buying a stickerpack reverts for some reason?
=> feat: check if a transaction is confirmed before installing a stickerpack

ui/app/AppLayouts/Wallet/components/AddAccountWithSeed.qml
=> fix(Wallet): reset add account modal

src/app/wallet/view.nim, src/status/libstatus/wallet.nim, ui/app/AppLayouts/Profile/Sections/AdvancedContainer.qml, ui/app/AppLayouts/Wallet/SendModal.qml, ui/app/AppMain.qml, ui/main.qml, ui/nim-status-client.pro, ui/shared/Address.qml, ui/shared/ToastMessage.qml, ui/shared/status/StatusButton.qml
- Remember when Wallet is enabled in the QT settings
- Add Loading state to the SendModal button when sending
- Add  bare ToastButton to be used later
Example:
=> Steps towards Send transaction loading state

ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml
=> fix: use messageid in comparator

src/app/wallet/views/token_list.nim, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/TransactionBubble.qml, ui/app/AppLayouts/Wallet/HistoryTab.qml
We used the `defaultTokenList` as if it was a model, but we can't do that because QT from the Nim -> QML transfer is a bit shitty
=> fix: fix defaultTokenList use in QML

src/app/chat/event_handling.nim, src/app/chat/view.nim, src/app/chat/views/sticker_pack_list.nim, ui/app/AppLayouts/Chat/components/StickerButton.qml, ui/app/AppLayouts/Chat/components/StickerMarket.qml
=> fix: show stickers as pending while trx is being mined

ui/app/AppLayouts/Profile/Sections/HelpContainer.qml, ui/shared/GlossaryEntry.qml, ui/shared/GlossaryLetter.qml, ui/shared/qmldir
=> feat: add need help section

ui/app/AppLayouts/Profile/Sections/SyncContainer.qml, ui/shared/BlockContactConfirmationDialog.qml, ui/shared/StyledTextArea.qml
=> uiux: ensure components have proper theme text color

src/app/profile/view.nim, ui/app/AppLayouts/Profile/Sections/ContactsContainer.qml
=> uiux(Contacts): add loading indicator when searching for contacts to add

ui/app/AppLayouts/Chat/ChatColumn/ChatInput.qml, ui/app/AppLayouts/Profile/Sections/SoundsContainer.qml, ui/main.qml
=> uiux(Settings): add slider to control audio volume

ui/app/AppLayouts/Profile/Sections/Contacts/Contact.qml, ui/app/AppLayouts/Profile/Sections/SyncContainer.qml, ui/app/AppLayouts/Wallet/components/SetCurrencyModalContent.qml, ui/shared/status/StatusRadioButton.qml, ui/shared/status/qmldir
=> feat: introduce StatusRadioButton component

ui/app/AppLayouts/Profile/Sections/AdvancedContainer.qml, ui/app/AppLayouts/Profile/Sections/DevicesContainer.qml, ui/app/AppLayouts/Profile/Sections/PrivacyContainer.qml, ui/shared/status/StatusSwitch.qml
=> feat: introduce StatusSwitch component

ui/app/AppLayouts/Profile/Sections/NotificationsContainer.qml, ui/shared/status/StatusRadioButton.qml, ui/shared/status/StatusSectionMenuItem.qml, ui/shared/status/StatusSwitch.qml, ui/shared/status/qmldir
=> feat: implement notification center screen

src/app/profile/views/ens_manager.nim, src/status/ens.nim, ui/app/AppLayouts/Profile/Sections/Ens/RegisterENSModal.qml, ui/app/AppLayouts/Profile/Sections/Ens/Search.qml, ui/app/AppLayouts/Profile/Sections/Ens/SetPubKeyModal.qml, ui/shared/GasValidator.qml, ui/shared/ToastMessage.qml
=> feat: transaction dialog for setPubKey

Makefile, ui/app/AppLayouts/Browser/BrowserLayout.qml, ui/app/AppLayouts/Profile/Sections/AdvancedContainer.qml, ui/app/AppLayouts/qmldir, ui/app/AppMain.qml, ui/main.qml, ui/nim-status-client.pro, ui/onboarding/Intro.qml
Includes an update to use `StatusSwitch` and to store the enabled flag in `appSettings`.
=> feat: reintroduce the dapp browser

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChannelIdentifier.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatReply.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/EmojiReactions.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/NormalMessage.qml, ui/imports/Themes/DarkTheme.qml, ui/imports/Themes/LightTheme.qml
=> Fix colors in dark mode

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/EmojiReactions.qml
=> fix: fix reaction direction in compact mode for current user

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/NormalMessage.qml
=> fix: fix mentions box being too big because plainText was the pubKey

ui/app/AppLayouts/Chat/components/RenameGroupPopup.qml, ui/app/AppLayouts/Profile/Sections/BackupSeedModal.qml, ui/app/AppLayouts/Profile/Sections/ContactsContainer.qml, ui/app/AppLayouts/Profile/Sections/SoundsContainer.qml, ui/nim-status-client.pro, ui/shared/GasValidator.qml, ui/shared/ModalPopup.qml
=> chore: fix qml warnings in a couple of components

ui/app/AppLayouts/Chat/ContactsColumn.qml, ui/app/AppLayouts/Chat/ContactsColumn/ChannelList.qml, ui/app/AppLayouts/Chat/ContactsColumn/EmptyView.qml, ui/app/AppLayouts/Chat/components/PublicChatPopup.qml, ui/app/AppLayouts/Chat/components/SuggestedChannels.qml, ui/app/AppLayouts/Chat/components/qmldir, ui/app/AppLayouts/Chat/data/channelList.js, ui/nim-status-client.pro
=> add Suggested channels sections to sidebar & join chat modal

src/status/libstatus/default_tokens.nim
In response to #1009 .
Tokens I have added:
- Uniswap (UNI)
- Compound (COMP)
- Balancer (BAL)
- Akropolis (AKRO)
- Orchid (OXT)
=> Add more tokens

src/app/chat/view.nim, src/app/profile/views/ens_manager.nim, src/app/utilsView/view.nim, src/app/wallet/view.nim, ui/app/AppLayouts/Chat/ChatColumn/ChatComponents/ChatCommandsPopup.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/TransactionBubble.qml, ui/app/AppLayouts/Profile/Sections/Ens/RegisterENSModal.qml, ui/app/AppLayouts/Profile/Sections/Ens/SetPubKeyModal.qml
Fixes https://github.com/status-im/nim-status-client/issues/931
Notes: For `ensRegisterAddress()` couldn't find it in either chat/wallet view. So I'm not sure if maybe you meant this function in `profile/views/ens_manager.nim`
https://github.com/status-im/nim-status-client/blob/81f5e4e7d8596216fbab257f517afc4f07fb1237/src/app/profile/views/ens_manager.nim#L203-L207
=> chore: refactor function to UtilsView

Makefile, ci/Jenkinsfile.linux, ci/Jenkinsfile.macos, ci/Jenkinsfile.windows
This PR introduces `ci/Jenkinsfile.windows` to build the Windows app in Jenkins.
The host used to run this build is currently configured using:
https://github.com/status-im/infra-ci/blob/bbf74e8dd/files/windows_setup_script.ps1
https://github.com/status-im/infra-ci/blob/bbf74e8dd/files/windows_startup_script.ps1
Though I intend to switch that to Ansible eventually.
Resolves: #595
=> Ci windows builds

ui/imports/Themes/DarkTheme.qml, ui/imports/Themes/LightTheme.qml, ui/shared/status/StatusChatInfoButton.qml
Fixes https://github.com/status-im/nim-status-client/issues/1024
Light and dark theme both hovered
Light  theme
Dark theme
=> fix: top bar theme color

.gitmodules, src/app/chat/view.nim, src/app/chat/views/channels_list.nim, src/app/chat/views/sticker_pack_list.nim, src/app/profile/views/device_list.nim, src/app/profile/views/ens_manager.nim, src/status/chat.nim, src/status/ens.nim, src/status/libstatus/coder.nim, src/status/libstatus/conversions.nim, src/status/libstatus/eth/contracts.nim, src/status/libstatus/eth/eth.nim, src/status/libstatus/eth/methods.nim, src/status/libstatus/eth/transactions.nim, src/status/libstatus/stickers.nim, src/status/libstatus/tokens.nim, src/status/libstatus/types.nim, src/status/libstatus/utils.nim, src/status/libstatus/wallet.nim, src/status/profile/devices.nim, src/status/signals/messages.nim, src/status/stickers.nim, src/status/transactions.nim, src/status/wallet.nim, src/status/wallet/collectibles.nim
Use nim-web3 library and remove internal encoding funcs that were copied from nim-web3.
Remove all instances of EthAddress (and therefore eth/common/eth_types imports)
=> refactor: use nim-web3 library

src/status/wallet.nim
Fixes: #929.
Calculates total wallet balance when it is requested.
=> fix: total wallet balance not displaying

ui/app/AppLayouts/Chat/ChatColumn/ChatComponents/ChatCommandsPopup.qml, ui/shared/status/StatusChatCommandButton.qml, ui/shared/status/StatusIconButton.qml, ui/shared/status/StatusRoundButton.qml, ui/shared/status/qmldir
This is a new version of our `ChatCommandButton` so it is an actual
`Button` element.
=> feat: introduce StatusChatCommandButton

src/app/provider/view.nim, src/status/permissions.nim, src/status/status.nim, ui/app/AppLayouts/Browser/BrowserLayout.qml
- Create privilege dialogs dynamically for each privilege requested
- Check if a privilege has been granted before to determine if dialog must be shown or not
- If dapp is allowed to use privilege, save it in the settings
=> feat: dapp browser privileges

src/app/chat/views/message_format.nim
=> fix: spacing around links

src/app/profile/view.nim, src/status/contacts.nim, ui/app/AppLayouts/Chat/components/NicknamePopup.qml, ui/app/AppLayouts/Chat/components/ProfilePopup.qml
=> feat: implement new design for the nickname popup

ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml, ui/imports/Themes/DarkTheme.qml, ui/imports/Themes/LightTheme.qml, ui/imports/Themes/Theme.qml
=> feat: implement design for the new messages box in chat

src/app/chat/view.nim, ui/app/AppLayouts/Chat/ChatColumn/ChatInput.qml, ui/shared/ToastMessage.qml
Fixes #1003
TLDR: Windows paths do not start with a slash
=> Fix Windows image upload crashing

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ImageLoader.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ImageMessage.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/NormalMessage.qml
=> feat(Chat): allow viewing unfurled images via popup

docs/building.md, scripts/windows_build_setup.ps1
This originally lived in the `infra-ci` repo but I think it makes more sense to if to be in this repo, since here it can be changed by devs as the project evolves.
=> add PowerShell script for build environment setup

src/app/utilsView/view.nim, ui/app/AppLayouts/Wallet/HistoryTab.qml, ui/app/AppLayouts/Wallet/components/TransactionModal.qml
partially fixes https://github.com/status-im/nim-status-client/issues/828 https://github.com/status-im/nim-status-client/issues/901
=> feat: beautify the hex values in transaction history

ui/app/AppLayouts/Chat/components/PublicChatPopup.qml
fixes https://github.com/status-im/nim-status-client/issues/1083
=> fix: change arrow button to 'start chat' for join public chat modal

ui/onboarding/Login.qml
fixes https://github.com/status-im/nim-status-client/issues/1076
=> fix: update generate keys button

scripts/windows_build_setup.ps1
Now You can source the script with .(dot) and use individual functions.
This also makes it easier to use in `infra-ci` Ansible roles.
=> refactor windows_build_setup.ps1 for easier re-usability

ui/app/AppLayouts/Chat/ContactsColumn/ChannelList.qml
=> feat(Chat): show 'no search results' message

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/NormalMessage.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/SentMessage.qml
=> uiux(Chat): remove sent badge

ui/shared/ConfirmationDialog.qml, ui/shared/status/StatusButton.qml
this fixes the text color in dark mode and the StyledButton is replaced with a StatusButton
For the StatusButton to support the color red, I added the color property that can be overridden
=> fix: update delete modal

src/app/chat/event_handling.nim, src/app/chat/view.nim, src/status/chat.nim, src/status/contacts.nim
=> fix(Chat): ensure local nicknames are propagated properly

ui/onboarding/ExistingKey.qml, ui/onboarding/MnemonicRecoverySuccessModal.qml
=> feat: introduce mnemonic recovery success modal

ui/main.qml
=> uiux: set minimum window height and width

ui/app/AppLayouts/Browser/BrowserLayout.qml
Fixes #1031 
maybe later we can add a setting to let the user change it manually, but for now, this fixes the Google login issue
=> fix: change user agent to Firefox on google to enable loging in

ui/app/AppLayouts/Chat/components/ManageUsersPopup.qml, ui/app/AppLayouts/POA/main.js
=> feat: show user list for users

ui/app/AppLayouts/Chat/ChatColumn/TopBar.qml, ui/app/AppLayouts/Chat/components/ManageOperatorsPopup.qml, ui/app/AppLayouts/Chat/components/ManageUsersPopup.qml
=> feat: add operator list and rename to moderators

src/status/wallet.nim, ui/app/AppLayouts/Chat/ContactsColumn/AddChat.qml, ui/app/AppLayouts/Chat/components/PermissionedGroupChatPopup.qml, ui/app/AppLayouts/Chat/components/SignPermissionedChatCreation.qml, ui/app/AppLayouts/POA/main.js, ui/app/AppMain.qml, ui/imports/Constants.qml, ui/nim-status-client.pro
- Removes the warnings from AppMain
- Makes the channel name start my `moderated-` 
- Let's you join the channel if it exists
- If it doesn't exist, shows the sign modal
=> Adds signature for create channel and make it join channel too, etc

ui/app/AppLayouts/Chat/ChatColumn.qml, ui/app/AppLayouts/Chat/components/XDaiTransactionDoneModal.qml, ui/nim-status-client.pro
Currently only calls allowUser, but later, we should call the join method with the burn
Also, once the TX is done, you still can't write until you reboot, but that will change when we have the events
=> feat: add button to join channel

src/status/libstatus/chat.nim
=> fix: ensure chats are ordered by last message timestamp

ui/app/AppLayouts/Browser/BrowserHeader.qml, ui/app/AppLayouts/Browser/BrowserLayout.qml, ui/app/AppLayouts/Browser/BrowserWalletMenu.qml, ui/app/AppLayouts/Profile/Sections/AdvancedContainer.qml, ui/app/AppLayouts/Wallet/AssetsTab.qml, ui/app/AppLayouts/Wallet/SendModal.qml, ui/app/AppLayouts/Wallet/WalletHeader.qml, ui/app/AppMain.qml, ui/imports/Constants.qml, ui/nim-status-client.pro, ui/shared/StatusTabButton.qml
=> Implement design for the wallet popup / account switcher

src/app/wallet/view.nim, src/status/wallet.nim, ui/app/AppLayouts/Wallet/SendModal.qml, ui/nim-status-client.pro, ui/shared/SendToContractWarning.qml
=> feat: Add warning if sending tokens directly to contract

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/TransactionBubble.qml
=> fix(Chat): ensure transaction bubbles are render on the correct side

ui/app/AppLayouts/Browser/BrowserConnectionModal.qml, ui/app/AppLayouts/Browser/BrowserHeader.qml, ui/app/AppLayouts/Browser/BrowserLayout.qml, ui/app/AppLayouts/Browser/BrowserWalletMenu.qml, ui/app/AppLayouts/Browser/FaviconImage.qml, ui/nim-status-client.pro, ui/shared/AccountSelector.qml, ui/shared/status/StatusButton.qml
=> Implements the design for the Approve modal in the browser

src/app/chat/view.nim, src/status/chat/message.nim, src/status/signals/messages.nim, ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml, ui/app/AppLayouts/Profile/Sections/NotificationsContainer.qml, ui/imports/Constants.qml, ui/main.qml, ui/shared/status/StatusChatInput.qml, ui/sounds/ErrorSound.qml
Can choose between all, just mentions, or nothing
=> feat: allow users to configure notification settings

ui/app/AppLayouts/Chat/ChatColumn.qml, ui/app/AppLayouts/Chat/ChatColumn/SuggestionBox.qml, ui/nim-status-client.pro, ui/shared/status/StatusChatInput.qml, ui/shared/status/StatusEmojiSuggestionPopup.qml, ui/shared/status/StatusInputListPopup.qml
Fixes #1073 and #1122
Implements the design for the emoji suggestion picker. Nothing special there
Then I refactored it to extract it into a reusable component, since I wanted to use the same behaviour for the emoji picker and the mentions
Sadly ,the mentions picker is way more complex. It uses a filter, cursor positions and much more. IMO, those could probably be simplified since it's the same thing as the emoji behaviour of inserting text at the right place, but I didn't do it too much because I was already scared of breaking it with the design changes. Anyway, something we might want to refactor at some point, but it works like this.
=> Design emoji suggestion picker and mention picker and make it use the keyboard

ui/app/AppLayouts/Chat/components/GroupChatPopup.qml, ui/app/AppLayouts/Chat/components/GroupInfoPopup.qml
=> Fix group info popup layout and make sure admin status updates corerectly

ui/app/AppLayouts/Browser/BrowserHeader.qml, ui/app/AppLayouts/Browser/BrowserLayout.qml, ui/app/AppLayouts/Browser/BrowserSettingsMenu.qml, ui/app/AppLayouts/Browser/FindBar.qml, ui/app/AppLayouts/Chat/ChatColumn/TopBar.qml, ui/app/AppLayouts/Profile/LeftTab.qml, ui/app/AppLayouts/Profile/LeftTab/Menu.qml, ui/app/AppLayouts/Profile/LeftTab/constants.js, ui/app/AppLayouts/Profile/ProfileLayout.qml, ui/app/AppLayouts/Profile/Sections/AboutContainer.qml, ui/app/AppLayouts/Profile/Sections/AdvancedContainer.qml, ui/app/AppLayouts/Profile/Sections/BrowserContainer.qml, ui/app/AppMain.qml, ui/imports/Constants.qml, ui/main.qml, ui/nim-status-client.pro, ui/shared/PopupMenu.qml
Fixes #1134  and #1135 
The profile section will require more settings once the design is done, but this already covers what we already supported
I put the setting the QT settings as well, so that way they persist through app reboots
=> Add browser settings menu and section in profile

ui/app/AppLayouts/Profile/Sections/HelpContainer.qml
=> chore: add context to help container letter i18n

ui/app/AppLayouts/Chat/ChatColumn/ChatComponents/ChatCommandModal.qml, ui/app/AppLayouts/Chat/ChatColumn/ChatComponents/SignTransactionModal.qml, ui/shared/AddressRequiredValidator.qml, ui/shared/TransactionPreview.qml
=> fix: introduce validation for required address requests in tx previews

src/app/wallet/view.nim, ui/app/AppLayouts/Browser/BrowserLayout.qml, ui/app/AppLayouts/Wallet/HistoryTab.qml, ui/shared/ToastMessage.qml, ui/shared/status/StatusChatInput.qml
This should fix all the QML warnings on master as of today 😄
=> fix: fix a couple of QML warnings

ui/app/AppMain.qml, ui/shared/status/StatusIconTabButton.qml
Prior to this commit, TabButtons where implemented with a lot of code duplication. In addition they where missing hover effects.
=> feat: introduce StatusIconTabButton component

ui/app/AppMain.qml, ui/shared/status/StatusIconTabButton.qml
I also moved a lot of the duplicated properties in the component itself
=> fix: fix tab bar buttons still having a margin when invisible

src/app/wallet/views/token_list.nim, ui/app/AppLayouts/Wallet/AddCustomTokenModal.qml, ui/app/AppLayouts/Wallet/TokenSettingsModal.qml, ui/app/AppLayouts/Wallet/components/TokenSettingsModalContent.qml, ui/shared/PopupMenu.qml
=> feat: show tokens details

ui/app/AppLayouts/Chat/ContactsColumn/Channel.qml, ui/app/AppLayouts/Chat/components/GroupChatPopup.qml, ui/imports/Utils.qml
Fixes a small vulnerability where users could enter a channel with html in them (including images and scripts)
=> fix: protect against XSS in chat names

ui/shared/PopupMenu.qml
=> uiux: fix channel context menu dropshadow and radius

ui/app/AppLayouts/Chat/ContactsColumn/AddChat.qml, ui/app/AppLayouts/Chat/ContactsColumn/ChannelList.qml, ui/shared/SearchBox.qml, ui/shared/status/StatusRoundButton.qml
Also make use of `StatusRoundButton` over `IconButton` since that's deprecated.
Closes #1115
=> uiux: channel list fixes

ui/shared/status/StatusChatInput.qml
=> feat: enable putting text after the shrug or tableflip

ui/app/AppLayouts/Chat/components/PrivateChatPopup.qml
fixes https://github.com/status-im/nim-status-client/issues/1084
=> feat: add loading spinner while resolving ens name

src/app/chat/view.nim, ui/app/AppLayouts/Chat/ChatColumn/SuggestionBox.qml, ui/shared/status/StatusChatInput.qml
Fixes #1327
Fixes #1344
Fixes #1326
See commit names to see what's fixed
=> A couple of fixes to mentions

src/status/contacts.nim, src/status/libstatus/contacts.nim
=> fix: app crashes when adding a contact and getContactById is nil

ui/app/AppLayouts/Chat/ChatColumn.qml
=> fix: hide chat input if you havent joined a group

ui/shared/status/StatusEmojiCategoryButton.qml
=> fix: emoji category button having a white background

ui/main.qml
=> fix: allow chat window to snap-resize

ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml
Fixes the scroll speed in the message area
=> fix: scroll speed

ui/app/AppLayouts/Profile/Sections/Ens/List.qml
=> fix: mangled ens name

src/app/chat/views/suggestions_list.nim, ui/app/AppLayouts/Chat/ChatColumn.qml, ui/shared/status/StatusChatInput.qml
=> feat: show nickname if there is one in the mentions

ui/shared/status/StatusEmojiPopup.qml, ui/shared/status/StatusEmojiSection.qml
=> fix: fix emoji search messing up with recents

ui/shared/status/StatusChatInputImageArea.qml
=> fix(StatusChatInput): ensure image have rounded corners

ui/app/AppLayouts/Chat/ChatColumn/TopBar.qml, ui/app/AppLayouts/Chat/ContactsColumn/ChannelList.qml, ui/app/AppLayouts/Chat/components/FetchMoreMessages.qml
fixes https://github.com/status-im/nim-status-client/issues/1380
=> feat: add fetch more menu item in the chat top right drop down

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/NormalMessage.qml
Follows this kindof https://github.com/status-im/nim-status-client/pull/1347#issuecomment-731105559
=> fix: change chat rectangle width to match designs

src/app/profile/view.nim, src/status/libstatus/stickers.nim, src/status/libstatus/tokens.nim, src/status/wallet.nim, ui/app/AppLayouts/Profile/Sections/AdvancedContainer.qml, ui/app/AppLayouts/Profile/Sections/Ens/Welcome.qml, ui/app/AppLayouts/Profile/Sections/NetworkRadioSelector.qml, ui/app/AppLayouts/Profile/Sections/NetworksModal.qml, ui/imports/Constants.qml, ui/imports/Utils.qml, ui/shared/status/StatusChatInput.qml
=> feat: choose network

src/status/chat.nim
=> fix: request mailserver messages for group and 1:1 chats

ui/app/AppLayouts/Browser/BrowserLayout.qml, ui/app/AppLayouts/Browser/JSDialogWindow.qml
Missing design. Custom dialogs are required to avoid XSS or loading local resources
=> feat: message dialogs

ui/app/AppLayouts/Wallet/AssetsTab.qml, ui/app/AppLayouts/Wallet/HistoryTab.qml, ui/app/AppLayouts/Wallet/LeftTab.qml, ui/app/AppLayouts/Wallet/components/SetCurrencyModalContent.qml
- Show scrollbars in asset list if needed
- Show scrollbars in account list if needed
- Fix margin between assets
- Add symbol to asset amounts
- Stop scrolling at element bounds
=> Various ui fixes on wallet

ui/shared/status/StatusStickersPopup.qml
=> fix: add scrollbar to installed sticker packs

ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml, ui/shared/NotificationWindow.qml
- If notification is clicked and app minimized, restore app
- If app is minimized, show notifications for active chat
=> fix: notifications

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/EmojiReactions.qml
I've made a fix to better handle rendering of reaction authors in conjuction with i18n
=> fix: reaction authors rendering

ui/imports/Themes/DarkTheme.qml, ui/imports/Themes/LightTheme.qml
=> fix: reply text colors

ui/app/AppLayouts/Wallet/components/AddAccountWithPrivateKey.qml, ui/app/AppLayouts/Wallet/components/AddAccountWithSeed.qml, ui/app/AppLayouts/Wallet/components/GenerateAccountModal.qml, ui/imports/Utils.qml, ui/onboarding/CreatePasswordModal.qml, ui/shared/TransactionSigner.qml
=> fix: password count change from 4 to 6

ui/app/AppLayouts/Profile/Sections/MyProfileContainer.qml
i was just working on a Qr Popup so decided to fix #1269 too
=> fix: update profile ui

ui/imports/Utils.qml, ui/onboarding/CreatePasswordModal.qml
=> fix: make validity error match design

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatText.qml
=> fix: ensure cursor is changed when hovering a link

docs/qml_api.md, src/app/chat/core.nim, src/app/chat/event_handling.nim, src/app/chat/view.nim, src/app/chat/views/groups.nim, src/app/chat/views/reactions.nim, src/app/chat/views/stickers.nim, src/app/chat/views/transactions.nim, src/app/utilsView/view.nim, ui/app/AppLayouts/Browser/BrowserLayout.qml, ui/app/AppLayouts/Chat/ChatColumn.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChannelIdentifier.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatText.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/EmojiReactions.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/TransactionComponents/AcceptTransaction.qml, ui/app/AppLayouts/Chat/components/EmojiReaction.qml, ui/app/AppLayouts/Chat/components/GroupChatPopup.qml, ui/app/AppLayouts/Chat/components/GroupInfoPopup.qml, ui/app/AppLayouts/Chat/components/RenameGroupPopup.qml, ui/shared/status/StatusStickerPackPurchaseModal.qml, ui/shared/status/StatusStickersPopup.qml
Extract private groups, reactions, stickers and transactions procs to individual view files
=> refactor: chats view

ui/app/AppLayouts/Chat/ChatColumn.qml, ui/app/AppLayouts/Chat/ChatColumn/Message.qml, ui/app/AppLayouts/Chat/components/MessageContextMenu.qml, ui/shared/status/StatusChatInput.qml
=> feat: allow message context menu to render emojis only

src/status/libstatus/accounts.nim, src/status/libstatus/types.nim, src/status/wallet.nim, ui/app/AppLayouts/Wallet/AccountSettingsModal.qml
=> fix: initialize wallet paths and types, and disable deletion of non-watch accounts

ui/onboarding/Intro.qml, ui/onboarding/KeysMain.qml
the intro screen was not readable when the system theme was the dark theme (on macs)
=> update intro and keys screen to use dark theme setttings correctly

src/app/chat/event_handling.nim, src/app/chat/view.nim, src/status/chat.nim, src/status/libstatus/chat.nim
Fixes the fact that writing to a community channel makes the channel show up in the channel list
Fixes the fetching of messages and reactions for community channels
=> Fix chat list and fetch

src/app/chat/core.nim, src/app/chat/view.nim, src/status/chat.nim, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/StatusUpdate.qml, ui/shared/status/StatusChatInput.qml
We were wrongly referring to `messageItem` which doesn't exist in the
scope of the component. `root` is what it was meant to be.
=> fix(Message): fix reference error

ui/app/AppLayouts/Chat/ContactsColumn/Channel.qml, ui/app/AppMain.qml, ui/shared/Input.qml, ui/shared/status/StatusInputListPopup.qml
Fixes #1053
Discord like channel switcher
It's very cool
I swear
=> feat: add channel switcher when hitting CTRL+K

src/app/chat/view.nim, ui/app/AppLayouts/Profile/Sections/MyProfileContainer.qml, ui/shared/status/StatusChatInput.qml
=> Fix crash on leaving a channel with no messages + clean QML warnings

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatReply.qml, ui/imports/Themes/DarkTheme.qml
=> fix: fix chat reply color and size

ui/app/AppMain.qml
=> fix: ensure changeAppSection links to correct section

ui/app/AppLayouts/Browser/BrowserHeader.qml, ui/app/AppLayouts/Browser/BrowserLayout.qml, ui/app/AppLayouts/Profile/Sections/BrowserContainer.qml, ui/app/AppLayouts/Profile/Sections/BrowserModals/EthereumExplorerModal.qml, ui/app/AppLayouts/Profile/Sections/BrowserModals/HomepageModal.qml, ui/app/AppLayouts/Profile/Sections/BrowserModals/SearchEngineModal.qml, ui/app/AppLayouts/Profile/Sections/PrivacyContainer.qml, ui/imports/Constants.qml, ui/main.qml, ui/nim-status-client.pro, ui/shared/status/StatusSettingsLineButton.qml
=> Add basic browser settings and implementations

src/app/chat/views/stickers.nim, src/app/profile/views/ens_manager.nim, src/status/libstatus/wallet.nim, src/status/signals/wallet.nim, src/status/wallet.nim
Fixes crashes on latest master
=> Fix status-go version and pending tx crash

ui/app/AppLayouts/Chat/ChatColumn/EmptyChat.qml
=> uiux: add visual effect to walkie-talkie links

ui/app/AppLayouts/Chat/components/ProfilePopup.qml, ui/shared/status/StatusButton.qml
=> fix: fix profile popup buttons to fit the design

ui/app/AppLayouts/Wallet/components/AddAccountWithPrivateKey.qml, ui/app/AppLayouts/Wallet/components/AddAccountWithSeed.qml, ui/app/AppLayouts/Wallet/components/AddWatchOnlyAccount.qml, ui/app/AppLayouts/Wallet/components/GenerateAccountModal.qml
`StyledButton` is considered obsolete and by using `StatusButton` we're getting
the expected and correct look & feel of buttons by default.
Closes #1627
=> uiux(Wallet): use StatusButton instead of StyledButton

ui/app/AppLayouts/Wallet/components/HeaderButton.qml
=> uiux(Wallet): ensure send and receive buttons have the right look & feel

ui/shared/StatusTabButton.qml
=> uiux(Wallet): introduce hover state for tab buttons

ui/app/AppLayouts/Chat/components/InviteFriendsPopup.qml, ui/shared/CopyToClipBoardButton.qml
=> Added tooltip when copy invite URL to clipboard

ui/app/AppLayouts/Chat/ChatLayout.qml, ui/app/AppLayouts/Chat/components/NicknamePopup.qml, ui/app/AppLayouts/Chat/components/ProfilePopup.qml, ui/shared/Address.qml, ui/shared/ModalPopup.qml, ui/shared/TextWithLabel.qml
Fixes #1454 
(disregard the buttons at the bottom, they are fixed in another PR)
=> fix: make profile popup look like the design

ui/app/AppLayouts/Chat/ChatColumn/TopBar.qml
=> fix: toggle top bar menu on button click

ui/app/AppLayouts/Chat/ChatLayout.qml, ui/app/AppLayouts/Chat/components/NicknamePopup.qml, ui/app/AppLayouts/Chat/components/ProfilePopup.qml, ui/shared/Address.qml, ui/shared/ModalPopup.qml, ui/shared/TextWithLabel.qml
=> fix: update profile popup qr code button to use StatusIconButton

ui/app/AppLayouts/Chat/components/InviteFriendsPopup.qml, ui/shared/CopyToClipBoardButton.qml
=> Update copy tooltip with StatusToolTip

ui/app/AppLayouts/Chat/components/MessageContextMenu.qml
=> Updated profile popup modal to show existing nickname of the current user

ui/app/AppLayouts/Browser/AddFavoriteModal.qml, ui/app/AppLayouts/Browser/JSDialogWindow.qml, ui/app/AppLayouts/Browser/SignMessageModal.qml, ui/app/AppLayouts/Chat/ChatColumn/ChatComponents/ChatCommandModal.qml, ui/app/AppLayouts/Chat/ChatColumn/ChatComponents/SignTransactionModal.qml, ui/app/AppLayouts/Chat/CommunityComponents/CommunitiesPopup.qml, ui/app/AppLayouts/Chat/CommunityComponents/CommunityDetailPopup.qml, ui/app/AppLayouts/Chat/CommunityComponents/InviteFriendsToCommunityPopup.qml, ui/app/AppLayouts/Chat/components/GroupChatPopup.qml, ui/app/AppLayouts/Profile/Sections/ChangeProfilePicModal.qml, ui/app/AppLayouts/Profile/Sections/Ens/ENSPopup.qml, ui/app/AppLayouts/Profile/Sections/Ens/RegisterENSModal.qml, ui/app/AppLayouts/Profile/Sections/Ens/SetPubKeyModal.qml, ui/app/AppLayouts/Wallet/AccountSettingsModal.qml, ui/app/AppLayouts/Wallet/AddCustomTokenModal.qml, ui/app/AppLayouts/Wallet/SendModal.qml, ui/app/AppLayouts/Wallet/SignPhraseModal.qml, ui/onboarding/CreatePasswordModal.qml, ui/onboarding/MnemonicRecoverySuccessModal.qml, ui/shared/ModalPopup.qml, ui/shared/status/StatusStickerPackPurchaseModal.qml
=> fix: fix PopupModal to not show a footer at all if there is no children

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ImageLoader.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/LinksMessage.qml
=> fix: fix image click not opening on click

ui/imports/Themes/DarkTheme.qml, ui/imports/Themes/LightTheme.qml, ui/imports/Themes/Theme.qml, ui/shared/StyledTArea.qml, ui/shared/StyledTextArea.qml, ui/shared/StyledTextEdit.qml, ui/shared/StyledTextField.qml, ui/shared/status/StatusChatInput.qml
=> Fixed: Text selection color should match design

ui/shared/status/StatusIconTabButton.qml
=> uiux: remove active checked state from StatusIconTabButton

ui/app/AppLayouts/Profile/Sections/HelpContainer.qml
=> uiux(Glossary): make links behave the way they should

ui/app/AppLayouts/Profile/Sections/PrivacyContainer.qml, ui/app/AppMain.qml, ui/main.qml
But add a profile switch to show them for everyone
Fixes #1674
=> feat: only show profile pics for contacts by default

ui/shared/status/StatusChatInput.qml
=> Fixed radius issue of the chat input box.

ui/app/AppLayouts/Profile/Sections/AboutContainer.qml
=> uiux(About): revamp about page

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatText.qml, ui/imports/Emoji.qml
=> Fixes: Emoji messages are rendered too big

ui/app/AppLayouts/Profile/Sections/PrivacyContainer.qml, ui/app/AppMain.qml, ui/shared/status/StatusSettingsLineButton.qml
=> Adjusted badge positions as designs.

src/app/chat/view.nim, src/app/chat/views/message_list.nim
=> fix: fix clearing history removing the fake messages

ui/app/AppLayouts/Chat/components/Contact.qml, ui/app/AppLayouts/Chat/components/PrivateChatPopup.qml, ui/app/AppLayouts/Profile/Sections/AdvancedContainer.qml, ui/app/AppLayouts/Profile/Sections/AppearanceContainer.qml, ui/app/AppLayouts/Profile/Sections/BrowserContainer.qml, ui/app/AppLayouts/Profile/Sections/NotificationAppearancePreview.qml, ui/app/AppLayouts/Profile/Sections/NotificationsContainer.qml, ui/nim-status-client.pro, ui/shared/status/StatusImageRadioButton.qml, ui/shared/status/StatusRadioButtonRow.qml, ui/shared/status/StatusSettingsLineButton.qml
Fixes #1663
Fixes most of the lists we have in the app so that they have a nice hover.
=> Fix lists style

ui/imports/Utils.qml
=> Changed the card date format to be short

ui/app/AppLayouts/Chat/components/GroupInfoPopup.qml
=> Updated group chat member list likes the design.

ui/imports/Themes/DarkTheme.qml, ui/imports/Themes/LightTheme.qml, ui/imports/Themes/Theme.qml, ui/shared/status/StatusToolTip.qml
It was requested to change the tooltip to black an white and white on
black in dark and light themes respectively.
This commit changes the colors accordingly.
=> uiux(StatusTooltip): change color according to theme

src/app/chat/view.nim, src/status/chat.nim, src/status/libstatus/chat.nim, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/LinksMessage.qml
=> feat: call getPreviewData (url unfurling) in a separate thread

src/app/chat/view.nim, src/app/chat/views/channels_list.nim
=> fix: fix channel not updating on new messages

ui/app/AppLayouts/Chat/components/GroupChatPopup.qml, ui/shared/Input.qml
=> Updated group naming functionality.

ui/app/AppLayouts/Chat/components/PrivateChatPopup.qml
=> Fixed filtering contacts issue on when create new chat

package-lock.json, package.json
Fixes #1443.
Move to a forked version of create-dmg that has updated assets.
=> feat: update installer design

ui/shared/ModalPopup.qml, ui/shared/status/StatusIconButton.qml, ui/shared/status/StatusWalletColorButton.qml
This is a new button component that can be used to implement account
wallet color pickers.
=> feat: introduce StatusWalletColorButton

ui/app/AppLayouts/Wallet/AccountSettingsModal.qml, ui/app/AppLayouts/Wallet/components/AddAccountWithPrivateKey.qml, ui/app/AppLayouts/Wallet/components/AddAccountWithSeed.qml, ui/app/AppLayouts/Wallet/components/AddWatchOnlyAccount.qml, ui/app/AppLayouts/Wallet/components/GenerateAccountModal.qml, ui/shared/ModalPopup.qml, ui/shared/status/StatusIconButton.qml, ui/shared/status/StatusWalletColorButton.qml, ui/shared/status/StatusWalletColorSelect.qml
This is a new form control component to select colors for wallet
accounts. It will replace the currently used `ColorSelect` in the
Status Desktop application so it aligns with the new designs.
Closes #1497
=> feat: introduce StatusWalletColorSelect component

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/TransactionComponents/AcceptTransaction.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/TransactionComponents/SendTransactionButton.qml
=> fix: fix double popup for estimating gas errors

ui/app/AppLayouts/Chat/ChatColumn/SuggestionBox.qml, ui/shared/status/StatusChatInput.qml
Fixes #1392 
@emizzle can I haz bonus points now?
=> Fix mention having no active index and enable inserting using tab

ui/app/AppLayouts/Profile/Sections/Contacts/Contact.qml, ui/app/AppLayouts/Profile/Sections/Contacts/ContactList.qml, ui/app/AppLayouts/Profile/Sections/ContactsContainer.qml
Fixes #1589 
Also includes a cleanup of Contact to remove the checkbox and the `selectable` prop as it was never used and was therefore not needed
=> feat: improve contact list clicks and hovers

ui/app/AppLayouts/Profile/LeftTab/components/MenuButton.qml
=> Updated profile settings icon color

src/app/chat/views/chat_item.nim, ui/app/AppLayouts/Profile/Sections/MutedChatsModal.qml, ui/app/AppLayouts/Profile/Sections/PrivacyContainer.qml
=> Fix muted chats not working in profile and fix privacy settings style

ui/shared/status/StatusSlider.qml
Fixes #1726
I also tried to update to QtControl 2, but it felt more clunky, so I gave up.
=> fix: fix slider sliding when using the mouse scroll

ui/shared/status/StatusChatInput.qml
=> Updated selection color of the chat input box as the design

src/app/chat/view.nim, ui/app/AppLayouts/Chat/ChatColumn/TopBar.qml, ui/app/AppLayouts/Chat/ContactsColumn/Channel.qml, ui/app/AppLayouts/Chat/ContactsColumn/ChannelList.qml, ui/app/AppLayouts/Chat/components/ChannelContextMenu.qml, ui/app/AppLayouts/Chat/components/GroupInfoPopup.qml
There's a reference error in our code that `mouseArea` is undefined.
This seems to be a left over, so this commit is removing its usage.
=> chore: remove reference error

AppRun
=> build: set QT_QPA_PLATFORM in AppRun of packaged builds for Linux

src/app/chat/views/message_list.nim, src/status/chat/utils.nim, src/status/libstatus/chat.nim, src/status/signals/messages.nim, ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml, ui/app/AppLayouts/Chat/ChatColumn/Message.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatButtons.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatReply.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatText.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/CompactMessage.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/EmojiReactions.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/MessageMouseArea.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/NormalMessage.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/TransactionBubble.qml, ui/app/AppLayouts/Chat/ContactsColumn/Channel.qml, ui/app/AppLayouts/Chat/ContactsColumn/ChannelList.qml, ui/app/AppLayouts/Chat/components/EmojiReaction.qml, ui/app/AppLayouts/Chat/components/MessageContextMenu.qml, ui/app/AppLayouts/Profile/Sections/AppearanceContainer.qml, ui/imports/Themes/DarkTheme.qml, ui/imports/Themes/LightTheme.qml, ui/imports/Themes/Theme.qml, ui/shared/status/StatusLetterIdenticon.qml
This is based on top of https://github.com/status-im/status-desktop/pull/1759
It fixes all the points listed in that PR, expect the link hover. It shall be done in another PR
=> Compact mode finishing touches

ui/onboarding/Login.qml
=> Updated showing wrong password exception

src/app/chat/view.nim, src/app/chat/views/message_list.nim, ui/app/AppLayouts/Chat/ChatColumn.qml, ui/shared/status/StatusChatInput.qml
=> fix: populate suggestion box with all users from the message list

ui/app/AppLayouts/Profile/LeftTab/Menu.qml
=> Resolved fixed width issue of profile setting's left panel items.

ui/app/AppLayouts/Chat/ChatColumn.qml, ui/shared/status/StatusChatInput.qml
=> fix: remove format on text

ui/app/AppLayouts/Profile/Sections/Contacts/ContactList.qml, ui/shared/ConfirmationDialog.qml
=> Adjusted confirm button wrong style

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatButtons.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/EmojiReactions.qml, ui/shared/CopyToClipBoardButton.qml, ui/shared/TransactionSigner.qml, ui/shared/status/StatusToolTip.qml
=> Adjusted padding and margin of the StatusTooltip component as design

ui/shared/status/StatusStickersPopup.qml
=> fix: loading indicator for sticker market

ui/app/AppLayouts/Chat/ChatColumn/Message.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/CompactMessage.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/NormalMessage.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/UserImage.qml, ui/imports/Constants.qml
=> Show chat image and username again after a couple of minutes in chat

ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml, ui/app/AppLayouts/Chat/ChatColumn/Message.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatReply.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatText.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/EmojiReactions.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/NormalMessage.qml, ui/app/AppLayouts/Chat/CommunityComponents/CommunityButton.qml, ui/app/AppLayouts/Chat/ContactsColumn/Channel.qml, ui/app/AppLayouts/Chat/ContactsColumn/ChannelList.qml, ui/app/AppLayouts/Profile/Sections/AppearanceContainer.qml, ui/main.qml
variable is renamed so it can start over
=> make compact mode the default

src/app/chat/views/chat_item.nim, ui/app/AppLayouts/Chat/ChatColumn/TopBar.qml
=> Fixed issue doesn't show nickname on profileview in 1:1 chat

ui/app/AppLayouts/Chat/ChatColumn/TopBar.qml
=> Fixed showing wrong ensname on one2one chat profile modal

ui/app/AppLayouts/Chat/ChatColumn/TopBar.qml, ui/app/AppLayouts/Chat/components/ChannelContextMenu.qml
=> fix: fix top bar menu position

ui/app/AppLayouts/Chat/ChatColumn/Message.qml, ui/imports/Constants.qml
=> feat: hide fetch old messages after 30 days

ui/app/AppLayouts/Chat/ChatColumn/TopBar.qml
=> Fixed an issue that doesn't update one2one chatview name when unassign nickname from the contact

ui/app/AppLayouts/Chat/components/MessageContextMenu.qml, ui/app/AppLayouts/Chat/components/ProfilePopup.qml, ui/imports/Utils.qml
=> Truncate long 3 words name

ui/shared/status/StatusChatInput.qml
=> feat(StatusChatInput): make text input formatting work via shortcuts

ui/app/AppLayouts/Chat/ChatColumn.qml, ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml, ui/main.qml
=> Hide notifications on app open

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatButtons.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/CompactMessage.qml, ui/app/AppLayouts/Chat/CommunityComponents/CommunityHeaderButton.qml, ui/app/AppLayouts/Chat/components/GroupChatPopup.qml, ui/imports/Themes/DarkTheme.qml, ui/imports/Themes/LightTheme.qml, ui/imports/Themes/Theme.qml, ui/shared/CopyToClipBoardButton.qml, ui/shared/ModalPopup.qml, ui/shared/PopupMenu.qml, ui/shared/TextWithLabel.qml, ui/shared/status/StatusChatInfo.qml, ui/shared/status/StatusChatInfoButton.qml, ui/shared/status/StatusCheckBox.qml, ui/shared/status/StatusSettingsLineButton.qml, ui/shared/status/StatusSwitch.qml
=> New Dark theme colors

ui/shared/status/StatusChatInput.qml
=> feat(StatusChatInput): render formatted text inside input

src/app/chat/view.nim, ui/app/AppLayouts/Chat/CommunityColumn.qml, ui/app/AppLayouts/Chat/CommunityComponents/CommunityButton.qml, ui/app/AppLayouts/Chat/CommunityComponents/CommunityHeaderButton.qml, ui/app/AppLayouts/Chat/CommunityComponents/CommunityList.qml, ui/app/AppLayouts/Chat/ContactsColumn.qml, ui/app/AppLayouts/Chat/components/LeftTabBottomButtons.qml, ui/app/AppMain.qml, ui/imports/Constants.qml, ui/imports/Utils.qml, ui/nim-status-client.pro, ui/shared/ImageLoader.qml, ui/shared/RoundedImage.qml, ui/shared/status/StatusIconTabButton.qml
Fixes #1835 
Example of what it could look like when you have a ton of communities (disregard the fact that the image is not showing)
=> Implement redesign of communities on the left tab

ui/app/AppLayouts/Chat/ChatColumn/Message.qml, ui/app/AppLayouts/Chat/ChatColumn/TopBar.qml, ui/app/AppLayouts/Chat/ChatLayout.qml, ui/app/AppLayouts/Chat/ContactsColumn/ChannelList.qml, ui/app/AppLayouts/Chat/components/ChannelContextMenu.qml, ui/app/AppLayouts/Chat/components/GroupInfoPopup.qml, ui/nim-status-client.pro
Also will probably increase performance... probly not by much, but at least 1 ms on login 😁
=> Fix QML warnings

src/app/onboarding/views/account_info.nim
=> fix: update image when switching account on login

src/status/contacts.nim, src/status/libstatus/contacts.nim
Fixes #1761
We need to update contact attributes including thumbnail image while saving contact. (`saveContact`)
=> Fixed dismissing issue when update contact's profile

AppRun
=> fix: set default language

src/app/chat/view.nim
=> fix: fix mention not being removed

ui/main.qml
=> fix:  Don't quit the app when clicking on "x" and Enable closing the app with CMD + W

src/app/chat/view.nim, src/app/chat/views/communities.nim, src/app/chat/views/community_item.nim, src/app/chat/views/community_list.nim, src/status/chat/chat.nim, src/status/chat/utils.nim, src/status/signals/messages.nim, ui/app/AppLayouts/Chat/CommunityComponents/CommunityButton.qml, ui/app/AppLayouts/Chat/CommunityComponents/CommunityHeaderButton.qml, ui/app/AppLayouts/Chat/CommunityComponents/CommunityList.qml, ui/app/AppLayouts/Chat/ContactsColumn/Channel.qml
Fixes #1871
Also fixes Community header button looking wrong in dark mode and fixes setActive broken
=> Show unviewed messages in community bar and last message received

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/CompactMessage.qml
=> fix: message height taking into account the image even when hidden

ui/shared/status/StatusStickerMarket.qml, ui/shared/status/StatusStickerPackPurchaseModal.qml
=> fix: don't estimate gas before when displaying sticker packs

ui/app/AppLayouts/Chat/ChatColumn.qml
=> fix: input html being shown when removing css format

src/status/wallet.nim
=> fix: fix asset balances on new accounts

ui/app/AppLayouts/Wallet/AssetsTab.qml, ui/app/AppLayouts/Wallet/HistoryTab.qml, ui/app/AppLayouts/Wallet/LeftTab.qml, ui/app/AppLayouts/Wallet/components/SetCurrencyModalContent.qml, ui/app/AppLayouts/Wallet/components/TokenSettingsModalContent.qml, ui/shared/StatusTabButton.qml
=> Fixed wrong color issue of the wallet layout

ui/shared/CopyToClipBoardButton.qml
=> Fixed copy button of the invite link in dark mode

ui/app/AppLayouts/Chat/ChatColumn/EmptyChat.qml
=> Fixed wrong invite description text color in dark mode

ui/app/AppLayouts/Chat/ChatColumn.qml, ui/shared/status/StatusChatInput.qml, ui/shared/status/StatusEmojiPopup.qml
- Uses a Loader for ChatMessages that activates once the active channel is changed
- Emoji categories are processed on opened instead of onCompleted
=> fix: improve qml bottlenecks

ui/shared/status/StatusChatInput.qml
=> uiux(StatusChatInput): close text format menu on deletion

ui/shared/status/StatusChatInput.qml
=> fix(StatusChatInput): exclude markdown indicators from formatting

ui/shared/status/StatusChatInput.qml, ui/shared/status/StatusTextFormatMenu.qml
This will highlight any option in the text formatting menu whose
formatting matches the selected text formatting
Closes #1931
=> uiux(StatusChatInput): highlight matching formatting option

ui/app/AppMain.qml
=> fix: fix left tab line not following height of parent

ui/app/AppLayouts/Chat/CommunityColumn.qml
=> Updated community popup menu btn style

ui/app/AppLayouts/Chat/CommunityComponents/CommunityHeaderButton.qml
=> fix: fix users being able to see admin popup

ui/app/AppLayouts/Chat/ChatColumn.qml, ui/app/AppLayouts/Chat/ChatColumn/SuggestionBox.qml
=> Fixed not showing issue for the profile thumbnail in the suggestion list

ui/onboarding/Login.qml
=> Fixed login btn pending status in case of invalid password

ui/app/AppLayouts/Profile/LeftTab/components/MenuButton.qml
=> fix: make the profile icons smooth

src/app/chat/view.nim
=> fix: fix getChannelById crashing on timeline call

src/app/chat/views/community_item.nim, ui/app/AppLayouts/Chat/CommunityComponents/CommunityMembersPopup.qml
=> fix: fix member popup layout and member not showing

ui/app/AppLayouts/Chat/CommunityComponents/CreateCommunityPopup.qml
=> fix: disable ENS only setting if user has no ENS name

src/app/chat/view.nim, src/status/chat.nim
Fixes #2035
Also goes back to your first channel when deleting the current channel
=> fix: fixes the ordering problem on deleting a channel

ui/app/AppLayouts/Chat/CommunityColumn.qml, ui/app/AppLayouts/Chat/CommunityComponents/CommunityWelcomeBanner.qml, ui/app/AppMain.qml
=> fix(Communities): ensure app remembers hidden community intro banners

ui/app/AppLayouts/Profile/LeftTab/Menu.qml, ui/app/AppLayouts/Profile/LeftTab/constants.js
=> fix: profile menu seperators

ui/app/AppLayouts/Profile/Sections/AppearanceContainer.qml
fixes #2021 , keeping the old code for now
=> hide chat mode switch for now and make compact mode the default

ui/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopupMembersList.qml, ui/shared/status/StatusSettingsLineButton.qml
The designs for the membership request button look different now, so this
commit makes use of the `StatusSettingsLineButton` to implement that new
look & feel.
=> refactor(Communities): make membershipt request button looks as designed

.gitignore, .gitmodules, src/app/wallet/core.nim, src/nim_status_client.nim, src/status/libstatus/accounts.nim, src/status/libstatus/core.nim, src/status/libstatus/wallet.nim
=> refactor: remove vendor/nim-status and replace with vendor/nim-status-go

ui/app/AppLayouts/Browser/BrowserHeader.qml, ui/app/AppLayouts/Profile/Sections/BrowserContainer.qml, ui/app/AppLayouts/Profile/Sections/BrowserModals/EthereumExplorerModal.qml, ui/app/AppLayouts/Profile/Sections/BrowserModals/SearchEngineModal.qml, ui/app/AppMain.qml
fixes #1900 
changed the key names to force the new defaults
=> update default settings

ui/app/AppMain.qml, ui/main.qml, ui/onboarding/CreatePasswordModal.qml, ui/onboarding/ExistingKey.qml, ui/onboarding/Login.qml
=> fix: fix appSetting not defined by removing sounds from login

ui/app/AppLayouts/Profile/ProfileLayout.qml, ui/app/AppLayouts/Profile/Sections/AboutContainer.qml, ui/app/AppLayouts/Profile/Sections/AdvancedContainer.qml, ui/app/AppLayouts/Profile/Sections/AppearanceContainer.qml, ui/app/AppLayouts/Profile/Sections/BrowserContainer.qml, ui/app/AppLayouts/Profile/Sections/ContactsContainer.qml, ui/app/AppLayouts/Profile/Sections/HelpContainer.qml, ui/app/AppLayouts/Profile/Sections/LanguageContainer.qml, ui/app/AppLayouts/Profile/Sections/MyProfileContainer.qml, ui/app/AppLayouts/Profile/Sections/NotificationsContainer.qml, ui/app/AppLayouts/Profile/Sections/PrivacyContainer.qml, ui/app/AppLayouts/Profile/Sections/SoundsContainer.qml, ui/app/AppLayouts/Profile/Sections/SyncContainer.qml
=> uiux(Profile): adjust layout max width of profile sections

ui/app/AppLayouts/Profile/Sections/BrowserModals/EthereumExplorerModal.qml, ui/app/AppLayouts/Profile/Sections/BrowserModals/HomepageModal.qml, ui/app/AppLayouts/Profile/Sections/BrowserModals/SearchEngineModal.qml, ui/app/AppLayouts/Profile/Sections/FleetRadioSelector.qml, ui/app/AppLayouts/Profile/Sections/FleetsModal.qml, ui/app/AppLayouts/Profile/Sections/MutedChatsModal.qml, ui/app/AppLayouts/Profile/Sections/NetworkRadioSelector.qml, ui/app/AppLayouts/Profile/Sections/NetworksModal.qml, ui/app/AppLayouts/Profile/Sections/OpenLinksWithModal.qml
=> fix: ensure lists and radio button groups look concise throughout app

src/app/profile/views/contacts.nim, ui/app/AppLayouts/Chat/components/PrivateChatPopupSearchResults.qml, ui/app/AppLayouts/Profile/Sections/ContactsContainer.qml
=> refactor: make add new contact modal looks the same as new chat modal

ui/imports/Emoji.qml
=> fix(Chat): align emojis within chat inputs properly

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatReply.qml
=> fix(Chat): ensure chat reply separator doesn't leak into message

ui/app/AppLayouts/Chat/CommunityComponents/CommunitiesPopup.qml, ui/app/AppLayouts/Chat/CommunityComponents/CommunityDetailPopup.qml, ui/app/AppLayouts/Chat/CommunityComponents/CommunityHeaderButton.qml, ui/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopup.qml
=> fix: fix communities not showing the letter identicon correctly

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatButtons.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/CompactMessage.qml
=> hide reactions and replies when the message is a transaction

ui/app/AppLayouts/Profile/Sections/DevicesContainer.qml, ui/app/AppLayouts/Profile/Sections/Ens/Welcome.qml, ui/app/AppLayouts/Profile/Sections/LanguageContainer.qml, ui/app/AppLayouts/Profile/Sections/SoundsContainer.qml, ui/app/AppLayouts/Profile/Sections/SyncContainer.qml
=> remove various titles from profile sections

ui/app/AppLayouts/Profile/Sections/Ens/Search.qml, ui/imports/Constants.qml
shouldve tested #2100 more thoroughly, i found some typos, and the fact that the switch statement only accepts string literals
=> fix typos and switch statement string literals

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatTime.qml, ui/app/AppLayouts/Chat/CommunityComponents/CommunityButton.qml, ui/app/AppLayouts/Profile/LeftTab.qml, ui/app/AppLayouts/Profile/LeftTab/Menu.qml, ui/app/AppLayouts/Profile/Sections/AboutContainer.qml, ui/shared/CopyToClipBoardButton.qml, ui/shared/status/StatusSectionDescItem.qml, ui/shared/status/StatusToolTip.qml
=> Fix multiple tooltip issues

ui/app/AppLayouts/Profile/Sections/DevicesContainer.qml
=> fix blank sync settings

ui/app/AppLayouts/Chat/CommunityComponents/CreateCommunityPopup.qml, ui/shared/status/StatusEmojiSection.qml, ui/shared/status/StatusSettingsLineButton.qml, ui/shared/status/StatusStickerButton.qml, ui/shared/status/StatusStickerMarket.qml, ui/shared/status/StatusStickerPackClickPopup.qml, ui/shared/status/StatusStickerPackDetails.qml
=> Fix dark mode texts and sticker modals layout

ui/shared/status/StatusInputListPopup.qml
=> fix: fix channel picker needing to hit bottom to select after searching

ui/app/AppLayouts/Chat/CommunityComponents/CommunitiesPopup.qml
=> fix: typo in community popup

src/app/chat/views/communities.nim, ui/app/AppLayouts/Chat/ChatColumn.qml
=> fix: input box disappearing on communities

ui/app/AppLayouts/Chat/CommunityColumn.qml
=> feat: add invite button to community menu

ui/app/AppLayouts/Chat/ChatColumn/TopBar.qml, ui/app/AppLayouts/Chat/ContactsColumn/AddChat.qml, ui/app/AppLayouts/Wallet/WalletHeader.qml, ui/app/AppLayouts/Wallet/components/AddAccount.qml
=> fix: menu dropdowns not closing on button click and position

src/app/chat/views/message_format.nim, ui/app/AppLayouts/Chat/ChatColumn.qml, ui/app/AppLayouts/Chat/ChatColumn/SuggestionFilter.qml, ui/shared/status/StatusChatInput.qml
=> Fix spaces in chat

src/status/mailservers.nim
This fixes the crash that happens when you leave a chat group
https://user-images.githubusercontent.com/1106587/113579186-eebdb880-95f1-11eb-9335-4e4ad6c36a5f.mp4
=> fix: leave chat groups

src/status/chat.nim
**BACKUP YOUR DATA FOLDER BEFORE RUNNING DESKTOP!**
=> Auto remove group chats

ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/CompactMessage.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/DateGroup.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/NormalMessage.qml
=> fix: date label not showing correctly

ui/shared/RoundedImage.qml
=> feat: make the identicon use the right color instead of white

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChannelIdentifier.qml
=> fix: fix channel-identifier-dark-text

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/CompactMessage.qml, ui/app/AppMain.qml, ui/main.qml, ui/shared/ModalPopup.qml
=> fix: fix compact message hover when a popup is opened

ui/app/AppLayouts/Chat/CommunityComponents/CommunityDetailPopup.qml, ui/app/AppLayouts/Chat/ContactsColumn/Channel.qml, ui/app/AppLayouts/Chat/ContactsColumn/ChannelList.qml
=> fix: fix channel list spacing during a search

ui/app/AppLayouts/Chat/components/MessageContextMenu.qml
=> fix: fix copy link submenu items being unreadable in dark theme

ui/app/AppLayouts/Chat/ChatColumn.qml
Fixes #1942
Also cleans up a little the ChatColumn abuse of rows
=> fix: remove possibility to click through the top bar on messages

ui/main.qml
=> fix: right click on app icon now always shows menu

ui/app/AppLayouts/Profile/Sections/NetworksModal.qml, ui/app/AppLayouts/Profile/Sections/NewCustomNetworkModal.qml, ui/nim-status-client.pro
=> fix: fix custom network modal not opening

ui/app/AppLayouts/Profile/ProfileLayout.qml, ui/app/AppLayouts/Profile/Sections/AboutContainer.qml, ui/app/AppLayouts/Profile/Sections/AdvancedContainer.qml, ui/app/AppLayouts/Profile/Sections/AppearanceContainer.qml, ui/app/AppLayouts/Profile/Sections/BrowserContainer.qml, ui/app/AppLayouts/Profile/Sections/ContactsContainer.qml, ui/app/AppLayouts/Profile/Sections/DevicesContainer.qml, ui/app/AppLayouts/Profile/Sections/Ens/List.qml, ui/app/AppLayouts/Profile/Sections/Ens/Search.qml, ui/app/AppLayouts/Profile/Sections/Ens/Welcome.qml, ui/app/AppLayouts/Profile/Sections/EnsContainer.qml, ui/app/AppLayouts/Profile/Sections/HelpContainer.qml, ui/app/AppLayouts/Profile/Sections/LanguageContainer.qml, ui/app/AppLayouts/Profile/Sections/MyProfileContainer.qml, ui/app/AppLayouts/Profile/Sections/NotificationsContainer.qml, ui/app/AppLayouts/Profile/Sections/PrivacyContainer.qml, ui/app/AppLayouts/Profile/Sections/SignoutContainer.qml, ui/app/AppLayouts/Profile/Sections/SoundsContainer.qml, ui/app/AppLayouts/Profile/Sections/SyncContainer.qml, ui/imports/Constants.qml, ui/main.qml
Fixes #1918
This makes it that the profile sections now have a minimum width and a max width. It is t 80% of the full width in between
I also fixed some small issues in the ENS section
=> fix: improve profile sections min width and scaling

src/app/chat/views/communities.nim, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/InvitationBubble.qml
=> fix: fix invite button not setting Joined correctly

src/app/chat/view.nim, src/app/chat/views/communities.nim
=> fix: fix notifications not working for community chats

src/app/chat/view.nim, src/app/utilsView/view.nim, ui/app/AppLayouts/Profile/Sections/NetworkRadioSelector.qml, ui/app/AppMain.qml, ui/shared/AddressInput.qml, ui/shared/ContactsListAndSearch.qml, ui/shared/RecipientSelector.qml, ui/shared/SearchResults.qml
Fixes #2164
Also fixes a bug where you couldn't switch network because the popup didn't open
=> Improve wallet ENS search + fix network switch modal

ui/app/AppLayouts/Wallet/components/AddAccountWithSeed.qml, ui/imports/Utils.qml, ui/nim-status-client.pro, ui/onboarding/EnterSeedPhraseModal.qml, ui/onboarding/ExistingKey.qml, ui/shared/SeedPhraseTextArea.qml, ui/shared/StyledTextArea.qml
=> fix: fix seed phrase modal UI logic

src/status/libstatus/contacts.nim
Fixes #2131.
After some heavy profiling, it became clear that sending of each message was causing a fetch to get all contacts from status-go. This was incurring a minimum of a 0.03s delay for each fetch, which was causing a bottleneck each time it was called for various operations throughout the codebase.
This code addds a layer of threadsafe caching to the contacts call, such that only the first call to contacts fetching will incur the delay, as well as every fetch after a contacts CUD operation.
=> feat: Add libstatus contacts caching

src/status/libstatus/settings.nim
Current settings caching logic was inefficient when attempting to retrieve settings that contain the sensitive mnemonic. While those calls were limited to the login logic, each call would need to round trip to status-go to get all settings when they wanted to include sensitive data, as the cache was not being updated for these calls.
This PR updates the cache regardless if sensitive data is requested of not, effectively making the caching mechanism more efficient during login.
=> feat: settings cache efficiency update

src/app/profile/view.nim, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatTime.qml, ui/app/AppLayouts/Chat/ContactsColumn/Channel.qml, ui/app/AppLayouts/Profile/Sections/AppearanceContainer.qml, ui/app/AppLayouts/Profile/Sections/LanguageContainer.qml, ui/app/AppLayouts/Profile/Sections/LanguageModal.qml, ui/app/AppLayouts/Wallet/AssetsTab.qml, ui/app/AppLayouts/Wallet/LeftTab.qml, ui/app/AppMain.qml, ui/imports/Style.qml, ui/main.qml
This commit introces global settings that apply across accounts used
inside the application. This is useful when settings like the selected
locale should b the same across all accounts.
Closes #2144
=> feat: introduce global settings

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/CompactMessage.qml
=> uiux(Chat): ensure emojis are centered vertically within messages

ui/app/AppLayouts/Chat/CommunityComponents/CreateCommunityPopup.qml
Fixes #2301
The image was being expected to be put, but it is optional.
I also put the button as enabled at all times, that way, yes you can click it too soon, but at least you get a message for what you missed instead of having to guess what's missing like with the image
=> Fix not being able to create a community

ui/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopupOverview.qml
Fixes #2272
The issue was already solved by @PascalPrecht , but I'm completely removing the button since it will probably never exist and it's not a big deal to add back if ever.
=> chore(CommunityProfile): comment notifications and remove Delete code

ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatButtons.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/CompactMessage.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/EmojiReactions.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/MessageMouseArea.qml
=> fix(CompactMessage): fix message hover getting stuck

ui/app/AppLayouts/Chat/CommunityComponents/CreateCommunityPopup.qml
=> Comment ENS toggle on communities

ui/shared/status/StatusChatInput.qml
=> uiux(StatusChatInput): toggle markdown from selection

ui/app/AppLayouts/Profile/Sections/AdvancedContainer.qml, ui/shared/ConfirmationDialog.qml
=> feat: add confirmation dialog on experimental features enabling

src/app/chat/views/stickers.nim, src/app/profile/views/ens_manager.nim, src/status/libstatus/wallet.nim
Fixes: #2323 and https://github.com/status-im/status-desktop/issues/2222
Depends on: https://github.com/status-im/status-go/pull/2197 being merged first
=> feat: use new pending transfer API

ui/app/AppLayouts/Chat/components/GroupInfoPopup.qml
=> fix: group members context menu icons

src/status/libstatus/wallet.nim
=> fix: handle tokens with no decimals

ui/app/AppLayouts/Profile/Sections/BackupSeedModal.qml
=> fix: seedphrase backup endless loop

ui/app/AppLayouts/Chat/components/ChannelContextMenu.qml, ui/imports/Themes/DarkTheme.qml, ui/imports/Themes/LightTheme.qml, ui/shared/Separator.qml
=> fix: channel context menu colors

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/CompactMessage.qml
=> fix(CompactMessage): fix reactions overlapping with the test

ui/app/AppLayouts/Chat/CommunityComponents/CreateCommunityPopup.qml, ui/app/AppLayouts/Chat/CommunityComponents/MembershipRadioButton.qml
=> fix(CreateCommunity): fix membership text color and spacing

ui/app/AppLayouts/Chat/CommunityComponents/CreateCommunityPopup.qml, ui/shared/StyledTextArea.qml
Fixes #2412
I couldn't fix the unfocus issue because it seems like a QML limitation. Every input field does that. Maybe @borismelnik has an idea?
=> fix(TextArea): fix selecting  text in a TextArea and placeholder color

src/app/chat/views/message_list.nim, ui/app/AppLayouts/Chat/ChatColumn/Message.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatReply.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/CompactMessage.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ImageLoader.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/Sticker.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/UserImage.qml, ui/app/img/reply-corner.svg
=> Implement redesign of message replies

ui/app/AppLayouts/Chat/ChatColumn/Message.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/CompactMessage.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/InvitationBubble.qml
=> fix(CompactChat): fix margins for images and invites

ui/app/AppLayouts/Browser/BrowserLayout.qml
=> fix: can't send transactions on browser

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/LinksMessage.qml
Fixes https://github.com/status-im/status-desktop/issues/2390
=> force refetching previews when preview whitelist changes

ui/app/AppLayouts/Chat/components/GroupInfoPopup.qml
=> fix: group info font

ui/app/AppLayouts/Chat/components/ProfilePopup.qml
=> don't allow username change for own user

.gitmodules
As mentioned in https://github.com/status-im/status-desktop/pull/2489/files#r626020553
=> chore: remove wrong git submodule

ui/app/AppLayouts/Profile/Sections/AdvancedContainer.qml
fixes #2427 for now we'll just hide this toggle until we have more stuff in the node tab
=> hide node tab toggle for now

ui/shared/status/StatusChatInput.qml
=> fix text formatter icons size & pixelation

ui/imports/Themes/DarkTheme.qml, ui/imports/Themes/LightTheme.qml, ui/imports/Themes/Theme.qml, ui/imports/Utils.qml
=> make url color blue

ui/app/AppLayouts/Chat/ChatColumn.qml, ui/app/AppMain.qml, ui/main.qml
=> Enable image drag/drop in communities

ui/app/AppLayouts/Chat/ContactsColumn/EmptyView.qml
=> use StatusIconButton component to avoid pixelized close button

ui/app/AppLayouts/Chat/components/ChannelContextMenu.qml
=> show confirmation dialog when leaving chat

ui/shared/status/StatusChatInput.qml
=> fix(Input): fix mention formation on rewriting a mention

ui/app/AppLayouts/Chat/CommunityComponents/CommunityList.qml, ui/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopupOverview.qml
=> fix(Community): leave community from Community profile popup

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatText.qml, ui/imports/Themes/DarkTheme.qml, ui/imports/Themes/LightTheme.qml, ui/imports/Themes/Theme.qml, ui/imports/Utils.qml
Fixes: #2388.
Adds a specific background color to hovered mentions.
=> fix: add mention hover

src/nim_status_client.nim, ui/main.qml
Fixes: #2311.
Add an event filter to `qApp` that can detect a dock icon click (in macos) when the main window is hidden or closed.
When the event has been triggered, the main window will be shown again.
Co-authored-by: Boris Melnik <82511785+borismelnik@users.noreply.github.com>
fix: support closing login window using native buttons
After closing the login window using the native "X" button, the application window would not restore correctly when clicking the dock icon. It was putting the application in to an unresponsive state. This PR fixes issue by handling the application window's `onClosing` event and hides the window manually.
~~Both the dependencies `status-im/nimqml` and `status-im/DOtherSide` have versions that are sitting on branches. Their respective PRs (linked below) should …
=> feat: add DockClicker event filter

src/app/chat/view.nim, src/app/chat/views/message_list.nim, src/app/profile/views/contacts.nim, ui/app/AppLayouts/Chat/ChatColumn.qml, ui/app/AppLayouts/Chat/ChatColumn/Message.qml
=> feat: delete messages on block

ui/app/AppLayouts/Browser/provider.js
=> Add missing accountsChanged event to web3 provider

src/app/provider/view.nim
=> fix: add id to signature response

src/app/chat/views/communities.nim, src/status/chat.nim, src/status/libstatus/chat.nim, ui/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopupMembersList.qml
=> feat(Communities): allow admins to ban users

ui/imports/Constants.qml, ui/imports/Utils.qml
=> fix(community): fix community link

src/app/chat/event_handling.nim, src/app/chat/view.nim, src/status/chat.nim, src/status/libstatus/mailservers.nim, src/status/tasks/marathon/mailserver/model.nim, src/status/tasks/marathon/mailserver/worker.nim, ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml, ui/app/AppLayouts/Chat/ChatColumn/Message.qml, ui/app/AppLayouts/Chat/components/ChannelContextMenu.qml
This PR hides the "Fetch Messages" channel context menu item, because wakuext_syncChatFromSyncedFrom does not support specifying a date range
Fixes #2578
=> Fetch more messages using new mailserver API

src/app/chat/event_handling.nim, src/app/chat/view.nim, src/app/chat/views/message_list.nim, src/status/chat.nim, src/status/chat/message.nim, src/status/contacts.nim, src/status/libstatus/chat.nim, src/status/libstatus/mailservers.nim, src/status/signals/messages.nim, src/status/tasks/marathon/mailserver/model.nim, src/status/tasks/marathon/mailserver/worker.nim, ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml, ui/app/AppLayouts/Chat/ChatColumn/Message.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatText.qml, ui/app/AppLayouts/Chat/components/ChannelContextMenu.qml, ui/app/AppLayouts/Chat/components/MessageContextMenu.qml, ui/app/AppLayouts/Chat/components/PrivateChatPopup.qml, ui/app/AppLayouts/Chat/components/ProfilePopup.qml, ui/app/AppLayouts/Chat/components/PublicChatPopup.qml, ui/app/AppLayouts/Chat/components/SuggestedChannel.qml, ui/app/AppLayouts/Profile/Sections/Contacts/Contact.qml, ui/imports/Constants.qml, ui/imports/Utils.qml
Should be merged after a PR for https://github.com/status-im/status-go/tree/chore/add-populate-db-script-rebase is created and merged in status-go develop branch
=> feat: mailserver gaps

ui/app/AppLayouts/Chat/CommunityComponents/CreateChannelPopup.qml
=> fix: hide private channels when creating a community

ui/app/AppLayouts/Chat/CommunityComponents/CommunityMembersPopup.qml, ui/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopupMembersList.qml
=> fix: hide kick and ban options for non-admin users

src/app/profile/views/contacts.nim, src/status/contacts.nim
=> fix: set nickname without creating a contact

src/app/chat/event_handling.nim, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatText.qml
=> feat: use new API for joining/leaving chats

src/app/chat/event_handling.nim
=> fix(Communities): disable chat input when active user is banned

src/status/chat.nim, src/status/libstatus/chat.nim, ui/app/AppLayouts/Chat/ChatColumn/ActivityCenter.qml
Fixes #2609
It doesn't yet follow the design as there is work to do on status-go to add contact requests to the activity center API. I added a new issue to handle it: https://github.com/status-im/status-desktop/issues/2616
For now, this PR does the job to have the contact requests in the activity center in a quick and easy way.
=> Add contact requests to the activity center

src/app/chat/view.nim
Fixes: #2618.
The main culprit was that `self.pinnedMessagesList` did not contain the `self.activeChannel.id` because it was incorrectly upserted in `upsertChannel`.
To fix this, `upsertChannel` was split between upserting a channel in `self.messagesList` (in `upsertChannel`) and upserting a channel in `self.pinnedMessagesList` (in `upsertPinnedChannel`).
Nil checks were added to parsing the messages RPC response in case specific fields were not returned in the response.
In addition, a copy/paste error was fixed in `asyncMessageLoadTask`.
The bad commit was https://github.com/status-im/status-desktop/commit/b52dceb984b3bb1a15173cac925408bd11dbeb8b.
=> fix: Timeline view crash with SIGSEGV when loaded

ui/shared/MacTrafficLights.qml
fixes https://github.com/status-im/status-desktop/issues/1266
=> feat: Add inactive colors for window title bar

ui/app/AppMain.qml, ui/nim-status-client.pro, ui/shared/GasSelector.qml, ui/shared/GasSelectorButton.qml, ui/shared/GasValidator.qml
Fixes #2536
Probably also fixes the gas validation error on ENS
=> Wallet gas selector redesign

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/InvitationBubble.qml
=> fix: display "View" on already joined community invites

src/app/chat/event_handling.nim
=> Remove community from list after being kicked/banned from it

ui/app/AppLayouts/Chat/ChatColumn.qml, ui/app/AppLayouts/Chat/ChatLayout.qml, ui/app/AppLayouts/Chat/CommunityColumn.qml, ui/app/AppLayouts/Chat/CommunityComponents/CreateChannelPopup.qml, ui/app/AppMain.qml
=> feat: add pin messages button to edit channel popup

ui/app/AppLayouts/Chat/ChatColumn.qml, ui/app/AppLayouts/Chat/ChatColumn/ActivityCenter.qml, ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml, ui/app/AppLayouts/Chat/ChatColumn/Message.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatButtons.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/CompactMessage.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/MessageMouseArea.qml
=> feat(act-center): scroll to the clicked message in the act center

src/app/chat/view.nim, src/app/chat/views/activity_notification_list.nim, src/status/chat.nim, ui/app/AppLayouts/Chat/ChatColumn/ActivityCenter.qml
=> feat: add show more button to activity center

ui/app/AppLayouts/Chat/ChatColumn/ActivityCenter.qml, ui/app/AppLayouts/Chat/ChatColumn/ChatComponents/ActivityCenterTopBar.qml
=> feat(act-center): hide viewed notifications when clicking the hide btn

src/app/chat/view.nim, src/status/libstatus/chat.nim, src/status/signals/messages.nim
Do not merge until https://github.com/status-im/status-go/pull/2250 is merged
=> fix: fix pinnedBy not being right when reopening the app

src/app/chat/views/activity_notification_list.nim, src/app/chat/views/communities.nim, src/status/chat.nim, src/status/libstatus/chat.nim, ui/app/AppLayouts/Chat/ChatColumn/ActivityCenter.qml
Fixes #2663
Don't merge until the status-go PR is merged (https://github.com/status-im/status-go/pull/2256)
=> feat: make it possible to mark individual as read

ui/app/AppLayouts/Profile/ProfileLayout.qml
=> refactor(ProfileLayout): make use of StatusQ layout components

ui/app/AppLayouts/Chat/ChatColumn.qml
Fixes #2533
https://user-images.githubusercontent.com/1106587/121940982-b4247a80-cd1c-11eb-911c-8159e2345c49.mp4
=> fix: invalid variable being used for identicons in transaction commands

ui/app/AppLayouts/Chat/ChatLayout.qml, ui/app/AppLayouts/Profile/ProfileLayout.qml, ui/app/AppLayouts/Wallet/SeedPhraseBackupWarning.qml, ui/app/AppLayouts/Wallet/WalletLayout.qml
These changes don't cause a visual change, but just make use of the
two panel layout component providedby StatusQ.
Closes #2688
=> refactor(ChatLayout): use StatusQ layout component to lay out view

src/app/chat/view.nim, src/app/chat/views/activity_notification_list.nim, src/app/chat/views/community_list.nim, src/status/chat.nim, ui/app/AppLayouts/Chat/ChatColumn/ActivityCenter.qml, ui/app/AppLayouts/Chat/ChatColumn/ChatComponents/ActivityChannelBadge.qml
=> feat(act-center): add community badge with link to community and channel

src/app/chat/core.nim, src/app/chat/signal_handling.nim, src/app/chat/view.nim, src/app/chat/views/messages.nim, ui/app/AppLayouts/Chat/ChatColumn.qml, ui/app/AppLayouts/Chat/ChatColumn/ChatComponents/ActivityChannelBadge.qml, ui/app/AppLayouts/Chat/ChatColumn/ChatComponents/InputArea.qml, ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml, ui/app/AppLayouts/Chat/ChatColumn/Message.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatReply.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/Retry.qml, ui/app/AppLayouts/Chat/CommunityComponents/CommunityButton.qml, ui/app/AppLayouts/Chat/CommunityComponents/CreateChannelPopup.qml, ui/app/AppLayouts/Chat/ContactsColumn/ChannelList.qml, ui/app/AppLayouts/Chat/components/FetchMoreMessages.qml, ui/app/AppLayouts/Chat/components/GroupInfoPopup.qml, ui/app/AppLayouts/Chat/components/MessageContextMenu.qml, ui/app/AppLayouts/Chat/components/PinnedMessagesPopup.qml, ui/app/AppLayouts/Timeline/TimelineLayout.qml, ui/app/AppMain.qml, ui/shared/SearchResults.qml, ui/shared/status/StatusChatInfo.qml
refactor: extract messages from chat view
refactor: extract messages from chat view
refactor: extract messages from chat view
update references to messageView
fix setup
remove duplicated method
=> refactor: extract messages from chat view

ui/shared/GasSelector.qml, ui/shared/GasValidator.qml
=> fix(wallet): fix gas price being 0 and add back validation

src/app/wallet/view.nim, src/app/wallet/views/balance.nim, src/app/wallet/views/history.nim, src/app/wallet/views/transaction_list.nim, src/app/wallet/views/transactions.nim, src/status/wallet.nim, ui/app/AppLayouts/Wallet/HistoryTab.qml
=> fix(hisotry): fix load more history button

ui/app/AppLayouts/Chat/CommunityColumn.qml, ui/app/AppLayouts/Chat/CommunityComponents/CommunityHeaderButton.qml, ui/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopup.qml
UI issue is fixed, additional similar issue is fixed in CommunityProfilePopup.qml.
Closes: #2492
=> fix(Communities) Long community names should be truncated

ui/app/AppLayouts/Chat/CommunityColumn.qml, ui/app/AppLayouts/Chat/CommunityComponents/BackUpCommuntyBanner.qml, ui/app/AppLayouts/Chat/CommunityComponents/CategoryList.qml, ui/app/AppLayouts/Chat/CommunityComponents/CommunityWelcomeBanner.qml
Fixes: #2547
Mouse areas added to qml files prevent sending right mouse button event to the mouse area placed in scroll view which is beneath all those qml components.
=> fix(communities): Right click inside the community pane does not open context menu

ui/app/AppLayouts/Browser/BrowserLayout.qml, ui/app/AppLayouts/Profile/Sections/Ens/TermsAndConditions.qml
Fixed issues #2560, #2795, #2796.
=> Fixed issues #2560, #2795, #2796.

src/app/profile/core.nim, src/app/profile/view.nim, src/app/profile/views/muted_chats.nim, src/app/profile/views/profile_picture.nim, src/app/profile/views/profile_settings.nim, src/app/provider/view.nim, ui/app/AppLayouts/Profile/Sections/ChangeProfilePicModal.qml, ui/app/AppLayouts/Profile/Sections/MutedChatsModal.qml, ui/app/AppLayouts/Profile/Sections/NotificationsContainer.qml, ui/app/AppMain.qml, ui/main.qml
=> refactor: Profile

src/app/chat/views/communities.nim, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/InvitationBubble.qml, ui/imports/Utils.qml
=> fix(communities): fix duplicated communities and joining through link

src/app/chat/views/channel.nim
=> fix(community): fix crash on going back to chats from community

src/app/chat/views/communities.nim, src/app/chat/views/community_item.nim, src/app/chat/views/community_list.nim, src/status/chat.nim, src/status/chat/chat.nim, src/status/libstatus/chat.nim, src/status/signals/messages.nim, ui/app/AppLayouts/Chat/CommunityColumn.qml, ui/app/AppLayouts/Chat/CommunityComponents/BackUpCommuntyBanner.qml, ui/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopupOverview.qml
Fixes #2421
When the Notification setting is unchecked, you don't receive OS notifications for new messages
~~Do not merge until the status go is merged: https://github.com/status-im/status-go/pull/2271~~ Merged
=> feat(community): add notification setting to community

ui/onboarding/BeforeGetStartedModal.qml
Privacy policy does not belong to the mandatory checkbox fields.
Fixes: #2804
=> fix(enhancement): Onboarding screen changes

src/app/chat/views/chat_item.nim, ui/app/AppLayouts/Chat/ChatColumn/Message.qml
=> Starting a group chat shouldn't show the section to fetch more messages.

src/app/wallet/views/transactions.nim, src/status/provider.nim, src/status/utils.nim, ui/app/AppLayouts/Chat/ChatColumn/ChatComponents/SignTransactionModal.qml, ui/app/AppLayouts/Wallet/SendModal.qml
=> refactor: separate slots for sending eth and tokens

src/app/chat/core.nim, src/app/chat/views/activity_notification_list.nim, src/status/chat.nim, src/status/chat/chat.nim, src/status/libstatus/chat.nim, src/status/signals/messages.nim, ui/app/AppLayouts/Chat/ChatColumn/ActivityCenter.qml, ui/app/AppLayouts/Chat/ChatColumn/ChatComponents/ActivityCenterGroupRequest.qml, ui/app/AppLayouts/Chat/ChatColumn/ChatComponents/ActivityCenterMessageComponent.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/CompactMessage.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/DateGroup.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/NormalMessage.qml, ui/app/AppLayouts/Chat/components/AcceptRejectOptionsButtons.qml, ui/app/AppLayouts/Chat/components/ContactRequest.qml, ui/imports/Constants.qml, ui/nim-status-client.pro
Fixes #2679
Do not merge until https://github.com/status-im/status-go/pull/2260 is merged
~~There is a known issue with the unread messages not updating correctly. It will be fixed with this issue https://github.com/status-im/status-desktop/issues/2727~~
=> feat: add group requests to the activity center

src/app/chat/views/message_list.nim, src/app/chat/views/user_list.nim, src/status/provider.nim, ui/app/AppLayouts/Chat/ChatColumn.qml, ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml, ui/app/AppLayouts/Chat/ChatColumn/TopBar.qml, ui/app/AppLayouts/Chat/ChatColumn/User.qml, ui/app/AppLayouts/Chat/ChatColumn/UserList.qml, ui/app/AppLayouts/Profile/Sections/AdvancedContainer.qml, ui/app/AppMain.qml, ui/imports/Themes/DarkTheme.qml, ui/imports/Themes/LightTheme.qml
=> feat: user list

ui/app/AppMain.qml, ui/shared/status/StatusEmojiPopup.qml, ui/shared/status/StatusEmojiSection.qml
* Icon was there but feature was not implemented
fixes #2534
=> [#2534] Adding emoji skin color selector in chat

ui/app/AppLayouts/Chat/components/GroupInfoPopup.qml, ui/app/AppLayouts/Chat/components/ProfilePopup.qml
=> Fixed #2430: Add members window shown when accessing 1x1 chat within group chat

src/app/chat/views/message_list.nim, src/app/chat/views/messages.nim
=> Fixes #2789: crash when pinning a message

src/app/chat/view.nim, ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml, ui/app/AppLayouts/Chat/ChatColumn/Message.qml, ui/app/AppLayouts/Timeline/TimelineLayout.qml
=> fix(@desktop/chat): Timeline shows wrong messages

ui/app/AppLayouts/Chat/ChatColumn/Message.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatText.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/StatusUpdate.qml, ui/app/AppLayouts/Timeline/TimelineLayout.qml
=> fix(@desktop/timeline): can't click the links and hashtags in timeline

ui/app/AppLayouts/Profile/Sections/BackupSeedModal.qml, ui/main.qml, ui/onboarding/ExistingKey.qml, ui/onboarding/KeysMain.qml
Fixes #2657
Also fixes the text color in the backup seed phrase modal
=> Fixes blank screen when closing the re-encrypt modal in the onboarding

ui/imports/Themes/DarkTheme.qml, ui/imports/Themes/LightTheme.qml, ui/shared/AssetAndAmountInput.qml, ui/shared/Input.qml, ui/shared/SearchResults.qml
=> fix(wallet): make it possible to send a 0 tx with a warning

ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml
=> fix: crash on chatmessages when using 5.15.2 

ui/app/AppLayouts/Chat/ChatColumn/SuggestionBox.qml, ui/app/AppLayouts/Chat/ChatColumn/SuggestionFilter.qml, ui/shared/status/StatusChatInput.qml
=> feat(mentions): show mentions ordered by how it matches the filter

src/status/libstatus/core.nim, src/status/wallet/collectibles.nim
fixes #2645 
Before:
Iterate until we have an error, this was the cause of the trace
After:
First, fetch the balance in order to know how many times we need to iterate
Also, I added writeStackTrace call when there is an error. This is to help debugging isues with rpc call
=> fix(@desktop/wallet): Iterate over collectible with balance

ui/shared/status/StatusChatInput.qml
For example, typing :D should turn into 😁
Closes #1608
=> [#1608] convert text to emoji automatically

ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml, ui/app/AppLayouts/Chat/ChatColumn/Message.qml
There are a bunch of references and expressions that are invalid.
This commit fixes them.
=> fix(@desktop/chat): fix various expression bugs in chat messages

ui/app/AppLayouts/Chat/components/ContactRequestsPopup.qml
fixes #2853
Same bug has been fixed for accept all request
=> fix(@desktop/profile): decline all request when big pending request list

ui/app/AppLayouts/Chat/ChatColumn/Message.qml, ui/app/AppLayouts/Chat/components/GroupInfoPopup.qml, ui/app/AppLayouts/Timeline/TimelineLayout.qml, ui/imports/Utils.qml, ui/shared/NoFriendsRectangle.qml, ui/shared/status/StatusChatImageQtyValidator.qml, ui/shared/status/StatusChatInput.qml, ui/shared/status/StatusChatInputImageArea.qml
=> fix(@desktop/timeline): timeline and images area bugfixes

src/app/chat/views/channel.nim, src/app/profile/views/muted_chats.nim, ui/app/AppLayouts/Profile/Sections/MutedChatsModal.qml
fixes #2557
https://user-images.githubusercontent.com/491074/125428325-5a768502-4df0-4af8-8de2-db8461a9a3b4.mp4
I also did some cleaning of code that *looks* dead. Is it fair to assume that a search and the fact that nim compile prove it ok?
=> fix(@desktop/profile): Unmuted chat from profile -> notification

ui/app/AppLayouts/Chat/components/ChatContextMenu.qml
=> fix(@desktop/chat): nickname disapear when closing the modal

ui/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopupOverview.qml
It should be red instead of blue
Closes #2398
=> [#2398] Updating "leave community" button color

ui/app/AppLayouts/Profile/Sections/ContactsContainer.qml, ui/shared/ContactsListAndSearch.qml
* Also removed from adding new chat
Closes #2376
=> [#2376] Removed invalid error message when adding new contact

src/app/chat/views/messages.nim, src/status/tasks/marathon/mailserver/model.nim, src/status/tasks/marathon/mailserver/worker.nim, ui/app/AppLayouts/Timeline/TimelineLayout.qml
=> fix(@desktop): windows application unresponsive when fetching messages

ui/app/AppLayouts/Chat/CommunityColumn.qml, ui/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopup.qml, ui/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopupInviteFriendsView.qml, ui/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopupMembersList.qml, ui/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopupOverview.qml, ui/app/AppLayouts/Chat/components/PrivateChatPopup.qml, ui/app/AppMain.qml, ui/shared/AddressInput.qml, ui/shared/ContactsListAndSearch.qml
Also add default `height` as it otherwise breaks UI in other places.
=> fix(ContactsListAndSearch): ensure component doesn't depend on `parent`

ui/app/AppLayouts/Chat/CommunityColumn.qml, ui/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopup.qml, ui/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopupInviteFriendsView.qml, ui/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopupMembersList.qml, ui/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopupOverview.qml, ui/app/AppLayouts/Chat/components/PrivateChatPopup.qml, ui/app/AppMain.qml, ui/shared/AddressInput.qml, ui/shared/ContactsListAndSearch.qml
=> ui(@desktop/chat): fine-tune chat info button position

src/app/node/core.nim, src/app/node/view.nim, src/nim_status_client.nim, src/status/accounts.nim, src/status/libstatus/accounts.nim, src/status/types.nim, ui/app/AppLayouts/Profile/Sections/AdvancedContainer.qml
=> feat: waku bloom filter mode switch

ui/shared/Input.qml, ui/shared/status/StatusChatInput.qml
[#2650] Fixed pasting rich text in text box
* Text copied from clipboard that included images
and other rich content was not visible in text
box when pasted, modified to keep only plain
text instead and removed unnecessary funtions
* Also removed unecessary Rectangle in Input
Closes #2650
=> [#2650] Fixed pasting rich text in text box

src/app/chat/event_handling.nim
=> fix(@desktop/communities): update communities chat

ui/app/AppLayouts/Chat/CommunityComponents/CreateCommunityPopup.qml, ui/app/AppLayouts/Chat/ContactsColumn.qml, ui/app/AppMain.qml
This replaces the modal popup with `StatusModal` in the `CreateCommunityPopup`
and also ensures that it adheres to the design.
There are still things to be refactored in here, primarily form control components.
Those will be tackled in future commits once they have been built in StatusQ
Closes #2882
=> refactor(Communities): use `StatusModal` in `CreateCommunityPopup`

ui/app/AppLayouts/Chat/CommunityComponents/TransferOwnershipPopup.qml
=> refactor(Communities): use `StatusModal` in `TransferOwnershipPopup`

src/status/chat.nim
=> fix(@desktop/chat): mentions badge cleanup

ui/app/AppLayouts/Chat/CommunityComponents/BackUpCommuntyBanner.qml
Key icon color was wrong at the community
welcome message
Closes #2550
=> [#2550] Fixed wrong color in key icon

Makefile, ci/Jenkinsfile.windows, scripts/windows_build_setup.ps1, status.iss
=> feat(widnows-installer): Add compilation windows installer build step

ui/app/AppLayouts/Chat/ChatColumn.qml, ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml, ui/app/AppLayouts/Chat/ChatColumn/Message.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatButtons.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/CompactMessage.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/EmojiReactions.qml, ui/app/AppLayouts/Chat/components/MessageContextMenu.qml
* Also replaces usage of synamic scoping with properties,
signals and functions where possible
Closes #2386
=> [#2386] Fixed inline emoji reaction menu not showing on top of message

ui/app/AppLayouts/Chat/CommunityColumn.qml, ui/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopupMembersList.qml, ui/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopupOverview.qml, ui/app/AppLayouts/Chat/CommunityComponents/CreateChannelPopup.qml, ui/app/AppLayouts/Chat/CommunityComponents/MembershipRequestsPopup.qml
=> refactor(Communities): use `StatusModal` in `MembershipRequestsPopup`

src/app/chat/views/groups.nim, src/status/chat.nim, src/status/libstatus/chat.nim, ui/imports/Utils.qml
Fixes #2676
The group chat is still not usable. It is missing the feature to request access to the group chat.
That feature will first require a design as we don't have that designed in desktop.
This is the issue that will implement the request https://github.com/status-im/status-desktop/issues/2962
=> feat(link): handle group chat invite links

ui/app/AppLayouts/Wallet/components/AddAccount.qml, ui/shared/Input.qml, ui/shared/SVGImage.qml
Fixes #2752.
Also, fixed a couple of very annoying QML warnings.
=> fix(@desktop/wallet): add account modal is not being closed

src/status/signals/messages.nim, ui/app/AppLayouts/Chat/ChatColumn.qml, ui/app/AppLayouts/Chat/ChatColumn/ActivityCenter.qml, ui/app/AppLayouts/Chat/ChatColumn/ChatComponents/ActivityCenterMessageComponent.qml, ui/app/AppLayouts/Chat/ChatColumn/ChatComponents/ActivityChannelBadge.qml, ui/app/AppLayouts/Chat/ChatColumn/ChatComponents/ChatRequestMessage.qml, ui/imports/Constants.qml
Fixes #2830
This makes it possible for mobile and desktop to 1-1 well
=> Unblock input box when not mutual contact and add 1-1 messages to activity center

src/app/chat/event_handling.nim, src/app/chat/signal_handling.nim, src/app/chat/views/communities.nim, src/app/chat/views/community_item.nim, src/app/chat/views/community_list.nim, src/app/chat/views/messages.nim, src/app/profile/core.nim, src/app/profile/view.nim, src/app/profile/views/profile_info.nim, src/status/chat.nim, src/status/chat/chat.nim, src/status/libstatus/chat.nim, src/status/profile/profile.nim, src/status/signals/messages.nim, src/status/signals/types.nim, src/status/types.nim, ui/app/AppLayouts/Chat/ChatColumn/User.qml, ui/app/AppLayouts/Chat/CommunityComponents/CommunityUserList.qml, ui/app/AppLayouts/Profile/Sections/AdvancedContainer.qml, ui/imports/Constants.qml
=> feat: show status of community members

src/nim_status_client.nim, ui/main.qml
Fixes #2919 
Do not merge before https://github.com/status-im/dotherside/pull/29 and https://github.com/status-im/nimqml/pull/21 are merged.
=> fix(@desktop): missing context menu on SystemTrayIcon

ui/main.qml
Closes: #2930 
Can be merge after https://github.com/status-im/dotherside/pull/30
=> fix: Update window position to center

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/InvitationBubble.qml
For performance reasons clipping doesn't work
with rounded corners - wrapping "Join" button in
an Item and apply clipping there instead
Closes #2563
=> [#2563] Fixed hover over Join button has wrong shape

ui/app/AppLayouts/Chat/ChatLayout.qml, ui/app/AppLayouts/Chat/ContactsColumn.qml, ui/app/AppLayouts/Chat/components/PrivateChatPopup.qml, ui/app/AppLayouts/Profile/LeftTab.qml, ui/app/AppLayouts/Profile/LeftTab/Menu.qml, ui/app/AppLayouts/Profile/LeftTab/components/MenuButton.qml, ui/app/AppLayouts/Profile/ProfileLayout.qml, ui/app/AppMain.qml, ui/imports/Config.qml, ui/imports/qmldir
My profile link was not shown when starting 1x1 chat
having someone in contacts as it is currently the case in
mobile app
Closes #2707
=> [#2707] Added "My Profile" button in new chat popup

src/app/chat/views/community_item.nim
=> fix(@desktop/communities): pending membership counter

src/nim_status_client.nim, ui/main.qml, ui/onboarding/Login.qml
Fixes #2603
Fixes #2843 
Additionally, updated UI for Login view - confirmed with Simon.
=> fix(@desktop/login): crash on login and login ux improvements

ui/imports/Utils.qml, ui/nim-status-client.pro, ui/onboarding/CreatePasswordModal.qml, ui/onboarding/GenKeyModal.qml
- The arrow in select chat name was not
from StatusQ
- The text in case of password missmatch
was wrongly displayed
- The loading icon color was not from StatusQ
Closes #2762
=> [#2672] Fixed onboarding bugs

src/app/chat/views/community_members_list.nim, ui/app/AppLayouts/Chat/ChatColumn.qml
=> fix: limit suggestions to member list in communities

src/app/chat/view.nim, src/app/chat/views/message_list.nim
=> fix: fix pin counter not updating for communities

ui/app/AppLayouts/Chat/ChatColumn.qml, ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml
=> fix(@desktop/chat): incorrect timestamp evaluation

src/app/utils/image_utils.nim
fixes #3034
I didn't check windows upload but that should not have impact... hopefully ;)#
It should solve all upload with a specific character
=> fix(@desktop/chat): fix upload of image with special characters

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/LinksMessage.qml
=> feat(chat): add unfurling message for images

src/app/chat/views/communities.nim
fixes #2826
When fetching communities, the chat attached to it are not complete.
In this commit, we ensure that everytime we fetch a community, we update
its chat with the chat being loaded which contains all the data we need
to properly display a chat
@jrainville what do you think of this strategy?
=> fix(@desktop/communities): Community chat colors stays up to date

ui/app/AppLayouts/Chat/CommunityComponents/CommunityDetailPopup.qml
=> fix(CommunityDetailPopup): ensure description wraps properly

ui/app/AppLayouts/Chat/ChatColumn.qml, ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml, ui/app/AppLayouts/Chat/ChatColumn/UserList.qml, ui/app/AppLayouts/Chat/ChatLayout.qml, ui/app/AppLayouts/Chat/CommunityColumn.qml, ui/app/AppLayouts/Chat/CommunityComponents/CommunityUserList.qml, ui/app/AppLayouts/Chat/ContactsColumn.qml
Switched to StatusAppThreePanelLayout as per new
design for members list
Depends on https://github.com/status-im/StatusQ/pull/283
Closes #2813
=> [#2813] Updating chat layout

src/app/chat/event_handling.nim, src/app/chat/signal_handling.nim, src/app/chat/view.nim, src/app/chat/views/messages.nim, src/status/chat.nim, src/status/chat/message.nim, src/status/libstatus/chat.nim, src/status/signals/messages.nim, src/status/signals/types.nim, ui/app/AppLayouts/Chat/ChatColumn/Message.qml, ui/app/AppLayouts/Chat/components/MessageContextMenu.qml, ui/app/AppMain.qml, ui/imports/Themes/DarkTheme.qml, ui/imports/Themes/LightTheme.qml, ui/shared/ConfirmationDialog.qml, ui/shared/PopupMenu.qml, ui/shared/status/StatusChatInput.qml
Fixes #2775
Do not merge until https://github.com/status-im/status-go/pull/2279 is merged
=> Enable deleting messages

ui/app/AppLayouts/Chat/ChatColumn/ChatComponents/ActivityCenterMessageComponent.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/InvitationBubble.qml
=> Fix mark as read in the activity center

ui/app/AppLayouts/Chat/ChatColumn/UserList.qml, ui/app/AppLayouts/Chat/CommunityComponents/CommunityUserList.qml
* Added clipping and scrollbar in user lists
=> [#2813] Fixing chat layout bugs

ui/main.qml
fixes #3006  (credit to @pinebit )
=> fix(@core): issue #3006 fix for cpu usage issue

ui/shared/status/StatusChatInput.qml
=> fix(@desktop/chat): ensure edit message input uses correct theme color

ui/app/AppMain.qml, ui/main.qml
=> fix(@desktop/onboarding): erase mnemonic when register with existing key

src/app/chat/views/channel.nim, ui/app/AppLayouts/Chat/ChatColumn/Message.qml, ui/app/AppLayouts/Chat/components/MessageContextMenu.qml, ui/app/AppLayouts/Chat/components/ProfilePopup.qml, ui/app/AppLayouts/Profile/Sections/Ens/List.qml, ui/app/AppLayouts/Profile/Sections/MyProfileContainer.qml, ui/imports/Utils.qml
=> fix: Display current user's ENS in profile and share URL

ui/app/AppLayouts/Chat/CommunityComponents/CommunitiesPopup.qml
=> fix(@desktop/communities): fix translation for members count

ui/app/AppLayouts/Chat/CommunityComponents/CreateCommunityPopup.qml
Needs this StatusQ change https://github.com/status-im/StatusQ/pull/302
Fixes https://github.com/status-im/status-desktop/issues/3095
=> fix(community): lock community type to on request

ui/app/AppLayouts/Chat/components/PrivateChatPopup.qml
=> [#3119] Fixiing profile picture not correct in add new chat popup

src/app/chat/views/communities.nim, src/app/chat/views/community_list.nim, src/status/chat.nim, src/status/libstatus/chat.nim, ui/app/AppLayouts/Chat/components/ChatContextMenu.qml
Fixes #2734
Do not merge until the status-go PR is merged: https://github.com/status-im/status-go/pull/2266
=> feat(communities): add delete community channel feature

src/app/chat/event_handling.nim, src/app/chat/view.nim, src/app/chat/views/chat_members.nim, src/app/chat/views/message_list.nim, src/app/chat/views/messages.nim, src/app/chat/views/user_list.nim, ui/app/AppLayouts/Chat/components/GroupInfoPopup.qml
=> fix: group member list

ui/shared/GasSelector.qml
=> fix(@desktop/wallet): Do not allow decimal number for gas limit

ui/shared/status/StatusChatInput.qml
=> fix(@desktop/timeline): profile picture is not updated in timeline

src/app/node/core.nim, src/app/node/view.nim, src/status/signals/core.nim, src/status/signals/stats.nim, src/status/signals/types.nim, src/status/types.nim, ui/app/AppLayouts/Node/NodeLayout.qml, ui/app/AppLayouts/Node/Rate.qml, ui/app/AppLayouts/Profile/Sections/AdvancedContainer.qml, ui/app/AppMain.qml
=> feat: bandwidth stats

src/app/wallet/view.nim
=> fix(@desktop/wallet): load collectible on initial account set

ui/app/AppLayouts/Profile/Sections/ContactsContainer.qml
fixes #3046
also fix the fact that the query is only triggered when the text is changed
vs when pressing any key
=> fix(@desktop/profile): handle empty text in add contact properly

ui/app/AppLayouts/Chat/components/MessageContextMenu.qml
=> feat(@desktop/chat): disable copy to clipboard when clicking on profile

src/app/chat/event_handling.nim, src/status/contacts.nim
fixes #2708
When blocking a contact, if there is a chat open, close it
=> fix(@desktop/profile): remove chat when blocking contact

ui/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopupInviteFriendsView.qml, ui/shared/ContactsListAndSearch.qml
fixes #3053
Align invite popup with design
=> fix(@desktop/communities): Remove search from invite

src/status/types.nim
=> fix: etherchains api parsing error

ui/app/AppLayouts/Chat/components/ChooseBrowserPopup.qml
fixes #3155
Also when remembering the choice, update the settings
=> fix(@desktop/browser): close popup when opening link

ui/app/AppLayouts/Profile/Sections/Contacts/Contact.qml
fixes #3158
First change area then activate the channel
=> fix(@desktop/profile): fix click on contact

ui/app/AppLayouts/Chat/ContactsColumn.qml, ui/app/AppMain.qml
=> fix(@desktop/communities): hide communities if not enabled

ui/app/AppLayouts/Profile/Sections/AdvancedContainer.qml
We have quite a few advance settings, allow to see them all via scroll
=> fix(@desktop/profile): Add scroll bar for advance settings

ui/app/AppMain.qml, ui/main.qml
=> fix(@desktop/communities): fix sharing community link

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatReply.qml, ui/imports/Themes/Theme.qml, ui/imports/Utils.qml
Updated the style of mention text when replying to one
fixes #3012
=> fix(@desktop/chat): mention color is too bright when replying

src/app/profile/core.nim, src/app/profile/view.nim, src/app/profile/views/profile_info.nim, src/status/profile/profile.nim, src/status/types.nim, ui/app/AppLayouts/Chat/ChatLayout.qml, ui/app/AppLayouts/Profile/Sections/AdvancedContainer.qml, ui/app/AppMain.qml, ui/shared/PopupMenu.qml, ui/shared/UserStatusContextMenu.qml, ui/shared/img/offline.svg, ui/shared/img/online.svg
=> feat: selector for online or invisible state

src/status/libstatus/stickers.nim, src/status/wallet.nim, src/status/wallet/balance_manager.nim
=> add missing http client close() so it doesn't run out of files

ui/app/AppLayouts/Profile/Sections/AdvancedContainer.qml, ui/app/AppLayouts/Profile/Sections/Ens/Welcome.qml, ui/app/AppLayouts/Profile/Sections/EnsContainer.qml, ui/app/AppMain.qml, ui/shared/status/StatusChatInput.qml
=> fix(@desktop/settings): Enable stickers/ens on ropsten

src/status/wallet/balance_manager.nim
fixes #3054
Before:
Total was only the total of ETH
After:
Total is the sum of all account asset (including eth)
=> fix(@desktop/wallet): Total balance reflect real total

src/app/profile/core.nim
fixes #3191
When retrieving keys, this value is nil
=> fix(@desktop/onboarding): fix crash when restoring keys

ui/app/AppLayouts/Chat/ChatColumn.qml, ui/app/AppLayouts/Chat/ChatColumn/Message.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatButtons.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/CompactMessage.qml, ui/app/AppLayouts/Chat/ChatColumn/User.qml, ui/app/AppLayouts/Chat/ChatColumn/UserList.qml, ui/app/AppLayouts/Chat/ChatLayout.qml, ui/app/AppLayouts/Chat/components/MessageContextMenu.qml
Updated from PopupMenu to StatusPopMenu. Removed buttons not in design.
Also added left and right button functionality on member list
fixes #2956, #3162
=> fix(@desktop/chat): pin button is blurred

src/app/login/core.nim, src/app/login/view.nim, src/app/onboarding/core.nim, src/app/onboarding/view.nim, src/nim_status_client.nim, ui/main.qml
=> fix(@desktop): crash when transitioning to the app state

src/status/wallet.nim
fixes #3141
Follow up of this commit: https://github.com/status-im/status-desktop/commit/3a042a4a09f74cb8099394ff948c24327b6cb37d
The field used is additionalData and not data
=> fix(@desktop/wallet): Use the new pending tx API for pending tx

src/app/wallet/view.nim, src/nim_status_client.nim
Fixes #3202 
Unfortunately I was unable to reproduce this issue, so this fix is based on the stacktrace shown by @anastasiyaig and after little brainstorming with @alaibe
=> fix(@desktop): crash on shutdown path

status.iss
=> fix(@desktop/installer): further improving of Inno Setup script

ui/app/AppLayouts/Wallet/LeftTab.qml, ui/shared/polyfill.number.toLocaleString.js
Added logic to round of large amounts to Millions and Billions.
fixes #2667
=> fix(@desktop/wallet) Truncate long wallet amount

ui/app/AppLayouts/Browser/FavoritesBar.qml
=> fix(@desktop/browser): hide favorite bar when there is none

ui/app/AppMain.qml
=> fix(@desktop/chat): fix shortcut for chat from communities

ui/app/AppLayouts/Profile/Sections/ContactsContainer.qml, ui/imports/Utils.qml
=> fix: display ENS on contact search results

src/app/chat/event_handling.nim, src/app/profile/views/contacts.nim, src/status/contacts.nim, src/status/libstatus/contacts.nim, src/status/profile/profile.nim, ui/app/AppLayouts/Chat/ChatColumn.qml, ui/app/AppLayouts/Chat/ChatColumn/ChatComponents/InputArea.qml, ui/app/AppLayouts/Chat/components/ContactList.qml, ui/app/AppLayouts/Profile/Sections/Contacts/ContactList.qml, ui/app/AppLayouts/Profile/Sections/ContactsContainer.qml, ui/app/AppMain.qml, ui/shared/BlockContactConfirmationDialog.qml, ui/shared/ExistingContacts.qml, ui/shared/status/StatusChatInput.qml
fixes #3047
See issues for full summary but TLDR:
* When blocking a contact, do not delete the chat & messages, keep him as contact, only update the system tags
* Update the chat UI to reflect that the contact is blocked
* Ensure that the blocked contact doesn't appear in the list of non blocked contact
=> feat(@desktop/profile): handle blocked contact

src/app/chat/views/channel.nim
=> fix(@desktop/chat): Going from communities to chat reopen latest opened

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/CompactMessage.qml, ui/app/AppLayouts/Chat/components/MessageContextMenu.qml, ui/app/AppLayouts/Chat/components/PinnedMessagesPopup.qml
=> fix(@desktop/pinned): proper popup menu for pinned messages dialog

src/app/chat/views/stickers.nim, src/status/chat.nim, src/status/libstatus/chat.nim, ui/app/AppLayouts/Chat/ChatColumn.qml, ui/shared/status/StatusChatInput.qml
=> fix(desktop/chatmessages) fixed stickers can't be used as reply

ui/shared/status/StatusChatInput.qml
And disabling all previous text formatting
Depends on https://github.com/status-im/dotherside/pull/42
Closes #2920
Closes #3063
=> fix(desktop/chat) Adding custom syntax highligther to StatusChatInput

ui/shared/status/StatusChatInput.qml
=> fix(desktop/chatinput) fixed automatic emoji replacement missbehavior

src/app/chat/view.nim, ui/app/AppLayouts/Chat/ChatColumn.qml, ui/app/AppLayouts/Chat/ChatColumn/Message.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/CompactMessage.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ImageLoader.qml, ui/app/AppLayouts/Chat/components/MessageContextMenu.qml, ui/app/AppLayouts/Timeline/TimelineLayout.qml, ui/shared/status/StatusImageModal.qml
Added copy and download Image functionality on right click of an image or its preview
closes #2672
=> feat(MessageContextMenu): Allow Copy and Download Image

src/app/chat/views/community_item.nim, src/app/chat/views/community_members_list.nim, ui/app/AppLayouts/Chat/ChatColumn/User.qml, ui/app/AppLayouts/Chat/CommunityComponents/CommunityUserList.qml, ui/main.qml
=> fix(@desktop/communities): improve member list sorting

src/app/chat/views/communities.nim, ui/app/AppLayouts/Chat/ChatColumn.qml
=> chore(@desktop): odd warnings

ui/app/AppLayouts/Chat/ChatColumn/Message.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/StatusUpdate.qml, ui/app/AppLayouts/Timeline/TimelineLayout.qml
fixes #3251
- Being able to react in timeline chat
- Once there is a reaction, being able to remove them or add new
- Height of the message taking in consideration if there is reaction or
not
=> fix(@desktop/timeline): Fix timeline reaction

src/app/wallet/v2/view.nim, src/app/wallet/v2/views/asset_list.nim, src/app/wallet/v2/views/collectibles.nim, src/app/wallet/v2/views/collection_list.nim, src/status/libstatus/wallet.nim, src/status/wallet.nim, src/status/wallet/account.nim, ui/app/AppLayouts/WalletV2/CollectiblesTab.qml, ui/app/AppLayouts/WalletV2/WalletV2Layout.qml, ui/app/AppLayouts/WalletV2/components/CollectibleCollection.qml, ui/app/AppLayouts/WalletV2/components/CollectibleModal.qml, ui/app/AppLayouts/WalletV2/components/qmldir
Status-go PR: https://github.com/status-im/status-go/pull/2320
=> feat(@desktop/wallet2): New collectibles API

src/app/wallet/v2/views/collectibles.nim
=> fix(@desktop/wallet2): Ensure app not crash when loading collectibles

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/InvitationBubble.qml, ui/app/AppLayouts/Chat/ContactsColumn.qml, ui/app/AppLayouts/Chat/ContactsColumn/EmptyView.qml
Fixes #3260 
and fixes one annoying QML warning in InvitationBubble.qml
=> fix(@desktop/chat): channel suggestions are not being displayed

src/app/chat/event_handling.nim, src/status/chat.nim, src/status/chat/chat.nim, src/status/signals/messages.nim, src/status/signals/types.nim
Depends on https://github.com/status-im/status-go/pull/2324
Fixes #3262
=> switch deletedMessages from string array to object array

src/app/profile/views/ens_manager.nim, src/status/ens.nim, src/status/libstatus/coder.nim, src/status/libstatus/eth/contracts.nim, src/status/libstatus/eth/transactions.nim, ui/app/AppLayouts/Profile/Sections/Ens/ENSDetails.qml, ui/app/AppLayouts/Profile/Sections/Ens/ENSReleased.qml, ui/app/AppLayouts/Profile/Sections/Ens/Search.qml, ui/app/AppLayouts/Profile/Sections/EnsContainer.qml, ui/shared/status/StatusETHTransactionModal.qml, ui/shared/status/StatusSNTTransactionModal.qml
It probably makes sense to test this after https://github.com/status-im/status-desktop/pull/3186 is merged.
Fixes #782
=> feat: release ENS names

src/app/chat/views/communities.nim, src/app/chat/views/community_item.nim, src/app/chat/views/community_members_list.nim, ui/app/AppLayouts/Chat/components/NicknamePopup.qml
=> fix(@desktop/communities): changing contact nickname

ui/app/AppLayouts/Chat/ChatColumn/SuggestionFilter.qml
Avoid extra computation when it is not needed for the suggestion filter
This is quite visible when the member list contains 1000s of members. 
It is the case when you load historical message (1 month).
When you start typing letters, they do not appear immediately
=> perf(@desktop/chat): Improve performance when big member list

ui/app/AppLayouts/Chat/ChatColumn.qml, ui/app/AppLayouts/Chat/ChatColumn/Message.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatButtons.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/CompactMessage.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/LinksMessage.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/MessageMouseArea.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/NormalMessage.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/StatusUpdate.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/UserImage.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/UsernameLabel.qml, ui/app/AppLayouts/Chat/ChatColumn/User.qml, ui/app/AppLayouts/Chat/components/MessageContextMenu.qml, ui/app/AppLayouts/Timeline/TimelineLayout.qml, ui/shared/status/StatusChatImageLoader.qml
Added logic to set parent ,x and y positions from the place where the menu is opened
fixes #2385
=> fix(@desktop/chat): Emoji reaction Menu is incorrect

src/app/chat/views/channel.nim, ui/app/AppLayouts/Chat/CommunityComponents/CreateChannelPopup.qml
=> fix(@desktop/chat): edit channel modal to show up-to-date values

ui/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopupMembersList.qml, ui/app/AppLayouts/Chat/components/ProfilePopup.qml, ui/app/AppLayouts/Timeline/TimelineLayout.qml, ui/app/AppMain.qml
**THIS DEPENDS ON**:
- https://github.com/status-im/StatusQ/pull/360
Closes #3319
=> refactor(ProfileModal): replace implementation with StatusQ components

ui/app/AppLayouts/Chat/CommunityComponents/CommunitiesPopup.qml, ui/app/AppLayouts/Chat/CommunityComponents/CommunityDetailPopup.qml, ui/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopup.qml, ui/app/AppLayouts/Chat/CommunityComponents/CreateCategoryPopup.qml, ui/app/AppLayouts/Chat/CommunityComponents/CreateChannelPopup.qml, ui/app/AppLayouts/Chat/CommunityComponents/CreateCommunityPopup.qml, ui/app/AppLayouts/Chat/CommunityComponents/InviteFriendsToCommunityPopup.qml, ui/app/AppLayouts/Chat/CommunityComponents/MembershipRequestsPopup.qml, ui/app/AppLayouts/Chat/CommunityComponents/MembershipRequirementPopup.qml, ui/app/AppLayouts/Chat/CommunityComponents/TransferOwnershipPopup.qml, ui/app/AppLayouts/Chat/components/ProfilePopup.qml
Also updated all StatusModals to use contentItem
instead of content
=> fix(desktop/statusQ) Updated StatusQ HEAD

ui/app/AppLayouts/WalletV2/ShareModal.qml, ui/app/AppLayouts/WalletV2/WalletHeader.qml
Added new popup to share wallet account details
To-do's:
1. Rounded corners in the QR code
2. Emoji's for the account
StatusQ PR link: https://github.com/status-im/StatusQ/pull/379/files
fixes #3304
=> feat(@desktop/wallet2): Added Share Modal

src/app/chat/core.nim, src/app/chat/event_handling.nim, src/app/chat/view.nim, src/app/chat/views/messages.nim, src/app/profile/view.nim, src/status/notifications/os_notification_details.nim, src/status/notifications/os_notifications.nim, src/status/status.nim, ui/app/AppLayouts/Chat/ChatColumn.qml, ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml, ui/app/AppLayouts/Chat/ContactsColumn.qml, ui/app/AppMain.qml, ui/imports/Constants.qml, ui/main.qml
Corresponding nimqml PR is [here](https://github.com/status-im/nimqml/pull/29) and dotherside PR is [here](https://github.com/status-im/dotherside/pull/45).
A feature for adding os notifications and responding on click on them is developed for Windows and MacOs.
Fixes: #2996
=> fix(@desktop/general): clicking push notification does expand the app but does not open correct channel/chat

ui/app/AppLayouts/Chat/CommunityComponents/CreateCommunityPopup.qml
This was broken due to a breaking change in StatusQ dependency.
Fixes #3389
=> fix(Communities): make creating communities work again

ui/app/AppLayouts/Chat/components/ProfilePopup.qml
Due to a breaking change in StatusQ, this modal caused a reference error.
This commit fixes it.
Fixes #3400
=> fix(ProfilePopup): ensure modal is working again

ui/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopup.qml, ui/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopupMembersList.qml
=> fix(Communities): ensure community profile popup is rendered correctly

ui/app/AppLayouts/Chat/CommunityComponents/CreateCategoryPopup.qml
=> fix(Communities): make create community categories modal work again

src/status/chat.nim
=> fix(@desktop/chat): do not crash when deleting a message

src/status/constants.nim, src/status/updates.nim
=> fix(@desktop/updates): using timeout when checking for new version

ui/app/AppLayouts/WalletV2/LeftTab.qml, ui/app/AppLayouts/WalletV2/components/AddAccount.qml, ui/app/AppLayouts/WalletV2/components/AddAccountPopup.qml, ui/app/AppLayouts/WalletV2/components/qmldir
based on the new concept
* Updates include only adding account with private key,
seed phrase to be done in a seperate PR
Depends on https://github.com/status-im/StatusQ/pull/384
Closes #3310
=> feat(@desktop/wallet2) Updates in AddAccount modal

src/app/chat/views/communities.nim, src/app/chat/views/community_item.nim
=> fix: membership requests dissapearing on a community update

ui/app/AppLayouts/Chat/ChatLayout.qml
=> fix(@desktop/chat): force focus on search input when popup is opened

ui/app/AppLayouts/Profile/LeftTab/Menu.qml, ui/app/AppLayouts/Profile/Sections/ChangePasswordSuccessModal.qml
Brought back back up seed phrase indicator in profile
menu "Privacy and security"
Closes #3433
=> fix(dektop/profile) Back up seed was gone

ui/app/AppLayouts/Profile/Sections/AdvancedContainer.qml, ui/app/AppMain.qml
Also changed icon from wallet to cancel, to indicate
that the feature is incomplete
Closes #3431
=> fix(desktop/wallet2) Updated wallet2 warning text

ui/app/AppLayouts/Profile/LeftTab.qml, ui/app/AppMain.qml
=> fix(@desktop/profile): change headline to settings

src/app/utilsView/view.nim
Status-go PR: https://github.com/status-im/status-go/pull/2349
Initial work to load networks when the wallet start
=> feat(@desktop/wallet2): Fetch networks on wallet init

.gitmodules, src/app/chat/view.nim, src/app/login/core.nim, src/app/profile/views/profile_settings.nim, src/app/wallet/v1/views/accounts.nim, src/app/wallet/v2/views/accounts.nim, src/constants.nim, src/nim_status_client.nim
Depends on https://github.com/status-im/status-lib/pull/9
=> refactor: extract app constants from status-lib and remove submodules

src/app/node/core.nim, src/app/profile/core.nim, src/status/libstatus/core.nim, src/status/libstatus/mailservers.nim, src/status/settings.nim, src/status/tasks/marathon/mailserver/model.nim, src/status/types.nim, ui/app/AppLayouts/Profile/LeftTab/Menu.qml
Depends on https://github.com/status-im/status-go/pull/2347
=> fix: wakuV2 mailserver cycle

src/app/wallet/v2/core.nim, src/app/wallet/v2/view.nim, src/app/wallet/v2/views/settings.nim, ui/app/AppLayouts/WalletV2/SettingsTab.qml, ui/app/AppLayouts/WalletV2/WalletV2Layout.qml, ui/app/AppLayouts/WalletV2/qmldir
https://github.com/status-im/StatusQ/pull/370
StatusQ PR link : https://github.com/status-im/StatusQ/pull/388
=> feat(desktop/wallet) Adding Setttings tab in wallet 2

ui/app/AppLayouts/Chat/ChatColumn/ActivityCenter.qml
=> fix(ActivityCenter): Fix reopen popup on bell button click

ui/app/AppLayouts/Chat/CommunityComponents/CommunitiesPopup.qml, ui/app/AppLayouts/Chat/ContactsColumn.qml
It's unclear to me why these were off since the latest StatusQ upgrade.
Closes #3396
=> fix(@desktop/chat): fix seach input paddings

ui/app/AppLayouts/Profile/LeftTab/Menu.qml
=> fix(@desktop/profile): add missing logout confirmation dialog

src/app/chat/views/sticker_pack_list.nim
depends on:
https://github.com/status-im/status-lib/pull/25
https://github.com/status-im/status-lib/pull/24
https://github.com/status-im/status-lib/pull/23
https://github.com/status-im/status-lib/pull/22
https://github.com/status-im/status-lib/pull/21
=> Update status lib

src/app/profile/views/ens_manager.nim, ui/app/AppLayouts/Profile/Sections/MyProfileContainer.qml
=> fix(@desktop/profile): show ENS username in profile page if available

Makefile
Usage:
```qml
SpellChecker {
id: spellchecker
lang: "en"
}
```
Closes: #3442
=> feat(Spellchecking): Add bottle for spellchecking

src/app/profile/view.nim, ui/app/AppLayouts/Profile/Sections/ChangePasswordModal.qml, ui/app/AppLayouts/Profile/Sections/ChangePasswordSuccessModal.qml, ui/app/AppLayouts/Profile/Sections/PrivacyContainer.qml
Implemented new change password workflow
Closes #3432
=> feat(desktop/profile) adding password changed modal

Makefile, src/app/node/core.nim, src/app/node/view.nim, src/nim_status_client.nim, ui/app/AppLayouts/Node/NodeLayout.qml
Requires
- https://github.com/status-im/status-lib/pull/31
Fixes
- #3506
=> feat: display logs in node management tab

ui/app/AppMain.qml, ui/main.qml
Also checked and updated drag and drop feature to work in commmunities
fixes #3495
=> fix(@deaktop/chat): drag & drop to upload a file/picture is not working

ui/app/AppLayouts/WalletV2/components/AccountNotFound.qml, ui/app/AppLayouts/WalletV2/components/AddAccountPopup.qml, ui/app/AppLayouts/WalletV2/components/PKeyAccountDetails.qml, ui/app/AppLayouts/WalletV2/components/SeedAccountDetailsDelegate.qml, ui/app/AppLayouts/WalletV2/components/SeedAddAccountView.qml
Added adding account with seed phrase feature
TODO add going through authorization popup process as soon as the popup is implemented
Closes #3311
=> feat(desktop/wallet2) Add account with seed modal

src/app/wallet/v2/views/asset_list.nim, src/app/wallet/v2/views/collection_list.nim, src/app/wallet/v2/views/trait_list.nim, ui/app/AppLayouts/WalletV2/CollectiblesTab.qml, ui/app/AppLayouts/WalletV2/LeftTab.qml, ui/app/AppLayouts/WalletV2/WalletV2Layout.qml, ui/app/AppLayouts/WalletV2/components/CollectibleCollection.qml, ui/app/AppLayouts/WalletV2/components/CollectibleDetailsHeader.qml, ui/app/AppLayouts/WalletV2/components/CollectibleDetailsPage.qml, ui/app/AppLayouts/WalletV2/components/qmldir
New features added :
1. Tab which displays the collection
2. Page which display the details of the NFT
Link to StatusQ PR : https://github.com/status-im/StatusQ/pull/407
Link to status-lib PR: https://github.com/status-im/status-lib/pull/30
Link to snim-status-lib PR: https://github.com/status-im/status-lib/pull/11
fixes #3306
=> feat(@desktop/wallet2): Added new Tab to display Collectibles

Makefile
@michaelsbradleyjr  request this changes. I hope i understand it right.
=> fix(Makefile): fix bottles order

src/app/profile/views/mailservers_list.nim, ui/app/AppLayouts/Node/NodeLayout.qml, ui/app/AppLayouts/Profile/Sections/SyncContainer.qml
=> fix: display current active mailserver

src/app/chat/view.nim, src/app/chat/views/channel.nim, src/app/chat/views/messages.nim, ui/app/AppLayouts/Chat/components/ChatContextMenu.qml, ui/app/AppLayouts/Profile/Sections/AdvancedContainer.qml, ui/app/AppMain.qml
fixes #3508
https://github.com/status-im/nimqml/pull/34
https://github.com/status-im/dotherside/pull/52
=> feat(@desktop/chat): download messages

src/app/wallet/v2/core.nim, src/app/wallet/v2/view.nim, src/app/wallet/v2/views/network_list.nim, src/app/wallet/v2/views/networks.nim, ui/app/AppLayouts/WalletV2/WalletHeader.qml, ui/app/AppLayouts/WalletV2/components/network/NetworkFilter.qml, ui/app/AppLayouts/WalletV2/components/network/NetworkSelect.qml, ui/app/AppLayouts/WalletV2/components/network/NetworkSelectPopup.qml, ui/app/AppLayouts/WalletV2/components/network/qmldir
Initial network selector (very simple design for now)
status-lib pr: https://github.com/status-im/status-lib/pull/28
=> feat(@desktop/wallet2): Add network select

ui/app/AppLayouts/WalletV2/WalletHeader.qml, ui/app/AppLayouts/WalletV2/WalletV2Layout.qml, ui/app/AppLayouts/WalletV2/components/network/NetworkSelect.qml, ui/app/AppLayouts/WalletV2/views/ActivityView.qml, ui/app/AppLayouts/WalletV2/views/AssetsView.qml, ui/app/AppLayouts/WalletV2/views/CollectiblesView.qml, ui/app/AppLayouts/WalletV2/views/PositionsView.qml, ui/app/AppLayouts/WalletV2/views/StackBaseView.qml, ui/app/AppLayouts/WalletV2/views/StackDetailBase.qml, ui/app/AppLayouts/WalletV2/views/assets/AssetDetailView.qml
Initial commit adding token detailed view as per new design
=> feat(desktop/wallet2) Adding token view

ui/app/AppLayouts/Profile/Sections/ContactsContainer.qml
fix(@desktop/profile): Blocked contacts counter doesn't show actual number
fixes #3421
=> fix(@desktop/profile): Blocked contacts counter doesn't show actual number

.gitmodules, Makefile
=> feat(spellchecking): add dictionaries as submodule

ui/app/AppLayouts/Profile/Sections/NetworksModal.qml, ui/app/AppLayouts/Profile/Sections/NewCustomNetworkModal.qml
Network ID is not being displayed when adding a custom network
* Also replaced ModalPopup with StatusModal and other design
related updates (eg top margins etc) in NewCustomNetworkModal.qml
Closes #3456
=> fix(desktop/profile) Bug in adding custom network

src/app_service/tasks/marathon/mailserver/model.nim, ui/app/AppLayouts/Node/NodeLayout.qml
Requires
- https://github.com/status-im/status-lib/pull/38
=> feat: display mailserver interactions

src/app/chat/views/channel.nim
fix(@desktop/communities): Fix for app doesn't preserve selected community chat
fixes #3486
=> fix(@desktop/communities): Fix for app doesn't preserve selected community chat

ui/shared/status/StatusGifPopup.qml
=> feat(@desktop/chat): Allow to retry when query fail

ui/app/AppLayouts/Chat/components/PrivateChatPopup.qml
=> fix(@desktop/chat): Fix color of my profile button

ui/main.qml
Reinstate missing settings, it was added: https://github.com/status-im/status-desktop/pull/3556/files
but removed: https://github.com/status-im/status-desktop/pull/3318/files
=> fix(@desktop/settings): reinstate downloadChannelMessagesEnabled config

ui/shared/status/StatusGifPopup.qml
=> fix(@desktop/gif): fix background color on dark mode

Makefile
Allow for `make` to check the timestamps of files relevant to those targets and thereby skip one or both targets if nothing's changed.
Related to a [discussion from yesterday](https://github.com/status-im/status-desktop/pull/3545#discussion_r709388487).
NOTE: I added some comments and commented code re: `UI_SOURCES` that I'll clean up prior to merge, after we decide what we want to do.
There are a lot of files in `ui/` such that:
```
UI_SOURCES := $(shell find ui -type f | grep -v resources\.qrc)
```
causes things to be slower (because `make` has to check so many timestamps) than simply rebuilding `resources.rcc` every time.
Using a smaller file set gives a nice speedup, but per my comment, developers will need to be aware that changing some kinds of files in `ui/` will require a manual …
=> chore: improve Makefile targets nim_status_client and rcc

ui/shared/status/StatusGifPopup.qml
=> fix(@desktop/chat): Reopening gif popup open trending

ui/app/AppLayouts/Wallet/SeedPhraseBackupWarning.qml, ui/app/AppLayouts/Wallet/WalletLayout.qml, ui/app/AppMain.qml
Also prevent backup warning to be double when we switch wallet 2 to 1
=> fix(@desktop/wallet): Fix backup warning

src/app/wallet/v2/views/account_list.nim
https://github.com/status-im/status-lib/pull/5
https://github.com/status-im/status-go/pull/2357
=> feat(@desktop/wallet2): Enable multi chain for collectible

ui/app/AppLayouts/Chat/ChatColumn.qml, ui/app/AppLayouts/Chat/ChatColumn/Message.qml
=> fix(@desktop/chat): blocked user messages disappear after the user is blocked

src/app/chat/view.nim, src/app/chat/views/activity_notification_list.nim, src/app/chat/views/channel.nim, src/app/chat/views/channels_list.nim
=> fix(@desktop/notifications): fixing wrong mentions counting

ui/main.qml
=> feat(@desktop/settings): set "Just @mentions" as the new default in Notifications preferences

src/app/wallet/v1/views/token_list.nim, src/app/wallet/v1/views/tokens.nim, src/app/wallet/v2/views/network_list.nim, src/app/wallet/v2/views/networks.nim
Adjust desktop to status lib and status go new API
https://github.com/status-im/status-lib/pull/29
https://github.com/status-im/status-go/pull/2359
@anastasiyaig when you have a few minutes to spare, if you help have a go at this one, *nothing* should change. (only requesting you to have a look cause there is a lot of change in status-lib)
=> feat(@desktop/wallet): Add chain id to internal API

ui/main.qml
=> fix(@desktop/members): Fix missing app settings

src/app/profile/views/contacts.nim, ui/app/AppLayouts/Chat/components/ProfilePopup.qml
PR: `status-lib` [here](https://github.com/status-im/status-lib/pull/44)
Fixes: #3418
=> fix(@desktop/chat): removing contact results in the same contact's contact request showing up again

ui/app/AppLayouts/Chat/ChatColumn/User.qml, ui/app/AppLayouts/Chat/components/PinnedMessagesPopup.qml
fix(@desktop/chat): Fix small UI issues
1. Removed back button from pinned popup
2. Added border to user identifier in members list
fixes #3552
=> fix(@desktop/chat): Fix small UI issues

ui/app/AppLayouts/Chat/components/AcceptRejectOptionsButtons.qml
=> fix(@desktop/chat): Open popup on click

ui/shared/status/StatusChatImageLoader.qml
Finally I managed to catch and fix the issue. Messages where are was able to reproduce this issue work well for me know.
Fixes: #3594
=> fix(@desktop/chat): scrolling of the chat with code blocks and reactions is repetitive

Makefile
These changes are a follow-up to #3582.
Also support `REBUILD_NIM=true` and `REBUILD_UI=true` variables so that it's possible to ensure a rebuild for the next invocation of `make` or `make run`.
Dev docs have been updated: https://hackmd.io/OtFjDnH6QtOl3K65fKKEGg?view#3-Build-and-run-the-app
Also adjust run targets so that e.g. `make -j16 run` works correctly.
Closes #3639.
=> fix: ensure Nim recompile after make update

Makefile, config.nims, package-lock.json, package.json, ui/app/AppLayouts/Chat/ChatColumn.qml, ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml, ui/app/AppLayouts/Chat/ChatColumn/Message.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/CompactMessage.qml, ui/app/AppLayouts/Chat/ChatColumn/SuggestionBox.qml, ui/app/AppLayouts/Chat/ChatColumn/SuggestionFilter.qml, ui/shared/ImageLoader.qml, ui/shared/status/StatusChatImageLoader.qml
=> fix(@desktop/mentions): editing mentions

src/app/profile/core.nim
Requires:
- https://github.com/status-im/status-go/pull/2378
- https://github.com/status-im/status-lib/pull/46
=>  feat: add mailserver request signals

Makefile
Requires
- https://github.com/status-im/status-go/pull/2381
- https://github.com/status-im/QR-Code-generator/pull/4
=> crosscompile to amd64 when building on darwin/arm64

src/app/wallet/v2/view.nim, src/app/wallet/v2/views/networks.nim, ui/app/AppLayouts/WalletV2/WalletV2Layout.qml, ui/app/AppLayouts/WalletV2/panels/NetworkSelectPanel.qml, ui/app/AppLayouts/WalletV2/panels/WalletHeaderPanel.qml, ui/app/AppLayouts/WalletV2/popups/NetworkSelectPopup.qml
Status-lib PR: https://github.com/status-im/status-lib/pull/49
=> feat(@desktop/wallet2): Toggle network

src/app/profile/views/contacts.nim
Status-lib PR: https://github.com/status-im/status-lib/pull/59
ALSO: FIX REMOVING A CONTACT
=> refactor: contact store use object

src/app/browser/view.nim, ui/app/AppLayouts/Browser/FavoritesList.qml
Status-lib PR: https://github.com/status-im/status-lib/pull/60
=> refactor: browser use object

src/app/chat/views/gif.nim, src/app/chat/views/gif_list.nim
Status-lib PR: https://github.com/status-im/status-lib/pull/61
=> refactor: gif store return object

ui/app/AppLayouts/Chat/components/ProfilePopup.qml
=> refactor(@desktop/profile): don't display footer or chat settings in profile popup for own profile

ui/app/AppLayouts/Chat/ChatColumn/ChatComponents/SignTransactionModal.qml, ui/app/AppLayouts/Wallet/SendModal.qml, ui/shared/status/StatusETHTransactionModal.qml, ui/shared/status/StatusSNTTransactionModal.qml
=> fix(@desktop/wallet): gas error position

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatText.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/CompactMessage.qml, ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/NormalMessage.qml
=> fix(ui): Resolve conflict between click on text message and click on message 

ci/Jenkinsfile.combined, ci/Jenkinsfile.linux, ci/Jenkinsfile.macos, ci/Jenkinsfile.windows
Depends on: https://github.com/status-im/status-jenkins-lib/pull/36
Related: https://github.com/status-im/status-go/pull/2388
=> ci: upgrade library and use of pkgFilename()

.gitmodules, Makefile
With this PR, all version changes in status-go must be done in status-lib
Requires
- https://github.com/status-im/status-lib/pull/50
Fixes: #3679
=> chore: remove status-go from desktop

ui/app/AppLayouts/Chat/ChatColumn.qml
feat(@desktop/chat): Added support for copy or click on link from channel descriptions
fixes #3517
=> feat(@desktop/chat): Added support for copy or click on link from channel descriptions

src/app/wallet/v1/views/token_list.nim
status-lib PR: https://github.com/status-im/status-lib/pull/68
=> refactor: ensure settings is accessed via model

src/app/node/core.nim, src/app/node/view.nim, src/app_service/tasks/marathon/mailserver/model.nim, ui/app/AppLayouts/Profile/LeftTab/Menu.qml, ui/app/AppLayouts/Profile/Sections/AdvancedContainer.qml
Depends on:
- https://github.com/status-im/status-lib/pull/15
=> feat: wakuV2 light client mode

src/app/profile/views/contact_list.nim, src/app/profile/views/contacts.nim
Requires
- https://github.com/status-im/status-lib/pull/74
- https://github.com/status-im/status-go/pull/2372
=> refactor: contacts-perfomance

ui/app/AppLayouts/Node/NodeLayout.qml, ui/app/AppLayouts/Node/stores/RootStore.qml, ui/app/AppLayouts/Node/views/RateView.qml
This refactors the node management module to use the stores/views/popups
architecture.
Closes #3711
=> refactor(@desktop/node-management): move to stores architecture

src/app/boot/app_controller.nim, src/app/modules/main/module.nim, src/app/modules/main/profile_section/module.nim, src/app/modules/main/profile_section/network/controller.nim, src/app/modules/main/profile_section/network/controller_interface.nim, src/app/modules/main/profile_section/network/custom_networks.nim, src/app/modules/main/profile_section/network/io_interface.nim, src/app/modules/main/profile_section/network/module.nim, src/app/modules/main/profile_section/network/view.nim, src/app/modules/main/profile_section/privacy/controller.nim, src/app/modules/main/profile_section/privacy/controller_interface.nim, src/app/modules/main/profile_section/privacy/io_interface.nim, src/app/modules/main/profile_section/privacy/module.nim, src/app/modules/main/profile_section/privacy/view.nim, src/app/utilsView/view.nim, src/app_service/service/network/service.nim, src/app_service/service/network/service_interface.nim, src/app_service/service/settings/service.nim, src/app_service/service/settings/service_interface.nim, ui/app/AppLayouts/Profile/controls/NetworkRadioSelector.qml, ui/app/AppLayouts/Profile/popups/NetworksModal.qml, ui/app/AppLayouts/Profile/popups/NewCustomNetworkModal.qml, ui/app/AppLayouts/Profile/stores/RootStore.qml, ui/app/AppLayouts/Profile/views/AdvancedView.qml, ui/app/AppLayouts/Profile/views/PrivacyView.qml
Add messages from contacts only
Add network module
Known issue:
- Using a custom network makes the app crash on login, due to some ENS function. I left it as is, but added a comment on the crashing line. Let me know if we can delete that line or fix it.
=> More profile modules

ui/app/AppLayouts/Wallet/panels/WalletHeader.qml, ui/app/AppLayouts/Wallet/popups/ReceiveModal.qml, ui/app/AppLayouts/Wallet/stores/RootStore.qml
=> fix(@desktop/wallet): make the receive modal use the old wallet

ui/app/AppLayouts/Wallet/popups/AddAccountWithSeedModal.qml
=> fix (desktop/wallet) account colors were not shown

ui/app/AppLayouts/Wallet/views/LeftTabView.qml
=> fix (desktop/wallet) fix menu button add button

ui/app/AppLayouts/Chat/popups/ChooseBrowserPopup.qml
=> fix(ChooseBrowserPopup): ensure popup is always centered

ui/app/AppLayouts/Onboarding/popups/GenKeyModal.qml
Added  objectName: "rightArrowSubmitBtn" for GenKeyModal.qml file
=> chore(GenKeyModal.qml): added object name for tests

ui/app/AppLayouts/Chat/panels/communities/BackUpCommuntyBannerPanel.qml, ui/app/AppLayouts/Chat/panels/communities/CommunityWelcomeBannerPanel.qml, ui/app/AppLayouts/Chat/popups/community/CommunityProfilePopup.qml, ui/app/AppLayouts/Chat/popups/community/CreateCommunityPopup.qml, ui/app/AppLayouts/Chat/views/CommunityColumnView.qml, ui/app/AppMain.qml
Fixes #3960
Fixes the edit popup not opening (along with a couple other popups) and fixes the call to `edit`
Fixes the Banners throwing warnings because of being undefined and also fixed the first `push` to the list since it was again undefined
=> Fix community edit, popup opens and banners

ui/app/AppLayouts/Chat/panels/communities/BackUpCommuntyBannerPanel.qml, ui/app/AppLayouts/Chat/panels/communities/CommunityWelcomeBannerPanel.qml, ui/app/AppLayouts/Chat/popups/community/CommunityProfilePopup.qml, ui/app/AppLayouts/Chat/popups/community/CreateChannelPopup.qml, ui/app/AppLayouts/Chat/popups/community/CreateCommunityPopup.qml, ui/app/AppLayouts/Chat/views/ChatContextMenuView.qml, ui/app/AppLayouts/Chat/views/CommunityColumnView.qml, ui/app/AppMain.qml
Fixes #4000
Branched off https://github.com/status-im/status-desktop/pull/4016
=> fix: fix edit community channel missing store

src/app/modules/main/profile_section/profile/controller.nim, src/app/modules/main/profile_section/profile/controller_interface.nim, src/app/modules/main/profile_section/profile/io_interface.nim, src/app/modules/main/profile_section/profile/model.nim, src/app/modules/main/profile_section/profile/module.nim, src/app/modules/main/profile_section/profile/view.nim, src/app_service/service/profile/service.nim, src/app_service/service/profile/service_interface.nim, ui/app/AppLayouts/Profile/popups/ChangeProfilePicModal.qml, ui/app/AppLayouts/Profile/stores/RootStore.qml
=> fix profile pic change and move it to new architecture

src/app/boot/app_controller.nim, src/app_service/service/language/service.nim, ui/app/AppLayouts/Profile/stores/RootStore.qml
=> Fix changing language

src/app/chat/views/communities.nim
=> fix(Communities): ensure community channels have community color

ui/app/AppLayouts/Chat/popups/GroupInfoPopup.qml
This happens because sometimes channel property in GroupInfoPopup is null.
This commit avoid crashes.
Closes: #3993
=> fix(GroupInfoPopup): check if channel exists

ui/app/AppLayouts/Onboarding/popups/MnemonicRecoverySuccessModal.qml
=> fix(@refactoring/base_01): profile picture is missing when recovering account

ui/app/AppLayouts/Profile/views/AppearanceView.qml
Font and scaling Sliders were so tiny making it unable to click and set value.
Depends on https://github.com/status-im/StatusQ/pull/477
Closes #3984
=> fix(desktop/profileSettings) fixed sliders in appearance

ui/app/AppLayouts/Chat/views/CompactMessageView.qml
=> fix(desktop/chat) image was not displayed in message

src/app/modules/main/wallet_section/account_tokens/model.nim, src/app/modules/main/wallet_section/accounts/item.nim, src/app/modules/main/wallet_section/accounts/model.nim, src/app/modules/main/wallet_section/accounts/module.nim, src/app/modules/main/wallet_section/current_account/view.nim, src/app_service/service/wallet_account/service.nim, ui/app/AppLayouts/stores/RootStore.qml, ui/app/AppMain.qml, ui/imports/shared/controls/AssetSelector.qml, ui/imports/shared/controls/RecipientSelector.qml, ui/imports/shared/popups/SendModal.qml, ui/imports/shared/views/TransactionPreview.qml, ui/imports/utils/Utils.qml
Fixes #4038
Fix the send modal. 
- Account lists
- Gas estimate
- Sending ETH
Depends on StatusQ PR https://github.com/status-im/StatusQ/pull/482
=> Fix Send modal

ui/app/AppLayouts/Chat/views/CompactMessageView.qml
=> refactor(desktop/chat) fixed sticker disappears when replying

ui/app/AppLayouts/Profile/panels/NotificationAppearancePreviewPanel.qml, ui/app/AppLayouts/Profile/panels/StatusNotificationWithDropShadowPanel.qml, ui/imports/shared/panels/NotificationWindow.qml
‼️ Depends on https://github.com/status-im/StatusQ/pull/471 ‼️
=> refactor: replace StatusNotification with StatusMacNotification

ui/app/AppLayouts/Browser/BrowserLayout.qml, ui/app/AppLayouts/Browser/popups/AddFavoriteModal.qml, ui/app/AppLayouts/Browser/views/BrowserWebEngineView.qml
fix(@desktop/browser): Add new bookmark Modal doesn't display url and name of website.
Also fixed behavior of add/removing a bookmark.
fixes #4037
=> fix(@desktop/browser): Add new bookmark Modal doesnt display url and name of website.

ui/app/AppLayouts/Chat/views/LinksMessageView.qml, ui/app/AppLayouts/Profile/popups/ChatLinksPreviewModal.qml, ui/app/AppMain.qml
=> fix(settings): fix whitelist setting that starts null

ui/app/AppMain.qml, ui/imports/shared/popups/UserStatusContextMenu.qml
=> fix(desktop/chat) online/offline selector not changing color/state

fleets.json
Requires:
- https://github.com/status-im/status-lib/pull/73
=> feat: wakuv2 rendezvous

src/app/chat/event_handling.nim, src/app/profile/core.nim
- Remove unneded mailserver request when joining a channel
- Add extra details to mailserver logs (request id, and num batches)
- Add signal emitted each time a batch is processed
=> feat: mailserver signals and improvements

src/app/modules/main/profile_section/controller.nim, src/app/modules/main/profile_section/controller_interface.nim, src/app/modules/main/profile_section/io_interface.nim, src/app/modules/main/profile_section/module.nim, src/app/modules/main/profile_section/view.nim, src/app_service/service/settings/service.nim, src/app_service/service/settings/service_interface.nim, ui/app/AppLayouts/Profile/views/AdvancedView.qml
Setting to enable push to telemetry server
Status lib: https://github.com/status-im/status-lib/pull/100
Status go: https://github.com/status-im/status-go/pull/2424
=> feat: allow to enable/disable telemetry

ui/imports/shared/status/StatusChatInput.qml, ui/imports/shared/status/StatusChatInputReplyArea.qml
=> fix(desktop/chatInput) sticker was not shown in reply area

ui/app/AppLayouts/Chat/panels/ChatButtonsPanel.qml, ui/app/AppLayouts/Chat/popups/PinnedMessagesPopup.qml, ui/app/AppLayouts/Chat/views/CompactMessageView.qml, ui/app/AppLayouts/Chat/views/MessageView.qml
=> fix(@desktop/chat): Modal on the Pinned Messages Popup isnt seen

ui/app/AppLayouts/Chat/popups/community/AccessExistingCommunityPopup.qml
fix(@desktop/communities): Fix for can't import community
fixes #4073
=> fix(@desktop/communities): Fix for can't import community

ui/app/AppLayouts/Browser/panels/BrowserTabView.qml
fix(@desktop/browser): Fix for custom homepage not launched in dapp browser
fixes #4036
=> fix(@desktop/browser): Fix for custom homepage not launched in dapp browser

ui/app/AppLayouts/Browser/panels/FavoritesBar.qml, ui/app/AppLayouts/Browser/popups/AddFavoriteModal.qml, ui/app/AppLayouts/Browser/views/BrowserWebEngineView.qml, ui/imports/utils/Constants.qml
fixes #4108
This button needs special case when it is not a real bookmark
browser
=> fix(desktop/browser): Fix add bookmark button

src/app/modules/main/wallet_section/accounts/controller.nim, src/app/modules/main/wallet_section/accounts/controller_interface.nim, src/app/modules/main/wallet_section/accounts/io_interface.nim, src/app/modules/main/wallet_section/accounts/module.nim, src/app/modules/main/wallet_section/accounts/view.nim, src/app_service/service/wallet_account/service.nim, src/app_service/service/wallet_account/service_interface.nim, ui/app/AppLayouts/Wallet/popups/AddAccountWithPrivateKeyModal.qml, ui/app/AppLayouts/Wallet/popups/AddAccountWithSeedModal.qml, ui/app/AppLayouts/Wallet/popups/GenerateAccountModal.qml
fixes #4067
Following up: #4097 
Fix an error when adding a new account in wallet
wallet
=> fix(desktop/wallet): new account with error

src/app_service/service/about/service.nim
=> chore(version): update to 0.4.0

ui/app/AppLayouts/Browser/stores/WalletStore.qml, ui/app/AppLayouts/Profile/views/EnsTermsAndConditionsView.qml, ui/imports/shared/status/StatusETHTransactionModal.qml, ui/imports/shared/status/StatusSNTTransactionModal.qml
Depends of: https://github.com/status-im/StatusQ/pull/487
fixes: #4075
Fix the accounts being loaded in tx modal
All tx modal
=> fix(@desktop/tx): Fix tx modal

src/app/boot/app_controller.nim, src/app/core/user_profile.nim, src/app/modules/main/controller.nim, src/app/modules/main/controller_interface.nim, src/app/modules/main/module.nim, src/app/modules/main/private_interfaces/module_view_delegate_interface.nim, src/app/modules/main/profile_section/profile/controller.nim, src/app/modules/main/profile_section/profile/model.nim, src/app/modules/main/view.nim, src/app/profile/view.nim, src/app/profile/views/profile_info.nim, src/app_service/service/accounts/service.nim, src/app_service/service/settings/service.nim, src/app_service/service/settings/service_interface.nim, ui/app/AppLayouts/Chat/ChatLayout.qml, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/stores/RootStore.qml, ui/app/AppMain.qml, ui/imports/shared/popups/UserStatusContextMenu.qml
This is a counterpart of [this one](https://github.com/status-im/status-desktop/pull/4103).
Also here in a second commit I fixed an issue found in account service.
=> fix(general): online/offline selector updated

ui/app/AppMain.qml, ui/imports/shared/views/chat/LinksMessageView.qml
Fixes #4131
Fixes:
- never ask again not hiding the box
- the box not showing for non-images
- the gif not showing when changing the display image setting (until changing channel)
=> Fix various problems with link messages not showing

src/app/modules/main/profile_section/controller.nim, src/app/modules/main/profile_section/controller_interface.nim, src/app/modules/main/profile_section/io_interface.nim, src/app/modules/main/profile_section/module.nim, src/app/modules/main/profile_section/view.nim, src/app_service/service/settings/service.nim, src/app_service/service/settings/service_interface.nim, ui/app/AppLayouts/Profile/views/AdvancedView.qml
Allow to enable/disable auto message which will send automatically message for you in order to create traffic
status go pr: https://github.com/status-im/status-go/pull/2441
status-lib pr: https://github.com/status-im/status-lib/pull/116
advance settings
=> feat: Allow to enable auto message

ui/app/AppLayouts/Chat/controls/GapComponent.qml
Closes #4188
Fixed gap component before/between dates showing as
"Invalid Date"
Message gap component
=> fix(desktop/chat) gap component dates were wrong

ui/app/AppLayouts/Node/NodeLayout.qml, ui/app/AppLayouts/Profile/views/SyncView.qml
=> fix: appimage freezes on login

ui/imports/shared/views/chat/MessageContextMenuView.qml
=> fix(chat): fix nickname not populated when clicking profile head in menu

ui/app/AppLayouts/Chat/panels/ChatRequestMessagePanel.qml, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Chat/views/ChatColumnView.qml
Depends on https://github.com/status-im/status-lib/pull/114
=> fix(contacts) fixed bug in add contacts function

ui/app/AppLayouts/Chat/controls/UserDelegate.qml, ui/app/AppLayouts/Chat/panels/UserListPanel.qml, ui/app/AppLayouts/Chat/panels/communities/CommunityUserListPanel.qml
This replaces the self-built components for the user list with StatusQ's
list item component and also addresses some of the quirks that existed in the UI
related to that original component.
The user list is now responsive and properly aligned.
‼️ **This depends on StatusQ v0.18.0** ‼️
=> refactor(@desktop/chat): use StatusQ components for chat user list

src/app/modules/main/chat_section/chat_content/input_area/module.nim, src/app/modules/main/chat_section/chat_content/messages/module.nim, src/app/modules/main/chat_section/chat_content/module.nim, src/app/modules/main/chat_section/chat_content/users/controller.nim, src/app/modules/main/chat_section/chat_content/users/module.nim, src/app/modules/main/chat_section/controller.nim, src/app/modules/main/chat_section/controller_interface.nim, src/app/modules/main/chat_section/module.nim, src/app/modules/main/chat_section/private_interfaces/module_access_interface.nim, src/app/modules/main/chat_section/private_interfaces/module_controller_delegate_interface.nim, src/app/modules/main/chat_section/private_interfaces/module_view_delegate_interface.nim, src/app/modules/main/chat_section/view.nim, src/app_service/service/chat/dto/chat.nim, src/app_service/service/chat/service.nim, src/app_service/service/chat/service_interface.nim, ui/app/AppLayouts/Chat/ChatLayout.qml, ui/app/AppLayouts/Chat/views/ChatColumnView.qml, ui/app/AppLayouts/Chat/views/ChatTextView.qml, ui/app/AppLayouts/Chat/views/ContactsColumnView.qml, ui/imports/utils/Utils.qml
Corresponding `status-lib` changes:
- https://github.com/status-im/status-lib/pull/121
We need this pr to be merged into `base_bc` first:
- https://github.com/status-im/status-desktop/pull/4196
=> refactor(chat): create/join public chat added

ui/app/AppLayouts/Onboarding/popups/BeforeGetStartedModal.qml
This needs https://github.com/status-im/StatusQ/pull/494
=> refactor(@desktop/startup): refactor modal to use StatusQ components

src/app/modules/main/chat_section/controller.nim, src/app/modules/main/chat_section/controller_interface.nim, src/app/modules/main/chat_section/model.nim, src/app/modules/main/chat_section/module.nim, src/app/modules/main/chat_section/private_interfaces/module_controller_delegate_interface.nim, src/app/modules/main/chat_section/private_interfaces/module_view_delegate_interface.nim, src/app/modules/main/chat_section/view.nim, src/app_service/service/chat/service.nim, src/app_service/service/message/service.nim, ui/app/AppLayouts/Chat/views/ChatContextMenuView.qml, ui/app/AppLayouts/Chat/views/CommunityColumnView.qml, ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
status-lib PR: https://github.com/status-im/status-lib/pull/130
Mark messages as read refactor
=> refactor(@chat): mark messages as read

src/app_service/service/contacts/service.nim
=> fix: ensure the contact name contains an ens name

ui/app/AppLayouts/Profile/ProfileLayout.qml, ui/app/AppLayouts/Profile/popups/ChatLinksPreviewModal.qml, ui/app/AppLayouts/Profile/popups/DappList.qml, ui/app/AppLayouts/Profile/popups/PermissionList.qml, ui/app/AppLayouts/Profile/popups/StoreToKeychainSelectionModal.qml, ui/app/AppLayouts/Profile/views/AboutView.qml, ui/app/AppLayouts/Profile/views/AdvancedView.qml, ui/app/AppLayouts/Profile/views/AppearanceView.qml, ui/app/AppLayouts/Profile/views/BrowserView.qml, ui/app/AppLayouts/Profile/views/ContactsView.qml, ui/app/AppLayouts/Profile/views/EnsListView.qml, ui/app/AppLayouts/Profile/views/EnsSearchView.qml, ui/app/AppLayouts/Profile/views/EnsView.qml, ui/app/AppLayouts/Profile/views/EnsWelcomeView.qml, ui/app/AppLayouts/Profile/views/HelpView.qml, ui/app/AppLayouts/Profile/views/LanguageView.qml, ui/app/AppLayouts/Profile/views/MyProfileView.qml, ui/app/AppLayouts/Profile/views/NotificationsView.qml, ui/app/AppLayouts/Profile/views/PrivacyView.qml, ui/app/AppLayouts/Profile/views/SoundsView.qml, ui/app/AppLayouts/Profile/views/SyncView.qml, ui/app/AppMain.qml, ui/imports/shared/status/StatusEmojiPopup.qml, ui/imports/utils/Global.qml, ui/main.qml
refactor: remove dynamic scoping from profile module
closes #4247
-Removing the dynamic scoping from the profile module
- fixes some minor errors seen
Profile Module
=> refactor: remove dynamic scoping from profile module

src/app/modules/main/app_search/controller.nim, src/app/modules/main/app_search/controller_interface.nim, src/app/modules/main/app_search/module.nim, src/app/modules/main/communities/controller.nim, src/app/modules/main/communities/controller_interface.nim, src/app/modules/main/communities/io_interface.nim, src/app/modules/main/communities/module.nim, src/app/modules/main/communities/view.nim, src/app/modules/main/controller.nim, src/app/modules/main/controller_interface.nim, src/app/modules/main/item.nim, src/app/modules/main/model.nim, src/app/modules/main/module.nim, src/app_service/service/community/dto/community.nim, src/app_service/service/community/service.nim, src/app_service/service/community/service_interface.nim, ui/app/AppLayouts/Chat/popups/community/CommunitiesPopup.qml, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
Needs https://github.com/status-im/status-lib/pull/133
First step for my part of the community refactor. It adds  a new module to show all communities known to display in the CommunitiesPopup.
=> Add communities module to show community list

src/app/boot/app_controller.nim, src/app/modules/main/wallet_section/saved_addresses/controller.nim, src/app/modules/main/wallet_section/saved_addresses/controller_interface.nim, src/app/modules/main/wallet_section/saved_addresses/io_interface.nim, src/app/modules/main/wallet_section/saved_addresses/module.nim, src/app/modules/main/wallet_section/saved_addresses/view.nim, src/app_service/service/saved_address/service.nim, src/app_service/service/saved_address/service_interface.nim, ui/app/AppLayouts/Wallet/stores/RootStore.qml
Connect list and change
Provide view API
Create events
=> feat: saved address view

src/app/modules/main/app_search/controller.nim, src/app/modules/main/chat_section/chat_content/controller.nim, src/app/modules/main/chat_section/chat_content/input_area/controller.nim, src/app/modules/main/chat_section/chat_content/input_area/module.nim, src/app/modules/main/chat_section/chat_content/module.nim, src/app/modules/main/chat_section/chat_content/users/controller.nim, src/app/modules/main/chat_section/chat_content/users/module.nim, src/app/modules/main/chat_section/controller.nim, src/app/modules/main/chat_section/module.nim, src/app/modules/main/chat_section/private_interfaces/module_access_interface.nim, src/app/modules/main/chat_section/private_interfaces/module_controller_delegate_interface.nim, src/app/modules/main/communities/controller.nim, src/app/modules/main/communities/controller_interface.nim, src/app/modules/main/controller.nim, src/app/modules/main/controller_interface.nim, src/app/modules/main/module.nim, src/app/modules/main/private_interfaces/module_controller_delegate_interface.nim, src/app_service/service/community/dto/community.nim, src/app_service/service/community/service.nim, src/app_service/service/community/service_interface.nim
Adds all the community functions in the service and controller plus the emiting and receiving of events
Needs this PR https://github.com/status-im/status-lib/pull/135
=> refactor(community): add all community function in the backend

Makefile, scripts/force-rebuild-status-go.sh
fixes #4297
Force rebuild of status go if more than 1 day old
Compilation
=> feat(general): Force rebuild of status go at least once a day

src/app/modules/main/chat_section/chat_content/controller.nim, src/app/modules/main/chat_section/chat_content/messages/controller.nim, src/app/modules/main/chat_section/chat_content/messages/controller_interface.nim, src/app/modules/main/chat_section/chat_content/messages/module.nim, src/app/modules/main/chat_section/chat_content/messages/private_interfaces/module_controller_delegate_interface.nim, src/app/modules/main/chat_section/chat_content/messages/private_interfaces/module_view_delegate_interface.nim, src/app/modules/main/chat_section/chat_content/messages/view.nim, src/app/modules/main/chat_section/chat_content/module.nim, src/app/modules/main/chat_section/chat_content/private_interfaces/module_controller_delegate_interface.nim, src/app/modules/shared_models/message_item.nim, src/app/modules/shared_models/message_model.nim, src/app/modules/shared_models/message_reaction_item.nim, src/app/modules/shared_models/message_reaction_model.nim, src/app_service/service/message/service.nim, ui/app/AppLayouts/Chat/popups/PinnedMessagesPopup.qml, ui/app/AppLayouts/Chat/stores/MessageStore.qml, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Chat/views/ChatContentView.qml, ui/app/AppLayouts/Chat/views/ChatMessagesView.qml, ui/imports/shared/panels/chat/EmojiReactionsPanel.qml, ui/imports/shared/views/chat/CompactMessageView.qml, ui/imports/shared/views/chat/MessageContextMenuView.qml, ui/imports/shared/views/chat/MessageView.qml, ui/imports/shared/views/chat/StatusUpdateView.qml
Add/remove reactions added for messages from a message list and for messages displayed in the pinned messages list.
=> refactor(@desktop/chat-messages): add/remove reactions
