status-im/status-desktop

ui/imports/shared/popups/UserStatusContextMenu.qml
Fixed setting user offline/online status from profile picture
UserStatusContextMenu
https://user-images.githubusercontent.com/31625338/146608231-e5fa9e11-97c0-42ca-96d6-f5ac3025101f.mov
=> refactor: fix setting user online/offline status

src/app/modules/main/browser_section/provider/view.nim, src/app_service/common/account_constants.nim, src/app_service/service/ens/service.nim, src/app_service/service/ens/service_interface.nim, src/app_service/service/provider/service.nim
New ens backend, for now, only used by the provider, the rest is not yet migrated
=> feat(ens): new backend

ui/app/AppLayouts/Profile/views/AppearanceView.qml
UI message preview was empty in Appearance menu
Appearance menu
=> refactor: fix ui message preview is empty

ui/app/AppLayouts/Profile/stores/RootStore.qml, ui/app/AppLayouts/Profile/views/DevicesView.qml
Fixes layout in Devices Settings which was broken
Menu -> Devices Settings
=> refactor: fix UI devices settings layout

src/app/global/utils.nim, src/app/modules/main/activity_center/module.nim, src/app/modules/main/chat_section/chat_content/input_area/controller.nim, src/app/modules/main/chat_section/chat_content/input_area/controller_interface.nim, src/app/modules/main/chat_section/chat_content/input_area/module.nim, src/app/modules/main/chat_section/chat_content/input_area/private_interfaces/module_access_interface.nim, src/app/modules/main/chat_section/chat_content/input_area/view.nim, src/app/modules/main/chat_section/chat_content/messages/controller.nim, src/app/modules/main/chat_section/chat_content/module.nim, src/app/modules/main/stickers/controller.nim, src/app/modules/main/stickers/controller_interface.nim, src/app/modules/main/stickers/module.nim, src/app/modules/shared_models/message_item.nim, src/app_service/common/types.nim, src/app_service/service/activity_center/service.nim, src/app_service/service/chat/service.nim, src/app_service/service/stickers/service.nim, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Chat/views/ChatColumnView.qml, ui/app/AppLayouts/Chat/views/ChatContentView.qml, ui/app/AppLayouts/Profile/stores/RootStore.qml
Makes send message and send image work. It sends and also processes the result and shows it.
Also fixes sending stickers.
There is still a weird chat message bug where the Chat Identifier is positioned weirdly when new messages are sent.
Also, we still don't receive new messages. Those will be done in another PR
Needs this PR https://github.com/status-im/status-lib/pull/141
=> refactor(chat): refactor send messages to work

src/app/modules/main/browser_section/dapps/controller.nim, src/app/modules/main/browser_section/dapps/controller_interface.nim, src/app/modules/main/browser_section/dapps/module.nim, src/app/modules/main/browser_section/dapps/private_interfaces/module_controller_delegate_interface.nim, src/app/modules/main/browser_section/dapps/view.nim, src/app/modules/main/browser_section/provider/controller.nim, src/app/modules/main/browser_section/provider/controller_interface.nim, src/app/modules/main/browser_section/provider/module.nim, src/app/modules/main/browser_section/provider/private_interfaces/module_controller_delegate_interface.nim, src/app/modules/main/browser_section/provider/view.nim, src/app/utilsView/view.nim, src/app_service/common/account_constants.nim, src/app_service/service/provider/service.nim, src/app_service/service/provider/service_interface.nim, ui/app/AppLayouts/Browser/helpers/provider.js, ui/app/AppLayouts/Browser/popups/BrowserConnectionModal.qml, ui/app/AppLayouts/Browser/popups/BrowserWalletMenu.qml, ui/app/AppLayouts/Browser/stores/RootStore.qml, ui/app/AppLayouts/Browser/stores/Web3ProviderStore.qml, ui/app/AppLayouts/Browser/views/WebProviderObj.qml
Requires
- https://github.com/status-im/status-lib/pull/136
=> refactor: move provider logic to status-go

src/app/modules/main/chat_section/chat_content/messages/controller.nim, src/app/modules/main/chat_section/chat_content/messages/controller_interface.nim, src/app/modules/main/chat_section/chat_content/messages/module.nim, src/app/modules/main/chat_section/chat_content/messages/private_interfaces/module_controller_delegate_interface.nim, src/app/modules/main/chat_section/chat_content/messages/private_interfaces/module_view_delegate_interface.nim, src/app/modules/main/chat_section/chat_content/messages/view.nim, src/app/modules/main/chat_section/chat_content/module.nim, src/app/modules/shared_models/message_item.nim, src/app/modules/shared_models/message_model.nim, src/app_service/service/chat/service.nim, src/app_service/service/message/async_tasks.nim, src/app_service/service/message/service.nim, ui/app/AppLayouts/Chat/stores/MessageStore.qml, ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
- load more messages on scroll up for chat/channel added
- sending messages improved in terms of adding new messages to
appropriate position
- scroll to message added on the qml side
- qml connected to the sending message success/failed signals
=> refactor(@desktop/chat-messages): load more messages

src/app/modules/main/chat_section/chat_content/input_area/controller.nim, src/app/modules/main/profile_section/contacts/controller.nim, src/app/modules/main/profile_section/contacts/controller_interface.nim, src/app/modules/main/profile_section/contacts/io_interface.nim, src/app/modules/main/profile_section/contacts/module.nim, src/app/modules/main/profile_section/contacts/view.nim, src/app_service/service/contacts/async_tasks.nim, src/app_service/service/contacts/service.nim, ui/app/AppLayouts/Chat/popups/ChatCommandModal.qml, ui/app/AppLayouts/Chat/popups/SignTransactionModal.qml, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Chat/views/ChatColumnView.qml, ui/app/AppLayouts/Chat/views/ChatContentView.qml, ui/imports/shared/controls/AssetAndAmountInput.qml, ui/imports/shared/controls/ContactSelector.qml, ui/imports/shared/controls/RecipientSelector.qml, ui/imports/shared/popups/SendModal.qml, ui/imports/shared/popups/SignTransactionModal.qml, ui/imports/shared/status/StatusETHTransactionModal.qml, ui/imports/shared/status/StatusSNTTransactionModal.qml, ui/imports/shared/views/EnsResolver.qml
Makes sending chat commands work and opening the send transaction modal work
The complete flow doesn't really work because the messages till don't show correctly in the list, but the commands are sent correctly to the other person
=> refactor(chat): hook chat commands to qml and fix ens resolve

src/app/REMOVE-profile/views/mailservers.nim, src/app/boot/app_controller.nim, src/app/modules/main/chat_section/chat_content/controller.nim, src/app/modules/main/chat_section/controller.nim, src/app/modules/main/module.nim, src/app/modules/main/profile_section/advanced/controller.nim, src/app/modules/main/profile_section/io_interface.nim, src/app/modules/main/profile_section/module.nim, src/app/modules/main/profile_section/sync/controller.nim, src/app/modules/main/profile_section/sync/controller_interface.nim, src/app/modules/main/profile_section/sync/io_interface.nim, src/app/modules/main/profile_section/sync/item.nim, src/app/modules/main/profile_section/sync/model.nim, src/app/modules/main/profile_section/sync/module.nim, src/app/modules/main/profile_section/sync/private_interfaces/module_access_interface.nim, src/app/modules/main/profile_section/sync/private_interfaces/module_base_interface.nim, src/app/modules/main/profile_section/sync/private_interfaces/module_controller_delegate_interface.nim, src/app/modules/main/profile_section/sync/private_interfaces/module_view_delegate_interface.nim, src/app/modules/main/profile_section/sync/view.nim, src/app/modules/main/profile_section/view.nim, src/app_service/service/mailservers/dto/mailserver.nim, src/app_service/service/mailservers/service.nim, src/app_service/service/settings/dto/settings.nim, src/app_service/service/settings/service.nim, src/app_service/service/settings/service_interface.nim, ui/app/AppLayouts/Profile/ProfileLayout.qml, ui/app/AppLayouts/Profile/stores/RootStore.qml, ui/app/AppLayouts/Profile/stores/SyncStore.qml, ui/app/AppLayouts/Profile/views/SyncView.qml
This PR moved `Profile/Sync Settings` section to the new backend structure.
Corresponding `status-lib` changes:
- https://github.com/status-im/status-lib/pull/145
=> refactor(@desktop/profile-sync): sync settings

src/app/boot/app_controller.nim, src/app/modules/main/module.nim, src/app/modules/main/profile_section/io_interface.nim, src/app/modules/main/profile_section/language/controller.nim, src/app/modules/main/profile_section/language/controller_interface.nim, src/app/modules/main/profile_section/language/io_interface.nim, src/app/modules/main/profile_section/language/module.nim, src/app/modules/main/profile_section/module.nim, src/app/modules/main/profile_section/view.nim, src/app_service/service/language/service.nim, src/app_service/service/language/service_interface.nim, src/app_service/service/token/dto.nim, ui/app/AppLayouts/Profile/ProfileLayout.qml, ui/app/AppLayouts/Profile/popups/LanguageModal.qml, ui/app/AppLayouts/Profile/stores/LanguageStore.qml, ui/app/AppLayouts/Profile/stores/RootStore.qml, ui/app/AppLayouts/Profile/views/LanguageView.qml
This PR updated `Profile/Language Settings` section.
**Note**: This PR is branched off #4344 so please review it first.
=> refactor(@desktop/settings-language): language settings

ui/app/AppLayouts/Profile/ProfileLayout.qml, ui/app/AppLayouts/Profile/stores/AppearanceStore.qml, ui/app/AppLayouts/Profile/stores/RootStore.qml, ui/app/AppLayouts/Profile/views/AppearanceView.qml, ui/imports/shared/views/chat/MessageView.qml
This PR updated `Profile/Appearance` settings section.
Note: This PR is branched off #4345 so please review it first.
=> refactor(@desktop/settings-appearance): appearance settings

src/app/profile/views/ens_manager.nim, src/app_service/service/ens/service.nim, ui/app/AppLayouts/Profile/stores/RootStore.qml, ui/app/AppLayouts/Profile/views/EnsTermsAndConditionsView.qml
New ENS API
https://github.com/status-im/status-go/pull/2471
https://github.com/status-im/status-lib/pull/143
=> feat: Use ens API

src/app/chat/views/channels_list.nim, src/app/chat/views/chat_item.nim, ui/imports/shared/controls/chat/FetchMoreMessagesButton.qml, ui/imports/shared/views/chat/MessageView.qml
Requires
- https://github.com/status-im/status-lib/pull/123
=> feat: show real sync date in "Fetch more messages" button

src/app/modules/main/chat_section/chat_content/input_area/controller.nim, src/app/modules/main/chat_section/controller.nim, src/app/modules/main/chat_section/module.nim, src/app/modules/main/communities/controller.nim, src/app/modules/main/communities/controller_interface.nim, src/app/modules/main/communities/io_interface.nim, src/app/modules/main/communities/module.nim, src/app/modules/main/communities/private_interfaces/module_access_interface.nim, src/app/modules/main/communities/private_interfaces/module_base_interface.nim, src/app/modules/main/communities/private_interfaces/module_controller_delegate_interface.nim, src/app/modules/main/communities/private_interfaces/module_view_delegate_interface.nim, src/app/modules/main/communities/view.nim, src/app/modules/main/controller.nim, src/app/modules/main/io_interface.nim, src/app/modules/main/module.nim, src/app/modules/main/private_interfaces/module_communities_section_delegate_interface.nim, src/app/modules/shared_models/active_section.nim, src/app/modules/shared_models/member_item.nim, src/app/modules/shared_models/section_item.nim, src/app_service/service/chat/dto/chat.nim, src/app_service/service/chat/service.nim, src/app_service/service/community/service.nim, ui/app/AppLayouts/Chat/popups/community/CommunityProfilePopup.qml, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Chat/views/CommunityColumnView.qml, ui/app/AppLayouts/stores/RootStore.qml
Adds the front-end model for the community (extends the section item)
Fixes/refactor those features:
- Create community
- Join
- Create channel
- write in channel
- edit community
The other features will be added in other PRs
Uses https://github.com/status-im/status-lib/pull/152
=> Refactor most of  communities front-end

src/app/modules/main/communities/controller.nim, src/app/modules/main/communities/controller_interface.nim, src/app/modules/main/communities/module.nim, src/app/modules/main/controller.nim, src/app/modules/main/module.nim, src/app/modules/main/private_interfaces/module_controller_delegate_interface.nim, src/app/modules/main/view.nim, src/app/modules/shared_models/active_section.nim, src/app/modules/shared_models/section_model.nim, src/app_service/service/community/service.nim, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
Adds the edit community feature
Is based on top of the other community front features branch.
Depends on https://github.com/status-im/status-lib/pull/153
=> refactor(community): hook edit community feature

src/app/modules/main/communities/controller.nim, src/app/modules/main/controller.nim, src/app/modules/main/controller_interface.nim, src/app/modules/main/module.nim, src/app/modules/main/private_interfaces/module_controller_delegate_interface.nim, src/app/modules/shared_models/section_model.nim, ui/app/AppLayouts/Chat/popups/community/CommunityProfilePopup.qml, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/stores/RootStore.qml, ui/app/AppMain.qml
Makes leaving a community work again
=> refactor(community): hook leave community

src/app/boot/app_controller.nim, src/app/modules/main/io_interface.nim, src/app/modules/main/module.nim, src/app/modules/main/node_section/controller.nim, src/app/modules/main/node_section/controller_interface.nim, src/app/modules/main/node_section/io_interface.nim, src/app/modules/main/node_section/module.nim, src/app/modules/main/node_section/private_interfaces/module_access_interface.nim, src/app/modules/main/node_section/private_interfaces/module_base_interface.nim, src/app/modules/main/node_section/private_interfaces/module_controller_delegate_interface.nim, src/app/modules/main/node_section/private_interfaces/module_view_delegate_interface.nim, src/app/modules/main/node_section/view.nim, src/app/modules/main/private_interfaces/module_node_section_delegate_interface.nim, src/app_service/service/node/async_tasks.nim, src/app_service/service/node/service.nim, src/app_service/service/node_configuration/service.nim, src/app_service/service/node_configuration/service_interface.nim, src/app_service/service/settings/service.nim, src/app_service/service/settings/service_interface.nim, ui/app/AppLayouts/Node/NodeLayout.qml, ui/app/AppLayouts/Node/stores/RootStore.qml, ui/app/AppLayouts/Node/views/RateView.qml, ui/app/AppLayouts/Profile/stores/ProfileSectionStore.qml
refactor(node): Move node section to new architecture
Closes: #3805
=> Refactoring node section

ui/app/AppLayouts/Wallet/popups/AccountSettingsModal.qml
=> fix(@wallet): delete account

src/app/boot/app_controller.nim, src/app/modules/main/communities/controller.nim, src/app/modules/main/communities/controller_interface.nim, src/app/modules/main/communities/module.nim, src/app/modules/main/communities/private_interfaces/module_access_interface.nim, src/app/modules/main/communities/view.nim, src/app/modules/shared_models/active_section.nim, src/app/modules/shared_models/section_item.nim, src/app_service/service/community/dto/community.nim, src/app_service/service/community/service.nim, ui/app/AppLayouts/Chat/ChatLayout.qml, ui/app/AppLayouts/Chat/panels/communities/CommunityProfilePopupInviteFriendsPanel.qml, ui/app/AppLayouts/Chat/panels/communities/CommunityProfilePopupOverviewPanel.qml, ui/app/AppLayouts/Chat/panels/communities/CommunityWelcomeBannerPanel.qml, ui/app/AppLayouts/Chat/popups/community/InviteFriendsToCommunityPopup.qml, ui/app/AppLayouts/Chat/views/CommunityColumnView.qml, ui/app/AppLayouts/stores/RootStore.qml, ui/app/AppMain.qml, ui/imports/shared/controls/ContactsListAndSearch.qml, ui/imports/shared/views/ExistingContacts.qml, ui/imports/shared/views/SearchResults.qml
FYI, while testing this, I found that adding contacts and accepting contact requests make the app crash. Then, the app crashes on its own when logging in next. I'm not sure what causes it, since there is no stack trace at all, but I don't think it's related to my PR, though it would be good to test it out first just in case.
=> refactor(community): hook invite user and fix community context menu

ui/app/AppLayouts/Onboarding/popups/EnterSeedPhraseModal.qml, ui/imports/shared/controls/SeedPhraseTextArea.qml
fixes #4364
Change height, but @anastasiyaig if that is not enough, would you mind sharing the seed phrase if that is ok so I can adjust it more
=> fix(@onboarding): Add more height to the textarea

scripts/fetch-brew-bottle.sh
Otherwise the OpenSSL installation fails due to lack of `mojave` key:
```
% brew info --json=v1 openssl@1.1 | jq '.[0].bottle.stable.files.mojave'
null
```
Because of changes in bottle definition: https://github.com/Homebrew/homebrew-core/commit/6de466c3e5608807b57f3f0fb453ba914dfec2db
Also added check for lack of URL and `-S` to `curl` to see errors.
Example failure: https://ci.status.im/job/status-desktop/job/branches/job/macos/view/change-requests/job/PR-4401/2/
=> fetch-brew-bottle.sh: don't hardcode macOS Mojave

src/app/boot/app_controller.nim, src/app/modules/main/node_section/controller.nim, ui/app/AppLayouts/Chat/panels/SuggestionBoxPanel.qml, ui/app/AppLayouts/Chat/stores/MessageStore.qml, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Chat/views/ChatColumnView.qml, ui/app/AppLayouts/Chat/views/ChatContentView.qml, ui/app/AppLayouts/Chat/views/ChatMessagesView.qml, ui/app/AppLayouts/Node/NodeLayout.qml, ui/app/AppLayouts/Profile/stores/AdvancedStore.qml, ui/app/AppLayouts/Profile/views/SoundsView.qml, ui/app/AppLayouts/Wallet/views/RightTabView.qml, ui/app/AppLayouts/WalletV2/panels/WalletHeaderPanel.qml, ui/app/AppMain.qml, ui/imports/shared/controls/StyledTextArea.qml, ui/imports/shared/status/StatusChatInput.qml, ui/imports/shared/status/StatusEmojiSuggestionPopup.qml, ui/imports/shared/stores/RootStore.qml, ui/imports/utils/Global.qml, ui/main.qml
=> refactor(@desktop/general): many errors from the log are fixed

ui/app/AppLayouts/Chat/panels/communities/CommunityProfilePopupOverviewPanel.qml, ui/app/AppLayouts/Chat/stores/RootStore.qml
=> fix(@communities): copy to clipboard community

src/app/boot/app_controller.nim, src/app/modules/main/chat_section/chat_content/input_area/controller.nim, src/app/modules/main/chat_section/chat_content/input_area/controller_interface.nim, src/app/modules/main/chat_section/chat_content/input_area/gif_column_model.nim, src/app/modules/main/chat_section/chat_content/input_area/module.nim, src/app/modules/main/chat_section/chat_content/input_area/private_interfaces/module_access_interface.nim, src/app/modules/main/chat_section/chat_content/input_area/view.nim, src/app/modules/main/chat_section/chat_content/module.nim, src/app/modules/main/chat_section/module.nim, src/app/modules/main/chat_section/private_interfaces/module_access_interface.nim, src/app/modules/main/controller.nim, src/app/modules/main/module.nim, src/app/modules/main/private_interfaces/module_access_interface.nim, src/app/modules/main/private_interfaces/module_controller_delegate_interface.nim, src/app_service/service/gif/dto.nim, src/app_service/service/gif/service.nim, src/app_service/service/gif/service_interface.nim, src/app_service/service/settings/dto/settings.nim, src/app_service/service/settings/service.nim, src/app_service/service/settings/service_interface.nim, ui/imports/shared/status/StatusGifColumn.qml, ui/imports/shared/status/StatusGifPopup.qml, ui/imports/shared/stores/RootStore.qml
=> refactor(@desktop): gif section

src/app/modules/main/activity_center/controller.nim, src/app/modules/main/activity_center/controller_interface.nim, src/app/modules/main/activity_center/module.nim, src/app/modules/main/chat_section/chat_content/controller.nim, src/app/modules/main/chat_section/chat_content/controller_interface.nim, src/app/modules/main/chat_section/chat_content/messages/controller.nim, src/app/modules/main/chat_section/chat_content/messages/controller_interface.nim, src/app/modules/main/chat_section/chat_content/messages/module.nim, src/app/modules/main/chat_section/chat_content/module.nim, src/app/modules/shared_models/message_item.nim, src/app/modules/shared_models/message_item_qobject.nim, src/app/modules/shared_models/message_model.nim, ui/app/AppLayouts/Chat/views/ChatMessagesView.qml, ui/app/AppLayouts/Profile/stores/AdvancedStore.qml, ui/imports/shared/views/chat/CompactMessageView.qml, ui/imports/shared/views/chat/MessageView.qml, ui/imports/utils/Global.qml
=> fix(chat): fix sticker button not showing + stickers not showing in chat

ui/app/AppLayouts/Chat/popups/community/CommunityProfilePopup.qml, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Chat/views/CommunityColumnView.qml, ui/app/AppLayouts/stores/RootStore.qml
=> fix: restore community private key field content in dialog

ui/app/AppLayouts/Onboarding/popups/BeforeGetStartedModal.qml
=> fix(@onboarding): no autoclose on popup

ui/app/AppLayouts/Chat/popups/PrivateChatPopup.qml, ui/imports/shared/controls/AddressInput.qml, ui/imports/shared/controls/ContactsListAndSearch.qml, ui/imports/shared/views/SearchResults.qml
=> fix(chat): fix starting 1-1 chat because of ContactList signal bug

src/app_service/service/node_configuration/service.nim
Changes the DNS discovery url used to retrieve Waku2 nodes, as described in here:
status-im/infra-nim-waku#34
=> chore: change dns discovery url (base_bc)

src/app_service/service/chat/service.nim, ui/app/AppLayouts/Chat/views/ChatMessagesView.qml, ui/imports/shared/views/chat/CompactMessageView.qml, ui/imports/shared/views/chat/MessageContextMenuView.qml, ui/imports/shared/views/chat/MessageView.qml
Update chat after image is sent.
Fixes: #4404
https://user-images.githubusercontent.com/33099791/149772483-c89295d3-233b-4221-b6b4-9f94950a7c87.mp4
=> fix(@desktop/chat): update chat after image is sent

src/app/global/utils.nim, ui/app/AppLayouts/Chat/ChatLayout.qml, ui/app/AppLayouts/Chat/popups/GroupInfoPopup.qml, ui/app/AppLayouts/Chat/popups/PinnedMessagesPopup.qml, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Chat/views/ChatColumnView.qml, ui/app/AppLayouts/Chat/views/ChatContentView.qml, ui/app/AppLayouts/Chat/views/CommunityColumnView.qml, ui/app/AppLayouts/Chat/views/ContactsColumnView.qml, ui/imports/shared/views/chat/MessageContextMenuView.qml
=> fix(chat): fix copy and download image

src/app/modules/shared_models/message_item_qobject.nim, src/app_service/service/activity_center/dto/notification.nim, ui/app/AppLayouts/Chat/ChatLayout.qml, ui/app/AppLayouts/Chat/popups/ActivityCenterPopup.qml, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Chat/views/ActivityCenterGroupRequest.qml, ui/app/AppLayouts/Chat/views/ActivityCenterMessageComponentView.qml, ui/app/AppLayouts/Chat/views/ChatColumnView.qml
Closes #4408
Fixed Activity center shows nothing
=> fix:activity center view is empty

src/app/modules/main/chat_section/module.nim
=> fix(chat): set 1-1 chat as active when already created

ui/app/AppLayouts/Chat/views/ChatContentView.qml, ui/app/AppLayouts/Chat/views/ChatContextMenuView.qml
=> fix(chat): fix 1-1 chat delete and profile top bar click

src/app/modules/main/chat_section/controller.nim, src/app/modules/main/chat_section/controller_interface.nim, src/app/modules/main/chat_section/model.nim, src/app/modules/main/chat_section/module.nim, src/app/modules/main/chat_section/private_interfaces/module_controller_delegate_interface.nim, src/app/modules/main/chat_section/sub_model.nim, src/app/modules/main/chat_section/view.nim, src/app_service/service/community/service.nim, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Chat/views/ChatContentView.qml, ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
fixes #4415
Adds missing delete channel functionality in communities
communities 
https://user-images.githubusercontent.com/60327365/149994016-40c2dd4d-1f1c-439f-b2f8-78d72b9592c6.mov
=> fix(@desktop/community): added option to delete community channel

src/app/modules/main/chat_section/chat_content/users/controller.nim, src/app/modules/main/chat_section/chat_content/users/model.nim, src/app/modules/main/chat_section/chat_content/users/module.nim, src/app/modules/main/chat_section/chat_content/users/private_interfaces/module_controller_delegate_interface.nim, src/app/modules/main/chat_section/controller.nim, src/app/modules/main/chat_section/controller_interface.nim, src/app/modules/main/chat_section/model.nim, src/app/modules/main/chat_section/module.nim, src/app/modules/main/chat_section/private_interfaces/module_controller_delegate_interface.nim, src/app/modules/main/chat_section/private_interfaces/module_view_delegate_interface.nim, src/app/modules/main/chat_section/view.nim, src/app/modules/shared_models/contacts_model.nim, src/app_service/service/chat/service.nim, ui/app/AppLayouts/Chat/ChatLayout.qml, ui/app/AppLayouts/Chat/panels/ContactListPanel.qml, ui/app/AppLayouts/Chat/popups/GroupChatPopup.qml, ui/app/AppLayouts/Chat/popups/GroupInfoPopup.qml, ui/app/AppLayouts/Chat/views/ChatContentView.qml, ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
=> refactor(groups): Move groups to new architecture

ui/app/AppLayouts/Chat/popups/community/CreateCommunityPopup.qml
=> fix(@communities): Disable create button on invalid form

src/app_service/service/wallet_account/service.nim
Status lib PR: https://github.com/status-im/status-lib/pull/167/files
Status go PR: https://github.com/status-im/status-go/pull/2492
fixes #4350
=> feat: move create accounts to status-go

ui/app/AppLayouts/Chat/popups/ProfilePopup.qml, ui/app/AppLayouts/Profile/ProfileLayout.qml, ui/app/AppLayouts/stores/RootStore.qml, ui/app/AppMain.qml
=> feat(ProfilePopup): Add avatar change functionality

ui/app/AppLayouts/Wallet/WalletLayout.qml, ui/app/AppLayouts/Wallet/stores/RootStore.qml
=> fix(@wallet): hide signing phrase accept

src/app/modules/main/chat_section/chat_content/messages/view.nim, src/dev/benchmark.nim, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Chat/views/ChatColumnView.qml, ui/app/AppLayouts/Chat/views/ChatContentView.qml
=> perf(@chat): Fix slow chat switch

src/app/modules/main/chat_section/chat_content/messages/controller.nim, src/app/modules/main/chat_section/chat_content/messages/module.nim, src/app/modules/main/chat_section/chat_content/messages/private_interfaces/module_view_delegate_interface.nim, src/app/modules/shared_models/message_model.nim
=> fix(@chat): react to on clear history

src/app/modules/main/chat_section/chat_content/users/controller.nim, src/app/modules/main/chat_section/chat_content/users/module.nim, src/app_service/service/community/service.nim
=> fix(userlist): member added to userlist on approve and duplicate member

ui/imports/shared/views/chat/CompactMessageView.qml
=> fix(@desktop/chat-messages): [base_bc] emojis alignment is wrong

ui/app/AppLayouts/Wallet/popups/AddAccountWithPrivateKeyModal.qml
=> fix(@wallet): Fix text area for importing private key

ui/app/AppMain.qml, ui/imports/shared/status/StatusEmojiSuggestionPopup.qml, ui/imports/shared/status/StatusInputListPopup.qml
=> fix(ChannelPicker): re-hook channel picker with new model and functions

ui/app/AppLayouts/Chat/popups/community/CreateCommunityPopup.qml
=> fix(community): fix community edit setting undefined color

src/app/modules/main/chat_section/controller.nim, src/app/modules/main/chat_section/controller_interface.nim, src/app/modules/main/chat_section/module.nim, src/app/modules/main/chat_section/private_interfaces/module_controller_delegate_interface.nim, src/app/modules/main/chat_section/private_interfaces/module_view_delegate_interface.nim, src/app/modules/main/chat_section/view.nim, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Chat/views/ChatContentView.qml, ui/app/AppLayouts/Chat/views/ChatContextMenuView.qml, ui/app/AppLayouts/Chat/views/CommunityColumnView.qml, ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
=> fix(@chat): react to on left chat

src/app_service/service/community/service.nim
=> fix(@communities): create channel

ui/app/AppLayouts/Wallet/popups/ReceiveModal.qml, ui/app/AppLayouts/Wallet/stores/RootStore.qml, ui/imports/shared/controls/Input.qml, ui/imports/shared/stores/RootStore.qml
=> fix(@wallet): receive modal

ui/app/AppLayouts/Chat/popups/community/CommunitiesPopup.qml, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Chat/views/ContactsColumnView.qml, ui/app/AppLayouts/stores/RootStore.qml
=> fix(communities): fix icon, members and color + set observed and active

ui/app/AppLayouts/Chat/panels/ContactListPanel.qml
=> fix(groups): Hide unchecked users in group creation popup

ui/app/AppLayouts/Chat/popups/GroupInfoPopup.qml
=> fix(groups): Update group info user list

src/app/modules/main/chat_section/chat_content/controller.nim, src/app/modules/main/chat_section/chat_content/messages/private_interfaces/module_access_interface.nim, src/app/modules/main/chat_section/chat_content/messages/private_interfaces/module_controller_delegate_interface.nim, src/app/modules/main/chat_section/controller.nim, src/app_service/service/community/service.nim
=> fix(@desktop/chat-content): [base_bc] can't select a community channel

ui/app/AppLayouts/Chat/views/ChatContentView.qml
fixes #4531
Added missing start new 1-1 chat code
chat
https://user-images.githubusercontent.com/60327365/151237296-3b555b11-89af-4eaf-b837-96a964ff2412.mov
=> fix(@desktop/chat): send message is not working from context menu

src/app_service/service/activity_center/service.nim
=> fix(@communities): Handle Activity center event

ui/app/AppLayouts/Profile/views/PrivacyView.qml
=> fix(@settings): fix privacy settings toggle

src/app/modules/main/controller.nim, src/app/modules/main/controller_interface.nim, src/app/modules/main/module.nim, src/app/modules/main/private_interfaces/module_access_interface.nim, src/app/modules/main/private_interfaces/module_controller_delegate_interface.nim, src/app/modules/shared_models/section_item.nim
=> fix(profile): fix profile seed phrase backup badge

src/app/modules/main/chat_section/chat_content/controller.nim, src/app/modules/main/chat_section/chat_content/module.nim, src/app/modules/main/chat_section/chat_content/private_interfaces/module_controller_delegate_interface.nim, src/app/modules/main/chat_section/chat_content/view.nim, src/app_service/service/chat/service.nim
=> feat(groups): Update chat details when group renamed

src/app/modules/main/activity_center/module.nim, src/app/modules/main/chat_section/chat_content/messages/controller.nim, src/app/modules/main/chat_section/chat_content/messages/controller_interface.nim, src/app/modules/main/chat_section/chat_content/messages/module.nim, src/app/modules/main/chat_section/chat_content/messages/private_interfaces/module_view_delegate_interface.nim, src/app/modules/main/chat_section/chat_content/messages/view.nim, src/app/modules/main/chat_section/chat_content/module.nim, src/app/modules/shared_models/message_item.nim, src/app/modules/shared_models/message_model.nim, src/app_service/service/message/async_tasks.nim, src/app_service/service/message/service.nim, ui/app/AppLayouts/Chat/popups/PinnedMessagesPopup.qml, ui/app/AppLayouts/Chat/stores/MessageStore.qml, ui/app/AppLayouts/Chat/views/ActivityCenterMessageComponentView.qml, ui/app/AppLayouts/Chat/views/ChatMessagesView.qml, ui/imports/shared/views/chat/CompactMessageView.qml, ui/imports/shared/views/chat/LinksMessageView.qml, ui/imports/shared/views/chat/MessageView.qml
https://github.com/status-im/status-lib/pull/171
fixes #4514
=> fix(@chat): display link urls

ui/imports/shared/views/chat/ChannelIdentifierView.qml, ui/imports/shared/views/chat/MessageView.qml
=> fix(groups): Hide invitation for admin

.gitignore, CMakeLists.txt, README.md, conanfile.py, test-cpp/CMakeLists.txt, test-cpp/testDeps.cpp
=> feat(@desktop/cpp): add conanfile, fruit, gtest

src/app_service/service/message/dto/message.nim, src/app_service/service/message/service.nim
=> fix(@chat): display message with link

src/app/modules/main/chat_section/controller.nim, src/app/modules/main/chat_section/controller_interface.nim, src/app/modules/main/chat_section/model.nim, src/app/modules/main/chat_section/module.nim, src/app/modules/main/chat_section/private_interfaces/module_controller_delegate_interface.nim, src/app/modules/main/chat_section/private_interfaces/module_view_delegate_interface.nim, src/app/modules/main/chat_section/view.nim, src/app/modules/main/communities/controller.nim, src/app/modules/main/communities/controller_interface.nim, src/app/modules/main/communities/module.nim, src/app/modules/main/communities/private_interfaces/module_access_interface.nim, src/app/modules/main/communities/view.nim, src/app_service/service/chat/dto/chat.nim, src/app_service/service/community/service.nim, ui/app/AppLayouts/Chat/popups/community/CreateCategoryPopup.qml, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Chat/views/ChatColumnView.qml, ui/app/AppLayouts/Chat/views/ChatContentView.qml, ui/app/AppLayouts/Chat/views/CommunityColumnView.qml, ui/imports/utils/Constants.qml
Fixes: https://github.com/status-im/status-desktop/issues/4406
=> feat(communities): create categories

src/app/boot/app_controller.nim, src/app_service/service/gif/service.nim, src/app_service/service/settings/dto/settings.nim, src/app_service/service/settings/service.nim, src/app_service/service/settings/service_interface.nim
Move the calls to Tenor to status_go
chat
fixes #4355
=> fix: Move gif to status-go

.clang-tidy
Closes: #4430
Integration steps: https://hackmd.io/@tvcxYXntQVCosMs79UIszw/rJxhcBHCY
=> feat(@desktop/cpp): add initial .clang-tigdy config

src/app/modules/main/chat_section/controller.nim, src/app/modules/main/chat_section/controller_interface.nim, src/app/modules/main/chat_section/module.nim, src/app/modules/main/chat_section/private_interfaces/module_view_delegate_interface.nim, src/app/modules/main/chat_section/view.nim, src/app_service/service/chat/dto/chat.nim, src/app_service/service/community/service.nim, ui/app/AppLayouts/Chat/popups/community/CreateChannelPopup.qml, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
Requires
- https://github.com/status-im/status-lib/pull/173
Fixes #4628
=> refactor(communities): create channel in category

ui/app/AppLayouts/Chat/views/CommunityColumnView.qml, ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
=> fix(groups): Add popup to view group context menu action

src/app/modules/main/communities/controller.nim, src/app/modules/main/communities/module.nim, src/app/modules/main/communities/private_interfaces/module_controller_delegate_interface.nim, src/app/modules/main/communities/view.nim, src/app_service/service/chat/service.nim, src/app_service/service/community/service.nim, ui/app/AppLayouts/Chat/popups/community/CommunityDetailPopup.qml
=> fix(communities): enable leaving and then re-joining a community

src/app/boot/app_controller.nim, src/app/modules/startup/module.nim, src/app/modules/startup/private_interfaces/module_access_interface.nim, src/app/modules/startup/view.nim, src/app_service/service/contacts/service.nim, src/app_service/service/keychain/service.nim, src/nim_status_client.nim, test-scripts/app-run-test.sh, ui/main.qml
Changes done in `dotherside`:
- https://github.com/status-im/dotherside/pull/55
Fixed issues:
- `setAppWidth` issue - fixed
- `signal connection` issue - fixed
Test script `app-run-test.sh` added to `test-scripts` folder.
=> multiple issues running the app

src/app/modules/main/chat_section/base_item.nim, src/app/modules/main/chat_section/chat_content/chat_details.nim, src/app/modules/main/chat_section/chat_content/module.nim, src/app/modules/main/chat_section/chat_content/view.nim, src/app/modules/main/chat_section/controller.nim, src/app/modules/main/chat_section/controller_interface.nim, src/app/modules/main/chat_section/item.nim, src/app/modules/main/chat_section/module.nim, src/app/modules/main/chat_section/private_interfaces/module_view_delegate_interface.nim, src/app/modules/main/chat_section/view.nim, src/app/modules/main/communities/controller.nim, src/app/modules/main/communities/module.nim, src/app/modules/main/communities/private_interfaces/module_controller_delegate_interface.nim, ui/app/AppLayouts/Chat/popups/community/CreateChannelPopup.qml, ui/app/AppLayouts/Chat/views/ChatContentView.qml, ui/app/AppLayouts/Chat/views/ChatContextMenuView.qml, ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
=> fix(community): hook edit community channel

src/app/boot/app_controller.nim, src/app/modules/main/wallet_section/transactions/controller.nim, src/app/modules/main/wallet_section/transactions/controller_interface.nim, src/app/modules/main/wallet_section/transactions/io_interface.nim, src/app/modules/main/wallet_section/transactions/module.nim, src/app/modules/main/wallet_section/transactions/view.nim, src/app_service/service/ens/utils.nim, src/app_service/service/eth/dto/contract.nim, src/app_service/service/provider/service.nim, src/app_service/service/transaction/service.nim, ui/app/AppLayouts/stores/RootStore.qml, ui/imports/shared/popups/SendModal.qml, ui/imports/shared/popups/SignTransactionModal.qml
Fixes #4557
This makes the browser send transaction work. Hooks the estimateGas and also implements the sendTransaction for the provider
=> fix(browser-tx): fix estimate gas and send TX on the browser

src/app_service/service/contacts/async_tasks.nim
fixes #4623
This fixes the issue that when wallet address is added to send modal, an incorrect contact information is not displayed.
Wallet
=> fix(@desktop/wallet): send transaction to address UI is broken

ui/app/AppLayouts/Chat/popups/community/CreateChannelPopup.qml, ui/app/AppLayouts/Chat/views/ChatContentView.qml, ui/app/AppLayouts/Chat/views/ChatContextMenuView.qml, ui/app/AppLayouts/Chat/views/CommunityColumnView.qml, ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
=> chore(community): remove pinned messages button in Edit community popup

src/app/modules/main/chat_section/controller.nim, src/app/modules/main/chat_section/controller_interface.nim, src/app/modules/main/chat_section/model.nim, src/app/modules/main/chat_section/module.nim, src/app/modules/main/chat_section/private_interfaces/module_controller_delegate_interface.nim, src/app/modules/main/chat_section/private_interfaces/module_view_delegate_interface.nim, src/app/modules/main/chat_section/sub_model.nim, src/app/modules/main/chat_section/view.nim, src/app_service/service/community/service.nim, ui/app/AppLayouts/Chat/popups/community/CreateCategoryPopup.qml, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
=> refactor(communities): edit categories

ui/app/AppLayouts/Chat/popups/GroupInfoPopup.qml
It restores job done in PR #4461 - Task #4386 after base_bc rebase.
Group Chat / View Group
=> fix(@desktop/chat):  [restore after rebase] Group members list must show only 5

src/app/modules/main/communities/controller.nim, src/app/modules/main/communities/module.nim, src/app/modules/main/communities/private_interfaces/module_access_interface.nim, src/app/modules/main/communities/private_interfaces/module_controller_delegate_interface.nim, src/app/modules/main/communities/view.nim, src/app/modules/main/controller.nim, src/app_service/service/community/service.nim, src/app_service/service/message/service.nim, ui/app/AppLayouts/Chat/popups/community/AccessExistingCommunityPopup.qml, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
=> fix(@desktop/communities): community import has some issues

src/app/modules/main/profile_section/advanced/controller.nim, src/app/modules/main/profile_section/advanced/controller_interface.nim, src/app/modules/main/profile_section/advanced/module.nim, src/app/modules/main/profile_section/advanced/private_interfaces/module_view_delegate_interface.nim, src/app/modules/main/profile_section/advanced/view.nim, ui/app/AppLayouts/Profile/stores/AdvancedStore.qml, ui/app/AppLayouts/Profile/views/AdvancedView.qml
=> feat(@desktop/settings): [re-add] Add developer mode toggle

src/app/modules/main/activity_center/controller.nim, src/app/modules/main/activity_center/controller_interface.nim, src/app/modules/main/activity_center/io_interface.nim, src/app/modules/main/activity_center/module.nim, src/app/modules/main/activity_center/view.nim, ui/app/AppLayouts/Chat/views/ActivityCenterMessageComponentView.qml
=> refactor(@activity_center): Add switch to section/chat

src/app_service/service/message/service.nim, ui/app/AppLayouts/Chat/popups/PinnedMessagesPopup.qml
=> fix(pins): fix max 3 pins and unpining pins the new message

ui/app/AppLayouts/Profile/popups/ChangeProfilePicModal.qml, ui/app/AppLayouts/Profile/views/MyProfileView.qml, ui/app/AppMain.qml, ui/imports/shared/popups/ProfilePopup.qml, ui/imports/utils/Global.qml
=> chore(@desktop/general): add avatar change functionality

src/app/modules/main/chat_section/chat_content/module.nim, src/app/modules/main/chat_section/chat_content/users/controller.nim, src/app/modules/main/chat_section/chat_content/users/controller_interface.nim, src/app/modules/main/chat_section/chat_content/users/module.nim, src/app/modules/main/chat_section/chat_content/users/private_interfaces/module_controller_delegate_interface.nim, src/app/modules/shared_models/user_item.nim, src/app/modules/shared_models/user_model.nim, src/app_service/service/chat/dto/chat.nim, src/app_service/service/chat/service.nim
fixes https://github.com/status-im/status-desktop/issues/4612
fixes https://github.com/status-im/status-desktop/issues/4613
fixes #4611
=> refactor(@chat): add chat members

src/app/modules/main/activity_center/controller.nim
fixes #4631
Only keep event from the services related to AC
=> fix(@activity_center): fix dup messages

src/app/boot/app_controller.nim, src/app_service/service/os_notification/service.nim
=> fix(notifications): [re-add] fix notification setup called too soon

src/app/modules/main/wallet_section/account_tokens/module.nim, src/app/modules/main/wallet_section/accounts/module.nim, src/app/modules/main/wallet_section/current_account/module.nim, src/app/modules/main/wallet_section/module.nim, src/app_service/service/wallet_account/service.nim, src/backend/wallet.nim
This change is actually the same one done in the commit [6915c19c84a75e7b0f99e9eb1899464ee0e2acff](https://github.com/status-im/status-desktop/commit/6915c19c84a75e7b0f99e9eb1899464ee0e2acff) we had in the "old" master.
Fixes #4670
=> feat(@desktop/wallet): move create accounts to `status-go`

ui/app/AppLayouts/Wallet/controls/TransactionDelegate.qml, ui/app/AppLayouts/Wallet/stores/RootStore.qml
Fixes #4684
Correctly display the date and if the node is an archival node
=> fix(@wallet): [re-add] tx history view

src/app/modules/main/chat_section/controller.nim, src/app/modules/main/chat_section/controller_interface.nim, src/app/modules/main/chat_section/model.nim, src/app/modules/main/chat_section/module.nim, src/app/modules/main/chat_section/private_interfaces/module_view_delegate_interface.nim, src/app/modules/main/chat_section/view.nim, src/app/modules/main/communities/controller.nim, src/app_service/service/chat/dto/chat.nim, src/app_service/service/community/service.nim, src/backend/communities.nim, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
=> refactor(communities): sort categories and chats

src/app/modules/main/chat_search_item.nim, src/app/modules/main/chat_search_model.nim, src/app/modules/main/chat_section/model.nim, src/app/modules/main/chat_section/module.nim, src/app/modules/main/chat_section/private_interfaces/module_access_interface.nim, src/app/modules/main/chat_section/sub_model.nim, src/app/modules/main/controller.nim, src/app/modules/main/controller_interface.nim, src/app/modules/main/module.nim, src/app/modules/main/private_interfaces/module_view_delegate_interface.nim, src/app/modules/main/view.nim, ui/app/AppLayouts/stores/RootStore.qml, ui/app/AppMain.qml, ui/imports/shared/status/StatusSearchListPopup.qml, ui/imports/shared/status/qmldir
Closes: #4059
**Updated version:**
https://user-images.githubusercontent.com/33099791/152864269-65c775d6-f23e-4085-b5ec-1bb3f9ee8091.mp4
Previous version:
https://user-images.githubusercontent.com/33099791/152536507-a04580be-f8a1-4ee8-b33f-31ebf5a4784b.mp4
=> fix(@desktop/sections): make ctrl+k display chats from communities

src/app/global/local_account_sensitive_settings.nim, ui/app/AppLayouts/Profile/stores/AdvancedStore.qml, ui/app/AppLayouts/Profile/views/AdvancedView.qml
Add a new feature flag for multi network
=> feat(@settings): Add feature flag for multi network

ui/imports/shared/status/StatusChatInput.qml, ui/imports/shared/status/StatusEmojiSuggestionPopup.qml
=> fix(ChatInput): fix clicking on emoji suggestion

ui/app/AppLayouts/stores/RootStore.qml, ui/app/AppMain.qml, ui/imports/shared/status/StatusChatImageLoader.qml, ui/imports/shared/views/chat/LinksMessageView.qml
=> fix(link-message): fix link unfurling display and height

ui/app/AppLayouts/Profile/popups/ChangePasswordModal.qml, ui/app/AppLayouts/Profile/views/PrivacyView.qml
Fixes #4672
Original issues
https://github.com/status-im/status-desktop/issues/4375
https://github.com/status-im/status-desktop/issues/4376
=> fix(@desktop/settings): [re-add] ensure new password is confirmed

ui/imports/shared/popups/SignTransactionModal.qml
=> fix(browser-sign): show signing phrase in the sign tx modal

src/app/boot/app_controller.nim, src/app/modules/main/wallet_section/all_tokens/controller.nim, src/app_service/common/network_constants.nim, src/app_service/service/ens/service.nim, src/app_service/service/network/service.nim, src/app_service/service/settings/dto/settings.nim, src/app_service/service/token/service.nim, src/app_service/service/wallet_account/service.nim, src/backend/eth.nim, src/backend/tokens.nim
* Balances are fetch for multi chain
* Native token are build based on the network information
=> feat(@wallet): Enable multi network for wallet account

ui/app/AppLayouts/Wallet/controls/NetworkFilter.qml, ui/app/AppLayouts/Wallet/panels/WalletHeader.qml, ui/app/AppLayouts/Wallet/popups/NetworkSelectPopup.qml, ui/app/AppLayouts/Wallet/stores/RootStore.qml, ui/app/AppLayouts/Wallet/views/RightTabView.qml
Bring from wallet 2 the network filter (data not plugged yet)
=> feat(@wallet): bring back filter network from wallet2

src/app/boot/app_controller.nim, src/app/modules/main/module.nim, src/app/modules/main/profile_section/io_interface.nim, src/app/modules/main/profile_section/module.nim, src/app/modules/main/profile_section/wallet/io_interface.nim, src/app/modules/main/profile_section/wallet/module.nim, src/app/modules/main/profile_section/wallet/networks/controller.nim, src/app/modules/main/profile_section/wallet/networks/controller_interface.nim, src/app/modules/main/profile_section/wallet/networks/io_interface.nim, src/app/modules/main/profile_section/wallet/networks/item.nim, src/app/modules/main/profile_section/wallet/networks/model.nim, src/app/modules/main/profile_section/wallet/networks/module.nim, src/app/modules/main/profile_section/wallet/networks/view.nim, src/app/modules/main/profile_section/wallet/private_interfaces/module_access_interface.nim, src/app/modules/main/profile_section/wallet/private_interfaces/module_base_interface.nim, ui/app/AppLayouts/Profile/ProfileLayout.qml, ui/app/AppLayouts/Profile/panels/MenuPanel.qml, ui/app/AppLayouts/Profile/stores/ProfileSectionStore.qml, ui/app/AppLayouts/Profile/stores/WalletStore.qml, ui/app/AppLayouts/Profile/views/LeftTabView.qml, ui/app/AppLayouts/Profile/views/WalletView.qml, ui/app/AppLayouts/Profile/views/wallet/MainView.qml, ui/app/AppLayouts/Profile/views/wallet/NetworksView.qml
Add App + Wallet section in settings when multi network is enabled
List networks (quite ugly but data is loaded)
=> feat(@settings): Add wallet settings with network

src/app/modules/main/chat_section/chat_content/messages/controller.nim, src/app/modules/main/chat_section/chat_content/messages/controller_interface.nim, src/app/modules/main/chat_section/chat_content/messages/module.nim, src/app/modules/main/chat_section/chat_content/messages/private_interfaces/module_controller_delegate_interface.nim, src/app/modules/main/chat_section/chat_content/messages/private_interfaces/module_view_delegate_interface.nim, src/app/modules/main/chat_section/chat_content/messages/view.nim, src/app/modules/shared_models/message_model.nim, ui/app/AppLayouts/Chat/stores/MessageStore.qml, ui/imports/shared/views/chat/ChannelIdentifierView.qml, ui/imports/shared/views/chat/MessageView.qml
=> fix(@desktop/chat): can't join to group chat by clicking [Join chat] or decline invitation with [Decline invitation]

src/app/modules/main/chat_section/chat_content/messages/module.nim, src/app/modules/shared_models/message_item.nim, src/app/modules/shared_models/message_model.nim, ui/imports/shared/views/chat/CompactMessageView.qml, ui/imports/shared/views/chat/LinksMessageView.qml
=> fix(links): fix editing a link and reflect what the new link shows

src/app_service/service/community/service.nim
Fixes #4816
The problem was that signals and responses containing community data don't contain the requests, so we must manually save them before sending the update events
=> fix(communities): fix pending request to join when receiving new signals

ui/app/AppLayouts/Chat/popups/GroupInfoPopup.qml, ui/app/AppLayouts/Chat/views/ChatContentView.qml
Closes: #4822
Fixed members count in group chat subtitle
Groups
=> fix(groups): Fix members count

src/app/modules/main/chat_section/base_item.nim, src/app/modules/main/chat_section/controller.nim, src/app/modules/main/chat_section/item.nim, src/app/modules/main/chat_section/model.nim, src/app/modules/main/chat_section/module.nim, src/app/modules/main/chat_section/private_interfaces/module_controller_delegate_interface.nim, src/app_service/service/chat/dto/chat.nim, src/app_service/service/chat/service.nim
Closes: #4767
[StatusQ PR](https://github.com/status-im/StatusQ/pull/560) 
Process `message.new` event and create new chat from groups invitations
Chat section
=> fix(groups): Fix invitations for groups

src/app/boot/app_controller.nim, src/app/global/utils.nim, src/app/modules/main/browser_section/dapps/private_interfaces/module_controller_delegate_interface.nim, src/app/modules/main/browser_section/dapps/private_interfaces/module_view_delegate_interface.nim, src/app/modules/main/browser_section/provider/controller.nim, src/app/modules/main/browser_section/provider/module.nim, src/app_service/common/network_constants.nim, src/app_service/service/provider/service.nim, src/app_service/service/provider/service_interface.nim, src/backend/provider.nim, ui/app/AppLayouts/Browser/BrowserLayout.qml, ui/app/AppLayouts/Browser/popups/BrowserConnectionModal.qml, ui/app/AppLayouts/Browser/stores/RootStore.qml, ui/app/AppLayouts/Browser/views/WebProviderObj.qml
Changes done here are applied on top of changes done in PR #4730, so check it before this one.
This change is actually the same one done in the commit [f5d53f9112cc2f1dbd14b31997d476d3936c0ecb](https://github.com/status-im/status-desktop/commit/f5d53f9112cc2f1dbd14b31997d476d3936c0ecb) we had in the "old" master.
Fixes #4693
=> refactor(@desktop/browser): move provider logic to `status-go`

src/app/modules/main/chat_section/chat_content/messages/controller.nim, src/app_service/service/contacts/service.nim, ui/imports/shared/controls/chat/UsernameLabel.qml, ui/imports/shared/views/chat/CompactMessageView.qml, ui/imports/shared/views/chat/MessageView.qml
=> fix: fix self profile image not showing in the message and fix name

src/app_service/service/community/service.nim
Fixes #4801
The problem was that the new state of the community wasn't saved and propagated correctly.
=> fix(communities): fix invite link enabling joining twice

src/app_service/service/contacts/service.nim, src/backend/contacts.nim, src/nim_status_client.nim
Fixes #4744
Requires
- https://github.com/status-im/nim-status-go/pull/6
- https://github.com/status-im/status-go/pull/2522
- https://github.com/status-im/dotherside/pull/56
- https://github.com/status-im/nimqml/pull/36
=> feat: use http server for images and identicons

src/app/modules/main/chat_section/controller.nim, src/app/modules/main/chat_section/controller_interface.nim, src/app/modules/main/chat_section/module.nim, src/app_service/service/chat/service.nim
=> fix(@dekstop/chat): wrong redirect when opening a profile -> send message inside of community

fleets.json, src/app/core/fleets/fleet_configuration.nim, src/app/modules/main/node_section/controller.nim, src/app/modules/main/profile_section/advanced/controller.nim, src/app_service/service/node/service.nim, src/app_service/service/node_configuration/service.nim, src/app_service/service/settings/dto/settings.nim, src/app_service/service/settings/service.nim, ui/app/AppLayouts/Chat/views/ChatContextMenuView.qml, ui/app/AppLayouts/Profile/popups/FleetsModal.qml, ui/app/AppLayouts/Profile/stores/AdvancedStore.qml, ui/imports/utils/Constants.qml
Fixes #4843 
Required for:
- https://github.com/status-im/infra-status/issues/1
Requires:
- https://github.com/status-im/status-go/pull/2544
=> feat: add status.test fleet

src/app_service/service/contacts/async_tasks.nim, src/app_service/service/contacts/service.nim
=> fix(@dekstop/chat): creating a chat with numeric only crashes the app

src/app/modules/main/activity_center/module.nim, src/app/modules/main/chat_section/chat_content/messages/module.nim, src/app/modules/main/chat_section/chat_content/module.nim, src/app/modules/main/communities/controller.nim, src/app/modules/shared_models/message_item.nim, src/app/modules/shared_models/message_model.nim, src/app_service/service/community/service.nim, src/app_service/service/message/dto/message.nim, ui/app/AppLayouts/Chat/views/ChatMessagesView.qml, ui/imports/shared/views/chat/CompactMessageView.qml, ui/imports/shared/views/chat/MessageView.qml
=> fix(invitation): fix community invite not showing in 1-1 chats

README.md
Add instructions to build CPP app for MacOS.
=> chore(cpp-app): Add instructions to build app for MacOS

src/app/modules/main/chat_section/chat_content/users/controller.nim, src/app/modules/main/chat_section/controller.nim, src/app/modules/main/chat_section/controller_interface.nim, src/app/modules/main/chat_section/module.nim, src/app/modules/main/chat_section/private_interfaces/module_view_delegate_interface.nim, src/app/modules/main/chat_section/view.nim, src/app/modules/main/communities/controller.nim, src/app/modules/main/communities/controller_interface.nim, src/app/modules/main/communities/module.nim, src/app/modules/main/communities/private_interfaces/module_access_interface.nim, src/app/modules/main/communities/view.nim, src/app/modules/shared_models/active_section.nim, src/app_service/service/community/service.nim, ui/app/AppLayouts/Chat/panels/communities/CommunityProfilePopupMembersListPanel.qml, ui/app/AppLayouts/Chat/stores/RootStore.qml
=> fix(community): re-hook kick user from community

src/app/modules/main/chat_section/chat_content/users/controller.nim
This fixed the issue in a way that members list on the right get updated immediately after we invite a new member. 
Currently there is a signal sent from the `status-go` which notifies the app when invited member joins a certain community, but it's hard to identify that it's sent because of that action, cause there are a lot of actions which are causing exactly the same signal with all details for that community.
Fixes #4870
=> fix(@dekstop/chat): members panel on the Community invite sender's app is only updated after the app is rebooted

src/app/modules/main/profile_section/privacy/controller.nim, src/app/modules/main/profile_section/privacy/controller_interface.nim, src/app/modules/main/profile_section/privacy/io_interface.nim, src/app/modules/main/profile_section/privacy/module.nim, src/app/modules/main/profile_section/privacy/view.nim, src/app_service/service/privacy/service.nim, ui/app/AppLayouts/Onboarding/shared/CreatePasswordModal.qml, ui/app/AppLayouts/Onboarding/views/LoginView.qml, ui/app/AppLayouts/Profile/popups/StoreToKeychainSelectionModal.qml, ui/app/AppLayouts/Profile/stores/PrivacyStore.qml, ui/app/AppLayouts/Profile/views/PrivacyView.qml
fixes #4358
Validated the entered password before it is stored to the keychain
Onboarding, Settings
https://user-images.githubusercontent.com/60327365/155523517-56f7c732-0c47-45e0-b6df-afa5c1513d81.mov
=> fix(@desktop/settings): Store pass to keychain does not validate entered password

ui/app/AppLayouts/Browser/BrowserLayout.qml, ui/app/AppLayouts/Chat/popups/ActivityCenterPopup.qml, ui/app/AppLayouts/Chat/popups/PrivateChatPopup.qml, ui/app/AppLayouts/Profile/ProfileLayout.qml, ui/app/AppLayouts/Profile/panels/MenuPanel.qml, ui/app/AppLayouts/Profile/stores/ProfileSectionStore.qml, ui/app/AppLayouts/Profile/views/LeftTabView.qml, ui/imports/shared/views/chat/LinksMessageView.qml, ui/imports/utils/Constants.qml, ui/imports/utils/Global.qml
=> fix(@dekstop/chat): clicking on `enable in settings` redirects to network settings

ui/app/AppLayouts/Chat/popups/GroupChatPopup.qml
=> fix(@dekstop/chat): increase the hard limit from 10 to 20 members in a group chat

ui/app/AppLayouts/Profile/views/wallet/MainView.qml
=> feat(@settings): Build layout for settings wallet

src/app/modules/main/chat_section/chat_content/users/controller.nim, src/app_service/service/message/service.nim
=> fix(user-list): fix adding users to user list on new messages

src/app/boot/app_controller.nim, src/app/core/main.nim, src/app/core/notifications/notifications_manager.nim, src/app/modules/main/chat_section/module.nim
Fixes #4263
The problem was that there was still the race condition on initiating the Windows Notification manager.
Also, we were not showing notifications if you were already on the channel that received a message, even if the app was minimized. The Notification manager should be the one handling whether to show a notif in that case, not the section module.
=> fix(notifications): fix windows tray icon and notifications

src/app/modules/main/module.nim, src/app/modules/main/wallet_section/controller.nim, src/app/modules/main/wallet_section/controller_interface.nim, src/app/modules/main/wallet_section/io_interface.nim, src/app/modules/main/wallet_section/module.nim, src/app/modules/main/wallet_section/transactions/controller.nim, src/app/modules/main/wallet_section/transactions/controller_interface.nim, src/app/modules/main/wallet_section/transactions/io_interface.nim, src/app/modules/main/wallet_section/transactions/module.nim, src/app/modules/main/wallet_section/transactions/view.nim, src/app/modules/main/wallet_section/view.nim, src/app_service/service/ens/service.nim, src/app_service/service/eth/utils.nim, src/app_service/service/network/service.nim, src/app_service/service/network/service_interface.nim, src/app_service/service/settings/service.nim, src/app_service/service/settings/service_interface.nim, src/app_service/service/stickers/service.nim, src/app_service/service/transaction/service.nim, src/backend/eth.nim, ui/app/AppLayouts/Browser/stores/WalletStore.qml, ui/app/AppLayouts/Browser/views/WebProviderObj.qml, ui/app/AppLayouts/stores/RootStore.qml, ui/imports/shared/controls/GasSelector.qml, ui/imports/shared/popups/SendModal.qml, ui/imports/shared/popups/SignTransactionModal.qml, ui/imports/shared/status/StatusETHTransactionModal.qml, ui/imports/shared/status/StatusSNTTransactionModal.qml
=> refactor: add back eip1559

src/app/modules/main/wallet_section/buy_sell_crypto/controller.nim, src/app/modules/main/wallet_section/buy_sell_crypto/controller_interface.nim, src/app/modules/main/wallet_section/buy_sell_crypto/io_interface.nim, src/app/modules/main/wallet_section/buy_sell_crypto/item.nim, src/app/modules/main/wallet_section/buy_sell_crypto/model.nim, src/app/modules/main/wallet_section/buy_sell_crypto/module.nim, src/app/modules/main/wallet_section/buy_sell_crypto/view.nim, src/app/modules/main/wallet_section/io_interface.nim, src/app/modules/main/wallet_section/module.nim, src/app_service/service/transaction/cryptoRampDto.nim, src/app_service/service/transaction/service.nim, src/backend/transactions.nim, ui/app/AppLayouts/Wallet/panels/WalletHeader.qml, ui/app/AppLayouts/Wallet/popups/CryptoServicesModal.qml, ui/app/AppLayouts/Wallet/stores/RootStore.qml
fixes #4925
Re-added the buy/sell crypto feature from https://github.com/status-im/status-desktop/pull/3359
Wallet
https://user-images.githubusercontent.com/60327365/156192046-7da95fdc-0fab-4505-93ff-7d47a939742e.mov
=> fix(@desktop/wallet): add/re-add buy crypto feature

ui/imports/shared/status/StatusChatInput.qml
Closes #4867 
Depends on https://github.com/status-im/dotherside/pull/59
Updated chat text input to store all mentions currently in the field and not allow the cursor to get into these when going either left right, or up/down. Also, fixed other copy/paste text issues, when for example a text is copied and pasted somewhere inline the existing string.
chat text input
https://user-images.githubusercontent.com/31625338/155813358-bffe1b34-04c6-4912-85e3-f4b8ba8fd9ec.mov
=> fix(statusChatInput): update mentions behavior when text is pasted

ui/app/mainui/SplashScreen.qml
Removes Lottie related code as it's not used for now
splash screen
=> fix(splashScreen): removed lottie related code

build-linux.sh, ci/Dockerfile, ci/Jenkinsfile.linux
Once merged, the docker image should be updated
=> fix: add qtlottie to linux build

ui/app/AppLayouts/Profile/stores/ProfileSectionStore.qml, ui/app/AppLayouts/Profile/stores/WalletStore.qml, ui/app/AppLayouts/Profile/views/wallet/MainView.qml
Settings are displayed base on wallet ff and not multi network
fixes #4997
=> feat(@settings): adjust feature flags for app settings

src/app/modules/main/profile_section/contacts/module.nim
Closes: #5018
Add check to populating contacts model function 
Contacts
=> fix(Contacts): Exclude myself from contacts

src/app/modules/main/chat_section/chat_content/messages/controller.nim, src/app/modules/main/chat_section/controller.nim, src/app/modules/main/chat_section/controller_interface.nim, src/app/modules/main/chat_section/module.nim, src/app/modules/main/chat_section/private_interfaces/module_view_delegate_interface.nim, src/app/modules/main/chat_section/view.nim, src/app_service/service/chat/service.nim, src/backend/chat.nim, src/backend/group_chat.nim, ui/app/AppLayouts/Chat/ChatLayout.qml, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Chat/views/ChatColumnView.qml, ui/app/AppLayouts/Chat/views/ChatContentView.qml, ui/app/AppLayouts/Chat/views/ChatContextMenuView.qml, ui/app/AppLayouts/Chat/views/ContactsColumnView.qml, ui/app/AppLayouts/Chat/views/CreateChatView.qml, ui/app/AppLayouts/Profile/stores/ContactsStore.qml, ui/imports/shared/status/StatusChatInput.qml, ui/imports/shared/views/chat/MessageContextMenuView.qml
Closes #4781
Updated create new chat flow based as per new designs in Figma.
chat section
https://user-images.githubusercontent.com/31625338/154775475-a8407728-7a69-4a31-966d-7f4426fbeb3e.mov
https://user-images.githubusercontent.com/31625338/154775480-2c58cf27-0b55-4055-9639-79306760cc34.mov
=> feat(desktop/chat): Updated create new chat/group flow

fleets.json, src/app/core/fleets/fleet_configuration.nim, src/app/modules/main/node_section/controller.nim, src/app/modules/main/profile_section/advanced/controller.nim, src/app_service/service/node/service.nim, src/app_service/service/node_configuration/service.nim, src/app_service/service/settings/dto/settings.nim, src/app_service/service/settings/service.nim, ui/app/AppLayouts/Chat/views/ChatContextMenuView.qml, ui/app/AppLayouts/Profile/popups/FleetsModal.qml, ui/app/AppLayouts/Profile/stores/AdvancedStore.qml, ui/imports/utils/Constants.qml
Requires
- https://github.com/status-im/status-go/pull/2583
=> chore: add status.prod fleet

src/app/modules/main/chat_section/base_item.nim, src/app/modules/main/chat_section/chat_content/module.nim, src/app/modules/main/chat_section/chat_content/view.nim, src/app/modules/main/chat_section/controller.nim, src/app/modules/main/chat_section/controller_interface.nim, src/app/modules/main/chat_section/model.nim, src/app/modules/main/chat_section/module.nim, src/app/modules/main/chat_section/private_interfaces/module_view_delegate_interface.nim, src/app/modules/main/chat_section/view.nim, src/app_service/service/community/service.nim, src/backend/communities.nim, ui/app/AppLayouts/Chat/popups/community/CreateChannelPopup.qml, ui/app/AppLayouts/Chat/popups/community/CreateCommunityPopup.qml, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Chat/views/ChatContentView.qml, ui/app/AppLayouts/Chat/views/ChatContextMenuView.qml, ui/app/AppLayouts/Chat/views/CommunityColumnView.qml, ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
=> feat(community): enable choosing and changing community channel color

src/app_service/service/token/async_tasks.nim, ui/app/AppLayouts/Profile/popups/AddShowTokenModal.qml
=> fix(@wallet): pre-populate token details

src/app/boot/app_controller.nim, src/app/global/user_profile.nim, src/app/global/utils.nim, src/app/modules/main/profile_section/profile/controller.nim, src/app/modules/main/profile_section/profile/controller_interface.nim, src/app/modules/main/profile_section/profile/io_interface.nim, src/app/modules/main/profile_section/profile/module.nim, src/app/modules/main/profile_section/profile/view.nim, src/app/modules/startup/onboarding/controller.nim, src/app/modules/startup/onboarding/controller_interface.nim, src/app/modules/startup/onboarding/module.nim, src/app/modules/startup/onboarding/private_interfaces/module_view_delegate_interface.nim, src/app/modules/startup/onboarding/view.nim, src/app_service/service/accounts/service.nim, src/app_service/service/accounts/service_interface.nim, src/app_service/service/profile/service.nim, src/app_service/service/profile/service_interface.nim, src/app_service/service/settings/dto/settings.nim, src/app_service/service/settings/service.nim, src/app_service/service/settings/service_interface.nim, src/backend/accounts.nim, ui/app/AppLayouts/Onboarding/popups/GenKeyModal.qml, ui/app/AppLayouts/Onboarding/stores/OnboardingStore.qml, ui/app/AppLayouts/Onboarding/views/GenKeyView.qml, ui/app/AppLayouts/Profile/stores/ProfileStore.qml, ui/app/AppLayouts/Profile/views/DisplayNamePopup.qml, ui/app/AppLayouts/Profile/views/MyProfileView.qml
Requires:
- https://github.com/status-im/nim-status-go/pull/7
- https://github.com/status-im/status-go/pull/2541
Fixes #4783
Adds the minimum required functionality for setting the display name. It looks ugly because it's just to show the functionality. 
That should be solved in #4921
=> feat: display name

src/app_service/service/community/service.nim
=> fix(community): join community when request is accepted

src/app_service/service/chat/service.nim, src/app_service/service/message/service.nim
=> fix(chat): only add active chats (fixes chats reappearing after leaving)

src/app/modules/main/browser_section/provider/view.nim, ui/app/AppLayouts/Browser/BrowserLayout.qml, ui/app/AppLayouts/Browser/stores/WalletStore.qml
fixes #4786
fixes #5014
also fixed simpledapp.eth due to need to resolve previous issue
=> fix(@browser): Fix etherscan link

ui/app/AppLayouts/Profile/panels/ContactPanel.qml, ui/app/AppLayouts/Profile/panels/ContactsListPanel.qml, ui/app/AppLayouts/Profile/stores/ContactsStore.qml, ui/app/AppLayouts/Profile/views/ContactsView.qml, ui/app/mainui/AppMain.qml, ui/imports/shared/popups/ProfilePopup.qml, ui/imports/shared/views/chat/qmldir, ui/imports/utils/Global.qml
Fixes #5004
Branched on top of https://github.com/status-im/status-desktop/pull/5003
StatusQ PR: https://github.com/status-im/StatusQ/pull/580
=> feat(profile): re-design Contacts setting view

src/app/modules/main/browser_section/current_account/controller.nim, src/app/modules/main/browser_section/current_account/controller_interface.nim, src/app/modules/main/browser_section/current_account/io_interface.nim, src/app/modules/main/browser_section/current_account/module.nim, src/app/modules/main/browser_section/current_account/view.nim, src/app/modules/main/browser_section/module.nim, ui/app/AppLayouts/Browser/popups/BrowserConnectionModal.qml, ui/app/AppLayouts/Browser/popups/BrowserWalletMenu.qml, ui/app/AppLayouts/Browser/stores/WalletStore.qml
=> fix(@browser): unlink wallet account and browser account

src/backend/visual_identity.nim
Adapt to status-go changes, (emoji/color)Hash is now called directly, not through RPC server.
=> chore: make (emoji/color)Hash direct status_go call

ui/app/AppLayouts/Browser/popups/AddFavoriteModal.qml, ui/app/AppLayouts/Chat/popups/community/TransferOwnershipPopup.qml
Adapted to https://github.com/status-im/StatusQ/pull/584
Affected areas:
- add favorite modal (browser section)
- transfer ownership popup (community section)
=> chore: adapt to StatusBaseInput changes

src/app_service/service/wallet_account/service.nim, src/backend/wallet.nim
also make only one call rather than one call per couple token/currency
status-go PR: https://github.com/status-im/status-go/pull/2595
fixes #5046
=> feat(@wallet): move fetch prices

ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Chat/views/ChatContentView.qml, ui/app/AppLayouts/Chat/views/ChatMessagesView.qml, ui/imports/shared/views/chat/ChannelIdentifierView.qml, ui/imports/shared/views/chat/MessageView.qml
=> feat(community): add emoji for channel header and identifier as well

scripts/windows_build_setup.ps1
closes https://github.com/status-im/status-desktop/issues/4998
=> chore: add qtlottie to aqtinstall parameters

ui/app/AppLayouts/Wallet/WalletLayout.qml, ui/app/AppLayouts/Wallet/panels/WalletFooter.qml, ui/app/AppLayouts/Wallet/panels/WalletHeader.qml, ui/app/AppLayouts/Wallet/views/RightTabView.qml, ui/app/mainui/AppMain.qml
fixes #5075
Moves the Action button to the bottom 
Wallet
=> feat(@desktop/wallet): Move action buttons to bottom as per new design

ui/app/AppLayouts/Onboarding/popups/GenKeyModal.qml
Closes: #5066
Add limitation to username input
GenKeyModal.qml
=> fix(GenKeyModal): Add maximum length to input

src/app_service/common/network_constants.nim, src/app_service/service/accounts/service.nim, src/app_service/service/mailservers/service.nim, src/app_service/service/node_configuration/dto/node_config.nim, src/backend/mailservers.nim
Requires:
- https://github.com/status-im/status-go/pull/2512/
Pending:
Fixes #705 
Fixes #4908
=> refactor: remove history request

src/app/modules/main/chat_section/chat_content/messages/controller.nim
=> fix(group-chat): fix function call to join public chat

ui/app/AppLayouts/Profile/panels/MenuPanel.qml, ui/app/AppLayouts/Profile/views/ContactsView.qml, ui/imports/shared/controls/StatusTabButton.qml
=> feat(contacts-settings): add badge for requests in contacts settings

ui/app/AppLayouts/Chat/views/CreateChatView.qml
Closes https://github.com/status-im/StatusQ/issues/531
Updates create chat view after updates in the StatusTagSelector component
Depends on https://github.com/status-im/StatusQ/pull/598
create chat view
=> fix(StatusTagSelector): move suggestions popup inside component

src/app_service/service/wallet_account/service.nim, src/backend/cache.nim
=> fix(@wallet): cache price to avoid multiple call

ui/app/AppLayouts/Onboarding/popups/GenKeyModal.qml
Closes: #5134
Trim username 
GenKeyModal
=> fix(GenKeyModal): Add trim to username

src/app/modules/main/app_search/module.nim
=> fix(@desktop/search): search popup UI breaks when clearing the input field

ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
=> fix(@desktop/general): search input in chat view should change cursor to input cursor when hovered

ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
Close: #5151
Close public chat popup when chat selected
PublicChatPopup
=> fix(PublicChatPopup): Add `close()` on join

ui/main.qml
Closes: #5170
Remove old `login` reference from `close` event
Root window
=> fix(main): Close app on onboarding step

ui/app/AppLayouts/Chat/views/CreateChatView.qml
the background color of the create new chat view was wrong
create new chat
=> fix(chat): corrected create new chat background color

ui/app/AppLayouts/Browser/controls/BookmarkButton.qml, ui/app/AppLayouts/Browser/panels/BrowserTabView.qml, ui/app/AppLayouts/Browser/panels/FavoritesBar.qml, ui/app/AppLayouts/Chat/panels/communities/CommunityProfilePopupOverviewPanel.qml, ui/app/AppLayouts/Chat/popups/community/CommunityDetailPopup.qml, ui/app/AppLayouts/Chat/popups/community/CreateCommunityPopup.qml, ui/app/AppLayouts/Profile/popups/RenameAccontModal.qml, ui/app/AppLayouts/Wallet/popups/AddAccountWithPrivateKeyModal.qml, ui/app/AppLayouts/Wallet/popups/AddAccountWithSeedModal.qml, ui/app/AppLayouts/Wallet/popups/AddEditSavedAddressPopup.qml, ui/app/AppLayouts/Wallet/popups/AddWatchOnlyAccountModal.qml, ui/app/AppLayouts/Wallet/popups/GenerateAccountModal.qml, ui/imports/shared/popups/NicknamePopup.qml, ui/imports/utils/Constants.qml, ui/imports/utils/Utils.qml
Fix malformed user input for:
- Migrate to StatusQ
- Partial redesign of browser settings (layout can be reused in the final implementation)
- Avoiding length limitation by enter key is not reproducible anymore
- Add contact option is not available anymore
Browser, contacts
Nickname editor popup simplified with the new StatusQ.StatusInput
Browser with limited and sanitized input
Tab with sanitized HTM content
Homepage StatusQ
Homepage with new designs layout and validation
Wallet Account Names
Saved Address
=> fix(general): Ignore invalid HTML user input

ui/app/AppLayouts/Chat/views/ChatContentView.qml
=> fix: loading indicator

src/app/modules/startup/onboarding/controller.nim, src/app/modules/startup/onboarding/io_interface.nim, src/app/modules/startup/onboarding/module.nim, src/app/modules/startup/onboarding/view.nim, src/app_service/service/accounts/dto/accounts.nim, src/app_service/service/accounts/service.nim, ui/app/AppLayouts/Onboarding/views/ConfirmPasswordView.qml, ui/app/AppLayouts/Onboarding/views/ExistingKeyView.qml, ui/imports/utils/Constants.qml
Fixes #5029
The behaviour will be improved with this next issue that will introduce a new status-go endpoint
=> fix(onboarding): show warning when trying to re-encrypt existing account

src/app/modules/main/browser_section/dapps/module.nim, src/app_service/service/wallet_account/service.nim
=> fix(@browser): deleted account with permission

src/app_service/common/network_constants.nim, src/app_service/service/node_configuration/dto/node_config.nim, src/app_service/service/node_configuration/service.nim, src/app_service/service/settings/service.nim, src/backend/node_config.nim
Requires
- https://github.com/status-im/nim-status-go/pull/9
- https://github.com/status-im/status-go/pull/2593
=> feat: switch fleet

src/app/core/signals/remote_signals/wallet.nim, src/app/modules/main/wallet_section/transactions/controller.nim, src/app/modules/main/wallet_section/transactions/io_interface.nim, src/app/modules/main/wallet_section/transactions/module.nim, src/app/modules/main/wallet_section/transactions/view.nim, src/app_service/service/transaction/service.nim, src/backend/eth.nim, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/stores/RootStore.qml, ui/imports/shared/controls/GasSelector.qml, ui/imports/shared/popups/SendModal.qml, ui/imports/shared/popups/SignTransactionModal.qml, ui/imports/shared/status/StatusETHTransactionModal.qml, ui/imports/shared/status/StatusSNTTransactionModal.qml
Move suggested fee to status-go and re-enable simple mode
=> feat(@wallet): move suggested fees to status-go

ui/app/AppLayouts/Onboarding/OnboardingLayout.qml, ui/app/AppLayouts/Onboarding/popups/MnemonicRecoverySuccessModal.qml, ui/app/AppLayouts/Onboarding/stores/OnboardingStore.qml, ui/app/AppLayouts/Onboarding/views/ConfirmPasswordView.qml, ui/app/AppLayouts/Onboarding/views/InsertDetailsView.qml, ui/app/AppLayouts/Onboarding/views/KeysMainView.qml, ui/app/AppLayouts/Onboarding/views/LoginView.qml
Fixes #5253
The problem was that we were using the generated account when importing instead of using the imported account.
=> fix(onboarding): fix importing seed phrase importing different accounts

src/app/modules/main/chat_section/chat_content/users/controller.nim, src/app/modules/main/chat_section/chat_content/users/module.nim, src/app_service/service/chat/dto/chat.nim, src/app_service/service/chat/service.nim, src/backend/chat.nim
Fixes #5122
This is a both a fix to the 1-1 mention but and an implementation of the new `getMembers` API. It makes it simpler to populate the users at the start of the app.
=> refactor(user-list): implement getMembers to populate user list

src/app_service/common/network_constants.nim, src/app_service/service/accounts/service.nim, src/app_service/service/node_configuration/dto/node_config.nim, src/app_service/service/node_configuration/service.nim
This adds missing configuration for enabling DiscV5 on WakuV2.
Requires
- https://github.com/status-im/status-go/pull/2616
=> feat: discV5

src/app/boot/app_controller.nim, src/app/modules/main/browser_section/module.nim, src/app/modules/main/browser_section/provider/controller.nim, src/app/modules/main/browser_section/provider/io_interface.nim, src/app/modules/main/browser_section/provider/module.nim, src/app/modules/main/browser_section/provider/view.nim, src/app_service/service/about/async_tasks.nim, src/app_service/service/provider/async_tasks.nim, src/app_service/service/provider/service.nim, ui/app/AppLayouts/Browser/popups/BrowserConnectionModal.qml, ui/app/AppLayouts/Browser/views/WebProviderObj.qml
=> fix(@browser): move post message async

src/app/modules/main/profile_section/privacy/controller.nim, src/app/modules/main/profile_section/privacy/io_interface.nim, src/app/modules/main/profile_section/privacy/module.nim, src/app/modules/main/profile_section/privacy/view.nim, src/app_service/service/privacy/service.nim, ui/app/AppLayouts/Profile/popups/ChangePasswordModal.qml
Closes: #5190
Add error message to change password popup
ChangePasswordModal
=> fix(change_pasword): Add error message to change password popup

ui/app/AppLayouts/Onboarding/stores/OnboardingStore.qml
=> fix(onboarding): fix seed phrase validation missing return

ui/imports/shared/views/chat/TransactionBubbleView.qml
=> fix(@wallet): Show error message when token is not found

src/app/modules/main/wallet_section/transactions/view.nim, src/app_service/service/transaction/service.nim
=> fix(@wallet): estimate gas fail when not enough fund

ui/app/AppLayouts/Profile/views/MyProfileView.qml
=> fix(@desktop/settings): copy correct chat key in profile view

ui/app/AppLayouts/Onboarding/views/SeedPhraseInputView.qml
=> fix(@onboarding): Allow to enter last word in seed phrase import

ui/imports/shared/views/PasswordView.qml
=> fix(PasswordView): Fix typo

ui/imports/shared/panels/chat/ChatReplyPanel.qml, ui/imports/shared/views/chat/CompactMessageView.qml
Fix #5266
Chat / replied message
=> fix(desktop/chat): Display sticker correctly in replied message.

ui/app/AppLayouts/stores/AppSearchStore.qml
=> fix(@desktop/chat): search triggered from within community doesn't seem to preset the right search location

ui/imports/shared/controls/ContactsListAndSearch.qml, ui/imports/shared/views/ExistingContacts.qml, ui/imports/shared/views/NoFriendsRectangle.qml, ui/imports/shared/views/SearchResults.qml
Closes #5362
Fixes popup height issues for inviting friends to community
Communities -> invite friends (add members) popup
=> fix(InviteFriendsToCommunityPopup): fixed popup height issues

ui/app/AppLayouts/Onboarding/views/SeedPhraseInputView.qml
Closes: #5415
Add persistence to seed phrase screens
Seed phrases view 
https://user-images.githubusercontent.com/82511785/162250416-157ba30b-501d-4242-b8f1-f3baa08611a3.mov
=> fix(seedphrase): Add persistence to seed phrase screens

ui/app/AppLayouts/Onboarding/views/InsertDetailsView.qml
Closes: #5352
Fix error message alignment
Onboarding
=> fix(@desktop/onboarding): Fix error message alignment

ui/imports/shared/status/StatusChatInput.qml
Closes #5107
Fixed the chat layout looks incorrect if message is more than 2000 characters
Chat text input
https://user-images.githubusercontent.com/31625338/162282850-55121c14-2fb5-4532-83d1-2e0df20e9896.mov
=> fix(StatusChatInput): missbehavior when text exceeds 2000 chars

ui/app/AppLayouts/Onboarding/popups/UploadProfilePicModal.qml, ui/app/AppLayouts/Onboarding/views/InsertDetailsView.qml
Closes #5237
Fixed title was empty on second opening
Upload profile picture popup title in onboarding
=> fix(SetProfilePicture): title was empty on second opening

src/app_service/service/eth/dto/method_dto.nim, src/app_service/service/transaction/service.nim
status go pr: 2628
fixes: #5365
=> fix(@wallet): link to tx hash

ui/app/AppLayouts/Wallet/views/AdvancedAddAccountView.qml
=> fix(@wallet): hide use 24 word button

src/app/modules/main/app_search/controller.nim, src/app/modules/main/app_search/module.nim
=> fix(@desktop/appsearch): render mentions in app search module

package-lock.json, package.json
Issue #5485
Upgrades fileicon to version 0.3.0
Build system
=> chore(@desktop/general): Upgrade fileicon to v. 0.3.0

src/app_service/service/chat/dto/chat.nim
Takes the fix for https://github.com/status-im/status-desktop/pull/5479 , kudos to @saledjenic
=> fix(@desktop/groups): group modal is missing context menu options

ui/app/AppLayouts/Wallet/popups/AddAccountModal.qml, ui/app/AppLayouts/Wallet/views/AdvancedAddAccountView.qml
fixes #5471
Adds watch only address functionality back
Wallet
https://user-images.githubusercontent.com/60327365/162692339-a3790fa7-2bb9-44ad-ab13-c723fb095deb.mov
=> feat(@desktop/wallet): re-add adding watch only address to wallet

ui/app/AppLayouts/Onboarding/shared/CreatePasswordModal.qml, ui/app/AppLayouts/Profile/popups/StoreToKeychainSelectionModal.qml, ui/app/AppLayouts/Profile/stores/PrivacyStore.qml, ui/app/mainui/AppMain.qml, ui/imports/utils/Global.qml
=> fix(@desktop/profile): settings to store pass in keychain remain the same

src/app/modules/main/profile_section/contacts/module.nim
Closes: #5460
Add condition to not include myself in sent requests model
Contacts
=> fix(ContactRequests): Remove add myself to sent request model

src/app/modules/main/activity_center/controller.nim, src/app/modules/main/activity_center/io_interface.nim, src/app/modules/main/activity_center/module.nim, src/app/modules/main/activity_center/view.nim, ui/app/AppLayouts/Chat/controls/activityCenter/ChannelBadge.qml, ui/app/AppLayouts/Chat/controls/activityCenter/CommunityBadge.qml, ui/app/AppLayouts/Chat/panels/ActivityChannelBadgePanel.qml, ui/app/AppLayouts/Chat/popups/ActivityCenterPopup.qml, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Chat/views/ActivityCenterMessageComponentView.qml, ui/imports/shared/views/chat/CompactMessageView.qml
=> fix(@desktop/activity-center): mentions and replies in the activity centre does not display community icon

ui/app/AppLayouts/Chat/popups/GroupInfoPopup.qml
=> fix(@desktop/groups): view group modal member list is missing identicon for self

src/app/boot/app_controller.nim, src/app/modules/main/wallet_section/all_tokens/controller.nim, src/app/modules/main/wallet_section/all_tokens/io_interface.nim, src/app/modules/main/wallet_section/all_tokens/module.nim, src/app/modules/main/wallet_section/all_tokens/view.nim, src/app_service/service/settings/dto/settings.nim, src/app_service/service/settings/service.nim, src/app_service/service/token/service.nim, src/app_service/service/wallet_account/service.nim, src/backend/backend.nim, ui/app/AppLayouts/Profile/panels/TokenSettingsModalContent.qml, ui/app/AppLayouts/Profile/popups/TokenSettingsModal.qml, ui/app/AppLayouts/Profile/stores/WalletStore.qml
fixes #5282 
status-go PR: https://github.com/status-im/status-go/pull/2624
=> feat(@wallet): move visible token to status go

src/app/modules/main/controller.nim
=> fix(main/controller): ensure mailserversService is initialized

ui/app/AppLayouts/Chat/popups/ActivityCenterPopup.qml
=> fix(act-center): fix changing section when clicking go to settings

src/app/modules/main/profile_section/contacts/module.nim, src/app/modules/main/profile_section/contacts/view.nim, src/app_service/service/contacts/dto/contacts.nim, src/app_service/service/contacts/service.nim, src/app_service/service/message/service.nim, src/backend/contacts.nim, ui/app/AppLayouts/Profile/stores/ContactsStore.qml, ui/app/AppLayouts/Profile/views/ContactsView.qml
Multiple contact related issues fixed.
`status-go` PR:
- https://github.com/status-im/status-go/pull/2635
Fixes #5354 #5225 #5198
=> fix(@desktop/contacts): multiple contact related issues fixed

ui/app/AppLayouts/Chat/popups/community/CommunitiesPopup.qml
Closes: #5380
Fix menu width
Import community menu
=> fix(ImportCommunity): Fix menu width

ui/app/AppLayouts/Profile/views/WalletView.qml
Closes: #5513
Fix scroll size
Wallet settings
=> fix(Settings): Fix wallet scroll sizes

ui/app/AppLayouts/Chat/views/ChatContentView.qml, ui/app/AppLayouts/Chat/views/ChatMessagesView.qml, ui/imports/shared/views/chat/CompactMessageView.qml, ui/imports/shared/views/chat/MessageView.qml
Closes: #5527
Set emoji popup to status input in edit message panel
Chat
=> fix(Chat): Add emoji popup to edit message input

ui/app/AppLayouts/Chat/popups/community/CommunityProfilePopup.qml
=> fix(CommunityPopup): Fix copy to clipboard

src/app/modules/main/wallet_section/all_tokens/controller.nim, src/app/modules/main/wallet_section/all_tokens/io_interface.nim, src/app/modules/main/wallet_section/all_tokens/module.nim, src/app/modules/main/wallet_section/all_tokens/view.nim, src/app_service/service/token/service.nim
=> feat(@wallet): prevent to duplicate token

ui/imports/shared/popups/ChatCommandsPopup.qml, ui/imports/shared/status/StatusChatInput.qml
=> feat(@chat): disable tx in chat when no wallet

src/app_service/service/ens/service.nim, ui/app/AppLayouts/Chat/stores/qmldir, ui/app/AppLayouts/Profile/ProfileLayout.qml, ui/app/AppLayouts/Profile/stores/EnsUsernamesStore.qml, ui/app/AppLayouts/Profile/stores/ProfileSectionStore.qml, ui/app/AppLayouts/Profile/views/EnsTermsAndConditionsView.qml, ui/app/AppLayouts/Profile/views/EnsView.qml, ui/imports/shared/status/StatusETHTransactionModal.qml
=> fix(@settings): fix Gas selector for snt

test/ui-test/testSuites/suite_statusLogin/shared/steps/steps.py, test/ui-test/testSuites/suite_statusLogin/tst_statusLoginPassword/test.feature
=> feat(uiTest): Data changes to fit new display name req.

ui/app/AppLayouts/Onboarding/views/WelcomeView.qml
=> fix(@onboarding): align button with design

ui/imports/shared/status/StatusEmojiPopup.qml, ui/imports/shared/status/StatusEmojiSection.qml
=> fix(StatusEmojiPopup): remove unnecessary spacing

ui/app/AppLayouts/Onboarding/views/SeedPhraseInputView.qml
=> fix(@onboarding): missing seed phrase headline

ui/app/AppLayouts/Chat/views/CreateChatView.qml
=> fix(@chat): press esc leave create chat view

ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
=> fix(@community): fix edit community save

ui/app/AppLayouts/Onboarding/popups/UploadProfilePicModal.qml, ui/app/AppLayouts/Onboarding/stores/OnboardingStore.qml, ui/app/AppLayouts/Onboarding/views/InsertDetailsView.qml
=> fix(@desktop/onboarding): it's impossible to delete a profile image on the onboarding page

ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
=> feat(ChatView): add tooltips to chat action buttons

ui/app/AppLayouts/Chat/controls/Contact.qml
Closes: #5528
Fix anchors for name text component
Invite friends popup
=> fix(InviteFriends): Fix width for names

ui/app/AppLayouts/Chat/popups/community/CreateCategoryPopup.qml, ui/app/AppLayouts/Chat/popups/community/CreateChannelPopup.qml
=> fix(@chat): channel/category name max length

ui/imports/shared/views/PasswordView.qml
As agreed with security team and from spec https://github.com/status-im/feature-specs/pull/38, password length has been updated from 6 to 10.
Onboarding / Create Password
Settings / Change Passord
=> feat(Password): Change minimum password length to 10

ui/app/AppLayouts/Chat/popups/community/CreateChannelPopup.qml, ui/app/AppLayouts/Wallet/popups/AddAccountModal.qml, ui/imports/shared/status/StatusEmojiPopup.qml
Fixes #5673
A couple of polishing to the create channel inputs for communities. It also affects the emoji picker in the wallet.
StatusQ PR: https://github.com/status-im/StatusQ/pull/660
=> Fix emoji icon picker and create channel inputs

ui/imports/shared/views/chat/LinksMessageView.qml
=> fix(@chat): unfurl twitter

ui/app/AppLayouts/Browser/BrowserLayout.qml, ui/app/mainui/AppMain.qml
Closes: #5475
Change old dialog to new
Browser
=> fix(Browser): Add new send modal

src/app/modules/main/wallet_section/all_tokens/controller.nim
=> fix(@wallet): apply order to token list

ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/imports/shared/popups/SendModal.qml
Closes: #5474
Convert empty input value to 0.0 ETH
Transactions
=> fix(SendModal): Send 0.0 amount if amount input is empty

src/app_service/service/community/service.nim
=> fix(@communities): Better error message when failing to import

ui/imports/shared/views/chat/CompactMessageView.qml
fixes #5546
Moved from onActiveChanged to onCompleted in order to be able to access the inner component
=> fix(@chat): move cursor to the end when edit message

ui/app/AppLayouts/Onboarding/OnboardingLayout.qml, ui/app/AppLayouts/Onboarding/panels/AccountMenuItemPanel.qml, ui/app/AppLayouts/Onboarding/views/LoginView.qml
=> fix(LoginView): add button to navigate to import existing key screen

.gitignore, src/app/modules/main/chat_section/chat_content/users/controller.nim
fixes: #5582
https://user-images.githubusercontent.com/33099791/167671503-aa711539-f1b9-44d1-9759-db2f8c20cf8d.mp4
=> fix(@desktop/chat): fix chat member getter for community

src/app/global/local_account_sensitive_settings.nim, ui/app/AppLayouts/Chat/panels/communities/CommunityChannelsAndCategoriesBannerPanel.qml, ui/app/AppLayouts/Chat/panels/communities/CommunityWelcomeBannerPanel.qml, ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
=> feat(CommunityColumn): add channels and categories admin banner

ui/app/AppLayouts/Wallet/panels/ImportSeedPhrasePanel.qml, ui/app/AppLayouts/Wallet/popups/AddAccountModal.qml, ui/app/AppLayouts/Wallet/views/AdvancedAddAccountView.qml
Fixes #5652
Same improvements done to the onboarding, but for the wallet.
When switching the form to 24 fields, since the fields are created asynchronously, we need the timer to wait for the fields to be created.
=> fix(wallet): improve wallet seed phrase import form

ui/app/AppLayouts/Chat/popups/community/CreateCommunityPopup.qml
Fixes #5647
Chat / Create new community
=> fix(@desktop/chat): Fix labels in a new community popup

ui/app/AppLayouts/Onboarding/OnboardingLayout.qml
=> fix(@onboarding): back button on seed phrase

ui/app/AppLayouts/Chat/views/ChatColumnView.qml, ui/imports/shared/controls/RecipientSelector.qml, ui/imports/shared/views/TransactionPreview.qml
=> fix(@desktop/chat): fix identicon in transaction preview

src/app/modules/main/chat_section/chat_content/controller.nim, src/app/modules/main/chat_section/chat_content/module.nim, src/app/modules/main/chat_section/chat_content/users/module.nim, src/app/modules/main/chat_section/controller.nim, src/app/modules/main/chat_section/io_interface.nim, src/app/modules/main/chat_section/module.nim, src/app/modules/main/chat_section/view.nim, src/app/modules/shared_models/user_model.nim, src/app_service/service/chat/service.nim, ui/app/AppLayouts/Chat/popups/GroupInfoPopup.qml, ui/app/AppLayouts/Chat/views/ChatContentView.qml, ui/app/AppLayouts/Chat/views/ChatContextMenuView.qml, ui/app/AppLayouts/Chat/views/ChatView.qml, ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
This was a special ops task Iuri gave to me to test and fix any issue I found in the group chat.
- I found is that if someone leaves the group, they weren't removed from the user list. Now they are.
- The add new member to group didn't work
- Fix context menu
- Fix pinned messages popup from the group info popup
=> Fix group chat issues

src/app/global/utils.nim, src/app_service/common/conversion.nim, src/app_service/service/contacts/service.nim, ui/imports/utils/Utils.qml
Fixes issues raised by @osmaczko in https://github.com/status-im/status-desktop/pull/5374
=> fix: chat key validation

resources/node-config.json, src/app_service/common/network_constants.nim, src/app_service/service/stickers/dto/stickers.nim, src/backend/stickers.nim
Fixes #5009 
Requires
- https://github.com/status-im/status-go/pull/2611
=> feat: use ipfs rate limiter

ui/app/AppLayouts/Chat/popups/ContactRequestsPopup.qml
fixes status-im/feature-specs#69
=> feat(@contacts): close modal on accept/decline all

ui/app/AppLayouts/Onboarding/views/InsertDetailsView.qml, ui/app/AppLayouts/Profile/views/MyProfileView.qml, ui/imports/shared/controls/EmojiHash.qml, ui/imports/shared/controls/chat/ProfileHeader.qml, ui/imports/shared/controls/chat/UserImage.qml, ui/imports/shared/popups/ProfilePopup.qml
=> fix(@desktop): add spacing to EmojiHash

ui/app/AppLayouts/Chat/popups/community/CreateChannelPopup.qml
As discussed during last UI meeting and because have been merged
=> fix(@chat): remove channel hash placeholder

ui/app/AppLayouts/Profile/views/DevicesView.qml
Fixes #4035
The sync was working, but the list of devices was not showing, because of bad anchoring and just bad layout.
I fixed it with a very hackish solution, but there is a new design, so I just went with a solution that works, to not duplicate any work. It was already painful to make it show as it is 😓
=> fix(Devices): fix devices list not showing

ui/app/AppLayouts/Chat/views/ChatColumnView.qml
=> fix(ChatColumnView): add missing emojiPopup passing to ChatContentView

ui/app/AppLayouts/Chat/popups/community/CreateChannelPopup.qml
Closes #5636
Depends on https://github.com/status-im/StatusQ/pull/671
Updates create new chat popup based on designs
Create new chat popup
https://user-images.githubusercontent.com/31625338/168133941-ef51de86-3b55-43ec-b862-4839afeae310.mov
=> fix(Community): Updated create new channel popup

ui/app/AppLayouts/Profile/views/ContactsView.qml
Closes #5732
Centered send contact request popup
Settings -> Messaging
https://user-images.githubusercontent.com/31625338/168575809-4694c839-636e-4625-9e84-6124b0da88d5.mov
=> fix(Settings): Centered send contact request popup

src/backend/chat.nim, ui/imports/shared/views/chat/CompactMessageView.qml
* fix overlap
* remove placeholder text
fixes #5768
=> fix(@chat): image don t overlap placeholder

ui/app/AppLayouts/Chat/popups/community/CreateCommunityPopup.qml
doing this to avoid some confusion
=> make approval required the default community type

ui/imports/utils/Utils.qml
=> fix(Chat/FetchMessage): Fetch date is empty in new chats with no messages

ui/app/AppLayouts/stores/MessageStore.qml, ui/imports/shared/panels/chat/ChatButtonsPanel.qml, ui/imports/shared/panels/chat/ChatReplyPanel.qml, ui/imports/shared/views/chat/CompactMessageView.qml, ui/imports/shared/views/chat/MessageContextMenuView.qml, ui/imports/shared/views/chat/MessageView.qml
=> fix(@chat): only show reaction to emoji right click

ui/app/AppLayouts/Onboarding/views/SeedPhraseInputView.qml
Closes #5669
Depends on: https://github.com/status-im/StatusQ/pull/663
Updates SeedInputPhrase layout due to new designs
Onboarding/SeedInputPhrase
https://user-images.githubusercontent.com/31625338/167887814-f41754a9-cbdb-45d6-930e-273b077ff356.mov
=> feat(StatusSeedPhraseView): Update layout

src/app/modules/main/chat_section/controller.nim, src/app/modules/main/chat_section/module.nim, src/app_service/service/chat/service.nim, src/app_service/service/community/service.nim
=> fix(@community): List channel/Add channel/Remove channel from category

ui/imports/shared/views/ExistingContacts.qml
fixes #5799
The attribute has been renamed!
=> fix(@community): invite contact renamed to mutual contact

src/app_service/service/message/service.nim
Main issue was in the `handleMessagesUpdate` proc. That proc receives array of chats and array of messages for all chats added to the array of chats, but the thing was that we were referring only to the chat on index `0` and sending all messages (even they are belonging to different chats) as messages of that chat on index `0`.
Fixes #5668
=> fix(@desktop/chat): [very hard to replicate] 1 to 1 chat window contains messages from other contacts

src/app/global/local_app_settings.nim, ui/main.qml
Close #3073
Desktop
https://user-images.githubusercontent.com/2522130/168570592-e8be70b0-c921-49e3-890b-a93977e2572d.mp4
=> fix(@desktop): Persist application window state & geometry

ui/imports/shared/views/PasswordView.qml
Closes #5734
Fixes password evaluation when text is changed
Create password view
https://user-images.githubusercontent.com/31625338/169550978-037907ef-da21-4127-a4f0-116d2e53fa7f.mov
=> fix(CreatePassword): evaluation added on text changed

ui/app/AppLayouts/Browser/BrowserLayout.qml, ui/app/mainui/AppMain.qml
Reverted changes done in `991e04ef955f853cb34efddc3d1ef2529f2d0375`
PR: https://github.com/status-im/status-desktop/pull/5502
Fixes #5721
=> feat(@desktop/browser): wrong screen is shown when claiming tokens in simpledapp.eth

src/app/boot/app_controller.nim, src/app/global/user_profile.nim, src/app/modules/main/profile_section/profile/controller.nim, src/app/modules/main/profile_section/profile/module.nim, src/app_service/service/contacts/service.nim, src/app_service/service/profile/service.nim, src/app_service/service/settings/dto/settings.nim, src/app_service/service/settings/service.nim
fixes #5765
For current user show name instead of alias or displayname
Profile popup
https://user-images.githubusercontent.com/60327365/168798579-57c605ee-8301-4291-a164-5b1f658c7bf7.mov
=> fix(@desktop/profile): changing username is not immediately updating

ui/app/AppLayouts/Profile/views/AppearanceView.qml
Close #5809
Replaced StatusSlider with StatusLabeledSlider
Profile
=> fix(@desktop/profile): Fix slider controls in appearance settings

ui/app/AppLayouts/Chat/popups/community/AccessExistingCommunityPopup.qml
=> fix(communities) validate privkey when importing a community

src/app_service/service/contacts/dto/status_update.nim, src/app_service/service/settings/service.nim, src/backend/status_update.nim
Fixes #5798
Status update selector
=> fix: broadcast update when changing status

ui/app/AppLayouts/Onboarding/OnboardingLayout.qml, ui/app/AppLayouts/Onboarding/views/KeysMainView.qml
Closes #5830
fixed back navigation for new users in onboarding screens
onboarding
https://user-images.githubusercontent.com/31625338/170056795-11f37209-e8a4-432c-941d-9e2ca9e2d92f.mov
=> fix(onboarding): fixed back navigation for new users

ui/app/AppLayouts/Profile/stores/LanguageStore.qml
Closes: #5843
Fix language model initialization time
Settings
=> fix(settings): Correct update for language model

ui/imports/shared/panels/chat/ChatTimePanel.qml, ui/imports/utils/Utils.qml
=> fix(@desktop/chat): timestamps are constant

ui/app/AppLayouts/Profile/views/AboutView.qml
Closes: #5844
Add new ui for `About` settings
Settings
=> feat(settings): Update ui for `About`

ui/app/AppLayouts/Chat/views/ChatContentView.qml
Closes:#5420
Show reply with sticker message
Chat
=> fix(ChatContentView): Fix link to reply

src/app/boot/app_controller.nim, src/app/core/notifications/notifications_manager.nim, src/app/global/local_account_sensitive_settings.nim, src/app/modules/main/profile_section/module.nim, src/app/modules/main/profile_section/notifications/controller.nim, src/app/modules/main/profile_section/notifications/item.nim, src/app/modules/main/profile_section/notifications/model.nim, src/app/modules/main/profile_section/notifications/module.nim, src/app_service/service/settings/dto/settings.nim, src/app_service/service/settings/service.nim, src/backend/settings.nim, ui/app/AppLayouts/Profile/views/NotificationsView.qml, ui/imports/utils/Constants.qml
- https://github.com/status-im/status-go/pull/2669
Fixes #5649
=> fix(@desktop/notifications): move notifications settings to `status-go`

ui/app/AppLayouts/Onboarding/OnboardingLayout.qml
Closes #5891
Fixes app crashes on going back to welcome
onboarding
=> fix(onboarding): app crashes on going back to welcome

src/app/modules/main/browser_section/current_account/view.nim, src/app/modules/main/wallet_section/accounts/module.nim, src/app/modules/main/wallet_section/current_account/view.nim, src/app_service/service/wallet_account/dto.nim, src/app_service/service/wallet_account/service.nim
fixes #5881
Aggregate balance for all token grouped by symbol:
status-go: https://github.com/status-im/status-go/pull/2689
https://github.com/status-im/feature-specs/pull/74/files
=> feat(@wallet): aggregate token balance

ui/imports/shared/views/PasswordView.qml
Closes: #5834
Add passwords validation to new password input
Onboarding
=> fix(onboarding): Add checking passwords to new password input

ui/app/AppLayouts/Chat/panels/communities/CommunityWelcomeBannerPanel.qml, ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
Closes: #5842
Add context menu to Communities View 
CommunitiesColumnView
=> feat(Communities): Add context menu to communities view

src/app/modules/main/browser_section/current_account/module.nim, src/app/modules/main/browser_section/current_account/view.nim, src/app/modules/main/wallet_section/accounts/module.nim, src/app/modules/main/wallet_section/current_account/module.nim, src/app/modules/main/wallet_section/current_account/view.nim, src/app_service/service/accounts/service.nim, src/app_service/service/wallet_account/async_tasks.nim, src/app_service/service/wallet_account/dto.nim, src/app_service/service/wallet_account/service.nim
=> fix(@desktop/wallet): show all tokens in wallet that have balance > 0

ui/app/AppLayouts/Profile/views/BrowserView.qml
=> fix(@desktop/browser): need empty screen for “DApp Permissions” screen

ui/app/AppLayouts/Profile/panels/MenuPanel.qml, ui/app/AppLayouts/Profile/popups/BackupSeedModal.qml, ui/app/AppLayouts/Profile/popups/backupseed/Acknowledgements.qml, ui/app/AppLayouts/Profile/popups/backupseed/Backup.qml, ui/app/AppLayouts/Profile/popups/backupseed/BackupSeedStepBase.qml, ui/app/AppLayouts/Profile/popups/backupseed/ConfirmSeedPhrasePanel.qml, ui/app/AppLayouts/Profile/popups/backupseed/ConfirmStoringSeedPhrasePanel.qml, ui/app/AppLayouts/Profile/popups/backupseed/TabBarButton.qml, ui/app/AppLayouts/Profile/stores/ProfileSectionStore.qml, ui/app/AppLayouts/Profile/views/LeftTabView.qml, ui/app/AppLayouts/Profile/views/PrivacyView.qml, ui/app/mainui/AppMain.qml, ui/imports/utils/Constants.qml
Closes #4918
Adds new Backup Seed Phrase section & modal
profile settings
https://user-images.githubusercontent.com/31625338/171409300-c2b8ea63-27a0-48b0-998f-45fcfbd06a08.mov
=> feat(settings): Adding new Backup Seed Phrase section & modal

ui/app/AppLayouts/Onboarding/views/InsertDetailsView.qml, ui/app/AppLayouts/Onboarding/views/KeysMainView.qml, ui/app/AppLayouts/Onboarding/views/WelcomeView.qml
Closes #5832
Fixed onboarding layout context positioning issues
Onboarding screens
=> fix(onboarding): fixing onboarding layout ctx positioning issues

src/app_service/service/token/async_tasks.nim, src/app_service/service/token/service.nim
Consider all possible networks based on the test network flag
=> feat(@wallet): resolve token multi network

ui/app/AppLayouts/Profile/views/LeftTabView.qml
Closes #5276
Fixes menu scrolls horizontally
Profile/LeftTabView
https://user-images.githubusercontent.com/31625338/171187749-bc1d912d-183b-417d-a647-26a1398313cc.mov
=> fix(Profile/LeftTabView): menu should not scroll horizontally

src/app/modules/main/app_search/controller.nim, src/app/modules/main/app_search/location_menu_sub_item.nim, src/app/modules/main/app_search/location_menu_sub_model.nim, src/app/modules/main/app_search/module.nim, src/app/modules/main/app_search/result_item.nim, src/app/modules/main/app_search/result_model.nim, src/app/modules/main/chat_section/base_item.nim, src/app/modules/main/chat_section/item.nim, src/app/modules/shared_models/color_hash_model.nim, src/app/modules/startup/login/item.nim, ui/app/mainui/AppSearch.qml
closes: #5459
needs: ~~https://github.com/status-im/StatusQ/pull/701~~
https://user-images.githubusercontent.com/33099791/171131163-fd4120e9-d227-4075-83a2-0d55bf95e68e.mp4
=> fix(@desktop/app-search): add color hash to chat icons

ui/app/mainui/AppMain.qml
Closes: #5899
Fix multiple creations of mailservers-not-working popup
mailservers-not-working popup
=> fix(appmain): Fix multiple creations of mailservers-not-working popup

ui/app/AppLayouts/Chat/popups/community/CreateCommunityPopup.qml, ui/imports/shared/popups/CommunityIntroDialog.qml
It removes ugly workarounds, functionally nothing changes.
Requires: https://github.com/status-im/StatusQ/pull/723
=> chore(community/popups): remove padding workarounds

ui/app/AppLayouts/Chat/panels/communities/CommunityPermissionsSettingsPanel.qml
https://github.com/status-im/status-desktop/pull/6067#pullrequestreview-1002894619
=> chore: apply PR suggestions to CommunityPermissionsSettingsPanel

ui/app/AppLayouts/Chat/panels/ContactListPanel.qml, ui/app/AppLayouts/Chat/panels/GroupChatPanel.qml, ui/app/AppLayouts/Chat/popups/GroupInfoPopup.qml, ui/app/AppLayouts/Chat/views/CreateChatView.qml
Fixed a few issues I've found caused by https://github.com/status-im/status-desktop/pull/6007
requires: https://github.com/status-im/StatusQ/pull/726
=> fix(@desktop): post user model refactor issues

ui/imports/shared/views/chat/InvitationBubbleView.qml
Fixes #5987
Bubble redesign by using `ColumnLayout`.
Chat / Community --> Community invitation Bubble
=> fix(Community/InvitationBubble): Community invitation doesn't look good

src/app/global/local_account_sensitive_settings.nim, src/app/modules/main/module.nim, src/app/modules/main/profile_section/notifications/controller.nim, src/app/modules/main/profile_section/notifications/io_interface.nim, src/app/modules/main/profile_section/notifications/module.nim, ui/app/AppLayouts/Chat/views/ChatContentView.qml, ui/app/AppLayouts/Chat/views/ContactsColumnView.qml, ui/app/AppLayouts/Profile/views/AdvancedView.qml, ui/imports/shared/views/chat/InvitationBubbleView.qml
Closes: #5922 
Enabled activity center and communities by default
Communities and Activity Center
=> chore(experemental-features): Enabled activity center and communities by default

src/app/modules/main/chat_section/chat_content/messages/controller.nim, src/app/modules/main/chat_section/chat_content/messages/io_interface.nim, src/app/modules/main/chat_section/chat_content/messages/module.nim, src/app/modules/main/chat_section/chat_content/messages/view.nim, src/app/modules/main/chat_section/controller.nim, src/app_service/service/chat/service.nim, src/backend/chat.nim, src/backend/group_chat.nim, ui/app/AppLayouts/Chat/stores/MessageStore.qml, ui/imports/shared/views/chat/ChannelIdentifierView.qml, ui/imports/shared/views/chat/MessageView.qml
closes: #5717
~~needs: https://github.com/status-im/status-go/pull/2684~~
https://user-images.githubusercontent.com/33099791/169406249-cf219705-6c24-4a87-87f8-4e95c06425da.mp4
=> feat(@desktop/group-chat): remove explicit join for groups

ui/app/AppLayouts/Chat/panels/UserListPanel.qml
=> fix(@desktop/chat): show compressed pubkey in members list

ui/app/AppLayouts/Chat/popups/community/CommunitiesPopup.qml, ui/app/AppLayouts/Profile/popups/SendContactRequestModal.qml
Closes #6002
Fixed some modals are misaligned in master
Contact request, create community and communities modals
=> fix(Popups): Some modals are misaligned in master

src/app/modules/main/chat_section/module.nim
Closes: #6003
Checks if user is group chat admin
Chat section
=> fix(chat): Fix checking admin privilages

src/app/modules/main/chat_section/controller.nim, src/app/modules/main/chat_section/io_interface.nim, src/app/modules/main/chat_section/module.nim, src/app/modules/main/chat_section/view.nim, src/app/modules/main/profile_section/contacts/controller.nim, src/app/modules/main/profile_section/contacts/io_interface.nim, src/app/modules/main/profile_section/contacts/module.nim, src/app/modules/main/profile_section/contacts/view.nim, src/app_service/service/activity_center/dto/notification.nim, src/app_service/service/contacts/service.nim, src/backend/contacts.nim, ui/app/AppLayouts/Chat/popups/ContactRequestsPopup.qml, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Profile/popups/SendContactRequestModal.qml, ui/app/AppLayouts/Profile/stores/ContactsStore.qml, ui/app/AppLayouts/Profile/views/ContactsView.qml, ui/imports/shared/popups/ProfilePopup.qml
Close #5846
Change send, accept and dismiss contact request implementations
Profile, Chat
https://user-images.githubusercontent.com/2522130/172174346-13131b7c-6451-40b2-bfb3-d820eced537d.mov
=> fix(@desktop/profile): Contact requests should support a message

src/app/global/local_account_sensitive_settings.nim, ui/app/AppLayouts/Profile/ProfileLayout.qml, ui/app/AppLayouts/Profile/stores/ProfileStore.qml, ui/imports/shared/panels/ModuleWarning.qml
Closes: #5743
Add back up seed phrase banner in profile settings
Settings
=> feat(settings): Add back up seed phrase banner in profile settings

ui/app/AppLayouts/Chat/panels/GroupChatPanel.qml, ui/app/AppLayouts/Chat/views/CreateChatView.qml
Closes #5955
GroupChatPanel - drop down was showing empty entries 
GroupChatPanel
https://user-images.githubusercontent.com/31625338/172180050-27450fc9-1a63-42f7-aac0-9089387a54a9.mov
=> fix(GroupChatPanel): drop down was showing empty entries

ui/app/mainui/SplashScreen.qml
Close #6172
Stop playing invisible animation
Desktop
=> feat(@desktop): Stop playing invisible animation

ui/app/AppLayouts/Profile/panels/MenuPanel.qml, ui/app/AppLayouts/Profile/stores/ProfileSectionStore.qml, ui/app/AppLayouts/Profile/views/LeftTabView.qml
Closes: #6100
Fix visibility community settings view
Settings
=> fix(settings): Fix visibility community settings view

src/app_service/service/wallet_account/service.nim
Changing timer interval to smaller value in order to close it correctly on shutdown.
Issue #5938
It turned out the the problem was a timer with a very long interval (15 minutes).
Timers are build on top of Nim's threadpool. The timer's tasks are executed in threads.
Timer's tasks uses sleep() function. This means that for a certain period of time, thread in the threadpool
is blocked and can't be joined on shutdown.
There is no way to kill the thread. Killing the thread is dangerous. Also, there is no good tool to do this.
I found only destroyThread() function in threads.nim but it is within "when false" statement and can't be used.
It is also impossible to talk to the thread via channel.
I came up to short-interval solution. I changed the interval of the timer to 1 sec , and if the time …
=> fix(@desktop/general): Fix application not responding on close

ui/app/AppLayouts/Onboarding/views/InsertDetailsView.qml, ui/app/AppLayouts/Onboarding/views/KeysMainView.qml, ui/app/AppLayouts/Onboarding/views/WelcomeView.qml
Closes #6066
Onboarding layouts were not properly aligned 
Onboarding layouts
https://user-images.githubusercontent.com/31625338/174578292-cffd9709-d156-48a6-868a-100a60f115ac.mov
=> fix(Onboarding): Centered onboarding layouts

ui/app/AppLayouts/Profile/panels/MenuPanel.qml, ui/imports/shared/views/chat/InvitationBubbleView.qml
=> fix(@communities): remove totally the toggle for experimental feature

src/app/modules/main/stickers/models/sticker_list.nim, src/app/modules/main/stickers/models/sticker_pack_list.nim, ui/imports/shared/status/StatusStickerMarket.qml
=> fix(@desktop/chat): filter paid stickers if the wallet is not enabled

src/app/modules/main/chat_section/chat_content/controller.nim, src/app/modules/main/chat_section/chat_content/users/controller.nim, src/app/modules/main/chat_section/controller.nim, src/app/modules/main/chat_section/module.nim, src/app/modules/main/profile_section/notifications/controller.nim, src/app_service/service/activity_center/service.nim, src/app_service/service/chat/service.nim, ui/app/AppLayouts/Chat/views/ChatColumnView.qml, ui/app/AppLayouts/Chat/views/ChatView.qml, ui/app/AppLayouts/Chat/views/CommunityColumnView.qml, ui/app/AppLayouts/Chat/views/ContactsColumnView.qml, ui/app/AppLayouts/Chat/views/CreateChatView.qml, ui/app/AppLayouts/Chat/views/qmldir, ui/app/mainui/AppMain.qml, ui/imports/utils/Global.qml
=> Replace plus button in community by adhoc btn and add buton at the bottom

src/app/modules/main/profile_section/contacts/view.nim, ui/app/AppLayouts/Chat/popups/PinnedMessagesPopup.qml, ui/app/AppLayouts/Chat/views/ChatContentView.qml, ui/app/AppLayouts/Chat/views/ChatView.qml, ui/app/AppLayouts/Profile/stores/ContactsStore.qml, ui/app/AppLayouts/Profile/views/ContactsView.qml, ui/app/mainui/AppMain.qml, ui/imports/shared/controls/chat/menuItems/SendContactRequestMenuItem.qml, ui/imports/shared/controls/chat/menuItems/qmldir, ui/imports/shared/popups/ProfilePopup.qml, ui/imports/shared/popups/SendContactRequestModal.qml, ui/imports/shared/views/chat/MessageContextMenuView.qml, ui/imports/utils/Global.qml
Close #6113
Add and modify profile context menu states
Desktop, Chat
https://user-images.githubusercontent.com/2522130/175028601-90460d4d-3bb9-4261-8c3b-e28ec6f3beec.mov
=> feat(@desktop/chat): New profile context menu states

src/app/modules/main/wallet_section/transactions/controller.nim, src/app/modules/main/wallet_section/transactions/io_interface.nim, src/app/modules/main/wallet_section/transactions/module.nim, src/app/modules/main/wallet_section/transactions/view.nim, src/app_service/service/transaction/service.nim, src/backend/eth.nim, ui/app/AppLayouts/stores/RootStore.qml, ui/imports/shared/controls/GasSelector.qml, ui/imports/shared/popups/SendModal.qml, ui/imports/shared/views/SendModalFooter.qml, ui/imports/utils/Constants.qml, ui/imports/utils/Utils.qml
Fixes #5398
In general applied logic rely on previous block and where would this transaction fall if it was included in the previous block.
https://user-images.githubusercontent.com/86303051/171695501-face2bf6-7fd0-4cf2-b6dc-31e0be8e0b44.mov
=> fix(@desktop/wallet): estimated time for transaction is always Unknown

ui/imports/shared/views/chat/CompactMessageView.qml
Fixes #6169
Let me know if you want more or less margin below or above
=> fix(CompactMessage): fix message height and spacing

ui/app/mainui/AppMain.qml
Closes #6222
Fixed Window resizing is not adjusting layout
App layout
https://user-images.githubusercontent.com/31625338/175339231-01efe7b7-aee9-4a2b-a75b-412c170f208e.mov
=> fix(AppLayout): Window resizing is not adjusting layout

ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
=> fix(CommunitySettingsView): add missing membership request modal

ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
fixed missing pendingRequestsToJoin
chat
=> fix(chat): fixed missing pendingRequestsToJoin

ui/app/AppLayouts/Profile/ProfileLayout.qml, ui/app/AppLayouts/Profile/panels/ContactsListPanel.qml, ui/app/AppLayouts/Profile/views/ContactsView.qml, ui/app/AppLayouts/Profile/views/SettingsContentBase.qml
Closes #5876
Closes #5926 
Fixes ContactsView in profile settings was not behaving correctly when it comes to layout and scrolling
ContactsView
https://user-images.githubusercontent.com/31625338/172392221-d0ed16c7-8245-4254-b3e8-5dd9c7c0695f.mov
=> fix(Profile): ContactsView layout and scrolling issues

src/app/modules/main/chat_section/module.nim
Closes: #6127
Add call `switchToOrCreateOneToOneChat` to contact added signal
chat_section
=> fix(chat): Open chat when contact request was accepted

ui/imports/shared/LoadingAnimation.qml, ui/imports/shared/controls/AmountInputWithCursor.qml, ui/imports/shared/panels/RoundedIcon.qml, ui/imports/shared/status/StatusStickerButton.qml, ui/imports/shared/views/chat/CompactMessageView.qml
statusq: https://github.com/status-im/StatusQ/pull/744
=> Only run animations when they are visible to avoid cpu issues

src/app_service/service/message/service.nim
Requires
- https://github.com/status-im/status-go/pull/2726
To test:
- Write a chat key like @zQ3shXmjxcjkkQc8HdAjfWfk9RgLxvt63DJtfiRkPTcRTQE4V in the chat input and it should be replaced by the username
=> feat: support compressed pubkey mentions

src/app/modules/main/chat_section/controller.nim, src/app/modules/main/chat_section/io_interface.nim, src/app/modules/main/chat_section/module.nim
=> fix(contacts): only open 1x1 chat when mutual contact when sending request

ui/app/mainui/AppMain.qml, ui/imports/shared/controls/AmountInputWithCursor.qml, ui/imports/shared/popups/SendModal.qml, ui/imports/shared/views/SendModalHeader.qml
fixes #6228
Uses the new floating buttons selector in the SendModal
Wallet
=> feat(@desktop/wallet): Using Floating Buttons in the Send Modal

ui/imports/shared/controls/AssetDelegate.qml
=> fix(@wallet): Always display snt/eth/dai

src/app/modules/main/chat_section/chat_content/chat_details.nim, src/app/modules/main/chat_section/chat_content/controller.nim, src/app/modules/main/chat_section/chat_content/io_interface.nim, src/app/modules/main/chat_section/chat_content/module.nim, src/app/modules/main/chat_section/chat_content/view.nim, src/app_service/service/contacts/dto/contacts.nim, src/app_service/service/contacts/service.nim
=> fix(1-1): fix contact label not updating when mutual contact changes

src/app/modules/main/networks/controller.nim, src/app/modules/main/networks/item.nim, src/app/modules/main/networks/model.nim, src/app/modules/main/networks/module.nim, src/app/modules/main/networks/view.nim, src/app_service/service/wallet_account/service.nim
Calculate balance per network
fixes #6285
=> feat: Add network balance

ui/imports/shared/status/StatusEmojiPopup.qml, ui/imports/shared/status/StatusGifColumn.qml, ui/imports/shared/status/StatusGifPopup.qml, ui/nim-status-client.pro
Close #6165 
Automatically pre-focus the search field in the gif and emoji popups upon opening them
Chat
[Záznam obrazovky z 5.7.2022 09:37:17.webm](https://user-images.githubusercontent.com/5377645/177275436-7b9bae5b-2243-4603-83b1-b260d5d76bf9.webm)
=> fix(gif/emoji popup): pre-focus the search field

ui/app/AppLayouts/Chat/views/ChatColumnView.qml
Closes: #6199
Add check if chats count is 0
Chat
=> fix(chat): Fix chat screen for empty state visibility

src/app_service/service/node_configuration/service.nim
=> fix(@node): set bloom filter to normal

src/backend/accounts.nim
=> chores(@general): bump status-go

ui/app/AppLayouts/Wallet/panels/ImportSeedPhrasePanel.qml, ui/app/AppLayouts/Wallet/popups/AddAccountModal.qml, ui/app/AppLayouts/Wallet/views/AdvancedAddAccountView.qml
Closes #6315
Fixes add account popup layout issues
AddAccountPopup
https://user-images.githubusercontent.com/31625338/177815709-d41ebf77-aaf9-4039-87a3-5bffac645e27.mov
=> fix(AddAccountPopup): layout issues

src/app_service/service/chat/service.nim, ui/imports/shared/views/chat/CompactMessageView.qml
Close #4905
Change rules how we get response on sent messages
Chat
https://user-images.githubusercontent.com/2522130/177334693-ebf4bde8-a010-4107-b934-6e8ab802e2e3.mov
=> feat(chat): Message display several images

ui/app/mainui/AppMain.qml, ui/imports/shared/controls/chat/ProfileHeader.qml, ui/imports/shared/popups/ProfilePopup.qml, ui/imports/shared/views/ProfileView.qml
Fixes various smaller UI issues in the profile popup
Fixes #6396
Fixes #6397
Fixes #6398
Profile {Popup,Header,View}
=> fix(ProfilePopup): various smaller UI issues

src/app/modules/main/controller.nim, src/app/modules/main/module.nim
Fixes #6415
Fixes crash when opening change user status dialog
=> fix(@desktop): Fix crash when opening change status dialog

Makefile, src/nim_status_client.nim
=> fix: logs on node tab

ui/app/AppLayouts/Chat/views/CreateChatView.qml
Closes #6354
CreateChatView: fixed no contacts text alignment
CreateChatView
=> fix(CreateChatView): fixed no contacts text alignment

src/app_service/service/eth/dto/method_dto.nim, src/app_service/service/transaction/dto.nim, src/app_service/service/transaction/service.nim, src/backend/transactions.nim
Adapt service to use new endpoint
status-go PR: https://github.com/status-im/status-go/pull/2751
fixes #6420
=> feat(@wallet): multi transaction

src/app/modules/main/profile_section/contacts/view.nim, src/app_service/service/contacts/service.nim, ui/app/AppLayouts/Profile/views/ContactsView.qml
Fix crash when rejecting contact request.
Seems to happen when sending request from mobile app ver. 1.19 to desktop application.
Also fixing accepting/dismissing requests in Settings/Contacts #6431 
Reason: status-go had a problem with finding latest request id, rpc call raised exception which was not caught.
What was done:
1. Setting default request id in status-go: https://github.com/status-im/status-go/pull/2753
2. Add try/catch in Nim code
3. Add missing functions and renaming in order to make accept/dismiss works
Requires status-go: https://github.com/status-im/status-go/pull/2753
=> 6395 fix acceptreject request

ui/app/AppLayouts/Chat/popups/RenameGroupPopup.qml, ui/app/mainui/AppMain.qml, ui/app/mainui/popups/MailserverConnectionDialog.qml, ui/imports/shared/popups/CommunityIntroDialog.qml
iterates: status-im/StatusQ#760
Adapted:
- rename-group dialog
- community-intro dialog
- mailserver-connection-issue dialog
=> StatusModal -> StatusDialog (first iteration)

ui/app/AppLayouts/Wallet/views/LeftTabView.qml
Align the Wallet left section navigation bar to the design
Fixes #6479
Fixes #6480 
Fixes #6489
- simplify using layouts
- fix margins/spacing
- fix font sizes and weights
Fixes smaller UI issues in the Wallet section navigation menu/bar
Wallet/LeftTabView
=> fix(Wallet/LeftTabView): style fixes

ui/main.qml
- fixes broken minimize/fullscreen shortcuts
- fixes settings being saved into different directories
main.qml
N/A
=> fix(@main): unbreak settings saving and window shortcuts

src/app/modules/main/profile_section/language/controller.nim, src/app/modules/main/profile_section/language/io_interface.nim, src/app/modules/main/profile_section/language/item.nim, src/app/modules/main/profile_section/language/locale_table.nim, src/app/modules/main/profile_section/language/model.nim, src/app/modules/main/profile_section/language/module.nim, src/app/modules/main/profile_section/language/view.nim, src/app/modules/main/profile_section/module.nim, src/app_service/service/language/service.nim
iterates: https://github.com/status-im/status-desktop/issues/6416
- [feat(settings): introduce language model](https://github.com/status-im/status-desktop/commit/446ba7b45790b73f850a4b73ff4fc54b56cfb3ab)
- [chore(settings): add and populate SIGNAL_LOCALE_UPDATE](https://github.com/status-im/status-desktop/commit/aa4931c207d85182ad273d15ff0e19cf044e0c01)
The missing part is to adapt qml code, it will be done in separate PR (unfortunately, [it is not as straightforward as I assumed](https://github.com/status-im/status-desktop/issues/6500)).
**There is nothing to test from the UI perspective, new language model is not used yet.**
=> introduce language model

ui/app/AppLayouts/Chat/views/ChatContentView.qml
- call arguments didn't match with prototype
fixes: #6407
=> fix(@desktop/chat): remove invalid argument from `showReplyArea`

src/app/modules/main/controller.nim, src/app/modules/main/io_interface.nim, src/app/modules/main/module.nim, src/app_service/service/contacts/service.nim, ui/imports/shared/popups/ProfilePopup.qml, ui/imports/shared/views/ProfileView.qml, ui/imports/shared/views/chat/MessageContextMenuView.qml, ui/imports/utils/Constants.qml
Fixes #6251
Adds the "Respond to Contact Request" and "Contact Request Pending" options to the MessageContextMenu
Also fixes some small issues with contact verification where the state of the incoming request was not correct
This branch is on top of https://github.com/status-im/status-desktop/pull/6377
=> feat(contacts): add respond to request and pending contact menu options

src/app/modules/main/profile_section/contacts/view.nim, ui/app/AppLayouts/Profile/views/ContactsView.qml
Closes: #6261
Add `acceptContactRequest` to profile_section/view and fix `reject` to `dismiss` in qml
Pending contact requests
=> fix(ContactRequests): Fix accept and reject pending requests functions

src/app_service/service/community/async_tasks.nim, src/app_service/service/community/service.nim, src/backend/communities.nim, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/imports/shared/views/chat/InvitationBubbleView.qml
fixes #6133
When restarting the app, the community is not in the list
and data needs to be requested
=> fix(@community): Fix community join bubble

src/app/modules/main/profile_section/contacts/view.nim
remove duplicate nim slot; looks like a rebase gone wrong
Fixes being unable to build/start the app
Closes #6599
Fixes app startup
ALL
N/A
=> hotfix(nim): Can't start the app

ui/app/AppLayouts/Profile/panels/ContactPanel.qml
Closes: #5514
Add icon settings to contacts view
Contacts view
=> fix(contacts): Showing letters for contacts without profile picture

ui/app/mainui/AppSearch.qml
Corresponding `StatusQ` changes:
- https://github.com/status-im/StatusQ/pull/799
Fixes: #6551
=> fix(@desktop/appsearch): searching doesn't work when "In: Anywhere" set by X button

ui/app/AppLayouts/Onboarding/views/InsertDetailsView.qml
=> fix(@desktop/onboarding): set proper user color icon

src/app/boot/app_controller.nim, src/app/global/local_app_settings.nim, src/app/modules/main/profile_section/language/controller.nim, src/app/modules/main/profile_section/language/io_interface.nim, src/app/modules/main/profile_section/language/item.nim, src/app/modules/main/profile_section/language/locale_table.nim, src/app/modules/main/profile_section/language/module.nim, src/app/modules/main/profile_section/language/view.nim, src/app_service/service/language/service.nim, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/CommunitiesPortal/stores/CommunitiesStore.qml, ui/app/AppLayouts/Profile/stores/LanguageStore.qml, ui/app/AppLayouts/Profile/views/LanguageView.qml, ui/app/AppLayouts/Wallet/views/LeftTabView.qml, ui/app/AppLayouts/stores/RootStore.qml
Use nim provided language model in qml.
closes: https://github.com/status-im/status-desktop/issues/6416
StatusQ: https://github.com/status-im/StatusQ/pull/797
changing language
=> use nim provided language model

ui/app/AppLayouts/Profile/panels/ContactPanel.qml, ui/app/AppLayouts/Profile/panels/ContactsListPanel.qml
Fixed runtime error with `icon` property
=> fix(ContactsPanel): Use `iconSource` property instead of `icon`

ui/app/AppLayouts/Onboarding/views/LoginView.qml, ui/imports/shared/controls/Input.qml
Closes #6519
Fixed password field design inconsistencies
LoginView
https://user-images.githubusercontent.com/31625338/181029375-1b42132c-6f09-48ae-a412-587b25e186a9.mov
=> fix(LoginView): Password field design inconsistencies

ui/app/AppLayouts/Onboarding/views/ConfirmPasswordView.qml, ui/app/AppLayouts/Onboarding/views/CreatePasswordView.qml
Closes: #6577
Add autofocus for password fields
Onboarding 
https://user-images.githubusercontent.com/6445843/181525443-731081a1-aa3c-4a34-bc2d-deafa2b1bbf5.mp4
=> fix(@desktop/onboarding): add password fields autofocus

src/app/modules/main/controller.nim, src/app/modules/main/io_interface.nim, src/app/modules/main/module.nim, src/app_service/service/contacts/service.nim, ui/app/AppLayouts/Profile/panels/ContactPanel.qml, ui/app/AppLayouts/Profile/panels/ContactsListPanel.qml, ui/app/AppLayouts/Profile/views/ContactsView.qml, ui/imports/shared/popups/ProfilePopup.qml, ui/imports/shared/views/ProfileView.qml, ui/imports/shared/views/chat/MessageContextMenuView.qml, ui/imports/utils/Constants.qml
Fixes #6252
This branch is on top of https://github.com/status-im/status-desktop/pull/6375 because it needs the mutual contact fixes
=> feat(MessageContextMenu): add option to verify identity in context menu

ui/app/AppLayouts/Onboarding/views/InsertDetailsView.qml
Closes #6022
fixed layout spacing and positioning in InsertDetailsView
InsertDetailsView
=> fix(InsertDetailsView): fixed layout spacing and positioning

src/app_service/service/wallet_account/dto.nim
=> fix(@wallet): total balance wallet

ui/imports/shared/controls/AssetDelegate.qml
=> fix(@wallet): do not display balance with scientific format

test/ui-test/src/drivers/SquishDriver.py, test/ui-test/src/screens/StatusChatScreen.py, test/ui-test/testSuites/suite_status/shared/scripts/names.py, test/ui-test/testSuites/suite_status/shared/steps/chatSteps.py, test/ui-test/testSuites/suite_status/tst_ChatFlow/test.feature, ui/imports/shared/panels/chat/ChatButtonsPanel.qml
Fixes #6670
Branched on top of https://github.com/status-im/status-desktop/pull/6701
=> test(chat): add test to reply a message

test/ui-test/src/screens/StatusWalletScreen.py, test/ui-test/testSuites/suite_status/shared/scripts/names.py, test/ui-test/testSuites/suite_status/shared/scripts/wallet/__init__.py, test/ui-test/testSuites/suite_status/shared/scripts/wallet/add_account.py, test/ui-test/testSuites/suite_status/shared/scripts/wallet/main.py, test/ui-test/testSuites/suite_status/shared/scripts/wallet/saved_addresses.py, test/ui-test/testSuites/suite_status/shared/scripts/wallet/send_popup.py, test/ui-test/testSuites/suite_status/shared/steps/walletSteps.py, test/ui-test/testSuites/suite_status/tst_wallet/test.feature, ui/app/AppLayouts/Wallet/views/SavedAddressesView.qml
split wallet section into multiple files
=> test: refactor names.py

Makefile, ci/Jenkinsfile.uitests, scripts/ubuntu_build_setup.sh, test/ui-test/testSuites/suite_status/suite.conf
Create a pipeline to run uitest.
Currently tests are failing but running.
Fixing the tests will be done in subsequent PRs
Results can be seen: https://ci.status.im/job/status-desktop/job/branches/job/uitests/job/PR-6602/96/
=> test: Add e2e to CI

src/app_service/service/message/service.nim
=> fix(message-service): ignore new messages in 1-1 when not a contact

src/app/modules/shared_models/message_model.nim, ui/app/AppLayouts/Chat/views/ChatMessagesView.qml, ui/imports/shared/views/chat/CompactMessageView.qml, ui/imports/shared/views/chat/MessageView.qml
Close #6543
Fixes in message model to get update on next and previous messages
Chat
=> fix(@dektop/chat): Fix messages timestamp update

src/app/modules/startup/controller.nim, src/app/modules/startup/module.nim, ui/main.qml
=> fix(@desktop/onboarding): startup stuck when entering wrong password

ui/app/AppLayouts/Chat/popups/ActivityCenterPopup.qml, ui/app/AppLayouts/Chat/popups/qmldir, ui/app/AppLayouts/Chat/views/ChatColumnView.qml, ui/app/AppLayouts/Chat/views/CreateChatView.qml, ui/app/mainui/AppMain.qml, ui/imports/utils/Global.qml
Reverts status-im/status-desktop#6654
=> Revert "fix(CreateChatView): Move `ActivityCenterPopup` to appmain"

src/app/modules/main/chat_section/chat_content/users/module.nim
fixes: #6455
- suffix removed
community members list
=> fix(community): Remove " You" suffix from the current user name

src/app/modules/main/profile_section/ens_usernames/controller.nim, src/app/modules/main/profile_section/ens_usernames/io_interface.nim, src/app/modules/main/profile_section/ens_usernames/module.nim, src/app/modules/main/profile_section/ens_usernames/view.nim, src/app_service/service/ens/service.nim, ui/app/AppLayouts/Profile/stores/EnsUsernamesStore.qml, ui/app/AppLayouts/Profile/views/EnsDetailsView.qml, ui/imports/shared/status/StatusETHTransactionModal.qml
Fixes #6192 
Requires:
- https://github.com/status-im/status-go/pull/2756
=> fix: ens details view

ui/app/AppLayouts/Profile/popups/ChangeProfilePicModal.qml, ui/app/AppLayouts/Profile/views/profile/MyProfileSettingsView.qml, ui/imports/shared/controls/ImageCropper.qml, ui/imports/shared/controls/chat/ProfileHeader.qml, ui/imports/shared/panels/CropCornerRectangle.qml, ui/imports/shared/popups/ImageCropperModal.qml
Reverts status-im/status-desktop#6862
=> Revert "fix(Profile): Added menu to remove profile image"

ci/Jenkinsfile.uitests, test/ui-test/src/screens/StatusCommunityScreen.py, test/ui-test/src/screens/StatusMainScreen.py, test/ui-test/testSuites/suite_status/shared/scripts/sections/global_names.py, test/ui-test/testSuites/suite_status/shared/steps/chatSteps.py, test/ui-test/testSuites/suite_status/tst_ChatFlow/test.feature, test/ui-test/testSuites/suite_status/tst_groupChat/test.feature, test/ui-test/testSuites/suite_status/tst_statusLoginPassword/test.feature, test/ui-test/testSuites/suite_status/tst_transaction/test.feature, test/ui-test/testSuites/suite_status/tst_wallet/test.feature, ui/imports/shared/panels/ModuleWarning.qml
Fixes #6853
Most of the comments are because the tests depend on the mailservers.
The wallet and transaction tests are just so Anthony does it :smile: 
Now, it **should** pass in the CI
=> test(all): fix all remaining tests and comments the broken ones

ui/app/AppLayouts/Onboarding/panels/AccountMenuItemPanel.qml, ui/app/AppLayouts/Onboarding/views/LoginView.qml, ui/imports/utils/Constants.qml
Fixes #6820
Welcome page adjustments
Desktop Welcome
https://user-images.githubusercontent.com/6445843/183679109-139e4673-854c-429c-a3f3-26e6814f9131.mp4
=> fix(@desktop/welcome) adjust welcome page

src/app_service/service/mailservers/service.nim
Useful for test
```
MAILSERVER=enode://7aa648d6e855950b2e3d3bf220c496e0cae4adfddef3e1e6062e6b177aec93bc6cdcf1282cb40d1656932ebfdd565729da440368d7c4da7dbd4d004b1ac02bf8@178.128.142.26:443 make run
```
=> feat(@node): Allow to set a static mailserver

ci/Jenkinsfile.uitests, test/ui-test/src/screens/StatusWalletScreen.py, test/ui-test/testSuites/suite_status/tst_wallet/test.feature
Make the screen of the test bigger to have similar behaviour with local
=> test(@wallet): fix test on CI

test/ui-test/src/screens/StatusCommunityScreen.py, test/ui-test/testSuites/suite_status/shared/scripts/sections/community_names.py, test/ui-test/testSuites/suite_status/shared/steps/communitySteps.py, test/ui-test/testSuites/suite_status/tst_communityFlows/test.feature, ui/app/AppLayouts/Chat/panels/communities/CommunityEditSettingsPanel.qml, ui/app/AppLayouts/Chat/panels/communities/CommunityOverviewSettingsPanel.qml, ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml, ui/app/AppLayouts/CommunitiesPortal/panels/CommunityColorPanel.qml, ui/imports/shared/popups/SettingsDirtyToastMessage.qml
Fixes #6756
StatusQ PR: https://github.com/status-im/StatusQ/pull/828
=> test(community): add a test that edits a community

src/nim_status_client.nim
Fixes https://github.com/status-im/status-desktop/issues/6930
=> fix(nim_status_client): Increased JS engine stack size

Makefile
closes: #6973
needs: https://github.com/status-im/dotherside/pull/68
Added QML_DEBUG and QML_DEBUG_PORT Makefile options.
Steps to enable qml debugging:
```
rm -rf vendor/DOtherSide/build
make run QML_DEBUG=true
```
Default port is: 49152
--- 
https://user-images.githubusercontent.com/33099791/184106117-0215e8ba-a736-4b11-86ae-610fe3a4d8be.mp4
=> feat(Makefile): add QML_DEBUG and QML_DEBUG_PORT options

test/ui-test/src/drivers/SquishDriverVerification.py, test/ui-test/src/screens/SettingsScreen.py, test/ui-test/testSuites/suite_status/shared/scripts/sections/settings_names.py, test/ui-test/testSuites/suite_status/shared/steps/settingsSteps.py, test/ui-test/testSuites/suite_status/suite.conf, test/ui-test/testSuites/suite_status/tst_settingsMenu/test.feature, test/ui-test/testSuites/suite_status/tst_settingsMenu/test.py, ui/app/AppLayouts/Profile/panels/MenuPanel.qml, ui/app/AppLayouts/Profile/views/LeftTabView.qml
=> test(@desktop/general): can quit app by going to settings -> quit

test/ui-test/src/drivers/SquishDriverVerification.py, test/ui-test/src/screens/SettingsScreen.py, test/ui-test/testSuites/suite_status/shared/scripts/sections/settings_names.py, test/ui-test/testSuites/suite_status/shared/steps/settingsSteps.py, test/ui-test/testSuites/suite_status/tst_wallet/test.feature, ui/app/AppLayouts/Profile/popups/RenameAccontModal.qml, ui/app/AppLayouts/Profile/views/wallet/AccountView.qml
fixes #6754
Add Squish test for edit account
Wallet
=> fix(@desktop/wallet): Add Squish test for edit account

test/ui-test/src/drivers/SquishDriverVerification.py, test/ui-test/src/screens/StatusWalletScreen.py, test/ui-test/testSuites/suite_status/shared/scripts/sections/wallet_names.py, test/ui-test/testSuites/suite_status/shared/steps/walletSteps.py, test/ui-test/testSuites/suite_status/tst_wallet/test.feature, ui/app/AppLayouts/Wallet/views/CollectiblesView.qml, ui/app/AppLayouts/Wallet/views/RightTabView.qml, ui/app/AppLayouts/Wallet/views/collectibles/CollectibleCollectionView.qml
fix(@desktop/wallet): Can see collectibles for an account
fixes #6896
Added squish test to ensure that a n account with valid collectibles are listed on the UI.
Wallet
=> fix(@desktop/wallet): Can see collectibles for an account

ui/app/AppLayouts/Chat/popups/ActivityCenterPopup.qml, ui/app/AppLayouts/Chat/popups/qmldir, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Chat/views/ChatColumnView.qml, ui/app/AppLayouts/Chat/views/ChatView.qml, ui/app/AppLayouts/Chat/views/CreateChatView.qml, ui/app/mainui/AppMain.qml, ui/imports/utils/Global.qml
Closes: #6345
Move ActivityCenterPopup to AppMain
ActivityCenter
=> fix(CreateChatView): Move `ActivityCenterPopup` to appmain

ui/app/AppLayouts/Chat/popups/community/MembershipRequestsPopup.qml
Closes: #6799
Fix listview size
MembershipRequestsPopup
=> fix(Communities): Fix membership requests popup

test/ui-test/src/drivers/SquishDriverVerification.py, test/ui-test/src/screens/StatusCommunityScreen.py, test/ui-test/testSuites/suite_status/shared/scripts/sections/community_names.py, test/ui-test/testSuites/suite_status/shared/steps/communitySteps.py, test/ui-test/testSuites/suite_status/tst_communityFlows/test.feature, ui/app/AppLayouts/Chat/views/ChatContextMenuView.qml
Require [StatusQ PR #849](https://github.com/status-im/StatusQ/pull/849)
=> test(community): delete community channel

test/ui-test/src/drivers/SquishDriver.py, test/ui-test/src/screens/SettingsScreen.py, test/ui-test/src/screens/StatusCommunityScreen.py, test/ui-test/src/screens/StatusMainScreen.py, test/ui-test/testSuites/suite_status/shared/scripts/sections/community_portal_names.py, test/ui-test/testSuites/suite_status/shared/scripts/sections/settings_names.py, test/ui-test/testSuites/suite_status/shared/steps/communitySteps.py, test/ui-test/testSuites/suite_status/shared/steps/settingsSteps.py, test/ui-test/testSuites/suite_status/tst_communityFlows/test.feature, ui/app/AppLayouts/Profile/panels/CommunitiesListPanel.qml, ui/app/mainui/AppMain.qml
Rebased on top of https://github.com/status-im/status-desktop/pull/6765, the top commit includes needed changes
=> test(Community Settings): leave community

test/ui-test/src/drivers/SquishDriver.py, test/ui-test/src/screens/StatusCommunityScreen.py, test/ui-test/testSuites/suite_status/shared/scripts/sections/chat_names.py, test/ui-test/testSuites/suite_status/shared/scripts/sections/community_names.py, test/ui-test/testSuites/suite_status/shared/scripts/sections/global_names.py, test/ui-test/testSuites/suite_status/shared/steps/communitySteps.py, test/ui-test/testSuites/suite_status/tst_communityFlows/test.feature, ui/app/AppLayouts/Chat/popups/community/CreateChannelPopup.qml, ui/imports/shared/status/StatusEmojiPopup.qml, ui/imports/shared/status/StatusEmojiSection.qml, ui/imports/shared/views/chat/ChannelIdentifierView.qml
I use code from @jrainville's PR that will be fixed on first conflict merge: https://github.com/status-im/status-desktop/pull/7008
=> test(Communities): can change the emoji of a community channel

src/app/modules/shared_modules/keycard_popup/controller.nim, src/app/modules/shared_modules/keycard_popup/internal/insert_keycard_state.nim, src/app/modules/shared_modules/keycard_popup/io_interface.nim, src/app/modules/shared_modules/keycard_popup/module.nim, src/app/modules/shared_modules/keycard_popup/view.nim, src/app/modules/startup/internal/keycard_insert_keycard_state.nim, src/app/modules/startup/internal/keycard_max_pairing_slots_reached_state.nim, src/app/modules/startup/internal/keycard_max_puk_retries_reached_state.nim, src/app/modules/startup/internal/keycard_not_empty_state.nim, src/app/modules/startup/internal/login_keycard_insert_keycard_state.nim, ui/app/AppLayouts/Onboarding/views/KeycardInitView.qml, ui/app/AppLayouts/Onboarding/views/LoginView.qml, ui/imports/shared/popups/keycard/states/KeycardInit.qml
The keycard library updated, information that the card might be wrongly inserted displayed in that case to inform a user.
Fixes: #6960
=> fix(@desktop/keycard): keycard is not recognized when inserted with wrong side

test/ui-test/src/screens/StatusCommunityScreen.py, test/ui-test/testSuites/suite_status/shared/scripts/sections/community_names.py, test/ui-test/testSuites/suite_status/shared/steps/communitySteps.py, test/ui-test/testSuites/suite_status/tst_communityFlows/test.feature, ui/app/AppLayouts/Chat/popups/community/CreateCategoryPopup.qml
Close #6752
Depends https://github.com/status-im/StatusQ/pull/854
Add squish test case for creating community category
=> test(community): add a test that creates a community category

ui/imports/shared/popups/CommunityIntroDialog.qml
Closes #6856
CommunityDialogIntro: Fixed intro txt layout issues
CommunityDialogIntro
=> fix(CommunityDialogIntro): Fixed intro txt layout issues

test/ui-test/src/drivers/SquishDriver.py, test/ui-test/src/screens/StatusChatScreen.py, test/ui-test/testSuites/suite_status/shared/scripts/sections/chat_names.py, test/ui-test/testSuites/suite_status/shared/steps/chatSteps.py, test/ui-test/testSuites/suite_status/tst_ChatFlow/test.feature, ui/imports/shared/status/StatusChatInput.qml, ui/imports/shared/status/StatusEmojiSection.qml
=> test(chat): add test that sends a message with an emoji

test/ui-test/src/drivers/SquishDriverVerification.py, test/ui-test/src/screens/StatusCommunityScreen.py, test/ui-test/testSuites/suite_status/shared/scripts/sections/community_names.py, test/ui-test/testSuites/suite_status/shared/steps/communitySteps.py, test/ui-test/testSuites/suite_status/tst_communityFlows/test.feature, ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
Close #6750
Add squish test case for deleting community category
=> test(community): add a test that deletes a community category

src/app/modules/main/profile_section/sync/view.nim, ui/app/AppLayouts/Profile/ProfileLayout.qml, ui/app/AppLayouts/Profile/popups/AddWakuNodeModal.qml, ui/app/AppLayouts/Profile/popups/WakuNodesModal.qml, ui/app/AppLayouts/Profile/views/MessagingView.qml
=> feat: add store nodes

test/ui-test/src/drivers/SquishDriver.py, test/ui-test/src/screens/StatusCommunityScreen.py, test/ui-test/testSuites/suite_status/shared/steps/communitySteps.py, test/ui-test/testSuites/suite_status/tst_communityFlows/test.feature, ui/app/AppLayouts/Chat/popups/community/CreateCategoryPopup.qml
Close #6888
Test editing community category. Tests edit and delete community category improved
=> test(community): add a test that edits a community category

src/app/modules/main/communities/module.nim, src/app/modules/main/module.nim, src/app/modules/shared_models/active_section.nim, src/app/modules/shared_models/member_item.nim, src/app/modules/shared_models/member_model.nim, src/app/modules/shared_models/section_item.nim, src/app_service/service/community/dto/community.nim, src/app_service/service/community/service.nim, src/backend/communities.nim, ui/app/AppLayouts/Chat/panels/communities/CommunityMembersSettingsPanel.qml, ui/app/AppLayouts/Chat/panels/communities/CommunityMembersTabPanel.qml, ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
This is a continuation of pr #6280
According to Figma design: https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=3113%3A356327
new tabs are added:
- Pending Requests
- Rejected
The scope is described in the issue.
Related prs:
- https://github.com/status-im/status-go/pull/2783
- https://github.com/status-im/StatusQ/pull/833
Community settings / members
https://user-images.githubusercontent.com/61889657/182907097-c51f666d-fb2d-43bf-801a-7de472373dab.mov
=> 6279 community requests management

ui/app/AppLayouts/Chat/views/CreateChatView.qml
Fixes #6942
Adjust Create chat page text size and anchors.
Desktop Chat
https://user-images.githubusercontent.com/6445843/185383594-24f69626-68eb-47ce-b9a0-67c76a67b5da.mp4
=> fix(@desktop/chat): adjust start chat page

ui/app/AppLayouts/Wallet/popups/ReceiveModal.qml
Fixes #6966
Adjust Receive modal address
Desktop Wallet
=> fix(@desktop/wallet): adjust receive modal adress

ui/app/AppLayouts/Chat/views/ContactsColumnView.qml, ui/app/AppLayouts/Profile/views/MessagingView.qml
Fix signal which doesn't work anymore
ContactRequests
=> fix(ContactRequests): Fix `sensor.onClicked` to `onClicked`

src/app/modules/main/browser_section/current_account/module.nim, src/app/modules/main/networks/model.nim, src/app/modules/main/wallet_section/accounts/module.nim, src/app/modules/main/wallet_section/current_account/module.nim, src/app/modules/shared_models/token_item.nim, src/app/modules/shared_models/token_model.nim, src/app_service/common/network_constants.nim, src/app_service/service/token/dto.nim, src/app_service/service/wallet_account/async_tasks.nim, src/app_service/service/wallet_account/dto.nim, src/backend/backend.nim, ui/app/AppLayouts/Wallet/controls/NetworkFilter.qml, ui/app/AppLayouts/Wallet/popups/ReceiveModal.qml, ui/app/AppLayouts/Wallet/views/RightTabView.qml, ui/app/AppLayouts/Wallet/views/collectibles/CollectibleCollectionView.qml, ui/imports/shared/controls/AssetsDetailsHeader.qml, ui/imports/shared/controls/InformationTag.qml, ui/imports/shared/controls/InformationTile.qml, ui/imports/shared/controls/qmldir, ui/imports/shared/stores/RootStore.qml, ui/imports/shared/views/AssetsDetailView.qml, ui/imports/shared/views/AssetsView.qml, ui/imports/shared/views/qmldir
fixes #6491
status-go PR: https://github.com/status-im/status-go/pull/2793
Implements the Token detail view defined here : https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=6455%3A122774
Wallet
https://user-images.githubusercontent.com/60327365/183645083-45a9e07d-413e-417b-b5dc-8e78d764999b.mov
=> feat(@desktop/wallet): Add Token Detail View

ui/app/AppLayouts/Chat/panels/ContactListPanel.qml, ui/app/AppLayouts/Chat/panels/UserListPanel.qml, ui/app/AppLayouts/Chat/panels/communities/CommunityMembersTabPanel.qml, ui/app/AppLayouts/Chat/popups/GroupInfoPopup.qml, ui/app/AppLayouts/Profile/popups/ExemptionNotificationsModal.qml, ui/app/AppLayouts/Profile/views/NotificationsView.qml, ui/imports/utils/Utils.qml
Fixes #6971
Add icon settings to ContactListPanel to cover no image case.
Desktop Chat
https://user-images.githubusercontent.com/6445843/185596070-d25c4daf-f6ab-4c8a-93db-b2fa817dc439.mp4
=> fix(@desktop/chat): adjust add members default picture

ui/app/AppLayouts/Profile/stores/EnsUsernamesStore.qml, ui/imports/shared/status/StatusETHTransactionModal.qml
requires https://github.com/status-im/status-go/pull/2792
Fixes the problem with gas estimation when releasing the ENS name
=> chore: update status-go and fix gas estimation when interacting with ens name

src/app/modules/main/app_search/module.nim, src/app_service/service/chat/service.nim, test/ui-test/src/drivers/SquishDriver.py, test/ui-test/src/screens/StatusMainScreen.py, test/ui-test/src/screens/StatusSearchScreen.py, test/ui-test/testSuites/suite_status/shared/scripts/names.py, test/ui-test/testSuites/suite_status/shared/scripts/sections/chat_names.py, test/ui-test/testSuites/suite_status/shared/scripts/sections/search_names.py, test/ui-test/testSuites/suite_status/shared/steps/chatSteps.py, test/ui-test/testSuites/suite_status/shared/steps/communitySteps.py, test/ui-test/testSuites/suite_status/shared/steps/searchSteps.py, test/ui-test/testSuites/suite_status/suite.conf, test/ui-test/testSuites/suite_status/tst_communityFlows/test.feature, test/ui-test/testSuites/suite_status/tst_groupChat/test.feature, test/ui-test/testSuites/suite_status/tst_searchFlows/test.feature, test/ui-test/testSuites/suite_status/tst_searchFlows/test.py
Fixes #7017
Fixes #6885
The serach was a bit broken where a new communities' channels didn't appear until a restart. Also, the check for channel name only did `startsWith` instead of `contains`, so searching `test` didn't give `automation-test` for example.
Then, I added tests for the search (second commit)
=> Fix search and add test for it

ui/app/AppLayouts/Chat/panels/communities/CommunityProfilePopupOverviewPanel.qml, ui/app/AppLayouts/Chat/popups/community/CommunitiesPopup.qml, ui/app/AppLayouts/Chat/popups/community/CreateCategoryPopup.qml, ui/app/AppLayouts/Chat/views/CommunityColumnView.qml, ui/app/AppLayouts/Profile/popups/ExemptionNotificationsModal.qml, ui/app/AppLayouts/Profile/popups/WakuNodesModal.qml, ui/app/AppLayouts/Profile/views/MessagingView.qml, ui/app/AppLayouts/Profile/views/NotificationsView.qml, ui/app/AppLayouts/Profile/views/profile/MyProfileSettingsView.qml, ui/imports/shared/controls/RadioButtonSelector.qml
Closes: #7135
Fix click on `StatusListItem`
App :)
=> fix(StatusListItem): fix `sensor.onClicked` to `onClicked`

src/app/modules/main/wallet_section/current_account/controller.nim, src/app/modules/main/wallet_section/current_account/io_interface.nim, src/app/modules/main/wallet_section/current_account/module.nim, src/app/modules/main/wallet_section/current_account/view.nim, src/app_service/service/token/service.nim, src/app_service/service/wallet_account/service.nim, ui/imports/shared/controls/AssetAndAmountInput.qml, ui/imports/shared/panels/StatusAssetSelector.qml, ui/imports/shared/popups/SendModal.qml
fixes #7014
Adds search bar to token selector
Fixes SendModal layout issues
Wallet
Uploading Screen Recording 2022-08-18 at 10.53.40 PM.mov…
=> fix(@desktop/wallet): Search Bar missing in token selection popup

ui/app/AppLayouts/Chat/views/ChatColumnView.qml, ui/app/AppLayouts/Chat/views/ChatContentView.qml
fixes: #7146
https://user-images.githubusercontent.com/33099791/186697208-b9ae258d-e85c-4b6a-b1df-4a01ce7350a9.mp4
=> fix(@chat/groups): resolve undefined chatContentModule

ui/app/AppLayouts/CommunitiesPortal/popups/CreateCommunityPopup.qml
=> feat(CreateCommunityPopup): introduce canGoNext and nextAction for modal pages

src/app/core/signals/remote_signals/community.nim, src/app/core/signals/remote_signals/signal_type.nim, src/app/core/signals/signals_manager.nim, src/app/modules/main/communities/controller.nim, src/app/modules/main/communities/io_interface.nim, src/app/modules/main/communities/models/discord_categories_model.nim, src/app/modules/main/communities/models/discord_category_item.nim, src/app/modules/main/communities/models/discord_channel_item.nim, src/app/modules/main/communities/models/discord_channels_model.nim, src/app/modules/main/communities/models/discord_file_item.nim, src/app/modules/main/communities/models/discord_file_list_model.nim, src/app/modules/main/communities/module.nim, src/app/modules/main/communities/view.nim, src/app_service/service/community/dto/community.nim, src/app_service/service/community/service.nim, src/backend/communities.nim, ui/app/AppLayouts/CommunitiesPortal/CommunitiesPortalLayout.qml, ui/app/AppLayouts/CommunitiesPortal/controls/IssuePill.qml, ui/app/AppLayouts/CommunitiesPortal/popups/CreateCommunityPopup.qml, ui/app/AppLayouts/CommunitiesPortal/stores/CommunitiesStore.qml, ui/imports/utils/Constants.qml
=> feat(CreateCommunityPopup): introduce file selector and category panels

test/ui-test/src/screens/SettingsScreen.py, test/ui-test/src/screens/StatusChatScreen.py, test/ui-test/testSuites/suite_status/shared/scripts/sections/chat_names.py, test/ui-test/testSuites/suite_status/shared/scripts/sections/settings_names.py, test/ui-test/testSuites/suite_status/shared/steps/chatSteps.py, test/ui-test/testSuites/suite_status/shared/steps/settingsSteps.py, test/ui-test/testSuites/suite_status/tst_ChatFlow/test.feature, ui/app/AppLayouts/Profile/views/MessagingView.qml, ui/app/AppLayouts/Profile/views/SettingsContentBase.qml, ui/imports/shared/status/StatusChatInput.qml, ui/imports/shared/status/StatusGifColumn.qml, ui/imports/shared/status/StatusGifPopup.qml
Closes: #6882
Test for sending a gif
=> test(chat): Can send a gif

test/ui-test/src/screens/StatusChatScreen.py, test/ui-test/testSuites/suite_status/shared/scripts/sections/chat_names.py, test/ui-test/testSuites/suite_status/shared/steps/chatSteps.py, test/ui-test/testSuites/suite_status/tst_ChatFlow/test.feature, ui/imports/shared/status/StatusInputListPopup.qml
Closes: #7020
Also, fixed #7019 
Fix emoji suggestions popup and add tests
Emoji popup
=> fix(EmojiPopup): Fix emoji suggestions and add tests for it

test/ui-test/src/drivers/SquishDriverVerification.py, test/ui-test/src/screens/SettingsScreen.py, test/ui-test/src/screens/StatusChatScreen.py, test/ui-test/testSuites/global_shared/scripts/global_names.py, test/ui-test/testSuites/suite_onboarding/suite.conf, test/ui-test/testSuites/suite_status/shared/scripts/sections/chat_names.py, test/ui-test/testSuites/suite_status/shared/steps/chatSteps.py, test/ui-test/testSuites/suite_status/tst_ChatFlow/test.feature, ui/imports/shared/popups/ModalPopup.qml, ui/imports/shared/status/StatusChatInput.qml, ui/imports/shared/status/StatusStickerMarket.qml, ui/imports/shared/status/StatusStickersPopup.qml
Fixes #6962
Branched on top of the IPFS gateway fix
=> test(chat): add a test that install a sticker pack and sends a sticker

src/app/modules/main/browser_section/current_account/module.nim, src/app/modules/main/wallet_section/accounts/module.nim, src/app/modules/main/wallet_section/current_account/module.nim, src/app/modules/shared_models/token_item.nim, src/app/modules/shared_models/token_model.nim, src/app_service/service/token/dto.nim, src/app_service/service/wallet_account/async_tasks.nim, src/app_service/service/wallet_account/dto.nim, ui/imports/shared/views/AssetsView.qml
fixes #6482
status-go: https://github.com/status-im/status-go/pull/2817
Implements the price change in the token view as expected in design.
https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=4222%3A178422
Wallet
=> feat(@desktop/wallet): Display price changes

test/ui-test/src/screens/StatusChatScreen.py
=> fix(tests): Fix typo

test/ui-test/src/screens/StatusCommunityScreen.py
Depends https://github.com/status-im/StatusQ/pull/870
Fix to make tests click on category title instead of random place of the category
=> test(community): Fix community categories tests

ui/imports/shared/status/StatusChatInput.qml, ui/imports/shared/status/StatusTextFormatMenu.qml
Fixes #6988
Requires https://github.com/status-im/StatusQ/pull/876
Add Quote text format menu action with required functionality
Desktop Chat
https://user-images.githubusercontent.com/6445843/187691122-1b6046b2-4993-4d3d-a277-fc12d7c1eda4.mp4
=> feat(@desktop/chat): add textformat quote option functionality

ui/app/AppLayouts/Wallet/popups/AddAccountModal.qml
Seems like a leftover from latest refactor
=> fix(@wallet): Add account not working

src/app_service/common/conversion.nim, ui/app/AppLayouts/stores/RootStore.qml, ui/imports/shared/popups/SendModal.qml, ui/imports/utils/Utils.qml
fixes #6695
Adds support to resolve ENS name and to send transaction to the corresponding address
Wallet
https://user-images.githubusercontent.com/60327365/187406460-5a1355d3-fbfa-4658-a456-3f774f99dc5f.mov
=> fix(@desktop/wallet): Entering ENS name in SendModal doesnt work

ui/app/AppLayouts/Wallet/popups/AddAccountModal.qml
=> fix(AddAccountModal): Updated password error message

src/app/modules/main/networks/model.nim, src/app/modules/main/wallet_section/all_tokens/controller.nim, src/app/modules/main/wallet_section/all_tokens/io_interface.nim, src/app/modules/main/wallet_section/all_tokens/module.nim, src/app/modules/main/wallet_section/all_tokens/view.nim, src/app/modules/main/wallet_section/saved_addresses/model.nim, src/app/modules/main/wallet_section/saved_addresses/view.nim, src/app/modules/main/wallet_section/transactions/controller.nim, src/app/modules/main/wallet_section/transactions/item.nim, src/app/modules/main/wallet_section/transactions/model.nim, src/app_service/service/transaction/dto.nim, ui/imports/shared/controls/InformationTag.qml, ui/imports/shared/controls/TransactionDelegate.qml, ui/imports/shared/stores/RootStore.qml, ui/imports/shared/views/HistoryView.qml, ui/imports/utils/Constants.qml, ui/imports/utils/Utils.qml
feat(@desktop/wallet): New design for Transaction History
fixes #7213
StatusQ PR: https://github.com/status-im/StatusQ/pull/879
Updates activity history to look like design (see https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=6105%3A75943 ) https://github.com/status-im/status-desktop/issues/7215
Wallet
https://user-images.githubusercontent.com/60327365/187955665-e8ceb93f-c469-4ada-a0e9-7e26e9dd8435.mov
=> feat(@desktop/wallet): New design for Transaction History

ui/imports/shared/status/StatusChatInput.qml
Fixes #7099
Add logic to handle input on left or right of mention.
Adjust function which recalculates mentions positions.
Add mention removal when Delete pressed on left from mention.
Desktop Chat
https://user-images.githubusercontent.com/6445843/188659992-d4da3877-0d98-4eac-a84a-9b2cb20c5593.mp4
=> fix(@desktop/chat): adjust mentions handing logic

ui/app/AppLayouts/Chat/panels/communities/CommunityMembersTabPanel.qml, ui/app/AppLayouts/Onboarding/panels/AccountMenuItemPanel.qml, ui/app/AppLayouts/Onboarding/views/LoginView.qml
Fixes #7284
Fix icons on lists: 
1. LoginView accounts 
2. Community members list.
🍺
=> fix(@desktop): Fix icons regressions

src/app/modules/main/browser_section/current_account/module.nim, src/app/modules/main/wallet_section/accounts/module.nim, src/app/modules/main/wallet_section/current_account/module.nim, src/app/modules/shared_models/token_item.nim, src/app/modules/shared_models/token_model.nim, src/app_service/service/wallet_account/async_tasks.nim, src/app_service/service/wallet_account/dto.nim, src/app_service/service/wallet_account/service.nim, ui/imports/shared/views/AssetsView.qml
=> fix(@wallet): display currency price rather than 24h change

test/ui-test/src/drivers/SDKeyboardCommands.py, test/ui-test/src/drivers/SquishDriver.py, test/ui-test/src/screens/StatusAccountsScreen.py, test/ui-test/src/screens/StatusChatScreen.py, test/ui-test/src/screens/StatusLoginScreen.py, test/ui-test/src/screens/StatusMainScreen.py, test/ui-test/src/utils/FileManager.py, test/ui-test/testSuites/global_shared/scripts/global_names.py, test/ui-test/testSuites/global_shared/scripts/login_names.py, test/ui-test/testSuites/suite_onboarding/shared/steps/signUpSteps.py, test/ui-test/testSuites/suite_status/shared/scripts/sections/chat_names.py, test/ui-test/testSuites/suite_status/shared/steps/chatSteps.py, test/ui-test/testSuites/suite_status/tst_groupChat/test.feature, ui/app/AppLayouts/Chat/popups/RenameGroupPopup.qml, ui/app/AppLayouts/Chat/views/ChatContextMenuView.qml, ui/app/AppLayouts/Chat/views/ContactsColumnView.qml, ui/app/AppLayouts/Onboarding/views/LoginView.qml, ui/imports/shared/panels/EditCroppedImagePanel.qml
=> test(group chat): Testing changing group chat's name, color and image.

src/app/modules/shared_models/balance_model.nim, src/app_service/service/wallet_account/async_tasks.nim, src/app_service/service/wallet_account/dto.nim, ui/imports/shared/controls/AssetsDetailsHeader.qml, ui/imports/shared/views/AssetsDetailView.qml, ui/imports/shared/views/AssetsView.qml
Fix asset formating and display of network only enabled
fixes #7129
=> fix(@wallet): asset formatting

ui/app/AppLayouts/Wallet/views/RightTabView.qml, ui/imports/shared/views/AssetsDetailView.qml
Closes #6490
adds a dummy price chart in assets detail view
Assets detail view
https://user-images.githubusercontent.com/31625338/190172322-891dc552-84a8-44fb-afda-076a00896ddb.mov
=> feat(AssetDetailView): Adding price history chart

src/app/modules/main/controller.nim, src/app_service/service/settings/service.nim
=> feat: set default sync period to 9d days for new accounts

ui/app/AppLayouts/Chat/panels/communities/BackUpCommuntyBannerPanel.qml, ui/app/AppLayouts/Chat/panels/communities/CommunityChannelsAndCategoriesBannerPanel.qml, ui/app/AppLayouts/Chat/panels/communities/CommunityWelcomeBannerPanel.qml, ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
- fix spacing/padding/margins
- remove MouseAreas, they block hovering the buttons (not needed any longer thanks to our new QQC2 buttons)
- some minor cleanups
Fixes #7366
Fixes some UI issues with community welcome banners
CommunityColumnView
=> fix: community banners UI fixes

ui/app/AppLayouts/Chat/popups/community/CommunitiesPopup.qml, ui/app/AppLayouts/Profile/panels/CommunitiesListPanel.qml, ui/app/AppLayouts/Profile/views/CommunitiesView.qml
- introduce proper plurals
- correct font sizes/weights for the list item
- fix header spacing
Closes #7362
Fixes various UI issues in the Communities settings section
Communities settings view
=> fix: Community settings panel fixes

ui/app/mainui/AppMain.qml, ui/imports/shared/status/StatusSearchListPopup.qml
Fixes: #7409
Fixes broken contact/chat images in StatusSearchListPopup
StatusSearchListPopup
Before:
After:
=> fix broken contact/chat images in StatusSearchListPopup

src/app_service/service/transaction/service.nim, ui/imports/shared/controls/AssetAndAmountInput.qml, ui/imports/shared/panels/StatusAssetSelector.qml, ui/imports/shared/popups/SendModal.qml, ui/imports/shared/views/SendModalFooter.qml, ui/imports/utils/Utils.qml
fix(@desktop/wallet): Send Modal doesn't fill available height and Drop Shadow missing in Send Modal Footer
Also fixed a crash found while fixing the above bugs
fixed #7133, #7134
Makes the SendModal adaptable to screen size and to use the max height available
Wallet
https://user-images.githubusercontent.com/60327365/187291052-3038fb39-6947-4ec4-82df-123cc72545c9.mov
=> fix(@desktop/wallet): Send Modal doesn't fill available height and Drop Shadow missing in Send Modal Footer

src/app/modules/main/profile_section/contacts/controller.nim, src/app/modules/main/profile_section/contacts/io_interface.nim, src/app/modules/main/profile_section/contacts/module.nim
=> fix: contact status not reflected in list

ui/app/AppLayouts/Chat/controls/community/EnsPanel.qml, ui/app/AppLayouts/Chat/controls/community/HoldingsDropdown.qml, ui/app/AppLayouts/Chat/controls/community/PermissionListItem.qml, ui/app/AppLayouts/Chat/controls/community/PermissionTypes.qml, ui/app/AppLayouts/Chat/controls/community/PermissionsDropdown.qml, ui/app/AppLayouts/Chat/views/communities/CommunityNewPermissionView.qml
"Is allowed to" section of the "New permission" view
depends on https://github.com/status-im/StatusQ/pull/897
Closes #6040
`CommunityNewPermissionView`
https://user-images.githubusercontent.com/20650004/189616019-584a3163-6ef9-47f0-a874-375d5ce9cc1f.mp4
=> feat(@desktop/communities) Permissions - 'is allowed to' dropdown

ui/app/AppLayouts/Wallet/views/RightTabView.qml, ui/imports/shared/views/AssetsDetailView.qml
Fixes `qrc:/imports/shared/views/AssetsDetailView.qml:85: TypeError: Cannot read property 'timeRangeTabBarIndex'` warning 
AssetsDetailView
=> fix(AssetsDetailView): fixed warning

src/app/modules/main/activity_center/io_interface.nim, src/app/modules/main/activity_center/module.nim, src/app/modules/main/activity_center/view.nim, src/app_service/service/activity_center/dto/notification.nim, src/app_service/service/activity_center/service.nim, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/mainui/activitycenter/panels/ActivityCenterPopupTopBarPanel.qml, ui/app/mainui/activitycenter/popups/ActivityCenterPopup.qml, ui/app/mainui/activitycenter/views/ActivityNotificationBase.qml, ui/app/mainui/activitycenter/views/ActivityNotificationContactRequest.qml, ui/app/mainui/activitycenter/views/ActivityNotificationMention.qml, ui/app/mainui/activitycenter/views/ActivityNotificationMessage.qml, ui/app/mainui/activitycenter/views/ActivityNotificationReply.qml, ui/imports/utils/Constants.qml, ui/imports/utils/Utils.qml
Close #7016
Getting any of AC notifications visible
=> fix(ActivityCenter): Fixing showing AC notifications

ui/imports/shared/views/chat/LinksMessageView.qml, ui/imports/shared/views/chat/MessageView.qml
The url is hidden when there is only one url in the message with no additional text and the image is shown (unfurled).
Closes: #7321
Depends on: https://github.com/status-im/StatusQ/pull/916
MessageView, LinksMessageView, StatusMessage
[Kazam_screencast_00003.webm](https://user-images.githubusercontent.com/20650004/191289692-3982e249-206e-4c2a-873f-4148b972486f.webm)
[Kazam_screencast_00005.webm](https://user-images.githubusercontent.com/20650004/191290682-3f32a996-9a43-41a8-89af-8c4873d67a9d.webm)
=> feat(MessageView): hide image url in the message when image is unfurled

ui/app/AppLayouts/Chat/panels/InlineSelectorPanel.qml, ui/app/AppLayouts/Chat/views/ChatHeaderContentView.qml, ui/app/AppLayouts/Chat/views/CreateChatView.qml, ui/app/AppLayouts/Chat/views/MembersSelectorView.qml
Closes #7369
Fixes spacing issues in Createchat/EditGroupChat views 
Affected areas
Createchat/EditGroupChat view
https://user-images.githubusercontent.com/31625338/191240237-ffd2433a-556d-47ea-ba06-97f4f2b002d2.mov
=> fix(Createchat/EditGroupChat view): fixed spacing all over

src/app/modules/main/chat_section/chat_content/users/module.nim, src/app/modules/main/chat_section/chat_content/users/view.nim, src/app/modules/main/communities/module.nim, src/app/modules/main/module.nim, src/app/modules/shared_models/active_section.nim, src/app/modules/shared_models/member_item.nim, src/app/modules/shared_models/member_model.nim, src/app/modules/shared_models/section_item.nim
Fixes #7378
Add Verified value loading into model for members list
Desktop Chat
=> fix(@desktop/community): add member verified model value

ci/Jenkinsfile.uitests, src/app_service/service/transaction/service.nim
=> fix(@wallet): Send tx popup

Makefile, src/app_service/common/network_constants.nim, src/app_service/service/accounts/service.nim
```bash
STATUS_PORT=30311 make -j10 run
```
=> chore(dev): enable STATUS_PORT environment variable to change listener port

ui/StatusQ/src/StatusQ/Popups/statusModal/StatusModalHeader.qml
Fixes #7294
Align close button and update size
=> fix(@desktop/community): community tags close button adjust

ui/StatusQ/src/StatusQ/Components/StatusChatList.qml, ui/StatusQ/src/StatusQ/Components/StatusMemberListItem.qml, ui/StatusQ/src/StatusQ/Components/private/statusMessage/StatusMessageHeader.qml, ui/StatusQ/src/StatusQ/Components/private/statusMessage/StatusTimeStampLabel.qml, ui/StatusQ/src/StatusQ/Controls/StatusIdenticonRing.qml, ui/app/AppLayouts/Chat/panels/UserListPanel.qml, ui/app/AppLayouts/Chat/panels/communities/CommunityMembersSettingsPanel.qml, ui/app/AppLayouts/Chat/panels/communities/CommunityMembersTabPanel.qml, ui/app/AppLayouts/Chat/popups/community/CreateCategoryPopup.qml, ui/app/AppLayouts/Chat/views/ChatContextMenuView.qml, ui/app/AppLayouts/Chat/views/ChatHeaderContentView.qml, ui/app/AppLayouts/Chat/views/ChatMessagesView.qml, ui/app/AppLayouts/Chat/views/ContactsColumnView.qml, ui/app/AppLayouts/Profile/controls/CommunityDelegate.qml, ui/app/AppLayouts/Profile/panels/ContactPanel.qml, ui/app/mainui/AppMain.qml, ui/imports/shared/controls/chat/ProfileHeader.qml, ui/imports/shared/controls/delegates/ContactListItemDelegate.qml, ui/imports/shared/popups/NicknamePopup.qml, ui/imports/shared/popups/ProfilePopup.qml, ui/imports/shared/popups/SendContactRequestModal.qml, ui/imports/shared/popups/UserStatusContextMenu.qml, ui/imports/shared/views/ExistingContacts.qml, ui/imports/shared/views/ProfileView.qml, ui/imports/shared/views/chat/MessageContextMenuView.qml, ui/imports/shared/views/chat/MessageView.qml, ui/imports/utils/Utils.qml
- don't display identicon rings for contacts with an ENS name
- prefer the at-form (@foo-user) whenever possible, and don't display their
username or pubkey unless they are locally given a nickname
- show compressed keys everywhere instead of the regular ones
- fix some warnings and drop dead code (separate commit)
Fixes: https://github.com/status-im/status-desktop/issues/7319
Fixes: https://github.com/status-im/status-desktop/issues/7515
Relevant figma design: https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=900%3A264518
A lot :)
1-1 chat with ENS, not renamed:
1-1 chat with ENS, renamed:
Community chat with messages and user list:
Start chat with user list:
Contacts list/addressbook:
AC messages:
Send contact request:
ENS contact profile popup, with local …
=> fix: ENS name issues

ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
Fixes #7322
Footer buttons anchored to `leftPanel` bottom.
Improved list view alignment.
Community Settings / Left panel
https://user-images.githubusercontent.com/97019400/192524248-a5d0dfb6-aecd-4767-8cb0-ccd191f754d5.mov
=> fix(Communities/Settings): Cropped bottom panel in Community Overview

test/ui-test/src/screens/StatusWalletScreen.py, test/ui-test/testSuites/global_shared/scripts/decorators.py, test/ui-test/testSuites/suite_status/shared/scripts/sections/wallet_names.py, test/ui-test/testSuites/suite_status/shared/steps/walletSteps.py, test/ui-test/testSuites/suite_status/tst_wallet/test.feature, ui/imports/shared/views/HistoryView.qml, ui/imports/shared/views/TransactionDetailView.qml
Added squish tests for transactions and transaction details
status_go: https://github.com/status-im/StatusQ/pull/915
fixes #7215
Squish test for Transactions
Squish tests for wallet
=> fix(@desktop/wallet): Added squish tests for transactions and transaction details

ui/imports/shared/status/StatusChatInput.qml
Fixes #7622
Revert usage of RichText in `getTextWithPublicKeys` in order to allow emoji.
Adjust logic to replace alias name with pubickey in RichText.
Add mentions sorting in order to simplify replacing logic, which is needed for case when same name is used for different accounts.
Adjust 'updateMentionsPositions` to use sorted mentions and update positions of mentions even if same name appears multiple time for same or different accounts. 
Desktop Chat
https://user-images.githubusercontent.com/6445843/192809833-f6f8f3a8-abe9-420f-a053-cf239d28f7a8.mp4
=> fix(@desktop/chat): adjust chat input logic to allow emojis

test/ui-test/src/screens/SettingsScreen.py, test/ui-test/testSuites/suite_status/shared/scripts/sections/settings_names.py, test/ui-test/testSuites/suite_status/shared/steps/settingsSteps.py, test/ui-test/testSuites/suite_status/tst_settingsMenu/test.feature, ui/app/AppLayouts/Profile/popups/ChangePasswordModal.qml, ui/app/AppLayouts/Profile/popups/ChangePasswordSuccessModal.qml, ui/app/AppLayouts/Profile/views/MyProfileView.qml, ui/imports/shared/views/PasswordView.qml
fixes #6900
Squish test for user being able to change his password and logging in
Settings
=> fix(@desktop/wallet): Added squish test for change password and relogin

ui/app/AppLayouts/Profile/popups/SendContactRequestModal.qml
Fix #7699
Send request to correct chat key for ens account.
Improve pasting chat key - the correctness is automatically checked w/o the need to click on input.
Chat / Send Contact Request
Tested together with @anastasiyaig
=> fix(@desktop/chat): Fix sending request to ens account - MASTER

ui/imports/shared/views/chat/InvitationBubbleView.qml, ui/imports/shared/views/chat/LinksMessageView.qml
Closes #7308
InvitationBubble & LinksMessageView fixes button radius corners
InvitationBubble & LinksMessageView 
=> fix(Invitation+LinksBubble): fixed button radius corners

src/app/modules/shared_models/message_model.nim, ui/app/AppLayouts/Chat/views/ChatMessagesView.qml, ui/imports/shared/views/chat/MessageView.qml, ui/imports/utils/Constants.qml
Closes: #7687
Add update methods for replies 
ChatLogView
=> fix(replies): Fire dataChanged when contact changed in reply

ui/app/AppLayouts/Onboarding/views/SeedPhraseView.qml
=> fix(@desktop/keycard): onboarding - typo

ui/StatusQ/src/StatusQ/Core/StatusCenteredFlow.qml, ui/StatusQ/src/StatusQ/Core/qmldir
Standard Flow component doesn't support center alignment. This component dispite of some limitations tries to amend this gap.
Closes: #7883
[Kazam_screencast_00051.webm](https://user-images.githubusercontent.com/20650004/195557716-3f923c22-80f2-4017-b8ec-d6cf4a107426.webm)
=> feat(StatusQ): StatusCenteredFlow

src/app/core/custom_urls/urls_manager.nim
Fix #7704
This simple fix makes able to handle opening urls after login.
This is needed when the user opens the Status application via web browser, eg:
- goes to "join.status.im/u/{ens name or chat key of some member}"
- clicks "Open in status" button
- the Status app is opened and user profile of the member is displayed
Deep links
https://user-images.githubusercontent.com/61889657/195376673-990b9ed4-fdd1-4738-b818-a1cac93ee0ba.mov
=> fix(@desktop/general): Fix opening deep links when the app is not logged in yet

src/app/modules/main/wallet_section/all_tokens/controller.nim, src/app/modules/main/wallet_section/all_tokens/io_interface.nim, src/app/modules/main/wallet_section/all_tokens/module.nim, src/app/modules/main/wallet_section/all_tokens/view.nim, src/app_service/service/token/async_tasks.nim, src/app_service/service/token/dto.nim, src/app_service/service/token/service.nim, src/backend/backend.nim, ui/StatusQ/src/StatusQ/Components/StatusChartPanel.qml, ui/app/AppLayouts/Wallet/views/RightTabView.qml, ui/imports/shared/stores/RootStore.qml, ui/imports/shared/stores/TokenMarketValuesStore.qml, ui/imports/shared/views/AssetsDetailView.qml, ui/imports/shared/views/AssetsView.qml, ui/imports/shared/views/TransactionDetailView.qml, ui/imports/utils/Utils.qml
feat(@desktop/wallet): Create API to retrieve historical price for a token
statusgo: https://github.com/status-im/status-go/pull/2882
fixes #7260
Implements the price graph for a token https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=6455%3A122774
Wallet
https://user-images.githubusercontent.com/60327365/192761510-d916cf77-d3e5-48a5-b289-e693038f8d2b.mov
=> feat(@desktop/wallet): Create API to retrieve historical price for a token

src/app/boot/app_controller.nim, src/app/modules/startup/controller.nim, src/app/modules/startup/io_interface.nim, src/app/modules/startup/module.nim, ui/imports/shared/popups/keycard/helpers/KeyPairItem.qml, ui/imports/shared/popups/keycard/helpers/KeyPairUnknownItem.qml, ui/imports/shared/popups/keycard/helpers/KeycardItem.qml
=> fix(@desktop/keycard): keypair is not registered for newly created keycard users

storybook/Storybook/PagesList.qml, storybook/Storybook/qmldir, storybook/main.qml, storybook/pages/CommunitiesPortalLayoutPage.qml, storybook/pages/CommunitiesPortalModelEditor.qml, storybook/pages/LoginViewPage.qml, storybook/qml.qrc
Adds light/dark mode switch
Moreover:
- load asynchronously switch fixed
- storybook refactored to rely on build-in components only
- some explicit sizes/spacings removed
- some bigger components split into smaller
Closes: #7898
`Storybook`
=> feat(Storybook): Light/dark mode switch

test/ui-test/src/screens/SettingsScreen.py, test/ui-test/testSuites/suite_wallet/config.xml, test/ui-test/testSuites/suite_wallet/suite.conf, test/ui-test/testSuites/suite_wallet/tst_wallet/test.feature
merge all previous test into one to reduce duration
The line commented in the feature are because there is bug in the app
=> test(@wallet): Add test to manage account

storybook/main.qml, storybook/pages/AboutViewPage.qml, storybook/qml.qrc, ui/app/AppLayouts/Profile/ProfileLayout.qml, ui/app/AppLayouts/Profile/views/AboutView.qml, ui/app/AppLayouts/Profile/views/qmldir
=> chore(@storybook): add about view to storybook, refactor about view to use calls from store instead of global

storybook/CMakeLists.txt, storybook/Storybook/StorybookUtils.qml, storybook/main.cpp, storybook/mocks/DotherSide/StatusSyntaxHighlighter.qml, storybook/mocks/DotherSide/qmldir, ui/imports/shared/views/chat/qmldir
Mock for `DotherSide` types added. Additionally `ui/imports/shared/views/chat/qmldir` fixed.
Closes: #7932
=> fix(Storybook): mock for DotherSide types added

ui/app/AppLayouts/Profile/ProfileLayout.qml, ui/app/mainui/AppMain.qml, ui/imports/shared/status/StatusSearchListPopup.qml, ui/imports/utils/Global.qml, ui/main.qml
- wrap everything we can in AppMain with a (async) Loader
- do not access globals w/o a proper store
- drop some dead code
Although I wasn't able to completely fix the bug, the ~50% improvement in startup time is still worth trying imho. On my machine, the startup time went down from ~7s to under 4s.
Related: #7292
Improves startup time after login
AppMain
=> chore(AppMain): improve startup time

ui/app/AppLayouts/CommunitiesPortal/CommunitiesPortalLayout.qml, ui/app/AppLayouts/CommunitiesPortal/popups/DiscordImportProgressContents.qml, ui/app/mainui/AppMain.qml
- correct plural in qsTr()
- readonly properties
- remove obsolete/dead/unused code
Communities
=> chore: minor Discord import related UI fixes

src/app_service/common/network_constants.nim
status go: https://github.com/status-im/status-go/pull/2910
Fix naming + serialization
=> fix(@test): token override

src/app/boot/app_controller.nim, src/app/modules/main/wallet_section/saved_addresses/item.nim, src/app/modules/main/wallet_section/saved_addresses/model.nim, src/app/modules/main/wallet_section/saved_addresses/module.nim, src/app_service/service/saved_address/dto.nim, src/app_service/service/saved_address/service.nim, src/backend/backend.nim, ui/app/AppLayouts/Wallet/views/SavedAddressesView.qml, ui/imports/shared/controls/SavedAddressesDelegate.qml
status-go: https://github.com/status-im/status-go/pull/2912
fixes #7088
=> feat(@wallet): display ens name with saved addressess

storybook/main.qml, storybook/pages/CommunitiesSectionPage.qml, storybook/qml.qrc, ui/app/AppLayouts/Profile/ProfileLayout.qml, ui/app/AppLayouts/Profile/panels/CommunitiesListPanel.qml, ui/app/AppLayouts/Profile/views/CommunitiesView.qml, ui/app/AppLayouts/Profile/views/NotificationsView.qml, ui/app/AppLayouts/Profile/views/qmldir
Adds Settings -> apps -> communities section to storybook.
The modals dont' currently work due to being global, we need to modify them somehow.
=> refactor(@ui/settings): move part of communities settings to storybook

storybook/main.qml, storybook/pages/DevicesSectionPage.qml, storybook/qml.qrc, ui/app/AppLayouts/Profile/ProfileLayout.qml, ui/app/AppLayouts/Profile/views/DevicesView.qml, ui/app/AppLayouts/Profile/views/qmldir
Add the device settings section to storybug. also fixes a bug with enable device, found while using storybook.
=> refactor(@ui/settings): add device syncing section to storybook; fix enable device bug

storybook/main.qml, storybook/pages/AdvancedSettingsPage.qml, storybook/qml.qrc, ui/app/AppLayouts/Profile/ProfileLayout.qml, ui/app/AppLayouts/Profile/stores/qmldir, ui/app/AppLayouts/Profile/views/AdvancedView.qml, ui/app/AppLayouts/Profile/views/qmldir
Adds the advanced settings section to storybook
=> refactor(@ui/settings): add advanced settings section to storybook

storybook/main.qml, storybook/pages/AdvancedSettingsPage.qml, storybook/pages/KeycardSectionPage.qml, storybook/qml.qrc, ui/app/AppLayouts/Profile/ProfileLayout.qml, ui/app/AppLayouts/Profile/stores/qmldir, ui/app/AppLayouts/Profile/views/AdvancedView.qml, ui/app/AppLayouts/Profile/views/KeycardView.qml, ui/app/AppLayouts/Profile/views/qmldir
This is first stab at adding the keycard settings section to storybook. a lot more to do in subsequent PRs
=> refactor(@ui/settings): add partially keycard section to storybook

src/app/boot/app_controller.nim, src/app/core/custom_urls/urls_manager.nim, src/app/core/main.nim, src/app/modules/main/io_interface.nim, src/app/modules/main/module.nim, src/app/modules/main/view.nim, src/nim_status_client.nim, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/imports/shared/views/chat/LinksMessageView.qml, ui/imports/shared/views/chat/MessageView.qml, ui/imports/utils/Constants.qml
Fixes #6302
Clicking any deep-link in chat: /u, /c, /cc does not open browser but executes instantly.
Deep links
https://user-images.githubusercontent.com/61889657/196920190-a4c1c59d-478d-4b0d-baba-e6307d20564b.mov
=> fix(@desktop/general): Fix clicking deep links in chat

ui/app/AppLayouts/Profile/ProfileLayout.qml, ui/app/AppLayouts/Profile/views/AboutView.qml
as a bonus, add the link to release notes as well
Fixes #8020
AboutView
=> fix(AboutView): "Our principles" button not working

storybook/CMakeLists.txt, storybook/main.cpp, storybook/main.qml, storybook/pages/BrowserSettingsPage.qml, storybook/stubs/AppLayouts/Profile/stores/LanguageStore.qml, storybook/stubs/AppLayouts/Profile/stores/ProfileSectionStore.qml, storybook/stubs/AppLayouts/Profile/stores/WalletStore.qml, storybook/stubs/AppLayouts/Profile/stores/qmldir, ui/app/AppLayouts/Profile/ProfileLayout.qml, ui/app/AppLayouts/Profile/popups/SearchEngineModal.qml, ui/app/AppLayouts/Profile/stores/qmldir, ui/app/AppLayouts/Profile/views/BrowserView.qml, ui/app/AppLayouts/Profile/views/LanguageView.qml, ui/app/AppLayouts/Profile/views/browser/DefaultDAppExplorerView.qml, ui/app/AppLayouts/Profile/views/browser/HomePageView.qml, ui/app/AppLayouts/Profile/views/qmldir, ui/app/AppLayouts/Profile/views/wallet/PermissionsListView.qml
Adds browser settings to the storybook.
~~Branched off of https://github.com/status-im/status-desktop/pull/7944 so I could inspire myself~~
=> feat(storybook): add browser settings in the storybook

ui/app/AppLayouts/Chat/panels/communities/CommunityWelcomeBannerPanel.qml, ui/app/AppLayouts/Chat/views/CommunityColumnView.qml, ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml, ui/app/AppLayouts/Profile/views/CommunitiesView.qml, ui/app/AppLayouts/Profile/views/ContactsView.qml, ui/app/mainui/AppMain.qml, ui/imports/shared/views/chat/MessageContextMenuView.qml
Fixes #8038
We added a callback arg to the signals, but signals do not support default args. You need to pass the exact number of args.
=> fix: fix signals not passing the callback

ui/imports/Themes/Theme.qml
Reverts accidentally removed import.
`Theme`
=> fix(Theme): restore accidentally removed import

ui/StatusQ/sandbox/CMakeLists.txt, ui/StatusQ/sandbox/qml.qrc, ui/StatusQ/src/assets.qrc, ui/StatusQ/src/statusq.qrc
- regenerated qrc files
- added qrc files as CMake's Sandbox target dependency
=> chore(StatusQ): fix Sandbox release build

ui/app/AppLayouts/Profile/views/ContactsView.qml
Fixes #8080
Fixes action button placement
ContactsView
=> fix(ContactsView): button is in the wrong position

src/app/modules/main/activity_center/item.nim, src/app/modules/main/activity_center/model.nim, src/app/modules/main/activity_center/view.nim, ui/app/AppLayouts/Browser/BrowserLayout.qml, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Chat/views/ChatView.qml, ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml, ui/app/AppLayouts/Chat/views/CreateChatView.qml, ui/app/AppLayouts/CommunitiesPortal/CommunitiesPortalLayout.qml, ui/app/AppLayouts/CommunitiesPortal/stores/CommunitiesStore.qml, ui/app/AppLayouts/Node/NodeLayout.qml, ui/app/AppLayouts/Node/stores/RootStore.qml, ui/app/AppLayouts/Profile/ProfileLayout.qml, ui/app/AppLayouts/Profile/stores/ProfileSectionStore.qml, ui/app/AppLayouts/Wallet/WalletLayout.qml, ui/app/AppLayouts/Wallet/stores/RootStore.qml, ui/app/AppLayouts/stores/RootStore.qml, ui/app/mainui/AppMain.qml, ui/app/mainui/activitycenter/popups/ActivityCenterPopup.qml, ui/app/mainui/activitycenter/stores/ActivityCenterStore.qml, ui/app/mainui/activitycenter/stores/RootStore.qml, ui/app/mainui/activitycenter/stores/qmldir, ui/app/mainui/activitycenter/views/ActivityNotificationBase.qml, ui/app/mainui/activitycenter/views/ActivityNotificationCommunityInvitation.qml, ui/app/mainui/activitycenter/views/ActivityNotificationCommunityMembershipRequest.qml, ui/app/mainui/activitycenter/views/ActivityNotificationMention.qml, ui/app/mainui/activitycenter/views/ActivityNotificationMessage.qml, ui/app/mainui/activitycenter/views/ActivityNotificationReply.qml
Close #7654
Fix and generalise AC notifications couning 
All (!)
=> Refactor AC Store & fix AC notifications count

test/ui-test/src/screens/StatusChatScreen.py, test/ui-test/src/screens/StatusWelcomeScreen.py, test/ui-test/testSuites/global_shared/scripts/global_names.py, test/ui-test/testSuites/global_shared/steps/startupSteps.py, test/ui-test/testSuites/global_shared/steps/steps.py, test/ui-test/testSuites/suite_communities/shared/scripts/community_names.py, test/ui-test/testSuites/suite_messaging/shared/steps/chatSteps.py, test/ui-test/testSuites/suite_messaging/tst_OneToOneChatFlow/bdd_hooks.py, test/ui-test/testSuites/suite_messaging/tst_OneToOneChatFlow/test.feature, test/ui-test/testSuites/suite_messaging/tst_OneToOneChatFlow/test.py, test/ui-test/testSuites/suite_onboarding/shared/steps/signUpSteps.py
Fixes #6884
Creates a new test case that by default logs in with the mutual contacts data dir.
@noeliaSD let me know if I did it correctly
=> test(chat): add a test to create a one to one chat with a mutual contact

test/ui-test/src/screens/StatusCommunityScreen.py, test/ui-test/testSuites/global_shared/scripts/global_names.py, test/ui-test/testSuites/suite_communities/shared/scripts/community_names.py, test/ui-test/testSuites/suite_communities/tst_communityFlows/test.feature, test/ui-test/testSuites/suite_communities/tst_communityMessageFlows/test.feature, test/ui-test/testSuites/suite_messaging/shared/scripts/chat_names.py, ui/app/AppLayouts/Chat/views/ChatHeaderContentView.qml
I rebased on top of Noelia's PR and some of the community tests are now still broken.
This PR now just fixes sending images (expect multiple images because the feature itself is broken) and pin and unpin.
=> fix(community-tests): fix a couple of community tests

ui/app/mainui/activitycenter/controls/ChannelBadge.qml, ui/app/mainui/activitycenter/controls/CommunityBadge.qml, ui/app/mainui/activitycenter/controls/ReplyBadge.qml, ui/app/mainui/activitycenter/popups/ActivityCenterPopup.qml, ui/app/mainui/activitycenter/views/ActivityNotificationBase.qml, ui/app/mainui/activitycenter/views/ActivityNotificationCommunityInvitation.qml, ui/app/mainui/activitycenter/views/ActivityNotificationCommunityMembershipRequest.qml, ui/app/mainui/activitycenter/views/ActivityNotificationCommunityRequest.qml, ui/app/mainui/activitycenter/views/ActivityNotificationMention.qml, ui/app/mainui/activitycenter/views/ActivityNotificationMessage.qml, ui/app/mainui/activitycenter/views/ActivityNotificationReply.qml
- Fix padding and margins in AC
- Make badges links work (even better)
=> fix(ActivityCenter): Polishing Activity Center UI

Makefile, ci/Jenkinsfile.imports, ui/StatusQ/CMakeLists.txt, ui/StatusQ/sandbox/CMakeLists.txt, ui/StatusQ/sanity_checker/CMakeLists.txt, ui/StatusQ/sanity_checker/main.cpp
Small app iterating over all qml files from `qrc` resources and compiling the in order to check imports and general validity.
Required by: https://github.com/status-im/status-desktop/issues/7854
Closes: #8071
Closes: #7854 
`StatusQ`
[Kazam_screencast_00077.webm](https://user-images.githubusercontent.com/20650004/198284649-896174a9-35c6-4122-be24-105343c0b124.webm)
=> feat(StatusQ): SanityChecker app for imports validation

Makefile
This way we avoid errors about missing QT when calling targets that do not require it, like `make clean` or `make deps`.
=> Makefile: move QT dir check to separate target

src/app/core/custom_urls/urls_manager.nim, src/app/global/utils.nim, src/app_service/service/accounts/utils.nim, src/backend/accounts.nim, ui/app/AppLayouts/Chat/panels/communities/CommunityProfilePopupInviteFriendsPanel.qml, ui/app/AppLayouts/Chat/panels/communities/CommunityProfilePopupOverviewPanel.qml, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/imports/utils/Utils.qml
Join community links contains compressed key: "https://join.status.im/c/zQ3sh...."
Links should work normally: via chat or via web browser as deep links (internal - status-im://c/zQ3.....)
Technical details:
zQ3.. format is a multiformat compression.
Community id is propagated in the system as a compressed 33-bytes string.
Utility function "changeCommunityKeyCompression" was added to change compressions 33-bytes <-> multiformat.
This function is used to create a share link or before opening link which uses zQ3 format.
Required prs:
https://github.com/status-im/status-go/pull/2924
https://github.com/status-im/nim-status-go/pull/17
Chat/Community/ Deep links
=> 8001 compressed community key2

ci/Jenkinsfile.uitests, src/app/boot/app_controller.nim, src/app/modules/main/profile_section/sync/controller.nim, src/app/modules/main/profile_section/sync/io_interface.nim, src/app/modules/main/profile_section/sync/module.nim, src/app/modules/main/profile_section/sync/view.nim, src/app_service/service/accounts/service.nim, src/app_service/service/mailservers/service.nim, src/app_service/service/settings/service.nim, ui/app/AppLayouts/Profile/popups/WakuNodesModal.qml, ui/app/AppLayouts/Profile/stores/MessagingStore.qml
Fixes #8025 
Requires:
- https://github.com/status-im/status-go/pull/2942
=> chore(CI): replace mailserver by storenode

src/app/modules/main/browser_section/provider/controller.nim, src/app/modules/main/controller.nim, src/app/modules/main/io_interface.nim, src/app/modules/main/module.nim, src/app/modules/main/profile_section/ens_usernames/controller.nim, src/app/modules/main/stickers/controller.nim, src/app/modules/main/wallet_section/accounts/controller.nim, src/app/modules/main/wallet_section/accounts/io_interface.nim, src/app/modules/main/wallet_section/accounts/module.nim, src/app/modules/main/wallet_section/accounts/view.nim, src/app/modules/main/wallet_section/transactions/controller.nim, src/app/modules/shared_modules/keycard_popup/controller.nim, src/app/modules/shared_modules/keycard_popup/io_interface.nim, src/app/modules/shared_modules/keycard_popup/module.nim, src/app_service/service/wallet_account/service.nim, ui/app/AppLayouts/Wallet/popups/AddAccountModal.qml, ui/app/AppLayouts/Wallet/stores/RootStore.qml
=> fix(@desktop/keycard): `ExportPublic` instead of `Sign` flow should be used for user authentication

ci/Jenkinsfile.uitests, src/app_service/common/network_constants.nim, test/ui-test/src/screens/SettingsScreen.py, test/ui-test/src/screens/StatusMainScreen.py, test/ui-test/src/screens/StatusWalletScreen.py, test/ui-test/testSuites/global_shared/scripts/global_names.py, test/ui-test/testSuites/global_shared/steps/settingsSteps.py, test/ui-test/testSuites/global_shared/steps/startupSteps.py, test/ui-test/testSuites/global_shared/steps/steps.py, test/ui-test/testSuites/global_shared/steps/walletInitSteps.py, test/ui-test/testSuites/suite_communities/shared/steps/communitySteps.py, test/ui-test/testSuites/suite_communities/tst_communityMemberFlows/test.feature, test/ui-test/testSuites/suite_communities/tst_searchFlows/bdd_hooks.py, test/ui-test/testSuites/suite_messaging/shared/steps/chatSteps.py, test/ui-test/testSuites/suite_messaging/tst_ChatFlow/bdd_hooks.py, test/ui-test/testSuites/suite_onboarding/shared/steps/signUpSteps.py, test/ui-test/testSuites/suite_onboarding/tst_statusSignUp/test.feature, test/ui-test/testSuites/suite_settings/tst_settingsMenu/test.feature, test/ui-test/testSuites/suite_wallet/shared/scripts/wallet_names.py, test/ui-test/testSuites/suite_wallet/shared/steps/walletSteps.py, test/ui-test/testSuites/suite_wallet/tst_transaction/bdd_hooks.py, test/ui-test/testSuites/suite_wallet/tst_transaction/test.feature, test/ui-test/testSuites/suite_wallet/tst_transaction/test.py, test/ui-test/testSuites/suite_wallet/tst_wallet/bdd_hooks.py, test/ui-test/testSuites/suite_wallet/tst_wallet/test.feature, test/ui-test/testSuites/suite_wallet/tst_wallet/test.py, ui/StatusQ/src/StatusQ/Components/StatusToolBar.qml, ui/app/AppLayouts/Wallet/views/LeftTabView.qml
Closes [#8012](https://github.com/status-im/status-desktop/issues/8012)
- Created `bdd_hooks` that contain the sing up steps just only once in the feature start and the needed start steps depending on the test case.
- Updated feature files removing sign up steps and given/when/then reorganization.
`suite_wallet`
=> test(chore/suite_wallet): Added specific bdd_hooks for `suite_wallet`

ui/app/AppLayouts/Chat/panels/InlineSelectorPanel.qml
fixes: #7495
- create chat
- edit group members
There is no design for this yet
https://user-images.githubusercontent.com/33099791/200281789-450e8219-938b-48ae-82fd-9ca0899e6235.mp4
=> chore(chat/MembersSelector): display "no results" when not found

src/app_service/common/utils.nim, src/app_service/service/settings/service.nim
Validate input social links via regexp on save
Profile social links saving
=> fix(@desktop/Profile): validate social links before saving #7926

ui/app/AppLayouts/Chat/panels/InlineSelectorPanel.qml, ui/app/AppLayouts/Chat/views/CreateChatView.qml, ui/app/AppLayouts/Chat/views/MembersEditSelectorView.qml, ui/app/AppLayouts/Chat/views/MembersSelectorView.qml, ui/app/AppLayouts/Chat/views/private/MembersSelectorBase.qml
Closes #7340
CreateChatView fixed tagselector various issues
CreateChatView
https://user-images.githubusercontent.com/31625338/194599748-cec9ffff-87c2-4b94-a046-5876fe839883.mov
https://user-images.githubusercontent.com/31625338/194599756-1729e3eb-b4e9-4adf-8863-4d8783cf070c.mov
https://user-images.githubusercontent.com/31625338/194599782-61b00742-9b8f-4d8b-82f3-335f1d8c03b3.mov
https://user-images.githubusercontent.com/31625338/194599793-c58aeae5-8607-4e98-b8b4-58a359b1b6bb.mov
=> fix(CreateChatView): fixed tagselector various issues

src/app/boot/app_controller.nim, src/app/modules/main/wallet_section/collectibles/collections/controller.nim, src/app/modules/main/wallet_section/collectibles/collections/io_interface.nim, src/app/modules/main/wallet_section/collectibles/collections/module.nim, src/app/modules/main/wallet_section/collectibles/module.nim, src/app_service/service/collectible/async_tasks.nim, src/app_service/service/collectible/service.nim
Now when switching account all remote call are non blocking
fixes #7430
=> fix(@wallet): switch account being slow

libs/Onboarding/src/Onboarding/Accounts/AccountsService.cpp, resources/node-config.json
=> feat(@desktop/cpp): Use env variable WAKUV2_PORT

ui/app/AppLayouts/Profile/views/MyProfileView.qml, ui/imports/shared/panels/ProfileBioSocialsPanel.qml
Preview Bio length and scroll area fix #7922
- fix incorrect scroll area size if set a lot of lines in Bio
- added scroll area for Bio with a big amount of lines 
Preview Bio widget
https://user-images.githubusercontent.com/117639195/201348172-af99f221-b8a5-446f-841d-b9a3167f5dd8.mov
=> fix:(@desktop/Profile): Preview Bio length and scroll area fix #7922

storybook/main.qml, storybook/pages/MembersSelectorModelEditor.qml, storybook/pages/MembersSelectorPage.qml, storybook/pages/ProfileDialogViewPage.qml, ui/StatusQ/src/StatusQ/Core/StatusListView.qml, ui/app/AppLayouts/Chat/panels/InlineSelectorPanel.qml, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Chat/stores/UsersStore.qml, ui/app/AppLayouts/Chat/views/ChatHeaderContentView.qml, ui/app/AppLayouts/Chat/views/MembersEditSelectorView.qml, ui/app/AppLayouts/Chat/views/MembersSelectorView.qml, ui/app/AppLayouts/Chat/views/private/MembersSelectorBase.qml, ui/app/AppLayouts/Chat/views/qmldir, ui/imports/shared/controls/delegates/ContactListItemDelegate.qml
closes: #8178
fixes: #8210
members selector, members editor
https://user-images.githubusercontent.com/33099791/201916638-8ebfbb66-233f-4c4b-b9dd-c5a3f1ac5a39.mp4
=> feat(storybook): add MembersSelector to storybook

ui/StatusQ/src/StatusQ/Controls/StatusSeedPhraseInput.qml, ui/app/AppLayouts/Onboarding/views/SeedPhraseInputView.qml
As requested in #8336
Closes #8336
=> fix(Onboarding): ignore seed phrase capitalization

ui/imports/shared/status/StatusChatInput.qml
Fixing up/down key handler when emojiSuggestions are visible
Fixing #8335
StatusChatInput navigation
https://user-images.githubusercontent.com/47811206/203015659-b3dae753-4cd3-4aa6-9c3e-41da4e9fd1f1.mov
=> StatusChatInput - Fixing emoij suggestion keyNav

ci/Jenkinsfile.combined, ci/Jenkinsfile.e2e, ci/Jenkinsfile.imports, ci/Jenkinsfile.linux, ci/Jenkinsfile.linux-cpp, ci/Jenkinsfile.macos, ci/Jenkinsfile.macos-cpp.todo, ci/Jenkinsfile.windows, ci/Jenkinsfile.windows-cpp.todo
Depends on: https://github.com/status-im/status-jenkins-lib/pull/53
=> ci: fix name of e2e test jobs in gh comments

src/app_service/service/contacts/dto/contacts.nim, src/app_service/service/contacts/service.nim, src/backend/contacts.nim
Close #8277
Fixed:
Fix accepting and declining identity verification requests
Contacts
=> fix(Contacts): Add self id for identity verification requests

test/ui-test/src/drivers/SquishDriver.py, test/ui-test/src/screens/StatusChatScreen.py, test/ui-test/src/utils/ObjectAccess.py, test/ui-test/testSuites/global_shared/scripts/global_names.py, test/ui-test/testSuites/suite_messaging/shared/scripts/chat_names.py, test/ui-test/testSuites/suite_messaging/tst_ChatFlow/test.feature
Fixing hover menu problems: reply, edit, delete message.
Fix #7911
=> fix(@desktop/test): Fixing chat flow test

test/ui-test/src/screens/StatusCommunityScreen.py, test/ui-test/testSuites/suite_communities/shared/scripts/community_names.py, test/ui-test/testSuites/suite_communities/shared/steps/communitySteps.py, test/ui-test/testSuites/suite_communities/tst_communityMessageFlows/test.feature
Add a squish test for replying to a msg in the community channel
Tests in `tst_communityMessageFlows` due to minor refactor
=> test(@desktop/chat): Can reply to a message in a community channel

ui/app/AppLayouts/Node/NodeLayout.qml
Also allows selecting text in the input used to write the RPC request
=> fix: allow copying the results of callPrivateRPC

src/app/modules/main/chat_section/module.nim
Fixes #6184 and fixes #8370
[notifs2022-11-24 11:59:31.webm](https://user-images.githubusercontent.com/11926403/203836145-e6153cf3-5c88-4ba6-8820-98c0ca4fdcda.webm)
=> fix(chat): dont notify or show badge on muted channels

storybook/PagesModel.qml, storybook/figma.json, storybook/figmaio.cpp, storybook/figmaio.h, storybook/figmalinkssource.cpp, storybook/figmalinkssource.h, storybook/main.qml, storybook/pages/ImagesGridViewPage.qml, storybook/src/Storybook/FigmaPreviewWindow.qml, storybook/src/Storybook/ImagesGridView.qml, storybook/src/Storybook/PageToolBar.qml, storybook/tests/tst_FigmaDecoratorModel.cpp
Adds possibility to add/remove Figma links directly from the app.
Closes: #8450
`Storybook`
[simplescreenrecorder-2022-11-29_12.15.57.webm](https://user-images.githubusercontent.com/20650004/204523204-ab0c1b51-f31e-4f8b-9716-cbfea1e7cfa5.webm)
=> feat(Storybook): Possibility to modify Figma links directly from the app

src/app/modules/main/chat_section/chat_content/messages/io_interface.nim, src/app/modules/main/chat_section/chat_content/messages/module.nim, src/app/modules/main/chat_section/chat_content/messages/view.nim, src/app/modules/shared_models/message_model.nim, ui/app/AppLayouts/Chat/stores/MessageStore.qml, ui/app/AppLayouts/Chat/views/ChatMessagesView.qml, ui/imports/shared/views/chat/MessageView.qml
Fixes: #7248
It was wrong solution to get message for reply from model, cos its can be not exist there.
Messaging
=> fix(replies): Get original message from status-go for replies

ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
=> fix(chat): rename 'Chat' -> 'Messages' headline

src/app_service/service/accounts/service.nim, src/app_service/service/node_configuration/dto/node_config.nim, src/app_service/service/node_configuration/service.nim
Requires
- https://github.com/status-im/status-go/pull/2438
=> feat: use identify protocol instead of separate wakuv2 nodeconfig items

ui/app/AppLayouts/Profile/views/AdvancedView.qml
Requires
- https://github.com/status-im/status-go/pull/2987
=> chore(waku2): disable light nodes in status.prod

src/app/modules/main/profile_section/advanced/controller.nim, src/app/modules/main/profile_section/advanced/io_interface.nim, src/app/modules/main/profile_section/advanced/module.nim, src/app/modules/main/profile_section/advanced/view.nim, src/app_service/common/network_constants.nim, src/app_service/service/community/service.nim, src/app_service/service/node_configuration/service.nim, src/backend/general.nim, src/backend/node_config.nim, ui/app/AppLayouts/Chat/controls/community/CommunityOptions.qml, ui/app/AppLayouts/Chat/panels/communities/CommunityOverviewSettingsPanel.qml, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml, ui/app/AppLayouts/CommunitiesPortal/popups/CreateCommunityPopup.qml, ui/app/AppLayouts/CommunitiesPortal/stores/CommunitiesStore.qml, ui/app/AppLayouts/Profile/stores/AdvancedStore.qml, ui/app/AppLayouts/Profile/views/AdvancedView.qml
Closes: #6098
Enable Community History Archive by default and remove toggle
Community
=> feat(Settings): Enable Community History Archive by default and remove toggle

src/app/modules/main/profile_section/advanced/controller.nim, src/app/modules/main/profile_section/advanced/io_interface.nim, src/app/modules/main/profile_section/advanced/module.nim, src/app/modules/main/profile_section/advanced/view.nim, src/app_service/common/network_constants.nim, src/app_service/service/community/service.nim, src/app_service/service/node_configuration/service.nim, src/backend/general.nim, src/backend/node_config.nim, ui/app/AppLayouts/Chat/controls/community/CommunityOptions.qml, ui/app/AppLayouts/Chat/panels/communities/CommunityOverviewSettingsPanel.qml, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml, ui/app/AppLayouts/CommunitiesPortal/popups/CreateCommunityPopup.qml, ui/app/AppLayouts/CommunitiesPortal/stores/CommunitiesStore.qml, ui/app/AppLayouts/Profile/stores/AdvancedStore.qml, ui/app/AppLayouts/Profile/views/AdvancedView.qml
Closes: #6098
Original commit by @borismelnik
Same as https://github.com/status-im/status-desktop/pull/6155 but on top of release/0.8.x (with conflict fixes)
=> feat(Settings): Enable Community  Archive by default and remove toggle

src/app/core/signals/remote_signals/community.nim, src/app/core/signals/remote_signals/signal_type.nim, src/app/core/signals/signals_manager.nim, src/app/modules/main/communities/controller.nim, src/app/modules/main/communities/io_interface.nim, src/app/modules/main/communities/module.nim, src/app/modules/main/communities/view.nim, src/app_service/service/community/service.nim, ui/app/AppLayouts/CommunitiesPortal/stores/CommunitiesStore.qml, ui/app/mainui/AppMain.qml
This needs: https://github.com/status-im/status-go/pull/2995
=> Add banner that indicates history archive downloads are in progress

src/app_service/service/transaction/async_tasks.nim, ui/StatusQ/src/StatusQ/Components/StatusCard.qml, ui/StatusQ/src/StatusQ/Core/Utils/Utils.qml, ui/imports/shared/views/NetworkCardsComponent.qml
fixes #8515 
Fixes the routing lines and makes it as per design: https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=2785%3A143842&t=dH45Y1y30MclwOh1-4
Wallet
https://user-images.githubusercontent.com/60327365/204843877-498a5505-2f55-4c9d-9c59-9bce1ce81655.mov
=> @fix(@desktop/wallet): Fix routing lines in SendModal Advanced view

src/app/modules/main/wallet_section/transactions/controller.nim, src/app/modules/main/wallet_section/transactions/io_interface.nim, src/app/modules/main/wallet_section/transactions/module.nim, src/app_service/service/wallet_account/service.nim, src/backend/backend.nim
status-go: https://github.com/status-im/status-go/pull/2993
move timers in status-go, they are causing issues in nim
=> feat(@wallet): move timer to status-go

storybook/PagesModel.qml, storybook/pages/ContactsListAndSearchPage.qml, storybook/stubs/shared/stores/RootStore.qml, storybook/stubs/shared/stores/qmldir, ui/imports/shared/views/ExistingContacts.qml
1. Changes filtering in `ExistingContacts` to use `SortFilterProxyModel` instead of setting visible to false for delegates (what was the source of the problem).
2. Added `ContactsListAndSearch` to the Storybook to make sure that changes in `ExistingContacts` doesn't change behavior of that component
Closes: #7707
`ExistingContacts`
[Kazam_screencast_00091.webm](https://user-images.githubusercontent.com/20650004/205179400-dc2b675e-dc28-4e70-ac9f-d4f733f309e4.webm)
=> fix(InviteFriendsToCommunityPopup): huge empty space between each contact when searching

src/app/modules/main/chat_section/chat_content/messages/module.nim, src/app_service/service/message/dto/message.nim
Fixes: #8369
Skip deleted messages 
Messaging
=> feat(messaging): Skip deleted and deletedForMe messages

src/app/modules/main/networks/model.nim, src/app/modules/main/networks/view.nim, src/app_service/service/transaction/async_tasks.nim, src/app_service/service/transaction/dto.nim, ui/StatusQ/src/StatusQ/Components/StatusCard.qml, ui/imports/shared/popups/SendModal.qml, ui/imports/shared/stores/TransactionStore.qml, ui/imports/shared/views/NetworkCardsComponent.qml, ui/imports/shared/views/NetworksAdvancedCustomRoutingView.qml
fixes #8530
Implement unpreferred and preferred networks 
Wallet
=> fix(@desktop/wallet): Implement missing unpreferred chains

storybook/figmadecoratormodel.h
=> fix(storybook): add missing <optional> include

src/app/modules/main/wallet_section/transactions/controller.nim, src/app/modules/main/wallet_section/transactions/io_interface.nim, src/app/modules/main/wallet_section/transactions/module.nim, src/app/modules/main/wallet_section/transactions/view.nim, src/app_service/service/transaction/async_tasks.nim, src/app_service/service/transaction/dto.nim, src/app_service/service/transaction/service.nim, src/backend/eth.nim, ui/app/AppLayouts/Browser/views/WebProviderObj.qml, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Profile/views/EnsDetailsView.qml, ui/app/AppLayouts/Profile/views/EnsTermsAndConditionsView.qml, ui/imports/shared/controls/GasSelector.qml, ui/imports/shared/popups/SendModal.qml, ui/imports/shared/status/StatusStickerMarket.qml, ui/imports/shared/status/StatusStickerPackClickPopup.qml, ui/imports/shared/stores/TransactionStore.qml, ui/imports/shared/views/FeesView.qml, ui/imports/shared/views/SendModalFooter.qml
fixes #8516 
Remove option to switch between slow, optimal and fast priority from SendModal
Wallet
- [] I've checked the design and this PR matches it
- doesn't match the design as of now, but it will be updated soon
https://user-images.githubusercontent.com/60327365/204805318-490ed8e9-5e61-4fc8-a062-f58d529fbd58.mov
=> Remove fees slow, optimal and fast only in simple view

src/app_service/service/community/service.nim
Fixes a bunch of problems related to community import:
#7414 
#7413 
#8100 
Status-go fix makes possible to import community correctly. It also sets correct admin roles for the user who imports.
https://github.com/status-im/status-go/pull/2873/files
Small fix added for change channel color propagation.
https://user-images.githubusercontent.com/61889657/203965146-6e2016c1-557a-4a0d-a869-da8ef6170eff.mov
=> 7414 import community fix

src/app/boot/app_controller.nim, src/app/modules/startup/controller.nim, src/app_service/service/accounts/service.nim
=> fix(@desktop/onboarding): `Onboarding -> Generate keys for a new keycard` - display name is not set

src/app/modules/main/chat_section/module.nim
Fixes #6184 and fixes #8370
I also found that mentions don't give a badge, which they should IMO. So I fixed. I'll open a PR on master too for that
=> Cherrypicked fix(chat): dont notify or show badge on muted channels

src/app_service/service/message/message_cursor.nim, src/app_service/service/message/service.nim, ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
cherry-picked https://github.com/status-im/status-desktop/pull/8664
=> Cherry-pick fix/fetch-messages

ui/app/mainui/activitycenter/views/ActivityNotificationMention.qml, ui/app/mainui/activitycenter/views/ActivityNotificationMessage.qml, ui/app/mainui/activitycenter/views/ActivityNotificationReply.qml
Fixes: #8121
Doesn't work perfectly, because the cherry pick had a big conflict. The state of the release branch and the master branch have diverted a lot for the AC, so I limited this to the bare minimum change that doesn't break anything but still kinda works.
=> CHERRYPICK feat(ActivityCenter): Click on reply message jumps to message in chat log

src/app_service/service/wallet_account/async_tasks.nim, src/app_service/service/wallet_account/service.nim, src/backend/backend.nim
fixes #8571
status-go: https://github.com/status-im/status-go/pull/2997
=> feat(@wallet): speed up add account

storybook/CMakeLists.txt, storybook/qmlTests/TestComponents/tst_StatusChatInput.qml, storybook/qmlTests/main.cpp
Adding qml tests to storybook
+dummy StatusChatInput test
Part of #8471 
storybook project configuration
=> Adding qml tests to storybook

ui/imports/shared/popups/SendModal.qml, ui/imports/shared/stores/TransactionStore.qml, ui/imports/shared/views/NetworkSelector.qml, ui/imports/shared/views/NetworksAdvancedCustomRoutingView.qml, ui/imports/shared/views/NetworksSimpleRoutingView.qml
fixes #8660
Fixes the decimals point places in the bridge simple routing view.
please note that the balance exceeded error is not addressed in this PR but will be check under https://github.com/status-im/status-desktop/issues/8665
Wallet
=> fix(@desktop/wallet): Wrong decimal place calculation on bridging

src/app/modules/main/chat_section/module.nim
=> fix(badge): show badge when mentioned even if channel is muted

ui/app/AppLayouts/Chat/panels/communities/CommunityMembersSettingsPanel.qml, ui/app/AppLayouts/Chat/views/ChatHeaderContentView.qml, ui/app/AppLayouts/Chat/views/ChatView.qml, ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml, ui/app/AppLayouts/Onboarding/OnboardingLayout.qml, ui/app/AppLayouts/Onboarding/stores/StartupStore.qml, ui/imports/shared/status/StatusStickersPopup.qml
Fixes: #8293
Fix some warnings
=> fix(warnings): Fix chat, community settings warnings

ui/app/AppLayouts/Profile/views/EnsWelcomeView.qml, ui/app/AppLayouts/Profile/views/SettingsContentBase.qml, ui/app/AppLayouts/Profile/views/profile/MyProfileSettingsView.qml, ui/imports/shared/views/chat/MessageView.qml
Fixes: #8293
Fix warnings in settings
Settings
=> fix(warnings): Fix warnings raised from settings

test/ui-test/src/drivers/SquishDriver.py, test/ui-test/src/screens/SettingsScreen.py, test/ui-test/src/screens/StatusAccountsScreen.py, test/ui-test/src/screens/StatusChatScreen.py, test/ui-test/src/utils/ObjectAccess.py, test/ui-test/testSuites/global_shared/scripts/settings_names.py, test/ui-test/testSuites/global_shared/steps/settingsSteps.py, test/ui-test/testSuites/suite_messaging/shared/steps/chatSteps.py, test/ui-test/testSuites/suite_messaging/tst_ChatFlow/test.feature, ui/app/AppLayouts/Profile/views/MessagingView.qml
Fix #7912
Fixes "The user can send a GIF" and "The user can activate image unfurling" scenarios
=> fix(@desktop/tests): Fixing gif and image unfirling scenarios

ui/app/mainui/AppMain.qml, ui/main.qml
Fixes: #8293
Fix undefined warnings 
AppMain
=> fix(warnings): Fix warnings from  AppMain and main on start

ui/StatusQ/src/StatusQ/Controls/StatusIdenticonRing.qml, ui/StatusQ/src/StatusQ/Popups/StatusMenuItem.qml, ui/StatusQ/src/StatusQ/Popups/StatusSearchLocationMenu.qml, ui/app/AppLayouts/Chat/panels/communities/CommunityChannelsAndCategoriesBannerPanel.qml, ui/app/AppLayouts/Chat/popups/community/TransferOwnershipPopup.qml, ui/app/AppLayouts/Chat/views/ChatMessagesView.qml, ui/app/AppLayouts/Chat/views/CommunityColumnView.qml, ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml, ui/app/AppLayouts/CommunitiesPortal/views/CommunitiesGridView.qml, ui/app/AppLayouts/Profile/views/KeycardView.qml, ui/app/AppLayouts/Profile/views/keycard/DetailsView.qml, ui/imports/shared/status/StatusChatInput.qml
Fixes: #8293
Rid off the last of warnings which I'm able to find.
Search, Communities, Settings
=> fix(warnings): Rid off warnings

ui/app/AppLayouts/stores/RootStore.qml, ui/app/mainui/AppMain.qml, ui/imports/utils/Global.qml, ui/main.qml
Closes #7933
Cleaned up Global from backend dependencies
Global
=> fix(Global): Cleaned up Global from backend dependencies

src/app/modules/main/activity_center/module.nim, src/app/modules/main/chat_section/chat_content/messages/module.nim, src/app/modules/main/chat_section/chat_content/module.nim, src/app/modules/shared_models/message_item.nim, src/app/modules/shared_models/message_item_qobject.nim, src/app/modules/shared_models/message_model.nim, src/app_service/common/conversion.nim, src/app_service/common/message.nim, src/app_service/service/message/dto/message.nim, src/app_service/service/message/service.nim, ui/app/AppLayouts/Chat/panels/SuggestionFilterPanel.qml, ui/app/AppLayouts/Chat/views/ChatContentView.qml, ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
Closes #8479
This needs: https://github.com/status-im/status-go/pull/3026
=> feat: introduce ability to `@everyone`

src/app/modules/main/profile_section/ens_usernames/io_interface.nim, src/app/modules/main/profile_section/ens_usernames/module.nim, src/app/modules/main/profile_section/ens_usernames/view.nim, src/app_service/service/transaction/async_tasks.nim, src/app_service/service/transaction/dto.nim, ui/StatusQ/src/StatusQ/Controls/StatusBaseInput.qml, ui/app/AppLayouts/Profile/stores/EnsUsernamesStore.qml, ui/imports/shared/controls/AmountInputWithCursor.qml, ui/imports/shared/controls/GasSelector.qml, ui/imports/shared/panels/StatusAssetSelector.qml, ui/imports/shared/popups/SendModal.qml, ui/imports/shared/stores/TransactionStore.qml, ui/imports/shared/views/AmountToReceive.qml, ui/imports/shared/views/AmountToSend.qml, ui/imports/shared/views/FeesView.qml, ui/imports/shared/views/NetworkSelector.qml, ui/imports/shared/views/NetworksAdvancedCustomRoutingView.qml, ui/imports/shared/views/NetworksSimpleRoutingView.qml, ui/imports/utils/Utils.qml
fixes #8609
Implements new design changes for the send modal from 👍 https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=9770%3A130516&t=rgLkbtLR3Ezm9GBW-4
https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=9541%3A116005&t=rgLkbtLR3Ezm9GBW-4
Wallet
https://user-images.githubusercontent.com/60327365/207940841-7ae7e166-8c36-4371-983f-ef2bb7373d56.mov
=> feat(@desktop/wallet): Send modal update

ui/app/mainui/activitycenter/panels/ContactRequestCta.qml, ui/app/mainui/activitycenter/views/ActivityNotificationContactRequest.qml
Close #8388
Update text & ui for AC contact requests
=> feat(ActivityCenter) Outgoing contact request notification text fixes

ui/app/mainui/activitycenter/views/ActivityNotificationContactRequest.qml, ui/app/mainui/activitycenter/views/ActivityNotificationContactVerification.qml, ui/app/mainui/activitycenter/views/ActivityNotificationMessage.qml
Close #8586
Subscribe on contact changes in AC notification
ActivityCenter
Uploading Screen Recording 2022-12-30 at 13.14.57.mov…
=> fix(ActivityCenter): Update AC notification on contact changes

ui/StatusQ/sandbox/pages/StatusCardPage.qml, ui/StatusQ/src/StatusQ/Components/StatusCard.qml, ui/StatusQ/src/StatusQ/Core/Utils/Utils.qml, ui/imports/shared/controls/BalanceExceeded.qml, ui/imports/shared/controls/GasValidator.qml, ui/imports/shared/popups/SendModal.qml, ui/imports/shared/views/AmountToSend.qml, ui/imports/shared/views/FeesView.qml, ui/imports/shared/views/NetworkCardsComponent.qml, ui/imports/shared/views/NetworkSelector.qml, ui/imports/shared/views/NetworksAdvancedCustomRoutingView.qml, ui/imports/shared/views/NetworksSimpleRoutingView.qml, ui/imports/utils/Constants.qml
fixes #8714
Implement updated designs 
https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=9770%3A128205&t=7Rxe3LkHoLYiYRgg-4
https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=9770%3A130516&t=7Rxe3LkHoLYiYRgg-4
Wallet
https://user-images.githubusercontent.com/60327365/209655071-4f82aca3-d02f-4506-a79b-9f741c023b37.mov
=> feat(@desktop/wallet): Update network card and routing lines in SendModal

ui/StatusQ/src/StatusQ/Components/StatusListItem.qml, ui/imports/shared/controls/AssetAndAmountInput.qml, ui/imports/shared/controls/TokenBalancePerChainDelegate.qml, ui/imports/shared/panels/StatusAssetSelector.qml, ui/imports/shared/popups/SendModal.qml, ui/imports/shared/views/TokenListView.qml
fixes #8713
Updates the token selector with latest design https://github.com/status-im/status-desktop/pull/new/feat/issue-8713
Wallet
=> feat(@desktop/wallet): Update the token selector in SendModal

src/app_service/service/token/service.nim
=> fix(@wallet): fix crash when sending a tx after toggling network

ui/app/mainui/AppSearch.qml
=> fix(AppSearch): close appsearch popup when sendmessage button is clicked

src/app_service/service/eth/dto/transaction.nim, src/app_service/service/transaction/service.nim
status-go: https://github.com/status-im/status-go/pull/3017
fixes #8235
=> feat(@wallet): cbridge integration

src/app/modules/main/chat_section/chat_content/users/module.nim
Add the correct chat member to the list during the chat update
Regression after MR https://github.com/status-im/status-desktop/pull/8899
Fixes: #8958
Chats member list
=> fix(@desktop/chat): empty chat members list

src/app/core/tasks/threadpool.nim
makes #5938 easier to debug
Since the app can be blocked essentially by any task we need a mechanism to identify the culprit. These logs will make it obvious what caused the app to hang on the exit.
Example:
```
DBG 2023-01-04 11:24:53.854+01:00 [threadpool task thread] initiating task   topics="task-threadpool" tid=787541 file=threadpool.nim:92 messageType=RequestMoreMessagesTaskArg:ObjectType threadid=8 task="{\"$type\":\"RequestMoreMessagesTaskArg:ObjectType\",\"chatId\":\"test2\",\"vptr\":94250510532432,\"slot\":\"mailserverSynced\",\"tptr\":94250488410208}" 
INF 2023-01-04 11:24:57.238+01:00 shutting down...                           topics="status-app" tid=787520 file=nim_status_client.nim:145          
DBG 2023-01-04 11:25:19.480+01:00 [threadpool task thread] sending 'done' notice …
```
=> chore: add task details to threadpool logs

Makefile, src/app/boot/app_controller.nim, src/app/modules/main/profile_section/advanced/controller.nim, src/app_service/service/node_configuration/service.nim, src/nim_status_client.nim
=> chore: re-enable logging in prod version

test/ui-test/src/screens/StatusCommunityScreen.py, test/ui-test/testSuites/suite_communities/shared/scripts/community_names.py, test/ui-test/testSuites/suite_communities/shared/steps/communitySteps.py, test/ui-test/testSuites/suite_communities/tst_communityFlows/test.feature
1. For test scenario: [suite_communities / tst_communityFlows] 'The admin edits a community' - validate test description and color. 
2. Added separate test for editing community name, description, and color separately
Closes: #8008
=> test(@desktop/community): [suite_communities / tst_communityFlows] Validate in 'The admin edits a community' test description and color

src/app/modules/main/wallet_section/transactions/controller.nim, src/app/modules/main/wallet_section/transactions/io_interface.nim, src/app/modules/main/wallet_section/transactions/module.nim, src/app/modules/main/wallet_section/transactions/view.nim, src/app_service/service/transaction/service.nim, ui/app/AppLayouts/stores/RootStore.qml, ui/imports/shared/stores/TransactionStore.qml
=> chore(@wallet): remove dead code about estimage gas

src/app/modules/startup/models/fetching_data_item.nim, src/app/modules/startup/models/fetching_data_model.nim, src/app/modules/startup/module.nim, src/app/modules/startup/view.nim, ui/app/AppLayouts/Onboarding/views/ProfileFetchingView.qml, ui/imports/utils/Constants.qml
- icon added to the ui items we're syncing
- in case data are fetched during 30 seconds timeframe the app is staying in success state
=> fix(@desktop/onboarding): fetching waku data ui improvements

ui/StatusQ/src/StatusQ/Components/StatusDateGroupLabel.qml
=> fix: remove group labels for 'today' and 'yesterday'

ui/StatusQ/sandbox/demoapp/ChatChannelView.qml, ui/StatusQ/src/StatusQ/Components/StatusMessage.qml, ui/StatusQ/src/StatusQ/Components/StatusMessageHeader.qml, ui/StatusQ/src/StatusQ/Components/private/statusMessage/StatusAudioMessage.qml, ui/StatusQ/src/StatusQ/Components/private/statusMessage/StatusEditMessage.qml, ui/StatusQ/src/StatusQ/Components/private/statusMessage/StatusMessageReply.qml, ui/StatusQ/src/StatusQ/Components/private/statusMessage/StatusPinMessageDetails.qml, ui/StatusQ/src/StatusQ/Controls/StatusInput.qml, ui/app/AppLayouts/Chat/ChatLayout.qml, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Chat/views/ChatColumnView.qml, ui/app/AppLayouts/Chat/views/ChatContentView.qml, ui/app/AppLayouts/Chat/views/ChatMessagesView.qml, ui/app/AppLayouts/Chat/views/CommunityColumnView.qml, ui/imports/shared/views/chat/LinksMessageView.qml, ui/imports/shared/views/chat/MessageView.qml, ui/imports/utils/Constants.qml
- drop dead code
- reduce number of direct bindings
- use Loaders whenever possible
Fixes #8744
StatusMessage & friends
=> chore: refactor/improve/optimize StatusMessage & friends

Makefile, ci/Jenkinsfile.tests-nim
- fixes always failing `jenkins/prs/tests-nim` due to the lack of `nim`
- addresses https://github.com/status-im/status-desktop/pull/8849#pullrequestreview-1242246713
=> fix(ci): make tests-nim use docker image with nim installed

ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
Create an empty string if tags are empty
Previously string was === """"
Fixes: #9024
community tags adding/removing
=> fix(@desktop/community): create an empty string if tags are empty

ui/imports/shared/status/StatusStickersPopup.qml
=> fix(StatusStickersPopup): fix stick pack list not scrollable

ui/imports/shared/status/StatusChatInput.qml
Closes #7600
Fixes paste action in status chat input
https://user-images.githubusercontent.com/31625338/210800080-385d6870-63ad-4d2e-8029-8aa045dcc53d.mov
=> fix(StatusChatInput): fixed paste action doesn't work

src/app_service/service/ens/utils.nim, src/app_service/service/eth/dto/coder.nim, src/app_service/service/transaction/dto.nim, src/app_service/service/transaction/service.nim, ui/imports/shared/controls/GasSelector.qml
approve transaction management
fixes #8806 
status-go https://github.com/status-im/status-go/pull/3050
=> feat(@wallet): multi tx approval/nonce

ui/StatusQ/src/statusq.qrc
remove left over from qrc file
remove left over from qrc file
NA
=> fix(@desktop/wallet): Remove Animations from StatusQ and solve sanity check failure

src/app_service/service/message/dto/message.nim
Fixes #8324
Status-go PR https://github.com/status-im/status-go/pull/3035
=> Make replies act as mentions (shows mention badge on channel and section)

ui/imports/shared/status/StatusChatInput.qml
=> fix(StatusChatInput): turn off reply mode after replying with gif message

ui/app/AppLayouts/Chat/controls/community/CommunityBannerPicker.qml, ui/app/AppLayouts/Chat/panels/communities/CommunityEditSettingsPanel.qml
Closes #9051
Fixes Community edit panel should have fixed width
Community edit panel
https://user-images.githubusercontent.com/31625338/212327821-0769e9af-753e-4d2f-8173-a7dd694a4619.mov
=> fix(CommunityEdit): content width should have fixed size

src/app/modules/shared_modules/keycard_popup/module.nim, src/app/modules/startup/internal/recover_old_user_state.nim, src/app/modules/startup/internal/state.nim, src/app/modules/startup/internal/state_factory.nim, src/app/modules/startup/internal/welcome_state_old_user.nim, src/app/modules/startup/module.nim, ui/app/AppLayouts/Onboarding/OnboardingLayout.qml, ui/app/AppLayouts/Onboarding/views/KeysMainView.qml, ui/imports/utils/Constants.qml
I made `Scan sync code` button disabled cause that flow is not developed yet.
Closes: #9120
=> feat(@desktop/onboarding): onboarding - recover account flow - UI adjustments

ui/StatusQ/src/StatusQ/Components/StatusDateGroupLabel.qml, ui/app/mainui/activitycenter/views/ActivityNotificationMessage.qml, ui/imports/shared/popups/ContactVerificationRequestPopup.qml, ui/imports/shared/popups/OutgoingContactVerificationRequestPopup.qml, ui/imports/shared/views/chat/SimplifiedMessageView.qml, ui/imports/shared/views/chat/qmldir
Close #9002 and #8950
Fix overlapping messages in ContactVerificationRequestPopup
Profile, ActivityCenter
=> fix(ContactVerificationRequestPopup): Fix overlapping messages

src/app/modules/main/activity_center/controller.nim, src/app/modules/main/activity_center/module.nim, src/app/modules/main/app_search/controller.nim, src/app/modules/main/app_search/module.nim, src/app/modules/main/chat_section/chat_content/controller.nim, src/app/modules/main/chat_section/chat_content/messages/controller.nim, src/app/modules/main/chat_section/chat_content/messages/module.nim, src/app/modules/main/chat_section/chat_content/module.nim, src/app/modules/main/chat_section/controller.nim, src/app/modules/main/chat_section/module.nim, src/app/modules/main/module.nim, src/app_service/service/message/service.nim
=> fix(chat): only turn available channels into clickable tags

src/app/modules/main/chat_section/base_item.nim, src/app/modules/main/chat_section/controller.nim, src/app/modules/main/chat_section/item.nim, src/app/modules/main/chat_section/model.nim, src/app/modules/main/chat_section/module.nim, src/app_service/service/chat/service.nim, ui/StatusQ/src/StatusQ/Components/StatusChatListAndCategories.qml, ui/StatusQ/src/StatusQ/Components/StatusChatListCategory.qml, ui/StatusQ/src/StatusQ/Components/StatusChatListCategoryItem.qml
=> fix(chat): make category bold if chats have unread messages

src/app_service/service/message/message_cursor.nim, src/app_service/service/message/service.nim, ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
closes: #8907
https://user-images.githubusercontent.com/33099791/212104535-5d2f2447-0281-4465-8c17-f36f1d1cfbaf.mp4
=> feat(chat): ignore not loaded messages

ui/app/AppLayouts/Profile/ProfileLayout.qml
- replace StackLayout with Loaders, activate them lazily and never unload
when staying inside the Settings sections
- drop some imperative code
- faster startup, subsection load times and quick switching between subsections
Fixes #8781
Refactors/simplifies ProfileLayout (aka Settings)
ProfileLayout (aka Settings)
Contacts:
About:
=> chore(ProfileLayout): improve startup time / memory usage

ui/app/AppLayouts/Profile/views/wallet/AccountView.qml
=> fix(@wallet): related account heights

scripts/password-hash.py
Created a script according to [our docs](https://hackmd.io/txoJObuQQ_GFZB35OSaEKA) for easy manual accessing application database.
Also improved the docs, btw.
=> feat(scripts): Python password hash script for manual database access

ci/Jenkinsfile.combined
Requires:
- https://github.com/status-im/status-go/pull/3108
=> chore: bump status-go to reduce the number of mailserver not available errors

src/app_service/service/stickers/service.nim, ui/StatusQ/src/StatusQ/Components/StatusMessage.qml, ui/imports/shared/views/chat/MessageView.qml
This reverts commit 7cdf053f5b1097f19dab4cd3fa22064b62915d27.
=> Revert "fix(StatusMessage): stickers were not aligned correctly"

src/app/modules/main/module.nim
Fix #8789
https://user-images.githubusercontent.com/61889657/208147177-cef493da-c4c3-4010-888c-24ecc7d26df6.mov
=> fix(@desktop/chat): Do not change screen when showing profile window

src/app/modules/startup/internal/profile_fetching_announcement_state.nim
=> chore(@desktop/onboarding): remove `Create a new profile with the same chatkey` screen from onboarding flow

src/app_service/service/wallet_account/service.nim, src/backend/backend.nim
Call API to check service up or down per chain
status-go: https://github.com/status-im/status-go/pull/3097
=> feat(@wallet): Integrate api to check service up or down

Makefile
Solution found [here](https://stackoverflow.com/a/54040213/7449458)
=> fix(Makefile): Fixed ANSI coloring

src/app/boot/app_controller.nim, src/app_service/service/mailservers/service.nim
This PR contains same commits from https://github.com/status-im/status-desktop/pull/9270 but it's targeting 0.9.x branch
=> fix(0.9.x): cancel mailserver requests on shutdown

ui/app/AppLayouts/Wallet/panels/DerivedAddressesPanel.qml, ui/app/AppLayouts/Wallet/popups/AddAccountModal.qml, ui/app/AppLayouts/Wallet/views/AdvancedAddAccountView.qml
=> fix(@wallet): preview button instead of enter password/pin

test/ui-test/src/screens/SettingsScreen.py, test/ui-test/testSuites/global_shared/scripts/settings_names.py, test/ui-test/testSuites/global_shared/steps/settingsSteps.py, test/ui-test/testSuites/suite_communities/shared/steps/communitySteps.py, test/ui-test/testSuites/suite_communities/tst_communityFlows/test.feature, test/ui-test/testSuites/suite_communities/tst_communityNavigation/bdd_hooks.py, test/ui-test/testSuites/suite_communities/tst_communityNavigation/test.feature, test/ui-test/testSuites/suite_communities/tst_communityNavigation/test.py, ui/app/AppLayouts/Profile/views/CommunitiesView.qml
Closes https://github.com/status-im/status-desktop/issues/8034
Implemented a simple test of create and leave community.
`suite_communitites`
=> feat(tst_communityNavigation): Implemented community leave test

ui/StatusQ/src/StatusQ/Core/LocaleUtils.qml, ui/imports/shared/views/AmountToSend.qml
fixes #9207
As per doc this method will fail when entering a float: https://doc.qt.io/qt-6/qml-qtqml-number.html#fromLocaleString-method
=> fix(@wallet): fix amount input send modal

src/app/modules/main/wallet_section/transactions/controller.nim, src/app/modules/main/wallet_section/transactions/module.nim, src/app_service/service/ens/service.nim, src/app_service/service/stickers/service.nim, src/app_service/service/token/service.nim, src/app_service/service/transaction/async_tasks.nim, src/app_service/service/transaction/dto.nim, src/app_service/service/transaction/service.nim, src/backend/transactions.nim
* Make get pending tx returning object instead of json
* Fix deserialization of small float for suggested routes
* Move wallet event handler to services
* Fix handling event with watch tx and check recent history
fixes #9228
=> fix(@wallet): Fix event for transaction

ui/app/AppLayouts/Browser/BrowserLayout.qml, ui/app/AppLayouts/Chat/controls/community/CommunityLogoPicker.qml, ui/app/AppLayouts/Onboarding/views/LoginView.qml, ui/app/AppLayouts/Profile/ProfileLayout.qml, ui/app/AppLayouts/Profile/views/AppearanceView.qml, ui/app/AppLayouts/Profile/views/CommunitiesView.qml, ui/app/AppLayouts/Profile/views/DevicesView.qml
Closes #8864
status app resolving QML errors/warnings
status app
=> fix(statusApp): resolving qml errors/warnings pt2

test/ui-test/testSuites/suite_communities/shared/scripts/community_names.py, test/ui-test/testSuites/suite_communities/tst_communityMessageFlows/test.feature, test/ui-test/testSuites/suite_messaging/shared/scripts/chat_names.py
=> test: re-add edit test as a community test

test/ui-test/testSuites/suite_communities/shared/scripts/community_names.py, test/ui-test/testSuites/suite_communities/tst_communityAdminFlows/test.feature, test/ui-test/testSuites/suite_communities/tst_communityFlows/test.feature, test/ui-test/testSuites/suite_communities/tst_communityMemberFlows/test.feature, test/ui-test/testSuites/suite_communities/tst_communityMessageFlows/test.feature, test/ui-test/testSuites/suite_messaging/shared/scripts/chat_names.py
=> test(community): re-add test that replies to another message

ci/Jenkinsfile.e2e, ci/Jenkinsfile.macos, scripts/macos_build_setup.sh, scripts/ubuntu_build_setup.sh
This needs to be synced with a Squish upgrade to match the QT version.
=> ci: update build setup scripts to Qt 5.15.2

ui/StatusQ/src/StatusQ/Components/StatusMessage.qml, ui/imports/shared/views/chat/MessageView.qml
Status Message: message height is broken when links posted
Status Message
https://user-images.githubusercontent.com/31625338/214853757-2ff006b8-744c-4f2a-9e11-4110dfdff8f6.mov
=> fix(StatusMessage): stickers were not aligned correctly

ui/StatusQ/src/StatusQ/Components/StatusChatList.qml
Part of #8642 
Fixing qml Connections warning
Status category "More" popup
=> Chore(Qt5.15): Fix qml warning

ui/imports/shared/status/StatusChatImageLoader.qml, ui/imports/shared/views/chat/LinksMessageView.qml, ui/imports/shared/views/chat/MessageContextMenuView.qml
Closes #7518
Status Message GIFs updated behavior as per designs
Status Message GIFs
https://user-images.githubusercontent.com/31625338/216101879-804b2f81-30aa-4c53-8783-73c3004cfa60.mov
=> fix(StatusMessage): updated GIFs behavior

src/app/modules/main/wallet_section/transactions/controller.nim, ui/imports/shared/views/HistoryView.qml
fixes #9320
When history is ready, we then need to load the tx and then we can say it is not loading
=> fix(@wallet): no tx found

src/app/modules/main/wallet_section/collectibles/current_collectible/view.nim, ui/app/AppLayouts/Wallet/controls/CollectibleDetailsHeader.qml, ui/app/AppLayouts/Wallet/views/collectibles/CollectibleDetailView.qml
=> fix(@wallet): display network short name for collectible

ui/StatusQ/src/StatusQ/Core/StatusScrollView.qml, ui/app/AppLayouts/Chat/controls/community/CommunityLogoPicker.qml, ui/app/AppLayouts/Chat/panels/communities/CommunityEditSettingsPanel.qml, ui/app/AppLayouts/Chat/panels/communities/CommunityOverviewSettingsPanel.qml, ui/app/AppLayouts/CommunitiesPortal/panels/CommunityColorPanel.qml, ui/app/AppLayouts/CommunitiesPortal/popups/CreateCommunityPopup.qml, ui/app/AppLayouts/Profile/views/NotificationsView.qml, ui/app/AppLayouts/Wallet/popups/AddAccountModal.qml, ui/app/AppLayouts/Wallet/views/CollectiblesView.qml
Relates to https://github.com/status-im/status-desktop/issues/8864 fixes
Closes https://github.com/status-im/status-desktop/issues/9326
status app resolving QML errors/warnings
status app
=> fix(statusApp): resolving qml errors/warnings pt2.1

test/ui-test/src/screens/StatusChatScreen.py, test/ui-test/src/screens/StatusMainScreen.py, test/ui-test/testSuites/global_shared/scripts/global_names.py, test/ui-test/testSuites/suite_communities/shared/scripts/community_names.py, test/ui-test/testSuites/suite_communities/tst_communityMessageFlows/test.feature, test/ui-test/testSuites/suite_messaging/shared/scripts/chat_names.py
Fixes #9240 #9241 #9242 #9243 #9239
=> test(community): re-add a couple of chat tests in community tests

test/ui-test/src/screens/StatusChatScreen.py, test/ui-test/testSuites/global_shared/scripts/global_names.py, test/ui-test/testSuites/suite_communities/tst_communityMessageFlows/test.feature, test/ui-test/testSuites/suite_messaging/shared/scripts/chat_names.py
=> test(community): re-add test that does a mention

test/ui-test/testSuites/suite_communities/shared/scripts/community_names.py, test/ui-test/testSuites/suite_communities/tst_communityMessageFlows/test.feature, test/ui-test/testSuites/suite_messaging/shared/scripts/chat_names.py
=> test(community): re-add emoji tests

test/ui-test/testSuites/suite_communities/shared/scripts/community_names.py, test/ui-test/testSuites/suite_communities/tst_communityMessageFlows/test.feature, test/ui-test/testSuites/suite_messaging/shared/scripts/chat_names.py
=> test(community): re-add sticker test as community test

test/ui-test/src/screens/StatusChatScreen.py, test/ui-test/src/screens/StatusCommunityScreen.py, test/ui-test/src/screens/StatusMainScreen.py, test/ui-test/testSuites/global_shared/scripts/global_names.py, test/ui-test/testSuites/suite_communities/shared/scripts/community_names.py, test/ui-test/testSuites/suite_communities/shared/steps/communitySteps.py, test/ui-test/testSuites/suite_communities/tst_communityMessageFlows/test.feature, test/ui-test/testSuites/suite_messaging/shared/scripts/chat_names.py, test/ui-test/testSuites/suite_messaging/shared/steps/chatSteps.py
=> test(community): re-add mark as read test in community tests

test/ui-test/testSuites/suite_settings/tst_userIdentity/test.feature, test/ui-test/testSuites/suite_wallet/tst_wallet/test.feature
It should make all the tests green.
I opened issues to fix the tests later: #9498 and #9499
=> chore: add mayfail to tests that fail on CI

src/app_service/service/transaction/service.nim
fixes #8813
1. Simplifies the breaks down the transfer function and
2. For multi tx the corresponding amount to each chain is sent with the request
Wallet
=> fix(@deaktop/wallet): Fix transfer function amount

src/app/modules/main/wallet_section/buy_sell_crypto/controller.nim, src/app/modules/main/wallet_section/buy_sell_crypto/io_interface.nim, src/app/modules/main/wallet_section/buy_sell_crypto/module.nim, src/app_service/service/token/service.nim, src/app_service/service/transaction/async_tasks.nim, src/app_service/service/transaction/service.nim, src/app_service/service/wallet_account/service.nim
@jrainville the only query left is getEthereumChains which is used by browser and not maintained
fixes #9491
=> feat(@wallet): move crypto on ramp async

src/app/modules/main/chat_section/chat_content/messages/module.nim
=> fix(Chat): Continue on deleted message in chat module

storybook/PagesModel.qml, storybook/pages/CommunityTokenPermissionsPopupPage.qml, storybook/pages/JoinCommunityPermissionsEditor.qml, storybook/pages/JoinCommunityViewPage.qml, storybook/pages/JoinPermissionsOverlayPanelPage.qml, ui/app/AppLayouts/Chat/panels/communities/JoinPermissionsOverlayPanel.qml, ui/app/AppLayouts/Chat/popups/community/CommunityTokenPermissionsPopup.qml, ui/app/AppLayouts/Chat/popups/community/qmldir, ui/app/AppLayouts/Chat/stores/CommunitiesStore.qml, ui/app/AppLayouts/Chat/views/communities/JoinCommunityView.qml
Closes #9433
- Created new dialog that shows community token permissions.
- Created storybook page for that.
- Some model properties renamed.
`JoinCommunityView` and `JoinPermissionsOverlayPanel`
New popup `CommunityTokenPermissionsPopup` --> **It can only be tested in storybook.**
https://user-images.githubusercontent.com/97019400/218984768-239bc241-6272-47e3-a44d-159e3448a247.mov
=> feat(TokensPermissionsPoupup): Created new popup

ui/StatusQ/README.md, ui/StatusQ/sandbox/scripts/build, ui/StatusQ/scripts/build
fixed Sandbox's build script
- StatusQ Sandbox
=> fix(StatusQ/Sandbox): move and update build script

ui/app/AppLayouts/Browser/popups/BrowserWalletMenu.qml, ui/app/AppLayouts/Wallet/controls/SavedAddressesDelegate.qml, ui/app/AppLayouts/Wallet/popups/ReceiveModal.qml, ui/app/AppLayouts/Wallet/views/TransactionDetailView.qml, ui/imports/shared/controls/CopyToClipBoardButton.qml, ui/imports/shared/controls/InformationTile.qml, ui/imports/shared/controls/chat/ProfileHeader.qml, ui/imports/shared/status/StatusExpandableAddress.qml, ui/imports/shared/status/StatusSectionDescItem.qml
=> fix(@wallet): trim tx data

ui/app/AppLayouts/Chat/controls/community/InDropdown.qml, ui/app/AppLayouts/Chat/panels/communities/CommunityPermissionsSettingsPanel.qml, ui/app/AppLayouts/Chat/views/communities/CommunityPermissionsView.qml, ui/imports/shared/popups/OutgoingContactVerificationRequestPopup.qml
community permissions, "InDropDown" fixed dropdown height
community permissions, "InDropDown"
https://user-images.githubusercontent.com/31625338/218122102-ff6dbe0d-edcc-40fa-b9df-af22d90ad026.mov
=> fix(communitypermissions): fixed dropdown height

src/backend/contacts.nim
Close #9625
Fix for changed payload filed
Contants
=> fix(Contancts): Fix retractContactRequest rpc payload

test/ui-test/src/utils/FileManager.py, test/ui-test/testSuites/suite_messaging/tst_OneToOneChatFlow/test.feature
Closes #8347
- Added if path exist check in `FileManager.py`
- Disabled some code that is causing CI failures in `suite_messaging/tst_OneToOneChatFlow`. Task to resolve it: https://github.com/status-im/status-desktop/issues/9335
CI / e2e tests
=> test(issue 8347): Add checker in `FileManager.py/clear_directory` to avoid crash when file path does not exist

Makefile, ci/Jenkinsfile.combined, ci/Jenkinsfile.e2e, ci/Jenkinsfile.imports, ci/Jenkinsfile.linux, ci/Jenkinsfile.linux-cpp, ci/Jenkinsfile.macos, ci/Jenkinsfile.macos-cpp.todo, ci/Jenkinsfile.tests-nim, ci/Jenkinsfile.windows, ci/Jenkinsfile.windows-cpp.todo, src/app_service/common/network_constants.nim, src/app_service/service/network/dto.nim, src/app_service/service/network/service.nim, src/backend/backend.nim
Status-go: https://github.com/status-im/status-go/pull/3204
fixes #9137
=> feat(@wallet): add pokt network + fallbak

ui/imports/shared/popups/keycard/helpers/KeyPairUnknownItem.qml
=> feat(keycard): remove balance from factory reset flow if user is not logged in

ui/imports/shared/popups/SendModal.qml
=> fix(@wallet): send zero tx

ui/app/mainui/activitycenter/popups/ActivityCenterPopup.qml
=> fix(ActivityCenter): fix missing membership notifications

src/app_service/common/network_constants.nim, src/app_service/service/accounts/service.nim
Improved readability by moving constants to NODE_CONFIG
=> chore(node_config): move constants to NODE_CONFIG

.gitmodules
This PR upgrades a number of libraries as well as nim itself, to address security issues and crashes that we've worked to solve over the past few months on the nimbus-eth2 side leading up to its 1.6 migration - they include changes that are safe to use in both 1.2 and 1.6 without requiring 1.6, making the code compatible with both versions.
In particular, 1.6 becomes more strict in several ways including exception handling, style and certain langauge constructs related to memory safety - as a result, we've cleaned up said libraries and improved their stability overall, including fixing several crashes.
* nim 1.2.18 - this is the last release in the 1.2 series we produced together with upstream based on nimbus' needs - between the version Desktop is using today and v1.2.18, changes are …
=> Nim library upgrades, pt1

src/app/modules/main/activity_center/controller.nim, src/app/modules/main/activity_center/io_interface.nim, src/app/modules/main/activity_center/module.nim, src/app/modules/main/activity_center/view.nim, src/app_service/service/activity_center/async_tasks.nim, src/app_service/service/activity_center/service.nim, src/backend/backend.nim, ui/app/mainui/activitycenter/panels/ActivityCenterPopupTopBarPanel.qml, ui/app/mainui/activitycenter/popups/ActivityCenterPopup.qml, ui/app/mainui/activitycenter/stores/ActivityCenterStore.qml
Switch on new endpoints : https://github.com/status-im/status-go/pull/3237
=> feat(ActivityCenter): Support status-go PR with endpoints refactor

test/ui-test/src/screens/StatusCommunityScreen.py, test/ui-test/testSuites/global_shared/scripts/global_names.py, test/ui-test/testSuites/suite_communities/shared/scripts/community_names.py, test/ui-test/testSuites/suite_communities/tst_communityFlows/test.feature, ui/StatusQ/src/StatusQ/Components/StatusChatList.qml, ui/StatusQ/src/StatusQ/Popups/statusModal/StatusModalHeader.qml, ui/app/AppLayouts/Chat/popups/community/CreateCategoryPopup.qml
I don't think there was an issue for that, but the create category test was very broken. 
I'll fix the other category tests later, they should hopefully be very simple to fix.
=> fix(test): fix create category test

src/app/boot/app_controller.nim, src/app/modules/main/communities/minting/controller.nim, src/app/modules/main/communities/minting/io_interface.nim, src/app/modules/main/communities/minting/module.nim, src/app/modules/main/communities/minting/view.nim, src/app_service/service/community_tokens/service.nim, src/backend/community_tokens.nim
Handle chainId during contract deployment process.
Related status-go pr: https://github.com/status-im/status-go/pull/3253
=> 9725 handle chainId

ui/app/AppLayouts/Chat/popups/community/CreateChannelPopup.qml, ui/imports/utils/Utils.qml
Allow capitals in the channel name
Fixes: #9689
Channel name
=> fix(@desktop/channels): allow capitals in the channel name

src/app/modules/main/communities/minting/models/token_model.nim, src/app/modules/main/networks/model.nim, src/app_service/service/community_tokens/service.nim, ui/app/AppLayouts/Chat/panels/communities/CommunityMintTokensSettingsPanel.qml, ui/app/AppLayouts/Chat/stores/CommunitiesStore.qml
Fix #9781
Expose missing fields
=> fix(@desktop/communities): Fix community tokens model

ui/imports/shared/status/StatusChatInput.qml
- Fixed reply message is gone when adding image
- Fixed pressing up arrow key when editing loses the cursor
Closes #9419
Closes #9139
StatusChatInput various fixes
=> [StatusChatInput]: fixed focus and reply component lost 

ui/app/AppLayouts/Wallet/popups/AddEditSavedAddressPopup.qml
=> fix(@wallet): saved address form typo

ui/app/AppLayouts/Wallet/popups/AddEditSavedAddressPopup.qml
=> fix(@wallet): close save address modal policy

ui/StatusQ/src/StatusQ/Components/StatusChatList.qml
Part of #3364
StatusChatList: fixed dnd uncategorized channels
StatusChatList
https://user-images.githubusercontent.com/31625338/224380269-81fddf04-1af0-42ac-a570-9fa061977ae4.mov
=> fix(StatusChatList): fixed dnd uncategorized channels

src/app/modules/main/wallet_section/saved_addresses/item.nim, src/app/modules/main/wallet_section/transactions/controller.nim, src/app/modules/main/wallet_section/transactions/module.nim, src/app/modules/main/wallet_section/transactions/multi_transaction_item.nim, src/app/modules/main/wallet_section/transactions/utils.nim, src/app_service/service/transaction/dto.nim, src/app_service/service/transaction/service.nim, src/backend/transactions.nim
Prepare the business logic for the upcoming multi-transaction UX changes.
Bump the status-go HEAD with the corresponding changes [#3257](https://github.com/status-im/status-go/pull/3257).
=> feat(wallet) fetch multi-transaction information

ui/app/AppLayouts/Profile/views/NotificationsView.qml
Change the text from "Allow Notifications" to "Allow Notification Bubbles" to better describe the intent
Fixes #9882
=> fix: Setting / Notification & Sounds - Copy update

ui/app/AppLayouts/Chat/views/MembersSelectorView.qml
Fixes: #9485
Blocking duplications of contact requests from new chat window.
[UI Part issue](https://github.com/status-im/status-desktop/issues/9736)
CreateChatView
=> fix(contacts): Block unlimited counts of request contacts from create  chat view

.gitmodules
This is part 2 of the nim library updates targeting networking and ETH libraries:
* bearssl: upstream security updates, refactoring
* chronos: significant stability updates across the board - ie better connection management, async fixes, updates, refactoring etc
* eth: updates across the board, including EIP support, discv5, etc
* http-utils: fixes
* json-rpc: replaced websocket engine with in-house nim-websock (vs news which is no longer supported)
* libp2p: lots of updates, but not relevant to status-desktop as of yet
* web3: new API and conformance updates based on execution API spec
* semver: crash fix, branch name
* news: removed in favour of nim-websock
=> Nim library updates, pt 2

Makefile, scripts/fetch-brew-bottle.sh, src/nim_status_client.nim
Fixing: #9741
Enable arm compilation for M1 Macs.
The Makefile will configure the build based on Qt's architecture. If the `PATH` env variable points to a `qmake` executable compiled for `arm64` it will compile `nim_status_client` for arm. Same for `x86_64`.
There is a bug either in golang or Qt where status-go is freezing after the Qt's main loop is started. It seems to be related to how Qt handled SVG files because the app can be started if we don't use any SVG image.
The same issue is reported here: https://github.com/golang/go/issues/48437.
The other GitHub project that reported the same issue found a workaround for it. This involves adding a dummy signaltstack before starting Qt's main loop. https://github.com/obsproject/obs-studio/discussions/7795. The golang devs say that go will …
=> Enable arm compilation for M1 Macs

src/app/modules/main/communities/tokens/module.nim, src/app_service/service/community_tokens/service.nim
Convert image to base64 format before saving in database and publishing to waku
=> 9866 image to base64

src/app/core/eventemitter.nim, src/app/core/unique_event_emitter.nim, src/app/modules/main/chat_section/chat_content/controller.nim, src/app/modules/main/chat_section/chat_content/input_area/controller.nim, src/app/modules/main/chat_section/chat_content/messages/controller.nim, src/app/modules/main/chat_section/chat_content/messages/module.nim, src/app/modules/main/chat_section/chat_content/module.nim, src/app/modules/main/chat_section/chat_content/users/controller.nim, src/app/modules/main/chat_section/chat_content/users/module.nim, src/app/modules/main/chat_section/controller.nim, src/app/modules/main/chat_section/io_interface.nim, src/app/modules/main/chat_section/module.nim, src/app/modules/main/module.nim, src/app_service/service/community/service.nim
Clean up chat_section nim resource on leaving the community and disconnect from the events
Fixes: #9376 
Joining, leaving the community
=> fix(@desktop/communities): remove chat_section data if user left the community

src/app/modules/main/chat_section/module.nim
=> fix(chat_section): fix link activation for channels inside categories

src/app/modules/main/wallet_section/transactions/controller.nim, src/app/modules/main/wallet_section/transactions/io_interface.nim, src/app/modules/main/wallet_section/transactions/module.nim, src/app/modules/main/wallet_section/transactions/view.nim
=> fix(@wallet): inifinite load tx

src/nim_status_client.nim
(new regression in 0.10)
fix a fatal typo when refactoring to use `main_constants.IS_MACOS` :)
Fixes #9791
Fix app icon under Windows
=> fix: Status app and taskbar icon on Windows

src/app/modules/startup/internal/sync_device_with_sync_code.nim
Fixes https://github.com/status-im/status-desktop/issues/9893
=> fix(Syncing): Added back state for sync_device_result state

ui/app/AppLayouts/Chat/ChatLayout.qml
Closing #9932 
Enable activity centre and start chat button functionality.
Join Community View
https://user-images.githubusercontent.com/47811206/226602539-c0d5a5f7-5721-42a6-8702-8acf139c81f3.mov
=> fix(JoinCommunityView): Enable activity centre and start chat button

storybook/PagesModel.qml, storybook/figma.json, storybook/pages/SignMintTokenTransactionPopupPage.qml, ui/StatusQ/src/StatusQ/Popups/Dialog/StatusDialogFooter.qml, ui/app/AppLayouts/Chat/panels/communities/CommunityMintTokensSettingsPanel.qml, ui/app/AppLayouts/Chat/popups/community/SignMintTokenTransactionPopup.qml, ui/app/AppLayouts/Chat/popups/community/qmldir, ui/app/AppLayouts/Chat/stores/CommunityTokensStore.qml, ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml, ui/app/AppLayouts/Chat/views/communities/CommunityMintedTokensView.qml
Closes #9802
- New sign mint token transactions popup created.
- Added transactions popup in minting flow.
- Added popup in storybook.
- Fixed self destruct property bug.
**NOTE: Fee calculation is mocked data. It needs backend integration.**
**- Storybook:**
https://user-images.githubusercontent.com/97019400/227220084-2404e795-3424-4ca9-af49-5840bbe91a91.mov
**- App:**
https://user-images.githubusercontent.com/97019400/227220106-e58eb9e6-a0a9-4430-b1df-582604c37c55.mov
https://user-images.githubusercontent.com/97019400/227220138-d0216c46-7d0b-4e5a-9b10-0174c814a1f2.mov
=> feat(Community Mint Collectibles): Add sign transaction dialog in minting creation flow

src/app_service/service/chat/service.nim
=> fix(group): fix editing group image on Windows

src/app/modules/main/wallet_section/add_account/module.nim, src/app/modules/shared/keypairs.nim, src/app/modules/shared_modules/keycard_popup/module.nim, ui/app/AppLayouts/Wallet/addaccount/panels/AddressWithAddressDetails.qml, ui/app/AppLayouts/Wallet/addaccount/states/EnterPrivateKey.qml, ui/app/AppLayouts/Wallet/addaccount/states/Main.qml, ui/imports/utils/Constants.qml
=> feat(@desktop/wallet): new add account modal - amends

src/app/boot/app_controller.nim, src/app/modules/main/communities/module.nim, src/app/modules/main/communities/tokens/controller.nim, src/app/modules/main/communities/tokens/io_interface.nim, src/app/modules/main/communities/tokens/module.nim, src/app/modules/main/communities/tokens/view.nim, src/app/modules/main/module.nim, src/app_service/service/community_tokens/service.nim, ui/app/AppLayouts/Chat/panels/communities/CommunityMintTokensSettingsPanel.qml, ui/app/AppLayouts/Chat/stores/CommunityTokensStore.qml, ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
This is a quick pr to show transaction fees for deployment.
TODOs for next milestone:
- make a call async
- UI should decide about formatting, right now Nim returns formatted string
=> fix(@desktop/communities): Computing fees in ETH and USD for Sign Transaction dialog

src/app/modules/main/communities/tokens/controller.nim, src/app/modules/main/communities/tokens/io_interface.nim, src/app/modules/main/communities/tokens/module.nim, src/app/modules/main/communities/tokens/view.nim, src/app_service/service/community_tokens/service.nim, src/backend/community_tokens.nim, test/ui-test/testSuites/suite_wallet/tst_transaction/test.feature, ui/app/AppLayouts/Chat/panels/communities/CommunityAirdropsSettingsPanel.qml, ui/app/AppLayouts/Chat/stores/CommunityTokensStore.qml, ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml, ui/app/AppLayouts/Chat/views/communities/CommunityNewAirdropView.qml
Handling airdrop community tokens functionality.
Requires https://github.com/status-im/status-go/pull/3320
=> 9783 mint to

src/app_service/service/community/service.nim, test/ui-test/src/screens/StatusCommunityScreen.py, test/ui-test/testSuites/suite_communities/tst_communityFlows/test.feature
Fixes the tests and removes the mayfail tags
=> fix(community-tests): fix edit and delete category tests

ui/StatusQ/src/StatusQ/Components/StatusMessage.qml, ui/StatusQ/src/StatusQ/Popups/StatusMenu.qml, ui/app/AppLayouts/Chat/popups/PinnedMessagesPopup.qml, ui/app/AppLayouts/Chat/views/ChatColumnView.qml, ui/app/AppLayouts/Chat/views/ChatContentView.qml, ui/app/AppLayouts/Chat/views/ChatHeaderContentView.qml, ui/app/AppLayouts/Chat/views/ChatMessagesView.qml, ui/app/mainui/Popups.qml, ui/imports/shared/status/StatusChatInput.qml, ui/imports/shared/views/chat/MessageContextMenuView.qml, ui/imports/shared/views/chat/MessageView.qml, ui/imports/utils/Global.qml
Close #9899
Disable sending messages for non contacts and remove text in chat input on chat gets disabled
Chat
https://user-images.githubusercontent.com/2522130/225246183-3b8cc4ce-b1cd-48ab-be90-5e995f31ea9d.mov
=> feat(Chat): Disable sending messages for non contacts

src/app_service/service/settings/service.nim, src/app_service/service/token/service.nim, ui/StatusQ/src/StatusQ/Controls/StatusAccountSelector.qml, ui/imports/shared/controls/AssetAndAmountInput.qml, ui/imports/shared/panels/StatusAssetSelector.qml, ui/imports/shared/views/TransactionPreview.qml, ui/imports/shared/views/chat/TransactionBubbleView.qml
fixes #9201
Do not change value of symbol as they should arrive already formatted
=> feat(@wallet): do not change value of symbol

ui/imports/shared/views/chat/InvitationBubbleView.qml
Closing https://github.com/status-im/status-desktop/issues/10057
Community invitation bubble
=> fix(LinkPreviews): Fixing implicitHeight binding loop

ui/StatusQ/src/StatusQ/Components/private/statusMessage/StatusEditMessage.qml, ui/imports/shared/views/chat/MessageView.qml
=> fix(edit): fix edit message not sending mentions correctly

src/app/modules/main/chat_section/chat_content/messages/controller.nim, src/app/modules/main/chat_section/chat_content/messages/module.nim, src/app/modules/main/chat_section/controller.nim, src/app/modules/main/chat_section/io_interface.nim, src/app/modules/main/chat_section/module.nim, src/app/modules/main/io_interface.nim, src/app/modules/main/module.nim, src/app/modules/shared_models/section_model.nim, src/app_service/service/message/service.nim
Fixes #10077
The fix itself is in the status-go PR.
The desktop changes are just to clean up the old code that no longer worked
status-go PR https://github.com/status-im/status-go/pull/3365
=> fix(edit): fix mentions in edits not counting towards the badge

src/app/modules/main/communities/models/curated_community_item.nim, src/app/modules/main/communities/models/curated_community_model.nim, src/app/modules/main/communities/module.nim, src/app_service/service/community/dto/community.nim, ui/app/AppLayouts/CommunitiesPortal/views/CommunitiesGridView.qml
=> feat(communities): extend community with active members count

src/app/modules/main/chat_section/chat_content/messages/view.nim
Skip edit mode for image messages
Input area
=> fix(edit-message): Blocks edit function for image messages

ui/main.qml
those evil typos :)
Fixes #10039
main
=> hotfix: unbreak showing encryption splash screen

src/app_service/service/message/service.nim
Fixes #10108
cherry pick of https://github.com/status-im/status-desktop/pull/10110
=> [CHERRY-PICK] fix(edit): don't send new message event on edits

src/app/modules/shared_modules/keycard_popup/internal/biometrics_ready_to_sign_state.nim, src/app/modules/shared_modules/keycard_popup/module.nim, src/app/modules/startup/controller.nim, src/app/modules/startup/module.nim, ui/app/AppLayouts/Onboarding/views/AllowNotificationsView.qml, ui/app/AppLayouts/Onboarding/views/InsertDetailsView.qml, ui/app/AppLayouts/Onboarding/views/KeysMainView.qml, ui/app/AppLayouts/Onboarding/views/TouchIDAuthView.qml, ui/app/AppLayouts/Onboarding/views/WelcomeView.qml, ui/imports/shared/popups/keycard/states/EnterPassword.qml
cherry-pick https://github.com/status-im/status-desktop/pull/10132
=> Cherry pick issue 10132

src/app/modules/main/wallet_section/add_account/module.nim, ui/app/AppLayouts/Wallet/addaccount/stores/AddAccountStore.qml
=> fix(@desktop/wallet): derivation path is not pre-selected by default when importing account in wallet

src/app/modules/startup/controller.nim
=> fix(@desktop/onboarding): if you fail your login once, it doesn't work after ever

src/app/boot/app_controller.nim, src/app/modules/main/communities/tokens/controller.nim, src/app/modules/main/communities/tokens/io_interface.nim, src/app/modules/main/communities/tokens/module.nim, src/app/modules/main/communities/tokens/view.nim, src/app_service/service/community_tokens/async_tasks.nim, src/app_service/service/community_tokens/service.nim, src/backend/community_tokens.nim, ui/app/AppLayouts/Chat/panels/communities/CommunityMintTokensSettingsPanel.qml, ui/app/AppLayouts/Chat/popups/community/SignMintTokenTransactionPopup.qml, ui/app/AppLayouts/Chat/stores/CommunityTokensStore.qml, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml, ui/imports/utils/Constants.qml
Compute deployment fees in async way.
Improve showing errors when estimating fees.
Related status-go pr: https://github.com/status-im/status-go/pull/3369
Minting token
https://user-images.githubusercontent.com/61889657/229502106-106158e2-e456-48f2-b992-27caad6add6a.mov
=> 10035 impr sign trans

src/app_service/service/message/service.nim
=> fix(@desktop/channels): chat/channel messages loading state is not disappearing

ui/app/AppLayouts/Chat/panels/communities/CommunityPermissionsSettingsPanel.qml
It's integral part of
https://github.com/status-im/status-desktop/pull/10166 but not pushed together by mistake.
=> fix(CommunityPermissionsSettingsPanel): fixing duplicates detection and permission updating

ui/app/AppLayouts/CommunitiesPortal/panels/CommunityColorPanel.qml, ui/app/AppLayouts/CommunitiesPortal/panels/CommunityTagsPanel.qml
backport https://github.com/status-im/status-desktop/pull/10145 into 0.11.x branch
Fixes: https://github.com/status-im/status-desktop/issues/10181
=> cherry-pick: fix(CommunityTagsPanel): unbreak the tags panel

src/app/modules/main/profile_section/contacts/controller.nim, src/app/modules/main/profile_section/contacts/io_interface.nim, src/app/modules/main/profile_section/contacts/module.nim, src/app/modules/main/profile_section/contacts/view.nim, src/app_service/service/contacts/async_tasks.nim, src/app_service/service/contacts/service.nim, src/backend/contacts.nim, ui/app/AppLayouts/Profile/stores/ContactsStore.qml, ui/app/mainui/Popups.qml, ui/imports/shared/controls/chat/ProfileHeader.qml, ui/imports/shared/controls/chat/UserImage.qml, ui/imports/shared/popups/SendContactRequestModal.qml
Fixes https://github.com/status-im/status-desktop/issues/8924
Requres:
- https://github.com/status-im/status-go/pull/3376
https://user-images.githubusercontent.com/25482501/229910831-bfd41df6-3286-49dd-8bee-8921fe76cb49.mov
=> fix(SendContactRequestModal): Contact info request and loading UI

ui/imports/shared/popups/AccountsModalHeader.qml, ui/imports/shared/popups/SendModal.qml, ui/imports/shared/stores/NetworkConnectionStore.qml, ui/imports/shared/stores/TransactionStore.qml, ui/imports/shared/views/TabAddressSelectorView.qml, ui/imports/shared/views/TokenListView.qml
fix(@desktop/wallet): Wallet: Active account changes when clicking send transaction from a watched account
fixes #9815
Separated selected account in sendModal and assetsViews. 
Also checked for modelReset and reintroducing any crashes that were seen before.
SendModal
Uploading Screen Recording 2023-04-06 at 3.01.40 PM.mov…
=> fix(@desktop/wallet): Wallet: Active account changes when clicking send transaction from a watched account

src/app/modules/main/activity_center/module.nim
=> fix(@desktop/activityCenter): jump to message by clicking on notification

src/app/modules/shared_models/message_model.nim
=> fix(Albums): Fix extra count of messages for image albums

ci/Jenkinsfile.linux, ci/Jenkinsfile.windows
=> chore(windows/ci): move env var up in the list to be like other files

ui/StatusQ/src/StatusQ/Components/StatusMessage.qml
=> fix(images): Wrap text in image message

src/app/modules/main/chat_section/chat_content/messages/controller.nim, src/app/modules/main/chat_section/chat_content/messages/io_interface.nim, src/app/modules/main/chat_section/chat_content/messages/module.nim, src/app_service/service/message/service.nim, ui/app/AppLayouts/Chat/stores/MessageStore.qml, ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
cherry pick of: https://github.com/status-im/status-desktop/pull/10151
=> cherry-pick: "Fix/10150/chat marked as read without seeing all messages"

src/app/modules/main/communities/view.nim
=> fix(Communities): Emit the signal about community tags changes

src/app/modules/main/chat_section/chat_content/messages/io_interface.nim, src/app/modules/main/chat_section/chat_content/messages/module.nim, src/app/modules/main/chat_section/chat_content/messages/view.nim, src/app/modules/main/chat_section/chat_content/module.nim, ui/app/AppLayouts/Chat/views/ChatMessagesView.qml, ui/imports/utils/Backpressure/Backpressure.qml
cherry-picked: https://github.com/status-im/status-desktop/pull/10222
=> cherry-pick: "Fix/10197/opening chat with unread msgs goes to bottom"

ui/app/AppLayouts/Chat/views/communities/CommunityNewCollectibleView.qml, ui/imports/utils/Constants.qml
Closing: https://github.com/status-im/status-desktop/issues/9850
Password: 7 characters max, ascii printable characters
Name and description: ascii characters
https://user-images.githubusercontent.com/47811206/229907190-02b23d94-4a4f-487e-afe7-cbb9661a4753.mov
=> fix(MintTokensPanel): Update input fields validation

src/app/modules/main/wallet_section/transactions/controller.nim, src/app/modules/main/wallet_section/transactions/io_interface.nim, src/app/modules/main/wallet_section/transactions/item.nim, src/app/modules/main/wallet_section/transactions/model.nim, src/app/modules/main/wallet_section/transactions/module.nim, src/app/modules/main/wallet_section/transactions/view.nim, src/app_service/service/transaction/service.nim, ui/imports/shared/views/HistoryView.qml
fixes #9593
Make activity responsive to network selection
=> feat(@wallet): make activity respect networks selector

storybook/PagesModel.qml, storybook/figma.json, storybook/pages/ChatAnchorButtonsPanelPage.qml, ui/StatusQ/src/StatusQ/Controls/StatusBaseButton.qml, ui/app/AppLayouts/Chat/panels/ChatAnchorButtonsPanel.qml, ui/app/AppLayouts/Chat/panels/qmldir
iterates: #9069
none (new component)
https://user-images.githubusercontent.com/33099791/230660847-1479452f-b92a-4d28-800a-41509f6a3b45.mp4
=> feat(storybook): add ChatAnchorButtonsPanel

app/README.md
=> Fix: minor typo

scripts/localfleet/README.md, scripts/localfleet/docker-compose-host.yml, scripts/localfleet/fleet.go.template, scripts/localfleet/fleets.json.template, scripts/localfleet/gen-config.sh, scripts/localfleet/main.go
Allows creating local test fleets with custom number of static nodes and mailserver nodes.
This has been only tested on linux
Requires
- https://github.com/status-im/status-go/pull/2821
Fixes: #7068
=> chore: script for creating local test fleet

scripts/notarize-macos-pkg.sh
Otherwise we get failures like:
```
parse error: Invalid numeric literal at line 1, column 11
```
Which results in `stderr` logs being included in `$OUT`.
=> ci: fix handling of stdout in MacOS notarization

src/app_service/service/community_tokens/airdrop_details.nim, src/app_service/service/community_tokens/dto/community_token.nim, src/app_service/service/community_tokens/service.nim, src/app_service/service/transaction/dto.nim, src/backend/community_tokens.nim
Tracking airdrop transaction and updating database only if transaction is successful.
Related status-go pr: https://github.com/status-im/status-go/pull/3374
=> 10161 track minting tx

ui/app/AppLayouts/Wallet/addaccount/states/Main.qml, ui/app/AppLayouts/Wallet/addaccount/stores/AddAccountStore.qml, ui/imports/utils/Constants.qml
=> fix(@desktop/wallet): account name character limit not enforced

src/app/modules/main/wallet_section/io_interface.nim, src/app/modules/main/wallet_section/module.nim, src/app/modules/main/wallet_section/overview/controller.nim, src/app/modules/main/wallet_section/overview/io_interface.nim, src/app/modules/main/wallet_section/overview/item.nim, src/app/modules/main/wallet_section/overview/module.nim, src/app/modules/main/wallet_section/overview/view.nim, ui/app/AppLayouts/Browser/popups/BrowserWalletMenu.qml, ui/app/AppLayouts/Wallet/panels/WalletHeader.qml, ui/app/AppLayouts/Wallet/stores/RootStore.qml, ui/app/AppLayouts/Wallet/views/RightTabView.qml, ui/imports/shared/views/HistoryView.qml
Create overview module disconnected from assets module
=> feat(@wallet): add overview module

src/app/modules/main/communities/module.nim, src/app/modules/main/communities/tokens/controller.nim, src/app/modules/main/communities/tokens/io_interface.nim, src/app/modules/main/communities/tokens/module.nim, src/app/modules/main/communities/tokens/view.nim, src/app/modules/main/controller.nim, src/app/modules/main/module.nim, src/app_service/service/community_tokens/service.nim, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Chat/stores/qmldir, ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml, ui/app/AppLayouts/Chat/views/communities/CommunityCollectibleView.qml, ui/app/AppLayouts/Chat/views/communities/CommunityMintedTokensView.qml, ui/app/mainui/AppMain.qml, ui/imports/shared/stores/CommunityTokensStore.qml, ui/imports/shared/stores/qmldir, ui/imports/utils/Constants.qml
Fix #9849
Show toast messages when:
- contract is deployed
- deployment is failed
- deployment is successful
=> fix(@desktop/communities): Displaying toast messages when minting

libs/ChatSection/include/Status/ChatSection/ChatSectionController.h, libs/ChatSection/qml/Status/ChatSection/ContentView.qml, libs/ChatSection/qml/Status/ChatSection/MainView.qml, libs/ChatSection/src/ChatSectionController.cpp, libs/StatusGoQt/CMakeLists.txt, libs/StatusGoQt/src/StatusGo/Messages/InputMessage.cpp, libs/StatusGoQt/src/StatusGo/Messages/InputMessage.h, libs/StatusGoQt/src/StatusGo/Messages/MessageDto.h, libs/StatusGoQt/src/StatusGo/Messages/MessagesApi.cpp, libs/StatusGoQt/src/StatusGo/Messages/MessagesApi.h, test/libs/StatusGoQt/test_messaging.cpp
Issue #7848
Add sendMessage() function.
https://user-images.githubusercontent.com/61889657/202766922-6e6529c2-8f21-4596-a420-502c51f74d0e.mov
=> fix(@desktop/cpp): Implement StatusGoQt::sendMessage() function

resources/node-config.json, src/app_service/common/network_constants.nim, src/app_service/service/accounts/service.nim, src/app_service/service/collectible/dto.nim, src/backend/collectibles.nim
Fixes #10290
status-go part: https://github.com/status-im/status-go/pull/3400
Support API to retrieve the list of addresses and balances of NFT owners from a certain contract address.
Infura [requires](https://docs.infura.io/infura/infura-expansion-apis/nft-api/authentication) the token key secret on top of the plain token key. They only have support for Ethereum (mainnet/testnet) and Arbitrum mainnet.
Alchemy requires a different API key per chain. The free plan lets us have up to 5 chains. We use Alchemy only for Arbitrum and Optimism (Mainnet/Goerli)
This is still not used anywhere in the app, but I tested it by calling the function with contracts from different networks:
```
echo "Eth Goerli"
try:
let response = collectibles.getCollectibleOwnersByContractAddress(5, …
```
=> feat: add api to get list of owners from a given nft contract

src/app/modules/main/profile_section/io_interface.nim, src/app/modules/main/profile_section/module.nim, src/app/modules/main/profile_section/view.nim, src/app/modules/main/profile_section/wallet/accounts/controller.nim, src/app/modules/main/profile_section/wallet/accounts/io_interface.nim, src/app/modules/main/profile_section/wallet/accounts/item.nim, src/app/modules/main/profile_section/wallet/accounts/model.nim, src/app/modules/main/profile_section/wallet/accounts/module.nim, src/app/modules/main/profile_section/wallet/accounts/related_account_item.nim, src/app/modules/main/profile_section/wallet/accounts/related_accounts_model.nim, src/app/modules/main/profile_section/wallet/accounts/utils.nim, src/app/modules/main/profile_section/wallet/accounts/view.nim, src/app/modules/main/profile_section/wallet/io_interface.nim, src/app/modules/main/profile_section/wallet/module.nim, src/app/modules/main/profile_section/wallet/networks/controller.nim, src/app/modules/main/profile_section/wallet/networks/io_interface.nim, src/app/modules/main/profile_section/wallet/networks/item.nim, src/app/modules/main/profile_section/wallet/networks/model.nim, src/app/modules/main/profile_section/wallet/networks/module.nim, src/app/modules/main/profile_section/wallet/networks/view.nim, ui/app/AppLayouts/Profile/popups/RenameAccontModal.qml, ui/app/AppLayouts/Profile/stores/ProfileSectionStore.qml, ui/app/AppLayouts/Profile/stores/WalletStore.qml, ui/app/AppLayouts/Profile/views/WalletView.qml, ui/app/AppLayouts/Profile/views/wallet/AccountView.qml, ui/app/AppLayouts/Profile/views/wallet/MainView.qml, ui/app/AppLayouts/Profile/views/wallet/NetworksView.qml
Separate wallet module from profile wallet module
1 - they caused us many conflict regarding current 
2 - better decoupling
3 - prepare work for wallet filter
part of #10247
=> feat:(@wallet): create wallet section in profile

ui/app/AppLayouts/Chat/panels/communities/CommunityAirdropsSettingsPanel.qml, ui/app/AppLayouts/Chat/panels/communities/CommunityMintTokensSettingsPanel.qml, ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml, ui/app/AppLayouts/Chat/views/communities/CommunityNewAirdropView.qml
Closes #10047
It enables navigation from mint token page to airdrop page selecting a specific collectible to be airdropped.
Community Settings / Mint token 
Community Settings / Airdrop token 
https://user-images.githubusercontent.com/97019400/232480998-b998d211-dd2e-4893-99a3-5d4e45bfe026.mov
=> feat(Mint/Airdrop Collectible): Implement `Airdrop` footer option

storybook/PagesModel.qml, storybook/figma.json, storybook/pages/MembersDropdownPage.qml, ui/app/AppLayouts/Chat/controls/community/HoldingsDropdown.qml, ui/app/AppLayouts/Chat/controls/community/MembersDropdown.qml, ui/app/AppLayouts/Chat/controls/community/qmldir, ui/imports/shared/views/PickedContacts.qml
Adds `MembersDropdown` component for further integration with `Airdrop`-related views.
Closes: #9800
`MembersDropdown.qml` (new component)
[Screencast from 17.04.2023 11:09:37.webm](https://user-images.githubusercontent.com/20650004/232449273-b17a0f0c-18a7-4e16-9440-80e162010e98.webm)
=> feat(Community/Airdrop): MembersDropdown

src/app/modules/main/chat_section/io_interface.nim, src/app/modules/main/controller.nim, src/app/modules/main/io_interface.nim, src/app/modules/main/module.nim, src/app/modules/shared_models/section_model.nim, ui/app/mainui/AppMain.qml
Closes #9694
StatusCommunity menu added "Mute" button
StatusCommunity menu
https://user-images.githubusercontent.com/31625338/233683714-7c33de5d-2945-4f9e-87d7-7e355a5945e2.mov
=> fix(StatusCommunityMenu): Added mute button

src/app_service/service/saved_address/dto.nim, src/app_service/service/saved_address/service.nim, ui/app/AppLayouts/Wallet/views/SavedAddressesView.qml
fixes #9772
status-go pr: https://github.com/status-im/status-go/pull/3265
=> feat(@wallet): sort saved addresses

ci/Jenkinsfile.combined, ci/Jenkinsfile.linux, ci/Jenkinsfile.macos, ci/Jenkinsfile.tests-e2e, ci/Jenkinsfile.tests-imports, ci/Jenkinsfile.tests-nim, ci/Jenkinsfile.windows
Was supposed to be done in:
* https://github.com/status-im/status-desktop/pull/10338
But it was merged without those changes.
Depends on:
* https://github.com/status-im/status-jenkins-lib/pull/62
=> ci: add Alchemy credentials, update Infura

src/app/modules/main/wallet_section/overview/module.nim
=> fix(@wallet): delete selected account

src/app/modules/main/activity_center/module.nim, src/app/modules/main/chat_section/controller.nim, src/app/modules/main/chat_section/io_interface.nim, src/app/modules/main/chat_section/module.nim, src/app/modules/main/chat_section/view.nim, src/app/modules/main/profile_section/contacts/controller.nim, src/app/modules/main/profile_section/contacts/io_interface.nim, src/app/modules/main/profile_section/contacts/module.nim, src/app/modules/main/profile_section/contacts/view.nim, src/app/modules/shared_models/message_item_qobject.nim, src/app_service/service/contacts/service.nim, src/backend/contacts.nim, storybook/pages/ProfileDialogViewPage.qml, ui/app/AppLayouts/Chat/stores/RootStore.qml, ui/app/AppLayouts/Profile/stores/ContactsStore.qml, ui/app/AppLayouts/Profile/views/ContactsView.qml, ui/app/mainui/activitycenter/panels/ContactRequestCta.qml, ui/app/mainui/activitycenter/views/ActivityNotificationContactRequest.qml, ui/app/mainui/activitycenter/views/ActivityNotificationContactVerification.qml, ui/app/mainui/activitycenter/views/ActivityNotificationMessage.qml, ui/imports/shared/views/ProfileDialogView.qml
Close #9788
Close #10127
Close https://github.com/status-im/status-go/issues/3326
Depends https://github.com/status-im/status-go/pull/3379
Update outgoing and incoming CR notifications text 
ActivityCenter
=> fix(ActivityCenter): Fix contact requests flows

src/app/modules/main/chat_section/chat_content/messages/view.nim, ui/StatusQ/src/StatusQ/Components/StatusMessage.qml
Fixes: #10072
[relevant STATUSGO PR](https://github.com/status-im/status-go/pull/3393)
Adds possibility to change a text for image messages
Edit messages
=> feat(edit-message): Edit image messages

src/app_service/service/community_tokens/service.nim, vendor/DOtherSide/lib/src/DOtherSide.cpp
Cherry picks of:
https://github.com/status-im/status-desktop/issues/10308
https://github.com/status-im/status-desktop/issues/10332
https://github.com/status-im/status-desktop/issues/10264
=> Cherry-picks of the issues for 0.11.1

ui/app/mainui/AppMain.qml
Fixes https://github.com/status-im/status-desktop/issues/10525
=> fix: Fixed ephemeral notifications shadow

src/app_service/service/wallet_account/service.nim
=> fix(@wallet): send a token without balance

ui/app/AppLayouts/Wallet/addaccount/panels/DerivationPath.qml
=> fix(@desktop/wallet): setting derivation path for a new account with keycard can get in infinite loop

ui/app/AppLayouts/Wallet/addaccount/panels/DerivationPath.qml, ui/app/AppLayouts/Wallet/addaccount/panels/DerivationPathInput.qml, ui/app/AppLayouts/Wallet/addaccount/panels/DerivationPathSection.qml
=> fix(@desktop/wallet): derivation path edit control breaks in custom mode

src/app/modules/main/communities/tokens/controller.nim, src/app/modules/main/communities/tokens/io_interface.nim, src/app/modules/main/communities/tokens/module.nim, src/app/modules/main/communities/tokens/view.nim, src/app_service/service/community_tokens/service.nim, ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml, ui/imports/shared/stores/CommunityTokensStore.qml
Fix #10486
Passing communityId to Qml, so the correct component display toast message.
https://user-images.githubusercontent.com/61889657/236149624-d54b4e2f-6be7-4e7f-acdf-0277c5d2c0bb.mov
=> fix(@desktop/communities): Fix double toast message

src/app/modules/shared_modules/keycard_popup/internal/migrating_key_pair_state.nim
=> fix(@desktop/wallet): issues migrating a keypair if the profile keypair is already migrated to a keycard fixed

ui/StatusQ/src/StatusQ/Controls/StatusBaseButton.qml
fixes: #10480
https://user-images.githubusercontent.com/33099791/236172165-159fe8ec-68cd-4f43-bb87-cbbbd98a6a93.mp4
=> fix(StatusQ/StatusBaseButton): use `Layout.*` properties properly

test/ui-test/src/drivers/elements/base_element.py, test/ui-test/src/screens/StatusLoginScreen.py, test/ui-test/src/screens/StatusWelcomeScreen.py, test/ui-test/testSuites/global_shared/scripts/onboarding_names.py, test/ui-test/testSuites/global_shared/scripts/settings_names.py, test/ui-test/testSuites/suite_onboarding/shared/steps/loginSteps.py, test/ui-test/testSuites/suite_onboarding/shared/steps/steps.py, test/ui-test/testSuites/suite_onboarding/tst_signUpNegativeCases/test.feature, test/ui-test/testSuites/suite_onboarding/tst_signUpSeedPhraseNegativeCases/test.feature, test/ui-test/testSuites/suite_onboarding/tst_statusLoginPassword/test.feature, test/ui-test/testSuites/suite_onboarding/tst_statusSignUp/test.feature, ui/main.qml
=> test(suite_onboarding): mayfail tag removed for pass tests
