status-im/status-desktop

- ui/app/AppLayouts/stores/RootStore.qml
- ui/app/mainui/AppMain.qml
- ui/imports/assets/icons/statuses/automatic.svg
- ui/imports/assets/icons/statuses/inactive.svg
- ui/imports/assets/icons/statuses/online.svg
- ui/imports/shared/popups/UserStatusContextMenu.qml
Adjust UserStatusContextMenu to Figma design:
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=77%3A19108
Requires StatusQ: https://github.com/status-im/StatusQ/pull/749
UserStatusContextMenu
> 6090 improve user status context menu

- ui/imports/shared/controls/chat/FetchMoreMessagesButton.qml
- ui/imports/shared/controls/chat/GapComponent.qml
leftover from the qsTrId() -> qsTr() transition; obey the locale
settings a bit more
Fixes the date/date range being displayed under "Fetch more messages..."; it got broken due to missing format placeholders (`%1`)
Chat view
> fix: unbreak "fetch more messages..."

- ui/app/AppLayouts/Wallet/panels/DerivedAddressesPanel.qml
- ui/app/AppLayouts/Wallet/panels/ImportPrivateKeyPanel.qml
- ui/app/AppLayouts/Wallet/views/AdvancedAddAccountView.qml
fixes #6257
fix(@desktop/wallet): Fix visual issues in add account modal:
1. Alignment of the Inputs
2. Background color of the derived address panel
**NOTE: There is another issue pending which is already reported separately as https://github.com/status-im/status-desktop/issues/6315**
Wallet
https://user-images.githubusercontent.com/60327365/177967189-102d4802-9f45-4ead-951f-28a97debfc32.mov
> fix(@desktop/wallet): Fix visual issues in add account modal

- ui/app/AppLayouts/Onboarding/views/LoginView.qml
Fixed the arrow icon in the login button
login
> fix(LoginView): Fixed arrow icon size

- ui/imports/shared/views/chat/CompactMessageView.qml
- ui/imports/shared/views/chat/MessageContextMenuView.qml
- ui/imports/shared/views/chat/MessageView.qml
Fixes #6264
Changed x and y assignment trigger to get the correct value once the position depends on the own popup height.
Chat / Context menu  - Emoji reaction
https://user-images.githubusercontent.com/97019400/178258104-0d9954ab-5838-40f2-968c-09ebbb8a425c.mov
> fix(Chat/ReactionDialog): The reaction dialog is shown in different places

- ui/app/AppLayouts/Profile/views/profile/MyProfileSettingsView.qml
Fixes #6361
Try harder to have the 'Biometric login and transaction authentication' entry fill the whole width
MyProfileSettingsView
> fix(MyProfileSettingsView): fingerprint entry should fill the full width

- ui/app/AppLayouts/Profile/controls/WalletAccountDelegate.qml
- ui/app/AppLayouts/Wallet/views/LeftTabView.qml
Fix for Wallet icon background color seems off in wallet settings under dark mode
fixes #6059
Uses the correct background color for the wallet icon
wallet, settings
https://user-images.githubusercontent.com/60327365/178507871-75b2241a-b18c-493b-bc91-d3105f256e4c.mov
> fix(@desktop/wallet): Fix for Wallet icon background color seems off in wallet settings under dark mode

- ui/app/AppLayouts/Onboarding/views/ConfirmPasswordView.qml
fixes: #6229
Makes "your" not "you" in _Confirm **your** password (again)_ sentence.
When app asks user for re-input password during creating a new user account - ConfirmPasswordView.qml
Appearance after fix:
> fix(@desktop): correct spelling of you-r

- ui/app/AppLayouts/Onboarding/views/LoginView.qml
fixes: #6052
Changes placeholder for password on LoginView, from 'Enter password' to 'Password' according to designs
Login screen, when app asks for password
Appearance after fix:
> fix(@desktop/onboarding): replace placeholder text to Password

- ui/imports/shared/controls/AssetAndAmountInput.qml
fixes #6056
Fixes the issue of text overlapping with the arrow when it is long
wallet, chat
- doesnt exactly match design but not sure what to do.
https://user-images.githubusercontent.com/60327365/178745691-6990790d-dd50-48b9-9181-24fb622c603b.mov
> fix(@desktop/chat): The asset name is overlapped by an arrow

- ui/app/mainui/AppMain.qml
Fixes #6023
Puts the dropRectangle in a Loader that is only active when we are dragging
> fix(AppMain): put dropRectangle in a Loader, active when dragging

- ui/app/AppLayouts/Onboarding/popups/BeforeGetStartedModal.qml
correct sizing, fonts, spacings, margins, etc
Fixes #6020
Needs status-im/StatusQ#776
Aligns the 'Before you get started' popup with design
Onboarding/BeforeGetStarted
Actual app:
Design:
> fix(Onboarding): align the 'Before you get started' popup with design

- ui/app/AppLayouts/CommunitiesPortal/CommunitiesPortalLayout.qml
Fixes #6356
Depends on https://github.com/status-im/StatusQ/pull/766
- Replaced `ScrollView` to new component in `StatusQ` -> `StatusScrollView`.
- Bump `StatusQ`.
Community Portal
https://user-images.githubusercontent.com/97019400/178980150-a6bcc755-c743-4790-9051-9cace28d450c.mov
> fix(CommunitPortal): Scroll doesn't work correctly on the Community Portal page

- ui/app/AppLayouts/Chat/views/CreateChatView.qml
Closes #6352
Updated top margin based on designs
CreateChatView
> fix(CreateChatView): Updated top margin based on designs

- ui/app/AppLayouts/Profile/popups/BackupSeedModal.qml
- ui/app/AppLayouts/Profile/popups/backupseed/Acknowledgements.qml
Fixes #6411
- fix the order of buttons and the Skip button transparent background
- don't let the subHeaderItem eat vertical space when it's not visible
- layout/margins/spacing/linespacing fixes
Disclaimer: "Not Now" btn text should stay capital case imo (as is it now)
Fixes UI issues in the Intro/Acknowledgements page of the BackupSeed modal
BackupSeedModal/Acknowledgements
Side by side comparison:
> fix(BackupSeedModal): fix the intro/acknowledgements page UI

- ui/app/AppLayouts/Chat/ChatLayout.qml
- ui/app/AppLayouts/Chat/controls/activityCenter/ReplyComponent.qml
- ui/app/AppLayouts/Chat/panels/ActivityCenterPopupTopBarPanel.qml
- ui/app/AppLayouts/Chat/panels/ActivityChannelBadgePanel.qml
- ui/app/AppLayouts/Chat/panels/communities/CommunityChannelsAndCategoriesBannerPanel.qml
- ui/app/AppLayouts/Chat/panels/communities/CommunityWelcomeBannerPanel.qml
- ui/app/AppLayouts/Chat/popups/ActivityCenterPopup.qml
- ui/app/AppLayouts/Chat/popups/GroupInfoPopup.qml
- ui/app/AppLayouts/Chat/popups/community/CommunitiesPopup.qml
- ui/app/AppLayouts/Chat/popups/community/CommunityDetailPopup.qml
- ui/app/AppLayouts/Chat/popups/community/MembershipRequestsPopup.qml
- ui/app/AppLayouts/Chat/stores/RootStore.qml
- ui/app/AppLayouts/Chat/views/ActivityCenterGroupRequest.qml
- ui/app/AppLayouts/Chat/views/ActivityCenterMessageComponentView.qml
- ui/app/AppLayouts/Chat/views/ChatColumnView.qml
- ui/app/AppLayouts/Chat/views/ChatContentView.qml
- ui/app/AppLayouts/Chat/views/ChatView.qml
- ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
- ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
- ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
- ui/app/AppLayouts/CommunitiesPortal/CommunitiesPortalLayout.qml
- ui/app/mainui/AppMain.qml
- ui/imports/utils/Global.qml
Closes #4244
Removed dynamic scoping from chat section
Chat section
> fix(chat): removing dynamic scoping from chat section

- ui/imports/assets/icons/status-logo-circle.svg
- ui/imports/assets/icons/status-logo-dev-circle.svg
- ui/imports/assets/icons/status-logo-dev-round-rect.svg
- ui/imports/assets/icons/status-logo-round-rect.svg
- ui/main.qml
The images had been moved and the icons used for the tray icon went missing. I added back the missing icons and, at least on Windows, the tray icon is back and the OS notifications work again.
> fix(main): fix missing icons for the tray icon

- src/app/core/notifications/details.nim
- src/app/core/notifications/notifications_manager.nim
- src/app/modules/main/ephemeral_notification_item.nim
- src/app/modules/main/ephemeral_notification_model.nim
- src/app/modules/main/io_interface.nim
- src/app/modules/main/module.nim
- src/app/modules/main/view.nim
- ui/app/mainui/AppMain.qml
Corresponding `StatusQ` PR:
- https://github.com/status-im/StatusQ/pull/737
Fixes: #5935
> fix(@desktop/notifications): nothing happens after clicking on any notification

- ui/app/AppLayouts/Profile/popups/backupseed/ConfirmStoringSeedPhrasePanel.qml
Follow up to PR #6467, just a few minor UI tweaks to align it to the
intended design
Fixes UI issues in the confirmation/final  page of the BackupSeed modal
BackupSeedModal/ConfirmStoringSeedPhrasePanel
Side by side comparison:
> fix(BackupSeedModal): fix the confirmation/final page UI

- ui/imports/shared/status/StatusChatInput.qml
Fixes #6298
`StatusButton` is now used correctly. There are 3 different button variations with preset heights/widths and paddings. The consumer cannot change the height without altering the expected behaviour and display of the button.
Button height is now consistent with chat input height.
1:1 Chat / Blocked user
> fix(StatusChatInput): 'Unblock' is not vertically aligned in 1-1 chat

- ui/app/AppLayouts/Onboarding/views/LoginView.qml
- ui/i18n/qml_en.ts
fixes #6053 
- incorrect password message aligned with design
- translation updated, some locations fixed
LoginView component
> fix(@desktop/onboarding): Align LoginView incorrect pass msg with design

- ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
- ui/i18n/qml_en.ts
fixes #6381 
- notifications section removed
- minor fix (== to ===)
- translation file fixed (line numbers, one unused entry removed)
Community management, CommunitySettingsView component
> fix(@desktop/chat): Remove notifications section from community management

- ui/app/AppLayouts/Wallet/controls/NetworkFilter.qml
- ui/app/AppLayouts/Wallet/stores/RootStore.qml
- ui/i18n/qml_en.ts
Closes #6483: all networks button should match design
Closes #6487: networks button should display number of selected networks
Closes #6488: network tags should display icons and look like designs
Fixes some UI issues with the wallet's network filter control
Wallet/NetworkFilter
(pls disregard the rest of the UI changes, will be in the upcoming PR)
Side by side:
All networks:
2 selected networks:
> fix(NetworkFilter): network filter UI fixes

- ui/app/AppLayouts/Chat/views/CreateChatView.qml
Closes #6452
CreateChatView updated layout spacing and sizes
CreateChatView
*Figma at top, app at the bottom
*Screenshot is taken in combination with this https://github.com/status-im/StatusQ/pull/780 change
TEXT
> fix(CreateChatView): updated layout spacing and sizes

- ui/app/AppLayouts/Wallet/WalletLayout.qml
- ui/app/AppLayouts/Wallet/panels/WalletHeader.qml
- ui/app/AppLayouts/Wallet/views/RightTabView.qml
- ui/app/AppLayouts/Wallet/views/SavedAddressesView.qml
Fixes various issues in the wallet/account header section
Closes #6484: Account header is different from design
Closes #6485: Account layout needs margins adjusted to match design
Closes #6493: Saved addresses header should look like designs
Wallet/WalletHeader,SavedAddressesView
Side by side:
Overall view:
Saved addresses:
> fix(WalletHeader): wallet section header UI fixes

- src/app/modules/main/wallet_section/module.nim
- src/app/modules/main/wallet_section/view.nim
- src/app_service/service/settings/service.nim
- src/app_service/service/wallet_account/service.nim
- ui/app/AppLayouts/Wallet/stores/CurrenciesStore.qml
This updates the desktop client with a newly emitted currency settings
that might originate from synchronization
> fix: handle sync currency settings

- ui/imports/shared/popups/NicknamePopup.qml
fixes #5930
- block "Done" when the input is invalid (it can be done by selecting existing text and pasting forbidden characters)
- some minor style fixes
NicknamePopup.qml
> fix(@desktop/chat): Block 'Done' btn when nickname is invalid

- ui/app/AppLayouts/Wallet/popups/AddAccountModal.qml
- ui/app/AppLayouts/Wallet/views/LeftTabView.qml
fix(@desktop/wallet): Wallet account generation popup doesn't support tab navigation
Please not tab access for advanced view is not implemented
fixes #6388
Added tab navigation between password, account name and confirm buttons on the add account modal
Wallet
https://user-images.githubusercontent.com/60327365/179791355-b71caa5c-0fc0-4e5e-93d6-ff24d55ea864.mov
> fix(@desktop/wallet): Wallet account generation popup doesn't support tab navigation

- ui/app/AppLayouts/Wallet/popups/ReceiveModal.qml
fix(@desktop/wallet): Multinetwork QR code sometimes doesn't update when there is only 1 network left
fixes #6496
When model is empty prefix is not calculated so check for empty model and reset it to empty string
Wallet
https://user-images.githubusercontent.com/60327365/179807727-b5bcf957-9793-4ad0-9a81-c0fa7b405a59.mov
> fix(@desktop/wallet): Multinetwork QR code sometimes doesn't update when there is only 1 network left

- src/app/modules/main/app_search/controller.nim
- src/app_service/service/message/service.nim
fixes #6427
- additional check added to the controller, if there is no chats or communities to search skip async search and return empty result
- go backend returns null when no messages found. It was causing error message - response validation fixed.
- some error messages added  for consistency
app search controller, message service
> fix(@desktop/chat): endless search when user has no chats or communities

- ui/imports/shared/controls/chat/ProfileHeader.qml
- ui/imports/shared/controls/chat/UserImage.qml
- ui/imports/shared/views/chat/CompactMessageView.qml
- ui/imports/shared/views/chat/MessageContextMenuView.qml
- ui/imports/shared/views/chat/MessageView.qml
Fixes a couple of issues with the MessageContextMenuView, namely:
- add the "(Un)Mark as Untrustworthy" action to the menu
- fix the placement and visuals of the "(Un)Block" menu item
- add a missing separator above these
- store the blocked and trust details in `d.contactDetails` and properly
refresh it upon opening the menu
- some other smaller UI fixes to align the menu to the design
Closes #6538: Stranger's (untrustworthy) menu doesn't match the Design
Closes #6535: The stranger's card doesn't match the Design
Also fixes issue with UserImage and the overall popup placement (see the individual commits for more details)
MessageContextMenuView, ProfileHeader, UserImage
Regular account:
Untrustworthy, not blocked:
Untrustworthy, blocked:
My profile menu:
A random profile popup:
> fix(MessageContextMenuView): context menu fixes

- scripts/translationScripts/update-en-ts.py
- ui/i18n/qml_en.ts
- ui/nim-status-client.pro
- handle `SOURCES` recursively, rather than spelling all the paths out;
most of them were outdated and some still missing
- include JS files too
- let the Python script skip existing translations (in case we need to
manually add plurals)
- updated qml_en.ts as a result of these changes
Stats:
```
Updating '../../ui/i18n/qml_en.ts'...
Found 1703 source text(s) (109 new and 1594 already existing)
Kept 35 obsolete entries
Same-text heuristic provided 35 translation(s)
```
It fixes issues with the way we extract strings for translations
Scripts
N/A
> fix(l10n): fix strings extraction

- ui/app/AppLayouts/Profile/views/EnsTermsAndConditionsView.qml
actually make it possible to also click the text to toggle :)
Closes #6558
Fixes vertical checkbox alignment
EnsTermsAndConditionsView
> fix(EnsTermsAndConditionsView): fix checkbox vertical alignment

- src/app/modules/main/chat_section/module.nim
Fixes #6574
We were switching to the first channel on reorder, which is annoying and not necessary. Now we stay on the same channel we were on.
This will also fix the problem where if the owner switches the order, you would get your channel switched as well.
> fix(community-chat): don't switch to the first channel when reordering

- ui/app/AppLayouts/Chat/panels/UserListPanel.qml
- [bump DOtherSide](https://github.com/status-im/status-desktop/pull/6562/commits/60e318ad958fb1fd11164b1aababa39e55adec65)
- [fix(@desktop/chat): sort display names in UserListPanel](https://github.com/status-im/status-desktop/commit/0fc4a5f11b03db2d3b296a9097110fb76c3bf14e)
- fixes: https://github.com/status-im/status-desktop/issues/6185
- [fix(@desktop/chat): sort users by online status](https://github.com/status-im/status-desktop/pull/6562/commits/51282ece0b18694dcb5bd4e14cdbdfa356776ac1)
-  fixes: https://github.com/status-im/status-desktop/issues/6563
Users model has to be sorted by online status first, otherwise
`UserListPanel` sections will be duplicated. That's because:
> Note: Adding sections to a ListView does not automatically re-order
the list items by the section criteria. …
> sort display names in UserListPanel

- ui/imports/shared/views/TabAddressSelectorView.qml
fix(@desktop/wallet): In the Send Modal the saved addresses and my accounts sections need to be adjusted to match design
fixes #6498
Solves the issue of name not shown on saved addresses and my accounts view in SendModal
Wallet
https://user-images.githubusercontent.com/60327365/180005047-0272cc3d-3527-42f6-b2c3-46f1cc2bc9cb.mov
> fix(@desktop/wallet): In the Send Modal the saved addresses and my accounts sections need to be adjusted to match design

- ui/imports/shared/controls/AmountInputWithCursor.qml
- ui/imports/shared/popups/SendModal.qml
- ui/imports/shared/views/TabAddressSelectorView.qml
fix(@desktop/wallet): Send Popup - Can't scroll outside the list of accounts after selecting one
fixes #6196
Created a border width for scroll view so that it can be scrolled separately from the account list
wallet
https://user-images.githubusercontent.com/60327365/179049747-45f035b9-d3ad-4051-8f17-1f5b02b3d3ba.mov
> fix(@desktop/wallet): Send Popup - Can't scroll outside the list of accounts after selecting one

- ui/app/AppLayouts/Chat/views/ChatView.qml
- ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
- ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
- ui/app/AppLayouts/Chat/views/CreateChatView.qml
- ui/app/mainui/AppMain.qml
#fixes #6542 
- problem with overlapping Start Chat view fixed for both Chat and Communities sections
- highlight handled properly in CommunityColumnView when Start Chat opened
- flow simplified, stores modified exclusively from AppMain
`ChatView`, `CommunityColumnView`, `ContactColumnView`, `CreatChatView`, `AppMain`
https://user-images.githubusercontent.com/20650004/180431962-0fd3be73-723e-4dcc-a65f-47c19624c712.mp4
> fix(@desktop/chat): chat content overlapping with Start Chat dialog

- ui/app/AppLayouts/Profile/panels/ContactsListPanel.qml
fixes #5928
- contacts can be searched by name, uncompressed pk and compressed pk
ContactsListPanel
https://user-images.githubusercontent.com/20650004/180462843-6dfe64cd-3755-41bb-9fd7-553d88aa8dec.mp4
> fix(@desktop/settings) contacts search doesn't work by compressed pk

- ui/imports/shared/controls/EmojiHash.qml
- ui/imports/shared/controls/chat/ProfileHeader.qml
Fixes: #6300
Reduce size and spaces between Emoji Icons visible in InsertDetailsView and ProfileHeader
1. Onboarding (when new user is created - InsertDetailsView.qml
2. Chat, when browsing user profile - ProfileHeader.qml
**1. Onboarding:**
_on left: Designs, on right: implementation including this fix_
_implementation including this fix(opacity = 0.5) over designs_ :
**2. ProfilHeader small:**
_on left: Designs, on right: implementation including this fix_
_implementation including this fix(opacity = 0.5) over designs_ :
**2a. ProfilHeader:**
_on left: Designs, on right: implementation including this fix_
_implementation including this fix(opacity = 0.5) over designs_ :
This is my very first PR in here, so I would like to say Hi! 👋
> fix(@desktop) emoji hash icons are very big

- ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
- ui/imports/shared/views/chat/CompactMessageView.qml
- ui/imports/shared/views/chat/MessageView.qml
Fixes #6576
Disables highlighting the message under the mouse cursor while scrolling thru the message list
CompactMessageView
> fix(CompactMessageView): disable hovering while scrolling

- ui/app/mainui/AppMain.qml
make the profile image + badge look as designed
Closes: #6622
Aligns the user profile icon with design
AppMain/StatusAppNavBar
> fix(AppMain): User profile image on sidebar should be a bit bigger larger

- ui/app/AppLayouts/Wallet/popups/AddEditSavedAddressPopup.qml
- ui/imports/shared/controls/AddressInput.qml
- ui/imports/shared/controls/ContactsListAndSearch.qml
- ui/imports/shared/controls/Input.qml
- Also replaced StatusModal with StatusDialog
Closes #6495
Fixes Saved address add/edit modal layout issues as well as replaces StatusModal with StatusDialog
Wallet Saved address add/edit modal
> fix(Wallet): Saved address add/edit modal layout issues

- ui/app/AppLayouts/Onboarding/views/AllowNotificationsView.qml
Closes: #6514
Fixes minor issues in the "Allow notifications" onboarding page
AllowNotificationsView
> fix(AllowNotificationsView): The page 'Allow notifications' differs from the Design

- ui/app/AppLayouts/Chat/controls/community/CommunityDescriptionInput.qml
- ui/app/AppLayouts/Chat/controls/community/CommunityIntroMessageInput.qml
- ui/app/AppLayouts/Chat/popups/community/CreateChannelPopup.qml
- ui/app/AppLayouts/Profile/popups/SendContactRequestModal.qml
- ui/app/AppLayouts/Profile/popups/backupseed/BackupSeedStepBase.qml
- ui/app/AppLayouts/Profile/views/ContactsView.qml
- ui/app/AppLayouts/Profile/views/NotificationsView.qml
- ui/imports/shared/popups/ContactVerificationRequestPopup.qml
- ui/imports/shared/popups/SendContactRequestModal.qml
- ui/imports/shared/views/ProfileView.qml
Closes #6637
Fixes status input custom height leftovers that were not updated
Modals that use status input
> fix(StatusInput): Updated status input custom height leftovers

- ui/app/AppLayouts/Profile/views/AppearanceView.qml
- ui/imports/shared/status/StatusImageRadioButton.qml
- fix system appearance preview being cut off
- bring the panel close to UI design (I haven't changed the common stuff like headline fonts, overall margins, etc)
Closes: #6623
Brings the Appearance Settings panel closer to the intended design
AppearanceView
Light:
Dark:
Side by side with design:
> fix(AppearanceView): UI issue fixes

- test/ui-test/src/drivers/SquishDriver.py
- test/ui-test/src/screens/StatusCommunityScreen.py
- test/ui-test/testSuites/suite_status/shared/scripts/names.py
- test/ui-test/testSuites/suite_status/shared/steps/communitySteps.py
- test/ui-test/testSuites/suite_status/tst_communityFlows/test.feature
- ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
Fixes #6609
The menu was lost because it used to be set as part of the ScrollView background, but it got changed to  a Flickable as part of the fix to the scrolls being not smooth.
Anyway, background doesn't exist on Flickables, so I removed it and moved the MouseArea to the CommunityColumnView instead.
Second commit adds integration tests
StatusQ PR: https://github.com/status-im/StatusQ/pull/802
> Fix missing context menu on right click in the community column + tests

- ui/imports/shared/controls/AmountInputWithCursor.qml
- ui/imports/shared/controls/GasValidator.qml
- ui/imports/shared/popups/SendModal.qml
- ui/imports/shared/views/SendModalFooter.qml
- ui/imports/shared/views/SendModalHeader.qml
fix(@desktop/wallet): Send Transaction modal colors need to be adjusted to match designs
fixes #6497
StatusQ: https://github.com/status-im/StatusQ/pull/807
Updated the background color for send modal and also updated necessary components on StatusQ side
Wallet
https://user-images.githubusercontent.com/60327365/181081972-a2aa35b9-2f50-409c-baef-83e9d61053ba.mov
> fix(@desktop/wallet): Send Transaction modal colors need to be adjusted to match designs

- ui/app/AppLayouts/Onboarding/views/InsertDetailsView.qml
fix some (line)spacing and margin problems
Closes: #6453
Fixes some (line)spacing and margin problems in the onboarding/details view
Onboarding/InsertDetailsView
> fix(InsertDetailsView): UI fixes

- ui/app/AppLayouts/Profile/panels/ContactsListPanel.qml
- ui/app/AppLayouts/Profile/views/ContactsView.qml
Fixes #6299: 'Send message' and icon for 1-1 chat are shown for a Blocked contact and they don't work 
Fixes #6669: Contact settings items have their right side options hidden (clipped)
ContactsListPanel/ContactsView
Unblocked contact:
Blocked contact:
> fix(ContactsListPanel/ContactsView): clipped width and action fixes

- ui/app/AppLayouts/Onboarding/views/LoginView.qml
Closes: #6518
Make the account name area to be clickable on the Log in page and open accounts menu
Desktop onboarding
https://user-images.githubusercontent.com/6445843/181278580-c3eb44fa-2ba1-49f8-a78e-826764ae40c2.mp4
> fix(@desktop/onboarding): make account name area clickable

- src/app_service/common/network_constants.nim
- src/app_service/service/network/service.nim
fixes #6601
only ENS stayed with ropsten but browser/sticker market are now using goerli
> feat(@wallet): make goerli default testnet

- ui/app/AppLayouts/Profile/panels/CommunitiesListPanel.qml
- ui/app/AppLayouts/Profile/views/CommunitiesView.qml
- ui/app/AppLayouts/stores/RootStore.qml
fixes #6305
- clicking on community entry moves to the corresponding community
**Note: it required adding `setActiveCommunity` to `AppLayouts/store/RootStore`, so now `setActiveCommunity` is duplicated, it occurs in 3 different places (RootStore, another RootStore and CommunityStore), because there is no common `RootStore` accessible from the whole app. Are there some plans to refactor those stores?**
- muting community works as expected
- invite icon opens invite dialog, Invite button sends invitations
`CommunitiesListPanel`, `CommunitiesView`, `AppLayouts/store/RootStore`
https://user-images.githubusercontent.com/20650004/180821070-f780a82a-daed-4369-a99b-b8bf2e2e3db3.mp4
> fix(communities): Cannot leave community, invite, mute from Settings/Communities

- resources/CMakeLists.txt
- ui/fonts/CMakeLists.txt
- ui/imports/assets/CMakeLists.txt
Otherwise, linker will optimize resources registration code on Linux,
resulting in resources loading failure.
> fix(cpp): make libraries which are not dynamically loaded static

- ui/app/AppLayouts/Profile/ProfileLayout.qml
Fixes: #6600
Needs: status-im/StatusQ#798
Fixes the testnet warning banner overflowing the profile layout width
Settings/ProfileLayout
> fix(Settings/ProfileLayout): TestNet banner overlaps left panel

- scripts/ubuntu_build_setup.sh
Add a script to install everything needed to build on ubuntu 20.04
Test scenario: from a `ubuntu:20.04` image:
- execute the script
- clone status-desktop
- run `make update` 
- run `make`
> test(@ci): add scripts to build on ubuntu

- ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
Fixes #6696 
Invitation message is sent as expected.
CommunitySettingsView
https://user-images.githubusercontent.com/20650004/181734333-0e0ecbd6-aadf-43ec-b709-baf9beffc671.mp4
> fix(community): Send community invitation fixed

- src/app/modules/main/chat_section/active_item.nim
- src/app/modules/main/chat_section/controller.nim
- src/app/modules/main/chat_section/module.nim
- src/app/modules/main/chat_section/view.nim
Fixes #6536
This doesn't fix the exact issue stated in the ticket, because I couldn't reproduce the same symptom, but I did have a problem with the same step.
My problem was that when leaving a channel and then rejoining the same one, the right panel (messages) would stay empty.
The reason was that when we leave a channel, we usually change the active item to the first channel in the list, but if there is no other channel, because we left the last channel, the active item stays the same. ie if you left `#test` as the last channel you ever had, the active item `id` would stay as `#test`, so when rejoining `#test`, the activeChannel props wouldn't update, since the ID is the same.
> fix(chat_section): reset activeItem when the last channel is removed

- test/ui-test/src/screens/StatusMainScreen.py
- test/ui-test/testSuites/suite_status/shared/scripts/names.py
- ui/app/AppLayouts/Chat/popups/PublicChatPopup.qml
Fixes the ChatFlow tets that were failing because the name for the channel name wasn't set and because the container for the message input wasn't valid.
For the channel name, I changed the type of Input to StatusInput, since Input is deprecated.
StatusQ PR: https://github.com/status-im/StatusQ/pull/813
> fix(chat-test): fix ChatFlow test that blocked because of the inputs

- ui/app/AppLayouts/Onboarding/views/SeedPhraseInputView.qml
Closes 	#6608
Fixes Suggestions are not displayed for last row in seed modal
SeedPhraseInputView
> fix(SeedPhraseInputView): sug list was clipped at bottom row

- ui/app/AppLayouts/Chat/controls/community/CommunityIntroMessageInput.qml
- ui/app/AppLayouts/Chat/controls/community/CommunityOutroMessageInput.qml
- ui/app/AppLayouts/Chat/panels/communities/CommunityEditSettingsPanel.qml
- ui/app/AppLayouts/CommunitiesPortal/popups/CreateCommunityPopup.qml
Closes #6697
fixed CommunityIntroMessageInput input height was set to 0
create communities
https://user-images.githubusercontent.com/31625338/181811770-e83e5b91-4f15-43e8-85bc-aae5d0afae46.mov
> fix(CommunityIntroMessageInput): input height was set to 0

- test/ui-test/src/drivers/SquishDriver.py
- test/ui-test/src/screens/StatusMainScreen.py
- test/ui-test/testSuites/suite_status/shared/scripts/names.py
- test/ui-test/testSuites/suite_status/shared/steps/chatSteps.py
- test/ui-test/testSuites/suite_status/tst_ChatFlow/test.feature
- ui/app/AppLayouts/Chat/views/ChatContextMenuView.qml
Fixes #6671
Sadly,  I don't know how to test if it worked, since there is no indicator that the process worked.
We can check if the "new message" indicator is gone, but just joining the channel does that.
Maybe if we ever make it possible to have multiple instances at once, then we could send a message in the channel and then mark as read.
Branched on top of https://github.com/status-im/status-desktop/pull/6701
> test(chat): add test to mark as read

- ui/app/AppLayouts/Chat/views/ChatColumnView.qml
- ui/app/mainui/AppMain.qml
- ui/imports/shared/controls/BalanceExceeded.qml
- ui/imports/shared/controls/GasSelector.qml
- ui/imports/shared/controls/GasValidator.qml
- ui/imports/shared/popups/SendModal.qml
- ui/imports/shared/popups/SignTransactionModal.qml
- ui/imports/shared/status/StatusETHTransactionModal.qml
- ui/imports/shared/status/StatusSNTTransactionModal.qml
- ui/imports/shared/views/NetworkSelector.qml
- ui/imports/shared/views/NetworksSimpleRoutingView.qml
- ui/imports/shared/views/TabAddressSelectorView.qml
fixes #6587
statusQ PR : https://github.com/status-im/StatusQ/pull/809
Use new StatusDialog instead of StatusModal which is deprecated now
Make the SendModal work as a wizard.
Wallet
https://user-images.githubusercontent.com/60327365/181508724-1879ea66-77c6-4135-980e-aa68b6f5beeb.mov
> feat(@desktop/wallet): Send modal should work as a wizard

- src/app/modules/main/chat_section/controller.nim
- src/app/modules/main/chat_section/io_interface.nim
- src/app/modules/main/chat_section/module.nim
- src/app/modules/main/chat_section/view.nim
- src/app/modules/main/communities/module.nim
- src/app/modules/main/module.nim
- src/app/modules/shared_models/active_section.nim
- src/app/modules/shared_models/section_item.nim
- src/app/modules/shared_models/section_model.nim
- src/app_service/service/chat/dto/chat.nim
- src/app_service/service/community/dto/community.nim
- src/app_service/service/community/service.nim
- src/backend/communities.nim
- ui/app/AppLayouts/Chat/panels/communities/CommunityMembersSettingsPanel.qml
- ui/app/AppLayouts/Chat/panels/communities/CommunityMembersTabPanel.qml
- ui/app/AppLayouts/Chat/stores/RootStore.qml
- ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
Issue #5979
According to Figma design: https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=3113%3A356327
new tabs are added: "All members" and "Banned". Also unban functionality is added.
The scope is described in the issue.
Community settings / members
https://user-images.githubusercontent.com/61889657/176382827-c215566b-65a1-4550-b6a3-9a9875767fdb.mov
> feat(@desktop/chat): Add sections to members tab of the community management

- ui/imports/shared/views/chat/CompactMessageView.qml
- ui/imports/shared/views/chat/MessageContextMenuView.qml
- keep context menu when emoji reaction clicked
Fixes #6633
Add missing handlers with setMessageActive calls.
Remove close call from emoji click handler.
Desktop Chat
https://user-images.githubusercontent.com/6445843/182192578-caa78873-badf-4366-93a2-7dfc32ce05c5.mp4
> fix(@desktop/chat) keep message hover effect while context menu open

- ui/app/AppLayouts/Chat/controls/community/CommunityDescriptionInput.qml
- ui/app/AppLayouts/Chat/controls/community/CommunityLogoPicker.qml
- ui/app/AppLayouts/Chat/controls/community/CommunityNameInput.qml
- ui/app/AppLayouts/Chat/controls/community/CommunityOptions.qml
- ui/app/AppLayouts/CommunitiesPortal/controls/CommunityColorPicker.qml
- ui/app/AppLayouts/CommunitiesPortal/controls/CommunityTagsPicker.qml
- ui/app/AppLayouts/CommunitiesPortal/panels/CommunityColorPanel.qml
- ui/app/AppLayouts/CommunitiesPortal/popups/CreateCommunityPopup.qml
- fix initial input focus
- fix texts according to design
- fix TAB keys between the input fields
- fix input fields text and placeholders alignment
- make the community options checkboxes clickable
- adjust margins/spacing according to design
The (missing) banner will be done as part of issue #6726 
Closes: #6724
Fixes various issues in the Create Community popup and its components
CreateCommunityPopup + components used
Light:
Design:
Dark:
> fix(CreateCommunityPopup): Create Community modal adjustments

- ui/imports/shared/controls/Input.qml
drop a defunct MouseArea that was being used for a context menu which got
removed in the meantime; it breaks clicking inside the TextField
Closes: #5167
Fixes being unable to place cursor in (esp. password) fields 
Input
- [n/a] I've checked the design and this PR matches it
> fix(Input): unable to place cursor using mouse

- ui/app/AppLayouts/CommunitiesPortal/panels/CommunityColorPanel.qml
Fixes #6728
Adjust the text in Community color picker
Desktop Community 
Expected
Actual
https://user-images.githubusercontent.com/6445843/182609173-957daa75-4af7-4aed-8bdc-5ee8332314ee.mp4
> fix(@desktop/community) adjust color picker

- test/ui-test/src/drivers/SquishDriverVerification.py
- test/ui-test/src/screens/StatusChatScreen.py
- test/ui-test/testSuites/suite_status/shared/scripts/sections/chat_names.py
- test/ui-test/testSuites/suite_status/shared/steps/chatSteps.py
- test/ui-test/testSuites/suite_status/tst_ChatFlow/test.feature
- ui/imports/shared/panels/chat/ChatButtonsPanel.qml
Fixes #6757
Same as with the reply test, there is a chance that the second test will fail because it relies on mailservers.
Branched on top of https://github.com/status-im/status-desktop/pull/6735
> test(chat): add test to delete messages

- ui/app/AppLayouts/Chat/views/ChatColumnView.qml
- ui/app/AppLayouts/Chat/views/ChatView.qml
- ui/app/AppLayouts/Chat/views/CreateChatView.qml
- ui/app/mainui/AppMain.qml
Closes #6700
Fixes various activity center button issues
- tooltip arrow was missaligned
- activity center was not opening
** Also fixed create chat view width to follow its parent
CreateChatView
https://user-images.githubusercontent.com/31625338/182383518-afb5109d-852f-4910-bb83-43d968f7f83e.mov
> fix(CreateChatView): activity center button issues

- ui/app/AppLayouts/Chat/panels/communities/CommunityProfilePopupOverviewPanel.qml
- ui/app/AppLayouts/Chat/popups/ChatCommandModal.qml
- ui/app/AppLayouts/Chat/popups/GroupInfoPopup.qml
- ui/app/AppLayouts/Chat/popups/community/CommunityDetailPopup.qml
- ui/app/AppLayouts/Chat/popups/community/CommunityProfilePopup.qml
- ui/app/AppLayouts/Chat/popups/community/InviteFriendsToCommunityPopup.qml
- ui/app/AppLayouts/Chat/popups/community/MembershipRequestsPopup.qml
- ui/app/AppLayouts/Chat/popups/community/TransferOwnershipPopup.qml
- ui/app/mainui/AppMain.qml
- ui/imports/shared/popups/SignTransactionModal.qml
- ui/imports/shared/status/StatusETHTransactionModal.qml
- ui/imports/shared/status/StatusSNTTransactionModal.qml
Closes #6727
Depends on: https://github.com/status-im/StatusQ/pull/821
introduces status back button in all necessary places
back button usage areas
https://github.com/status-im/StatusQ/pull/821#issuecomment-1202432404
> fix(StatusModal): back button arrow was tiny

- ui/app/AppLayouts/CommunitiesPortal/CommunitiesPortalLayout.qml
- ui/app/mainui/AppMain.qml
Fixes #6723
- update button text
- add contentPrefferedWidth property to CommunitiesPortalLayout which changes contentWidth of StatusScrollView(Flickable) 
https://user-images.githubusercontent.com/6445843/182700146-9cb742d4-6c6c-4c10-a669-39291293fb3d.mp4
> fix(@desktop/community) Community portal adjustment

- src/app/modules/main/chat_section/model.nim
- src/app/modules/main/view.nim
- src/app_service/service/community/service.nim
Fixes: #6597
Fixes: #6722
Fixes: #6777
The chats model is not reordered internally in backend, reordering is done on qml side by SortFilterProxyModel. When user requests reorder, only position is updated in the model instead of sorting items and resetting the whole model.
chat section model, community service
https://user-images.githubusercontent.com/20650004/182590609-f951dafc-a718-41f2-afb7-418951ed65e2.mp4
> fix(communities): Chat model reordering refactored, updates fixed 

- ui/app/AppLayouts/Chat/panels/SuggestedChannelsPanel.qml
- ui/app/AppLayouts/Chat/popups/PublicChatPopup.qml
Closes #6632
PublicChatPopup featured channels were aligned in a column
PublicChatPopup
> fix(PublicChatPopup): sug channels were missaligned

- ui/app/AppLayouts/Chat/popups/community/CreateChannelPopup.qml
- ui/app/AppLayouts/Chat/views/ChatContextMenuView.qml
Fixes #6732
Add Delete channel button to Edit Channel popup
Update labels for other buttons in Edit Channel popup
Expected
Implemented
https://user-images.githubusercontent.com/6445843/182875213-e3acbd20-6de2-423e-ab94-54c69799e18a.mp4
> fix(@desktop/community) add delete button to edit channel popup

- ui/app/AppLayouts/Profile/views/wallet/AccountView.qml
- ui/app/AppLayouts/Wallet/panels/WalletHeader.qml
Fixes: #6659
Depends on StatusQ's StatusAddressPanel generic control [PR](https://github.com/status-im/StatusQ/pull/826)
> fix(wallet): bring back copy wallet address

- ui/app/AppLayouts/Chat/popups/ActivityCenterPopup.qml
- ui/app/AppLayouts/Chat/popups/qmldir
- ui/app/AppLayouts/Chat/views/ChatColumnView.qml
- ui/app/AppLayouts/Chat/views/CreateChatView.qml
- ui/app/mainui/AppMain.qml
- ui/imports/utils/Global.qml
Closes: #6345
Move `ActivityCenterPopup` to `AppMain` and add creation method to `Global`
ActivityCenter
> fix(CreateChatView): Move `ActivityCenterPopup` to appmain

- src/app/modules/main/chat_section/chat_content/controller.nim
- src/app/modules/main/chat_section/chat_content/io_interface.nim
- src/app/modules/main/chat_section/chat_content/module.nim
- src/app/modules/main/chat_section/chat_content/view.nim
- src/app/modules/main/chat_section/controller.nim
- src/app/modules/main/chat_section/io_interface.nim
- src/app/modules/main/chat_section/model.nim
- src/app/modules/main/chat_section/module.nim
- src/app/modules/main/chat_section/view.nim
- src/app_service/service/chat/service.nim
- src/backend/chat.nim
- ui/app/AppLayouts/Chat/popups/GroupInfoPopup.qml
- ui/app/AppLayouts/Chat/popups/RenameGroupPopup.qml
- ui/app/AppLayouts/Chat/views/ChatContentView.qml
- ui/app/AppLayouts/Chat/views/ChatContextMenuView.qml
- ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
- ui/imports/shared/panels/EditCroppedImagePanel.qml
- ui/imports/shared/popups/ImageCropWorkflow.qml
The user is able to change group chat's color. Changing image will be added in the next phase.
Additionally, users have got the same chat color during creation.
Fix added - changes can be done only by the admin.
Required  prs:
- status-go - https://github.com/status-im/status-go/pull/2754
- StatusQ - https://github.com/status-im/StatusQ/pull/777
Chat
https://user-images.githubusercontent.com/61889657/179198071-f2109c9c-ab58-45c2-94be-f4dd6a477652.mov
> 5982 edit group name and color

- ui/imports/shared/popups/ImageCropWorkflow.qml
Issue #6866
Change import Qt.labs.platform into QtQuick.Dialogs.
FileDialog from Qt.labs.platform does not have needed functions.
EditCropImagePanel
Selected & cropped image is shown correctly
> fix(@desktop/general): Fix import in ImageCropWorkflow

- src/app/modules/main/chat_section/item.nim
- src/app/modules/main/chat_section/model.nim
- src/app/modules/main/chat_section/module.nim
- src/app/modules/main/chat_section/sub_model.nim
- src/app_service/service/community/service.nim
fixes #6292
it's based on some earlier works: https://github.com/status-im/status-desktop/pull/6371
Current approach is based on changes regarding reordering (https://github.com/status-im/status-desktop/pull/6792). UI no longer relies directly on the order of items in the chat section model - UI is inteded to rely on `position` role and use it for sorting.
- add reorder method to SubModel
- remove prepended communityID to chatID when emitting SIGNAL_COMMUNITY_CHANNEL_REORDERED
- remove prependItem/prependItems methods because ordering is now intended to be done on ui side
community service, chat section model
https://user-images.githubusercontent.com/20650004/183056551-4b52a7b7-e6a5-4d28-82c0-ccb47b03262d.mp4
> fix(Communities/ChatsList): chats order updates handled correctly, subitems reordering fixed

- ui/app/AppLayouts/CommunitiesPortal/panels/CommunityTagsPanel.qml
Close #6739
Depends https://github.com/status-im/StatusQ/pull/831
Update spacings, text & icon sizes
Communities
> feat(@desktop/communities): Polishing CommunityTagsPanel design

- scripts/ubuntu_build_setup.sh
xvfb is needed in order run squish test into a headless server
> test: Add xvfb to the runtime dependencies

- ui/app/AppLayouts/Wallet/controls/NetworkFilter.qml
- ui/app/AppLayouts/Wallet/popups/NetworkSelectPopup.qml
Fixes #6486
Adjust Wallet Network dropdown paddings and sizes
Desktop Wallet
**! highlight is forced just for comparison here !**
https://user-images.githubusercontent.com/6445843/183363141-336fefa2-8447-490e-9e11-51f5d02f1629.mp4
> fix(@desktop/wallet) adjust network dropdown

- ui/app/AppLayouts/Chat/layouts/SettingsPageLayout.qml
- ui/app/AppLayouts/Chat/panels/communities/CommunityMembersSettingsPanel.qml
- ui/app/AppLayouts/Chat/panels/communities/CommunityMembersTabPanel.qml
- ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
Fixes #6786
Requires https://github.com/status-im/StatusQ/pull/842
Adjust Community Members tab
> fix(@desktop/comminities) adjust Community members tab

- ui/app/AppLayouts/Chat/controls/community/CommunityLogoPicker.qml
- ui/imports/shared/popups/ImageCropWorkflow.qml
Fixes #6835
Requires https://github.com/status-im/StatusQ/pull/839
Requires https://github.com/status-im/StatusQ/pull/848
Adjust ImageUpload popup and use updated StatusQ version
> fix(@desktop/community) adjust Image Upload popup

- ci/Jenkinsfile.uitests
- test/ui-test/src/drivers/SquishDriver.py
- test/ui-test/src/screens/SettingsScreen.py
- test/ui-test/src/screens/StatusWalletScreen.py
- test/ui-test/testSuites/suite_status/shared/scripts/sections/wallet_names.py
- test/ui-test/testSuites/suite_status/shared/steps/settingsSteps.py
- test/ui-test/testSuites/suite_status/shared/steps/walletSteps.py
- test/ui-test/testSuites/suite_status/tst_wallet/test.feature
- ui/app/AppLayouts/Wallet/controls/NetworkFilter.qml
- ui/app/AppLayouts/Wallet/popups/NetworkSelectPopup.qml
- ui/imports/shared/controls/AssetDelegate.qml
- ui/imports/shared/views/AssetsView.qml
> test(@wallet): Add test for toggling network & balance

- ui/app/AppLayouts/Profile/views/LeftTabView.qml
Fixes #6773
Change Settings header anchors and menu left margin to match Design
Desktop Settings
> fix(@desktop/settings) align settings header and menu

- ui/imports/assets/icons/keycard/card-error3@2x.svg
- ui/imports/assets/icons/keycard/card-error3@3x.svg
- ui/imports/assets/icons/keycard/card-success3@2x.svg
- ui/imports/assets/icons/keycard/card-success3@3x.svg
- ui/imports/assets/icons/keycard/card0@2x.svg
- ui/imports/assets/icons/keycard/card0@3x.svg
- ui/imports/assets/icons/keycard/card1@2x.svg
- ui/imports/assets/icons/keycard/card1@3x.svg
- ui/imports/assets/icons/keycard/card2@2x.svg
- ui/imports/assets/icons/keycard/card2@3x.svg
- ui/imports/assets/icons/keycard/card3@2x.svg
- ui/imports/assets/icons/keycard/card3@3x.svg
Images are updated the way they are the same as those we're using for the light
theme, but now without white background. All in all it does the job till we get
a better images from the design team, specialized for the dark theme.
Fixes: #6823
> fix(@desktop/keycard): keycard images have white background on dark mode

- ui/imports/shared/status/StatusStickersPopup.qml
Closes #6833
StatusStickerPopup fixed Bottom row layout issues
StatusStickerPopup
> fix(StatusStickerPopup): Bottom row layout issues

- ui/app/AppLayouts/Onboarding/views/LoginView.qml
Fixes #6821
Updated logo size on Welcome page
Desktop Onboarding
> fix(@desktop/onboarding) update logo size

- ui/app/AppLayouts/stores/RootStore.qml
- ui/imports/shared/popups/SendModal.qml
- ui/imports/shared/views/SendModalHeader.qml
fixes #6474
Fixes crash caused by current account not being set correctly on the UI.
Wallet
> fix(@desktop/wallet): Crash when staying on Advanced screen for ~30 minutes

- ui/app/AppLayouts/Chat/popups/ActivityCenterPopup.qml
Closes: #6628
ActivityCenterPopup use `MouseArea` as `modeless` component which blocks clicks outside of popup (sometimes). This PR add processing `click` signal for `MouseArea` component.
ActivityCenterPopup
> fix(ActivityCenter): Close activity center on click outside (via MouseArea)

- ui/app/mainui/AppSearch.qml
Closes: #6638
[StatusQ PR](https://github.com/status-im/StatusQ/pull/818)
Fix warning in `onOpen` slot which stops method 
AppSearch
> fix(AppSearch): Fix `forceActiveFocus` in StatusSearchPopup

- ci/Jenkinsfile.combined
To make this not send 3 notifications for each platform we build for I've created a special job just for building `master` branch:
https://ci.status.im/job/status-desktop/job/master/
For more details see: https://plugins.jenkins.io/discord-notifier/
This is blocked by issue with Jenkins GitHub plugin:
* https://github.com/status-im/infra-ci/issues/55
> ci: Discord notification for master build failrues

- .gitignore
- test/ui-test/src/drivers/SquishDriver.py
- test/ui-test/src/drivers/SquishDriverVerification.py
- test/ui-test/src/screens/SettingsScreen.py
- test/ui-test/src/screens/StatusChatScreen.py
- test/ui-test/testSuites/suite_status/shared/scripts/sections/chat_names.py
- test/ui-test/testSuites/suite_status/shared/steps/chatSteps.py
- test/ui-test/testSuites/suite_status/tst_ChatFlow/test.feature
- ui/app/AppLayouts/Chat/panels/SuggestionBoxPanel.qml
- ui/imports/shared/status/StatusChatInput.qml
- ui/imports/shared/views/ProfileView.qml
Closes [#6879
](https://github.com/status-im/status-desktop/issues/6879)
**IMPORTANT: Weak test because it relys on `mailserver` and if the chat history is not loaded, it will fail!!!**
`tst_chatFlow`:
- Added basic test scenario for sending a mention in a public chat with needed validations.
- Added basic test scenario to check a mention cannot be done if it is a non existing user.
`StatusChatScreen` updates:
- Updated join room method to validate the chat is loaded.
- Added methods for doing and verifying a mention.
`SquishDriver` updates:
- Added support in `SquishDriver` to click into a link in a text or label component.
- Minor function renames.
- `tst_chatFlow`
- Can do mention:
https://user-images.githubusercontent.com/97019400/184088019-4a9bdf9f-7720-4654-8f6c-25d0df11b383.mov
- …
> test(chat): Can do a mention in a chat

- ui/imports/shared/controls/chat/VerificationLabel.qml
- ui/imports/shared/views/chat/CompactMessageView.qml
Closes #6832
fixes big space between username and time
chat message
> fix(Chat): big space between username and time

- ui/imports/utils/Tracer.qml
- ui/imports/utils/qmldir
Adding Tracer component: Used to help determine UI components position and dimensions. Example photo attached
utilities
> feat(utils): Adding Tracer component

- ui/app/AppLayouts/Wallet/popups/AddAccountModal.qml
- ui/app/AppLayouts/Wallet/stores/RootStore.qml
Fixes #6625 
Fixes #6983
Fixes issues regarding password checking and disabling "Add account" button, depending on used origin:
- Default / Imported
The "Add account" button is disabled always when password is incorrect (password is needed to fetch the derived addresses ist)
- Import new Seed Phrase / Generate from Private key
The password is checked when "Add account" is pressed and error label is set in the password is wrong
Moreover:
- js code modernized, "readonly" modifier added to properties where applicable
- some unnecessary checks removed
- password field cleared on close instead on open
`AddAccountModal`
https://user-images.githubusercontent.com/20650004/184322788-1706d451-b2d6-4feb-a271-03a9f46bf355.mp4
https://user-images.githubusercontent.com/20650004/184322793-3c15e8aa-8578-4 …
> fix(@desktop/wallet): add account - password checking adjusted

- ui/imports/shared/controls/chat/UserImage.qml
Closes #6852
Chat/UserImage: corrected user image dimensions
Chat/UserImage
Design:
https://user-images.githubusercontent.com/176720/183133173-32a68277-5eb5-4f46-a64d-ca60751e7a85.png
> fix(Chat/UserImage): corrected user image dimensions

- ui/app/AppLayouts/Onboarding/views/LoginView.qml
-use StatusQ with updated PopupMenu
Fixes #6822
Requires https://github.com/status-im/StatusQ/pull/853
Add binding for accountsPopup.topMargin to maintain it on same place when window is resized
Desktop Onboarding
https://user-images.githubusercontent.com/6445843/184600928-2a3afffa-4032-4631-8863-051dfa00a015.mp4
Latest version with StatusListView
https://user-images.githubusercontent.com/6445843/184636638-5e5bb59b-63ac-4b98-a7e9-dbe468b7908b.mp4
> fix(@desktop/onboarding): adapt account dropdown

- src/app/modules/main/communities/controller.nim
- src/app/modules/main/communities/io_interface.nim
- src/app/modules/main/communities/module.nim
- src/app/modules/main/communities/view.nim
- src/app_service/service/community/service.nim
- src/backend/communities.nim
- ui/app/AppLayouts/Chat/stores/RootStore.qml
- ui/app/AppLayouts/CommunitiesPortal/popups/CreateCommunityPopup.qml
- ui/app/AppLayouts/CommunitiesPortal/stores/CommunitiesStore.qml
- ui/app/AppLayouts/stores/RootStore.qml
- ui/nim-status-client.pro
as status-go already supports parsing the banner JSON string, just pass
it along the NIM backend
Closes #6726
Implements support for adding community banner on its creation
CreateCommunityPopup
Create community:
Edit community (for verification):
> feat(CreateCommunityPopup): Add Community Banner to Create Community Modal

- test/ui-test/src/drivers/SquishDriver.py
- test/ui-test/src/drivers/SquishDriverVerification.py
- test/ui-test/src/screens/SettingsScreen.py
- test/ui-test/src/screens/StatusLanguageScreen.py
- test/ui-test/testSuites/suite_status/shared/scripts/sections/settings_names.py
- test/ui-test/testSuites/suite_status/shared/steps/settingsSteps.py
- test/ui-test/testSuites/suite_status/suite.conf
- test/ui-test/testSuites/suite_status/tst_languageSettings/test.feature
- test/ui-test/testSuites/suite_status/tst_languageSettings/test.py
- ui/app/AppLayouts/Profile/panels/MenuPanel.qml
- ui/app/AppLayouts/Profile/views/LanguageView.qml
Closes #6903
`tst_languageSettings`:
- Feature and basic scenarios definition: Change language by selection and change language by search.
- Added `StatusLanguageScreen` class and related methods to change and validate language.
`SquishDriver`:
- Added support to scroll at a specific list view index.
- Added support  to directly type into a focused element.
`settings_names.py`:
- Added support for object names related to `side bar` options.
- Unified some nomenclature related to settings objects.
tst_languageSettings
- **Scenario 1:** Select by click, restart and validate
https://user-images.githubusercontent.com/97019400/184405485-e3f02350-5eca-440b-bd8f-f6741f864353.mov
- **Scenario 2:** Search and then select by click
https://user-images.githubusercontent.com/97019400/184405208-983f443a …
> test(Settings/Language): Can change language

- ui/app/AppLayouts/Chat/controls/community/CommunityDescriptionInput.qml
- ui/app/AppLayouts/Chat/controls/community/CommunityIntroMessageInput.qml
- ui/app/AppLayouts/Chat/controls/community/CommunityNameInput.qml
- ui/app/AppLayouts/Chat/controls/community/CommunityOutroMessageInput.qml
- ui/app/AppLayouts/Chat/popups/community/CreateChannelPopup.qml
- ui/app/AppLayouts/Profile/popups/SendContactRequestModal.qml
- ui/app/AppLayouts/Profile/popups/backupseed/BackupSeedStepBase.qml
- ui/imports/shared/popups/SendContactRequestModal.qml
Fixes #6825
Requires https://github.com/status-im/StatusQ/pull/858.
BREAKING CHANGE: many StatusInputs now validate on dirty and show error
when needed.
Use fixed version of StatusInput from StatusQ
Remove ValidationMode.Always for StatusInputs and use valid & dirty
instead to show error after any edit.
Remove condition from errorMessage of BackupSeedStepBase as not needed
Desktop Community and other.
https://user-images.githubusercontent.com/6445843/185095640-dbdb7c70-85b0-49e6-ba41-90ec232470e4.mp4
> fix(@desktop/community)!: missing error messages

- ui/imports/shared/status/StatusChatInput.qml
- ui/imports/shared/views/chat/ChatTextView.qml
- ui/imports/shared/views/chat/CompactMessageView.qml
Closes #6855
Chat/CompactMessageView: removed space above image in msg
Chat/CompactMessageView
> fix(Chat/CompactMessageView): removed space above image in msg

- test/ui-test/src/screens/StatusMainScreen.py
- test/ui-test/testSuites/suite_status/shared/scripts/sections/community_portal_names.py
- test/ui-test/testSuites/suite_status/shared/scripts/sections/global_names.py
The navbar didn't use a correct name and with a recent update to master, something broke.
> fix(community-test): fix community test not finding the nav bar

- ui/app/AppLayouts/Chat/popups/GroupInfoPopup.qml
Fixes #6970
Adjust Search member input paddings to exclude scrolling 
Desktop Chat
> fix(@desktop/chat): adjust search member input

- ui/imports/shared/status/StatusChatInput.qml
Fixes #7076
This PR is first from series of PRs aiming fixing issues related to copy/paste behavior of StatusChatInput
- Instantiator used instead of ListView to access model items (itemAtIndex from ListView could return null)
- role adjusted (name -> displayName)
- some minor refactor of related js code
https://user-images.githubusercontent.com/20650004/185583022-d9223b97-c06b-4328-957a-12ffcb3a32d2.mp4
> fix(StatusChatInput): infinite loop when pasting mention

- src/app_service/service/accounts/service.nim
- test/ui-test/src/screens/StatusMainScreen.py
- test/ui-test/testSuites/global_shared/scripts/global_names.py
- test/ui-test/testSuites/suite_onboarding/shared/steps/signUpSteps.py
- test/ui-test/testSuites/suite_onboarding/tst_statusSignUp/test.feature
- ui/app/mainui/AppMain.qml
fix(@desktop/profile): Can set own online state to online, offline
fixes #6854 
status-go: https://github.com/status-im/status-go/pull/2798
Implements a fix for and test case for User should be online after first time login
Wallet
> fix(@desktop/profile): first login shows state offline in the sidebar fixes #6854

- test/ui-test/src/drivers/SquishDriver.py
- test/ui-test/src/screens/SettingsScreen.py
- test/ui-test/src/screens/StatusCommunityScreen.py
- test/ui-test/testSuites/suite_status/shared/scripts/debug_helpers.py
- test/ui-test/testSuites/suite_status/shared/scripts/sections/settings_names.py
- test/ui-test/testSuites/suite_status/shared/steps/settingsSteps.py
- test/ui-test/testSuites/suite_status/tst_settingsMenu/test.feature
- ui/app/AppLayouts/Profile/popups/BackupSeedModal.qml
- ui/app/AppLayouts/Profile/popups/backupseed/Acknowledgements.qml
- ui/app/AppLayouts/Profile/popups/backupseed/BackupSeedStepBase.qml
- ui/app/AppLayouts/Profile/popups/backupseed/ConfirmSeedPhrasePanel.qml
- ui/app/AppLayouts/Profile/popups/backupseed/ConfirmStoringSeedPhrasePanel.qml
Extra changes
- Added debug helpers found useful in debugging while implementing squish
tests
Closes: #6902
> tests(Settings): Can backup seed phrase

- test/ui-test/src/screens/StatusMainScreen.py
- test/ui-test/testSuites/suite_status/shared/scripts/sections/settings_names.py
- test/ui-test/testSuites/suite_status/shared/steps/settingsSteps.py
- test/ui-test/testSuites/suite_status/tst_settingsMenu/test.feature
- ui/imports/shared/popups/UserStatusContextMenu.qml
fix(@desktop/wallet): Added squish test for the user being able to turn his state to online and/or offline
fixes #6895 
Added test case to make sure user is able to suceesfully set is status to online and offline
Wallet
> fix(@desktop/wallet): Added squish test for the user being able to turn his state to online and/or offline

- .gitignore
- Makefile
- src/app_service/service/accounts/service.nim
To output the messages to a csv file, execute:
`make run OUTPUT_CSV=true`
Requires
- https://github.com/status-im/status-go/pull/2737
> feat: output messages to csv

- src/app/global/local_account_sensitive_settings.nim
- ui/app/AppLayouts/Chat/panels/communities/CommunityOverviewSettingsPanel.qml
- ui/app/AppLayouts/CommunitiesPortal/CommunitiesPortalLayout.qml
- ui/app/AppLayouts/CommunitiesPortal/popups/CreateCommunityPopup.qml
- ui/app/AppLayouts/Profile/stores/AdvancedStore.qml
- ui/app/AppLayouts/Profile/views/AdvancedView.qml
- ui/imports/shared/panels/CommunityBanner.qml
- ui/imports/shared/panels/qmldir
This adds a feature flag for the discord import tool so we can start
landing individual pieces of the feature without it being fully
implemented.
It also introduces the modal chooser for creating new communities but
it doesn't do anything more than that, as of this commit
Co-authored with @caybro 
Closes #6843
> feat(AdvancedView): introduce feature flag for discord import tool

- ui/app/mainui/AppMain.qml
Closes: #6767
In general, `toastArea` (which is `StatusListView`) missed `width` and also I it use `anchors` to parent - it block mouse clicks under toast notifications area.
AppMain
> fix(toast-notifications): Fix notifcations listview sizes

- test/ui-test/testSuites/suite_status/shared/steps/chatSteps.py
- test/ui-test/testSuites/suite_status/tst_ChatFlow/test.feature
Closes: #7019
The original `send message` will be failed if `:)` replaced by 🙂. I add method to send a message without verification
Add test for emoji auto replacing 
UI tests
> test(chat): Emoji autoreplace

- test/ui-test/src/screens/SettingsScreen.py
- test/ui-test/src/screens/StatusMainScreen.py
- test/ui-test/src/screens/StatusWalletScreen.py
- ui/imports/shared/views/AssetsView.qml
The test network was toggled twice. The banner was impeding with the wallet setting click. The asset list item was missing the objectName and also checking the balance was not resilient
> fix(wallet-test): fix balance test

- ui/app/AppLayouts/Onboarding/panels/AccountMenuItemPanel.qml
- ui/app/AppLayouts/Onboarding/views/LoginView.qml
Fix #7045
Hides chosen account from the accounts list
Onboarding
> fix(@desktop/onboarding): Hide current account from accounts list

- src/app/modules/main/chat_section/controller.nim
- src/app/modules/main/chat_section/module.nim
- src/app/modules/main/profile_section/contacts/controller.nim
- src/app/modules/main/profile_section/contacts/module.nim
- src/app/modules/shared_models/user_item.nim
- ui/app/AppLayouts/Chat/panels/communities/CommunityProfilePopupInviteFriendsPanel.qml
- ui/app/AppLayouts/Chat/panels/communities/CommunityProfilePopupInviteMessagePanel.qml
- ui/app/AppLayouts/Chat/popups/community/InviteFriendsToCommunityPopup.qml
- ui/imports/shared/views/ExistingContacts.qml
- ui/imports/shared/views/PickedContacts.qml
Fixes #6985
Add online status indication to Community invite modal.
Replace Contact component with StatusMemberListItem.
Add missing Nim functions to fill models with onlineStatus.
Adjust components paddings to match design. 
https://user-images.githubusercontent.com/6445843/186401891-3f70efb6-0305-4a3f-a43d-aa6979c40e7d.mp4
> fix(@desktop/community): add online status to invite modal

- src/app/modules/startup/controller.nim
- src/app/modules/startup/io_interface.nim
- src/app/modules/startup/module.nim
- src/app/modules/startup/view.nim
- src/app_service/service/accounts/service.nim
- ui/app/AppLayouts/Onboarding/stores/StartupStore.qml
- ui/app/AppLayouts/Onboarding/views/CreatePasswordView.qml
fix(@desktop/wallet): Assign an emoji to the default wallet account during onboarding
fixes #6694
Sets a random emoji for the default wallet during onboarding. This is done by setting it during the create password step from the UI.
Wallet
https://user-images.githubusercontent.com/60327365/186653142-0640eadb-3831-4465-86c4-c2f32e34f2f7.mov
> fix(@desktop/wallet): Assign an emoji to the default wallet account during onboarding

- ui/app/AppLayouts/Wallet/panels/DerivedAddressesPanel.qml
- ui/app/AppLayouts/Wallet/panels/ImportPrivateKeyPanel.qml
- ui/app/AppLayouts/Wallet/popups/AddAccountModal.qml
- ui/imports/utils/Utils.qml
Remove the unneeded native error dialog showing internal status-go
error strings. Instead redirect the error message for wrong private key
as a specific error message.
Notes:
- I find the back and forth of data and states between `AddAccountModal` , `AdvancedAddAccountView` and `ImportPrivateKey` cumbersome. However, I consider the big refactoring not worth the effort given the upcoming redesign and the importance of the Private Key Import feature.
- `StatusAsyncValidator` has a complex pulling mechanism and something else would have been better alternative, though not worth the investigation due to low feature importance.
Wallet - Add a private key account
> fix(Wallet/AddAccountModal): fix status-go error messages

- ui/imports/utils/Global.qml
strip the URL from any HTML tags before trying to open it; Qt sometimes
likes to leave some HTML tags there and that breaks the URL validity
checks further on
Fixes: #7170
Fixes opening URLs in browser in some cases
Global/openLink()
> fix(Global): 'Open in Browser' doesn't work in chat

- ui/imports/shared/status/StatusChatInput.qml
Requires https://github.com/status-im/StatusQ/pull/868
Fixes #7093
Fixes #7171
Calls ensureVisible for Flickable container of ChatInput to ensure cursor is visible.
Desktop Chat
https://user-images.githubusercontent.com/6445843/186673886-f46e48c2-89f6-48f6-946d-2d3690878210.mp4
> fix(@desktop/chat): add autoscroll to cursor in chat input

- src/app/core/signals/remote_signals/signal_type.nim
- src/app/core/signals/remote_signals/status_updates.nim
- src/app/core/signals/signals_manager.nim
- src/app/core/signals/types.nim
- src/app_service/service/contacts/service.nim
Issue #6403
Remove timers logic since the logic was moved to status-go.
Handle additional status.updates.timedout signal. This signal inform about Inactive state of contacts with Automatic statuses which has been offline for more than 5 minutes.
Testing scenario:
1. Start 2 application instances. Both accounts should be contacts
2. Set Automatic status in 1st account and close the application
3. The 2nd account should see 1st account as online for 5 minutes.
4. After that time the status of 1st account should change to Inactive.
🍺
> fix(@desktop): Fixing setting contacts statuses

- src/app/modules/main/chat_section/chat_content/messages/io_interface.nim
- src/app/modules/main/chat_section/chat_content/messages/module.nim
- src/app/modules/main/chat_section/chat_content/messages/view.nim
- src/app/modules/main/chat_section/chat_content/module.nim
- src/app/modules/main/chat_section/chat_content/view.nim
- src/app/modules/main/chat_section/controller.nim
- src/app/modules/main/chat_section/io_interface.nim
- src/app/modules/main/chat_section/module.nim
- src/app_service/service/chat/dto/chat.nim
- src/app_service/service/chat/service.nim
- src/backend/chat.nim
- ui/app/AppLayouts/Chat/popups/GroupInfoPopup.qml
- ui/app/AppLayouts/Chat/popups/RenameGroupPopup.qml
- ui/app/AppLayouts/Chat/stores/MessageStore.qml
- ui/app/AppLayouts/Chat/views/ChatContentView.qml
- ui/app/AppLayouts/Chat/views/ChatContextMenuView.qml
- ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
- ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
- ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
- ui/imports/shared/views/chat/MessageView.qml
- ui/imports/utils/Utils.qml
This is a continuation of #6464
The user is able to change group chat's image. The image is cropped correctly and propagated to other chat members.
Required: https://github.com/status-im/status-go/pull/2797
Groupchat
https://user-images.githubusercontent.com/61889657/184336256-a46f0269-8cdb-470e-88e5-cba58ab52d6b.mov
> 6466 group chat image

- ui/imports/shared/controls/SearchBox.qml
- ui/imports/shared/status/StatusChatInput.qml
- ui/imports/shared/status/StatusEmojiPopup.qml
- ui/imports/shared/status/StatusEmojiSection.qml
Please see the individual commits for the bug fixes; it made sense to group these fixes in one PR as they all happen in one file and the individual changes would conflict with each other
Closes #7174
Closes #7175
StatusEmojiPopup
Clear button margins fixed:
Flags section aligned correctly:
Overall emoji popup alignment (y-pos) fixed:
> fix(StatusEmojiPopup): various UI fixes

- ui/main.qml
Fixes #6630
Use system theme while onboarding visible.
Desktop Onboarding
https://user-images.githubusercontent.com/6445843/187663392-7885b78f-7ac8-43d0-ad5a-48c643c22f94.mov
> fix(@desktop/onboarding): use system theme while onboarding

- ui/imports/shared/status/StatusChatInput.qml
Fixes #7094
Add logic to capture emoji popup by changing parent and close policy on emoji popup open from Chat input, also release by reverting those properties when emoji popup is closed.
Desktop Chat
https://user-images.githubusercontent.com/6445843/187939475-0e81ad72-8fb3-403d-8fab-75b51df9db69.mp4
> fix(@desktop/chat): adjust emoji popup behaviour

- src/app_service/service/transaction/service.nim
The error seen in the bug is linked to getSuggestedFees returning an rpc error that was unhandled, I think this should resolve this issue.
fixes #6801
The error seen in the bug is linked to getSuggestedFees returning an rpc error that was unhandled, I think this should resolve this issue.
Wallet
> fix(@desktop/wallet): Wallet - Send - Crash after opening send modal

- ui/app/AppLayouts/Profile/views/MessagingView.qml
- ui/imports/shared/status/StatusGifPopup.qml
- ui/imports/shared/status/StatusGifPopup/ConfirmationPopup.qml
- ui/imports/shared/status/StatusGifPopup/EmptyPlaceholder.qml
- ui/imports/shared/status/StatusGifPopup/GifPopupDefinitions.qml
- ui/imports/shared/status/StatusGifPopup/StatusGifColumn.qml
- ui/imports/shared/status/qmldir
- ui/imports/shared/stores/RootStore.qml
- ui/imports/shared/views/chat/LinksMessageView.qml
- ui/imports/shared/views/chat/MessageView.qml
Depends on the [status-go PR](https://github.com/status-im/status-go/pull/2832)
Enable preview for gifs after enabling the gif functionality
Disable gif functionality if the preview was disabled
Addition fixes
- The gifs weren't checked if all images weren't enabled
- The subdomain wasn't checked for whitelisting if the main domain wasn't enabled
Chat workflow for gif popup and link unfurling
https://user-images.githubusercontent.com/47554641/187740744-adcfff22-3c2d-4958-9bf7-5df4888b39f7.mov
I considered having the "gif enabled" - "tenor unfurling" relation embedded in the controller but it would require extensive refactoring by implementing a data-model for unfurling whitelisted domains
> fix(Chat): improve gif confirmation popup and fix preview whitelisting

- ui/app/mainui/AppMain.qml
Fixes #7197
Fixes Profile button size after changing language in Settings
AppMain/ProfileButton
English:
Arabic:
> fix(AppMain): profile image doesn't look good after changing language

- ui/app/AppLayouts/Profile/views/LanguageView.qml
- pull in required StatusQ changes (see status-im/StatusQ#882)
- simplify the radio buttons handling, no need for a ButtonGroup as they
share the same parent
- the radio buttons have the desired font size as a result ;)
Merely pulls in required StatusQ changes and simplifies the code
Settings/LanguageView
> fix(LanguageView): simplify the radio buttons handling

- ui/app/AppLayouts/Chat/controls/community/CollectiblesPanel.qml
- ui/app/AppLayouts/Chat/controls/community/EnsPanel.qml
- ui/app/AppLayouts/Chat/controls/community/ExtendedDropdownContent.qml
- ui/app/AppLayouts/Chat/controls/community/HoldingsDropdown.qml
- ui/app/AppLayouts/Chat/controls/community/HoldingsTabs.qml
- ui/app/AppLayouts/Chat/controls/community/ListDropdownContent.qml
- ui/app/AppLayouts/Chat/controls/community/OperatorsSelector.qml
- ui/app/AppLayouts/Chat/controls/community/TokensPanel.qml
- ui/app/AppLayouts/Chat/layouts/SettingsPageLayout.qml
Fixes: https://github.com/status-im/status-desktop/issues/6338
Addition of the ENS panel and changes to the existing functionality, which was the very first version (still using mocked backend) and therefore required some changes.
commit 1: HoldingsDropdown refactor
- decomposed into set of separate components
- reduced number of magic numbers
- code duplication reduced
- minor adjustments with design
commit 2:
- ENS panel added & initially integrated to "Who holds" selector
depends on https://github.com/status-im/StatusQ/pull/875
Community settings -> permissions, HoldingsDropdown component
https://user-images.githubusercontent.com/20650004/187688346-c7d51f02-b5b2-46f9-9ce9-409fac9f7b7a.mp4
> feat(@desktop/communities) Permissions - ENS panel added to "Who holds" selector

- ui/app/AppLayouts/Chat/controls/community/HoldingTypes.qml
- ui/app/AppLayouts/Chat/controls/community/HoldingsDropdown.qml
- ui/app/AppLayouts/Chat/controls/community/HoldingsTabs.qml
- ui/app/AppLayouts/Chat/stores/CommunitiesStore.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityNewPermissionView.qml
Adds possibility to edit and remove items from the "Who holds" section of the "New permission" page.
Closes #6339
Depends on https://github.com/status-im/StatusQ/pull/887
Community settings -> permissions, HoldingsDropdown component
https://user-images.githubusercontent.com/20650004/188904493-20f90696-922c-4474-884a-b83c0b55687c.mp4
> feat(@desktop/communities) Permissions - holdings edit and remove

- ui/app/AppLayouts/Wallet/popups/AddAccountModal.qml
probably a leftover from the StatusAssetSettings porting (plus remove some non-existing functions)
Fixes setting an emoji for a new account
AddAccountModal
> hotfix(AddAccountModal): fix setting account emoji

- ui/app/AppLayouts/Profile/views/profile/MyProfileSettingsView.qml
Fix #7177
Change Profile display name validationMode to force validation of name.
Desktop Settings
https://user-images.githubusercontent.com/6445843/189145573-4b17c371-3cd8-4e96-93bb-c508c9603059.mp4
> fix(@desktop/settings): update display name validation to unblock saveability

- ui/app/AppLayouts/Chat/popups/GroupInfoPopup.qml
- ui/app/AppLayouts/Chat/views/ChatHeaderContentView.qml
Fix #7242 and #7247
Shows group chat image correctly in a few places.
1. Create a group chat
2. Set group chat image (chat context menu -> "Edit name and image")
3. Verify if image was set
4. Pin some messages in a chat
5. Click on pin icon in chat info button
6. Pin icon should work correctly 
Pinned messages button fixed
🍺
> fix(@desktop/chat): Fix showing groupchat image in a few places

- ui/imports/shared/status/StatusChatInput.qml
Fixes #7131
Change message length check condition to allow sending 2000 chars message.
Desktop Chat
https://user-images.githubusercontent.com/6445843/189399107-2b9b3b2e-c0a3-4b23-a953-f4b3e6ae0e78.mp4
> fix(@desktop/chat): adjust message length check condition

- src/app/modules/main/wallet_section/saved_addresses/controller.nim
- src/app/modules/main/wallet_section/saved_addresses/io_interface.nim
- src/app/modules/main/wallet_section/saved_addresses/item.nim
- src/app/modules/main/wallet_section/saved_addresses/model.nim
- src/app/modules/main/wallet_section/saved_addresses/module.nim
- src/app/modules/main/wallet_section/saved_addresses/view.nim
- src/app_service/service/saved_address/dto.nim
- src/app_service/service/saved_address/service.nim
- src/backend/backend.nim
- ui/app/AppLayouts/Wallet/popups/AddEditSavedAddressPopup.qml
- ui/app/AppLayouts/Wallet/stores/RootStore.qml
- ui/app/AppLayouts/Wallet/views/SavedAddressesView.qml
- ui/imports/shared/controls/SavedAddressesDelegate.qml
- ui/imports/shared/popups/AddEditSavedAddressPopup.qml
- ui/imports/shared/stores/RootStore.qml
- ui/imports/shared/views/TransactionDetailView.qml
Depends on `status-go`'s API change [in review PR #2844](https://github.com/status-im/status-go/pull/2844)
Notes
- Remove duplicate name instead of ESN
- Fixes elide address
Wallet - Saved Addresses
| Implementation | Design |
| :-: | :-: |
| ![image](https://user-images.githubusercontent.com/47554641/185463363-d46d1833-d0a6-40d0-a1b8-9afe37817faa.png) | ![image](https://user-images.githubusercontent.com/47554641/185463531-920b7675-181b-490d-a355-28ee27d14759.png) |
> feat(wallet): favorites for saved addresses

- ui/app/AppLayouts/Chat/panels/UserListPanel.qml
Unbreaks the context menu of UserListPanel
StatusAssetSettings porting leftover (split into 2 commits for better legibility)
Closes #7302
UserListPanel
> fix: unbreak User List Panel context menu

- ui/app/AppLayouts/Profile/views/ContactsView.qml
- ui/app/AppLayouts/Profile/views/SettingsContentBase.qml
Fixed #7296
Adjust paddings and spacing in Settings -> Contacts
Desktop Settings
> fix(@desktop/settings): adjust contacts settings

- ui/app/AppLayouts/Chat/panels/ActivityCenterPopupTopBarPanel.qml
- ui/app/AppLayouts/Chat/popups/ActivityCenterPopup.qml
- ui/app/AppLayouts/Chat/views/ActivityCenterGroupRequest.qml
- ui/app/AppLayouts/Chat/views/ActivityCenterMessageComponentView.qml
Close #7161
This PR contains is a preparation for new notification categories listed in this epic: *[***](https://github.com/status-im/status-desktop/issues/7070)
> feat:(@desktop/activity-center): AC notification categories according new designs

- ui/app/AppLayouts/Browser/popups/AddFavoriteModal.qml
- ui/app/AppLayouts/Chat/popups/community/TransferOwnershipPopup.qml
- ui/app/AppLayouts/CommunitiesPortal/CommunitiesPortalLayout.qml
- ui/app/AppLayouts/Profile/panels/CommunitiesListPanel.qml
- ui/app/AppLayouts/Profile/popups/BackupSeedModal.qml
- ui/app/AppLayouts/Profile/popups/SendContactRequestModal.qml
- ui/app/AppLayouts/Wallet/panels/DerivationPathsPanel.qml
- ui/app/AppLayouts/Wallet/popups/ReceiveModal.qml
- ui/imports/shared/controls/GasSelector.qml
- ui/imports/shared/popups/SendModal.qml
- ui/imports/shared/status/StatusGifPopup/StatusGifColumn.qml
- ui/imports/shared/views/NetworksAdvancedCustomRoutingView.qml
- ui/imports/shared/views/SendModalFooter.qml
- ui/imports/shared/views/SendModalHeader.qml
- ui/imports/shared/views/chat/InvitationBubbleView.qml
unbreaks the startup due to changes in StatusQ/master StatusButton implementation
ALL
> fix: port to StatusButton changes in master

- ui/app/AppLayouts/Chat/panels/communities/BackUpCommuntyBannerPanel.qml
- ui/app/AppLayouts/Chat/views/ChatHeaderContentView.qml
- ui/app/AppLayouts/Chat/views/ChatView.qml
- ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
Small fixes for various issues related to chat header functionality (split into separate commits for better legibility)
- a StatusButton porting leftover (Backup community dialog was broken)
- fix for the Edit community popup emoji selector
- tooltip fix for the community Start chat button
- port changes for StatusChatInfoButton (fixes #7313)
Chat/ChatHeader
Pin counter and new StatusChatInfoButton in the chat toolbar:
Emoji selector in the Edit channel dialog:
Backup community dialog:
Start chat tooltip fixed:
> fix: chat header fixes

- ui/app/AppLayouts/Chat/popups/PinnedMessagesPopup.qml
- ui/app/AppLayouts/Chat/views/ChatColumnView.qml
- ui/app/AppLayouts/Chat/views/ChatContentView.qml
- ui/app/AppLayouts/Chat/views/ChatView.qml
- ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
- ui/imports/shared/views/chat/MessageView.qml
- align the dialog to design
- fix radio button logic (it was possible to uncheck a mutually exclusive checked button eventhough it's inside the button group, leaving the Unpin button in an undefined state)
- port to StatusDialog and layouts, dropping a lot of needless code
- remove dead code for passing around the `property Component pinnedMessagesListPopupComponent`; the popup is being invoked via `Global.openPopup()`
- hide quick (hover button) actions inside this popup
Fixes #7315 
Fixes #7316 
Fixes various issues with PinnedMessagesPopup
Pinned messages overview:
Choosing a message to unpin (nothing selected yet):
Message to unpin selected:
> fix(PinnedMessagesPopup): pinned messages modal design issues

- src/app/modules/shared_modules/keycard_popup/internal/create_pin_state.nim
- src/app/modules/shared_modules/keycard_popup/internal/enter_pin_state.nim
- src/app/modules/shared_modules/keycard_popup/internal/enter_seed_phrase_state.nim
- src/app/modules/shared_modules/keycard_popup/internal/factory_reset_confirmation_displayed_metadata_state.nim
- src/app/modules/shared_modules/keycard_popup/internal/factory_reset_confirmation_state.nim
- src/app/modules/shared_modules/keycard_popup/internal/factory_reset_success_state.nim
- src/app/modules/shared_modules/keycard_popup/internal/insert_keycard_state.nim
- src/app/modules/shared_modules/keycard_popup/internal/key_pair_migrate_failure_state.nim
- src/app/modules/shared_modules/keycard_popup/internal/keycard_empty_metadata_state.nim
- src/app/modules/shared_modules/keycard_popup/internal/keycard_empty_state.nim
- src/app/modules/shared_modules/keycard_popup/internal/keycard_inserted_state.nim
- src/app/modules/shared_modules/keycard_popup/internal/keycard_locked_state.nim
- src/app/modules/shared_modules/keycard_popup/internal/keycard_metadata_display_state.nim
- src/app/modules/shared_modules/keycard_popup/internal/keycard_not_empty_state.nim
- src/app/modules/shared_modules/keycard_popup/internal/max_pin_retries_reached_state.nim
- src/app/modules/shared_modules/keycard_popup/internal/migrating_key_pair_state.nim
- src/app/modules/shared_modules/keycard_popup/internal/not_keycard_state.nim
- src/app/modules/shared_modules/keycard_popup/internal/pin_set_state.nim
- src/app/modules/shared_modules/keycard_popup/internal/pin_verified_state.nim
- src/app/modules/shared_modules/keycard_popup/internal/plugin_reader_state.nim
- src/app/modules/shared_modules/keycard_popup/internal/reading_keycard_state.nim
- src/app/modules/shared_modules/keycard_popup/internal/recognized_keycard_state.nim
- src/app/modules/shared_modules/keycard_popup/internal/repeat_pin_state.nim
- src/app/modules/shared_modules/keycard_popup/internal/seed_phrase_display_state.nim
- src/app/modules/shared_modules/keycard_popup/internal/seed_phrase_enter_words_state.nim
- src/app/modules/shared_modules/keycard_popup/internal/select_existing_key_pair_state.nim
- src/app/modules/shared_modules/keycard_popup/internal/wrong_pin_state.nim
- src/app/modules/shared_modules/keycard_popup/internal/wrong_seed_phrase_state.nim
- ui/imports/shared/popups/keycard/KeycardPopup.qml
- ui/imports/shared/popups/keycard/states/KeycardPin.qml
A new rule introduced which should provide easier tracking/maintainig later. The rule says:
- popup contains up to 3 action buttons and one back button (optional)
- if 3 buttons are displayed in the popup then the most left button, but not back button, always triggers tertiary action, middle button always triggers secondary action and the most right button always triggers primary action
- if 2 buttons are displayed, then: 
- if one of them is "Cancel" (left button) it should trigger tertiary action and the other one (right button) should trigger primary action 
- if non of them is "Cancel" then the left button triggers secondary action and the right button triggers primary action
- if single button is displayed, then: 
- if it's "Cancel" it triggers tertiary action
- if it is not "Cancel" …
> refactor(@desktop/keycard): buttons' responibility in the keycard popup improved

- ui/app/mainui/AppMain.qml
Fixes app startup
Unbreaks app startup
AppMain
> hotfix: make sure to remove all references to pinnedMessagesListPopup

- ci/Jenkinsfile.combined
- ci/Jenkinsfile.linux
- ci/Jenkinsfile.linux-cpp
- ci/Jenkinsfile.macos
- ci/Jenkinsfile.macos-cpp.todo
- ci/Jenkinsfile.windows
- ci/Jenkinsfile.windows-cpp.todo
By using `s3cmd` through PowerShell instead of Git Bash we improve upload speeds on Windows slightly, as described here:
* https://github.com/status-im/infra-ci/issues/40
We also split uploads of 7z and EXE files into parallel steps. Though honestly I'd rather avoid uploading the duplicate EXE.
This should cut down the upload step to ~3 minutes instead of the usual ~6 minutes.
Requires:
* https://github.com/status-im/status-jenkins-lib/pull/43
> ci: fix upload speeds on Windows

- ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
Fixes #7370
Fixes unmuting a chat from the chat list
CommunityColumnView
> fix(CommunityColumnView): Mute button in the chat list is not working

- ui/app/AppLayouts/Chat/popups/PinnedMessagesPopup.qml
- sync StatusQ (corrects the spacing in "Pinned by author" message)
- and fix a typo
Fixes: #7305
Corrects the spacing in "Pinned by @author" message
StatusQ/StatusPinMessageDetails
> fix: correct the spacing in "Pinned by @author" message

- ui/imports/shared/popups/SendContactRequestModal.qml
Fixes: #7295
Fixes displaying user name and their compressed key in the Send Contact Request dialog
SendContactRequestModal
> fix(SendContactRequestModal): display userName + compressed key

- test/ui-test/src/drivers/SquishDriver.py
- test/ui-test/src/screens/SettingsScreen.py
- test/ui-test/src/screens/StatusChatScreen.py
- test/ui-test/testSuites/suite_status/shared/scripts/sections/chat_names.py
- test/ui-test/testSuites/suite_status/shared/scripts/sections/settings_names.py
- test/ui-test/testSuites/suite_status/shared/steps/chatSteps.py
- test/ui-test/testSuites/suite_status/shared/steps/settingsSteps.py
- test/ui-test/testSuites/suite_status/tst_ChatFlow/test.feature
- ui/app/AppLayouts/Profile/views/MessagingView.qml
- ui/imports/shared/views/chat/LinksMessageView.qml
The gif test was manually activating the unfurling, which is no longer necessary. Now check that enabling gifs will enable tenor unfurling
Also
- add a test for image unfurling and validate the unfurling image links components and preview settings.
- improve the scrolling API by adding an option to search for a specific component instead of hardcoding the count of steps
> tests(chat): adapt gif test and add image unfurling test

- test/ui-test/src/drivers/SquishDriver.py
- test/ui-test/src/screens/StatusWelcomeScreen.py
- test/ui-test/testSuites/global_shared/scripts/onboarding_names.py
- ui/app/AppLayouts/Onboarding/views/InsertDetailsView.qml
It seems due to the latest changes there are additional delays in transitioning to enable some of the controls that drive the onboarding workflow. This PR accounts for that and waits for components to become ready.
Still, it will be great to find out why are tests failing now. Why there is more delay in between some screen transitions?
> fix(tests): make onboarding test steps workflow working

- ui/app/AppLayouts/Chat/panels/UserListPanel.qml
Closes: #7309
Two fixes:
- current user's picture is always visible
- hide pictures off all members (excluding self) when "noOne" options is set
`UserListPanel`
https://user-images.githubusercontent.com/20650004/190635568-16a6a0df-3291-4411-b98d-192a402802e4.mp4
> fix(@chat/members): display member's picture according to settings

- src/app/modules/main/chat_section/chat_content/messages/view.nim
- ui/app/AppLayouts/Chat/popups/PinnedMessagesPopup.qml
- ui/app/AppLayouts/Chat/views/ChatContentView.qml
- ui/app/AppLayouts/Chat/views/ChatHeaderContentView.qml
- ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
- ui/imports/shared/views/chat/MessageView.qml
This was never implemented, eventhough a similar approach is used with the global AppSearch. Expose the method `scrollToMessage(messageId)` so that it can be called from QML directly.
Fixes #7375
Selecting the message to jump to:
Message selected & highlighted:
> fix(PinnedMessagesPopup): “Jump to” button doesn’t work in pinned messages popup

- ui/app/AppLayouts/Onboarding/controls/AccountViewDelegate.qml
- ui/app/AppLayouts/Profile/views/EnsTermsAndConditionsView.qml
- ui/app/AppLayouts/Wallet/controls/HeaderButton.qml
- ui/app/AppLayouts/Wallet/panels/SeedPhraseBackupWarning.qml
- ui/imports/Themes/Theme.qml
- ui/imports/shared/controls/RecipientSelector.qml
- ui/imports/shared/controls/StyledTextArea.qml
- ui/imports/shared/controls/StyledTextEdit.qml
- ui/imports/shared/controls/StyledTextField.qml
- ui/imports/shared/panels/Address.qml
- ui/imports/shared/panels/ModuleWarning.qml
- ui/imports/shared/panels/StyledText.qml
- ui/imports/shared/panels/TextWithLabel.qml
- ui/imports/shared/status/StatusChatInput.qml
- ui/imports/shared/status/StatusExpandableAddress.qml
- ui/imports/shared/status/StatusStickerButton.qml
- ui/imports/shared/status/StatusStickerPackDetails.qml
Updates StatusQ to version with StatusBaseButton font fixed. Additionally refactors fonts loading by hiding font variants and using single reference for given font in components regardless what weight is used.
Fixes: #7389
Fixes: #7359
StatusQ, ThemePalette
> fix(general): buttons font fixed, font loading refactored

- ui/app/AppLayouts/Profile/panels/ContactsListPanel.qml
- ui/app/AppLayouts/Profile/views/ContactsView.qml
- ui/app/AppLayouts/Profile/views/SettingsContentBase.qml
Closes #6262
All contacts should be shown in one long list, should the list is longer than the page, the page should scroll down
ContactsView
https://user-images.githubusercontent.com/31625338/189392161-7c795d4b-e851-48c3-b449-334505eb33a2.mov
https://user-images.githubusercontent.com/31625338/189392205-85d58715-62f2-4e6e-98b5-4208bbd0512c.mov
***The black images is list of dummy contacts
> fix(Profile/ContactsView): updated contacts layout

- ui/app/AppLayouts/Profile/views/profile/MyProfileSettingsView.qml
Fixes #7306
Fixes the biometrics switch entry's horizontal padding
MyProfileSettingsView
Before:
After:
> fix(MyProfileSettingsView): adjust biometrics switch padding

- ui/app/AppLayouts/Chat/views/ChatHeaderContentView.qml
for 1-to-1 chats; makes sense as you can't have chats with non-contacts anyway.
Other types of chats unaffected
Fixes: #7419
ChatHeaderContentView
1-to-1 chat:
Community chat:
> fix(ChatHeaderContentView): don't display "Contact" subtitle

- ui/app/AppLayouts/Chat/popups/PinnedMessagesPopup.qml
- ui/imports/shared/views/chat/MessageContextMenuView.qml
and remove the context actions we do not actually use
Fixes: #7439
Adds the "Unpin" action to the messages' context menu in this popup
Context menu:
Unpin action performed:
> feat(PinnedMessagesPopup): enable Unpin context menu entry

- ci/Jenkinsfile.linux
- ci/Jenkinsfile.linux-cpp
- ci/Jenkinsfile.macos
- ci/Jenkinsfile.macos-cpp.todo
- ci/Jenkinsfile.uitests
- ci/Jenkinsfile.windows
- ci/Jenkinsfile.windows-cpp.todo
In most cases developers only care about the most recent version.
> ci: abort old PR builds to make queue shorter

- ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
Fix #7379
Only admin can open community settings.
Community
https://user-images.githubusercontent.com/61889657/191026430-05bc1d95-cb7e-4eab-897d-04cc82a6a09b.mov
> fix(@desktop/community): Only admin can open community settings

- ui/app/AppLayouts/Chat/popups/community/TransferOwnershipPopup.qml
Closes #7412
Community/TransferOwnershipPopup: added right margin in copy button
Community/TransferOwnershipPopup
> fix(TransferOwnershipPopup): copy button right margin

- src/app_service/service/node_configuration/service.nim
Desktop should still connect to the waku2 nodes described in fleets.status.im
> chore: use enrtrees for status.* fleets instead of connecting directly to the nodes

- ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
remove the disastrous binding loop warning
Fixes: #7481
Fixes unclickable area at the bottom of the screen, overlapping messages, malfunctioning quick buttons and being unable to close the reply area
ChatMessagesView
> fix(ChatMessagesView): unbreak closing reply bubble

- src/app_service/service/chat/dto/chat.nim
Fix #7371
Do not show default chat identicon created by status-go.
Identicons can't be removed from status-go now, because they are still needed in mobile apps.
Chat
User w/o icon:
User with icon:
> fix(@desktop/chat): Do not show chat identicons

- ui/app/AppLayouts/Profile/panels/CommunitiesListPanel.qml
we want same icon sizes here, no matter if there's an image or not
Fixes: #7285
Unifies icon sizes in the communities list
CommunitiesListPanel
> fix(CommunitiesListPanel): set uniform icon size

- src/app_service/service/community/service.nim
Fixes #7380
After some investigation I found out that getChatById for new category channels is using wrong parameter.
Looks like old channels moved to new category already have correct chat.id and no need to search by fullChatId.
https://user-images.githubusercontent.com/6445843/190864893-4cd5f9d8-a49b-4adb-8dc8-9065c4114501.mp4
> fix(@desktop/community): update new category handling

- ui/app/AppLayouts/Chat/views/ChatContentView.qml
- ui/imports/shared/status/StatusChatInput.qml
Fixes #7220
After investigation I found that `replaceMentionsWithPubKeys` from `message.nim` always uses first known contact with some name which appears in message, and in case you have two or more contacts with same name the second one will never be used for replacing name with publicKey in message.
In order to have correct publicKeys instead of names I am adding `publicKey` into `mentionsPos` when inserting mentions into text. And instead of `textInput.text` I am using  `getTextWithPublicKeys` function when passing message to Chat RootStore. This function replaces names with publicKeys based on information from 'mentionPos' which has information about name, publicKey, leftIndex and rightIndex.
Desktop Chat
https://user-images.githubusercontent.com/6445843/191431123-1a31c74f-0137-4497-b6 …
> fix(@desktop/chat): handle same name mentions

- ui/imports/shared/popups/ConfirmationDialog.qml
Closes: #7519
Fixes the Remove Contact dialog being unavailable
ProfilePopup
> fix: "Remove contact" button in ProfilePopup doesn't work

- ui/imports/shared/views/chat/ChannelIdentifierView.qml
Fixes #7353
Adjust chat name properties to wrap on small width
Desktop Chat
https://user-images.githubusercontent.com/6445843/191476243-0c5dfcb0-b2d9-4971-87d1-f6c5e72c9be9.mp4
> fix(@desktop/chat): adjust chat name placement

- ui/app/AppLayouts/Chat/panels/InlineSelectorPanel.qml
Closes #7493
CreateChatView, disable confirm button if no tags added
CreateChatView
https://user-images.githubusercontent.com/31625338/192315035-70dd3648-0366-4aeb-ad8f-1202a0335479.mov
> fix(CreateChatView): disable confirm button if no tags added

- ui/imports/shared/views/SendModalHeader.qml
fixes #7427
Updated usage of the StatusButton in the SendModalHeader to make the text and emoji centre-aligned 
Wallet
> fix(@desktop/wallet): Fix the emoji and text placement in the SendModal

- ui/imports/shared/popups/ProfilePopup.qml
Closes #7521
Block contacts popup fixed display name
Block contacts popup
> fix(ProfilePopup): fixed display name on block popup

- src/app/core/signals/remote_signals/messages.nim
- src/app/core/signals/remote_signals/signal_type.nim
- src/app/core/signals/signals_manager.nim
- src/app/modules/main/chat_section/chat_content/messages/controller.nim
- src/app/modules/main/chat_section/chat_content/messages/io_interface.nim
- src/app/modules/main/chat_section/chat_content/messages/module.nim
- src/app/modules/shared_models/message_item.nim
- src/app/modules/shared_models/message_model.nim
- src/app_service/service/message/dto/message.nim
- src/app_service/service/message/service.nim
Fixes #7367
Add logic required to handle "message.delivered" signal for delivered messages.
Add logic required to handle "envelope.sent" signal for sent messages.
Desktop Chat
https://user-images.githubusercontent.com/6445843/192495691-9c569192-ca6d-4ae6-a6b6-7843640ecb8e.mp4
> fix(@desktop/chat): add message sent and delivered handler

- src/app/modules/main/module.nim
- src/app/modules/main/view.nim
- src/app/modules/shared_models/section_model.nim
- ui/app/mainui/AppMain.qml
- ui/imports/utils/Global.qml
Fix #7478
Ctrl+n shortcut changes enabled section.
User can switch only to sections which are visible on the left panel.
Sections panel.
https://user-images.githubusercontent.com/61889657/192762618-071f8a33-3ccf-45e7-8c54-531dd951f328.mov
> fix(@desktop/general): Fix sections switching shortcuts

- src/app/modules/main/module.nim
- src/app_service/service/contacts/service.nim
- ui/app/AppLayouts/Chat/panels/InlineSelectorPanel.qml
- ui/app/AppLayouts/Chat/views/CreateChatView.qml
- ui/app/AppLayouts/Chat/views/MembersSelectorView.qml
- ui/imports/shared/popups/ProfilePopup.qml
- ui/imports/shared/popups/SendContactRequestModal.qml
- ui/imports/shared/popups/qmldir
- ui/imports/utils/Global.qml
Fixes https://github.com/status-im/status-desktop/issues/7176
Open a "Send contact request" popup when user pastes a valid chat key to "create chat" text field.
Supported values are:
- Public key
- Public key wrapped in a URL
- Compressed key
- Compressed key wrapped in a URL
⚠️  I also made an important (but not a breaking) change - I switched `Global` root item from `QtObject` to `Item`, so that Components could be create right there. This is needed so that we could get the reference to created popup whenever we use `Global.openContactRequestPopup`. In this particular case we bind to it's `closed` signal.
⚠️ Also I made changes to Nim contacts service:
`getContactById` now supports compressed keys.
CreateChat, ProfilePopup
https://user-images.githubusercontent.com/25482501/190861714-7213 …
> feat(CreateChatView): Support pasting chat key

- ui/StatusQ/src/StatusQ/Controls/StatusChatInfoButton.qml
lower the spacing to better match the designs
Closes #7592
StatusChatInfoButton
> fix(StatusChatInfoButton): space between # and channel name

- ui/imports/shared/views/ProfileView.qml
Fixes #7538
Changed hardcoded name to the corresponding user name parameter.
Verify Identity popup
> fix(Chat/Verify Identity): Identity verification typo

- ui/imports/shared/views/ExistingContacts.qml
- ui/imports/shared/views/PickedContacts.qml
Fix #7477
Shows only members which are not community members.
Fixes member icons in the invitation message panel
Community , members list
> fix(@desktop/communities): Show only not community members

- ui/app/AppLayouts/Wallet/stores/RootStore.qml
The `RootStore` was calling `checkRecentHistory` on the wallet section `View` instead of the transaction `View`.
Still, the workflow is broken due to the 20 minutes timer that calls the `checkRecentHistory` and hangs the main thread (UI) for a long time
Required changes
- We do this on demand when `Load More` button is pressed which doesn't work for the newly sent transaction
- The button calls `transactions.view.nim->loadTransactionsForAccount` which doesn't update to include new transaction
Required improvements
- follow up issue https://github.com/status-im/status-desktop/issues/7530
Wallet activity tab view (transactions)
> fix(wallet): fix never fetching transactions

- Makefile
- src/app_service/service/accounts/service.nim
The environment variable overrides libp2p protocol TCP port and discovery v5 UDP with the same value
> chore(debug): use WAKUV2_PORT environment variable to change Waku V2 ports

- ui/StatusQ/src/StatusQ/Popups/StatusStackModal.qml
- ui/app/AppLayouts/Chat/ChatLayout.qml
- ui/app/AppLayouts/Chat/popups/PublicChatPopup.qml
- ui/app/AppLayouts/Chat/popups/community/CreateCategoryPopup.qml
- ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
- ui/app/AppLayouts/CommunitiesPortal/panels/CommunityColorPanel.qml
- ui/app/AppLayouts/CommunitiesPortal/panels/CommunityTagsPanel.qml
- ui/app/AppLayouts/CommunitiesPortal/popups/CreateCommunityPopup.qml
- ui/app/AppLayouts/Profile/popups/BackupSeedModal.qml
- ui/app/AppLayouts/Profile/popups/backupseed/Acknowledgements.qml
- ui/app/AppLayouts/Profile/popups/backupseed/BackupSeedStepBase.qml
In various popups with scrollable content, scrolled elements are cut-off too early because of clipping on Flickable directly. The clipping bounds are extended to achieve desired behavior.
Closes #7293
> fix(Popups): clipping area fixed in various popups

- src/app/modules/main/wallet_section/transactions/controller.nim
- src/app/modules/main/wallet_section/transactions/io_interface.nim
- src/app/modules/main/wallet_section/transactions/module.nim
- src/app/modules/main/wallet_section/transactions/view.nim
- ui/app/AppLayouts/Chat/stores/RootStore.qml
- ui/app/AppLayouts/stores/RootStore.qml
- ui/imports/shared/popups/SendModal.qml
Actually this is not a signing transaction, but rather authenticating logged in user when he wants to send a transaction. An authentication is done by entering password(regular user) or pin(keycard user).
A real signing transaction feature will be (hopefully) added in a near future where we're going to sign a transaction on a keycard which corresponds to a certain account, a user wants to send a transaction from.
To sum up... this change just removes password from the send modal and introduces `Authenticate` flow instead.
Fixes: #7510
> feat(@desktop/keycard): sign transaction using `Authenticate` flow

- Makefile
- src/app_service/service/accounts/dto/accounts.nim
- src/app_service/service/accounts/service.nim
- src/backend/accounts.nim
The following scenarios must be tested:
Login with an existing account
Login after changing the password
Exporting a database
New account creation
Creating an account with seed phrase
Creating an account with keycard
Login with keycard
Requires
- https://github.com/status-im/status-go/pull/2796
> feat: use a higher kdf number for DB encryption

- ci/Jenkinsfile.uitests
- ci/mailserver/config.json
- ci/mailserver/get_enode.sh
- src/app/modules/main/profile_section/sync/controller.nim
- src/app_service/service/accounts/service.nim
- src/app_service/service/mailservers/service.nim
- test/ui-test/testSuites/suite_status/tst_groupChat/test.feature
fixes #6999
- Creates a mailserver as part of the uitests
- Adds the `TEST_PEER_ENR` environment variable which should contain the enode address that will be added as a peer, bootnode and pinned mailserver.
> chore: setup a mailserver as part of UI tests run in CI

- ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
Direct binding was causing problems with height calculation in some environments (qt 5.15) and lack of binding in other (5.14). This is a solution which seems to work in both cases.
Closes: #7703
`ChagMessagesView`
> fix(ChatMessageView): delayed binding for proper msg height calculation

- ui/app/AppLayouts/Chat/views/ChatContentView.qml
- ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
- ui/imports/shared/status/StatusChatInput.qml
- ui/imports/shared/status/StatusChatInputReplyArea.qml
- remove the extra spinner (ok'ed by John and Benj)
- use the more modern StatusIcon, w/o the unconditional ColorOverlay
- some minor cleanup
Closes: #7645
Fixes visual glitch in the bottom right corner
ChatMessagesView
Before:
After:
> fix(ChatMessagesView): Loading spinner and scroll to bottom button overlap

- ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
Reverts https://github.com/status-im/status-desktop/pull/7721
It turned out that it doesn't work as expected - causes scrolling slow in both 5.14.2 and 5.15.
Reverts https://github.com/status-im/status-desktop/pull/7485
This PR was solving problem of overlapping messages in 5.15 but introduces that problem to builds based on 5.14, which is currently used for building packages on CI.
Original issues: https://github.com/status-im/status-desktop/issues/7703, https://github.com/status-im/status-desktop/issues/7481
`ChatMessagesView`
> fix(ChatMessagesView): reverts in chat messages view

- src/app/modules/main/ephemeral_notification_item.nim
- src/app/modules/main/ephemeral_notification_model.nim
- ui/app/mainui/AppMain.qml
Fixes #7487
Fixes #7613
Change usage of id(int64) to timestamp(string) for EphemeralNotification because there is an issue with passing int64 from Nim to QML, which was resulting in incorrect ids when using them for interaction with Nim from QML
Desktop Chat
https://user-images.githubusercontent.com/6445843/193087297-52272aff-112b-41d4-b923-93484d7e0bfd.mp4
NOTE: In video you can see model.id and model.timestamp in Toast messages.
> fix(@desktop/chat): update toast message logic

- ui/StatusQ/src/StatusQ/Core/StatusProfileImageSettings.qml
- ui/imports/shared/views/chat/MessageView.qml
This broke with the introduction of discord messages because we were setting the `assetSettings.isImage = true` when `isDiscordMessage`.
This has overriden the default config for all non discord messages which check for whether the asset source includes `("data")`.
> fix(Chat): ensure profile image with base64 sources are working

- src/app_service/service/language/service.nim
- ui/app/AppLayouts/Profile/views/LanguageView.qml
Will temporary fix #7709
- Enabled restart info popup after language is changed --> Workaround to temporary resolve the crash we have when language is changed (`startupModule` is null and some qml bindings are still calling this dead pointer) so, change language will not retranslate and instead, also on mac and win, the app will need a restart to apply the new language.
- Disabled retranslations for all os on the corresponding service.
Language change / windows and mac
> fix(Language): App crashes when language is changed

- ui/app/AppLayouts/Chat/views/ChatHeaderContentView.qml
Instead of being unreachable under bell icon, icons are placed over chat name with some semi transparent background for readability.
Closes: #7647
`ChatHeaderContentView`
[Kazam_screencast_00037.webm](https://user-images.githubusercontent.com/20650004/194289416-be90ae60-27e5-4db4-ba75-b6abdbd78190.webm)
> fix(ChatHeaderContentView): Unreachable buttons in community header at min width

- ui/imports/shared/status/StatusChatInput.qml
It fixes the issue causing that copying text in `StatusChatInput` containing `@` resulted in replacing `underline` to `none`.
Closes: #7109
`StatusChatInput`
[simplescreenrecorder-2022-10-12_10.27.53.webm](https://user-images.githubusercontent.com/20650004/195292658-22f2f297-5913-48c1-9597-3ad56f34aae5.webm)
> fix(StatusChatInput): paste mentions without changing msg content

- src/app/modules/main/controller.nim
- src/app/modules/main/io_interface.nim
- src/app/modules/main/module.nim
Part of: #7072
Add ephemeral notification when request to join was sent
Community
> feat(Community): Add ephemeral notification when request to join was sent

- ui/app/AppLayouts/Onboarding/views/KeysMainView.qml
This workflow doesn't save the keystore files which are required in order to create new wallet accounts. It is not yet clear how to proceed with saving the keystore files without an `accountId`. See `setupAccountKeycard` which is missing `storeAccount*` calls vs working workflow done in `setupAccount`
Closes: #7867
New onboarding flow:
> fix(Keycard): disable onboarding keycard login feature

- storybook/main.qml
It adds possibility of loading pages in Storybook asynchronously.
Note: As presented in the video it unveils problem in `StatusCommunityTags` component. It also causes problems with size of this component in the app, it's reported as a separate issue - https://github.com/status-im/status-desktop/issues/7870.
Closes: #7868
`Storybook`
[Kazam_screencast_00049.webm](https://user-images.githubusercontent.com/20650004/195329645-914e755f-b3e7-4158-9714-2983a28683fe.webm)
> feat(Storybook): Allow loading pages asynchronously

- ui/app/AppLayouts/Chat/popups/PinnedMessagesPopup.qml
- ui/imports/shared/views/chat/MessageContextMenuView.qml
Fixes wrong menu items in pinned messages popup
Additionally, unbreak the "Jump to" menu item functionality
Fixes #7853
User context menu:
Selecting the "Jump to" item:
Message jumped to:
> fix: wrong menu items in pinned messages popup

- ui/app/mainui/AppMain.qml
Active/hovered communities have proper color.
Closes: #7763
`AppMain`
> fix(AppMain): Community color shown in left bar

- src/app/core/signals/remote_signals/messages.nim
There's something off with the `savedAddresses` signal data, which causes it to be `JNull` instead of an empty array (`JArray`) and breaks signal decoding.
Ultimately this should be fixed in status-go, but this unblocks Desktop.
> fix(signals_manager): ensure `savedAddresses` event has `JNull` check

- src/app/core/signals/remote_signals/messages.nim
This includes a fix in message signals that would otherwise break Desktop's signal encoding.
See: https://github.com/status-im/status-desktop/pull/7888
Hence, it reverts the now unnecessary fix introduced in:
Revert "fix(signals_manager): ensure `savedAddresses` event has `JNull` check"
This reverts commit 013e226c66fc9de26575b5bd55acc64c45a5566e.
> chore: update status-go

- src/app/modules/main/profile_section/keycard/controller.nim
- src/app/modules/main/profile_section/keycard/io_interface.nim
- src/app/modules/main/profile_section/keycard/module.nim
- src/app/modules/main/profile_section/keycard/view.nim
- src/app/modules/shared_modules/keycard_popup/controller.nim
- src/app/modules/shared_modules/keycard_popup/internal/migrating_key_pair_state.nim
- src/app/modules/shared_modules/keycard_popup/internal/reading_keycard_state.nim
- src/app/modules/shared_modules/keycard_popup/internal/wrong_keycard_state.nim
- src/app/modules/shared_modules/keycard_popup/io_interface.nim
- src/app/modules/shared_modules/keycard_popup/models/key_pair_item.nim
- src/app/modules/shared_modules/keycard_popup/models/keycard_item.nim
- src/app/modules/shared_modules/keycard_popup/models/keycard_model.nim
- src/app/modules/shared_modules/keycard_popup/module.nim
- src/app_service/service/wallet_account/key_pair_dto.nim
- src/app_service/service/wallet_account/service.nim
- ui/app/AppLayouts/Profile/ProfileLayout.qml
- ui/app/AppLayouts/Profile/stores/KeycardStore.qml
- ui/app/AppLayouts/Profile/views/KeycardView.qml
- ui/app/AppLayouts/Profile/views/SettingsContentBase.qml
- ui/app/AppLayouts/Profile/views/keycard/DetailsView.qml
- ui/app/AppLayouts/Profile/views/keycard/MainView.qml
- ui/imports/shared/popups/keycard/KeycardPopup.qml
- ui/imports/shared/popups/keycard/helpers/KeycardItem.qml
- ui/imports/shared/popups/keycard/helpers/qmldir
- ui/imports/shared/popups/keycard/states/KeycardInit.qml
Keycard settings view - UI - developed in a way that list of keycards is displayed
if there is at least one keycard set up. If the a keycard is locked or gets locked it
will be correctly marked in red. Selecting keycard from the list, its details may be
seen and additional flows may be run for it (so far only unlock flow is developed).
Fixes: #7025
> feat(@desktop/keycard): UI for the keycard settings in case user has set up a keycard

- ui/app/AppLayouts/Profile/views/KeycardView.qml
- ui/imports/utils/Constants.qml
> fix(@desktop/keycard): clicking `Get Keycard` button should direct to purchase page

- ui/StatusQ/src/StatusQ/Controls/StatusSeedPhraseInput.qml
- ui/app/AppLayouts/Wallet/panels/ImportSeedPhrasePanel.qml
Remove the workaround to the approach of using the "complete last word" event for three-letter seed words. The three letters condition introduced another side effect when completing the "sentence" and made the `_internal.mnemonicInput` contain an extra duplicate word.
Unify the event `doneInsertingWord` generation for the internal purpose with the external. This will trigger a secondary for some users but I see no problem with even in other usages.
Fix the corner case when the user enters a correct seed word that is not singular and uses the mouse to jump. In that case, the `doneInsertingWord` is not triggered and the sentence is not validated
Regression tests for the fixed issues: https://github.com/status-im/status-desktop/pull/7893
All the places where we use a seed phrase. Checked …
> fix(Wallet): fix import seed in account creation

- .gitmodules
Build system recently broke due to Nimbus updating the nim version to 1.6 in nimbus-build-system and vendor/nim. Since nimbus-build-system is pointing to a branch `nimbus` it automatically updates everywhere to this latest changes no matter what. This PR uses a fork of `nimbus-build-system` that points to the correct commit and modifies the build script to always use the correct commit so we don't have this issue again.
> Fix build2

- src/app_service/service/community/service.nim
New community that appears through community update signal can also be the community we are already members of, in that case we need to emit SIGNAL_COMMUNITY_JOINED, so that it appears on the side bar.
It fixes the imported community not appearing on the sidebar.
joining communities
> fix(communities): emit SIGNAL_COMMUNITY_JOINED for new communities

- ui/app/AppLayouts/CommunitiesPortal/popups/CreateCommunityPopup.qml
Prior to this commit we would reset the file list (and categories and channels) whenever the `CreateCommunityPopup` was closed.
This made sense because at that point we could assume that the user has decided to somehow stop the process of an import, so the next time the modal is opened again, we want that data to be reset.
However, it turned out that this introduced a bug in the scenario where and import is running, and while it's running, when the user decides to hide the progress modal, it would reset the warnings count, resulting in the progress banner to show an invalid state until the next progress signal was emitted.
We don't want to reset this data every time we close the modal. We only want to reset it when we know there's no import in progress.
Fixes #7787
> fix(CreateCommunityPopup): reset discord filelist when modal is opened

- ui/StatusQ/src/StatusQ/Components/StatusMessage.qml
- ui/imports/shared/views/chat/MessageView.qml
Fixes https://github.com/status-im/status-desktop/issues/7815
Moved `DateGroupLabel` out of `StatusMessage`. 
Now hovering works correctly.
chat
> fix(MessageView): Changed visual borders of message

- ui/app/AppLayouts/CommunitiesPortal/CommunitiesPortalLayout.qml
- ui/app/AppLayouts/CommunitiesPortal/views/CommunitiesGridView.qml
Do not display the Featured/Popular labels when the corresponding section is emtpy
Fixes: #7946
Fixes wrong section labels
CommunitiesGridView
> fix(CommunitiesGridView): don't display header labels when section empty

- ui/imports/shared/views/ProfileDialogView.qml
Fixes #7988
Uses compressed key to create the link to profile
Own profile:
Other profile:
> fix(ProfileDialogView): Use compressed chat key in "Copy Link To Profile

- storybook/main.cpp
- storybook/main.qml
- storybook/pages/ProfileDialogViewPage.qml
- storybook/src/Storybook/Logs.qml
- ui/imports/shared/views/ProfileDialogView.qml
- ui/imports/utils/Global.qml
- ui/imports/utils/Utils.qml
This adds the ProfileDialogView to storybook pages
For now, there's just one control to switch between own profile and another profile; more to come in later PRs.
The mocked global objects (mainModule and globalUtils) are done in C++, as it's impossible to do in QML mocks
Fixes: #7820
Adds Profile Popup view to storybook
Storybook
Random profile:
Own profile:
> feat(storybook): add Profile Popup

- src/app/core/custom_urls/urls_manager.nim
- src/app/global/app_signals.nim
- src/app/modules/main/controller.nim
- src/app/modules/main/io_interface.nim
- src/app/modules/main/module.nim
Cleanups in deep links - removing not needed link handlers, according to new specs: https://github.com/status-im/specs/blob/feature/url-shema/docs/draft/17-url-scheme.md
Improving `open community` and `open channel` deep links - spectate community if not a member.
join.status.im does not handle community deep links. This ticket is for internal deep links ("status-im://")
Fix #7892
Deep links
Testing requires installing a package.
Use your dogfooding account, so you are a member of Status community. 
Community you are a member of:
status-im://c/0x032aa2439b14eb2caaf724223951da89de1530fbfa5d5a639b93b82cd5341713fd - Status community
Channel in community you are a member of:
status-im://cc/0x032aa2439b14eb2caaf724223951da89de1530fbfa5d5a639b93b82cd5341713fd67ee9155-7a5a-4229-8612-690320f9ad34 …
> fix(@desktop/general): Fix community deep links

- ui/app/AppLayouts/Profile/popups/BackupSeedModal.qml
- ui/app/AppLayouts/Profile/popups/backupseed/BackupSeedStepBase.qml
Closes #7680
BackUpSeedPhrasePopup steps 2+3 had no focus in text input
BackUpSeedPhrasePopup
https://user-images.githubusercontent.com/31625338/196689138-6a0f895a-3da6-419b-befb-a3068cfcd416.mov
> fix(BackUpSeed): Confirm # word input had no focus

- storybook/pages/ProfileDialogViewPage.qml
- ui/imports/shared/views/ProfileDialogView.qml
now one can play around with various UI aspects of the new Profile Dialog
Adds controls to storybook/ProfileDialogViewPage
Storybook
> feat(storybook): add controls to profile page

- ui/app/AppLayouts/Chat/views/MembersSelectorView.qml
- ui/app/mainui/AppMain.qml
- ui/app/mainui/Popups.qml
- ui/imports/Themes/Theme.qml
- ui/imports/shared/views/ProfileDialogView.qml
- ui/imports/utils/Global.qml
Having components definitions in singleton was enforcing loading popups code at very early stage, leading to some races. In 5.15 there are warnings about that. In 5.14 Storybook was hanging on loading some components e.g. `InviteFriendsToCommunityPopup`.
Closes: #7992
> fix(Global): Popup components moved from Global.qml to dedicated non-singleton component

- test/ui-test/src/screens/StatusCommunityScreen.py
- test/ui-test/testSuites/global_shared/scripts/global_names.py
- test/ui-test/testSuites/global_shared/steps/startupSteps.py
- test/ui-test/testSuites/global_shared/steps/steps.py
- test/ui-test/testSuites/suite_communities/shared/scripts/community_names.py
- test/ui-test/testSuites/suite_communities/shared/steps/communitySteps.py
- test/ui-test/testSuites/suite_communities/shared/steps/searchSteps.py
- test/ui-test/testSuites/suite_communities/tst_communityFlows/bdd_hooks.py
- test/ui-test/testSuites/suite_communities/tst_communityFlows/test.feature
- test/ui-test/testSuites/suite_communities/tst_communityFlows/test.py
- test/ui-test/testSuites/suite_communities/tst_communityMessageFlows/bdd_hooks.py
- test/ui-test/testSuites/suite_communities/tst_communityMessageFlows/test.feature
- test/ui-test/testSuites/suite_communities/tst_communityMessageFlows/test.py
- test/ui-test/testSuites/suite_communities/tst_searchFlows/bdd_hooks.py
- test/ui-test/testSuites/suite_communities/tst_searchFlows/test.feature
- test/ui-test/testSuites/suite_communities/tst_searchFlows/test.py
- test/ui-test/testSuites/suite_messaging/shared/scripts/chat_names.py
- test/ui-test/testSuites/suite_messaging/shared/steps/chatSteps.py
- test/ui-test/testSuites/suite_messaging/tst_adminGroupChat/test.feature
Closes #7955 and also #7889 where extensive analysis has been done on the `suite_communities` and separate tasks have been created to address the issues one by one.
Fixes  #7977 and #7978
- Created `bdd_hooks` that contain the sing up steps just only once in the feature start and the needed start steps depending on the test case.
- Updated feature files removing sign up steps and given/when/then reorganization.
- Done some cleanups and reorganization in `communitySteps.py` and `searchSteps.py`.
`suite_communitites`
> test(chore/suite_communities):  Added specific `bdd_hooks` for `suite_communities`

- storybook/directorieswatcher.cpp
- storybook/main.qml
- storybook/pages/CommunityProfilePopupInviteFriendsPanelPage.qml
- storybook/pages/CommunityProfilePopupInviteMessagePanelPage.qml
- storybook/pages/InviteFriendsToCommunityPopupPage.qml
- storybook/src/Storybook/LogsView.qml
- ui/app/AppLayouts/Chat/panels/communities/CommunityProfilePopupInviteMessagePanel.qml
- ui/app/AppLayouts/Chat/panels/communities/qmldir
- ui/app/AppLayouts/Chat/popups/community/InviteFriendsToCommunityPopup.qml
- ui/imports/shared/views/PickedContacts.qml
Invite candidates list made scrollable. Additionally, bottom padding is fixed to avoid cutting-off the list
too early. Relevant components are added to the Storybook.
Closes: #8004 
Closes: #7603 
`Storybook`, `InviteFriendsToCommunityPopup`
[Kazam_screencast_00073.webm](https://user-images.githubusercontent.com/20650004/197735150-5e5b3695-85e7-45d1-be35-103cc7d6e7ae.webm)
> fix(InviteFriendsToCommunityPopup): Invite candidates list made scrollable

- ui/app/mainui/activitycenter/views/ActivityNotificationMessage.qml
- ui/imports/shared/views/chat/MessageView.qml
due to the refactor, StatusMessage is no longer the toplevel item inside the delegate, so adjust the functions
some minor cleanups and dead code removals; striving for keeping the number of properties and bindings inside a ListView delegate at a minimum
MessageView
Message reply + original msg edited:
> fix(MessageView): unbreak message reply update and found animation

- ci/Jenkinsfile.linux
- ci/Jenkinsfile.linux-cpp
- ci/Jenkinsfile.macos
- ci/Jenkinsfile.macos-cpp.todo
- ci/Jenkinsfile.uitests
- ci/Jenkinsfile.windows
- ci/Jenkinsfile.windows-cpp.todo
This is a continuation of a fix done in: https://github.com/status-im/status-desktop/pull/7968
This adds `deleteDirs` option to delete the whole workspace:
>When deferred wipeout is disabled, the old implementation of filesystem content deletion is used. If you want the same behavior as with deferred wipeout, you have to set the plugin attribute `deleteDirs` to true as well.
https://github.com/jenkinsci/ws-cleanup-plugin#deferred-wipeout
Because otherwise the `vendor` folder remains and causes issues when `.git` is a file.
Also use `cleanup` instead of `always` step in post section.
https://www.jenkins.io/doc/book/pipeline/syntax/#post
> ci: add deleteDirs:true for cleanWs to fix cleanup

- ui/app/AppLayouts/Chat/panels/communities/CommunityWelcomeBannerPanel.qml
- ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
- ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
- ui/app/AppLayouts/Profile/views/CommunitiesView.qml
- ui/app/AppLayouts/Profile/views/ContactsView.qml
- ui/app/mainui/AppMain.qml
- ui/imports/shared/views/ProfileDialogView.qml
- ui/imports/shared/views/chat/MessageContextMenuView.qml
We were showing the contact request buttons (accept or reject) in the profile popup even when the user had removed the other.
It would be better if we had better handling of contact requests with more statuses. This requires a refactor. This issue should cover it: https://github.com/status-im/status-desktop/issues/7734
> fix(ProfileDialogView): hide contact request buttons when removed

- ui/StatusQ/src/StatusQ/Components/StatusMessage.qml
Closes #7318
StatusMessage - reduces top+bottom margins to 2px based on figma spec
StatusMessage
> fix(StatusMessage): Reduced top+bottom margins based on figma spec

- ui/imports/shared/views/chat/MessageView.qml
use the correct way to get the original message's content type and compare it with the correct Constant type
Fixes a bug when color ring was never shown in replies
MessageView
Before the fix (watch Michal's ring in the middle):
After fix (Michal's ring in the reply is correct, cammellos' still correct too):
> fix(MessageView): unbreak showing identity ring in replies

- Makefile
Makes it possible to run StatusQ sanity checker using following command:
```
make run-statusq-sanity-checker
```
Closes: #7854
Related to: https://github.com/status-im/status-desktop/issues/8071
`Makefile`
> chore(general): ability to run StatusQ sanity checker from main Makefile

- ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
- ui/imports/shared/popups/CommunityIntroDialog.qml
Part of: #7072
Add checking access type in Welcome modal
Communities
> feat(Communities): Add checking access type in Welcome modal

- src/app/modules/shared_models/message_item.nim
- ui/imports/shared/views/chat/MessageView.qml
- ui/imports/utils/Utils.qml
- fill the senderId just like other messages
- add some checks in Utils since the "publicKey" (ID) coming Discord isn't in the format we'd normally expect
Closes #6678
MessageView
Imported community from Discord (read only):
> fix: consecutive discord messages should be grouped like status messages

- src/app/modules/main/module.nim
Part of: #7072
Add ephemerial notification when request to join was accepted
Communities
> feat(Communities): Add ephemerial notification when request to join was accepted

- ui/app/AppLayouts/Chat/stores/RootStore.qml
- ui/app/AppLayouts/Profile/popups/SendContactRequestModal.qml
- ui/imports/utils/Utils.qml
Fix #8070
Accept a profile deep link in "Send Contact Request to chat key" in Settings/Messaging/Contacts
Settings/Messaging/Contacts
https://user-images.githubusercontent.com/61889657/198548143-40fda901-7ab3-4ff1-855c-62bdb34846ea.mov
> fix(@desktop/chat): Accept profile deep link in "Send Contact Request to chat key"

- src/app/modules/shared_models/message_item.nim
Messages are parsed to transform markdown to something that can be rendered in a formatted way.
When this happens, the parsed text is applied to a message's `text` property inside desktop.
There was no formatted message support for imported discord messages, so we were relying purely on `discordMessage.content`.
However, now formatting support is pending in status-go here: https://github.com/status-im/status-go/pull/2933
This means, once this lands, we can simply rely on `messsageItem.text`.
I'm adding this guard here such that this will continue to work without the feature in status-go, but once the feature in status-go lands, desktop will automatically adapt.
Closes #8086
> feat(Message): fallback to import message content if necessary

- ui/StatusQ/src/StatusQ/Controls/StatusCheckBox.qml
- ui/StatusQ/src/StatusQ/Controls/StatusRadioButton.qml
- ui/app/AppLayouts/Onboarding/popups/BeforeGetStartedModal.qml
additionally correct the way a font is propagated from a QQC2 Control down to our components
Fixes #6515
Fixes some minor UI defects (margins/padding/spacing)
BeforeGetStartedModal
> fix(BeforeGetStartedModal): fix padding and (line) spacings

- src/app_service/service/accounts/service.nim
The WAKUV2_PORT env var was only being used during login, so the account creation would be saved, but it wouldn't let you in the app, you needed to close and retry, this time with a login.
Now, the WAKUV2_PORT var is used for both so it's possible to run tests for example with it.
> fix(accounts-service): use WAKUV2_PORT env var for account creation too

- src/backend/contacts.nim
The underlying API was mistakenly removed in status-go, then reintroduced, but as `getLatestVerficiationRequestFrom`.
This commit fixes the RPC call.
Needs https://github.com/status-im/status-go/pull/2934
> fix(contacts): fix `getVerificationRequestFrom`  API

- src/app/modules/shared_modules/keycard_popup/controller.nim
- src/app/modules/shared_modules/keycard_popup/internal/key_pair_migrate_failure_state.nim
- src/app/modules/shared_modules/keycard_popup/module.nim
- src/app/modules/startup/controller.nim
- src/app_service/common/account_constants.nim
- src/app_service/service/accounts/dto/generated_accounts.nim
- src/app_service/service/accounts/service.nim
- src/backend/accounts.nim
- https://github.com/status-im/status-go/pull/2928
Corresponding `nim-status-go` PR:
- https://github.com/status-im/nim-status-go/pull/18
DB password for a Keycard user is now `publicKey` of encryption derivation.
kdf iterations for keycard users are set to 256000 so it's the same as we have
for regular users.
Fixes: #8066
> fix(@desktop/keycard): change db password for a keycard users

- ui/imports/utils/Constants.qml
Those have been changed in status-go, resulting in wrong visualization of import warnings and errors.
This commit adjusts them so they match the correct codes again.
> fix(Communities): adjust discord import error codes

- src/app/modules/main/communities/models/discord_import_task_item.nim
- src/app/modules/main/communities/models/discord_import_tasks_model.nim
- src/app_service/service/community/dto/community.nim
This commit enures we render proper errors during an import, even if we've reached the maximum of warning/error items to render.
> fix(communities): allow actual import errors to come through

- scripts/windows_build_setup.ps1
Fixes the following build error:
```
protocol\messenger.go:5957:6: missing function body
protocol\messenger.go:5957:16: syntax error: unexpected [, expecting (
protocol\messenger.go:5959:2: syntax error: non-declaration statement outside function body
note: module requires Go 1.18
```
> ci: lock windows Go version at 1.18.8

- Makefile
- ci/Jenkinsfile.linux
- ci/Jenkinsfile.linux-cpp
- ci/Jenkinsfile.macos
- ci/Jenkinsfile.macos-cpp.todo
- ci/Jenkinsfile.uitests
- ci/Jenkinsfile.windows
- ci/Jenkinsfile.windows-cpp.todo
This is a continuation of attempts to fix provlems with Windows CI hosts getting into a broken state due to `.git` directory becoming a file for random submodules for unknown reason.
Instead of relying on Jenkins functionality of `cleanWs()` function provided by the [Workspace Cleanup Plugin](https://plugins.jenkins.io/ws-cleanup) we use Git which should be more reliable, and possibly also speed up the initial checkout of the repo and submodules.
A nice side-effect is that the repo checkout on all builds after the first one takes ~1 minute instead of ~5 minutes.
Previous issues:
- https://github.com/status-im/status-desktop/pull/7968
- https://github.com/status-im/status-desktop/pull/8046
> ci: use git clean instead of cleanWs() function

- ui/imports/shared/views/chat/MessageView.qml
The referenced method does not exist; use the correct one from Utils
Fixes: #8123
Fixes clicking URL links in any chat
MessageView
> fix(MessageView): fix opening URL links

- ui/StatusQ/src/StatusQ/Components/private/statusMessage/StatusTextMessage.qml
Setting `visible` or `enabled` to `false` stops mouse events from being propagated -> hide the original message using `opacity` instead
Fixes links being unclickable when the gradient/mask is in effect
Closes #8116
Fixes text messages being non interactive
StatusTextMessage
> fix(StatusTextMessage): Links not clickable in a long collapsed message

- storybook/pages/CommunityProfilePopupInviteFriendsPanelPage.qml
- storybook/pages/CommunityProfilePopupInviteMessagePanelPage.qml
- storybook/pages/InviteFriendsToCommunityPopupPage.qml
- storybook/src/Storybook/PagesList.qml
- ui/app/AppLayouts/Chat/popups/community/InviteFriendsToCommunityPopup.qml
Fixes problems with improper size and inconsistent footer of `InviteFriendsToCommunityPopup`.
Closes: https://github.com/status-im/status-desktop/issues/7604
Closes: https://github.com/status-im/status-desktop/issues/7605
`InviteFriendsToCommunityPopup`
[Kazam_screencast_00078.webm](https://user-images.githubusercontent.com/20650004/200326982-4ad1e3c2-5ecc-417e-8b63-d5103380ccae.webm)
> fix(InviteFriendsToCommunityPopup): adaptive popup height, consistent footer height

- src/app/core/signals/remote_signals/community.nim
- src/app/modules/main/communities/controller.nim
- src/app/modules/main/communities/io_interface.nim
- src/app/modules/main/communities/module.nim
- src/app/modules/main/communities/view.nim
- src/app_service/service/community/service.nim
- ui/app/AppLayouts/CommunitiesPortal/popups/DiscordImportProgressContents.qml
- ui/app/AppLayouts/CommunitiesPortal/stores/CommunitiesStore.qml
This needs https://github.com/status-im/status-go/pull/2947
There's one issue here though:
We only get the image from the backend when the community has been created which takes a short moment.
So we should ideally show a loading indicator instead of the image.
@caybro if you have ideas how to make that work with our existing components, feel free to update the PR
> fix(communities): add missing community image to import process

- ui/app/mainui/AppMain.qml
- ui/app/mainui/AppSearch.qml
closed
Otherwise, the loader stays active, which requires users to hit CTRL-F twice to reopen it again (because it'll first deactivate, then activate again).
Fixes #7989
> fix(AppSearch): ensure app search loader is deactivated when popup is

- src/app/core/signals/remote_signals/messages.nim
Fixes: #8099 
Instead of enabling this only on DEBUG as requested in original issue, I'm doing it on INFO, since debug adds a lot of noise in the geth.log file, while this only logs the envelope hashes and message IDs (there's a point to discuss whether this could expose unwanted data).
Requires:
- https://github.com/status-im/status-go/pull/2948
In go-waku, changes were done in https://github.com/status-im/go-waku/tree/status-go . This branch is meant only for tracing the missing messages and is not going to be merged on master.
Text to search for when tracing a message:
- `waku.store retrieved` - Contains an array of WakuMessage hashes of all messages retrieved from store node
- `waku.relay received` - Contains hash of WakuMessage received via waku relay
- `waku.relay published` - …
> chore(waku2): add extra logging

- src/app/modules/main/communities/controller.nim
- src/app/modules/main/communities/io_interface.nim
- src/app/modules/main/communities/module.nim
- src/app/modules/main/communities/view.nim
- src/app_service/service/community/dto/community.nim
- src/app_service/service/community/service.nim
- src/backend/communities.nim
- ui/app/AppLayouts/Chat/stores/RootStore.qml
- ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
- ui/imports/shared/popups/CommunityIntroDialog.qml
Part of: #7072
[Status-go PR](https://github.com/status-im/status-go/pull/2915)
Add methods to cancel membership requests to community
Communities
https://user-images.githubusercontent.com/82511785/197172029-0cb4f83b-37c5-4df8-8d03-d4cb08dd0409.mov
UPDATE:
@caybro @PascalPrecht I update ui logic as expect:
https://user-images.githubusercontent.com/82511785/197408822-42345c19-f216-46a5-8501-543a6d7caa66.mov
> feat(communities): User is able to cancel membership request

- src/app_service/service/contacts/dto/contacts.nim
- src/app_service/service/contacts/service.nim
There's a bug in determining pending incoming contact requests where we don't honor already rejected ones.
Simply checking if a contact in question `hasAddedUs` isn't enough because that only tells us if the contact has sent us a request in the past. It doesn't tell is whether the request was rejected already.
As a result, rejected contact requests keep popping up in the UI after restarting the app. See #8156 for more information.
This commit introduces a `ContactRequestState` enum in Status Desktop, similar to how it exists in status-go. Using this as `requestState` on `ContactDto`, we can easily figure out what's the request state for any given contact.
Notices that this only makes use of `ContactRequestState` to check for whether a request was rejected.
We probably want to consider …
> fix(Contacts): use `ContactRequestState` to filter out rejected requests

- src/app/modules/main/chat_section/chat_content/messages/controller.nim
- src/app/modules/main/chat_section/chat_content/messages/io_interface.nim
- src/app/modules/main/chat_section/chat_content/messages/module.nim
- src/app/modules/main/chat_section/chat_content/messages/view.nim
- src/app_service/service/message/service.nim
- src/backend/messages.nim
- ui/app/AppLayouts/Chat/stores/MessageStore.qml
- ui/imports/shared/views/chat/MessageView.qml
Closes: #7879
In general, status-go validation is wrong when user trying to edit the message. If content type of message was not set, status-go replace message content type with `ChatMessage_UNKNOWN_CONTENT_TYPE` successfully.
Provide `ContentType` of edited message in request.
Edit messages
> fix(edit-message): Add content-type to edit message request

- src/app/modules/main/activity_center/module.nim
- src/app/modules/main/chat_section/chat_content/messages/module.nim
- src/app/modules/main/chat_section/chat_content/module.nim
- src/app/modules/shared_models/message_item.nim
- src/app/modules/shared_models/message_model.nim
fixes: #8153
Use clock for messages ordering. If there is a tie, use message ID.
- messages ordering in every chat
> fix(chat): use clock for messages ordering

- ui/StatusQ/src/StatusQ/Components/StatusMessage.qml
- ui/StatusQ/src/StatusQ/Components/private/statusMessage/StatusMessageReply.qml
- ui/StatusQ/src/StatusQ/Components/private/statusMessage/StatusTextMessage.qml
- ui/StatusQ/src/StatusQ/Core/Utils/Utils.qml
- ui/imports/shared/views/chat/MessageView.qml
- ui/imports/utils/Utils.qml
Fixes https://github.com/status-im/status-desktop/issues/7673
- Click on a replied message to jump to it
- Remove text styling in replied messages
- Replied messages smooth fade out instead of clipping
chat
NOTE:
As discussed with design team, there should be no code styling in the text of relied messages, even that we have "mentions" styling in designs.
> Replied messages styling and behavior fixes

- src/app_service/service/contacts/service.nim
- src/backend/contacts.nim
Fixes #7791
Adds the retractContactRequest status-go api call. Calling it when removing a contact makes sure to send a signal to that other user so they can understand that we are no longer mutual contacts or don't have a request anymore
(sorry for the bad branch names. I was fixing the #7791 issue and found some small bugs in doing so and I split my PRs accordingly but forgot to rename the branch for those :shrug: )
> fix(contacts): retract the contact request when removing a contact

- storybook/main.qml
- storybook/pages/CreateChannelPopupPage.qml
- storybook/pages/InviteFriendsToCommunityPopupPage.qml
- storybook/src/Storybook/LogsAndControlsPanel.qml
- storybook/src/Storybook/PopupBackground.qml
- storybook/src/Storybook/qmldir
- ui/app/AppLayouts/Chat/popups/community/CreateChannelPopup.qml
- ui/app/AppLayouts/Chat/popups/community/qmldir
- ui/imports/utils/Utils.qml
When typing at non-end position (in channel name filed) cursor is no longer jumping to the end. Additionally binding loop on "contentWidth" is fixed.
`CreateChannelPopup` has been added to the Storybook.
Closes: https://github.com/status-im/status-desktop/issues/7805
`CreateChannelPopup`
[Kazam_screencast_00081.webm](https://user-images.githubusercontent.com/20650004/200682950-5800545d-a780-4850-ba1a-25460597127d.webm)
> fix(CreateChannelPopup): cursor not jumping to the end 

- ui/StatusQ/src/StatusQ/Controls/StatusBaseInput.qml
This commit fixes scrolling on macOS using trackpad in the context of Add Wallet Account using seed-phrase.
The scrolling of advanced input with seed-phrase selected was failing when mouse pointer was moving over a word phrase.
Scrolling of the popup content in `AddAccountModal` would not work when the mouse pointer was over the `StatusSeedPhraseInput` form the `ImportSeedPhrasePanel`
The identified root cause is `StatusBaseInput`'s `Flickable` which captures the specially generated mouse wheel event. It seems the trackpad wheel events are handled differently on `macOS` by the `Flickable` and are not propagated to the parent.
The fix disables user interactions for single-line items where there should be no need
Add Account Wallet and all the panels and views that might rely on the StatusQ …
> fix(StatusQ) scrolling on macOS if mouse pointer is over StatusBaseInput

- ui/StatusQ/src/StatusQ/Controls/StatusActivityCenterButton.qml
- ui/app/mainui/AppMain.qml
Close #8030, #8124
Fix positioning AC popup & tooltip text
Activity Center, all screens
> fix(ActivityCenter): Fix positioning AC popup

- src/app/modules/main/profile_section/profile/view.nim
- ui/StatusQ/src/StatusQ/Components/StatusSmartIdenticon.qml
- ui/StatusQ/src/StatusQ/Core/StatusAssetSettings.qml
- ui/app/AppLayouts/Profile/views/MyProfileView.qml
- ui/app/AppLayouts/Profile/views/profile/MyProfilePreview.qml
- ui/app/AppLayouts/Profile/views/profile/MyProfileSettingsView.qml
- ui/app/mainui/AppMain.qml
- ui/imports/shared/controls/chat/ProfileHeader.qml
- ui/imports/shared/controls/chat/UserImage.qml
- ui/imports/shared/popups/ImageCropWorkflow.qml
- ui/imports/shared/views/ProfileDialogView.qml
- ui/imports/utils/Global.qml
Closes: #7920 
Closes: #7917
Update profile settings after save button and update preview profile to dirty values
Profile settings
https://user-images.githubusercontent.com/82511785/200647135-4d39bee2-c908-4a2c-83ed-bd72b7fa9c9e.mov
> fix(profile-settings): Add usage dirty values for preview and load image profile on save

- ui/app/AppLayouts/Wallet/popups/AddEditSavedAddressPopup.qml
- ui/imports/shared/popups/AddEditSavedAddressPopup.qml
This fixes #8214
The definition of `StatusDialogHeader` for `AddEditSavedAddressPopup.qml` was missing the action for the close button. This PR adds it.
Wallet
1. Enable wallet
2. Click "Saved addresses"
3. Click "Add new address¨
4. On the popup, click the close button (X)
The popup should close
> fix(@desktop/wallet): fix add new saved address popup close button

- Makefile
By using the pipe(`|`) operator which indicates order-only dependencies we can avoid unnecessary rebuilds triggered by additon of QT dir check:
https://www.gnu.org/software/make/manual/html_node/Prerequisite-Types.html
~~This will also probably fix CI builds timeouts.~~
> makefile: avoid rebuilds by using order-only deps

- src/app_service/common/types.nim
- src/app_service/service/activity_center/dto/notification.nim
Alright this was very painful to figure out.
Because desktop didn't know about the notification type for `ContactVerification`, the signal processing for incoming contact verifications would fail.
At the same time, the new message content type was missing a type variant for content verification as well, which would cause the app to crash at runtime for both, sender and receiver of verification requests.
Fixes #8205
> fix: prevent app from crash due to missing type variants

- ci/Jenkinsfile.linux
Since we change cleanWs by a clean git, the submodule are not fetch on checkout.
Running make update would hopefully update reference to latest
> fix: ci build

- ui/app/AppLayouts/Chat/popups/PublicChatPopup.qml
Limit chat name length to 24 symbols 
Closes: #6938
Chat name length
> fix(@desktop/chat): Limit chat name length #6938

- ci/Jenkinsfile.linux
- ci/Jenkinsfile.macos
- ci/Jenkinsfile.windows
This was added to fix some build issues to Linux:
* https://github.com/status-im/status-desktop/pull/8233
But other 2 platforms also have had the cleanup stage change which could have cause these submodules update issues.
> ci: add make update to for other platforms

- ui/app/AppLayouts/Wallet/popups/AddEditSavedAddressPopup.qml
- ui/imports/shared/controls/AddressInput.qml
- ui/imports/shared/controls/ContactsListAndSearch.qml
- ui/imports/shared/controls/RecipientSelector.qml
- ui/imports/shared/popups/AddEditSavedAddressPopup.qml
This fixes #8114
The error message shown when the user's ENS name is entered in component `ContactsListAndSearch.qml` is now a property. By default it keeps the old value ("Can't chat with yourself"). Particularly in `AddEditSavedAddressPopup.qml` it is now changed with "Can't add yourself as a saved address".
Wallet. Change was also included in shared resource.
Before:
After:
> fix(@desktop/wallet): correct error message when adding own ENS name to saved addresses

- ui/StatusQ/src/StatusQ/Controls/Validators/StatusRegularExpressionValidator.qml
- ui/imports/shared/popups/NicknamePopup.qml
- do not restrict NicknamePopup's regexp to ASCII characters
- a similar thing could be done to the user's DisplayName but currently that's blocked on status-go side
- uses RXValidator from dotherside
Needs status-im/dotherside/pull/74
Fixes #8115
Fixes Unicode support for local nicknames
NicknamePopup
> fix(NicknamePopup): add support for Unicode nicknames

- ui/StatusQ/src/StatusQ/Components/private/statusMessage/StatusTextMessage.qml
Closes #8242
StatusTextMessage: Removed vertical text alignment leftover
StatusTextMessage
> fix(StatusTextMessage): Removed vertical text alignment leftover

- ui/app/AppLayouts/Profile/views/profile/MyProfileSettingsView.qml
- ui/imports/shared/popups/SettingsDirtyToastMessage.qml
Fixes: #8247
If view isn't ready and `dirty` flag is true in initial state, toast message trying to scroll ui, but contentHeight is 0. This PR may be just a workaround, but hidden scrolling shouldn't exist. 
SettingsDirtyToastMessage
> fix(SettingsDirtyToastMessage): Avoid scrolling when content height is 0

- ui/imports/shared/stores/TransactionStore.qml
- ui/imports/shared/views/NetworkCardsComponent.qml
- ui/imports/shared/views/NetworkSelector.qml
- ui/imports/shared/views/NetworksAdvancedCustomRoutingView.qml
fixes #8224
1. This PR fixes the issue with the suggested routes not getting updated after a network is enabled and disabled
2. The USDC is using 18 decimals and not 6 decimals 
Wallet
https://user-images.githubusercontent.com/60327365/201908589-a990e366-65ab-41cb-a4bb-6d02a7a8229a.mov
> fix(@desktop/wallet): Fix for send transaction USDC error

- ui/imports/shared/status/StatusChatInput.qml
- unbreak upload image shortcut (Ctrl+U)
- add Esc key handler to close reply area
> fix(StatusChatInput): various keyboard shortcut fixes

- ui/StatusQ/src/StatusQ/Components/StatusMessage.qml
Fixes #8267
Fixes the individual StatusMessage subcomponents being too squashed together by adding a 2px spacing
StatusMessage
> fix(StatusMessage): add spacing between individual subcomponents

- src/app/modules/main/networks/model.nim
- src/app/modules/main/networks/networks_extra_store_proxy.nim
- src/app/modules/main/networks/view.nim
- ui/app/AppLayouts/Profile/stores/AdvancedStore.qml
- ui/app/AppLayouts/Wallet/popups/NetworkSelectPopup.qml
- ui/app/AppLayouts/Wallet/popups/ReceiveModal.qml
- ui/app/AppLayouts/Wallet/stores/RootStore.qml
- ui/imports/shared/popups/AccountsModalHeader.qml
- ui/imports/shared/popups/SendModal.qml
- ui/imports/shared/popups/qmldir
Add `AccountsModalHeader`, a reusable header control shared between Send and Receive modals
Send and Receive Wallet modals
- Don't have them integrated
| Send | Receive | Design |
| ----- | -------- | ------- |
| ![image](https://user-images.githubusercontent.com/47554641/201630321-e4c27202-ef7a-4c83-b011-3540e0acb82e.png) | ![image](https://user-images.githubusercontent.com/47554641/201632180-bf8bf88f-0e70-415e-ad98-3859e6a31156.png) | ![image](https://user-images.githubusercontent.com/47554641/201631840-d444c582-0836-4054-91e4-147d23dd695a.png) |
| | ![image](https://user-images.githubusercontent.com/47554641/201630503-5161a0d7-c32c-4a87-8e9b-34c7325f6f31.png) |  |
| | ![image](https://user-images.githubusercontent.com/47554641/201630616-40062461-32ce-482d-b97d-f4e5107881f4.png) | |
> fix(receive) fix header alignment and network selection for ReceiveModal

- ui/app/AppLayouts/Chat/views/ChatColumnView.qml
- ui/app/AppLayouts/Chat/views/ChatContentView.qml
- ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
- ui/app/AppLayouts/Chat/views/ChatView.qml
- ui/app/AppLayouts/Chat/views/CreateChatView.qml
- ui/app/mainui/AppMain.qml
- ui/imports/shared/status/StatusChatInput.qml
- ui/imports/shared/status/StatusStickersPopup.qml
- ui/imports/shared/views/chat/MessageView.qml
Fixes #7906 
The original problem was that the Windows build wasn't opening. Technically, this PR doesn't fix that, because for me, on Windows 10, master already opened fine. So something in 0.8 already fixed that.
However, the chat view was completely empty. No message, no input, nothing, just the top bar. Even the community portal was empty.
It seems like it was caused by some sort of memory overflow, though increasing the max stack didn't do the trick.
Anyway, the thing is that our StatusChatInput is used A LOT. Each channel has one, and even worst, each **Message** has one, for the edit feature.
Then each ChatInput has a couple of Popups. Last time, Igor found that we have some sort of problem with those popups. He's working on a fix, but in the meantime, Windows is fully broke, so …
> Fix Windows' chat being empty because of some kind of popup overflow

- ui/imports/shared/views/ProfileDialogView.qml
Fixes #8219
Adds a 2 second timeout after which the original "Copy" text is restored from "Copied"
> fix: Copy to clipboard button in profile view should reset to "Copy"

- src/app/modules/main/chat_section/chat_content/module.nim
- ui/app/AppLayouts/Chat/views/ChatHeaderContentView.qml
Fixes #8303
Fixes local nickname change not being reflected in 1-1 chat header
ChatHeaderContentView
Before nickname change:
After nickname change:
> fix(ChatHeaderContentView): reflect nickname changes in 1-1 chat

- test/ui-test/src/screens/StatusChatScreen.py
- test/ui-test/testSuites/suite_messaging/shared/steps/chatSteps.py
- test/ui-test/testSuites/suite_messaging/tst_ChatFlow/test.feature
- ui/StatusQ/src/StatusQ/Components/StatusMessage.qml
- ui/StatusQ/src/StatusQ/Components/private/statusMessage/StatusMessageReply.qml
Prior to this commit we were merely checking if the message in question was the last one.
With this commit we now check whether there's a reply in the first place and whether the reply-to-message is the correct one.
Closes #7909
> tests(suite_messaging): properly check if reply message has reply

- test/ui-test/src/drivers/SquishDriver.py
Probably a mistake. This was defined twice in our package.
> cleanup(squish): remove redundant definition of `mouse_over_object` api

- test/ui-test/src/screens/StatusChatScreen.py
- test/ui-test/testSuites/suite_messaging/shared/steps/chatSteps.py
- test/ui-test/testSuites/suite_messaging/tst_ChatFlow/test.feature
This adds an assertion that checks whethere a message was indeed edited by checking its `isEdited` property.
> tests(suite_messaging): add assertion that message was indeed edited

- libs/Helpers/src/Helpers/JsonMacros.h
- libs/StatusGoQt/src/StatusGo/Chat/ChatDto.cpp
Set needed fields optional (w/o this chat section crashed).
Adding optional helper macro.
Fix #8305
> fix(@desktop/cpp): Fix chatDto json serialization.

- storybook/CMakeLists.txt
- storybook/main.cpp
- storybook/main.qml
- storybook/sectionsdecoratormodel.cpp
- storybook/sectionsdecoratormodel.h
- storybook/src/Storybook/FilteredPagesList.qml
- storybook/src/Storybook/PagesList.qml
- storybook/tests/tst_SectionsDecoratorModel.cpp
Provides 2-level foldable sections for storybook's pages list. Model is implemented in c++, thanks to that qml code stays simple and modular.
Note: current implementation is suboptimal (internal model reset on source model filtering), but sufficient for that case. In the future similar approach can be used in other parts of the application for speed, clean code and separation of concerns.
Basic unit tests has been added for the c++ module. It can be run conveniently from QtCreator or via cmake/ctest.
Closes: #7928
Storybook's pages list
[Kazam_screencast_00083.webm](https://user-images.githubusercontent.com/20650004/202198121-bd9bcf6e-0d14-45fb-9b57-586107c3e188.webm)
> feat(Storybook): Foldable sections in pages list

- ui/StatusQ/src/StatusQ/Components/StatusMessage.qml
- ui/StatusQ/src/StatusQ/Components/StatusMessageHeader.qml
- ui/StatusQ/src/StatusQ/Components/StatusSmartIdenticon.qml
- ui/StatusQ/src/StatusQ/Components/qmldir
- ui/StatusQ/src/statusq.qrc
- ui/app/mainui/activitycenter/controls/ReplyBadge.qml
- ui/app/mainui/activitycenter/popups/ActivityCenterPopup.qml
- ui/app/mainui/activitycenter/views/ActivityNotificationBase.qml
- ui/app/mainui/activitycenter/views/ActivityNotificationCommunityInvitation.qml
- ui/app/mainui/activitycenter/views/ActivityNotificationCommunityMembershipRequest.qml
- ui/app/mainui/activitycenter/views/ActivityNotificationCommunityRequest.qml
- ui/app/mainui/activitycenter/views/ActivityNotificationContactRequest.qml
- ui/app/mainui/activitycenter/views/ActivityNotificationMention.qml
- ui/app/mainui/activitycenter/views/ActivityNotificationMessage.qml
- ui/app/mainui/activitycenter/views/ActivityNotificationReply.qml
Close #8285
- Replace MessageView in the Activity Center with custom ActivityNotificationMessage
- Limit AC notifications msg height in lines: contact and identity verification requests - 5, others - 2 
- Make AC notifications message plain (without stickers, links and etc),
> feat(ActivityCenter): Remove MessageView from the Activity Center

- ui/app/mainui/activitycenter/panels/ActivityCenterPopupTopBarPanel.qml
Close #8310
Add StatusRollArea for fading  AC tabs header
https://user-images.githubusercontent.com/2522130/202667262-68a3c26f-a02d-41fe-91ce-04647ab07fe4.mov
> fix(ActivityCenter): Fader for AC tabs header

- Makefile
This avoids a situation in which `variables.mk` from `nimbus-build-system` does't exist, but at the same time `git submodule update` doesn't work due to sumodules stuck in a bad state.
> ci: improve clean-git by reseting submodules

- ui/StatusQ/src/StatusQ/Components/StatusMessage.qml
- ui/imports/shared/views/chat/MessageView.qml
also move the top/bottom margins one level up so that the message editor gets the same margins as well
Fixes: #8185
Removed quick action when editing a message
StatusMessage/MessageView
> fix: disable quick actions when editting a message

- ci/Jenkinsfile.combined
- ci/Jenkinsfile.imports
- ci/Jenkinsfile.linux
- ci/Jenkinsfile.linux-cpp
- ci/Jenkinsfile.macos
- ci/Jenkinsfile.macos-cpp.todo
- ci/Jenkinsfile.uitests
- ci/Jenkinsfile.windows
- ci/Jenkinsfile.windows-cpp.todo
Possible fix for slow upload speeds and failures caused by most probably hitting per-bucket rate limits of DigitalOcean:
>- 500 total operations per second to any individual bucket.
>- 300 combined PUT, POST, COPY, DELETE, and LIST operations per second
>  to any individual Space. We may further limit LIST operations if
>  necessary under periods of high load.
https://docs.digitalocean.com/products/spaces/details/limits/#rate-limits
Depends on: https://github.com/status-im/status-jenkins-lib/pull/52
> ci: separate buckets for mobile and desktop builds

- test/ui-test/src/screens/StatusMainScreen.py
- test/ui-test/testSuites/global_shared/scripts/bdd_hooks.py
- test/ui-test/testSuites/global_shared/scripts/global_names.py
- test/ui-test/testSuites/global_shared/steps/commonInitSteps.py
- test/ui-test/testSuites/suite_communities/tst_communityFlows/bdd_hooks.py
- test/ui-test/testSuites/suite_communities/tst_communityMessageFlows/bdd_hooks.py
- test/ui-test/testSuites/suite_communities/tst_searchFlows/bdd_hooks.py
- test/ui-test/testSuites/suite_messaging/tst_ChatFlow/bdd_hooks.py
- test/ui-test/testSuites/suite_messaging/tst_OneToOneChatFlow/bdd_hooks.py
- test/ui-test/testSuites/suite_onboarding/tst_passwordStrength/bdd_hooks.py
- test/ui-test/testSuites/suite_onboarding/tst_signUpNegativeCases/bdd_hooks.py
- test/ui-test/testSuites/suite_settings/tst_mainSettingsSection/bdd_hooks.py
- test/ui-test/testSuites/suite_settings/tst_signUpAndQuit/test.feature
- test/ui-test/testSuites/suite_settings/tst_userIdentity/bdd_hooks.py
- test/ui-test/testSuites/suite_wallet/tst_transaction/bdd_hooks.py
- test/ui-test/testSuites/suite_wallet/tst_wallet/bdd_hooks.py
- ui/app/AppLayouts/Chat/panels/EmptyChatPanel.qml
Closes #8330 
- Enables Screenshots on Test Failures and Errors
`ui-test` project
> test(chore): Add Automatic Screenshots on Test Failures and Errors

- src/app_service/service/chat/service.nim
- test/ui-test/testSuites/suite_communities/tst_communityMessageFlows/test.feature
Fixes: #7961
The problem was in processing several messages after send. Images were sent, but displaying several messages was impossible (was expected several messages from different chats).
Fix image validation in ui-test
Messaging
edit: this also fixes showing your own replies
> fix(messaging): Fix processing successfully sent messages and remove @mayfail from relevant ui test

- ui/app/AppLayouts/Chat/popups/PinnedMessagesPopup.qml
similar to the profile dialog, we need to add an opacity mask in front of the contentItem to ensure the rounded corners at the bottom are preserved when we have no margins/padding inside the popup
Fixes #7759
Fixes rounded corners at the bottom 
> fix(PinnedMessagesPopup): Pinned messages cover rounded corners of modal

- ui/app/AppLayouts/Profile/views/AboutView.qml
use the default (existing) color for the text
Fixes #8374
fixes text color in dark mode
AboutView
> fix(AboutView): Version text is still black on dark mode

- src/app/boot/app_controller.nim
- src/app/modules/main/profile_section/advanced/controller.nim
- src/app/modules/main/profile_section/advanced/io_interface.nim
- src/app/modules/main/profile_section/advanced/module.nim
- src/app/modules/main/profile_section/advanced/view.nim
- src/app_service/service/community/service.nim
- src/app_service/service/node_configuration/service.nim
- ui/app/AppLayouts/Profile/stores/AdvancedStore.qml
- ui/app/AppLayouts/Profile/views/AdvancedView.qml
Enabling the community archive protocol could fail when another app is using the same port that is specified as torrent client port.
This would cause the app to crash.
With these changes we:
1. No longer crash the app but output an error in the logs
2. We popup a dialog telling the user that the specified pord is in use
Closes #7328
> fix(Settings): better error handling for toggling archive protocol

- storybook/CMakeLists.txt
- storybook/README.md
- storybook/StoryBook.pro
- storybook/main.cpp
- storybook/pages/CreateChannelPopupPage.qml
- ui/imports/Themes/Theme.qml
- ui/imports/utils/Constants.qml
This changeset contains the prerequisites required to compile StoryBook on wasm_32 and the README file with instructions
Fixing #7563 
git clone https://github.com/emscripten-core/emsdk.git
#go to emsdk folder
cd emsdk
#install Emscripten v1.38.27
./emsdk install emscripten-1.38.27
#activate emscripten-1.38.27
./emsdk activate emscripten-1.38.27
#install Fastcomp backend
./emsdk install fastcomp-clang-tag-e1.38.27-64bit
#activate Fastcomp backend
./emsdk activate fastcomp-clang-tag-e1.38.27-64bit
#add emsdk tools to env variables
./emsdk construct_env
echo 'source "/Users/alexjbanca/Repos/emsdk/emsdk_env.sh"' >> $HOME/.zprofile
#check environment
em++ --version
cmcc --version
More documentation: https://emscripten.org/docs/getting_started/downloads.html
Newer versions of QtCreator won't …
> Adding qmake project file for wasm

- ci/Jenkinsfile.e2e
I tried using `--exitCodeOnFail` but it didn't work.
https://doc.qt.io/squish/cli-squishrunner.html#playback-option-op-op-op-op-exitcodeonfail
> ci: clarify why we ignore UNSTABLE squish state

- ui/StatusQ/src/StatusQ/Core/Utils/Emoji.qml
- ui/imports/shared/status/StatusEmojiSuggestionPopup.qml
use an SVG icon instead of a potentially lowres PNG
Fixes #8409
Fixes blurry emojis in the suggestion popup list
StatusEmojiSuggestionPopup
> fix(StatusEmojiSuggestionPopup): emoji is blurry in the suggestions popup

- src/app/core/signals/remote_signals/messages.nim
- src/app_service/service/community/service.nim
We were ignoring the `removedChats` in the messenger response and therefore never processed deleted community chats in the client.
This commit adds `removedChats` to `handleCommunityUpdates()` and ensures that the community channel's ID is used when emitting a signal to the app.
This needs: https://github.com/status-im/status-go/pull/2973
Closes #8000
> fix(communities): handle removed community chats properly

- ui/app/mainui/AppMain.qml
- don't reference non-existent code
- positioning it manually is wrong anyway
Fixes: #8447
Fixes image context menu being not visible
Chat
> fix: unbreak the image context menu

- ui/imports/shared/status/StatusChatInput.qml
- ui/imports/utils/Utils.qml
- don't consider `_` as a "punct" or invalid character, some emojis like flags do contain it in their name
Fixes: #8446
> fix: unbreak suggestions for emojis containing an underscore

- storybook/CMakeLists.txt
- storybook/main.cpp
For linux the linker is set to gold which fixes the problem with linking described in the ticket.
Closes: #8454
`Storybook`
> fix(Storybook): linking WebEngine causes errors on Linux

- storybook/StoryBook.pro
Simple check preventing building for other platforms than wasm using `Storybook.pro` config file.
Closes https://github.com/status-im/status-desktop/issues/8451
`Storybook`
> feat(Storybook): Prevent building for desktop using Storybook.pro

- storybook/CMakeLists.txt
- storybook/PagesModel.qml
- storybook/figma.json
- storybook/figmadecoratormodel.cpp
- storybook/figmadecoratormodel.h
- storybook/figmaio.cpp
- storybook/figmaio.h
- storybook/figmalinks.cpp
- storybook/figmalinks.h
- storybook/figmalinksmodel.cpp
- storybook/figmalinksmodel.h
- storybook/figmalinkssource.cpp
- storybook/figmalinkssource.h
- storybook/main.cpp
- storybook/main.qml
- storybook/modelutils.cpp
- storybook/modelutils.h
- storybook/sectionsdecoratormodel.cpp
- storybook/sectionsdecoratormodel.h
- storybook/src/Storybook/FigmaImagesProxyModel.qml
- storybook/src/Storybook/ImagesNavigationLayout.qml
- storybook/tests/tst_FigmaDecoratorModel.cpp
Figma links are read dynamically from a separate file. It's a prerequisite to have figma links modifiable (adding/removing) directly from the app.
Note: initially it was planned to be yaml, but qt has no buit-in support for yaml. This file is not intended to be edited manually (when saving from gui is added) so json should be ok as well.
Closes: #8187 
`Storybook`
[simplescreenrecorder-2022-11-25_11.10.51.webm](https://user-images.githubusercontent.com/20650004/203962652-c108a15d-d445-4cdb-aee6-afd1ce11e3cb.webm)
> feat(Storybook): Figma links loaded from a JSON file

- src/app/modules/main/chat_section/chat_content/input_area/controller.nim
- src/app/modules/main/chat_section/chat_content/input_area/module.nim
- src/app/modules/main/chat_section/chat_content/input_area/view.nim
- src/app_service/service/chat/service.nim
- ui/app/AppLayouts/Chat/stores/RootStore.qml
- ui/app/AppLayouts/Chat/views/ChatContentView.qml
- ui/imports/shared/status/StatusChatInput.qml
This adds support for receiving copied images from the clipboard and pasting it into the chat input.
After pasting, chat input will recognize the image and render a preview similar to how it would do it when selecting images via the file dialog.
**Also important to note**:
At the time of this PR, it seems that desktop only supports sending jpegs to status-go. I'm not sure if this was deliberately done this way because the protocol says it supports jpg, png, webp and gif.
Because of this, pasting for example pngs will work, however transparency will be lost (which is also most likely the cause of #8220 )
This PR operates on that assumption. So while it adds support for copy/pasting images, it does not address the lack of file type support.
Closes #3395
> feat(chat): support copy & pasting images into chat input

- src/app/modules/main/activity_center/model.nim
- src/app/modules/main/activity_center/view.nim
- ui/StatusQ/src/StatusQ/Components/StatusDateGroupLabel.qml
- ui/app/mainui/activitycenter/popups/ActivityCenterPopup.qml
- ui/app/mainui/activitycenter/views/ActivityNotificationBase.qml
- ui/imports/shared/views/chat/MessageView.qml
Close #8434
Should help with binding loop with Qt 5.15
ActivityCenter
https://user-images.githubusercontent.com/2522130/203771797-f1943fdc-0303-4417-9f74-232fad5ab93f.mov
> hotfix(ActivityCenter): Fix binding loop for previousMessageIndex

- ui/app/mainui/activitycenter/views/ActivityNotificationMention.qml
- ui/app/mainui/activitycenter/views/ActivityNotificationMessage.qml
- ui/app/mainui/activitycenter/views/ActivityNotificationReply.qml
Fixes: #8121
Makes activity center reply clickable
https://user-images.githubusercontent.com/82511785/203430609-63a1f590-353e-4337-9e26-4b7209a76f9f.mov
> feat(ActivityCenter): Click on reply message jumps to message in chat log

- src/app_service/service/wallet_account/service.nim
Fixes #8401
Threads in Nim are very bad and when the app closes, the thread doesn't close until it is done. That means that the 20 minute timer needs to finish before it can be closed.
This partially breaks the history fetching. I want @alaibe 's and @Khushboo-dev-cpp 's eyes on this before merging. We'll need to move that timer to status-go. If possible, one from the wallet cohort should do it.
edit: @alaibe gave me the thumbs up to merge, so feel free to review
> hotfix(wallet): comment out history timer to fix app hanging on close

- ui/imports/shared/views/chat/MessageView.qml
Hide quick actions panel in non-joined chats
Hide mouse context menu with actions
Fixed: #8301
Quick actions panel visibility
Mouse context menu visibility
https://user-images.githubusercontent.com/117639195/204486765-3cdaffee-b04c-433b-926d-216f464ac025.mov
> fix(@desktop/chat): Hide quick actions panel in non-joined chats

- test/ui-test/src/screens/SettingsScreen.py
- test/ui-test/testSuites/global_shared/scripts/settings_names.py
- test/ui-test/testSuites/global_shared/steps/settingsSteps.py
- test/ui-test/testSuites/suite_settings/suite.conf
- test/ui-test/testSuites/suite_settings/tst_contactsFlow/test.feature
- test/ui-test/testSuites/suite_settings/tst_contactsFlow/test.py
- ui/app/AppLayouts/Profile/panels/ContactPanel.qml
- ui/app/AppLayouts/Profile/panels/ContactsListPanel.qml
- ui/app/AppLayouts/Profile/popups/SendContactRequestModal.qml
- ui/app/AppLayouts/Profile/views/ContactsView.qml
- ui/app/AppLayouts/Profile/views/MessagingView.qml
Partial fix of #6883 
This sends a contact request using the chat key
I'll create a new PR that uses a chat message to send a request
> test(Settings): adds a test that sends a contact request with chat key

- ui/StatusQ/src/StatusQ/Core/Utils/Utils.qml
- recognize parentheses, `(` and `)` respectively, as part of a URL when linkifying the hyperlink; these are valid URL characters
- also correct the "status-im" deep link prefix to the new form
Fixes: #8512
Fixes highlighting URLs containing `(` or `)`
Utils.linkifyAndXSS()
> fix: figma links pasted in channel are not clickable

- ui/app/mainui/activitycenter/popups/ActivityCenterPopup.qml
- ui/app/mainui/activitycenter/views/ActivityNotificationBase.qml
- ui/app/mainui/activitycenter/views/ActivityNotificationCommunityInvitation.qml
- ui/app/mainui/activitycenter/views/ActivityNotificationCommunityKicked.qml
- ui/app/mainui/activitycenter/views/ActivityNotificationCommunityMembershipRequest.qml
- ui/app/mainui/activitycenter/views/ActivityNotificationCommunityRequest.qml
- ui/app/mainui/activitycenter/views/ActivityNotificationContactRequest.qml
- ui/app/mainui/activitycenter/views/ActivityNotificationMention.qml
- ui/app/mainui/activitycenter/views/ActivityNotificationMessage.qml
- ui/app/mainui/activitycenter/views/ActivityNotificationReply.qml
Close #8499
Replace DelegateChooser with Loader
> fix(ActivityCenter): Get rid of DelegateChooser in ActivityCenterPopop

- ui/StatusQ/src/StatusQ/Components/StatusSmartIdenticon.qml
- ui/StatusQ/src/StatusQ/Core/StatusAssetSettings.qml
- ui/imports/shared/controls/chat/ProfileHeader.qml
- ui/imports/shared/controls/chat/UserImage.qml
Removes not working code for cropping tmp profile image.
It was a source of warnings in the app and storybook.
Qml `rect` type cannot be set to `undefined` like that:
```
property rect cropRect: undefined
```
Closes: #8519
> fix(general): removed not working code for cropping tmp profile image

- ui/StatusQ/src/StatusQ/Components/StatusSmartIdenticon.qml
- ui/StatusQ/src/StatusQ/Core/StatusAssetSettings.qml
- ui/app/AppLayouts/Profile/views/profile/MyProfileSettingsView.qml
- ui/imports/shared/controls/chat/ProfileHeader.qml
- ui/imports/shared/controls/chat/UserImage.qml
Fixes cropping for temporary profile images.
Closes: #8520
`MyProfileSettingsView`
[Kazam_screencast_00090.webm](https://user-images.githubusercontent.com/20650004/205007620-48b46a97-5c8d-4955-93be-187b4d6c1797.webm)
> fix(MyProfileSettingsView): Temporary image cropped properly

- ui/imports/shared/views/chat/InvitationBubbleView.qml
a simple refactor to use a QML Control with separate `background` and `contentItem`
Fixes: #8360
Fixes community invite box layout issues
InvitationBubbleView
> fix(InvitationBubbleView): Community invite box cta bleeds out of box

- ui/imports/shared/panels/ProfileBioSocialsPanel.qml
Fixes binding loops mentioned in the ticket (in the app and storybook).
Closes: #8536
`ProfileBioSocialsPanel`
> fix(ProfileBioSocialsPanel): binding loops fixed

- ui/StatusQ/src/StatusQ/Components/StatusMessage.qml
- ui/StatusQ/src/StatusQ/Components/private/statusMessage/StatusMessageReply.qml
- ui/app/AppLayouts/Chat/panels/SuggestionBoxPanel.qml
- ui/app/AppLayouts/Chat/panels/UserListPanel.qml
- ui/app/AppLayouts/Chat/panels/communities/CommunityMembersTabPanel.qml
- ui/app/AppLayouts/Chat/popups/community/MembershipRequestsPopup.qml
- ui/app/AppLayouts/Chat/views/ChatColumnView.qml
- ui/app/AppLayouts/Chat/views/ChatContentView.qml
- ui/app/AppLayouts/Chat/views/MembersSelectorView.qml
- ui/app/AppLayouts/Onboarding/views/InsertDetailsView.qml
- ui/app/AppLayouts/Profile/panels/ContactPanel.qml
- ui/app/mainui/AppMain.qml
- ui/app/mainui/Popups.qml
- ui/app/mainui/activitycenter/views/ActivityNotificationCommunityMembershipRequest.qml
- ui/app/mainui/activitycenter/views/ActivityNotificationContactRequest.qml
- ui/app/mainui/activitycenter/views/ActivityNotificationMessage.qml
- ui/imports/shared/controls/chat/ProfileHeader.qml
- ui/imports/shared/controls/chat/UserImage.qml
- ui/imports/shared/controls/delegates/ContactListItemDelegate.qml
- ui/imports/shared/status/StatusInputListPopup.qml
- ui/imports/shared/status/StatusStickersPopup.qml
- ui/imports/shared/views/ExistingContacts.qml
- ui/imports/shared/views/ProfileDialogView.qml
- ui/imports/shared/views/TransactionPreview.qml
- ui/imports/shared/views/chat/MessageContextMenuView.qml
- ui/imports/shared/views/chat/MessageView.qml
- ui/imports/utils/Utils.qml
- when calling `Utils.getColorHashAsJson()` we don't actually need to issue ID verification requests at all and there might be situations when we know beforehand that we don't need the ENS verification either
- change these helper functions' syntax and do early returns in that case
- in MessageContextMenuView, the "contact details" were duplicated, so remove one
- remove dead code, fix some warnings
Reduces the number of verification related RPC calls
A lot (mostly messaging)
Community, chat, user list, user profile:
Addressbook:
> chore: reduce the number of (verification) RPC calls

- src/app/modules/main/chat_section/module.nim
- restore contact request by pubkey in the model after removing from the model during the contact block
- fixes badge icon displaying after block/unblock
Fixed: #7520
Displaying contact requests in chat after blocking/unblocking
https://user-images.githubusercontent.com/117639195/204743254-270a0c89-838d-4dc2-a747-af0f834520e3.mov
> fix(@desktop/chat): Pending request disappear from the contacts list when blocked and unblocked

- ui/app/mainui/activitycenter/controls/ReplyBadge.qml
Close #8526
Re-layout and fix eliding reply badge 
> Fix(ActivityCenter): Fix reply badge text eliding

- src/app/boot/app_controller.nim
- src/app/modules/startup/io_interface.nim
- src/app/modules/startup/module.nim
- src/app_service/service/general/service.nim
- src/backend/general.nim
Fixes:
- https://github.com/status-im/status-desktop/issues/8552
> fix: display an error if StartMessenger fails

- src/app/global/local_account_sensitive_settings.nim
remove the dialog that asks users if they would like to open a link in Status Desktop's browser and always open them in the user's external browser
(merely changing defaults here wouldn't help for existing users)
Fixes #8568
Hardcodes opening links in an external browser
settings
> fix(settings): open links in external browser

- src/app_service/common/network_constants.nim
- src/app_service/service/accounts/service.nim
Fixes #8553
The torrent port was clashing with the release app since both of them have it on by default now. That was causing the messenger to fail on start. This new PORT_SHIFT env var can be used to shift the port of the torrent service and wakuV2. No more need to use WAKUV2_PORT. we can also add more ports that need shifting.
This enables opening multiple instances of the app very easily. Just increase PORT_SHIFT by one
> fix(network_constants): fix torrent port clash by adding PORT_SHIFT

- src/app/modules/shared_modules/keycard_popup/models/key_pair_selected_item.nim
- src/app/modules/shared_modules/keycard_popup/module.nim
- ui/app/AppLayouts/Profile/views/keycard/MainView.qml
- ui/imports/shared/popups/keycard/states/KeycardConfirmation.qml
Addressed all points from the issue:
- 01: Keycard settings menu labelling - fixed in this commit
- 02: Modal title renaming - not developed yet
- 03: Additional decision diamond and flow - not developed yet
- 04: Modal title renaming - not developed yet
- 05: Modal title renaming - done in issue #7035
- 06: Copy change - fixed in this commit
Fixes: #8458
> fix(@desktop/keycard): modal title edits and migrate flow

- ui/StatusQ/src/StatusQ/Core/Utils/emojiList.js
I'm sorry, this is probably the most silly thing of all time. But I like :smile:, and I find :smiley: creepy
Discords transforms :D to :smile:, so I'm happy. But status-desktop changes :D to :smiley:, so I can't sleep at night.
This PR changes :D to :smile: (:-D and =D still point to :smiley: for you creeps out here)
> Change `:D` to `:smile:` alias

- ui/app/AppLayouts/Profile/views/ContactsView.qml
Fixed tab content jump in `settings -> messaging -> contacts, requests`
The problem was that if `ContactsListPanel` does not have data - UI was not hidden and spacing was applied between the element without data and the next element.
Fixed: #8245 
settings -> messaging -> contacts, requests
The margin was discussed with Benji directly
https://user-images.githubusercontent.com/117639195/205107445-a3035e44-e650-45ea-aebb-742cdd8c4012.mov
> fix(@desktop/settings): Tab content jump fix

- src/app/modules/main/profile_section/ens_usernames/module.nim
- src/app/modules/main/stickers/module.nim
- src/app/modules/main/wallet_section/transactions/module.nim
- ui/app/AppLayouts/Profile/views/EnsDetailsView.qml
- ui/app/AppLayouts/Profile/views/EnsSearchView.qml
- ui/app/AppLayouts/Profile/views/EnsTermsAndConditionsView.qml
- ui/imports/shared/popups/SendModal.qml
- ui/imports/shared/status/StatusStickerMarket.qml
- ui/imports/shared/status/StatusStickerPackClickPopup.qml
- ui/imports/shared/views/NetworkCardsComponent.qml
- ui/imports/utils/Constants.qml
fix(@desktop/wallet): Wrong Password error should not be handled in the SendModal
fixes #8527
Handles the issues below:
- Wrong Password error should not be handled in the SendModal
- sender Address in advanced view should be capitalised
- While scrolling the gradient should show up on top of the content and not be added extra
Wallet
> fix(@desktop/wallet): Wrong Password error should not be handled in the SendModal

- src/app/modules/main/wallet_section/accounts/module.nim
- src/app_service/service/wallet_account/dto.nim
Fixes: #8582
The following function makes no sense:
```
proc getBalance*(self: WalletAccountDto, chainIds: seq[int]): float64 =
return self.tokens.map(t => t.getBalance(chainIds)).foldl(a + b, 0.0)
```
It's adding the balances of different tokens (for example, 10ETH + 5 USDC + 0.1BTC = 15.1USD).
The proper function is `WalletAccountDto::getCurrencyBalance`, since it first converts each token's balance to a common currency before adding them.
- Function `WalletAccountDto::getBalance` was removed
- Usages of `WalletAccountDto::getBalance`were replaced with `WalletAccountDto::getCurrencyBalance`
This fixes the balances shown for each acount on the wallet's LeftTabView, which now match the balances in the corresponding Account header.
Before:
After:
Wallet
> fix(@desktop/wallet): fix wallet account item balances

- ci/Jenkinsfile.e2e
fixes #8317
starts one server per node but allows up to 10 server to run in parallel
> feat(@test): parallelize test

- ui/app/AppLayouts/Chat/panels/InlineSelectorPanel.qml
- ui/app/AppLayouts/Chat/views/MembersSelectorView.qml
Subscribe on resolvedENS signal and if the chat key is valid - hide 'no results found' msg in the start chat
Fixed: #8541
Start chat 'no results found' msg displaying
> fix(@desktop/chat): Hide 'no results found' when entering the chat key in start chat

- src/app_service/service/community/service.nim
Fixes: #8539
Add `return` after cancel request to join response processing 
Communities
> fix(communities): Break loop when cancel request was sent

- src/app/core/notifications/notifications_manager.nim
- src/app/modules/main/controller.nim
- src/app/modules/main/io_interface.nim
- src/app/modules/main/module.nim
- src/app/modules/main/view.nim
- ui/main.qml
Fixes #4943
The custom OS notifications we have in place make it possible to click the notification and go to the right place in the app, but it causes a big issue in Windows; it breaks the tray icon, it becomes no longer clickable.
The easy fix I did here is the go back to using the QML `sendMessage` function. It works fine to send the notif and the tray icon keeps working. The only downside is we lose context when clicking on the notification, so it doesn't navigate to the chat.
IMO, this is a good tradeoff.
When we end up using QT6, doing a patch of `showMessage` should be more manageable.
> fix(windows): use QML's OS notification for Windows

- src/app_service/service/message/message_cursor.nim
- src/app_service/service/message/service.nim
- ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
It may happen `asyncLoadMoreMessagesForChat` is called many times in a row. Previously it did not check whether there is any pending fetch for a given chat, which resulted in many same cursors fetches from status-go. Furthermore, in this case, `lastUsedMsgCursor` ended up with the same value as `msgCursor` resulting in wrong state where there are no more messages to fetch.
- Simplified message loading code by introducing MessageCursor helper type
- Ensured messages are not loaded twice for the same cursor
fixes: #8602
- messages loading when scrolling
> fix(chat/messages): prevent multiple same cursor fetches

- ui/app/mainui/activitycenter/panels/ContactRequestCta.qml
- ui/app/mainui/activitycenter/popups/ReviewContactRequestPopup.qml
- ui/app/mainui/activitycenter/views/ActivityNotificationContactRequest.qml
- ui/app/mainui/activitycenter/views/ActivityNotificationMessage.qml
- ui/imports/shared/panels/AcceptRejectOptionsButtonsPanel.qml
Fixes: #8461
Details view popup for Contact Requests
https://user-images.githubusercontent.com/82511785/205679961-8ec2c404-be76-42db-88cc-cf466e1b3b05.mov
> feat(activity-center): Add details view dialog for contact requests

- src/app/modules/shared_models/social_link_item.nim
- src/app/modules/shared_models/social_links_model.nim
- src/app_service/common/social_links.nim
- storybook/pages/ProfileDialogViewPage.qml
- ui/StatusQ/src/StatusQ/Popups/StatusMenuItem.qml
- ui/app/AppLayouts/Profile/controls/StaticSocialLinkInput.qml
- ui/app/AppLayouts/Profile/panels/ProfileDescriptionPanel.qml
- ui/app/AppLayouts/Profile/popups/SocialLinksModal.qml
- ui/imports/shared/controls/SocialLinkPreview.qml
- ui/imports/shared/panels/ProfileBioSocialsPanel.qml
- ui/imports/shared/views/ProfileDialogView.qml
- ui/imports/utils/Constants.qml
- ui/imports/utils/Utils.qml
Rework the way social links are displayed/edited; we now only allow to enter a so called "handle" and then substitute that in the final URL template
This has several advantages:
- we display only the "handle" and don't have to elide some long URL
- we won't let users enter random URLs into their profile and spoof the viewing part into clicking it
Additionally, make the social link "button" clickable -> navigate to the target URL, and make the tooltip behave as "usual" (on mouse hover).
Fixes #7918
Fixes #8614
Simplifies displaying/editting social links in profile dialog
Social links
Profile preview:
Edit profile:
Edit social links:
> feat(SocialLinkPreview): links are too short to display even short urls

- src/app/modules/main/communities/controller.nim
- src/app/modules/main/communities/io_interface.nim
- src/app/modules/main/communities/module.nim
- src/app/modules/main/communities/view.nim
- src/app/modules/main/io_interface.nim
- src/app/modules/main/module.nim
- src/app/modules/main/view.nim
- src/app_service/service/community/async_tasks.nim
- src/app_service/service/community/service.nim
- ui/app/AppLayouts/Chat/stores/RootStore.qml
- ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
- ui/app/AppLayouts/CommunitiesPortal/stores/CommunitiesStore.qml
- ui/imports/shared/popups/ImportCommunityPopup.qml
- ui/imports/utils/Utils.qml
Status allows for importing communities via their private keys.
There's a requested feature that users should be able to import a community via its public key as well.
This will behave differently as private keys won't give users ownership of the communities. When importing via a (compressed) public key, Status will try to fetch information about the community from the network. If it finds such information, it'll load it into the app and create a communitiy view from which users can then request access.
If it can't find a community or community information in the network, the user will get a dedicated error message.
This commit also refactors the `ImportCommunityPopup` such that it uses `StatusDialog` and updates the copy accordingly since importing via public key is now possible as well. …
> feat(communities): allow community import via public key

- storybook/PagesModel.qml
- storybook/pages/MembersSelectorPage.qml
- storybook/pages/StatusChatInputPage.qml
- storybook/pages/UserListPanelPage.qml
- storybook/pages/UsersModelEditor.qml
- storybook/src/Models/UsersModel.qml
- storybook/src/Models/qmldir
- storybook/stubs/shared/stores/RootStore.qml
Adding StatusChatInput to storybook.
Reuse the usersModel and UsersModelEditor from UsersListPanelPage and MembersSelectorPage.
Part of #8471 
MembersSelectorPage
UsersListPanelPage
https://user-images.githubusercontent.com/47811206/205854844-fd0d578a-0f06-4224-aa4f-e20573d09288.mov
> Adding StatusChatInput to storybook

- ui/imports/shared/views/chat/InvitationBubbleView.qml
a simple refactor to use a QML Control with separate `background` and `contentItem`
Fixes: #8360
> CHERRY_PICK fix(InvitationBubbleView): Community invite box cta bleeds out of box

- scripts/notarize-macos-pkg.sh
Right now we don't see what's actually happening:
```
!!! Notariztion Error
{"tool-version":"5.4211.13411","tool-path":"\/Applications\/Xcode.app\/Contents\/SharedFrameworks\/ContentDeliveryServices.framework\/Versions\/A\/Frameworks\/AppStoreService.framework","os-version":"12.3.1","product-errors":[{"message":"You supplied an invalid RequestUUID: null","userInfo":{"NSLocalizedFailureReason":"Apple Services operation failed.","NSLocalizedRecoverySuggestion":"You supplied an invalid RequestUUID: null","NSLocalizedDescription":"You supplied an invalid RequestUUID: null"},"code":1515}],"warnings":[{"message":"altool has been deprecated for notarization and starting in late 2023 will no longer be supported by the Apple notary service. You should start using notarytool to notarize your …
```
> ci: show output from xcrun_altool on notarize error

- ui/app/AppLayouts/stores/RootStore.qml
- ui/app/mainui/AppMain.qml
- ui/imports/shared/stores/RootStore.qml
- ui/imports/utils/Audio.qml
Fix a bunch of problems with handling sound/notifications related options coming from the backend:
- `volume` and `notificationSoundsEnabled` live in a different settings object; adjust the stores for that
- unbreak loading the actual wav/mp3 files (was never working on Linux outside of AppImage!) -> use "qrc:/", same as the NIM backend does
- fix the volume scaling (backend has [1,100], QML is [0, 1])
- simplify our Audio QML item interface; no need for an extra property and resolving the URL twice (which results in broken scenarios mentioned above); we know which sounds we want to load
Closes #8668
Fixes notification sounds mute/volume
AppMain
> fix(Settings): cant switch off sounds for notifications

- src/app_service/service/token/service.nim
fixes #8623
This is expected as we can use it with symbol
> fix(@wallet): remove uneeded log

- ui/app/AppLayouts/Profile/views/NotificationsView.qml
- ui/imports/utils/Audio.qml
Use logarithmic scale instead of linear when interpreting the sound volume value
TLDR; we were literally overblowing the speakers with absolute sound volume levels; for the whole story I recommend reading: https://www.dr-lex.be/info-stuff/volumecontrols.html
Also play a sound preview when changing the volume in Settings
Needs https://github.com/status-im/dotherside/pull/83
Fixes #8426
Fixes sound volume for notifications
Audio component; Settings/Notifications&Sound
> fix(notifications): The sound of notifications is harsh and annoying

- ui/app/AppLayouts/Chat/layouts/SettingsPageLayout.qml
- ui/app/AppLayouts/Chat/panels/communities/CommunityOverviewSettingsPanel.qml
- ui/app/AppLayouts/Chat/panels/communities/CommunityPermissionsSettingsPanel.qml
- ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
Fixes #8455
- Added property `previousPageName` into `SettingsPageLayout`.
- Added needed slots in `CommunitySettingsView` to get - `previousPageName` property changes and display the correct string. 
- Renamed `updateState` method to `navigateBack` to have a better accurate name.
`Community Settings`
https://user-images.githubusercontent.com/97019400/206232810-1b995ce0-568e-4534-a8ba-31c91a42466c.mov
> fix(CommunitySettings): Previous page navigations are broken in community settings sections

- src/app/boot/app_controller.nim
- src/app/modules/main/chat_section/module.nim
- src/app_service/service/community/service.nim
- src/app_service/service/message/service.nim
Fixes #7512
The problem was twofold.
1. We didn't try to fetch the messages when we re-joined, since the cursor was not reseted
2. The messages are not longer in the DB since they get deleted on joining.
I fixed 1. by reseting the cursor on leave and calling fetch on spectate I fixed 2. in the status-go PR so that we no longer delete the messages when leaving.
~~Based on top of https://github.com/status-im/status-desktop/pull/8664 to not conflict with the cursor and to be able to test the fetching~~
Status-go PR: https://github.com/status-im/status-go/pull/3006
> fix(community): fix messages being gone when we re-join a community

- src/app/modules/main/activity_center/module.nim
- src/app/modules/main/chat_section/chat_content/messages/controller.nim
- src/app/modules/main/chat_section/chat_content/messages/io_interface.nim
- src/app/modules/main/chat_section/chat_content/messages/module.nim
- src/app/modules/main/chat_section/chat_content/messages/view.nim
- src/app/modules/main/chat_section/chat_content/module.nim
- src/app/modules/shared_models/message_item.nim
- src/app/modules/shared_models/message_model.nim
- src/app_service/service/message/dto/message.nim
- src/app_service/service/message/service.nim
- src/backend/messages.nim
- ui/StatusQ/src/StatusQ/Components/StatusMessage.qml
- ui/StatusQ/src/StatusQ/Components/StatusMessageHeader.qml
- ui/app/AppLayouts/Chat/stores/MessageStore.qml
- ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
- ui/imports/shared/views/chat/MessageView.qml
- ui/imports/utils/Constants.qml
Fixes #7643
This adds the backend to resend. It then hooks the button to it. This also adds a visual state for when we are sending. This gives a good indication that a message was sent.
I don' think there is a design for the `sending` state, so for now, I just put a `Sending...` label.
In the video, you can see the `Sending..` label real quick. In a public channel, the encryption is faster, so I don't even see the label.
[Screencast 2022-12-08 16:08:36-sending.webm](https://user-images.githubusercontent.com/11926403/206567875-b953a494-033c-402f-8265-4fa75ef7447d.webm)
FYI, I couldn't actually test the Resend with a message that failed to send, since I couldn't repro. So I faked it, and I did get the right signals for `sent`. So if someone still has the `Resend` shown, please test this. …
> fix(messages): fix Resend btn not working and add Sending visual state

- src/app/global/app_sections_config.nim
- src/app/modules/main/module.nim
- test/ui-test/testSuites/global_shared/scripts/global_names.py
- ui/app/mainui/AppMain.qml
- ui/i18n/qml_base.ts
- ui/i18n/qml_en.ts
- ui/imports/utils/Utils.qml
... and do it the proper way, ie. make the string translatable as we
can't handle translations coming from NIM files at the moment
(separate commit to update/extract the messages)
Closes #8418
Changes Chat->Messages in the navbar tooltip
AppMain/NavBar
> fix: Rename "Chat" tooltip to "Messages"

- ui/main.qml
Set configured font size after Status app restart
Fixes: #8462
Font size after app restart
> fix(@desktop/chat): use configured font size after restart

- ui/app/AppLayouts/Chat/layouts/SettingsPageLayout.qml
Fixes: #8293
`SettingsPageLayout` was used as base component for `CommunityOverview`, but content type isn't `Flickable`.
I think that solution when `SettingsDirtyToastMessage` unexpectedly got a control for `contentItem` was wrong.
In fact of PR type I won't rectaforing this component, I will fix just warning. But I think, we should change it.
Settings
> fix(warnings): Avoid flickable manipulations in SettingsPageLayout when dirty toast message isn't active

- ui/imports/shared/views/ProfileDialogView.qml
Tokens -> Assets
NFTs -> Collectibles
(to be consistent with the rest of the app)
Fixes #8716
Fixes wording in the Profile Dialog
> fix(ProfileDialogView): Wrong name "Tokens" in Profile preview

- ui/app/AppLayouts/Chat/views/communities/CommunityNewPermissionView.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityPermissionsView.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityWelcomePermissionsView.qml
Fixes #8584
Modified `Flickable` in `CommunityNewPermissionView`, `CommunityWelcomePermissionsView` and `CommunityPermissionView` to `StatusScrollView`
`CommunityXXXPermissionsView`
https://user-images.githubusercontent.com/97019400/207327162-4dd3fe9d-973f-481d-becd-7568e91be5cb.mov
> fix(CommunityPermissions): Change `Flickable` to `StatusScrollView`

- src/app/modules/main/module.nim
If `activeSectionId` does point to section that is not restored correctly (by any reason), then the app will crash. That's becasue code assumes there is always an active section set and it will try to reference null item in this case.
fixes: #8785
The above happened because (most likely) joining a community that was removed previously does not restore it after app restart.
It should be cherry-picked to 0.8.x branch
> fix: prevent crash by ensuring there is active section on app start

- src/app/modules/main/wallet_section/collectibles/current_collectible/controller.nim
- src/app/modules/main/wallet_section/collectibles/current_collectible/io_interface.nim
- src/app/modules/main/wallet_section/collectibles/current_collectible/module.nim
- src/app/modules/main/wallet_section/collectibles/current_collectible/view.nim
- src/app/modules/main/wallet_section/collectibles/module.nim
- src/app_service/service/collectible/service.nim
- ui/app/AppLayouts/Wallet/controls/CollectibleDetailsHeader.qml
- ui/app/AppLayouts/Wallet/views/RightTabView.qml
- ui/app/AppLayouts/Wallet/views/collectibles/CollectibleDetailView.qml
- ui/imports/shared/controls/InformationTag.qml
#5076
This PR completes [#5076](https://github.com/status-im/status-desktop/issues/5076)
Reordered several items 
Depends on https://github.com/status-im/status-go/pull/2984
Wallet
Tested several different cases, resized window to check everything works as expected (particularly of interest: large number of properties and/or long description)
Tested on light and dark theme
Design: https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=6455%3A123667&t=aBz9k21RQUEWxgEt-0
PR:
[collectible_details-2022-11-28_18.13.24.webm](https://user-images.githubusercontent.com/11161531/204382386-38cdb53c-8404-4ea1-b6da-51ef35701d88.webm)
I've checked the design and this PR matches it, except for:
- The design shows network name "Ethereum", while the backend returns name "Ethereum Mainnet" …
> fix(@desktop/wallet): adjust collectible details screen to design

- ui/imports/shared/stores/RootStore.qml
Fixes: #8293
Fix warnings
```
Warning: qrc:/imports/shared/stores/RootStore.qml: ReferenceError: chatSectionChatContentInputArea is not defined (qrc:/imports/shared/stores/RootStore.qml:4294967295, )
Warning: qrc:/imports/shared/stores/RootStore.qml: ReferenceError: chatSectionChatContentInputArea is not defined (qrc:/imports/shared/stores/RootStore.qml:4294967295, )
Warning: qrc:/imports/shared/stores/RootStore.qml: ReferenceError: chatSectionChatContentInputArea is not defined (qrc:/imports/shared/stores/RootStore.qml:4294967295, )
Warning: qrc:/imports/shared/stores/RootStore.qml:39: TypeError: Cannot read property 'isNonArchivalNode' of undefined (qrc:/imports/shared/stores/RootStore.qml:39, )
```
shared RootStore
> fix(warnings): Remove warnings from shared RootStore

- storybook/PagesModel.qml
- storybook/pages/HoldingsDropdownPage.qml
- ui/app/AppLayouts/Chat/controls/community/ExtendedDropdownContent.qml
- ui/app/AppLayouts/Chat/controls/community/HoldingsDropdown.qml
- ui/app/AppLayouts/Chat/controls/community/qmldir
- ui/app/AppLayouts/Chat/helpers/CommunityPermissionsHelpers.qml
- ui/app/AppLayouts/Chat/helpers/qmldir
- ui/app/AppLayouts/Chat/stores/CommunitiesStore.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityNewPermissionView.qml
- `HoldingsDropdown` added to the Storybook
- some routines not related to backend excluded from `CommunitiesStore` to `CommunityPermissionsHelpers`
- search for collectibles dropdown 
Closes: https://github.com/status-im/status-desktop/issues/7158
`Storybook`, `ExtendedDropdownContent`
[Kazam_screencast_00095.webm](https://user-images.githubusercontent.com/20650004/205961984-c5b952b6-9c12-4aa4-973b-156ba77b1f85.webm)
> feat(CommunityPermissions): search for collectibles dropdown 

- ui/imports/shared/status/StatusChatInput.qml
Fix https://github.com/status-im/status-desktop/issues/8822
On foreign layouts where Shift isn't needed for `:`, emoji completion is a bit broken
(example azerty layout)
chat-input
This branch with AZERTY:
Master:
> fix(chat-input): Colon detection for foreign keyboard layout

- src/app/modules/main/wallet_section/collectibles/collectibles/controller.nim
- src/app/modules/main/wallet_section/collectibles/collectibles/io_interface.nim
- src/app/modules/main/wallet_section/collectibles/collectibles/module.nim
- src/app/modules/main/wallet_section/collectibles/module.nim
- src/app_service/service/collectible/async_tasks.nim
- src/app_service/service/collectible/service.nim
Fixes #8406
Collection fetch is now non-blocking. This makes collection expansion more responsive.
Added a couple of changes to Collectibles service as preparation for future work.
Old:
[collection_expand_old-2022-11-29_15.42.29.webm](https://user-images.githubusercontent.com/11161531/204618274-1f0309df-47f0-4e20-a3bb-060a93f9e806.webm)
New:
[collection_expand_new-2022-11-29_15.37.38.webm](https://user-images.githubusercontent.com/11161531/204618300-9cf525a3-0f26-4d82-9729-6525f71a9143.webm)
Depends on https://github.com/status-im/status-desktop/pull/8487
Wallet -> Collectibles
> fix(@desktop/wallet) make collection expansion more responsive

- src/app/modules/main/chat_section/chat_content/users/view.nim
fixes: #8832
group chat members addition/removal
> fix(chat/groups): do not propagate empty members sequence

- src/app/core/notifications/notifications_manager.nim
- src/app/global/global_events.nim
- src/app/modules/main/chat_section/module.nim
- src/app_service/service/contacts/service.nim
1. Block sending messages from us as notifications. This can happen when we send a contact request. After the recipient accepts a contact request, a chat is created and we receive our "send request" message as a new msg in the chat.
2. Notify the sender of the contact request about accepting the contact request by the recipient
Closed: #8488 #8381
- Contact service
- Sending chat notifications
https://user-images.githubusercontent.com/117639195/207837108-2fab49d1-67d0-4b72-8577-fd84b6b0b13b.mov
> fix(@desktop/notifications): sent contact request accepted notification fix

- storybook/CMakeLists.txt
- storybook/qmlTests/TestComponents/tst_StatusChatInput.qml
- storybook/qmlTests/main.cpp
- storybook/qmlTests/src/TextUtils.cpp
- storybook/qmlTests/src/TextUtils.h
- storybook/stubs/shared/stores/RootStore.qml
- ui/StatusQ/src/StatusQ/Core/Utils/Emoji.qml
There are two commits. The first one is removing the qrc mentioning from emoji regex parser. This is needed in order for emoji and other StatusChatInput features that depend on text length computation to work properly on projects that do not use qt resource system.
The second one is adding qml test for StatusChatInput covering the following scenarios:
```
Scenario: StatusChatInput initialisation
Given a new instance of StatusChatInput
When there is no keyboard input
Then the StatucChatInput raw text is empty
But the StatusChatInput is configured to support Rich Text
```
```
Scenario: StatusChatInput will display any typed Ascii visible character
Given a new instance of StatusChatInput
When the user is typing any Ascii visible character as <text>
Then the text is displayed as it is typed …
```
> Add qml tests for StatusChatInput

- storybook/pages/CommunityPermissionsSettingsPanelPage.qml
- storybook/pages/CommunityPermissionsViewPage.qml
- ui/app/AppLayouts/Chat/controls/community/PermissionItem.qml
- ui/app/AppLayouts/Chat/layouts/SettingsPageLayout.qml
- ui/app/AppLayouts/Chat/panels/communities/CommunityPermissionsSettingsPanel.qml
- ui/app/AppLayouts/Chat/stores/CommunitiesStore.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityNewPermissionView.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityPermissionsView.qml
Closes [#8581](https://github.com/status-im/status-desktop/issues/8581)
- Enabled `duplicate` action (mocked).
- Enabled `delete` action (mocked) and added / updated navigations in case all permissions are removed. Added delete confirmation popup.
- Enabled `edit` action (mocked) where changes are detected and the `dirty changes toast` appears properly.
**COMMENTS:**
- All is mocked data!!!
- Edit / dirty changes managements first step done in js. Here a new task to improve it by creating a new C++ object type: https://github.com/status-im/status-desktop/issues/8830
Community permissions
https://user-images.githubusercontent.com/97019400/207913637-3b13f638-e274-4382-a3a1-de24b6fc8257.mov
> feat(CommunitySettings): Implement UI for`edit`, `duplicate` and `remove` actions in community permissions page

- ui/main.qml
Fixes #8848
I'm not 100% sure why the issue is fixed by this, but I was able to pin point the source with a bisect and by running the Squish test for public chats over and over.
> fix: random crash when joining a channel for the first time

- src/app/modules/main/chat_section/chat_content/messages/view.nim
- src/app/modules/main/chat_section/controller.nim
- src/app_service/service/mailservers/service.nim
`loadingHistoryMessagesInProgress` was moved to content module but the property was never removed from the messages module view
see: fc24f16525e6f71b3a00848b4efd94543753ac0b
> chore: remove unused `loadingHistoryMessagesInProgress` property

- storybook/pages/StatusChatInputPage.qml
- storybook/qmlTests/TestComponents/tst_StatusChatInput.qml
- ui/imports/shared/status/StatusChatInput.qml
Fixes #8740, #8742, #8731, #7686
1. Don't allow mention invalidation by altering mention with mouse or keyboard
3. Don't allow mention duplication on the same position in mentionsPos
4. Clean mentions after text with mentions changes
5. Fix mention selection
6. Make sure mention is separated by text with valid separators (by default we're using only space)
7. Cursor will consider the mention as an object and will jump over it as it would be a single character (placing cursor inside leaves room for mention invalidation)
StatusChatInput.qml
tst_statusChatInput.qml
StatusChatInputPage.qml
https://user-images.githubusercontent.com/47811206/208405944-adc76aeb-9615-47a1-aff4-0b4861f3d85f.mov
> Fix Mentions in statusChatInput - don't allow unintended mention invalidation

- src/app/boot/app_controller.nim
- src/app/modules/main/controller.nim
- src/app/modules/main/io_interface.nim
- src/app/modules/main/module.nim
- src/app/modules/main/view.nim
- src/app/modules/startup/controller.nim
- src/app/modules/startup/io_interface.nim
- src/app/modules/startup/module.nim
- ui/app/AppLayouts/Profile/popups/ChangePasswordModal.qml
- ui/imports/utils/Constants.qml
1. If the user has biometrics enabled and changes the password, we need to let the user enter a current password, check it and if it's valid we need to store it to the keychain and update the `storeToKeychain` prop to `store`
2. Button rename
Fixes: #7349
- changing the password
- login via biometrics
https://user-images.githubusercontent.com/117639195/208120591-91918053-5252-4982-a311-91582bbb8485.mov
> fix:(@desktop/keystone): Request saving password to keystone on a startup after changing the password through settings

- src/app/global/utils.nim
- ui/imports/shared/views/chat/MessageContextMenuView.qml
Fixes #8755
Paths are not formatted correctly on Windows. There were three `/`s and also the path cannot start with `/`
edit: I tested on both Windows and Linux
> fix(image): fix image download on Windows

- ui/StatusQ/sandbox/controls/ListItems.qml
- ui/StatusQ/sandbox/demoapp/StatusAppCommunitiesPortalView.qml
- ui/StatusQ/src/StatusQ/Components/StatusCommunityCard.qml
- ui/StatusQ/src/StatusQ/Components/StatusItemSelector.qml
- ui/StatusQ/src/StatusQ/Components/StatusListItemTag.qml
- ui/app/AppLayouts/Chat/controls/community/PermissionItem.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityNewPermissionView.qml
- ui/app/AppLayouts/Profile/views/wallet/AccountView.qml
- ui/app/AppLayouts/Wallet/panels/SelectGeneratedAccount.qml
- ui/imports/shared/popups/SendModal.qml
- ui/imports/shared/popups/keycard/helpers/KeyPairItem.qml
- ui/imports/shared/popups/keycard/helpers/KeycardItem.qml
Fixes https://github.com/status-im/status-desktop/issues/8580
1. `StatusListItemTag`: Changed API and added test elide property when a specific width is forced
2. Changed `PermissionItem` component to not allowing adding labels with long texts that exceeds the content itself
3. `NewPermissionView`: Some adjustments in holdings tags icon size/position to fit the design
`CommunityPermissions/PermissionsView`.
`CommunityPermissions/NewPermissionView`.
`StatusListItemTag` and components that use it.
https://user-images.githubusercontent.com/97019400/208924593-e4cfc21e-ae54-4945-9703-a24ea8403558.mov
> fix:`PermissionItem` component allows to add tags with long texts that exceed the content itself

- storybook/PagesModel.qml
- storybook/figma.json
- storybook/pages/CommunityNewPermissionViewPage.qml
- storybook/pages/CommunityPermissionsSettingsPanelPage.qml
- storybook/pages/InDropdownPage.qml
- storybook/pages/StatusChatListAndCategoriesPage.qml
- storybook/src/Models/ChannelsModel.qml
- ui/StatusQ/src/StatusQ/Components/StatusItemSelector.qml
- ui/StatusQ/src/StatusQ/Controls/StatusChatInfoButton.qml
- ui/StatusQ/src/StatusQ/Controls/StatusCheckBox.qml
- ui/app/AppLayouts/Chat/controls/community/CommunityCategoryListItem.qml
- ui/app/AppLayouts/Chat/controls/community/CommunityListItem.qml
- ui/app/AppLayouts/Chat/controls/community/InDropdown.qml
- ui/app/AppLayouts/Chat/controls/community/qmldir
- ui/app/AppLayouts/Chat/panels/communities/CommunityPermissionsSettingsPanel.qml
- ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityNewPermissionView.qml
- ui/nim-status-client.pro
1. Adds `InDropdown` popup for selecting whole community or particular channels
2. Integrates `InDropdown` with `CommunityNewPermissionsView` component
3. Add some extensions to used components (`StatusItemSelector`, `StatusCheckBox`, `StatusChatInfoButton`)
4. Adds minor fix to `nim-status-client.pro` to display `qmldir` files in QtCreator
5. Adds several new pages to Storybook
Closes: #6041 
`CommunityNewPermissionsView`, `StatusItemSelector`, `StatusCheckBox`, `StatusChatInfoButton`
[Kazam_screencast_00097.webm](https://user-images.githubusercontent.com/20650004/208645062-8ccf29d8-e4ab-4623-82e5-4f6404dece20.webm)
> feat(CommunityPermissions): New permision - InDropdown added and integrated

- src/app/modules/main/chat_section/controller.nim
- src/app/modules/main/chat_section/io_interface.nim
- src/app/modules/main/chat_section/module.nim
- src/app_service/service/community/service.nim
- ui/app/AppLayouts/Chat/views/ChatColumnView.qml
Fixes: #8297
- Fixes empty chat view after:
- - creating a new category with an active channel
- - adding/removing an active channel to the category
- - changing active channels inside the category and removing any channel from the category
- Keep the correct active state for the model when the community was edited
- Refactored chat selection based on the active state of the chat model
- Tiny optimization in community service during searching for changes
- Chat view in the community
- Correct chat selection in the community
https://user-images.githubusercontent.com/117639195/208879197-32b775dd-edf1-41fe-b065-d18e833d6217.mov
> fix(@desktop/communities): empty chat view during adding/removing active channel to the category

- ui/imports/shared/status/StatusChatInput.qml
Do not allow sending an empty message
Fixes: #8268
https://user-images.githubusercontent.com/117639195/209141808-570f1492-6bc2-41ba-9679-ccdd0422df0d.mov
> fix(@desktop/chat): Do not allow sending empty message

- ui/StatusQ/src/StatusQ/Components/StatusMessage.qml
- ui/imports/shared/views/chat/MessageView.qml
Fix #8675
Added padding between messages as specified in Figma: 
topPadding - 8 if the current message has header, 2 otherwise 
bottomPadding - 8 if both current and next message have header, 2 otherwise
MessageView
StatusMessage
https://user-images.githubusercontent.com/47811206/208677808-c5198dc7-a944-4c01-9770-be4345ce290f.mov
> fix(messagesView): Increase spacing between chat messages

- ui/main.qml
Fixes #8726
This took me longer than I dare to admit to fix.
Turns out it's a simple call in QML that made it fails on open. I fixed by checking if the wanted position is within the possible screen layout. If not, I reset to the default position and size.
I think the bug only appeared on Windows BTW
> fix(windows): fix app not showing when monitor setup changed

- ui/app/AppLayouts/Profile/views/profile/MyProfileSettingsView.qml
Fixed saving Profile changes with enabled Biometrics. Do not show store password popup if biometrics toggle was not enabled
Fixes: #8843
Saving biometrics profile settings
> fix(@desktop/profile): do not show store password to keychain dialog during saving Bio with enabled biometrics

- src/app/modules/main/chat_section/chat_content/users/controller.nim
- src/app/modules/main/chat_section/chat_content/users/module.nim
1. Decrease amount of chat_getMembers calls
2. Do not try to add members to the model if we are not a member of the community. Members won't be added anyway as they will have joined=false status
Fixes: #8801
Community members list display after the join
> fix(@desktop/community): Decrease amount of chat_getMembers calls

- src/app/modules/main/activity_center/item.nim
- src/app/modules/main/activity_center/model.nim
- src/app/modules/main/activity_center/module.nim
- src/app/modules/shared_models/user_item.nim
- src/app_service/service/activity_center/dto/notification.nim
- src/app_service/service/contacts/dto/contacts.nim
- src/app_service/service/contacts/service.nim
- ui/app/mainui/activitycenter/panels/ActivityCenterPopupTopBarPanel.qml
- ui/app/mainui/activitycenter/panels/ContactRequestCta.qml
- ui/app/mainui/activitycenter/panels/IncomingContactVerificationCta.qml
- ui/app/mainui/activitycenter/panels/MembershipCta.qml
- ui/app/mainui/activitycenter/panels/OutgoingContactVerificationCta.qml
- ui/app/mainui/activitycenter/popups/ActivityCenterPopup.qml
- ui/app/mainui/activitycenter/views/ActivityNotificationContactRequest.qml
- ui/app/mainui/activitycenter/views/ActivityNotificationContactVerification.qml
- ui/app/mainui/activitycenter/views/ActivityNotificationMessage.qml
- ui/imports/utils/Constants.qml
- ui/imports/utils/Utils.qml
Close #7373, #8222
Needs https://github.com/status-im/status-go/pull/3029
Add identity verification notifications in AC
ActivityCenter, Contacts
https://user-images.githubusercontent.com/2522130/208482742-e41236d7-b4c6-452d-a42a-ea66e47623a8.mov
> fix(ActivityCenter): Add identity verification AC notifications

- src/app/global/local_account_sensitive_settings.nim
- src/app/modules/main/chat_section/module.nim
- src/app/modules/main/module.nim
Restore the last open chat for different sections.
1. Create a new QSettings group
2. Store the last opened chat by key/value, where the key is section and the value is chat
3. Remove the key with value if the community was removed
4. Remove the key with value if the community does not have any chat
Fixes: #8889
Depends on:
- status-im/nimqml#44
- status-im/dotherside#84 
Chat selection
https://user-images.githubusercontent.com/117639195/210069116-ac439ec7-7821-424a-8096-76ee6f78b8a5.mov
> fix(@desktop/chats): restore last opened chat during app launch

- src/app/global/utils.nim
- ui/imports/shared/popups/ContactVerificationRequestPopup.qml
- ui/imports/shared/status/StatusChatInput.qml
- ui/imports/utils/Utils.qml
We always take the plain text from the clipboard but even the plaintext can contain HTML tags, so escape those and wrap the result in a `<div style='white-space: pre-wrap'>foo</div>` container. That way we preserve not only the linebreaks but also any whitespace or tags. This also improves code snippet pasting a _lot_ (see 2nd screenshot).
The problem was that TextEdit was interpreting the HTML tags as if we were pasting HTML text (in fact we don't want this, we always meant to support plaintext only)
Remove manipulating the `messageInputField.cursorPosition`, it's done automatically by `messageInputField.insert` and we'd get it wrong most of the time anyways :)
Fixes #8919
Fixes #8538
Fix pasting of plain text to preserve formatting
Text:
Inside a codeblock:
> fix: Chat input: can't send html text from the clipboard

- src/app/modules/main/chat_section/module.nim
- src/app/modules/main/controller.nim
- src/app/modules/main/module.nim
Fixes #8943
If a channel is muted, don't increase `unviewedMessagesCount` for it. 
Only count mentions
> fix(chat-badge): don't count unread messages when restarting

- test/ui-test/src/drivers/SquishDriver.py
- test/ui-test/src/screens/SettingsScreen.py
- test/ui-test/src/screens/StatusChatScreen.py
- test/ui-test/src/screens/StatusMainScreen.py
- test/ui-test/src/screens/StatusWelcomeScreen.py
- test/ui-test/testSuites/global_shared/scripts/global_names.py
- test/ui-test/testSuites/global_shared/scripts/login_names.py
- test/ui-test/testSuites/global_shared/scripts/settings_names.py
- test/ui-test/testSuites/global_shared/steps/commonInitSteps.py
- test/ui-test/testSuites/global_shared/steps/settingsSteps.py
- test/ui-test/testSuites/global_shared/steps/steps.py
- test/ui-test/testSuites/suite_communities/tst_communityFlows/test.feature
- test/ui-test/testSuites/suite_messaging/shared/steps/chatSteps.py
- test/ui-test/testSuites/suite_onboarding/shared/steps/signUpSteps.py
- test/ui-test/testSuites/suite_settings/tst_contactsFlow/test.feature
- test/ui-test/testSuites/suite_settings/tst_contactsFlow/test.py
- ui/StatusQ/src/StatusQ/Components/StatusMessageHeader.qml
- ui/app/AppLayouts/Onboarding/views/LoginView.qml
- ui/app/AppLayouts/Profile/popups/SendContactRequestModal.qml
- ui/app/AppLayouts/Profile/views/ContactsView.qml
- ui/imports/shared/controls/chat/menuItems/ViewProfileMenuItem.qml
- ui/imports/shared/popups/SendContactRequestModal.qml
- ui/imports/shared/views/ProfileDialogView.qml
> test(contact): add a test that sends a contact request  from the chat

- ui/StatusQ/src/StatusQ/Layout/StatusAppNavBar.qml
partially revert ba811acc27eb27f73a4259e318f9e0d9c0f5f6fa and silence the warning
Fixes white margins on top/bottom of the nav bar
StatusAppNavBar
Before:
After:
> fix: unbreak StatusAppNavBar margins

- ui/app/AppLayouts/Chat/views/ChatContentView.qml
- ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
Fixes #8966
Put focus back to chat input when the edit is done
ChatContentView, ChatMessagesView
> fix: Chat Input isn't focused after editing a message

- ui/app/AppLayouts/Chat/views/CreateChatView.qml
- ui/app/mainui/AppMain.qml
`CreateChatView` didn't have a `statusStickersPopup` (was null), so when the user clicked the message box buttons, we had a qml error that the sticker popup is null and further code did not execute
Fixed: #8730 
CreateChatView
https://user-images.githubusercontent.com/117639195/211282497-2abacb78-e7cf-4fc4-9d7e-85fd57727fbb.mov
> fix(@desktop/chat): message box buttons do not work in group chat creation screen

- src/app/modules/shared_models/active_section.nim
- src/app/modules/shared_models/section_item.nim
- src/app/modules/shared_models/section_model.nim
- ui/app/AppLayouts/Chat/views/ChatContentView.qml
- ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
- ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
- ui/app/mainui/AppMain.qml
Fixes: #8761
Add ban community state. Also fix some warnings.
Communities
> feat(communities): Process ban state for community

- ui/app/AppLayouts/Chat/panels/SuggestionBoxPanel.qml
- ui/imports/shared/status/StatusChatInput.qml
- follow the order of properties that `ProfileUtils.displayName()` uses
elsewhere in the application
- prefer nickname or ensName over displayName if the user has those
Fixes: #8691
Fixes wrong suggestions for mentioned users
Multiple users with the nickname of "alex":
Selecting a user with nickname:
Suggestion activated and pasted correctly into chat input:
> fix(StatusChatInput): return correct mention suggestions

- src/app/modules/main/chat_section/module.nim
- ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
Fixes
- show mention or unread msg badge for inactive section
- non-disappearing section and channel badge during app launch (when we restore on channel with unread msg)
- show unread msg marker for the channel which was active before switching to the settings section and then user return to this channel
Fixes: #8940
- new messages marker display
- badge icon
https://user-images.githubusercontent.com/117639195/210971549-32e346ed-62e4-4fcc-94b1-92e8f4b3e80f.mov
> fix(desktop/chat): show the badge during receiving the new messages in inactive section

- ui/StatusQ/src/StatusQ/Components/StatusListItemTag.qml
Fixes #8876
It removes `Layout.rightMargin` on the text component. The text is now centered horizontally even though the close button is not visible.
`StatusListItemTag`
> fix(SQ/StatusListItemTag):  Text is not horizontally centered

- ui/app/mainui/activitycenter/views/ActivityNotificationMessage.qml
Close #8915, close #8950
Limit ActivityNotificationMessage's text to 350 chars (That should be fixed value  tom make all notifications look similar)
ActivityCenter
> feat(ActivityCenter): Update ActivityNotificationMessage's text maximum width

- ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
- ui/app/AppLayouts/Chat/views/CreateChatView.qml
Fixes #8749
I couldn't fully test it because it needs #8991 to be fixed to see if the message is sent correctly
> fix(CreateChatView): enable mentioning people selected in create chat

- ui/app/AppLayouts/Chat/stores/RootStore.qml
- ui/app/AppLayouts/Chat/views/ChatColumnView.qml
- ui/app/AppLayouts/Chat/views/ChatContentView.qml
- ui/app/AppLayouts/Chat/views/CreateChatView.qml
Allow sending an initial message during group chat creation.
The problem is that we send a message for the new chat during `ChatContentView` component is completed (onCompleted. slot), and at this moment new chat item is not set as Active due to View is constructing, so we send the initial message during group chat creation to the previously opened chat
Fixes: #8991 
Send chat messages
https://user-images.githubusercontent.com/117639195/211526529-3012765e-43f6-4b81-b603-a568be50488e.mov
> fix(@desktop/chat): show message which was sent during group chat creation

- ui/StatusQ/src/StatusQ/Components/StatusMessage.qml
Revert to using Date functions; Qt broke the API between Qt 5.14 and Qt 5.15
(https://doc.qt.io/archives/qt-5.14/qml-qtqml-qt.html#formatDateTime-method vs https://doc.qt.io/qt-5/qml-qtqml-qt.html#formatDateTime-method)
We'll move this function to C++ in a followup PR to preserve the API compatibility while keeping it fast enough
Fixes #9037
Restore message timestamps under Qt 5.14
StatusMessage
> hotfix(StatusMessage): restore timestamps

- ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
Closes #8947 
Fixes Community left column banners where overlapping
Community left column
> fix(Community): banners where overlapping

- ui/StatusQ/src/StatusQ/Controls/StatusNavBarTabButton.qml
- ui/app/mainui/AppMain.qml
- another bit on the road to reduce startup time and be more conservative
towards RAM usage
- remove more imperative JS code
- only preload/prepare the currently active community, not all of them on
startup
- separate commit to delay context menu creation for StatusNavBarTabButton
Fixes https://github.com/status-im/status-desktop/issues/8782
AppMain
Everything still works as expected :)
> chore(AppMain): use Loaders more aggressively, unloading any previous unused section

- ui/app/AppLayouts/Chat/controls/community/ExtendedDropdownContent.qml
Fixes #8827
Removed (hidden) minting and import option in assets dropdown
Assets (still named as tokens) dropdown
> fix(Community Permissions): Remove (hide) minting and import option in assets dropdown

- ui/app/AppLayouts/Chat/controls/community/PermissionItem.qml
Fixes #9049
It removes `and` text between items in `In` section.
Community Permissions -- Permissions Item
> fix(Community Permissions): Update `PermissionItem` according to the new design

- ui/app/AppLayouts/Chat/layouts/SettingsPageLayout.qml
- ui/app/AppLayouts/Chat/panels/communities/CommunityPermissionsSettingsPanel.qml
- ui/imports/shared/popups/SettingsDirtyToastMessage.qml
Fixes #9046
- It exposes new properties in `SettingsDirtyToastMessage` to customise buttons texts. 
- It exposes new properties in `SettingsPageLayout` to customise dirty toast buttons texts.
`SettingsDirtyToastMessage` button texts.
This is how the issue looks like:
These are some other pages where the toast was already used so, we can see in the following images that nothing it's being broken by this change:
> fix(Community Permissions): Update change detected buttons labels according to the new design

- src/app/modules/shared_models/message_model.nim
Fixes: #9014
Update `NewMessagesMaker` when some message was deleted
Chat
> fix(chat): Update new messages marker when message was removed

- src/app/modules/main/activity_center/module.nim
- src/app/modules/main/chat_section/chat_content/messages/module.nim
- src/app/modules/main/chat_section/chat_content/messages/view.nim
- src/app/modules/main/chat_section/chat_content/module.nim
- src/app/modules/shared_models/message_item.nim
- src/app/modules/shared_models/message_item_qobject.nim
- src/app/modules/shared_models/message_model.nim
- src/app_service/service/message/dto/message.nim
- test/nim/message_model_test.nim
- test/ui-test/testSuites/suite_wallet/tst_wallet/test.feature
- ui/app/AppLayouts/Chat/stores/MessageStore.qml
- ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
- ui/imports/shared/views/chat/MessageView.qml
- ui/imports/utils/Utils.qml
Fixes [#7754](https://github.com/status-im/status-desktop/issues/7754)
Uses the already available QuotedMessage data that comes with the Message to show the replied message instead of fetching it using JSON. It's cleaner, less error prone (fixes the issue above) and is way faster.
~~I put this as a Draft because I still need to figure out what to do with deletions of original messages. I can set it as `deleted` when we receive the signal, but if I restart, the message is back, because status-go doesn't handle the og message deletion in the QuotedMessage section.
I need to figure out if that's a bug or if it's intended.~~
The bug has been fixed in status-go. Here is the PR: https://github.com/status-im/status-go/pull/3054
> Fix empty reply message

- src/app/modules/main/activity_center/module.nim
- src/app/modules/main/chat_section/chat_content/messages/module.nim
- src/app/modules/main/chat_section/chat_content/module.nim
- src/app/modules/shared_models/message_item.nim
- src/app/modules/shared_models/message_item_qobject.nim
- src/app/modules/shared_models/message_model.nim
- ui/app/AppLayouts/Chat/stores/RootStore.qml
- ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
- ui/imports/shared/views/chat/MessageContextMenuView.qml
- ui/imports/shared/views/chat/MessageView.qml
Adds the action to copy the right-clicked message's text.
It copies the unparsed text (no html).
For that, I had to add it in the MessageItem and expose it in the model.
I also fixed the copy MessageId action that didn't show + didn't work even if it would have shown.
Plus some small cleanups.
The text copied in the screenshot above results in 
```
**bold** test
enter
emopty
*italic* ok ~~strik~~
```
> feat(context-menu): add Copy message action in message context menu

- ui/StatusQ/src/StatusQ/Components/StatusMessage.qml
- ui/imports/shared/views/chat/MessageView.qml
Part of #3067 
Depends on #9031. In #9031 the hover is disabled while scrolling. This means the quick action Items will not be created at all while scrolling.
Create quick action Items only when needed.
Chat history quick actions
> perf(chatScroll): Create message quick context items only when message row is hovered

- src/app/modules/main/wallet_section/transactions/controller.nim
- src/app/modules/main/wallet_section/transactions/io_interface.nim
- src/app/modules/main/wallet_section/transactions/model.nim
- src/app/modules/main/wallet_section/transactions/module.nim
- src/app/modules/main/wallet_section/transactions/view.nim
- src/app_service/service/transaction/async_tasks.nim
- src/app_service/service/transaction/service.nim
- ui/imports/shared/views/HistoryView.qml
fixes #7278
The a load more button was greyed out even before the entire Tx list was presented , not allowing users to load more transaction
Added loading icon to the load more button so its clear a request is ongoing
Each time we request transaction they are made for all the networks enabled by the user, the issue was that we were showing that loading is completed before all the requests were completed and we wouldnt see the loader on the UI at all.
Wallet
https://user-images.githubusercontent.com/60327365/210331311-058262e9-8ad0-4892-a0cf-210610bb44e7.mov
> fix(@desktop/wallet): Wallet -> Activity tab: transaction history issues

- src/app/modules/main/stickers/controller.nim
- src/app/modules/main/stickers/io_interface.nim
- src/app/modules/main/stickers/models/sticker_pack_list.nim
- src/app/modules/main/stickers/module.nim
- src/app/modules/main/stickers/view.nim
- src/app_service/service/stickers/async_tasks.nim
- src/app_service/service/stickers/service.nim
- ui/imports/shared/status/StatusStickersPopup.qml
Fixes #6567 
Improve installing stickers code so it does not hang when there is no internet connection.
The solution contains 2 fixes:
- [status-go](https://github.com/status-im/status-go/pull/3043) fix - using timeout context - the operation times out after 5 seconds
- executing status-go request in thread in order not to block UI
Chat / installing stickers
https://user-images.githubusercontent.com/61889657/210208304-dc3e8a37-e14a-490f-9b32-9621d386ca2a.mov
> 6567 stickers hang when disconnected

- Makefile
- monitoring/HotComponentFromSource.qml
- monitoring/HotLoader.qml
- monitoring/Main.qml
- monitoring/MonitorEntryPoint.qml
- ui/nim-status-client.pro
Allows building the app with support for live inspection. When enabled, the separate window is opened to present inspection results. The intention is to track raw data coming from the backend, what can be beneficial for both development and debugging/profiling.
To compile the app with the monitoring support, `MONITORING=true` should be passed to `make`.
When compiled with the monitoring support, the monitoring window can be disabled by defining `DISABLE_MONITORING_WINDOW` env variable.
This is the initial setup, further work is intended to be provided in separate prs.
Closes: #8786
Depends on: https://github.com/status-im/dotherside/pull/85
[Kazam_screencast_00098.webm](https://user-images.githubusercontent.com/20650004/210600259-a41fd2b9-98b2-44af-b253-85ba872a0801.webm)
> feat(general): Initial setup for app monitoring tool

- storybook/pages/CommunityNewPermissionViewPage.qml
- storybook/pages/CommunityPermissionsSettingsPanelEditor.qml
- storybook/pages/CommunityPermissionsSettingsPanelPage.qml
- storybook/pages/HoldingsDropdownPage.qml
- storybook/src/Models/AssetsCollectiblesIconsModel.qml
- storybook/src/Models/AssetsModel.qml
- storybook/src/Models/ModelsData.qml
- storybook/src/Models/PermissionsModel.qml
- storybook/src/Models/qmldir
- ui/app/AppLayouts/Chat/controls/community/AssetsPanel.qml
- ui/app/AppLayouts/Chat/controls/community/ExtendedDropdownContent.qml
- ui/app/AppLayouts/Chat/controls/community/HoldingTypes.qml
- ui/app/AppLayouts/Chat/controls/community/HoldingsDropdown.qml
- ui/app/AppLayouts/Chat/helpers/CommunityPermissionsHelpers.qml
- ui/app/AppLayouts/Chat/stores/CommunitiesStore.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityNewPermissionView.qml
Fixes #8816
- It updates enumerators that were defining `tokens` instead of `assets`.
- It updates property names and labels.
- It updates signals and components names.
- It updates storybook.
The only visual change is in  `Community Permissions/How holds dropdown`.
Internal changes - `Community Permissions` flow and related `storybook` pages.
> fix(Community Permissions): Update `tokens` names to `assets`

- test/ui-test/src/screens/StatusCommunityScreen.py
- test/ui-test/testSuites/suite_communities/shared/scripts/community_names.py
- test/ui-test/testSuites/suite_communities/tst_communityFlows/test.feature
Verify results of edit community tests only when the element is visible
The only assumption why they can fail is that after clicking `save changes`, we requested the `name` before it was updated and displayed
P.S. Locally tests are not failing
Potential fix for #8977
Squish community test
> test(@desktop/community): edit community tests - verify results only when the element is visible

- monitoring/MonitorEntryPoint.qml
- monitoring/MonitorUtils.qml
- monitoring/qmldir
1. Fixes bug - accessing some keycard-related properties resulted with segfault when
accessed in inappropriate time, e.g. via tools like GammaRay or internal
inspection tool.
2. Implements backend's properties and models visualization
- objects exposed as context properties can be freely browsed (types, values)
- models are visualized in a generic way as a table
Depends on: https://github.com/status-im/dotherside/pull/88
[Kazam_screencast_00099.webm](https://user-images.githubusercontent.com/20650004/212334816-d5ca7483-c397-4d6a-810f-4eb8ffe95efc.webm)
> feat(Monitoring): Backend's properties and models visualization 

- src/app/modules/main/chat_section/chat_content/messages/controller.nim
- src/app/modules/main/chat_section/chat_content/messages/io_interface.nim
- src/app/modules/main/chat_section/chat_content/messages/module.nim
- src/app/modules/main/chat_section/chat_content/messages/view.nim
- ui/app/AppLayouts/Chat/stores/MessageStore.qml
- ui/imports/shared/views/chat/MessageView.qml
Part of #3067
Adding signals for chat color, icon, type and channel settings in MessageStore in order to use property bindings in MessageView instead of backend calls on delegate creation.
Related to PR #9031
Community settings representation in chat history (admin settings and members are allowed to pin message)
Chat settings representation in chat history (chat color, icon, type)
https://user-images.githubusercontent.com/47811206/212032123-c2fec5ea-67cf-4350-b44d-b2acea892b45.mov
> perf(chatScroll): Adding signals for chat settings in MessageStore

- ui/imports/shared/views/chat/MessageView.qml
Fixing regression introduced by #9085
The Reactions popup was being destroyed because its parent was getting destroyed by the loader.
Chat reactions
https://user-images.githubusercontent.com/47811206/212666101-f257a872-b71d-4a1b-a64a-1c0184891ace.mov
> Fix message view quick actions regression

- src/app_service/service/currency/service.nim
When implementing the Cache for CurrencyAmount format, a single object was shared between all tokens with the same peg, resulting in a wrong symbol. This PR fixes that.
> fix(@desktop/wallet): fix wrong symbol for pegged tokens

- src/app/modules/main/activity_center/module.nim
- src/app/modules/main/chat_section/chat_content/messages/module.nim
- src/app/modules/main/chat_section/chat_content/module.nim
- src/app/modules/shared_models/message_item.nim
- src/app/modules/shared_models/message_item_qobject.nim
- src/app/modules/shared_models/message_model.nim
- src/app_service/service/message/dto/message.nim
- test/nim/message_model_test.nim
- ui/imports/shared/views/chat/MessageView.qml
Because we've switched to `QuotedMessage` as an attached payload to messages to make message replies data more reliable, we lost some of the author information in imported messages, that was available prior to that move.
This commit introduces `quotedMessageAuthorDisplayName` and `quotedMessageAuthorAvatar` to our model so it can be set in case we can't retrieve contact details for a given message (which is always the case for imported messages)
> fix: make avatar info in replies of imported messages work again

- ui/app/AppLayouts/Profile/popups/backupseed/Acknowledgements.qml
This is to ensure users don't get confused with the fact there's more checkboxes to check in the modal until they can continue.
Depending on viewport size, checkboxes can be hidden but it's not obvious that the area is scrollable.
See #8651
Closes #8651
> fix(BackupSeedModal): always show vertical scrollbar

- src/app/modules/main/chat_section/module.nim
Fixes #9152
I had forgotten that we did that when I removed the contact request button  and popup
> chore(badge): stop counting contact request in chat section badge

- ui/app/mainui/AppMain.qml
Mentions #9131
This is partial fix for #9131 that limits opening more one one popup per component. I believe it can be helpful regardless of actual fix of mailserver
AppMain
> fix(AppMain): Open only one popup per component

- ui/StatusQ/src/StatusQ/Core/LocaleUtils.qml
Fixes #9013
Currency amounts smaller than the resolution are now shown as "<(resolution) (unit)".
> feat(@desktop/wallet): handle very small currency amounts

- src/app/modules/main/activity_center/item.nim
- ui/app/mainui/activitycenter/views/ActivityNotificationCommunityMembershipRequest.qml
- ui/app/mainui/activitycenter/views/ActivityNotificationMessage.qml
- ui/imports/shared/views/chat/SimplifiedMessageView.qml
1. Fix some qml warnings
2. Align text properly if SimplifiedMessageView has badge
3. Don't count verified verification notification as unread
ActivityCenter
> hotfix(ActivityCenter): Fix warnings and text align with messageBadge

- ui/StatusQ/src/StatusQ/Components/StatusMessage.qml
- ui/StatusQ/src/StatusQ/Core/Theme/StatusColors.qml
- ui/StatusQ/src/StatusQ/Core/Theme/StatusDarkTheme.qml
- ui/StatusQ/src/StatusQ/Core/Theme/StatusLightTheme.qml
- ui/StatusQ/src/StatusQ/Core/Theme/ThemePalette.qml
Use the colors defined by design:
```
Light theme: Light Desktop / Blue 20% (4360DF 20%)
Dark theme: Dark Desktop / Blue 20% (869EFF 20%)
```
Separate commit to fixup palette color groups handling
Fixes https://github.com/status-im/status-desktop/issues/8271
Fixes highlight colors for message found
StatusMessage, Theme
Light theme:
Dark theme:
> fix: Highlight color of jump-to-message has too little contrast

- ui/app/AppLayouts/Chat/views/ChatHeaderContentView.qml
- ui/app/AppLayouts/Chat/views/ChatView.qml
- ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
Fixes https://github.com/status-im/status-desktop/issues/9145
Open add/remove member text field via context menu to the group chat.
https://user-images.githubusercontent.com/25482501/212966387-0120c2fe-d069-4bc0-b329-e04815422fb3.mov
> fix(ContactsColumnView): Open add/remove group member on context menu

- storybook/PagesModel.qml
- storybook/figma.json
- storybook/pages/PermissionQualificationPanelPage.qml
- ui/app/AppLayouts/Chat/panels/communities/PermissionQualificationPanel.qml
- ui/app/AppLayouts/Chat/panels/communities/qmldir
- ui/app/AppLayouts/Chat/views/communities/CommunityNewPermissionView.qml
Shows some details regarding members fulfilling permission and counts of members with known/uknown addresses.
Closes: #9044
`CommunityNewPermissionView`
> feat(CommunityPermissions): UI support to show the % of members fulfilling permission

- src/app/modules/shared_models/message_model.nim
Fixes #9156
Fixes it by checking new messages added to the model and updating the quoted message if it's the right message ID and the quoted message was not already populated.
This is hard to manually reproduce without waiting a day for messages to go in the store node and then receive them out of order.
What I did was I modified the `chat_contact/module` and added this to `viewDidLoad`:
```nim
self.messagesAdded(@[
MessageDto(
id: "replyMessage",
responseTo: "quotedMessage",
`from`: "0x04b2a87e119964bf1b338a80f5aecf8f09aa6b246172c0951bdee0ca8ef1f402e5b90eeeb48d9539ec69886ecadb070cb1e81ccc7588a2b93968b172f832745ef5",
alias: "Hospitable Frizzy Sealion",
seen: true,
outgoingStatus: "",
rtl: false,
parsedText: @[ParsedText(
`type`: "paragraph",
literal: "",
destination: "",
children: …
```
> fix(replies): update quoted message data when receiving new messages

- src/app/modules/main/activity_center/module.nim
- src/app/modules/main/chat_section/chat_content/messages/module.nim
- src/app/modules/main/chat_section/chat_content/module.nim
- src/app/modules/shared_models/message_item.nim
- src/app/modules/shared_models/message_item_qobject.nim
- src/app/modules/shared_models/message_model.nim
- src/app_service/service/message/dto/message.nim
- test/nim/message_model_test.nim
- ui/imports/shared/views/chat/MessageView.qml
Because we've switched to `QuotedMessage` as an attached payload to messages to make message replies data more reliable, we lost some of the author information in imported messages, that was available prior to that move.
This commit introduces `quotedMessageAuthorDisplayName` and `quotedMessageAuthorAvatar` to our model so it can be set in case we can't retrieve contact details for a given message (which is always the case for imported messages)
> [CHERRY_PICK] fix: make avatar info in replies of imported messages work again

- ui/app/AppLayouts/Chat/controls/community/EnsPanel.qml
- ui/app/AppLayouts/Chat/controls/community/HoldingsDropdown.qml
- ui/app/AppLayouts/Chat/stores/CommunitiesStore.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityNewPermissionView.qml
- ui/imports/shared/controls/AmountInput.qml
- Fixed ENS icon in "Who holds"
- Fixed locale handling in `AmountInput` (warning was generated, locale was set improperly)
- ENS tab simplified according to updated design
Closes #8818 
`EnsPanel`, `HoldingsDropdown`, `CommunityNewPermissionsView`
> chore(CommunityPermissions): ENS tab simplified according to updated design

- test/ui-test/testSuites/global_shared/steps/settingsSteps.py
- test/ui-test/testSuites/suite_wallet/shared/steps/walletInitSteps.py
- Updated `walletInitSteps` and `settingsSteps` properly: `settingsSteps.py` was referring to some `wallet_init_steps` methods but it was not imported. Reorganization and cleanup.
`suite_settings`
> test(suite_settings): Restore broken tests

- ui/app/AppLayouts/Chat/panels/SuggestionFilterPanel.qml
- ui/imports/shared/status/StatusChatInput.qml
Closes #8495
removes extra markup when typing any text before mention
status chat input & text message
https://user-images.githubusercontent.com/31625338/213291232-4bc50abd-198e-4d73-8efd-6729c480f9ae.mov
one more bug found related to @everyone mention, reported [here](https://github.com/status-im/status-desktop/issues/9186)
> fix(message): removed extra markup when typing before mention

- ui/app/AppLayouts/Chat/views/communities/CommunityNewPermissionView.qml
Closes #9195
It adds logic to hidden  `Add` button when the number of items 5 is reached.
Community Permissions / Create new permission
https://user-images.githubusercontent.com/97019400/213519016-b99c6f00-5cd9-4222-b834-5f8d26be46d9.mov
> feat(Community Permissions): Hide `Who holds - Add` button when there are 5 items already added

- src/app/boot/app_controller.nim
- src/app_service/service/mailservers/service.nim
This should allow doing individual storenode requests that can take up to 30s, and when logging out, it should not stop the app from closing.
Requires
- https://github.com/status-im/status-go/pull/3129
> fix: cancel mailserver requests on shutdown

- test/ui-test/testSuites/suite_communities/tst_communityFlows/test.feature
- test/ui-test/testSuites/suite_onboarding/tst_signUpSeedPhraseNegativeCases/test.feature
- test/ui-test/testSuites/suite_onboarding/tst_statusLoginPassword/test.feature
- test/ui-test/testSuites/suite_onboarding/tst_statusSignUp/test.feature
- test/ui-test/testSuites/suite_settings/tst_contactsFlow/test.feature
- test/ui-test/testSuites/suite_settings/tst_mainSettingsSection/test.feature
- test/ui-test/testSuites/suite_wallet/tst_transaction/test.feature
Tagged with `@mayfail` some scenarios that seem to be unstable / broken on CI and also locally.
`SETTINGS:`
1. tst_contactsFlow --> The user can add a contact with a chat key
2. tst_mainSettingsSection --> The user can switch state to online 
3. tst_mainSettingsSection --> The user can switch state to offline 
4. tst_mainSettingsSection --> The user can switch state to automatic
5. tst_mainSettingsSection --> The user can change the password and login with new password
`ONBOARDING:`
1. tst_statusSignUp --> The user signs up with imported seed phrase and and its state is online
2. tst_statusLoginpassword -- > User tries to login with an invalid password
3. tst_signUpSeedPhraseNegativeCases -->  User signs up with wrong imported seed phrase
`COMMUNITIES:`
1. tst_communityFlows --> The admin …
> test: Skip broken/unstable tests

- storybook/PagesModel.qml
- storybook/figma.json
- storybook/pages/CommunityNewPermissionViewPage.qml
- storybook/pages/PermissionConflictWarningPanelPage.qml
- ui/app/AppLayouts/Chat/panels/communities/PermissionConflictWarningPanel.qml
- ui/app/AppLayouts/Chat/panels/communities/qmldir
- ui/app/AppLayouts/Chat/stores/CommunitiesStore.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityNewPermissionView.qml
Closes [#8738](https://github.com/status-im/status-desktop/issues/8738)
- It adds conflicts warning in `New permission` page. Mocked data.
- It adds new pages and updates figma files in storybook.
`Community Permission / Create new permission`
https://user-images.githubusercontent.com/97019400/214085887-ffb10816-2088-44b3-b6d7-c2e361d31acc.mov
> feat(Community Permissions): Add conflicts waring in `New permission` page

- src/app/modules/main/chat_section/chat_content/module.nim
- src/app/modules/main/chat_section/chat_content/users/module.nim
- src/app/modules/main/chat_section/module.nim
Community (chat_section) now has its own usersMembers and shares this data with chat_content. This allows us:
1. Decrease the amount of `chat_getMember` calls to DB
2. Reduce `usersMembers` duplicate data in memory for the communities
3. Speed up startup
Closes: #9090
status-go PR: https://github.com/status-im/status-go/pull/3122
Chat members
> refactor(@desktop/channel): refactor members list to only have one list per community

- src/app/modules/main/chat_section/chat_content/messages/module.nim
- src/app/modules/shared_models/message_item.nim
- ui/StatusQ/src/StatusQ/Components/StatusDateGroupLabel.qml
- ui/StatusQ/src/StatusQ/Components/private/statusMessage/StatusMessageReply.qml
- ui/app/AppLayouts/Chat/panels/UserListPanel.qml
- ui/imports/shared/views/chat/MessageView.qml
- optimizes StatusMessageReply and StatusDateGroupLabel 
- fixes a couple of issues with displayName being wrong in various places
Fixes: https://github.com/status-im/status-desktop/issues/9016
StatusMessageReply, StatusDateGroupLabel
Contact with a local nickname (Alexxx/Alex99), original msg and reply:
Correct (repeated) date group labels, same correct date formatting as in the msg tooltips:
> chore: optimize StatusMessageReply/StatusDateGroupLabel

- storybook/pages/HoldingsDropdownPage.qml
- storybook/src/Models/AssetsModel.qml
- ui/app/AppLayouts/Chat/controls/community/EnsPanel.qml
- ui/app/AppLayouts/Chat/controls/community/ExtendedDropdownContent.qml
- ui/app/AppLayouts/Chat/controls/community/HoldingTypes.qml
- ui/app/AppLayouts/Chat/controls/community/HoldingsDropdown.qml
- ui/app/AppLayouts/Chat/controls/community/ListDropdownContent.qml
- ui/app/AppLayouts/Chat/controls/community/ThumbnailsDropdownContent.qml
- ui/app/AppLayouts/Chat/controls/community/TokenItem.qml
- ui/app/AppLayouts/Chat/controls/community/TokenPanel.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityNewPermissionView.qml
Implements logic preventing from duplicating tokens and ens names in `Who holds` section when creating/editing community permissions.
Closes: #8817 
Components related to `Community Permissions` functionality.
[Kazam_screencast_00107.webm](https://user-images.githubusercontent.com/20650004/214429305-538ab21b-cbb9-4b80-85cd-8c92188cd7e5.webm)
> feat(CommunityPermissions): prevent adding tokens and ens names that are already chosen

- ui/imports/shared/views/chat/MessageContextMenuView.qml
Fixes #9295
hide the "Copy message (ID)" actions when in profile or emoji reactions mode 
MessageContextMenuView
> fix(MessageContextMenuView): "Copy message" action visible in emoji reactions and profile clicks

- storybook/pages/CommunityNewPermissionViewPage.qml
- storybook/pages/CommunityPermissionsSettingsPanelPage.qml
- storybook/pages/InDropdownPage.qml
- ui/StatusQ/src/StatusQ/Components/StatusItemSelector.qml
- ui/app/AppLayouts/Chat/controls/community/InDropdown.qml
- ui/app/AppLayouts/Chat/controls/community/PermissionListItem.qml
- ui/app/AppLayouts/Chat/controls/community/PermissionsDropdown.qml
- ui/app/AppLayouts/Chat/stores/CommunitiesStore.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityNewPermissionView.qml
- Disable granting admin permission for non-owners
- Simplify InDropdown popup (selecting only channels, no add channel button)
- Setting icon/default values for 'In' section depending on chosen permission
- Adjust behavior of 'Hide permission' switch depending on selected permission
Closes #9050 
Needed alignments for `StatusSwitch` are excluded to a separate ticket: https://github.com/status-im/status-desktop/issues/9212
`CommunityNewPermissionView` and releted components
[Kazam_screencast_00104.webm](https://user-images.githubusercontent.com/20650004/213686907-e33edeea-ddeb-48a1-9261-631a59ac1442.webm)
> [Community Permissions] Update `Is allowed`, `In` and `Hide permission` logic according to the new design

- storybook/mocks/DotherSide/StatusSyntaxHighlighter.qml
- ui/imports/shared/status/StatusChatInput.qml
@mentions have a special `onRelease()` key handler that makes sure a space is inserted around the mention when needed. 
Fix the `onRelease()` handler to prevent control or otherwise unprintable characters being inserted as text. This happened when pressing a keyboard shortcut involving the `Ctrl` modifier
(2 separate commits to fixup other minor issues)
Fixes: https://github.com/status-im/status-desktop/issues/7685
Fixes unprintable characters appearing when pressing a keyboard shortcut
> fix(StatusChatInput): don't insert control characters

- test/ui-test/src/screens/StatusAccountsScreen.py
Updated `findAccount` method since statement `When the user "xxx" logs in with password "xxx"` was broken due to `accountsList` iteration was wrong.
Tests that call the following statement: `When the user "xxx" logs in with password "xxx"`
I.e: `tst_groupChat`
> test(onboarding): Select specific account was broken

- src/app_service/service/message/service.nim
- test/ui-test/testSuites/suite_messaging/tst_OneToOneChatFlow/test.feature
Fixes #9297
This was caused by the fact we skip new message signals when we don't have the cursor for it.
This might undo some of @osmaczko 's performance improvement, but that improvement caused a huge regression.
> fix(message-service): fix receiving messages from channels not loaded

- ui/imports/shared/views/chat/MessageContextMenuView.qml
- fetch latest dotherside for the fix
- minor cleanup
Fixes #9307
Fix saving image to the correct folder
MessageContextMenuView
> fix(chat): Download image is saving to wrong folder

- src/app/modules/main/activity_center/controller.nim
- src/app/modules/main/activity_center/io_interface.nim
- src/app/modules/main/activity_center/item.nim
- src/app/modules/main/activity_center/model.nim
- src/app/modules/main/activity_center/module.nim
- src/app/modules/main/activity_center/view.nim
- src/app_service/service/activity_center/service.nim
- src/backend/backend.nim
- ui/app/mainui/activitycenter/popups/ActivityCenterPopup.qml
- ui/app/mainui/activitycenter/stores/ActivityCenterStore.qml
- ui/app/mainui/activitycenter/views/ActivityNotificationBase.qml
Close #8074
Needs https://github.com/status-im/status-go/pull/3126
Replace custom AC notifications counting with `wakuext_unreadAndAcceptedActivityCenterNotificationsCount `
ActivityCenter
https://user-images.githubusercontent.com/2522130/214000836-33a865fc-069a-4607-85f6-e50178d35a9e.mov
> feat(ActivityCenter): Move AC notifications counting to status-go

- src/app/modules/shared_models/token_model.nim
- src/app_service/common/cache.nim
- src/app_service/service/token/service.nim
- ui/app/AppLayouts/Profile/views/EnsTermsAndConditionsView.qml
- ui/imports/shared/popups/SendModal.qml
Fixes https://github.com/status-im/status-desktop/issues/9264
FIxes https://github.com/status-im/status-desktop/issues/9281
This fixes the process of buying ENS. It works now.
There're more places where `CurrencyAmount` should be properly processed. I left it out of this PR, as intention was to fix ENS buying process.
* `token_model.rowData` now returns `tokenBalance` and `totalCurrencyBalance` as JSON
* `ENSTermsAndConditions` processed tokenBalance` and `totalCurrencyBalance` as JSON
* Fixed `init` function in `cache.nim` 
* Separated token service initialization into 2 parts, improved logging messages
`SendModal`, token service
> fix: Fixed tokens initialization. Fixed SendModal for ENS.

- src/app/core/signals/remote_signals/community.nim
- src/app/modules/main/communities/controller.nim
- src/app/modules/main/communities/io_interface.nim
- src/app/modules/main/communities/module.nim
- src/app/modules/main/communities/view.nim
- src/app_service/service/community/service.nim
- ui/app/AppLayouts/CommunitiesPortal/popups/DiscordImportProgressContents.qml
- ui/app/AppLayouts/CommunitiesPortal/stores/CommunitiesStore.qml
This adjust the front-end for the import tool by handling new properties that have been added to the discord import progress signals.
Namely, the import is now done in chunks, so the progress signal contains information about how many chunks have been processed.
This needs: https://github.com/status-im/status-go/pull/3134
Closes #9262 #9261
> Adjust import tool front-end to latest refactor

- ui/app/mainui/AppMain.qml
- ui/imports/shared/panels/ModuleWarning.qml
they stopped appearing after the introduction of `localAppSettings.testEnvironment`
Fixes https://github.com/status-im/status-desktop/issues/9354
Fixes app banners
AppMain, ModuleWarning
Before (update check banner):
After:
> fix: unbreak ModuleWarning banners

- src/app/modules/main/controller.nim
connect to the correct signal
the store node (aka mailserver) is no longer a dialog that would let the user select a new available mailserver; we care about a working and _active_ mailserver here
Fixes #9358
AppMain
Offline:
Back online:
Banners gone:
> fix: "Cannot connect to store node" banner never disappears

- ui/app/AppLayouts/Chat/controls/community/CommunityDescriptionInput.qml
- ui/app/AppLayouts/Chat/controls/community/CommunityNameInput.qml
- ui/app/AppLayouts/Chat/panels/communities/CommunityEditSettingsPanel.qml
- ui/app/AppLayouts/Chat/popups/community/CreateChannelPopup.qml
- ui/app/AppLayouts/CommunitiesPortal/panels/CommunityColorPanel.qml
- ui/imports/utils/Constants.qml
- Allow in community name/description and channel name only numbers, ANSII letters, underscores whitespaces, and hyphens (taken from Profile name restrictions)
- Block saving the data if an input error is showing
- Disable the "Select community color" button during setting community color if an invalid color hex was set
Fixes: #9180
Community name/description, channel name creation
Saving community changes
Saving community color changes
https://user-images.githubusercontent.com/117639195/215474448-2a102c67-f9a8-472f-902e-c01d4e6c819a.mov
> fix(@desktop/communities): enforce alphanumerical characters in community name/description, channel name

- storybook/PagesModel.qml
- storybook/pages/StatusScrollViewPage.qml
- ui/StatusQ/src/StatusQ/Core/StatusScrollView.qml
- ui/StatusQ/src/StatusQ/Popups/StatusColorDialog.qml
- ui/app/AppLayouts/Chat/controls/community/CommunityBannerPicker.qml
- ui/app/AppLayouts/Chat/controls/community/CommunityLogoPicker.qml
- ui/app/AppLayouts/Chat/controls/community/CommunityOptions.qml
- ui/app/AppLayouts/Chat/controls/community/InDropdown.qml
- ui/app/AppLayouts/Chat/panels/communities/CommunityEditSettingsPanel.qml
- ui/app/AppLayouts/CommunitiesPortal/controls/CommunityColorPicker.qml
- ui/app/AppLayouts/CommunitiesPortal/controls/CommunityTagsPicker.qml
- ui/imports/shared/status/StatusStickersPopup.qml
Cleaned up binding loop warnings related to
ScrollView and added StatusScrollView in
storybook
As part of #8864
Cleans up binding loop warnings related to
ScrollView and adds StatusScrollView in
storybook
###Affected areas
StatusScrollView
https://user-images.githubusercontent.com/31625338/215132676-442244cd-46b3-40f6-b518-7f83a18096a5.mov
> Fix(desktopapp): adding scrollview to storybook

- src/app/boot/app_controller.nim
- src/app/modules/main/profile_section/ens_usernames/controller.nim
- src/app/modules/main/profile_section/ens_usernames/io_interface.nim
- src/app/modules/main/profile_section/ens_usernames/model.nim
- src/app/modules/main/profile_section/ens_usernames/module.nim
- src/app/modules/main/profile_section/ens_usernames/view.nim
- src/app_service/service/ens/async_tasks.nim
- src/app_service/service/ens/dto/ens_username_dto.nim
- src/app_service/service/ens/service.nim
- src/app_service/service/network/service.nim
- src/app_service/service/settings/service.nim
- src/backend/ens.nim
- ui/app/AppLayouts/Profile/popups/ENSPopup.qml
- ui/app/AppLayouts/Profile/stores/EnsUsernamesStore.qml
- ui/app/AppLayouts/Profile/views/EnsDetailsView.qml
- ui/app/AppLayouts/Profile/views/EnsListView.qml
- ui/app/AppLayouts/Profile/views/EnsSearchView.qml
- ui/app/AppLayouts/Profile/views/EnsTermsAndConditionsView.qml
- ui/app/AppLayouts/Profile/views/EnsView.qml
Fixes #3234 
Corresponding status-go PR: https://github.com/status-im/status-go/pull/3066
* Support ENS usernames on different networks.
* Only current network ENS usernames are shown in settings.
* The new table is maintained fully in status-go, not from app (as it was before)
* Preferred username is temporarily dumb-fixed during network chain: https://github.com/status-im/status-desktop/issues/9035
ENS usernames settings
https://user-images.githubusercontent.com/25482501/211618608-3a0654fa-72c8-4fa9-a146-3fd88ad9640a.mov
> ENS usernames depend on the network

- ui/StatusQ/src/StatusQ/Core/StatusScrollView.qml
All `StatusModal` popups got broken because of these two lines removal.
They were removed in this commit: https://github.com/status-im/status-desktop/commit/9a2ffc0fc7e45675a2d38a9d7cb87a8ffebeff5a
I just brought them back.
Popups were without content, just header and footer:
> fix(@desktop/general): broken `StatusModal` popups fixed

- ci/Jenkinsfile.e2e
- ci/Jenkinsfile.macos
To avoid mixing builds on upgraded and unupgraded hosts.
> ci: add missing qt labels for build hosts

- ui/app/AppLayouts/Wallet/views/AdvancedAddAccountView.qml
Fixes adding account modal, which was broken due to incomplete `SelectGeneratedAccount` enum change.
> fix(@desktop/wallet): unable to add account

- ui/app/AppLayouts/Profile/views/KeycardView.qml
Running keycard flows was broken due to changes introduced in commit `81a4d7093276d1e762cc3d3c88bbf58a4373a938`
> fix(@desktop/keycard): broken keycard flows fixed

- src/app/core/fleets/fleet_configuration.nim
- src/app/modules/main/profile_section/io_interface.nim
- src/app/modules/main/profile_section/module.nim
- src/app/modules/main/profile_section/view.nim
- src/app/modules/main/profile_section/waku/controller.nim
- src/app/modules/main/profile_section/waku/io_interface.nim
- src/app/modules/main/profile_section/waku/item.nim
- src/app/modules/main/profile_section/waku/model.nim
- src/app/modules/main/profile_section/waku/module.nim
- src/app/modules/main/profile_section/waku/view.nim
- src/app_service/service/node_configuration/service.nim
- ui/app/AppLayouts/Profile/popups/AddWakuNodeModal.qml
- ui/app/AppLayouts/Profile/popups/AddWakuStoreModal.qml
- ui/app/AppLayouts/Profile/popups/WakuNodesModal.qml
- ui/app/AppLayouts/Profile/popups/WakuStoreModal.qml
- ui/app/AppLayouts/Profile/stores/MessagingStore.qml
- ui/app/AppLayouts/Profile/stores/ProfileSectionStore.qml
- ui/app/AppLayouts/Profile/views/MessagingView.qml
Adds a new option in the settings: Settings > Messaging > Waku Nodes, only active for waku2 fleets. It can be used to see the list of nodes from the current fleet, as well as adding new nodes.
In addition to that, it displays the current active storenode when using waku2
> feat: add custom waku2 nodes

- src/app/core/fleets/fleet_configuration.nim
- src/app/modules/main/profile_section/advanced/controller.nim
- src/app/modules/main/profile_section/advanced/io_interface.nim
- src/app/modules/main/profile_section/advanced/module.nim
- src/app/modules/main/profile_section/advanced/view.nim
- src/app/modules/main/profile_section/io_interface.nim
- src/app/modules/main/profile_section/module.nim
- src/app/modules/main/profile_section/view.nim
- src/app/modules/main/profile_section/waku/controller.nim
- src/app/modules/main/profile_section/waku/io_interface.nim
- src/app/modules/main/profile_section/waku/item.nim
- src/app/modules/main/profile_section/waku/model.nim
- src/app/modules/main/profile_section/waku/module.nim
- src/app/modules/main/profile_section/waku/view.nim
- src/app_service/service/node_configuration/dto/node_config.nim
- src/app_service/service/node_configuration/service.nim
- ui/app/AppLayouts/Chat/stores/RootStore.qml
- ui/app/AppLayouts/Profile/popups/AddWakuNodeModal.qml
- ui/app/AppLayouts/Profile/popups/AddWakuStoreModal.qml
- ui/app/AppLayouts/Profile/popups/WakuNodesModal.qml
- ui/app/AppLayouts/Profile/popups/WakuStoreModal.qml
- ui/app/AppLayouts/Profile/stores/AdvancedStore.qml
- ui/app/AppLayouts/Profile/stores/MessagingStore.qml
- ui/app/AppLayouts/Profile/stores/ProfileSectionStore.qml
- ui/app/AppLayouts/Profile/views/AdvancedView.qml
- ui/app/AppLayouts/Profile/views/MessagingView.qml
Requires
- https://github.com/status-im/status-go/pull/3132
This PR adds a toggle to enable the wakuv2 store functionality. Once enabled, after restarting the client, the following log line should be seen in geth.log, to indicate that the store was enabled successfully.  They shouldn't appear if the protocol is disabled
```
t=2023-01-25T11:13:38-0400 lvl=info msg="Store protocol started"                
t=2023-01-25T11:13:38-0400 lvl=info msg="Subscribing store to broadcaster" 
```
> feat: waku2 store

- storybook/pages/CommunityPermissionsSettingItemEditor.qml
- storybook/pages/CommunityPermissionsSettingsPanelEditor.qml
- storybook/pages/CommunityPermissionsSettingsPanelPage.qml
- storybook/pages/CommunityPermissionsViewPage.qml
- storybook/src/Models/ChannelsModel.qml
- storybook/src/Models/PermissionsModel.qml
- ui/app/AppLayouts/Chat/controls/community/PermissionItem.qml
- ui/app/AppLayouts/Chat/panels/communities/CommunityPermissionsSettingsPanel.qml
- ui/app/AppLayouts/Chat/stores/CommunitiesStore.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityNewPermissionView.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityPermissionsView.qml
Adds tracking of dirty values and storing state for `In` section of community permission.
Closes: #8855 
`CommunityPermissionsSettingsPanel`, `CommunityNewPermissionView`, `CommunityPermissionsView`
[Kazam_screencast_00112.webm](https://user-images.githubusercontent.com/20650004/215483417-611988a5-2236-4794-8ae0-163e4d69e183.webm)
> feat(Community Permissions): Integrate In section with permission creation/editing

- ui/app/AppLayouts/Chat/controls/community/CommunityLogoPicker.qml
- ui/app/AppLayouts/CommunitiesPortal/popups/CreateCommunityPopup.qml
got broken with the recent scroll view fixes
CreateCommunityPopup
Before: 
After:
> fix: unbreak community options layout

- src/app_service/service/message/service.nim
- make the `href` point to `#` to prevent Qt from resolving the empty URL as if it were a relative link
- prepend the at sign (`@`) to the mention tag, just like Discord and `@everyone` else :)
Fixes #9364
Fixes `@everyone` link leading to bogus destination
Chat
Pinned messages popup:
Chat:
> fix: '@everyone' in the pinned messages leads to 'qrc:/app/mainui/1'

- ui/app/AppLayouts/Chat/popups/PinnedMessagesPopup.qml
implement jumping to a message on a simple click
Fixes #9365
About to click on a pinned message:
Message jumped to and highlighted:
> fix: nothing happens after clicking on a pinned message

- ui/app/AppLayouts/Wallet/views/AdvancedAddAccountView.qml
It was a cyclic dependency issue.
Fixes: #9412
> fix(@desktop/wallet): opening add account popup causes the app to crash

- ci/Dockerfile
- ci/Jenkinsfile.imports
- scripts/ubuntu_build_setup.sh
Without the following dependencies:
```
libxcb-shape0 libxcb-randr0 libxcb-icccm4 libxcb-image0
libxcb-keysyms1 libxcb-render-util0 libxcb-render0 libxcb-xinerama0
```
The `libqxcb.so` library is unusable:
```
> ldd -v /opt/qt/5.15.2/gcc_64/plugins/platforms/libqxcb.so
> echo $?
1
>
> LD_TRACE_LOADED_OBJECTS=1 /lib64/ld-linux-x86-64.so.2 /opt/qt/5.15.2/gcc_64/plugins/platforms/libqxcb.so
zsh: segmentation fault (core dumped)  LD_TRACE_LOADED_OBJECTS=1 /lib64/ld-linux-x86-64.so.2
```
Related to:
* https://github.com/status-im/status-desktop/pull/9398
* https://github.com/status-im/infra-ci/issues/70
Also arranged the deps in `ci/Dockerfile` a bit to create some order.
> ci: add missing dependencies for Qts libqxcb.so

- ui/app/AppLayouts/Wallet/views/CollectiblesView.qml
- ui/app/AppLayouts/Wallet/views/collectibles/CollectibleView.qml
- ui/imports/utils/Constants.qml
fixes #9106
Implements collectibles loading screen as show in design  https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=10534%3A121225&t=wYf3EDYJ41PmvLnR-4
Collectibles View under wallet
https://user-images.githubusercontent.com/60327365/215740337-9eb1819d-cbad-4688-b87f-d904f89373c2.mov
> feat(@desktop/wallet): Implement loading state for collectibles

- ui/StatusQ/sandbox/pages/StatusCardPage.qml
- ui/StatusQ/src/StatusQ/Components/StatusCard.qml
- ui/imports/shared/controls/BalanceExceeded.qml
- ui/imports/shared/controls/GasValidator.qml
- ui/imports/shared/popups/SendModal.qml
- ui/imports/shared/stores/TransactionStore.qml
- ui/imports/shared/views/FeesView.qml
- ui/imports/shared/views/NetworkCardsComponent.qml
- ui/imports/shared/views/NetworksSimpleRoutingView.qml
fixes #9107 
#9348 
Implements loading state for Send and. Bridge Modal, however there is a bug on the bridge modal that the routes are not loaded.  Bug raised https://github.com/status-im/status-desktop/issues/9348
Wallet 
https://user-images.githubusercontent.com/60327365/215406859-d3a67d42-5991-4667-8dd0-0bc60f4f0d43.mov
> feat(@desktop/wallet): Implement loading state for Send/Bridge Modal

- ui/app/AppLayouts/Onboarding/views/ConfirmPasswordView.qml
- ui/app/AppLayouts/Profile/popups/ChangePasswordModal.qml
do not break/overwrite the Submit button's `enabled` property binding; the button would stay in the "loading" state
Fixes #9465
Fixes "Change password" popup
ChangePasswordModal
Before submitting:
After submitting:
> fix: changing password with wrong current one fails

- test/ui-test/testSuites/suite_communities/tst_communityMessageFlows/test.feature
> test(community): re-add test for mention non existing user

- test/ui-test/testSuites/suite_wallet/dev/.env
- test/ui-test/testSuites/suite_wallet/dev/docker-compose.yml
- test/ui-test/testSuites/suite_wallet/dev/readme.md
- test/ui-test/testSuites/suite_wallet/tst_wallet/test.feature
Bumps status-go to include the fix for not fetching balance for overridden tokens: [PR #3168](https://github.com/status-im/status-go/pull/3168)
Add documentation on how to run wallet tests locally using ganache
> test(wallet): fix user can manage and observe a watch only account

- ui/app/AppLayouts/Wallet/popups/AddAccountModal.qml
I checked basic flows; there is no side effect.
Wallet - Add Account modal
> fix(wallet): add wallet account - enable advanced section all the time

- src/app/boot/app_controller.nim
- src/app/modules/main/controller.nim
- src/app/modules/main/io_interface.nim
- src/app/modules/main/module.nim
- src/app/modules/main/view.nim
- src/app_service/service/chat/async_tasks.nim
- src/app_service/service/chat/service.nim
- ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
- ui/app/mainui/AppMain.qml
- ui/imports/utils/Constants.qml
Fixes #9340
Makes the getChats call async, so opening the app will be faster. You might see a (placeholder) loader when opening the app until chats and communities appear.
For QAs testing this, make sure the community section, chat section, stickers, activity center, ad-hoc chat thingy all still work as before
> refactor(chat): make getChats async to speed up start time

- ci/Jenkinsfile.e2e
- test/ui-test/README.md
Temporary possible solution to hanging E2E tests.
> ci: revert to using Squish 6.7.2 for Qt 5.14.x

- src/app/modules/main/chat_section/model.nim
- src/app_service/service/chat/service.nim
- ui/StatusQ/src/StatusQ/Components/StatusChatList.qml
- ui/app/AppLayouts/Wallet/views/CollectiblesView.qml
- fix chat category/section height not being (re)set to 0 properly and
hidden
- restore the chat category header highlighting when it contains new
messages/mentions after the new flattened chat model refactoring
Fixes #9493
StatusChatList; chat model
Mobile category collapsed; alleged new msg in desktop:
Desktop channel activated, whole category unmarked:
> fix: unbreak chat categories height and highlight 

- ui/app/AppLayouts/Chat/views/ChatColumnView.qml
- scroll chat to the bottom or last unread msg when the chat is the first time opening
- does not unload opened chat from memory. This allows us to keep the last scroll position and unsend msg during switching between the chats
Fixes: #9303
Scroll chat to the bottom on the first-time chat open
https://user-images.githubusercontent.com/117639195/217565934-ab2adf55-426d-422a-a516-6fb8042c8eb4.mov
> fix(@desktop/chats): Scroll chat to the bottom or last unread msg when chat is first time opening

- storybook/CMakeLists.txt
- ui/StatusQ/StatusQSources.cmake
- ui/StatusQ/sandbox/CMakeLists.txt
- vendor/DOtherSide/lib/CMakeLists.txt
This PR relocates components, that are integral part of `StatusQ` but so far were located under `DOtherSide` directory, to their proper location (`StatusQ` dir):
1. `StatusWindow` 
- fixed duplication in `sandbox` app
3. `QClipboardProxy`
- now `QClipboardProxy` works in `Storybook`
4. `StatusSyntaxHighlighter`
- mock in Storybook no longer need, now Storybook uses the real component
5. `RxValidator`
In general, now there is possibility to define c++ components in StatusQ lib.
Note: The next step is to create full cmake config for StatusQ as a standalone library.
Closes: https://github.com/status-im/status-desktop/issues/9426
`DOtherSide`, `StatusQ`
> chore(StatusQ): move c++ files that are integral part of `StatusQ` from `DOtherSide` to `StatusQ` dir

- storybook/pages/AboutViewPage.qml
- storybook/pages/CommunitiesPortalLayoutPage.qml
- storybook/pages/ProfileDialogViewPage.qml
- test/ui-test/testSuites/suite_settings/tst_userIdentity/test.feature
- ui/StatusQ/src/StatusQ/Controls/Validators/StatusUrlValidator.qml
- ui/StatusQ/src/StatusQ/Controls/Validators/StatusValidator.qml
- ui/StatusQ/src/typesregistration.cpp
- ui/app/AppLayouts/Browser/popups/AddFavoriteModal.qml
- ui/app/AppLayouts/Chat/ChatLayout.qml
- ui/app/AppLayouts/Chat/popups/ChatCommandModal.qml
- ui/app/AppLayouts/Chat/stores/RootStore.qml
- ui/app/AppLayouts/Chat/views/ChatContentView.qml
- ui/app/AppLayouts/Chat/views/ChatHeaderContentView.qml
- ui/app/AppLayouts/Profile/popups/SocialLinksModal.qml
- ui/app/AppLayouts/Profile/stores/AdvancedStore.qml
- ui/app/AppLayouts/Profile/views/NotificationsView.qml
- ui/app/mainui/AppMain.qml
- ui/app/mainui/Popups.qml
- ui/app/mainui/qmldir
- ui/imports/shared/popups/ImageCropWorkflow.qml
- ui/imports/shared/popups/NicknamePopup.qml
- ui/imports/shared/popups/keycard/helpers/KeyPairUnknownItem.qml
- ui/imports/shared/popups/keycard/states/ManageAccounts.qml
- ui/imports/shared/stores/qmldir
- ui/imports/shared/views/ProfileDialogView.qml
- ui/imports/shared/views/chat/MessageContextMenuView.qml
- ui/imports/shared/views/chat/MessageView.qml
- ui/imports/utils/Global.qml
- all remaining global popup components moved into a separate Popups entity
- removed some static objects from the Global singleton (appMain, pinnedMessagesPopup, communityProfilePopup, sounds); rationale: singletons should not contain any state
- fixed support for popups in storybook
- fixed some warnings (most of them broke the popups in one way or the other)
Fixes #9311
Fixes #9499
Consolidates popup handling
Global, AppMain
Profile Popup:
Mock profile in Storybook, including another popup on top:
> chore: consolidate & refactor popup handling

- src/app/modules/main/chat_section/controller.nim
- src/app/modules/main/chat_section/io_interface.nim
- src/app/modules/main/chat_section/model.nim
- src/app/modules/main/chat_section/module.nim
- src/app_service/service/community/service.nim
We were not reordering chats when their category IDs have changed, this resulted in missing updates in community member's UIs
Closes #9329
> fix(community): ensure chats are reordered when cateories have changed

- storybook/PagesModel.qml
- storybook/figma.json
- storybook/pages/CommunityColumnHeaderPanelPage.qml
- storybook/pages/CommunityInfoEditor.qml
- storybook/pages/CommunityPermissionsViewPage.qml
- storybook/pages/JoinCommunityPermissionsEditor.qml
- storybook/pages/JoinCommunityViewPage.qml
- storybook/pages/JoinPermissionsOverlayPanelPage.qml
- storybook/pages/StatusMessagePage.qml
- storybook/src/Models/ModelsData.qml
- storybook/src/Models/PermissionsModel.qml
- storybook/src/Models/qmldir
- ui/StatusQ/src/StatusQ/Components/StatusMessage.qml
- ui/app/AppLayouts/Chat/panels/communities/CommunityColumnHeaderPanel.qml
- ui/app/AppLayouts/Chat/panels/communities/HoldingsListPanel.qml
- ui/app/AppLayouts/Chat/panels/communities/JoinPermissionsOverlayPanel.qml
- ui/app/AppLayouts/Chat/panels/communities/qmldir
- ui/app/AppLayouts/Chat/stores/RootStore.qml
- ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
- ui/app/AppLayouts/Chat/views/communities/JoinCommunityView.qml
- ui/app/AppLayouts/Chat/views/communities/qmldir
Closes https://github.com/status-im/status-desktop/issues/9267
Separated in different commits:
- It creates `CommunityColumnHeaderPanel` component and updates `CommunityColumnView` to use it. Storybook new page added for that.
- It creates join permission overlay panel. Storybook new page added for that.
- It creates `JoinCommunityView` page containing blur custom background layout. It will allow to create different fake data that can be completely fake or we can get some information real from the specific community.  Storybook new page added for that.
- It adds `StatusMessage` component in storybook but just with 2 basic validations.
**NOTE:** `JoinCommunityView` is still not integrated in the app (waiting for backend). This pr only contemplates the UI part.
- Left panel - **Community …
> feat(CommunityPermission): Create main UI page for joining a community that requires permissions

- ui/StatusQ/src/StatusQ/Components/StatusListItem.qml
- ui/imports/shared/controls/TokenBalancePerChainDelegate.qml
- ui/imports/shared/panels/StatusAssetSelector.qml
- ui/imports/shared/popups/SendModal.qml
- ui/imports/shared/views/TokenListView.qml
- fix high-level mixed and broken sizing due to missing a consistent layouting strategy
- fix the first selection. The floating header covered the first entry in the list. I tried to force `StatusListView` to account for the floating header but nothing worked
- moved header outside the StatisListView (a good example of control
want to be doing too many things)
- fixed background colour of the TokenListView
- fixes the impossibility of clicking on chain balance tag
- fixes `StatusListItem`, which is a base on `StatusListItemTag`, from `TokenBalancePerChainDelegate`
- Send Modal
- StatusListItem tags ignore mouse if not scrollable, not an expected behaviour
| Scope | Dark | Light |
| -- | -- | -- |
| Tokens list | ![image](https://user-images.githubusercontent.com/47554641/216395700-9527c53f …
> fix(wallet): some of SendModal's broken windows

- src/app_service/service/node_configuration/service.nim
- ui/imports/shared/panels/StatusAssetSelector.qml
- ui/imports/shared/popups/SendModal.qml
- ui/imports/shared/stores/CurrenciesStore.qml
StatusScrollView was missing a height hint, so even though it was expanding, the parent layout didn't know how much to allow it.
Root cause change: https://github.com/status-im/status-desktop/pull/9469
Wallet, SendModal
> fix(wallet): SendModal layout

- test/ui-test/src/screens/StatusWalletScreen.py
- test/ui-test/testSuites/suite_wallet/tst_wallet/test.feature
- ui/imports/shared/popups/keycard/KeycardPopup.qml
Fixes following the improvements brought with this change: https://github.com/status-im/status-desktop/pull/9469
- The user can manage and observe a watch-only account
- I don't understand how it did work, given that the address was hidden. The `StatusScrollView` changes were probably optimized and made the invisible items not found. 
- The user imports a private key
- The user generates a new account from wallet and deletes it
- The placeholder used to identify seed input might not work for scrolling!?
Wallet
> fix(tests): wallet tests

- ui/app/AppLayouts/Chat/ChatLayout.qml
- ui/app/AppLayouts/Chat/stores/qmldir
- ui/app/mainui/AppMain.qml
... doesn't work in the community section
Extract the `Chat.RootStore` as a toplevel/shared property and pass it down to ChatLayouts, instead of cross referencing it between different components. This was also problematic since the ChatLayouts now live inside a Loader, so it's more appropriate to refer to the `Chat.RootStore` directly, instead of
`personalChatLayoutLoader.item.rootStore`, since the `personalChatLayoutLoader.item` might not be visible (due to it being inside a Loader and a StackLayout) or it might even be a different component (`loadingStateComponent` or `errorStateComponent`).
This also caused similar problems for other components, such as ActivityCenterPopup or StatusStickersPopup.
Fixes #9513
AppMain, ChatLayout
> fix: pasting a user's profile link in the ad-hoc chat search

- storybook/CMakeLists.txt
Replaced `PROJECT_NAME` to `PROJECT_LIB` for MacOS in cmake file.
MacOS storybook
> fix(storybook): Fix cmake file for macos

- ui/StatusQ/src/StatusQ/Components/StatusChatList.qml
The root-cause of this issue is that we use a Listview with height == contentHeight and delegate the scrolling to a ScrollView. The reasoning is that we can attach other items to the bottom of the listview and delegating the scroll to a ScrollView will enable us to scroll the listview+other items attached at the bottom at the same time. 
The fix is to set ListView.interactive to false when the listview cannot be scrolled. Also fixed the listview height so that it can be used as a scrollable listview.
Closing #9460
Community chat list
Contacts chat list
> fix(StatusChatList): Fixing StatusChatList scrolling

- ui/imports/shared/views/ProfileDialogView.qml
rectifies one of the StatusScrollView behavior changes done recently
Fixes #9519
> fix: profile preview doesn't show entire profile

- ci/Jenkinsfile.e2e
Changed UNSTABLE state to be considered as a failure since UNSTABLE state means some tests have failed during the retries but also in the last retry so, it contemplates real failures too.
jenkins file for e2e tests
> ci(e2e): Changed UNSTABLE state to be considered as a failure

- src/app/modules/main/wallet_section/accounts/controller.nim
- src/app/modules/main/wallet_section/accounts/io_interface.nim
- src/app/modules/main/wallet_section/accounts/module.nim
- src/app/modules/main/wallet_section/accounts/view.nim
- src/app/modules/shared_modules/keycard_popup/models/key_pair_account_model.nim
- src/app/modules/shared_modules/keycard_popup/models/key_pair_item.nim
- src/app_service/service/wallet_account/async_tasks.nim
- src/app_service/service/wallet_account/service.nim
- src/backend/accounts.nim
- ui/app/AppLayouts/Wallet/panels/DerivationPathsPanel.qml
- ui/app/AppLayouts/Wallet/panels/DerivedAddressesPanel.qml
- ui/app/AppLayouts/Wallet/popups/AddAccountModal.qml
- ui/app/AppLayouts/Wallet/stores/RootStore.qml
- ui/app/AppLayouts/Wallet/views/AdvancedAddAccountView.qml
- ui/imports/shared/popups/keycard/helpers/KeyPairItem.qml
- ui/imports/shared/popups/keycard/helpers/KeyPairList.qml
Check box added to warn user if they want to add a path out of the default Status' wallet derivation path. In case they do that, they are not able to migrate such keypair to a Keycard.
- https://github.com/status-im/status-go/pull/3149
Once we get the final design, we will updated add account modal accordingly.
Closes: #9118
> feat(@desktop/wallet): adding wallet derivation path updates

- ui/app/AppLayouts/Profile/views/EnsDetailsView.qml
`int` is not enough for a timestamp
Fixes #9381
Fixes formatted ENS release date
EnsDetailsView
> fix(ENS): For an ENS name the wrong release date is shown

- src/app/modules/main/chat_section/chat_content/messages/controller.nim
- src/app/modules/main/chat_section/chat_content/messages/io_interface.nim
- src/app/modules/main/chat_section/chat_content/messages/module.nim
- src/app/modules/main/chat_section/chat_content/messages/view.nim
- src/app_service/service/message/async_tasks.nim
- src/app_service/service/message/service.nim
- ui/app/AppLayouts/Chat/stores/RootStore.qml
- ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
- ui/imports/shared/controls/chat/MessageBorder.qml
- ui/imports/shared/status/StatusChatImageLoader.qml
- ui/imports/shared/views/chat/LinksMessageView.qml
- ui/imports/shared/views/chat/MessageView.qml
LinksMessageView component will receive the urls from nim as string and it will only forward the string to getLinkPreviewData slot implemented in nim together with some settings (supported img extensions and unfurling preferences).
On nim side the urls will be parsed and validated using the settings received from qml. Images are now validated before sending them to the UI using the HEAD request.
LinkMessageView
> fix(LinksMessageView): Refactor LinksMessageView to remove business logic from qml

- ui/StatusQ/src/StatusQ/Components/StatusAddressPanel.qml
- ui/imports/shared/popups/SendModal.qml
- ui/imports/shared/views/NetworkCardsComponent.qml
- ui/imports/shared/views/NetworkSelector.qml
- ui/imports/shared/views/NetworksAdvancedCustomRoutingView.qml
Changes:
- Add "WILL RECEIVE" after identity
- Allow ENS name if resolved
- Elide the middle if doesn't fit (the main is displayed above and can be checked)
Also, fix `autHideCopyIcon` of `StatusAddressPanel` property  working independently behaviour of `showCopy` property
- Wallet Send Modal
- Copy address changes behaviour when `showCopy` is `false`, and `autHideCopyIcon` is `true`. I've checked and none of our usages has this corner case 
Considerations
- Tried to fix `NetworksSimpleRoutingView` scrolling is blocked found issue but it seems complicated and will take some time, so I gave up.
- The new design is partially described in the corresponding ticket
| Dark | Light |
| -- | -- |
| ![image](https://user-images.githubusercontent.com/47554641/216108763-82510835-c6af-41e5-ab9a-d6d15f …
> fix(wallet): improve send modal advanced recipient text

- ui/imports/shared/views/chat/MessageView.qml
Fixing regression from LinksMessagePreview refactoring where if the message contains text + image url, the message will be hidden.
Issue found here: https://github.com/status-im/status-mobile/issues/15065
MessageView
> fix(MessageView): Show message when there is one img preview and extra text

- ui/imports/shared/status/StatusChatInput.qml
Closes #8478
Closes #8750
status chat input prevents adding emoji when links are pasted 
status chat input
https://user-images.githubusercontent.com/31625338/219080580-327eac9c-5fd4-4f20-a877-0a5cb4265701.mov
> fix(statusChatInput): do not replace text with emojis on links

- storybook/src/Models/AssetsModel.qml
- storybook/src/Models/CollectiblesModel.qml
- ui/app/AppLayouts/Chat/controls/community/ExtendedDropdownContent.qml
- ui/app/AppLayouts/Chat/controls/community/ListDropdownContent.qml
- ui/app/AppLayouts/Chat/controls/community/TokenCategories.qml
- ui/app/AppLayouts/Chat/controls/community/qmldir
- ui/app/AppLayouts/Chat/stores/CommunitiesStore.qml
Currently community permissions UI uses mocked store. Tokens models (assets, collectibles) had "category" name containing string presented in UI. It's changed to provide from backend only enum representing some predefined categories. UI is responsible for displaying proper textual representation to the user.
Closes: #9556
`Community Permissions` components: `ExtendedDropdownContent`, `ListDropdownContent`
UI hasn't changed.
> chore(CommunityPermissions): Use enum for token category, keep string labels in UI only

- src/app/global/utils.nim
- ui/imports/shared/status/StatusChatImageSizeValidator.qml
as we're dealing with local file URLs only here, we don't want to turn the plus signs (`+`) into spaces (leads to failing to open the file, emits an exception, crashes later on in our JS code)
Fixes #9538
Fixes a crash trying to open/upload an image
globalUtils
Opening an image with a `+` in its filename:
Image uploaded with no crash:
> fix: App crashes on uploading an image containing "+" in its name

- ui/imports/shared/popups/keycard/KeycardPopup.qml
- ui/imports/shared/popups/keycard/KeycardPopupDetails.qml
During my work on other issue, I noticed that some buttons were enabled for some states (keycard inserted, reading...) when they should not be. Logic updated.
> fix(@desktop/keycard): update logic of enabling action buttons during the flow

- ui/StatusQ/src/StatusQ/Controls/StatusLinkText.qml
- ui/StatusQ/src/StatusQ/Controls/qmldir
- ui/app/mainui/activitycenter/controls/CommunityBadge.qml
- ui/app/mainui/activitycenter/views/ActivityNotificationBase.qml
- ui/app/mainui/activitycenter/views/ActivityNotificationCommunityKicked.qml
- ui/app/mainui/activitycenter/views/ActivityNotificationCommunityMembershipRequest.qml
- ui/app/mainui/activitycenter/views/ActivityNotificationCommunityRequest.qml
- ui/app/mainui/activitycenter/views/ActivityNotificationMessage.qml
Close #9402
Make CommunityBadge respect long community and channel names
ActivityCenter
> fix(ActivityCenter): Fix CommunityBadge eliding

- src/app/modules/main/module.nim
- src/app/modules/main/profile_section/keycard/module.nim
- src/app/modules/main/profile_section/module.nim
- src/app/modules/main/wallet_section/accounts/module.nim
- src/app/modules/shared_modules/keycard_popup/controller.nim
- src/app/modules/shared_modules/keycard_popup/io_interface.nim
- src/app/modules/shared_modules/keycard_popup/models/key_pair_account_item.nim
- src/app/modules/shared_modules/keycard_popup/models/key_pair_account_model.nim
- src/app/modules/shared_modules/keycard_popup/models/key_pair_item.nim
- src/app/modules/shared_modules/keycard_popup/module.nim
- src/app/modules/startup/module.nim
- src/app_service/service/wallet_account/async_tasks.nim
- src/app_service/service/wallet_account/service.nim
- ui/app/AppLayouts/Chat/stores/StickersStore.qml
- ui/app/AppLayouts/Profile/stores/ContactsStore.qml
- ui/app/AppLayouts/Profile/stores/EnsUsernamesStore.qml
- ui/app/AppLayouts/Profile/stores/ProfileSectionStore.qml
- ui/app/AppLayouts/Profile/stores/ProfileStore.qml
- ui/app/AppLayouts/Profile/stores/WalletStore.qml
- ui/imports/shared/popups/keycard/helpers/KeyPairUnknownItem.qml
- ui/imports/shared/stores/CurrenciesStore.qml
- ui/imports/shared/stores/RootStore.qml
- ui/imports/utils/Global.qml
- ui/main.qml
There are 2 logically different contexts where we can run factory reset flow:
- before user logs in
- after user logs in
For the first case, because of the current limitations (fixing this entails many other things) cause `getWalletToken` call is a json rpc endpoint on the status-go side, therefore it is unavailable before user logs in, we display always 0$ for balance. 
Maybe we can check with the design team and remove that info in that context or invest more time and try to make `getWalletToken` call available even user is not logged in. @alaibe what do you think?
For the second case loading indicator will be shown till the balance is fetched and calculated.
The second commit, cleans the log from warnings caused by undefined context props mostly.
Fixes: #9418
> fix(@desktop/keycard): Keycard -> Factory reset: $NaN amount is shown in factory reset flow when account has no funds

- src/app/global/app_sections_config.nim
- src/app/modules/main/controller.nim
- src/app/modules/main/io_interface.nim
- src/app/modules/main/module.nim
- src/app/modules/shared_models/section_item.nim
Fixes #9508
The issue was caused by some calls that try to update the activeSection's item, but during chat loading, the activeSection had the possibility of being empty, thus causing a crash. The fix here is to create a LoadingItem and set it as active during the time the chats load (if the last active section was a community or chat). Then, the updates go to that Item and do nothing, but that's normal.
> fix(main): create loading item for activeSection on start

- src/app/modules/main/activity_center/controller.nim
- src/app/modules/main/activity_center/io_interface.nim
- src/app/modules/main/activity_center/module.nim
- src/app/modules/main/activity_center/view.nim
- src/app_service/service/activity_center/service.nim
- src/app_service/service/community/service.nim
- src/app_service/service/contacts/service.nim
- src/backend/backend.nim
- ui/StatusQ/sandbox/controls/Layout.qml
- ui/StatusQ/sandbox/demoapp/CreateChatView.qml
- ui/StatusQ/sandbox/demoapp/StatusAppChatView.qml
- ui/StatusQ/src/StatusQ/Components/StatusToolBar.qml
- ui/StatusQ/src/StatusQ/Controls/StatusActivityCenterButton.qml
- ui/StatusQ/src/StatusQ/Layout/StatusSectionLayout.qml
- ui/app/AppLayouts/Browser/BrowserLayout.qml
- ui/app/AppLayouts/Chat/views/ChatView.qml
- ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
- ui/app/AppLayouts/Chat/views/CreateChatView.qml
- ui/app/AppLayouts/Node/NodeLayout.qml
- ui/app/AppLayouts/Profile/ProfileLayout.qml
- ui/app/AppLayouts/Wallet/WalletLayout.qml
- ui/app/mainui/activitycenter/popups/ActivityCenterPopup.qml
- ui/app/mainui/activitycenter/stores/ActivityCenterStore.qml
Close #9347
Depends https://github.com/status-im/status-go/pull/3148
Add indication for visited/unvisited ActivityCenter state
ActivityCenter
https://user-images.githubusercontent.com/2522130/217846552-615831db-6e11-43ea-8b6c-b90c5b8c62c8.mov
> feat(ActivityCenter): Add indication for visited/unvisited AC state

- storybook/pages/CommunityIntroDialogPage.qml
- ui/StatusQ/src/StatusQ/Controls/StatusBaseButton.qml
- ui/imports/shared/popups/CommunityIntroDialog.qml
- ui/imports/shared/popups/ContactVerificationRequestPopup.qml
- ui/imports/shared/popups/OutgoingContactVerificationRequestPopup.qml
- ui/imports/shared/views/ProfileDialogView.qml
- ui/imports/shared/views/chat/MessageContextMenuView.qml
- ui/imports/shared/views/chat/SimplifiedMessageView.qml
- port to StatusDialog
- fix binding loops
- fix `timestamp` to be a double rather than a `string`
Fixes #9563
ID verification popups
Outgoing:
Incoming:
Incoming with response:
Community intro:
> fix: contact ID verification and community intro sizing issues

- ui/app/AppLayouts/Wallet/views/AssetsDetailView.qml
- ui/imports/shared/controls/InformationTag.qml
- ui/imports/shared/controls/TokenDelegate.qml
- ui/imports/shared/stores/CurrenciesStore.qml
(in separate commits)
- fix formatting floating point numbers (asset percentage/changes)
- CurrenciesStore fixes
- Information tag fixes (text overflowing)
Wallet/Asset view
Asset overview (percentage change using correct decimal separator):
Asset detail (percentage changes using correct decimal separator, correct info tag text, not overflowing):
> fix(i18n/wallet): properly format floating point numbers

- storybook/pages/CommunityPermissionsViewPage.qml
- storybook/src/Models/AssetsModel.qml
- storybook/src/Models/CollectiblesModel.qml
- ui/StatusQ/StatusQSources.cmake
- ui/StatusQ/include/StatusQ/modelutilsinternal.h
- ui/StatusQ/sanity_checker/CMakeLists.txt
- ui/StatusQ/sanity_checker/main.cpp
- ui/StatusQ/src/StatusQ/Core/Utils/ModelUtils.qml
- ui/StatusQ/src/modelutilsinternal.cpp
- ui/StatusQ/src/typesregistration.cpp
- ui/app/AppLayouts/Chat/controls/community/ListDropdownContent.qml
- ui/app/AppLayouts/Chat/controls/community/ThumbnailsDropdownContent.qml
- ui/app/AppLayouts/Chat/helpers/CommunityPermissionsHelpers.qml
- ui/app/AppLayouts/Chat/panels/communities/CommunityPermissionsSettingsPanel.qml
- ui/app/AppLayouts/Chat/panels/communities/HoldingsListPanel.qml
- ui/app/AppLayouts/Chat/views/communities/HoldingsSelectionModel.qml
- vendor/DOtherSide/lib/src/DOtherSide.cpp
Generic `QAbstractItemModel` don't have `get` method to access data by role names. It's problematic in some cases when direct lookup is needed. This PR resolves that problem by providing utility methods allowing handling both `ListModel` and `QAbstractItemModel` in the same way transparently.
Closes: https://github.com/status-im/status-desktop/issues/9562
`StatusQ`
> feat(StatusQ): Add cpp model utils to allow handling ListModel and generic QAbstractItemModel uniformly

- storybook/pages/CommunityNewPermissionViewPage.qml
- storybook/pages/CommunityPermissionsViewPage.qml
- ui/app/AppLayouts/Chat/panels/communities/CommunityPermissionsSettingsPanel.qml
- ui/app/AppLayouts/Chat/stores/CommunitiesStore.qml
So far store had methods for update/remove taking index of the permission in the model. Now those ops are based on unique identifier representing permission, independent from position in the input model.
Closes: #9577
`CommunityPermissionsSettingsPanel`
> feat(CommunityPermissions): Handle update/remove by permission's key instead of index

- ui/StatusQ/sandbox/controls/Controls.qml
- ui/StatusQ/src/StatusQ/Components/StatusChatInfoToolBar.qml
- ui/StatusQ/src/StatusQ/Components/StatusToolBar.qml
- ui/StatusQ/src/StatusQ/Controls/StatusChatInfoButton.qml
- ui/StatusQ/src/StatusQ/Controls/StatusLinkText.qml
- ui/StatusQ/src/StatusQ/Controls/StatusToolTip.qml
- ui/app/AppLayouts/Chat/views/ChatHeaderContentView.qml
The chat title/subtitle no longer bleeds into the action buttons
- handle long texts in chat description, elide them and show the whole
text in a tooltip
- minor UI fixes in ChatHeaderContentView and StatusToolBar
- adjust Sandbox' Controls page
Fixes #9583
Fixes #9056
StatusChatInfoButton, StatusToolBar, ChatHeaderContentView
[Záznam obrazovky z 2023-02-21 12-22-13.webm](https://user-images.githubusercontent.com/5377645/220332034-9080541e-daf8-4cb0-9506-6b7fd2d482e5.webm)
> fix: truncation of channel description and pinned message text

- ui/StatusQ/src/StatusQ/Components/StatusCard.qml
- ui/imports/shared/stores/TransactionStore.qml
- ui/imports/shared/views/NetworkCardsComponent.qml
fixes #9456
Adds background to the statuscard so that the highlight doesnt look white in dark mode
Fixes issue of preferredChains not updated after editing them
Wallet, SendModal
https://user-images.githubusercontent.com/60327365/217328179-639aff1f-d713-4971-a44f-a234e096ada1.mov
https://user-images.githubusercontent.com/60327365/217328224-26041ebd-9c75-4daf-8983-a1fba4ace5d4.mov
> fix(@desktop/wallet): Preferred network doesn't reflect in advanced view

- ui/StatusQ/src/StatusQ/Components/private/statusMessage/StatusTimeStampLabel.qml
- ui/StatusQ/src/StatusQ/Core/LocaleUtils.qml
- implement LocaleUtils.formatRelativeTimestamp() that does all the heavy lifting
- use it in StatusTimeStampLabel -> propagates to all message timestamps (chat, activity center, settings, etc)
Closes #9397
Implements relative timestamps based on proximity
StatusTimeStampLabel
Today == Tuesday, 21st February
Today/Yesterday:
Earlier this week (<7 days); last Wednesday -> relative, day before that -> absolute:
Year turnover (current one displayed w/o year number):
> feat: relative or absolute timestamping depending on time/date proximity

- ui/StatusQ/sandbox/controls/Controls.qml
- ui/StatusQ/sandbox/pages/StatusAccountSelectorPage.qml
- ui/StatusQ/sandbox/pages/StatusAddressPage.qml
- ui/StatusQ/sandbox/pages/StatusCardPage.qml
- ui/StatusQ/sandbox/pages/StatusChartPanelPage.qml
- ui/StatusQ/sandbox/pages/StatusChatCommandButtonPage.qml
- ui/StatusQ/sandbox/pages/StatusColorSelectorPage.qml
- ui/StatusQ/sandbox/pages/StatusColorSpacePage.qml
- ui/StatusQ/sandbox/pages/StatusComboBoxPage.qml
- ui/StatusQ/sandbox/pages/StatusCommunityTagsPage.qml
- ui/StatusQ/sandbox/pages/StatusInputPage.qml
- ui/StatusQ/sandbox/pages/StatusMacNotificationPage.qml
- ui/StatusQ/sandbox/pages/StatusSelectPage.qml
- ui/StatusQ/sandbox/pages/StatusTabBarButtonPage.qml
- ui/StatusQ/sandbox/pages/StatusTabBarIconButtonPage.qml
- ui/StatusQ/sandbox/pages/StatusWalletColorButtonPage.qml
- ui/StatusQ/sandbox/pages/StatusWalletColorSelectPage.qml
Closes: #9594
Some sandbox pages had an unused import `import Sandbox`. That namespace had been removed at some point causing errors on pages where it was used.
The second part of the ticker (build script) has been covered here: https://github.com/status-im/status-desktop/pull/9595
`StatusQ`'s pages
> fix(StatusQ): Removed nonexisting/unused imports from Sandbox pages

- ui/StatusQ/src/StatusQ/Components/StatusItemSelector.qml
- ui/StatusQ/src/StatusQ/Core/Utils/ModelChangeTracker.qml
- ui/StatusQ/src/StatusQ/Core/Utils/ModelUtils.qml
- ui/app/AppLayouts/Chat/controls/community/ListDropdownContent.qml
- ui/app/AppLayouts/Chat/helpers/CommunityPermissionsHelpers.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityNewPermissionView.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityPermissionsView.qml
- Fix `ModelChangeTracker` and `ModelUtils` to handle properly - assigning `undefined` caused many warning from Connection component
- Use only key/amount to compare holdings when tracking duplicates - only those values are significant and identify given holding
- clean warnings by preventing assigning when some roles doesn't exist - backend may skip some roles, especially in early phases of development, ui should handle such cases seamlessly
Closes: #9608
CommunityPermission's components, StatusQ utils - `ModelChangeTracker`, `ModelUtils`
[Kazam_screencast_00120.webm](https://user-images.githubusercontent.com/20650004/220450923-520cf163-35ab-4cfa-b03f-7b93032b784a.webm)
> [Community permissions]: Align UI to work with real backend, remove warnings

- ui/app/AppLayouts/Chat/panels/communities/CommunityPermissionsSettingsPanel.qml
- ui/app/AppLayouts/Chat/stores/CommunitiesStore.qml
So far `CommunitiesStore`'s methods like `createPermission` were assuming that e.g. holdings are provided as a model. For generality it's changed to take just plain JS array instead. Side-effect benefit is the fact that real impl and mock won't have to repeat the same conversion.
Closes: #9611
`CommunityPermissionsSettingsPanel`, `CommunitiesStore`
> fix(CommunityPermissions): Adjust store API to not take models as parameters, move conversion to the caller

- storybook/pages/CommunityPermissionsSettingsPanelPage.qml
- storybook/pages/CommunityPermissionsViewPage.qml
- storybook/pages/CommunityTokenPermissionsPopupPage.qml
- storybook/pages/HoldingsDropdownPage.qml
- storybook/stubs/AppLayouts/Chat/stores/CommunitiesStore.qml
- storybook/stubs/AppLayouts/Chat/stores/RootStore.qml
- storybook/stubs/AppLayouts/Chat/stores/StickersStore.qml
- storybook/stubs/AppLayouts/Chat/stores/qmldir
- ui/app/AppLayouts/Chat/ChatLayout.qml
- ui/app/AppLayouts/Chat/controls/community/ExtendedDropdownContent.qml
- ui/app/AppLayouts/Chat/controls/community/HoldingsDropdown.qml
- ui/app/AppLayouts/Chat/panels/communities/CommunityPermissionsSettingsPanel.qml
- ui/app/AppLayouts/Chat/popups/community/CommunityTokenPermissionsPopup.qml
- ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityNewPermissionView.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityPermissionsView.qml
- ui/imports/shared/stores/CurrenciesStore.qml
So far single implementation of `CommunitiesStore`, serving mocked data was used in both the app and storybook. In order to integrate the backend, the mock version is separated and moved to storybook. The app still serves mocks but replacing by integrating with backend won't affect storybook's pages.
Moreover:
- usages of `CommunitiesStore` are refactored to be strongly typed
- `CommunityTokenPermissionsPopup` and corresponding storybook's page fixed (displaying tokens)
Closes: #9612
Community Permission components
> chore(CommunityPermissions): Dissect real and mocked CommunitiesStore, adapt Storybook's pages

- src/app/modules/main/wallet_section/transactions/controller.nim
- src/app/modules/main/wallet_section/transactions/io_interface.nim
- src/app/modules/main/wallet_section/transactions/item.nim
- src/app/modules/main/wallet_section/transactions/model.nim
- src/app/modules/main/wallet_section/transactions/module.nim
- src/app/modules/main/wallet_section/transactions/view.nim
- src/app_service/service/transaction/async_tasks.nim
- src/app_service/service/transaction/service.nim
- ui/StatusQ/src/StatusQ/Components/StatusListItem.qml
- ui/app/AppLayouts/Wallet/views/AssetsDetailView.qml
- ui/imports/shared/controls/InformationTag.qml
- ui/imports/shared/controls/TransactionDelegate.qml
- ui/imports/shared/views/HistoryView.qml
… view and replace with automatic loading when the user scrolls down using a skeleton loading state
fixes #8987
raised a follow up for a glitchy behaviour seen https://github.com/status-im/status-desktop/issues/9320
Implements loading state + load more behavior for the transaction view as defined in design https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=10401%3A122250&t=k58Oy9eh3MsUsFer-4
When the transactions are loading we should see loading item and then on scrolling if the user drags the list, it should fetch more transaction
Wallet
https://user-images.githubusercontent.com/60327365/214768818-ed …
> fix(@desktop/wallet): Remove the 'Load More' button from the Activity view

- .gitmodules
- src/app/core/tasks/threadpool.nim
- src/app_service/service/stickers/async_tasks.nim
- src/app_service/service/stickers/service.nim
Reduce memory usage. The previous implementation was using 400+ mb of memory for a threadpool with 16 threads.
The nim heap was used in 95% by the following data:
[Heap] seq[SelectorKey[asyncloop.SelectorData]]: #18; bytes: 460063296
This is because of the nim_task_runner implementation that will create a new thread dispatcher. [Code here](https://github.com/status-im/nim-task-runner/blob/a87f3f85be052fb3332358f95079a059cf1daf15/task_runner/achannels.nim#L77)
Each thread dispatcher will create an array of SelectorData having the size of system `maxfilesperproc` (on my system was 245760). A good way to test it on master is to run `sudo sysctl kern.maxfilesperproc=1000`, restart the app and observe the memory usage.
This is a proposal for a new threadpool using nim …
> fix(NimThreadpool): Implement lightweight threadpool

- storybook/pages/DidYouKnowSplashScreenPage.qml
- ui/imports/shared/panels/DidYouKnowSplashScreen.qml
- ui/imports/shared/panels/private/DidYouKnowMessages.qml
Changes based on this discussion: https://github.com/status-im/status-desktop/pull/9551#issuecomment-1434581374
1. Update messages - see [Notion page](https://www.notion.so/Loading-screen-messaging-be82db41dac746f9b203ac82eb6be0b3)
2. Increase messages shuffle time to 7 sec
3. Add fade in animation to DidYouKnow messages
4. Update storybook page
5. Use single line text whenever possible (with our current min app size it will always be on a single line)
Splash screen
https://user-images.githubusercontent.com/47811206/220327182-61074760-5c43-46d8-a132-a8eb040a4172.mov
> fix(DidYouKnowSplashScreen): Implement UI changes

- src/app/modules/main/communities/controller.nim
- src/app/modules/main/communities/io_interface.nim
- src/app/modules/main/communities/module.nim
- src/app/modules/main/communities/view.nim
- src/app/modules/main/module.nim
- src/app_service/service/community/async_tasks.nim
- src/app_service/service/community/dto/community.nim
- src/app_service/service/community/service.nim
- ui/app/AppLayouts/CommunitiesPortal/stores/CommunitiesStore.qml
This makes loading of curated communities asynchronous as the task can take quite a while.
Closes #9341
> refactor(communities): load curated communities asynchronously

- src/app/boot/app_controller.nim
- src/app/core/signals/remote_signals/messages.nim
- src/app/modules/main/profile_section/keycard/controller.nim
- src/app/modules/main/profile_section/keycard/io_interface.nim
- src/app/modules/main/profile_section/keycard/module.nim
- src/app/modules/main/wallet_section/accounts/module.nim
- src/app/modules/shared_modules/keycard_popup/controller.nim
- src/app/modules/shared_modules/keycard_popup/internal/renaming_keycard_state.nim
- src/app/modules/shared_modules/keycard_popup/internal/wrong_seed_phrase_state.nim
- src/app/modules/shared_modules/keycard_popup/models/key_pair_account_model.nim
- src/app/modules/shared_modules/keycard_popup/module.nim
- src/app/modules/startup/module.nim
- src/app_service/common/utils.nim
- src/app_service/service/wallet_account/async_tasks.nim
- src/app_service/service/wallet_account/key_pair_dto.nim
- src/app_service/service/wallet_account/service.nim
- src/backend/backend.nim
- ui/app/AppLayouts/Profile/views/KeycardView.qml
- ui/app/AppLayouts/Profile/views/keycard/DetailsView.qml
This commit resolves a crash happened due to connection to `SIGNAL_WALLET_ACCOUNT_TOKENS_REBUILT` when keycard sync flow was run in the background.
Also updated the keycard synchronization process with the current state of the application and is the first step of many which leads towards completion of entire syncing feature.
The first commit syncs a Keycard with the current app state, second commit introduces syncing keycard details among devices.
- https://github.com/status-im/status-go/pull/3211
Here is the demo how keycard syncing among devices work:
https://user-images.githubusercontent.com/86303051/221022963-e9154baf-e694-49e5-a9c5-aea5fe8cdda3.mov
> chore(keycard): sync keycard with the current app state updated

- src/app/modules/main/chat_section/chat_content/messages/module.nim
prevent spam of "requested community doesn't exists"
The spam was caused by calling `getCommunityById` with empty id.
> fix: prevent spam of "requested community doesn't exists"

- src/app/core/notifications/notifications_manager.nim
Send OS notifications if the app is not focused
Closes: #9631
OS notifications
> fix(@desktop/notifications): send OS notifications if the app is not focused

- ui/imports/shared/views/chat/InvitationBubbleView.qml
- ui/imports/shared/views/chat/LinksMessageView.qml
Closing #9653
`visible: invitationData && !invitationData.fetching` This condition is failing when invitationData is null or undefined.
Also fixed warnings in [InvitationBubbleView.qml](https://github.com/status-im/status-desktop/compare/fix/issue-9653?expand=1#diff-08a51598e69bdd9997718cb97efe31d0fd4bd5f6132ddb88720dd402e7b21ad2) when the community data cannot be found by adding default values.
Unfurling community urls
> fix(UnfurlingUrls): Fix community invitation when community cannot be fetched (or in progress)

- src/app/modules/main/activity_center/controller.nim
- src/app/modules/main/activity_center/io_interface.nim
- src/app/modules/main/activity_center/module.nim
- src/app/modules/main/activity_center/view.nim
- src/app_service/service/activity_center/async_tasks.nim
- src/app_service/service/activity_center/dto/notification.nim
- src/app_service/service/activity_center/service.nim
- src/backend/backend.nim
- ui/app/mainui/activitycenter/panels/ActivityCenterPopupTopBarPanel.qml
- ui/app/mainui/activitycenter/popups/ActivityCenterPopup.qml
- ui/app/mainui/activitycenter/stores/ActivityCenterStore.qml
- ui/app/mainui/activitycenter/views/ActivityNotificationCommunityMembershipRequest.qml
- ui/app/mainui/activitycenter/views/ActivityNotificationCommunityRequest.qml
- ui/imports/utils/Constants.qml
Close #8510
Depends https://github.com/status-im/status-go/pull/3206
What should be fixed by this PR:
> feat(ActivityCenter): Remove UI-side AC notifications filtering & sorting

- ui/app/mainui/AppMain.qml
- ui/app/mainui/panels/DropAreaPanel.qml
Fixes #9630
- Drag/drop images are available from all chat types (1:1 , group chats and community channels).
- In case of community settings views, it is disabled.
Chats / Channels
Community Settings Views
https://user-images.githubusercontent.com/97019400/221190842-53f12741-098c-43dc-83bc-b7bbec6a9f3b.mov
> fix(Chats): Drag/drop image files is only available for community channels

- src/app/boot/app_controller.nim
- src/app/modules/startup/module.nim
1. Bump nimqml version to include fixes for qmodelindex, char* and qabstractlistmodel memory leaks
2. Fixing app crash after qabstractlistmodel leak is fixed in nimqml. The `startupModule` is exposed in qml and we need to reset the `rootContextProperty` after delete. Also, the `self.delegate.finishAppLoading` called from `startup/module.nim` is triggering the module delete on the same call stack. This is dangerous and this PR is fixing the symptoms by moving `self.delegate.finishAppLoading()` at the end of the method.
Part of #9558
> fix(QAbstractItemsModel): Fixing nim memory leaks

- src/app/modules/main/chat_section/io_interface.nim
- src/app/modules/main/chat_section/item.nim
- src/app/modules/main/chat_section/model.nim
- src/app/modules/main/chat_section/module.nim
- src/app/modules/main/chat_section/view.nim
- src/app_service/service/community/service.nim
- ui/StatusQ/src/StatusQ/Components/StatusChatList.qml
- ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
Fixes #9494
Simplifies the chat model by putting categories inside the model as an Item. We use the `type` to differentiate chats and categories, that way we can choose the right delegate.
To test: if everything with regards to chats, channels and categories work as expected
> refactor(chat-model): simplify chat model and put category as an Item

- src/app/modules/main/chat_section/controller.nim
- src/app/modules/main/chat_section/module.nim
Fixes #9236 and #9438
Makes it so we activate only the active chat in the active section.
Before, one chat of each community would activate and trigger the message fetch, db get and `firstUnseenMessage` calls.
> refactor: make sure we only set active the active chat of active section

- src/app/boot/app_controller.nim
- src/app/modules/main/profile_section/devices/controller.nim
- src/app/modules/main/profile_section/devices/io_interface.nim
- src/app/modules/main/profile_section/devices/model.nim
- src/app/modules/main/profile_section/devices/module.nim
- src/app/modules/main/profile_section/devices/view.nim
- src/app_service/service/devices/async_tasks.nim
- src/app_service/service/devices/service.nim
- ui/app/AppLayouts/Profile/stores/DevicesStore.qml
- ui/app/AppLayouts/Profile/views/DevicesView.qml
Fixes #9439
#9525 Makes the getInstallations call load only when we enter the device screen and makes it async.
I added a very basic loading and error text as well.
The DeviceView was very old too, so there were stuff that I cleaned up, but there is more to clean there, that should be done later.
> refactor(devices): make loading devices lazy load and async

- ui/StatusQ/src/StatusQ/Components/StatusChatList.qml
- add an extra space for the item height to fix spacing; can't do this using regular `spacing` due to height of collapsed categories
- remove dead code
Fixes #9657
StatusChatList
> fix(StatusChatList): Missing space between channels in StatusChatList

- scripts/clean-git.sh
Currently the `nimbus-build-system` exists twice in each checked out `status-desktop` reposity, and each contains the `Nim-csources-v1` submodule, which weights close to 900MB each:
https://github.com/nim-lang/csources_v1
Because of this each `status-destop` clone takes up 4 GB of disk space after the cleanup has run, which is not okay.
This might slow down CI job startup, but the disk space we reclaim is worth it.
> ci: remove submodule vendor folders to save space

- storybook/CMakeLists.txt
- storybook/README.md
So far README.md had only description for WASM builds what was misleading, suggesting that's the only proper way of building Storybook.
Additionally, `README.md` added to `storybook/CMakeLists.txt` in order to show readme file in QtCreator.
Closes: #9679
Storybook's readme
> chore(Storybook): Update Readme to point CMakeLists.txt as the main way to build instead of WebAssembly

- ui/imports/shared/status/StatusChatInput.qml
Closes #3291
StatusChatInput): fixed invisible text when pasting text with emoji
https://user-images.githubusercontent.com/31625338/220933363-4e8129a3-37a1-4e88-97c9-ad8a56b1e87a.mov
> fix(StatusChatInput): fixed invisible text when pasting text with emoji

- .gitmodules
- src/app/core/main.nim
As of #9596, task-runner is no longer used.
Due to how the build system works, task-runner was providing nim-stew, nim-bearssl and nim-chronos to the project, even though these are also top-level dependencies - effectively this means there were multiple versions of these libraries in the source tree and it is not entirely intuitive which is actually used - adding to the confusion, the submodule was pinning different versions.
This PR removes task-runner and resets the other dependencies to the versions in task-runner thus minimising collateral changes.
A duplicate copy of bearssl is also removed.
> remove task-runner dependency

- src/app/modules/main/browser_section/bookmark/io_interface.nim
- src/app/modules/main/browser_section/bookmark/module.nim
- src/app/modules/main/browser_section/io_interface.nim
- src/app/modules/main/browser_section/module.nim
- src/app/modules/main/communities/module.nim
- src/app/modules/main/module.nim
- src/app_service/service/bookmarks/service.nim
- src/app_service/service/community/async_tasks.nim
- src/app_service/service/community/service.nim
Fixes #9440
Lazy loads browser bookmarks so they only get fetched when we open the browser section.
I also fixed in the first commit an issue with the curated communities fetch. First, we didn't handle errors correctly. Second, I forgot to only load once, so if you leave the community portal and reopen, it would fetch again.
> Lazy load bookmarks for the browser + fix curated community loading in case of error

- src/nim_status_client.nim
AppController executes status-go Logout function when it's being deleted, and that will stop all status-go services and kill pending mailserver requests. If StatusFoundation is deleted before the AppController, it's possible for some tasks to freeze the app on logout
> fix: delete `appController` before `statusFoundation`

- src/app/modules/main/wallet_section/transactions/controller.nim
- src/app_service/service/transaction/dto.nim
- src/app_service/service/transaction/service.nim
- ui/app/AppLayouts/Wallet/views/LeftTabView.qml
- ui/imports/shared/popups/SendModal.qml
Bump status-go to include the propagation of transaction ID for status-go APIs
Remove deletion of pending from Nim, it is done in status-go on first transaction status change
Also
- Add leftover fixes from SendModal layout :(
Updates: #7663
> feat(wallet) propagate multi-transaction ID to Nim

- storybook/CMakeLists.txt
- storybook/qmlTests/main.cpp
`StatusQ` types are registered properly for `Storybook/qmlTests` now in order to make that target functional again.
Closes: #9690
Storybook/qmlTests
> fix(Storybook): Register StatusQ types for Storybook/qmlTests

- src/app_service/service/chat/service.nim
- src/app_service/service/community/service.nim
When a community link is shared with a user and that user visits that community, it turns out that the chat objects for that community have not been created yet.
This results in chat data being malformed/non-existent until another message signal is processed that updates the chats in memory. This update can someimes occur earlier, sometimes later, which is why the issue isn't always reproducible.
This commit ensures we're loading chats from status-go again upon spectating, to ensure they exist in memory when we try to access the data in the UI.
Closes #8361
> fix(Communities): ensure community chats exist in memory upon spectating

- ui/StatusQ/src/StatusQ/Layout/StatusAppNavBar.qml
- ui/main.qml
- reduce top margin for non-macOS builds
Fixes #9684
Fixes extra margin on top of the primary navbar when not running on macOS
StatusAppNavBar, main
> fix: Primary nav bar vertical alignment on Windows/Linux

- src/app_service/service/community/service.nim
Fixes #9678
We need to use `formatImagePath` for any image paths for Windows to work.
> fix(community-service): fix community image parsing for windows

- ui/StatusQ/src/StatusQ/Components/StatusContactVerificationIcons.qml
- ui/StatusQ/src/StatusQ/Components/StatusExpandableItem.qml
- ui/StatusQ/src/StatusQ/Components/StatusListItem.qml
- ui/StatusQ/src/StatusQ/Components/StatusListItemTag.qml
- ui/StatusQ/src/StatusQ/Components/StatusSmartIdenticon.qml
Fixes: #9714
Changes to StatusRoundIcon in PR [9574](https://github.com/status-im/status-desktop/pull/9574) specifically lines:
https://github.com/IvanBelyakoff/status-desktop/blob/ae082b26ff245fac902491139b98f599187ae139/ui/StatusQ/src/StatusQ/Components/StatusRoundIcon.qml#L22
this:
`radius: bgWidth / 2`
was changed to:
```
bgRadius: bgWidth / 2
...
radius: asset.bgRadius
```
Does not work, when asset is entirely overwritten, but `bgRadius` is not specified:
_Somewhere in code:_
```
asset.bgWidth: 40
// asset.bgRadius: asset.bgWidth / 2 // This is not done!
...
asset: root.asset // `bgWidth` will be set, but `bgRadius` is now empty even if it defaulted to `bgWidth / 2` for StatusRoundIcon, icon background will be square, but meant to be circle
```
I still believe the fix was correct, …
> fix(@desktop/statusq): Fix icons background square, but must be circle

- src/app/modules/main/chat_section/chat_content/messages/module.nim
- src/app/modules/shared_models/message_item.nim
- ui/StatusQ/src/StatusQ/Components/StatusMessage.qml
Fixes: #9564
Mobile app sending images with text in one message. This PR adds filtering images in messages and displaying text from message.
P.S.: Don't know how to fix out placeholder in image messages which already sent.
Chat
> fix(chat): Display text from image message

- storybook/main.qml
- storybook/src/Storybook/PageToolBar.qml
Adds small convenience button to storybook allowing to copy component name to clipboard in order to find it quickly in QtCreator via Ctrl+K, Ctrl+V sequence.
Closes: #9673
Storybook (PageToolBar)
[Kazam_screencast_00125.webm](https://user-images.githubusercontent.com/20650004/221978849-60531e7a-2c3d-4140-b87f-c20696041749.webm)
> feat(Storybook): Add button for copying component name to clipboard

- src/app/core/notifications/details.nim
- src/app/core/notifications/notifications_manager.nim
- src/app/global/global_events.nim
- src/app/modules/main/chat_section/controller.nim
- src/app/modules/main/chat_section/io_interface.nim
- src/app/modules/main/chat_section/module.nim
- src/app/modules/main/chat_section/view.nim
- src/app/modules/main/controller.nim
- src/app/modules/main/io_interface.nim
- src/app/modules/main/module.nim
- src/app/modules/shared_models/token_criteria_item.nim
- src/app/modules/shared_models/token_criteria_model.nim
- src/app/modules/shared_models/token_list_item.nim
- src/app/modules/shared_models/token_list_model.nim
- src/app/modules/shared_models/token_permission_chat_list_item.nim
- src/app/modules/shared_models/token_permission_chat_list_model.nim
- src/app/modules/shared_models/token_permission_item.nim
- src/app/modules/shared_models/token_permissions_model.nim
- src/app_service/service/community/dto/community.nim
- src/app_service/service/community/service.nim
- src/app_service/service/community_tokens/service.nim
- src/app_service/service/token/service.nim
- src/app_service/service/wallet_account/dto.nim
- src/app_service/service/wallet_account/service.nim
- src/backend/communities.nim
- ui/app/AppLayouts/Chat/controls/community/HoldingTypes.qml
- ui/app/AppLayouts/Chat/panels/communities/CommunityPermissionsSettingsPanel.qml
- ui/app/AppLayouts/Chat/stores/CommunitiesStore.qml
- ui/app/AppLayouts/Chat/stores/RootStore.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityPermissionsView.qml
This commit is the first of implementing community permissions. **It is not implementing the complete feature**, rather does it introduce the first pieces, such that we can get code reviewed and merged before it grows too big.
To review these features, please make sure to
1. Enable wallet (Settings -> Advanced -> Wallet toggle)
2. Enable community permissions (Settings -> Advanced -> Community Permissions toggle)
You'll have to restart the app after doing so.
The commit introduces the following:
**UI, API calls and view models to CRUD community permissions**
After creating a community, the user can go to the community settings and create new token permissions. The user can also update and delete existing permissions.
**Asset and collectible view models**
To create community token …
> feat(Communities): allow for creating community permissions

- storybook/pages/CommunityPermissionsViewPage.qml
- storybook/src/Models/ChannelsModel.qml
- storybook/src/Models/PermissionsModel.qml
- ui/StatusQ/src/StatusQ/Core/Utils/ModelChangeGuard.qml
- ui/StatusQ/src/StatusQ/Core/Utils/ModelChangeTracker.qml
- ui/StatusQ/src/StatusQ/Core/Utils/qmldir
- ui/app/AppLayouts/Chat/controls/community/CommunityListItem.qml
- ui/app/AppLayouts/Chat/controls/community/InDropdown.qml
So far channel models was 2-level. The first level for channels/categories, the second one for channels in category. Now it's simplified and the model is flattened. The `InDropdown` component has been updated for that.
Moreover: 
- fixed `CommunityPermissionsViewPage` which was altering singleton's data making it impossible to reset state of the page
Requires: https://github.com/status-im/status-desktop/pull/9518 (needs to be integrated first)
Closes: https://github.com/status-im/status-desktop/issues/9591
`InDropdown`
> chore(InDropdown): Adapt to flattened model for channels

- ui/StatusQ/src/StatusQ/Core/LocaleUtils.qml
For small numbers (<10^-6), java script's Number.toString() returns string representing number in scientific notation. This case wasn't handled properly so far by `fractionalPartLength` method, causing some undesired truncation for small numbers.
Closes: #9681
`LocaleUtils`
[Kazam_screencast_00123.webm](https://user-images.githubusercontent.com/20650004/222207524-621f1c20-7e1b-417d-aa4b-787d34c4a396.webm)
> fix(LocaleUtils): Improve handling small numbers by fractionalPartLength(num)

- ui/StatusQ/src/StatusQ/Core/LocaleUtils.qml
- ui/imports/shared/controls/AmountInput.qml
Only number of digits is taken into consideration when calculating input length for comparison with the limit. Possibility of using non-standard digits is taken into account.
Closes: #9718
`AmountInput`
[Kazam_screencast_00124.webm](https://user-images.githubusercontent.com/20650004/222418850-8df1a116-8bc2-4167-bd99-68ec239bb3f0.webm)
> fix(AmountInput): Skip non-digits for max input length limit validation

- ci/Jenkinsfile.e2e
- test/ui-test/README.md
- Updated squish version from `6.7.2` to `7.1-SNAPSHOT`. 
Related information: https://github.com/status-im/status-desktop/issues/9451#issuecomment-1453391615
CI / e2e job
> ci(e2e): Updated squish version from 6.7.2 to 7.1-SNAPSHOT

- src/nim_status_client.nim
- vendor/DOtherSide/lib/include/DOtherSide/DOtherSide.h
- vendor/DOtherSide/lib/src/DOtherSide.cpp
Part of #9558
Motivation: The splash screen is freezing when the main thread is blocked even with the new animator introduced here #9524.
Enable threaded renderer except when using Qt5 for `arm64` on Macs.
I'm adding the nimqml changes to be reviewed here first. Will add nimqml PR and bump the version when this PR is reviewed.
Qt renderer
> fix(SplashScreen): Enable threaded renderer

- src/app/modules/main/wallet_section/collectibles/controller.nim
- src/app/modules/main/wallet_section/collectibles/current_collectible/controller.nim
- src/app/modules/main/wallet_section/collectibles/current_collectible/view.nim
- src/app/modules/main/wallet_section/collectibles/io_interface.nim
- src/app/modules/main/wallet_section/collectibles/models/collectibles_item.nim
- src/app/modules/main/wallet_section/collectibles/models/collectibles_model.nim
- src/app/modules/main/wallet_section/collectibles/models/collectibles_utils.nim
- src/app/modules/main/wallet_section/collectibles/models/collections_item.nim
- src/app/modules/main/wallet_section/collectibles/models/collections_model.nim
- src/app/modules/main/wallet_section/collectibles/module.nim
- src/app/modules/main/wallet_section/collectibles/view.nim
- src/app/modules/main/wallet_section/transactions/controller.nim
- src/app/modules/main/wallet_section/transactions/io_interface.nim
- src/app/modules/main/wallet_section/transactions/item.nim
- src/app/modules/main/wallet_section/transactions/model.nim
- src/app/modules/main/wallet_section/transactions/module.nim
- src/app/modules/main/wallet_section/transactions/utils.nim
- src/app_service/common/wallet_constants.nim
- src/app_service/service/collectible/async_tasks.nim
- src/app_service/service/collectible/dto.nim
- src/app_service/service/collectible/service.nim
- src/app_service/service/transaction/async_tasks.nim
- src/app_service/service/transaction/dto.nim
- src/app_service/service/transaction/service.nim
- src/backend/backend.nim
- src/backend/collectibles.nim
- ui/app/AppLayouts/Wallet/stores/RootStore.qml
- ui/app/AppLayouts/Wallet/views/TransactionDetailView.qml
- ui/imports/shared/controls/TransactionDelegate.qml
- ui/imports/shared/views/HistoryView.qml
Fixes #8811
The activity tab now properly shows erc721 (NFT) transfers. Not much attention was put to the design, since @benjthayer is currently reworking it. Some basic information (name and icon) is shown to validate the backend work.
The way it currently works is the following: When some transactions are fetched, before finishing the async call, we fetch the needed collectibles (contract address + tokenID) for any erc721 transaction in the list. We include them as part of the transaction fetch result.
I would've liked to implement this differently (fetch transactions and collectibles separately, and update the transaction list when the collectibles arrive), but the way the transactions module is implemented made this difficult without a bigger rework.
Renamed some stuff in the …
> feat(@dekstop/wallet): support collectibles in activity tab

- .gitmodules
- Info.dev.plist
- Info.plist
- Makefile
- build-linux.sh
- ci/Dockerfile
- ci/Jenkinsfile.linux
- ci/Jenkinsfile.tests-nim
- docker-linux-app-image.sh
- scripts/ubuntu_build_setup.sh
- ui/StatusQ/CMakeLists.txt
- ui/StatusQ/sandbox/CMakeLists.txt
- ui/StatusQ/sandbox/demoapp/data/Models.qml
- ui/StatusQ/sandbox/main.qml
- ui/StatusQ/sandbox/sandboxapp.cpp
- ui/StatusQ/sanity_checker/CMakeLists.txt
- ui/StatusQ/sanity_checker/main.cpp
- ui/StatusQ/src/StatusQ/Components/StatusQrCodeScanner.qml
- ui/StatusQ/src/StatusQ/Components/qmldir
- ui/StatusQ/src/statusq.qrc
- vendor/DOtherSide/CMakeLists.txt
- vendor/DOtherSide/lib/CMakeLists.txt
- vendor/DOtherSide/lib/src/DOtherSide.cpp
Required for https://github.com/status-im/status-desktop/issues/5837
Overrides:
- https://github.com/status-im/status-desktop/pull/5756
- https://github.com/status-im/dotherside/pull/65
This is a QR code scanner. Based on [QZXing](https://github.com/ftylitak/qzxing).
Notes:
1. I have an issue on MacOS, that camera loads quite long, about 5-10 seconds. 
Didn't fix it yet, will try to improve it later.
2. I implemented a camera selector, but it didn't fully work for me.
Will try to fix it later.
3. I will also create a PR with changes made for QZXing library. 
Currently pointing to status-im fork.
StatusQ …
> QR code scanner (QML component)

- src/app_service/common/network_constants.nim
Requires:
- https://github.com/status-im/status-go/pull/3247
Sets the default port for new accounts to 0 for both WakuV2 and Torrent.
It also replaces the PORT_SHIFT variable for TORRENT_PORT and WAKU_PORT which can be used in case someone wants to use an specific port number, otherwise, it will automagically find a new port.
(Currently this only applies to new accounts, maybe we should create a migration so existing users find a random port too?)
> chore: use random ports for waku and torrents

- src/app/modules/main/wallet_section/accounts/item.nim
- src/app/modules/main/wallet_section/accounts/utils.nim
- src/app/modules/main/wallet_section/accounts/view.nim
- src/app/modules/main/wallet_section/current_account/module.nim
- src/app/modules/shared_modules/keycard_popup/module.nim
- src/app_service/service/wallet_account/service.nim
What I noticed while was fixing this is that wallet account module for the settings part of the app is pretty weirdly developed. A lot of nested dependencies which may affect the performance of that part, actually that part is so light (like just reading and displaying data stored in the db) that it should be displayed instantly. I didn't refactor there anything just fixed the issue with as little as possible changes, but just wanted to warn about that part (we should keep that in mind).
- https://github.com/status-im/status-go/pull/3245
Closes: #9667
> fix(@desktop/wallet): keypairs are displayed wrongly after account removal

- storybook/pages/CommunityNewPermissionViewPage.qml
- storybook/pages/CommunityPermissionsSettingsPanelPage.qml
- storybook/pages/CommunityPermissionsViewPage.qml
- ui/app/AppLayouts/Chat/controls/community/InDropdown.qml
- ui/app/AppLayouts/Chat/panels/communities/CommunityPermissionsSettingsPanel.qml
- ui/app/AppLayouts/Chat/stores/CommunitiesStore.qml
- ui/app/AppLayouts/Chat/stores/PermissionsStore.qml
- ui/app/AppLayouts/Chat/stores/RootStore.qml
- ui/app/AppLayouts/Chat/stores/qmldir
- ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityNewPermissionView.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityPermissionsView.qml
So far CP components (views, panels) were accessing stores directly. Now `CommunitySettingsView` is a single place where stores are accessed. Other components no longer depend on stores.
Moreover:
- dedicated store `PermissionsStore` created for handling permissions in a single, separated place
- storybook pages fixed
- some warnings fixed
Closes: #9784
Iterates: https://github.com/status-im/status-desktop/issues/9663
Note: in the next step naming should be aligned for both community permissions and minting components.
CommunityPermissions components
> chore(CommunityPermissions): refactor access to stores in CP components 

- ui/generate-rcc.go
let the `generate-rcc.go` skip files under `vendor` and `tests` subdirs; decreases the binary size and thus RAM usage by ~130 MB!
It became more pronounced recently with the import of `ui/StatusQ/vendor/qzxing` git submodule
```
$ ls -al resources.*
-rw-r--r--. 1 ltinkl ltinkl  81950109 Mar  8 14:47 resources.rcc
-rw-r--r--. 1 ltinkl ltinkl 215385428 Mar  8 12:35 resources.rcc.bloat
```
Reduces binary resources/app size
> chore: fix qrc resource bloat

- src/app/boot/app_controller.nim
- src/app/modules/main/chat_section/chat_content/input_area/controller.nim
- src/app/modules/main/chat_section/chat_content/input_area/io_interface.nim
- src/app/modules/main/chat_section/chat_content/input_area/module.nim
- src/app/modules/main/chat_section/chat_content/input_area/view.nim
- src/app/modules/main/chat_section/chat_content/module.nim
- src/app_service/service/gif/async_tasks.nim
- src/app_service/service/gif/service.nim
- src/backend/gifs.nim
Instead of loading recent gifs right on startup eagerly,
we postpone the task to when it's actually needed (when the gif popup is
opened and the recent gifs tab is activated), and on top of that
we also load the data asynchronously to keep the amount of work
that needs to be done in a single tick as short as possible.
This needs: https://github.com/status-im/status-go/pull/3170
Closes https://github.com/status-im/status-desktop/issues/9437
> refactor: load gifs asynchronously

- src/app/modules/main/stickers/controller.nim
- src/app/modules/main/stickers/io_interface.nim
- src/app/modules/main/stickers/module.nim
- src/app/modules/main/stickers/view.nim
- src/app_service/service/stickers/async_tasks.nim
- src/app_service/service/stickers/service.nim
- ui/imports/shared/status/StatusStickersPopup.qml
This postpones the loading of recently used stickers to the point when a) the stickers popup is opened and the recent stickers tab was the last visited one or b) when the sticker popup is open and one switches to the recent stickers tab.
Partially closes #9435
> refactor: load recent stickers asynchronously

- src/app/modules/main/chat_section/controller.nim
- src/app_service/service/community/service.nim
- src/backend/communities.nim
Fixes #9570
Removes the `joinedCommunities` cache Table and uses `allCommunities` instead, which was renamed just `communities`.
It simplifies the code a lots, plus should be lighter and faster.
If we need just a table of `joined` communities, I added `getFilteredJoinedCommunities` which does a manual filter on `communities`. The function `getJoinedCommunities` that was used by some controllers uses that function.
> refactor(communities): refactor communities cache in service

- src/dev/benchmark.nim
Adding thread safe benchmarking tools
Motivation: https://github.com/status-im/status-desktop/issues/9739
There are two ways to use this tool:
1. Use the benchmark `benchmarkProc` macro to benchmark a block of code. It will automatically call registerDuration with the name of the procedure and the start and end time
2. Manually call registerDuration with name, start and end time
The output file is named procBenchmark.csv and is located in the current working directory. It will be created at app exit.
The output is sorted by total time in descending order.
Output format:
```
Procedure, Number of runs, Total time in ms, Avg time in ms, Weight
test*,1,100.00,100.00,50.00%
test2*,1,100.00,100.00,50.00%
```
usage:
```
proc test() {.benchmarkProc.} =
sleep(1)
proc test2() {.benchmarkProc.} = …
```
> Chore: add thread safe benchmarking tool

- src/app/modules/shared_models/token_list_model.nim
- ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
Adds proxy model on top of assets model to serve static icons for tokens. This approach is used in wallet but there are some works in progress to change it in the future, including this place affected by this PR.
Closes: #9613
`CommunitySettingsView.qml`
> fix(CommunityPermissions): Temporary solution for assets icons

- src/app/modules/main/chat_section/controller.nim
- src/app/modules/main/chat_section/io_interface.nim
- src/app/modules/main/chat_section/module.nim
- src/app/modules/main/chat_section/view.nim
- src/app/modules/shared_models/token_criteria_model.nim
- src/app/modules/shared_models/token_list_model.nim
- src/app/modules/shared_models/token_permissions_model.nim
- src/app_service/service/community/dto/community.nim
- src/app_service/service/community/service.nim
- ui/app/AppLayouts/Chat/ChatLayout.qml
- ui/app/AppLayouts/Chat/stores/PermissionsStore.qml
- ui/app/AppLayouts/Chat/stores/RootStore.qml
- ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
This does a few things:
- It integrates with the latest `CommunityTokensMetadata` to access community specific ERC721 token
- It changes `ChatLayout` such that it conditionally loads either `ChatView` or `JoinCommunityView`. `JoinCommunityView` has been specifically designed for token-gated communities
Here's what works (in terms of token permissions):
1. If a community has token permissions and the the current users is not a member of that community, we show `JoinCommunityView` instead of `ChatView`
2. Any community token permissions of type "Become member" are listed in the `JoinCommunityView`
3. There are different types of token critera a permission can have: ERC20 token, ERC721 token, or ENS (which is also ERC721 but we have a type for that nonetheless)
Only ERC20 token balances are …
> feat: introduce first JoinCommunityView for token-gated communities

- test/ui-test/src/screens/StatusCommunityScreen.py
- test/ui-test/testSuites/suite_communities/tst_communityFlows/test.feature
Fixes #8005
Fixes #9287
Fixes creating, editing and deleting a channel because they rely on createChannel, that sometimes fails because the mouse click was off the button.
> fix(tests): fix tests that rely on creating a channel

- ui/StatusQ/src/StatusQ/Components/StatusMessage.qml
Close #9812
Show message's text for community invitation
Chat
> fix(Chat): Show message's text for community invitation

- ui/app/AppLayouts/Profile/views/NotificationsView.qml
Fixes #9708
Use `@everyone` instead of `@here` and `@channel` for the description
Settings/NotificationsView
> fix(NotificationsView): fixup global @everyone text

- ui/main.qml
Closing #9789 
Set the app minimum width to 1200. Also added validation for persistent settings in order not to break the min width/height.
Application window
https://user-images.githubusercontent.com/47811206/224982438-51872a26-3a50-40b2-8aad-725a2f1aea6c.mov
> fix: Set app minimum width to 1200

- src/app/modules/main/communities/controller.nim
- src/app/modules/main/communities/io_interface.nim
- src/app/modules/main/communities/module.nim
- src/app_service/service/community/async_tasks.nim
- src/app_service/service/community/dto/community.nim
- src/app_service/service/community/service.nim
- ui/app/AppLayouts/CommunitiesPortal/CommunitiesPortalLayout.qml
Fixes #9752
Adds properties to `CommunityDto` so that `curatedCommunities` can be removed and we only need `communities`.
For testers, make sure curated communities work as before in the community portal (TBH, it was pretty messed up before, so just having communities show up there is a good thing lol)
Normal communities should also work as expected, but I didn't actually touch that.
> refactor(community-service): merge curatedCommunities in communities

- ui/imports/shared/views/ProfileDialogView.qml
Close #9897
Add Reverse Contact Rejection action to profile
Profile, Contacts
https://user-images.githubusercontent.com/2522130/225340066-34741232-42c8-4b06-80bd-adb066ec32cb.mov
> fix(Contacts): Add Reverse Contact Rejection to profile actions

- src/app_service/common/types.nim
- ui/imports/shared/views/chat/MessageView.qml
- ui/imports/utils/Constants.qml
Fixes: #9655
Rename `Edit` type to `ContactRequest` and use it type as Text message
Chat
> fix(messaging): Sync with status-go content type enum

- src/app/modules/main/activity_center/controller.nim
- src/app/modules/main/activity_center/io_interface.nim
- src/app/modules/main/activity_center/module.nim
- src/app/modules/main/activity_center/view.nim
- src/app_service/service/activity_center/dto/notification.nim
- src/app_service/service/activity_center/service.nim
Fixes: #9751
[STATUS-GO PR](https://github.com/status-im/status-go/pull/3277)
Remove notifications from activity center model when source was deleted.
> fix(activity_center): Remove notifications from activity center

- test/ui-test/testSuites/suite_wallet/tst_wallet/test.feature
Disable the test case "The user can manage and observe a watch-only account" from running in CI.
The manual run also fails to show the real SNT balance in the ganache server. Requesting using `curl` works, so it seems to be something on the wallet side or ganache test integration.
On a second restart of the app, the `SNT` balance is displayed as expected.
Issue to fix and enable it: https://github.com/status-im/status-desktop/issues/9927
> tests(wallet) disable add watch only account failing test

- ui/StatusQ/sandbox/controls/ListItems.qml
- ui/StatusQ/src/StatusQ/Components/StatusDescriptionListItem.qml
- ui/app/AppLayouts/Chat/panels/communities/CommunityProfilePopupInviteFriendsPanel.qml
- ui/app/AppLayouts/Chat/panels/communities/CommunityProfilePopupOverviewPanel.qml
- set the width on title/subtitle
- put the subtitle with its optional icon into a Row
- elide title/subtitle
- update Sandbox
Fixes #9701
Fixes "Share URL" link eliding
CommunityProfilePopupInviteFriendsPanel/CommunityProfilePopupOverviewPanel
- [-] add documentation if necessary (new component, new feature)
Invite contacts popup:
View community popup:
> fix: ‘Share community’ URL is unnecessarily ellipsed

- ui/StatusQ/sandbox/controls/Controls.qml
- ui/StatusQ/src/StatusQ/Controls/StatusToolTip.qml
Fixes #9918
Fixes word wrap/elide for overly long text in the tooltip
StatusTooltip
> fix(StatusTooltip): long text goes out of bounds

- ui/app/AppLayouts/Chat/panels/communities/CommunityPermissionsSettingsPanel.qml
Fixing: https://github.com/status-im/status-desktop/issues/9765
The height and width is set by [SettingsPageLayout](https://github.com/status-im/status-desktop/blob/33d38a408124ba63243bd8af12874a9d4e817104/ui/app/AppLayouts/Chat/layouts/SettingsPageLayout.qml#L84). Overriding it breaks the layout.
Community Permissions
https://user-images.githubusercontent.com/47811206/225901737-76c21a60-b13f-4d28-a400-73d0b670530d.mov
> fix(CommunityPermissionsSettingsPanel): Fix height and width for permission views

- ui/app/AppLayouts/Chat/controls/community/PermissionsDropdown.qml
Simply comments-out part responsible for displaying channel-level permissions. It's intended to be restored to the previous version when that functionality is implemented in the backend.
Closes: https://github.com/status-im/status-desktop/issues/9537
`PermissionsDropdown.qml`
> chore(PermissionsDropdown): Temporarily hide channel-level permissions from the dropdown

- src/app/modules/main/profile_section/devices/model.nim
- src/app/modules/main/profile_section/devices/module.nim
- ui/StatusQ/sandbox/controls/ListItems.qml
- ui/StatusQ/sandbox/controls/LoadingStates.qml
- ui/StatusQ/src/StatusQ/Components/StatusListItem.qml
- ui/StatusQ/src/StatusQ/Components/StatusOnlineBadge.qml
- ui/StatusQ/src/StatusQ/Components/StatusSyncDeviceDelegate.qml
- ui/StatusQ/src/StatusQ/Components/qmldir
- ui/StatusQ/src/StatusQ/Core/LocaleUtils.qml
- ui/StatusQ/src/statusq.qrc
- ui/app/AppLayouts/Profile/views/SettingsContentBase.qml
- ui/app/AppLayouts/Profile/views/SyncingView.qml
- ui/imports/shared/views/DeviceSyncingView.qml
Fixes https://github.com/status-im/status-desktop/issues/9916
1. Fixes calculation for "Last seen online" subtitle
Note: actual timestamps are currently invalid, but the calculation is tested to be correct.
I will fix the investigate invalid timestamp values as a separate issue.
2. Added online/offline badge
3. Fixed "Devices" title design
4. Fixed "Syncing" page scrolling
5. `This device` is now always first
6. Fixed duplication of Devices list
Settings -> Syncing
> Fix synced devices list UI bugs

- storybook/PagesModel.qml
- storybook/pages/StatusDotsLoadingIndicatorPage.qml
- storybook/pages/StatusFlowSelectorPage.qml
- storybook/pages/StatusGroupBoxPage.qml
- storybook/pages/StatusItemSelectorPage.qml
- ui/StatusQ/doc/src/statusqcomponents.qdoc
- ui/StatusQ/sandbox/main.qml
- ui/StatusQ/sandbox/qml.qrc
- ui/StatusQ/src/StatusQ/Components/StatusFlowSelector.qml
- ui/StatusQ/src/StatusQ/Components/StatusGroupBox.qml
- ui/StatusQ/src/StatusQ/Components/StatusItemSelector.qml
- ui/StatusQ/src/StatusQ/Components/qmldir
- ui/StatusQ/src/statusq.qrc
- ui/app/AppLayouts/Chat/views/communities/CommunityNewAirdropView.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityNewPermissionView.qml
Decomposes `StatusItemSelector` into smaller components that can be used as a building blocks in other scenarios:
- `StatusGroupBox` - styled box with a background, title and icon, based on `GroupBox`
- `StatusFlowSelector` - base component for components implementing flow-based selection - implements placeholder item, "add" button and flow layout
- `StatusItemSelector` - based on `StatusFlowSelector` (instead of `Rectangle), the functionality as before.
Closes: https://github.com/status-im/status-desktop/issues/9851
`StatusItemSelector`
> refactor(StatusItemSelector): Decompose into smaller components

- src/app/modules/main/activity_center/controller.nim
- src/app/modules/main/activity_center/module.nim
- src/app/modules/main/chat_section/chat_content/controller.nim
- src/app/modules/main/chat_section/chat_content/messages/controller.nim
- src/app/modules/main/chat_section/chat_content/messages/io_interface.nim
- src/app/modules/main/chat_section/chat_content/messages/module.nim
- src/app/modules/main/chat_section/chat_content/module.nim
- src/app/modules/shared_models/message_item.nim
- src/app/modules/shared_models/message_model.nim
- src/app_service/service/message/service.nim
- test/nim/message_model_test.nim
Fixes #9859
getMessageById was called way too often, because each time a contact was updated, we called it on every message that contained a mention. Now we only call it on messages that contain a mention from that specific user.
Also, we called emojiReactionsByChatIDMessageID as part of that service call, but only the pinned message used it, so I removed it from the service function. This means that the pinned messages will no longer have the emoji reactions. I could add them back if we really want, but IMO, it's not really necessary. You can just click on the message and see it in the chat instead.
I removed the call to `getMessageById` in the activity center as well, since we can get the replied message info from the MessageDto directly now.
I also removed some dead code in the …
> refactor: reduce calls to getMessageById and remove calls for reactions

- ui/StatusQ/src/StatusQ/Components/private/statusMessage/StatusMessageEmojiReactions.qml
always use "white on blue"
Fixes #9944
Light mode:
Dark mode:
> fix(StatusEmojiReactions): Text in own reactions has wrong color in dark mode

- src/app/modules/main/profile_section/devices/controller.nim
- src/app/modules/main/profile_section/devices/io_interface.nim
- src/app/modules/main/profile_section/devices/model.nim
- src/app/modules/main/profile_section/devices/module.nim
- src/app/modules/main/profile_section/devices/view.nim
- src/app_service/service/devices/dto/installation.nim
- src/app_service/service/devices/service.nim
- src/backend/installations.nim
- ui/app/AppLayouts/Profile/popups/SyncDeviceCustomizationPopup.qml
- ui/app/AppLayouts/Profile/stores/DevicesStore.qml
Fixes https://github.com/status-im/status-desktop/issues/9584
Requires https://github.com/status-im/status-go/pull/3294
Now it's possible to change device name :)
https://user-images.githubusercontent.com/25482501/225600994-24f7d13c-8049-4aff-bd1b-4e878a51bdce.mov
> Fixed changing device name

- ui/app/AppLayouts/Chat/controls/community/ExtendedDropdownContent.qml
- ui/app/AppLayouts/Chat/controls/community/HoldingsDropdown.qml
Closing #9385
Implement dynamic height for `HoldingsDropdown`.
There is one workaround in place in order for the Popup to be able to properly compute the height when the content implicit height changes from a value higher than available height to something smaller. The workaround is to temporarily set the popup height to 0 before setting the height to undefined and let it compute the proper height.
HoldingsDropdown
ExtendedDropdownContent
https://user-images.githubusercontent.com/47811206/226444716-e702fde8-a428-4419-b052-85fd2dee3f43.mov
https://user-images.githubusercontent.com/47811206/226444819-0083f8be-54ca-4054-8 …
> fix(HoldingsDropdown): Implement dynamic height for holdings dropdown

- src/app_service/service/token/service.nim
Nim didn't complain, but the data was being "swallowed" resulting in a broken asset list in the permissions view.
> fix(tokenService): ensure token address map is properly initialized

- ui/StatusQ/src/StatusQ/Controls/StatusBaseInput.qml
- ui/StatusQ/src/StatusQ/Controls/StatusInput.qml
- ui/app/AppLayouts/Chat/controls/community/EnsPanel.qml
- ui/app/AppLayouts/Chat/controls/community/ExtendedDropdownContent.qml
- ui/app/AppLayouts/Chat/controls/community/HoldingsDropdown.qml
- ui/app/AppLayouts/Chat/controls/community/TokenPanel.qml
- ui/imports/shared/controls/Input.qml
Closing #9967 
1. When Holdings dropdown is open, activate focus to searcher in assets and collectibles. Changes focus to ENS input in case ENS tab is active.
2. In Holdings dropdown, when ENS tab is active and Add button is enabled, pressing enter key should behave same than clicking on the button itself.
3. In Holdings dropdown, when one asset or collectible has been selected, activate focus in the amount input, then when Add button is enabled, pressing enter key should behave same than clicking on the button itself.
HoldingsDropdown
StatusQ/Input/BaseInput.qml - forward focus to the input component and send signals on Enter/Return pressed
StatusQ/Input/StatusInput.qml - forward focus to the input component
https://user-images.githubusercontent.com/47811206/226682999-3d2d1bd0-49f6-4c7b-9 …
> fix(HoldingsDropdown): Add basic focus management and keyboard support

- .gitmodules
- storybook/CMakeLists.txt
- storybook/StoryBook.pro
- ui/StatusQ/CMakeLists.txt
- vendor/DOtherSide/CMakeLists.txt
Lets avoid creating chaos by having multiple vendor folders.
Also resolves errors like this:
```
> git submodule update --init --recursive
error: submodule git dir '/home/jakubgs/work/status-desktop/.git/modules/ui/StatusQ/vendor/qzxing' is inside git dir '/home/jakubgs/work/status-desktop/.git/modules/ui/StatusQ'
fatal: refusing to create/use '/home/jakubgs/work/status-desktop/.git/modules/ui/StatusQ/vendor/qzxing' in another submodule's git dir
Failed to clone 'ui/StatusQ/vendor/qzxing'. Retry scheduled
error: submodule git dir '/home/jakubgs/work/status-desktop/.git/modules/ui/StatusQ/vendor/qzxing' is inside git dir '/home/jakubgs/work/status-desktop/.git/modules/ui/StatusQ'
fatal: refusing to create/use '/home/jakubgs/work/status-desktop/.git/modules/ui/StatusQ/vendor/qzxing' in …
```
> move qzxing and SortFilterProxyModel to vendor folder

- src/app/modules/main/chat_section/controller.nim
- src/app/modules/main/chat_section/io_interface.nim
- src/app/modules/main/chat_section/module.nim
- src/app/modules/main/chat_section/view.nim
- src/app/modules/main/controller.nim
- src/app/modules/main/io_interface.nim
- src/app/modules/main/module.nim
- src/app/modules/shared_models/member_item.nim
- src/app/modules/shared_models/member_model.nim
- src/app/modules/shared_models/section_item.nim
- src/app/modules/shared_models/section_model.nim
- src/app_service/service/community/async_tasks.nim
- src/app_service/service/community/service.nim
- ui/app/AppLayouts/Chat/panels/communities/CommunityMembersTabPanel.qml
- ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
- ui/imports/shared/popups/NoPermissionsToJoinPopup.qml
- ui/imports/shared/popups/qmldir
This is necessary because with community token permissions, when owners
manually accept a request, we a) don't want to block the UI when the
users funds are check on chain and b) in case of insufficient funds,
we'll react with a modal that tells the owner that the user can't be
accepted.
All of that is done in this commit.
https://user-images.githubusercontent.com/445106/226599431-ea91b7ba-743f-46ba-b24b-d5983263f5ed.mp4
> refactor: make accepting member requests to join async

- src/app/core/unique_event_emitter.nim
- src/app/modules/main/chat_section/controller.nim
- src/app/modules/main/chat_section/io_interface.nim
- src/app/modules/main/chat_section/module.nim
- src/app/modules/main/chat_section/view.nim
- src/app/modules/main/communities/controller.nim
- src/app_service/service/community/service.nim
- src/backend/communities.nim
- ui/app/AppLayouts/Chat/ChatLayout.qml
- ui/app/AppLayouts/Chat/stores/RootStore.qml
Users that request access to community that are token permissioned need to authenticate and enter their password, so they can reveal their wallet addresses
> feat: add authentication modal to join commmunity view

- ui/app/AppLayouts/Chat/views/MembersSelectorView.qml
Fixes: #9881
`Paste` event not working perfect. I change it to parsing text which works 100%.
Just one suggestion: Checking the length of `CompressedPubkey` cos  `zQ3` is valid for method `isCompressedPubKey`
MembersSelectorView
> fix(MembersSelectorView): Change paste event to parsing text for lookup contacts

- src/app/modules/main/chat_section/chat_content/input_area/controller.nim
- src/app/modules/main/chat_section/chat_content/input_area/io_interface.nim
- src/app/modules/main/chat_section/chat_content/input_area/module.nim
- src/app/modules/main/chat_section/chat_content/input_area/view.nim
- src/app_service/service/gif/async_tasks.nim
- src/app_service/service/gif/service.nim
- ui/imports/shared/status/StatusGifPopup.qml
- ui/imports/shared/status/StatusGifPopup/EmptyPlaceholder.qml
- ui/imports/shared/stores/RootStore.qml
Fixes #9949
Only calls `setTenorAPIKey` once we need it (when doing a search or getting trending).  Also caches the trending gifs so that they are only fetched once. Makes the search and trending calls async by create an async tenor query async task.
For QAs: test that the gif popup works as before. You'll see a (quick) loading indicator when searching and opening for the first time.
> refactor(gifs): lazy load tenor api key + make search async

- src/app_service/service/accounts/service.nim
- src/app_service/service/devices/service.nim
Fixes https://github.com/status-im/status-desktop/issues/9982
Requires https://github.com/status-im/status-go/pull/3248
Update status-desktop to newer version of local pairing in status-go.
For user nothing should've changed, it's just internal update of structures.
Tested with https://github.com/status-im/status-mobile/pull/15412
I've tested all possible combinations:
* mobile -> desktop
* desktop -> mobil
* desktop -> desktop
Syncing
> fix(Syncing): Update to newer version of status-go local pairing

- ui/imports/shared/views/ProfileDialogView.qml
Close #9901 and #9898
Remove ability to cancel outgoing contact request
Contacts, Profile
> feat(Contacts): Remove ability to cancel outgoing CR

- src/app/modules/main/activity_center/module.nim
- src/app/modules/main/chat_section/chat_content/input_area/controller.nim
- src/app/modules/main/chat_section/chat_content/input_area/io_interface.nim
- src/app/modules/main/chat_section/chat_content/input_area/module.nim
- src/app/modules/main/chat_section/chat_content/input_area/view.nim
- src/app/modules/main/chat_section/chat_content/messages/module.nim
- src/app/modules/main/chat_section/chat_content/module.nim
- src/app/modules/shared_models/message_item.nim
- src/app/modules/shared_models/message_model.nim
- src/app_service/service/chat/service.nim
- src/app_service/service/message/dto/message.nim
- src/backend/chat.nim
- test/nim/message_model_test.nim
- ui/StatusQ/src/StatusQ/Components/StatusMessage.qml
- ui/StatusQ/src/StatusQ/Components/StatusMessageDetails.qml
- ui/app/AppLayouts/Chat/stores/RootStore.qml
- ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
- ui/imports/shared/views/chat/MessageView.qml
Fixes: #9564 #6374
Changes:
- User may send images without any text
- Display images album
- User may send images in one message
Relevant [status-go pr](https://github.com/status-im/status-go/pull/3287)
Chat
> fix(chat): Sent images with text correctly

- storybook/pages/HoldingsDropdownPage.qml
- ui/app/AppLayouts/Chat/controls/community/ExtendedDropdownContent.qml
- ui/app/AppLayouts/Chat/controls/community/HoldingsDropdown.qml
- ui/app/AppLayouts/Chat/controls/community/ListDropdownContent.qml
- ui/app/AppLayouts/Chat/panels/communities/CommunityAirdropsSettingsPanel.qml
- ui/app/AppLayouts/Chat/panels/communities/CommunityPermissionsSettingsPanel.qml
- ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityNewAirdropView.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityNewPermissionView.qml
Closes #9938
- Added `isCollectiblesOnly` option in `HoldingsDropdown`.
- Hidden assets tab in airdrop `HoldingsDropdown`.
- No data message added in `HoldingsDropdown`.
- Enabled navigation to mint tokens settings section from `HoldingsDropdown`.
- `storybook` updated accordingly.
Community Settings / Airdrop / Permissions holdings dropdown
https://user-images.githubusercontent.com/97019400/227328116-e61ca05a-dd09-45c8-bd99-4b529d29d78f.mov
https://user-images.githubusercontent.com/97019400/227328157-576ba7f3-79f3-4215-951f-60e8e4b142d1.mov
> feat(Airdrop): Some `HoldingsDropdown` improvements / adjustments

- ui/app/AppLayouts/Chat/stores/RootStore.qml
- ui/app/AppLayouts/Profile/stores/ProfileSectionStore.qml
- the community invitation bubble would never show up when pasting a link into a chat
- the import community popup in settings was missing some required store methods
> Fix: import join/community flow

- src/app/modules/main/chat_section/io_interface.nim
- src/app/modules/main/chat_section/module.nim
- src/app/modules/main/chat_section/view.nim
- ui/app/AppLayouts/Chat/ChatLayout.qml
- ui/app/AppLayouts/Chat/stores/RootStore.qml
There's a bug that all requests to join a community require the user to
authenticate themselves. This should only be needed for community that
are token permissioned.
This commit fixes it by only performing auth when requesting from the
tokengated community view.
Fixes #10010
> fix(communities): only require auth for token gated communities

- ui/StatusQ/src/StatusQ/Controls/StatusActivityCenterButton.qml
- ui/app/AppLayouts/Chat/views/ChatView.qml
Fixing #9615
Position tooltip arrow in the middle of the button
App toolbar
> fix(ActivitiCenterTooltip): Position tooltip arrow in the middle of the button

- storybook/pages/StatusItemSelectorPage.qml
- ui/StatusQ/src/StatusQ/Components/StatusItemSelector.qml
- ui/app/AppLayouts/Chat/controls/community/PermissionItem.qml
- ui/app/AppLayouts/Chat/panels/communities/HoldingsListPanel.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityNewPermissionView.qml
- ui/app/AppLayouts/Chat/views/communities/HoldingsSelectionModel.qml
Fixing https://github.com/status-im/status-desktop/issues/9766
The main change is that the model will now provide the image type, on top of the image source. The image type can be either icon or image. Icons will be coloured with the same colour as the text.
> fix(StatusItemsSelector): Allow icons to be provided by the model

- src/app/modules/main/chat_section/chat_content/messages/controller.nim
- src/app/modules/main/chat_section/chat_content/messages/io_interface.nim
- src/app/modules/main/chat_section/chat_content/messages/module.nim
- src/app/modules/main/chat_section/chat_content/messages/view.nim
- src/app/modules/main/chat_section/chat_content/module.nim
- src/app_service/service/message/async_tasks.nim
- src/app_service/service/message/service.nim
- ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
- ui/app/AppLayouts/Chat/views/MessagesLoadingView.qml
- show loading state when switching channels/chats until initial messages loading
- make `getFirstUnseenMessageIdFor` call async
Closes: #9441
1. Showing chat content during switching between the channels
2. First unseen message marker
https://user-images.githubusercontent.com/117639195/227528514-222e4bcb-17f5-4a02-b84b-a459cb7d9833.mov
> feat:(@desktop/channels): loading state when switching channels/chats

- ui/app/mainui/panels/DropAreaPanel.qml
- ui/imports/shared/status/StatusChatImageExtensionValidator.qml
- ui/imports/shared/status/StatusChatImageSizeValidator.qml
- ui/imports/shared/status/StatusChatInput.qml
- ui/imports/utils/Constants.qml
- ui/imports/utils/Utils.qml
Fixes #9966
Uses the validate function to paste images so that it concatenates the previous images.
Fixes the validate function to also accept data images.
Moves the size validation function to Utils to reuse the data path prefix constant and fix the possible crash when we try to get the size of a data image.
> fix(images): fix second pasted image replaces the first one

- ui/StatusQ/src/StatusQ/Components/StatusEmojiAndColorComboBox.qml
Redirect the click event and let the CustomComboItem fill the whole `contentItem` (otherwise a Button over another Button eats all the mouse events)
Fixes: #9977
Fixes opening/closing the combo box
[Záznam obrazovky z 2023-03-29 01-44-47.webm](https://user-images.githubusercontent.com/5377645/228391145-812d6b7f-b7ba-482a-b39c-58d0eaaff986.webm)
> fix: StatusComboBox doesn't react on click outside indicator

- src/app/modules/main/chat_section/controller.nim
- src/app/modules/main/chat_section/io_interface.nim
- src/app/modules/main/chat_section/module.nim
- src/app/modules/main/controller.nim
- src/app/modules/main/io_interface.nim
- src/app/modules/main/module.nim
- src/app_service/service/community/dto/community.nim
Marks collectible token criteria items in JoinCommunityView as we owned if the account owns wallets that match the criteria
Ideally, this PR lands first: https://github.com/status-im/status-go/pull/3348
> fix(permissions): check ownership of collectibles in permissions view

- src/app_service/common/network_constants.nim
Required for https://github.com/status-im/status-desktop/pull/9981
This doesn't make any sense 🙂 
Waku2Config is default now, afaik.
> Fix `WakuConfig` enabled

- src/app/modules/main/chat_section/controller.nim
- src/app/modules/main/chat_section/io_interface.nim
- src/app/modules/main/chat_section/model.nim
- src/app/modules/main/chat_section/module.nim
- src/app/modules/main/io_interface.nim
- src/app/modules/main/module.nim
- src/app/modules/shared_models/section_model.nim
- src/app_service/service/chat/service.nim
- src/app_service/service/community/service.nim
- src/app_service/service/message/async_tasks.nim
Fixes #10058
We were calling `updateParentBadgeNotifications` with wrong values, so we basically removed the badge all the time by accident.
Now, we calculate the unread messages and messages from the service's cache. 
Also, we still called `updateParentBadgeNotifications` when a contact is updated, as if the contact requests still went in the old contact request popup.
> fix(unread): fix badge disappearing because of wrong calculation

- src/app/modules/startup/controller.nim
- src/app/modules/startup/io_interface.nim
- src/app/modules/startup/module.nim
- src/app/modules/startup/view.nim
- src/app_service/service/accounts/service.nim
- ui/app/mainui/SplashScreen.qml
- ui/imports/shared/panels/DidYouKnowSplashScreen.qml
- ui/imports/utils/Constants.qml
- ui/main.qml
Fixes: #10039
Adds the recommendation to not close the app
Startup
> feat(SplashScreen): Display recommendation do not close the app on re-encryption process

- Makefile
- ci/Jenkinsfile.e2e
- config.nims
- src/app_service/service/devices/service.nim
- ui/StatusQ/sandbox/QrCodeScannerPage.qml
- ui/StatusQ/sandbox/main.qml
- ui/StatusQ/sandbox/qml.qrc
- ui/StatusQ/src/StatusQ/Components/StatusQrCodeScanner.qml
- ui/StatusQ/src/StatusQ/Controls/StatusComboBox.qml
- ui/app/AppLayouts/Onboarding/views/SyncCodeView.qml
- ui/app/AppLayouts/Onboarding/views/sync/SyncDeviceFromDesktop.qml
- ui/app/AppLayouts/Onboarding/views/sync/SyncDeviceFromMobile.qml
- ui/imports/shared/views/DeviceSyncingView.qml
FIxes https://github.com/status-im/status-desktop/issues/9865
Requires:
- https://github.com/status-im/status-desktop/pull/10088
- https://github.com/status-im/status-go/pull/3358
1. Embed `StatusQrCodeScanner` for "Setup with sync code" onboarding
1. Link `qzxing` as shared library
`qzxing` is built with many exceptions and `try/catch` blocks.
Currently catching doesn't work in the desktop app (though it works in sandbox).
When the library is build as shared one, it works. 
https://github.com/status-im/status-desktop/issues/9863 should fix this, for example.
1. Log error on `inputConnectionStringForBootstrappingFinished`
This should not happen, so I didn't implement any UI here
1. Hide user profile image until it's received from other device. …
> Embed QR code scanner for syncing devices on onboarding

- ui/StatusQ/src/StatusQ/Components/StatusMessage.qml
Fixes: #10044
Fix text component sizes for image messages
StatusMessage
> fix(images): Wrap text in image message

- storybook/pages/JoinCommunityViewPage.qml
- ui/app/AppLayouts/Chat/ChatLayout.qml
- ui/app/AppLayouts/Chat/panels/communities/JoinPermissionsOverlayPanel.qml
- ui/app/AppLayouts/Chat/stores/RootStore.qml
- ui/app/AppLayouts/Chat/views/communities/JoinCommunityView.qml
- ui/imports/utils/Constants.qml
Fixes: #9857 
1. Add login type enum
2. Pass the user login type from `JoinCommunityView` to `Reveal your address` button and configure the icon based on this value
JoinCommunityView
https://user-images.githubusercontent.com/47811206/228797764-e7956d42-7761-45b4-8caf-509976df2496.mov
KeyCard user using biometrics:
Keycard user without biometrics:
> fix(JoinCommunityView): Change Reveal Address button icon based on auth type

- src/app/modules/shared_models/message_model.nim
Fixes: #9958
[status-go pr](https://github.com/status-im/status-go/pull/3345)
Skip extra count of new messages for image albums
Chat
> fix(Albums): Fix extra count of messages for image albums

- src/app_service/service/message/service.nim
Fixes #10108
We were sending SIGNAL_NEW_MESSAGE_RECEIVED and SIGNAL_MESSAGE_EDITED, but the former is not needed, because the message editing is all done with the latter. The new message signal was sending the OS notification, which is not wanted, plus it did some useless processing, like trying to re-edit the message model, when it was already done.
The badge does get updated anyway, but that seems like an issue in status-go. It was telling me I had 3 unread messages, and I'm not sure why.
> fix(edit): don't send new message event on edits

- ui/StatusQ/src/StatusQ/Controls/StatusPasswordInput.qml
- ui/app/AppLayouts/Profile/popups/ChangePasswordModal.qml
- ui/imports/shared/views/PasswordView.qml
- enables selecting text with mouse in password input
- minor cleanups/fixes related to password modal
Fixes #9837
password input related classes
> fix(StatusPasswordInput): enable mouse interaction

- ui/main.qml
(backport/cherry fix of 27045501d6fe3658fa15fc8e3e4bb452d3bd390b into `release/0.11`)
those evil typos :)
Fixes #10039
> hotfix: unbreak showing encryption splash screen

- storybook/PagesModel.qml
- storybook/figma.json
- storybook/pages/AddressesInputListPage.qml
- storybook/pages/AddressesSelectorPanelPage.qml
- storybook/pages/AirdropRecipientsSelectorPage.qml
- storybook/src/Models/AddressesModel.qml
- storybook/src/Models/qmldir
- ui/app/AppLayouts/Chat/controls/community/AddressesInputList.qml
- ui/app/AppLayouts/Chat/controls/community/AddressesSelectorPanel.qml
- ui/app/AppLayouts/Chat/controls/community/AirdropRecipientsSelector.qml
- ui/app/AppLayouts/Chat/controls/community/MembersSelectorPanel.qml
- ui/app/AppLayouts/Chat/controls/community/qmldir
Implements selector component for adding eth addresses and eth members.
Closes: #9799
only new components in Storybook
https://user-images.githubusercontent.com/20650004/229463568-ab3af29d-817e-47b0-b6ef-9e21fe095f49.mp4
> feat(Airdrops): Component for selecting recipient addresses and members

- ui/app/AppLayouts/Chat/popups/community/CreateCategoryPopup.qml
- ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
Adjust according to Figma design
- the "Delete Category" button should be inside the footer
- the asset size should be 40x40
- fix the listview's horizontal alignment
- fix the confirmation dialog(s!) title
Fixes #9887
Aligns the popup with Figma design
CreateCategoryPopup
Delete confirmation:
> fix(CreateCategoryPopup): move the delete button into footer

- ui/app/AppLayouts/CommunitiesPortal/panels/CommunityColorPanel.qml
- ui/app/AppLayouts/CommunitiesPortal/panels/CommunityTagsPanel.qml
yet another little victim of the StatusScrollView regression; same (similar) thing for the color panel
Fixes #9971
Makes it possible to edit community tags again
CommunityTagsPanel/CommunityColorPanel
Tags preview:
Tags editing:
> fix(CommunityTagsPanel): unbreak the tags panel

- ui/StatusQ/src/StatusQ/Controls/StatusColorRadioButton.qml
- ui/StatusQ/src/StatusQ/Controls/StatusColorSelectorGrid.qml
- ui/StatusQ/src/StatusQ/Controls/StatusPickerButton.qml
- ui/StatusQ/src/StatusQ/Popups/StatusColorDialog.qml
- ui/app/AppLayouts/Chat/popups/community/CreateChannelPopup.qml
- ui/app/AppLayouts/CommunitiesPortal/controls/CommunityColorPicker.qml
- ui/app/AppLayouts/CommunitiesPortal/panels/CommunityColorPanel.qml
- use spacing as designed in Figma
- re-use StatusColorSelectorGrid title label component (not leaving extra
space behind when empty)
- always use white text for the color previews (our color palette/picker
are designed for this)
- give Channel color dialog a title (as designed)
- use BE spelling (as designed, and to be consistent with the rest of the app)
Fixes: #9841
Color selector/picker related components
Edit community panel:
Community color dialog:
Create new community wizard:
Create new community wizard (color selection sub-popup):
Edit channel preview:
Channel Color dialog:
> fix: Excessive vertical spacing between subtitle and standard colour selector in all colour selectors

- ui/StatusQ/src/StatusQ/Popups/StatusStackModal.qml
- ui/app/AppLayouts/Chat/panels/communities/CommunityEditSettingsPanel.qml
Remove the the back button here in a separate color dialog popup (same for Tags dialog as well)
Fixes #9790
CommunityEditSettingsPanel
Back button gone from the community color dialog:
> fix: Edit Community / Community Color selector dialogue does not need the back button

- src/app/modules/main/network_connection/controller.nim
- src/app/modules/main/network_connection/io_interface.nim
- src/app/modules/main/network_connection/module.nim
- src/app/modules/main/network_connection/network_connection_item.nim
- src/app/modules/main/network_connection/view.nim
- src/app_service/service/network_connection/service.nim
- ui/app/mainui/AppMain.qml
- ui/imports/shared/panels/ConnectionWarnings.qml
fixes #10124
Removes auto retries for connections errors.
In case of an error there are two things that can happen
1. The user can manually click on "Retry now"
2. We have a 10 in timer on wallet, after whichb all the data shown is refreshed
Connection error toasts
Collectibles down: 
https://user-images.githubusercontent.com/60327365/229581508-e16df052-7234-4eb3-84f2-150d1641da62.mov
Market Down:
https://user-images.githubusercontent.com/60327365/229581549-05c250cf-d8ed-4331-9e25-59c96570b36e.mov
Blockchain down: 
Uploading Screen Recording 2023-04-03 at 7.19.36 PM.mov…
> fix(@desktop/wallet): Remove auto retries for connections errors.

- src/app/modules/main/network_connection/controller.nim
- src/app/modules/main/network_connection/io_interface.nim
- src/app/modules/main/network_connection/module.nim
- src/app/modules/main/network_connection/network_connection_item.nim
- src/app/modules/main/network_connection/view.nim
- src/app_service/service/network_connection/service.nim
- ui/app/mainui/AppMain.qml
- ui/imports/shared/panels/ConnectionWarnings.qml
cherry-pick https://github.com/status-im/status-desktop/pull/10140
Removes auto retries for connections errors.
In case of an error there are two things that can happen
1. The user can manually click on "Retry now"
2. We have a 10 in timer on wallet, after whichb all the data shown is refreshed
Connection error toasts
Collectibles down: 
https://user-images.githubusercontent.com/60327365/229581508-e16df052-7234-4eb3-84f2-150d1641da62.mov
Market Down:
https://user-images.githubusercontent.com/60327365/229581549-05c250cf-d8ed-4331-9e25-59c96570b36e.mov
Blockchain down: 
Uploading Screen Recording 2023-04-03 at 7.19.36 …
> Cherry pick issue 10124

- ui/app/AppLayouts/Profile/ProfileLayout.qml
- ui/app/AppLayouts/Profile/views/NotificationsView.qml
Fixes #9683
Settings/Notifications
> fix: Remove syncing header from ‘Notifications and Sounds’

- storybook/pages/CommunityNewPermissionViewPage.qml
- storybook/pages/CommunityPermissionsSettingsPanelPage.qml
- storybook/pages/StatusGroupBoxPage.qml
- ui/StatusQ/src/StatusQ/Components/StatusGroupBox.qml
- ui/StatusQ/src/StatusQ/Components/StatusItemSelector.qml
- ui/app/AppLayouts/Chat/controls/community/PermissionItem.qml
- ui/app/AppLayouts/Chat/panels/communities/CommunityPermissionsSettingsPanel.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityNewPermissionView.qml
- adds visual representation of disabled StatusGroupBox's label
- adds switch to "Who holds" selector
- integrates the switch with duplicates detection
- updates dirty state checks
- allows defining permissions without holdings specified
Community Permissions components
Note: full integration with the app will be done when per-channel permissions are implemented.
https://user-images.githubusercontent.com/20650004/229830161-ce797bf2-69b8-4a64-88df-f76f2f85294d.mp4
> feat(CommunityPermissions): Switch to enable/disable 'Who holds' section 

- src/app/boot/app_controller.nim
- src/app/modules/main/wallet_section/collectibles/controller.nim
- src/app/modules/main/wallet_section/collectibles/io_interface.nim
- src/app/modules/main/wallet_section/collectibles/models/collectibles_model.nim
- src/app/modules/main/wallet_section/collectibles/module.nim
- src/app/modules/main/wallet_section/collectibles/view.nim
- src/app/modules/main/wallet_section/current_account/controller.nim
- src/app/modules/main/wallet_section/current_account/module.nim
- src/app/modules/main/wallet_section/module.nim
- src/app/modules/startup/controller.nim
- src/app_service/service/collectible/async_tasks.nim
- src/app_service/service/collectible/service.nim
- src/app_service/service/network_connection/service.nim
- src/app_service/service/wallet_account/service.nim
fixes https://github.com/status-im/status-desktop/issues/10063
cherrypicks https://github.com/status-im/status-desktop/pull/10073
Fix several issues related to collectibles:
- Properly handle errors when fetching collectibles. There's now an `Error` state, which prevents further fetching until a reset occurs.
- Added missing init, fixing periodic re-fetches
- Reduced chunk size to improve responsiveness
- Fixed loading items on initial fetch
- Made collectibles screen match the design when an error occurs
> Cherrypick Fix/10063 various collectibles bugs

- ui/StatusQ/src/StatusQ/Components/StatusCard.qml
- ui/StatusQ/src/StatusQ/Core/LocaleUtils.qml
- ui/app/AppLayouts/Chat/controls/community/TokenPanel.qml
- ui/imports/shared/controls/AmountInput.qml
- ui/imports/shared/views/AmountToSend.qml
- ui/imports/shared/views/NetworkCardsComponent.qml
Cherrypicks #10169
Fixes #10125
Regardless of system locale, use `en_US` locale for user input. That means that `.` is the only accepter decimal separator.
https://user-images.githubusercontent.com/11161531/229835309-1dc9e3ef-6288-4899-bfec-0f78998d1d63.mov
> fix(@desktop): only allow dot as decimal separator for user input

- ui/app/AppLayouts/Chat/panels/communities/CommunityMembersSettingsPanel.qml
- ui/app/AppLayouts/Chat/panels/communities/CommunityMembersTabPanel.qml
- ui/app/AppLayouts/Chat/stores/RootStore.qml
- ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
Part of https://github.com/status-im/status-desktop/issues/9912
This PR is unifying the user click handling between members list and community members settings:
Left click will open the user profile
Right click will open the context menu
1. Fix left click handler - Open user profile
2. Add context menu on right click (reusing the same one from Members list)
Community members settings
https://user-images.githubusercontent.com/47811206/230408955-76ea5492-819f-49a5-b83f-b222882a6b34.mov
> fix(CommunityMembersSettings): Add member context menu + fix user click handler

- ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
Closing: https://github.com/status-im/status-desktop/issues/10131
Use Listview [currentIndex](https://doc.qt.io/qt-6/qml-qtquick-listview.html#currentIndex-prop) to scroll to message instead of positionViewAtIndex. The currentIndex implementation can be fine tuned to work with our async delegates with dynamic height.
https://user-images.githubusercontent.com/47811206/229896629-9c9e5bd5-e292-42e2-af1b-d40caa1d6acc.mov
https://user-images.githubusercontent.com/47811206/229896701-f64ba3f1-1585-4da3-887f-d1d82ef4e802.mov
> fix(ChatMessagesView): Fixing scroll to message

- src/app/modules/main/communities/view.nim
Fixes: #10146
The problem was in `setCommunityTags` which change the tags but not notify UI about it. 
Communities
> fix(Communities): Emit the signal about community tags changes

- src/app/modules/main/activity_center/module.nim
- src/app/modules/main/chat_section/chat_content/messages/module.nim
- src/app/modules/main/chat_section/chat_content/module.nim
- src/app/modules/shared_models/message_item.nim
- src/app/modules/shared_models/message_model.nim
- src/app_service/service/message/dto/message.nim
- test/nim/message_model_test.nim
- ui/StatusQ/src/StatusQ/Components/StatusMessage.qml
- ui/StatusQ/src/StatusQ/Components/StatusMessageDetails.qml
- ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
- ui/imports/shared/views/chat/MessageView.qml
Fixes: #9990
Display image placeholder. 
Unfortunately, old versions where album was received can't display images anymore. But I will try to add some migration to status which add `albumCount` for old albums.
Message view
> fix(images): Display image placeholder when image from album not loaded

- ui/StatusQ/src/StatusQ/Components/StatusChatListItem.qml
Closes #8265
StatusChatList: added marks indicating unread msg and mentions respectively
StatusChatList
https://user-images.githubusercontent.com/31625338/230621766-cc154c84-bb64-4fb5-a58b-ba3e8f6785ff.mov
> [StatusChatList]: added marks indicating unread msg and mentions

- ui/StatusQ/src/StatusQ/Components/StatusCursorDelegate.qml
- ui/StatusQ/src/StatusQ/Components/qmldir
- ui/StatusQ/src/StatusQ/Controls/StatusBaseInput.qml
- ui/StatusQ/src/StatusQ/Controls/StatusTextArea.qml
- ui/StatusQ/src/statusq.qrc
- ui/app/AppLayouts/Chat/panels/InlineSelectorPanel.qml
- ui/imports/shared/controls/AmountInputWithCursor.qml
- ui/imports/shared/panels/ModuleWarning.qml
- ui/imports/shared/status/StatusChatInput.qml
Fixes several smaller UI and perf issues; see individual commits for explanation, namely:
- fix "Unblock" chat button
- speedup channel switching
- speed up emoji parsing and replacements
- fix handling "up" key event in multiline text
- fix stealing input focus
- extract cursor delegate into StatusCursorDelegate 
- fix inline emoji replacements behavior
> chore/fix: various StatusChatInput fixes and spedups

- ui/app/AppLayouts/Chat/panels/InlineSelectorPanel.qml
Closes #9885
StartNewChat: fixed/added scrolling behavior
StartNewChat
https://user-images.githubusercontent.com/31625338/230932422-289b9778-5992-47a6-808b-bec25d5b8f07.mov
> [StartNewChat]: fixed text input scroll

- ui/app/AppLayouts/Chat/panels/SuggestionFilterPanel.qml
- ui/imports/shared/status/StatusChatInput.qml
Fixes #10212
The problem was that we were detecting that the name was empty string and comparing to another empty string and inserting that, which is incorrect.
There was also a problem with the detection of the name being completely written. onKeyPressed didn't take into account the new letter added, onKeyReleased does.
I did some small clean ups too.
> fix(mentions): fix @everyone inserting incorrectly sometimes

- src/app_service/service/community/service.nim
The community data we get from the signals and responses don't contain the pending requests so we must copy previously received `pendingRequestsToJoin`, `declinedRequestsToJoin`, `canceledRequestsToJoin`
Fixes: #10147 
Membership request button
> fix(@desktop/community): membership request button disappears when a category is edited

- storybook/PagesModel.qml
- storybook/pages/RemoteSelfDestructPopupPage.qml
- storybook/pages/SelfDestructAlertPopupPage.qml
- storybook/pages/TokenHoldersPanelPage.qml
- storybook/src/Models/TokenHoldersModel.qml
- ui/StatusQ/src/StatusQ/Controls/StatusItemDelegate.qml
- ui/app/AppLayouts/Chat/panels/communities/CommunityMintTokensSettingsPanel.qml
- ui/app/AppLayouts/Chat/panels/communities/MintTokensFooterPanel.qml
- ui/app/AppLayouts/Chat/panels/communities/TokenHoldersPanel.qml
- ui/app/AppLayouts/Chat/popups/community/RemoteSelfDestructPopup.qml
- ui/app/AppLayouts/Chat/popups/community/SelfDestructAlertPopup.qml
- ui/app/AppLayouts/Chat/popups/community/qmldir
- ui/app/AppLayouts/Chat/stores/CommunityTokensStore.qml
- ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityMintedTokensView.qml
Closes #10051
- Created needed popups and added storybook support.
- Extended token holders panel with selector mode.
- Integrated remote self-destruct flow in the app. **ONLY UI - BACKEND NEEDED**
Community Settings / Mint tokens / Self-destruct option
https://user-images.githubusercontent.com/97019400/229211010-0783eca8-1c7e-43aa-91c5-6c368b79aa29.mov
https://user-images.githubusercontent.com/97019400/229211021-be47b4cb-d284-433f-af65-54c09a91e026.mov
> feat(Mint Collectibles): Implement Remotely self-destruct footer option

- src/app/modules/main/wallet_section/collectibles/current_collectible/view.nim
- src/app/modules/main/wallet_section/collectibles/models/collectibles_item.nim
- src/app/modules/main/wallet_section/collectibles/models/collectibles_model.nim
- src/app/modules/main/wallet_section/collectibles/models/collectibles_utils.nim
- src/app_service/service/collectible/dto.nim
- ui/StatusQ/doc/src/statusqcomponents.qdoc
- ui/StatusQ/src/StatusQ/Components/StatusAnimatedImage.qml
- ui/StatusQ/src/StatusQ/Components/StatusImage.qml
- ui/StatusQ/src/StatusQ/Components/StatusRoundedComponent.qml
- ui/StatusQ/src/StatusQ/Components/StatusRoundedImage.qml
- ui/StatusQ/src/StatusQ/Components/StatusRoundedMedia.qml
- ui/StatusQ/src/StatusQ/Components/StatusVideo.qml
- ui/StatusQ/src/StatusQ/Components/qmldir
- ui/StatusQ/src/statusq.qrc
- ui/app/AppLayouts/Chat/views/communities/CommunityMintedTokensView.qml
- ui/app/AppLayouts/Wallet/views/CollectiblesView.qml
- ui/app/AppLayouts/Wallet/views/collectibles/CollectibleDetailView.qml
- ui/app/AppLayouts/Wallet/views/collectibles/CollectibleView.qml
Fixes #9836
status-go part: https://github.com/status-im/status-go/pull/3334/files
Adds support for different types of NFT media
- Pictures / GIFs
- Video
A new component `StatusRoundedMedia` was added that handles the whole logic of using the appropriate QML viewer according to the mediaType. There's also some retry logic involved and a fallback mechanism to be able to successfully display as many NFTs as possible. This logic can possibly be moved to C++ for a cleaner implementation.
https://user-images.githubusercontent.com/11161531/227303708-df2cb604-bcc1-4df6-883a-b20dd7dcef41.mov
> feat(@desktop/wallet): add support for more NFTs media types

- src/app_service/service/community/dto/community.nim
- src/app_service/service/community/service.nim
Show members in spectate mode (non-joined communities) for open communities and hide for closed communities
Fixes: #9697
Members list displaying
> fix(@desktop/communities): show members in spectate mode for open communities and hide for closed communities

- src/app/modules/main/chat_section/module.nim
Fixes: #10162
Adds `Image` text to notifications with images when its needed
OS Notifications
> fix(os-notifications): Add `Image` text to notifications with image without a text

- src/app_service/service/chat/service.nim
Fixes #10264
First commit fixes the category hightlight on new messages. We didn't correctly check the categoryId, so as soon as a channel has unread messages in the community, it would be bold.
Second commit ups status-go to fix the badge on the left side. The count was done only for personal chats by accident.
status-go PR https://github.com/status-im/status-go/pull/3389
> Fix badge and category highlight

- src/app_service/service/activity_center/service.nim
- src/app_service/service/community/service.nim
Close #9811
Depends https://github.com/status-im/status-go/pull/3390
Right user gets the notification about kicking from community
Activity Center, Communities
> fix(ActivityCenter): Update status-go ActivityCenterNotificationTypeCommunityKicked and fix accepting community requests from AC

- ci/Jenkinsfile.combined
- ci/Jenkinsfile.e2e
- ci/Jenkinsfile.imports
- ci/Jenkinsfile.tests-e2e
Useful for tracking down which commit introduced a breaking change.
I'm lowering `maxConcurrentTotal` limit for e2e parallel build since the release builds on `ci.infra.status.im` do not share the same throttling limits across Jenkins instances, so we can hit a licenses usage limit.
Also increasing number of builds to keep to 30.
> ci: run e2e tests for release and master builds

- ci/Jenkinsfile.tests-e2e
Allows for easier running of individual test suites and selecting tags.
> ci: add suite and tags parameters to e2e CI job

- src/app/modules/main/chat_section/chat_content/controller.nim
- src/app/modules/main/chat_section/chat_content/messages/controller.nim
- src/app/modules/main/chat_section/chat_content/messages/io_interface.nim
- src/app/modules/main/chat_section/chat_content/messages/module.nim
- src/app_service/service/message/async_tasks.nim
- src/app_service/service/message/service.nim
Closing: #10231
The root cause of this issue is that the get chat messages and get pinned messages RPC are bundled in the same async task. Get pinned messages RPC is really heavy and it would delay the get chat messages response.
There are 3 main changes in this PR:
1. Separate get chat messages and get pinned messages calls in two async tasks.
2. Optimise the get pinned messages calls. Now it's called only once when the channel gets initialised.
3. Optimise the get first unseen message calls. Now it's called only once when the channel gets initialised.
Chat messages
Pinned messages
First unseen message
`master` - light theme
this branch - dark theme
1. General channels loading time
https://user-images.githubusercontent.com/47811206/231709228-aee6ee2a-0368-4e8f-b06e-87d121469fb1.mov
2. …
> perf(ChatLoadingTime): Separate get chat messages and get pinned messages in different tasks

- ui/imports/shared/views/chat/SimplifiedMessageView.qml
Close #10297
Remove stripping html tags from base AC message
> fix(ActivityCenter): Fix displaying mention as a tag in AC

- src/app/modules/main/wallet_section/accounts/model.nim
- src/app/modules/main/wallet_section/accounts/view.nim
- ui/imports/shared/controls/LoadingTokenDelegate.qml
- ui/imports/shared/controls/TransactionDelegate.qml
fix(@desktop/wallet): Wallet: user can click on dummy loading items from activity-history and open an empty transaction view
fixes #10083
Make List items non interactive when loading,for 
1. Assets List
2. Transactions list
Assets and Transactions view
https://user-images.githubusercontent.com/60327365/230599408-30475912-95b9-4c11-ba55-968a08a44a46.mov
https://user-images.githubusercontent.com/60327365/230599434-79f4e458-0bad-4e5c-bbcc-767a76ebe6ed.mov
> fix(@desktop/wallet): Wallet: user can click on dummy loading items from activity-history and open an empty transaction view

- test/ui-test/src/screens/SettingsScreen.py
Fixes https://github.com/status-im/status-desktop/issues/10350
Remove hover action from back up seed phrase test because it was failing to me. The test itself passed without this hovering thing so i decided to remove it for now
> test(tst_mainSettingsSection): remove hover action

- Makefile
Fix #10349
- move StatusQ to order-only-dependencies of the app
- hide StatusQ build output
> fix(Makefile): Move StatusQ to order-only-dependencies of the app

- src/app/modules/main/chat_section/controller.nim
- src/app/modules/main/chat_section/io_interface.nim
- src/app/modules/main/chat_section/module.nim
- src/app_service/service/chat/service.nim
Fixes #10313
There were a couple of small issues.
First, we didn't call the function to calculate the highlight on new messages. Secondly, the calculation was bugged because the category wasn't saved correctly in the channelGroup update.
> fix(category): fix category highlight calculation

- ci/Jenkinsfile.linux
- ci/Jenkinsfile.macos
- ci/Jenkinsfile.tests-e2e
- ci/Jenkinsfile.windows
This way we prevent situation in which a developer or QA engineer runs a custom job with adjusted parameters, and then all following jobs use those modified parameters implicitly. The more sane behavior is to always revert to defaults for PR builds, but remember last used parameters for non-PR builds.
Also added some missing options and comments for other jobs.
> ci: force default Squish params for PR jobs

- ui/app/AppLayouts/Chat/views/ChatColumnView.qml
- ui/app/AppLayouts/Chat/views/ChatContentView.qml
fixes: #10378
wraps `contextMenu` and `chatInput` into Loader, see: https://github.com/status-im/status-desktop/pull/10343#issuecomment-1515103756
Please note that this solution serves as a temporary workaround and
comes with variety of limitations, particulary concerning the chat
input state. For instance, the reply area is not retained when switching
between chats.
Ideally the root cause, which is the high memory consumption of both
`StatusChatInput` and `MessageContextMenuView`, should be fixed. Once
this issue is addressed, the current workaround can be reverted.
> fix(chat): wrap `contextMenu` and `chatInput` into Loader

- src/app/modules/startup/controller.nim
- src/app_service/service/accounts/service.nim
Fixes #10352
Adds a 1 second timer before re-encrypting, to make sure the loading screen is shown before it starts, since it can freeze.
Do note that this is on top of the release branch. I'll cherry-pick on master once it is merged.
I have not tested with an actual big re-encryption yet, but I could reproduce the issue with a `sleep` and the timer fixed the freeze.
I'll test later on Windows.
> fix(re-encryption): make sure loading screen is shown when re-encrypting

- ui/StatusQ/src/StatusQ/Components/StatusChatListItem.qml
Fixes the mute icon overlapping the badges
Partly fixes (the UI issue): #10345
StatusChatListItem
> fix(StatusChatListItem): fix mute icon overlapping badges

- src/app/modules/main/chat_section/module.nim
Fixes: #10294
Shows emoji for notifications with stickers instead of placeholder text
OS Notifications
> fix(os-notifications): Display image emoji for sticker in notification

- src/app/modules/main/wallet_section/transactions/view.nim
- src/app_service/service/contacts/async_tasks.nim
- ui/StatusQ/src/StatusQ/Core/Theme/StatusDarkTheme.qml
- ui/StatusQ/src/StatusQ/Core/Theme/StatusLightTheme.qml
- ui/StatusQ/src/StatusQ/Core/Theme/ThemePalette.qml
- ui/app/AppLayouts/Profile/controls/WalletAccountDelegate.qml
- ui/app/AppLayouts/Profile/views/wallet/MainView.qml
- ui/app/AppLayouts/Wallet/views/LeftTabView.qml
- ui/imports/shared/controls/ClearButton.qml
- ui/imports/shared/controls/SavedAddressListItem.qml
- ui/imports/shared/controls/SearchBoxWithRightIcon.qml
- ui/imports/shared/controls/TokenBalancePerChainDelegate.qml
- ui/imports/shared/controls/WalletAccountListItem.qml
- ui/imports/shared/panels/StatusAssetSelector.qml
- ui/imports/shared/popups/SendModal.qml
- ui/imports/shared/stores/TransactionStore.qml
- ui/imports/shared/views/RecipientView.qml
- ui/imports/shared/views/TabAddressSelectorView.qml
- ui/imports/shared/views/TokenListView.qml
fixes #10344, #10321, #10320
IMplements brlow features/bugs:
 Magnify in search should be correct size and joint to  the list
SendModal
https://user-images.githubusercontent.com/60327365/233621104-7a60e7f6-58d4-473b-ac6f-91adb33dc727.mov
> feat(@desktop/wallet): Wallet -> Send: polish Send/Bridge Modals

- ui/StatusQ/src/StatusQ/Components/StatusContactRequestsIndicatorListItem.qml
- ui/StatusQ/src/StatusQ/Components/StatusSyncDeviceDelegate.qml
- ui/StatusQ/src/StatusQ/Core/LocaleUtils.qml
- ui/app/AppLayouts/Profile/controls/WalletNetworkDelegate.qml
- ui/app/AppLayouts/Profile/views/EnsListView.qml
- ui/app/AppLayouts/Profile/views/MessagingView.qml
- ui/app/AppLayouts/Profile/views/keycard/MainView.qml
- ui/app/AppLayouts/Profile/views/wallet/MainView.qml
- ui/app/AppLayouts/Wallet/popups/CryptoServicesModal.qml
- ui/imports/shared/status/StatusSettingsLineButton.qml
- prevent QML `int` overflow
- use `LocaleUtils.formatRelativeTimestamp()` to perform the timestamp
formatting
- separate commit for the next/chevron icons
Fixes https://github.com/status-im/status-desktop/issues/10412
Settings/Syncing
> fix: device sync timestamp is wrong

- vendor/DOtherSide/lib/src/DOtherSide.cpp
Close #10332
Solution found by @alexjbam, discussion [here](https://github.com/status-im/status-desktop/issues/10332#issuecomment-1519850306)
DOtherSide
> Fix(DOtherSide): Exclude threaded renderer all darwin architectures

- Makefile
- ui/StatusQ/CMakeLists.txt
- ui/StatusQ/src/statusq.qrc
Makefile:
- silent `StatusQ` build output
- silent `QrCodeGenerator` build output
- silent `StatusQ` cmake warnings
- `clean` command for `DOtherSide` and `status-go`
Other:
- silent `SortFilterProxyModel` and `qzxing` warnings
- removed duplication in `statusq.qrc`
Makefile, build system
> fix(makefile): Bugfixes and minor improvements

- ui/StatusQ/src/StatusQ/Controls/StatusImageCrop.qml
- ui/app/AppLayouts/Chat/controls/community/CommunityBannerPicker.qml
- ui/app/AppLayouts/Chat/controls/community/CommunityLogoPicker.qml
- ui/app/AppLayouts/Chat/panels/communities/CommunityOverviewSettingsPanel.qml
- ui/imports/shared/panels/EditCroppedImagePanel.qml
- move the add/edit FAB icon to the topright corner as designed
- prepare UI changes for being able to delete banner/logo (missing impl in status-go)
Fixes: #9680
Community logo/banner picker
> fix: community logo/banner edit icon fixes

- ui/imports/shared/popups/SendModal.qml
- ui/imports/shared/stores/NetworkConnectionStore.qml
When a path is shown on goreli and I disable it , it still shows the path to Goreli on simple view
fixes #10393
Fixes the bug of disabled chain not added to list of disabled chains
SendModal
Uploading Screen Recording 2023-04-25 at 9.50.49 AM.mov…
> fix(@desktop/wallet): Disabled network still shows in valid path

- ui/imports/utils/Constants.qml
Closes #10120 
Onboarding: prevent user to create display names with whitespaces in the beginning or end
Onboarding
https://user-images.githubusercontent.com/31625338/234036903-9b118bb4-a028-4d43-a46f-b00b096236fe.mov
> [onboarding]: forbid display name whitespaces on beggining and end

- Makefile
- ci/Jenkinsfile.macos
- scripts/notarize-macos-pkg.sh
Notarization has been taking longer recently and it times out.
> macos: bump notarization retry limit from 20 to 40

- ui/StatusQ/src/StatusQ/Components/StatusCommunityCard.qml
- ui/StatusQ/src/StatusQ/Components/StatusContactVerificationIcons.qml
- ui/StatusQ/src/StatusQ/Components/private/statusMessage/StatusImageMessage.qml
- ui/StatusQ/src/StatusQ/Controls/StatusImageCrop.qml
- ui/StatusQ/src/StatusQ/Controls/StatusImageSelector.qml
- ui/app/AppLayouts/Browser/views/BrowserWebEngineView.qml
- ui/app/AppLayouts/Chat/panels/ChatRequestMessagePanel.qml
- ui/app/AppLayouts/Chat/popups/ChooseBrowserPopup.qml
- ui/app/AppLayouts/Chat/views/communities/CommunityWelcomeSettingsView.qml
- ui/app/AppLayouts/Onboarding/views/AllowNotificationsView.qml
- ui/app/AppLayouts/Onboarding/views/InsertDetailsView.qml
- ui/app/AppLayouts/Onboarding/views/KeysMainView.qml
- ui/app/AppLayouts/Onboarding/views/TouchIDAuthView.qml
- ui/app/AppLayouts/Onboarding/views/WelcomeView.qml
- ui/app/AppLayouts/Profile/popups/backupseed/Acknowledgements.qml
- ui/app/AppLayouts/Profile/popups/setupsyncing/DisplaySyncCode.qml
- ui/app/AppLayouts/Profile/views/AboutView.qml
- ui/app/AppLayouts/Profile/views/CommunitiesView.qml
- ui/app/AppLayouts/Profile/views/EnsTermsAndConditionsView.qml
- ui/app/AppLayouts/Profile/views/EnsWelcomeView.qml
- ui/app/AppLayouts/Profile/views/keycard/MainView.qml
- ui/app/AppLayouts/Wallet/addaccount/states/ConfirmAddingNewMasterKey.qml
- ui/app/AppLayouts/Wallet/controls/CollectiblesHeader.qml
- ui/app/AppLayouts/Wallet/views/LoadingGraphView.qml
- ui/app/mainui/panels/DropAreaPanel.qml
- ui/imports/shared/controls/chat/ProfileHeader.qml
- ui/imports/shared/status/StatusChatImageLoader.qml
- ui/imports/shared/status/StatusChatInputImageArea.qml
- ui/imports/shared/views/chat/LinksMessageView.qml
for everything that's not a user interface element, esp. for static/big images or chat/message elements which get served locally anyway from status-go
Iterates #10339
Reduce RAM usage by _not_ caching non-UI interface elements
> fix: reduce Image cache

- src/app/modules/main/module.nim
Fixes #10428
The issue above happened when you double click on a chat section. It causes the fetch to happen twice, which is wasteful, but also causes the model to get reset while it's being processed, thus creating the crash.
The fix here is to not signal that we are changing section if we are trying to switch to the section which is already active (makes sense ofc)
> fix(main/module): don't signal a section switch if it's the same section

- src/app_service/common/conversion.nim
- src/app_service/service/contacts/async_tasks.nim
- src/app_service/service/contacts/service.nim
- ui/app/AppLayouts/Chat/panels/InlineSelectorPanel.qml
- ui/app/AppLayouts/Chat/views/MembersSelectorView.qml
Fixes https://github.com/status-im/status-desktop/issues/10318
Relates to:
- https://github.com/status-im/status-desktop/pull/7420
- https://github.com/status-im/status-desktop/pull/9996
- https://github.com/status-im/status-desktop/pull/8659
I've consolidated all the work we've done here and here's the solution.
1. We agreed with @John-44 to support "editing", not just "pasting"
2. What's supported:
- ENS name
- compressed keys
- uncompressed key
- link with one of above
3. Any leading and ending spaces are trimmed
4. Pasting processed immediately, editing has a heuristic delay of 500ms
5. Compressed key length is checked
6. Compressed key is checked to start with `zQ3sh`
7. Fixed `asyncRequestContactInfoTask` which led to a crush
8. `getContactById` checks the decompressed key for …
> fix: Fix and rework "start chat" text field input

- src/app_service/service/language/service.nim
- ui/app/AppLayouts/Profile/views/LanguageView.qml
- vendor/DOtherSide/lib/src/DOtherSide.cpp
disable retranslation, display a confirmation dialog and apply the language change after app restart
rationale: the way the retranslation works internally is that it forces reevaluation of _all_ QML bindings which:
- might lead to crashes (immediately or later)
- lots of warnings printed to console, some bindings can get broken as a result
- not all UI is correctly retranslated on the fly (we have lots of places where we assign the text imperatively via JS code), so these wouldn't appear translated before app restart anyway
Fixes #7823
Settings/Language
For comparison, this is when changing the language on-the-fly, before and after restart (parts of the app don't get retranslated correctly)
> fix(Settings/LanguageView): do not change language on the fly

- src/app/modules/main/activity_center/model.nim
- src/app/modules/main/activity_center/module.nim
Close #10455
AC notification can have nil message, but with recent changes this caused segfault 
ActivityCenter
> fix(ActivityCenter): Workaround for nil message

- ui/app/AppLayouts/Chat/views/ChatColumnView.qml
- ui/app/AppLayouts/Chat/views/ChatContentView.qml
the StatusChatInput (among other things) was disabled due to wrong `activeChatType` being passed down to `ChatContentView` which does all sorts of checks whether we are allowed to chat with that contact
The `root.activeChatType` no longer reflects the chat that we are going to activate (probably due to the extensive use of `Loader`s)
(plus remove some dead code)
Fixes: #10463
Unbreaks 1-1 chats
ChatColumnView/ChatContentView
> fix(ChatColumnView): unbreak 1-1 chats

- src/app/global/local_account_sensitive_settings.nim
- test/ui-test/src/drivers/SquishDriverVerification.py
- test/ui-test/src/screens/SettingsScreen.py
- test/ui-test/src/screens/StatusCommunityPortalScreen.py
- test/ui-test/testSuites/global_shared/steps/settingsSteps.py
- test/ui-test/testSuites/suite_communities/shared/scripts/community_portal_names.py
- test/ui-test/testSuites/suite_communities/shared/steps/communitySteps.py
- test/ui-test/testSuites/suite_communities/tst_communityPermissions/test.feature
- ui/app/AppLayouts/Chat/stores/RootStore.qml
- ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
- ui/app/AppLayouts/CommunitiesPortal/CommunitiesPortalLayout.qml
- ui/app/AppLayouts/Profile/stores/AdvancedStore.qml
- ui/app/AppLayouts/Profile/views/AdvancedView.qml
- ui/imports/shared/panels/CommunityBanner.qml
Closes #10115
Settings removed community permissions, tokens, airdrop and discord import options - should be enabled by default
Also:
test(suite_communities): Fixed community related tests
- A new intermediate popup is now displayed when user clicks on `Create New Community` button from `Community Portal`.
- Reformulated `tst_communityPermissions` since now it is a default option without the need of activating it from experimental feature's section.
Settings
https://user-images.githubusercontent.com/31625338/234640392-1fdfc26e-8b14-4ccc-9c6a-0e9a2e2f08fc.mov
> (settings): removed community permissions,tokens,airdrop and discord options

- ui/app/AppLayouts/Chat/ChatLayout.qml
- ui/app/AppLayouts/Chat/views/ChatView.qml
- ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
- ui/app/AppLayouts/CommunitiesPortal/CommunitiesPortalLayout.qml
- ui/app/AppLayouts/CommunitiesPortal/popups/qmldir
- ui/app/AppLayouts/Profile/views/AdvancedView.qml
- ui/app/AppLayouts/Wallet/WalletLayout.qml
- ui/app/AppLayouts/Wallet/views/LeftTabView.qml
- ui/app/mainui/AppMain.qml
- ui/app/mainui/Popups.qml
- ui/imports/utils/Global.qml
- CommunitiesPortalLayout was the last piece still unconditionally loaded on startup -> fixed (this will further improve the startup speed)
- extract the `communitiesStore` into `AppMain` to be able to reuse it from other components
- move the import/create community dialogs to `Popups` (reusability)
- wrapped `EmojiPopup` in a loader too
- cleanup and remove some dead code, fix warnings
Iterates #6204
AppMain/Popups/CommunitiesPortalLayout
Portal + create community popup:
Portal + import community:
> perf(AppMain): wrap CommunitiesPortalLayout in a Loader

- ui/app/AppLayouts/Profile/panels/ProfileShowcasePanel.qml
- ui/app/AppLayouts/Profile/panels/ProfileSocialLinksPanel.qml
- ui/imports/shared/controls/ShapeRectangle.qml
- ui/imports/shared/controls/qmldir
- ui/imports/shared/views/HistoryView.qml
Issue: #10443
* Updated no activity text according to new designs
* Moved ShapeRectangle.qml to shared directory to be used in multiple places
Wallet activity view and Profile (usage of ShapeRectangle)
Design: 
App:
> feat(@desktop/activities): Updated no activity text style

- ui/StatusQ/src/StatusQ/Components/StatusMessage.qml
- ui/StatusQ/src/StatusQ/Components/private/qmldir
- ui/StatusQ/src/StatusQ/Components/private/statusMessage/StatusMessageImageAlbum.qml
- ui/StatusQ/src/StatusQ/Components/private/statusMessage/StatusMessageReply.qml
- ui/StatusQ/src/statusq.qrc
- ui/app/AppLayouts/Chat/views/ChatContentView.qml
- ui/imports/shared/status/StatusChatInput.qml
- ui/imports/shared/status/StatusChatInputReplyArea.qml
- ui/imports/shared/views/chat/MessageView.qml
Fixes: #9957
Adds implementation of albums in replies
ChatInput and Replies
> feat(image-album): Display album of images in replies

- src/app/modules/startup/module.nim
- ui/app/AppLayouts/Onboarding/views/InsertDetailsView.qml
- ui/app/AppLayouts/Profile/stores/ProfileStore.qml
- ui/imports/utils/Utils.qml
Fixes https://github.com/status-im/status-desktop/issues/10099
1. The profile image is visible when login after first onboarding
2. The identicon ring is visible during onboarding
3. Minor cleanup
Onboarding
https://user-images.githubusercontent.com/25482501/235351769-490f937f-4d0a-46fa-b93e-c8e532bcce51.mov
> fix(Onboarding): Image is visible after first onboard. Other minor fixes

- ui/app/AppLayouts/Wallet/addaccount/panels/WatchOnlyAddressSection.qml
Fixes https://github.com/status-im/status-desktop/issues/10513. It was confirmed with @benjthayer to change the placeholder to the one in figma https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=12272-280578&t=QIlxb9Ht7sPwTp3S-4
Add account form
> fix(wallet): change placeholder for watch-only account
