status-im/status-desktop

Makefile

That one is too aggressive by trying to install system packages and
seems only relevant for developing status-go itself, not just building
the library like we do here.

Makefile: don't run the "setup-dev" target in vendor/status-go

---

ui/app/AppLayouts/Chat/ChatLayout.qml

Fixes #77 
The scroll in the chat list was bugged because scrollToBottom sucks, so instead I use the "follow the last item technique", which works well.
I also made it so that it only scrolls to the bottom if the scroll is at bottom, i.e. if you scroll up to look at older texts, you won't get scrolled down. It will only keep scrolling back down if you go back down.
Finally, I fixed the hardcoded height of the chat items. Now, they scale depending on the height of the message.

Fix chat list scroll + chat item height

---

src/app/onboarding/view.nim
src/app/profile/profileView.nim
src/models/accounts.nim
src/nim_status_client.nim
src/status/accounts.nim
src/status/types.nim
ui/onboarding/GenKey.qml
ui/onboarding/OnboardingMain.qml

Previously, the displayed key for generated accounts was displaying the public key of the account, and not the whisper account. This has been fixed.
Futher work has gone in to strongly-typing a lot of the responses from status-go and removed a lot of the manual string parsing.
Simplified types and type-conversions by using the `nim-serialization` library.
Removed the `subaccounts` property from the accounts model as it was no longer being used.

fix: change onboarding account to whisper key

---

src/app/onboarding/core.nim
src/app/profile/core.nim
src/app/wallet/core.nim

Uninherited `ProfileController` and `OnboardingController` from `SignalSubscriber` as they were not listening for signals from the node.
Added an `onSignal` dummy method in `WalletController` to make the compiler happy. The main app is assuming this is a `SignalSubscriber` but it is unclear if it being used (maybe it's a WIP).

fix: remove `onSignal` not overridden warnings

---

src/models/accounts.nim
src/models/chat.nim
src/status/accounts.nim
src/status/chat.nim

Fixes #60
Makes it possible to get the last 20 messages from a channel when joining that channel.
Known issue: the messages will **not** be ordered. It needs a small adjustment to how we get new messages.
Just showing that all of this was on load:

feat: get last 20 messages of a channel when joining the chat

---

ui/onboarding/GenKey.qml

Selecting a generated account other than the first one in the list would always use the first generated account.
Uncomment commented-out code that updates the selected index in the view.

fix: Inability to select generated account

---

src/app/login/core.nim
src/app/login/view.nim
src/app/onboarding/core.nim
src/models/accounts.nim
src/models/profile.nim
src/nim_status_client.nim
src/signals/core.nim
src/signals/types.nim
src/status/accounts.nim
src/status/libstatus.nim
src/status/types.nim
ui/onboarding/GenKey.qml
ui/onboarding/Intro.qml
ui/onboarding/Login.qml
ui/onboarding/OnboardingMain.qml

Update nim-stew to latest version.
Change references to Address to the common type Account to prevent repeating of types (later this should be changed in to a model -- a model that is just a very barebones non-functional shell).
Distinguish between unknown and unhandled signals.
Pass signals through to subscribers regardless if the signal type is known (in case the SignalSubscriber handles it with string comparison or other).
Update serialization as much as possible
Latest nim-stew updates allow inheritance, however this seems to break with enums
Remove onboarding and login models completely
NOTE: generating a new account shows chat counts, but logging in with existing account does not.
NOTE: Since the login and onboarding models have been removed, the models for these are really in …

feat: add login functionality

---

src/status/chat.nim

In ebd29d9ffd6d1981160c82a26d35be602b9231a3 we've introduced a regression where
the channel list didn't expose the chat's chatType to the view, causing 1-on-1 chats
identicons to break.
This commit reintrodruces the chatType to the view.

fix(chat): ensure chatType is set properly

---

ui/app/AppLayouts/Chat/ChatColumn/TopBar.qml
ui/app/AppLayouts/Chat/ContactsColumn/Channel.qml
ui/app/AppLayouts/Chat/components/ChannelIcon.qml
ui/app/AppLayouts/Chat/components/qmldir

This component renders channel identicons based on the chat type
and channel name and will render a user identicon in case of a one-on-one
chat.
One-on-one chats still look broken in the contacts column until #247 has landed.

feat(ui): introduce `ChannelIcon` component

---

src/app/login/core.nim
src/app/login/view.nim
src/app/onboarding/core.nim
src/app/onboarding/view.nim
src/status/accounts.nim
ui/onboarding/ExistingKey.qml
ui/onboarding/GenKey.qml
ui/onboarding/Login.qml

- fix: Change displayed login key to whisper public key (starts with 0x04)
- fix: remove key displayed on login accounts as this value is not passed to use from status-go's openAccounts
- feat: add selected account view when entering password for login and generating an account (same UI as importing a key)

fix: small onboarding/login fixes and feats

---

Makefile
README.md
config.nims
nim.cfg
src/nim_status_client.nim
src/nim_status_client.nim.cfg

- unify the "build-..." targets
- enable a debug build by default, to simplify development
- bump vendor/DOtherSide
- avoid DOtherSide checks for docs/tests-specific tools like Doxygen
- switch to an in-place build for DOtherSide
- silence the DOtherSide build when V=0, make it more verbose with V=1
- don't delete checked out submodules in the "clean" target
- update build instructions in the README
- centralise Nim compiler options in a top-level "config.nims" (except `-d:debug` which needs to be on the command line)

build system refactoring

---

src/app/chat/core.nim
src/app/chat/view.nim
src/app/chat/views/message_list.nim
src/status/chat.nim
src/status/chat/chat_message.nim
ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml
ui/app/AppLayouts/Chat/ChatColumn/Message.qml

- Use a single message list instead of a message list per channel
- load messages on channel switch.
- Use section identifiers as a way to identify if messages have been sent by the current user (no need to modify the model with `repeatMessageInfo`)

Using section identifiers and performance improvements over sorting

---

ui/app/AppLayouts/Chat/components/ProfilePopup.qml
ui/app/AppLayouts/Chat/components/PublicChatPopup.qml
ui/app/AppLayouts/Wallet/Components/AddAccountWithSeed.qml
ui/shared/ModalPopup.qml

Similar to its `footer` content, ModalPopup can now receive header components
allowing consumers to design the header part of the modal to their likings.
Usage:
```
ModalPopup {
id: popup
header: Item {
...
}
...
}
```
The header section will take the height of the root element of the substree
passed to `header`

feat(ui/shared): allow  ModalPopup to receive header components

---

ui/app/AppLayouts/Chat/components/ProfilePopup.qml

This commit extends the profile popup to align more with the application
designs. There's still work left to be done such as showing/hiding the
qrcode view or copying data to the clipboard.
The profilepopup also relies on context data at the moment and should rather
receive its data via the newly introduced `getContractByID()` API proposed in
https://github.com/status-im/status-go/pull/1987

refactor(ui/ProfilePopup): make use of newly introduced header content

---

ui/shared/RoundImage.qml

The border color of `RoundedColor` is way darker than channel and chat icons in
other places of the application.
This commit aligns it so it's the same everywhere

ui: fine-tune rounded icon border

---

ui/app/AppLayouts/Chat/components/PrivateChatPopup.qml
ui/app/AppLayouts/Wallet/AccountSettingsModal.qml
ui/app/AppLayouts/Wallet/TokenSettingsModal.qml
ui/app/AppLayouts/Wallet/components/AddAccountWithPrivateKey.qml
ui/app/AppLayouts/Wallet/components/AddAccountWithSeed.qml
ui/app/AppLayouts/Wallet/components/AddWatchOnlyAccount.qml
ui/app/AppLayouts/Wallet/components/GenerateAccountModal.qml
ui/imports/Utils.qml
ui/imports/qmldir
ui/nim-status-client.pro
ui/shared/Input.qml
ui/shared/StyledTextArea.qml

Adds the `validationError` prop on Input and StyledTextArea to show a message on the field when there is an error
Add validation to add private chat and the wallet forms.
Known issue: if you have a validation then fix it and press enter, the error stays even though it was removed from memory. The problem is that QT "freezes" when we call the Nim function so it doesn't re-render. We have that problem at a couple of places where we'd need loading states.

Add form validation

---

ui/app/AppLayouts/Chat/ChatLayout.qml
ui/app/AppLayouts/Profile/ProfileLayout.qml
ui/app/AppLayouts/Wallet/WalletLayout.qml
ui/app/AppMain.qml
ui/main.qml

Branched on top of: https://github.com/status-im/nim-status-client/pull/415
Adds the Settings element that enables to keep on disk some cool settings. Right now, I used it to keep the state of the SplitViews so that if you change the size of the split, it's gonna reopen to that state (you need to close the app with the X at the top, not with CTRL+C in the terminal, becuase otherwise the `onDestruction` events are not triggered)
This can be used for the window size, the language, etc.

feat: enable saving app settings like the SplitView state

---

ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml
ui/app/AppLayouts/Chat/ChatLayout.qml
ui/app/AppLayouts/Chat/ContactsColumn.qml
ui/app/AppLayouts/Chat/ContactsColumn/Channel.qml
ui/app/AppLayouts/Chat/ContactsColumn/ChannelList.qml
ui/app/AppLayouts/Node/NodeLayout.qml
ui/app/AppLayouts/Profile/LeftTab.qml
ui/app/AppLayouts/Profile/ProfileLayout.qml
ui/app/AppLayouts/Wallet/LeftTab.qml
ui/app/AppLayouts/Wallet/WalletLayout.qml
ui/app/AppMain.qml
ui/imports/Theme.qml
ui/main.qml
ui/nim-status-client.pro
ui/shared/SplitViewHandle.qml
ui/shared/qmldir

Ups the version of QtControls to 2.13. This means that SplitViews needed to be fixed/changed.
One big problem was  that the new handle property changed and now, if we put a width of `1` on the handle, it's not usable. It is too small to grasp.
That's why, for now, I put it as `2` px large. I tried using a MouseArea or even putting the rectangle inside an Item and the item being bigger, but if you put the `implicitWidth` bigger for the mouse area to be bigger, it creates a margin that I wasn't able to fix.
Anyway, I put the handle in it's own component, so it's easy to change and I also added a hover and on click effect to make it obvious that you can resize.

chore: up import version and fix SplitViews

---

ui/app/AppLayouts/Chat/components/ProfilePopup.qml
ui/app/AppLayouts/Profile/LeftTab.qml
ui/app/AppLayouts/Profile/LeftTab/Menu.qml

Fix the profile buttons.
It's the old behaviour, so the split view doesn't work well in the profile, but it needs to be redesigned and refactored. Tab buttons suck when trying to lay them out

Fix the profile buttons

---

Makefile
ci/Dockerfile
ci/Jenkinsfile.linux
ci/Jenkinsfile.macos
ci/README.md
ci/lib.groovy
docs/README.md
scripts/sign-macos-pkg.sh

This implements a CI setup for Jenkins:
* Adds `ci/Dockerfile` for creating `statusteam/nim-status-client-build:latest` used in builds
* Adds `ci/Jenkinsfile.linux` and `ci/Jenkinsfile.macos` for respective platforms
* Simplifies MacOS signing by adding `scripts/sign-macos-pkg.sh` script
* Makes `Makefile` use `scripts/sign-macos-pkg.sh` to make the DMG
* Makes `APPIMAGE` and `DMG` in `Makefile` modifiable by environment
* Adds `--passL:"-headerpad_max_install_names"` to `NIM_PARAMS` to fix MacOS signing issues
You can find the jobs here: https://ci.status.im/job/nim-status-client/
In the future I might replace the Container used for linux with Nix.

add Jenkinsfile and Dockerfile for CI

---

ci/Jenkinsfile.linux
ci/Jenkinsfile.macos

Fix for `QTDIR` in CI to include the compiler subfolder due to dfef4374f65bf2a8f29a8ac9e73649f9731b2c1b.
Successful builds:
* https://ci.status.im/job/nim-status-client/job/linux/job/fix-qt-in-ci/
* https://ci.status.im/job/nim-status-client/job/macos/job/fix-qt-in-ci/

fix QTDIR paths for CI

---

Makefile
config.nims

Replaces #82, which in any case is out-of-date re: the current state of this repo's Makefile.
Introduces the ability to build `nim_status_client.exe` directly on Windows, i.e. without needing to use Windows Subsystem for Linux or otherwise cross-compile on Linux.
Note: this commit does not introduce packaging or code signing for the Windows build as those pieces are still a work in progress.
The `make` targets should be run in a Bash shell, e.g. in *Git Bash* as included in the installation of [Git for Windows][git-win].
[Microsoft Visual C++ Build Tools][ms-build] must be installed.
Qt's `MSVC 2017 64-bit` and `MinGW 7.3.0 64-bit` toolchains must both be installed, e.g. with the Qt Online Installer tool.
CMake needs to be installed; it is available via the Qt Online Installer tool under …

build: enhance build system so that it can run directly on Windows

---

Makefile
src/status/libstatus/accounts.nim
src/status/libstatus/accounts/constants.nim

If the environment variable `NIM_STATUS_CLIENT_DEV` is not empty then the `./data` dir is created/used relative to the current working directory, as was always the case prior to the changes introduced in this commit.
`NIM_STATUS_CLIENT_DEV` is set to `t` when doing `make run`. To get the production behavior in development do:
```
$ NIM_STATUS_CLIENT_DEV="" make run
```
or on Windows in a Bash shell:
```
$ NIM_STATUS_CLIENT_DEV="" mingw32-make run
```
Closes #391
---
Per @zah's [comment](https://github.com/status-im/nim-status-client/issues/391#issuecomment-648006108) we can/should refine this at some point.

refactor: store data folder in OS appropriate location

---

ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml
ui/app/AppLayouts/Chat/ChatColumn/Message.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChannelIdentifier.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatReply.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatText.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatTime.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/CompactMessage.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/DateGroup.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ImageMessage.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/MessageMouseArea.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/NormalMessage.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/SentMessage.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/Sticker.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/UserImage.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/UsernameLabel.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/qmldir
ui/app/AppLayouts/Chat/ChatColumn/qmldir
ui/app/AppLayouts/Profile/ProfileLayout.qml
ui/app/AppLayouts/Profile/Sections/AdvancedContainer.qml
ui/app/AppLayouts/Profile/Sections/HelpContainer.qml
ui/imports/Utils.qml
ui/main.qml
ui/nim-status-client.pro

Adds a compact mode to the chat where everything is on the left side with full width.
I will add in another PR the compact mode for the Channel list, whihc should be simpler.
This includes a **massive** refactor of the Message component. The biggest points are that now, the different types of Messages are now Components that are loaded using a `Loader`, meaning that there should be a small improvement in memory usage, since before, the different types were all loaded in momeory and just invisible.
The other big point is that all parts of the message were split in components, first because I needed to reuse them for both the NormalMessage (old bubble one) and the CompactMessage and also because it's cleaner and causes less conflicts.
To switch to compact mode, just go in Profile > Advanced …

Add Chat compact mode

---

src/app/chat/views/sticker_pack_list.nim
src/app/profile/core.nim
src/app/profile/view.nim
src/signals/messages.nim
src/status/accounts.nim
src/status/devices.nim
src/status/libstatus/accounts.nim
src/status/libstatus/accounts/constants.nim
src/status/libstatus/contracts.nim
src/status/libstatus/settings.nim
src/status/libstatus/stickers.nim
src/status/libstatus/types.nim
src/status/libstatus/utils.nim
src/status/libstatus/wallet.nim
src/status/status.nim
src/status/wallet.nim
src/status/wallet/collectibles.nim
ui/app/AppLayouts/Chat/ChatColumn/ChatInput.qml
ui/app/AppLayouts/Profile/Sections/AdvancedContainer.qml

Fixes #555 
Allow switching to Ropsten by flipping a toggle switch in Profile > Advanced settings.
When switching networks, note that installed stickers will be uninstalled, and recent stickers will be removed. Sticker packs can be reinstalled after login. Purchased sticker packs will not need to be re-purchased, but will need to be re-installed.
Mailserver fleet information will **not** be updated. This can be controlled by a separate (undeveloped yet) setting.
**NOTE**
This PR is based off of https://github.com/status-im/nim-status-client/pull/550, and should be rebased only after it is merged. 
https://github.com/status-im/nim-status-client/pull/545 > https://github.com/status-im/nim-status-client/pull/550 > This PR

feat: Enable switching to testnet

---

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/CompactMessage.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ImageMessage.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/NormalMessage.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/RectangleCorner.qml
ui/nim-status-client.pro

Also extracts the ReactangleCorner that hides one of the corners of the chat box  to a component
Note: we can reduce the size of the image if we want. Also, one thing we might want to experiment later is putting the images side-by-side

Show images in compact

---

src/status/chat.nim
src/status/libstatus/stickers.nim
src/status/libstatus/types.nim

To test this, comment `wallet.init()` in nim_status_client.nim

fix: capture RpcExceptions generated by stickers that would not allow login

---

Makefile
config.nims
src/nim_status_client.nim
src/nim_windows_launcher.nim
windows-install.txt

Implement a `pkg-windows` target that ultimately results in `Status.zip` being written to `pkg/`.
Note: this commit does not introduce code signing for the Windows build since that piece is still a work in progress.
`pkg-windows` creates a portable folder in `tmp/windows/dist` with the help of [`windeployqt`][windeployqt], which copies the needed portions of Qt into the folder.
Since DLL resolution is relatively inflexible, a launcher `Status.exe` is created at the top-level of the folder; the launcher opens `bin/Status.exe` while adding the portable folder's `bin/` to the `PATH`, allowing `bin/Status.exe` to resolve the DLLs in that folder.
A few additional tools need to be installed (e.g. with [scoop][scoop]) and availble in `PATH`:
* 7-zip
* dos2unix (provides unix2dos)
* findutils
* …

build: implement packaging steps for the Windows build

---

src/app/chat/view.nim
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatReply.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatText.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/MessageMouseArea.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/NormalMessage.qml

Fixes #605 
- Fix text overflowing out of the balloon
- This was caused by the `white-space` css property. Without `pre`, using `SHIFT+ENTER`, there were no line breaks, but with `pre`, the auto wrap didn't work. The solution was switching to `pre-wrap`.
- Fix replies being squished
- Happened when the reply was smaller than the message being replied to. 
- Now it takes the bigger text as the width
- Fix text selection
- Was caused by the MouseArea being on top, eating all the click
- Putting it right under the text fixes it, but broke the link clicking, so I moved the link clicking to the Text itself. So the MouseArea only handles right clciks.

Fix message UI issues

---

src/app/chat/views/channels_list.nim
src/app/chat/views/message_list.nim
src/signals/messages.nim
src/status/chat/message.nim
ui/app/AppLayouts/Chat/ChatColumn/Message.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatImage.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatReply.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatTime.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/CompactMessage.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/NormalMessage.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/SentMessage.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/UserImage.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/UsernameLabel.qml
ui/app/AppLayouts/Chat/ContactsColumn/Channel.qml
ui/app/AppLayouts/Chat/ContactsColumn/ChannelList.qml
ui/imports/Constants.qml

This displays images on messages of contentType 7 (Images).
The following behaviors were added:
- In the channel list, if the last message is of image type, the word "Image" will be displayed (like in mobile)
- Images will have a max width of 250 with a preserveAspectFit to keep proportionality, and with no minimum width. MessagBox will grow depending on the width of the image. 
- Replies will resize the image to a max of 50x50

feat: display messages with an image contenttype

---

src/app/chat/view.nim

Replaces https://github.com/status-im/nim-status-client/pull/642
Fixes #286
@richard-ramos please check if it might break something. I know you changed it a bit recently.
Basically, I think that call doesn't belong there, that signal should only be called when we change the active channel, which we do above in the code. Otherwise, we end up scrolling down with force on new messages

fix: fix chat list scrolling down when user was looking up the chats

---

src/app/wallet/views/account_list.nim
ui/app/AppLayouts/Profile/Sections/LanguageContainer.qml
ui/app/AppLayouts/Wallet/AccountSettingsModal.qml
ui/app/AppLayouts/Wallet/SendModal.qml
ui/app/AppLayouts/Wallet/components/AddAccountWithPrivateKey.qml
ui/app/AppLayouts/Wallet/components/AddAccountWithSeed.qml
ui/app/AppLayouts/Wallet/components/AddWatchOnlyAccount.qml
ui/app/AppLayouts/Wallet/components/GenerateAccountModal.qml
ui/app/AppLayouts/Wallet/components/SendModalContent.qml
ui/imports/Themes/DarkTheme.qml
ui/imports/Themes/LightTheme.qml
ui/nim-status-client.pro
ui/shared/AccountSelector.qml
ui/shared/ColorSelector.qml
ui/shared/Select.qml

Fixes #670.
Component spec based on https://www.notion.so/emizzle/Wallet-transaction-components-2003b78a8d0d41c4ab3d21eb2496fb20.
Changes the current Select shared component to a model databound component. This means we can bind directly to `QAbstractListModel`'s coming from Nim instead of needing manipulating the data in to javascript objects. The changes to the Select component will be used for the upcoming Asset selector shared component.

feat: Send transaction component -- Account selector

---

ui/app/AppLayouts/Wallet/components/SendModalContent.qml
ui/shared/AccountSelector.qml

Remove all `walletModel` references from the `AccountSelector` component, as the component should not be aware of the API's existence.
Pass currency to `AccountSelector` component.

fix: Remove walletModel reference from AccountSelector

---

src/app/chat/views/message_format.nim
ui/app/AppLayouts/Chat/ContactsColumn/Channel.qml

- Added a &nsbp; in front of paragraphs, otherwise the alignment property was ignored
- Enabled richformat for channel list to avoid emoji overlap in last message

fix: alignment of emojis

---

scripts/sign-macos-pkg.sh

We had an issue with iOS release signing due to this script not restoring fully the previous keychain list.
The issue was researched in: https://github.com/status-im/infra-ci/issues/22

fix MacOS signing script to restore original keychain list

---

src/app/wallet/view.nim
src/app/wallet/views/account_list.nim
ui/app/AppLayouts/Wallet/components/SendModalContent.qml
ui/shared/AssetAndAmountInput.qml
ui/shared/AssetSelector.qml

When tokens are added/removed, the asset list in the AssetAndAmountInput is updated.
The selected asset can be specified by the parent component which is needed for things like sticker market where we need to set SNT as the fixed token.
Improved the validation for the component:
- validate() can be called externally
- validation display is handled internally and messages can be customised
- validation error messages are handled by the Input component and validation UX is consistent with other tx components
1. Don't be alarmed at the amount of changes to the component. Most of it was just fixing of the spacing (from a mix of 2/4 spaces to complete 4 spaces).
2. The base branch is `feat/tx-comps/recipient-selector`. Hopefully that will get merged first.

fix/tx-comps: Update assets when tokens changed

---

ui/app/AppLayouts/Wallet/LeftTab.qml
ui/app/AppLayouts/Wallet/ReceiveModal.qml
ui/app/AppLayouts/Wallet/WalletHeader.qml
ui/nim-status-client.pro
ui/shared/AccountSelector.qml
ui/shared/Input.qml
ui/shared/StyledButton.qml
ui/shared/qmldir

Add receive modal in the wallet to show a QR code and address selector
Improve Input component to be able to show a Copy button that copies to clipboard
Improve AccountSelector modal to be able to not show details and fix eliding

feat: add receive modal

---

ui/app/AppLayouts/Wallet/ReceiveModal.qml
ui/app/AppLayouts/Wallet/SendModal.qml
ui/app/AppLayouts/Wallet/components/SendModalContent.qml
ui/imports/Utils.qml
ui/nim-status-client.pro
ui/shared/AccountSelector.qml
ui/shared/AssetAndAmountInput.qml
ui/shared/ContactSelector.qml
ui/shared/GasSelector.qml
ui/shared/LabelValueRow.qml
ui/shared/RecipientSelector.qml
ui/shared/Select.qml
ui/shared/TransactionPreview.qml

Fixes #675.
Adds a TransactionPreview component as per the spec https://www.notion.so/emizzle/Wallet-transaction-components-2003b78a8d0d41c4ab3d21eb2496fb20
- update ReceiveModal dropdown to match design
- long alias and account name support
- long name support in account selector
- strip all trailing zeros from displayed balances

feat/tx-comps: Add TransactionPreview component

---

ui/app/AppLayouts/Wallet/components/SendModalContent.qml
ui/nim-status-client.pro
ui/shared/GasSelector.qml

This commit fine-tunes the layout of the advanced modal input controls.
It also adds validation so that only numeric values are accepted as
gas price and gas limit values

chore: improve GasSelector Component

---

ui/app/AppLayouts/Chat/ContactsColumn/AddChat.qml
ui/app/AppLayouts/Wallet/components/AddAccount.qml
ui/shared/IconButton.qml

So far our `IconButton` hasn't been a proper button control which comes
with many downsides, such as:
- Some default button behaviours need to be simulated (e.g. `onClicked`)
- Any support built-in features for all controls in QML like `ToolTip` aren't can't be used
- There are probably accessibility aspects to it as well
We use the `IconButton` in many different places. Sometimes it doesn't
even act as a button, but just as an icon. I suggest we introduce a separate
`StatusIcon` component for that in future changes.
This commit turns the `IconButton` into a proper `RoundButton`, restoring
the control behaviour and features we get from QML.
This also required to expose the `icon` property as a `iconImg`,
because a `RoundButton` already comes with an `icon`.
On the other hand, we could …

refactor(IconButton): turn IconButton into proper button control

---

src/app/wallet/view.nim
src/app/wallet/views/account_list.nim

branched off of https://github.com/status-im/nim-status-client/pull/762
Saves the collectibles in the Wallet account so that when we switch between account and one collectible was already loaded, we don't reload again.

feat: save collectiblesList to WalletAccount

---

Makefile
src/app/chat/core.nim
src/app/chat/event_handling.nim
src/app/chat/signal_handling.nim
src/app/chat/view.nim
src/app/chat/views/message_list.nim
src/signals/core.nim
src/signals/messages.nim
src/signals/types.nim
src/status/chat.nim
src/status/chat/message.nim
src/status/libstatus/chat.nim
ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml
ui/app/AppLayouts/Chat/ChatColumn/Message.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatText.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/CompactMessage.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/EmojiReactions.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ImageMessage.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/NormalMessage.qml
ui/app/AppLayouts/Chat/components/EmojiReaction.qml
ui/app/AppLayouts/Chat/components/MessageContextMenu.qml
ui/nim-status-client.pro

Get emoji reactions and display them on the messages. Updates on add and retraction. Should work when loading new chats, but I couldn't test because of the status-go issue. See below for more details
Do note that there was no design for the desktop version of reactions, so some of the reactions look a bit odd, especially for images. Also, with bubbles, the reaction ends up on top of the date 🤷 
Known issue: status-go version has an issue with saveChat. This is a draft PR because we can't merge until status-go is fixed. It makes joining chats undoable.

feat: get and display emoji reactions in chat

---

src/app/profile/core.nim
src/app/profile/view.nim
src/nim_status_client.nim
src/status/libstatus/settings.nim
ui/app/AppLayouts/Profile/Sections/BackupSeedModal.qml
ui/nim-status-client.pro

Necessary cases are:
- Onboarding to show the list of 5 accounts
- After login in, I delete the Onboarding and Login views to clear their memory
- In QML when we show it to the user for the backup
- Change it to a Loader, so the component and its memory is cleaned when closed
- Before, the Profile view had the mnemonic in memory all the time, now we fetch it only when opening the modal
Let me know if you think I forgot a place where we store the mnemonic or password

refactor: never save mnemonic in memory unless totally necessary

---

src/app/chat/view.nim
src/status/chat.nim
src/status/libstatus/chat.nim

Also, selecting a channel with unread messages marks them as seen as well
Closes #738

fix(Chat): ensure new active channel messages are marked as seen

---

ui/app/AppLayouts/UIComponents/UIComponents.qml
ui/shared/status/StatusRoundButton.qml

As per discussion, there's no "primary" and "secondary" type in round buttons.
They just appear in different sizes (44x44, 40x40, 32x32). The size determines
their look & feel

fix(StatusRoundButton): fixes binding loop and removes type property

---

Makefile
config.nims

~~This shouldn't be merged yet because `vendor/status-go` in this branch currently points to a commit in open PR https://github.com/status-im/status-go/pull/2015.~~
~~Also, earlier today when testing this repo's `master` with `vendor/status-go` pointing to current HEAD of status-go I found that the application completely locks up when you try to join a chat. Note that problem is not connected to changes in this PR but builds with this branch have the same issue because https://github.com/status-im/status-go/pull/2015 is one commit ahead of current HEAD of status-go.~~
Good to go now!

build: dynamically link to status-go built as a shared library

---

ui/app/AppLayouts/Chat/ChatColumn/ChatInput.qml
ui/imports/Emoji.qml

Hey @emizzle @PascalPrecht @richard-ramos @iurimatias 
I've made a PR that fixes https://github.com/status-im/nim-status-client/issues/800 
Can you please review?
- typing the chars `:joy:` will be replaced with the corresponding emoji
- you can do this at any position in the text
- when you paste the chars `:joy:` it will be replaced with the corresponding emoji
- if the emoji string is not found or the token doesn't match the required format no replacements will be done
The above is made possible with any emoji state machine which checks the text before the cursor for matching tokens like `:joy:` in order to decide to convert them or not.
Note: I've left one state event open for implementation of interacting with the emoji popup

feat: replace emoji code with correct emoji code point

---

src/app/wallet/core.nim
src/app/wallet/view.nim
ui/app/AppLayouts/Wallet/HistoryTab.qml
ui/app/AppLayouts/Wallet/LeftTab.qml
ui/app/AppLayouts/Wallet/WalletLayout.qml
ui/app/AppLayouts/Wallet/components/collectiblesComponents/CollectiblesContent.qml
ui/app/AppLayouts/Wallet/components/collectiblesComponents/CollectiblesModalContent.qml

- Determine if the recent transaction history is being fetched or available before obtaining the first 20 transactions
- On account change, reset the selected tab to show the asset list
- Collectibles were kinda pixelated/blurry (not anymore)
Fixes #806

fix: transaction history handling

---

scripts/sign-macos-pkg.sh

Right now I can find old non-existent keychains from previous builds in keychain search list, like so:
```
jenkins@macos-02.ms-eu-dublin.ci.misc:~ % security list-keychains | grep -v "^/private"  
"/Users/jenkins/Library/Keychains"
"/Users/jenkins/Library/Keychains/login.keychain-db"
"/Users/jenkins/workspace/nim-status-client_macos_PR-728@tmp/secretFiles/1689603e-2878-454f-b0c6-319f6b842138/nim-status-client.keychain-db"
"/Users/jenkins/workspace/nim-status-client_macos_PR-749@tmp/secretFiles/b1821a37-09e8-45bd-9811-a9b88b658bd8/nim-status-client.keychain-db"
"/Library/Keychains/System.keychain"
```

sign-macos-pkg.sh: don't restore Jenkins secret keychains

---

ui/app/AppLayouts/Profile/Sections/ContactsContainer.qml

fix(Contacts): use qsTr() over qsTrId() for concrete text

---

src/status/ens.nim
src/status/libstatus/coder.nim
src/status/stickers.nim

Allows `ApproveAndCall` to accept a generic byte-length.
@richard-ramos - please close this if you've incorporated it already

change dynamicbytes to be more dynamic

---

src/app/chat/view.nim
src/status/stickers.nim
ui/shared/AccountSelector.qml

Fixes: #815
Previously, only stickers purchased from the main status account were shown. Now, stickers purchased from any of the accounts are shown.
Accounts include any accounts returned by `accounts_getAccounts` and are non-chat accounts.

feat: show stickers purchased from non-main account

---

ui/shared/RecipientSelector.qml

Disable the selection of "contact" in the send transaction modal, because right now, this is not possible, but it will be in the future. Once we get this working, we can uncomment it.

feat: disable selection of "contact" in send modal

---

src/status/signals/messages.nim

Looks like this may have ended up in the codebase unintentionally.

fix: remove spaces from sticker hashes

---

src/status/libstatus/accounts.nim
src/status/wallet.nim

This commit address two bugs:
1. When importing a mnemonic, the resulting "master" account and its address
was used as account to be stored as opposed to its derived default account
2. The account was stored in the wrong path, resulting in status not being able
to locate accounts when sending transactions.
Fixes #787

fix(Wallet): derive accounts from imported mnemonic and store correctly

---

ui/app/AppLayouts/Chat/ChatColumn.qml
ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml
ui/app/AppLayouts/Chat/ChatColumn/Message.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/MessageMouseArea.qml
ui/app/AppLayouts/Chat/components/ImagePopup.qml

Implements requested feature https://github.com/status-im/nim-status-client/issues/850
- When the user left clicks on a message of type image a modal with the size of the image pops up
- If the image size exceeds the users screen size the modal is made to fit the screen
Test:

feat: open modal when user left clicks on message containing image

---

src/app/wallet/view.nim

Fixes #884 
A very fun one liner that ended up costing me multiple hours of time
The issue was that we update the asset in the current account's `assets`, but not in its `assetList`, which is the View for that AssetList

fix: fix assets not updating in views when getting new balance

---

src/app/chat/view.nim
src/app/profile/views/ens_manager.nim
src/app/wallet/view.nim
src/status/ens.nim
src/status/libstatus/eth/eth.nim
src/status/libstatus/eth/methods.nim
src/status/stickers.nim
src/status/wallet.nim
ui/app/AppLayouts/Chat/ChatColumn/ChatComponents/SignTransactionModal.qml
ui/app/AppLayouts/Chat/components/StickerPackPurchaseModal.qml
ui/app/AppLayouts/Profile/Sections/Ens/RegisterENSModal.qml
ui/app/AppLayouts/Wallet/SendModal.qml

Currently, exceptions thrown during transactions or gas estimation that were spawned in another thread are not being propagated, due to a limitation in nim (see https://nim-lang.org/docs/manual_experimental.html#parallel-amp-spawn).
This means any exceptions from status-go were not propagated correctly and would cause the app to crash. This includes entering the wrong password when trying to send a transaction.
The issue was addressed by passing a `success` variable by reference, which is set to false if an exception was thrown by status-go.
Another issue was fixed relating to estimating token transaction gas. This was fixed by importing `$` in to the wallet model.

fix: exception handling in mutli-threaded transactions

---

src/status/wallet.nim
ui/app/AppLayouts/Wallet/AssetsTab.qml
ui/app/AppLayouts/Wallet/LeftTab.qml
ui/imports/Utils.qml
ui/shared/polyfill.number.toLocaleString.js

Uses `toLocaleString()` polyfill to insert `.` and/or `,` as
needed based on currently selected locale.
Closes #845

uiux(Wallet): improve readability of high value balances

---

src/app/chat/view.nim

Fixes https://github.com/status-im/nim-status-client/issues/665
The above diagram details the logic that is executed when a user switches channel. The flow colored in red executes first and then comes the flow colored in blue.
This logic comes from the following function:
https://github.com/status-im/nim-status-client/blob/c3d946b16517ce00ab9374c42a361fa923f60ecd/src/app/chat/view.nim#L242
More specifically line 255 through 257 and these lines will remain the basis of this discussion:
https://github.com/status-im/nim-status-client/blob/c3d946b16517ce00ab9374c42a361fa923f60ecd/src/app/chat/view.nim#L255-L257
The `setActiveChannel` function executes the following two statements
https://github.com/status-im/nim-status-client/blob/c3d946b16517ce00ab9374c42a361fa923f60ecd/src/app/chat/view.nim# …

fix: call wakuext_contacts RPC once

---

src/app/chat/view.nim
src/app/profile/view.nim
src/app/profile/views/contact_list.nim
src/status/chat/chat.nim
src/status/contacts.nim
src/status/ens.nim
src/status/libstatus/contacts.nim
src/status/profile/profile.nim
ui/app/AppLayouts/Chat/ChatColumn.qml
ui/app/AppLayouts/Chat/ChatColumn/Message.qml
ui/app/AppLayouts/Chat/components/GroupChatPopup.qml
ui/app/AppLayouts/Chat/components/GroupInfoPopup.qml
ui/app/AppLayouts/Chat/components/MessageContextMenu.qml
ui/app/AppLayouts/Chat/components/NicknamePopup.qml
ui/app/AppLayouts/Chat/components/ProfilePopup.qml
ui/app/AppLayouts/Profile/Sections/Contacts/Contact.qml
ui/app/AppLayouts/Profile/Sections/Contacts/ContactList.qml
ui/app/AppLayouts/Profile/Sections/ContactsContainer.qml
ui/nim-status-client.pro

Fixes #833 
Adds a nickname popup to set the nickname of a contact. It is then saved in the Contact itslef in Sttaus-Go.
I also refactored quickly chatModel because it had `addContact`, `blockContact`, etc. and profileModel had it too. So I made the decision to only keep the profileModel ones.

Add support for local contact nickname

---

ui/app/AppLayouts/Chat/ChatColumn/SuggestionBox.qml
ui/app/AppLayouts/Chat/ChatColumn/TopBar.qml
ui/app/AppLayouts/Chat/ContactsColumn/Channel.qml
ui/app/AppLayouts/Chat/components/Contact.qml
ui/app/AppLayouts/Chat/components/GroupInfoPopup.qml
ui/app/AppLayouts/Chat/components/MessageContextMenu.qml
ui/app/AppLayouts/Profile/Sections/Contacts/Contact.qml
ui/onboarding/Login.qml
ui/onboarding/Login/AddressView.qml
ui/shared/ContactSelector.qml
ui/shared/TransactionPreview.qml
ui/shared/status/StatusIdenticon.qml
ui/shared/status/StatusImageIdenticon.qml
ui/shared/status/StatusLetterIdenticon.qml
ui/shared/status/qmldir

This component introduces `StatusLetterIdenticon`, `StatusImageIdenticon`
and `StatusIdenticon`.
- `StatusLetterIdenticon` renders an identicon with a single letter based on a
name.
- `StatusImageIdenticon` renders an actual image based on an identicon URL
- `StatusIdenticon` is a composition of the former both, but with a loading mechanism
to decide which should be rendered
The commit also ensures all of these components are used respectively throughout
the application.

feat: introduce StatusIdenticon components

---

ui/app/AppLayouts/Chat/ChatColumn/ChatInput.qml
ui/app/AppLayouts/Chat/components/EmojiPopup.qml

Fixes #967
Also now enables using the emoji selector (popup) in between words instead of always putting the emoji at the end

fix: fix spaces and line breaks disappearing when pasting

---

ui/app/AppLayouts/Chat/ChatColumn.qml
ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml

Fixes #927
It would require a new design by @simonricoo because it's not super pretty.
It uses the same box as the new message box:

feat: add a button to scroll back to the end of the chat list

---

src/app/profile/views/profile_info.nim
ui/app/AppLayouts/Profile/Sections/AppearanceContainer.qml
ui/main.qml
ui/shared/status/StatusRadioButton.qml

Fixes #599.
Supports system dark mode. Changes the user appearance setting to a 3-way setting of System, Light, Dark.
New accounts will have their appearance setting set to "System", which uses the system setting to determine if dark mode should be applied.
Breaking change: Users who had their settings on Light Theme, will now get the system theme (light or dark). Users who had their theme set to Dark, will now get the Light theme.
At startup, the onboarding screens will have the system-level setting of dark mode applied or not. Once, logged in, the user settings will be applied.
1. An appearance setting of "System" is not dynamic to the system-level setting. This means that if a user has "System" set for their appearance (and ie, the user has light mode set), and then user then changes …

feat: Support system dark mode theme

---

src/app/profile/views/profile_info.nim
ui/app/AppLayouts/Profile/Sections/AppearanceContainer.qml
ui/main.qml
ui/onboarding/CreatePasswordModal.qml
ui/onboarding/EnterSeedPhraseModal.qml
ui/onboarding/GenKeyModal.qml
ui/onboarding/Login.qml
ui/onboarding/Login/AddressView.qml
ui/onboarding/Login/SelectAnotherAccountModal.qml
ui/shared/status/StatusRadioButton.qml

Related to #599.
This PR is based off of #1036, which supports system colors at app startup, meaning the onboarding screens may be in dark mode, if the user has their system set to dark mode. This PR fixes the onboarding screens so they support dark mode.
It also:
1. Adds radio buttons to the `AccountList` component, as per the design
2. Adds `qsTr` where missing on the onboarding screens
3. Fixes some minor design issues
4. Updates the modals titles to match the design
5.  Uses reusable Status components where possible. `EnterSeedPhraseModal` and `GenKeyModal` could have used the `StatusRoundButton` component, but there were some limitations that preventing this from being possible.

fix: Support dark mode for onboarding screens

---

src/app/provider/core.nim
src/app/provider/view.nim
src/nim_status_client.nim
ui/app/AppLayouts/Browser/BrowserLayout.qml
ui/app/AppLayouts/Browser/provider.js
ui/nim-status-client.pro

- Changed WebView to WebEngineView
- Created a new controller/view for the web3 provider
- Created a private profile
- Created a channel for comms browser - qml
- Changed the startpage to status test dapp, since it will make easier testing the provider implementation
- Added the provider code from status-react, althrough it's commented and must be adapted to desktop needs
To test this:
1. Setup an env variable: `export QTWEBENGINE_REMOTE_DEBUGGING=<port_number>`
2. Connect from chrome devtools to localhost:port_number
3. Open desktop and login. You'll see the following stuff happening:
- The dapp will attempt to request a permission from the status api.
- `postMessage` will be invoked in BrowserLayout.qml. This will log the request and call nim's provider/view `postMessage` and print the …

feat: injecting scripts needed for communicating from browser to nim

---

ui/shared/status/StatusIconButton.qml
ui/shared/status/qmldir

This component is similar to a StatusRoundButton that holds an icon.
However, the StatusRoundButton has a fixed number of variations based on the
designs. Sometimes we need clickable icons that have a different look and feel
E.g. in the chat input component.
This component aims to cover that use case.

feat: introduce StatusIconButton component

---

ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml

Fixes #1047
Branched on top of https://github.com/status-im/nim-status-client/pull/1000
Only shows the button after scrolling 400 pixels. Can be adjusted easily.

feat: only show the scrollDown when scrolled up 400 pixels

---

src/app/utilsView/view.nim
ui/app/AppLayouts/Chat/ChatColumn/ChatComponents/ChatCommandsPopup.qml
ui/nim-status-client.pro

`$` was returning a weird object stringified, that we couldn't display anyway

fix: fix eth2Wei returning a bad string

---

ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatText.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/NormalMessage.qml
ui/app/AppLayouts/Profile/Sections/Ens/List.qml
ui/imports/Constants.qml

Fixes #849
You'll see that it doesn't always crop perfectly on a line, that's because we use TextEdit for the text instead of Text, because Text doesn't have the possibility to select the text (to copy for example) (oh man, that's a lot of the word "text" in one sentence). However, TextEdit doesn't have `elide` in return.
The ability to copy is way more important so it's fine to stay with TextEdit, but like you'll see in the CompactMode image, it can make the cropped text look weird.
Sadly, we can't just `substring` the text and add `...` because the text we receive has HTML tags in it, so it would break a lot of stuff.
Anyway, it's not that big a deal since it only happens in very long texts and when the number of lines and spaces arrives on an unlucky cropping line.
Normal mode
Compact …

feat: add a read more button and crop text when message is too long

---

src/status/wallet/collectibles.nim
ui/app/AppLayouts/Wallet/components/collectiblesComponents/CollectiblesHeader.qml
ui/imports/Constants.qml

Fixes #807 
Before, we only loaded 20 because that is the Cryptokitties API limit.
Now, we load everything using a recursive function and increasing the offset

feat: enable loading all the cryptokitties assets with recursion

---

src/app/chat/core.nim
src/app/chat/view.nim
ui/app/AppLayouts/Chat/components/StickersPopup.qml

Closes: #586
Previously, loading sticker packs and stickers would show a lot of blank and non-interactive content.
Now, stickers and sticker packs have grey circles to indicate loading. Additionally, the sticker market button (+) shows a loading indicator until the sticker packs are loaded.
If a recent sticker is clicked while the sticker packs are still loading, the app crashes due to some kind of conflict in threads. I spent some time trying to figure this out, but could not get anywhere. Maybe @richard-ramos has an idea?

feat: add sticker loading UI

---

src/app/utilsView/view.nim
src/app/wallet/view.nim
src/status/libstatus/types.nim
src/status/wallet.nim
ui/app/AppLayouts/Chat/components/StickerPackPurchaseModal.qml
ui/shared/TransactionPreview.qml
ui/shared/status/StatusStickerPackPurchaseModal.qml

Fixes: #926.
Gas estimations were not being decoded correctly (indicated with "error getting gas price predictions" in the console) and were preventing transaction dialogs from continuing past the step containing the GasSelector component. This affected mainnet only, because in testnet we have hardcoded gas prices (for when the gas prices on mainnet are insane) which is why it was not apparent in testnet.
fix: Contract address not showing correctly
This was caused by `getStickerMarketContractAddress` being moved to `utilsView` but not updated in QML

fix: Estimating gas prevents transaction modal continue

---

ui/app/AppLayouts/Chat/ChatColumn.qml
ui/app/AppLayouts/Chat/ChatColumn/ChatInput.qml

Fixes https://github.com/status-im/nim-status-client/issues/1006
The chat input bar height adjusts to the message length (The height attributes supports integer so the transition isn't as smooth). The color of the message size changes from green to red if user has passed the character limit. The message won't be send if limit is passed, but instead a MessageModal will open explaining that to be courteous you need to adhere to 2000 char limit.

feat: introduce a character limit with a char limit counter UI

---

src/app/wallet/view.nim
src/app/wallet/views/transaction_list.nim
src/status/libstatus/wallet.nim
ui/app/AppLayouts/Wallet/HistoryTab.qml

fixes https://github.com/status-im/nim-status-client/issues/827
A button is added that load mores transaction by appending newly fetched trxs to the current list.
I was unable to find a way to let the ListView + Scrollbar to start the display all the way to the bottom when new transactions are appended, so it always resets to the beginning of the list
[https://i.imgur.com/xCzXZrK.mp4](https://i.imgur.com/xCzXZrK.mp4)

feat: load more transactions with a button

---

ui/app/AppLayouts/Wallet/components/AddAccountWithSeed.qml
ui/imports/Utils.qml
ui/onboarding/EnterSeedPhraseModal.qml
ui/shared/StyledTextArea.qml

fixes: https://github.com/status-im/nim-status-client/issues/1078
- If the count matches the required amount a tick will be included next the count
- The format is "✓ 12 words"
- This commit also fixes the text color when in dark in the wallet add new account modal
- This feature is added on both login and wallet add account with wallet seed modal

feat: implement seed word phrase counter

---

ci/Dockerfile
ci/Jenkinsfile.linux

We do this here to avoid having to fork the original image repo: https://github.com/a12e/docker-qt
Resolves: https://github.com/status-im/nim-status-client/issues/523
I also switched from using `latest` tag to `1.0.0`. I wanted to use commit `SHA1` but that would change once this is merged...

ci: re-install Qt in Docker image to add QtWebEngine

---

ui/onboarding/Login.qml

On the Login screen, the "generate new keys" button was not clickable since the most recent update to the button.

fix: "Generate new keys" not clickable

---

ui/app/AppLayouts/Chat/ChatColumn.qml
ui/app/AppLayouts/Chat/ChatColumn/Message.qml
ui/app/AppLayouts/Chat/ChatLayout.qml
ui/app/AppLayouts/POA/main.js
ui/app/AppMain.qml
ui/imports/Constants.qml

I had to change the dictionnary to contain the channelHash and the userAddress instead of the chatid and pubkey, since the contract only contains the former and we cannot unhash.

feat: listen to add and ban events and update the dictionnary

---

.gitmodules
src/app/chat/core.nim
src/app/login/core.nim
src/app/node/core.nim
src/app/onboarding/core.nim
src/app/profile/core.nim
src/app/wallet/core.nim
src/eventemitter.nim
src/nim_status_client.nim
src/status/accounts.nim
src/status/chat.nim
src/status/contacts.nim
src/status/libstatus/types.nim
src/status/mailservers.nim
src/status/messages.nim
src/status/network.nim
src/status/node.nim
src/status/profile.nim
src/status/signals/core.nim
src/status/signals/types.nim
src/status/status.nim
src/status/stickers.nim
src/status/wallet.nim
src/status/wallet/account.nim

The event emitter was firing multiple times or not at all for events when multiple threads were involved. First, I started by adding references to objects in the events array, but ended up not being enough. Instead, a refactor of the library was easier and more robust.

refactor: make event emitter threadsafe

---

ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/Sticker.qml
ui/shared/ImageLoader.qml

Fixes #1125
The problem seemed to happen when there was stickers at the bottom of a channel. We don't use the same loader and the one for stickers doesn't have the scroll to bottom call
Also, I added a double call to scroll to bottom, one straight away and one with a timer, because if you scroll down and the last elements are pictures or stickers, they will be small for the scroller, but once loaded, will take more space, hence creating a gap. With the timeout, the scroll goes to the right position after 100 ms. It's small enough that it's not too noticeable, but also long enough to let the images load again.

Fix scroll at bottom when switching chats and with the button

---

ui/app/AppLayouts/Chat/ChatColumn/ChatComponents/ChatCommandModal.qml
ui/app/AppLayouts/Chat/ChatColumn/ChatComponents/SignTransactionModal.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/TransactionComponents/SendTransactionButton.qml
ui/shared/AccountSelector.qml
ui/shared/BalanceValidator.qml
ui/shared/IconButton.qml
ui/shared/TransactionPreview.qml

Fixes #1202
I had to revert the loader changes that switched from/to as it was causes quite a lot of logistical complexity. Instead of using Loaders, we are setting the type of account (account or contact), and it is being displayed appropriately. There is a very slight deviation from the design, however it is consistent with the design for other transaction previews.
feat: add BalanceValidator
Shows an exclamation icon next to the "from" account when the balance for the requested asset is too low.
This is useful when the user starts the transaction wizard on the TransactionPreview step.

fix:  from/to account not showing correctly

---

ui/app/AppLayouts/Chat/components/GroupInfoPopup.qml

Fixes #1121 kindof
The profile popup already showed when clicking the name of someone. I only fixed it to not close when the profile popup closes

fix: don't close group info popup when closing profile popup

---

ui/app/AppLayouts/Browser/BrowserLayout.qml
ui/app/AppLayouts/Browser/BrowserSettingsMenu.qml
ui/main.qml

While reading about sqlite errors and QT, I found the following issues in which a problem similar to what we have is described to happen when the UserAgent is changed.
https://github.com/gort818/qtwebflix/issues/53
https://bugreports.qt.io/browse/QTBUG-75884
The error @jrainville reported in Discord had the same type of errors that can be seen in qtwebflix/issues/53
```
[38748:38824:1007/152520.131938:ERROR:database.cc(1598)] Cookie sqlite error 5, errno 0: database is locked, sql: PRAGMA auto_vacuum
[38748:38824:1007/152520.132098:ERROR:database.cc(1598)] Cookie sqlite error 5, errno 0: database is locked, sql: PRAGMA journal_mode=TRUNCATE
[38748:38824:1007/152520.132129:ERROR:database.cc(1598)] Cookie sqlite error 5, errno 0: database is locked, sql: SELECT 1 FROM sqlite_master WHERE …
```

fix?: sqlite crash - Cookie sqlite error 5, errno 0: database is locked

---

ui/app/AppLayouts/Chat/ChatColumn/ChatComponents/SignTransactionModal.qml
ui/shared/BalanceValidator.qml
ui/shared/GasValidator.qml
ui/shared/TransactionPreview.qml

`BalanceValidator` and `GasValidator` have been moved outside of the `TransactionPreview` component, because there are some transaction modals that may not need them to be baked in to `TransactionPreview`. It is useful to have these components on the tx preview step only when we start the process on the preview step.

feat: move validators outside of TransactionPreview

---

scripts/windows_build_setup.ps1

Before:
```
admin@windows-01 MINGW64 ~
$ ls -l /c/Qt/5.14.2/msvc2017_64/include/ | grep Web
drwxr-xr-x 1 admin 197121 0 Mar 27  2020 QtWebChannel
drwxr-xr-x 1 admin 197121 0 Mar 27  2020 QtWebSockets
drwxr-xr-x 1 admin 197121 0 Mar 28  2020 QtWebView
```
After running:
```
aqt install --output "C:\Qt" "5.14.2" windows desktop win64_msvc2017_64 -m qtwebengine
```
```
admin@windows-01 MINGW64 ~
$ ls -l /c/Qt/5.14.2/msvc2017_64/include/ | grep Web
drwxr-xr-x 1 admin 197121 0 Mar 27  2020 QtWebChannel
drwxr-xr-x 1 admin 197121 0 Mar 28  2020 QtWebEngine
drwxr-xr-x 1 admin 197121 0 Mar 28  2020 QtWebEngineCore
drwxr-xr-x 1 admin 197121 0 Mar 28  2020 QtWebEngineWidgets
drwxr-xr-x 1 admin 197121 0 Mar 27  2020 QtWebSockets
drwxr-xr-x 1 admin 197121 0 Mar 28  2020 QtWebView
```

ci: install qtwebengine with Qt on windows

---

ci/Jenkinsfile.linux
ci/Jenkinsfile.macos
ci/Jenkinsfile.windows

It was asked in `#desktop` how we could provide the infura token to CI builds. This is pretty much it.
Windows is slightly different because it doesn't run `make nim_status_client`. If I remember correctly that was to avoid rebuilds.

[WIP] ci: provide INFURA_TOKEN to builds

---

src/app/chat/views/chat_item.nim
src/app/wallet/view.nim
ui/app/AppLayouts/Chat/ChatColumn.qml
ui/app/AppLayouts/Wallet/SendModal.qml
ui/imports/Utils.qml
ui/shared/AddressInput.qml
ui/shared/ContactSelector.qml
ui/shared/EnsResolver.qml
ui/shared/RecipientSelector.qml

feat: Re-enable contact selection in the wallet send dialog
Selecting a ENS-verified contact will resolve it's ENS address so transactions can be sent directly to contacts from the wallet (if and only if they have ENS enabled for their account).
feat: add EnsResolver component that shows a loader and allows automated ENS resolution from within QML

feat: Re-enable contact selection in the wallet send dialog

---

ui/shared/status/StatusRoundButton.qml

Also introduces a new `pressed` state which allows for icon rotation if needed.

refactor(StatusRoundButtno): move to QML states and transitions

---

ui/app/AppLayouts/Chat/components/GroupChatPopup.qml
ui/app/AppLayouts/Chat/components/PublicChatPopup.qml
ui/imports/Utils.qml

Fixes ##1085
Adds a whitelist regex for the channel names. For now, only accepts lowercase letters, numbers and dashes.
This with the XSS filter in the other PR makes it pretty impossible to bamboozle us through the channel name

feat: whitelist the characters possible for the channel names

---

src/app/chat/views/channels_list.nim

Fixes #1311
this caused spaces to disappear when using markdown
@richard-ramos I saw you were the one to add the strip. What was the original reasoning?
I tried without the  strip to adds multiple spaces, enters and markdowns and everything works

fix: do not strip spaces from the parts of messages

---

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/CompactMessage.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ImageLoader.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ImageMessage.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/MessageMouseArea.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/NormalMessage.qml
ui/shared/status/StatusImageModal.qml

Fixes #1330
Makes the Gifs play. It only needed `AnimatedImage` instead of `Image`.
I worried that "always" using `AnimatedImage` might have negative impact on memory or CPU usage, but I tested and it doesn't. Animated is basically just a wrapper around image that has like 5 extra properties.
Also, I made sure that no images keep playing while scrolled up and to make it less annoying, you can also stop the animation by clicking on the image or un-focusing the window
Two improvements/issues:
1. When scrolling and the image disappears, it gets completely thrown out of the memory (it's done automatically by ListView). It's cool for memory usage, but it means that once the image is back in the view, it has to re-render it. That also makes it so that if you stopped a gif before, scroll away …

feat: enable animated gifs but stop them on click and out of focus

---

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatText.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/NormalMessage.qml

Fixes #1348
I basically put it at 50% of the chat window or 400 (as before)
Let me know if  it's not something we want (cc @simonricoo )
Normal: 
Wide

feat: make the message box scale according to the parent's width

---

src/status/wallet/collectibles.nim

Fixes #1325
The problem is that the request to get a token from the contract returns an error and we threw on it because there was no `result`.
Sadly, I don't think there is a way to not have the rpc error, because it's the contract itself responding with a revert when the address doesn't have a token instead of just retuning an "empty" result.

fix: remove errors on collectibles rpc errors

---

ui/shared/status/StatusChatInput.qml

Fixes #1354 mostly
The problem is that adding code to a TextArea using `insert` or `text =` triggers QML's XSS protection. So it's virtually impossible to put `<script>` using `insert.
However, just a normal paste works if we don't call `insert`. So in the `interrogateMessage` function that is called when pasting, I only call `insert` if it is needed aka when there is an emoji.
TLDR: you can now paste `<script>` but it will go away if you put emojis with it

fix: enable copying <script> but will still go away when putting emoji

---

ci/Jenkinsfile.linux
ci/Jenkinsfile.macos
ci/Jenkinsfile.windows

The artifacts from this repo are taking up too much space on the CI master:
```
admin@master-01.do-ams3.ci.misc:/docker/jenkins/data/jobs % sudo du -hsc ./* | sort -h | tail -n5
13G	./status-react
17G	./status-go
18G	./nimbus
73G	./nim-status-client
122G	total
```

lower number of artifacts to keep in CI to 10

---

Makefile

According to help, options are single-dash - in fact, the default `rcc`
on fedora doesn't accept double-dash.
```
[arnetheduck@tempus nim-status-client]$ rcc --help
Qt resource compiler
rcc: Unknown option: '--help'
Usage: rcc  [options] <inputs>
Options:
-o file              write output to file rather than stdout
-name name           create an external initialization function with name
-threshold level     threshold to consider compressing files
-compress level      compress input files by level
-root path           prefix resource access path with root path
-no-compress         disable all compression
-binary              output a binary file for use as a dynamic resource
-namespace           turn off namespace macros
-project             Output a resource file containing all
files …
```

rcc: single dash options

---

ui/app/AppLayouts/Browser/BrowserLayout.qml
ui/app/AppLayouts/Browser/DownloadBar.qml
ui/app/AppLayouts/Browser/DownloadElement.qml
ui/app/AppLayouts/Browser/DownloadView.qml

fixes https://github.com/status-im/nim-status-client/issues/1232
This PR re-purposes the DownloadView into a Loader component of a browser tab and is displayed when: 
1. a new "Downloads tab" is opened (via shortcut "Ctrl+D") or
2. a new tab with the link `status://downloads` or finally when 
3. the ShowAll button has been clicked.
You can open any number of Downloads tabs
When you open a new tab and type in status://downloads the title will remain as 'New Tab'

feat: make download view a browser tab instead

---

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/EmojiReactions.qml

fixes https://github.com/status-im/nim-status-client/issues/1386
Added a tooltip that shows username or alias of chat keys stored in the emojiReactions model fromAccount attribute

feat: support seeing who liked a message

---

Makefile

The fleets file was placed in resources but it was needed in the root 🤷

fix: fix fleets.json file wrongly placed in Windows builds

---

src/app/chat/view.nim
ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml
ui/shared/NotificationWindow.qml

Fixes #1305
The group chats notifications showed the channel's pubkey and no emoticons because it didn't know the channel name

fix: fix notification banner showing the pubkey of group chats

---

src/app/chat/views/message_format.nim

Fixes #1339
We now support `***text***`
I also made it so that if there are other types added later, we still show the text even though we don't support the formatting yet

feat: support italic-bold in messages

---

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/CompactMessage.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/NormalMessage.qml

It was missing the signal and also it needed a higher Z. I'm not sure why it needed the higher Z, since it didn't need it before

fix: fix ChatImage not opening in the popup

---

src/status/libstatus/accounts.nim
ui/app/AppLayouts/Wallet/components/AddAccountWithPrivateKey.qml

This fixes the issue with creating transactions. The derivation paths should change depending on the type of account being used. We were also missing calling a nim-status function when the private key are imported.

fix: wallet derivation paths for generated accounts , imported seed phrases and private keys

---

src/app/chat/event_handling.nim
src/app/chat/view.nim
src/status/chat.nim
src/status/chat/utils.nim
ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml

fix https://github.com/status-im/nim-status-client/issues/898
The segmentation fault occured because the RPC response returned json with an error message as opposed to the usual data required to update the chat. Since the section of the code didn't handle this error message it caused the app to crash. I've handled this error to show an error alert box by emitting a `sendMessageFailed` event

fix: stop crash by showing error message

---

src/app/profile/view.nim
ui/app/AppLayouts/Chat/ChatColumn.qml
ui/app/AppLayouts/Chat/components/ProfilePopup.qml
ui/imports/Utils.qml
ui/shared/status/StatusChatInput.qml

This PR is a response to @emizzle's suggested change in PR #1431 . It checks if a user is blocked before exposing certain functionality to the user in a Profile popup. 
I've also added functionality to the StatusChatInput component that checks whether the chat recipient has been blocked and disabling it if the latter is true. The caveat is that the update to the `profileModel's blocked list` doesn't get picked up by the current active chat window. It only gets picked up when you find some way to reload the chat component eg switching chats/changing nickname

fix: check if user is blocked on profile popup

---

ui/app/AppLayouts/Chat/ContactsColumn/EmptyView.qml

fix: add padding to the empty chat view

---

ui/app/AppLayouts/Chat/components/ProfilePopup.qml

We've introduced a bug in https://github.com/status-im/nim-status-client/commit/8fd28dfa where a
non-existing `UnblockContactConfirmationDialog` usage was added.
This commit changes it to be a standard `ConfirmationDialog` to make the application compile
again.

fix: use ConfirmationDialog when unblocking users

---

ui/shared/status/StatusChatInput.qml

fixes #1376
the messages still get trimmed if you send a normal message with leading whitespace for example (or when there's too many whitespaces between 2 words)

fix: markdown leading whitespace

---

ui/shared/status/StatusChatInputImageArea.qml

We were only resetting the `Image` source but not the consumer facing `imageSource`
property when removing a selected image from the image area.
This cause the `imageSource` to practically never change after an image has
been selected the first time. Selecting an image another time would open the
image area, but if the image happens to be the same as the first time, the `imageSource`
practically didn't change, causing the app to render an "empty" image.

fix(Chat): ensure image area is reset properly when removing images

---

Makefile
ci/Jenkinsfile.linux
ci/Jenkinsfile.macos
src/status/libstatus/accounts/constants.nim

Allow environmental override at runtime. Also, in the Makefile set a free-tier default token so that setting up an Infura account isn't strictly necessary for community contributors to build the app, even though in our docs it should be recommended they do so.
Core contributors should setup their own free-tier Infura account, create a key, and set it in the environment variable INFURA_TOKEN in their environment used to build the desktop app locally.
There is one aspect of this work that is incomplete. Ideally, in the handler for the `login` event the relevant settings in the database should always be updated with the resolved Infura key. However, when calling `getSetting[string](Setting.Networks_Networks)` in the handler it causes a segfault every time. Neither the reason for the crash …

refactor: embed Infura key at compile time

---

ui/app/AppLayouts/Chat/ChatColumn.qml
ui/shared/status/StatusChatInput.qml

StatusChatInput was relying on the suggestions ListModel, even though there was
no guarantee that it would exist. This is more apparent when using the component
in different context (e.g. Timeline/Status Updates). QML will throw a reference
error in this case.

refactor(Chat): move suggestions ListModel into StatusChatInput

---

src/app/chat/view.nim
src/app/chat/views/message_list.nim
src/status/chat/message.nim
src/status/signals/messages.nim
ui/app/AppLayouts/Chat/ChatColumn.qml
ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml
ui/app/AppLayouts/Chat/ChatColumn/Message.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/CompactMessage.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/NormalMessage.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/UsernameLabel.qml
ui/app/AppLayouts/Chat/components/MessageContextMenu.qml
ui/app/AppLayouts/Profile/Sections/Ens/List.qml
ui/shared/status/StatusChatInput.qml

In timeline status update messages we want to render the ENS name next to a
local nickname in case it exists. This commit extends the `UsernameLabel` to do
just that.
Closes #1488
Couple of things are happening here:
- Prior to this commit, in QML we had `message.userName` which was reading from the Nim's `message.alias` counterpart.
- This means, in QML, `message.userName` could've been either the user's the word alias, its ENS name, or its local nickname
- We need all of them in `UserNameLabel` to implement the design for the status updates timeline so this commit introduces two new properites to the QML object: `localName` and `alias`
- Now, just like the names intend, `localName` is always `contact.localNickName`. `alias` is always `contact.alias` and `userName` stays what it was …

feat: make `UserNameLabel` render local nick names and ENS names

---

ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml
ui/app/AppLayouts/Profile/Sections/NotificationsContainer.qml
ui/imports/Constants.qml
ui/main.qml
ui/shared/NotificationWindow.qml

Fixes #1423 
Adds OS notifications, meaning notifications that use your OS' notification tray.
Adds a setting in Notifications as well to switch back to the old "Status notifications"
I also fixed the Timer issue we had where the Status Notification never went away.
Known issues:
- In Linux, clicking the notification just closes it without calling `onClick`. Not sure if there is much we can do about it
- In Linux, the notification doesn't disappear after the timer
- the icon is not changeable to anything that is useful. I tried using `NoIcon`, but it ddoesn't work both on lInux and Windows, so we're stuck with the `Info` icon. The other options are `Wanring` and `Danger` which are obviously worse.

feat: add OS notification and setting to switch back

---

src/app/chat/view.nim
src/app/chat/views/message_list.nim
src/status/chat/message.nim
src/status/signals/messages.nim
ui/app/AppLayouts/Chat/ChatColumn.qml
ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml
ui/app/AppLayouts/Chat/ChatColumn/Message.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/CompactMessage.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/NormalMessage.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/UsernameLabel.qml
ui/app/AppLayouts/Chat/components/MessageContextMenu.qml
ui/app/AppLayouts/Profile/Sections/Ens/List.qml
ui/shared/status/StatusChatInput.qml

`StatusChatInput` ideally shouldn't rely on chatsModel and other global
objects at all. Also, when using the component in different places, it can cause
accidental sending of message when testing the component (because all the logic is already
wired up)

refactor(Chat): move send message logic out of status chat input

---

Makefile
src/nim_status_client.nim

In the context of Windows packaged builds, this is consistent with other resources needed by the application; organizing them in this way keeps the top-level directory of Windows packaged builds clear of files that most users should never have to see or think about.
---
See: https://github.com/status-im/nim-status-client/pull/1412#issuecomment-736779309.

refactor: in Windows packaged build fleets.json should be in resources/

---

src/app/chat/view.nim
src/status/libstatus/chat.nim
src/status/libstatus/types.nim
ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml
ui/app/AppLayouts/Chat/ChatColumn/Message.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/CompactMessage.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ImageLoader.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ImageMessage.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/LinksMessage.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/NormalMessage.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/Sticker.qml

YouTube link unfurling was not working for a couple reasons.
There were two main parts fixed:
1. QML context for messages pertaining to linkUrls and imageUrls was changed from implicit to explicit. By this, I mean that any time we referenced linkUrls/imageUrls, we were relying on the knowledge that those values would be populated by some parent context several levels up. Now, we are referring to properties that have been explicitly defined on the components. This offers the ability to reuse components, and makes reading the code and debugging much easier.
2. Error handling has been added to getting link preview data. An unhandled "error" was thrown each time a link that wasn't whitelisted was passed in, causing the app to crash. For example, when a link to a tenor gif was posted in the …

fix: YouTube unfurling

---

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatReply.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/NormalMessage.qml

fix: chat reply width when content is smaller than author

---

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatText.qml

This restores URL click-ability and selecting/copying text in chats.

fix: restore z-index to root Item of ChatText.qml

---

ui/app/AppLayouts/Chat/CommunityComponents/CommunityList.qml
ui/app/AppLayouts/Chat/ContactsColumn/Channel.qml
ui/app/AppLayouts/Chat/ContactsColumn/ChannelList.qml

I had to use some magic numbers because even if the height of the listview elements is 0, there's still some contentHeight  ¯\\\_(ツ)_/¯

fix: channel/communities listview height depending on search string

---

src/status/chat/chat.nim
src/status/signals/messages.nim

When dealing with Timeline and Profile chat data, the `HEAD~1` would break
because we're trying to access `ChatType(4)` inside our `toChat` API.
To fix this issue, we have to make `ChatType` aware of `4` and `5` which are
`Profile` and `Timeline` respectively.

fix: introduce chat types for Timeline and Profile

---

src/app/chat/views/stickers.nim
ui/shared/status/StatusChatInput.qml
ui/shared/status/StatusStickerList.qml
ui/shared/status/StatusStickersPopup.qml

Fixes #1284.
Fixes #1529. 
The sticker loading UI was removed when the StatusChatInput and friends were added in. This PR re-adds the sticker loading UI introduced in PR# 955 (https://github.com/status-im/nim-status-client/pull/955).

chore: re-add sticker loading UI

---

ui/app/AppLayouts/Chat/ChatColumn/Message.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatReply.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/CompactMessage.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ImageLoader.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ImageMessage.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/NormalMessage.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/StatusUpdate.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/Sticker.qml

The problem was that the Image didn't receive the `container` (which is Message) correctly, so the mechanism to remember if an image already loaded didn't work

fix: fix scroll going back down when hitting images

---

src/status/contacts.nim

Primary motivator here was that the current `getContacts` APIs requries
a `ContactModel` which isn't always around. In fact, there's actually
no particular reason this APIs has to live on a model object.
However, to not break existing APIs I'm introducing a `getAllContacts`
API that returns all contacts as profiles, just like `contacts.getContacts`
does, without it being dependent on a `ContactModel`.
The same function is then used to add an API for returning all *added*
contacts as profiles.

feat: introduce getAllContacts and getAddedContacts APIs

---

src/status/chat.nim
src/status/contacts.nim
src/status/libstatus/chat.nim

Previously, this API would take a flag `oneToOne` and would use it to determine
whether the chat type is going to be `1` or `2`. However, there are many more chat
types, so it's important this API supports all of them.
Since we already have an enum in place, I'm changing this function to take it instead.
In addition, it also gets a `profile` parameter which is needed to implement
the status timeline functionality.

feat: make saveChat API more flexible by taking a ChatType

---

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/StatusUpdate.qml

This commit introduces some `MouseArea`s so components inside the
`StatusUpdate` component cancel it out by having a higher `z`.
Also, in some cases we need to conditionally set the `root.hovered` property
to ensure the values get inverted correctly, otherwise it causes undesired
flicker effects.

fix(StatusUpdate): ensure hover effect is working properly

---

src/app/chat/core.nim
src/app/chat/view.nim
src/status/chat.nim
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/StatusUpdate.qml
ui/shared/status/StatusChatInput.qml

When sending a profile status update, the message has to be sent to
a specific channel that has the id `@PUBKEY`.
This commit introduces a flag that controls whether the message is
sent to the currently active channel, or tot he profile status channel.
The same is done for the `sendImage` API.

feat: introduce isStatusUpdate flag in sendMessage APIs

---

ui/app/AppLayouts/Chat/ChatColumn/Message.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatText.qml
ui/app/AppLayouts/Chat/ChatColumn/TopBar.qml
ui/app/AppLayouts/Chat/ChatLayout.qml
ui/app/AppLayouts/Chat/ContactsColumn/Channel.qml
ui/app/AppLayouts/Chat/ContactsColumn/ChannelList.qml
ui/app/AppLayouts/Chat/components/GroupInfoPopup.qml
ui/app/AppMain.qml
ui/shared/status/StatusChatInfo.qml
ui/shared/status/StatusChatInfoButton.qml

Prior to this commit, the function was expected on a `chatView` QML object.
This has worked out so far because the places where the API is used were always
living inside `ChatLayout`.
With the new timeline however, this is no longer the case so we have to make sure
that the API is available to other views as well.

refactor: move getProfileImage API to appMain

---

src/app/chat/core.nim
src/app/chat/event_handling.nim
src/app/chat/view.nim
src/app/chat/views/sticker_pack_list.nim
src/app/chat/views/stickers.nim
src/app/node/core.nim
src/app/utilsView/core.nim
src/nim_status_client.nim
src/status/network.nim
src/status/stickers.nim
src/status/wallet.nim
ui/shared/GasSelector.qml
ui/shared/ImageLoader.qml
ui/shared/status/StatusStickerButton.qml
ui/shared/status/StatusStickerPackPurchaseModal.qml
ui/shared/status/StatusStickersPopup.qml

When the network connection is changed, the sticker packs are cleared and then re-loaded (either loading the offline (installed) sticker packs, or all the sticker packs from the network).
Stickers can be sent while offline, though the sticker images do not load once offline (this is likely a side effect of the bug described below).
There is a known bug in QNetworkAccessManager (https://bugreports.qt.io/browse/QTBUG-55180) that was re-introduced in 5.14.1 that does not allow us to download resources if we go offline then come back online. The workaround employed in this PR manually sets the NetworkAccessible property of QNetworkAccessManager once we have been connected back online. The NetworkAccessible property is marked as obsolete and will be removed in Qt6, so it is something that we …

feat: load installed stickers while offline

---

src/app/chat/view.nim
ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml

I was annoyed that I didn't get notifications when the active channel is the one receiving messages because it was minimized.
Now, if you minimize the app, you'll get notifications for any unmuted channels

fix: show notification if the window isn't focused

---

src/app/chat/view.nim
src/app/chat/views/community_item.nim
src/app/chat/views/community_members_list.nim
src/status/chat.nim
src/status/libstatus/chat.nim
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/InvitationBubble.qml
ui/app/AppLayouts/Chat/CommunityComponents/CommunityMembersPopup.qml

Adds the `removeUserFromCommunity`. It works on the admin side, but it doesn't send a signal for the other side to update, I assume it's a status-go bug. Anyway, it's already good.
I also fixed the community invite that would crash if the 1:1 channel didn't exist yet.

Enable removing member and fix invites

---

src/app/chat/view.nim

The `messageList` model used for rendering messages gets notified by the
`activeChannelChanged()` signal. That signal is not immediately emitted inside
the timeline when new messages are received.
This causes the underlying view data to be out of sync with the model,
causing UI bugs, such as rendering the `EmptyTimeline` component when in fact,
the timeline is not empty.
To fix this, there are two options:
1. Change the signal from `activeChannelChanged` to `messagePushed` signal, which
is for sure emitted when messages are received
2. Ensure `activeChannelChanged` is emitted when messages are pushed and the
active channel is indeed the timeline
Since the application has been relying on `activeChannelChanged` so far, I decided
to go with option 2 as I'm not sure whether option 1 would …

fix(Timeline): ensure messagesList QtProperty is notified for rendering

---

ui/app/AppLayouts/Profile/Sections/Contacts/Contact.qml

The "more actions" button in the contacts list had some hard coded colors
for its hover effect which break the experience in dark mode.
This commit makes changes those so that they work universally.

uiux(Profile): theme color fixes for the contact list

---

ui/app/AppLayouts/Profile/Sections/ContactsContainer.qml

The contact list was taking the entire width of its surrounding element,
making it grow too wide to be usable (see #1589).
In fact, it's not following the designs made for this part of the application,
so this commit changes the max layout width to align with the intended
design and should also fix some of the usability issues mentioned in #1589
Fixes #1589

uiux(Profile): adjust layout of contact list section

---

src/app/chat/view.nim

That was my bad, during a rebase or something like that, I messed up the `else`. It used to be attached to `if (msg.chatId != self.activeChannel.id)` but I removed that `if` because it is handled by the QML side now, but the `else` got attached to the `isMuted` by accident.
I readded the right condition (reversed) and now everything works like before

fix: fix chat not scrolling because the signal was not called

---

src/app/chat/view.nim
src/app/chat/views/reactions.nim
ui/app/AppLayouts/Chat/ChatColumn/Message.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/EmojiReactions.qml
ui/app/AppLayouts/Chat/ChatLayout.qml
ui/app/AppLayouts/Chat/CommunityComponents/CommunityMembersPopup.qml
ui/app/AppLayouts/Chat/components/EmojiReaction.qml
ui/app/AppLayouts/Chat/components/GroupInfoPopup.qml
ui/app/AppMain.qml

This commit makes reactions in the status timeline work.
There are two things prior to this commit that are broken:
1. The logic that opens the reaction context menu always expects
and instance of `chatsView` because it tries to calculate a users
nickname. Such an instance isn't always available in that context, so
the nickname logic has been moved to `appMain` for now, removing that
dependency and therefore making it work in both, the chat view as well
as the status view.
2. While 1) makes the context menu work, it turns out that adding and
removing reactions inside the status timeline is still not working.
The reason for that is, that the reactions component maintains its own
`messageList`, which isn't aware of the fact that reactions for messages
coming from chats of …

fix(Timeline): make reactions works

---

ui/app/AppLayouts/Wallet/TokenSettingsModal.qml
ui/app/AppLayouts/Wallet/WalletHeader.qml
ui/app/AppLayouts/Wallet/components/TokenSettingsModalContent.qml

This commit does a couple of things:
- It changes a label in the wallet menu from "Add/remove Token" to "Manage Assets"
as it has been designed
- It changes the asset list so a hover state could be introduced. Previously there
was no visual effect or response to mouse hover on asset items
- It improves usability of the asset list by making an entire asset item
clickable to toggle the asset in the wallet. This was not possible before.
Users had to click the checkbox achieve this effect
Closes #1631

uiux(Wallet): improve asset manager usability and UI

---

ui/app/AppLayouts/Wallet/components/SetCurrencyModalContent.qml

Setting the default currency through the UI doesn't work because of a `MouseArea` that
is masking the an underlying `StatusRadioButton` which will tricker the default currency
change.
This commit enhances the `MouseArea` to trigger the default currency change and it
also ensures the UI is responding accordingly. Namely that the new default currency
is correcly selected in the list of currencies.
There's also a little change in the background hover color so it works well across
light and dark themes.
Fixes #1632

fix(Wallet): fix bug that prevented users from setting the currency

---

ui/app/AppLayouts/Profile/Sections/ContactsContainer.qml

Adding a contact through the Add Contact Modal isn't working because the
function being called to add a contact doesn't actually exist.
This was most likely a mistake as the change was just to call that function
in question from a different property.
This commit does exactly that.
Fixes #1660

fix(Contacts): make add contact button work again

---

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatTime.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/NormalMessage.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/SentMessage.qml

Fixes #1606 
Mucho prettier
Only works for images sent as part of a private message, because link messages can contain more than one image and even unfurled links, so it still looks better underneath

Show time of sending in the image itself and change `Sent` to  a check

---

ui/shared/status/StatusSectionDescItem.qml

This is a component that is similar to the `StatusSectionMenuItem` component, just
with the difference that it's not a clickable element, rather "description" element,
inspired by HTML `<dl>`, `<dt>` and `<dd>` elements ("description list", "description term",
"description" respectively).
The component comes with a `CopyToClipBoardButton` by default. We might want to decide
to make it configurable later on, as there could be places where we just want to
render the description item, without a copyble description.

feat: introduce StatusSectionDescItem

---

src/app/profile/core.nim
src/app/profile/view.nim
ui/main.qml
ui/onboarding/ExistingKey.qml

As reported in #1584 the message that asks users to backup their seed phrase
is shown even when the seed phrase was imported in the first place, implying that
the mnemonic is already backed (it has to come from somewhere, right?).
This commit introduces a new `appSettings` property that is temporarily set to
determine whether or not the backup message should be shown.
It's set only temporarily because we actualy determine whether we want to show the
backup message, by checking if the account's mnemonic is still stored in the settings.
When a backup is done, Status removes the mnemonic from the profile settings.
So in order to get the right behaviour we need to make sure to remove the mnemonic
from the profile settings after the account has logged-in and originated from
an imported seed …

fix: don't show backup message when mnemonic was imported

---

src/app/wallet/view.nim
src/status/wallet.nim
ui/app/AppLayouts/Chat/ChatColumn/ChatComponents/SignTransactionModal.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/TransactionComponents/AcceptTransaction.qml

fixes #935
A bug occurs when someone requests a large amount of funds from you since the gas estimation will fail and there isn't a way of handling errors in the source yet and so the operation results in a crash. Another place where the same gas estimation procedures are used is in the Wallet Send Modal where gas estimation error handling is much more robust.
This PR handles the error appropriatley for both `estimateGas` and `estimateTokenGas` where the response is only converted from hex to int if the RPC call was successful. Otherwise return the error message as the response and let the UI decide how to display it.
Currently the error for gas estimation in transaction bubbles is displayed in a popup however, ive come to realize that 2 popups open instead of one. This is a new bug of …

fix: gas estimate error

---

ui/app/AppLayouts/Wallet/WalletHeader.qml
ui/shared/status/StatusExpandableAddress.qml

This introduces a new component to render Addresses that can be
expanded as well as copied using `CopyToClipBoardButton`.
While there's already an `Address` component that allows for expansion,
it doesn't give us control over it's look and feel and, should rather
be a `Button` anyways.
There's also cases in the application where we render a collapsed address
and don't allow for expanding it. In such cases, we might not want/need
a button at all.
Might make sense to introduce a separate address component that just shows
a collapsed address without any behaviour, which can then be used inside
`StatusExapandableAddress`.
Closes #1633

feat: introduce StatusExpandableAddress component

---

ui/shared/CopyToClipBoardButton.qml

The background color of the component was hard coded to grey.
This commit changes it to `backgroundHover` so it looks consistent
in dark and light themes.

uiux(CoptyToClipBoardButton): make hover state work in all themes

---

ui/shared/status/StatusChatInfo.qml

With the recent addition of the `muted` property in this component,
the `width` is no longer reliably calculated. Sometimes it can happen
that the muted bell icon jumps out of the component. This is very apparent
inside of a `StatusChatInfoButton`.
This commit ensure that the width of this component always includes all
of its children, fixing the ui bug mentioned above.

fix(StatusChatInfo): ensure component width is calculated properly

---

src/app/chat/view.nim

Fixes #1317
This was already implemented before, but if you muted/unmuted the active channel, the icon didn't appear

fix: update muted channel state if the channel is the active one

---

package.json

The actual fix was applied to the `master` branch of the status-im/create-dmg repo (a fork of the upstream sindresorhus/create-dmg repo).  However, in this repo's `package.json` the dependency on Status' fork is specified (implicitly) as that repo's `master` branch. Instead, specify a (short) SHA-1 hash (committish) for our fork so that if a change to status-im/create-dmg introduces a build problem/failure it will be easier to track down in this repo's commit history.

fix: inside packaged macOS builds 'OPEN ME.webloc' should be a file not a symlink

---

src/app/chat/view.nim
ui/app/AppLayouts/Chat/ChatColumn/TopBar.qml
ui/app/AppLayouts/Chat/ContactsColumn/Channel.qml
ui/app/AppLayouts/Chat/components/ChannelContextMenu.qml
ui/app/AppLayouts/Chat/components/GroupInfoPopup.qml

This commit does a bunch of things:
- First and foremost, it removes the active channel dependency.
This is needed to have it operate on the correct channel object,
without forcing us to change the active channel (e.g. right-clicking
on a channel item that's not active, will make it active eventually)
- To make that work, this commit changes the `ChannelContextMenu`
to receive a `ChatItemView`, so it can be used for things like determining
what menu options are shown, what members are in a group, whether
someone is admin of a group etc.
- This also required a new `QtProperty` called `contextChannel`.
The reason this is required, is because in some cases, like receiving
members count of groups, we need a complete `ChatItemView` object
as we don't have access to certain APIs otherwise.
- …

refactor(ChannelContextMenu): remove dependency on active channel

---

ui/app/AppLayouts/Profile/Sections/ContactsContainer.qml

There's a but in the app's profile section where the link to
invite friends is never rendered, even if the currently logged-in
user has no added contacts.
This is because the UI refers to the count of *all* contacts the
user has (even removed ones - remember that, once added, removing
a contact is only done by removing a tag).
This commit ensures that the invitation link is rendered by
relying on the *added* contacts list. It also prevents the
"blocked contacts" button from rendered when there's no blocked
contacts.

fix(Profile): ensure invite friends link is rendered

---

ui/app/AppLayouts/Profile/Sections/ContactsContainer.qml
ui/imports/Themes/DarkTheme.qml
ui/imports/Themes/LightTheme.qml
ui/shared/status/StatusRoundButton.qml

The `StatusRoundButton` was missing the `hoverEnabled` flag, causing it
to not turn the cursor into a pointer when the component is hovered.
It's also not rendering the proper hover color.
This commit fixes that to improve usability and look & feel.

fix(StatusRoundButton): enable and correct hover on component

---

ui/app/AppLayouts/Chat/components/GroupChatPopup.qml
ui/app/AppLayouts/Chat/components/GroupInfoPopup.qml
ui/app/AppLayouts/Profile/Sections/ContactsContainer.qml
ui/imports/Themes/DarkTheme.qml
ui/imports/Themes/LightTheme.qml
ui/shared/status/StatusRoundButton.qml

There are some places in the application where a custom round
button has been implemented, which essentially can be realized
using our `StatusRoundButton`. This commit addresses those cases.

refactor: replace custom buttons with StatusRoundButton

---

ui/app/AppLayouts/Wallet/SetCurrencyModal.qml
ui/app/AppLayouts/Wallet/WalletHeader.qml

There's a bug in the `SetCurrencyModal` where it runs into a callstack size
exceeded error because we're calling it's `open()` API to open itself.
That function happens to call itself again and again.
The reason that API was introduced in the first place, was to ensure that
the configured default currency is reflected currectly.
This commit fixes that issue by getting rid off the `open()` and `close()`
APIs which cause the mentioned error, and rely on `openPopup`'s parameters
configuration instead.

fix(SetCurrencyModal): fix callstack size exceeded error

---

ui/app/AppLayouts/Chat/ChatColumn/TopBar.qml

This was missing in one of our previous PRs and causes the
channel context menu to not function properly e.g. when deleting
chats, it currently always deletes the first chat in the channel list
instead of the active channel.

fix: make sure context menu receives correct channel index

---

ui/app/AppMain.qml

Having the Timeline component loaded eagerly made switching
between channels rather slow because it always tries to read
the current message list from the chats model.
This commit changes the layout so that the timeline layout container
is only loaded conditionally when indeed activated.

chore: improve channel switch perf

---

docs/qml_api.md

Add all publically exposed QtProperties, Signals, Methods (slots), and partial view models for the Wallet Model.

chore: Add Wallet Model QML API documentation

---

src/app/chat/views/reactions.nim

Turns out message reactions weren't functional in 1 on 1 chats.
Reaction signals come with a `chatId` that they correspond to, which is
then used to determine to channel and message list to apply/remove
the reaction to.
Inside of a 1 on 1 chat, the `chatId` of a reaction coming from the
will always be the pubKey of the the user that receives it.
A user however, usually doesn't store a chat item for her own pubKey
unless it's of type `Profile`.
This results in an illega storage access as reported in #1828
This commit fixes this bug by checking whether the reaction `chatId`
matches the user's `pubKey`. If that's the case, we know that the reaction
corresponds to the reaction's `fromAuthor` chat.
Fixes #1828

fix: make reactions in 1-on-1 chats work

---

ui/app/AppLayouts/Chat/ChatColumn/Message.qml
ui/app/AppLayouts/Chat/components/MessageContextMenu.qml
ui/shared/PopupMenu.qml

This commit adds a menu item to the message context menu to
copy links that may exist inside of a message.
There are three possible scenarios:
1. There's no link in the message, which causes the menu to not
render the dedicated menu item at all
2. There's one link in the message, which renders an additional
`Action` with a copy-to-clipboard functionality
3. There are multiple links in a single message. This adds a
nested `PopupMenu` in the existing menu with menu items for each
link extracted from the message
To make this work there were some changes in the `PopupMenu` component
needed, as it wasn't take the sub menu's `enabled` state into account
properly. This makde it always render nested menus even when they
should've been invisible.
Closes: #1733

feat(MessageContextMenu): add copy link actions

---

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChannelIdentifier.qml

In some cases inside of 1-on-1 chats, the fake messages added to
the beginning of the message list, wouldn't determine the correct
username of the contact in question.
This commit explicitly calls `chatsModel.userNameOrAlias()` instead
of relying on `activeChannel.name` which tries to do the same.

fix(Chat): ensure correct contact username is shown

---

ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml
ui/app/AppMain.qml
ui/main.qml

This reverses the chatMessages ListView so that the start is actually the Bottom. This, paired with Richard's StackLayout change should make the channel switching very fast

Fix channel scroll issues + errorSound

---

ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml

Before that fix, the profile image was put on your last message instead of your first, making it look like your previous message was said by the person above you

fix: fix profile image order since reversing the list order

---

ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml

For an unknown reason, when the `chatLogView` ListView uses
a `verticalLayoutDirection: BottomToTop`, it prevents the application
from successfully rendering during login and crashes.
From debugging this, we know that this only happens when the above
condition applies *and* when a `DelegateModel` is used.
The delegate doesn't even need proper data, it application would still
crash.
We found out that the crash can be avoided when another `ListView` exists
in this component (however it's unclear why).
For now this commit adds such a placeholder `ListView` until it
we know more about what's going on.

chore: add dummy ListView to ChatMessages to avoid app crash

---

src/status/contacts.nim
ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml

In https://github.com/status-im/status-desktop/commit/31a9d1a6f we've fixed
a bug where a contact's thumbnail hasn't been passed to the `saveContact`
API.
Unfortunately, that fix wasn't memory safe. There are cases when a contact's
`identityImage` is `nil`, resulting in illegal storage access when accessing
a contact's thumbnail.
This commit fixes the issue by safe guarding around `identityImage` possibly
being `nil`.

fix(libstatus): make saveContact API memory safe(r)

---

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/InvitationBubble.qml
ui/app/AppLayouts/Chat/CommunityComponents/CommunityDetailPopup.qml

When the communities code was moved into its own view in https://github.com/status-im/status-desktop/commit/b38d1df59
it broke the functionality to join communities again.
Qt complains that the Nim API in use `chatsModel.communities.joinCommunity`
expects two parameters, when it's call with just one.
This is unexpected because the API in question set a default value
for its second parameter.
To make this work again, we have to make sure the `setActive`
parameter is supplied every time we call the API from
within QML.
Also, worth noting that this is not the first time we're running into
a scenario like this.

fix(Communities): make rejoining communities work

---

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/InvitationBubble.qml
ui/app/AppLayouts/Chat/CommunityColumn.qml
ui/app/AppLayouts/Chat/CommunityComponents/CommunityDetailPopup.qml

Very similar to #1986, we're trying to access the `activeCommunity`
property on the `chatsModel` object, which doesn't have such a property
anymore every since we've moved communities into its own view.
This causes errors when trying to create channels.
This commit fixes this bug by ensuring `activeCommunity` is accessed
from `chatsModel.communities` instead.

fix(Communities): make creating channels work again

---

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/InvitationBubble.qml
ui/app/AppLayouts/Chat/CommunityColumn.qml
ui/app/AppLayouts/Chat/CommunityComponents/CommunityDetailPopup.qml

Turns out in https://github.com/status-im/status-desktop/commit/81bb7fcc6 we've introduced a regression where
leaving a communities isn't possible anymore because we're trying
to call an API that doesn't exist on the `chatsModel`.
This commit fixes it by ensuring the API is called from `chatsModel.communities`.

fix(Communities): make leaving communities work again

---

ui/app/AppLayouts/Chat/CommunityComponents/CreateCommunityPopup.qml
ui/app/AppLayouts/Profile/Sections/ChangeProfilePicModal.qml
ui/shared/CropCornerRectangle.qml
ui/shared/ImageCropper.qml
ui/shared/ImageCropperModal.qml

Fixes #1981
This adds a ratio to the image cropper, more specifically for the profile image and community image that need square images.
It is not the cleanest that it could be, but it's best I could do with my current knowledge and my level of being tired of working on this (🙃)
Here is a demo:
https://user-images.githubusercontent.com/11926403/110144925-e54cf080-7da6-11eb-8a71-0badf890324a.mp4

Add image cropper ratio

---

ui/app/AppLayouts/Chat/CommunityComponents/AccessExistingCommunityPopup.qml

In https://github.com/status-im/status-desktop/commit/a90a30af1 we've introduced the functionality to import
communities through the UI via a community private key.
That private key is being validated before it gets imported.
For some reason, validation has been removed in another refactor
later on in https://github.com/status-im/status-desktop/commit/534cb23e1, rendering the import
functionality broken.
This commit re-introduces the `validate()` method to make importing
communities work again.

fix(Communities): make validation on community import work again

---

src/app/chat/views/communities.nim
src/status/chat.nim
src/status/libstatus/chat.nim
ui/app/AppLayouts/Chat/CommunityComponents/AccessExistingCommunityPopup.qml

Prior to this commit we were ignoring the returned response of the
API call, making it impossible to work with it in case it's needed.

fix(Communities): ensure importCommunity API returns response

---

src/app/chat/views/communities.nim
src/app/chat/views/community_item.nim
src/app/chat/views/community_list.nim
src/status/chat.nim
src/status/chat/chat.nim
src/status/libstatus/chat.nim
src/status/signals/messages.nim
ui/app/AppLayouts/Chat/CommunityComponents/AccessExistingCommunityPopup.qml
ui/app/AppLayouts/Chat/CommunityComponents/CommunityList.qml
ui/shared/status/StatusIconTabButton.qml
ui/shared/status/StatusLetterIdenticon.qml

Prior to this commit, communities without an image would render invisible
in the navigation bar of the application. To avoid this, we're now falling
back to our StatusLetterIdenticon component, which renders the first letter
of the community name with the color of the community.

fix(Communities): fallback to letter identicon if no image available

---

ui/app/AppLayouts/Chat/CommunityComponents/CommunityHeaderButton.qml
ui/app/AppLayouts/Chat/CommunityComponents/CommunityWelcomeBanner.qml

The `communityProfilePopup` relies on the currently `activeCommunity` to
get its data. Unfortunately, once read, even when `chatsModel.setActiveCommunity()`
is called which triggers `activeCommunityChanged`, the data in the popup
won't be updated. The next time one would open a community profile page,
it'd have the data that was previously received from the model.
This commit ensures that the popup is hydrated with the most recent data
by explicitly updating its properties right before it's opened.

fix(Communities): ensure profile popup is hydrated with correct data

---

ui/app/AppLayouts/Chat/CommunityComponents/CommunityDetailPopup.qml
ui/app/AppLayouts/Chat/CommunityComponents/CommunityHeaderButton.qml
ui/app/AppLayouts/Chat/CommunityComponents/CommunityWelcomeBanner.qml

Prior to this commit there was a scenario where the application would
crash due a memory bug when attempting to (re)join a community.
The scenario is as follows:
1. User creates or has been invited to community with `ON_REQUEST` permissions
2. User leaves community
3. User decides to rejoin, so she selects the community she's been part
of and hits the "Join" button
At this point Status Desktop would send a new `RequestToJoin` request, as the
community has a corresponding permissions setting.
This would then result in an `already a member` error in status-go, because
status-go checks whether the requestee is already part of the members list of
the community. The error isn't handled inside Status Desktop which causes
a crash because we're trying to access data in memory that doesn't exist. …

fix(Communities): don't crash on rejoin attempt

---

ui/app/AppLayouts/Chat/CommunityComponents/CommunityHeaderButton.qml
ui/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopup.qml
ui/app/AppLayouts/Chat/CommunityComponents/CommunityWelcomeBanner.qml

This was hardcoded into `isAdmin` for some reason. It also seems that the
property isn't actually used anywhere in the profile popup, so we might
as well get rid off it.

fix(Communities): properly pass `admin` state to profile popup

---

src/app/chat/view.nim
src/app/utilsView/view.nim
src/status/chat.nim
src/status/libstatus/chat.nim
ui/app/AppLayouts/Chat/ChatColumn.qml
ui/app/AppLayouts/Timeline/TimelineLayout.qml
ui/app/AppMain.qml
ui/imports/Constants.qml
ui/imports/Utils.qml
ui/main.qml
ui/shared/status/StatusChatImageExtensionValidator.qml
ui/shared/status/StatusChatImageQtyValidator.qml
ui/shared/status/StatusChatImageSizeValidator.qml
ui/shared/status/StatusChatImageValidator.qml
ui/shared/status/StatusChatInput.qml
ui/shared/status/StatusChatInputImageArea.qml

Closes #1374 
Allow up to 5 images to be dragged and dropped in to one-on-one chats and in the timeline. Can be combined with the existing upload button. The upload file dialog has been changed to allow multiple selections. Drag and dropped images adhere to the following rules, with corresponding validations messages:
- Max 5 image
- Image size must be 0.5 MB or less
- File extension must be one of [".png", ".jpg", ".jpeg", ".heif", "tif", ".tiff"]
Drag and drop and uploaded images are now also deduplicated.
1. There is a console message that appears sometimes when uploading an image via the `FileDialog` component "Model size of -5 is less than 0", however this does not appear to be an error and might be related to known bugs: https://bugreports.qt.io/browse/QTBUG-79168 and …

feat: drag and drop images

---

ui/app/AppLayouts/Chat/CommunityComponents/CommunityHeaderButton.qml
ui/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopup.qml
ui/app/AppLayouts/Chat/CommunityComponents/CommunityWelcomeBanner.qml
ui/shared/ModalPopup.qml

In the recent past we've improved our `ModalPopup` to allow for a bit more control
when it comes to rendering a modal footer section with call-to-action items.
The footer section is rendered when there's `footerContent` and when the height
of the footer content is > 0. This means it's possible to also hide the footer content
section from the modal, even when there's footer content children.
However, there's a separator rendered whenver the footer is visible, regardless of its
height. This results in undesired behaviour when rendering footer children of height 0.
To avoid this, this commit adjust the condition so that the separator is only rendered
when the footer visible AND the height of it is > 0.

feat(ModalPopup): hide footer section if footerContent height is 0

---

ui/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopupMembersList.qml

There's no `parent` in that componen, which results in a QML type error
at runtime.

fix(Communities): remove type error in item width

---

src/app/chat/views/message_list.nim
src/app/chat/views/sticker_pack_list.nim
src/status/chat/message.nim
src/status/signals/messages.nim
ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml
ui/app/AppLayouts/Chat/ChatColumn/Message.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/MessageMouseArea.qml
ui/app/AppLayouts/Chat/ChatLayout.qml
ui/shared/status/StatusStickerPackClickPopup.qml

Displays a popup containing all the packs that belong to a sticker pack
This option is only available after all the stickers packs have been loaded. 
Video:
https://user-images.githubusercontent.com/1106587/110371347-3b2dcc80-8023-11eb-9d50-209dfcf25ee0.mp4

feat: see stickers details when clicking on a sticker

---

ui/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopup.qml
ui/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopupMembersList.qml
ui/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopupOverview.qml

Prior to this commit, the community memberlist was represented in a nested modal
which doesn't adhere to the designs. Rather, the section should render inside the
existing modal, requiring it to be refactored using a `StackView`.
This commit refactors the community profile popup so that the different content
sections ("Overview" and "MemberList") are rendered inside of the popup and can
be pushed onto and popped off a stack view.
The content components (newly introduced in this commit) `CommunityProfilePopupMembersList`
and `CommunityProfilePopupOverview` need to define a `headerTitle`, `headerDescription` and
if needed `imageSource` so they can alter the modal's header.
The same pattern might be used in other places of the modal if required.
Partially fixes #1959

refactor(Communities): use StackView inside profile popup for memberlist

---

src/status/libstatus/chat.nim

We've introduced a regression in https://github.com/status-im/status-desktop/commit/f1e83f74b#diff-f35edd413addd14c1f81816d6b5ee2bcbdf85fa0e3295d324cb78c98e26d4327L364 where we check whether an RPC's `error` is `null`
and its `result` is not `null`.
This breaks the application with an illegal storage access,
as in case of a successful API call, the response will have only a `result` key
(even when it's `null`).
Since we haven't done anything with a possible `error` in the reponse even before
that change was made, this commit removes the `error` check and safe guards around
whether `result` exists.
Fixes #2062

fix(libstatus): add safety check before accessing API response

---

ui/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopupMembersList.qml

This change aligns the member list's look & feel of the community profile popup
with the designs by implementing the proper member list items styles, hover effects
and fine-tuning the context menu.
**This commit also comments some of the actions provided by the context menu,
which aren't implemented yet. There's no point in having UI components that don't or
can't function.**
Those will be re-introduced once they are actually implemented.
Closes #1959

refactor(Communities): make member list look as intended

---

src/app/chat/views/communities.nim
src/status/signals/messages.nim
ui/app/AppLayouts/Chat/ChatColumn/Message.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/InvitationBubble.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/LinksMessage.qml
ui/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopupOverview.qml
ui/app/AppLayouts/Chat/CommunityComponents/InviteFriendsToCommunityPopup.qml
ui/app/AppLayouts/Chat/CommunityComponents/MembershipRequestsButton.qml
ui/app/AppLayouts/Chat/components/ProfilePopup.qml
ui/app/AppLayouts/Profile/Sections/MyProfileContainer.qml
ui/app/AppMain.qml
ui/imports/Constants.qml
ui/imports/Utils.qml

Fixes #1878
Unfurls community links in chat. If the community is not known, shows a generic unfurling.
Also adds unfurling for public chats
Community link:
Public chat link:

Unfurl community links in chat

---

ui/shared/Separator.qml

Sometimes, `Separator` is used inside context menus to separate groups
of actions that belong together. The separator in itself doesn't have any
padding or margins in this case because the just gets transcluded as is
in the context menu, between menu items.
There are cases in the design where a padding/margin is desired though.
This change makes that possible by wrapping the separator `Rectangle` with
another `Rectangle` which controls a custom height (if desired). The inner
rectangle is then just always vertically center.
In practice this means, existing usages of `Separator` behave exactly the same,
they don't break. In addtion one can set `Separator { height: x }` while maintaining
a 1px separator line.

feat(Separator): enabled custom separator height

---

.gitignore
.gitmodules
src/app/chat/views/stickers.nim
src/app/wallet/view.nim
src/nim_status_client.nim
src/status/ens.nim
src/status/libstatus/eth/contracts.nim
src/status/libstatus/settings.nim
src/status/libstatus/stickers.nim
src/status/libstatus/tokens.nim
src/status/status.nim
src/status/stickers.nim
src/status/tasks/stickers.nim
src/status/tasks/task_manager.nim
src/status/tasks/threadpool.nim
src/status/wallet.nim

The `TaskManager` threadpool is a memory-safe replacement for the `spawnAndSend` operations that are currently causing memory issues in status-desktop.
From a fundamental memory management point of view, `libstatus/settings`, `libstatus/contracts`, and `libstatus/tokens` (custom tokens) have all been converted to `{.threadvar.}`s and `Atomic[bool]`s to maintain the cache and `dirty` flag across threads, respectively, eliminating the need for thread locks and incorrect `{.gcsafe.}` compiler overrides. ~NOTE: there is one remaining `{.gcsafe.}` left to remove -- it is in `libstatus/stickers.getPackData`, and it is due to the `edn.nim` dependency relying on global variables to do its decoding.~ (this has been removed with changes in https://github.com/status-im/edn.nim/pull/1)
The successful …

feat: introduce Task Manager threadpool

---

src/app/chat/views/stickers.nim
src/status/stickers.nim
src/status/tasks/common.nim
src/status/tasks/stickers.nim
src/status/tasks/threadpool.nim
src/status/wallet/collectibles.nim

Move the remaining stickers `spawnAndSend` (`obtainAvailableStickerPacks`) into a threadpool task.
refactor: create a base class for tasks models to inherit from
NOTE: this branch is based off of `experiment/tasks-3` and should be rebased on master once that branch is merged.

feat: stickers spawnAndSend to threadpool task

---

ui/shared/Separator.qml

This was a regression introduced in https://github.com/status-im/status-desktop/pull/2065.
The new wrapping Rectangle would get the color that is possibily passed down
to Separator. Instead it should get properly bound to the actual separator.

fix(Separator): ensure custom color works as expected

---

ui/app/AppLayouts/Profile/Sections/BrowserModals/EthereumExplorerModal.qml
ui/app/AppLayouts/Profile/Sections/BrowserModals/HomepageModal.qml
ui/app/AppLayouts/Profile/Sections/BrowserModals/SearchEngineModal.qml
ui/app/AppLayouts/Profile/Sections/FleetRadioSelector.qml
ui/app/AppLayouts/Profile/Sections/FleetsModal.qml
ui/app/AppLayouts/Profile/Sections/MutedChatsModal.qml
ui/app/AppLayouts/Profile/Sections/NetworkRadioSelector.qml
ui/app/AppLayouts/Profile/Sections/NetworksModal.qml
ui/app/AppLayouts/Profile/Sections/OpenLinksWithModal.qml
ui/shared/status/StatusRadioButtonRow.qml

There were cases in which this component was used and its `checked` state wasn't
properly emitted to the underlying component.
This commit fixes that by ensuring the `MouseArea` only alters the radio button's
`checked` state and let the radio button handle the event propagation.

fix(StatusRadioButtonRow): ensure checked state is propagated properly

---

ui/app/AppLayouts/Chat/ChatColumn/SuggestionFilter.qml
ui/imports/Constants.qml
ui/imports/Emoji.qml
ui/shared/status/StatusChatInput.qml

Fixes #1957
Makes the mentions in the input highlighted as well as in the chat.
This was harder than the other text formations, because mentions don,t wrap the name, they just have an `@` before them and they sometimes have 1 word, sometimes 3.
So I had to create a new deparse "tag" called `[[mention]]`. that way, when we deparse, we add those around so that when we parse back to "normal" text, we remember to add back the styling to highlight. When we send the message, the `span`s are all removed so we just send the normal message as before.

feat: highlite mentions in the chat input as well

---

src/app/profile/views/contacts.nim

There was a bug introduced https://github.com/status-im/status-desktop/commit/2ac67f95a where we'd rely on the
possibly resolved public key, which is passed to `generateAlias()`.
The public key is never guaranteed to be an actual key (if resolution fails,
it's a an empty string). Passing an empty string to `generateAlias()` causes
`status-go` to crash and we don't handle that error.
This commit ensures that we only attempt to generate an alias when we
indeed have a successfully resolved public key.

fix(Contacts): ensure app doesn't crash when contact can't be resolved

---

src/app/profile/views/contacts.nim
ui/app/AppLayouts/Chat/components/PrivateChatPopupSearchResults.qml

This commit introduces a `reset()` function so that search results inside
the application can be easily reset. It also introduces a `resultClickable`
flag which allows consumers of this component to decide whether a search result
is clickable and emits a dedicated event.
This is useful when UIs should only allow actions via the result icon button
(as it's the case with the new add-to-contact modal).

feat(PrivateChatPopupSearchResults): introduce reset() and config API

---

src/app/wallet/view.nim
src/status/libstatus/settings.nim
src/status/libstatus/tokens.nim
src/status/wallet.nim
ui/app/AppLayouts/Wallet/components/TokenSettingsModalContent.qml

We used to set the settings as dirty only when the `saveSettings` failed, so that meant that in a best case scenario, the settings would **never** be set as dirty.
Dirty means that out local cache needs to be updated when fetching a new setting.
Apart from that, I also made the asset fetch more performant and also removed the useless parameters

fix: fix settings not being refetched when they had been edited before

---

src/app/chat/view.nim
src/app/chat/views/message_list.nim
ui/app/AppLayouts/Chat/ChatColumn.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatText.qml
ui/app/AppLayouts/Timeline/TimelineLayout.qml
ui/imports/Utils.qml
ui/shared/status/StatusChatInput.qml
ui/shared/status/StatusChatInputReplyArea.qml

Fixes #2016
Fixes #2088
Fixes the bug where three word names didn't work for some users. The problem was that we added a new way to get suggestions, since contacts are not reliable. that new way involved parsing the messages to get all the users, but in the Nim side, we didn't have that same list of contacts, so when we matched the name with our list, it didn't find it.
To fix it, I now pass the list we created in QML to Nim so that it can use it, but I made it optional, so that the status update send works too.
The other bug was that mentions showed as the pubkey in the mention  text. I fixed it by rendering the message correctly using the data function, also I now show the style and use RichText. It disables the use of Elide because of a QT bug, but I hide the excess so it doesn't look …

Fix mentions not showing correctly

---

ui/main.qml

increase min width to 1280px so as to fix #1918
(1024px still has overlap issues)

fix: increase min width to alleviate overlaps

---

ui/shared/status/StatusChatInput.qml

There was a UI bug in the StatusChatInput where, only in the timeline view,
the scrollview wrapping the textarea would have a weird behaviour in which
it would render the visible text(placeholder) *lower* than how it's actually
positioned. Once the textarea is clicked, it would re-adjust with a smooth
scroll.
Obviously this is undesired behaviour as the text should always render in the
correct position.
This commit finally fixes this weird behaviour by moving the dynamic height
calculation to the wrapping Rectangle and changing the textarea's top- and
bottom paddings dynamically.
Fixes #2018

fix(StatusChatInput): fix text area alignment so it doesn't jump

---

src/app/chat/views/message_list.nim

Two fake messages are usually added to chat message lists inside a channel or
chat:
- One that imitates a chat identifier
- one that creates a button to fetch older messages
These two fake messages are added so it's ensured they show up at the beginning
of the chat.
The status timeline is also just a list of messages (filtered by a certain message
type), however there's no need to render these fake messages in this scenario.
That's why a `addFakeMessages` flag has been introduced which conditionally adds
those fake messages here: https://github.com/status-im/status-desktop/commit/3f012dbf0#diff-6aa545137319516beb03623bc6a9750e1d14a40c68d8868b5a672320fc4d680aR69
At some point, possibly around here (https://github.com/status-im/status-desktop/commit/8ee5abe57), the fake message for
the …

fix(Timeline): remove "fetch more" fake message

---

ui/main.qml

this increased width causes issues for people that want to have the window side by side with others, we should find an alternative solution for #1918

Revert "fix: increase min width to alleviate overlaps"

---

src/app/wallet/views/token_list.nim
ui/app/AppLayouts/Wallet/AddCustomTokenModal.qml
ui/shared/Input.qml

Fixes: #2036.
When contract addresses that are not ERC-20 or ERC-721 were input, the token would be allowed to be added and would crash the app.
In addition, when an ERC-20 contract was deployed without a name and symbol, “Invalid ERC-20 address” would appear.
This PR adds error checking from the token detail lookup and reports the error back to the user in the modal. This prevents non-ERC-20/721 contracts from being able to be added to the app and prevents a crash.
Here you can see the error message when attempting to add the SimpleStorage contract as a custom token:

fix: custom token validation for non-token addresses

---

ui/app/AppMain.qml

Prior to this commit, we would only set the translation package for the
application's engine when `appSettings.locale !== "en"`.
This is problematic because it seems that `engine` is already provided with
a system default that may not be `en`. In practice, this means that, initially,
engine is loaded with, say `de`. `appSettings.locale` might be `en` but because
we're only loading the correct translation package when it's **not** `en`,
the application will stay in `de`.
Changing the language to `en` at runtime is fine, however once the application
is restarted, `engine` is again initialized with some other possible system default.
It seems that we should *always* load the translation packge when `appSettings` are
loaded.

fix: enforce locale provided by appSettings

---

src/app/chat/views/chat_item.nim

This was caused by the fact that the canPost property was not exposed from the ChatItem model.
I'm actually not sure why it didn't show an error trying to call  a function that doesn't exist

fix: fix unable to write to invite only community channels

---

ci/Jenkinsfile.linux
ci/Jenkinsfile.macos
ci/Jenkinsfile.windows
docs/README.md

Desktop build artifacts are taking up far too much space.
Also, noticead that `README.md` title is outdated.

CI - Lower number of artifacts kept

---

ui/app/AppLayouts/Wallet/SignPhraseModal.qml

This is what it looks like right now:

fix(Wallet): prevent signing phrase from leaking out of modal

---

ui/shared/status/StatusIconTabButton.qml

fix: fix community button staying active when clicking on a new section

---

src/app/utilsView/view.nim
ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml
ui/imports/Constants.qml

Fixes #2121
Makes the scroll twice as fast as before on Windows. It's also possible to customize the other OSes.
Let me know if it's too fast or still too slow @johnlea-quiup

fix: fix scroll speed on Windows

---

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/CompactMessage.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/MessageMouseArea.qml

Fixes #2126
I was not able to reproduce the wrong sticker shown, but I changed the conditions to be more restrictive, so hopefully, it should not happen again.

fix: fix sticker click modal to only open on sticker click

---

ui/app/AppLayouts/Chat/CommunityComponents/InviteFriendsToCommunityPopup.qml
ui/app/AppLayouts/Chat/components/PrivateChatPopup.qml
ui/app/AppLayouts/Chat/components/qmldir
ui/app/AppLayouts/Profile/Sections/ContactsContainer.qml
ui/nim-status-client.pro
ui/shared/ContactsListAndSearch.qml
ui/shared/ExistingContacts.qml
ui/shared/InviteFriendsPopup.qml
ui/shared/NoFriendsRectangle.qml
ui/shared/SearchResults.qml

Fixes #2138 
I did so by extracting the Start a new chat (one on one) field and components to a shared component.  That way, there is close to no duplication.

Add chat key, search and ENS field to the community invite

---

ui/shared/status/StatusChatInput.qml

Fixes #1926
It's not possible to know the exact position of the selected text (as far as I know), so instead I either do the average of mouse start position and the final position OR in the case of  a double click, show the menu on top of the double click

fix: show formation menu in middle of selection or above double click

---

src/app/chat/view.nim

ENS search was executed in a task runner task. The task had a mistake during the copy/paste port from spawnAndSend.

fix: ens search hang

---

ui/app/AppLayouts/Chat/CommunityComponents/CommunityList.qml
ui/app/AppMain.qml

Fixes #2154
The communities api doesn't return the date of joining or creation, but it always returns them in order of oldest to newest, so it was only a matter of inverting the display order.
Later, we can implement drag and drop and save that order, hopefully in the DB
In this picture, the communities were created from 1 to 3

fix: order joined communities from newest to oldest

---

ui/app/AppLayouts/Profile/Sections/Contacts/ContactList.qml

When the profile popup is opened inside the contacts list, it doesn't have
a surrounding window context (`Popup` types should usually be used within `ApplicationWindow`
or `Window` components as per https://doc.qt.io/qt-5/qml-qtquick-controls2-popup.html).
This is problematic when popup are nested, like it's the case with the
nickname popup that will be instantiated by the profile popup.
With no window context, such nested popup can't be opened by the application.
This commit ensures the profile popup is created with a proper context,
fixing the issue that the nickname popup won't open when visting via
contacts list.
Fixes #2216

fix(Profile): ensure profile popup has window

---

ci/Jenkinsfile
ci/Jenkinsfile.combined
ci/Jenkinsfile.linux
ci/Jenkinsfile.macos
ci/Jenkinsfile.windows

This is part of a general restructuring in layout of Jenkins job folders before we can properly introduce Release signing and notarization.  We need this to distinguish between pr/dev builds and release ones to avoid signing the dev builds with a release certificate.
The meta job managed with `ci/Jenkinsfile.combined` runs a job for all 3 platforms and currently is quite basic, but in the future can be extended to include - like the mobile one - updating the nightlies page, or publishing draft GitHub releases.
The addition of `make check-pkg-target-*` steps to other `Jenkinsfile`s is necessary because the sub-jobs under [`platforms`](https://ci.status.im/job/status-desktop/job/platforms/) have no option for checking out Git submodules at the beginning, so I'm making use of how the …

CI: Add a combined Jenkinsfile for releases

---

Makefile
config.nims

bintray (for open source) is shutting down permanently on May 1:
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
At this time downloading from GitHub Packages requires specifying a username and personal acccess token, but it seems they don't have to be valid. For example, in the changes to the Makefile I specified `_:_` as the username and token.
Also, change the minimum macOS version from 10.13 to 10.14 since Homebrew bottles are no longer built for 10.13 (High Sierra):
https://github.com/Homebrew/discussions/discussions/1264#discussioncomment-601544
Closes #1851

build: fetch macOS Homebrew bottles from GitHub Packages instead of bintray

---

Makefile
ci/Jenkinsfile.macos
scripts/fetch-brew-bottle.sh

See #2255. With the changes made in this PR, to build the app on macOS it will be required to have `GITHUB_USER` and `GITHUB_TOKEN` set in the shell environment where `make` is run.
To generate a personal access token, on the GitHub website open your profile's *Settings*, then go to *Developer settings*, then *Personal access tokens*, then *Generate new token*,  assign it the `read:packages` scope and then at the bottom click the green *Generate token* button.
@jakubgs if it's okay for it to work in Jenkins the same way it's intended to work locally, then `GITHUB_USER` and `GITHUB_TOKEN` will need to be setup in the Jenkins environment.
If instead we're going to pin the bottles then in the Makefile I'll need to add some more environment variables and change the logic a bit more.
--- …

build: use GitHub credentials when downloading bottles for macOS

---

Makefile
scripts/fetch-brew-bottle.sh

It's not supported to run `brew update` multiple times simultaenously. A better fix for this can be implemented, but for now in the Makefile have target `bottles/pcre` depend on target `bottles/openssl` so that they run serially when `-jN` is passed to `make`.
I was originally going to change `brew update >/dev/null` to `brew update >/dev/null || true` but decided the Makefile change provides a better guarantee that simultaenous `brew` commands won't interfere with each other. In the process, I revised some of the script's `echo` output just a bit.

fix: don't run scripts/fetch-brew-bottle.sh in parallel

---

ui/app/AppLayouts/Chat/CommunityComponents/CreateChannelPopup.qml
ui/app/AppLayouts/Chat/CommunityComponents/CreateCommunityPopup.qml
ui/shared/ImageCropper.qml
ui/shared/ImageCropperModal.qml

Fixes #2050.
This PR contains changes to fix the name validation for new communities and new channels in communities. In the process of updating this, better validation was also added to both popups (create community and create channel), including the prevention of the "Create" button from being enabled until all form fields were valid.
During this process, it was noticed that the community image cropper was not actually cropping the image *in the preview*. Once the community was created, status-go was successfully cropping the image as the user intended. However, the preview thumbnail prior to creation was not accurately showing the cropped image preview and showing the entire image centred instead. *This is still yet to be fixed.* One solution is to upgrade Qt to `5.15` to take …

fix: create community and channel name validation

---

ui/app/AppLayouts/Profile/Sections/AppearanceContainer.qml
ui/app/AppMain.qml
ui/imports/Style.qml
ui/main.qml

As discussed in https://github.com/status-im/status-desktop/issues/2144#issuecomment-817791172 and https://github.com/status-im/status-desktop/discussions/2145, it's no longer desired
to have different appearance settings across multiple accounts.
Instead, the appearance setting should apply globally to all accounts,
essentially bypassing the individual setting stored in status-go.
This commit introduces a new global setting called `theme` which,
at the time of introducing this commit, can be either:
0 => Light
1 => Dark
2 => System
Because those enum values matches the `AppearanceContainer.Theme` enum,
this commit removes it completely and simply relies on QML's built-in
`Universal.[Light|Dark|System] variants respectively.
Closes #2144

feat: store appearance settings globally across accounts

---

ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml

Fixes: #2246.
Allows emojis to be shown without HTML in the notifications.

fix: remove emoji html from notifications

---

ui/app/AppLayouts/Chat/CommunityColumn.qml

Normal members shouldn't be able to create channels, nor should "leave
channel" be an option of the context menu provided inside of a community.
This commit removes these.

chore(Communities): remove community context menu for non-admins

---

ui/app/AppLayouts/Chat/CommunityColumn.qml
ui/app/AppLayouts/Chat/CommunityComponents/CommunityHeaderButton.qml

Prior to this commit, only admins of a community could open up the community
profile popup from inside the community. However, normal members should be able
to do so too.

fix(Communities): allow everyone to activate community profile popup

---

ui/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopup.qml
ui/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopupInviteFriendsView.qml
ui/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopupMembersList.qml
ui/app/AppLayouts/Chat/CommunityComponents/CreateChannelPopup.qml
ui/app/AppLayouts/Chat/CommunityComponents/InviteFriendsToCommunityPopup.qml

The popup to invite friends to communities has so far always been a brand new
popup that's opened on top of possible existing popups.
The design however, expects that the same section should be shown as part
of a wizard-like process inside of the existing community profile overview
popup, when entered from there.
This commit extracts the invite friends popup section into component that
can be reused as stack view, as well as modal content, to implement both
scenarios.

fix(Communities): make invite popup push onto modal stackview

---

ui/app/AppLayouts/Chat/CommunityComponents/CommunityMembersPopup.qml
ui/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopupMembersList.qml

There's a regression in the application where kicking members from communities
doesn't work anymore. This was due to UI logic being moved to a different model
without updating the corresponding view action.
Fixes #2274

fix(Communities): make kicking members work again

---

ui/app/AppLayouts/Profile/Sections/Ens/TermsAndConditions.qml
ui/shared/AccountSelector.qml
ui/shared/TransactionPreview.qml

Fixes #1872
Elides those values and adds a tooltip to show them completely
(disregard the red text, I had to "cheat" the value to test)
Same for the network fee

fix(TransactionModal): fix values oferflowing

---

ui/app/AppLayouts/Chat/components/ChannelContextMenu.qml

Community channels can't be left, only muted.
Closes #2273

fix(Communities): remove context menu option to leave channel

---

ci/Jenkinsfile.combined
ci/Jenkinsfile.linux
ci/Jenkinsfile.macos
ci/Jenkinsfile.windows

Essentially same thing as: https://github.com/status-im/status-react/pull/12015
Depends on: https://github.com/status-im/status-jenkins-lib/pull/24

ci: bump jenkins lib to make release filenames nicer

---

.gitignore
.gitmodules
Makefile
src/app/utilsView/view.nim
src/nim_status_client.nim
src/nim_windows_launcher.nim
src/status/libstatus/accounts.nim
src/status/libstatus/accounts/constants.nim
src/status/tasks/marathon/mailserver/model.nim

In the repo:
```
$ bin/nim_status_client --help
```
In the packaged app (macOS example):
```
$ cd /Applications/Status.app/Contents/MacOS
$ ./nim_status_client --help
```
Output:
```
Usage:
nim_status_client [OPTIONS]...
The following options are available:
-d, --dataDir      Status Desktop data directory.
```
**Using the option**
```
$ cd ~/status-ci-builds/master/Status.app/Contents/MacOS
$ ./nim_status_client --dataDir:"${HOME}/status-dirs/master"
```
In another terminal:
```
$ cd ~/status-ci-builds/PR-4242/Status.app/Contents/MacOS
$ ./nim_status_client --dataDir:"${HOME}/status-dirs/PR-4242"
```
The path supplied can be relative or absolute, and can be specified with `--dataDir:[path]`, `--dataDir=[path]`, `-d:[path]`, or `-d=[path]`.
Either `:` or `=` must be used, i.e. this *will …

feat: command-line option can be used to specify app's data directory

---

src/app/chat/view.nim

Fixes: #2418.
Chat notifications for one-on-one chats were showing only a user’s alias and not their ENS name if they have one.
This PR now shows a user’s ENS name if they have one, or their alias if they don’t in one-on-one chat notifications.

feat: show ENS name in notifications

---

AppRun
Makefile
build-linux.sh
ci/Dockerfile
ci/Jenkinsfile.linux
docker-linux-app-image.sh
nim-status.desktop

Make the docker-related logic for doing a local packaged build on Linux match with the Jenkins CI build for Linux.
Also fix the problems with packaged builds for Linux (local or CI) where gstreamer errors were displayed in the terminal shortly after app start/login and there was no sound output.
---
~~Until the `statusteam/nim-status-client-build` docker image has been updated, Jenkins CI builds for Linux will still not have sound output. See: https://github.com/status-im/infra-ci/issues/30.~~
Tag `1.0.2` has been pushed to the docker hub: https://hub.docker.com/layers/statusteam/nim-status-client-build/1.0.2/images/sha256-9d9e493b5d1d5e414bb503d8be25009c9afab91c178b3582e1f6281902bb1f4d?context=explore.
---
Closes #2441.

build: use same container as Jenkins CI for local packaged builds on Linux

---

src/app/profile/view.nim

Fixes #2312
This will reset the QT settings of all users, since we change from using the address to using the pubkey.
The reason for that is that the account address also called keyId is somehow not set correctly on first login. The pubkey stays constant on the other hand. So using the pubkey is better.

fix(Settings): fix QT settings not being saved on first start

---

Makefile
ci/Jenkinsfile.combined
ci/Jenkinsfile.linux
ci/Jenkinsfile.macos
ci/Jenkinsfile.windows
docs/windows_signing.md
scripts/sign-windows-bin.sh
scripts/windows_build_setup.ps1

This introduces the `scripts/sign-windows-bin.sh` script which is used
by the `Makefile` to sign application libraries and executables. It also
implements the logic necessary to distinguish between different types of
builds: release and non-release builds.
Some other changes:
* Refactore the `Makefile` target that creates the Windows ZIP to make less verbose.
* Added `Microsoft.VisualStudio.Component.Windows10SDK.10240` to VisualStudio component
* Added `BUILD_TYPE` parameter to `Jenkinsfile`s for different platform builds
Depends on: https://github.com/status-im/status-jenkins-lib/pull/25
Resolves: https://github.com/status-im/status-desktop/issues/2170
Successful release build: https://ci.status.im/job/status-desktop/job/release/job/ci-windows-signing/3/

ci: scripts/sign-windows-bin.sh for signing Windows binaries

---

src/app/chat/signal_handling.nim
src/status/chat.nim
src/status/libstatus/chat.nim
src/status/libstatus/types.nim
src/status/libstatus/wallet.nim
src/status/signals/communities.nim
src/status/signals/core.nim
src/status/signals/types.nim

This commit ensures that, once a community was imported, the application
will listen to the newly introduced `community.found` signal, which will be
emitted by status-go.
The signal exposes a `Community` object that is then used to add a
community item to the community list in the UI.
**This can only land after https://github.com/status-im/status-go/pull/2177 has landed first!**
Fixes #2024

fix(Communities): receive community info after community import

---

ui/app/AppLayouts/Chat/ChatColumn/ChatComponents/ChatCommandModal.qml
ui/app/AppLayouts/Profile/Sections/Ens/RegisterENSModal.qml
ui/app/AppLayouts/Profile/Sections/Ens/SetPubKeyModal.qml
ui/app/AppLayouts/Wallet/SendModal.qml
ui/shared/AccountSelector.qml
ui/shared/status/StatusStickerPackPurchaseModal.qml

Fixes: #2257.
If a user had selected a watch-only address in the wallet, the backend `walletModel.currentAccount` property would also change. When loading a transaction modal, this property was used to set the `selectedAccount` value for the “from” `AccountSelector`, regardless if the account was a watch-only address.
This PR updates the logic for `selectedAccount` such that it will only allow the account to be selected if it is not a watch-only account.

fix: do not show watch-only accounts as “from address”

---

src/app/chat/view.nim
src/status/signals/messages.nim
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatText.qml
ui/app/AppLayouts/Chat/components/ProfilePopup.qml
ui/app/AppMain.qml

Fixes: #2364
The Send Message button click event was erroring due to a refactor that had been done to allow for changing app sections.
This has been updated to follow the current way to change app sections.

fix: Send Message button not working in profile popup

---

ui/app/AppLayouts/Chat/CommunityComponents/TransferOwnershipPopup.qml
ui/shared/Input.qml

Fixes #2419
Makes it so the private key is elided by default so you can see it all from the get-go. If you focus the field, the key will "unfurl" and you can copy it manually.
Otherwise. the Copy button will always copy the whole key

fix(CommunityTransfer): fix private key display to match design

---

Info.dev.plist
Makefile

For notifications to work in local dev builds (`make run`) *and* if the orange development icon is to display properly, it's important to invoke `bin/nim_status_client` in an `.app` bundle-directory that has the correct layout and an `Info.plist`. The `make run` logic for macOS handles all that automatically per the changes in this PR.
Note that sometimes the notifications for dev and prod builds will mysteriously stop working. If that happens (or they're already not working), on macOS open System Preferences -> Notifications. Then scroll until you reach Status and/or StatusDev. If there's an entry for Status, click on it and press the delete key. If there's an entry for StatusDev, click on it and press the delete key.
The next time you run the dev/prod app, macOS will prompt you to allow …

build: modify run logic for macOS dev builds so notifications work

---

src/app/chat/views/communities.nim
src/status/chat.nim
ui/app/AppLayouts/Chat/ChatColumn/Message.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/InvitationBubble.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/LinksMessage.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/UsernameLabel.qml
ui/imports/Utils.qml

Fixes #2290
When we find link in the chat and the community is not part of our list, we fetch it from the mailserver.
Since sometimes the mailserver is not ready at first, we use the event to fetch at the right time.
Then we get the signal from QML and show the unfurled data.
We might want a design for what do show during the loading.
Steps to test:
1. Login in account 1
2. Create a community
3. Click Invite and copy the invite link
4. Paste invite link in a chat where the second account can see it
5. Logout and login with account 2
6. Go in the channel where you can see the link
7. Wait a couple of seconds for the fetch to finish (will need a design)
8. Unfurling appears

Fetch community info from link

---

.gitmodules
src/nim_status_client.nim
ui/generate-rcc.sh

This commit does a couple of things:
- add StatusQ as a dependency (https://github.com/status-im/StatusQ)
our emerging component library
- updates the rcc generation script to follow symlinks as well
- add qrc:/./StatusQ/src as import path
At the time of creating this commit `StatusQ` provides only the StatusIcon
component, but more will be added in the future.
```
import Status.Core 0.1
```
More modules will be added soon (e.g. `Status.Controls`, `Status.Components`, `Status.Popups` etc)

chore: add StatusQ as dependency

---

ui/app/AppLayouts/Chat/ChatColumn.qml
ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChannelIdentifier.qml
ui/app/AppLayouts/Chat/ChatColumn/TopBar.qml
ui/shared/status/StatusChatInfo.qml

Fixes #2384
Adds the "Add to Contact" banner at the top if it's a 1 to 1 chat and the user is not a contact. You can hide it. The banner will come back if you close the app and reopen. It can be changed to be in the settings if wanted.
Positions the chat identifier at the top of the screen when it's empty (or not enough content). We used to have it like that before too, but when we changed the ListView to BottomToTop, we lost it. 
To fake that behaviour, I added a `header` that is invisible and just adds a spacer. I added a big comment in the ChatMessages file to explain how and why it works.

Implement redesign of empty chat

---

src/app/wallet/view.nim
src/status/libstatus/accounts.nim
src/status/wallet.nim
ui/app/AppLayouts/Browser/BrowserLayout.qml
ui/app/AppLayouts/Chat/ChatColumn/ChatComponents/SignTransactionModal.qml
ui/app/AppLayouts/Profile/Sections/Ens/RegisterENSModal.qml
ui/app/AppLayouts/Profile/Sections/Ens/SetPubKeyModal.qml
ui/app/AppLayouts/Wallet/SendModal.qml
ui/app/AppLayouts/Wallet/components/AddAccountWithPrivateKey.qml
ui/app/AppLayouts/Wallet/components/AddAccountWithSeed.qml
ui/app/AppLayouts/Wallet/components/GenerateAccountModal.qml
ui/imports/Utils.qml
ui/shared/status/StatusStickerPackPurchaseModal.qml

Fixes #2448.
Currently, if a wrong password is entered when generating a wallet account, the app will crash due to attempting to decode a `GeneratedAccount` from the rpc response containing only an error.
With this PR, we are detecting if an error is returned in the response, and if so, raising a `StatusGoException`. This exception is caught in the call chain, and translated in to a `StatusGoError` which is serialised and sent to the QML view, where it is parsed and displayed as an invalid password error in the input box.
refactor: remove string return values as error messages in wallet model
In the wallet model, we were passing back empty strings for no error, or an error as a string. This is not only confusing, but does not benefit from leaning on the compiler and strong types. One has …

fix: prevent crash on generate account wrong password

---

src/app/chat/view.nim
ui/imports/Emoji.qml
ui/shared/status/StatusChatInput.qml

Fixes #2326 
So, enabling ctrl-z should have been simple, it's actually available by default on TextEdits, but since we used `textEdit.text = ...` so much, it breaks the functionality.
So I had to refactor the text formation and the other text insertions like mentions and emojis, so instead of replacing the whole text (and also reparsing ALL of the text), we just remove and insert the particular part that changed.
It's both way more performant and also makes it possible to undo and redo.
I also moved the txt formation regex checks to Ni, because the QML regex engine is a little old and there is no look-behind. Also, it should be a bit faster in Nim than in JS.
Some known issues:
- If thee is an emoji and you move the cursor next to the emoji then hit a space or another character, the …

refactor text formation to increase performance and enable undo

---

src/app/profile/core.nim
ui/app/AppLayouts/Chat/ChatColumn.qml

Fixes: #2365.
Previously, suggestions for mentions were showing profile pics even for users who were not contacts. Now, profile pics are only shown for those users who are contacts. The user’s identicon is shown otherwise.
fix: user thumbnail not shown when no profile pic
When a user was a contact, but didn’t have a profile pic, an image would not be loaded and a ‘reload’ image would be shown instead. With this PR, if the user is a contact and they do not have a profile pic, their identicon will be shown instead.

fix: show suggestion profile pics for contacts only

---

ui/shared/status/StatusLetterIdenticon.qml

Due to historic reasons, conditionally assign a font size for the letter
identicon, based on whether or not the app's compact mode is active.
Compact mode has become the new default a while back and the component's
`isCompact` property isn't set anywhere in throughout the application,
resulting in `letterSize` to always be `21`, which is too big.
This commit removes the condition, defaulting to always having a letter size
of 15 pixels as designed.

fix(StatusLetterIdenticon): ensure letterSize is correct

---

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/EmojiReactions.qml
ui/imports/Emoji.qml

Fixes: #2387.
Shows the emoji in the emoji reaction tooltip instead of the shorthand (ie 👎 instead of `:thumbsdown:`).

fix: show emoji in reaction tooltip

---

src/app/chat/views/community_item.nim
ui/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopupInviteFriendsView.qml
ui/shared/ContactsListAndSearch.qml
ui/shared/ExistingContacts.qml

When inviting contacts to a community, Status Desktop suggests a list of
all contacts, even if contacts of that list are already members of the community.
This commit introduces a new flag to `ExistingContacts` component that
allows for configuring whether community members should be hidden or not
Fixes #2502

fix(Communities): don't list members in contacts to invite list

---

src/app/chat/views/stickers.nim
src/app/profile/views/ens_manager.nim
src/status/libstatus/core.nim
src/status/wallet.nim

There is an unknown state that the data dir seems to get in that causes the application to crash when checking pending transactions. This is fixed by checking if the pending transactions RPC result has a `”result”` field first before attempting to read it.
Clearing the data directory fixed the issue for me, however I do not know what caused it in the first place. While the crash was happening, there was also an error appearing in the logs:
```
ERR 2021-05-18 15:40:47+10:00 rpc response error                         topics="rpc" tid=3893906 file=core.nim:24 methodName=wallet_getPendingTransactions payload=[] result="{\"jsonrpc\":\"2.0\",\"id\":0,\"error\":{\"code\":-32000,\"message\":\"no such column: transaction_hash\"}}"
```
After clearing the data dir, this error also went away.

fix: prevent crash checking pending transactions

---

src/status/chat.nim
src/status/chat/chat.nim
src/status/libstatus/chat.nim
src/status/signals/messages.nim

Prior to this commit, loaded channels and chats would always be
sorted by date of last message received, with the latest one being
moved to the top of the list.
When new channels or chats are joined, they are added on top of the
list as well, however, when the application is restarted,
those new joined chats would not necessarily show up at the top anymore
becaue nothing keeps track of when a channel was joined, which should
be taken into account when preserving the order.
The changes introduced in this commit solve this by introducing a
new `joined` property on the `Chat` type which gets updated with
the current timestamp whenever a channel is joined.
It also depends on the changes made to the `status-go` client, which
have to land first: https://github.com/status-im/status-go/pull/2158 …

fix(Chat): honor joined date when preserving channel order

---

src/app/chat/views/stickers.nim
src/app/wallet/view.nim
src/status/libstatus/stickers.nim
src/status/stickers.nim
src/status/tasks/marathon/mailserver/worker.nim
src/status/tasks/threadpool.nim
src/status/wallet/collectibles.nim

Fixes: #2318.
Currently, when exiting the app and the sticker packs task is being run, the app will wait for the sticker packs task to completely finish before exiting the app. This causes a beachball to be displayed and can cause a long delay while waiting for the task to finish.
This PR passes an interrupt signal to the sticker pack loading task in the threadpool thread. The task loads the interrupt on each iteration of its loop (each sticker pack to load) and also during the processing of each sticker pack (getting of sticker pack data). This allows the application to exit neatly.
fix: Handle shutdown of long-running (marathon) task before login
Currently, we wait for the “loggedIn” message to be passed to the marathon task runner before initialising the mailserver model. We were, …

fix: interrupt running sticker task when exiting

---

Makefile

Fix a typo in a recently added header file in DOtherSide that causes problems on case-sensitive filesystems, e.g. on Linux.
Also unify the build command for DOtherSide across platforms.

fix: correct a typo in DOtherSide that was causing Linux packaged builds to fail.

---

src/app/chat/views/communities.nim
src/app/chat/views/community_list.nim
src/status/chat.nim
src/status/libstatus/chat.nim
ui/app/AppLayouts/Chat/CommunityColumn.qml
ui/app/AppLayouts/Chat/CommunityComponents/CommunityHeaderButton.qml
ui/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopup.qml
ui/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopupMembersList.qml
ui/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopupOverview.qml
ui/app/AppLayouts/Chat/CommunityComponents/CommunityWelcomeBanner.qml
ui/app/AppLayouts/Chat/CommunityComponents/CreateCommunityPopup.qml
ui/app/AppMain.qml

Fixes: #2566.
Fixes: #2582.
Allow editing of Community name, description, image, colour, and access.
1. This PR relies on a [PR for status-go](https://github.com/status-im/status-go/pull/2229) that is currently not merged. It should be merged *first*, after which this PR can be updated with the new commit hash and then merged.
2. The PR for status-go is based on top of `develop` which may have some consequences for our use of `status-go`.

feat: edit communities

---

src/app/chat/event_handling.nim

fix: fix community crash when no chat is active

---

ui/main.qml
ui/shared/MacTrafficLights.qml

Clicking close button on MacOS should not close the desktop app, instead it should be closed and running until you quit it by CMD+Q or from OS UI:

fix: close window instead of app

---

ci/Jenkinsfile.combined
ci/Jenkinsfile.linux
ci/Jenkinsfile.macos
ci/Jenkinsfile.windows

We identified this issue in status-desktop release from branch `release/0.1.0-beta.10` which had old version in VERSION file.
https://ci.status.im/job/status-desktop/job/release/job/release%252F0.1.0-beta.10/
Depends on: https://github.com/status-im/status-jenkins-lib/pull/28
Signed-off-by: Jakub Sokołowski <jakub@status.im>

ci: do no delete non-draft releases

---

Makefile
ci/Jenkinsfile.linux

I made changes to `ci/Jenkinsfile.linux` (will see if they work) but I'm not sure if changes need to be made re: the logic of the release builds for Linux.
Closes #1033.
---
Update now that the CI build for Linux finished:
Works fine, e.g. on Ubuntu download the `.AppImage.tar.gz`, double-click it in the file explorer and drag from the archive listing GUI into the folder you want. Afterward, you can simply double click the `.AppImage` and it works as expected.
Alternatively, you can unpack on the command-line with e.g. `tar xvzf Status*`.
I'm still not sure if changes will need to be made re: the release builds logic (I did look at the Jenkinsfile), but hopefully @jakubgs can give provide insight.

build: on Linux use tar+gzip to preserve +x attribute of .AppImage

---

src/app/chat/view.nim
src/app/chat/views/chat_item.nim
src/status/chat/chat.nim
src/status/chat/utils.nim
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChannelIdentifier.qml
ui/app/AppLayouts/Chat/ChatColumn/TopBar.qml
ui/app/AppLayouts/Chat/components/ChannelContextMenu.qml
ui/app/AppLayouts/Chat/components/GroupInfoPopup.qml

Fixes: #2601, #2672
Kicking a user and re-inviting them now correctly redisplays the join/decline options. Other combinations of User B leaving or declining an invitation are not handled. Please see the notes below for clarification.
Additionally, the group invite popup (that shows the list of members belonging to the group) correctly shows when a user is kicked or when a user leaves the group in real time. Previously, the popup needed to be reopened to display this.
fix: decline invitation crash
Declining a group invitation was crashing the app. This has been fixed.
1. In the case where User A invites User B to a group, but User B declines (or User B joins, then leaves), then from a status-go standpoint, User B is still part of the group, but the chat is marked as `active: false` for …

fix: kick and re-invite user to group chat

---

ui/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopupMembersList.qml

Fixes: #2486.
In the community member managment popup, for the current user, remove the “more actions” menu that allows kicking of the user and viewing of their profile.

fix: remove actions from community member when self

---

src/app/chat/view.nim
src/status/chat.nim
ui/app/AppLayouts/Timeline/TimelineLayout.qml

- Timeline updates were displaying the current active chat messages
- Cursor for existing chat messages was being overwritten

fix: various

---

ui/app/AppLayouts/Chat/CommunityComponents/CreateChannelPopup.qml

Fixes: #2694.
Display channel name in modal header when editing a channel instead of “New channel”.

fix: edit channel modal header

---

ui/app/AppLayouts/Chat/CommunityComponents/CategoryList.qml

Fixes: #2691.
When not an admin, the menu for adding/removing/editing of channels inside of a category should not be visible.

fix(communities): hide edit category menu for non-admins

---

ui/app/AppLayouts/Chat/components/MessageContextMenu.qml

Fixes: #2722.
Remove the “Copy” action from the emoji popup menu.

fix: remove “Copy” action from emoji menu

---

src/app/chat/views/communities.nim
src/app/chat/views/community_list.nim
src/status/libstatus/chat.nim
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/InvitationBubble.qml

Fixes: #2649.
Upon receipt of status-go signals which included communities that have been left (`joined: false`), those communities were being rejoined automatically when they should not have been.
fix(communities): Invitation bubble button state updates
The community state inside of the invitation bubble was not reactive to any community actions (such as joining, leaving, updating). In addition, requesting to join a community changed the button’s text to “Pending”, but upon approval, the button’s state was not updating.
The component was setting an observed community in the Component.onCompleted event, which was occurring for all invitation bubbles, but because the community wasn’t bound correctly to the bubble, once a bubble  with a different community was encountered, the community in …

fix(communities): re-joining of left communities

---

src/app/chat/views/channel.nim

Fixes: #2686.
Previously, when using a new account, joining a chat then creating a community and then returning back to the chat would not show a chat at all and instead show the default chat view. This was due to the previous index not being set when there were no other channels in the chat.
This has been updated such that the previous channel index is set when switching from chat to community and no previous channel index has been set.

fix: chat view shown after community creation

---

ui/shared/status/StatusChatInput.qml

This is a simple fix for the issue where the text after '<' character was ignored when user pasted it.
Fixes: #2267

fix: typing in `<` in the input box deletes everything afterwards in

---

ui/app/AppLayouts/Chat/CommunityComponents/CreateCategoryPopup.qml
ui/app/AppLayouts/Chat/CommunityComponents/CreateChannelPopup.qml
ui/app/AppLayouts/Chat/CommunityComponents/CreateCommunityPopup.qml
ui/imports/Utils.qml
ui/shared/Input.qml

I sorted out some validation related stuff. There were some unused and some redundant methods. I guess that validation messages for each input will be uniform now, across these three parts (channel, channel category and community). If it's needed we may easily change text of the error messages (Utils.validateAndReturnError) which will have same pattern now.
Fixes: #2297

fix(communities): Naming validation for communities

---

ui/shared/ContactsListAndSearch.qml

The issue actually appeared because of ignoring message label when we calculated the top margin offset, fixed now.
Fixes: #2449

fix(communities): bug: "Invite successfully sent" shown prematurely on Community invite popup

---

src/status/utils.nim
ui/shared/AssetAndAmountInput.qml

Validation check is updated, so user cannot enter zero or less than zero value in amount input field.
Also in utils.nim a crash prevention check is added so if we try to convert a less than zero float number to an unsigned number, app won't crash any more, but that casting will return a zero as unsigned int number.
Fixes: #2755

fix(wallet): Clicking Request Address when sending -1 STT crashes the app

---

src/app/wallet/views/gas.nim
ui/shared/GasSelector.qml

Validation check is updated, so user cannot enter zero or less than zero value for "gas amount limit" or "per-gas overall limit".
In gas.nim a crash prevention check is added.
Fixes: #2753

fix(wallet): Crash when enter -1 to Gas Selector

---

src/app/login/view.nim
src/status/types.nim

Generated accounts were using the address as the keyuid value during first login. This was causing that profile pictures updates to not be broadcasted unless you logged out and in again.

fix: invalid keyuid being used with a newly generated account on first login

---

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatReply.qml

fixes #2574
Bottom part of reply text was cut. Increased a bit the component's height to avoid this misbehavior.

[#2574] Increased reply TextInput's height to avoid bottom cutting

---

src/app/wallet/core.nim
ui/app/AppLayouts/Wallet/WalletLayout.qml

Fixes: #2725.
When clicking on the History tab for a wallet account, there was a QML error for `qrc:/app/AppLayouts/Wallet/WalletLayout.qml:113: TypeError: Property 'checkIfHistoryIsBeingFetched' of object HistoryTab_QMLTYPE_503(0x7fed35da2710) is not a function`. This must have been reintroduced when StatusQ objects were introduced. It has now been removed.
chore: change log level to warn for non-archival node
Previously, there was an error being logged for non-archival infura nodes being used (typically in dev). This log level has been reduced to a warning as the application still functions with non-archival nodes.

fix(wallet): QML error when loading history

---

src/status/provider.nim

There's an API used in `provider.nim`, which is defined in `utils.nim` but utils aren't imported.
The usage of that API was introduced in https://github.com/status-im/status-desktop/commit/065bd26786ac7be28e1fc1644f3ea0cf36c53300#diff-778feda87f0918b600d692bd16cdd1af92ae0611f81ae6557749e5f462636694R127

fix(Status): import missing `utils` module

---

src/app/chat/event_handling.nim
src/app/chat/views/activity_notification_list.nim
src/app/chat/views/channel.nim
src/app/chat/views/channels_list.nim
src/app/chat/views/chat_item.nim
src/app/chat/views/communities.nim
src/app/chat/views/community_list.nim
src/status/chat.nim
src/status/chat/chat.nim
src/status/signals/messages.nim
ui/app/AppLayouts/Chat/ContactsColumn/Channel.qml
ui/app/AppLayouts/Chat/ContactsColumn/ChannelList.qml

Mark all mention notifications as read is fixed. Also mark as read one by one notification removes "@" from the appropriate channel along with the marking as read last mention notification for that channel. hasMention field which was bool is switched with mentionsCount field which is int, so we have evidention how many mentions were for each channel.
Fixes: #2788

fix(activity_center): Mark as read does not clear @ symbol in chat

---

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/TransactionComponents/AcceptTransaction.qml

A reason why the crash is happening is actually previous step, when an user who is about to receive
a transaction clicks "confirm and share address" button. In that moment instead of his address an
empty js object is shared. After that clicking on the "sign and send" button, by sender, causes an
app crash because transaction cannot be made using invalid address of the recipient.
Fixes: #2718

fix(@desktop/wallet): app crash when click on sign and send message

---

src/app/wallet/views/transactions.nim

The issue was accessing non existent property after parsing received response. That caused
app crash, fixed now.
Fixes: #2623

fix(@desktop/wallet): app crash when signing token transaction with invalid password

---

ui/app/AppLayouts/Chat/ChatColumn.qml

A crash is happening not only when you click on a notification bubble with mentions, but on any
chat notification displayed in macOS' notification center. Discussion and details how we can
overcome this may be seen on zenhub, in issue 2819. So far this commit is just a simple solution
to avoid an app crash.
Fixes: #2819

fix(@desktop/chat): app crash when you click macOS' notification

---

ui/app/AppLayouts/Chat/ContactsColumn/EmptyView.qml

fix(@desktop/chat): update color of close suggestion to be lighter

---

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatTime.qml

fix(@desktop/timeline): update color of chat time when image

---

src/app/chat/views/channel.nim
src/app/chat/views/channels_list.nim
src/app/chat/views/chat_item.nim
ui/app/AppLayouts/Chat/components/AcceptRejectOptionsButtons.qml
ui/app/AppLayouts/Chat/components/ContactRequest.qml

This issue is being happened randomly, no general rule, in my case it happens often when you accept
first contact from the list immediately after the app start, but the ticket says that it happens
when you click accept while context menu is opened.
Two places were threat for this crash and both are fixed here:
- getChannel proc, direct access by index to Chat element of the chats sequence,
- setChatItem proc, where we actually were setting chatItem and accessing its property without
checking if it is an empty object.
Fixes: #2837

fix(@desktop/chat): app crash when you accept contact request

---

ui/app/AppLayouts/Chat/ChatColumn/Message.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatButtons.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/CompactMessage.qml
ui/app/AppLayouts/Chat/components/PinnedMessagesPopup.qml

fixes #2852 
Main chat:
Pinned popup:

fix(@desktop/communities): disable edit for pined message popup

---

ui/app/AppLayouts/Chat/components/PrivateChatPopup.qml
ui/shared/ContactsListAndSearch.qml
ui/shared/SearchResults.qml

fixes #2595
From private chat:
From add contact:

fix(@desktop/chat): Hide add contact button on private chat

---

src/app/chat/views/channel.nim
src/status/chat.nim
ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml
ui/app/AppLayouts/Chat/ChatColumn/Message.qml

The issue is happening randomly. I managed to catch it few times and hopefully fix it. Problem was
in leave proc in src/status/chat.nim cause we were sending activeChannelChanged signal from it what
started setting activeChannel to the value of the backToFirstChat variable, and while that process
was in progress setActiveChannelByIndex was called from activeChannel what caused another emit of
activeChannelChanged signal while the previous one was not completed. That caused new setting of
activeChannel with active channel index 0, what caused an app crash.
This is fixed by setting active channel to the first one from the list when we get a signal that
any channel from the list is removed. This way activeChannelChanged is broadcasted to the other
parts correctly.
Fixes: #2825

fix(@desktop/chat): app crash when you leave a chat

---

src/app/chat/views/messages.nim
ui/app/AppMain.qml

The chat navbar tab button renders an indicator when there's unread messages
in any of the chats. It also renders a message count, which prior to this commit
equals to the number of total unread messages.
This however is not the desired behaviour. Instead, the count should be the total
number of unread one on one messages (DMs), plus the total number of mentions in any
chats the user is participating in.
This commiit ensures the correct message count is rendered. It also adds an "unread messages"
indicator to community buttons.
Closes #2869

fix: ensure Chat navbar tab button shows correct message count

---

src/app/profile/core.nim
src/app/profile/views/contact_list.nim
src/app/profile/views/contacts.nim

fixes #2637
When changing a contact, the notification about being able to chat was sent again.
Prevent this behaviour by ensuring the contact hasn't already been added

fix(@desktop/profile): chat confirmation notification

---

src/app/chat/views/messages.nim
ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml

fixes #2450
messageType is always empty, I am not sure to what it corresponds but contentType seems to be the field to look for as this is an enum which correspond to the qml part

fix(@desktop/chat): fix sticker/image notification with placeholder

---

ui/app/AppLayouts/Chat/ChatColumn.qml
ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml

This bug is happening if you have more than one private chat in the contacts column. How many chats
you have that many same notifications you will get. That's happening cause connection is made
between chatsModel.messageView and ChatsMessages component for each private chat, and for each of
them ChatsMessages component is maintained in StackLayout component what means all of them are
exist but only selected instance is visible. When new messageNotificationPushed signal is emitted
each qml component triggers its slot (regardless component is not currently visible it exists in
the background, it's not deleted) and that's why we see more than one OS' notification bubble for
the same notification.
That is fixed adding kind of a filter in those slots, so OS' notification bubble will be fired …

fix(@desktop/chat): push notification is duplicated when mentioning

---

ui/app/AppLayouts/Chat/CommunityColumn.qml
ui/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopup.qml
ui/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopupInviteFriendsView.qml
ui/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopupMembersList.qml
ui/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopupOverview.qml
ui/app/AppMain.qml

This commit refactors the `CommunityProfilePopup` to use `StatusModal`. Since it's made of
various popup content components, it also updates the memberlist, the overview and the
invite friends view, so it doesn't break the UI along the way.
Closes: #2885, #2887, #2888

refactor(Communities) replace `CommunityProfilePopup` with `StatusModal`

---

ui/app/AppLayouts/Chat/CommunityColumn.qml
ui/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopup.qml
ui/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopupInviteFriendsView.qml
ui/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopupMembersList.qml
ui/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopupOverview.qml
ui/app/AppLayouts/Chat/CommunityComponents/CreateChannelPopup.qml
ui/app/AppLayouts/Chat/components/PrivateChatPopup.qml
ui/app/AppMain.qml
ui/shared/AddressInput.qml
ui/shared/ContactsListAndSearch.qml

There are two regressions introduced in https://github.com/status-im/status-desktop/commit/080767c3382c9820ce99d5b63cd8877572a5193e where
the `CreateChannelPopup` isn't properly centered when triggered in edit mode,
and that the channel name field isn't hydrated with channel data.
This commits fixes both bugs.

fix(Communities): fix channel popup position and field hydration

---

src/app/chat/event_handling.nim
src/app/chat/view.nim
src/app/chat/views/message_list.nim
src/app/chat/views/messages.nim
src/app/chat/views/transactions.nim
src/status/chat.nim
src/status/chat/message.nim
src/status/chat/utils.nim
src/status/libstatus/chat.nim
src/status/libstatus/chatCommands.nim
src/status/signals/messages.nim
ui/app/AppLayouts/Chat/ChatColumn/ChatComponents/SignTransactionModal.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/TransactionBubble.qml

The reason for this issue is a message where recipient accepted to share his address with sender.
In that message recipient's public key is set as a "from" property of a "Message" object and we
cannot determine which of two users has initiated transaction actually.
This is fixed checking if the "from" address from the "commandParameters" object of the "Message"
is contained as an address in the wallet of logged in user. If yes, means that currently logged in
user has initiated a transaction (he is a sender), otherwise currently logged in user is a
recipient.
We were just sending a transaction, without notifying message about that. Now we call
callPrivateRPC("acceptRequestTransaction".prefix, %* [transactionHash, messageId, signature])
and that notifies message about the change, but only …

fix(@desktop/chat): sign and send appears for both recipient and sender when sharing the address

---

ui/app/AppLayouts/Chat/ChatColumn/Message.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatTime.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/StatusUpdate.qml
ui/app/AppLayouts/Timeline/TimelineLayout.qml
ui/imports/Utils.qml

In according with Figma, we need to render messages' age instead of time/date.
https://www.figma.com/file/Zz6KMBxwrB0l2NPgsjnPjq/%F0%9F%91%A4-Profile%E2%8E%9CDesktop?node-id=1918%3A13058
Fixes #2918

fix(@desktop/timeline): render message age instead of message time

---

ui/app/AppLayouts/Chat/ContactsColumn.qml

In chat search box the focus state was remaining true
even though the user was clicking outside of it
Closes #2263

[#2263] Change Focused state back to default in search box

---

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/InvitationBubble.qml

fix(@desktop/chat): invitation bubble long text support

---

ui/shared/status/StatusToolTip.qml

ToolTip was wrongly top positioned when on top of the screen
Closes #1945

[#1945] Fixed ToolTip position when there is no space

---

src/app/wallet/view.nim
src/app/wallet/views/transaction_list.nim
src/status/wallet.nim
ui/app/AppLayouts/Wallet/components/TransactionModal.qml

fixes #2715
Also, I update the hash to be the transaction hash rather than the block, let me know if you want me to revert that part. It seemed more logical to me while looking at the transaction popup ;)

feat(@desktop/wallet): display confirmation block count

---

ui/app/AppLayouts/Chat/CommunityColumn.qml

fixes #2839
depends of: https://github.com/status-im/StatusQ/pull/268
Right click are disabled, as well as + action and category action

fix(@desktop/communities): remove context menu leftover

---

src/app/chat/event_handling.nim
src/app/chat/view.nim
src/app/chat/views/message_list.nim
src/app/chat/views/messages.nim

fixes #2659
~~1 - Avoid to double refresh the pin messages by removing call to addPinMessage and removePinMessage.~~
~~This is done by event~~
This is only done by event when pinning from a communities chat, not from a group chat
2 - Change call from remove to deleteMessage
Remove were not updating the index and was causing the issue
3 - Erase the remove proc as the deleteMessage should always be used
3 - Rename addPinnedMessages to refreshPinnedMessages

fix(@desktop/chat): cannot unpin last message in modal

---

ui/app/AppLayouts/Profile/Sections/Ens/RegisterENSModal.qml
ui/app/AppLayouts/Profile/Sections/Ens/Search.qml
ui/app/AppLayouts/Profile/Sections/Ens/SetPubKeyModal.qml
ui/app/AppLayouts/Profile/Sections/Ens/TermsAndConditions.qml
ui/i18n/base.ts
ui/i18n/qml_ar.ts
ui/i18n/qml_de.ts
ui/i18n/qml_en.ts
ui/i18n/qml_es.ts
ui/i18n/qml_fil.ts
ui/i18n/qml_fr.ts
ui/i18n/qml_id.ts
ui/i18n/qml_it.ts
ui/i18n/qml_ko.ts
ui/i18n/qml_pt_BR.ts
ui/i18n/qml_ru.ts
ui/i18n/qml_tr.ts
ui/i18n/qml_ur.ts
ui/i18n/qml_zh.ts
ui/i18n/qml_zh_TW.ts
ui/shared/GasSelector.qml
ui/shared/status/StatusStickerPackPurchaseModal.qml

Fixes #2434.  
Modals that were affected by this issue were:
- RegisterENSModal (for registeing an ens username)
- SetPubKeyModal (for changing the contact code of an already owned ens)
- StatusStickerPackPurchaseModal (for acquiring a sticker pack)

fix: make gas selector visible in transaction modals

---

src/status/chat.nim

fixes #2902
If we want to create a one to one chat but one already exists, we still need to trigger the event, otherwise the chat is not added to the channel list

fix(@desktop/chat): start chat after contact request accepted

---

src/app/node/view.nim
src/status/libstatus/accounts/constants.nim
src/status/libstatus/settings.nim
src/status/settings.nim
ui/app/AppLayouts/Profile/Sections/AdvancedContainer.qml
ui/app/AppLayouts/Profile/Sections/BloomSelectorButton.qml

feat: select bloom filter level

---

src/app/chat/views/category_item.nim
src/app/chat/views/communities.nim
src/app/profile/views/muted_chats.nim
src/app/profile/views/profile_settings.nim
src/status/contacts.nim
src/status/libstatus/eth/methods.nim
src/status/mailservers.nim
src/status/types.nim

When building the app, nim compiler yields several warnings about unused imports. This PR fixes unused imports and ensures the build log is clean.

chore(@desktop): nim compilation warnings - unused imports

---

src/app/chat/views/communities.nim
ui/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopupOverview.qml

fixes #2880
It was previously deleted from: https://github.com/status-im/status-desktop/commit/7fbccec227492c9c9f5188e1088e80304e1101fd#diff-8a095f0b8791047bc1263bddbedc82992225cc88cb743dc9bd35d05d370c5d82
Also the checked value needs to be the opposite of the current one.

fix(@desktop/communities): mute/unmute communities

---

ui/app/AppLayouts/Profile/Sections/MutedChatsModal.qml
ui/app/AppLayouts/Profile/Sections/NotificationsContainer.qml

Muted contacts and Muted chats modals were blank when
nothing added to list, added indicative text label
Closes #2549

[#2549] Muted contacts and chats modal was missing indicative text

---

Makefile
src/app/chat/view.nim
src/app/chat/views/gif.nim
src/app/chat/views/gif_list.nim
src/status/gif.nim
ui/app/AppLayouts/Profile/Sections/AdvancedContainer.qml
ui/app/AppMain.qml
ui/shared/status/StatusChatInput.qml
ui/shared/status/StatusGifPopup.qml
ui/shared/status/qmldir

fixes #1372
Create the popup for gif, only visible if the feature is enabled.
It is possible to search for gif, by default, the trendings one are being send.
When clicking on a gif, the url is added to the text input and the message is send.
Then the image is being preview in the chat.
I used the wallet icon because I couldn't find one for GIF (can easily be replaced)
Next:
* Better UI/UX
* Categories
See below for a few screenshots:

feat(@desktop/chat): Display gif popup next to emoji

---

src/app/chat/views/messages.nim
ui/app/AppLayouts/Chat/ChatColumn.qml

fixes #2484
Also refactor to add all the guard in nim rather than being in 2 places.
Let me know if the guard I added makes sense

fix(@desktop/chat): hide notification when leaving/creating a group

---

src/app/chat/views/channels_list.nim

fixes #2999
Before:
After:
We switch to the already existing channel

fix(@desktop/chat): prevent double addition of private chat

---

src/app/chat/view.nim
src/app/chat/views/chat_item.nim
src/status/chat.nim
src/status/libstatus/chat.nim
ui/app/AppLayouts/Chat/CommunityComponents/CreateChannelPopup.qml

As described in #3015, when editing channels that belong to a category of a community,
after saving them, they'll get kicked out of the category.
This is because we haven't passed the category id along the API that performs the
save operation.
This commit ensures we have access to a category chats' `categoryId` and send it
over to `editCommunityChat` RPC API provided by status-go
Fixes #3015

fix(Communities): preserve category id when editing channels

---

src/app/login/view.nim
src/app/onboarding/view.nim
src/app/onboarding/views/account_info.nim
ui/nim-status-client.pro
ui/onboarding/GenKeyModal.qml
ui/onboarding/Login.qml
ui/onboarding/Login/AccountList.qml
ui/onboarding/Login/AccountView.qml
ui/onboarding/Login/SelectAnotherAccountModal.qml
ui/onboarding/Login/qmldir

fixes #3035
* Avoid mismatch between keyuid and address
* Remove the keyuid from the login screen
We found out that we cannot get the address from the keyuid, and before login the address is not available.

fix(@desktop/onboarding): do not display keyuid as address

---

ui/onboarding/CreatePasswordModal.qml

Allow to click enter when generating a new account and clicking enter
Error was:
qrc:/onboarding/CreatePasswordModal.qml:53: Error: Insufficient arguments

fix(@desktop/onboarding):

---

ui/shared/status/StatusStickerMarket.qml
ui/shared/status/StatusStickerPackPurchaseModal.qml

Bug is easily reproducible if you try to buy some stickers, in that case suggestion text
overlaps divider and buttons, and if you don't enough balance warning about that will overlap
all that also.
Fixed by increasing hight of the appropriate modal.
Fixes: #2994

bug(@desktop/wallet): gas selector modal has text, divider and custom/suggestions toggle overlapped

---

ui/app/AppLayouts/Chat/components/MessageContextMenu.qml
ui/app/AppLayouts/Chat/components/PinnedMessagesPopup.qml
ui/imports/Constants.qml

Fixes #2629
Limits the number of pins per chat to 3. This is done in the optic to have the pin messages be "permanent", so that we don't have to save that many pins on the history node.
There is still the part to make the pins permanent, but it's better to split the original issue, so here is the new issue to track making the pin permanent: https://github.com/status-im/status-desktop/issues/3024

Limit to 3 pins and show how to unpin

---

src/app/chat/views/chat_item.nim
ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml
ui/app/AppLayouts/Chat/ChatColumn/Message.qml

This is causing fetch more message to not be visible in other chat type
such as public chat
Mainly revert:
#2797 
fixes #2856
The original issue #2379 : Load more message should not be present when creating a group chat is still present

fix(@desktop/chat): revert the visible logic for fetch more messages

---

src/app/chat/views/activity_notification_list.nim
ui/app/AppLayouts/Chat/ChatColumn.qml
ui/app/AppLayouts/Chat/ChatColumn/ActivityCenter.qml
ui/app/AppLayouts/Chat/ChatColumn/ChatComponents/ActivityCenterMessageComponent.qml
ui/app/AppLayouts/Chat/ChatColumn/ChatComponents/ActivityCenterTopBar.qml
ui/app/AppLayouts/Chat/ChatColumn/ChatComponents/ActivityChannelBadge.qml

Fixes the following issues:
- Adds the contact request count to the bell icon count
- Fixes an issue where notifications could become duplicated
- Fixes an issue where if there is no notif in the center, the notifs will have a 0 height and width
- Fix the 1-1 accept to go to the channel
- Fix the reply badge missing the message text

fix(act-center): multiple fixes to the activity center

---

ci/Jenkinsfile.combined
ci/Jenkinsfile.linux
ci/Jenkinsfile.macos
ci/Jenkinsfile.windows

Fixes:
```
Caused: java.io.NotSerializableException: groovy.json.internal.LazyMap
```
https://ci.status.im/job/status-desktop/job/release/job/release%252F0.1.0-beta.11/2/

ci: fix JSON parsing in release process

---

ui/app/AppLayouts/Wallet/SendModal.qml

fixes #2714
Increase height of the modal and position the validator to below the previous
item

fix(@desktop/wallet): correct position of not enough gas error

---

ui/app/AppLayouts/Chat/ChatColumn.qml
ui/app/AppLayouts/Chat/components/ChatContextMenu.qml
ui/app/AppLayouts/Chat/components/GroupInfoPopup.qml

This broke during the modal refactoring because we're no longer relying
on `chatsModel.contextChannel`.
Passing the channel item to the popup ensures it's properly hydrated again.
Closes #3050

fix(@desktop/chat): make chat group popup work again

---

ui/app/AppLayouts/Profile/LeftTab/Menu.qml

Click on "Notification settings" in activity center takes user to profile tab, but not to the
notification section there, but to the last selected section. That is fixed now. Also marking
selected section within profile section is fixed now.
Fixes: #3049

fix(@desktop/chat): click on "Notification settings" doesn't take the user to that section

---

ui/app/AppLayouts/Browser/AddFavoriteModal.qml
ui/app/AppLayouts/Browser/BrowserWalletMenu.qml
ui/app/AppLayouts/Chat/ChatColumn/ActivityCenter.qml
ui/imports/Themes/DarkTheme.qml
ui/imports/Themes/LightTheme.qml
ui/imports/Themes/Theme.qml
ui/shared/ToastMessage.qml
ui/shared/status/StatusInputListPopup.qml

Fixes #3100
Adds the `dropShadow` color in the theme and use it where needed
Also removes the activity center backdrop

Remove activity center backdrop

---

ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/CompactMessage.qml
ui/app/AppLayouts/Chat/components/PinnedMessagesPopup.qml

Fixes #3072 
Besides #3072, this adds other improvements:
1. in message edit mode, the user can press Esc to cancel editing (unless popup or mentions are shown)
2. in message edit mode, the user can press Enter to commit editing
3. when leaving editing mode, the scroll view is positioned at the item (was - partially visible).
4. ListView is already Flickable, and I removed odd ScrollView around ListView (ChatsMessages).

fix(@desktop/chat): support to mentions in message edit mode

---

src/app/chat/views/stickers.nim
src/status/utils.nim

Call the same function as to when we do a transaction to validate
the argument. From there we validate that the gas in an int.
sister PR of #3071
@anastasiyaig if you could double check that buying sticker pack still work?

chores(@desktop/chat): add guard when buying stickers

---

ui/imports/Constants.qml

Fixes #3068 
While sending an image, we call `dos_image_resizer` utility function that uses `QImage` to shrink any given image to max of 2000px width and height. Then it encodes the image to JPEG @ 75 quality. This usually results in <1MB of size.
However, on the UI I think we should impose certain limit and I suggest 10Mb which should be fine for Desktop platform.
If we were removing this limit at all, then resizing of a truly large image (say 100Mb) may cause abnormal memory and CPU usage. Given that we do not have any visual feedback while processing the image, for the user it will look like a UI freeze.

fix(@desktop/chat): uploading image limit is 0.5Mb

---

src/app/wallet/views/gas.nim

The current implementation converts any gas price the user inputs to an integer. With this fix, the gas price will be parsed as a floating point value, fixing this issue

fix: it should be possible to enter gas prices with decimals

---

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatButtons.qml

Re-parented to 'more' button so that it's
following that when scaling the window
Closes #2584

[#2584] Fixing 'more' chat menu position

---

src/app/chat/views/message_list.nim
src/app/chat/views/message_list_proxy.nim
src/app/chat/views/messages.nim
src/status/chat.nim
src/status/libstatus/chat.nim
src/status/status.nim
src/status/tasks/qt.nim
ui/app/AppLayouts/Chat/components/SearchPopup.qml

Current code adapted to handle future changes on message search (like searching message in multiple
channels). 
Memory leak which was happening in qml assigning (copying) MessageItem to qml variable messageItem
(where that qml variable messageItem was never deleted) is fixed.
Searching messages by some term for a specific channel is added on the side of status-go and an
appropriate part on the side of nim is developed accordingly.
Fixes: #2912

feature(@desktop/chat): implement search on sqlcipher (status-go side)

---

ui/app/AppLayouts/Chat/ChatColumn.qml

This fix adds a background to the member button when the members section is open.
fixes #3101

fix(@desktop/chats): add background to member button

---

ui/app/AppLayouts/Chat/ChatColumn.qml

Updated offset of the notification tooltip arrow based on if the members list is visible. The arrow should be in center when member list is visible else it should be right aligned as there is no place on the window
fixes #3102

fix(@desktop/chat): Activity tooltip arrow position is incorrect when members list is visible

---

src/nim_status_client.nim

When recovering an account, ensure the mnemonic is backed up
Also, we need to ensure that this bug is not back:
https://github.com/status-im/status-desktop/commit/5a7aac0baf8c6f6b82c32e98835076f3e1fde060
fixes https://github.com/status-im/status-desktop/issues/3089

fix(@desktop/onboarding): display the app, then init the profile

---

ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml

When replying to a chat, we were reloading messages and rerendering
the messages which were causing issue with the reply id
fixes #3219

fix(@desktop/chat): fix replying to message at early chat

---

Makefile
ci/Dockerfile
ci/Jenkinsfile.combined
ci/Jenkinsfile.linux
ci/Jenkinsfile.macos
ci/Jenkinsfile.windows
scripts/sign-linux-file.sh
scripts/sign-macos-pkg.sh

Adds `scripts/sign-linux-file.sh` which expectes the following variables set:
* `LINUX_GPG_PRIVATE_KEY_FILE` - Path to the GPG export of private key.
* `LINUX_GPG_PRIVATE_KEY_PASS` - Password necessary to use the private key.
Given a file it creates a file with a `.asc` suffix containing the signature:
```
> wget -q https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-210809-144822-1b77e5-pr3185.tar.gz
> tar xvf StatusIm-210809-144822-1b77e5-pr3185.tar.gz                                                              
StatusIm-210809-144822-1b77e5-pr3185.AppImage
StatusIm-210809-144822-1b77e5-pr3185.AppImage.asc
> gpg --verify StatusIm-210809-144822-1b77e5-pr3185.AppImage.asc 
gpg: assuming signed data in 'StatusIm-210809-144822-1b77e5-pr3185.AppImage'
gpg: Signature made Mon 09 …
```

ci: add scripts/sign-linux-tarball.sh for GPG signing

---

src/app/chat/event_handling.nim
src/app/chat/views/channels_list.nim
src/app/chat/views/communities.nim
src/app/chat/views/community_item.nim
src/app/chat/views/community_list.nim
src/status/chat/chat.nim
src/status/signals/messages.nim
ui/app/AppMain.qml

Counting mentions for community seems was not developed yet. That's added here in this commit, but
instead of using "mentionsCount" we introduced on the side of nim, I found that we're receiving
"unviewedMentionsCount", but only for new messages. I used it for this fix.
Fixes: #2972

fix(@desktop/communities): `joinedCommunities` doesn't update underlying community

---

ui/main.qml

This issue is reproducible on the app only if you're not logged in yet.
The issue is fixed mostly on the side of dothersidem, [here](https://github.com/status-im/dotherside/pull/34).
Fixes: #3112

fix(@desktop/general): right click the icon on the dock and press quit doesn't quit the app (macos)

---

ui/app/AppLayouts/Chat/CommunityComponents/BackUpCommuntyBanner.qml

The transfer ownership popup triggered by the backup community baner button
was behaving weirdly because the banner from where it originates lives inside
a loader that is deactivated once the popup was opened.
Moving the logic that deactivates the loader into the onClosed handler of the
popup solves this issue.
Thanks to @pinebit for getting to the bottom of this!
Fixes #2997

fix(Communities): move backup community popup logic to onClosed handler

---

src/nim_status_client.nim
ui/app/AppLayouts/Profile/Sections/AppearanceContainer.qml
ui/imports/Style.qml
ui/main.qml

App is responsive to the OS theme change event.
Now we're following system set theme when the app is started.
Corresponding part on the side on nimqml is added, [here](https://github.com/status-im/dotherside/pull/37).
Corresponding part on the side on dotherside is added, [here](https://github.com/status-im/nimqml/pull/25).
On the side of dother side we had kind of a memory leak, cause objects added to
the filter were not deleted ever. When the app is closing, it just removes
filters, but doesn't delete them.
I faced a logical issue, that we were sending qmlengine pointer to the
installEventFilter method, instead object which may or may not rely on the
qqmlengine instance, that is fixed also.
With this change we will be able to add more filter (if that's need) easily. 
Fixes: #1725

fix(@desktop/general): Changing System Appearance on the fly is not working

---

ui/app/AppLayouts/Profile/Sections/BackupSeedModal.qml
ui/shared/ConfirmationDialog.qml

Added code so that in the backup seed phrase modal all actions can be performed with the enter key.
Also added logic for default focus on the confirm button in the ConfirmationDialog.
fixes#2359

fix(@desktop/profile): Enter key doesnt activate button

---

ui/app/AppLayouts/Chat/ChatColumn.qml
ui/app/AppLayouts/Chat/ChatColumn/Message.qml
ui/app/AppLayouts/Chat/ChatColumn/UserList.qml
ui/app/AppLayouts/Chat/ChatLayout.qml
ui/app/AppLayouts/Chat/components/MessageContextMenu.qml

Fix the bug introduced by removing MessageContextMenu from Chat column. Added missing logic for edit message via MessageContextMenu
fixes #3223

fix(@desktop/chat): Right click message actions dont work

---

ui/shared/status/StatusChatInput.qml

fixes #3249
@alexandraB99 if you could help review this one ;) Moving the StatusSyntaxHighlighter prevent it to crash the app when leaving the timeline chat

fix(@desktop/timeline): Fix leaving the timeline chat

---

Makefile
src/nim_status_client.nim
src/status/constants.nim
src/status/libstatus/accounts/constants.nim

fixes #3146
Create a dir: Status/logs
Each time the app start, create a new log file: app_{current_timestamp}.log
In order to avoid nearly 0 logs, set the loglevel to error: `make LOG_LEVEL=error`

feat(@desktop/internal): Specific logfile per app start

---

ui/app/AppMain.qml
ui/shared/UserStatusContextMenu.qml

fixes #3239
This is not visible because this is darkGrey on a color too close to darkGrey, using midGrey fix the problem

fix(@desktop/chat): fix offline indicator in dark mode

---

src/app/chat/views/messages.nim

fixes #3192 
In order to avoid re-sending notification on scroll, update
the channel joined time to now

fix(@desktop/chat): avoid to resend notification on scroll

---

ui/app/AppLayouts/Browser/AddFavoriteModal.qml
ui/app/AppLayouts/Browser/BrowserHeader.qml
ui/app/AppLayouts/Browser/BrowserLayout.qml
ui/app/AppLayouts/Browser/FavoritesList.qml
ui/app/AppLayouts/Browser/components/BookmarkButton.qml

Adapted the bookmark list to a grid view to accomodate items when the list gets long.
Max column size is 7 and in case screen cannot show 7 columns it will flow to the next row.
Also added ideinticon for a website with no icon
Fixed the issue of DApps launching on all new tabs.
fixes #2009

fix(@desktop/browser): Favorite list get truncated when its too long

---

ui/app/AppLayouts/Chat/components/MessageContextMenu.qml

when only "Delete" is available
Closes #3243

fix(desktop/messages) Removed separator from options menu

---

src/app/chat/views/channel.nim
src/app/profile/views/contacts.nim
src/status/chat.nim
src/status/chat/async_tasks.nim
src/status/libstatus/core.nim

As we keep a local list of contact request and contact added
we should not need to query this data each time we switch chat as
we already have this data in memory.
This data should be maintained each time there is a change
fixes #1642
Also: Remove what seems to be duplicated and dead code about
getContactById

perf(@desktop/chat): avoid query when switching chat

---

ui/app/AppLayouts/Chat/ChatColumn/User.qml
ui/app/AppLayouts/Chat/CommunityComponents/CommunityUserList.qml

fixed to display online status only if is the current user and
if they have been active in the last 7 minutes. Respective color
is shown depending on if they are in "do not disturb" mode or they
have been active more than 5 minutes ago
Closes #3282

fix(@desktop/chat) members' status circle is not always right

---

src/app/chat/views/message_search/result_item.nim
src/app/chat/views/message_search/result_model.nim
src/app/chat/views/message_search/view_controller.nim
ui/app/AppLayouts/Chat/ChatLayout.qml

PR: `StatusQ` [here](https://github.com/status-im/StatusQ/pull/361)
Icons added for messages senders in the search result, also community and chat
icons are colorized now.
Fixes: #3259

fix(@desktop/chat): no identicon/profile picture shown and wrong time stamp format in search results

---

ui/shared/status/StatusChatInput.qml

When text from clipboard that contained any emoji was pasted
in the chat input it was becoming invisible
Closes #3291

fix(@desktop/chatInput) Pasting text with emoji was invisible

---

src/app/utilsView/view.nim
src/nim_status_client.nim
ui/app/AppLayouts/Profile/Sections/AppearanceContainer.qml
ui/app/AppLayouts/Profile/Sections/ConfirmAppRestartModal.qml
ui/app/AppLayouts/Profile/Sections/qmldir

Fixes #2178 
Requires DOtherSide: https://github.com/status-im/dotherside/pull/48
Requires NimQML: https://github.com/status-im/nimqml/pull/31
Quick summary:
1. Qt's scale factor default rounding rule did not work well with fractional system scale factors, such as 150%. Enabled pass-through rule in hope all modern desktops can handle it. Needs to be tested on Mac and Linux. On Windows 10 this works fine.
2. For HIDPI screens (4K+) at 100% scale, UI appeared too small despite XXL font size was selected. Discord has the same issue, but it also allows to change general zoom factor, which I also added to the app. Unfortunately, Qt does not allow changing scale factor on the fly, so we will require application restart. The selected scale factor value is persisted in Status folder as a file, …

fix(@desktop): various UI scaling fixes

---

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatText.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/CompactMessage.qml

fixes #3366
When image display is enabled:
When image display is disabled:

feat(@desktop/chat): Hide chat text when the link is only an image

---

ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml
ui/app/AppLayouts/Chat/ChatColumn/Message.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChannelIdentifier.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/InvitationBubble.qml

InvitationBubble binding loop on height fixed.
Scroll down if you reach the top of the chat is not blocked any more.
Fixes: #3320

fix(@desktop/chat): after reaching the top of chat history, unable to scroll down again

---

ui/app/AppMain.qml

When other than the profile menu was selected
Closes #3457

fix(desktop/profile) back seed indication missing

---

src/app/chat/views/messages.nim

Fixes #3329 
REQUIRES: https://github.com/status-im/nim-status-lib/pull/2
Original issue description:
`inviteUsersToCommunity` (status-go) call creates and sends an invitation message to the peer, but it was not appeared in my own chat as "sent invitation". 
How to test: just follow the instructions from #3329

fix(@desktop/communities): processing response from InviteUsers call

---

src/app/chat/core.nim
src/app/chat/view.nim
src/nim_status_client.nim
src/nim_windows_launcher.nim
status.iss

Fixes #837 
Fixes https://github.com/status-im/status-desktop/issues/3371
Requires https://github.com/status-im/nim-status-lib/pull/6
1. Windows only.
2. Installer to execute `vc_redist.x64.exe` silently while installing the app.
3. Installer to register `status-im://` protocol handler.
4. Application to receive `--url=status-im://0x123...` cmd line argument to create/open 1-1 chat.
5. Only 1-1 chat links are supported for now.
Future work (TODOs):
1. Integrate "single instance" feature https://github.com/status-im/status-desktop/issues/3374
2. Support status protocol variations for communities, public chats, etc. Need a full list of possibilities.
How to test:
1. Uninstall Status app.
2. Install Status app using the new installer built from this branch.
3. Open a browser (e.g. Chrome) or …

feat(@desktop/installer): status-im:// protocol support and improvements

---

src/app/profile/views/ens_manager.nim

Fixes: #3292
Notice that in the case of buying an ENS, it will be set as the preferred username once the transaction is mined.

fix: set preferred username

---

src/nim_status_client.nim
ui/main.qml

As a user, I should not be able to run the second Status application instance, either intentionally or not, **for the same data directory** (the directory having your status account data).
The default data directory can be overridden with -d switch. 
If the user is attempted to start the second Status instance, the new process should be immediately terminated and the other (already running) instance should be activated (the main window should be made visible and brought to the foreground).
TODO: support passing command line arguments such as --url for deep links.

feat(@desktop): single application instance

---

ui/app/AppLayouts/Chat/ChatColumn.qml
ui/app/AppLayouts/Chat/ChatColumn/UserList.qml
ui/app/AppLayouts/Chat/ChatLayout.qml
ui/app/AppMain.qml

* The userlist toggle made persistent between restarts
* Members is enabled by default for communities
* Public channels changed title to "last seen"
instead of "Members"
Closes #3502

feat(desktop/members) Improvements in members list

---

Makefile
ci/Jenkinsfile.windows

Closes #3324
In addition to the installer, we want to create and publish an archive with the app contents. This is because some users may not want to install the app and prefer running "portable" version of the app.

feat(@desktop/windows): produce 7z archive when packaging

---

ui/app/AppLayouts/Profile/Sections/ContactsContainer.qml
ui/shared/ContactsListAndSearch.qml

Fixes: #3422.
The string stored in the translation had been doubled-up, so when a validation error occurred, the doubled-up string appeared.
The fix removes the currently in use translation.

fix(@desktop/contacts): Double validation for incorrect ENS name

---

src/app/wallet/v2/view.nim
src/app/wallet/v2/views/saved_addresses.nim
src/app/wallet/v2/views/saved_addresses_list.nim
ui/app/AppLayouts/Chat/CommunityComponents/CreateCategoryPopup.qml
ui/app/AppLayouts/Chat/CommunityComponents/CreateChannelPopup.qml
ui/app/AppLayouts/Chat/CommunityComponents/CreateCommunityPopup.qml
ui/app/AppLayouts/WalletV2/LeftTab.qml
ui/app/AppLayouts/WalletV2/SavedAddresses.qml
ui/app/AppLayouts/WalletV2/WalletV2Layout.qml
ui/app/AppLayouts/WalletV2/components/AddEditSavedAddress.qml
ui/app/AppLayouts/WalletV2/components/SavedAddressesError.qml

Closes #3307.
WalletV2 view can be toggled between normal wallet view and the SavedAddresses view.
Users can load, add, edit, and delete saved addresses. All operations are completely asynchronous and handled off the main UI thread by way of task runner. Any errors encountered are handled at each layer: libstatus > status > view > QML.
Favouriting a saved address is out of scope, as is sending to a saved addresses, drilling down in to a saved address, and supporting multiple networks.
Updates components that utilised the StatusMinLengthValidator component to support the changes made to StatusQ.
1. ~Depends on status-go PR https://github.com/status-im/status-go/pull/2356~ Merged in to develop.
2. Depends on StatusQ PR ~https://github.com/status-im/StatusQ/pull/394~ …

feat(wallet2): introduce saved addresses

---

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/InvitationBubble.qml
ui/app/AppLayouts/Chat/CommunityComponents/CreateCommunityPopup.qml
ui/app/AppLayouts/Chat/CommunityComponents/MembershipRequirementPopup.qml

Closes #3410.
Re-enables open membership communities, with necessary changes in the Inivitation Bubble for one-on-one chats.
fix: add/edit communities components not appearing
On add/edit community popup load, some components below the thumbnail image picker were not appearing until the app window was resized. Removing the height of the ScrollView fixed the issue (on mac).
NOTE: this may require windows and linux users to test (@anastasiyaig)

feat(communities): re-enabled open membership communities

---

ui/app/AppLayouts/Chat/components/ProfilePopup.qml

Closes #3496.
This may not be the desired solution, but #3496 was very light on suggestions how the profile popup should be changed.

fix: in profile popup display Username instead of ENS Username if ENS is not verified

---

src/app/profile/view.nim
ui/app/AppLayouts/Profile/Sections/AdvancedContainer.qml

Closes #3509.
https://user-images.githubusercontent.com/194260/133298112-6694198a-7df6-4286-8253-ace77bc0c465.mp4
#3509 calls for a button, but a link seems to work nicely. I'll test on Windows and Linux after the CI builds become available for this PR.
For the sake of the screen capture I changed `text: qsTrId("app-logs")` to `text: qsTrId("Application Logs")`, but in the commit it's `text: qsTrId("app-logs")`. For this PR to be merge-worthy, do I need to run the i18n scripts or what exactly?
Also, I wasn't sure the best way to deal with top padding of the `StyledText`, so I divided in half the value for `anchors.topMargin` in `AboutContainer.qml` and it looks about right. However, there may be a better way to deal with the styling, I'm just not familiar with it because I've spent so …

feat(desktop/profile): add link in advanced settings so log directory can be opened directly

---

src/app/chat/event_handling.nim
src/app/chat/view.nim
src/app/chat/views/channel.nim
src/app/chat/views/chat_item.nim
src/app/chat/views/chat_members.nim
src/app/chat/views/community_members_list.nim
src/app/chat/views/message_item.nim
src/app/chat/views/message_list.nim
src/app/chat/views/user_list.nim
src/app/profile/core.nim
src/app/profile/view.nim
src/app/profile/views/contacts.nim

fixes #3485
see dependent PR: https://github.com/status-im/status-lib/pull/37
* correct handling of contacts events, we fetch them from the store and display them rather than having a third contact store not being sync with chat contacts and contacts

fix(@desktop/contacts): Keep only one contacts list

---

ui/app/AppLayouts/Chat/ContactsColumn.qml

**DEPENDS ON https://github.com/status-im/StatusQ/pull/415**
When StatusQ switched to using `DelegateModel` in `StatusChatList` to enable drag and drop,
we lost the API `itemAt` which was previously exposed via the `Repeater` that was aliased as
`chatListItems`.
StatusQ now exposes `statusChatListItems` additionally so we can still access `model.itemAt`
which is used in this commit.
The only reason this is done here though, is because we need to update the profile picture of
contacts when we get a contact changed signal. Ideally, we handle contact changes including the
profile picture entirely in the backend and have it then just rerender the screen (instead of
using a `Connection`).
Fixes #3328

fix(ContactsColumn): call itemAt on statusChatListItems.model instead of delegate

---

Makefile
scripts/fetch-brew-bottle.sh

With these changes it will be easier to maintain, i.e. to add/remove bottles just modify the `BOTTLES :=` list.
`brew update` is removed from `scripts/fetch-brew-bottle.sh` and instead done
in an [order-only prerequisite](https://www.gnu.org/software/make/manual/html_node/Prerequisite-Types.html). This allows multiple bottles to be fetched in parallel (e.g. `make -j16`) without overlapping invocations of `brew update` (which can result in the script failing for one/more bottles).

chore: improve the bottles logic in Makefile

---

src/app/chat/views/messages.nim

fix(@desktop/chat): Push notification body contains only chat key when user is mentioned
fixes #3347

fix(@desktop/chat): Push notification body contains only chat key

---

src/app/chat/view.nim
src/app/chat/views/channel.nim
src/app/chat/views/channels_list.nim
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/ChatText.qml

PR: `status-lib` [here](https://github.com/status-im/status-lib/pull/42)
In case clicked channel:
- exists in a community -> the app will switch you to it
- doesn't exist in a community, but exists in the public chat list -> the app
will switch to `Chat` section and also to the appropriate channel there
- doesn't exist in a community and doesn't exist in the public chat list -> the app
will switch to `Chat` section and join new channel
Fixes: #3489

fix(@desktop/chat): channel links sends to main public channel instead of a channel in that community

---

src/app/chat/core.nim
src/app/chat/views/message_list.nim
src/app/chat/views/messages.nim
ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml
ui/app/AppLayouts/Chat/ChatColumn/Message.qml

Fixes: #3473.
Sometimes when blocking users and changes channels, blocked user messages would still appear.
This PR fixes the issue by toggling a `hide` property on  messages from a contact when that contact is blocked or unblocked. Previously, the messages were only removed from the view when the contact was blocked, but when the view was reloaded, that state was not tracked correctly.

fix: block/unblock contacts not persisting

---

ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/CompactMessage.qml

Fixes #3606.
The “resend” link for failed messages was not aligned correctly in the light theme. This was due to setting the `verticalCenter` as well as `anchors.top` in some situations. `verticalCenter` has been removed in favour of setting the top and bottom anchors.

fix(chat): Re-position “resend” link

---

ui/app/AppLayouts/Chat/ChatColumn/UserList.qml
ui/app/AppLayouts/Chat/CommunityComponents/CommunityUserList.qml

The scrollbar should only be visible when scrolling
through the members list
Closes #3557

fix(desktop/membersList) hide scrollbar when inactive

---

ui/app/AppLayouts/Chat/ChatColumn/SuggestionBox.qml

formattedPlainTextFilter was not reset when suggestion
box was closed causing the insertMention function to be
called again even thought there was no mention in the
chat input
Closes #3535

fix(desktop/chatInput) mentions were misused

---

ui/app/AppLayouts/Chat/ChatColumn.qml
ui/app/AppMain.qml

fix(@desktop/chat): Create separate chatInput for each conversation
Moved the statusChatInput to the repeater in stackview so that each conversation has its own separate textInput area which maintains its own state
fixes #1351

fix(@desktop/chat): Create separate chatInput for each conversation

---

ui/app/AppLayouts/Chat/CommunityComponents/CommunityUserList.qml

fix(@desktop/chat): Online/offline labels are hard to read in darkmode
fixes #3550

fix(@desktop/chat): Online/offline labels are hard to read in darkmode

---

ui/app/AppMain.qml

fix(@desktop/settings): Navbar icon shows a profile icon instead of settings icon
fixes #3615

fix(@desktop/settings): Navbar icon shows a profile icon instead of settings icon

---

src/app/wallet/v2/core.nim

fixes #3659
fixes #3646
Wallet2 needs its own event otherwise wallet1/2 event mixes
and as not everything is implemented in wallet2, it crashes
In this particular case, the account is added into wallet1 but trigger
an event intercepted by wallet2, wallet2 doesn't have the new account
and crash
status-lib PR: https://github.com/status-im/status-lib/pull/47

fix(@desktop/wallet): emit wallet2 event

---

ui/shared/status/StatusGifColumn.qml
ui/shared/status/StatusGifPopup.qml

Fixes: #3564.
Several UI bug fixes have been made for the gif widget:
1. Star now only appears once the gif is hovered
2. Default hover star colour is “grey”
3. Once the star is hovered, the star turns yellow
4. If the gif is favourited, the star fills in yellow
5. Removed square border around the gif
6. Added invisible padding around the star to increase the mouse surface area for hover/click
7. Added tooltip to the star for adding/removing from favourites
1. An initial attempt at changing star state based on gif thumb hover and star hover proved unsuccessful. Changing visibility of the star had to depend on both the hover state of the thumb AND the star — relying on only the thumb hover caused a flicker.
2. Relying on the local hover state of the star and the thumb hover state caused …

fix(chat): GIF widget UI bugs

---

Makefile
config.nims

Homebrew for macOS recently switched the `openssl` bottle from being an alias for `openssl@1.1` to it being an alias for `openssl@3`.
When attempting to link against version 3, the compiler fails with:
```
Undefined symbols for architecture x86_64:
"_SSL_get_peer_certificate", referenced from:
_checkCertName__YJ34V0ITZpxT1cfjKMD8vQ in stdlib_net.nim.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: execution of an external program failed: 'clang  @nim_status_client_linkerArgs.txt'
make: *** [bin/nim_status_client] Error 1
```
Until a change is made in Nim's stdlib to facilitate linking against version 3, we'll use version 1.1.

fix: on macOS download openssl@1.1 bottle because openssl bottle is now alias for openssl@3

---

package-lock.json
package.json

Also modify `package.json` so that npm version must be >= 7 and node version must be >= 10 (same prereq as npm v7). This will avoid `package-lock.json` churn if someone builds with npm version < 7.
---
~~The changes in `package.json` may require changes in the Jenkins macOS environment re: versions of node and npm, so I've made this a draft PR for the time being.~~
The reason for this PR is that yesterday a commit landed in `master` that included a changed `package-lock.json`. See efbc8073e15410b8c4e551c9aece440b4ca59a7e.
When `make run` resulted in `npm i` being run on my laptop, I saw afterward that there were unstaged changes in `package-lock.json`. The reason is that I was using npm v6 while the changes in efbc8073e15410b8c4e551c9aece440b4ca59a7e were a result of npm v7 having been …

build: regenerate package-lock.json with npm v7

---

ui/shared/ImageLoader.qml

This issue is very hard to fix without using some profilers. I've been trying with nim profiler and valgrind and actually not that much useful info there. Actually nim profiler gets stuck when app comes to remote procedure call, and just start hanging, so output file is always empty. Using valgrind is slightly better, but it always end up showing to a calls from macOS dyld lib. I managed to see there a lot of calls to `ImageLoader::recursiveBind` from `ImageLoader::recursiveBindWithAccounting` ([macos dyld class](https://opensource.apple.com/source/dyld/dyld-635.2/src/ImageLoader.cpp.auto.html)) and started to check how we are loading images in the app and applied some changes here.
If this fix does not solve the issue #3626,  it will at least slightly improve performances.

fix(@desktop/chat): abnormal CPU usage and slowness

---

ui/app/AppLayouts/Chat/ChatColumn.qml
ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml
ui/app/AppLayouts/Chat/ChatColumn/Message.qml
ui/app/AppLayouts/Chat/ChatColumn/MessageComponents/CompactMessage.qml

Added animation to highlight selected message
from search popup. Currenly when a message is clicked
from the search results, the user is navigated to
that message but it's not clear where is the
message in the screen
Closes #3562
* When selecting search results from in different chat channels, it might occur that the message list is not scrolled to the selected message. Bug fixed [here](https://github.com/status-im/status-desktop/pull/3696).

feat(desktop/searchMessage) Updating highlight animation

---

src/app/chat/event_handling.nim
src/app_service/tasks/marathon/mailserver/model.nim

- Display loading indicator on login when mailserver messages are requested
- Fix bug where the mailserver that's selected as soon as you login is disconnected while being still in the process of connecting instead of waiting until 10s have passed to try connecting to a different mailserver
- Use status-go version that fixes an issue fetching mailserver messages when more than 999 messages are being verified if they're in the cache

fix: message history issues

---

ui/app/AppMain.qml
ui/main.qml

fix(@desktop/chat): Remember the last tab (in nav bar) opened when status app is reopened
With this fix after a restart the tab which the user was last one (chat, community, wallet, browser, settings) will be the active one.
If the user was on the timeline tab when the app is closed, the app will be launched with the chat tab.
fixes #3559

fix(@desktop/chat): Remember the last tab (in nav bar) opened when status app is reopened

---

ui/app/AppLayouts/Chat/ChatColumn.qml
ui/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml

Position view at chosen message when coming from either search or notifications was not working properly, especially when coming from another channel (eg from desktop to test). Added timer to delay positioning action until the messages model is almost fully loaded so that the view knows all indexes.
Closes #3592, #3683

fix(desktop/chat) fixed position view at index

---

ui/app/AppLayouts/Chat/CommunityComponents/CreateChannelPopup.qml

This was a reference error as there's no `errors` object on `StatusValidator`.
When accessing errors exposed by `StatusInput` we need to dot into the component
reference.

fix(Communities): make channel popup validation work again

---

src/app/login/view.nim
src/app/onboarding/view.nim
src/app/profile/core.nim
src/app/profile/view.nim
src/app_service/service/local_settings/service.nim
src/nim_status_client.nim
ui/app/AppLayouts/Profile/Sections/PrivacyContainer.qml
ui/app/AppLayouts/Profile/Sections/StoreToKeychainSelectionModal.qml
ui/main.qml
ui/onboarding/CreatePasswordModal.qml
ui/onboarding/Login.qml

Since https://github.com/status-im/status-desktop/commit/e0c53b7012354023e367c33093598f7523063aa6 settings where loaded
according to the username while they should be loaded after the public
key
As the public key is only available once the login happened, it needs
to be set when the profile is being initialized
fixes #3624

fix(@desktop/profile): Fix loading the correct settings

---

ui/app/AppLayouts/Profile/views/AppearanceView.qml
ui/app/AppLayouts/Profile/views/DevicesView.qml
ui/app/AppLayouts/Profile/views/EnsAddedView.qml
ui/app/AppLayouts/Profile/views/EnsConnectedView.qml
ui/app/AppLayouts/Profile/views/EnsDetailsView.qml
ui/app/AppLayouts/Profile/views/EnsListView.qml
ui/app/AppLayouts/Profile/views/EnsRegisteredView.qml
ui/app/AppLayouts/Profile/views/EnsReleasedView.qml
ui/app/AppLayouts/Profile/views/EnsSearchView.qml
ui/app/AppLayouts/Profile/views/EnsTermsAndConditionsView.qml
ui/app/AppLayouts/Profile/views/EnsWelcomeView.qml
ui/app/AppLayouts/Profile/views/NotificationsView.qml
ui/app/AppLayouts/Profile/views/SoundsView.qml
ui/app/AppLayouts/Profile/views/SyncView.qml

When we switched to `StatusBaseText` we lost the default theme color.
We probably want to consider giving `StatusBaseText` a default theme color
similar to `StyledText` did.

fix(@desktop/profile): make devices view work in darkmode again

---

ui/app/AppLayouts/Onboarding/panels/AccountListPanel.qml

There is no need to allow user to scroll here as all the 5 chat name options should be visible on the popup already.
fixes #3823

fix(@desktop/onboarding):  All chat names are not displayed on the popup

---

src/app_service/service/contacts/service.nim

It was very hidden issue here, crash is not reproducible neither on mac nor on win if you're building and running the app, but only if you're testing installed app and finally I managed to catch it on Win using windows installer.
The thing is in `JsonNode` cause returned result from the `status_contacts.getContacts` is actually a `JsonNode` which is not an iterable type, and we need to make it iterable first using [getElems](https://nim-lang.org/docs/json.html#getElems%2CJsonNode%2Cseq%5BJsonNode%5D) and then do a for loop over it. Also an exception may happen extracting properties form `toContactsDto` proc raised by Json module, that's why we must have that in try/catch.
@anastasiyaig hope the crash is behind us now.
Fixes: #3953

fix(@refactoring/base_01): crash on recovering account

---

src/app/chat/views/channel.nim
ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
ui/app/AppLayouts/Chat/views/ContactsColumnView.qml

This fixes the issue where the Group Info popup would be empty when opening it from the context menu from the channel column.
This was a very weird issue to track, because sometimes, the channel data would be there, and then a second later, disappear, without ever being changed.
I tried to track down what or where it could change and I didn't exactly find an answer. It just seems that whenever a new API call was received, the memory would be erased.
Basically, what we used to do is call `getChatItemById` to receive the Channel as a fresh view.
While it works when you receive it, I think the garbage collector ends up removing it, because it is not binded to any model.
What I did to fix it is just use the `contextChannel` property we already had. Somehow, it was never used, but that is the …

Fix context menu losing data and group info being empty sometimes

---

src/app_service/service/wallet_account/service.nim

Fixes #4040
Adding the token never crashed for me like the issue says, but enabling it sometimes did.
It was because `fecthBalance` sometimes reverted and it wasn't caught.

fix(wallet): fix getting balance of custom tokens

---

ui/app/AppLayouts/Chat/panels/communities/BackUpCommuntyBannerPanel.qml
ui/app/AppLayouts/Chat/popups/community/CommunityProfilePopup.qml
ui/app/AppLayouts/Chat/popups/community/TransferOwnershipPopup.qml
ui/app/AppLayouts/Chat/stores/RootStore.qml
ui/app/AppLayouts/Chat/views/CommunityColumnView.qml

There was a bug in our store where an API wouldn't return a value.
This commit fixes this and also replaces the legacy `Input` component
with StatusInput
Fixes: #4082

fix(TransferOwnershipPopup): ensure community key is exported properly

---

ui/app/AppLayouts/Profile/views/ContactsView.qml
ui/imports/shared/views/SearchResults.qml

Added logic to update status of the contact being search once it is added to contact list. Basically to show the "check-mark" on the Add Contact modal after a contact was successfully added
Profile/Settings
:dancers:

fix(@desktop/profile): Fix to show a confirmation that the contact was added

---

src/app/modules/main/profile_section/controller.nim
src/app/modules/main/profile_section/controller_interface.nim
src/app/modules/main/profile_section/io_interface.nim
src/app/modules/main/profile_section/module.nim
src/app/modules/main/profile_section/view.nim
src/app_service/common/account_constants.nim
src/app_service/service/accounts/service.nim
src/app_service/service/settings/service.nim
src/app_service/service/settings/service_interface.nim
ui/app/AppLayouts/Chat/stores/RootStore.qml
ui/app/AppLayouts/Chat/views/MessageContextMenuView.qml
ui/app/AppLayouts/Profile/views/AdvancedView.qml

Fixes #4083 
In a separate PR, i'll make the toggle also switch chronicles log level, since it probably makes sense for release versions to run in info level by default (right now it runs in debug level)

feat: add toggle for switching status-go DEBUG log level

---

ui/app/AppLayouts/Browser/BrowserLayout.qml

Closes: #4107
This PR add return new created from `addNewTab()` method and use it for requested opening url.
`BrowserLayout`

fix: Fix missing setup url for new opened tab

---

ui/app/AppLayouts/Wallet/panels/WalletHeader.qml
ui/app/AppLayouts/Wallet/popups/ReceiveModal.qml
ui/app/AppLayouts/Wallet/stores/RootStore.qml

In receive modal the account color was not corresponding to
the actual account color
* Updated StatusAccountSelector to use accounts from
new backend
* Updated WalletHeader to use currentAccount from new
backend
Closes #4071

fix(dekstop/wallet) wrong account color displayed

---

ui/app/AppLayouts/Browser/panels/BrowserHeader.qml
ui/app/AppLayouts/Browser/panels/FavoritesBar.qml

fix(@desktop/browser): Fix for Favorites bar is not shown without disabling and enabling toggle
Also fixed issue of overlap after a switch between disabled to enabled state
fixes #4105
This PR assigns a fixed height of 38 to the FavoritesBar because of which it was seen first time.
It also fixes the issue of overlap after a switch between disabled to enabled state
Browser
https://user-images.githubusercontent.com/60327365/142197548-579bd65f-14e2-4090-a91c-f36a938fdb0e.mov
:dagger:

fix(@desktop/browser): Fix for Favorites bar is not shown without disabling and enabling toggle

---

src/app/chat/views/activity_notification_list.nim
ui/app/AppLayouts/Chat/views/ActivityCenterMessageComponentView.qml

As raised in #3665, users aren't able to mark activity center notifications as unread.
The APIs for that didn't exist yet so they have been added in:
- status-go (https://github.com/status-im/status-go/pull/2383)
- status-lib (https://github.com/status-im/status-lib/pull/53)
respectively.
Closes #3665

feat(ActivityCenter): allow users to mark notifications as unread

---

ui/main.qml

Fixes #4128
The app didn't minimize on Windows and Linux, because the handling of minimizing was moved to the Mac component

fix(app): fix minimizing the app on close for Windows and Linux

---

src/app/boot/app_controller.nim

A call to the init of the language service was missing.
Calling it during boot process resolves the bug.
fixes #4104
A call to the init of the language service was missing.
Calling it during boot process, initialized the path to the .qm files and hence the languages are loaded correctly.
Language
https://user-images.githubusercontent.com/60327365/142438351-17652796-5750-479c-9cf0-223f17d1a5df.mov
:1st_place_medal:

fix(@desktop/profile): changing language does not change it in UI

---

src/app/core/user_profile.nim
src/app/modules/main/profile_section/profile/controller.nim

fix(@desktop/profile): Custom picture is not applied everywhere in the app without restart
fixes #4099
Profile and NavBar
https://user-images.githubusercontent.com/60327365/142012022-13b92bfc-0cae-4c9e-ba9e-ed94a200e82a.mov

fix(@desktop/profile): Custom picture is not applied everywhere in the app without restart

---

ci/Dockerfile
ci/Jenkinsfile.linux
ci/Jenkinsfile.macos

Otherwise cloning of BearSSL fails with:
```
Cloning into '/home/jenkins/workspace/status-desktop/platforms/linux/vendor/status-lib/vendor/nim-task-runner/vendor/nim-bearssl/bearssl/csources'...
fatal: unable to access 'https://www.bearssl.org/git/BearSSL/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
fatal: clone of 'https://www.bearssl.org/git/BearSSL' into submodule path '/home/jenkins/workspace/status-desktop/platforms/linux/vendor/status-lib/vendor/nim-task-runner/vendor/nim-bearssl/bearssl/csources' failed
Failed to clone 'bearssl/csources'. Retry scheduled
```
https://ci.status.im/job/status-desktop/job/platforms/job/linux/125/console
https://blog.dnsimple.com/2021/09/letsencrypt-intermediate-expiration/

ci: upgrade ca-certificates in Linux Docker image

---

ci/Dockerfile
ci/Jenkinsfile.linux

Just upgrading `ca-certificates` is not enough. This works though:
```
> docker run --rm -it -u root statusteam/nim-status-client-build:1.1.2 /bin/bash
root@f7bd54502356:/home/user# git clone https://www.bearssl.org/git/BearSSL
Cloning into 'BearSSL'...
remote: Counting objects: 1948, done.
remote: Compressing objects: 100% (1805/1805), done.
remote: Total 1948 (delta 1508), reused 227 (delta 135)
Receiving objects: 100% (1948/1948), 1.30 MiB | 2.18 MiB/s, done.
Resolving deltas: 100% (1508/1508), done.
root@f7bd54502356:/home/user# 
```
https://www.openssl.org/blog/blog/2021/09/13/LetsEncryptRootCertExpire/
https://blog.dnsimple.com/2021/09/letsencrypt-intermediate-expiration/
https://scotthelme.co.uk/lets-encrypt-old-root-expiration/

ci: manually fix expired LetsEncrypt X3 root cert

---

ui/app/AppMain.qml

fix(@desktop/startUpPage): Fix for footer shown when clicking - share your chat key
fixes #3462
The fix removes the footer when clicking - share you key when no chats are started on a profile
replaced the older profileModule.pubKey with the new profileModule.model.pubKey
AppMain.qml
:)

fix(@desktop/startUpPage): Fix for footer shown when clicking - share your chat key

---

src/app_service/service/contacts/service.nim

This adjust the changes needed to have Status Desktop
talk to new contact related APIs that were introduced in status-lib
and status-go as of https://github.com/status-im/status-lib/pull/110
Closes #4147

fix: make contact related APIs working again

---

src/app/core/local_account_sensitive_settings.nim

Closes #4102
Setting's properties were moved to nim which doesn't
have support for arrays, thus properties recentEmojis,
hiddenCommunityWelcomeBanner,  hiddenCommunityBackUpBanners
and  whitelistedUnfurlingSites were not handled. Added
support for recentEmojis as well as the rest properties.
chat section
https://user-images.githubusercontent.com/31625338/142469941-6fb8e7fa-6cd9-40f2-8240-0a40d648d6f8.mov

fix(desktop/chat) Can't select emoji from the list

---

src/app/modules/main/profile_section/contacts/controller.nim
src/app_service/service/contacts/service.nim

Changes in contact data caused via calls to any contact related APIs wouldn't be
reflected in the UI because it doesn't re-fetch the updated state from status-go.
This commit makes the contactsService `fetchContacts` API public so it can be
used on the profile section control to re-fetch contact data when changes to
contacts have been emitted.

fix: ensure contact data is refetched when changes where made

---

ui/app/AppLayouts/Browser/BrowserLayout.qml
ui/app/AppLayouts/Browser/popups/BrowserConnectionModal.qml

fix(@desktop/browser): Wallet permissions and enter password modals are stretched
fixes #4150
Fixes alignment issues in the popup
Started using StatusModal instead of Popup
Browser

fix(@desktop/browser): Wallet permissions and enter password modals are stretched

---

ui/app/AppLayouts/Browser/stores/WalletStore.qml
ui/app/AppLayouts/Browser/views/WebProviderObj.qml

fix(@desktop/browser): Sign message to dapp is broken
fixes #4154
Uses the correct Api for current wallet account
Browser

fix(@desktop/browser): Sign message to dapp is broken

---

ui/imports/shared/status/StatusStickersPopup.qml

This makes sure we don't wait until all sticker packs are loaded
to show the user that now packs were installed (we know this much earlier).
Fixes #4127

uiux: inform user early when there's no stickers installed

---

ui/main.qml

This broke in https://github.com/status-im/status-desktop/pull/4135 due to incorrect
initialization of `recentEmojis` property in `localAccountSensitiveSettings`.
Closes #4102

fix(@desktop/chat): ensure emoji selection works

---

ui/imports/shared/controls/chat/FetchMoreMessagesButton.qml

Closes #4168
Fetch more messages is spinning indefinitely when
fetch more messages button is clicked and messages
are never displayed
chat messages
https://user-images.githubusercontent.com/31625338/143450811-39308024-d1eb-498a-9246-4e4ef99efcbd.mov

fix(desktop/chat) fetch more messages not working

---

ui/app/AppMain.qml

fix(@desktop/profile): Users profile image/identicon not shown in application navbar
fixes #4170
Used the userProfile module instead of ProfileModule in order to retrieve the thumbnail image
AppMain

fix(@desktop/profile): Users profile image/identicon not shown in application navbar

---

ci/Jenkinsfile.macos

Since now we have a 5th Gen Mac Mini with `arm64` M1 CPU.

ci: specify macos host architecture in labels

---

ui/imports/shared/views/chat/MessageView.qml

fix(@desktop/chat): Blocking a user with big messages leaves an empty space in the chat
fixes #4123
Made height of column 0 when item is not visible
Chat view

fix(@desktop/chat): Blocking a user with big messages leaves an empty space in the chat

---

src/app/global/app_sections_config.nim

fix(@desktop/profile): Application nav bar settings button is incorrect
Updated the settings icon in the config file.
fixes #4172
The PR updates the settings icon name in the config file so that the correct icon is loaded
StatusNavBar in AppMain

fix(@desktop/profile): Application nav bar settings button is incorrect

---

ui/app/AppLayouts/stores/MessageStore.qml
ui/imports/shared/controls/chat/UserImage.qml
ui/imports/shared/panels/chat/ChatReplyPanel.qml
ui/imports/shared/views/chat/CompactMessageView.qml
ui/imports/shared/views/chat/MessageView.qml

Fixes #4185
The binding to the image/identicon was broken, but also, the MessageStore does **not** behave like it should.
Right now, the MessageStore is a single instance, so whenever a message changes the values of the store, it changes them for **all** messages. So if we ever want to use that store, we need to create a new instance for each message,
Anyway, the problem is solved here

fix(reply): fix reply image displaying the current user

---

ui/main.qml

Fixes #4183 and #4205
So turns out the issue for the Windows notifications not working was that the icon was missing/wrong.
I went down the whole DotherSide rabbit hole because the error was emitted from there, but turns out the error happens because the Tray is not found by the C++ code because the Tray fails to load on Windows with a bad icon.
Anyway, Windows notifications work on Windows now and the icon is back on every platform
I think Linux notifs are still broken, I'll try and fix in another PR.

fix(notifications): fix missing task bar icon making notif not work

---

ui/app/AppLayouts/Chat/views/ChatColumnView.qml
ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
ui/app/AppMain.qml
ui/main.qml

Fixes #4183
Linux OS notifications are not implemented in Nim yet, so show them with the TrayIcon QML function.

Fix Linux notifications

---

ui/imports/shared/views/chat/CompactMessageView.qml

Closes #4213
When in message editing mode was not possible to cofirm edit and
close edit mode when pressing enter key as the clicked signal
of the StatusButton is called without an argument, aparently that
signal has a var mouse parameter. Passed null as parameter to
get the signal emitted.
Chat messages
https://user-images.githubusercontent.com/31625338/144319241-0bff8baf-637a-44c9-ab21-b78a9d6acf0f.mov

fix(desktop/chat): Fixed finish editing msg when pressing enter

---

src/app/core/local_app_settings.nim
ui/main.qml

This adds the functionality that the application window size is saved in the
app settings, so that it restores the same size the next time the application
is started.
Closes #4120

feat: preserve app window size after resize

---

ui/imports/shared/controls/chat/MessageMouseArea.qml

Closes #4203
Fixed can't open a sticker pack when clicking a sticker in a chat.
Chat
https://user-images.githubusercontent.com/31625338/143903638-ae7eafff-1724-42f0-82b3-4baec306f2aa.mov

fix(desktop/chat): stickers pack popup not opened

---

src/app/modules/main/stickers/io_interface.nim
src/app/modules/main/stickers/item.nim
src/app/modules/main/stickers/models/sticker_list.nim
src/app/modules/main/stickers/models/sticker_pack_list.nim
src/app/modules/main/stickers/module.nim
src/app/modules/main/stickers/view.nim
src/app/modules/main/wallet_section/accounts/item.nim
src/app_service/service/settings/dto/settings.nim
src/app_service/service/settings/service.nim
src/app_service/service/settings/service_interface.nim
src/app_service/service/stickers/async_tasks.nim
src/app_service/service/stickers/service.nim
ui/imports/shared/status/StatusStickersPopup.qml

- remove dependency on dto in views and use Item instead
- Fix getting installed and recent stickers
- Fix stickers appearing as loading on a new account when joining a channel for the first time
- Remove import to the old status-lib code
Has a dependency on https://github.com/status-im/status-lib/pull/124

Final touches to the sticker refactor + fixes

---

ui/app/AppLayouts/Chat/popups/community/CommunityProfilePopup.qml
ui/app/AppLayouts/Chat/popups/community/CreateCommunityPopup.qml

fixes #4126
When saving the communities all the popup are closed
Create/Edit Community popup

fix(@desktop/communities): Close popup when edit is successful

---

ui/app/AppLayouts/Browser/panels/BrowserHeader.qml

fix(@desktop/browser): Website URL overlaps with reload and add favourite buttons
fixes #4214
Ensures that there is a padding between the url text and the buttons on the right
Browser

fix(@desktop/browser): Website URL overlaps with reload and add favourite buttons

---

ui/app/AppMain.qml
ui/imports/utils/Utils.qml
ui/main.qml

Fixes https://github.com/status-im/status-desktop/issues/4254
Since the timeline was removed, this introduced a little hiccup in
the application section selection.
This commit ensures navigation tab buttons match the correct section.

fix: ensure app tab buuttons match correct app section

---

ui/app/AppLayouts/Chat/popups/community/AccessExistingCommunityPopup.qml
ui/app/AppLayouts/Chat/views/ContactsColumnView.qml

Fixes this error:
```
ERR 2021-11-30 09:14:34.783-04:00 rpc response error                         topics="rpc" tid=480760 file=core.nim:24 result="{\"jsonrpc\":\"2.0\",\"id\":0,\"error\":{\"code\":-32000,\"message\":\"method handler crashed\"}}" payload="[\"\"]" methodName=wakuext_importCommunity
```
which can be seen as soon as you open this dialog:

fix:  RPC method invocation as soon as Import Community popup was opened

---

ui/app/AppLayouts/Chat/stores/RootStore.qml
ui/app/AppMain.qml
ui/imports/utils/Utils.qml
ui/main.qml

There's a bug where the last active community will be set in local settings
and not removed when a user leaves a community.
This causes the app to start on an invalid screen/state as it still tries to
render the community view for a community that the user has just left.
This commit ensure we're resetting the last active community in the local settings
when a users leaves the community.
Fixes: #4094

fix: ensure last active community is reset when leaving community

---

ui/imports/shared/status/StatusChatInput.qml

This broke when we removed timeline support. Most likely because `profileImage`
is undefined, the entire expression fails, leaving `anchors.left` `undefined`,
causing the text area to be slammed to the right.

fix(StatusChatInput): ensure anchors of textfield are set correctly

---

src/app_service/main.nim
src/app_service/service/os_notification/service.nim

This fixes part of the problems with notifications and tray icon on Windows, but there is still a bit more to do, but I have to move to the refactor for now.

fix(notifications): fix notification setup called too soon

---

ui/app/AppLayouts/Browser/BrowserLayout.qml
ui/app/AppLayouts/Browser/panels/BrowserHeader.qml
ui/app/AppLayouts/Browser/panels/BrowserTabView.qml
ui/app/AppLayouts/Browser/panels/DownloadBar.qml
ui/app/AppLayouts/Browser/panels/DownloadView.qml
ui/app/AppLayouts/Browser/panels/FavoritesBar.qml
ui/app/AppLayouts/Browser/panels/FavoritesList.qml
ui/app/AppLayouts/Browser/panels/FindBar.qml
ui/app/AppLayouts/Browser/popups/AddFavoriteModal.qml
ui/app/AppLayouts/Browser/popups/BrowserConnectionModal.qml
ui/app/AppLayouts/Browser/popups/BrowserSettingsMenu.qml
ui/app/AppLayouts/Browser/popups/BrowserWalletMenu.qml
ui/app/AppLayouts/Browser/popups/DownloadMenu.qml
ui/app/AppLayouts/Browser/popups/FavoriteMenu.qml
ui/app/AppLayouts/Browser/popups/SignMessageModal.qml
ui/app/AppLayouts/Browser/stores/BookmarksStore.qml
ui/app/AppLayouts/Browser/stores/RootStore.qml
ui/app/AppLayouts/Browser/views/BrowserShortcutActions.qml
ui/app/AppLayouts/Browser/views/BrowserWebEngineView.qml
ui/app/AppLayouts/Browser/views/WebProviderObj.qml
ui/app/AppMain.qml
ui/imports/shared/popups/SendModal.qml

refactor: remove dynamic scoping from browser module
closes #4246
This PR aims at removing the dynamic scoping within the browser module. Whats done is -
1. Pass component from layout to the child components instead of them accessing it directly via dynamic scoping
2. Add and internal compose tin BrowserLayout so that accessing it from other components is not straightforward to discourage it in the future.
3. Move some logic to the store
4. Removed unnecessary import statements an cleaned up some code
Browser
https://user-images.githubusercontent.com/60327365/145122811-9d228ffe-5c32-4002-a2b1-ee9f9f34bda1.mov

refactor: remove dynamic scoping from browser module

---

ui/main.qml

This is needed because on screens that are too big, the app becomes
huge.

fix: add upper limit to initialized app window size

---

src/app/global/app_sections_config.nim
src/app/modules/main/item.nim
src/app/modules/main/module.nim
ui/app/AppMain.qml
ui/imports/utils/Constants.qml
ui/main.qml

We've recently removed timeline related code from the application.
It seems that either a) new changes have been introduced related to timeline
despite it being removed from the application, or b) a few more changes
where left out as part of the new architecture.
This causes the app to misbehave when selecting sections in the application
nav bar.
This commit fixes this by removing leftover timeline related code.

fix: ensure app sections work correctly

---

ui/imports/shared/views/chat/CompactMessageView.qml

fix(@desktop/chat): Messages do have wrong indentation (alignment) when being sent in a row
Providing temp fix as this component  will be redesigned and moved to StatusQ
fixes #4211
Fixed the alignment issues when chatting in communities
Communities and Chat View

fix(@desktop/chat): Messages do have wrong indentation (alignment) when being sent in a row

---

ui/app/AppLayouts/Chat/ChatLayout.qml

There seems to have been a confusion in how the store is named.

fix: fix access to root store property for user online status

---

ui/app/AppLayouts/Browser/BrowserLayout.qml
ui/app/AppLayouts/Browser/panels/FavoritesList.qml
ui/app/AppLayouts/Browser/popups/AddFavoriteModal.qml

fix(@desktop/browser): Clicking on add buttons adds the same button twice
fixes #4280
This fix ensures that the string are validated so that the "Add" button is not activated when nothing in entered by user
Browser

fix(@desktop/browser): Clicking on add buttons adds the same button twice

---

src/app/modules/main/chat_section/chat_content/messages/controller.nim
src/app/modules/main/chat_section/chat_content/messages/controller_interface.nim
src/app/modules/main/chat_section/chat_content/messages/module.nim
src/app/modules/main/chat_section/chat_content/messages/private_interfaces/module_view_delegate_interface.nim
src/app/modules/main/chat_section/chat_content/messages/view.nim
src/app/modules/main/chat_section/chat_content/module.nim
src/app/modules/shared_models/message_item.nim
src/app/modules/shared_models/message_model.nim
src/app_service/service/message/service.nim
ui/app/AppLayouts/Chat/ChatLayout.qml
ui/app/AppLayouts/Chat/controls/UserDelegate.qml
ui/app/AppLayouts/Chat/panels/UserListPanel.qml
ui/app/AppLayouts/Chat/panels/communities/CommunityUserListPanel.qml
ui/app/AppLayouts/Chat/popups/PinnedMessagesPopup.qml
ui/app/AppLayouts/Chat/stores/MessageStore.qml
ui/app/AppLayouts/Chat/views/ChatColumnView.qml
ui/app/AppLayouts/Chat/views/ChatContentView.qml
ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
ui/app/AppLayouts/Timeline/TimelineLayout.qml
ui/imports/shared/controls/chat/MessageMouseArea.qml
ui/imports/shared/panels/chat/ChatButtonsPanel.qml
ui/imports/shared/panels/chat/ChatReplyPanel.qml
ui/imports/shared/views/chat/CompactMessageView.qml
ui/imports/shared/views/chat/MessageContextMenuView.qml
ui/imports/shared/views/chat/MessageView.qml

- `MessageContextMenuView` is updated a bit in a way that it exposes properties which that component is using, so there is no need to pass entire store or instances of modules to this popup. Also we have appropriate signals for actions which may be performed by this component.
- `PinnedMessagesPopup` is updated in a similar way, only necessary things needed for this popup to work properly are exposed as properties which may be set for this component.
- `MessageStore` moved to `ChatContentView` since it's unique per chat/channel
- `clickMessage` of `MessageView` component updated so it handles all clicks on a certain message and set properties of `MessageContextMenuView` accordingly.

refactor(@desktop/chat-messages): pin/unpin messages and pinned messages list updated

---

src/app/modules/main/module.nim
src/app/modules/main/profile_section/io_interface.nim
src/app/modules/main/profile_section/module.nim
src/app/modules/main/profile_section/notifications/controller.nim
src/app/modules/main/profile_section/notifications/controller_interface.nim
src/app/modules/main/profile_section/notifications/io_interface.nim
src/app/modules/main/profile_section/notifications/item.nim
src/app/modules/main/profile_section/notifications/model.nim
src/app/modules/main/profile_section/notifications/module.nim
src/app/modules/main/profile_section/notifications/private_interfaces/module_access_interface.nim
src/app/modules/main/profile_section/notifications/private_interfaces/module_base_interface.nim
src/app/modules/main/profile_section/notifications/private_interfaces/module_controller_delegate_interface.nim
src/app/modules/main/profile_section/notifications/private_interfaces/module_view_delegate_interface.nim
src/app/modules/main/profile_section/notifications/view.nim
src/app/modules/main/profile_section/view.nim
src/app_service/service/chat/service.nim
ui/app/AppLayouts/Profile/ProfileLayout.qml
ui/app/AppLayouts/Profile/popups/MutedChatsModal.qml
ui/app/AppLayouts/Profile/stores/NotificationsStore.qml
ui/app/AppLayouts/Profile/stores/RootStore.qml
ui/app/AppLayouts/Profile/views/NotificationsView.qml

This PR moved `Profile/Notifications Settings` section to a new structure.
**Note**: This PR is branched off #4343 so please review it first.
@anastasiyaig  just for a reference, I noticed that the following don't work in master:
- `Profile/Notifications Settings` list of muted/unmuted chats is not loaded well after app restart if there are muted chats
- if we have more than one chat only one is displayed in a list
- those lists are not updated on leaving chat action
All that is fixed in `base_bc` (in this PR).

refactor(@desktop/profile-notifications): notifications settings added

---

ui/imports/shared/views/chat/CompactMessageView.qml

Closes #4143
Download an image to a local folder was not working as
clickMessage function was called from root. and root has
no such function. Switched to use clickMessage via dynamic
scoping.
TODO: remove dynamic scoping
chat messages

fix: Cannot download uploaded or embed images in private chat

---

ui/app/AppLayouts/Chat/views/ChatContextMenuView.qml
ui/app/AppMain.qml

`editChannelPopup` was only used in `ChatContextMenuView` and via dynamic scoping. Moved into `ChatContextMenuView` and cleaned up dynamic scoping.
`ChatContextMenuView` and `CreateChannelPopup`

refactor: move editChannelPopup to ChatContextMenuView

---

src/app/core/fleets/fleet_configuration.nim
src/app/core/tasks/marathon/mailserver/controller.nim
src/app/core/tasks/marathon/mailserver/model.nim
src/app/core/tasks/marathon/mailserver/worker.nim

This PR updated the mailserver part so it's referring to the new `status-lib` section now.
Corresponding `status-lib` part:
- https://github.com/status-im/status-lib/pull/150

refactor(@desktop/general): mailservers doesn't refer to the old `status-lib` code

---

ui/app/AppLayouts/Wallet/views/collectibles/CollectibleCollectionView.qml

fixes #3808
In some cases, the opensea API return collection for an owner without
assets, we handle this case in the UI

fix(@wallet): Collection without assets

---

src/app/boot/app_controller.nim
src/app/modules/main/app_search/controller.nim
src/app/modules/main/chat_section/chat_content/messages/controller.nim
src/app/modules/main/chat_section/chat_content/messages/module.nim
src/app/modules/main/chat_section/chat_content/messages/private_interfaces/module_controller_delegate_interface.nim
src/app_service/service/message/service.nim

Fixes #4370
Adds the signal for new messages received
It seems like other signals like reactions and pins might not be there yet as well, but they can be added later since they aren't as needed

fix(chat): add signal to display new messages received

---

src/app/modules/main/chat_section/chat_content/view.nim
src/app/modules/main/chat_section/controller.nim
src/app/modules/main/chat_section/module.nim
src/app_service/service/chat/service.nim
ui/app/AppLayouts/Chat/views/ChatColumnView.qml

https://github.com/status-im/status-desktop/issues/4367
There were 3 small problems, that all compounded in the chat to be empty and unusable when joining (but worked when rebooting)
1. The call to `appendItem` was called before adding the module in the list, so the UI reacted to the new Item, but asked for the module details, but it didn't exist yet
2. The chatDetails weren't loaded on new chats. Now called after the appendItem (plus added the signal to say the details changed)
3. The new chat was not added in the table in the service, resulting in no return

fix(chat): fix loading chats when joining them

---

src/app/modules/main/module.nim

This was because the community when created was not loaded, so it didn't listen to events.

fix(community): fix creating channels in a new community does not work

---

scripts/fetch-brew-bottle.sh
src/app/core/eventemitter.nim
src/app/modules/main/chat_section/chat_content/controller.nim
src/app/modules/main/chat_section/chat_content/messages/controller.nim
src/app/modules/main/chat_section/chat_content/messages/module.nim
src/app/modules/shared_models/message_model.nim
src/app_service/service/mailservers/service.nim
src/app_service/service/message/service.nim

@iurimatias faced 2 issues:
1. initial messages have not been loaded when user joins a public chat
2. messages sent to a certain chat are visible into other chats as well
The second issue is fixed here and received new messages are now filtered by the chat id they belong to.
The first issue is something we need to figure out why it's happening, we have mailserver signals added to the log so we can follow easier what's happening. Added logging refers to the following signals:
- `SignalType.HistoryRequestStarted`
- `SignalType.HistoryRequestBatchProcessed`
- `SignalType.HistoryRequestCompleted`
- `SignalType.HistoryRequestFailed`
Out of 10 tries (starting from an empty Status data and joining public chat) I didn't get initial messages loaded in ~30% cases. If you receive initial history …

refactor(@desktop/chat): loading messages on join public chat

---

ui/imports/shared/popups/SignTransactionModal.qml
ui/imports/shared/views/chat/TransactionBubbleView.qml

fix(@desktop/wallet): Fix for - Recipient of the transaction message is not notified that transaction is completed
Also fixes broken UI when sending/receveing transactions from chat
fixes #2915
This PR fixes the 
1. broken ui for send/received transaction in chat
2. the event of transaction sent not handled correctly in a requestTransaction flow
chat, wallet
https://user-images.githubusercontent.com/60327365/148805554-442f7829-756a-434a-9cb6-2931448600e9.mov

fix(@desktop/wallet): Fix for - Recipient of the transaction message is not notified that transaction is completed

---

src/app/modules/main/chat_section/chat_content/module.nim
src/app/modules/main/chat_section/chat_content/private_interfaces/module_access_interface.nim
src/app/modules/main/chat_section/chat_content/view.nim
src/app/modules/main/chat_section/controller.nim
src/app/modules/main/chat_section/model.nim
src/app/modules/main/chat_section/module.nim
src/app/modules/main/chat_section/private_interfaces/module_controller_delegate_interface.nim
src/app/modules/main/chat_section/sub_model.nim
src/app/modules/main/chat_section/view.nim
src/app/modules/main/module.nim
src/app/modules/main/private_interfaces/module_chat_section_delegate_interface.nim
src/app/modules/shared_models/section_model.nim
src/app_service/service/message/service.nim

- non active chats/channels are made bold if there are new messages inside them
a dot badge is added to the chat/community section if it's needed in that case
- for non active chats/channels count badge is added if there are new mentions
inside them, a count badge is added to the chat/community section if it's needed in
that case
- selecting chat/channel marks messages from it as read and update its displaying
and dot/count badge of chat/community section accordingly
Fixes #4403

refactor(@desktop/chat): reading a channel message does not mark it as read

---

ui/imports/shared/status/StatusChatInput.qml

Closes #3542
The text input in chat was highlighting whatever was starting
with @. Fixed to highlight only valid user mentions.
Chat
https://user-images.githubusercontent.com/31625338/147973493-7f133ef5-0ddd-4bb2-8baa-b8b62cd72e27.mov

fix: The text entry box shouldn't highlight invalid @mentions

---

src/app/modules/main/activity_center/controller.nim

This was proc'ing the `No implementation available` exception

fix(act-center): fix badly named controller function causing a crash

---

ui/imports/shared/views/chat/CompactMessageView.qml

fixes #4413
The issue is caused because of the way the mouse area is implemented for overall mouse area, using the MessageMouseArea to handle this fixes the issue. 
Chat, community

fix(@desktop/chat): on right click no option to pin/unpin messages

---

ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
ui/imports/shared/views/chat/CompactMessageView.qml

A reason why this issue was happening is that prev and next message
were set in a wrong way. An important thing is that list of messages is set
in descending order in terms of `timestamp` of a message, that means a
message with the most recent time is added at index 0.
That further means that getting an index of the previous message from the
current one is defined as `currentIndex + 1` and getting an index of the next
one is defined as `currentIndex - 1`.
Fixes #4417

refactor(@desktop/chat): username is misplaced when sending messages in the channel

---

ui/app/AppLayouts/Chat/popups/GroupInfoPopup.qml

Closes #4386
The members list modal containing the list of profiles within a group chat visualizes 5 members at a time and when scrolling, the new members are bounded inside the corresponding area.
Group Chat / View Group
Scrolling action:

fix(@desktop/chat): Group members list must show only 5

---

src/app/chat/view.nim
ui/app/AppLayouts/Profile/views/PrivacyView.qml
ui/app/AppMain.qml

Fix relations between switches and line sensor and local settins
Closes: #4191
This PR change interaction in `StatusListItem` in Privacy settings
Privacy settings
https://user-images.githubusercontent.com/82511785/144581330-964e4b2e-ed3b-40d4-90f5-275c985542bd.mov

fix(PrivacyView): Fix relations between switches and line sensor and local settins

---

ui/app/AppLayouts/Chat/popups/ProfilePopup.qml
ui/app/AppLayouts/Chat/views/ChatColumnView.qml

Closes [#3547](https://github.com/status-im/status-desktop/issues/3547)
Using a new UI component from [#513](https://github.com/status-im/StatusQ/pull/513) it displays a status bar for blocked users in the user profile view.
Contacts/Blocked Contacts/View Profile
It must be approved PR [#513](https://github.com/status-im/StatusQ/pull/513) before merging the current one

Feat: Add a Blocked bar for blocked user profile

---

src/app/modules/main/communities/module.nim
src/app/modules/main/controller.nim
src/app/modules/main/module.nim
src/app/modules/shared_models/active_section.nim
src/app/modules/shared_models/members_model.nim
src/app/modules/shared_models/section_item.nim
src/app_service/service/community/dto/community.nim
src/app_service/service/community/service.nim
ui/app/AppLayouts/Browser/stores/RootStore.qml
ui/app/AppLayouts/Chat/panels/communities/CommunityProfilePopupMembersListPanel.qml
ui/app/AppLayouts/Chat/panels/communities/CommunityProfilePopupOverviewPanel.qml
ui/app/AppLayouts/Chat/popups/community/CommunityDetailPopup.qml
ui/app/AppLayouts/Chat/popups/community/CommunityProfilePopup.qml
ui/app/AppLayouts/Chat/stores/RootStore.qml
ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
ui/imports/shared/views/chat/InvitationBubbleView.qml

Adds the member list model and hooks it to the popup and front end so that the number of members now works from the model.
Also hooks the event for community updates, so if the community changes from a signal, the changes are reflected.

Add member list model and hook it + updates to community

---

src/app/modules/shared_models/message_model.nim

#4482 
Newest message are being received before the historical one. The historical contains the new message  too so that create duplicate in the list.
Adding a filter when adding many message in the list to guarantee no message with same id can make it to the list

fix(@chat): Guarantee message uniqueness in list

---

ui/app/AppMain.qml
ui/imports/shared/popups/ProfilePopup.qml

Closes #4419
Using `profileStore` property  _profile modal_ shows  ENS name or public key.
_Copy to clipboard_ action copies, as well, the same information.
It also fixes the same issue but in Contact/ViewProfile/ShareProfileURL. It was also showing incorrect info.
ProfileModal/ViewProfile/ShareProfileURL
Contact/ViewProfile/ShareProfileURL
PROFILE MODAL:
CONTACT/VIEW PROFILE:

fix(@desktop/ProfilePopup): [base_bc] share profile url in profile modal is incorrect

---

src/app/modules/main/chat_section/controller.nim
src/app/modules/main/chat_section/controller_interface.nim
src/app/modules/main/chat_section/module.nim
src/app/modules/main/chat_section/private_interfaces/module_view_delegate_interface.nim
src/app/modules/main/chat_section/view.nim
src/app/modules/main/communities/controller.nim
src/app/modules/main/communities/controller_interface.nim
src/app/modules/main/communities/module.nim
src/app/modules/main/communities/private_interfaces/module_access_interface.nim
src/app/modules/main/communities/view.nim
src/app/modules/shared_models/section_model.nim
ui/app/AppLayouts/Chat/panels/communities/CommunityProfilePopupMembersListPanel.qml
ui/app/AppLayouts/Chat/panels/communities/CommunityWelcomeBannerPanel.qml
ui/app/AppLayouts/Chat/popups/community/CommunityProfilePopup.qml
ui/app/AppLayouts/Chat/popups/community/MembershipRequestsPopup.qml
ui/app/AppLayouts/Chat/stores/RootStore.qml
ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
ui/app/AppLayouts/stores/RootStore.qml
ui/app/AppMain.qml

Fixes #4473 and #4485
This moves the membership request function as well as two others to the chat_section module, since they are for that specific section (community), therefore, we can remove the community_id from the function calls and use `sectionId`.
It also removes the use of `observedCommunity` from AppMain, instead, for the community context menu, we use the communitySectionModule and community model.
Sadly, this didn't fix the active_setion crash (see https://github.com/status-im/status-desktop/pull/4465#discussion_r785491337)

refactor(community): move membership functions to chat_section

---

ui/imports/shared/controls/ContactsListAndSearch.qml

Closes #4416
Invite friends button placed to be consistent with other views like in GroupChat/Add members popup.
Community/Add Members
Example of another view to be consistent:

fix(@communities/InviteFriends): [base_bc] invite friends button is misplaced

---

src/app/modules/main/chat_section/controller.nim
src/app/modules/main/chat_section/controller_interface.nim
src/app/modules/main/chat_section/module.nim
src/app/modules/main/chat_section/private_interfaces/module_view_delegate_interface.nim
src/app/modules/main/chat_section/view.nim
src/app/modules/main/communities/controller.nim
src/app/modules/main/communities/controller_interface.nim
src/app/modules/main/communities/module.nim
src/app/modules/main/communities/private_interfaces/module_access_interface.nim
src/app/modules/main/communities/view.nim
src/app_service/service/community/service.nim
ui/app/AppLayouts/Chat/panels/communities/CommunityProfilePopupInviteFriendsPanel.qml
ui/app/AppLayouts/Chat/panels/communities/CommunityWelcomeBannerPanel.qml
ui/app/AppLayouts/Chat/popups/community/CommunityProfilePopup.qml
ui/app/AppLayouts/Chat/popups/community/CreateCommunityPopup.qml
ui/app/AppLayouts/Chat/popups/community/InviteFriendsToCommunityPopup.qml
ui/app/AppLayouts/Chat/stores/RootStore.qml
ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
ui/app/AppLayouts/stores/RootStore.qml
ui/app/AppMain.qml

Fixes #4489
This moves the remaining community functions that are not general to the chat_section. It also fixes some small missing hooks (for members for example) 
There are other functions that will need to be moved, like the category ones and some others, but they are not yet fully implemented on the front-end, and in the case of categories, are being worked on by @borismelnik so I don't want to conflict with his work.

Move community specific functions to chat_section

---

ui/app/AppLayouts/Chat/popups/community/CreateChannelPopup.qml

Closes #4444
Fixed create button to be disabled when name and description
text fields are empty in create channel popup
Create channel popup

fix: create channel popup create button was enabled always

---

src/app/modules/main/chat_section/chat_content/controller.nim
src/app/modules/main/chat_section/chat_content/messages/controller.nim
src/app/modules/main/chat_section/chat_content/messages/module.nim
src/app/modules/main/chat_section/chat_content/messages/private_interfaces/module_controller_delegate_interface.nim
src/app/modules/main/chat_section/chat_content/module.nim
src/app/modules/main/chat_section/chat_content/private_interfaces/module_controller_delegate_interface.nim
src/app/modules/shared_models/message_item.nim
src/app/modules/shared_models/message_model.nim
src/app/modules/shared_models/message_reaction_item.nim
src/app/modules/shared_models/message_reaction_model.nim
src/app_service/service/message/service.nim

Desktop app does handle message reactions properly now.
Reactions are properly handled by the pinned messages model as well.
Fixes #4525

fix(@desktop/chat-messages): [base_bc] adding emoji to a message does not reflect on desktop

---

src/app/modules/main/module.nim
src/app/modules/main/view.nim
src/app/modules/shared_models/section_model.nim

Fixes #4566
The problem was that when no community exists, there were no community section in the model, so the new section was added last.
There might be a follow up StatusQ fix to make the StatusAppNavBar a bit smarter or order better in a later case were we want the communities always second, but this fix works.

fix(community/section): fix new community order in the sections

---

src/app_service/service/chat/service.nim

Reply to a reply is not visible sometimes, because we fetch for the last reply on the 0th index of the messages received in response to the sendMessage API. However the last reply may not be at 0th position but also at some other position.
In this fix, I am sending the event for the message to be updated for all messages that have a response to and as it correctly filters out the duplicate entries, the correct one is listed
chat

fix(@desktop/chat): can't reply to a reply

---

ui/app/AppLayouts/Chat/views/ChatColumnView.qml
ui/app/AppMain.qml

Fixes #4586
The problem was that the popup was put in the `ChatColumnView` and the `ChatColumnView` is repeated for each community, plus the normal chat section. So if you have joined 3 community, clicking an image triggered the image opening 4 times, so you would have had to close it 4 times (4 clicks)

fix(image-modal): fix having to click multiple times to close the image

---

ui/app/AppLayouts/Chat/views/ChatContentView.qml
ui/imports/shared/status/StatusChatInput.qml

Fixes #4524
When new channel/chat is selected, text input field focus is forced properly.
Chat-Channel / Input Message focus

Fix/issue 4524: [base_bc] selecting a channel does not auto-focus on the text input field

---

src/app/modules/main/app_search/controller.nim
src/app/modules/main/app_search/controller_interface.nim
src/app/modules/main/app_search/module.nim
src/app/modules/main/app_search/private_interfaces/module_view_delegate_interface.nim
src/app/modules/main/app_search/result_model.nim
src/app/modules/main/app_search/view.nim
src/app/modules/main/chat_section/chat_content/messages/controller.nim
src/app/modules/main/chat_section/chat_content/messages/controller_interface.nim
src/app/modules/main/chat_section/chat_content/messages/module.nim
src/app/modules/main/chat_section/chat_content/messages/private_interfaces/module_controller_delegate_interface.nim
src/app/modules/main/chat_section/chat_content/messages/view.nim
src/app/modules/main/chat_section/controller.nim
src/app/modules/main/chat_section/module.nim
src/app/modules/main/chat_section/private_interfaces/module_controller_delegate_interface.nim
src/app/modules/main/controller.nim
src/app/modules/shared_models/message_model.nim
src/app_service/service/chat/service.nim
src/app_service/service/message/service.nim
ui/app/AppLayouts/Chat/views/ActivityCenterMessageComponentView.qml
ui/app/AppLayouts/Chat/views/ChatColumnView.qml
ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
ui/app/AppLayouts/stores/AppSearchStore.qml
ui/app/AppLayouts/stores/RootStore.qml
ui/app/AppMain.qml
ui/app/AppSearch.qml
ui/imports/shared/views/chat/MessageView.qml

This PR fixes:
- broken "jump to a section/chat/message" feature
- added loading indicator while searching is in progress
- animation when we point to the searched message is in place again
Fixes #4577
**Note**:
When db is a bigger one (has lot of chats/messages...) searching lasts for a while, maybe we should improve a query on the `status-go` side and/or do some indexing in db and/or add some pagination in the search result panel (display only the newest 20 messages at first and scrolling down to load more and more as needed).

fix(@desktop/app-search): [base_bc] can't jump to a message from search results

---

ui/app/AppLayouts/Browser/popups/BrowserConnectionModal.qml

Fixes #4547
Add Theme in ´StatusBaseText´ components used in ´BrowserConnectionModal´.
Browser / Permissions Modal

fix(@desktop/browser): [base_bc] permissions modal looks off in dark mode

---

ui/app/AppLayouts/Chat/panels/EmptyChatPanel.qml
ui/app/AppLayouts/Chat/panels/EmptyViewPanel.qml
ui/app/AppLayouts/Chat/panels/communities/CommunityProfilePopupInviteFriendsPanel.qml
ui/app/AppLayouts/Chat/popups/PrivateChatPopup.qml
ui/app/AppLayouts/Chat/views/ChatColumnView.qml
ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
ui/app/AppLayouts/Profile/ProfileLayout.qml
ui/app/AppLayouts/Profile/views/AboutView.qml
ui/imports/shared/controls/ContactsListAndSearch.qml
ui/imports/shared/controls/CopyToClipBoardButton.qml
ui/imports/shared/popups/InviteFriendsPopup.qml
ui/imports/shared/status/StatusSectionDescItem.qml
ui/imports/shared/views/NoFriendsRectangle.qml
ui/imports/utils/Constants.qml

Fixes #4529
It has been added root store propagation in order to use the global `copyToClipboard` method.
`InviteFriendsPopup` has been refactored to use StatusQ components.
Chat / InviteFriends button
Settings / About / App version and Node version
- **Invite Friends button**
- **App version and Node version**

fix(@desktop/CopyToClipboard): [base_bc] can't copy from Invite friends as well as App Version and Node Version

---

ui/app/AppLayouts/Wallet/WalletLayout.qml
ui/app/AppLayouts/Wallet/panels/WalletHeader.qml
ui/app/AppLayouts/Wallet/views/RightTabView.qml
ui/app/AppLayouts/WalletV2/WalletV2Layout.qml
ui/app/AppLayouts/WalletV2/panels/WalletHeaderPanel.qml
ui/app/AppMain.qml
ui/imports/shared/status/StatusExpandableAddress.qml

Fixes #4636
Store propagation in order to use the global `copyToClipboard` method.
It is also applied in WalletV2.
Wallet / Wallet address copy to clipboard

fix(@desktop/wallet): [base_bc] can't copy wallet address

---

src/app_service/service/bookmarks/service.nim
ui/app/AppLayouts/Browser/popups/FavoriteMenu.qml

Fixes #4549
Edit existing bookmark name is now correctly updated in the view.
Browser / Edit existing bookmark

fix(@desktop/browser): [base_bc] renaming bookmark is not persistent

---

src/app/modules/main/chat_section/module.nim
src/app/modules/main/module.nim
src/app/modules/main/private_interfaces/module_chat_section_delegate_interface.nim

This issue was mostly fixed in `base_bc`, but now I rechecked it and improved it a bit more handling some edge cases.
Here is a [video](https://drive.google.com/file/d/1JUDp9jOBALbLhi-cByh2Ef7bOo4E33Ne/view?usp=sharing) where I tested the behaviour. I used mobile app and firstly added normal messages in community, for both channels that's the reason why blue dot was added. Then I opened community where after marking second channel in the community blue dot for community went away. Then I tested mentions and you may see in the video what is mentions behaviuor.
Fixes #3630

fix(@desktop/chat): the @mention emblem isn't being displayed on the channel list

---

src/app_service/service/contacts/async_tasks.nim
ui/app/AppLayouts/Profile/views/ContactsView.qml
ui/imports/shared/views/SearchResults.qml

@Khushboo-dev-cpp please check in the app do changes I did here (in `contacts/async_tasks.nim`) affect somehow what you fixed in your PR regarding searching for user's address when you want to send him a transaction. If it does affect please give me the steps how to reproduce it, since I tried and it looked ok for me.
Fixes #4658

fix(@desktop/settings-contacts): it is not possible to add new contacts after the first one is added

---

src/app/modules/main/wallet_section/transactions/controller.nim
src/app/modules/main/wallet_section/transactions/controller_interface.nim
src/app/modules/main/wallet_section/transactions/io_interface.nim
src/app/modules/main/wallet_section/transactions/module.nim
src/app/modules/main/wallet_section/transactions/view.nim
src/app_service/service/eth/dto/contract.nim
src/app_service/service/eth/dto/method_dto.nim
src/app_service/service/transaction/service.nim
src/app_service/service/wallet_account/service.nim
ui/app/AppLayouts/stores/RootStore.qml
ui/imports/shared/popups/SendModal.qml
ui/imports/shared/stores/RootStore.qml

Fixes #4650 and more
This started as a fix for the Gas estimation, but I found that the whole wallet Send was not hooked, so I did it all before @anastasiyaig could go ahead and complain (jk... unless 🤫 )
There will still be remaining work, but the normal flow to send ETH and tokens (tested with STT) works.
The remaining work includes:
- Making the service functions async and hook the Connections again
- Adding a debounce to the calls for estimatingGas and getting the fiatPrice would be good too, because it causes a small lag when typing a value currently

Fix Wallet send of ETH and tokens

---

ui/app/AppLayouts/Chat/popups/PinnedMessagesPopup.qml
ui/imports/shared/panels/chat/ChatButtonsPanel.qml
ui/imports/shared/views/chat/CompactMessageView.qml
ui/imports/shared/views/chat/MessageContextMenuView.qml
ui/imports/shared/views/chat/MessageView.qml

Fixes #4540
This fits the design on Figma (at least the old one that we still have)

fix(pins): only enable jump to and unpin buttons from the pinned popup

---

src/app/modules/main/browser_section/provider/controller.nim
src/app_service/service/provider/dto.nim
src/app_service/service/provider/service.nim
src/app_service/service/provider/service_interface.nim
ui/app/AppLayouts/Browser/popups/BrowserConnectionModal.qml
ui/app/AppLayouts/Browser/views/WebProviderObj.qml

Fixes #4721
This was hard to debug, because it hapended with the merge/clash of master and base_bc.
Basically, both master and base_bc sent the provider calls correctly, but when they merged, they both had small mistakes that compounded in each other, making it totally explode.
Also, tracking bugs with the provider is hard.
Anyway, the issue was that we passed 1 parameter at one place, and two at an other, so the call ended up not working. Also, I hit the "No implementation available" issue, but again, I didn't have that message, it just crashed.

fix(browser-provider): fix browser provider not asking for authorization

---

ui/main.qml

Fixes #4698
This is needed because on screens that are too big, the app becomes huge.

fix: [re-add] add upper limit to initialised app window size

---

src/app/modules/main/chat_section/active_item.nim
src/app/modules/main/chat_section/active_sub_item.nim
src/app/modules/main/chat_section/base_item.nim
src/app/modules/main/chat_section/controller.nim
src/app/modules/main/chat_section/item.nim
src/app/modules/main/chat_section/model.nim
src/app/modules/main/chat_section/module.nim
src/app/modules/main/chat_section/private_interfaces/module_controller_delegate_interface.nim
src/app/modules/main/chat_section/sub_item.nim
src/app/modules/main/chat_section/sub_model.nim
src/app/modules/main/chat_section/view.nim
ui/app/AppLayouts/Chat/views/ChatColumnView.qml
ui/app/AppLayouts/Chat/views/ChatContentView.qml
ui/imports/shared/popups/ProfilePopup.qml

- blocked bar is added for profile popup
- blocked bar is added for a chat
Within this pr new field `blocked` is added to the item and subItem of the `chatsModel` and it is updated correctly in case of `Chat` section. Adding `blocked` to subItem gives us possibility to easily add "blocking" feature to community's channels later (when that become a request), but till then `blocked` prop is set to `false` in case of community for all channels.
Fixes #4673

fix(@desktop/chat): add a blocked bar for blocked user profile

---

src/app/modules/main/module.nim

Fixes #4519
Fixed switching/highlight between community and regular navigation button after a newly **created** and/or **edited** community.
Active property value in `createCommunityItem(..)` has been set depending on if the current active section corresponds with the item we are going to create.
Community navigation bar
https://user-images.githubusercontent.com/97019400/152738261-cda02d95-7daa-45aa-82a3-a1113ee45baf.mov

fix(@desktop/communities): Newly created Community remains highlighted

---

ci/Jenkinsfile.linux
ci/Jenkinsfile.macos
ci/Jenkinsfile.windows

It appears this was some leftover from ancient times and wasn't being used.
On the other hand the `RELEASE` environment variable controls if Nim builds
of the client binary include debug symbols:
https://github.com/status-im/status-desktop/blob/ba7a6d5d341d273d0a1e48439dd19ae0ded95cfe/Makefile#L177-L184
The shorthand `?:` symbol means that if this is changed for a given job it stays changed.
Thanks to @abhi-status who noticed the confusing inconsistency.
__EDIT:__ Also added `VERBOSE` parameter because it's convenient.

ci: drop unused BUILD_TYPE, add useful RELEASE param

---

CMakeLists.txt

fix: Add a min cmake version for the cpp app so that the user is prompted to install the latest cmake version instead of getting an ambiguous error

fix: Add a min cmake version for the cpp app

---

ui/imports/shared/status/StatusChatInput.qml

Fixes #4678
The text input in chat was highlighting whatever was starting
with @. Fixed to highlight only valid user mentions.
Also fixes an issue where mentioning yourself would make writing text and a space emptied the input

fix: [re-add] The text entry box shouldn't highlight invalid @mentions

---

ui/app/AppLayouts/Browser/BrowserLayout.qml
ui/imports/shared/popups/ModalPopup.qml

Closes #4361
Fixed transaction popup position
Fixed JSDialogWindow title was going off popup boundaries
Browser, ModalPopup

fix(Browser) Transaction Popup was misaligned

---

src/app_service/common/message.nim
src/app_service/common/utils.nim
src/app_service/service/ens/utils.nim

Fixes #3634
As discussed internally, names with `stateofus.eth` will only show `@name`
Names with only `.eth` or other subdomain will show the whole name `@name.eth`
Three word names show as before as well as nicknames.

fix(mentions): fix showing .eth for normal ENS names in chat

---

src/app/modules/main/chat_section/chat_content/users/controller.nim
src/app/modules/main/chat_section/chat_content/users/controller_interface.nim
src/app/modules/main/chat_section/chat_content/users/module.nim
src/app/modules/main/communities/controller.nim
src/app/modules/main/communities/controller_interface.nim
src/app/modules/main/communities/module.nim
src/app/modules/main/controller.nim
src/app/modules/main/controller_interface.nim
src/app/modules/main/module.nim
src/app/modules/shared_models/active_section.nim
src/app/modules/shared_models/section_item.nim
src/app/modules/shared_models/user_item.nim
src/app/modules/shared_models/user_model.nim
ui/app/AppLayouts/Chat/panels/SuggestionFilterPanel.qml
ui/imports/shared/status/StatusChatInput.qml

Fixes #3707
I upgraded the item and model to contain the ensname, nickname and alias. That way the filter can check any of those when searching the mention

fix: make mentions work with ensname, alias and nickname

---

src/app/modules/main/chat_section/chat_content/messages/controller.nim
src/app/modules/main/chat_section/chat_content/messages/controller_interface.nim
src/app/modules/main/chat_section/chat_content/messages/module.nim
src/app/modules/main/chat_section/chat_content/messages/private_interfaces/module_controller_delegate_interface.nim
src/app/modules/main/chat_section/chat_content/messages/view.nim
src/app/modules/main/chat_section/controller.nim
src/app/modules/main/chat_section/module.nim
src/app/modules/main/chat_section/private_interfaces/module_controller_delegate_interface.nim
src/app/modules/main/chat_section/view.nim
ui/app/AppLayouts/Chat/stores/MessageStore.qml
ui/app/AppLayouts/Chat/stores/RootStore.qml
ui/app/AppLayouts/Chat/views/ChatContentView.qml
ui/app/AppLayouts/Chat/views/ChatMessagesView.qml

I also moved the loading indicator code in nim one level up because it applies to all chats, not only to the current active chat.
Fixes #4733

fix: continue showing loading indicator when store fetching failed

---

ui/app/AppLayouts/Chat/popups/GroupInfoPopup.qml

Closes: #4840
Hide `Add members` button if you not an admin
Group info popup
<=====
=========>--------------  *PIU PIU PIU*
=========>--------------
<=====

fix(Groups): block add members button for non-admin in group chat

---

src/app/modules/main/app_search/view.nim
ui/app/AppLayouts/Chat/popups/GroupInfoPopup.qml
ui/app/AppMain.qml
ui/app/AppSearch.qml

Fixes #4795
Makes sure to only open the profile popup if the click is a pubkey.
Also opens the popup on ctrl+f

fix(search): fix profile popup opened on search title clicked

---

src/app/modules/main/chat_section/chat_content/messages/module.nim
src/app/modules/main/chat_section/chat_content/messages/private_interfaces/module_view_delegate_interface.nim
src/app/modules/main/chat_section/chat_content/messages/view.nim
ui/app/AppLayouts/Chat/ChatLayout.qml
ui/app/AppLayouts/Chat/stores/MessageStore.qml
ui/app/AppLayouts/Chat/views/ChatContentView.qml
ui/imports/shared/panels/chat/ChatReplyPanel.qml
ui/imports/shared/status/StatusChatImageLoader.qml
ui/imports/shared/status/StatusChatInputReplyArea.qml
ui/imports/shared/status/StatusGifPopup.qml
ui/imports/shared/views/chat/CompactMessageView.qml
ui/imports/shared/views/chat/LinksMessageView.qml
ui/imports/shared/views/chat/MessageView.qml
ui/imports/shared/views/chat/StatusUpdateView.qml

If there are more chats containing gifs, only gifs displayed in the active chat will be playing and that will be only if the app is active, in case the app is not the active window all gifs will be paused.
Gif panel is now unloaded once it gets closed, so there are no placed gifs any more once we close gif panel.
Another improvement we can do here is to pause gifs if they go out of the visible area of the list view, but for that I am not fully sure if we can do it well with the current qml structure, but maybe we should try. But also I think that ListView unloads delegates if they go out of visible area (not completely sure).
Fixes #4829

fix(@dekstop/chat): higher cpu usage after opening gif selector

---

ui/imports/shared/views/chat/MessageView.qml

Fixes #4852
The problem happened when the admin wrote first, because the system text saying "X invited Y to the group" was counted as being made by the host, even though it's not really. 
Since we have a condition that hides the image and username of the message if the user wrote twice, or more, in a row, in a short period of time, then in this case, the name and image didn't appear, because the code considered the last message to be made by the same user.

fix(groups): fix first message of group chats not appearing

---

src/app/modules/main/chat_section/controller.nim
src/app/modules/main/chat_section/module.nim
src/app/modules/main/chat_section/private_interfaces/module_controller_delegate_interface.nim

A crash happened here because of wrong chat filtering most likely. At this moment adding new channel to one of community adds it twice and also add it to all other communities as well as to the Chat section. When that comes to chat section module of a certain community and `addNewChat` proc need to be executed for a channel which has `categoryId` set but a category with that id is not added to that community, we didn't have check if item is `nil` and that's the main reason of a crash.
Now the code is slightly updated that all chats/channels changes are being just ignored by the chat section module if they don't belong to it.
Fixes #4827

fix(@dekstop/chat): dogfooding_3 crash

---

src/app/modules/main/chat_section/controller.nim
src/app/modules/main/chat_section/model.nim
src/app/modules/main/chat_section/module.nim
src/app/modules/main/chat_section/private_interfaces/module_controller_delegate_interface.nim
src/app/modules/main/chat_section/sub_model.nim
src/app_service/service/chat/dto/chat.nim
src/app_service/service/community/service.nim
ui/app/AppLayouts/Chat/stores/RootStore.qml
ui/app/AppLayouts/Chat/views/ChatContentView.qml

Fixes #4859, #4858, #4865, #4753
The problem was that signals were received with chat updates, but we didn't check the communityId correctly, and also we didn't check if the chat wasn't added yet.
This also implements the community category signal handling, making it possible to update the categories and chats within it when updating from another device. It also fixes issues of duplication when doing that.

Fix duplicate channels on community signals for edits and category changes (implements all category signal)

---

src/app_service/service/eth/dto/method_dto.nim
src/app_service/service/transaction/service.nim
ui/imports/shared/popups/SendModal.qml
ui/imports/shared/popups/SignTransactionModal.qml
ui/imports/shared/views/chat/AcceptTransactionView.qml

Async methods for send transaction is not impolemented yet and this is a fix until the proper flow is implemented.
Also resolves the same issue observed in chat section.
fixes #4821
This fix emits a transaction sent event with the error when calling the send api from status_go to represent any error observed when sending a transaction.
Wallet, Chat
https://user-images.githubusercontent.com/60327365/155593694-fd609619-fbc7-442e-a3b5-d2e4db975037.mov

fix(@desktop/wallet): Sign transaction accepts incorrect password

---

src/app/modules/main/chat_section/chat_content/messages/module.nim
src/app/modules/shared_models/message_item.nim
src/app/modules/shared_models/message_model.nim
ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
ui/imports/shared/controls/chat/GapComponent.qml
ui/imports/shared/views/chat/MessageView.qml

Issue with wrong timestamp is fixed and another UI issue is fixed also where to long text of the `Fetch messages` message was cut and its ends were not visible if you reduce the app with, now it is displayed as multiline text in that case.
Fixes #4850

fix(@dekstop/chat): timestamp for `Fetch messages` is wrong

---

src/app/modules/main/controller.nim
src/app/modules/main/controller_interface.nim
src/app/modules/main/module.nim
src/app/modules/main/private_interfaces/module_controller_delegate_interface.nim
src/app/modules/main/private_interfaces/module_view_delegate_interface.nim
src/app/modules/main/view.nim
src/app_service/service/node/service.nim
ui/app/AppLayouts/Chat/views/ChatContentView.qml
ui/imports/shared/panels/ImageLoader.qml
ui/imports/shared/status/StatusStickersPopup.qml

I started this as a possible fix to https://github.com/status-im/status-desktop/issues/4810, but it seems like the events to re-fetch was already there. The banner however wasn't so now we have a UI element to show we reconnected

refactor: re-hook disconnected and re-connected signals and banner

---

ui/app/AppLayouts/Chat/ChatLayout.qml

Don't allow the chat sidebar to be resized. Fixes  #4882
The main interface. After this change user, won't see the cursor to drag the side of the sidebar

fix(layout) Keep chat sidebar at a fixed width #4882

---

src/app/modules/main/wallet_section/saved_addresses/controller.nim
src/app/modules/main/wallet_section/saved_addresses/controller_interface.nim
src/app/modules/main/wallet_section/saved_addresses/io_interface.nim
src/app/modules/main/wallet_section/saved_addresses/module.nim
src/app/modules/main/wallet_section/saved_addresses/view.nim
src/app_service/service/saved_address/service.nim
src/app_service/service/saved_address/service_interface.nim
ui/app/AppLayouts/Wallet/WalletLayout.qml
ui/app/AppLayouts/Wallet/controls/SavedAddressesError.qml
ui/app/AppLayouts/Wallet/popups/AddEditSavedAddressPopup.qml
ui/app/AppLayouts/Wallet/stores/RootStore.qml
ui/app/AppLayouts/Wallet/views/LeftTabView.qml
ui/app/AppLayouts/Wallet/views/SavedAddressesView.qml
ui/app/AppMain.qml
ui/imports/shared/controls/AddressInput.qml
ui/imports/shared/controls/ContactsListAndSearch.qml
ui/imports/shared/controls/RecipientSelector.qml

fixes #4747
Readied Saved addresses from wallet V2
Wallet

fix(@desktop/wallet): Re-add saved addresses view from Wallet V2

---

ui/app/AppLayouts/Chat/views/ChatColumnView.qml
ui/app/AppLayouts/Chat/views/ChatContentView.qml
ui/app/AppMain.qml
ui/imports/shared/status/StatusChatInput.qml
ui/imports/utils/Global.qml
ui/main.qml

Fixes #4904
Moves drag zone to the AppMain so that we can check if the current chat accepts the images
Also disables the Input Connection if the channel is not active, because there was also the issue that once you drag an image, all Inputs captured it.

fix(drag-zone): make drag zone only work in correct chats

---

ui/app/AppLayouts/Profile/panels/MenuPanel.qml
ui/app/AppLayouts/Profile/stores/ProfileSectionStore.qml

Fixes #4916
All changes described in #4916
Profile settings list
New visibility behaviour:
https://user-images.githubusercontent.com/61889657/156754281-4a1bf7c0-5a5b-41e9-9016-8962f9f040f2.mov

chore(@desktop/profile): Change labels and ordering in Profile settings list

---

ui/app/AppLayouts/Chat/popups/GroupInfoPopup.qml

Root cause: the name used as input for the naming edit field was sourced from the active group entry which is updated only hen switching the active group.
fixes #4910
Group Chats

fix(group-chats): wrong group name in a subsequent edit attempt

---

ui/app/AppLayouts/Chat/views/ChatColumnView.qml

Removes some duplication for the category and normal channels that was suggested here: https://github.com/status-im/status-desktop/pull/4929#discussion_r818429901
Also, and more importantly, in the second commit, I put the `ChatContentView` in a Loader that is disabled by default.
What this does is speeding up the initial app load since only one channel will be loaded. It also reduces the initial memory usage.
We retain the channel switching speed improvement we implemented last time, because once a channel is loaded, we don't unload it when switching, we just hide it like before.
The only downside of this change is that the first load of a clicked channel can have a mini delay, since it loads the content. However, once it is loaded, you can go back and forth between it and another and it …

Improve ChatContentView loading and duplication

---

ui/imports/shared/status/StatusChatInput.qml

Fixes https://github.com/status-im/status-desktop/issues/4981
It was still possible for the cursor to get inside mentions when ctrl+left was pressed. Added condition to preven this.
chat text input / mentions

fix(chat/textInput): prevent break mentions when ctrl+left is pressed

---

ui/app/AppLayouts/Chat/panels/communities/CommunityProfilePopupInviteFriendsPanel.qml
ui/app/AppLayouts/Chat/panels/communities/CommunityProfilePopupOverviewPanel.qml

Change copy buttons tooltip text from “Copy to clipboard” into “Copied!” in panels: "Add members" and "Manage community"
Fixes #3520
Chat / communities

fix(desktop/chat): Update copy button tooltip text in communities

---

ui/imports/utils/Utils.qml

Closes #3510 
Depends on https://github.com/status-im/status-desktop/pull/4889
When pasting 
A
B
C
D
in text input ,
A
B
C
D
was received
Chat messages
https://user-images.githubusercontent.com/31625338/156405606-e9517525-9ba1-4a66-9b54-ff3135c24200.mov

fix(chatMessages): line breaks in message were not respected when pasting text

---

ui/imports/shared/popups/NicknamePopup.qml
ui/imports/shared/popups/ProfilePopup.qml
ui/imports/shared/status/StatusChatInput.qml

Changes
- Show beam mouse cursor over the chat message field
- Fix applying edit of nickname using the enter key
Chat edit control, Nickname edit control

fix(chat): Show beam mouse cursor over the chat message field

---

ui/imports/shared/views/chat/MessageContextMenuView.qml

Fixes #4907
Do not display "Send message" action when right-clicking community member which 
is logged-in.
Communities / members list
https://user-images.githubusercontent.com/61889657/157437853-0b13b477-a2ba-4631-88d2-0c96aa389b69.mov

fix(desktop/chat): Do not display "Send message" to logged-in user

---

src/app/boot/app_controller.nim

The settings needs to be loaded before the token as they depends of it
fixes #5007

fix(@wallet): Correctly load token at boot

---

src/app/modules/main/chat_section/chat_content/users/module.nim
ui/imports/shared/status/StatusChatInput.qml

fix(@dekstop/chat): mentioning oneself display the full key instead of username

---

src/app/modules/main/chat_section/chat_content/messages/module.nim
src/app/modules/main/chat_section/chat_content/messages/view.nim
src/app/modules/shared_models/message_model.nim
ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
ui/imports/shared/views/chat/CompactMessageView.qml
ui/imports/shared/views/chat/MessageView.qml

There are multiple ways of fixing this, but the correct one is sending `dataChanged` signal with `ResponseToMessageWithId` role set for the items which have id of the edited message set for their `ResponseToMessageWithId` property. And I spent some time trying to make it work, but not sure if that's because of Nim or some hidden issue on the qml side an item doesn't receive update for that property. At the end I decided to sent a signal explicitly and connect to it on the qml side and do the necessary update. We should check this when we move that part to c++.
Fixes #4891

fix(@dekstop/chat): editing a message does not update the reply

---

ui/app/AppLayouts/Profile/views/ContactsView.qml

Fixes #3747
When dragging user list, the content will not overlay other items.
Settings / Contact list and Blocked contact list
https://user-images.githubusercontent.com/61889657/157877199-b7d954c7-3a22-44ee-a69b-5ce0fee42939.mov

fix(@desktop/profile): Clip user list when dragging

---

ui/app/AppLayouts/Onboarding/OnboardingLayout.qml
ui/app/AppLayouts/Onboarding/views/ConfirmPasswordView.qml
ui/app/AppLayouts/Onboarding/views/CreatePasswordView.qml
ui/app/AppLayouts/Onboarding/views/ExistingKeyView.qml
ui/app/AppLayouts/Onboarding/views/GenKeyView.qml
ui/app/AppLayouts/Profile/popups/ChangePasswordModal.qml
ui/app/AppLayouts/Profile/popups/StoreToKeychainSelectionModal.qml
ui/app/AppLayouts/Profile/views/PasswordView.qml

Closes #4785
It modifies the onboarding screen related to password creation by adding 2 different ones that fit the new design.
It modifies the change password modal view.
For doing that it has been created a shared `PasswordView.qml` component that incorporates the following logic:
- Type of characters introduced.
- Length of strength indicator bar depending on characters length (It will be reviewed / modified .
- Show/hide icons.
- Error messages / validation.
- Algorithm for password categorisation. It will be used `dropbox zxcvbn` tool agreed with **Security team** and will be addressed in a separate task. So now, the algorithm implemented is a basic one described here:  https://github.com/status-im/feature-specs/pull/38/files#r818531131
**NOTE:** This PR can be merged directly in …

feat(Desktop/Password): New password view design

---

src/app/modules/main/browser_section/provider/controller.nim
src/app/modules/main/browser_section/provider/controller_interface.nim
src/app/modules/main/browser_section/provider/module.nim
src/app/modules/main/browser_section/provider/view.nim
ui/app/AppLayouts/Browser/BrowserLayout.qml
ui/app/AppLayouts/Browser/popups/BrowserWalletMenu.qml
ui/app/AppLayouts/Browser/stores/RootStore.qml
ui/app/AppLayouts/Browser/stores/Web3ProviderStore.qml
ui/app/AppLayouts/Browser/views/WebProviderObj.qml

fixes #4053
This removes the account after disconnect is clicked.
1. On switching a a url check if wallet was connected/disconnected and update the button in the header
2. on disconnect reload url and revoke permission
Browser
https://user-images.githubusercontent.com/60327365/158219583-95d2de48-572f-4e9b-906e-9c32f587781a.mov

fix(@desktop/wallet): Disconnect button doesnt disconnect Wallet from Browser

---

ui/app/AppLayouts/Browser/popups/BrowserWalletMenu.qml
ui/app/AppLayouts/Browser/stores/RootStore.qml
ui/app/AppLayouts/Wallet/panels/WalletHeader.qml
ui/app/AppLayouts/Wallet/popups/ReceiveModal.qml
ui/app/AppLayouts/Wallet/stores/RootStore.qml
ui/imports/shared/controls/CopyToClipBoardButton.qml
ui/imports/shared/panels/TextWithLabel.qml
ui/imports/shared/status/StatusExpandableAddress.qml
ui/imports/shared/status/StatusSectionDescItem.qml

closes  #5039
Updated receive modal as per new design.
Whats not adapted:
1. The new floating buttons on top of the Modal
2. The white area at the bottom as its not clear if its the footer etc and it would be more consistent when the generic popup behaviour is defined
3. Note that the border around the QR code is not visible in Light mode as the background of the Modal is white just like the color of the rectangle. Can be seen clearly in dark mode. 
Wallet

feat(@desktop/wallet): adapt receive modal design

---

src/app/modules/main/profile_section/privacy/controller.nim
src/app/modules/main/profile_section/privacy/controller_interface.nim
src/app/modules/main/profile_section/privacy/io_interface.nim
src/app/modules/main/profile_section/privacy/module.nim
src/app/modules/main/profile_section/privacy/view.nim
src/app_service/service/privacy/service.nim
src/backend/privacy.nim
ui/app/AppLayouts/Profile/stores/PrivacyStore.qml

Together with [PR #2589](https://github.com/status-im/status-go/pull/2589) and  and [PR #8](https://github.com/status-im/nim-status-go/pull/8) it closes #4980
Added all necessary methods to call to a new `status-go` endpoint that allows to get the password strength quality info.
Added new method in `PrivacyStore` prepared to be used in the needed password views.
When it is integrated in the new onboarding screens the new functionality will allow to get information about the password strength when creating a new password in the onboarding process as well as in settings / change password modal.

feat(privacy): Added password strength calls

---

ui/app/AppLayouts/Chat/ChatLayout.qml
ui/app/AppLayouts/Chat/stores/RootStore.qml
ui/app/AppLayouts/Chat/views/ChatColumnView.qml
ui/app/AppLayouts/Chat/views/ChatContentView.qml
ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
ui/app/AppLayouts/Chat/views/CreateChatView.qml
ui/imports/shared/status/StatusChatInput.qml

While I was checking what's wrong with this Issue #5094, I noticed multiple things which we need to improve/update/fix. Going to list them now:
1. The same `CreateChatView` component is shared between "create chat" and "edit chat" functionalities even those two belong to different context and different use cases.
2. `StatusChatInput` component which is subcomponent of `ChatContentView` is used from the 2 levels up and borrowed to `CreateChatView` in case we're creating new chat, what is a big misuse and bring lot of confusion. 
3. Furthermore point 2. brings another issue where displayed `StatusChatInput` depends on selected chat, but not on selected contacts for `1:1` or `group chat` (request is if there is a single contact selected except sending message, image, gif, emoji or sticker we …

fix(@desktop/chat): cannot create a group chat by hitting `Confirm`

---

ui/app/AppLayouts/Onboarding/views/ConfirmPasswordView.qml
ui/app/AppLayouts/Onboarding/views/CreatePasswordView.qml

Closes #5065
fixes the create password view is white on dark mode
onboarding

fix(onboarding): create pwd view was white in dark mode

---

ui/imports/shared/status/StatusChatInputReplyArea.qml

Emojis are parsed in a message to transform from special emojis characters in qml image links. After this transformation, an XSS filter was applied that "fixes" all the image URLs introduced by the previous stage.
Reversing the order of these operations fixed the issue.
Chat message list

fix(chat): fix removal of emojis in reply preview

---

src/app/boot/app_controller.nim
src/app/modules/main/module.nim
src/app/modules/main/profile_section/module.nim
src/app/modules/main/profile_section/privacy/controller.nim
src/app/modules/main/profile_section/privacy/module.nim
src/app/modules/startup/module.nim
src/app/modules/startup/onboarding/controller.nim
src/app/modules/startup/onboarding/io_interface.nim
src/app/modules/startup/onboarding/module.nim
src/app/modules/startup/onboarding/view.nim
src/app_service/service/general/service.nim
src/app_service/service/privacy/service.nim
src/backend/general.nim
src/backend/privacy.nim
ui/app/AppLayouts/Onboarding/OnboardingLayout.qml
ui/app/AppLayouts/Onboarding/stores/OnboardingStore.qml
ui/app/AppLayouts/Onboarding/views/ConfirmPasswordView.qml
ui/app/AppLayouts/Onboarding/views/CreatePasswordView.qml
ui/app/AppLayouts/Profile/popups/ChangePasswordModal.qml
ui/app/AppLayouts/Profile/views/PasswordView.qml

Closes #5096
Used new `PrivacyStore` method `getPasswordStrengthScore` and link it to the new password strength bar value.
Used backend/general to call to `status-go` method and services/general to define the common `GetPasswordStrengthScore` service.
Added onboarding chain to get password strength score information from `OnboardingStore` to `status-go` call.
Fixed `darkmode` issue in onboarding screens.
Settings Privacy / Change Password
Onboarding / Create New Password
- **Settings Privacy / Change Password:**
https://user-images.githubusercontent.com/97019400/159479204-03fe3ce4-3879-4938-9588-9552d8d7e16d.mov
- **Onboarding screens:**
https://user-images.githubusercontent.com/97019400/159679659-10cbaaad-5228-4dd6-a0c7-361f142067f7.mov

feat(onboarding / privacy): Integrate password validation (zxcvbn lib) in new password screens

---

ui/app/AppLayouts/Chat/popups/community/CreateChannelPopup.qml
ui/app/AppLayouts/Chat/views/ChatContextMenuView.qml

Fixes #5045
StatusQ PR: https://github.com/status-im/StatusQ/pull/596
This also fixes the Edit channel where there were no emojis before. Now it assigns a random one that you can modify.
Also, it fixes the emoji save. It saved the whole `img`, now it only saves the UTF emoji

fix(emoji-icon): fix emoji icon position and saving on edit

---

Makefile
src/app_service/service/about/service.nim
src/constants.nim
src/nim_status_client.nim

Logs are named app_yyyyMMdd_HHmmss.log
Version, commit and start date information are displayed in logs at the begining.
Injecting commit version from Makefile.
Moving DESKTOP_VERSION const to constants.nim
Fix #3611
Desktop / log files

feature(desktop/internal): Improve log file naming convention

---

src/app/modules/main/activity_center/module.nim
src/app/modules/main/chat_section/chat_content/messages/controller.nim
src/app/modules/main/chat_section/chat_content/messages/module.nim
src/app/modules/main/chat_section/chat_content/module.nim
src/app/modules/main/chat_section/controller.nim
src/app/modules/main/chat_section/io_interface.nim
src/app/modules/main/chat_section/module.nim
src/app/modules/shared_models/message_item.nim
src/app/modules/shared_models/message_model.nim
src/app_service/service/message/dto/message.nim
src/app_service/service/message/service.nim

When the user is mentioned in edited message he is notified about it.
Technical details (discussed with @saledjenic):
Introduce new signal in message service: SIGNAL_MENTIONED_IN_EDITED_MESSAGE.
Keeping mentioned users public keys in message item/model.
When message is edited, message module sends request to message service to
check if the current user is mentioned and emit SIGNAL_MENTIONED_IN_EDITED_MESSAGE.
The new signal is caught in chat_section module and badges are updated.
Chat section.
https://user-images.githubusercontent.com/61889657/159040501-ba71548e-3bb9-47ea-a10d-dbe5b58b723f.mov

fix(desktop/chat): Notifies when the user is mentioned in edited message #4475

---

ui/app/AppLayouts/Profile/views/MyProfileView.qml
ui/imports/shared/controls/chat/ProfileHeader.qml
ui/imports/shared/popups/ProfilePopup.qml

Note that the PR is targeting and include changes in #5125 for clarity.
Further investigations are required to check if this can be achieved without a workaround or high effort.
Add "supersampling" option to the ProfileHeader. Enabling the option will draw the emojis at double the resolution and downsample them by scaling down the text control by half to compensate for the resolution increase
Profile preview
| Before         | After     |
|--------------|-----------|
| ![supersampling_off](https://user-images.githubusercontent.com/47554641/159808989-3e4d1ddb-2956-45b1-8850-3e1ac6aa7bfd.png) | ![supersampling_on](https://user-images.githubusercontent.com/47554641/159808986-edc3f653-0474-415d-adfc-edf073aa07e2.png)|
| ![14-supersampling-off](https://user-images.githubusercontent.com/47554641 …

wip idea(Profile): workaround to increase emoji sharpness in Profile

---

src/app/modules/main/browser_section/current_account/module.nim
src/app/modules/main/browser_section/current_account/view.nim
src/app/modules/main/browser_section/module.nim
src/app/modules/main/module.nim
src/app/modules/main/wallet_section/module.nim
src/app_service/service/wallet_account/service.nim
ui/app/AppLayouts/Browser/popups/BrowserWalletMenu.qml
ui/app/AppLayouts/Wallet/WalletLayout.qml
ui/app/AppLayouts/Wallet/views/LeftTabView.qml

User stays on removed account view in wallet after account removal from settings
fixes #5037
Switch account for wallet and browser when an account is deleted
Wallet, Browser
https://user-images.githubusercontent.com/60327365/159912379-4ab91883-7a2a-4948-8816-772b993ef94b.mov

fix(@desktop/wallet): User stays on removed account view in wallet after account removal from settings

---

ui/app/AppLayouts/Profile/views/MyProfileView.qml
ui/imports/shared/controls/chat/ProfileHeader.qml
ui/imports/shared/controls/chat/UserImage.qml
ui/imports/shared/popups/ProfilePopup.qml

@elina2015 I think that emojis rendering in are slightly better now.
As of profile image... I checked what's happening and I could do literally nothing cause by default identicons are generated in size of 50x50 pixels and in that "change profile picture" popup we display them in size of 160x160 pixels, and that's the reason of poor quality in that view. For comparison if you check the same identicon on the login screen you will see that it is displayed far better, but that's because we display it there in 40x40 pixels.
To check that, just open any identicon and download that image from your browser, for example open this in your browser:
`data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADIAAAAyCAYAAAAeP4ixAAAAjUlEQVR4nOzWwQmAMAxAURV30QEdwwF1Gr0Xi8mh8An/nUvhEwhZpiIMoTGExhAaQ2jKhKzRh+d9PZmPj22 …

fix(@desktop/general): the default profile picture and profile emojis are blurred on the Profile page

---

ui/app/AppLayouts/Chat/popups/GroupInfoPopup.qml

Closes: #5203
Fix remove functionality for Groups
GroupInfoPopup

fix(Groups): Add empty community id for functions call and change `model.pubKey` to `model.id`

---

src/app_service/service/stickers/dto/stickers.nim

fixes #5195
The attribute Status is marked as omit empty in backend

fix(@chat): handle status being nil in stickers

---

ui/app/AppLayouts/Chat/views/ChatColumnView.qml
ui/app/AppLayouts/Wallet/panels/WalletFooter.qml
ui/app/AppLayouts/stores/RootStore.qml
ui/app/mainui/AppMain.qml
ui/imports/shared/controls/AmountInputWithCursor.qml
ui/imports/shared/controls/ContactsListAndSearch.qml
ui/imports/shared/controls/GasSelector.qml
ui/imports/shared/popups/SendModal.qml
ui/imports/shared/views/SendModalFooter.qml
ui/imports/shared/views/SendModalHeader.qml
ui/imports/shared/views/TabAddressSelectorView.qml
ui/imports/shared/views/TabNetworkAndFees.qml
ui/imports/utils/Utils.qml

StatusQ PR :https://github.com/status-im/StatusQ/pull/595
fixes https://github.com/status-im/status-desktop/issues/5040
This PR aims at adapting the SendModal to the new design  https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=3014%3A175789
However many things are not exactly as the design for example -
1. Modal look
2. Floating buttons behaviour for account selection
3. The saved address look and feel in design are not supported yet and need to check if this support should be added in StatusQ
4. The recent addresses list look and feel not exactly like design
5. There is a new asset selector design and if its final needs to adapted in StatusQ first
6. The Simple/Advanced/Custom parts are not implemented yet
7. Suggested fees functionality needs to be implemented before …

feat(@desktop/wallet): Adapt to new SendModal Design

---

ui/app/mainui/AppSearch.qml

The search text is displayed correctly. It is not cut anymore.
Also the loading icon is hidden if the user clears the search text.
Chat / Search

5197 search box input is cut in half

---

ui/app/AppLayouts/Chat/popups/community/CommunitiesPopup.qml

Fix #5200
Fixes wrong text alignment in communities search box.
Chat / Search communities
https://user-images.githubusercontent.com/61889657/160447570-d1be033a-d210-4304-b952-bf737c2c74da.mov

fix(desktop/chat): Using default height and padding for community search box

---

ui/imports/shared/controls/Input.qml

Closes: #5188
Because of rendering issue spaces between `,` and next character was too small. I change base component for validation string to `StatusBaseText` which fixed it by standard font family usage.
Input.qml

fix(Input): Change `TextEdit` to `StatusBaseText` in `Input.qml`

---

Makefile
src/nim_status_client.nim

Log level can be chosen during application startup.
Logs are disabled for production build.
Fix #3609
Logs are disabled for production builds - no log file, no logging.
Logs are configurable during development. Need to pass LOG_LEVEL parameter,
eg. make run LOG_LEVEL=ERROR.
Possible levels are taken from Nim chronicles:
TRACE, DEBUG, INFO, NOTICE, WARN, ERROR, FATAL, and NONE.
Desktop / logs
Log only errors:

feature(desktop/general): Configurable logs

---

ui/app/AppLayouts/Profile/views/DisplayNamePopup.qml
ui/app/AppLayouts/Profile/views/MyProfileView.qml

Closes #5110 and #5193.
It has been used a `StatusInput` component from `StatusQ`.
`placeholderText`property updated to "Display Name" and button / content layout redefined to be shown correctly.
It incorporates the same validation rules as in the current onboarding process:
- Min and max length validation.
- Regular expression.
- Ends with '.eth' or '_eth' or '-eth'.
- Alias validation.
Settings / Profile / Edit
https://user-images.githubusercontent.com/97019400/160372018-02c023a9-f323-4eaa-addc-e9620a219a8e.mov

fix(Settings/Profile/Edit): The form for editing Display name looks incorrect

---

ui/app/AppLayouts/Profile/panels/TokenSettingsModalContent.qml
ui/app/AppLayouts/Profile/views/ContactsView.qml
ui/imports/shared/controls/SearchBox.qml
ui/imports/shared/status/StatusGifPopup.qml

Fixes #5090
Adds a clear button to the Contact Settings search bar, and all other search bars (emoji, gif, Wallet setting, etc)

feat(SearchBox): use StatusInput for SearchBox and add clear button

---

ui/app/AppLayouts/Chat/views/ContactsColumnView.qml

Closes #5146
Closes #5137 
icon buttons for join public chat and create new chat were remaining highlighted even though unselected.
create / join chat icon buttons

fix(create/join chat): icon buttons were highlighted always

---

src/app/global/utils.nim
ui/app/AppLayouts/Chat/stores/RootStore.qml
ui/imports/shared/views/chat/MessageContextMenuView.qml

The issue was caused because the data being passed to the UI is now a URL and not image data.
Added support to download/copy image by URL
NIMQML: https://github.com/status-im/nimqml/pull/40
DOtherside: https://github.com/status-im/dotherside/pull/62
fixes #5194
Adds support to download/copy image by url
chat
https://user-images.githubusercontent.com/60327365/160496743-880688c0-f8b2-4208-9610-ee5ca848f968.mov

fix(@desktop/chat): Downloading/Copying an image from chat crashes the app

---

src/app/modules/main/chat_section/chat_content/users/controller.nim
src/app/modules/main/chat_section/chat_content/users/io_interface.nim
src/app/modules/main/chat_section/chat_content/users/module.nim

Fixes #5202
You had to restart the app to see newly joined users in a group chat. Now they are added when they join.
**Note**: This also changes the behaviour of the user list. Only `joined` users (of a group or a community) will show in the list.
First, it fixes the weird behaviour of group chats where on creating them, the list would be empty, but on restarting, every user would be there, even if they didn't join.
Second, it also makes sense, because the user isn't actually in the group chat or community, so seeing them in the list is misleading.
I tested public chats as well, and it didn't affect them.

fix(users): user not added when joining group + only show joined users

---

src/app/modules/main/chat_section/chat_content/controller.nim
src/app/modules/main/chat_section/chat_content/module.nim
src/app/modules/main/chat_section/controller.nim
src/app/modules/main/chat_section/module.nim
src/app/modules/main/controller.nim
src/app/modules/main/module.nim
src/app/modules/main/profile_section/contacts/controller.nim
src/app/modules/main/profile_section/contacts/io_interface.nim
src/app/modules/main/profile_section/contacts/module.nim
src/app/modules/main/profile_section/contacts/view.nim
src/app/modules/shared_models/contacts_item.nim
src/app/modules/shared_models/contacts_model.nim
src/app_service/service/chat/service.nim
src/app_service/service/contacts/dto/contacts.nim
src/app_service/service/contacts/service.nim
src/app_service/service/message/service.nim
ui/app/AppLayouts/Chat/stores/RootStore.qml
ui/app/AppLayouts/Profile/panels/ContactPanel.qml
ui/app/AppLayouts/Profile/panels/ContactsListPanel.qml
ui/app/AppLayouts/Profile/stores/ContactsStore.qml
ui/app/AppLayouts/Profile/views/ContactsView.qml
ui/imports/shared/controls/StatusTabButton.qml
ui/imports/shared/views/chat/MessageContextMenuView.qml
ui/imports/utils/Constants.qml

In [this video](https://drive.google.com/file/d/1vPup0U377AKIQr4q6x-CTFtCpcC3XkHh/view?usp=sharing) you may see that `settings->messaging->contacts` section roughly match requested design. Once we have details set up on the `status-go` side we will just updated them in `contact service`, so far I dealt with contact's properties which we currently have on disposal to simulate what we will have at the end (I mean to procs attached to `ContactsDto`).
@richard-ramos you may be interested in this PR since @iurimatias said that you're working on adding new props for contacts on the `status-go` side.
The first commit solves point 3 form the description of the ticket.
The second commit solves points 1, 2 and 4.
Fixes #5117

Contact lists should only shown mutual contacts

---

ui/app/AppLayouts/Chat/views/CreateChatView.qml

Closes #5199
Closes #5258 
Depends on: https://github.com/status-im/StatusQ/pull/606
Fixed the contacts list was not visible in start chat contact list
start a new chat

fix(statustagselector): contacts list was not visible

---

src/app/global/utils.nim
src/app_service/service/accounts/service.nim
src/backend/accounts.nim
ui/app/AppLayouts/Chat/panels/communities/CommunityMembersSettingsPanel.qml
ui/app/AppLayouts/Onboarding/views/InsertDetailsView.qml
ui/app/AppLayouts/Profile/views/MyProfileView.qml
ui/imports/shared/controls/chat/ProfileHeader.qml
ui/imports/shared/popups/ProfilePopup.qml
ui/imports/utils/Utils.qml

closes: https://github.com/status-im/status-desktop/issues/5181
Share Profile URL was not adapted -> `https://join.status.im/u/0x04ccb45ffb964e4e0b856c88f30002c85bd68ce0c98842811e3f37cbdf32dc542ea7f876d6e64089f4e3d1f779aa1f9d510c34753091327a16632f058d45866162`
"when we display the fragment in the chat view e.g. next to a user's name in small text (above the message the user has typed), we should not grey the first 3 characters there.  But wherever a chat key fragment is displayed in the UI, from this point onwards it should always be  the first 6 characters then the last 3 characters e.g. zQ3k83...t5N" @John-44

show compressed multiformat public keys

---

ui/app/AppLayouts/Onboarding/views/InsertDetailsView.qml
ui/app/AppLayouts/Profile/views/DisplayNamePopup.qml
ui/imports/utils/Constants.qml

- validators included for the display name field in the onboarding process
- in display name popup "Ok" button disabled by default
Fixes #5236

fix(@desktop/onboarding): users can save an empty "Display Name" in new onboarding

---

ui/app/AppLayouts/Chat/views/CreateChatView.qml
ui/imports/shared/status/StatusChatInput.qml
ui/imports/shared/status/StatusGifColumn.qml

The issue was happening because adding gif to the recently used gifs model
was initiated after `gifSelected` action was fired and that action actually removed
the context within `addToRecentsGif` ought to be called and the app crashed.
That's fixed now updating the order of those two calls.
Fixes #5263

fix(@desktop/chat): the app is crashed after sending gif to a group chat

---

src/app_service/service/provider/async_tasks.nim
ui/app/AppLayouts/Browser/views/WebProviderObj.qml
ui/imports/utils/Utils.qml

Removes the logic to convert a password into a hashPassword which was causing the issue
Browser
https://user-images.githubusercontent.com/60327365/161793990-f0c9e73e-69c9-4b70-9e98-33ddfbb25a83.mov

fix(@desktop/browser): Unable to sign message from simepledapp.eth

---

ui/app/AppLayouts/Chat/popups/community/InviteFriendsToCommunityPopup.qml

Closes: #5343
Remove sending invites to members when they selected by user in list
Invite friends to community popup

fix(@desktop/communities): Remove sending invites when user select members for inviting to community

---

ui/imports/shared/controls/SearchBox.qml

Fix #5381
Removed implicitHeight which was too small and overrode original implicitHeight.
The height was too small to display text correctly.
Places where SearchBox is used:
- Edit channel / search emoji
- Chat / search gif
- Settings / Wallet / Manage Assets

fix(@desktop/chat): Improve SearchBox default height to display text correctly

---

ui/app/AppLayouts/Chat/popups/community/CreateCategoryPopup.qml

Closes: #5350
Fix emoji displaying into category popup
Create category popup

fix(@desktop/categories): Fix display emoji into create category popup

---

ui/app/AppLayouts/Onboarding/views/SeedPhraseInputView.qml

Closes #5388
The submit / restore status profile was staying enabled even when switching between seed word count tabs
Onboarding/StatusSeedPhraseInput

fix(SeedPhraseInputView): Submit button should disable when switching tabs

---

ui/app/AppLayouts/Chat/views/CreateChatView.qml

Depends on: https://github.com/status-im/StatusQ/pull/633
Closes #5294
fixed big text goes outside text edit
create new chat

fix(CreateChatView): fixed big text goes outside text edit

---

ui/app/AppLayouts/Wallet/views/AdvancedAddAccountView.qml

fix #5406
Makes the limit for chars to be entered when importing a private key to 66 from 64. Allowing users to import private key with and without 0x prefix
wallet

fix(@desktop/wallet): Allow entering private keys with and without 0x prefix

---

ui/imports/shared/views/SendModalHeader.qml

fixes #5447
Sets the correct height for the to field
Wallet

fix(@desktop/wallet): To field is not showing address in wallet

---

ui/imports/shared/status/StatusStickersPopup.qml

Fixes #5458
- It has been changed footer layout from Item to row.
- The colour of the Add button has been changed to match the rest of the style.
- The recent tab control has been changed to be consistent with other popups like gifts or emojis and the used component directly controls the different themes.
Chat / Stickers 
https://user-images.githubusercontent.com/97019400/162785386-bf9900bc-aa9d-46ce-9992-cddee85c6d44.mov

fix(Chat/Stickers): Recent stickers icon is missing

---

ui/imports/shared/views/TabAddressSelectorView.qml

fixes #5472
Adjusts space of the address selection based on the height of the child
Wallet
https://user-images.githubusercontent.com/60327365/162810974-fcec61f9-df16-409c-a177-bd0e67c18800.mov

fix(@desktop/wallet): Send modal has a big space when created addresses section is empty

---

ui/app/AppLayouts/Onboarding/views/InsertDetailsView.qml

Closes #5235
Fixed display name clear button was always visible
Onboarding
https://user-images.githubusercontent.com/31625338/162291708-2b7f2435-0457-4bf2-aa82-f9533608de99.mov

fix(Onboarding): display name clear button was always visible

---

ui/app/AppLayouts/Chat/popups/community/CreateChannelPopup.qml
ui/app/AppLayouts/Wallet/popups/AddAccountModal.qml

Fixes #5161
Also, changes the chat one to use `deparse` instead. It's basically the same thing, just in the Emoji file.
For testers, just see that saving the emoji for chats and wallets works as before. In the backend, it saves in a simpler format.

fix(wallet-emoji): fix wallet emoji save by only saving the utf char

---

ui/app/AppLayouts/Onboarding/popups/UploadProfilePicModal.qml
ui/app/AppLayouts/Onboarding/views/InsertDetailsView.qml
ui/imports/shared/popups/ModalPopup.qml

Apply avatar icon only if the user accepts it.
Fix #5238
Fixes setting avatar image icon process - if the user quit the image popup, or cropping popup,
the icon will not be applied.
Profile / onboarding 
https://user-images.githubusercontent.com/61889657/161555042-ea0461b9-fe66-4266-a102-2c2adf22a089.mov

fix(desktop/profile): Does not apply avatar icon if quitted popup

---

ui/app/AppLayouts/Chat/panels/ActivityCenterPopupTopBarPanel.qml

Fixes #5469
Chat / Activity Center / More actions popup
https://user-images.githubusercontent.com/97019400/162917340-251cbf0c-56b6-4a1b-a47c-a5cd4c34c63b.mov

fix(Chat/ActivityCenter): Activity center context menu keeps moving position

---

src/app/modules/shared_models/active_section.nim
src/app_service/service/community/service.nim

Also remove unnecessary signals
Those changes were supposed to go into a PR that was already merged.

chore: add safeguards when checking for community data in response

---

ui/app/AppLayouts/Wallet/popups/AddEditSavedAddressPopup.qml
ui/imports/shared/controls/AddressInput.qml
ui/imports/shared/controls/ContactsListAndSearch.qml
ui/imports/shared/controls/RecipientSelector.qml
ui/imports/utils/Utils.qml

fixes #5534
Public key should not be allowed as a input when saving addresses. 
Placeholder text updated with correct message.
Updated to show correct error message in case anything else except for a wallet address or a ENS Name is entered.
Wallet
https://user-images.githubusercontent.com/60327365/163158292-84fabc71-ce09-40d6-b5e4-6cf81d5b2c9d.mov

fix(@desktop/wallet): Can't add an address to saved addresses

---

src/app/modules/startup/onboarding/controller.nim
src/app/modules/startup/onboarding/io_interface.nim
src/app/modules/startup/onboarding/module.nim
src/app/modules/startup/onboarding/view.nim
src/app_service/service/general/service.nim
src/backend/general.nim
ui/app/AppLayouts/Onboarding/popups/UploadProfilePicModal.qml
ui/app/AppLayouts/Onboarding/stores/OnboardingStore.qml
ui/app/AppLayouts/Onboarding/views/InsertDetailsView.qml

The issue occurred cause image was not cropped properly, but used the original one. 
While I was working on this issue I noticed that we're using calls from some modules, like main module, profile module... that are available only after user logs in successfully, and that display some errors/warning in the log.
Corresponding `status-go` PR: 
- https://github.com/status-im/status-go/pull/2627
Corresponding `nim-status-go` PR: 
- https://github.com/status-im/nim-status-go/pull/12
Fixes #5241

fix(@desktop/onboarding): the profile image doesn't look good on the onboarding page

---

ci/Jenkinsfile.linux
ci/Jenkinsfile.macos
ci/Jenkinsfile.windows

Upgrade of Jenkins to `2.343` has introduced a security fix that breaks caching plugin when it's configured to store cache on Master host: https://issues.jenkins.io/browse/JENKINS-67173
Sine the [Caching plugin](https://plugins.jenkins.io/jobcacher/) hasn't been upgraded in 5 years the only good temporary workaround is just drop caching of dependencies like Nim compiler entirely.
In the future we can try some other caching methods.
Related: https://github.com/status-im/nimbus-eth2/pull/3594

ci: remove caching of dependencies

---

ui/imports/shared/status/StatusGifPopup.qml

Removes extra clear button in the StatusGifPopup because similar button is already existing in the SearchBox
Chat

fix(Chat): Remove extra button to clear text in gif search

---

ui/app/AppLayouts/Onboarding/panels/AccountMenuItemPanel.qml
ui/app/AppLayouts/Onboarding/views/LoginView.qml

This includes changing the account selector from being a modal to
a drop down menu, which also includes an option to generate a new
account.
In addition, it adds the status logo plus a dedicated headline.
Closes: #5623 #5624

ui: revamp login view to match latest designs

---

ui/app/AppLayouts/Chat/views/ChatContentView.qml

There was a bug that no handler was attached to the `onShowReply()`
signal, which is necessary to hydrate the chat input with reply data.
Fixes #5497

fix(ChatContentView): make replying to messages work again

---

ui/app/AppLayouts/Profile/ProfileLayout.qml
ui/app/AppLayouts/Profile/controls/WalletNetworkDelegate.qml
ui/app/AppLayouts/Profile/panels/ContactsListPanel.qml
ui/app/AppLayouts/Profile/stores/ProfileSectionStore.qml
ui/app/AppLayouts/Profile/views/AboutView.qml
ui/app/AppLayouts/Profile/views/AdvancedView.qml
ui/app/AppLayouts/Profile/views/AppearanceView.qml
ui/app/AppLayouts/Profile/views/BrowserView.qml
ui/app/AppLayouts/Profile/views/ContactsView.qml
ui/app/AppLayouts/Profile/views/DevicesView.qml
ui/app/AppLayouts/Profile/views/HelpView.qml
ui/app/AppLayouts/Profile/views/LanguageView.qml
ui/app/AppLayouts/Profile/views/MessagingView.qml
ui/app/AppLayouts/Profile/views/MyProfileView.qml
ui/app/AppLayouts/Profile/views/NotificationsView.qml
ui/app/AppLayouts/Profile/views/PrivacyView.qml
ui/app/AppLayouts/Profile/views/SettingsContentBase.qml
ui/app/AppLayouts/Profile/views/SoundsView.qml
ui/app/AppLayouts/Profile/views/WalletView.qml
ui/app/AppLayouts/Profile/views/wallet/AccountView.qml
ui/app/AppLayouts/Profile/views/wallet/DappPermissionsView.qml
ui/app/AppLayouts/Profile/views/wallet/MainView.qml
ui/app/AppLayouts/Profile/views/wallet/NetworksView.qml
ui/app/AppLayouts/Profile/views/wallet/PermissionsListView.qml
ui/imports/utils/Constants.qml

The most important thing added here is `SettingsContentBase` component. It defines high level structure for all subsections in the settings section (all of them should inherit it). Having that whenever we need to change something global for settings section like update margins, title font, color, back button... we will do it from a single place with a single change and affect all subsections. Also `getNameForSubsection` function is added to `ProfileSectionStore` so updating subsection name in a single place will be visible to all corresponding places. Section names are fixed now and only scrollable part is subsection content. 
`EnsView` is not affected by these changes, since it has completely different structure and that should be handled via separate ticket.
Changes done here refers …

fix(@desktop/settings): content on the right side for all subsections need to have the same geometry

---

ui/app/AppLayouts/Onboarding/views/ConfirmPasswordView.qml

Fixes #5611
Since this screen is just a confirmation one, it has been agreed with designer that it should not display any error message and the only way of enabling the finalize button is if it is exactly the same password than created in the previous screen.
So:
- Removed code related to validation.
- Modified enable button condition (just only when password is exactly the same than the previous introduced one).
https://user-images.githubusercontent.com/97019400/167431011-1bb0b75f-c61e-43cb-b780-8ceaca733652.mov

fix(Onboarding/ConfirmationPassword): Remove validation error and enable button only when pw is the expected

---

ui/app/AppLayouts/Profile/views/ContactsView.qml

Fixes #5288
Added more top margin in tab component.
Messaging/Contacts

fix(Messaging/Contacts): The titles of folders in Settings-Messaging are shown very close to the search field

---

.gitignore
ui/app/AppLayouts/Onboarding/popups/UploadProfilePicModal.qml
ui/imports/shared/panels/EditCroppedImagePanel.qml
ui/imports/shared/panels/NoImageUploadedPanel.qml
ui/imports/shared/panels/qmldir

Depends on https://github.com/status-im/StatusQ/pull/615
Based on:
- [Profile picture designs](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=1197%3A314660)
- [Community logo new design](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=4662%3A406927)
Onboarding, profile image

feature(Onboarding/Profile Image): use image cropper to set the initial profile picture

---

src/app_service/service/community/service.nim

overwritten
When communities are edited, status-go sends a signal with the community
description, to ensure the network is updated to the latest changes.
However, that community description doesn't include `communitySettings`.
When we then compose the `CommunityDto` object from that signal, it will have
a default certain settings to `false` which might actually be `true`.
The result is that data in memory is incorrect.
To ensure we don't run into this issue, we check whether the attached
settings have an id, if they don't, we know the settings do not
originate from the signal data, meaning we can use the settings we
already have.

fix(CommunityService): ensure communitySettings aren't mistakenly

---

ui/app/AppLayouts/Profile/popups/SendContactRequestModal.qml

This causes a runtime error and prevents the app from bootstrapping.

fix(SendContactRequestModal): fix typo in input property

---

ui/app/AppLayouts/Chat/views/CreateChatView.qml

Closes #5643
Increased name tag limit from 5 to 20 in create new 1-1/group chat tag selector
Create new chat
Depends on: https://github.com/status-im/StatusQ/pull/653

fix(CreateNewChat): Increased name tag limit to 20

---

ui/app/AppLayouts/Chat/views/ContactsColumnView.qml

Closes #5627
Fixed channel stays highlighted when create chat view is opened
chat
https://user-images.githubusercontent.com/31625338/166701494-5a7ebbc2-22c4-4632-9f1a-7d0ef7a7ac0f.mov

fix(Chat): Deactivate channel when create chat is opened

---

src/app/modules/main/chat_section/chat_content/users/controller.nim
src/app/modules/main/chat_section/chat_content/users/io_interface.nim
src/app/modules/main/chat_section/chat_content/users/module.nim
src/app/modules/main/chat_section/module.nim
src/app_service/service/chat/dto/chat.nim

Fixes #5462
The problem was that the event to update the nickname in the mentions was blocked by the `isUsersListAvailable` condition. What I did is I rearranged the events behind better conditions. 
The user status (online, offline, etc) and member adds and  removed are only needed when `isUsersListAvailable`.
The events about messages are only needed for public chats, because they use the messages to build the member list.
Finally, the events about contact changed, nickname changed and image changed are needed for every type of chat. That's how the 1-1 bug is fixed.
Finally, I made it so that `isUsersListAvailable` is set to `false` for public chats as well, since we no longer show it in public chats.

Fix 1-1 mentions not updating nickname + rearrange events

---

src/app/modules/main/controller.nim
src/app/modules/main/io_interface.nim
src/app/modules/main/module.nim
src/app_service/service/community/service.nim

Fixes #5454
So this was a bug/feature. We never knew that if you are admin of a community, lose your data, re-import and then receive a new signal for that community, it would come back. It,s pretty cool.
However, if you have the community flag off in Advanced settings, it would appear randomly and remove the setting cog button.
Now we make sure the Communities are enabled before showing it.

fix(community): community would appear even if not activated

---

src/app/modules/main/app_search/controller.nim
src/app/modules/main/app_search/module.nim
src/app/modules/main/app_search/result_item.nim
src/app/modules/main/chat_section/controller.nim
src/app/modules/main/chat_section/io_interface.nim
src/app/modules/main/chat_section/module.nim
src/app/modules/main/controller.nim
src/app/modules/main/module.nim
src/app_service/service/chat/service.nim

Fixes #5183
This removes the need for `buildCommunityUI` and consolidates chat section and community.
This is based on the getChats PR.
For QAs that want to test it, it's the same as the other, just make sure the Chat and Communities work as before.

refactor(chats): pass chat group to chat section to simplify UI build

---

ui/app/AppLayouts/Chat/controls/UserDelegate.qml

Closes #5637
Corrected click behavior in members list
- Left click should launch profile popup
- Right click should open context menu
Chat Members list
https://user-images.githubusercontent.com/31625338/167629458-6a26a61d-4bec-4b78-aca0-b73a9b506611.mov

fix(Chat): Corrected click behavior in members list

---

src/app/modules/main/wallet_section/accounts/derived_address_item.nim
src/app/modules/main/wallet_section/accounts/derived_address_model.nim
src/app/modules/main/wallet_section/accounts/view.nim
src/app_service/service/wallet_account/derived_address.nim
ui/app/AppLayouts/Wallet/panels/DerivedAddressesPanel.qml
ui/app/AppLayouts/Wallet/stores/RootStore.qml

feat(@desktop/wallet): greying out already imported/derived addresses  in address list and also choosing next available as default one
fixes #5539
Greys out derived addresses that have already been used by user and selects the next available one by default
Wallet
https://user-images.githubusercontent.com/60327365/163185930-d92fa7e8-f9c0-401b-b1df-84072bd8265f.mov

feat(@desktop/wallet): greying out already imported/derived addresses  in address list and also choosing next available as default one

---

ui/imports/shared/controls/EmojiHash.qml
ui/imports/shared/status/StatusEmojiPopup.qml
ui/imports/shared/status/StatusEmojiSection.qml
ui/imports/shared/views/chat/ChatTextView.qml
ui/imports/utils/Style.qml

Corresponding StatusQ PR:
- https://github.com/status-im/StatusQ/pull/673
Fixes #5259.
Emojis are loaded as SVG everywhere except `ChatMessage` (it used PNG because Qt `TextEdit` doesn't render SVG in good quality)
Chat

fix(@chat): Fixed blurry emojis

---

ui/imports/shared/views/PasswordView.qml

Close #5702
Update text from 6 to 10 chars
Set minimal non-zero value for progress bar
Onboarding

fix(@desktop/onboarding): Password strength indicator fixes for 10-chars

---

ui/app/AppLayouts/Browser/views/WebProviderObj.qml

fix(@desktop/browser): Can't sign in to Cryptokitties (sing a message to dapp)
fixes #5013
Adds the from field so that the signature is authorized
browser

fix(@desktop/browser): Can't sign in to Cryptokitties (sing a message to dapp)

---

ui/app/AppLayouts/Chat/views/ChatContentView.qml

fix(@desktop/activityCenter): Activity Centre's Activity tool tip is slightly off
fixes #5508
Fixes the tooltip offset when its a one on one chat and no member list is available 
activity centre
https://user-images.githubusercontent.com/60327365/168576381-8968af9c-1a3b-4f4a-8e7e-d68e2a341402.mov

fix(@desktop/activityCenter): Activity Centre's Activity tool tip is slightly off

---

src/app/modules/main/chat_section/chat_content/module.nim
src/app/modules/main/chat_section/chat_content/view.nim
src/app/modules/main/chat_section/model.nim
src/app/modules/main/chat_section/module.nim

The issue is that, after an account accepts a contact request, the
sender of the request receives a message signal where the
chat's name in the response is the first 8 characters of the chat's
public key. This is because status-go doesn't actually try to keep
the chat's `name` up-to-date if it's a one on one chat.
This results in chat details being updated with a name that is
incorrect. This commit ensures we only update the name of the chat
details if we indeed don't deal with a 1-on-1 chat.
Fixes https://github.com/status-im/status-desktop/issues/5738

fix(Chat): don't override chatdetails name with pubkey substr

---

src/app_service/service/chat/dto/chat.nim

Fixes #5729
Community chat creation / edition / importing a community / rejoining a community
https://user-images.githubusercontent.com/1106587/168635149-3feb2a1d-bf76-41e4-91a1-f28e6b084b79.mp4

fix: duplicated channels when joining a community

---

ui/app/AppLayouts/Profile/views/ContactsView.qml

Fixes #5731
Removed "Contacts" title in ContactsView.qml.
Settings / Messaging / Contacts

fix(Settings/Messaging/Contacts): Contacts label shows up twice

---

ui/app/AppLayouts/Onboarding/views/InsertDetailsView.qml

Fixes #5761
Removed capitalization: User can insert a display name starting with lowercase char.
Onboarding / InsertDetailsView.qml
https://user-images.githubusercontent.com/97019400/168759931-0a20120b-6d9a-40ce-ae43-82324f6731bf.mov

fix(Onboarding/DisplayName): User is forced to use display name with first case uppercase

---

src/backend/accounts.nim
ui/app/AppLayouts/Wallet/panels/DerivedAddressesPanel.qml

feat(@desktop/wallet): Add has activity to the derived addresses in wallet
fix #5655
status_go PR : https://github.com/status-im/status-go/pull/2663
show has activity no activity on the derived addresses when adding a new account
Wallet
https://user-images.githubusercontent.com/60327365/166953420-9b21d7ad-a135-4539-91cc-12f63a8dcabc.mov

feat(@desktop/wallet): Add has activity to the derived addresses in wallet

---

src/app/modules/main/activity_center/controller.nim
src/app/modules/main/activity_center/item.nim
src/app/modules/main/activity_center/model.nim
src/app/modules/main/activity_center/module.nim
ui/app/AppLayouts/Chat/controls/activityCenter/ReplyComponent.qml
ui/app/AppLayouts/Chat/panels/ActivityChannelBadgePanel.qml
ui/app/AppLayouts/Chat/views/ActivityCenterMessageComponentView.qml

Fix #5523
Shows badge with message text for reply elements.
Chat / Activity center

fix(@desktop/chat): Show badge and message in activity center for reply elements

---

ui/app/AppLayouts/Chat/views/CreateChatView.qml

Closes #5625
Depends on: https://github.com/status-im/StatusQ/pull/676
Fixes members list should show online status in create new DM/group chat
create new DM/group chat view

fix(CreateChatView): Members should show online status

---

ui/app/AppLayouts/Chat/views/CommunityColumnView.qml
ui/app/AppLayouts/Chat/views/ContactsColumnView.qml

Closes #5211
Depends on: https://github.com/status-im/StatusQ/pull/680
fixed alignment of chats list in left column
chats list

fix(chatlistcolumn): fixed alignment in chats list

---

ui/imports/shared/views/chat/MessageContextMenuView.qml
ui/imports/shared/views/chat/MessageView.qml

Closes #5766
Hides "edit" option from message context menu when message is sticker
Message context menu
https://user-images.githubusercontent.com/31625338/168820728-7b4f5be6-e5e9-4bbd-bf6c-c6048234a7de.mov

fix(ChatMessage): hide "edit" option when right click on sticker

---

src/app/modules/main/chat_section/chat_content/messages/io_interface.nim
src/app/modules/main/chat_section/chat_content/messages/module.nim
src/app/modules/main/chat_section/chat_content/messages/view.nim
src/app/modules/main/chat_section/controller.nim
src/app/modules/main/chat_section/io_interface.nim
src/app/modules/main/chat_section/module.nim
src/app/modules/main/chat_section/view.nim
src/app/modules/main/communities/controller.nim
src/app/modules/main/communities/io_interface.nim
src/app/modules/main/communities/module.nim
src/app/modules/main/communities/view.nim
src/app/modules/main/module.nim
src/app/modules/shared_models/active_section.nim
src/app/modules/shared_models/section_item.nim
src/app/modules/shared_models/section_model.nim
src/app_service/service/chat/dto/chat.nim
src/app_service/service/community/dto/community.nim
src/app_service/service/community/service.nim
src/backend/communities.nim
ui/app/AppLayouts/Chat/popups/community/CreateCommunityPopup.qml
ui/app/AppLayouts/Chat/stores/MessageStore.qml
ui/app/AppLayouts/Chat/stores/RootStore.qml
ui/imports/shared/views/chat/CompactMessageView.qml
ui/imports/shared/views/chat/MessageContextMenuView.qml
ui/imports/shared/views/chat/MessageView.qml

This adds a checkbox to configure whether or not community members are
allowed to pin any message of a community channel, based on the newly
introduced `CommunityAdminSettings` that are introduced in https://github.com/status-im/status-go/pull/2668
Closes #5662

feat(CommunitySettings): add checkbox to allow members to pin messages

---

src/app/core/signals/remote_signals/mailserver.nim
src/app/core/signals/remote_signals/signal_type.nim
src/app/modules/main/controller.nim
src/app/modules/main/io_interface.nim
src/app/modules/main/module.nim
src/app/modules/main/view.nim
src/app_service/service/mailservers/service.nim
src/backend/signals.nim
ui/app/mainui/AppMain.qml

This makes Status Desktop aware of the `mailserver.not.working` signal.
When emitted by status-go, desktop will show a popup that informs the
user about the connection failure.
Furthermore, users can then decide to either retry (same as just closing
the popup as retrying already happens by default), or pick another
pinned mailserver, for which they'll get redirected to the messaging
settings panel.
Closes #5166

feat: handling `mailserver.not.working` signal

---

ui/imports/shared/status/StatusImageModal.qml

Closes: #5251
Change `Image` to `AnimatedImage` in StatusImageModal
StatusImageModal.qml
https://user-images.githubusercontent.com/82511785/168687738-ea0d85ae-be42-424f-8845-16c261c78ec9.mov

fix(gifs): Change `Image` to `AnimatedImage` in StatusImageModal

---

src/app_service/service/message/service.nim

Fix #5858
Incoming messages and edited messages are shown correctly in 1:1 chat.
Previously, they showed up only after restarting the application.
1:1 chat

fix(@desktop/chat): Fix 1:1 chat

---

ui/app/AppLayouts/Profile/views/wallet/MainView.qml

Temporary commented, we need to bring it back after MVP.
Fixes #5856

fix(@desktop/settings): remove the `Manage Assets & Lists` functionality from `Settings/Wallet`

---

ui/app/AppLayouts/Onboarding/views/SeedPhraseInputView.qml
ui/app/AppLayouts/Wallet/panels/ImportSeedPhrasePanel.qml

Fix #5613
The page remembers seed phrases when switching to different seed phrase modes.
Onboarding: Add existing user/ Enter seed phrase
https://user-images.githubusercontent.com/61889657/169807592-91b323b5-0b33-46d2-90ed-5eae18ffbb87.mov

fix(@desktop/onboarding): not remove seed phrases when changing number of words

---

src/app/modules/main/profile_section/notifications/model.nim
src/app/modules/main/profile_section/notifications/module.nim

- A crash was happening because of emitting signal from the Q_PROPERTY slot,
fixed now.
- Checks added to `addChat` methods that only 1:1 and group chats participate
in notifications setting exemptions.
Crash reported in discord, [here](https://discord.com/channels/624205794384281629/697843216048717905/978199910237225030)

fix(@desktop/settings): crash enabling/disabling communities

---

src/app/modules/main/activity_center/model.nim
ui/app/AppLayouts/Chat/popups/ActivityCenterPopup.qml
ui/app/AppLayouts/Chat/views/ChatContentView.qml

Fix #5739
Activity center icon displays a badge with a number of unchecked items in the list.
Activity center

fix(@desktop/chat): Fix activity center icon badge displaying

---

ui/app/AppLayouts/Profile/views/NotificationsView.qml

Removes an error seen in the terminal when receiving messages:
```
ERR 2022-05-17 14:27:03.953-04:00 error colorHashOf:                         tid=303181 file=service.nim:26 errDescription="invalid pubkey: 0x02032ea19a8ac74c0495effdea0a999f27cf3b17e22a7d28e76d4d6a4721864fc5"
```

fix: invalid pubkey error

---

src/app/global/local_account_sensitive_settings.nim
src/app/modules/main/communities/controller.nim
src/app/modules/main/communities/io_interface.nim
src/app/modules/main/communities/models/curated_community_item.nim
src/app/modules/main/communities/models/curated_community_model.nim
src/app/modules/main/communities/module.nim
src/app/modules/main/communities/view.nim
src/app/modules/main/module.nim
src/app/modules/main/profile_section/advanced/controller.nim
src/app/modules/main/profile_section/advanced/io_interface.nim
src/app/modules/main/profile_section/advanced/module.nim
src/app/modules/main/profile_section/advanced/view.nim
src/app_service/common/network_constants.nim
src/app_service/service/community/dto/community.nim
src/app_service/service/community/service.nim
src/backend/communities.nim
ui/app/AppLayouts/CommunitiesPortal/CommunitiesPortalLayout.qml
ui/app/AppLayouts/CommunitiesPortal/stores/CommunitiesStore.qml
ui/app/AppLayouts/Profile/stores/AdvancedStore.qml
ui/app/AppLayouts/Profile/views/AdvancedView.qml
ui/app/AppLayouts/stores/RootStore.qml
ui/imports/shared/stores/RootStore.qml

Requires:
- https://github.com/status-im/status-go/pull/2685
Adds a model with curated communities. To access it in QML: `communitiesModule.curatedCommunities`
The following attributes are available:
- `available`: indicates if the community info is available or not. (We should display a loading indicator or something if a commnity is not available)
- `name`
- `description`
- `id`

feat: add backend code to retrieve curated communities

---

src/app/modules/main/chat_section/module.nim
src/app/modules/main/controller.nim
src/app/modules/main/ephemeral_notification_item.nim
src/app/modules/main/ephemeral_notification_model.nim
src/app/modules/main/io_interface.nim
src/app/modules/main/module.nim
src/app/modules/main/view.nim
ui/app/AppLayouts/Browser/BrowserLayout.qml
ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
ui/app/AppLayouts/Profile/views/EnsView.qml
ui/app/mainui/AppMain.qml
ui/imports/shared/popups/SendModal.qml
ui/imports/shared/popups/SignTransactionModal.qml
ui/imports/shared/popups/qmldir
ui/imports/utils/Constants.qml
ui/imports/utils/Global.qml

This PR is a continuation of notifications implementation, added on top of #5334
Corresponding `StatusQ` PR:
- https://github.com/status-im/StatusQ/pull/651
Changes:
- ephemeral notifications implemented as toast messages
- old notifications added aligned with new toast messages
Fixes #5629
https://user-images.githubusercontent.com/86303051/166918444-5505ca97-8377-47a8-afce-56b213477be4.mov

feat(@desktop/profile): add ephemeral notifications

---

ui/app/AppLayouts/Profile/views/MessagingView.qml

Closes #5847
Improved spacing between elements in `MessagingView.qml`
Here figma reference file: https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?node-id=427%3A34461
Settings / Messaging

fix(Settings/Messaging): Spacing is wrong between “System Default Browser” and separator

---

src/app/modules/main/browser_section/dapps/accounts.nim
ui/app/AppLayouts/Profile/views/wallet/PermissionsListView.qml

Corresponding `StatusQ` PR:
- https://github.com/status-im/StatusQ/pull/698
From the UI meeting (section Wallet Settings, issues 13, 14, 15):
https://docs.google.com/document/d/1Nd7YQOYVPR-KMz5qdU1AIGpL7vwBAZs-efifnZ0IkO8/edit#
13. Dapp Permissions: fetch favicon (network request)
14. Dapp Permissions: Dapp title should be site title
15. Dapp Permissions: show wallet emoji/icon rather than the first letter of account
Fixes #5906
Screenshot of changes done in this PR:

fix(@desktop/browser): settings -> Browser, connected dapps items do not follow figma

---

src/app/modules/main/chat_section/controller.nim
src/app/modules/main/chat_section/io_interface.nim
src/app/modules/main/chat_section/module.nim
src/app/modules/main/chat_section/view.nim
src/app_service/service/community/service.nim
ui/app/AppLayouts/Chat/panels/communities/CommunityEditSettingsPanel.qml
ui/app/AppLayouts/Chat/panels/communities/CommunityOverviewSettingsPanel.qml
ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
ui/imports/shared/popups/BannerCropperModal.qml

Use EditCroppedImagePanel to edit the community logo.
Beware that this PR depends on the #5437, and it is rebased on top of it for easy reviewing. However, the base will be changed to `master` before merging. 
Community editing

feat(Community/Logo): use image crop approach for community Logo

---

src/app/modules/main/chat_section/controller.nim
src/app/modules/main/chat_section/io_interface.nim
src/app/modules/main/chat_section/module.nim
src/app/modules/main/chat_section/view.nim
src/app_service/service/chat/service.nim
ui/app/AppLayouts/Chat/panels/GroupChatPanel.qml
ui/app/AppLayouts/Chat/views/ChatContentView.qml
ui/app/AppLayouts/Chat/views/ChatContextMenuView.qml
ui/app/AppLayouts/Chat/views/CreateChatView.qml

Closes #5522 without new specs. New specs will be addressed in: https://github.com/status-im/status-desktop/issues/5941
1. Added new option add / remove contacts in dropdown and created navigation to modify the loaded component in the toolbar.
2. Enabled addition of new members into a group chat by the admin.
3. Enabled removal of members of the group chat by the admin.
4. Admin is not displayed in the group chat panel.
5. Added into `ChatContentView` components related to chat toolbar: 
- `StatusTagSelector` and its corresponding logic
-  Moved `StatusChatInfoButton` from toolbar to content view.
6. Esc (when focused) to leave the group chat panel without changes.
7. Updated `StatusQ` link. Depends on: https://github.com/status-im/StatusQ/pull/700
Group Chats …

feat(GroupChat/Add-Remove-Contacts): Implement "Add / remove from group" button for group chats

---

src/app/boot/app_controller.nim
src/app_service/service/about/service.nim

The work was already done in the actual call, but we kept the guard.
The guard is now remove as it was useless

fix(@about): always check for update

---

ui/app/AppLayouts/Onboarding/views/InsertDetailsView.qml
ui/imports/shared/panels/EditCroppedImagePanel.qml
ui/imports/shared/popups/ImageCropWorkflow.qml
ui/imports/shared/popups/qmldir

A wrong merge conflict solving was the root cause for the issue
Also rename the crop image workflow
Community banner and logo editing

fix(Communities): loading of new images for logo and banner

---

ui/app/AppLayouts/Profile/panels/ContactPanel.qml

Closes #5246
Updates right buttons colors when those are hovered
Contacts Panel

fix(ContactPanel): updated right button colors when hovered

---

ui/imports/utils/Constants.qml

Fixes #5877
Modified color text into the corresponding tag.
Chat Input / Mentions color in dark mode
https://user-images.githubusercontent.com/97019400/171430634-8892141a-3396-4dcf-b744-8d90cb3f1432.mov

fix(ChatInput): Mentions have very bad color/contrast ratio in dark mode

---

ui/app/AppLayouts/Chat/views/CreateChatView.qml

Closes #5875
Depends on: https://github.com/status-im/StatusQ/pull/702
Fixed icon color was not correct in create chat view contacts list
Create chat view contacts list

fix(CreateChatView): icon color was not correct

---

ui/app/AppLayouts/Chat/panels/UserListPanel.qml

Closes: #5897
Add crown to admins
Members in chat view

feat(chat): Add crow to admins in group chat

---

src/app/modules/main/chat_section/view.nim

Without it, removing users from the group doesn't work.

fix(@desktop/group-chat): restore missing removeMembersFromGroupChat

---

ui/app/AppLayouts/Profile/views/EnsListView.qml
ui/imports/shared/views/chat/ChatTextView.qml
ui/imports/shared/views/chat/CompactMessageView.qml
ui/imports/shared/views/chat/MessageView.qml
ui/imports/utils/Utils.qml

Closes: #6005
Removing displaying urls from messages with gif's
Chat

fix(Chat): Messages with GIF not display the url

---

ui/imports/shared/status/StatusChatInput.qml

Closes: #3565
Unfortunately, seems like standard Mac OS emoji popup shortcut not fixed in current Qt version. But I fix opening our emoji popup.
Fix `click` call for emoji shortcut

fix(StatusChatInput): Fix emoji button click arguments

---

src/app/modules/main/wallet_section/accounts/module.nim
src/app/modules/main/wallet_section/module.nim

fixes #6013 
Refresh account list and total currency when tokens are retrieved
Wallet
https://user-images.githubusercontent.com/60327365/172840764-390e9e44-b036-446e-baea-9bf8b4181f45.mov

fix(@desktop/wallet): Wallet balance is 0 when enabling multinetwork toggle

---

scripts/bump-status-go.sh

This is a tool to help creating PRs with specific status-go versions
If the given name matches both a branch and a tag the tag is used.
Usage:
./scripts/bump-status-go.sh {version}
Examples:
./scripts/bump-status-go.sh feature-abc-xyz
./scripts/bump-status-go.sh v2.1.1
./scripts/bump-status-go.sh 1a2b3c4d
./scripts/bump-status-go.sh PR-2134
This script will automatically checkout latest master, create a new branch, upgrade status-go to the specified branch/tag/commit, push the new branch, then proceed to delete the branch. A link will be shown that you have to browse to create the PR that bumps status-go
Use at your own risk :dagger:

chore: create script to bump status-go

---

src/app_service/service/community/service.nim

Closes: #5818
Add possibility to import community without chats
should be merged after [status-go PR](https://github.com/status-im/status-go/pull/2694). Otherwise, after import app stuck on login.
Communities

fix(Communities): Fix import community without chats

---

ui/app/AppLayouts/Chat/panels/AcceptRejectOptionsButtonsPanel.qml
ui/app/AppLayouts/Chat/views/ChatContextMenuView.qml
ui/app/AppLayouts/Profile/panels/ContactPanel.qml
ui/imports/shared/controls/chat/menuItems/MuteChatMenuItem.qml
ui/imports/shared/controls/chat/menuItems/SendMessageMenuItem.qml
ui/imports/shared/controls/chat/menuItems/ViewProfileMenuItem.qml
ui/imports/shared/controls/chat/menuItems/qmldir
ui/imports/shared/views/chat/MessageContextMenuView.qml

[fix(@desktop/chat): extract chat menu items](https://github.com/status-im/status-desktop/pull/6064/commits/d39213a959ced6593a2682d4aae68a6238e4fbd7) 
It removes duplication and unifies menu items across the app.
fixes: #5985

fix(@desktop/chat): unify view user profile menu item

---

src/app/core/signals/remote_signals/messages.nim
src/app_service/service/community/service.nim

This adds the missing handling of community settings that are synced
when communities are created/edited etc.
Needs https://github.com/status-im/status-go/pull/2701 to function.

fix: ensure sync community settings are handled

---

src/app/boot/app_controller.nim
src/app/core/signals/remote_signals/messages.nim
src/app/modules/main/controller.nim
src/app_service/service/settings/service.nim

This fixes a bug where the new user status set by the logged in user
would not be broadcast because the corresponding setting would prevent
status-go from doing so.
The fix is done by always enabling broadcasting the user status, then
disabling it again right after setting, in case it was set to "offline".
This commit also ensures that, when current user status updates are
broadcast, the updates are handled across paired devices in real-time.

fix(sync): handle syncronization of user status

---

src/app/boot/app_controller.nim
src/app/core/signals/remote_signals/messages.nim
src/app/modules/main/browser_section/bookmark/controller.nim
src/app/modules/main/browser_section/bookmark/module.nim
src/app/modules/main/browser_section/module.nim
src/app_service/service/bookmarks/dto/bookmark.nim
src/app_service/service/bookmarks/service.nim
src/backend/backend.nim
src/backend/browser.nim

Bookmarks were only synced when devices were synced, but not when
bookmarks were added/removed/updated.
To account for this, there's are new messenger APIs in status-go
proposed here: https://github.com/status-im/status-go/pull/2709
Based on those APIs, desktop can now add/remove/update bookmarks and the
changes are automatically synced to other devices in real-time.
This commit also ensures that changes from other devices with regards to
bookmarks are handled and updated on the current device.

fix: handle bookmarks syncing signals properly

---

src/app/core/signals/remote_signals/messages.nim
src/app/modules/main/profile_section/privacy/controller.nim
src/app/modules/main/profile_section/privacy/io_interface.nim
src/app/modules/main/profile_section/privacy/module.nim
src/app_service/service/settings/dto/settings.nim
src/app_service/service/settings/service.nim

There are a bunch of settings which are synced an not handled by
desktop, one of them being the `profile-pictures-show-to` setting.
This commit introduces a new `SettingsFieldDto` so we can react to
message signals that include individual setting fields that originate
from syncing.
The first setting hanlded is the one mentioned above, so a new
application signal is introduced to inform the app that there was an
update in that particular setting, so it can re-render the view.

fix(Privacy): handle sync setting of `show-profile-pictures-to`

---

src/app/core/signals/remote_signals/messages.nim
src/app_service/service/chat/dto/chat.nim
src/app_service/service/chat/service.nim
src/backend/chat.nim

When histories are cleared on a paired devices, that clearance should be
synced and reflected in other paired devices as well.
This commit ensures desktop calls the correct API to clear histories,
which will then cause an implicit sync.

feat(chat): handle sync clear history messages

---

ui/app/AppLayouts/Onboarding/views/InsertDetailsView.qml

Fixes #6012
Click button action is now only called if the button is enabled.
Onboarding/Your profile

fix(Onboarding): User is able to bypass validation of username when using keyboard

---

src/app_service/service/community/service.nim
ui/app/AppLayouts/Profile/panels/CommunitiesListPanel.qml
ui/app/AppLayouts/Profile/views/CommunitiesView.qml

Closes: #6074
When `curatedCommunities` request is failed that affected all requests in `init` method cos of `try/catch` block. I moved `try` block to every each request method.
Communities

fix(communities): Fix `try/catch` block in communities service

---

ui/imports/shared/views/chat/CompactMessageView.qml

fixes #5934
Mobile still send the placeholder so we need to handle this case
manually by removing text if this is exactly equal to the placeholder

fix(@chat): handle image placeholder

---

ui/app/AppLayouts/Chat/views/ChatContentView.qml

Fixes #6119
The button is now in highlighted state when it's active.
Activity Center button
https://user-images.githubusercontent.com/97019400/175263418-53d9ed80-1ef4-4184-93bf-61e5194c6ca2.mov

fix(ActivityCenter): Activity center button is not active when activity center is opened

---

src/app/modules/main/module.nim
ui/imports/shared/controls/ContactsListAndSearch.qml

In case of a public key, the loader was always visible and an ephemeral
notification was display but it should not
Also, the show not found is disabled if there is no contact list being
displayed
fixes #6194

fix(@wallet): address input keep loading

---

scripts/fetch-brew-bottle.sh

My local build was failing due to expired `GITHUB_TOKEN` and spent some time figuring out why. I propose this PR to reaise awareness for the next poor soul that gets into the same issue.
Retrospective:
- No awareness that our build system downloads brew custom dependencies on MacOS
- The error was misleading that `bew update` failed due to permissions. After fixing permissions it was failing on bottles that I had already installed and reinstalled.
- `scripts/fetch-brew-bottle.sh` was silently failing with "Failed to fetch file" due to token expired [see fetch-brew-bottle.sh](https://github.com/status-im/status-desktop/blob/95326620c38f0e5a28e07afffeb6003dbabcfe1a/scripts/fetch-brew-bottle.sh#L2) and `curl` failed silently as requested [see …

chore(internal): raise awareness of brew bottle download failed

---

src/app/global/local_account_sensitive_settings.nim
src/app/modules/main/module.nim
ui/app/AppLayouts/Chat/popups/qmldir
ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
ui/app/AppLayouts/CommunitiesPortal/CommunitiesPortalLayout.qml
ui/app/AppLayouts/CommunitiesPortal/popups/CreateCommunityPopup.qml
ui/app/AppLayouts/CommunitiesPortal/stores/CommunitiesStore.qml
ui/app/AppLayouts/Profile/views/AdvancedView.qml
ui/app/AppLayouts/stores/RootStore.qml
ui/imports/shared/stores/RootStore.qml

Closes #6099
- Removed 'Communities Portal' toggle from the advanced settings and enable it by default.
- Removed dropdown menu. The button opens directly the join public chat modal.
- In the portal, "Import community" button is now clickable and opens the import community modal.
- In the portal, "Create community" button is now clickable and opens the create community modal.
- Enabled navigation to the clicked community.
Chat / Join Chat & Communities dropdown
Comunities Portal
https://user-images.githubusercontent.com/97019400/175099639-fe29be04-9681-44c9-8606-fb11b19f1067.mov

feat(CommunitiesPortal): Enable Communities portal & update chat menu

---

Makefile

Otherwise `make pkg` would deploy already built status client,
regardless of its initial configuration.
`make clean` is not required before `make pkg` anymore.
fixes: #6241

fix(Makefile): ensure `pkg` target rebuilds status client

---

ui/app/AppLayouts/Wallet/popups/AddAccountModal.qml

Closes #6245
Adds left and right padding in add account popup
Wallet - add account popup

fix(Wallet): Fixed padding in add account popup

---

ui/app/AppLayouts/Chat/views/ChatContentView.qml
ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
ui/imports/shared/controls/chat/UserImage.qml
ui/imports/utils/Utils.qml

Fixes #5615
This fixes some QML warnings that I thought might have a effect, but also makes the message loading more "async".
The fix I did is a bit hackish, but what is does is only show the first 10 messages in the first 10 milliseconds, and then enable the rest.
The reason why it was so slow was that the scroll goes wild when switching. I haven't been able to find the reason for that sadly.
Anyway, since the scroll goes crazy, it loads messages that shouldn't be loaded, so that's why it's slow.
Now, by loading only 10 at the start and waiting a fraction of a second to "load" the rest, the scroll has time to settle and switching is faster.
I tested on Windows and it made a good difference. The switch is not instantaneous, but on Windows it was always a bit slow. I would think that on …

fix(chat): fix switching back to chats is very slow

---

ui/imports/shared/views/chat/CompactMessageView.qml

Removed the condition that was causing the chat highlight animation to run each time it was visible
Removes the condition -` running = visible`, which was causing the chat background to animate each time its visibility turned to true
Chat
https://user-images.githubusercontent.com/60327365/176479094-8d282cf2-3d84-4ccd-8031-cad4a19d860b.mov

hotfix(@desktop/chat): Removed the condition that was causing the chat highlight animation to run each time it was visible

---

ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
ui/imports/shared/status/StatusChatImageLoader.qml
ui/imports/shared/views/chat/CompactMessageView.qml
ui/imports/shared/views/chat/MessageView.qml

Sets playing to `false` on gifs when the channel is no longer active.
Also doesn't set `allMessagesLoaded` to false when switching channel in the same group, because we want to keep the fast switching for that.

fix(chat): fix gifs staying active in the background when switching chat

---

build/.gitignore

- build directory is already ignored by main .gitignore
- removing build directory shows build/.gitignore in git status
which is annoying

chore: remove .gitignore from build dir

---

ci/Jenkinsfile.macos

For some release builds the notarization step fails because Apple backend takes too long to return results. But the timeout triggered is the Jenkins job timeout and no the notarization timeout.

ci: bump macos job timeout to 25 minutes

---

src/app/modules/main/communities/models/curated_community_item.nim
src/app/modules/main/communities/module.nim
src/app/modules/main/module.nim
src/app/modules/shared_models/active_section.nim
src/app/modules/shared_models/section_item.nim
src/app/modules/shared_models/section_model.nim
src/app_service/service/community/dto/community.nim
ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
ui/app/AppLayouts/CommunitiesPortal/controls/CommunityTagsPicker.qml

Close #6089
Requires https://github.com/status-im/status-go/pull/2739
Add display and edit tags functionality to community edit page
Communities

feat(Communities): support tags in community edit page

---

src/app/modules/main/module.nim
src/nim_status_client.nim

Close #6254
- since Qt 5.xy, hover is not enabled by default for QQC2, so enable it
unconditionally as we are a desktop app anyway
- this fixes several hover effects being broken, mostly for builtin
components like MenuItem and some buttons (eg. the leftmost NavBar)
where we haven't enabled those with `hoverEnabled: true` explicitely
- additionally, provide a tooltip for the default "chat" section which
doesn't seem to supply its own (unlike the other sections)
Fixes mouse over (hover) effects being (mostly) broken
All areas of status-desktop

fix(@desktop): enable the hover effects by default

---

src/app/boot/app_controller.nim
src/app/global/user_profile.nim
src/app/modules/main/chat_section/chat_content/users/module.nim
src/app/modules/main/communities/controller.nim
src/app/modules/main/communities/module.nim
src/app/modules/main/controller.nim
src/app/modules/main/io_interface.nim
src/app/modules/main/module.nim
src/app/modules/main/view.nim
src/app/modules/shared_models/member_item.nim
src/app/modules/shared_models/member_model.nim
src/app/modules/shared_models/user_item.nim
src/app/modules/shared_models/user_model.nim
src/app_service/common/conversion.nim
src/app_service/common/types.nim
src/app_service/service/contacts/dto/status_update.nim
src/app_service/service/contacts/service.nim
src/app_service/service/settings/dto/settings.nim
src/app_service/service/settings/service.nim
ui/app/AppLayouts/Chat/panels/UserListPanel.qml
ui/app/AppLayouts/Chat/panels/communities/CommunityMembersSettingsPanel.qml
ui/app/mainui/AppMain.qml
ui/imports/shared/popups/UserStatusContextMenu.qml
ui/imports/utils/Constants.qml

Issue #5886
Make user statuses enum the same as in status-go.
User can choose 3 statuses (like in mobile): Always Online, Automatic, Inactive.
Handling updating own status on member list (Online/Inactive)
Always online - the status is broadcasted every 5 minutes. After finishing application user is visible as online for 2 weeks.
Automatic - the status is broadcasted every 5 minutes. After finishing application user is visible as Inactive.
Inactive - no broadcast, user is visible as Inactive :)
TODO:
Updating choose status menu to Figma design will be done in next task #6090
Changing statuses:
https://user-images.githubusercontent.com/61889657/173034614-6773dc8a-28eb-4606-b02d-67e06d7b35a2.mov
Update after 5 minutes (Automatic status): …

feat(@desktop/general): Change user statuses

---

ui/app/AppLayouts/Chat/views/ChatMessagesView.qml
ui/imports/shared/views/chat/MessageView.qml

The problem was that the messages were re-rendered completely when switching, mostly because of the `active` on the loader being reset to false.
Then, since it needed re-render, the  height needed to be re-calculated, and since the height defaults to 0 when starting, the list though that it needed to render **everything**, hence it took an awful lot of time to switch back.
This should all be fixed. I tested in Windows and Linux and it felt very fast to me. Please test it out yourselves.

Fix slow chat switching because of height recalculation

---

ui/app/AppLayouts/Profile/stores/LanguageStore.qml
ui/app/AppLayouts/Wallet/stores/CurrenciesStore.qml

Fixes #6306
- update the StatusQ components to the latest commit which includes
the StatusIcon fixes
- switch the LanguageStore and CurrenciesStore to use SVG icons for flags
and money icons instead of PNGs
- add forgotten `qsTr()` around categories
Fixes blurry icons in the language/currency lists
Settings -> Language & Currency; all

fix(settings): flags are blurred in the Languages list

---

ui/app/AppLayouts/Chat/panels/GroupChatPanel.qml
ui/app/AppLayouts/Chat/views/CreateChatView.qml

Fixes #6353
- hide the TagSelector's `listLabel` and disable the `textEdit` when the
contacts model is empty
- add forgotten `qsTr()`
- remove some no-op positioniers/anchors/width/height bindings (these are
handled automatically for QQC2 Control's header and contentItem)
It hides the Contacts label and disables the internal tag selector when the contacts model is empty
CreateChatView

fix(CreateChatView): hide the Contacts label when no contacts

---

ui/app/AppLayouts/Profile/views/profile/MyProfileSettingsView.qml
ui/imports/shared/controls/chat/ProfileHeader.qml
ui/imports/shared/popups/ProfilePopup.qml
ui/imports/shared/views/ProfileView.qml

Closes #6295
- use the recently introduced `profileLargeImage` property for bigger user
images
- fix some QML(lint) warnings
It fixes blurry profile picture images in several places (My Profile, Profile View)
My Profile, Profile View, Chat View (with big profile image)

fix(profile): the profile image is blurred in different places

---

src/app/modules/main/controller.nim
src/app/modules/main/io_interface.nim
src/app/modules/main/module.nim
src/app/modules/shared_models/active_section.nim
src/app/modules/shared_models/section_item.nim

Closes: #6132
Process statuses for members model
Community overview

fix(CommunitySettings): Process statuses for members model

---

ui/app/AppLayouts/Chat/views/CommunityColumnView.qml

Closes: #6162
Add check for admin permissions for context menu
Community column

fix(Community): Add check for admin permissions for context menu

---

src/app/modules/main/communities/view.nim
src/app_service/service/community/service.nim
src/backend/communities.nim
ui/app/AppLayouts/Chat/popups/community/CommunityDetailPopup.qml
ui/app/AppLayouts/Chat/stores/RootStore.qml
ui/imports/shared/views/chat/InvitationBubbleView.qml

We no longer send community invites to users, instead we just share the
community and let users request access.
That request will either be automatically or manually accepted by the owner/admin.
Depends on https://github.com/status-im/status-go/pull/2682
Closes #5115

refactor: always request access to join community

---

src/app_service/service/contacts/service.nim
ui/imports/shared/views/chat/MessageContextMenuView.qml

Close #5289
This handler needed because we set contact data on menu open, but not reset it on close. This caused not to update menu state when we click on the same contact.
Chat

Fix(Chat): Reset MessageContextMenuView state on close

---

ui/app/AppLayouts/Chat/panels/EmptyViewPanel.qml
ui/app/AppLayouts/Chat/popups/community/CreateChannelPopup.qml
ui/app/AppLayouts/Chat/views/ContactsColumnView.qml
ui/app/mainui/AppMain.qml

Fixes #6343 
Fixes #6344
Fixes #6347
- basically switch over to a column + row layout(s), bringing consistent
margins and paddings, scratches a lot of redundant code
- fix the icon colors
- fixed another bug when opening the create chat panel, and then clicking
on an existing channel in the list, doesn't close this create panel
- remove unused signals and connections
Mainly fixes layout issues in ContactsColumnView
ContactsColumnView

fix(ContactsColumnView): fix layout issues to match design
